### ISSUE TITLE
Getting user's name (notify) in echo client

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1005]
Hi, 
When starting the echo client, everything works perfectly!
If I send something from my phone I get the shell response:
Echo Test to 49*****

Is it possible to include in line 23 at yowsup/demos/echoclient/layer.py
where it says:
 print("Echoippppng %s to %s" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False)))

somehow the whatsapp users name (notify)? If I run it in debug mode I get  
...
notify="UsersName"
...
However, I don't want to run it in debug mode, just get that additional information in the echo client...
Any help here is welcome!

Thanks!

**Comment by Dl0tt** [comment]
print("Echoing %s to %s (%s)" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False), messageProtocolEntity.getNotify() ))

this should do it

**Comment by kw005** [comment]
messageProtocolEntity.getNotify() does NOT work :-(

....
 File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line 71, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/layer.py", line 9, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/layer.py", line 26, in onTextMessage
TypeError: not all arguments converted during string formatting

**Comment by Dl0tt** [comment]
This means you have an (or several) extra (or missing) "%s" in your string. What exactly is on line 26 that raised the error? post the code.

-------- Original Message --------

**Comment by kw005** [comment]
That's the line: 

print("Echoing %s to %s (%s)" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False), messageProtocolEntity.getNotify() ))

 messageProtocolEntity.getNotify() did NOT converted.
