### ISSUE TITLE
Listening to disconnected event, but object has no attribute 'login' (re-logging)

### ISSUE THREAD

**Issue by EmilianoCenizo** [tgalal/yowsup#1008]
Hi there!

I am doing a simple " helper" with yowsup2. I used the tutorial echo client as a starting base and been developing from there.

The issue is that, as a lot o ppl over there, after aprox 300 secs my app disconnects if it didnt had any activity.

So, I added an " onEvent" method to listen to the disconnect event, which it works!

`    def onEvent(self, layerEvent):
        print "Evento ("+str(datetime.datetime.now())+"):" + layerEvent.getName()  
        
        if layerEvent.getName() == "org.openwhatsapp.yowsup.event.network.disconnected":
            print "Disconnected: %s" % layerEvent.getArg("reason")
            self.connected = False
            YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT)
            reactor.callLater(2,self.login)       
        elif layerEvent.getName() == "org.openwhatsapp.yowsup.event.network.connected":
            self.connected = True
        return False`

The probem is, my ClassLayer(YowInterfaceLayer) does not have a " login" method!

So... how do I login again?

Thanks in advance

**Comment by Dl0tt** [comment]
```python
self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
```
make sure to import these:
```python
from yowsup.layers					import YowLayerEvent
from yowsup.layers.interface				import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.network				import YowNetworkLayer
```

By the way, being disconnected every 300 sec normally means you're not sending some acks, there's a few I'll link you to some of them when possible

**Comment by rami-dabain** [comment]
try self.L()

**Comment by tgalal** [comment]
@Dl0tt self.broadcastEvent would do

@EmilianoCenizo correct method in YowInterfaceLayer is called ```connect```
```python
self.connect()
```
