### ISSUE TITLE
error: could not create '/usr/local/lib/python2.7/dist-packages/yowsup': Permission denied

### ISSUE THREAD

**Issue by elect86** [tgalal/yowsup#1011]
https://gist.github.com/elect86/d108ca38a3b894625a37

How can I solve it?

**Comment by abhiramnarla** [comment]
Use sudo

**Comment by elect86** [comment]
I tried, now I get

`curve25519module.c:3:20: fatal error: Python.h: No such file or directory`

[log](https://gist.github.com/elect86/f9841c5ef1d7cf36fd3d)

**Comment by tgalal** [comment]
Did you also try reading the installation instructions ?

**Comment by omarfuzzer** [comment]
elect86 you can try with.-   sudo apt-get  update; sudo apt-get install  python-dev -y

**Comment by saurabhjhamb** [comment]
or yum install python-devel on centos
