### ISSUE TITLE
receive ack of read from client

### ISSUE THREAD

**Issue by DiegoVallely** [tgalal/yowsup#1014]
hi guys,

indeed, I want to receive from client the signal that he's reading the message that I sent to him, that is it the blue ticket. because I have implemented it in this demo sendclient, but, when I use the callback('receipt') from him, nothing happens! Is there a best way to create that method that I can read ack from 'delivery' and 'read'? thanks a lot
##

**Comment by sah-anshu** [comment]
+1

**Comment by adinanp** [comment]
+1
