### ISSUE TITLE
Send content UnicodeDecodeError

### ISSUE THREAD

**Issue by hostman89** [tgalal/yowsup#1015]
Hi, I've been watching the issues and I have not seen anyone pass him my problem.
I am using the demo client but modified, the question is that when I want to send from my phone raspberry pi to a string with accents jumps me this error and does not send the message:

UnicodeDecodeError: 'utf8' codec can`t decode byte xxx in position x: unexpected end of data

If anyone knows how please help modify.
Thank you very much and please excuse my English.

**Comment by Dl0tt** [comment]
see #847
