### ISSUE TITLE
How to use the yowsup-cli earlier version commands?

### ISSUE THREAD

**Issue by abhinavchawla** [tgalal/yowsup#1019]
Yowsup-cli 2.0 as you said is still in development mode so there are only a few commands. 
But the commands which are shown like in this one, https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Command-line-client, after using --yowsup, how can we use those as we go in offline once we type --yowsup

**Comment by moyamo** [comment]
Offline mode means you are not logged in. To log in type

    /L

or

    /login <phonenumber> <password>
