### ISSUE TITLE
How I can use the xml of yowsup?

### ISSUE THREAD

**Issue by DiegoVallely** [tgalal/yowsup#1021]
I saw that yowsup has a ProtocolEntity that transform data of the Whatsapp sent to us in xml, but I can't figure out how use them. for example, I want to read the receipt from client like this: <receipt to="xxxxxxxxxxx@s.whatsapp.net" id="1415389947-15" type="read"></receipt>. how I can supose to do that? In this case, is just use receipt.getType() and it return to me "read"? I did it in my onReceipt method and nothing happens. Can you help me, pls?

**Comment by DiegoVallely** [comment]
In demo SendClient I can figure out with ack in onAck method this:
ACK:
ID: 1440800530-2
Class: message
From: xxxxx@s.whatsapp.net
timestamp: 1440800530

but, I need of the tag type="read"! How I can use that in onReceipt method? 
I was trying to get with IncomingReceiptProtocolEntity but nothing =/
Is there a way to handle that automatically?

**Comment by moyamo** [comment]
I'm not sure what you are trying to do. `IncomingReceiptProtocolEntity.getType()` will return None if the message was just delivered and `"read"` if the message was read.

**Comment by DiegoVallely** [comment]
@moyamo so where I should use the IncomingReceiptProtocolEntity for that is to work? Because I have tried this, and not work:
@ProtocolEntityCallback("receipt")
def onRead(self, entity):
    read = IncomingReceiptProtocolEntity(entity.getId(), entity.getFrom(), time.time())
    self.toLower(read)

Can you explain me?

**Comment by moyamo** [comment]
If you want to check if a person has read your message:

    @ProtocolEntityCallback("receipt")
    def onRead(self, entity):
        if entity.getType() == 'read':
            # Message has been read, do code to display double blue tick

If you want to tell a person that you have read their message. You
probably want to do something like this:

    @ProtocolEntityCallback("message")
    def onMessage(self, entity):
        _id = entity.getId()
        _from = entity.getFrom()
        read = 'read' # Use None if you don't want just a double tick
        participant = entity.getParticipant()
        receipt = OutgoingReceiptProtocolEntity(_id, _from, read, participant)
        self.sendEntity(receipt)

This will send a double-blue tick whenever you receive the message.
