### ISSUE TITLE
How do I scale yowsup?

### ISSUE THREAD

**Issue by ignitedpear** [tgalal/yowsup#1025]
Can I receive and send messages at the same time (maybe in different threads)? If yes then I am facing a problem that I am not able to send and receive messages at the same time. Is there a way to solve this through multithreading?

Can I run receive/send processes in multiple terminals to scale the above processes?

**Comment by Dl0tt** [comment]
Yowsup supports read/send by default, the sample app does it.
What exactly are you doing? trying the yowsup-cli or a layer.py/run.py setup?

**Comment by ignitedpear** [comment]
I am using yowsup-cli for sending and receiving. I had to switch between sending and receiving at regular interval of time. I know this is a bad way.
Could you please guide me how to implement sending and receiving of messages at the same time, so that no switching is required?

**Comment by tgalal** [comment]
read docs in wiki

**Comment by ignitedpear** [comment]
The sample app doc just contains echo client. whenever a message is received, it sends the same message back to the sender. 
What I want is to trigger the sending part myself. Can you guide me in this? How do you manually call the sending flow?

**Comment by kamyarg** [comment]
follow [this article](https://github.com/tgalal/yowsup/wiki/Sample-Application)  
You can edit layer.py to call your own function instead of sending the reply.
