### ISSUE TITLE
Can the user be None? (potentially unreachable code in class WriteEncoder/writeJid)

### ISSUE THREAD

**Issue by magicgoose** [tgalal/yowsup#1027]
See these lines:
https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/encoder.py#L138-L141

        if user is not None:
            self.writeString(user, data)
        else:
            self.writeToken(0, data)

I searched for usages of the method and I can't think of any way for `user` to be `None`. Is this code really unreachable or I'm missing something?

**Comment by tgalal** [comment]
might be unreachable yes, but I'll leave it there for now
