### ISSUE TITLE
Large piece of duplicated code in WriteEncoder.writeInternal

### ISSUE THREAD

**Issue by magicgoose** [tgalal/yowsup#1028]
This line: https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/encoder.py#L33
has a big expression and it's exactly the same as the first argument in this line: https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/encoder.py#L35

Also `x` is not used, so it looks like someone extracted a variable and forgot to change the method call to use it.

Also it might be better if reformatted, for example like this:

        x = 1 + \
            (0 if node.attributes is None else len(node.attributes) * 2) + \
            (0 if not node.hasChildren() else 1) + \
            (0 if node.data is None else 1)

— IMHO, it's more readable

**Comment by tgalal** [comment]
Thanks, updated.
