### ISSUE TITLE
How to run unit tests?

### ISSUE THREAD

**Issue by magicgoose** [tgalal/yowsup#1029]
How to run unit tests? The wiki says they  do exist (and they indeed do exist in code), but there are no straight hints about how to run them all at once.

**Comment by aesedepece** [comment]
```bash
pip install nose
nosetests
```

**Comment by magicgoose** [comment]
Done.

BTW, Is it a realistic time to run all tests? :)

    $ nosetests
    ......................................................................................................................
    ----------------------------------------------------------------------
    Ran 118 tests in 0.679s

    OK
