### ISSUE TITLE
Issue with Registration

### ISSUE THREAD

**Issue by biddyweb** [tgalal/yowsup#1032]
I keep getting this when trying to create new account despite receiving the sms
{'status': u'fail', 'kind': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': 3600, 'currency': None, 'reason': u'temporarily_unavailable', 'cost': None, 'expiration': None, 'login': None, 'type': None}
##

**Comment by dd12345772** [comment]
When I tried to register with the latest version now I got a 'failed' 'old version' response - what command did you use to get to the point of receiving an SMS?

**Comment by d3dx9** [comment]
Hi,

got erros with registration too, used 4 different numbers for trying, but don't work.

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

Everywhere the same thing.

d3dx9

**Comment by guicouto** [comment]
I have the same problem. Did you get around this?

**Comment by decklord** [comment]
We move the registration part to use Chat API
