### ISSUE TITLE
Untrusted identity exception

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#1034]
Anyone knows what is this?

  File "/usr/local/lib/python3.4/dist-packages/axolotl/sessioncipher.py", line 91, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python3.4/dist-packages/axolotl/sessionbuilder.py", line 38, in process
    raise UntrustedIdentityException("Untrusted identity!!")
axolotl.untrustedidentityexception.UntrustedIdentityException: Untrusted identity!!

**Comment by jlguardi** [comment]
Same issue described in #829 but @tgalal solution doesn't fix the error due to message is resend by server. Moreover, include ack doesn't work due to next messages from this number are rejected as untrusted too. 

I've fixed removing axolot database but it's too heavy.

**Comment by rami-dabain** [comment]
How did you remove the database? did that help?
what possibly can be a workaround? I can't access the code now but would
ignoring the exception disconnect my client? or that might work?

**Comment by joaoricardo000** [comment]
To remove the database just exclude the ~/.yowsup/<phonenumber>/axolot.db file. This will cause to regenerate it in the next run.

**Comment by tgalal** [comment]
@jlguardi error still happens but doesn't crash, right ?

**Comment by jlguardi** [comment]
@tgalal yes, it is. But I think we need to regenerate all credential/keys for the message sender. I was reading axolot API in order to find some function to perform this but I didn't.
Without ack the app crashes due to missing ack after 5 retries.

**Comment by janboll** [comment]
I deleted the corresponding entry out of axolotl.db (table identities) and the message was received as expected.

@tgalal Is deleting the entry out of the table an appropriate option to get implemented? I am not sure if it implies security infringements, cause the user is authenticated against whatsapp.

**Comment by moyamo** [comment]
Currently yowsup just ignores UntrustedIdentityExceptions. This means if a whatsapp user changes their phone a yowsup user will not be able to send or receive messages to them. I suggest that yowsup atleast broadcasts and event when an UntrestedIdentityException occurs so that the application using yowsup can take appropriate action.

**Comment by yniv** [comment]
@janboll how did you delete the specific entry our of axolotl.db? 
I'm currently having this issue. is there any fix for users who changed their phone? 
If i'll erase the axolotl.db, will it fix this?

**Comment by janboll** [comment]
@yniv i used the following SQL:
delete from identities where recipient_id = 'Phone-Number'
Make sure to increase the logging to debug. Then you can see the problematic inbound message, with the phone-number within the attributes of the message. 

To execute the sql i ran http://sqlitebrowser.org/

**Comment by fjrmaulana** [comment]
sir.. sory.. whether it can not run in this year?
