### ISSUE TITLE
Can't access documentation

### ISSUE THREAD

**Issue by andrewmichaelsmith** [tgalal/yowsup#1037]
https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app

Turns up a blank page

**Comment by Dl0tt** [comment]
https://github.com/tgalal/yowsup/wiki/Sample-Application

is the new link

-------- Original Message --------

**Comment by andrewmichaelsmith** [comment]
Ah, I was getting that link from the README. Have submitted a pull request to update the links.

**Comment by andrewmichaelsmith** [comment]
fixed by #1039
