### ISSUE TITLE
Send messages on demand example

### ISSUE THREAD

**Issue by nabor** [tgalal/yowsup#1041]
Hi
I'm currently trying to send messages on demand, but I want to do it without creating a new process every time as in the examples, so I can keep only one process for sending and receiving.

I tried making parallel layers for listen and send them, but the sending layer is locking the whole process (Tried using a loop, waiting looking for messages on the onSuccess() method in the sending layer ).

In the meantime I have a buffer to store outgoing messages and send them on receiving an iq from the server.

The problem is that this method is too slow for the final user as the iq is received only once a minute.

So is there any way to send a message on demand using the same process I have listening messages? for example, sending a signal to the process

Any help is appreciated

**Comment by rami-dabain** [comment]
You will need multithreading
http://www.tutorialspoint.com/python/python_multithreading.htm

**Comment by gagandeep** [comment]
you will need to read Multiprocessing and Queues in python.
