### ISSUE TITLE
Issue in message sending

### ISSUE THREAD

**Issue by chandan11** [tgalal/yowsup#1043]
After using send command. It is not showing any error. 

[connected]: Sent 1442152172-33
Iq:
ID: 34
Type: result
from: CCXXXXXXX@s.whatsapp.net

But message is not delivered what could be the possible reasons?

**Comment by moyamo** [comment]
Did you send an Iq or a message? Do you have encryption enabled?

**Comment by chandan11** [comment]
@moyamo  I am using --send <contact> <content> for sending message and I am getting following response: 
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown

**Comment by moyamo** [comment]
It could be yowsup having problems with the encryption. Remove the file `~/.yowsup/<your number>/axolotol.db'. And try again. The message will not go through the first time, since yowsup needs to generate keys. But it might go through the second time.

**Comment by chandan11** [comment]
Couldn't find that file :(

**Comment by moyamo** [comment]
What operating system are you using? Also are you using the latest version of yowsup?

On 14 September 2015 18:34:06 SAST, Chandan Singh <notifications@github.com> wrote:
>Couldn't find that file :(
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tgalal/yowsup/issues/1043#issuecomment-140136189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chandan11** [comment]
Ubuntu. I am using the yowsup-cli v2.0.13
Using yowsup v2.4.2.
