### ISSUE TITLE
Using old axolotl keys results in dropped messages when changing phones

### ISSUE THREAD

**Issue by moyamo** [tgalal/yowsup#1044]
If a recipient using the official whatspp client changes their phone, yowsup users are unable to send or receive messages to or from the recipient. Yowsup users can send messages to the recipient only if they delete `axolotl.db`

Steps to reproduce:

  - Send a message from yowsup to the whatsapp user to exchange keys.
  - Remove the SIM card from the whatsapp user's device and place it in a new device.
  - On the new device register the SIM card with the official whatsapp client.
  - Send messages from yowsup to the whatsapp user or Send messages from whatsapp to the yowsup user. Notice how no messages are received.

FIx:
  - Delete `axolotl.db` to re-exchange keys.

**Comment by moyamo** [comment]
Duplicate of #829 and #1034

**Comment by fjrmaulana** [comment]
please sir step by step to compile and runing yowsup..
