### ISSUE TITLE
 status: fail reason: old_version

### ISSUE THREAD

**Issue by SouthernAgeena** [tgalal/yowsup#1058]
I'm getting the following when trying to request an sms code:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

I've updated with pip, didn't fix it, I updated pip (just incase that was some how the problem), I even uninstalled and reinstalled yowsup, unfortunately nothing seems to work.

Any ideas?

**Comment by naghizadeh** [comment]
same issue

**Comment by ak52** [comment]
thank you I want to be able to send media just like demos/sendclient send
messages could you give me some hint please?

**Comment by mgp25** [comment]
#1060

**Comment by tgalal** [comment]
Fixed in master, thanks @mgp25
