### ISSUE TITLE
Sending a group notification on addition of a new member

### ISSUE THREAD

**Issue by v-abhijay** [tgalal/yowsup#1059]
Hi,

When I create a group and add a new member(the number of the newly added member is the number which is used to login to yowsup), I want to send a notification to all the members saying "Hello!". This reply should be automated. How do I do this?

I added a function in the file demos/cli/layer.py

 def createGroupMessage(self, groupID,messageBody):
        groupID = groupID + "@g.us" 
        outgoingMessageProtocolEntity = TextMessageProtocolEntity(
            messageBody,
            to = groupID
        )
        print outgoingMessageProtocolEntity
        self.toLower(outgoingMessageProtocolEntity)

I am trying to call this in the file layers/ protocol_groups/protocolentities/notification_groups_create.py
after doing the necessary imports: 

def __init__(self, _id, _from, timestamp, notify, participant, offline,
                 createType, groupId, creationTimestamp, creatorJid,
                 subject, subjectTime, subjectOwnerJid,
                 participants):
        super(CreateGroupsNotificationProtocolEntity, self).__init__(_id, _from, timestamp, notify, participant, offline)
        self.setGroupProps(createType, groupId, creationTimestamp, creatorJid, subject, subjectTime, subjectOwnerJid, participants)
        self.foo1 = YowsupCliLayer()
        self.foo1.createGroupMessage(groupId,"Hello !\n")

Although the code gives no error, I don't get any message when I add the yowsup number. 

Please let me know where am I going wrong or how can I solve this? 
Thanks!

**Comment by tgalal** [comment]
Notifications are to be received only and not sent. You can send a text message to the group instead.
