### ISSUE TITLE
Problem with the 'send' demo

### ISSUE THREAD

**Issue by JackMedley** [tgalal/yowsup#1066]
Hi,

I'm trying to get the send demo to go.  I've installed the requirements and set up my config as follows:

cc=44
phone=447849581163
password=cwr5yP9E9vuIB2S57g2d7EWfVG0=

but when I run the command

./yowsup-cli demos -c config --send 447849581163 "hi" -d

I get the error

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features>
readreceipts>
/readreceipts>
groups_v2>
/groups_v2>
privacy>
/privacy>
presence>
/presence>
/stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
auth passive="true" user="447841580663" mechanism="WAUTH-2">
/auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

Has anyone else come across this?

**Comment by iwancuy** [comment]
i have same problem with you, anybody help me please

**Comment by tgalal** [comment]
incorrect credentials
