### ISSUE TITLE
exit of console

### ISSUE THREAD

**Issue by rpalmeira** [tgalal/yowsup#1073]
I'm using a shell script to conect, send an image, disconnect and exit using yowsup client. 
The script works fine, but there is no command exit and I need to do cntrl+c to stop... :-(

Follows my script:

#!/bin/bash

yowsup-cli demos --yowsup --login 55xx98900xxxx:sJkF66BEAMIJic2WnrvBlxdQCGQ=  << EOF 
/L
/message send 5521xxxx09590 "hello world"
/image send 5521xxxx09590 /mnt/hgfs/Compartilhado/Logo/logo_test.jpg "Logo test" 
EOF

**Comment by rami-dabain** [comment]
get the PID of the process and kill it using kill -9 [PID] in your script
