### ISSUE TITLE
What exactly does test the method `test_manyEncode`? It's missing any assertions.

### ISSUE THREAD

**Issue by magicgoose** [tgalal/yowsup#1076]
I'm talking about this test:

https://github.com/tgalal/yowsup/blob/master/yowsup/layers/auth/test_keystream.py#L49-L53

    def test_manyEncode(self):
        keys = self.keysTarget
        kstream = KeyStream(keys[2], keys[3])
        for i in range(0, 300):
            encoded = kstream.encodeMessage(self.inputMessage, 0, 4, len(self.inputMessage) - 4)

Is it just a useless computation that does nothing but wasting resources, or it really tests something? If it does, what is it?
If it doesn't, why not delete it?

**Comment by tgalal** [comment]
it's just a test for the encryption algorithm. It'd throw an exception if it fails. And passing a single test call is not enough indication that it's working as supposed.
