### ISSUE TITLE
i send the message but the receiver don't receive the data.

### ISSUE THREAD

**Issue by andrepaes** [tgalal/yowsup#1077]
Hello, i installed a yowsup but when i'll send a message this message appear in the terminal and the message don't arrive on the receiver.

message:

" andre@andre-Inspiron-N5010 ~/yowsup-master $ ./yowsup-cli demos -c config -s 5527996399 "hello"
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown"

**Comment by jlguardi** [comment]
Please, add -d to get the debug info. ‎Perhaps it is a certificate check failed in the other side.

De: andrepaes
Enviado: jueves, 1 de octubre de 2015 03:58
Para: tgalal/yowsup
Responder a: tgalal/yowsup
Asunto: [yowsup] i send the message but the receiver don't receive the data. (#1077)


Hello, i installed a yowsup but when i'll send a message this message appear in the terminal and the message don't arrive on the receiver.

message:

" andre@andre-Inspiron-N5010 ~/yowsup-master $ ./yowsup-cli demos -c config -s 5527996399 "hello"
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown"


---
Reply to this email directly or view it on GitHub:
https://github.com/tgalal/yowsup/issues/1077

**Comment by andrepaes** [comment]
Thanks @jlguardi to reply my issue so fast. I did what u ask me, and this is the reply:

"andre@andre-Inspiron-N5010 ~/yowsup-master $ ./yowsup-cli demos -c config -s 5527996346399 "hello" -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e15.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5527988571807" mechanism="WAUTH-2">
�X��Oz�>�>�CBI��g��0��L�HĪ��ًJ���R��R�
HEX:eb58a5aa4f7ad33eca3ead43421249ebcd671da0b43000a6f24c986a0848c4aaf6b0d98b4afff218c25202fee052bb
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1443664066" expiration="1475200066" props="4" t="1443691097">
�#�j��9�6�����4uW
HEX:d823a5036a9ad51639cc3617f5a5e697ec347557
</success>

DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="2">
<key>
<user jid="5527996346399@s.whatsapp.net">
</user>
</key>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1443691097" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="2">
<list>
<user jid="5527996346399@s.whatsapp.net">
<registration>
^�7�
HEX:5efd378d
</registration>
<type>

HEX:05
</type>
<identity>
��5~�9a}UhCf���g�L�A�)���ⶎ�<
HEX:c3d1357e9239617d55684366ebefc567cb4c1ba241b62993f91eb4e2b68e883c
</identity>
<skey>
<id>

HEX:000000
</id>
<value>
�F�9CY�$>�'ԫÁ��<����y٧��y�
HEX:f7c4cd39435996243eb027d4abc381e4ad3c8dbef79679d9a7afa479870dd646
</value>
<signature>
����
 ��xY[Q�z�Z�AqrsM�>B?��pѠ�&5���z��)��c����

HEX:a894dfdb0cbe99863a36563e0e3a820d20fd1d0fe378595b51ca7a9b5a96417172734d883e423fd0e07001d1a0da2635a9af867aade029caf063fa02e9d4ef0c
</signature>
</skey>
<key>
<id>
���
HEX:e3d3ff
</id>
<value>
;��);7Bc|ˍ@ �e�_���ݕL����D
HEX:023b8bf5293b3742637ccb8d4020d21865f15f1f08ada294dd954cf5faaca844
</value>
</key>
</user>
</list>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<message to="5527996346399@s.whatsapp.net" type="text" id="1443691097-1">
<enc type="pkmsg" v="1">
��!�%[��B��o�Ȃ	z�
                  O`���3:�*�[n�4!Ci_�Y�>�?��\��H{�1 �f@��	?�Y"B3
!�'��+S�
        T�(���y�H���'Z��
"�m�<"zoB 蚒��W�ʮ�V�B(���
0
HEX:3308ffa78f07122105d5255b91ac42e2b26f93c882097aaa0c4f60a0a11b80333ae42a9d5b6e981e341a2105430113695fbd59b33edd3fde01ea5c97ed487be13120ed66401296cd093fae592242330a2105e1279ee82b538c070c54ad28f71deed2798248d7d3fb275ac4f70b40cab4400d100018002210fc6dfb3c227a6f024220e89a92c4dd57fd7fcaae9f56c84228c6ddc9d40a3000
</enc>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1443691098" from="5527996346399@s.whatsapp.net" class="message" id="1443691097-1">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown"

**Comment by andrepaes** [comment]
Look @jlguardi i don't know why,but when i used -d the yowsup worked fine

**Comment by kwngeaw** [comment]
Hi, I already follow all the instruction here but the receiver still don't receive the data. Does anyone know why?

**Comment by jlguardi** [comment]
Have you tried the app in other pc before? Is it possible tha you are have changed your credentials? Try to remove axolot database (home/.yowsup/number/axolot.db) and start again the app.

**Comment by kwngeaw** [comment]
Oh, thanks a lot. It worked like a charm~

**Comment by dgua** [comment]
I have the same problem, and deleting the axolot database does not resolve it. 

The first time I try to send a test message after requesting registration, I get the following:
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys

The second time, I get the same message as OP.

Help, please...

**Comment by itssvet** [comment]
Hello! I need help, too
I use yowsup. Try to send on the one number - the message is recieved. Try the other number - "Message sent", but not recieved.
The debug output are the same both:
_________________________
# yowsup-cli demos -l 7913XXXXXXX:YYYYYYYYYYYYYY --send 7913ZZZZZZZ 123 -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth mechanism="WAUTH-2" user="7913XXXXXXX" passive="true">
B>T$F¡}\å¬{wo!8ñôØ'}EÄÌ_
                                   »ÿ8
HEX3:b'42999b920e3e1254244601a17d95965ce5ac7be97f776f21153803f1f4d8277d14458cc4cc1e5f0b08bb0eff38'
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success props="4" creation="1442395263" status="active" expiration="1473931263" t="1447927933" kind="free">
Q½Õü¨¶-a®q~Rî±ç«
HEX3:b'7f518099bdd5fca896b62d61ae717e52eeb1e7ab'
</success>

DEBUG:yowsup.layers.logger.layer:tx:
<message type="text" id="1447927933-1" to="7913ZZZZZZZ@s.whatsapp.net">
<enc type="pkmsg" v="1">
b'3\x08\xac\xa1\xd7\x06\x12!\x05\x19\xbaEJ\xebE\xf1YV\xc7\xa0\xa7\xfdD\xd1:d=.q\xe2|\x08\x843\x8a\r{K\x12\xc2}\x1a!\x05IW\x8azlU\x01\xc5\x93\xd8\x84J\xe5\xcc\xb6\x9e\xe3g\xc8g\x0c\x03\xc6p\xf8\xfeb\xd7\xa8.r\x16"B3\n!\x05\xbb\x003\xad#=lK\xe9l\xec\x1e!a\xc8\x9c\x04\x7f\xf1\x81$\xc2\x7f\x17\xbe\x86X\x84\xf1\xb9_\x0b\x10$\x18\x00"\x101\xc9\x81\xf6\xfe\x1b\x80\xe4G\x012\x86\xbaSL\x9c\x9246\x91\x00\xb0\x06%(\xe2\xc1\xe6\xa1\n0\x00'
HEX:b'3308aca1d70612210519ba454aeb45f15956c7a0a7fd44d13a643d2e71e27c0884338a0d7b4b12c27d1a210549578a7a6c5501c593d8844ae5ccb69ee367c8670c03c670f8fe62d7a82e72162242330a2105bb0033ad233d6c4be96cec1e2161c89c047ff18124c27f17be865884f1b95f0b10241800221031c981f6fe1b80e447013286ba534c9c9234369100b0062528e2c1e6a10a3000'
</enc>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty type="groups" timestamp="1447927933">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack from="7913ZZZZZZZ@s.whatsapp.net" id="1447927933-1" class="message" t="1447927933">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown
__________________________________________
And this client receive all messages from all other contacts.
The sender is not blocked.
I tried to follow all the instruction before, but there is no result.
I dont know what should I do.. First weeks it all worked fine.

**Comment by DataGreed** [comment]
Why was it closed? Was there any solution found? Facing the same issue
