### ISSUE TITLE
Need Help, how can I get rid these errors

### ISSUE THREAD

**Issue by Coolprohj** [tgalal/yowsup#1081]
DEBUG:yowsup.stacks.yowstack:Initializing stack
Traceback (most recent call last):
  File "/home/pi/yowsup/pitalk.py", line 44, in <module>
    stack=YowsupReceiveStack(credential())
  File "/home/pi/yowsup/wareceive.py", line 64, in **init**
    self.stack = YowStack(layers)
  File "/home/pi/yowsup/yowsup/stacks/yowstack.py", line 131, in **init**
    self._construct()
  File "/home/pi/yowsup/yowsup/stacks/yowstack.py", line 202, in _construct
    inst = s()
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 147, in **init**
    self.sublayers = tuple([sublayer() for sublayer in sublayers])
TypeError: 'NoneType' object is not iterable
##

**Comment by jlguardi** [comment]
Perhaps you missed a correct layer definition. You need something like:
```
        layers = \
                (YowsupRestLayer,) +\
                (YOWSUP_PROTOCOL_LAYERS_FULL,) +\
                (YowAxolotlLayer,) +\
                YOWSUP_CORE_LAYERS
        stack = YowStack(layers)
```

**Comment by Coolprohj** [comment]
@jlguardi  
Pi is able to receive  messages but unable to reply back.
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Media Layer

**Comment by Coolprohj** [comment]
ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 2614 
ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 2614 
these errors too.

**Comment by Coolprohj** [comment]
WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...

**Comment by jlguardi** [comment]
i'm getting this axolotl errors but I didn't fixed yet. By now, you can remove axolot.db database and restart the application

**Comment by hadipramono** [comment]
I also got the same error... 

We've already setup a session for this V3 message, letting bundled message fall through...

**Comment by ronromer** [comment]
+1
