### ISSUE TITLE
Can't register new number from yowsup.

### ISSUE THREAD

**Issue by girish946** [tgalal/yowsup#1084]
I'm trying to register new number using yowsup.
the command I'm using is 

```
yowsup-cli registration --requestcode sms --phone xxxxxxxxxxxx --cc 91 --mcc 404 --mnc 90
```

The output m getting is 

```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
```
##

**Comment by dedmen** [comment]
"reason":"old_version"
env/env_android.py
needs to be updated with new token and version and stuff. I dont have the time right now. Maybe someone else has. Its also possible to find a tutorial on how to do that but i dont remember where.

**Comment by mgp25** [comment]
**Nokia:**
- Version: 2.13.9
- Release time: 1443042907375

**Android:**
- Version: 2.12.297
- Classes MD5: U+w9L64wtuyknyhiDVdM/w==

**Comment by Iskenof** [comment]
I have the samve Problem:

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=49&in=1578xxxx&lc=GB&lg=en&sim_mcc=262&sim_mnc=003&method=sms&token=b1f8bab2041c771a899306fc60e94a08&id=%C3A%A2%00%F6+%B7%2B%D3%B8%DA%98%11%F5C%A9%F2%3EP%CC
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=49&in=1578xxxx&lc=GB&lg=en&sim_mcc=262&sim_mnc=003&method=sms&token=b1f8bab2041c771a899306fc60e94a08&id=%C3A%A2%00%F6+%B7%2B%D3%B8%DA%98%11%F5C%A9%F2%3EP%CC
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version


yowsup-cli version
yowsup-cli v2.0.13
Using yowsup v2.4.2

**Comment by jlmadurga** [comment]
Current version is 2.13.5 and you are using 2.12.96  that I think is the one in pip repository.
I assume you have installed from pip. That version has env files obsolete. Use the git/master ones.
Install master version from git or change pip env files for the last ones in git/master.
