### ISSUE TITLE
Group members who are not friends - where does this name come from?

### ISSUE THREAD

**Issue by ChrisKnott** [tgalal/yowsup#1089]
When you are in a group with someone who is not a contact, their number is trailed by "~ Joe Bloggs" or whatever. The text it shows is whatever you write as your name in your profile.

Where is this data in Yowsup? Is it possible to fetch it for a contact or group member?
##

**Comment by ChrisKnott** [comment]
It seems like this name is used in the "notify" value on message entity - is there any way to get this data WITHOUT receiving a message from the contact? I feel like this must be possible somehow as this data shows in the "Group Info" on WhatsApp even for numbers that have never sent you a message

**Comment by mgp25** [comment]
Only in messages or notifications

Regards
