### ISSUE TITLE
i can't send message from yowsup2

### ISSUE THREAD

**Issue by nasermuh** [tgalal/yowsup#1092]
i install yowsup2 and register my number bet when i try to send message i recive this message:

root@kali:~/Desktop# yowsup-cli demos -c conf -s 9729523022668 "hi" --debug
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="9720549466482" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�dz(�����?��5VV���
HEX:1edd64117a28c8e3c19bfa3fa2ba355656aae182
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
    :'�?}��~yX4v��!z!2�|?K�Qx��9�\���c���)s�j�
HEX:093a27ac143f7df1f07e79583476e8b8217a2132c57c3f4b05b88e6d5178a6ab39df5c84f6d163c7eec52973846ac0
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized
##

**Comment by nasermuh** [comment]
root@kali:~/Desktop# yowsup-cli demos --config conf --yowsup
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

**Comment by jlguardi** [comment]
Try to register again your phone number. Your password is incorrect or your number is banned.

**Comment by nasermuh** [comment]
i try to register again i recive this:
status: ok
kind: free
pw: 3y8xQr7InE97YvwRpKqAl2OGUwo=
price: 3.90 ₪
price_expiration: 1447516723
currency: ILS
cost: 3.90
expiration: 1475347347
login: 972549466482
type: existing

i copy&paste the pw: 3y8xQr7InE97YvwRpKqAl2OGUwo= to config file but i have the same problem yet
help me please

**Comment by nasermuh** [comment]
i try more than a phone number

**Comment by Rustem** [comment]
@nasermuh  provide your conf please

**Comment by lazarobaca** [comment]
Does it have solution? I have the same problem
