### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by aks82info** [tgalal/yowsup#1093]
I was just testing your work done on yowsup project. I am trying to use it on my NAGIO server from where I will forward all critical alerts on my mobile number registered with Whatsapp.

So, while running the setup file inside "yowsup" directory, 

#python setup.py install

I am getting below error. Can you please let me know how can I fix it and why I am getting it? By the way, I am using CentOS 7.
![image](https://cloud.githubusercontent.com/assets/11291830/10428080/8be8f70c-710c-11e5-979f-ca4c0470c0da.png)

Inline image 1

**Comment by akhld** [comment]
Install the python-dev package, for Ubuntu/Debian you may use:
   sudo apt-get install python-dev

**Comment by tgalal** [comment]
As @akhld mentioned, the installation needs python headers to be installed
