### ISSUE TITLE
Black Image Preview in WhatsApp sended by yowsup

### ISSUE THREAD

**Issue by JuergenHB** [tgalal/yowsup#1097]
Hallo,
I've got black image preview from Image in WhatsApp client sended by yowsup since a few days ago. Befor I saw a correct image preview.
If I open the image, I see the correct image. if I send a image from another WhatsApp client, the preview is also correct. 
I send Image by yowsup using FHEM or wamedia.I doesn't matter whether I send it to my smartphone or tablet, to a single client or a group.
To resolve the problem, I updated my Raspberry, yowsup (now version V2.4) and Pillow and several libraries used by Pillow.
But without success.

Any idea?

Thank you

Jürgen

**Comment by gagandeep** [comment]
+1 . I got it too.

**Comment by gagandeep** [comment]
This fix will help. https://github.com/tgalal/yowsup/pull/1098

**Comment by JuergenHB** [comment]
thank you very much, it works fines
