### ISSUE TITLE
My account is blocked after performing 5 shipments.

### ISSUE THREAD

**Issue by fatercio** [tgalal/yowsup#1100]
I have an application that performs simultaneous submissions to different contacts. A week ago I enfretando the problem of sending a message and someone gets locked out. Any suggestions for this?
PS: Daily make sending 2000 messages.

**Comment by janboll** [comment]
Hi, 

try checking:
https://www.whatsapp.com/faq/en/general/28030003
https://www.whatsapp.com/faq/en/general/23154266

Use broadcasts, sync contacts and ask the people you send messages to, to add you as contact as well.
Furthermore alter the message you send, for instance by personalizing it. Do not send to many messages at once.

Greetings

**Comment by fatercio** [comment]
Today I make the submission as follows : Before you send the message I sync the contact, sending a message and wait 10 seconds to send the next message. All messages are have the same content, only add the recipient's name . The broadcasts serves me , @janboll how I create the broadcasts with the library ?
Thanks.

**Comment by ihfazhillah** [comment]
Try check this:
(https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_messages/protocolentities/message_text_broadcast.py)

**Comment by fatercio** [comment]
@ihfazhillah thanks a lot.
