### ISSUE TITLE
Register new account got blocked immediately.

### ISSUE THREAD

**Issue by mkc188** [tgalal/yowsup#1105]
Today, my script got blocked again when syncing new contact. So I try to register another account.
I can't register new account using yowsup-cli or http://www.watools.es/pwd.html.
The first time I register a new phone number, I got the following response after entering sms code:

```
{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}
```

If I try again, I got blocked:

```
{"status":"fail","reason":"blocked"}
```

I am already on a different ip when using yowsup-cli. Am I the only one who got this problem? I don't have many phone numbers left to figure out what happened.
##

**Comment by Rustem** [comment]
Could you please provide the details of the message being sent to these forms ? Whatsapp does not block by IP

**Comment by fatercio** [comment]
@mkc188  I'm having the same problem. @Rustem Although Whatsapp not to block the user IP believe that the blockade be at the web browser agent is possible.

**Comment by Mafioso** [comment]
@fatercio Yes you are right. What is your work around then ? I see the only way is Spam Avoidance actions that was mentioned in other issues.

**Comment by rami-dabain** [comment]
They only workaround is to play it save, and retry only after the given amount of time. the official client will wait 3600 seconds if told so, others are not official clients so they get blocked. no magic here

**Comment by rami-dabain** [comment]
Happened to me today, 2 new SIM cards never used before:

    {"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

then i tried after a day

    {"status":"fail","reason":"blocked"}

**Comment by decklord** [comment]
I think that they are actually blocking IP. We are building an app for customer service, so our whatsapp usage is not for spam, just for answering questions from real customers.

On our tests, if we connect 1 number using yowsup on a "clean" IP, we are ok. If we connect a second number before 24 hours, the second number gets blocked and all the following numbers are blocked. It seems that IP's are going black listed after that.

**Comment by Rustem** [comment]
So, I also have this issue. I had four simcards getting blocked after activating the first. Any actions on this issue ?

**Comment by Wilm0r** [comment]
Yup, same issue here now, they're very strict. Pretty much out of numbers now that I can test my client with. :-( Anyone found out how long these blockages last?

**Comment by rubenscarrilho** [comment]
I'm getting a massage "Authentication Error: not-authorized" from my raspberry pi wich I installed the yowsap couple months ago. 
Possible reason...
I let the raspberry pi turned off for about 2 months and now I turn it on and I getting this message...

anyone can help me?  (sorry for my bad english)

**Comment by rami-dabain** [comment]
@mkc188  like you see it says "retry_after":3600 , means retry after an hour, which their app does automatically, so if you don't abide by it, the system knows you are using a fake client, and will block you (they are a*****es indeed)

**Comment by rami-dabain** [comment]
@Wilm0r , my last numbers got unblocked after 6 months, i believe they store the numbers in memory based storage which gets wiped with server reboot / version upgrade or whatever, or they just unblock it because they assume your number got diactivated and someone else bought it. try registering it with an official whatsapp client
