### ISSUE TITLE
How to receive messages (listen for messages). Cant send, but don't know how to receive.

### ISSUE THREAD

**Issue by msanchezt** [tgalal/yowsup#1107]
Hi,

With this command (with the demo) I can send messages:

python /home/pi/yowsup/yowsup-cli demos -c /home/pi/yowsup/whatsapp_config.txt -s PHONE_NUMBER TEXT_MESSAGE

I've ben trying to receive messages (I need to keep listening until I receive a message), but I can't find how. There is a demo for that? I need to write a custom script? There is any custom script already created for that?

Thanks,

**Comment by Mafioso** [comment]
@msanchezt hi, 
try to look at this demo: https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/layer.py#L22

**Comment by msanchezt** [comment]
Thanks, that was just what I needed.
