### ISSUE TITLE
Open Whatsapp connection and send text and media from python program

### ISSUE THREAD

**Issue by bbtimx** [tgalal/yowsup#1108]
Hey,
I want to open the yowsup whatsapp connection and send text and media, but dont want to reopen the connection each time.

For example:

``` python
wa = YowsupStack(self.auth) # Stack with all Layers
wa.SendText(number, someText)
/* some other code stuff */
wa.SendImage(number, Image)
wa.CloseConnection()
```

But its only working like this:

``` python
YowsupTextStack(self.auth, [(self.number, self.message)]) # my Text Stack
/* some other code stuff */
YowsupImageStack(self.auth, [(self.number, self.image)]) # my Image Stack
```

It always connect to whatsapp, send the text and close connection and redo this every time I send something. 

Is it possible to do it like my example??

THX
##

**Comment by Vimalanathan93** [comment]
Hey Im trying to send messages from python code and not the cli. I have gotten the password.Please do tell me what the next step is to enter the password and send messages in python code? Thank You!
