### ISSUE TITLE
Whatsapp acknowledges even if client offline (Yowsup 2.4)

### ISSUE THREAD

**Issue by MaGiCaLB** [tgalal/yowsup#1109]
When sending a message to a client.
The network is sending an acknowledgement even when the client is offline.

What I am looking for is an acknowledgement when the message is being delivered on the client.
## from the sendclient:

```
#after receiving the message from the target number, target number will send a ack to sender(us)
@ProtocolEntityCallback("ack")
```

---

This ack is also being delivered when the client is not online / connected to whatsapp.

Any other way to verify the message has actually been delivered?
##

**Comment by jlguardi** [comment]
The ack i received when messag is persisted int whatsapp server. So, pending work is not made by your app but by whatsapp servers. 
When message is delivered to recipient, receipt notification is send to you. 
Finally, when recipient reads the message, a second receipt notification of type read is sent to you.
In summary, you are asking for receipts and not for acks.

**Comment by Mafioso** [comment]
In brief, @MaGiCaLB you need to look at "receipt" protocol details.
