### ISSUE TITLE
Is there any way to know if somebody has blocked me

### ISSUE THREAD

**Issue by ashishnetworks** [tgalal/yowsup#1112]
In many real life scenario due to many unpredictable reasons people are blocked by their colligious and friends. There are few tricks available online that works very well to know whether we are blocked or not by any specific contact. But I was wondering if there is any way to know the same thing using Yowsup API

I'm sure it would of lot help to many guys
Code snippet would be appriciated. Thanks
##

**Comment by catch2patch** [comment]
You say  "There are few tricks available online that works very well to know whether we are blocked or not by any specific contact"
What are those tricks?

**Comment by ashishnetworks** [comment]
You can alternatively check by trying to pay for an account of your friend whom you suspect has blocked you. WhatsApp will not allow you to do so if you are indeed blocked, if you aren't blocked the app will present you a list of available options for paying.
