### ISSUE TITLE
Is there any method to send message after success.

### ISSUE THREAD

**Issue by group-hands** [tgalal/yowsup#1117]
Hi Experts!

I trying to send message using the function once WhatsApp client get connected successfully of course ! I can send message @success protocolentity but problem is it stop the send messages after 2-3 mins idle, also defined ping to whatsapps but this way could not works. 

So I thinking to call function to send message on demand.

Followed : https://github.com/tgalal/yowsup/issues/475 link but it's giving me error.

Please suggest me new way :)

Followed:
http://stackoverflow.com/questions/29274668/yowsup-integrating-sending-and-receiving
https://github.com/tgalal/yowsup/issues/475
##

**Comment by t0rr3sp3dr0** [comment]
You can try this:
```python
while True:
    try:
        stack.start()
    except:
        break
```

**Comment by mohanrex** [comment]
For this you need to define a new thread where you could call that function. Your application structure should be like this.
UI thread where you will send message on button click or on demand. create a new thread with the stack class
Stack thread with reference to layer object and pass that layer object to yowsup stack.
Layer will have the function.
Now you could call the send function with the help of the reference in UI thread. 
If you have any help. I'm happy to help you.
whe
