### ISSUE TITLE
Help with async operation / threadsafe

### ISSUE THREAD

**Issue by appa1303** [tgalal/yowsup#1123]
Hi

Thanks for your amazing work on this project !
I am new to python, so my question might be trivial or it might be something that I missed in the wiki & past issues. 
If the processing of incoming messages takes a long time then I can't do the processing and reply to the messages from within the onMessage event (is this correct ?)
Can I ran self.stack.loop() to get messages, but send messages (or other commands) from another thread ?
If not, how do I extent  self.stack.loop() to run my own code periodically

Thanks
##

**Comment by yniv** [comment]
Yes, you should open another thread for sending messages
