### ISSUE TITLE
Can't see online state indications on the phone

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1125]
Hi all,

When I do login to whatsapp like in the CLI I can't see the Online indication if I look at the number in my phone. Also, all presence events does not shown like state_paused or state_typing.
What am I doing wrong?

Thanks!

**Comment by jlguardi** [comment]
Have you call /presence available and /state typing?
Have you checked privacy options? (just with develop branch)

**Comment by yniv** [comment]
Yes, I called presence available and typing/paused but still nothing...
What are privacy options though I'm sure the number I'm checking don't have any privacy blocks or something cause when i checked it on the phone app it worked... Any ideas?
