### ISSUE TITLE
Ack to notifications not received/accepted

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1126]
Hi,

I posted this in the wrong place, so I am re-posting here - help much appreciated!

I am sending ack's for notifications (create group), but apparently it is not working or Whatsapp doesnt like it, it closes my connection after a while and when I reconnect, it sends me the notifications again and again.

here's an extract from my log:

--------------------------------------------------------------------
```
06/11/2015 11:54:41 AM - yowsup.layers.logger.layer - DEBUG - rx:
<notification participant="34678622605@s.whatsapp.net" t="1446809587" from="34678622605-1439305804@g.us" offline="3" type="w:gp2" id="1636557512" notify="Alex M">
<create>
<group s_t="1439305804" creator="34678622605@s.whatsapp.net" creation="1439305804" id="34678622605-1439305804" s_o="34678622605@s.whatsapp.net" subject="Plus pirata">
<participant jid="34651878415@s.whatsapp.net">
</participant>
<participant jid="34638495203@s.whatsapp.net">
</participant>
<participant jid="34626517929@s.whatsapp.net">
</participant>
<participant jid="34678622605@s.whatsapp.net" type="admin">
</participant>
<participant jid="34669783598@s.whatsapp.net">
</participant>
<participant jid="34696497386@s.whatsapp.net">
</participant>
</group>
</create>
</notification>

06/11/2015 11:54:41 AM - yowsup.layers.logger.layer - DEBUG - tx:
<receipt to="34678622605-1439305804@g.us" id="34678622605-1439305804@g.us">
</receipt>

......

06/11/2015 11:59:51 AM - yowsup.layers.logger.layer - DEBUG - rx:
<stream:error>
<ack id="1636557512">
</ack>
</stream:error>

06/11/2015 11:59:52 AM - yowsup.layers.network.layer - DEBUG - Disconnected, reason: Connection Closed
```
--------------------------------------------------------------------

Is it possible the problem is that the ack is notifying an ID that is equal to the group ID, but not the ID of the notification?

Thanks!

**Comment by t0rr3sp3dr0** [comment]
Similar to the problem I had #1090. Fixed in my fork https://github.com/t0rr3sp3dr0/yowsup.

**Comment by jodersus** [comment]
Works great, thanks!!
Is this going to be merged with the main yowsup module?

**Comment by t0rr3sp3dr0** [comment]
I've already sent the pull request, I'm just waiting it to be accepted and merged to the master branch.
