### ISSUE TITLE
More issues with notification ack's

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1131]
Following my #1126 (which is solved and closed) I now have noticed another issue. Let me explain:

I applied the patch that @t0rr3sp3dr0 proposed, and it worked. Here's the log for a notification received when including my app in a group, with a correct response:

```
09/11/2015 10:53:07 AM - yowsup.layers.logger.layer - DEBUG - rx:
<notification participant="34678622605@s.whatsapp.net" notify="Alex M" from="34678622605-1447066345@g.us" type="w:gp2" id="110745706" t="1447066345">
<create type="new">
<group s_t="1447066345" creator="34678622605@s.whatsapp.net" creation="1447066345" id="34678622605-1447066345" s_o="34678622605@s.whatsapp.net" subject="Prueba">
<participant jid="34638495203@s.whatsapp.net">
</participant>
<participant jid="34678622605@s.whatsapp.net" type="admin">
</participant>
</group>
</create>
</notification>

09/11/2015 10:53:07 AM - yowsup.layers.logger.layer - DEBUG - tx:
<receipt to="34678622605-1447066345@g.us" id="110745706">
</receipt>
```

Shortly after validating it, I deleted the test group I included my app's number in. That created two more notifications: a 'promote' and a 'remove' notification. 

For some reason, the 'remove' notification got a receipt generated and returned, but the 'promote' never got a receipt. I got disconnected because Whatsapp did not got the ack and I have been receiving this notification again on every reconnect.

``` 
09/11/2015 10:53:36 AM - yowsup.layers.logger.layer - DEBUG - rx:
<notification type="w:gp2" notify="WhatsApp" from="34678622605-1447066345@g.us" id="1967004540" t="1447066374">
<promote>
<participant jid="34638495203@s.whatsapp.net">
</participant>
</promote>
</notification>

09/11/2015 10:53:36 AM - yowsup.layers.logger.layer - DEBUG - rx:
<notification participant="34678622605@s.whatsapp.net" notify="Alex M" from="34678622605-1447066345@g.us" type="w:gp2" id="985704731" t="1447066374">
<remove subject="Prueba">
<participant jid="34678622605@s.whatsapp.net">
</participant>
</remove>
</notification>

09/11/2015 10:53:36 AM - yowsup.layers.logger.layer - DEBUG - tx:
<receipt to="34678622605-1447066345@g.us" id="985704731">
</receipt>

```

How could this be if they're both ``` entity.getTag() == "notification" ``` ?
Is it possible it's got to do with the 'parameters' in the notification's entity? 

Thanks!

**Comment by t0rr3sp3dr0** [comment]
Try to send the ack manually every time you receive a notification.
```python
@ProtocolEntityCallback("notification")
def onNotification(self, notification):
    self.toLower(notification.ack())
```

**Comment by jodersus** [comment]
Gracias :) 
I already have that (or similar), which is why *some* notifications are being acknowledged, the questions is why not all of them?

I have got:
```
    def receive(self, entity):
      if entity.getTag() == "message":
        self.toLower(entity.ack())
        self.toLower(entity.ack(True))
        self.onMessage(entity)
      elif entity.getTag() == "receipt":
        self.toLower(entity.ack())
      elif entity.getTag() == "notification":
        self.toLower(entity.ack())
```

**Comment by jodersus** [comment]
Hi,
Still struggling with group notifications and acks/receipts.
Any help please?

**Comment by jodersus** [comment]
@tgalal Tarek, please help.
I do send ack's back for 'normal' notifications, but not the number changes or promotion to admin
Why are these not being sent like the normal ones?
Thanks,

**Comment by jodersus** [comment]
Solved.
Honestly, I don't know how....

**Comment by pabloruan0710** [comment]
@jodersus I fixed this error?
