### ISSUE TITLE
not-authorized in legacy branch

### ISSUE THREAD

**Issue by gmistick** [tgalal/yowsup#1132]
bad login attempts, challenge response is not authorized. Works in master branch.
1. I debugged the getAuthBlob from the master and legacy, hex output seems OK. 
2. Env is updated to latest.

@tgalal  What else am i missing? Anywhere to read on the protocol to understand what might be the difference?
##

**Comment by jodersus** [comment]
I am also facing auth issues apparently due to the challenge response.
Much interested in this issue. If there's anything I can do to help, do let me know.
