### ISSUE TITLE
What happens if the Stack doesn't contain any proper handlers?

### ISSUE THREAD

**Issue by gmistick** [tgalal/yowsup#1133]
What is the default behavior of using the Yowsup stack?
If i extend the yowsupInterfaceLayer  like in the documentation. and i use YOWSUP_CORE_LAYERS:
- YowAuthenticationProtocolLayer only.

If i get a message, what happens? does the stack silently ignore it? does it handle it automatically ( get message and send ack ? )

If it ignores it, doesn't it mean we must use all of the protocol layers? i guess otherwise whatsapp will block the user?
##

**Comment by moyamo** [comment]
> If i get a message, what happens? does the stack silently ignore it? does it handle it automatically ( get message and send ack ? )

It just ignores the message. You have to send acks manually.

> If it ignores it, doesn't it mean we must use all of the protocol layers? i guess otherwise whatsapp will block the user?

Possibly. I don't think whatsapp will ban the user for a malfunctioning client (but don't take my word on this). If yowsup doesn't send the necessary acks whatsapp will just disconnect you. I think this was the problem in https://github.com/tgalal/yowsup/issues/648
