### ISSUE TITLE
Is there a way to set the location of the axoltol.db file?

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1134]
Like if I want to put it on a shared network drive or something like that?
##

**Comment by Holi0317** [comment]
It is hard-coded

https://github.com/tgalal/yowsup/blob/master/yowsup/common/constants.py#L22

You can still use `ln` command to link it or use syncthing/btsync/etc. to sync between clients

**Comment by moyamo** [comment]
It's not hardcoded.

    import YowConstants
    YowConstants.PATH_STORAGE = "/path/to/shared/drive/.yowsup"

**Comment by yniv** [comment]
@moyamo thanks! have you tried to make this work? with what you make a shared drive?
i need to share this db with two or more linux servers

**Comment by moyamo** [comment]
I haven't used it on a shared drive but I have used it to change the directory. Just make sure you change the `YowConstants.PATH_STORAGE` before you do anything with yowsup. If this creates too much problems, using a symlink will work as well. What are you using for a shared drive?

**Comment by yniv** [comment]
@moyamo i'm trying to implement a solution where i have multiple servers running yowsup. each number can connect to any of the servers at a given time to recieve/send messages. this means that i need all the servers to look at the same axoltol.db
