### ISSUE TITLE
Sending and receiving messages in one aplication

### ISSUE THREAD

**Issue by rasheed8777** [tgalal/yowsup#1135]
Hi Tarek

Thanks for this wonderful  creation. I am trying to integrate this in to my home automation project. I have few queries. 
1. Is it possible  to do send and receive in one application. Which means the same application  will recieve messages and reply to that. At the same time it will check a file , read some values from the file and send those values to a contact.
2. In an echo client architecture .. is it possible to open a timer to check a file and do the send message. 
3. Can I call the stack.loop with a timeout and pyt it in another loop which will scan a file and send messages. 

I am very new to python so I apologise if I am putting forward some nonsense queries here .

Thanks and regards 
Abdul Rasheed 
##

**Comment by mohanrex** [comment]
I guess the first method will be very easy in implementation as other methods needs to tailor the library.

**For first method Implementation:**
You need to have two threads for sending and receiving.

* First of all you will have a main thread where home automation project runs. In that you build a yow stack. build yow stack with echolayer object and have reference in your main thread.

* In echo layer add send_message function. It could be like this.
```Python
def send_message(self, phone, message):
        self.lock.acquire()
        if '@' in phone:
            entity = TextMessageProtocolEntity(message, to=phone)
        elif '-' in phone:
            entity = TextMessageProtocolEntity(message, to="%s@g.us" % phone)
        else:
            entity = TextMessageProtocolEntity(message, to="%s@s.whatsapp.net" % phone)
        self.ackQueue.append(entity.getId())
        self.toLower(entity)
        print(entity)
        self.lock.release()
```
* Start another thread and in that call stack.loop function. It will start to receive messages and it will process it according to your call backs.

* In your main thread whenever you need to send message, call the function to send message in the echo layer with phone number and message as parameter through the reference you had in your main thread.. 

You could see the implementation in the Yowsup-cli. 
If you need any more help regarding starting new thread you could ask google or <a href ="http://www.tutorialspoint.com/python/python_multithreading.htm">Multithreading</a>

**Comment by rasheed8777** [comment]
Thanks a ton Mohan. i will definitely   try this out and will let you know soon.  Again thanks for your timely assistance , really appreciate it.

**Comment by rasheed8777** [comment]
Hello Mohan,
                       I tried to modify as below. 
   In the run.py ,  i defined a thread enabled class and created an instance from main block as given below.  But here how can i get the object of Echolayer to pass reference to start the second thread for sending.   EchoLayer class itself is passed to the layers tuples  ,  the instance or object is not available. The recvthread is running and is able to receive messages.    Also i noticed that the thread terminates after running more than half an hour i think .   Python is completely new for me ,  so if this is a some non sense query , i apologise.  

class RecvThread(threading.Thread):

    def __init__(self,phone, password):
        threading.Thread.__init__(self)

        CREDENTIALS = (phone, password) # replace with your phone and password


        layers = (
                  EchoLayer,
                  (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer,                 YowIqProtocolLayer,YowReceiptProtocolLayer, YowAckProtocolLayer),YowAxolotlLayer
                  ) + YOWSUP_CORE_LAYERS

        stack = YowStack(layers)
        stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
        stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
        stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
        stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

        stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
    def run(self):
        stack.loop() #this is the program mainloop

if __name__==  "__main__":
        whatsAppRecvThread =  RecvThread("xxxxxxxxxxx", "xxxxxxxxxx")
        whatsAppRecvThread.start()

**Comment by mohanrex** [comment]
Just initialize the echoLayer this line before layers passing.

```Python
    self.echo_layer = EchoLayer()
```
then you could pass the self.echo_layer instead of EchoLayer in layer stack.
You could access this echolayer methods by calling the receivThread.echo_layer.someMethod()

Then i don't know about the half an hour thread termination. It also happens to me for some times. There is also some issues regarding loop termination with error. I overcame with making stack.loop() in an endless loop. so that even if got disconnected it could automatically connect with it. 
The above method may not be pythanoic way. But i just use like this for time being...

**Comment by rasheed8777** [comment]
Thanks a lot Mohan.  It is working fine.  Putting stack.loop in endless loop , i didn't try yet.. but i think that should solve that issue.  Thanks again.  really appreciate your help.. 

Best regards
Rasheed

**Comment by kwngeaw** [comment]
Hi there,

I successfully run the echo client demo on yowsup-cli. When I tried using the run.py & layer.py, I got auth error instead. Does anybody know why?

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.


C:\Python34>run.py
Implicit declaration of parallel layers in a tuple is deprecated, pass a YowPara
llelLayer instead
Traceback (most recent call last):
  File "C:\Python34\run.py", line 31, in <module>
    stack.loop() #this is the program mainloop
  File "C:\Python34\lib\site-packages\yowsup\stacks\yowstack.py", line 195, in l
oop
    asyncore.loop(*args, **kwargs)
  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "C:\Python34\lib\site-packages\yowsup\layers\network\layer.py", line 86,
in handle_read
    self.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\network\layer.py", line 94,
in receive
    self.toUpper(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\stanzaregulator\layer.py", l
ine 28, in receive
    self.processReceived()
  File "C:\Python34\lib\site-packages\yowsup\layers\stanzaregulator\layer.py", l
ine 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\auth\layer_crypt.py", line 6
3, in receive
    self.toUpper(payload)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\coder\layer.py", line 35, in
 receive
    self.toUpper(node)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\logger\layer.py", line 14, i
n receive
    self.toUpper(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 169, in r
eceive
    s.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 105, in r
eceive
    recv(node)
  File "C:\Python34\lib\site-packages\yowsup\layers\auth\layer_authentication.py
", line 77, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

**Comment by dkiran** [comment]
Hi rasheed, can you share your code with both sending and receiving messages with threads
