### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by mapring0019** [tgalal/yowsup#1136]
I always got message ``Auth Error, reason not-authorized`` when i login. https://github.com/WHAnonymous/Chat-API can login with that account.

**Comment by darkstar999** [comment]
Hey i have the same problem and can't find a solution. It's so bad  anyone have a solution?

**Comment by kumarshivam675** [comment]
I am again unable to use yowsup library. My settings are 
in file path /yowsup.common.http/warequest.py
CURRENT_ENV = S40YowsupEnv()

_VERSION = "2.13.39"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "Nokia302"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1456529096701{phone}"
    _AXOLOTL = True

_MD5_CLASSES = "7UDPOXwpiLBvEjT8uNwsuA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.12.550"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True

I am able of connect using yowsup-cli but unable to send or receive messages. It shows message sent but I don't recieve any message. when I execute "python run.py" then I get following error:
Authentication Error: not-authorized

Can somebody help. Thanks
