### ISSUE TITLE
status: fail reason: old_version

### ISSUE THREAD

**Issue by CHagHrz** [tgalal/yowsup#1138]
Hi, 

has whatsapp changed?

fhem@raspberrypi:/opt/yowsup-master$ python yowsup-cli registration -c /opt/yowsup-config/yowsup.config -R 9xxxxx --debug
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.89 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=xx&in=91xxxx&id=...&code=9xxxxx
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=xx&in=91xxxx&id=...10%DDFnc2%1F&code=9xxxxx
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
fhem@raspberrypi:/opt/yowsup-master$ 

An Idea?
##

**Comment by Stetanchi** [comment]
Do have the same issue here

**Comment by CHagHrz** [comment]
Do you have an solution for this problem?

2015-11-17 21:43 GMT+01:00 Stetanchi <notifications@github.com>:

**Comment by jlmadurga** [comment]
Use last version of env devices, not the ones in pip repository. The current version is 2.13.5 and you are using  2.12.89.
Install from git or install pip version and change env files

**Comment by thonnycleuton** [comment]
Hello, fellas,
I've got the same problem. Despite I've researched about this error for 2 days and after I have updated it to the last version, as most of the tips here say, the error keeps going.
Thank you so much in advance.


yowsup-cli registration -r sms -p 55XXXXXXXXXXX81 -C 55 -m 724 -n 31 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=55XXXXXXXXXXX81&lc=GB&lg=en&sim_mcc=724&sim_mnc=031&method=sms&token=201fe92981bbc394456a3d1627323efb&id=%CB%F5%99%21M%03%CB%BD%9A%B9%12%9A%B1%BB%B8%94Z%AA%02o
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=55XXXXXXXXXXX81&lc=GB&lg=en&sim_mcc=724&sim_mnc=031&method=sms&token=201fe92981bbc394456a3d1627323efb&id=%CB%F5%99%21M%03%CB%BD%9A%B9%12%9A%B1%BB%B8%94Z%AA%02o
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
This issue wa opened last tim the error occurred. Coul someone with rights close it?
Now read #1335.
