### ISSUE TITLE
Updated https://v.whatsapp.net/v2/exist hashing algorithm

### ISSUE THREAD

**Issue by shirioko** [tgalal/yowsup#114]
Thought I might share my findings for tonight:
https://github.com/venomous0x/WhatsAPI/issues/283#issuecomment-16417688

It seems that WhatsApp has changed their identity hashing algorithm for exists check, which now seems to include the phonenumber or JID. Requesting a password using -e doesn't seem to work anymore (for me at least).

Can you confirm or deny this?

My other issue also contains a few examples for you to try to reconstruct the hash.

**Comment by jlguardi** [comment]
Deprecated.
