### ISSUE TITLE
temporarily_unavailable

### ISSUE THREAD

**Issue by peppeska** [tgalal/yowsup#1143]
Since yesterday when I send my sms code on registration i recive:

```
peppeska@hostname:/home/peppeska$ yowsup-cli registration -C COUNTRYCODE -R SMS-CODE -p COUNTRYCODE+PHONENUMBER

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

status: fail
retry_after: 3600
reason: temporarily_unavailable
```

What's appen?

**Comment by peppeska** [comment]
if I try again to send code without waiting (retry_after: 3600) receive:

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

status: fail
reason: blocked

**Comment by sinjuice** [comment]
Same happens with PHP API. Any solution?

**Comment by peppeska** [comment]
maybe whatsapp blocked the telephone number :(

**Comment by jaimeguaman** [comment]
we are facing the same problem.
we tried with several numbers and the same status is returned

this issue should be reopened

**Comment by jlguardi** [comment]
+1. 
Yesterday I got error: missing. Today: unavailable

**Comment by decklord** [comment]
+1, not able to connect any numbers now.

**Comment by yoanntel** [comment]
Same issue for me also !!! I blocked 5 real SIMs !  I can't register anything .............
also if i connected with squid and export http_proxy="http://PROXY_IP:PORT/" and same result ;-( 

first :
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

status: fail
retry_after: 3600
reason: temporarily_unavailable

and after :
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

status: fail
reason: blocked

**Comment by moshekarmel1** [comment]
Same issue.

**Comment by decklord** [comment]
Having same issue right now.

**Comment by wachin** [comment]
Same issue
