### ISSUE TITLE
Number Blocked after try register

### ISSUE THREAD

**Issue by yoanntel** [tgalal/yowsup#1148]
Dear,
When I try to register a new number I get the message:
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
And the number is immediately blocked!
Repeat the process with different numbers in different IPs (3 different IPs).
There were 8 attempts, succeeded in just 1 number, others 7 were blocked!
I am using the latest version of the API, and example registerTool.php.
I use the API to several months, and I've done it several times successfully!
But now it is not working anymore.

i got the following message : 
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
 and after with a second try : SIM blocked ;-(

I tried also with squid and export http_proxy="http://PROXY_IP:PORT/" and same result 
##

**Comment by yniv** [comment]
this is indeed disturbing. I registered a new number just 2 days ago and everything worked just fine.

**Comment by yoanntel** [comment]
please find here my debug :

python /var/www/yowsup-master/yowsup-cli registration -C 33 -p 33632583578 -R 374067
INFO:yowsup.common.http.warequest:
{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}
status: fail
retry_after: 3600
reason: temporarily_unavailable
And after a second registration after 3600

python /var/www/yowsup-master/yowsup-cli registration -C 33 -p 33632583578 -R 374067
INFO:yowsup.common.http.warequest:
{"status":"fail","reason":"blocked"}
status: fail
reason: blocked

**Comment by yoanntel** [comment]
it's like my IP is blocked. It's possible to use proxy or change something else ?

**Comment by yniv** [comment]
have you activated many different numbers in a short period of time from same ip?

**Comment by yoanntel** [comment]
yes ;-(

**Comment by yoanntel** [comment]
not many but approx 10

**Comment by yoanntel** [comment]
yes 10 same day :-(

2015-11-24 16:17 GMT+02:00 yniv <notifications@github.com>:

**Comment by jokebattle3** [comment]
Same problem here. SMS requested & received successfull. However registration failed with "reason:temporarily_unavailable" and after that with "status: fail, reason:blocked".

Please help!

**Comment by yoanntel** [comment]
any fix ?

**Comment by jokebattle3** [comment]
I was now able to register successfully from another IP. So - for me - this is an evidence WhatsApp is doing some kind of IP based blocking. At some point. At least during the process of the registration...

**Comment by yoanntel** [comment]
So to fix it i need to change my server ip.... Do you have a tips to do it directly when i launch yowsup-cli ?

**Comment by jokebattle3** [comment]
@yoanntel: no, I have no idea if it is possible to change the behavior of yowsup-cli. Maybe it is possible to route network traffic for the python app to decidacted network adapters with different IPs. 

Maybe the problem is only relevant during the process of registration. After the number has been registered successfully I was even able to connect with yowsup-cli from a server where the registration actually failed. 

So maybe for the process of registration you will need a number of IPs and / or (v)Servers...

**Comment by yoanntel** [comment]
i need to find a solution with a proxy switcher or something like that...

**Comment by jokebattle3** [comment]
Yes, it seems so. In my case I've done registration from another (v)server. I don't know what kind of checks WA is doing to detect signatures or foodprints of the technologie used to register a new number.

**Comment by yoanntel** [comment]
it's against mass marketing, and spammers i think.

**Comment by cyberp1983** [comment]
I use usb modem registration numbers for each new SIM card modem restarts and gets a new ip. But over the past 2 weeks I have almost nothing could register.
I try to register with nature get the answer:

REG RESPONSE(11647962): {'status': u'fail', 'kind': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': 3600, 'currency': None, 'reason': u'temporarily_unavailable', 'cost': None, 'expiration': None, 'login': None, 'type': None}

REG RESPONSE(11647962): {'status': u'fail', 'kind': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': None, 'currency': None, 'reason': u'blocked', 'cost': None, 'expiration': None, 'login': None, 'type': None}

I'm willing to pay to those who can solve this problem!

**Comment by carlosedubarreto** [comment]
The simples way i found to register is using an android rooted phone.
Install whatsapp and register the chip, than use an apk called get pw, i dont know where i found it, but i can send it.

Just teel me.

**Comment by yoanntel** [comment]
so by yowsup it's not possible ;-(

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/wiki/Extracting-password-from-device

**Comment by carlosedubarreto** [comment]
Great mgp25, that the one I use.

Hi yoanntel, not that you cannot register using yowsup, but i gess thar uf you use whatsapp app to register your chip, its much less probable that you'll get your number bloqued. 

The first attempt i did, i lost my number because i did something wrong and whatsapp server bloquex my number.

**Comment by yoanntel** [comment]
I not have rooted phone ;-(
