### ISSUE TITLE
Automatic Update like codeRUS's API for yowsup?

### ISSUE THREAD

**Issue by h1rule** [tgalal/yowsup#1152]
Hey.

latest months - bots get killed when WhatsApp is changing their token / env informations.

tokenData = {
"v": "2.13.5",
"r": "S40-14.26",
"u": "WhatsApp/2.13.5 S40Version/14.26 Device/Nokia302",
"t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1442277896714{phone}",
"d": "Nokia302"
}

@CODeRUS has some cool feature for his API's. they check theirself for new token informations:

https://coderus.openrepos.net/whitesoft/whatsapp_version
https://coderus.openrepos.net/whitesoft/whatsapp_classes
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Can you build something like that into yowsup too, so it never gets killed by whatsapp? :p
##

**Comment by mgp25** [comment]
@capsload its just to check, its not good to update data automatically, versions and data should be pushed manually, that way we guarantee the API will work as expected.

Anyway is just a json, just take as an array, but as i said, i wouldnt recommend to update it automatically.

Regards
