### ISSUE TITLE
The problem of registration of channels Whatsapp

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1155]
I use usb modem registration numbers for each new SIM card modem restarts and gets a new ip. But over the past 2 weeks I have almost nothing could register.
I try to register with nature get the answer:

REG RESPONSE(11647962): {'status': u'fail', 'kind': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': 3600, 'currency': None, 'reason': u'temporarily_unavailable', 'cost': None, 'expiration': None, 'login': None, 'type': None}

REG RESPONSE(11647962): {'status': u'fail', 'kind': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': None, 'currency': None, 'reason': u'blocked', 'cost': None, 'expiration': None, 'login': None, 'type': None}

I'm willing to pay to those who can solve this problem!
[log29.txt](https://github.com/tgalal/yowsup/files/46580/log29.txt)
##

**Comment by tyana6472** [comment]
where can I get the smsreg.py to debug this issue?

**Comment by cyberp1983** [comment]
Напишите свою почту

**Comment by cyberp1983** [comment]
write your email

**Comment by tyana6472** [comment]
satyanarayan6472@gmail.com

**Comment by cyberp1983** [comment]
sent

**Comment by tyana6472** [comment]
Got it

**Comment by tyana6472** [comment]
[temp.txt](https://github.com/tgalal/yowsup/files/46639/temp.txt)

its working in my  machine, attached the log

**Comment by unicast** [comment]
Have the same problem

**Comment by mgp25** [comment]
this could be because: your are spamming, you are in a flagged network, bad flow behaviour

**Comment by unicast** [comment]
I'm just trying to set up environment with this tool...
Just two commands:
./yowsup-cli registration --requestcode sms --phone 79038207228 --cc 7
./yowsup-cli registration --register 926781 --phone 79038207228 --cc 7
And than I'm receiving "temporarily_unavailable" message, and than "blocked"
It's my personal phone ((((

**Comment by cyberp1983** [comment]
How is determined that it is I, I change the ip with each new request

**Comment by cyberp1983** [comment]
How can I solve this problem?

**Comment by mgp25** [comment]
@cyberp1983 your network is flagged or you are using virtual phone numbers or numbers from a provider that WhatsApp has banned. As simply as that

**Comment by cyberp1983** [comment]
What other information received to identify whatsapp?
