### ISSUE TITLE
connection keeps closing

### ISSUE THREAD

**Issue by chrisw85** [tgalal/yowsup#1156]
Hi

Very new to all of this but I'm using a script that would send a message back to me based on keywords. It works great the first time I run the script but then after a few seconds it wont reply to my prompts. I've started the debug in python and I get the following

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Media Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

Any help would be very much appreciated.

Thanks
##

**Comment by shedokan** [comment]
Try adding the YowIqProtocolLayer from yowsup.layers.protocol_iq, you should read the FAQ:
https://github.com/tgalal/yowsup/wiki/FAQ
