### ISSUE TITLE
Registration of multiple numbers

### ISSUE THREAD

**Issue by alexus37** [tgalal/yowsup#1161]
Hey guys,
thanks a lot for that awesome tool!!
But I am struggeling to register multiple phone numbers to whatsapp. I am running:
`
python yowsup-cli registration -C 49 -r sms -p 49XXXXXXXXXXX
`
Afterwards I receive the sms, but when I run 
`
python yowsup-cli registration -C 49 -R YYY-YYY -p 49XXXXXXXXXXX
`
I get 
`status: fail
retry_after: 3600
reason: temporarily_unavailable
`
and If I run it again I get 
`
status: fail
reason: missing
`
I would really appreciate some hints or ideas how to register multiple phone numbers to whatsapp?!

Thanks!
##

**Comment by kantorv** [comment]
* what does it mean 'YYY-YYY'? verification code shouldn't contain the `-` character, i guess
* "status: fail retry_after: 3600" means retry after one hour, if you will try again before, the phone will be banned for 24h, after more attempt within this period will be blocked forever.

anyway, i'm registering multiple numbers without any issue, so check the registration flow.

**Comment by altmas5** [comment]
I have registered several numbers on the same box also
