### ISSUE TITLE
old_version

### ISSUE THREAD

**Issue by terminet85** [tgalal/yowsup#1164]
I suppose we need to update in yowsup the version string, it stops work today.
##

**Comment by yniv** [comment]
Yeah, I'm getting not authorized since a couple of hours...

**Comment by nurdan** [comment]
Yes , Jam 7 Pagi WIB tadi sudah tidak bisa, You are right..

**Comment by yniv** [comment]
Any solution for this?

**Comment by darksampar** [comment]
Edit yowsup/env/env_s40.py

Change from:

<code>class S40YowsupEnv(YowsupEnv):</code>
<code>    _VERSION = "2.12.96"</code>
<code>    _OS_NAME= "S40"</code>
<code>    _OS_VERSION = "14.26"</code>
<code>    _DEVICE_NAME = "Nokia302"</code>
<code>    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1439921717185{phone}"</code>
<code>    _AXOLOTL = True</code>

to

<code>class S40YowsupEnv(YowsupEnv):</code>
<code>      _VERSION = "2.13.5"</code>
<code>    _OS_NAME= "S40"</code>
<code>    _OS_VERSION = "14.26"</code>
<code>    _DEVICE_NAME = "Nokia302"</code>
<code>    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1442277896714{phone}"</code>
<code>    _AXOLOTL = True</code>

**Comment by nurdan** [comment]
Thank You  darksampar ,  it's Work.. (y)

**Comment by nurdan** [comment]
Alhamdulillah let us go to pray first..

**Comment by goldalworming** [comment]
will token string change constantly in certain period?

**Comment by mgp25** [comment]
Use this:

Android:
- 09sjXC+mX2wWtCCpi3+i7Q==
- 2.12.374

S40:
- 1447796090073
- 2.13.21

**Comment by darksampar** [comment]
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by edit-christian** [comment]
Yes, I am getting a "Authentication Failure" since 4 hours.
Can you elaborate on the above solution for this issue? What exactly is the problem?

Thanks
Christian

**Comment by slpond** [comment]
My problem persist.....
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by terminet85** [comment]
ty  darksampar

**Comment by slpond** [comment]
hi i changed the version in 2 files: env_s40.py and env_android.py and got success !

**Comment by capsload** [comment]
Thanks :)

It would be nice if yowsup's env'.py files would AUTOMATICALLY fetch the "newest" informations from https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Is that possible?

**Comment by mgp25** [comment]
Its possible but not recommended. version and token must be static to avoid update issues

**Comment by fgendorf** [comment]
But is possible create a a "trigger" to verify that information version/token was changed?

**Comment by capsload** [comment]
@fgendorf yes it is! you have to "monitor" the website https://coderus.openrepos.net/whitesoft/whatsapp_scratch and if something changes, you'll get information..

**Comment by BrunoVillanova** [comment]
I dont know what combination token number to use. Anyone?

**Comment by mgp25** [comment]
_sigh..._

```
_VERSION = -->  e value
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "Nokia302"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk<TIMESTAMP>{phone}"
_AXOLOTL = True
```

where `<TIMESTAMP>` is `h` value. The rest of values are static (device related)...

**Comment by BrunoVillanova** [comment]
thanks!

**Comment by ctoveloz** [comment]
I tried everything and could not, always the same error "old_version"
All informations from: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

env_s40.py
       _VERSION = "2.13.21"
	_OS_NAME= "S40"
	_OS_VERSION = "14.26"
	_DEVICE_NAME = "Nokia302"
	_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073{phone}"
	_AXOLOTL = True

env_android.py
    _VERSION = "2.12.374"
    _OS_NAME= "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True

**Comment by gmathur** [comment]
Works for me though

**Comment by gmathur** [comment]
Im running into an issue registering a new number -- I can get the SMS code just fine, but then run into a problem

yowsup-cli registration --register XXXXXX --phone 1XXXXXXXXXX --cc 1
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}
status: fail
reason: missing

**Comment by moyamo** [comment]
@gmathur the form of the registration number is XXX-XXX (don't leave the hyphen out)

**Comment by moyamo** [comment]
@tgalal Could you please release a fix on pypi?

**Comment by nikestar98** [comment]
This wont work for me please some help:
```
class S40YowsupEnv(YowsupEnv):
 _VERSION = "2.13.5"
 _OS_NAME= "S40"
 _OS_VERSION = "14.26"
 _DEVICE_NAME = "Nokia302"
 _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1442277896714{phone}"
 _AXOLOTL = True
```
```
class AndroidYowsupEnv(YowsupEnv):
    _SIGNATURE = "//Removed it for Posting - too long//"
    _MD5_CLASSES = "09sjXC+mX2wWtCCpi3+i7Q=="
    _KEY = "/UIGKU1FVQa+ATM2A0za7G2KI9S/CwPYjgAbc67v7ep42eO/WeTLx1lb1cHwxpsEgF4+PmYpLd2YpGUdX/A2JQitsHzDwgcdBpUf7psX1BU="

    _VERSION = "2.12.374"
    _OS_NAME= "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True
```

Everytime I am trying to Login:
```
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized
```

**Comment by mgp25** [comment]
Check if your number is blocked. If it id blocked then you know why its happening that. On the other hand, newer versions wont work properly with the API yet.

Regards

**Comment by nikestar98** [comment]
@mgp25 how can I check if my Number is blocked?

**Comment by eskorbutin** [comment]
Could someone please post an exact copy of their relevant details in your env_s40.py and env_android.py?

There are several options mentioned in the post for different values, so I'd like to try whatever is known to have already worked for someone.

My account is not blocked, it works fine from a phone when activated there.

Thanks a lot!

**Comment by borisski** [comment]
worked fine for me, be careful  whith copy paste, space char. matters. Thanks !!!

**Comment by zykat** [comment]
@gmathur do you manage to register SMS code?
At first, while trying to register my code XXX-XXX, I get status: "temprorary_unavailable" and waiting for 3600 sec, then I always get  "status: fail, reason: missing". 
There was _VERSION = "2.13.5"  in my env_s40.py,  I've changed  to _VERSION = "2.13.21" but still have the same problem.

**Comment by gmathur** [comment]
Yes - I had to try once or twice but it finally registered with the XXX-XXX
(Im pretty sure last time I tried this it accepted it without the '-' but I
could definitely be mistaken here)

>

**Comment by AndreCapo** [comment]
PORCO DIO NON VA UN CAZZO
