### ISSUE TITLE
Login Failed, reason: not-authorized

### ISSUE THREAD

**Issue by vsarinho** [tgalal/yowsup#1169]
After 3-4 months with normal logins, all of my apps presented this message:

Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Error in LibrasZap, reason not-authorized

Numbers were not blocked yet. Someone with the same problem??
##

**Comment by nikestar98** [comment]
I got the same Problem :/ I think it happens because whatsapp updated their servers. When i am trying to register my number again its says ,Out of date'.

**Comment by eskorbutin** [comment]
Same here; the password became invalid the other day for no apparent reason. I followed the usual steps, got a new SMS code, generated a new password just fine but the unauthorized error persists. The phone number is fine; I can use WhatsApp from a phone just fine if I register it from a phone instead.

Something must have changed at WhatsApp's end; for the first time I'm seriously considering moving my stuff to Telegram + Bots (an incredibly well-designed and easy to use integration API).

**Comment by nikestar98** [comment]
@eskorbutin don't Worry :-1: 
Look at this post https://github.com/tgalal/yowsup/issues/1164 maybe this could help you guys :+1:

**Comment by vsarinho** [comment]
Problem solved. Thanks!!

**Comment by eskorbutin** [comment]
Hey vsarinho,

Could you please post an exact copy of the relevant details in your env_s40.py and env_android.py?

There are several options mentioned in the other post for different values, so I'd like to try whatever is known to have worked for you.

Thanks a lot!

**Comment by nikestar98** [comment]
@eskorbutin +1

**Comment by vsarinho** [comment]
Just put the new version and token-string in the yowsup/env/env_s40.py file. Worked fine to me.

_VERSION = "2.13.5"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1442277896714{phone}"

**Comment by janboll** [comment]
thank you @vsarinho !
this worked for me too.
