### ISSUE TITLE
Do updated Whatsapp clients use the new, server-side generated passwords?

### ISSUE THREAD

**Issue by DandyDev** [tgalal/yowsup#117]
Does the password also change when you update an (Android) client that's been on your phone for a long time? In other words, does updating an existing Whatsapp client on your phone, through the update-button in the Play-store, reset the password to a new, server-generated one? I'm asking, because the documentation isn't really clear about that, and I'd assume that updating the Whatsapp client on your phone, technically isn't a new registration.
##

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.
