### ISSUE TITLE
No preview in pics

### ISSUE THREAD

**Issue by gmathur** [tgalal/yowsup#1173]
I have been using a specific phone number for a while now with yowsup, but recently (timing seems to coincide with the latest update), I dont seem to get any previews for the pics I am sending. Clicking on the pic does download it though so the pictures are there, just have no previews.

My testing account seems to be working fine with the same code (it uses media uploader like in the CLI demo). Does anyone have any idea how to go about debugging this?
##

**Comment by joaoricardo000** [comment]
Same problem... Also started after the latest update.

**Comment by ekkucukarpaci** [comment]
Happens to me too, first time I've tried sending images. Just a white square in the chat window, opens up the image when tapped on.

**Comment by gmathur** [comment]
Ditto - and no dice in trying to figure it out as yet.
