### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by thiarly** [tgalal/yowsup#1175]
Good day.
I'm having problems sending message whatsapp, do the installation and can usually register the phone number.
When I run the script to send a test message is generated is message:

root @ srv-mon: / opt / yowsup-master # yowsup-cli demos -c yowsup-cli.config -s 55xxxxxxxxxxxx "test message"

WARNING: yowsup.stacks.yowstack: Implicit declaration of parallel layers in a tuple is deprecated, pass the YowParallelLayer instead

Authentication Error: not-authorized

Could anyone help me solve this problem?
##

**Comment by drecchia** [comment]
Same problem here!
Edit env/env_s40.py and change:
_VERSION = "2.12.96"
to
_VERSION = "2.13.96"

Solved here!

**Comment by bdbais** [comment]
Is it possible to code a check and update of that datas?

**Comment by blackjack4494** [comment]
still having that problem. i tried registration and it told me everything is fine. i copied new password to config. but still having that error

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Authentication Error: not-authorized
