### ISSUE TITLE
How solve Ping - Pong to whatsapp servers

### ISSUE THREAD

**Issue by carlosfelipe29** [tgalal/yowsup#1179]
Hi,
I got this error after a few minutes, when I run the code with yowsup  run.py

File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_authentication.py", line 89, in handleStreamError
yowsup.layers.auth.autherror.AuthError: Unhandled stream:error node:
stream:error
<ping id="1449597555">
</ping>
/stream:error

That is because whatsapp does not give me a ping.    how I keep alive my program?.

I am trying to use the  protocolentity_iq, and the layer inside of it.   but with not suceed.

any suggestions.   thanks
##

**Comment by MrDinky** [comment]
Same ploplem, does somebody solved this in two years?
