### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by neeraj360** [tgalal/yowsup#1184]
Getting below error

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

Cuurently installed version of yowsup2
yowsup2 (2.4.2)
##

**Comment by marcelomess** [comment]
I am having problem in the registry as well, but with an error a little different.


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}

status: fail
reason: missing

yowsup-cli version
yowsup-cli v2.0.13
Using yowsup v2.4

**Comment by neeraj360** [comment]
@tgalal Please help us bro ..

**Comment by aztrock** [comment]
same problem

**Comment by brianlwh** [comment]
I have same problem, too.  I am using CentOS

**Comment by marcelomess** [comment]
root@producao1 [~]# yowsup-cli registration -R 346-136 -c /root/scripts/whatspp.config --debug
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.5 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=71986470525&id=Y%9Ff%ED%C6%02%BAdQy%7FN%89%E1%D5%5C%EC%CD%FB%FB&code=346136
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=55&in=71986470525&id=Y%9Ff%ED%C6%02%BAdQy%7FN%89%E1%D5%5C%EC%CD%FB%FB&code=346136
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}

status: fail
reason: missing

**Comment by jlguardi** [comment]
@marcelomess Is the cc missing in the phone number? I always use cc and cc+phone.

**Comment by marcelomess** [comment]
@jlguardi my configuration file is that way.

cc=55
phone=5571986470525
password=

**Comment by heimax** [comment]
You may refer to pull request #1177

**Comment by sbogeman** [comment]
# Missing
have you try to unsintall and install again?
I am facing the same issue last week (#1183)
But then i uninstall yowsup...install again..(remove all residue files) and then change the agent instead of using Nokia, i use Android ( but it should not be the issue i guess).
Then ask new sms request code, and then register...then it's success.

**Comment by jodersus** [comment]
Have you tried manually updating the env? by manually I mean download the file and replace the one in your local system 'the old fashioned way' (not git not pip/easy-install, etc...)
