### ISSUE TITLE
Chat Integration 

### ISSUE THREAD

**Issue by fnbns** [tgalal/yowsup#1186]
Hello guys,
I am trying to run a small demo with the send stack, but I don't understand how I can run the stack in a personal app. I want to have a small 'run' script that instantiate a new stack with the send and calls a send method with some parameters. Unfortunately, I cannot find a way to call such a method. Can you please guide me ?

Thank you!
##

**Comment by Pauldic** [comment]
Having similar issues too. I wish someone can help
