### ISSUE TITLE
How to make a registered channel Whatsapp protected.

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1188]
Programs like WART when registering channels WhatsApp make them protected by setting a password, how can this be done through yowsup?
##

**Comment by cyberp1983** [comment]
up

**Comment by mgp25** [comment]
By default random bytes are generated to create the identity, so its protected always, in case of Chat API the identity is stored in a `.dat` file. I don't know in yowsup store it.

Regards
