### ISSUE TITLE
Problem with Basic Example

### ISSUE THREAD

**Issue by yezgar** [tgalal/yowsup#1189]
A few days ago someone change the basic example of yowsup (https://github.com/tgalal/yowsup/wiki/Sample-Application).

now it not works:

YowParallelLayer(YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
TypeError: __init__() takes at most 2 arguments (5 given)

Please fix it

**Comment by trivix** [comment]
Try YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer]), this worked for me.

**Comment by tgalal** [comment]
updated
