### ISSUE TITLE
Registration fails.

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1192]
I got latest version of yowsup, and can't send a registration code request.

 Desktop]$ yowsup-cli registration --requestcode sms --phone 55229xxxxxxx --cc 55 --mcc 724 --mnc 06 -d

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=2299xxxxxxx&lc=GB&lg=en&sim_mcc=724&sim_mnc=006&method=sms&token=a42097d12c34bd995e559ef2791c4cdf&id=6%06%85%29PP%BD%B3L%DDC%1B%ADEC%89%7B%AF%5E%C6
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=229xxxxxxxx&lc=GB&lg=en&sim_mcc=724&sim_mnc=006&method=sms&token=a42097d12c34bd995e559ef2791c4cdf&id=6%06%85%29PP%BD%B3L%DDC%1B%ADEC%89%7B%AF%5E%C6
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"bad_token"}\n'
status: b'fail'
reason: b'bad_token'

Any insight or token alternatives? I tried a few tweaks on yowsup/env/env_android.py as suggested by some users on other issues. My phone operator got some different MNCs, does it matter? Thanks.

**Comment by mgp25** [comment]
Check last pull request.

Regards

**Comment by Gab0** [comment]
Fixed! Thanks.
