### ISSUE TITLE
Can numbers somehow be whatsapp-blocked for yowsup and yet work from phones?

### ISSUE THREAD

**Issue by eskorbutin** [tgalal/yowsup#1194]
Sounds like a stupid question, but here is my experience:
- Installed (everything imaginable), reinstalled, rebooted, checked, double-checked, etc.; multiple times.
- Requested SMS for my secondary number - All OK.
- Registered number with SMS provided - All OK.
- Tried to send messages with the pwd provided - Failed, not authorized
- Registered same number with smartphone - All OK.
- Sent and received messages using smartphone - All OK.
- Retried steps above multiple times with different tweaks (Linux, Windows, fresh installs, different python versions, etc.) - Always the same results.

Based on the above, I thought something was wrong with yowsup, specially because whatsapp works just fine using that same phone number on a smartphone.

However, I repeated the steps above using my primary number and yowsup worked just fine!!!

Any ideas as to what could be going on here? Two numbers for which whatsapp on the phone works just fine; they both registered fine with yowsup but one actually works whereas the other one _always_ gets a not-authorized error?

Any ideas?

Thanks a lot!
##

**Comment by nurdan** [comment]
Just paste your yowsup-cli command here please..

**Comment by jodersus** [comment]
they may have blocked the IP from where you use your yowsup application to connect to WA servers...

**Comment by jlmadurga** [comment]
Any blocking experience registering/running multiple numbers from same IP?

**Comment by yniv** [comment]
@jlmadurga good question. so far i've succeeded in running 6 whatsapp numbers from same IP. never got blocked but i wished i knew the limit.

**Comment by bdbais** [comment]
an enterprise company has 1 ip for thousand of workers so I hope they didn't have a limit for IP, probably they will check for repeat action with same text.
