### ISSUE TITLE
Question: Does yowsup work with "virtual numbers"?

### ISSUE THREAD

**Issue by eskorbutin** [tgalal/yowsup#1197]
Is it possible to register "virtual" numbers (e.g. GoogleVoice) with yowsup and have it work as if it were a "real" number?

I tried but things failed (not sure if something else was at play though); has anyone done this recently? If it's supposed to work, does anyone have a pointer to reliable, up-to-date steps?

I ran a couple of searches but didn't find anything that looked up-to-date.

Thanks a lot!
##

**Comment by yniv** [comment]
The only problem is the registration because you need whatsapp to send an sms to a real phone with whatsapp installed to extract the code. other than that it should work.

**Comment by lalves** [comment]
They are blocking virtual numbers... I think they lookup the number first...
