### ISSUE TITLE
Updating yowsup to the last version

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1198]
NOOBIE QUESTION AHEAD :)

I see there is a new yowsup version (2.4.48)
What is the best safe way to update the yowsup lib to last version on a linux(ubuntu)?
does `pip install yowsup2 --upgrade` safe?

thanks!
##

**Comment by janboll** [comment]
What do you mean with safe way? Yes pip will upgrade the local files and replace them with the newest version. 

But there is no guaranty that you program will work after that. You will have to test it afterwards.

Anyhow i strongly recommend that you take a look into http://docs.python-guide.org/en/latest/dev/virtualenvs/ With this you can setup test-environments to test new/different versions of libs
