### ISSUE TITLE
Presence Name is not send to WhatsApp Server

### ISSUE THREAD

**Issue by jokebattle3** [tgalal/yowsup#1203]
I try to set the push name in yowsup with no luck. I've done some debugging and found (with debug mode on) out that yowsup is not sending 
```
"<presence name="my name">
</presence>" 
```
to the whatsapp server. However when using the cli-demos it is working right and as expected.

I'm trying to set the name inside the onSuccess function on the sendclient in layer.py with:
```
entity = PresenceProtocolEntity(name = "my name")
self.toLower(entity)
```

However the presence name is not set / presence not send to server. I have no clue why yowsup is not firing the function to send the presence tag to the server. Does anyone has an idea?

**Comment by tgalal** [comment]
YowPresenceProtocolLayer is in your stack ?

**Comment by jokebattle3** [comment]
@tgalal This does the trick! Thank you very much!

Adding 
```
from yowsup.layers.protocol_presence           import YowPresenceProtocolLayer
```

and to the stack
```
YowPresenceProtocolLayer
```

solved the problem! The Event is now send to the whatsapp server and the push name is displayed correctly on my phone (iphone) when receiving the message.
