### ISSUE TITLE
Service to get valid phone numbers

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1204]
Does anyone know of a service to get (real) phone numbers that can be registered to use with WA?
Apparently virtual numbers are no longer registrable with WA?

Free would be ideal, but for charge is OK (within reason!)
Preferrably through an API, so new numbers can be obtained programmatically, though 'manual' would also be workable.

I am working on an application to connect a wide network of servers using these numbers to talk to each other.
##

**Comment by moyamo** [comment]
@jodersus To register a number with whatsapp you need to be able receive a SMS or phone call to that number. I can't imagine how you can do this without buying a SIM card.

**Comment by janboll** [comment]
@jodersus You could try to use voice registration with a classic landline telephone.

**Comment by jodersus** [comment]
@janboll thanks, tried that, but apparently WA checks for number being an actual mobile. At least in Spain.

**Comment by jodersus** [comment]
@moyamo I was hoping there was a service that could provide valid mobile numbers that I could manage online i.e. receive/send sms... without needing an actual device (and ideally via API) 

If anyone knows of such a service/company please do let me know

Cheers,

**Comment by AShabana** [comment]
yes this is valid i.e. via short code , I am working in a company that rent short code and forward traffic comming to this short code to its customer , you can make use of those in whatsapp register

**Comment by jodersus** [comment]
Great! thanks @AShabana. Could you send me a link to the company's website or somewhere to get a bit more info, and a method for contacting please?
