### ISSUE TITLE
temporarily_unavailable Error and no SMS on requestcode

### ISSUE THREAD

**Issue by idorompr** [tgalal/yowsup#1207]
Hi,

I have some numbers on Twilio and I have difficulties in registering my numbers to Twilio.
All numbers are UK numbers.

Scenarios:
1. I bought 4 new numbers at Twilio that haven't been registered yet.
2. At the start of the day for the first number I am trying to register - when I do:
    yowsup-cli registration --requestcode sms --phone 44XXXX --cc 44  
    The output message is with 'sent' status but no SMS is reached the Twilio log.
3. Some other numbers do get SMS to Twilio log, but when I am trying to register: 
    yowsup-cli registration --register XXX-XXX --phone 44XXXX --cc 44
    I get the message: with status 'Not-Available'
4. All numbers with status Not-Available on register become blocked the day after.

yowsup-cli registration --requestcode sms --phone 44XXXXXXXXXX --cc 44
INFO:yowsup.common.http.warequest:b'{"status":"sent","length":6,"method":"sms","retry_after":10805}\n'
retry_after: 10805
method: b'sms'
length: 6
status: b'sent'

yowsup-cli registration --register XXX-XXX --phone 44XXXXXXXXXX --cc 44
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}\n'
reason: b'temporarily_unavailable'
retry_after: 3600
status: b'fail'

I would appreciate your answer about this behavior.
Thanks
##

**Comment by EdisonHundLucas** [comment]
Hi,
I got the same error, when i try register a number.

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

status: fail
retry_after: 3600
reason: temporarily_unavailable

**Comment by lalves** [comment]
they are blocking all virtual company numbers... Make sure that the number you are buying is registered by a telecom company that is not a virtual phone company. (yes, there is a database that they can lookup).

**Comment by EdisonHundLucas** [comment]
I tried with real numbers, and in second time I got:

yowsup-cli registration --register 3XX-3XX --phone 5551XXXXXXXX --cc 55 --mcc 724 --mnc 05
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}

status: fail
reason: missing

**Comment by idorompr** [comment]
Thanks.
Tarek - I would appreciate it if you could comment us with an answer what do you think is the reason for this behavior.

Thanks, Ido
