### ISSUE TITLE
YOWSUP - receiving and sending back a message

### ISSUE THREAD

**Issue by bossonaro** [tgalal/yowsup#1209]
Hi, I get this sample in internet, but it´s not run.
How can I fix it?

The code (run.py and layer.py):

##### run.py

from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup import env
from layer import EchoLayer
from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator

CREDENTIALS = ("554188737321", "9reGsDsDeSsQW9q7wRv4+4xd+WuX=")     #here number and password

if __name__==  "__main__":
    layers = (
            EchoLayer,
            (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
            YowCoderLayer,
            YowCryptLayer,
            YowStanzaRegulator,
            YowNetworkLayer
        )
    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
    stack.loop()

##### layer.py

import os, subprocess, time
from yowsup.layers                                     import YowLayer
from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_messages.protocolentities  import TextMessageProtocolEntity
from yowsup.layers.protocol_receipts.protocolentities  import OutgoingReceiptProtocolEntity
from yowsup.layers.protocol_acks.protocolentities      import OutgoingAckProtocolEntity

allowedPersons=['551188442211','551191121009']
ap = set(allowedPersons)

class EchoLayer(YowInterfaceLayer):
    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
                if messageProtocolEntity.getType() == 'text':
                        self.onTextMessage(messageProtocolEntity)
    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
        self.toLower(ack)
    def onTextMessage(self, messageProtocolEntity):
                receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
                if messageProtocolEntity.getFrom(False) in ap:
                        if 'hi' in messageProtocolEntity.getBody():
                                antwort = 'HI!'
                                self.toLower(receipt)
                                self.toLower(TextMessageProtocolEntity(antwort, to = messageProtocolEntity.getFrom()))
                        elif 'test' in messageProtocolEntity.getBody():
                                 t=float(subprocess.check_output(["cat /root/yowsup/auto/teste/test.txt"], shell=True)[:-1])
                                 ts=str(t)
                                 antwort = 'This test is '+ts+'.'
                                 self.toLower(receipt)
                                 self.toLower(TextMessageProtocolEntity(antwort, to = messageProtocolEntity.getFrom()))
                        else:
                                antwort = 'I dont understood.'
                                self.toLower(receipt)
                                self.toLower(TextMessageProtocolEntity(antwort, to = messageProtocolEntity.getFrom()))
                else:
                        antwort = 'You arent a valid sender.'
                        self.toLower(receipt)
                        self.toLower(TextMessageProtocolEntity(antwort, to = messageProtocolEntity.getFrom()))

##### command line

python /yowsup-develop/yowsup/teste/run.py

##### problem

No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    stack.loop()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read

  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    antwort = 'Hello!'
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    #    GPIO.setmode(GPIO.BCM)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
    #elif 'Temperature' in messageProtocolEntity.getBody():
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    self.toLower(ack)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'

**Comment by EdisonHundLucas** [comment]
If u send a message, like:

yowsup-cli demos --send 55xxxxxxxxxx "Test message yowsup" -c yowsup-cli.config

and in yowsup-cli.config:
cc=55
phone=554188737321
id=
password=9reGsDsDeSsQW9q7wRv4+4xd+WuX=
Is it works?

**Comment by bossonaro** [comment]
Yes, it works!
And  this below also works:

yowsup-cli demos -c ./config.txt -s 554188737321 "This is a test!"

I need a sample to listening (loop) and when it receive a message, then it verify allowed persons and if ok, it send back a message. 

Can you help me, please?

**Comment by bossonaro** [comment]
This bellow works fine too.
yowsup-cli demos -c config.txt -y

**Comment by bossonaro** [comment]
SOLVED!!!
Bmutinda commented on Mar 18 as bellow:
It mostly happens when the message is encrypted.
Import the YowAxolotlLayer like this

from yowsup.layers.axolotl import YowAxolotlLayer

Then Add YowAxolotlLayer in your layers stack like this before you broadcast a connect event.

layers = (
        EchoLayer,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
        YowAxolotlLayer,
    ) + YOWSUP_CORE_LAYERS
