### ISSUE TITLE
Encryption Axolot prevent message reception.

### ISSUE THREAD

**Issue by axel-angel** [tgalal/yowsup#1216]
Messages aren't received anymore when `YowAxolotlLayer` is put into the layer stack of the application https://github.com/axel-angel/whatsapp-email-bridge/blob/master/WhatsAppEmailForwarder.py#L186 . The message is send by the applicationd then I wait until I receive it locally (sender = receiver = myself). It's the same stack as in the echo client: https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/stack.py but it doesn't work: messages aren't received anymore or it makes it crashes. Something must be missing?

The stack is the following:

```
        layers = (
            self.layer,
            YowParallelLayer([
                YowPresenceProtocolLayer, YowAuthenticationProtocolLayer,
                YowMessagesProtocolLayer, YowReceiptProtocolLayer,
                YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer
            ]),
            YowAxolotlLayer, # FIXME: This prevents us from sending messages!
        ) + YOWSUP_CORE_LAYERS
```

Encrypted messages cannot be received because either (1) the Axolot layer is enabled and the message is never received, or (2) it isn't enabled and yowsup crashes: https://github.com/axel-angel/whatsapp-email-bridge/issues/13 .

Thanks for the help.
##

**Comment by fsmit3** [comment]
I'm experiencing the exact same thing. In my case this isn't true for all encrypted messages. Most messages will be received, however from some numbers we did receive messages in the past but we don't anymore. 

@axel-angel do you also receive some messages?

**Comment by axel-angel** [comment]
Yes indeed. Maybe worth investigating if there is a device-specific difference in whatsapp encryption: iphone versus android (my guts) and yowsup of course.

**Comment by fsmit3** [comment]
We see it happening on both android devices (Samsung Galaxy S5) and iOS devices (Iphone 4S, 5S en 6S).

**Comment by bjacog** [comment]
I think my problem is related to yours. Forwarding messages to a group, one member only receives it on the group. He also has two devices on the group on two different numbers, a samsung s5 and a samsung s6, only the s5 receives the messages. There are other s5 users on the group who do not receive the message. 

I'm so stumped, only thing I can imagine is his device is allow the unecrypted messges or something along those lines.

**Comment by relima** [comment]
Whatsapp has updated its protocol to 1.6. Yowsup still does not suppor it. From what I have gathered, it is supposedly a work in progress.

https://github.com/tgalal/yowsup/issues/1221

**Comment by axel-angel** [comment]
Thanks for letting us now, what's this wa16 branch btw?

**Comment by fsmit3** [comment]
We think we know what is causing it. In our case this happens when people send a message to a phone number from one operating system (for example, Android) and then change their operating system and try to send a new message to that same phone number. That message is not delivered. The weird thing, however, is that when that person sends an image, a video, or audio we do receive the message.

If it would have to do with the protocol change then we should not receive any messages right?

**Comment by jlguardi** [comment]
@fsmit3 Your issue is related with #1045 which wasn't merged.
To fix that, you can apply the pull request or remove your local axolotl.db and restart again so you will accept the new identity of these people.

**Comment by fsmit3** [comment]
@jlguardi Removing the local axolotl.db didn't work.

**Comment by axel-angel** [comment]
I ask somebody to send me a message from android and I got this one:
https://github.com/tgalal/yowsup/issues/1225

Receiving messages has become really unreliable now. :(

**Comment by jlguardi** [comment]
@axel-angel I've experienced this issue working with android env due to unsupported protocol 1.6. I fix that sending ack of all pending messages (I've edited axolotl/layer for auto ack on error), removing axolotl database and starting as S40 again.

**Comment by fsmit3** [comment]
@relima I am trying to use the WA16 branch but now I receive encrypted media from WhatApp with .enc extension. I didn't yet figure out how to decrypt the media. Do you know how to do this?

**Comment by bjacog** [comment]
I tested with wa16 and the problem was still there. a Group created almost a year ago, still do not receive messages.

**Comment by niastakevin** [comment]
Parsing config: config.yaml

Traceback (most recent call last):
  File "C:\Users\Yuana\Desktop\whatsapp-email-bridge-master\WhatsAppEmailForwarder.py", line 617, in <module>
    config = loadConfig(args.config)
  File "C:\Users\Yuana\Desktop\whatsapp-email-bridge-master\WhatsAppEmailForwarder.py", line 578, in loadConfig
    config = yaml.load(cfg)
  File "C:\Python27\lib\site-packages\yaml\__init__.py", line 71, in load
    return loader.get_single_data()
  File "C:\Python27\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python27\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Python27\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Python27\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Python27\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Python27\lib\site-packages\yaml\scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Python27\lib\site-packages\yaml\scanner.py", line 576, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "config.yaml", line 11, column 40


please help me with this issue
