### ISSUE TITLE
Yowsup logs

### ISSUE THREAD

**Issue by idorompr** [tgalal/yowsup#1224]
Hi,

Are there any logs of Yowsup.
I am working with Yowsup through my code and not from cli.
I looked at /var/log but nothing there.

Thanks 
##

**Comment by widnyana** [comment]
yowsup use python's logging module, just init some configuration for it and the log will be there for you.

**Comment by bdbais** [comment]
import logging

logging.basicConfig(level=logging.DEBUG)
