### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by kapil019** [tgalal/yowsup#1228]
Disconnected: Connection Closed
general: Disconnected: Connection Closed
##

**Comment by a7lan** [comment]
I also have this error.

**Comment by a7lan** [comment]
./yowsup-cli demos -c ./config -s +7XXXXXXXXXX TEST -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="7XXXXXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by rami-dabain** [comment]
Same here
