### ISSUE TITLE
How long will yowsup still exist?

### ISSUE THREAD

**Issue by dbischof90** [tgalal/yowsup#1229]
I know, bad way to start an issue, but seeing that WhatsApp now actively has pushed down many, many projects from GitHub (this one is one of the last ones) with law suits, is this project doomed?
I was wondering if I should start working on an ncurses-client based on this library, but found out that WhatsApp is super against that, will block numbers and sue developers.

Because well... demotivating, I know but then it's more like "use it as long as it exists, but could be taken down the day after you finish your client".

:(
##

**Comment by freistil90** [comment]
It's just such a pity, this would have been the last element for not needing any desktop anymore. And my friends don't use telegram etc, so... damn.

**Comment by mgp25** [comment]
@freistil90 this project and Chat API https://github.com/WHAnonymous/Chat-API/ will remain alive. Both works.

Just one thing, only use it for personal usage.

Regards

**Comment by freistil90** [comment]
But concerning this, what I have found a couple of times already:

https://github.com/github/dmca/blob/master/2014-02-12-WhatsApp.md

where yowsup is listed too. Almost all other projects have been taken down already.
Why not this one?

**Comment by mgp25** [comment]
@freistil90 that was 2 years ago, as i said: https://github.com/tgalal/yowsup/issues/1229#issuecomment-168701344

**Comment by freistil90** [comment]
Okay - but why? Why have the others gone down and not this one?
I mean there are news article from late 2015 that Whatsapp is still going against third party applications and -libraries.

**Comment by tomerb15** [comment]
+1
