### ISSUE TITLE
registration temporarily_unavailable (an observation)

### ISSUE THREAD

**Issue by rwrnet** [tgalal/yowsup#1230]
As I was suffering from the temporarily_unavailable issue, already issued multiple times, I wanted to share my latest finding, for other folks running into the same issue.

Preset: yesterday I was registering the first of my two SIMs. All went pretty well. I got the code, and then the password. But then I tried to register my second SIM. I perfectly got the SMS, but when trying to register it, it failed:

```
# yowsup-cli registration --register XXXXXX --phone 49XXXXXXXXXX --cc 49
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}
```

and subsequently:

```
# yowsup-cli registration --register XXXXXX --phone 49XXXXXXXXXX --cc 49
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}
```

I was then trying it multiple times, carefully respecting the retry timeout. But it got more weird than better. E.g. the subsequent tries responded with fail and success the same time:

```
# yowsup-cli registration --requestcode sms --phone 49XXXXXXXXXX --cc 49
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}

INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":10805}
```

The SMS arrived, but registering still failed with unavailable. I also tried a third number of a friend. Same results.

What finally helped today was, to switch to another installation of yowsup (same version), also behind a different IP address.

Difficult to say, whether it was due to the IP address, or due to the yowsup installation, but my guess is the latter one. It would be very risky for WhatsApp, to prevent registrations from an IP address, which already registered another phone. That scenario could easily happen under regular conditions. But when its really the installation, whats the bug? How is Whatsapp recognizing the second number from same device as such? I will give the third number a try on the second installation, as soon as I get access to it again. If that fails, I'll try switching IP address, just to prove my assumption.
##

**Comment by chenwayne** [comment]
met the same problem, one of my number was banned already
