### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1245]
I'm trying to make simple app with yowsup

Idea is :

Login -->
Add new phone number then send to it message -->
Add new phone number then send to it message -->
Add new phone number then send to it message -->
... etc
--> LogOut

What I'm doing is :

<code>
# coding: utf-8

import sys; reload(sys).setdefaultencoding("utf-8")

import os
from time import sleep
import random

msg =
"""'

Hi there :)

'"""

while True:
    phone_number = ("9639" + str(random.randrange(00000000, 99999999)))
    try:
        do = os.system("/usr/local/bin/python2.7 ./yowsup-cli demos --config config.txt --send %s %s" % (phone_number, message))
        if "Sent" in do: print("msg sent to : %s" % phone_number)
        else: print("I can't send msg to : %s" % phone_number)
    except Exception as why: print why; sleep(5)
<code>

It's work just for 40 numbers then happened this error :

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

I think the error happened because the account Login --> Send Msg --> Log Out
And after many of login and logout ... etc my account blocked.

Is there any Simple app to send Message ?
is there any solutions for my problem?

thanks.
##

**Comment by jlguardi** [comment]
This is SPAM and it isn't supported by Whatsapp and so by yowsup. After 10-20 messages to recipient who had never interacted with you, your account will be blocked and conexion will be closed.

**Comment by deounix** [comment]
but in my number and my friend number always send ads msg to us. how can they do it ?
