### ISSUE TITLE
where does yowsup store recieved images?

### ISSUE THREAD

**Issue by e0xify** [tgalal/yowsup#1246]
yowsup demos in screen session says:

hatsapp.net(15-01-2016 09:53)]:[1452848027.--255]      [Media Type:image, Size:22493, URL:https://mmi326.whatsapp.net/d/Vkw8DtRL7qym1p__h-EhsFaYs6AABSsadg/AoRClnWWnGe5fsX5uhPWX9swDcmP6gqw3nBa
QF1y1fPh9v.jpg]  
Message 1452848027.--255: Sent delivered receipt and Read  
connected:                  

but where will the recieved image be stored on the system?                                     
##

**Comment by tgalal** [comment]
cli demo doesn't download or store incoming media
