### ISSUE TITLE
Logging in an existing user

### ISSUE THREAD

**Issue by vertangelx** [tgalal/yowsup#1249]
If I already have Whatsapp account on my phone (iPhone for example), how can I log in to Whatsapp a second time using `yowsup`?

Looking at the [echo sample application](https://github.com/tgalal/yowsup/wiki/Sample-Application), there is a place to insert the phone number and password. What format should the phone number be in? Where can the password be found?
##

**Comment by mjdev** [comment]
Thats not possible, WhatsApp can only be connected with one device at a time.

That means you have to use yowsup-cli and do the registration process, then you can use WhatsApp service.

**Comment by mgp25** [comment]
Well, you can extract the password from your device, but as @mjdev said, you can only be connected with one device at a time.

**Comment by jlmadurga** [comment]
@vertangelx  It is not recommended to make tests with your own personal number. If you don't use it properly it can get blocked from whatsapp
