### ISSUE TITLE
Pillow not building

### ISSUE THREAD

**Issue by darrynza** [tgalal/yowsup#1250]
This is probably not your issue, but was hoping someone could point out a missing dependency.

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

This happens when attempting to run setup.py install  as well as pip install yowsup2.

**Comment by darrynza** [comment]
sudo apt-get install libjpeg62 libjpeg62-dev libfreetype6 libfreetype6-dev zlib1g-dev

For anyone struggling to install on willy

**Comment by max1220** [comment]
I can confirm that this also was needed on a fresh Debian Jessie install.
