### ISSUE TITLE
yowsup-cli registration failed, reason blocked

### ISSUE THREAD

**Issue by FabrizioA** [tgalal/yowsup#1256]
Hi, 
I have a problem with yowsup registration.
On ubuntu 14.04 LTS I have installed yowsup with all dependencies.
If I execute:

`yowsup-cli registration -r sms -c /etc/myconf/whatsapp.conf`

I get:

```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}
status: fail
reason: blocked
```

my whatsapp.conf

```
cc=39
phone=012345678
id=myid
password=
```
##

**Comment by chenwayne** [comment]
got the same problem, my number was also blocked

**Comment by Maffelz** [comment]
You can send a short request to support@support.whatsapp.com

Just ask for unblocking your phone number and they'll do it (once).

**Comment by hkocaoglu** [comment]
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

status: fail
reason: blocked

Today , i have the same problem .

**Comment by pipsoft** [comment]
I need to add some annoying aspect to this "reason":"blocked" issue from my side. I add one or two extra numbers to phone numbers I use like (example, not a real number, don't use or call!) 0049 555 7965 xy where I choose xy freely. I register these numbers by voice request which will all end up on my phone as it does not matter how many more numbers you add once the real number is complete. For WA though those are different users. I'm sure this is a known trick and not an invention of mine.

This way I'm using three numbers for quite some time now 0049 555 7965 01, 0049 555 7965 02 and 0049 555 7965 03

Two on Raspian with Pis, and one on a Notebook with Ubuntu. In the past it happened from time to time that things would stop working, but after reading these forums I was always able to apply patches and get it running again. But for some weeks now I experience, that after only a few days or just one the number for the Ubuntu Notebook gets blocked. I increment to the next number xy and after some short time it gets blocked again.

All three systems should behave the same way just giving very few status messages. Ideally one "Alive" message a day at 19:30.  So this should not trigger any Spam alert at WA for excessive automated use. And if it would trigger an alert all of my three systems should have this problem not just the one. I'm puzzled. Any Idea what could cause this and after that any idea how to fix it?

I'm seriously considering to replace the functionality on the Notebook with a Pi but then I still would not know what caused the problem.

**Comment by acondoriml** [comment]
HI there is any way to not  be blocked ? 

Ty

**Comment by chriso0710** [comment]
@pipsoft Nice trick!

I think the blocking has nothing to do with sending messages or spamming. I had a yowsup client running, which only received messages. Virtual phone number worked great for 2 years but got blocked for the first time last week.
Maybe is has something to do with me testing and upgrading to @jlguardi 's master branch (which has worked great). Or WA gets better in detecting "unofficial third party" clients.

**Comment by pipsoft** [comment]
In the meantime my other two setup (the PIs) also stopped working because the are now blocked, too. I did not change anything for these systems. No updates, no nothing. They only sent an eMail once a day.

**Comment by progerjkd** [comment]
Same error here. Got blocked this morning.

**Comment by tvcnando** [comment]
Same error here. Got blocked this morning.

**Comment by progerjkd** [comment]
Message from whatsapp support team to my unblocking request. :(



##- WhatsApp Support -##

Hi,

Thanks for your message.

It appears that you are using an unauthorized application of WhatsApp. Unauthorized applications are not supported; they contain source code which WhatsApp can not guarantee as safe. Your private information is potentially being passed to 3rd parties. In addition, these may not function correctly and may cease to work at any given time.

Please uninstall your application and install an authorized version from:

www.whatsapp.com/download

After installing the authorized version, please reply to this email with a screenshot or an image of your screen from inside the app.

You can refer to your phone's user manual for detail steps of taking screenshots on your device.

Please note WhatsApp only works on smartphones, non-telephony devices including tablets are not supported.

Best Regards,
Peter

WhatsApp Support Team

**Comment by yniwly43** [comment]
@pipsoft tried it, didn't work, with Germany and several other country prefixes. I guess they blocked that trick too :) Too bad, wanted to see if it could get some numbers "unblocked" for the sake of tests..

**Comment by pipsoft** [comment]
I stopped working on this as the constant run to keep it working became too tedious for me. Instead I switched to email. But the last thing that worked for me in Germany was:

yowsup-cli registration --phone 491741*mynum*00 --mcc 262 --mnc 04 --cc 49

Replace the 00 with any numer you like. The last time I used this it worked, but got blocked after a day or two. I had up to 4 clients running before for over a year.

**Comment by thundergreen** [comment]
But registration works? Would be helpful to investigate

Thorsten Fröhlich
Am 28.04.2016 10:10 schrieb "pipsoft" <notifications@github.com>:

**Comment by pipsoft** [comment]
OK, just tried the following which worked perfect:

yowsup-cli registration --phone 491741******4 --mcc262 --mnc 04 --cc 49 --requestcode voice
yowsup-cli registration --phone 491741******4 --cc49 --regsiter 180356
yowsup-cli demos -c ~/yowsup-conf -s 491741******4 "TEST"

But I'm pretty sure the "******4" number will be blocked again in shortest time. That was the last of my ten possible options I had for this trick. Interestingly attaching more then two numbers did not work for me. So it did not work to you "491741******42

**Comment by yniwly43** [comment]
This might be because German numbers can be 9 numbers long, or 8 numbers long. Right? Or even less.

Read:
http://www.toytowngermany.com/forum/topic/172372-understanding-german-phone-numbers/

I mean, your number is 1741***, you attached the 4, I am pretty sure that is a possibly valid new number, no?

**Comment by pipsoft** [comment]
Did you follow the discussion above? Yes, those are all valid numbers.

The trouble is - number like this or "real physical" number the same - they all get blocked after short time. It seems WhatsApp recognizes yowsup and blocks?

**Comment by yniwly43** [comment]
It isn't related to the number, though, it is related to Yowsup itself, which is currently in a state that causes blocking to most users.

Cool trick! Thought it would be useful for trying to fix yowsup, not burning tons of numbers on the go, but.. you can't get old German numbers, only new ones with the maximum amount of digits :)

**Comment by swingingcode** [comment]
I agree on that, @pipsoft - suddenly my perfectly working (german) nr got blocked without any usage in the meantime!

**Comment by klein0r** [comment]
How long does it took until you have been blocked? I'm using yowsup for about 1 week with hundrets of daily messages without any issue.

**Comment by thundergreen** [comment]
Can u tell us exactly which branch u use ..which python and if file
transfer works or not and group messages

Thorsten Fröhlich

Am 20.07.2016 10:45 schrieb "Matthias Kleine" <notifications@github.com>:

How long does it took until you have been blocked? I'm using yowsup for
about 1 week with hundrets of daily messages without any issue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgalal/yowsup/issues/1256#issuecomment-233888990>, or mute
the thread

**Comment by pipsoft** [comment]
I quit using yowsup at that time. But it took only couple minutes to hours to get blocked at that time. Really frustrating so I gave up and switched to eMail notifications.

**Comment by adken123** [comment]
I have the same issue..After being registered and getting the password..I sent 3 whatsapp messages and after this my number have been blocked. Now I'm getting an Authentication Error: not-authorized.

**Comment by Messiefee** [comment]
I have the same problem, any idea?

**Comment by adken123** [comment]
I wrote a message to Whatsapp support...Below their reply.

Thanks for your message.
Unfortunately, we do not have a version of WhatsApp for your device right now. 
WhatsApp is compatible with:
1.	iPhone with iOS 6 or later 
2.	Android phones with Android OS v 2.1 or later 
Note: We offer limited support for Android tablets with an active SIM card
3.	BlackBerry with BB OS 6 or 7 
4.	Select Nokia Symbian devices: http://www.whatsapp.com/nokia 
5.	Select Nokia S40 devices: http://www.whatsapp.com/s40 
6.	Windows Phone 7 and higher 
7.	BlackBerry 10
As we announced in our blog, WhatsApp will no longer be supported on Blackberry, Blackberry 10, Nokia S40, Nokia Symbian S60, Android 2.1, Android 2.2 and Windows Phone 7 by the end of 2016. As such, we no longer offer customer support for inquiries related to those smartphones. 
Please note, WhatsApp is not supported on tablets or other platforms not listed above. We can’t support any user who is using WhatsApp on an unsupported platform.
For a detailed explanation of supported and unsupported devices, please read this FAQ article. 
If you have any other questions or concerns, please feel free to contact us. We would be happy to help!

**Comment by swingingcode** [comment]
I do strongly believe that WhatsApp will launch a bot service, soon and for this reason all unofficial APIs and workarounds are getting blocked.

**Comment by kennthchu** [comment]
same here.

Linux 4.4.11-23.53.amzn1.x86_64 x86_64
yowsup-cli v2.0.15
Using yowsup v2.5.0

I sent message for reports in one message group every 15 mins(0800-2030) in past week.
New number -> sent one week -> get blocked

I agree with @swingingcode  , they can setup some rules or just add a flag to indicate that was unofficial APIs or not easily. :(

Please forgive me the bad english.

**Comment by siouxme** [comment]
same problem here. Can't use it any more :-(

**Comment by AlexLoushkin** [comment]
Got blocked as well after 2 days using it.
status: fail
reason: blocked
login: 7962*******

**Comment by argaytan** [comment]
Got blocked too after 1 day using it :/
status: fail
reason: blocked
login: 521******

**Comment by johnduxx** [comment]
got blocked after few hours

**Comment by johnduxx** [comment]
what are the strategies to use the app

**Comment by johnduxx** [comment]
please contact support. it will take around 3-4 days

**Comment by Viclo** [comment]
Tengo un problema al pedir la verificación con "yowsup-cli"

## yowsup-cli registration --requestcode sms --phone 591xxxxxxxx --cc 591 --mcc 736 --mnc 03

INFO: yowsup.comon.http.warequest:{"login":"591xxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 591xxxxxxxx

Muchas gracias por su tiempo, espero llegar a recibir su ayuda.

**Comment by siouxme** [comment]
Ahorate el tiempo y dejalo..... Al fin igual te bloquean el número después
de 1-3 días. ...

Am 12.01.2017 17:34 schrieb "Viclo" <notifications@github.com>:

**Comment by cjaburto** [comment]
> @Viclo tienes que actualizar la version y el token string, yo clone la repo de nuevo actualize y listo
,pero al parecer ahora estan bloqueando los numeros estoy probando con otro para confirmar.

**Comment by Viclo** [comment]
@cjaburto Disculpa a que te refieres exactamente con el "token string". Aún soy novato

**Comment by mgp25** [comment]
Try to speak in English, this is an international repo. Other people could find this helpful.

By token string -> `PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk`
timestamp -> `1478194472015L`

There are tons on duplicate issues about this

**Comment by cjaburto** [comment]
@Viclo 
when i clone the repo it was a diference in those lines so i change them in yowsup/env/env_s40.py , look into #1889 

cuando clone la repo habia una diferencia en esas lineas cuando las cambie  en yowsup/env/env_s40.py , pude registrar el numero y enviar mensajes al dia siguiente me blockearon el número.

`_VERSION = "2.16.11"`
`_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"`

**Comment by jlguardi** [comment]
Usa el env_s40.py de mi master. Copialo en la ubicación del archivo bajado de github/tgalal/master ‎y haz: python setup.py install

De: Viclo
Enviado: jueves, 12 de enero de 2017 17:34
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi; Mention
Asunto: Re: [tgalal/yowsup] yowsup-cli registration failed, reason blocked (#1256)



Tengo un problema al pedir la verificación con "yowsup-cli"

yowsup-cli registration --requestcode sms --phone 591xxxxxxxx --cc 591 --mcc 736 --mnc 03

INFO: yowsup.comon.http.warequest:{"login":"591xxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 591xxxxxxxx

Muchas gracias por su tiempo, espero llegar a recibir su ayuda.

**Comment by tecnicosya** [comment]
I find an small solution, I try to register with a new number phone and show the error Old_version, but if I try to register a number was registred on the past all work fine.
Then try first to register your new number on real Whatsapp APP (Android emulator is valid, I do it with genymotion), then try to register on Yowsup, and now all working fine!

**Comment by b3zi** [comment]
@tecnicosya can you please give sone better translation of your solution. Getting interesting.

**Comment by sreeharibs** [comment]
got blocked just after sending a message, with in minutes

**Comment by motoseed** [comment]
Tuve el mismo problema con algunos números que intente registrar dentro de la API, pero encontré que primero registrando los números en un teléfono con whatsapp real los números no son bloqueados ya que su estatus de registro es existing y no NEW, al parecer cuando registras el número nuevo desde la máquina detecta que no es oficial pero al ya existir un registro previo en la APP oficial lo toma como cambio de teléfono.
 Esto lo digo porque hice pruebas con varios números de los cuales todos los que no pre-registre en Whastapp se me fueron bloqueando y los que si hice el Pre-registro siguen funcionando sin problemas.

**Comment by marcosmarchiore** [comment]
@motoseed  you solved problem ?

**Comment by Sakai92** [comment]
Hi Guys, I have problem with whatsapp wart registration failed and blocked.

First Request Code and confirm will come out with this message 
{"login":"601117xxxxxx","status":"fail","reason":"temporarily_unavailable","retry_after":3600}

Second time Request code will be blocked my number
Could not request code {"status":"fail","reason":"blocked","login":"601117xxxxx"}

have anyone of you know how to fix this problem ? I willing to pay for your service ^^

![1](https://user-images.githubusercontent.com/55705464/65442465-c67ec680-de5e-11e9-8fb2-c2b3d6b2cf58.PNG)
![2](https://user-images.githubusercontent.com/55705464/65442482-cf6f9800-de5e-11e9-8c03-3de96b9fdcd8.PNG)
