### ISSUE TITLE
Can't register a phone

### ISSUE THREAD

**Issue by EralpB** [tgalal/yowsup#1257]
Hello, can anyone register a phone?

I'm executing following 2 commands

yowsup-cli registration -r sms -c yowsup_config 
yowsup-cli registration -R 685-756 -c yowsup_config -d

my config is like:
    cc=49
    phone=49151458395**
    id=
    password=

SMS comes and the second command outputs:

```
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=49&in=151458395**&id=7W%A6%80%2MYIDQ%A8wfy%A6%D8v%87%C2%A6p&code=685756
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=49&in=151458395**&id=7W%A6%80%2MYIDDQ%A8wfy%A6%D8v%87%C2%A6p&code=685756
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}
```

status: fail
reason: missing

I can't seem to understand what's missing, I edited the code and added sim_mnc etc to the request but it didn't help, a parameter is missing?
##

**Comment by marga-debian** [comment]
It seems yowsup has stopped working with the latest whatsapp changes :(
