### ISSUE TITLE
How to get a string with User Status?

### ISSUE THREAD

**Issue by ArchangelZeero** [tgalal/yowsup#1259]
I want to save on a variable the content of a specific whatsapp user, like "Hey There, I'm using whatsapp!"

I was searching in the context of the command line "/statuses get <contact>", but I didnt manage how to get the most basic programming to get only the user status text. Someone could help me on this or even say if its possible right now with Yowsup?
##

**Comment by tgalal** [comment]
See [statuses_get](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L390) method in cli demo layer as an example.
