### ISSUE TITLE
NEXTLINE!!! Anyone success sending one now?

### ISSUE THREAD

**Issue by kwngeaw** [tgalal/yowsup#1260]
I can't direct yowsup to send nextline. Does anyone have a solution?

**Comment by tgalal** [comment]
nextline ?

**Comment by mgp25** [comment]
@tgalal  i think he means the `\n`

**Comment by tgalal** [comment]
I think he also means yowsup-cli demo

**Comment by kwngeaw** [comment]
Yeah, I mean the the "\n" in yowsup-cli demo.
