### ISSUE TITLE
isn't possibility of Yowsup getting banned more now specially after their declaration of FREE service all over the world.

### ISSUE THREAD

**Issue by ashishnetworks** [tgalal/yowsup#1261]
Yesterday I saw on media that whatsApp has officially announced that they are going to provide free service allover the world. During the declaration CEO Jan Koum said

"company won't be replacing the subscription fee with third-party advertisements like intrusive banner and interstitials, which nowadays is a common practice used to make free applications profitable.
Instead, the company will explore ways businesses can use WhatsApp to connect with individuals, and will introduce new ways for users to communicate with businesses and organisations that will pay the company to target relevant communications with customers." [ Source : http://goo.gl/8IOkjb ]

Its apparent that they are talking about creating their official WhatsApp API which will allow organizations to use WhatsApp as their communication medium like for sending OTP or Alert messages. They probably will charge to developers for using their official API, so it seems very obvious that they might block all the available unofficial APIs of WhatsApp like our very lovley Yowsup. I'm afraid about it. What do you guys think on the issue

**Comment by jegue** [comment]
The dream is over,
What can I say?
The dream is over
Yesterday
I don't believe in zuckerberg man!!!

**Comment by zenithanon** [comment]
I tend to disagree with this line of thought. If you use yowsup for non commercial purposes, I dont see why you should get banned.

**Comment by ashishnetworks** [comment]
@zenithanon Actually I was not talking about individual getting banned, I suspected blocking of entire Yowsup API to so that serious-developers community could rush for their Official API

**Comment by yniv** [comment]
Lets hope they will give us time to migrate gracefully to their API before blocking any unofficial API's or numbers that are using unofficial API's. I think it's in their own interest to allow all developers to migrate and not to hurt them.

**Comment by mgp25** [comment]
WA can't block the API because this is based in their own code, if WA block this, they are blocking the app too. Too much nosense here

**Comment by ashishnetworks** [comment]
@mgp25 I'm not sure about How part. But they(WA Folks) have somehow manged to block other unofficial APIs so I suspected misfortune. If you are right about their inability to discriminate between original device & Yowsups Bots then its really good news for us bro !  But I highly doubt about their such inability ..

**Comment by mgp25** [comment]
meh... it's quite easy to emulate original app with the API, but we don't give such features so WA can detect easily spammers

**Comment by zenithanon** [comment]
@mgp25 My thoughts exactly

**Comment by ashishnetworks** [comment]
suspected misfortune turning true, feeling sorry. isn't blocking of every single new Yowsup number the harbinger of last breath of our Yowsup? !! :disappointed:

**Comment by thundergreen** [comment]
I give up! I unblocked my number once they won't unblock it a second time I
guess as I already have a file .... I wanna focus on telegram and get this
running under spectrum transport ...but still there I'm lost.Facebook irc
ICQ Yahoo Skype work perfectly but telegram won't work.any help appreciated

Thorsten Fröhlich
Am 16.05.2016 21:07 schrieb "Ashish Networks" <notifications@github.com>:
