### ISSUE TITLE
how can I get info about admins of group

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1265]
How can I get info about admins of some group?
thnx.
##

**Comment by deounix** [comment]
why no one answer me :( !

I'm trying to fetch information about group admins but I don't know how can I do it, there is no example for that.

thanks.

**Comment by tgalal** [comment]
Using [InfoGroupsIqProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_groups/protocolentities/iq_groups_info.py). Example used in yowsup-cli cli demo command:
```
/group info 201006960035-1557093203
```
