### ISSUE TITLE
auth failed 

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#1267]
Guess they pushed a new version. auth fails now for existing accounts

**Comment by ToninoTarsi** [comment]
Same problem. Auth error starting from today.

**Comment by grindelsack** [comment]
Same here. Problem started yesterday (22.01) around 09:30pm (GMT+1)

**Comment by ToninoTarsi** [comment]
looking back at my log I got 

firsrt this Exception
   expecting STREAM_START in streamStart, instead got token: failure

and then always 
   AuthError

**Comment by rami-dabain** [comment]
Anyie kows how to fix it? i can edit code and push but i do t know what exactly should be done. Have wireshark and shit installed in case its reuired to capture aome packets

**Comment by addodelgrossi** [comment]
Same problem. Auth error starting from today.

**Comment by ToninoTarsi** [comment]
In my case updating to the last version solved the problem :-)

git clone git://github.com/tgalal/yowsup.git
cd yowsup
sudo python setup.py install

**Comment by addodelgrossi** [comment]
In my case also corrected

**Comment by grindelsack** [comment]
Unfortunately  I cannot confirm this:

D:\dev\yowsup\yowsup-git\yowsup>python yowsup-cli demos -y -c yowsup.cfg
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

D:\dev\yowsup\yowsup-git\yowsup>python yowsup-cli version 
yowsup-cli v2.0.13
Using yowsup v2.4.48

Any further idea or hint?

BTW: I also noticed that the number, I am using for Yowsup has been removed from all Whatsapp-groups. Should I rather go and re-register?

**Comment by decklord** [comment]
Check if you have been blocked checking the status number on a cellphone. If you see 'Invite to whatsapp' the number has been blocked. We also have been experiencing issues with connecting new numbers and then staying connected, we are being blocked right away with the last version of yowsup.

¿Is there any token to update?

**Comment by rami-dabain** [comment]
Updates the version (though i did it before) works.
