### ISSUE TITLE
Error during registration "no_routes" for my GV number, but works with real android device. 

### ISSUE THREAD

**Issue by thisisdos1984** [tgalal/yowsup#1269]
Hi guys, 

I have google voice number for which I wanted to register. I can do it using my old android device, send/receive text. But when I try to register same number using yowsup cli then I am getting "no_routes" error. Any idea ? I really appreciate any help. 
Thanks. 
##

**Comment by thisisdos1984** [comment]
Does yowsup not support google voice numbers  ?

**Comment by relima** [comment]
I have tried through multiple ways to get google voice numbers working with whatsapp and it seems they are blocked or unrecognized as a mobile number by them. Yowsup does not seem to have anything to do with it.

**Comment by thisisdos1984** [comment]
But I am able to register/activate same number on my android phone.

**Comment by relima** [comment]
Really? A google voice number? Give it a try to https://github.com/mgp25/WART

**Comment by thisisdos1984** [comment]
i tried WART and now I am getting "blocked" error :( 
Now how do I unblock my number  ?

**Comment by relima** [comment]
You can send a request to support@support.whatsapp.com

But I really dont think your google voice number will ever work with whatsapp.

**Comment by thisisdos1984** [comment]
Thank you for the suggestion. I will drop an email to support. 

GV number actually worked for me, I was able to register and send/receive messages using google voice number from my spare android phone.
