### ISSUE TITLE
Adding contacts

### ISSUE THREAD

**Issue by maticapa96** [tgalal/yowsup#1270]
Hi people.

I'm doing a notification system via Whatsapp, but i want to add the clients to my contacts to avoid a ban.

I understand if i have the people who i send messages in my contacts, whatsapp dont ban my number.

How can i do this?

Thanks a lot! :) Sorry for my bad english
##

**Comment by zenithanon** [comment]
You can also have your users send you an initial message (something like a subscription to receive messages from you) so Whatsapp doesnt thinkyou are spamming them.

**Comment by chenwayne** [comment]
my number also banned, how to add a virtual contact list so that whatsapp think it is a real user?

**Comment by maticapa96** [comment]
Thanks zenithanon! You are saying if the user send me first a subscription message whatsapp doesn't ban me? Are you sure?

Thanks :+1:

**Comment by zenithanon** [comment]
@maticapa96 or better still, let your users add your yowsup number as a whatsapp contact. You will never get banned.

**Comment by maticapa96** [comment]
@zenithanon yes, this is true. But i understand if i have the clients in contacts i will never get banned too. It's a little hard all my contacts add me to his contacts.
