### ISSUE TITLE
Registration failes due " status: fail; reason: missing"

### ISSUE THREAD

**Issue by Maffelz** [tgalal/yowsup#1271]
Hello,
I requested my SMS-Code with
`yowsup-cli registration --requestcode sms --phone 49176xxxxxxx --cc 49 --mcc 262 --mnc 07`
I received the SMS-code without any problems.

However, after I tried to confirm that this number is mine via
`yowsup-cli registration --register xxxxxx --phone 49176xxxxx --cc 49`
I got the following output:

```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}
status: fail
reason: missing
```

Well, I have no idea, what should be missing. Any ideas?
##

**Comment by chenwayne** [comment]
I got similar registration failure, but always show temporarily_unavailable after key in whatsapp verification code

**Comment by andersonpaac** [comment]
Same issue with yowsup-cli registration
```
yowsup-cli registration -R 236568 -p 1XXXXXXX -C 1 --debug
```
returning
```
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=1&in=2178487398&id=%87%8Al%223%F8%DD%5B%21%88p%D1%A6%0C%E4%EFc%BD%C7%F0&code=236568
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=1&in=2178487398&id=%87%8Al%223%F8%DD%5B%21%88p%D1%A6%0C%E4%EFc%BD%C7%F0&code=236568
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}

status: fail
reason: missing
> 

```

**Comment by Maffelz** [comment]
Were you able to fix this? I wasn't :/

**Comment by EralpB** [comment]
Me neither, I would love to be able to register.
