### ISSUE TITLE
when registering new whatsapp through yowsup, it is always temporally unavailable 

### ISSUE THREAD

**Issue by chenwayne** [tgalal/yowsup#1272]
After I key in the verification code from whatsapp, it showed temporally unavailable message. using the latest version of yowsup client   
##

**Comment by chenwayne** [comment]
<img width="845" alt="screen shot 2016-01-25 at 5 19 56 pm" src="https://cloud.githubusercontent.com/assets/5594664/12546912/f7e6e360-c387-11e5-91be-12550f80aa17.png">

error message given

**Comment by marga-debian** [comment]
Yeah, I'm seeing the same.  My old number got banned, so I'm trying to register a new one and it always says temporarily unavailable.

**Comment by iamtimde** [comment]
same here :-(
