### ISSUE TITLE
yowsup is dead?

### ISSUE THREAD

**Issue by Aydar77** [tgalal/yowsup#1273]
Hi friends, Friday yowsup does not send the message. Prior to that, all messages sent
 
The logs writes:
 WARNING: yowsup.stacks.yowstack: Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
 /....../yowsup-master/yowsup/demos/sendclient/stack.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
   print ("Authentication Error:% s"% e.message)
 whatsapp.sh: line 10: Authentication: command not found

 version__ = "2.0.13"

who sent the message right now?

**Comment by moscheIT** [comment]
Hi , to fix your problem you need edit env_s40.py 
like this
https://github.com/tgalal/yowsup/blob/master/yowsup/env/env_s40.py

and rebuild all.

this fix work for me !

**Comment by Aydar77** [comment]
Thank you, this work
