### ISSUE TITLE
Can not install pyton-axolotl during yowsup install, undefined reference to _imp__Py_InitModule4

### ISSUE THREAD

**Issue by bassijtsma** [tgalal/yowsup#1274]
Hi all,
I'm trying to install yowsup on a Windows (8.1) machine, with python 2.7.11. I ran the steps described at [the yowsup repo](https://github.com/tgalal/yowsup):

- installed the mingw compiler
- added mingw to path
- added the distutils file
- installed gcc with mingw-get.exe install gcc (no errors)
- added the zlib DLL folder to windows/system32

Now attempting to run the setup.py install, it goes smoothly until the python-axolotl install. I receive a long list of undefined references, such as these 3 (in total they are about 20 references):

`build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x367): undefined reference to '_imp__PyErr_SetString'`
`build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x3ab): 
undefined reference to '_imp__PyString_FromStringAndSize'`
`build\temp.win-amd64-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x3ea): 
undefined reference to '_imp__Py_InitModule4'`
    `collect2.exe: error: ld returned 1 exit status
    error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1`

I found [this](https://github.com/tgalal/python-axolotl-curve25519/issues/5) issue had the same problem, but I would rather not install python 3.4 as I'm no familiar with the difference in syntax etc. Any suggestions?

edit:for future reaaders: have not found a solution. Installing py3.4 did not work either. I spun up a linux vm and am doing it on another machine now.

**Comment by Vishal9650** [comment]
i am getting same issue any solution

vishalg2\appdata\local\temp\easy_install-xkgzbj\python-axolotl-curve25519-0.1\eg
g-dist-tmp-vq_1ym
curve25519module.c: In function 'calculateSignature':
curve25519module.c:50: warning: pointer targets in passing argument 1 of 'curve2
5519_sign' differ in signedness
curve25519module.c:50: warning: pointer targets in passing argument 2 of 'curve2
5519_sign' differ in signedness
curve25519module.c:50: warning: pointer targets in passing argument 3 of 'curve2
5519_sign' differ in signedness
curve25519module.c:50: warning: pointer targets in passing argument 5 of 'curve2
5519_sign' differ in signedness
curve25519module.c: In function 'verifySignature':
curve25519module.c:76: warning: pointer targets in passing argument 1 of 'curve2
5519_verify' differ in signedness
curve25519module.c:76: warning: pointer targets in passing argument 2 of 'curve2
5519_verify' differ in signedness
curve25519module.c:76: warning: pointer targets in passing argument 3 of 'curve2
5519_verify' differ in signedness
curve/ed25519/additions\curve_sigs.c: In function 'curve25519_keygen':
curve/ed25519/additions\curve_sigs.c:10: warning: unused variable 'ed_y'
curve/ed25519/additions\zeroize.c: In function 'zeroize':
curve/ed25519/additions\zeroize.c:6: warning: unused variable 'retval'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x5f):
 undefined reference to `_imp__PyExc_ValueError'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x84):
 undefined reference to `_imp__PyExc_ValueError'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x104)
: undefined reference to `_imp__PyExc_ValueError'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x175)
: undefined reference to `_imp__PyExc_ValueError'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x1f4)
: undefined reference to `_imp__PyExc_ValueError'
build\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x219)
: more undefined references to `_imp__PyExc_ValueError' follow
collect2: ld returned 1 exit status
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by hoehermann** [comment]
Why is this issue closed? I face the same problem.

**Comment by arjunbahl** [comment]
Check this:
http://stackoverflow.com/questions/34043334/unable-to-install-leven-package-using-python27-minggw-on-windows-10-collect2-exe

I had the exact problem and it got resolved. I simply installed 32Bit version of python as against 64Bit that i had installed earlier on the 64 bit machine.
