### ISSUE TITLE
my yowsup is not work

### ISSUE THREAD

**Issue by helfari** [tgalal/yowsup#1276]
Hi;
My yowsup is not working since 22nd january. I use for send messages of nagios.
I didn't do updates and changes. 
I did  a few of tests send messages and returned error:
# ./yowsup-cli demos -s XXXXXX "Test of ZAP ZAP" -M -c nagconf

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
##

**Comment by chenwayne** [comment]
same problem

**Comment by jlguardi** [comment]
Please, close this issue and read current issues.
