### ISSUE TITLE
You can read the number when they share a contact?

### ISSUE THREAD

**Issue by tanrax** [tgalal/yowsup#1282]
In the example application only receive text sample. I wanted is to capture phone numbers when I share a contact.
##

**Comment by jlmadurga** [comment]
As far I know, contacts comes in Vcard format https://en.wikipedia.org/wiki/VCard.
You can use some python lib to parse it i.e. http://eventable.github.io/vobject/

**Comment by tanrax** [comment]
The problems are not the format, but do not get the message.I get nothing when they share a contact me.

**Comment by jlguardi** [comment]
Vcards aren't text messages but media messages.

**Comment by tanrax** [comment]
As I capture media messages?

**Comment by t0rr3sp3dr0** [comment]
You can use the old Echo Client Demo as a base for your code https://github.com/tgalal/yowsup/tree/7cb3679451e6a6c9aa61b22dfe36ff7ccc65bc3b/yowsup/demos/echoclient
After you get the message entity of the vCard, you can do whatever you want to with it
