### ISSUE TITLE
How can I send an image using it URL?

### ISSUE THREAD

**Issue by johncordeiro** [tgalal/yowsup#1283]
I am receiving an image using Yowsup, so I'm saving the URL, but I need to send this image to another user and I don't want to upload the image again.

Is there anyway to do it?
##

**Comment by t0rr3sp3dr0** [comment]
Forward the message, you can see a good example of it in the Echo Client Demo https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/

**Comment by johncordeiro** [comment]
In the case of EchoClient, the message is received and forward using the same instance. I want to send the message in another moment. Do you have an example how to do it?

**Comment by x23piracy** [comment]
Hi,

look at this project using yowsup, for myself i heavily changed it for my needs (managing an indoor soccer group): https://github.com/joaoricardo000/whatsapp-bot-seed


Regards X23
