### ISSUE TITLE
onEvent not working

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1286]
Hi,

I am trying to setup a function that will restart the connection if it goes down. I read #1181 and related,  and tried to implement something similar but I could not get callbacks to work.

I tryed then a bit of DIY, added the following code in my appLayer, but I have tested and it does not get triggered.

```
  def onEvent(self, ev):
    if ev.getName() == YowNetworkLayer.EVENT_STATE_DISCONNECTED:
      print "Event Disconnected!"
      time.sleep(3)
      print "restarting..."
      return self.broadcastEvent(YowNetworkLayer.EVENT_STATE_CONNECT)
    else: return False
```

Any help pls?

A
##

**Comment by tgalal** [comment]
missing decorator
