### ISSUE TITLE
Downloading Files from user whcih are not in contact list

### ISSUE THREAD

**Issue by arnzel** [tgalal/yowsup#1288]
Hi,

when i get messages from users, which are not in my contact list, can is download these files automatically ?

when i use Whatsapp on my smartphone i must first confirm that i accept this file. i want to do this automatically.
##

**Comment by tgalal** [comment]
[Media Sink demo](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/mediasink/layer.py)
