### ISSUE TITLE
ERROR: No such signedprekeyrecord! 57691

### ISSUE THREAD

**Issue by maticapa96** [tgalal/yowsup#1289]
Hi people.

I cant send or receive messages. When i try to login in yowsup console or start the echo demos i obtain this:

ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 57691 

a lot of times.

Any help is apreciated!! Sorry for my bad english. Greetings!

**Comment by jlguardi** [comment]
Remove encryption database (axolotl.db) and start again cli.

**Comment by maticapa96** [comment]
HI @jlguardi for your response. Where i can find this archive? Thanks!!

**Comment by jlguardi** [comment]
In linux, you can find it in $HOME/.yowsup/phonenumber/axolotl.db.

**Comment by maticapa96** [comment]
Thanks you a lot!! :)
