### ISSUE TITLE
Who's going to fix the problem for $100 "reason: temporarily_unavailable"

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1290]
When the yowsup registration of channels with registration code get the response "reason: temporarily_unavailable". Use USB modem, my IP after each error.

При работе программы по регистрации каналов при регистрации кода получаю ответ "reason: temporarily_unavailable". Использую USB модем, меня IP после каждой ошибки.
##

**Comment by cyberp1983** [comment]
I will pay to anyone who can solve my problem.

**Comment by cyberp1983** [comment]
my skype: int-el

**Comment by cyberp1983** [comment]
$50

**Comment by yniv** [comment]
have you tried to activate multiple numbers from the same IP at a short time??

**Comment by capsload** [comment]
how do you register? did you used this:

yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456

you can find your MCC and MNC codes here: https://en.wikipedia.org/wiki/Mobile_country_code

replace the following with yours:

49XXXXXXXX
49
123
456

PM me for Paypal Address.

**Comment by tobilektri** [comment]
Problem still there?
