### ISSUE TITLE
Auth error while registering and number banned

### ISSUE THREAD

**Issue by iamanoopmk** [tgalal/yowsup#1293]
I used the cli to register and tried logging in. But there was auth error and now my whatsapp says that my number is banned. Please help me to get it unbanned please.
##

**Comment by max1220** [comment]
Seems like a common thing nowadays. Try reading the PW of a phone with Whatsapp installed!
(If that's not an option, try to specify the full MCC)


https://github.com/tgalal/yowsup/issues/1256
https://github.com/tgalal/yowsup/issues/1271

**Comment by jlguardi** [comment]
I've experienced this issue but first login was successful until I've received a message sent before registration. Then my account became blocked.
