### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by bachoo786** [tgalal/yowsup#1295]
Please Please Please help me I have installed a fresh copy on the raspberry pi 3 times to install yowsup  but i get the same errors overtime. here they are:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pillow

Please help me.

Many thanks
##

**Comment by bachoo786** [comment]
anyone??

**Comment by thundergreen** [comment]
@ bachoo786 u Miss pillow ... Install  it with pip install pillow

**Comment by bachoo786** [comment]
Hi
Thanks for your reply.
Can you please show me how to install with pillow ?
Thanks
Sent from my Samsung device

-------- Original message --------

**Comment by thundergreen** [comment]
Please join my channel:

yowsup@chat.no-ip.me

It's my private yowsup channel for now

Thorsten Fröhlich
Am 12.02.2016 13:49 schrieb "bachoo786" <notifications@github.com>:

**Comment by nlsdfnbch** [comment]
As Thundergreen already mentioned:
`sudo pip install pillow` for Python2.7 and I think
`sudo python3 pip install pillow` for python3.x
sudo might be optional, depending on your setup.

**Comment by thundergreen** [comment]
@nlsdfnbch does transwhat work for you? I use transwhat but I get loop error somehow [#1307](https://github.com/tgalal/yowsup/issues/1307)
