### ISSUE TITLE
Pillow Installation fails

### ISSUE THREAD

**Issue by SoundWavezZzZz** [tgalal/yowsup#1302]
File "/tmp/easy_install-fB_dIt/Pillow-3.1.1/setup.py", line 516, in build_extensions

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

Seems to be a bug with pillow, unfortunately, I do not know how to solve the problem. I'm running debian 8, python 2.7.9.

**Comment by mubbashar84** [comment]
Install libjpeg8-dev and the issue will be resolved.



Regards,

On Tue, Feb 9, 2016 at 3:14 PM, Kevin <notifications@github.com> wrote:

> File "/tmp/easy_install-fB_dIt/Pillow-3.1.1/setup.py", line 516, in
> build_extensions
>
> ValueError: jpeg is required unless explicitly disabled using
> --disable-jpeg, aborting
>
> Seems to be a bug with pillow, unfortunately, I do not know how to solve
> the problem. I'm running debian 8, python 2.7.9.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgalal/yowsup/issues/1302>.
>



-- 
اسلام عليكم

**Comment by SoundWavezZzZz** [comment]
The one is solved, another appeared:

  File "/tmp/easy_install-d3Uic6/Pillow-3.1.1/setup.py", line 519, in build_extensions

ValueError: --enable-zlib requested but zlib not found, aborting.

**Comment by mubbashar84** [comment]
Kevin,

Install these packages this will resolve the issue. libtiff4-dev
libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
tcl8.5-dev tk8.5-dev python-tk


Regards,

**Comment by SoundWavezZzZz** [comment]
Tyvm for your help, that resolved it :)
