### ISSUE TITLE
EXCEPTION : unimplemented notification type - encrypt

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#1304]
After yesterdays whatsapp update, there seems to be a new notification of type "encrypt" which theows 
[screeshot](http://i.imgur.com/3PcJObk.jpg)

YowAxolotlLayer added as well... was working yesterday before whatsapp update

**Comment by yniv** [comment]
What whatsapp update? I did'nt know they updates something... here everything as ussuall
