### ISSUE TITLE
YowSup not receiving messages only from my number

### ISSUE THREAD

**Issue by Giotino** [tgalal/yowsup#1306]
I made a small python program using yowsup, all works fine, but my app not receive messages from my number.

I don't know why, other numbers work, please help me

**Comment by jlguardi** [comment]
Keys error. Remove axolotl.db database and restart again your app.
If you enable debug info, you can see what I happening internally.

**Comment by Giotino** [comment]
I deleted axolotl.db, but my app still not working
Then randomly it received all the messages, NICE!

@jlguardi Thanks for your rapid answer
