### ISSUE TITLE
Storing Image

### ISSUE THREAD

**Issue by kumarshivam675** [tgalal/yowsup#1308]
Where does yowsup store received images. Does it automitically store it or do I need to add some kind of function.
##

**Comment by thundergreen** [comment]
In Gateway mode, the server takes care of stored messages.

**Comment by tgalal** [comment]
yowsup doesnt store or download incoming media. See [https://github.com/tgalal/yowsup/blob/master/yowsup/demos/mediasink/layer.py](Media sink demo) for an example how to implement that
