### ISSUE TITLE
MessageProtocolEntity.getFrom() returns group ID but not actual sender's phone#

### ISSUE THREAD

**Issue by nlsdfnbch** [tgalal/yowsup#1309]
`    def onTextMessage(self,messageProtocolEntity):
        # just print info
        print(archive_msg(messageProtocolEntity.timestamp,
                messageProtocolEntity.getFrom(),
                messageProtocolEntity.getBody()))`
where `.getFrom()` always returns `GroupFounderNum-GroupID@g.us`. How can I get the number it's actually from? I have 3 people in the group and I'm using the bot to archive the messages.

**Comment by Giotino** [comment]
Use messageProtocolEntity.participant, it will give you the writer of the message

**Comment by nlsdfnbch** [comment]
Cheers!
