### ISSUE TITLE
Other ways to request codes?

### ISSUE THREAD

**Issue by mounssif** [tgalal/yowsup#1310]
Hi

I have a Blackberry Z10, WhatsApp was already installed but when i tried to pull out my simcard all my sim slots went out. So my phone doesn't read any simcards now. I still can access my WhatsApp but how can i receive a code without simcard? Is it possible to receive the code on WhatsApp? Like Telegram does?

Kind regards
##

**Comment by aRandomStranger** [comment]
**Hi **there,

**no**, unfortionally you need a sms-ready phone number.

**Comment by jlguardi** [comment]
But you you get sms on on phone and use this code on other. However it isn't related with yowsup.

**Comment by aRandomStranger** [comment]
Using WART
