### ISSUE TITLE
ImportError: No module named 'glue.lal'

### ISSUE THREAD

**Issue by rayenough** [tgalal/yowsup#1312]
Whenever I try to run  from gwpy.timeseries import TimeSeries, this error occurs. 
Please let me know what I am doing wrong. 
##

**Comment by 786487768** [comment]
you should install glue.

**Comment by simotonno** [comment]
I get the same error even if I already have glue installed. how can I fix this error?

**Comment by tgalal** [comment]
personal problems are irrelevant to yowsup
