### ISSUE TITLE
Need a developer to create a script to send Whatsapp messages

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1316]
Need a developer to create a script to send Whatsapp messages. Requirements for the program: Send more than 50 msg with 1 channel, speed more than 10K messages per hour, delivery report, sending a picture + text. Payment PayPal. Waiting for suggestions
My Skype: int-el

**Comment by nashe** [comment]
Uses a USB modem and wants to send more than 10K messages per hour? 

\**smelling like spam*\*

**Comment by cyberp1983** [comment]
Where did you get this? I will consider any options and suggestions.
