### ISSUE TITLE
How to add a contact on yowsup on raspberry pi?

### ISSUE THREAD

**Issue by bachoo786** [tgalal/yowsup#1319]
Hi All

Can anyone tell me on how to add a contact on yowsup on raspberry pi? I am having difficulties to remember numbers and typing them every time to send them a message?

Many thanks.

**Comment by steven-chau** [comment]
If you are using `yowsup-cli`, maybe you can edit this section:
https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L54-L59

**Comment by thundergreen** [comment]
Why don't you use spectrum2 Ejabberd and transwhat? Like this u add your contacts in the roster of the server. Works perfectly. I have Ejabberd spectrum2 and transwhat running on the pi 2

**Comment by bachoo786** [comment]
hi thundergreen 

how do I install and configure Ejabberd spectrum2 and transwhat running on the pi 2?

**Comment by bachoo786** [comment]
Hi Steven Chau

How do I edit that section that you showed me? which file is it on my raspberry pi 2?

**Comment by thundergreen** [comment]
@bachoo786

Well..first of all u need a xmpp client.then we can meet in a muc to discus
this. This is not the right place here. My jid: thorsten@emevth.no-ip.biz

See u

Thorsten Fröhlich
Am 20.02.2016 00:35 schrieb "bachoo786" <notifications@github.com>:
