### ISSUE TITLE
Failed to build 'python-axolotl' when installing on Windows

### ISSUE THREAD

**Issue by aviaryan** [tgalal/yowsup#1321]
Python 3.5.1 ( Anaconda 64 bit ) . PyCrypto is already installed.

```
Collecting yowsup2
Requirement already satisfied (use --upgrade to upgrade): pyreadline in c:\anaconda3\lib\site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): argparse in c:\anaconda3\lib\site-packages (from yowsup2)
Collecting python-axolotl>=0.1.7 (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): pillow in c:\anaconda3\lib\site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in c:\anaconda3\lib\site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): pycrypto in c:\anaconda3\lib\site-packages (from python-axolotl>=0.1.7->yowsup2)
Collecting python-axolotl-curve25519 (from python-axolotl>=0.1.7->yowsup2)
  Using cached python-axolotl-curve25519-0.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): protobuf<3.0.0-alpha-2,>=2.6 in c:\anaconda3\lib\site-packages (from python-axolotl>=0.1.7->yowsup2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil->yowsup2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\anaconda3\lib\site-packages\setuptools-19.4-py3.5.egg (from protobuf<3.0.0-alpha-2,>=2.6->python-axolotl>=0.1.7->yowsup2)
Building wheels for collected packages: python-axolotl-curve25519
  Running setup.py bdist_wheel for python-axolotl-curve25519: started
  Running setup.py bdist_wheel for python-axolotl-curve25519: finished with status 'error'
  Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Avi\\AppData\\Local\\Temp\\pip-build-z3d7vm3o\\python-axolotl-curve25519\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\Avi\AppData\Local\Temp\tmp7tjw3w1ipip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'axolotl_curve25519' extension
  error: Unable to find vcvarsall.bat
  
  ----------------------------------------
  Running setup.py clean for python-axolotl-curve25519
Failed to build python-axolotl-curve25519
Installing collected packages: python-axolotl-curve25519, python-axolotl, yowsup2
  Running setup.py install for python-axolotl-curve25519: started
    Running setup.py install for python-axolotl-curve25519: finished with status 'error'
    Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Avi\\AppData\\Local\\Temp\\pip-build-z3d7vm3o\\python-axolotl-curve25519\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Avi\AppData\Local\Temp\pip-sd28m4v4-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'axolotl_curve25519' extension
    error: Unable to find vcvarsall.bat
    
    ----------------------------------------

 Failed building wheel for python-axolotl-curve25519
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Avi\\AppData\\Local\\Temp\\pip-build-z3d7vm3o\\python-axolotl-curve25519\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Avi\AppData\Local\Temp\pip-sd28m4v4-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Avi\AppData\Local\Temp\pip-build-z3d7vm3o\python-axolotl-curve25519
You are using pip version 8.0.1, however version 8.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by tgalal** [comment]
```error: Unable to find vcvarsall.bat```

**Comment by Dayait** [comment]
I am installing on windows by the time it finishes getting error, Please advise

Collecting python-axolotl-curve25519
  Using cached python-axolotl-curve25519-0.1.tar.gz
Installing collected packages: python-axolotl-curve25519
  Running setup.py install for python-axolotl-curve25519 ... error
    Complete output from command c:\python\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\users\\u0133698\\appdata\\local\\temp\\pip-build-znzjd6\\
python-axolotl-curve25519\\setup.py';exec(compile(getattr(tokenize, 'open', open
)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c
:\users\u0133698\appdata\local\temp\pip-sgixh4-record\install-record.txt --singl
e-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'axolotl_curve25519' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\curve
    creating build\temp.win32-2.7\Release\curve\ed25519
    creating build\temp.win32-2.7\Release\curve\ed25519\additions
    creating build\temp.win32-2.7\Release\curve\ed25519\nacl_sha512
    C:\Users\U0133698\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyt
hon\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icurve/ed25519/nacl_
includes -Icurve/ed25519/additions -Icurve/ed25519 -Ic:\python\include -Ic:\pyth
on\PC /Tccurve25519module.c /Fobuild\temp.win32-2.7\Release\curve25519module.obj

    curve25519module.c
    curve25519module.c(76) : error C2143: syntax error : missing ';' before 'typ
e'
    curve25519module.c(78) : error C2065: 'result' : undeclared identifier
    curve25519module.c(82) : error C2143: syntax error : missing '{' before '*'
    curve25519module.c(100) : warning C4133: 'return' : incompatible types - fro
m 'PyObject *' to 'int *'
    curve25519module.c(146) : warning C4133: 'initializing' : incompatible types
 - from 'int *(__cdecl *)(PyObject *,PyObject *)' to 'PyCFunction'
    error: command 'C:\\Users\\U0133698\\AppData\\Local\\Programs\\Common\\Micro
soft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python\python.exe -u -c "import setuptools, tokenize;__file__='c:\\u
sers\\u0133698\\appdata\\local\\temp\\pip-build-znzjd6\\python-axolotl-curve2551
9\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().repla
ce('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\u0133698\appdata
\local\temp\pip-sgixh4-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in c:\users\u0133698\appdata\local\temp
\pip-build-znzjd6\python-axolotl-curve25519\

**Comment by me21** [comment]
Same here, error while building.

**Comment by mrkhanakia** [comment]
SOLUTION:
1. Go to Control Panel\Programs\Programs and Features and Check is your Python27 is 64bit if yes then this is the reason for error
2. Simply uninstall Python27 64 bit
3. Download Python 27 32bit from here https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi
4. Install it and then try to build it will solve your error

Happy Coding !!!!
