### ISSUE TITLE
No Routes

### ISSUE THREAD

**Issue by EmersonHenriique** [tgalal/yowsup#1323]
Ola galera estou com problemas para registrar um numero whatsapp, sempre que coloco um numero aparece no routes e já verifiquei no host e todas as portas estão liberadas, estou usando ubuntu 14.04  servidor vps hospedado em Chicago, alguém poderia me ajuda ?

**Comment by EmersonHenriique** [comment]
Hello guys I have problems to register hum whatsapp number , always put que um number appears there are routes and I checked no host and all the doors are released, I'm using Ubuntu 4.14 Server VPS Hosted in Chicago Could anyone help me ?

**Comment by EmersonHenriique** [comment]
Logs :
root@DBO:~# yowsup-cli registration --requestcode sms --phone 5518991XXXXXX --cc 55 --mcc 724 --mnc 05
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by relima** [comment]
@EmersonHenriique try registering with WART instead - https://github.com/mgp25/WART

**Comment by EmersonHenriique** [comment]
@relima Excuse my ignorance with this WART I register my number and then place the PASSWORD in the config and so can not send messages to whatsapp?

**Comment by EmersonHenriique** [comment]
someone could help me? I put the check number and the system informs me that this wrong: /

**Comment by thonnycleuton** [comment]
Hey @EmersonHenriique da uma sacada nessa Issue, pra mim isso resolveu.
 https://github.com/tgalal/yowsup/issues/1585
This issue above worked like a charm for me. cheers bro.
