### ISSUE TITLE
Can authorize CLI and phone app at the same time? 

### ISSUE THREAD

**Issue by csawall** [tgalal/yowsup#1325]
Hello!  I've had Whatsapp on my iPhone for quite sometime.  I installed Yowsup with success and was able to register.  Per the instructions, I send the SMS code and do the registration on my rPI with my phone's phone number.  Everything works and I can log in.  But what it then does is make my phone app unusuable as it states another device has registered my number.  If I re-register and verify the app on my phone, then Yowsup stops working for a similar reason.

Am I missing in the instructions how to register Yowsup successfully AND have my phone Whatsapp working at the same time? 

Thanks!
chris

**Comment by jlguardi** [comment]
You can't with register method. If you perform a registration, you invalidate previous credential.  

You need to stole credentials from your rooted phone.

**Comment by csawall** [comment]
So, the only way to make this Yowsup work, if you also want to have Whatsapp on your phone is to root your phone?  Doesn't seem like a practical way to do this.  There are no other options?  Thanks!
