### ISSUE TITLE
Whatsapp to stop support for Symbian... how that will affect yowsup?

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#1327]
https://blog.whatsapp.com/10000617/WhatsApp-support-for-mobile-devices

based on their blogpost they will stop support for symbian devices and others, how thatbwill affect yowsup? how easy it would be to fix it?

this is a serious issue that willt affect all of us for unknown time, any suggesstions on what should we do and how to preparea?

**Comment by danielblx** [comment]
Anyone know if this will affect the yowsup?

**Comment by mgp25** [comment]
It wont affect, easy changes

Regards

**Comment by rami-dabain** [comment]
But yowsup is registering on the network as a symbian device

**Comment by pulimento** [comment]
I think they will stop to support and distribute for those platforms, but current apps will continue working

**Comment by wbeirigo** [comment]
I agree with rami-dabain. The chances are high.

**Comment by rami-dabain** [comment]
We need to be prepared.
Any suggestions ?

Kind regards ,
Rami Dabain

**Comment by rami-dabain** [comment]
So it begins: http://www.androidpolice.com/2016/03/04/whatsapp-starts-emphasizing-end-to-end-encryption-collapses-long-messages-and-tests-some-minor-interface-changes/

**Comment by rami-dabain** [comment]
can this be linked to : https://github.com/tgalal/yowsup/issues/1304 ?
