### ISSUE TITLE
Number blocked and see whatsapp support response

### ISSUE THREAD

**Issue by hayesrobin** [tgalal/yowsup#1329]
I have registered a whatsapp account using yowsup-cli 3 days ago and found it blocked today. After reading some issues on "Auth" in this repo. I've learned that whatsapp could unblock my number if I send them a mail to their support email --> support@support.whatsapp.com . After sending email this is what they responded --> 

```
##- WhatsApp Support -##

Hi,

Thanks for your message.

Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.

Please uninstall your application and install an authorized version on supported devices from:

www.whatsapp.com/download

Please note that we do not provide support for unofficial clients or for jailbroken/rooted (including emulators), and unsupported devices.

Should we determine that your actions continue to violate our Terms of Service, your account will be permanently banned and there will be no possibility of an appeal.

If you have any other questions or concerns, please feel free to contact us. We would be happy to help!

Georgia

WhatsApp Support Team

Interested in translating for us? Please visit our website: http://translate.whatsapp.com

Take a look at our FAQ: http://www.whatsapp.com/faq
```

Now, can anybody please tell me how can I efficiently run a whatsapp bot backed by yowsup that won't get blocked.

**Comment by rami-dabain** [comment]
dont send to people that dont know you. once they press block/spam you r labeled as spammer. if you want to spam people use sms

**Comment by hayesrobin** [comment]
Hi, @rami-dabain thanks for the reply , The bot i have created just to test. And I tested it using my three phones. But I think I did some mistake 

1) I have accessed whatsapp using all three mobile at a time from same ip . 
2) I named my bot as "MarkBot" :P 

I didn't message to anyone else except me .

**Comment by rami-dabain** [comment]
1 - If you connect 2 devices at once from the same whatsapp account that would be an issue.
2 - Those you send messages to have to be in your contact list (sync)
3 - Make sure you add the number use use with yowsup to your contact list in mobile.

This is not 100% correct, but it makes sense, I would check for those if i were whatsapp :)
