### ISSUE TITLE
Cannot login to WhatsApp 

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1332]
Hi all i have installed yowsup in linux redhat 6.Everything is installed and getting the whatsapp message also but the problem is when i tried  /L to login its show error like this.please give solution for this  

[offline]:/L
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Segmentation fault (core dumped)

Thanks

**Comment by hayesrobin** [comment]
Same here! In my case after inserting /L it is saying "offline or disconnected "

**Comment by abhiroock** [comment]
yes exactly same results "offline" or "disconnect".

**Comment by abhiroock** [comment]
I am not able to login to Whatsapp account because of the above mentioned problem.I need to send image offline in linux redhat 6.Is their any way to send image using (Command line client) yowsup-cli  demos to send image.
