### ISSUE TITLE
document sharing

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1334]
Hi,
Whatsapp today released a new functionality to allow users to share document files (only pdf for now though)
Will this be also possible through Yowsup (someday) ?

for ref:
[http://www.businessinsider.in/Guess-what-Whatsapp-now-lets-you-share-PDF-files-with-yourcontacts/articleshow/51243009.cms]

Thanks,
Alex

**Comment by tgalal** [comment]
fixed
