### ISSUE TITLE
add support to new document attachment

### ISSUE THREAD

**Issue by yakovyarmo** [tgalal/yowsup#1337]
WhatsApp just added a new document attachment.
When I tried to attach a document from my phone and send it to yowsup, I get that it is not supported because yowsup is on an older WhatsApp version

**Comment by bdbais** [comment]
Same here, probably new feature will be supported... I don't know when,.

**Comment by jodersus** [comment]
Raised it in #1334 too, just linking the two

I guess there's a lot going on to look at new features right now...

**Comment by tgalal** [comment]
fixed
