### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1342]
im using the current library and when i try to connect and login i got this message 

Authentication Error: not-authorized

is very frustrating to me because i cant connect and i see my phone number is blocked when i used the warp app and get the password. what happend is whatssap servers or is the library because i cant register or send any message (video,audio,text).

**Comment by chiessilmb** [comment]
Same to me too.

I'm using --debug to get more details and this is the end of debug:

**_DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure_**

So, I try to register again and get this return:

**_INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
_**

Thanks!

**Comment by jlguardi** [comment]
@chiessilmb You've been blocked! Probably your app sent too many messages or you sent too many messages to people who haven't you as contact. 
Now you are trying to register with master code which has an old version number. Read #1335 
However, you are blocked and need to wait for 60 days (this happened to me).

**Comment by minimaldev** [comment]
@jlguardi  ok how i can prevent whatsapp phone number block when i havent contact on my contact list. i need to sync conctacs first ?

**Comment by jlguardi** [comment]
Nobody knows actual whatsapp filters to detect non-official apis. But sync contacts before to write them seems a good practice. However I've never made and I keep all lines alive for 2 years.

**Comment by minimaldev** [comment]
@jlguardi  on every conversation ? or every message ? this sync is one time per contact number or is every message

**Comment by jlguardi** [comment]
@minimaldev you can see a good proposal for a correct flow in https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#whatsapp-workflow

**Comment by minimaldev** [comment]
@jlguardi ok seeing the documentation i can see my phone number online when i try to send message from another phone why happend this

**Comment by eugenebann** [comment]
@jlguardi thanks a lot for your work re. Android ENV, I figured out the S40 thing on my own actually before seeing your update! However, I'm now getting booted off all my lines, even those operating for > 6 months. My question is, do you know how much of https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#whatsapp-workflow has been implemented implicitly in yowsup, and which do we need to call manually?
