### ISSUE TITLE
yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by ganesansays** [tgalal/yowsup#1343]
ubuntu@ip-172-31-23-19:~/yowsup/yowsup$ yowsup-cli registration --requestcode sms --debug --phone 91phonenumber --cc 91 --mcc 404 --mnc 84
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=91&in=phonenumber&lc=GB&lg=en&sim_mcc=404&sim_mnc=084&method=sms&token=fc4d7ce0f27db7f77d9a05953890a3ee&id=%1Ec%02ET%B1%F3%F1%F1%BD%D4%2F%7E%EA9%E1%04Fj%02
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=9962644988&lc=GB&lg=en&sim_mcc=404&sim_mnc=084&method=sms&token=fc4d7ce0f27db7f77d9a05953890a3ee&id=%1Ec%02ET%B1%F3%F1%F1%BD%D4%2F%7E%EA9%E1%04Fj%02
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
Read #1335 and close this issue because it is duplicated.

**Comment by ganesansays** [comment]
Thanks much @jlguardi ... your pull request worked ...
