### ISSUE TITLE
{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by arminth** [tgalal/yowsup#1345]
Dear Tgalal,

again, we have an old version registration failure. Worked about two weeks ago, now on registration, I get:

 python yowsup-cli registration --requestcode sms --phone 4917212345678 --cc 49 --mcc 262 --mnc 09

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

Please fix, if possible!

Thanks
Arminth

**Comment by arminth** [comment]
Sorry, didn't realize that issue was already adressed in #1336 and solved by jlguardi. A merge to the master would be nice.

**Comment by thundergreen** [comment]
I'm wondering when yowsup will finally be updated . so many bugs and so fix
atm

Thorsten Fröhlich
Am 08.03.2016 20:35 schrieb "arminth" <notifications@github.com>:
