### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by Cardosoalexandre** [tgalal/yowsup#1347]
Hello guys,

I'm using Python 2.7 and the latest version of yowsup 2.4.48
I think I'm using the latest yowsup - https://github.com/tgalal/yowsup

1. I am unable to send message via yowsup2, follows return.
![send_message](https://cloud.githubusercontent.com/assets/5559139/13634368/e62903d8-e5d3-11e5-883f-a7c37e1a8144.jpg)

2. And when I try to log in via Yowsup Cli client have no success also, can someone help me ??
![login_yowsup](https://cloud.githubusercontent.com/assets/5559139/13634379/f4bc909a-e5d3-11e5-849f-f46399f5a27f.jpg)

**Comment by jlguardi** [comment]
Register again your phone (probably you have been banned) due to your password is invalid. Remember that master doen't supports registration currently (read #1335).

**Comment by Cardosoalexandre** [comment]
Success!!!! Thank @jlguardi
Updated some files and it worked.

But I now install whatsapp on my phone and requested a new code and now the yowsup stopped working and can not use the same code to generate a new PW
![error](https://cloud.githubusercontent.com/assets/5559139/13644139/012b4ca2-e603-11e5-887d-fce6d4bc55cd.jpg)

**Comment by jlguardi** [comment]
Whenever you register a new client (official client or yowsup/chatAPI/...) whatsapp server invalidates previous generated keys. So you "can't" run multiples clients of whatsapp.

There are other ways to stole credentials from official whatsapp (see chatAPI documentation) but you could never run both simultaneously.
