### ISSUE TITLE
How do I update the files automatically to fix {old version issue}

### ISSUE THREAD

**Issue by mabbashm110** [tgalal/yowsup#1350]
Sorry guys newbie here
Using cli 2.0.13
yowsup 2.4.48

What are the steps to fix the old version issues, I see the files modified, do I have to makes changes to each manually and recompile or there is a better way of doing it using github?

Appreciate urgent response

**Comment by tchibu** [comment]
Hi! I as another newbie would like to ask the same question. ;)

**Comment by jlguardi** [comment]
In #1335 you have some git commands for that.

**Comment by mabbashm110** [comment]
I did it manually.. Lol
It fixed my issue
Here are the files you need to work on, go to the yowsup folder and make changes.
https://github.com/tgalal/yowsup/pull/1336/files

**Comment by hs-hugosantos** [comment]
Thanks mate!

**Comment by tchibu** [comment]
Thanks  @jlguardi, I've got it running! :)
