### ISSUE TITLE
Can used with demos but cannot run my run.py app

### ISSUE THREAD

**Issue by bourloud** [tgalal/yowsup#1353]
Everything fine with yowsup-cli demos --yowsup --login XXXXXXXX:pwd

But impossible to used my own solutions with run.py:

`from layer import EchoLayer
from yowsup.layers                             import YowParallelLayer
from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS
from yowsup.layers.axolotl                     import YowAxolotlLayer
from yowsup import env

CREDENTIALS = ("XXX", "XXXX") # replace with your phone and password

if **name**==  "**main**":
    layers = (
        EchoLayer,
        YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer]),YowAxolotlLayer
    ) + YOWSUP_CORE_LAYERS

```
stack = YowStack(layers)
stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
stack.loop() #this is the program maintop
```

`

And layer.py:

`from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_messages.protocolentities  import TextMessageProtocolEntity
from yowsup.layers.protocol_receipts.protocolentities  import OutgoingReceiptProtocolEntity
from yowsup.layers.protocol_acks.protocolentities      import OutgoingAckProtocolEntity

class EchoLayer(YowInterfaceLayer):

```
@ProtocolEntityCallback("message")
def onMessage(self, messageProtocolEntity):
    #send receipt otherwise we keep receiving the same message over and over

    if True:
        receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom(), 'read', messageProtocolEntity.getParticipant())

        outgoingMessageProtocolEntity = TextMessageProtocolEntity(
            messageProtocolEntity.getBody(),
            to = messageProtocolEntity.getFrom())

        self.toLower(receipt)
        self.toLower(outgoingMessageProtocolEntity)

@ProtocolEntityCallback("receipt")
def onReceipt(self, entity):
    ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", entity.getType(), entity.getFrom())
    self.toLower(ack)
```

`

**Comment by BobboSA** [comment]
Have the same issue as this when trying to run the "http://www.mascal.it/public/wasend.py" application / script

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tupl                                                                                        e is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer -                                                                                         Receipt Layer - Ack Layer - Media Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e10.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

Eventually it fails with a connection timed out 110 error, I've tried E1 - E16 endpoints but still the same - In the CLI demo interface everything works 100%.

When i send a message to it before it times out i see this:

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message                                                                                                                               , letting bundled message fall through...
