### ISSUE TITLE
does yoswup 2.4.48 still working on raspberry pi ?

### ISSUE THREAD

**Issue by EiderDiaz** [tgalal/yowsup#1355]
pi@raspberrypi~/yowsup $ `python yowsup-cli registration --requestcode sms --phone 39xxxxxxxxxx --cc 39 --mcc 222 --mnc 10

`
`INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version`
![12018710_10209437110513040_879239442_o 2](https://cloud.githubusercontent.com/assets/17805140/13726406/61ef3686-e88b-11e5-827d-e64e3347b5a9.jpg)
 i already unistalled and instaled yowsup 
anyone can please help me ? :cry: :sob:

**Comment by gauravdave01** [comment]
Refer this issue: [https://github.com/tgalal/yowsup/issues/1335](1335)

**Comment by EiderDiaz** [comment]
that´s only for andriod im looking for raspberry pi  but thanks btw :+1:

**Comment by jlguardi** [comment]
@EiderDiaz you've misunderstood what android env means. It is the platform used to identify the account not the running platform. So, you can use it in raspberry pi.

**Comment by EiderDiaz** [comment]
@gauravdave01 @jlguardi i did the modifications to the code like #1335 but now show me this :cry: 
 ![12422420_10209455708457977_746108171_o](https://cloud.githubusercontent.com/assets/17805140/13767148/59ebe65c-ea2d-11e5-899e-e071b7e527ac.jpg)

**Comment by jlguardi** [comment]
You did the modifications but you made indentation errors. Tabulation is made with white spaces and not with tabs!!!

I guess this is the error.

**Comment by fbpinheiro** [comment]
Hello! I made the change and it worked! However I have problems receiving messages. for example if you get Hello World !! Can someone help me?

general: Disconnected: Connection Closed
[offline]:
/L
[offline]:
Auth: Logged in!
[554784416804@s.whatsapp.net(16-03-2016 09:32)]:[19E51555A10EF70F5FCF54ACB0F8D3]         ello World!!}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
Message 19E51555A10EF70F5FCF54ACB0F8D3: Sent delivered receipt and Read
[connected]:

[554784416804@s.whatsapp.net(16-03-2016 09:32)]:[D01D76F52255F0A3956259BD7AF7CF]         ello World!!▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
Message D01D76F52255F0A3956259BD7AF7CF: Sent delivered receipt and Read
[connected]:

[554784416804@s.whatsapp.net(16-03-2016 09:32)]:[194232E271282FBA235AF8B433BAC4]         Hello World!!OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
Message 194232E271282FBA235AF8B433BAC4: Sent delivered receipt and Read
[connected]:

**Comment by thundergreen** [comment]
You should turn on debug. What are u using? transwhat?

2016-03-16 13:37 GMT+01:00 fbpinheiro <notifications@github.com>:

**Comment by fbpinheiro** [comment]
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="4">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="554891434487@s.whatsapp.net" id="4" t="1458134489">
</iq>

Iq:
ID: 4
Type: result
from: 554891434487@s.whatsapp.net

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Felipe Barboza Pinheiro" from="554784416804@s.whatsapp.net" id="F99D594CFC210EEEF751CA81BB42C2" t="1458134490">
<enc type="msg" v="2">
3
!e▒=OܭqpT▒▒▒▒JEV▒g?▒▒"r▒▒]I"▒Յ6j▒▒▒'▒▒▒?▒EC▒▒*z▒AZ
H▒▒▒▒x▒▒▒z▒v▒h▒g▒▒▒sJ▒IZ▒
                         tE▒▒▒▒ڄ▒▒-R    (▒C
                                           7G▒▒T▒▒!+qY▒▒j▒܀y(▒R▒▒▒4
▒▒f▒▒0▒▒▒FaKƱ▒▒yO       ▒#7u?̈́▒?<▒񙫭H▒▒▒H@▒6Ǚ▒q▒.▒]▒5r▒▒}
HEX:330a210565d63d4fdcad717054c1fea1f78e4a450356e8671a3ffef722721eef8ee65d491001180222c001d585366af1c0ef27bbf6e3a03f98044543d3c82a7a19cc02415a020a48cd1a8dc2fb78f0129fd4147afa76f768e767c0ad1d0018aa3d088d734ab949015ab10b7445a48300e9dcda848b19e02d520928d9430b3747b6b05480b812212b715991d96acadc80792811f152ad90b9340cfa8af6c9cb6510f44680a4623dfbcda339a555794f09e48d2337753f00cd84b53f3cc3f199abad48bb87ab48401cf836c799c871a42ef6ba5d0fe2b635721ab9e5b47d190da39f66e3e0308b989f46614bc6b19a891b2e234b
</enc>
</message>

PuTTY
[554784416804@s.whatsapp.net(16-03-2016 10:21)]:[F99D594CFC210EEEF751CA81BB42C2]         ello World!!▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="554784416804@s.whatsapp.net" type="read" id="F99D594CFC210EEEF751CA81BB42C2">
</receipt>

Message F99D594CFC210EEEF751CA81BB42C2: Sent delivered receipt and Read
[connected]:
DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" from="554784416804@s.whatsapp.net" class="receipt" id="F99D594CFC210EEEF751CA81BB42C2">
</ack>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="5">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="554891434487@s.whatsapp.net" id="5" t="1458134539">
</iq>

Iq:
ID: 5
Type: result
from: 554891434487@s.whatsapp.net
