### ISSUE TITLE
Garbled Text from getBody method

### ISSUE THREAD

**Issue by kangwa** [tgalal/yowsup#1356]
Hi Guys,

when I call the getBody method for a text message protocol entity I'm getting back garbled/incorrect text. If I sent **Text** from a WhatsApp client I get back **Tesrxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx** from Yowsup

anyone else getting this or know how to fix it?

**Comment by jlguardi** [comment]
Have you run your account in other machine or with other user (i.e: root)?. Probably you have now different keys that the ones used at the begining of the session with the other number. So, try to remove the encryption database (axolotl.db) and restart de app.

**Comment by kangwa** [comment]
@jlguardi 
tried removing the encryption database and generating new keys but still getting the same issue after restarting.

**Comment by s-alexey** [comment]
I have solved this issue by fixing `unpadV2Plaintext` ([axolotl/layer.py](https://github.com/s-alexey/yowsup/blob/padding/yowsup/layers/axolotl/layer.py#L283)) to:
```python
    def unpadV2Plaintext(self, v2plaintext):
        # length of the left padding
        end = -ord(v2plaintext[-1])
        # first k bytes is the length of the message
        start = 0
        length = 0
        while length + start < len(v2plaintext) + end:
            length *= 127
            start += 1
            length += ord(v2plaintext[start])

        return v2plaintext[start:end]
```

**Comment by jlguardi** [comment]
@s-alexey I found some problems with your implementation. i.e: length has 7bit encoding and your proposal is not decoding it.

I've adapted your code to:
```
    def decodeInt7bit(self, string):
        idx = 0
        while ord(string[idx]) >= 128:
            idx += 1
        consumedBytes = idx + 1
        value = 0
        while idx >= 0:
            value <<= 7
            value += ord(string[idx]) % 128
            idx -= 1
        return value, consumedBytes

    def unpadV2Plaintext(self, v2plaintext):
        end = -ord(v2plaintext[-1]) # length of the left padding
        length,consumed = self.decodeInt7bit(v2plaintext[1:])
        return v2plaintext[1+consumed:end]
```

Tested up to 65535 characters.

**Comment by yniv** [comment]
@jlguardi @kangwa I'm having this exact issue since I updated the Nokia version from #1385 
Is this a solution??? can you pull request it? so i can't see the finished code?

**Comment by jlguardi** [comment]
PR #1390

**Comment by nauramutiara** [comment]
I try to remove axolotl.db and regenerate with root and without root and it's just stop after. Axolotl layer is generating keys Storing prekeys 100%. Any suggestion??

**Comment by jodersus** [comment]
the app stops after generating the keys, simply start it again (without deleting the db again!) and it should work.

**Comment by voltagex** [comment]
Is https://github.com/tgalal/yowsup/issues/1356#issuecomment-199564230 still correct? This thread is referenced everywhere, but the pull request is closed.

**Comment by MauricioAHM** [comment]
I made the fix but the problem persists

Here is the correction I made
![captura de pantalla 50](https://cloud.githubusercontent.com/assets/18564255/14694759/3b036028-0731-11e6-9825-16652b309f04.png)

**Comment by yezgar** [comment]
I have the same problem.
I tryed the solution of this post and the solution off [#1396](https://github.com/tgalal/yowsup/issues/1396) but still not working.
Can you solve this issue in the official repo?

**Comment by danleyb2** [comment]
I was working on a project using this library and i got stuck at this issue, i was waiting for someone to fix it and since no has i tried and got mine to work, this is what i did

**tested to work on python3.5** 

in `yowsup/layers/axolotl/layer.py`

replace [line 192](https://github.com/s-alexey/yowsup/blob/padding/yowsup/layers/axolotl/layer.py#L192) which is
```py
191                padded.extend(self.encodeInt7bit(len(plaintext)))
192                padded.extend(plaintext) # this is the line. replace it
193                padded.append(ord("\x01"))
```
with this
```py
    padded.extend(plaintext.encode() if isinstance(plaintext,str) else plaintext)
```
add @jlguardi fix but i had to modify it a bit to work for me
```py
    def decodeInt7bit(self, string):
        idx = 0
        while string[idx] >= 128:
            idx += 1
        consumedBytes = idx + 1
        value = 0
        while idx >= 0:
            value <<= 7
            value += string[idx] % 128
            idx -= 1
        return value, consumedBytes

    def unpadV2Plaintext(self, v2plaintext):
        print(v2plaintext)
        v2plaintext=bytearray(v2plaintext,'utf8') if isinstance(v2plaintext,str) else v2plaintext
        end = (-(v2plaintext[-1])) # length of the left padding
        length,consumed = self.decodeInt7bit(v2plaintext[1:])
        return v2plaintext[1+consumed:end]

```
#### Looks clean on the client side
![2016-05-11-11-27-07](https://cloud.githubusercontent.com/assets/9919961/15175276/2f7886fa-176e-11e6-8d56-98a49ad8bee5.jpg)

#### The garbled text though still appears on the server
![snapshot2](https://cloud.githubusercontent.com/assets/9919961/15175374/a3933bac-176e-11e6-82a2-46a3e3807a14.png)

*Hope it works for you*

**Comment by sphaero** [comment]
#1390 fixed it for me as well. I didn't need to change line 192 (python 3.4.3)

**Comment by tgalal** [comment]
Fixed

**Comment by voltagex** [comment]
What was the actual fix? Link to commit?

**Comment by jlguardi** [comment]
Use tgalal/master.
