### ISSUE TITLE
Error ,old_version

### ISSUE THREAD

**Issue by gabriel2012** [tgalal/yowsup#1357]
Hello,  i need a hand with this , when i tried to register a number , i have this error .

/yowsup-master$ yowsup-cli registration --requestcode voice --phone 5492324552718 --cc 54 --mcc 722 --mnc 07 --debug
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=54&in=92324552718&lc=GB&lg=en&sim_mcc=722&sim_mnc=007&method=voice&token=bfe0acc96691bd6aab3f9c2065ffcfc2&id=%D0%B8%E9%06%21r%E9%3E%3BTqP%08A%9BU%BC%1F%85%81
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=54&in=92324552718&lc=GB&lg=en&sim_mcc=722&sim_mnc=007&method=voice&token=bfe0acc96691bd6aab3f9c2065ffcfc2&id=%D0%B8%E9%06%21r%E9%3E%3BTqP%08A%9BU%BC%1F%85%81
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

Mi version is : 

yowsup-cli v2.0.13
Using yowsup v2.4.48

Thanks in advance.

**Comment by jlguardi** [comment]
Read #1335.
