### ISSUE TITLE
Stopped working after updating whatsapp client to 2.12.510

### ISSUE THREAD

**Issue by akhld** [tgalal/yowsup#1360]
yowsup stopped receiving private messages after updating my whatsapp client to 2.12.510 version.

**Comment by jlguardi** [comment]
Have you updated yowsup env to 2.12.510??? or official app in other number?

**Comment by akhld** [comment]
I updated the official app to the version 2.12.510 on my phone and the yowsup client I have no longer receives private messages.

**Comment by jlguardi** [comment]
Probably you changed your Id in the phone and yowsup gets invalid key authentication. enable debug and upload logs and, by the way, try to remove axolotl.db to ask again for keys.

**Comment by akhld** [comment]
Here's a screenshot of whats happening 
![image](https://cloud.githubusercontent.com/assets/5821837/13782670/10ab3940-eaee-11e5-9806-1ff3bff87dc7.png)

As you can see the last seen is 20:40 and the messages sent at 16:03 aren't delivered. Although it delivers the multimedia messages.

Also, I get this errors when I use the yowsup-cli

	Auth: Logged in!
	[connected]:ERROR:yowsup.layers.axolotl.layer:Untrusted identity!!
	WARNING:yowsup.layers.axolotl.layer:Ignoring message with untrusted identity
	ERROR:yowsup.layers.axolotl.layer:Untrusted identity!!
	WARNING:yowsup.layers.axolotl.layer:Ignoring message with untrusted identity
	ERROR:yowsup.layers.axolotl.layer:Untrusted identity!!
	WARNING:yowsup.layers.axolotl.layer:Ignoring message with untrusted identity
	ERROR:yowsup.layers.axolotl.layer:Untrusted identity!!
	WARNING:yowsup.layers.axolotl.layer:Ignoring message with untrusted identity

**Comment by akhld** [comment]
Oh I just saw someone referring the issue over here https://github.com/tgalal/yowsup/issues/1121

**Comment by akhld** [comment]
and yeah, it worked after removing the axolotl.db :)
