### ISSUE TITLE
Unable to send message to group

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1363]
With stock yowsup-develop, when I sent message to group, axolotl would raise AttributeError;

......

```
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/layer.py", line 181, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/layer.py", line 345, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
```

So I modified line 112 of yowsup/layers/axolotl/layer.py to:

```
def send(self, node):
        if node.tag == "message" and node["type"] == "text" and node["to"] not in self.skipEncJids and not "-" in node["to"]:
```

Now it bypasses axolotl when message is to group, and works... is it valid?

**Comment by nurdan** [comment]
https://github.com/tgalal/yowsup/issues/1359

**Comment by adirevelo** [comment]
Gab0 your bypass work for me tks

**Comment by relima** [comment]
@Gab0 - Awesome, it works for me too. Thanks!

**Comment by kumarshivam675** [comment]
@Gab0 - Thanks, it worked for me too...

**Comment by wcypierre** [comment]
@Gab0 it didn't worked for me unfortunately. I'm using python 2.7.6 using yowsup-develop

**Comment by Gab0** [comment]
@wcypierre Dump the error here. Also, I think axolotl-develop works best.

**Comment by wcypierre** [comment]
@Gab0 it seems like I've made a silly mistake. Group message works now, but I'll test it over the next few days to test for its stability and see how it goes.

**Comment by wcypierre** [comment]
@Gab0 it seems that I've spoken too early..... it still crashes when I try to send images over(but not everytime) 

Dump: http://pastebin.com/nd2UMRmL

**Comment by Gab0** [comment]
@wcypierre My yowsup crashes when I send text or image to a person who doesn't have me on their contact list. The error is the same you got, might be this..

**Comment by wcypierre** [comment]
@Gab0 but the weird that is that I can send some images over, but not the others, despite both having the same file extension.

Crashes yowsup: http://memesvault.com/wp-content/uploads/Funny-Okay-Meme-15.jpg
Doesn't: https://i.imgur.com/COVM3.jpg

**Comment by Gab0** [comment]
@wcypierre Are you sending them by url or got a local copy?

**Comment by wcypierre** [comment]
@Gab0 what I'm doing is that any user in the group can post the url of the image, and server will fetch the image from the url and upload it back to the group.

**Comment by Gab0** [comment]
@wcypierre I've never seen "result of uploading media has no url" error but by the traceback it seems an axolotl layer thing... will look into this..

**Comment by wcypierre** [comment]
@Gab0 I see  "result of uploading media has no url" error being thrown here  https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_media/mediauploader.py  is still under yowsup I think?

**Comment by Gab0** [comment]
@wcypierre axolotl layer is also under yowsup.. I don't know how media uploader works but by looking at it it seems that the info is traded between the media uploader and the server directly without passing through all layers as usual... try to change sleep(1) at line 108 to sleep(3) on this mediauploader.py and maybe it will work.

**Comment by wcypierre** [comment]
@Gab0 I've just tried it and it didn't worked. I'll try to debug it myself and see how it goes
