### ISSUE TITLE
"Last seen at" never upgraded

### ISSUE THREAD

**Issue by ale-rinaldi** [tgalal/yowsup#137]
Hello,
i hope not to be repetitive, but I scrolled the issues list a while and didn't find anything similar... nothing even on Google and so on, so I'm sorry to disturb you...
I use the YowsUp library in our small radio station to let listeners send us WhatsApp messages. We basically use the yowsup-cli example client with small modifications, using the "-l -a -k" switches. We never send message, only collect them to read on air.
Everything's working like a charm, but users see "Last seen at 02/06/2013" in our contact informations, which is the last time I used WhatsApp on a mobile phone.
So how can I update that time?
Thankss! :)

**Comment by jerryames** [comment]
First post here, Love Yowsup! I have the same problem. After I sign on my iPhone and switch back to Yowsup, my last seen never update, still the day and time when I switch off iPhone. It seems the code above does not work any more in Yowsup 2. I cannot find sendAvailable
