### ISSUE TITLE
How does Yowsup read the command line after one logs in

### ISSUE THREAD

**Issue by ShopriteDevelopment** [tgalal/yowsup#1372]
I have traced back through debugging all the different calls one can make from the cli (I am using PyCharm community edition)

However, if I run the following 
    demos -c config.txt -y
Then I get all the way to yowsup-cli.DemosArgParser.startCmdline =>
   stack = cli.YowsupCliStack(credentials, not self.args["unmoxie"]) 
   stack.start()

This then steps into 
  yowsup.demos.sendclient.stack.YowsupCliStack.start

From there 

    def start(self):
        print("Yowsup Cli client\n==================\nType /help for available commands\n")
        self.stack.broadcastEvent(YowLayerEvent(YowsupCliLayer.EVENT_START))

        try:
            self.stack.loop(timeout = 0.5, discrete = 0.5)
        except AuthError as e:
            print("Auth Error, reason %s" % e)
        except KeyboardInterrupt:
            print("\nYowsdown")
            sys.exit(0)

So I drill down to
    self.stack.loop(timeout = 0.5, discrete = 0.5)

My question is, how does the code now read and then process a call from the cli such as /L

Regards
Clive

**Comment by tgalal** [comment]
It's running in a different thread, see [this](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/cli.py) and [this](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.)
