### ISSUE TITLE
Whatsapp registration numbers not working  "status":"fail","reason":"old_version"

### ISSUE THREAD

**Issue by satishkkk** [tgalal/yowsup#1377]
Hello,
I am trying to register my phone using:
yowsup-cli registration -C 91 -r sms -p 9173XXXXXXX
9173XXXXXXX:-> this is my phone number:)

But I get this error:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

As I am beginner please help me out!
Help appreciated!

Thanks!

**Comment by jlguardi** [comment]
remove the '+' symbol

**Comment by satishkkk** [comment]
thanks jiguardi i removed the + sign but now i get this error


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by satishkkk** [comment]
working perfectly thanks jlguardi
