### ISSUE TITLE
Not receiving iPhone messages

### ISSUE THREAD

**Issue by gkawamoto** [tgalal/yowsup#1378]
Hello!

I'm developing a small project using your library and tonight I've stopped receiving iPhone text messages. Android seems to be still working, and images and other media are still good as well.

The Axolotl layer started raising an exception of "No valid sessionsBad mac" and deleting the ${HOME}/.yowsup/<celnumber>/axolotl.db did not work.
My bet is that something in the encryption has changed for the iPhone WhatsApp, but no clue about what it is.

Can someone help me figure it out?

Thanks in advance!

**Comment by ronromer** [comment]
For no valid sessionsbad Mac, run yowsup debug -d to see what user is the problem and just send any message test.. For the other issue I have the same problem and other users too

**Comment by gbarba** [comment]
this issue is duplicated ( #1130 ), please concentrate all scenarios and conversations in a single issue

**Comment by tgalal** [comment]
This is [not a problem](https://github.com/tgalal/yowsup/issues/1436#issuecomment-214690516)
