### ISSUE TITLE
Is there a known limit for the <groups> iq?

### ISSUE THREAD

**Issue by msshapira** [tgalal/yowsup#1380]
Or just a limit of groups that one can be a member of?
I find that the <groups> iq i recieve is constantly missing at least one or more groups - but i continue to recieve message from the missing group. After restarting - the <group> message still misses a group - but not always the same group. 
This only started happening when the number was a member of over 120 groups.
Has anyone experienced this?

**Comment by tgalal** [comment]
question to be directed to WhatsApp and not yowsup
