### ISSUE TITLE
Can't use identity registered by WART

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1381]
Hi, 

I have a number which was registered using WART, but I can't figure out how use the "id" which was provided. Can anyone help me out with this?

I tried to run the "yowsup-cli" on registration mode, so the script could wrote an "id" file that I can edit with the right value, but I had no success either.

I'm running python on a Windows enviroment.

**Comment by jlguardi** [comment]
The Id is used just for registration but not for login. 

Password and phone obtained with wart should work wit h yowsup.

**Comment by luizlzz** [comment]
@jlguardi 

It's exactly what I was trying to do, without success. Take a look:

![wart](https://cloud.githubusercontent.com/assets/17954946/13959719/03c2f4de-f034-11e5-837a-84a0dc521e16.png)

![wart2](https://cloud.githubusercontent.com/assets/17954946/13959721/0601790a-f034-11e5-878d-5dcbf065f9c6.png)

Am I doing something wrong?

Thank you for the help.

**Comment by rami-dabain** [comment]
Can't even register through yowsup itself, registration goes fine, get the password, and then it disconnects as not auth-ed

**Comment by luizlzz** [comment]
I just tried on a Linux environment, still got no success... Can't really figure out what is the problem. I would really appreciate if someone could help me with that.

**Comment by jlguardi** [comment]
Read #1384
