### ISSUE TITLE
Error getting the key

### ISSUE THREAD

**Issue by M4STERANGEL** [tgalal/yowsup#1382]
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

This error happens me every time that I enter my phone to get the key

**Comment by jlguardi** [comment]
Read #1335 and close this issue.

**Comment by M4STERANGEL** [comment]
Not working.
The same error

**Comment by M4STERANGEL** [comment]
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
M4STER_ANGEL@vps251263:~/yowsup$

* * *

Now this

**Comment by bdbais** [comment]
https://github.com/tgalal/yowsup/pull/1336/files
