### ISSUE TITLE
Is there a way to inject messeges to send on a looping stack

### ISSUE THREAD

**Issue by tawanda** [tgalal/yowsup#1383]
As i see it i can

1) loop and get messages and reply to them by echoing back or using a sting i want

2) i can connect send messages and disconnect

i cant do both at the same time

how do i inject messages i want to send whilst a receiving loop is running, if i try it now it disconnects the running loop to send if i open another terminal for instance

**Comment by bastronaut** [comment]
Read the Sample Application instructions:
https://github.com/tgalal/yowsup/wiki/Sample-Application

basically, have an inject layer listen to an onMessage and prepare a response within the stack loop

**Comment by tawanda** [comment]
But that means i can only reply to messages, whereas i would like to send a message to a different number whilst i'm receiving messages from another numbers. or maybe just have my loop listen for incoming messages and still be able to send an outgoing message if no messages are coming in, without disconnecting the loop

**Comment by bastronaut** [comment]
You can simply build your logic to send messages in an injected player. For instance, in the sample echo client you can find something similar to:

```
outgoingMessageProtocolEntity = TextMessageProtocolEntity('message to send',
                to = messageProtocolEntity.getFrom())
self.toLower(outgoingMessageProtocolEntity)
```

If you want to send it to other people, just change the 'to' field. 

There's no reason that you have to do this in onMessage. If you want to send messages without messages coming in, simply build your logic outside of onMessage on another event

**Comment by tawanda** [comment]
Thanks for the response @bastronaut , however there is a problem with that because i can change the to field and the text here

```
outgoingMessageProtocolEntity = TextMessageProtocolEntity('message to send',
                to = messageProtocolEntity.getFrom())
self.toLower(outgoingMessageProtocolEntity)
```

and i can put that that in any event i want ..true, but once i call

```
stack.loop()
```

I cant send other messages, i would have to stop the loop and update my outgoing message and number and then start the loop again. because once you call stack.loop() you cant execute more code


Thats why i was thinking if there is an event that ticks every 5seconds or something i could do something like


```
onTick(self):
    messeges =  cache.get('messeges_to_send'')
    if messeges:
          outgoingMessageProtocolEntity = TextMessageProtocolEntity(messege.content,  to = messege.to)
          self.toLower(outgoingMessageProtocolEntity)
          cache.delete('messeges')
```

and then everytime i want to send a message i can run from another script

`cache.set('messeges', ('0000000@s.whatsapp.net', 'hello world '))`

**Comment by bastronaut** [comment]
What I've done is have my messages and receivers in a database. Then, in an injected layer, I set an onEvent listener. You can propagate your event (on a 5 second time if that's what you wanted), check if the event matches, get the messages/receivers from my database and process them.

```
def onEvent(self, layerEvent):
    if layerEvent.getName() == 'youreventname':
        messages = db.getMessagesToSend()
        if messages:
             outgoingMessageProtocolEntity = ....
```

Hope it helps.

**Comment by jodersus** [comment]
You could also use a Queue ([https://docs.python.org/2/library/queue.html#queue-objects])

**Comment by tawanda** [comment]
Awesome stuff, thanks guys.

**Comment by Jufik** [comment]
@tawanda I'm looking to do something similar, could you please provide some sample code ?

Another question I have is how to break loop once it's called?

**Comment by Jufik** [comment]
@tawanda > Thanks for your help.
I found out solutions has heavily been influenced by the demos found in the repo'.

Who needs to loop over an array when you can send your stuff live? 
My need is to send a message when I need it, and chose to use Threadin.

**Create your stack subclassing Thread.**
Notice the _send_message_ function which send an event, and  and the _run_ function required for threading.

```
# -*- coding: utf-8 -*-
from yowsup.stacks import YowStackBuilder
from recieve_layer import RecieveLayer
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from threading import Thread
class YowsupRecieveStack(Thread):
    def __init__(self, credentials, encryptionEnabled=True):
        """
        :param credentials:
        :param encryptionEnabled:
        :return:
        """
        Thread.__init__(self)
        stackBuilder = YowStackBuilder()

        self.stack = stackBuilder\
            .pushDefaultLayers(encryptionEnabled)\
            .push(RecieveLayer)\
            .build()
        self.stack.setCredentials(credentials)

    def run(self):
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
        self.stack.loop()

    def send_messages(self, phone, message):
        self.stack.broadcastEvent(YowLayerEvent('send_message', message=message, phone=phone))
```

**Handle the _send_message_ (or Whatever the name you'll choose) event in your layer:**
```
class RecieveLayer(YowInterfaceLayer):
    def __init__(self):
        super(RecieveLayer, self).__init__()
        self.ackQueue = []
        self.lock = threading.Condition()

    def onEvent(self, yowLayerEvent):
        if yowLayerEvent.getName() == 'send_message':

            message = yowLayerEvent.getArg('message')
            phone = Jid.normalize(yowLayerEvent.getArg('phone'))
            print "%s %s"%(message,phone)
            messageEntity = TextMessageProtocolEntity(
                message,
                to=phone)

            # append the id of message to ackQueue list
            # which the id of message will be deleted when ack is received.
            self.ackQueue.append(messageEntity.getId())
            self.toLower(messageEntity)
```

**Usage**
Create your layer instance, and _start_ it.
Whenever you want, _bam_: you can send a message using "send_message"
Note I use a time.sleep to make sure _success_  happens before I send messages 
```
recieving_stack = YowsupRecieveStack(credentials)
recieving_stack.start()

time.sleep(1)
recieving_stack.send_messages('33607235671', 'World')
```

**Comment by tawanda** [comment]
@Jufik but you can only do this in the file you are creating your instance on, if you have


```
def run():
  recieving_stack = YowsupRecieveStack(credentials)
  recieving_stack.start()

  time.sleep(1)
  recieving_stack.send_messages('33607235671', 'World')
```

after you call `run()`

you no longer have access to the instance outside of that function, what if after an hour you have messages to send? You have to call your run() function again, and it will kill the other instances thread since you cant have 2 whatsapp loops running at the same time. Is there something im missing here ?

**Comment by Jufik** [comment]
@tawanda I'm planning to write an article about this, I'll give you the reference.

**Comment by pk299** [comment]
@tawanda @Jufik can you guys help me to use it with django websocket? I need to build a real time chat app with whatsapp. yowsup-cli is working perfect in my linux system but don't know how to use it with django channels and websocket. If you already did this please help me
