### ISSUE TITLE
yowsup stops working every couple weeks

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1392]
yowsup works fonde but stops working for no reason after a couple weeks/month.
What can I do to solve that problem?
# yowsup-cli demos -c conf_2 -e

Authentication Error: not-authorized

@Registration:
# yowsup-cli registration -c conf_2 -r sms

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version

**Comment by x23piracy** [comment]
Close this and read https://github.com/tgalal/yowsup/issues/1387

**Comment by kw005** [comment]
I did the file changes and installed it. (https://github.com/tgalal/yowsup/pull/1336/commits/8ab14dc8a1bd4d7d1776111ec39f7e08184214d2) Still does not work.


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by kw005** [comment]
still getting 
Authentication Error: not-authorized

**Comment by shedokan** [comment]
@kw005 Try https://github.com/tgalal/yowsup/issues/1387#issuecomment-200449001 Let me know if it works for you :)

**Comment by kw005** [comment]
yes, after changing the _TOKEN and _VERSION it worked.A stable version should be upload though. The workaround here and there is horrible.
