### ISSUE TITLE
yowsup blocket my 4 phones 

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1393]
i got 

Authentication Error: not-authorized

and after my phone is blocket why happends this

**Comment by kw005** [comment]
got the same error. I don't know. Every couple weeks I got the same.

**Comment by x23piracy** [comment]
Close this read https://github.com/tgalal/yowsup/issues/1387

**Comment by yniv** [comment]
@minimaldev @kw005 look at the pull requests. WhatsApp changed the token for S40.

**Comment by x23piracy** [comment]
@yniv after that its working again? Do you have link?

**Comment by yniv** [comment]
@x23piracy it works but there is no support for image messages. check the last pull requests from @jlguardi

**Comment by kw005** [comment]
@yniv: I did change the files (https://github.com/tgalal/yowsup/pull/1336/commits/8ab14dc8a1bd4d7d1776111ec39f7e08184214d2), re-installed it, and I get


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes


How to solve that issue?

**Comment by minimaldev** [comment]
no no i used wart for the get the password for my phone but in two days he ban me 4 phones and i make the change for the issue and update the platform but the phone is blocket
