### ISSUE TITLE
No support for receiving Image messages with yowsup

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1394]
As i understand now, currently there is no support for receiving image messages with yowsup!
after the S40 token change, now we're getting encrypted images.
please update here if someone is working on this, or any progress regarding this issue. because without this support now this lib is pretty much useless...

**Comment by yniv** [comment]
i've seen that @tgalal has commited some changes regarding this in wa16. did someone tried it?

**Comment by cfenollosa** [comment]
Chat-API has the same problem. Given that yowsup is a port of Chat-API, I wouldn't count on getting that fixed soon: https://github.com/mgp25/Chat-API/issues/1750

**Comment by mgp25** [comment]
@cfenollosa image encryption/decryption is already implemented in Chat API and its fully working. I didn't enabled the encryption/decryption to groups yet, but its working and its just adding 1 more line of code.

Probably in about weeks (no ETA), we'll release protocol 2.0 with full document support and more features. I would recommend to translate to python what is already done in Chat API.

Regards

**Comment by stevie86** [comment]
Thanks, receiving Images works now!

**Comment by yniv** [comment]
@stevie86 how does it work? what have you did?

**Comment by antoniespinosa** [comment]
@stevie86 What have you did?

**Comment by cgraefe** [comment]
@stevie86 Please share with us if you got encrypted images to work.

**Comment by stevie86** [comment]
Sorry, it doesn't work after all :(

**Comment by jlguardi** [comment]
I've working version in jlguardi/master (at least I downloaded 5 hours ago several encrypted/unencrypted images). Could you check if you have this code working? Could you post logs?

**Comment by cgraefe** [comment]
@jlguardi I'm already on it, looks promising so far. Thanks for you efforts!

**Comment by jlguardi** [comment]
Remembe that message.getMediaContent() returns unencrypted (if required) image. If you use cli, it is made internally.

**Comment by cgraefe** [comment]
@jlguardi Thanks for the reminder, I would have missed that. Downloading and decrypting images does indeed work well on you master branch. I seem to be having problems with audio and location messages now though. I'll investigate further and will open separate issues on your fork if need be and you don't mind.

**Comment by SpEcHiDe** [comment]
Hi. Could you please explain how to decrypt the downloaded image?

**Comment by tgalal** [comment]
Fixed by 5ac5c3c1f056b389d3b4a60416bcaa264cf9bdb1
