### ISSUE TITLE
Message body corrupted

### ISSUE THREAD

**Issue by bdbais** [tgalal/yowsup#1396]
I'm not sure whats happend but now I have this effect:
```

Message:
ID: 7AFF428664A4C084B9BD6000C21DD1
From: 32393934449@s.whatsapp.net
Type:  text
Timestamp: 1458750438
Body: HelloSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
```

all messages come with different random repeated last letter...

**Comment by jlguardi** [comment]
Apply #1390

**Comment by bdbais** [comment]
Message:
ID: E326A3098F24E26765BD02511F7DC9
From: 32393934449@s.whatsapp.net
Type:  text
Timestamp: 1458752809
Body: ipext▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

**Comment by bdbais** [comment]
Probably wrong place, I'm doing it again.

**Comment by bdbais** [comment]
It works, now message is cleaned.

**Comment by ronromer** [comment]
@jlguardi  work for me also ... thanks

**Comment by jodersus** [comment]
@bdbais  pls close this issue if all is fixed

**Comment by yezgar** [comment]
Hi,

I still have this problem.
I try the fix but it not work. The problem appears only for some message, not all (always aleatory)
Can you solve this issue in the official repo?

Tnks

**Comment by tgalal** [comment]
Fixed
