### ISSUE TITLE
onPong example

### ISSUE THREAD

**Issue by bdbais** [tgalal/yowsup#1397]
Anybody can help me to create a onPong event example?
I want to use it for check activity to do on database.

I tried to add on my layer.py based on Echolayer example:

class EchoLayer(YowInterfaceLayer):

      def onPong(self. entity):
             print("Pong received")

but nothing happend, miss something I suppose.
any suggest ?

**Comment by jodersus** [comment]
Have a look at #1181 and see if you can work something from there.
You'll have to set callbacks for Events which, to the best of my knowledge, is not setup in the current master branch.

**Comment by bdbais** [comment]
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="9">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="XXXXXXXXXXXXXX@s.whatsapp.net" id="9" t="1459267642">
</iq>


On debug mode I can see this kind of events but I can't handle it.


    @ProtocolEntityCallback("result")
    def onPing(self, entity):
        print "Ping received"

**Comment by bdbais** [comment]
on network layer:

/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py


added:
```
    EVENT_STATE_PING_OK    = "org.openwhatsapp.yowsup.event.network.pingok"
    EVENT_STATE_PING_KO    = "org.openwhatsapp.yowsup.event.network.pingko"
```
   ------

on:  /usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_iq/layer.py"

----

    def waitPong(self, id):
        self._pingQueueLock.acquire()
        self._pingQueue[id] = None
        pingQueueSize = len(self._pingQueue)
        self._pingQueueLock.release()
        self.__logger.debug("ping queue size: %d" % pingQueueSize)
        if pingQueueSize >= 2:
            self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_PING_KO, reason = "Ping Timeout"))
            self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_DISCONNECT, reason = "Ping Timeout"))
        else:
            self.__logger.debug("starting ping thread success.")
            self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_PING_OK, reason = "Ping Received"))

------

now I must to trap that event and call my function and I reached my goal....

**Comment by bdbais** [comment]
Any suggestion?

**Comment by bdbais** [comment]
I'm trying to keep event:


```
    def onEvent(self, layerEvent):
        if layerEvent.getName() == YowNetworkLayer.EVENT_STATE_DISCONNECTED:
            self.connected = False
            exit(1)
        elif layerEvent.getName()== YowNetworkLayer.EVENT_STATE_PINGKO:
            print("Ping KO Received!")
        elif layerEvent.getName()== YowNetworkLayer.EVENT_STATE_PINGOK:
            print("Ping OK Received!")

```

where I can to put this code ?

**Comment by bdbais** [comment]
@EventCallback(YowNetworkLayer.EVENT_STATE_CONNECTED)
    def onStateConnected(self,layerEvent):
        print("Connected: %s" % layerEvent.getArg("reason"))

    @EventCallback(YowNetworkLayer.EVENT_STATE_DISCONNECTED)
    def onStateDisconnected(self,layerEvent):
        print("Disconnected: %s" % layerEvent.getArg("reason"))

    @EventCallback(YowNetworkLayer.EVENT_STATE_PING_KO)
    def onEvent(self, layerEvent):
        print("Ping KO Received!")

    @EventCallback(YowNetworkLayer.EVENT_STATE_PING_OK)
    def onEvent(self, layerEvent):
        print("Ping OK Received!")
