### ISSUE TITLE
message to groups sent, but never arrives ERROR 401

### ISSUE THREAD

**Issue by gcat000** [tgalal/yowsup#1402]
i have a trouble:
when i sending a message to group (with -M key), message sent succesfully, but never arrives in chat ;(

otherwise, private messages sending ang arriving OK with and without '-M' key

yowsup-cli demos -c /Users/gcat/yowsup.cfg  -s 792xxxxxxx/792xxxxxxx-xxxxxxxxxx 'test' -M
INFO:yowsup.demos.sendclient.layer:Message sent

without '-M' key - 
AttributeError: 'NoneType' object has no attribute 'getChild'

i use android env (env_android.py)
_VERSION = "2.12.440"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"

and in warequest.py:
from yowsup.env import AndroidYowsupEnv
CURRENT_ENV = AndroidYowsupEnv()

may be i forgot to do somthing? like to make a changes in some other files, like **init.py**, for example? help me please!

**Comment by gcat000** [comment]
debug argument shows an error:
DEBUG:yowsup.layers.logger.layer:rx:
<ack id="1458920974-1" t="1458920974" class="message" from="792xxxxxxx/792xxxxxxx-xxxxxxxxxx@g.us" error="401">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

how to fix it?

**Comment by jadariman** [comment]
Hello gcat00 

I am try 

./yowsup-cli demos -d -c yowsup-cli.config -M -s 5xxxxxxxxxxx-5xxxxxxxxxxx "Prueba"

Next debug yowsup send me 

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1460578089" error="401" from="5xxxxxxxxxx-5xxxxxxxxxx@g.us" class="message" id="1460578090-1">
</ack>

this same your problem ... Can you fix this problem ?
