### ISSUE TITLE
[[[[[[ DEV CHANNEL ]]]]]]

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1406]
This yowsup issue takes a lot of traffic and weird conversation flows. I would like to offer a jabber channel to discuss every changes in the yowsup to make it more sufficent
Herefore I would like to invite every guys to a central channel on my server to discuss it there instead of opening 10000 issues here on github. Like this we can work all together and put together all informations and discuss.

What do u think about this?
the channel has already been created
# 

PLEASE FEEL FREE TO JOIN!!!!
## JABBER
# yowsup@chat.noip.me
## IRC
# #yowsup on freenode

Would highly appreciate to welcome you there!

Greetz
ThUnD3r|Gr33n

**Comment by chenwayne** [comment]
Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

**Comment by yniv** [comment]
i entered #yowsup on freenode but no one is there. where is the DEV channel?

**Comment by jodersus** [comment]
Hi,
I'm trying to connecto to your jabber chat, but I'm new to it. Can you help? using pidgin
Ta,
A

**Comment by thundergreen** [comment]
Officially there's no dev channel yet.there's one on gitter. Would love the
active devs could say something

Thorsten Fröhlich
Am 27.03.2016 12:50 schrieb "Alex" <notifications@github.com>:

**Comment by jlguardi** [comment]
I join yowsup@chat.noip.me but is always empty (with @jodersus config)

**Comment by mgp25** [comment]
I do not recommend any public channel. There are some stuff that should be private
