### ISSUE TITLE
[wa16] no message reception

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1408]
With stock wa16 branch install, I can send message normally, but when message comes, it just doesn't appear, with no crash. Group and contact messages.. Anyone got this?

**Comment by rokha** [comment]
@Gab0 same here while working on #1407 and going via working on wa16 branch

**Comment by Gab0** [comment]
The server is actually not sending the messages... I checked out.. may be some Ack issue

**Comment by jlguardi** [comment]
Without logs is imposible to know what is really happend. I guess you are skiping encrypted group messages but no ack is sent. After 5 pending acks connection is closed and other effects have been reported. 
Post debug logs from yowsup-cli (don't use your own code to avoid other causes)

**Comment by Gab0** [comment]
@jlguardi The logs are not helpful, there is no crash nor extraneous movements... I'm still connected and receive the periodic 'result' IQ, but the server simply doen't send any more messages. After this, I patched the network layer to show incoming bytes, and and it shows only the bytes of the IQs.
The problem started just after I got to use the wa16 branch, maybe you could try it...

**Comment by cfenollosa** [comment]
I am affected by this too. Check out #1409

**Comment by eduardobento** [comment]
Some debugs:

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Eduardo Bento" from="554799643507@s.whatsapp.net" id="712E59078EBE63F27D" t="1459101876">
<enc type="msg" v="1">
3
!²§}½;[[░09ë]RnË\(ZbAyÕ╠q_Ö,┴h§uÐ
\000"êL┬
Õp4.R#¬KÔ ¡╝> º╬┤ß©
HEX:330a2105fdf57dab3b5b155bb03039895d526ed35c285a624179e5cc715f992cc168f57510d11c18002210884cc21de570342e5223aa4be2ffadbc3e20a7ceb417e1b8
</enc>
</message>
```

* Above the recent of a message, for me this happens only in enc type=msg.

```
ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad mac!
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="554799643507@s.whatsapp.net" type="retry" id="712E59078EBE63F27D">
<retry count="1" v="1" t="1459101876" id="712E59078EBE63F27D">
</retry>
<registration>
8└Ê
HEX:3804c0d2
</registration>
</receipt>
```

* Look, yowsup trows exception No valid sessions and send retry

```
DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="554799643507@s.whatsapp.net" class="receipt" id="712E59078EBE63F27D">
</ack>
```

* This is the ack os retry received

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Eduardo Bento" from="554799643507@s.whatsapp.net" id="712E59078EBE63F27D" t="1459101876">
<enc count="1" type="msg" v="1">
3
!²§}½;[[░09ë]RnË\(ZbAyÕ╠q_Ö,┴h§uÊ
\000"·Û└¥ÜVÂ¶øƒ§Ï0¿ìz
ÃjÐ
HEX:330a2105fdf57dab3b5b155bb03039895d526ed35c285a624179e5cc715f992cc168f57510d21c18002210fa1beac0be9a56b67ff49b9ff5d80530a88d7a1dc78d6ad1
</enc>
</message>
```

* Here the message was sent again.

In axlotl\protocol\whispermessage.py:

```
        if ourMac != theirMac:
            raise InvalidMessageException("Bad Mac!")
```

The verification seems that 'outMac' is different os 'theirMac'. 
When the yowsup send a message to this contact, he store a valid session, so the receipt is ok. But if I delete axolotl.db, this session is lost and the problem come back.

**Comment by Gab0** [comment]
My debug is similar, replacing `No valid sessionsBad mac!` to `No such signedprekeyrecord! 9348 `, maybe because I deleted .db files; After I connect, I get the same five messages, and then no more, still being able to normally send a message. Must be an ack problem.

**Comment by jodersus** [comment]
Have you updated python-axolotl from tgalal's repository?

**Comment by jlguardi** [comment]
@jodersus yes from  https://github.com/tgalal/python-axolotl/tree/develop

De: Alex
Enviado: lunes, 28 de marzo de 2016 11:40
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi
Asunto: Re: [yowsup] [wa16] no message reception (#1408)


Have you updated python-axolotl from tgalal's repository?

---

**Comment by thundergreen** [comment]
Hiw to update the axolotl ? By installing from scratch ?

Thorsten Fröhlich
Am 28.03.2016 11:40 schrieb "Alex" <notifications@github.com>:

**Comment by jodersus** [comment]
yeah, clone the repository @jlguardi mentions, and python setup.py install with admin privies.

**Comment by naamakat** [comment]
Is there any difference between the develop and the master branch of  https://github.com/tgalal/python-axolotl/tree/develop? It seems the same.

**Comment by jodersus** [comment]
yeah, github says they're the same

**Comment by jlguardi** [comment]
I've removed develop now which was the same than master.

De: naamakat
Enviado: lunes, 28 de marzo de 2016 11:47
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi
Asunto: Re: [yowsup] [wa16] no message reception (#1408)


Is there any difference between the develop and the master branch of  https://github.com/tgalal/python-axolotl/tree/develop? It seems the same.

---

**Comment by eduardobento** [comment]
pkmsg type messages with normal receives...
msg type messages with no valid session problem...

**Comment by bdbais** [comment]
I have these warnings:
everytime I receive a message:
WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...

everytime I send a message:
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)

after some tries this appear and "client received flag appear" but not message I sent.

WARNING:yowsup.layers.axolotl.layer:Too many retries!! Going to send the delivery receipt myself!

**Comment by bdbais** [comment]
Message delivered 4 times, I have 4 copies on db.
And reply never sent.

**Comment by tgalal** [comment]
wa16 is still WIP

**Comment by flayla** [comment]
I've noticed that it's character related, try using only english characters in the message

**Comment by Gab0** [comment]
My whatsapp account still doesn't receive messages, with any of the repos. Just saying for community acknowledgement xd.

**Comment by naamakat** [comment]
@Gab0 same here ...

**Comment by Gab0** [comment]
@naamakat Can you try to re-register and see what happens?
