### ISSUE TITLE
Can any body help me with register ?

### ISSUE THREAD

**Issue by deounix** [tgalal/yowsup#1410]
I can't register using YowSup I get this error -->

```
 --requestcode voice
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
```

Is there patch or something to fix this error ? thnx.

**Comment by jlguardi** [comment]
Are you using a mobile line? Landlines or most of virtual lines don't work. 
If it's a mobile, try to set mnc/mcc.

**Comment by kantorv** [comment]
you can register using 3rd party tools.
1) get genymotion, then run some image (e.g. galaxy 5)
2) download official apk (https://www.whatsapp.com/android/), drag it to the emulator, register your number (ask for voice code)
3) recover password like described here: http://www.digitalinternals.com/security/extract-whatsapp-password-android/374/
4) profit
