### ISSUE TITLE
I have tried all versions, they all have this error, how can I fix? Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

### ISSUE THREAD

**Issue by chenwayne** [tgalal/yowsup#1413]
Error message is: Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

**Comment by jodersus** [comment]
are you using yowsup-cli or your own app?
I reckon the issue is in your stack build.

**Comment by tgalal** [comment]
This is not an error, and should be gone anyways if it was in yowsup-cli and you update to latest  version
