### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by jmmartinez84** [tgalal/yowsup#1414]
I've lost my yowsup password. It seems that in this moment there is not so easy to get a new one.
I have a yowsup  authentication debug log (encrypted content)  and my axolotl.db file. Could be possible, with that information recover my lost account password?

Thanks in advance

**Comment by mgp25** [comment]
The only thing you need is the identity. Try requesting the sms code using that identity, and you'll get a new password

**Comment by jmmartinez84** [comment]
@mgp25 What do you mean with identity? phone number? I tried do register but yesterday but I was getting old_version error (S40 device)

**Comment by jlguardi** [comment]
@jmmartinez84 read https://github.com/mgp25/Chat-API/ where where clearly explained. 
A used updated sw version of yowsup in jlguardi/yowsup

**Comment by Dimelay** [comment]
@jmmartinez84 
Update yowsup/env/env_s40.py

```
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.13.39"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1456529096701{phone}"
    _AXOLOTL = True
```

**Comment by jmmartinez84** [comment]
Done! thank you so much! :smile:
