### ISSUE TITLE
Status: fail and Reason: old_version

### ISSUE THREAD

**Issue by bossonaro** [tgalal/yowsup#1417]
Hello,
I have a problem. My yowsup app ran until last week and after that, it's stoped.
When I tried connect, I receive this:

```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version
```
My version:
```
yowsup-cli v2.0.13
Using yowsup v2.4.48
```
How to do?
Thank you
Adriano

**Comment by harpreetrekhi** [comment]
Try in andriod environment:

wget https://github.com/jlguardi/yowsup/archive/Android_2.12.440.zip
unzip Android_2.12.440.zip
cd yowsup-Android_2.12.440
sudo python setup.py install

Though I got same error and used the above procedure to update the yowsup to android environment but still I am unable to login as I am getting authentication error even though re-registration is successful.. Stil waiting for its solution

**Comment by jlguardi** [comment]
Please close this duplicated issue and read all others.

**Comment by thundergreen** [comment]
I guess Wiki is maintained ?

Thorsten Fröhlich
Am 28.03.2016 22:08 schrieb "jlguardi" <notifications@github.com>:
