### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by Aydar77** [tgalal/yowsup#1420]
Hi guys, recently stopped sending messages.
here comes the error

> WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
> /usr/local/share/zabbix/alertscripts/yowsup-master/yowsup/demos/sendclient/stack.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
>   print("Authentication Error: %s" % e.message)
> Authentication Error: not-authorized

I need to change?

__version__ = "2.0.13"

**Comment by Aydar77** [comment]
What should I do? update to the latest version?

**Comment by tgalal** [comment]
Updating to latest  version should fix the problem
