### ISSUE TITLE
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure Authentication Error: not-authorized

### ISSUE THREAD

**Issue by sunny1974** [tgalal/yowsup#1421]
Hi guys,
Got below exception and unable to send messages.

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by moscheIT** [comment]
Hi 
edit your file yowsup-master/yowsup/env/env_s40.py

very this two line
_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073{phone}"
_VERSION = "2.14.21"

and recompile all 
for me work

**Comment by tgalal** [comment]
Updating to latest  version should fix the problem

**Comment by pippopippo69** [comment]
HI,

changed /home/pi/yowsup/yowsup/env/env_s40.py as for moscheIT indications ...and ... no joy !

DEBUG:yowsup.env.env:Current env changed to s40 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x760b6330>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x76202f90>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="XXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
??H???{
       ??=?Z??!/
HEX:83f848869afb7b1a0b801b89dd3dc05a8891212f
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
+,?A?߆?ZT"@?&??,.B?Au?󢹊+m??9??????R?XdJ?eܖ?????N?j.u?(?
HEX:2b032ca041a3df8605975a542240f7268f029c2c2e421fb24175dbf3a2b98a01012b6da9fc391915edc1a6b793eb52d9089858644ac465dc96afdae5e0db4ee36a2e75d928d5
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized
