### ISSUE TITLE
general : login failed , reason : not- authorized

### ISSUE THREAD

**Issue by maroscenter** [tgalal/yowsup#1425]
I salute you did everything as described and it was working well , I managed to send message and recivi from my Raspberry Pi, but several days ago is giving me this error (general : login failed , reason : not- authorized ) , saw some forum says you need to update the yowsup but not how it is if you know anything of this error PLEASE HELP YOUR GOOD SERIOUS thanks

**Comment by OneMoreRaspi** [comment]
I have the same problem.
And when I start the registration again, I get 
status: fail
reason: old_version
I also repeated the whole installation process and came to the same result.
Thanks for any helpful hints!
Christoph

**Comment by maroscenter** [comment]
I also installed from 0 the Raspbian system and try to register several different numbers and even continued with this error, if someone has the solution please share it pls.

**Comment by drecchia** [comment]
Same problem here.

**Comment by bkenny** [comment]
+1

**Comment by jlguardi** [comment]
The solution is shared!!! Read closed and open issues searching "old-version" and close this re-duplicated issue.

**Comment by moscheIT** [comment]
Hi 
edit your file yowsup-master/yowsup/env/env_s40.py

very this two line
_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073{phone}"
_VERSION = "2.14.21"

and recompile all 
for me work

**Comment by OneMoreRaspi** [comment]
Thanks moscheIT, this worked for me as well!

**Comment by drecchia** [comment]
works for me, thanks.

**Comment by tgalal** [comment]
Updating to latest  version should fix the problem
