### ISSUE TITLE
registration failed because of an "old version"

### ISSUE THREAD

**Issue by flori8029** [tgalal/yowsup#1427]
Hello community,
today I installed yowsup and all of its components. I made following registration file (config.yowsup):
```
cc=49
phone=493652059776
id=
password=
```
When I want to register with the following code...:
`python yowsup-cli registration -c config.yowsup -r voice`
...this message appeared:
```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version
```
After that I reinstalled yowsup but it appears again. I downloaded the files from this (official) website.
I would be very kind if you could help me with my problem.

Greetings
flori8029

**Comment by mgp25** [comment]
@flori8029 let me be your guide here. Have you noticed this part of github's page?

![search](http://s23.postimg.org/5mxyhnetn/image.png)

Oh wow, and with an only string query look what we have found:

![result](http://s8.postimg.org/838s6swrp/image.png)

Awesome, right? 

Now, i recommend you to close this issue, and search in the recently related issues. Hope you find this useful

Regards

**Comment by moscheIT** [comment]
Hi 
edit your file yowsup-master/yowsup/env/env_s40.py

very this two line
_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073{phone}"
_VERSION = "2.14.21"

and recompile all 
for me work

**Comment by tgalal** [comment]
Update to latest yowsup version
