### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by giulianopoggi** [tgalal/yowsup#1432]
the last version no  problem for registration
send messages problem
this log
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/opt/local/scripts/yowsup/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/opt/local/scripts/yowsup/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/opt/local/scripts/yowsup/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/opt/local/scripts/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/opt/local/scripts/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/opt/local/scripts/yowsup/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/opt/local/scripts/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/opt/local/scripts/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/opt/local/scripts/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/opt/local/scripts/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/opt/local/scripts/yowsup/yowsup/layers/axolotl/layer.py", line 130, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/opt/local/scripts/yowsup/yowsup/layers/__init**.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/opt/local/scripts/yowsup/yowsup/layers/axolotl/layer.py", line 188, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/opt/local/scripts/yowsup/yowsup/layers/axolotl/layer.py", line 628, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "build/bdist.linux-armv6l/egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/opt/local/scripts/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 19, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/opt/local/scripts/yowsup/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by msshapira** [comment]
same occurs for me. 
I noticed that moving to a different machine solved that

**Comment by chenwayne** [comment]
@msshapira I got the same problem, can you elaborate how to fix?

**Comment by msshapira** [comment]
Not really, the same code works fine under Linux but shows the above
exception in Windows

**Comment by chenwayne** [comment]
@msshapira  my bot is also running on Linux, but got this error as well

**Comment by meyerpr** [comment]
I get the same error message running on a Raspian Wheezy

**Comment by giulianopoggi** [comment]
there is no one else who can help me about this error.
I use a raspberry with Raspbian Jessie Lite distribution

**Comment by thundergreen** [comment]
@giulianopoggi i also run this setup.. maybe u use traswhat and spectrum2? The transport starts very well and then after a couple of time it breaks down with several error messages. I'm wondering why it works before and then it crashes.. i won't send any logs here cause they have aleady been sent 100 times :)

**Comment by giulianopoggi** [comment]
And 'at least two years that I use from my raspberry yowsup server to send alarms and more, I've never had a problem if the final date that solved with a new recording. The debian distribution I use is Raspbian Jessie Lite. I tried again today with the latest versions.
   proceed in the following way:
-drainage the new version
   yowsup-cli v2.0.15
   yowsup v2.4.102
-remove directory /root/.yowsup
-install python setup.py install
- recording of a real number (mother phone) without problems
-Send message and shows the usual error
    TypeError: 'NoneType' object is not iterable
Today I tried deleting repeatedly axolotl.db file
    rm /root/.yowsup/393336243xxx/axolotl.db
The third or fourth time that clear  the file is finally are able to download
I think the key to reaching 100%.
From that moment the messages are sent ............
hurray

**Comment by meyerpr** [comment]
Found a work around at least... 
`sudo pip uninstall python-axolotl`

And then add -M to the 'yowsup-cli demos' call to disable encryption. This works for me.

**Comment by giulianopoggi** [comment]
is not true, it does not work again

**Comment by giulianopoggi** [comment]
sudo pip uninstall python-axolotl 
  done
And then add -M to the 'yowsup-cli demos' call to disable encryption. This works for me.
done
Work again   grazie................evviva

**Comment by flayla** [comment]
uninstalling does not work for me
`Successfully uninstalled python-axolotl
root@kali-flayla:/home# yowsup-cli demos -l 65X6433X62:XXXXXXXXbGHKNFUonx+JRAevJJc= -e -d -M
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 229, in process
    self.startEcho()
  File "/usr/local/bin/yowsup-cli", line 258, in startEcho
    from yowsup.demos import echoclient
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/echoclient/__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/echoclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer 
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import DocumentDownloadableMediaMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/protocolentities/__init__.py", line 2, in <module>
    from .message_media_downloadable import DownloadableMediaMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 10, in <module>
    from axolotl.kdf.hkdfv3 import HKDFv3
ImportError: No module named axolotl.kdf.hkdfv3
root@kali-flayla:/home# 
`

**Comment by jlguardi** [comment]
You need axolotl module. Download from tgalal/python-axolotl nrach develop and install it. Don't use -M in cli due to many messages will be lost.

**Comment by flayla** [comment]
I'm using your master branch with its axolotl module. 
Is tgalals anxolotl module working and yours not?

**Comment by jlguardi** [comment]
I haven't axolotl module. I use tgalal's.

**Comment by flayla** [comment]
Still no good :(
I changed echocliend (dirt hard code) to simply echo private messages from specific person to specific group.
For English text it works.
For Hebrew text and any other media it doesn't.
Log:

`root@kali-flayla:~# pip install git+https://github.com/tgalal/python-axolotl@develop --upgrade
Downloading/unpacking git+https://github.com/tgalal/python-axolotl@develop
  Cloning https://github.com/tgalal/python-axolotl (to develop) to /tmp/pip-WuUeHT-build
  Running setup.py (path:/tmp/pip-WuUeHT-build/setup.py) egg_info for package from git+https://github.com/tgalal/python-axolotl@develop
    
Requirement already up-to-date: pycrypto in /usr/lib/python2.7/dist-packages (from python-axolotl==0.1.34)
Requirement already up-to-date: python-axolotl-curve25519 in /usr/local/lib/python2.7/dist-packages (from python-axolotl==0.1.34)
Requirement already up-to-date: protobuf>=3.0.0.b2 in /usr/local/lib/python2.7/dist-packages (from python-axolotl==0.1.34)
Installing collected packages: python-axolotl
  Found existing installation: python-axolotl 0.1.34
    Uninstalling python-axolotl:
      Successfully uninstalled python-axolotl
  Running setup.py install for python-axolotl
    
Successfully installed python-axolotl
Cleaning up...
root@kali-flayla:~# yowsup-cli demos -c /root/config -e -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e9.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="65XX433XXX" mechanism="WAUTH-2">
�'Q�T#����8��U�d���D��|Jy�>Hl��Fa���
                                     _h	�)��S�b��^qݨ�>*]�b)��Y�Iͧ8d�
HEX:b82751f85423a5a6f0da388e66a8c455d564a5aa03d744a5b17c4a79eb3e486c92b84661e180c00b5f68099a29fdd153e26281b45e71dda8ad3e2a5d8462291454088d8059a749cda73864c3
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1459514583" expiration="4444444444" props="4" t="1459605525">
�����?:��\��gy�
HEX:e00d941cd5ebf102f91e3f3ab1e45ceab8677996
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1459605525" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="51537B864874219629447EE544D974" t="1459605544">
<enc type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X("bFX�,(�2t
��*)ɗ��:Ӂ	
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102818002210624658cb2c289f3274150a7f99be2a29c9979d9f3ad38109
</enc>
</message>

*******ITS FROM MASTER*******
Echoing Test to 97X5X83XXX65
DEBUG:yowsup.layers.logger.layer:tx:
<message to="97X5X83XXX65-1459522161@g.us" type="text" id="1459604571-1">
<body>
Test
HEX:54657374
</body>
</message>

DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" id="51537B864874219629447EE544D974" t="1459605544">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="read" id="51537B864874219629447EE544D974" t="1459605544">
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack count="1" t="1459605545" from="97X5X83XXX65-1459522161@g.us" class="message" id="1459604571-1">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="read" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="51537B864874219629447EE544D974">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt participant="97X5X83XXX65@s.whatsapp.net" from="97X5X83XXX65-1459522161@g.us" id="1459604571-1" t="1459605545">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="97X5X83XXX65-1459522161@g.us" participant="97X5X83XXX65@s.whatsapp.net" id="1459604571-1" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605552">
<enc type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X)" !V]a��'a�3�I�k	W����[�6�"�pP���/��
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de10581029180022201921565d61b8f9276106aa33b0499c6b0957b0f0f9c71e045b8c36d8229770509ea5b717192ff9d3
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="retry" id="35027CF9B19B9418026D3070DAE312" t="1459605552">
<retry count="1" v="1" t="1459605552" id="35027CF9B19B9418026D3070DAE312">
</retry>
<registration>
���
HEX:1f9e96e0
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="35027CF9B19B9418026D3070DAE312">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605552">
<enc count="1" type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X*"U�TU��WYsQ�DՔD���C����#
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102a1800221055845455edef57597351a644d594448bd7fd4391c8cad023
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="retry" id="35027CF9B19B9418026D3070DAE312" t="1459605552">
<retry count="1" v="1" t="1459605552" id="35027CF9B19B9418026D3070DAE312">
</retry>
<registration>
���
HEX:1f9e96e0
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="35027CF9B19B9418026D3070DAE312">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605553">
<enc count="1" type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X+" 빣-݋I|�Y��#-�T��t�'��_��g졸�%
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102b18002220113d7febb9a32ddd8b17497c8059fda6232d945417f10885ff7403ac27decc5f97b567eca1b8cf25
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="retry" id="35027CF9B19B9418026D3070DAE312" t="1459605553">
<retry count="1" v="1" t="1459605553" id="35027CF9B19B9418026D3070DAE312">
</retry>
<registration>
���
HEX:1f9e96e0
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="35027CF9B19B9418026D3070DAE312">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605554">
<enc count="1" type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X,"�+ML�\qq��h�J�X�
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102c1800221010b32b4d4cef115c7171f40500f268be4a17fdb5077f58c8
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="retry" id="35027CF9B19B9418026D3070DAE312" t="1459605554">
<retry count="1" v="1" t="1459605554" id="35027CF9B19B9418026D3070DAE312">
</retry>
<registration>
���
HEX:1f9e96e0
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="35027CF9B19B9418026D3070DAE312">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605554">
<enc count="1" type="msg" v="2">
3
!�	��Q,|r�f�E,
d�٫U�]Y��/         �wg�{`-�9�f��(�X-" �W��ɯ��e=8t'��R�J����[a
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102d18002220ff57b9bc03c9affbc1653d387427ee8952c74a9ecd467fafb45b610d64d3d9ab55b1175d59b5c82f
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" type="retry" id="35027CF9B19B9418026D3070DAE312" t="1459605554">
<retry count="1" v="1" t="1459605554" id="35027CF9B19B9418026D3070DAE312">
</retry>
<registration>
���
HEX:1f9e96e0
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="97X5X83XXX65@s.whatsapp.net" class="receipt" id="35027CF9B19B9418026D3070DAE312">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="Me" from="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605555">
<enc count="1" type="msg" v="2">
3
!�	��Q,|r�f�E,
                    �wg�{`-�9�f��(�X." ��E�
��]��������c	��Ln"�G��tE��
HEX:330a2105b409d2c316512c7c72ae66ea452c0cdb7767a77b602dbb39c966f6e728de1058102e18002220fa9a45f30acb80bd3b0df0b65dafadded901e3d3eca563099680064c6e0e22e847b6e7077445e387
</enc>
</message>

*******ITS FROM MASTER*******
Echoing טסט to 97X5X83XXX65
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
WARNING:yowsup.layers.axolotl.layer:Too many retries!! Going to send the delivery receipt myself!
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="97X5X83XXX65@s.whatsapp.net" id="35027CF9B19B9418026D3070DAE312" t="1459605555">
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" participant="97X5X83XXX65@s.whatsapp.net" from="97X5X83XXX65-1459522161@g.us" id="1459604571-1" t="1459605558">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="97X5X83XXX65-1459522161@g.us" participant="97X5X83XXX65@s.whatsapp.net" type="read" id="1459604571-1" class="receipt">
</ack>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:`

**Comment by profcav** [comment]
just a workaround:
if I try
**yowsup-cli demos -l NUMBER:PASSWORD -s TONUMBER MESSAGE**
I get the same error.
But if I use
**yowsup-cli demos -l NUMBER:PASSWORD -y**
   **/L**
the keys are correctly created and then I can use without any problem the previous command
**yowsup-cli demos -l NUMBER:PASSWORD -s TONUMBER MESSAGE**

**Comment by chenwayne** [comment]
@jlguardi I tried install  axolotl module, downloaded from tgalal/python-axolotl both develop and master. But the error remains. 

can you elaborate in detail how to avoid this error?
Thanks
Best,
Wayne

**Comment by eribertomota** [comment]
Hi,

I packaged the 2.4.102 version in Debian now. I can see the same issue here and I confirm that the procedure used by profcav works.

---
From profcav:
"But if I use
yowsup-cli demos -l NUMBER:PASSWORD -y
/L
the keys are correctly created and then I can use without any problem the previous command"
---

In my case, I used a configuration file:

$ yowsup-cli demos -c ~/yowsuprc -y
/L

Thanks in advance!

Regards,

Eriberto

**Comment by LeoSdls** [comment]
Hi friends, anyone knows that when receiving messages on whatsapp my raspberry, erroneously receive the message, for example: sending "hello" from a mobile to my raspberry and receive "helloooooooooooooooooooooooooooo" or incomplete message. By submitting no problem, I have only this error when receiving the message, I get incomplete so to speak. Sorry for my English
