### ISSUE TITLE
Again axolotl.layer:No valid sessionsBad Mac!

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#1436]
latest git master python-axolotl 0.1.34, protobuf 3.0, yowsup 2.4.102
Before start axolotl.db was deleted.

```
<ib from="s.whatsapp.net">
<offline count="1">
</offline>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="79131111111@s.whatsapp.net" class="receipt" id="013C0B77572EC8D23AD29F2EDCC8A2">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="daemonserj" from="79131111111@s.whatsapp.net" id="FBBB2E85CD0419E9EC70FD44622256" t="1459496430">
<enc type="msg" v="2">
*** encdata ***
HEX:*** hexdata ***
</enc>
</message>

ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="79131111111@s.whatsapp.net" type="retry" id="FBBB2E85CD0419E9EC70FD44622256">
<retry count="1" v="2" t="1459496430" id="FBBB2E85CD0419E9EC70FD44622256">
</retry>
<registration>
*** encdata ***
HEX:*** hexdata ***
</registration>
</receipt>

PuTTYDEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="79131111111@s.whatsapp.net" class="receipt" id="FBBB2E85CD0419E9EC70FD44622256">
</ack>


```

**Comment by msshapira** [comment]
Same here

**Comment by bdbais** [comment]
Remove key database and start again.

/home/YOURUSERNAME/.yowsup/YOURPHONE/axolotl.db

**Comment by daemonserj** [comment]
did it before

**Comment by bdbais** [comment]
download and build/install again axolotl library, I did it and removed db and now I have no more Bad Mac.

**Comment by bdbais** [comment]
I received Bad Mac another time because I stopped my script to much times and I rebuild db, all old messages are marked Bad Mac and discarted, just wait queue is empty and it didn't show it again. Probably you are testing and stopping your script too much time.

**Comment by gbarba** [comment]
this issue is duplicated ( #1130 ), please concentrate all scenarios and conversations in a single issue

**Comment by DreamFlasher** [comment]
@bdbais for me there is no `/home/YOURUSERNAME/.yowsup/YOURPHONE/axolotl.db` -- when is it supposed to be created? I checked out the latest version, `python setup.py install`, did the registration successful, but in the echo demo I get the "ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!". But there is no axolotl.db anywhere.

**Comment by DreamFlasher** [comment]
Okay found it, in docker it's created in /YOURUSERNAME/.yowsup/YOURPHONE/axolotl.db

**Comment by bdbais** [comment]
now the problem is... how to except this exception and clean db automaticaly by program?

```
    def sendmessage(self, msg, cell):
        self.lock.acquire()
        try:
            print("Message : %s " % msg)
            messageEntity = TextMessageProtocolEntity(msg, to=Jid.normalize(cell))
            self.ackQueue.append(messageEntity.getId())
            self.toLower(messageEntity)
        except:
            print("ERROR:  with sending message.")
```

any advice ?

**Comment by tgalal** [comment]
Guys, this is not a problem. You can see that after it says ```:No valid sessionsBad Mac!```, it sends a retry receipt, on which the other side would re-encrypt the message with correct keys and resend it (whenever it gets online). There is no need to clear the database or anything. 
I do admit though that the ```:No valid sessionsBad Mac!``` message should be changed to a warning or just info instead of an error.

**Comment by rudepython** [comment]
after warning "No valid sessionsBad Mac!" i'm not able to receive any message. other side re-encrypt and resend seems doesn't work. any idea?

**Comment by jlguardi** [comment]
@rudepython Update recipient keys (/keys get jid) and try to send a message from yowsup to recipient. I guess it will fix the error.

**Comment by rudepython** [comment]
sorry,
I'm not enough experienced. can you be more clear? (/keys get jid)

**Comment by rudepython** [comment]
where i can find /keys command?

**Comment by jlguardi** [comment]
Use yowsup-cli
