### ISSUE TITLE
run.py from wiki not working | object has no attribute 'CURRENT_ENV'

### ISSUE THREAD

**Issue by fipso** [tgalal/yowsup#1439]
Hello,
the run.py from the wiki is not working at me.
I think the code broke at last update.

`Traceback (most recent call last):
  File "run.py", line 29, in <module>
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client
AttributeError: 'module' object has no attribute 'CURRENT_ENV'
`

**Comment by zynacks** [comment]
It was changed in the latest release. Look at changelog and use `YowsupEnv.getCurrent()` instead now.

**Comment by swapnil94** [comment]
I have same error...Changed from
```
from yowsup import env
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
```
to
```

from yowsup.env import YowsupEnv
stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent())
```

Now getting this error:

> 
> coder.py", line 117, in writeString
>     atIndex = tag.index(at)
> AttributeError: 'AndroidYowsupEnv' object has no attribute 'index'

**Comment by tgalal** [comment]
@fipso should now be ```YowsupEnv.getCurrent()```
@swapnil94 you need to do instead: 
```python
stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())
```
