### ISSUE TITLE
Does not show the message in Yowsup-cli client

### ISSUE THREAD

**Issue by LuisEnVilla** [tgalal/yowsup#1440]
When sending messages no problem,
but when you receive a message does not show

this is what shows me when mendo "Hi!"

`yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
# Yowsup Cli client

Type /help for available commands

[offline]:Auth: Logged in!
[connected]:[5217721199947@s.whatsapp.net(01-04-2016 12:04)]:[3BEF54C99ADDF5EE501860D79503FB]    i!��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
Message 3BEF54C99ADDF5EE501860D79503FB: Sent delivered receipt and Read`

**Comment by thundergreen** [comment]
Same issue here. No sending confirmation but message delivered .no messages
receiving at all.this morning it worked like a charm

Thorsten Fröhlich
Am 01.04.2016 20:11 schrieb "Luis Villa" <notifications@github.com>:

**Comment by eduardobento** [comment]
This problems ocorrur when api broadcast msg or manage a group (dont know exacly). 
Just get last jlguard repo that resolve...
