### ISSUE TITLE
Problem when receiving message

### ISSUE THREAD

**Issue by jg19** [tgalal/yowsup#1442]
Upon receiving the same message gets strange characters, as was encrypted. It is sending normally.

yowsup-cli v2.0.15
Using yowsup v2.4.102

`DEBUG:yowsup.layers.logger.layer:rx:
<message type="text" notify="joelson pscz" from="554XXXXX0650@s.whatsapp.net" id="D694D556245B4DAB09B63982BA4D44" t="1459540748">
<enc type="msg" v="2">
3
!�c����u�Z:/��9��t��~���R�i��r"��n�J{�G�1/$=�09.���n�ظ�Ԅ
                                                               �6[y$Pw�#z�[=S�_DQ8���U��U��Tg��Ec/��T\��w��8f?�0f8L��>X�-��d#s���ޅ��
����O�s��/2)
                 <d
HEX:330a2105d763b18f8882f9e275cf5a3a2f89c239b7d874f8827eb5ab8952a869a2bd167210001800228001b26eb74a7bac47068331192f243df33017392ea7950eaf6ecad8b8bad4840bca07365b792413500e77d115237adc5b3d53f45f445138c9d0d055ff059055caf05467aef745632f85ee54175cd0db779bde38663fca3066384cddde3e5813b62db7fc642373b7f5afde859e9eec0ae41914ab008fccda1ca44f8d73c516068a2f3229130b083c0e64
</enc>
</message>

Echoing Testxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx to 554XXXXX650
DEBUG:yowsup.layers.logger.layer:tx:
<message to="554XXXXX0650@s.whatsapp.net" type="text" id="1459540748-11">
<enc type="msg" v="2">
3
�h�gEeD�se���ؖ�a5��!k��FAR�_��F8�dzbl�a�NW-z`�j��� rgk�s
                                                                 樎��I�m�3�Y
�%�̬Z�D
HEX:330a210575994f794838b310a9ba03ed3906f6d6119fd794cab44e573a36e88a3d9985131000180022800175bbdec8c68382bf8236f8dcbd882afe541f2b7e8ff531d6d29ab1084df66e6bdc2a622a45676b97730daa689c674565440ed3730665f1e911b4d89612d36135d7c517211a6b94ef4641529e5fa0c8467f38051cb8647a01627f6c9961994e572d7a1d1060f6066a029da5169f20720ce6a88e8100ce49ac6de433b359d40aa225b3ccac5a02dd44
</enc>
</message>
`

`DEBUG:yowsup.layers.logger.layer:rx:
<message from="554XXXXX650@s.whatsapp.net" notify="joelson pscz" offline="0" type="text" id="DBDE4B8BBA89DB331CE7A614597C6F" t="1459540930">
<enc type="msg" v="2">
3
!�s�6�� 
����ׂU.%;{%-\*o"����aĩq�\���c���G�VVp}�iw�  ���6Q/h�5}
�v�EN�/�)5�+Nw��>v߼��Z�KqB��W;8]U�l��`ķ��uLx&��B��_*ɫG�����ծ�N�ݓĞ�`�p��#AO��æ��e�oB���������#��S�k�ܸ$�t���R�.&
HEX:330a2105830813f0739036ffeb200a17ee199ff39807d782552e253b7b252d5c1e2a026f1000180022b00115ee8810f561c4a9177100ec5cb0fec163dff317974793565614701f057df1690177f609e4c1da1436512f68cd35027d18c50aa676ec02454ea02fdc291135cc2b4e77d6eb3e76dfbc98ec5a804b714297c6573b385d55dc7f6c1787a060c4b79603bc754c7826a1ef42859f5f2ac9ab47ab1587eda4ccd5aec44e1cc6dd93c49e16b860f770a3bd23414fffe8c3a6819d65806f4200c4170706b9e6fb0296e6f79ae523838253d66ba78ec4dcb824bc74dfc2ee52f62e26
</enc>
</message>

Echoing est2�������������������������������������������������������������������������������������������������������������������������������������������������������������������� to 554XXXXX0650
DEBUG:yowsup.layers.logger.layer:tx:
<message to="554XXXXX0650@s.whatsapp.net" type="text" id="1459540942-1">
<enc type="msg" v="2">
3
!�����Ŏ��7
           �_��yr��c�V.���"0�N"��DR�i��F���zX'�O��N6S�gs����0^�zLi��&�g�������7����&WS����1|�|�����l�?X�z������m��d����$��־�j'6�Ϡd-�;
                                                ׿1į�x_�ĭ�K�k�B�@}��a��[C�xΥ~,T�\�y]�Ćkt�k8�5�E4���6�YgY
HEX:330a210596bbbaab9f06c58ef5c1370bcc5f85c67972c7049c63e0562ec3f1d12230834e1000180022b001834452ec698f28881acb468b00989e7a5827ef4ffed54e3653856773cceff1e9305eab7a4c69c7d326c667a583f3a7fd97893701a8b1ee8a265753b4f086d4317c0ff0167cbdb3b194846ce33f58fd7a1af0eba3e197d96df1a364bfb4f702d924aef60893d6beb36a27368bcfa0642db13b0cd7bf31c4afba785fa6c4addd064b8b1e6bd2421fbb407d01a3de61bf8b5b43b478cea57e2c5419a85cd5795dc0c4866b74e66bc499a9358c4534f9cff71936b75967590d38
</enc>
</message>

DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="554XXXX60650@s.whatsapp.net" id="DBDE4B8BBA89DB331CE7A614597C6F">
</receipt>
`

**Comment by ronromer** [comment]
there is a closed issue about this.. let me check where I read it

Regards,
