### ISSUE TITLE
Error  in yowsup echo  , 

### ISSUE THREAD

**Issue by gabriel2012** [tgalal/yowsup#1446]
Hi , 

Have a litle problem with the the text format , for example  recently i send the text "ana" and the yowsup echo  received : na������������������������������������������������������������������������������������������������������������������������������������������������������� 

Whats is the problem ? .

Regards , and thanks in advance

**Comment by jlguardi** [comment]
Are you using latest version? This is the well known, and supposed fixed, issue with V2padding. Try latest version and feedback.

**Comment by flayla** [comment]
@jlguardi Is there currently a working version/branh/env for encrypted messages/media private&group?

**Comment by jlguardi** [comment]
@flayla I've a working version (it's almost my master) but I've patched a couple of things that I haven't uploa yet. For example, media is sent always in plain, broadcast also, I've fixed a bug in upload media... I've also used S40 and Android for media reception and, by now, no troubles.
I'll try to commit soon but I'd like to merge directly with @tgalal master if w16 was available. I prefer to delete my fork as soon as possible to avoid so many versions.

**Comment by flayla** [comment]
@jlguardi please don't delete, i'm relying on your fork :)
I'm using your master but i got blocked yesterday, guessing from all the multiple retries, the asci issue and the encryption issue still open

**Comment by flayla** [comment]
oh and does your version support the regular echoclient that uses simple forward() with encryption on media?

**Comment by jlguardi** [comment]
@flayla I've never gotten blocked and I really send multiple retries ;)

**Comment by flayla** [comment]
@jlguardi yesterday i got "auth error" all off a sudden and re-registration gave me reason: blocked

Have no idea why.. did not try other whatsapp client...

**Comment by gabriel2012** [comment]
Yes @jlguardi  this is the latest version.

**Comment by gabriel2012** [comment]
Done , this is the fix:
https://github.com/jlguardi/yowsup/commit/956626e77fc4aa777da65f57978a27b0518a8410
