### ISSUE TITLE
Error in receiveing text

### ISSUE THREAD

**Issue by pushkardravid** [tgalal/yowsup#1448]
If I send 'test', the message that is being sent back is something like 'testVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'. Some extra chars are being appended to the actual text. I have the latest version running and it was working fine but has suddenly started giving weird results. What do I do? Any help would be appreciated.

**Comment by minimaldev** [comment]
me too i see this error and i dont know i can solve

**Comment by jg19** [comment]
me too #1442

**Comment by ronromer** [comment]
[https://github.com/tgalal/yowsup/pull/1390](url)

**Comment by ronromer** [comment]
https://github.com/tgalal/yowsup/pull/1390

**Comment by tsblack** [comment]
This patch fixed this issue for me - https://github.com/jlguardi/yowsup/commit/956626e77fc4aa777da65f57978a27b0518a8410
