### ISSUE TITLE
yowsup read client add strange characters

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1450]
when i use messageProtocolEntity.getBody() i get strange characters when i use whatsapp web or android 5.0

**Comment by ronromer** [comment]
[https://github.com/tgalal/yowsup/pull/1390](url) maybe this can help you

**Comment by freelo** [comment]
Are all characters of the mssage 'strange characters'? Then it may be an encryption issue => Try the latest version or another branch (e.g. jlguardi's). If it does not help, provide all details such as your yowsup version and a debug log of a 'strange' session.

**Comment by jroman** [comment]
I if is like my issue, the "strange chars" are unexpected chars appended to the message.
Right?

Cheers

**Comment by freelo** [comment]
If there is additional strange data at the end, then I should add that there were some patches in jlguardi's branch dedicated to bad padding at the end of the message. There even is a pull request regarding "V2Padding".

**Comment by sanketplus** [comment]
I have the same issue!! If I send _'Hello world xyz'_ I get _'ello world xyzXXXXXXXXXXXXXXXXXXX'_

where XXXXX are some random characters appended!! :( please someone look into it! 

yowsup-cli v2.0.15
Using yowsup v2.4.102

**Comment by ronromer** [comment]
#1390 and #1356

**Comment by jlguardi** [comment]
Will be fixed with wa16.
