### ISSUE TITLE
Traceback (most recent call last):   File "run.py", line 34, in <module> 

### ISSUE THREAD

**Issue by maroscenter** [tgalal/yowsup#1451]
(No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())    #info about us as WhatsApp client
AttributeError: 'module' object has no attribute 'CURRENT_ENV')

si sabes que puedo hacer te lo voy a agradecer, gracias

**Comment by pushkardravid** [comment]
It should be like this.
`self.stack.setProp(YowCoderLayer.PROP_RESOURCE,env.YowsupEnv.getCurrent().getResource())`
