### ISSUE TITLE
Not authorized in last version

### ISSUE THREAD

**Issue by chmodrs** [tgalal/yowsup#1455]
Hi,

In last week my yowsup stop to send message with my zabbix. I see in this forum about the issue with the last version of whatsapp and the solution explained here for fix this. i changed the _VERSION and _TOKEN variable, but no way to work. Now i downloaded the last version for tgalal (v2.4.102) and compile and register again, but still not working.

Somebody have any idea for solution this?

Below is debug for send message.

yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="554891920851" mechanism="WAUTH-2">
# *r▒▒▒jSV]▒▒ts▒r▒▒;O▒▒▒Ej֊▒▒▒▒▒▒G

HEX:141ccec83ec5888516ba6a53565dfd1dbe7473de72efa2c23b4fb9aec5456ad68ae0eb12b69093d7470d232a72f3
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒VrC▒▒▒"mqD▒▒▒,▒
HEX:e85672431ef1c7c7226d7144d8f98f1dcf152cfd
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
X▒▒AA▒i▒D▒▒
&▒▒&E▒n▒{?▒l▒▒v΄Ay%▒▒▒▒▒m
HEX:58c3dc4141b469f40744b3a10c26a91cefbb2645f56ead7b3ffc6cddfc1c76ce844179259edad117f094e9b76d20
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized code="105" expire="417646" retry="208823">
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized
[root@monitoramento yowsup-master]# yowsup-cli demos -s 554898108989 "funcionaaaa" -c /etc/zabbix/zap.conf -d
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e15.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="554891920851" mechanism="WAUTH-2">
"-p▒>ň▒▒jSV]▒▒ts▒r▒▒;O▒▒▒Ej֊▒▒▒▒▒▒G
HEX:39914c613ec5888516ba6a53565dfd1dbe7473de72efa2c23b4fb9aec5456ad68ae0eb12b69093d7470d222d70f6
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒▒▒ey4▒Y▒▒h{#!▒▒
HEX:fbc57f8d15fc657934a259e2f1680f7b23219ea9
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒~▒▒▒&ۉ▒▒Vl▒I/yQا▒▒
;G▒(▒.▒O▒▒ke▒
HEX:cf7ee8e4b601d726db89179fe6566ce9492f7951d8a7b10ffe0c758e4042850d3b47a428e02ebf154fece56b659d
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized code="105" expire="416928">
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by relima** [comment]
@chmodrs same issue.

**Comment by theslash** [comment]
Same Here on 2.4.102

general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

**Comment by snappshare** [comment]
still same probleme here :/
even with new numbers.

**Comment by ilkerkopan** [comment]
I had the same error, pulling latest codes resolved my problem. I guess they are updating some authentication keys inside code.

**Comment by exziz** [comment]
@ilkerkopan having same issue will really appreciate if you code indicate how you pulled the latest codes. As in syntax used. (am a Newbiee)...Thanks

**Comment by ilkerkopan** [comment]
@exziz  if you have latest version of the master branch you dont need to pull, there must be something different. git pull simply pulls the latest codes from repository. 
A quick tutorial is here:
https://www.atlassian.com/git/tutorials/syncing
