### ISSUE TITLE
NameError: global name 'YowsupEnv' is not defined

### ISSUE THREAD

**Issue by shacharlovett** [tgalal/yowsup#1456]
I installed python3.5, reinstalled yowsup2 from scratch, still getting this problem. I saw issues #1435 and #1453 but the problem still persists.

**Comment by topcoderme** [comment]
This is a recurring issue with everyone and there is no solution at all anywhere ?

**Comment by jlguardi** [comment]
Install yowsup. Not installed code doesn't work.
