### ISSUE TITLE
Problem when receiving media message

### ISSUE THREAD

**Issue by martifg** [tgalal/yowsup#1457]
File "yowsup/layers/protocol_media/layer.py", line 43, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue

please help me

**Comment by thundergreen** [comment]
Same here
Am 04.04.2016 23:50 schrieb "martifg" <notifications@github.com>:

**Comment by thundergreen** [comment]
Update:
I updated python-axolotl with newest master branch here and now get these errors:

2016-04-05 17:26:19,562 DEBUG Session: Received image message Message:                                                                                                
ID: 86D76203930F21016E06BF8B2DE412                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  media                                                                                                                                                          
Timestamp: 1459869972                                                                                                                                                 
Media Type: image                                                                                                                                                     
Has Preview: True                                                                                                                                                     
MimeType: image/jpeg                                                                                                                                                  
File Hash: i58QEP/nFNwXjVBla45+p3L9H5ki8uiqO0Q/1H5t+5M=                                                                                                               
URL: https://mmi656.whatsapp.net/d/LPU5FtH0HwlnFkrY2Vclq1cD2RM/AlAky_FOVcN2xi7Dpw9tHov5ffkzJ1i-TMU6LMV6G7MC.enc                                                       
IP: 0                                                                                                                                                                 
File Size: 119480                                                                                                                                                     
File name: enc                                                                                                                                                        
File is encrypted                                                                                                                                                     
Encoding: raw                                                                                                                                                         
Width: 0                                                                                                                                                              
Height: 0                                                                                                                                                             
                                                                                                                                                                      
2016-04-05 17:26:19,563 DEBUG Session: Message sent from 33658589847 to 33781852856: https://mmi656.whatsapp.net/d/LPU5FtH0HwlnFkrY2Vclq1cD2RM/AlAky_FOVcN2xi7Dpw9tHov
5ffkzJ1i-TMU6LMV6G7MC.enc                                                                                                                                             
2016-04-05 17:26:19,571 INFO Session: Started typing: 33658589847                                                                                                     
2016-04-05 17:26:19,886 DEBUG yowsup.layers.protocol_iq.layer: ping queue size: 1                                                                                     
2016-04-05 17:26:20,611 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: E077586FB54FEA84C7E43DAAF1FDE9                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459869978                                                                                                                                                 
Body: Bild gesendet                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:20,612 DEBUG Session: received TextMessageE077586FB54FEA84C7E43DAAF1FDE9 33658589847@s.whatsapp.net None Serge Inacio 1459869978 None None None Bild 
gesendet                                                                                                                                                              
2016-04-05 17:26:20,616 INFO Session: Message received from 33658589847 to 33781852856: Bild gesendet (at ts=1459869978)                                              
2016-04-05 17:26:20,617 DEBUG Session: Message sent from 33658589847 to 33781852856: Bild gesendet                                                                    
2016-04-05 17:26:26,361 INFO Session: Started typing: 33658589847                                                                                                     
2016-04-05 17:26:29,697 INFO Session: Paused typing: 33658589847                                                                                                      
2016-04-05 17:26:29,841 INFO Session: Started typing: 33658589847                                                                                                     
2016-04-05 17:26:36,301 INFO Session: Paused typing: 33658589847                                                                                                      
2016-04-05 17:26:36,473 INFO Session: Started typing: 33658589847                                                                                                     
2016-04-05 17:26:47,364 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870001                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:47,366 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:26:47,489 DEBUG Session: received ack DFB544C202CEE3967795BFDF1EA2E5 receipt 33658589847@s.whatsapp.net None                                            
2016-04-05 17:26:48,346 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870007                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:48,347 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:26:48,516 DEBUG Session: received ack DFB544C202CEE3967795BFDF1EA2E5 receipt 33658589847@s.whatsapp.net None                                            
2016-04-05 17:26:49,203 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870008                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:49,205 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:26:49,321 DEBUG Session: received ack DFB544C202CEE3967795BFDF1EA2E5 receipt 33658589847@s.whatsapp.net None                                            
2016-04-05 17:26:51,229 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870009                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:51,232 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:26:51,378 DEBUG Session: received ack DFB544C202CEE3967795BFDF1EA2E5 receipt 33658589847@s.whatsapp.net None                                            
2016-04-05 17:26:58,634 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870011                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:26:58,637 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:26:58,764 DEBUG Session: received ack DFB544C202CEE3967795BFDF1EA2E5 receipt 33658589847@s.whatsapp.net None                                            
2016-04-05 17:27:00,130 DEBUG YowsupAppLayer: Received Message: Message:                                                                                              
ID: DFB544C202CEE3967795BFDF1EA2E5                                                                                                                                    
From: 33658589847@s.whatsapp.net                                                                                                                                      
Type:  text                                                                                                                                                           
Timestamp: 1459870019                                                                                                                                                 
Body: ���������☝���                                                                                                                                                   
                                                                                                                                                                      
2016-04-05 17:27:00,131 WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)                        
2016-04-05 17:27:00,132 WARNING yowsup.layers.axolotl.layer: Too many retries!! Going to send the delivery receipt myself!    

Text is not a Problem but emojies won't work Pictures are still .enc.

Dunno how to turn it out. Any ideas?

**Comment by martifg** [comment]
# error: 
using echo mode

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="media" notify="José Martín Fiestas Guarn" from="51945343331@s.whatsapp.net" id="BA82492A60B6480997DC6EBFB70C11" t="1459872014">
<enc type="msg" mediatype="image" v="2">
3
!N��-r��y���▒���
}pꗓt��>1��ל<���н���.swh�#L,��b�v��z��+�z��3b{,���R�ݶ���W[�̲����bsT�Z���\E�ʑ���Dz�RwO�-2�K�,�
                                                                                           盻�ϲ2P�9J��O�������~��t���\�ک�^�� ��8��S'�fO����&��=��1]\�r(���▒<QJ=:!���� ]rƂ�"t~��@�Qq}��H�1$ �~
                                                                               ��@Z���>��VCɷ�g���v�j)νVa��9?��Of��ӓ�� ���X�02o8�▒���
��k+]��r�Mf�����P�\[�Fh7b���量�$
���ݛ2���?�c�{�̈3z�2��⧨:y ���bJ\7=�c▒�M|B�h6Њ�UȀ�j�Z��~~�8r�\i��b<��ȅE�����g�Uq�  �B�~�32!SA����Zw�▒fi�\��P%E�23��N����������"ńï/�Z�f
4�f�=�z�G�3��Ql<�Cѕ���Q�o�����▒�x�Uɫu��foF���r���ً�▒*�������a�rBqCSb伛�����2�UXMB�B�G�~�TYL��<LW�Ӷ�H�9>��Q�Y��z
                                +)4,
.mً�(������|X����8��ךz��� ��o=ڎVZ�����<wK�sg�L$  -J����
�▒��xq"�� }.����G钜~���3�R���[[.Ihw�NVhb3���,L{S�8��1ݥ�g���2(▒������ƴ��D{��������g�Âf���u)��J�8*�&��I���:͉0�����
 p|}�Y�PK���Ƶ�R����֑�n�E��������a9�L��mw�����po
����1�ӹ�[����Z�W~>���_-�S6��a\�               w��֋i,�� ���AAd89��~��d��ˌ;
W��x����~�|�S��-˃sʼ+�������V�L�1��.�'1�[j#��teP%�)Ù�k�/ڲ��
                                                          X�"��v����yſDژ��n�F>6�^#Y���@��!/R�����*��V����2E��x��*�7A���7�����H/8'�{
xHвn�7[��5�=�å�ǫn`h쑾��9zS��:��:�
                                 ix^rM�����(�3i��

                                                 El�l��
/�((\��ԜJqj
�ϷdM,�;� ��[єl�§��Z�B��Eّ���=�_���]u&p�������K���Sm%�-<���i�G�ǵ���ʇМ�HZq�"�MŘ�
�*G���.��:q�-�Z>V*�Q��,�#��t{e�݉��ɷM����`GR$�+�L]�3~O�o���G��
I�rG�.D3���*▒�E�uEė΀�p�p��s�i���6�������VjX��N��$��\
                                                    -6�T�`�C��Z�ą����s%18�+P�Z\��!�x
                                                                                    h:x��ß�}�-7���
�=uʍ����m�����(�{��ji   P�t�+�ĵs�npIV�<����b"~�:_
                                                �)�[׋<�'�Gy⺄�����
                                                                  ��.�Y�i����EX��q�1s$l�2ʳě�▒ j9J�du����.i���X��),�����6�A<�@�
��G
   �@����o��C$D��8x��8M�t��
                           ��v
�����brXR�B��SO̸+����j.Ȕ��5EK�YO:��gs��Y�Î��yԠ�W'Q�S�8��܇�����H����\��^�+7��f1E�-y���ڢ   ���������!����ݙ���=�1����#����S��鹡2��t�)}���C����
�AbM�����:�ıh�ę髷B����QA�8؁�V�۳LC       �O�����x�'�j5O}�[����m}�+�m�8xT���zU�+Hz�A`�)ci�%0���?
����N▒�3����,��r����
C���
�=?ޗR[��Kx�#���f3�v��)��6�j#�����Ԣ�c��8��À�~���
��z�L��A���>���4J�0۸�����������;��O"�U������I�8�������O%�?�J7�0�%��O�ii�?g�]����yzf�l&�����m�]KV�&�m
                                                                                                    �+jTU▒�h0�[�����B8kk̿˾�@�v"/���Hl��B"T���"@���1gh����������]�أ��qn������)q���q�f�v��w��QbI9��L5労ʸ����P\��j3��     �Pd��s����,�G^�����sU��݋���xzp▒�i�����������c���U��%4$���`Ew�jmx���#V���큏�r(<��B��
                                                                             ��U;�fwp�e���U�n7Q�xۊ��518.X��������/y��9
�/�a9��
=���+E��Nj&ΔB����������U�
|�D��P�b ���aB�
               ؒ$F�����mu▒2�vPX �3y4f,'�▒�<@�?�J&�Y�
                                                    �ſ��E3�����E��8�    ��YVt�����mc~�:����m�����NJ������    ���[��
��B�▒�[\"�M��ޥ����D?�J�.G&      w���г��n��0 :8����+�R+A���_�~󿡿_i2����=��e��MQK����fL�2V��"���  A�i�.]��{
    ��U8N��jO ��0���n�ڵ�܀�W�
                            �v�B <O[��B\���A
�e��U&�i���GBk��Ņ(�~(:�+p����Eߡ��>��(�Li9d6�F��� Y k�����n��*��z�������B*~;9���a,�*ws�d\s�q��A�▒Ьw0I��B��`��Kj����_p6}4�&�=����ֹ���W��!B�
���4����&���g��X�?��_�~)�/=��p��+�Q88������L�▒��o�]I��+X�����XǤ�.766���T        7�c������?�����2C��7�����`g8����#z�dc����:�QpأI��lO�"JƊ�����s[ϼ��▒Od�����>ydU�g2�C�   ��X��<%��       >J�XS3w���i�Et[�g&ϩq+G�c
�dD~5������s}c�_5��/}�D
                       W��&�[
L�o��~Bx,��\��w|E��D�d'��$V�)Ƌ���k�_��`����-▒:9�M������▒�����hXk�B<r�sw�/}��W;��&�k#ز-�>�� �Ɨ}��ߩ
                                   ~KN�$]hA�z������C��힮
zs��Ƕ3��?��5�麢��>R�S��MnQ�T�J!#��n��O
                                      4��֙���ӇG�[��Q�o�ѯ�U�����0
��Az�x?T�fqsO�b��rX��4�1���aÊ����9��ں�w�
                                        J�Y)▒r'�rz:
�h^�U�al('w��ׁ��6t�'�@u.�▒�m�*��3c��~A���l�m*��i�
                                         ��s��R�{�!�,�[$��&O.�
                                                              ׿_?��bOV�PTK���F��E+
h��[���I�ӠN��',͚ai��>��jW>y�����B�q���5"S9��RCD��
                                                 ���Q������\�������A��̍-k%i������D���w���'"�:�������p�i�ĥ�Q��ْ��Fg�X�Y�D�7�&H���lu�&����x�b�F�D&�]▒4������9|̔dF�={,G>r�J��85��$Gp���'��c�׼��{���s\|x%a7tC�}�V�U��LJ?�[�▒�raRG`]{�/��M�U����e>I)��ӱb3!o��\�ðx��m�D��0I�����lI��M�o�#����pu`�r8�!���ʇ0���&k��s���b�,%
HEX:330a21054ea3ba2d72feeb79c1109def18d37fe9fc0aa1db61cd8e7622ee72dfc717d76d1000180122b0232a486115da5da9c3170ee2b50d7d70ea979374a5c83e31d1eed79c3cae83ecd0bd8bbde12e14737768ea234c2ca5cc62f176dbcb7a99b92bbc7aeeb233627b2c9f9ddc528cddb688161d90f4575b97ccb2fe92d71684627354b35afd979f5c4503e3ca91f6c4158d447aa852774f812d32ca4bf22c880c7f2108e79bbb99cfb23250b0394adbc44fefedf2e30fd100c7db027ef800149e74be06afcd5cc6daa9c05eb09620c0e838a8a95327bf664fbdceffec26cd1bfce23df895315d5cc2720f28c0a58e1688183c514a103d3a21a18cb4c285ac095d72c6828422747e9494408051717dbf8b4815cc312420b27e0cab9f405ad9fab93e89f55643c9b7f767e6b4ec76a36a29cebd5661ac91393ff49f4f66f283d3938ee020bdffdb588930326f38a41ad51ce9d80a91e96b2b5d95fa72f14d66ff9fbaf39f50a85c5b97466837621486faebe9878f89240abe978bdd9b32b494c23f1b73df63d37b13a6cc880f337af432f8cfe2a7a83a790991f2e3624a5c373dff631ab24d7c42806836d08aea55c880dc6ace5a8eba7e7ebc3872a75c698ba4623cd2e5c8851d45839181fe91679b5571e61e09de42a47ee333322153419cb092b6055a77f7186669e05ca481502545cd3233dcdc4eea93e4e611fdeb12fd8016b9cf220312c58405c3af2fbd5a84660a087afb77ca967cd1a115bdc1b21125dcadadc89b5991d37b58e286e611ad8702ec36ed75eef15dcebe2e1e5c4bfe38d7be987d64bc9b7426ec66a0d7172ecdcb8dd937b6d733d5c1efcb09f02d097e4544633f7869ea7a567d7a2804909c4e70967e81240dd512358f617ca6a16f5de35d0e4444945d9901e78fa8f708da33ffd75cbe5fcd3443d50ee35615a078d5551dc9ab7514bddf666f46808ad27212cbfff5d98b1217dc1a2aa88681f3b1daf861a80e7f724271435362e4bc9b85e5bff801891932f755584d42f2429847d47ec454594c19b7a43c4c57c1d3b6ea48ad39043ed40e99511cbc59c40f807a0d030434aa66e03dd87abc47cd0433aadf516c3cb543d195daebfa0051d66f8ed2fadcc3031a1f1c980c2b29342c0a2e6d06d98b1dd628a8ded5f59acb1b307c58abd7cbfb38d2e7d79a7abc1786b4208bca6f3dda8e565af3f8b10519ceea3c774bcc7367e0014c24092d4a978accf20ad218d80fd178107122fb991b6d207d2e9ab6a38847e9929c7ead94a233815292ffdd5b155b2e496877ee4e566862330219f91b669d05b30e122c4c7b53dd38fce331dda5fb671f81afea1b2d32281a0efab187d5e7cec6b4bdab447b989efbb0dfdccf02bd67d7c38266a0bae77529ff9f124a9510382a8026c5c307498d9bd93acd8930f79888f9810b707c7db659a8504bf97fac90c6b5dd52e5eef7d3d691906eb645bf8daaebd207e3fd8661391ffe4cfcbd6d77bc8882ae92706f06170b77edf4d68b692c8bc320fea07fd84141643839aaa4081fd27ec9fd648ac9cb8c073b0d8ce308d8f4b631e7d3b9069f5b86be84925a831d577e9a083e91e4965f2dac53360e10a483615cac0a57f3e178f28f8cc07e14bf7cc453f9892dcb831e73cabc2bd0fe82d8f094e556f74ce4319be02e1001e2072731c65b6a23ef9f74655025d929c399cd6b9a2fdab2def20b58c822e4c876f517a8f5a879c5bf44da98dafd6e84463e36bf5e2359bcb0e340efde212f52adbe92bef92aaaad567f8ea4b5c43245a0f078f542f73e13dde877a11ac2658eadf4bd482f3827837b0db3b02af637419fdbff379d810ba874b69b130456036d0d7848d0b26edb375ba8f235e63d8a01c3a596c7ab6e016068ec91be8dc3397a53d9f3103ad50e883aa60c69785e724d04e390e9f69428a37f336994c60b0c45116cce6cdec5000a2fc528ff08285c9495d49c4a1e716a0ae0cfb71d644d2cc03bfd2089815bd1946c11c4c2a7efab5ad242c8da45d9911603e5b7d7013da85fad8f855d752670ccf9f30f90dfc3d74b8cadfc536d25ab2d3c82f2ae69d7470eeac7b5d2f6caca87d09ca2485a71b422fc4dc598db020aed2a4785d3cc2ea7ec3a71b30e2dfc5a3e562afc5187932cb723a4d8747b659cdd89e385c9b74df29fccf360475224972b11f04c5dab337e4f9b6fa1a8a247d7e00a0849e0720047be2e4433859d00da2a1aab45f600077545c497ce80c4041370c870a4aa73f469f8fd10df3683bbbef1ff96d6566a135880834ee7ab248ec95c0b2d36bf54e26005de43971fd55a9cc485a1c3f4b87325153138b6032b5002a05a035c1db3d92189780b683a780497c7c39fde7dc0be2d37c3f1970a1db83d75ca8de1a4e0996db8f007e38d1b3df51628a97b9ba96a69030950a474982bc9c4b573eb6e704956843cb489f79962227edc1d023a5f0c088b1c29b55bd78b3cf227cb4779e2ba84b44c08a9c61dbac3040cc4c08d2ef859d716691c88c8ddf34558b3cd71853173246cc532cab3c49beb1a206a39004af46475b388e7ae2e699091f15898ab1714292cbaadfdb9ab36ae1c413ce040ed0aad9d470c8a4097f5118f8d6f17e380432444e7843878f1f3384dcc74b99c0cf6aa760b91c25b74778f5cbe31b98a78700db7fca6eb8a62725852ce4201aed8534f16ccb82b96b900fcc76a2ec89490ec3545044b8b594f3ae2fa677381b159f7c38e9712fa79d4a00e9157275186539d38e3a1dc87f2e5e1abe248a0cff5d05c96ef115ea32b371d8cbf663145e1072d7991ecd8daa2150f09badde1f59ea9e816e68f219e1282d6ccdd999ba31d8b013d9e3195f91d178d9123969da8e153eacfe9b9a132fbc374b3297da08211e443c0a9ab0605eed30ab741624dc7efb6f21fb83ae8c4b11668e8c499e9abb742a582e392510741bd38d881e1075692dbb34c4309ea4f83aeb68fe07f78cf1927f9006a354f7d14cd5bc8c3d71dd16d7dfb162bcd6db803387854bdd9f21d007a55e42b481e7aa6044160bb296369fe2530b0f9ed3f0a8dd7d3e24e011891339188aaa42c899f72c010c5f6840a43bdcfdc0c89b70fa0ecd96e0ebf39736d491b70559df3e1e89bcc8602a9544079760d833d7f3fde97525bbed04b78a023b0ae15800e6633da76e2ea29d6d536a66a23a7bca0bdf0d4a2bc63a3c13895f7c38007f47eafe1f30bf00fd4c942f51ebebc6ced73e8b6bf7baecc90b2a36f7ec84d2181bb5c497f7da90dfab47abb4c8680418ff0bc3e8b8011df00344aed7f30dbb81793aeafb185e788c0cada04f13bf1874f22c90455c9c5fb85b4fb49e638a2b61bb106febe9cb7b74f25cc3fc44f08074a3797308b2587fc4fd66969823f67885df905f7e3da79167a66a86c2603f711fafc8f8e6d00eb5d4b568926856d0b912b6a54557f1a9d6830d05be196cbf2c542386b6bccbfcbbed340b11076222f848ffd486c8db019422254beaf8e22740840efb1f731146768be14a880b9d8c50098aacdee5d95d8a31be7bb8cf6f1716efcb2dbf485fd2971e1e206bc71de668c76e1e077f019d151624939a28a4c35e58ab4cab80496e592ca505cfe9e6a330fe2a11709cd500664ffb173b5aed6f12caa475efc8d9a96f8731f558ac2dd8b8df5a7787a701acb1669d288babdfeded9c31bb3908d16bcabf563d500b9db55a7ee172534248a87a360457710d16a6d78a714fd822356ccf6aced818fc872283c13ef81429fb00b88d4553baa661177160f709b65a8ecd355e66e3751ae0e78db8abf833531382e58c188bab5988c8f93902f7987ff390a9cef86be2f9b6139e993190a3df4981df12b124584e54e6a26ce9442169dd3f7f29008f7ef9ad5faff1c55c108be0a7c1cf244febd50c36220c4eeae1e6142960cd8922446adfac5f9a56d751a320fe076505820ee337934662c27a41abe3c408e3fa34a26ee59b10bc9110ec5bfe6b94533e9f2b1bee145e0c238fb09b0f559560f74f286c8c2de6d637e833af3bd1482856dacfce5fcb7114e1d4ab5a7f817c5feaa099df18b5bebfc0cb72c19c5bab9d6563b8e04e654b8bfb944041c3ffb4ae907022e4726097f77b0b88bd0b31795806ebed81d30203a38cff186bd2bb819522b41ef1ce2c25fbd197ef3bfa1bf5f016917320ff280b9e53df59565d1d24d514bb1ede4e9664cb53256e69522efc4fa0941cf69db2e5d15971d01f57b0d738170581a9d5b5c22a94dd9f6dea5a50deedf42a10cace255384ed1e26a4f5c0820d8ec3099a8cb6ec8dab5acdc8014ff57d50bf576a142203c4f5bbca9425cf6df19139e410aed659fab5526d5691fa2eb8c47426bad85c58528ad7e28123aa82b70e4cbf18345dfa1e38a3ee48a1628dd4c6939643690469eabe0201e59206b8f8fb5e9926edef22ab29b7aeff0e3f390e2e5422a7e3b39fe92c41bcc9d612cd7172a7773d9645c73af71b1c31e41fe1ad0ac773049a7c542e88d60eafd4b6aa91da2df14855f70367d348926d5143dcf1ebbd6d8d6b9d0e1e4578b902142f20a88f6b634eb03b17fbbe91926eeb9f1678eec58e43fdce85fab7e29cc2f3df9c070cff52b8351383887f81e0302ceead2f54ca71afda96f925d4982c42b58d813ebf784b7a6a60fc258c7a4ef2e1337073636a3adf303540937fd63e6c5e0f89eef3fb38985eae43243fbb837fee9e5c20499606738c5cb006fd863e3aa2a9800ceecca54786028739b540498d7234577b8949461d1d4742e236036c246c23217734e82818c1d95123e796455fded12244143ad0df419c423197ab16463bac09daf983a9f5170d8a349949f6c4faa224ac68a9accc5c1d9735bcfbcf61f109f1a4f64b2e1c209671f32df09bcef0658e4a93c25cbf1093e4aaf58c5170806533377cbfeae698145745b0fcc1c6726cfa9712b4710f7630a9264447e35928abe8aeb04d8737d63855f35dfc87f2f7dab440c57ace026f05b010c51900418d63b6b5fdfcd6014e7bf04daf12d1bf91a163a1939ff144d9fa119a1b4ed921aa2e1f386dd68586b88423c72f67377942f7d90170202ea06573bc098e426bd6b23d8b22de93e8ee32082c6977de9fedfa90d4cfc6ff8a77e42782c8991115c8dc61e777c45cbf044fd6427e614a72456ef29c68b980684c46bdf0b7e4b4ea1245d6841f37ad81308a6bcb7dbeb1df043aa0fb9ed9eae0a7a1173c3f1c7b633dedc3fffac351311b713e9baa2f2913e52fb53fada7f4d7f6e51bf54884a21230486e76ea6c64f0b34dcd8d699e2d7e9d38747c05bd6c8514308d06fb010d1afd355b0a998138292300ab1b20d33c9c3b2cbb2c87fe7c268417082835395ce0dfd89417a058b783f54db6671734fe3628cf2f3087258cad634a531d404f301a661c38a83eeb5c19539bdc3dabafe77ad0b4afb5915290018721d279c727a3a0aeff3774af5182ac28de46a134ef91475dfabc27b5b5f4d42d34351d8ace769acc166dd07b259f4e9d011e7dfcc78c7426c1bef71147355a1f506f6be0d6610cb9ba538f0b9f622f6c1793ffff9e6bd02f770b51ce593854c6057ec381066b05482b686c34ed386ffd8549bf055c76d2aa7b9690db4685ef955b801616c282777e712e9d781f8a83674ab27d84075002ef818bc6dbc2ab19c3363bc06867e41b4bcfb6c0bb4d273a58652a91b477b981e21d12c9e5b24ecde264f2ed90cd7bf015f3f85128c624f56e250544bf2b69b46c5c0452b0aa5d1576c2b8bbda8654230926b28fe8e6df1378f557ec83f1f1d392ea80d68ee8d5bebe0fc4905dbd3a04ebc04a2272c06cd9a6169f1da3e14b6b46a573e79e6c1f399d442a071fb88be35b3082253399f8b52434498bc0bfc8cc051e6f79b9fe8b95c1789fbd2c9d2daf8411e03bcfecc8d2d6b2569d00e0f96aa9ff7d0449d8ad277a8f0972722ff3aaa87b0a189f30eec70ab691e19dec4a58051c7f1d992aed84667a858001fe559b744f337ba2648f314f4ba6c0e759e2617ddd2fdf4a6a6b378b962cf46ab4426fb5d1a349b80ddede49f397ccc946446983d7b2c470e3e72bd4aa9c0383594e4244770acbd8c27d0d263a7d7bc13efd87bf6ade1735c7c7814042561377451081343ef7d9f569555f79b4c4a163f825b0fec1c18d372615247605d384d9982c85f3f77c4ff93bf3450c92f1a34703bda34ef05a611123958f1037a226ed64615571ee0b1b4fb35325f7cfe50dbd6b51c2654ed32b2d69d80ff7e06b8d3745fd0131f746460882da97544e37d67ab6d14d5b788fbcea75cb33f05c9b64e251ff526a5ec2c250d7bef2fa77ffc4dc355d114e9f78d653e4929a9a6d3b162160f330e216fee91015cffc3b0788bf56d8b4417cbd93049b6d2f6b2f26c49c4e94dc28e8a6f9e23fe9795e1707560d7721738c1b021f0f79eca8730d8dce4266b01f91b9ec67319bc0ee59662
</enc>
</message>

Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 270, in process
    self.startEcho()
  File "./yowsup-cli", line 308, in startEcho
    stack.start()
  File "/home/martijm/yowsup-master/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/home/martijm/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/martijm/yowsup-master/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/martijm/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/home/martijm/yowsup-master/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/martijm/yowsup-master/yowsup/layers/axolotl/layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/martijm/yowsup-master/yowsup/layers/axolotl/layer.py", line 288, in handleWhisperMessage
    self.toUpper(node)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/home/martijm/yowsup-master/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/home/martijm/yowsup-master/yowsup/layers/protocol_media/layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'
```

**Comment by freelo** [comment]
@thundergreen
> Pictures are still .enc.

So what? You can decode its contents, but that won't change the URL into .jpg or something. You probably need to get your hands dirty and fiddle with your transwhat in order to make it handle non-ascii text and decode image contents.

**Comment by thundergreen** [comment]
@freelo I think so. I have to admit I'm not a dev not knowledged in python
...so I will have to check with the transwhat dev :( thanks anyway for your
response

Thorsten Fröhlich
Am 05.04.2016 19:34 schrieb "freelo" <notifications@github.com>:

**Comment by jlguardi** [comment]
Use jlguardi/yowsup/master or tgalal/wa16 for develop branches with media encryption support.
