### ISSUE TITLE
Reusing an open connection

### ISSUE THREAD

**Issue by teehamaral** [tgalal/yowsup#1459]
Hello guys. How could I solve the reconnection problem by reusing an already open, for example, use the same send connection to listen on different instances and environments (could be using the connection HEX)? Someone is using this solution or could help me implement it?

**Comment by freelo** [comment]
Could you clarify, please?
a) What is the "reconnection problem"?
b) How is a "send connection" "listen"ing?
c) Are you trying to handle different accounts through a single connection? I don't assume that is supported by the manufacturer.
d) What is HEX?

**Comment by teehamaral** [comment]
a) The problem is that we must use different instances with the same account. So we are currently using onEvent method to reconnect after the fall.
b) See item a)
c) I'm trying to use from different places the same connection, being in a connection only to send and others only to receive messages. Exactly the opposite of what you said.
d) It would be something related to a connection hash that could be reused in another.

**Comment by jlguardi** [comment]
Probably is easier to have just one process reading/sending messages and forwarding to other machines and resending from with rest. In summary, a proxy between whatsa.. and rest.

**Comment by freelo** [comment]
Sorry, I think I don't get it. Of course we can send and receive messages in a single connection(1 process, 1 connection). If the connection fails, we simply reconnect. This could be achieved in the main loop/thread. I agree that when sending a message asynchronously to an already established connection, it's a pain to sync with the corresponding ack. But it works.

**Comment by johncordeiro** [comment]
I see that you suggest using the same connection to send/listen messages. My question is: This is the only option and is impossible to reuse the same connection using yowsup in different machines? It is a big requirement for me as well.

If it's not possible, how can we contribute to yowsup support this "feature" ?

**Comment by freelo** [comment]
If it's possible on a single machine, then you can redirect messages from/to your local network. You would write an application consisting of a single wa connection and multiple connections to local machines, dispatching amongst them. This is what jlguardi called a proxy. However, this is completely unrelated and out of this project's scope.

**Comment by johncordeiro** [comment]
I understand that in a single process to send/listen this problem wouldn't happen. But suppose that I can only have different processes to listen and send messages, what can we do to make yowsup support this architecture?

**Comment by freelo** [comment]
I don't think there is any reason to implement that high-level stuff within yowsup (which claims to be a wa library, nothing else). You can develop a proxy server application utilizing yowsup and a client interface library which connects to that single server. Having a separate, independent proxy setup, you could then even go ahead and exchange yowsup by something else if you decide to use some other messenger for all of your clients.
