### ISSUE TITLE
End-to-end encryption and Yowsup

### ISSUE THREAD

**Issue by dbareiro** [tgalal/yowsup#1462]
Hi all!

I'm planning to do some tests with Yowsup and I wonder if these [1] changes made on the platform could generate some inconvenience to implement Yowsup.

Thanks in advance!

Kind regards,
Daniel

[1] https://blog.whatsapp.com/10000618/end-to-end-encryption

**Comment by freelo** [comment]
By looking at the current issues, pull requests and forks you could tell:
Yes, it generated some trouble and it still is not fully supported.
However, you are welcome to help. Deterministic testing and smart conclusions is what we need here.

**Comment by dbareiro** [comment]
Hi, Freelo. Thanks for the prompt reply.

Do you think this would be a blocking issue to use normally the library?

Kind regards,
Daniel

**Comment by freelo** [comment]
You can use it normally, but don't be offended if some messages won't be received. If that happens, just track down why and provide a patch. :)

**Comment by dbareiro** [comment]
Hi, Freelo.

I'll keep that in mind :-) Thanks for your reply!

Kind regards,
Daniel

**Comment by drizzentic** [comment]
What is the impact of end-to-end encryption on yowsup library?

**Comment by tgalal** [comment]
E2E is supported in yowsup for [over a year](https://github.com/tgalal/yowsup/releases/tag/v2.2.15) now, at least for texts. Groups and media encryption support is WIP in wa16 and almost done.

**Comment by msshapira** [comment]
great news!! ("almost done")

**Comment by dbareiro** [comment]
Hi, Tarek. Thanks for your reply.

I had read this [1] reference of September 2015 on the wiki, but as the article [2] mentioned was written yesterday on the blog of Whatsapp, I thought maybe they would have introduced another layer of encryption that could make Yowsup not work properly with the current implementation.

That's why I decided to consult here.

Kind regards,
Daniel

[1] https://github.com/tgalal/yowsup/wiki/End-to-End-encryption
[2] https://blog.whatsapp.com/10000618/end-to-end-encryption

**Comment by LeoSdls** [comment]
Hi All!

I have a problem when receiving messages on my raspberry, erroneous messages arrive, for example, sent from a mobile "Hello" and I get (in raspberry) "helloxxxxxxxxxx" (etc). Anyone know what problem may have when receiving messages? It is the problem of the latest version of yowsup, axolotl?
I appreciate your help.

Note: When I send a message from my raspberry to a mobile no problem.
