### ISSUE TITLE
No routes issue while registering

### ISSUE THREAD

**Issue by kaptoxic** [tgalal/yowsup#1465]
I get this error while registering (S60 device, tried adding country/operator codes that did not help, tried setting/changing some of the environment variables):
```
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}\n'
reason: b'no_routes'
status: b'fail'
retry_after: 3600
```
I saw some people having issues with this, tried some proposed solutions, but none have worked. (I updated the app, so I have: yowsup-cli  v2.0.15, and yowsup v2.4.102.)

**Comment by molayac** [comment]
I have the same error, but with one line more before yours:

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}
status: fail
retry_after: 3600
reason: no_routes

Thanks for your help

**Comment by ronromer** [comment]
It happened to me, I think that Whatsapp have a list of virtual number ..

**Comment by kaptoxic** [comment]
I update to the new version and still have this issue -- did you manage to find a workaround perhaps?

**Comment by ronromer** [comment]
Hi, it is not a yowsup issue .. You can't not use that number for whatsapp

**Comment by kaptoxic** [comment]
On the contrary, that is not the case -- whatsapp is working fine both on my phone and on the web
