### ISSUE TITLE
layer for sending and read messages like youwsup cli

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1467]
i dont know how i can do it but im was created a layer for sending and read messages but i dont know when it read the messages is ok but when i send the messages fails and is not showing on my whatsapp phone here my code 

--layer

`   import os
    import time
    import sys
    from yowsup.layers import YowLayerEvent
    from yowsup.layers.network import YowNetworkLayer
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
    from yowsup.layers.protocol_media.protocolentities import *
    from yowsup.layers.protocol_media.mediauploader import MediaUploader
    from yowsup.layers.protocol_messages.protocolentities import TextMessageProtocolEntity
    from yowsup.layers.protocol_contacts.protocolentities import GetSyncIqProtocolEntity, ResultSyncIqProtocolEntity
    from yowsup.layers.protocol_iq.protocolentities import ErrorIqProtocolEntity
    
    import logging
    logger = logging.getLogger(__name__)
    
          
    class ImageSent(Exception):
        def __init__(self, value):
            self.value = value
        def __str__(self):
            return repr(self.value)
            
    class MediaDiscover(object):
        EXT_IMAGE=['jpg','png','gif']
        EXT_AUDIO=['mp3','wav','aac','wma','ogg','oga']
        EXT_VIDEO=['mp4']
    
        @staticmethod
        def getMediaType(path):
            for ext in MediaDiscover.EXT_IMAGE:
                if path.endswith(ext):
                    return "image"
            for ext in MediaDiscover.EXT_VIDEO:
                if path.endswith(ext):
                    return "video"
            for ext in MediaDiscover.EXT_AUDIO:
                if path.endswith(ext):
                    return "audio"    
            return None                
     
    
    
    class AllLayer(YowInterfaceLayer):
    
        is_conected = False
        def __init__(self):
            super(AllLayer, self).__init__()
    
        @ProtocolEntityCallback("success")
        def onSuccess(self, successProtocolEntity):
    
            print "connected"
            self.is_conected = True
    
    
        def assertConnected(self):
            return self.is_conected
            
    
        def SendMediaMessageTonumber(self, phone, message):
            if self.assertConnected():
    
                if '@' in phone:
                        pass
                elif '-' in phone:
                    phone = "%s@g.us" % phone
                else:
                    phone = "%s@s.whatsapp.net" % phone
    
                for p in message:
                    self.MEDIA_TYPE = MediaDiscover.getMediaType(p)
                    if self.MEDIA_TYPE is None:
                        self.disconnect("ERROR MEDIA")
                    if self.MEDIA_TYPE == "image":
                        self.image_send(phone, p)
                    elif self.MEDIA_TYPE == "video":
                        self.video_send(phone, p)
                    elif self.MEDIA_TYPE == "audio":
                        self.audio_send(phone, p)
    
                
    
        def SendTextMessageTonumber(self, phone, message):
            
            if self.assertConnected():
    
                if '@' in phone:
                    pass
                elif '-' in phone:
                    phone = "%s@g.us" % phone
                else:
                    phone = "%s@s.whatsapp.net" % phone            
                    
                message = message.encode('utf-8')
    
                messageEntity = TextMessageProtocolEntity(
                        message, 
                        to=phone
                    )
                
                self.toLower(messageEntity)
            
        def SyncContacts(self, contact):
            if self.assertConnected():
                
                if len(contacts) > 0:
                    contactEntity = GetSyncIqProtocolEntity(contact)
                    self._sendIq(
                        contactEntity, 
                        self.onGetSyncResult, 
                        self.onGetSyncError
                    )  
                      
    
        @ProtocolEntityCallback("message")
        def onMessage(self, messageProtocolEntity):
    
            if messageProtocolEntity.getType() == 'text':
                self.onTextMesssage(messageProtocolEntity)
            
            if messageProtocolEntity.getType() == 'media':
                self.onMediaMesssage(messageProtocolEntity)       
            self.toLower(messageProtocolEntity.ack(True))
            
    
        def onTextMesssage(self, messageProtocolEntity):
            .....
        def MediaImageMesssage(self, messageProtocolEntity):
            .....
        def MediaLocationMesssage(self, messageProtocolEntity):
            .....
        def MediaVideoMesssage(self, messageProtocolEntity):
            .....
        def MediaAudioMesssage(self, messageProtocolEntity):
            .....
    
        def onMediaMesssage(self, messageProtocolEntity):
            
            if messageProtocolEntity.getMediaType() == "image":
                self.MediaImageMesssage(messageProtocolEntity)
    
            if messageProtocolEntity.getMediaType() == "video":
                self.MediaVideoMesssage(messageProtocolEntity)
    
            if messageProtocolEntity.getMediaType() == "audio":
                self.MediaAudioMesssage(messageProtocolEntity)
    
            if messageProtocolEntity.getMediaType() == "location":
                self.MediaLocationMesssage(messageProtocolEntity)
    
        @ProtocolEntityCallback("ack")
        def onAck(self, entity):
            
            if entity.getClass() == "message":
                print("Message Sent : %s" % entity.getId())
                
    
        @ProtocolEntityCallback("receipt")
        def onReceipt(self, entity):
            self.toLower(entity.ack())  `

My Stack

`import sys
from yowsup.stacks import YowStackBuilder
from .layer import AllLayer
from .axotollayer import YowAxolotlLayer
from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.auth  import YowCryptLayer, YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.network import YowNetworkLayer
lass YowsupAllClientsStack(object):

    def __init__(self, credentials):
        stackBuilder = YowStackBuilder()
        self.stack = stackBuilder\
            .pushDefaultLayers(True)\
            .push(AllLayer)\
            .build()

        self.stack.setCredentials(credentials)
        self.stack.setProp(YowAuthenticationProtocolLayer.PROP_PASSIVE, True)
        self.stack.setProp('phone',credentials[0])

    
    def start(self):
        phone = self.stack.getProp('phone')
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))        
        try:
            t = self.stack.loop()
        except AuthError as e:
            print("Authentication Error: %s" % e.message)                        
        except Exception as e:
            print e
            sys.exit(0)

`

**Comment by freelo** [comment]
1. What about punctuation?
2. What's the error you get? Don't expect anyone to guess...

**Comment by minimaldev** [comment]
via programming i never get the error but when i send me message with SendTextMessageTonumber but the message never arrives with the phone after receive messages with onMessage

**Comment by jlguardi** [comment]
Enable debug log and post it.

**Comment by minimaldev** [comment]
other thing im using the wa16 version mixed with master version.....

**Comment by minimaldev** [comment]
how i can enable the debug ?? @jlguardi

**Comment by minimaldev** [comment]
`
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 139, in receive
    self.toUpper(protocolTreeNode)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/var/www/html/PYTHON/testapp/venv/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_authentication.py", line 80, in handleFailure
    raise AuthError(nodeEntity.getReason())
AuthError: not-authorized


`
