### ISSUE TITLE
Question: there is a way to know through yowsup if a number is banned from whatsapp without requesting the sms code?

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#1472]
Well, at title says, through the yowsup api, there is a way to know if a number is banned from the whatsapp service, without asking for the sms code?

Thanks

**Comment by mgp25** [comment]
@logging in or checking credentials (previously registered).

In the first case, if you receive a `not-authorized` then you are blocked (or wrong password, im supossing the password ir right)

**Comment by minimaldev** [comment]
using warp....
