### ISSUE TITLE
Register Attempts with no sucsess!

### ISSUE THREAD

**Issue by DaniloMurbach** [tgalal/yowsup#1473]
**Hello.

Please a need help to register this number, i follow every steps, but my sms request code never reaches my phone number.**

LOGS:
### # yowsup-cli  registration --requestcode sms --phone  5511930116414  --cc 55 --mcc 724 --mnc 39
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":1805,"sms_wait":1805,"voice_wait":65}

status: sent
retry_after: 1805
length: 6
method: sms 

**I also tried to request this sms code directly from my Android`s Whatsapp, so  the sms request reach my device, however, when i try to request user and password...**

LOGS 
# yowsup-cli registration --register 641-376  --phone 5511930116414  --cc 55
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"guessed_too_fast","retry_after":32}

status: fail
retry_after: 32
reason: guessed_too_fast

I am interested to donate.

Thanks

Best REgards

**Comment by jlguardi** [comment]
First of all, you can donate with the link in the Readme.md (main page of the repository). I'm sure that tgalal will thank you. 
About your issue:
- you can't request code from an android device and use it in the app. You use different IDs and it will not work. 
- you are using mnc 39 b seems to be 02 asking lookups. 
- wait for 30 min and ask fo voice call from yowsup. Probably it'll work.

**Comment by fbpinheiro** [comment]
Oi Danilo, comigo ocorreu o mesmo, " status: sent " mas não recebi o código.

**Comment by DaniloMurbach** [comment]
Yes, fbpinheiro.

I realy dont know if something change in Brazilian PSTN, since today. Yesterday i registred, twice.


But today this issue is happening.

**Comment by jlguardi** [comment]
If no news about that, I guess fixed (temporal issue). Reopen if necessary.
