### ISSUE TITLE
About the Acks,  threading.Condition() and the self.lock.acquire and lock release and the demo cli

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1474]
seeing the source code for the demos some files has   threading.Condition() and others not.... i need to now why is the reason threading.Condition() and the self.lock.acquire, acks and release on demos. why i dont see on the cli demo this option what is the function for that sorry im beginer on python threads how ever

**Comment by freelo** [comment]
Are you talking about sendclient? There is no reason for Condition, it could be a simple Lock as well. The obvious reason here is that both methods modify the simple python list `self.ackQueue`. I these methods were not synchronized, you might get multiple 'message sent' messages when sending multiple messages at once. The way it is implemented, you will only receive one single confirmation after all acks for all messages were received.
Having said that: the lower yowsup layers should be working without synchronization. It's just the application logic.

**Comment by minimaldev** [comment]
so i can use the send client without the thread condition and  self.lock.acquire and self.ackQueue??

**Comment by freelo** [comment]
Yes, simply strip it down/extend it to your needs and test it. After that -- if you think yowsup behaves incorrectly -- don't hesitate to ask a specific question.

**Comment by minimaldev** [comment]
but i use the echo and send layer both layer in one stack and when receive the messages from whatsapp to my phone ok but at the same time when i send the message is not working and not sending the message

**Comment by jlguardi** [comment]
Are you using both layers in parallel?  Otherwise it will not work.

**Comment by minimaldev** [comment]
yes im using in parallel why i cant use in parallel if the stack by layers and the layers uses two diferente methods i dont what connect and disconect to send and receive messages and seeing the cli demo never disconnect and connect

**Comment by freelo** [comment]
Please use the nice character '.' more often. It makes it a lot easier to understand what you mean when talking about parallel or not parallel and layers and stack and different methods and connect and disconnect and send and receive and the cli demo or things that work and that dont. Thanks :)

**Comment by minimaldev** [comment]
@freelo so i never can create or use a layer for read and send messages its not posible be connected while sending and reading messages ??. in this case y only can disconnect and connect for read messages or disconnect and connect for send messages ?

**Comment by freelo** [comment]
I think jlguardi meant to tell you that you should use YowParallelLayer. And you said you *are* using in parallel.
Have you read the wiki?
https://github.com/tgalal/yowsup/wiki/Architecture

**Comment by minimaldev** [comment]
@freelo yes i read but my question i can use the send layer and echo layer at the same time with YowParallelLayer?. and if i used it i can read and send messages ?

**Comment by jlguardi** [comment]
@minimaldev yes, you can! Whatever you receive a message, it is passed to both layers (they are in parallel). Send layer will ignore and echo layer will response end ack. 
When you send a message from send layer or echo layer, it is passed to stack.

**Comment by minimaldev** [comment]
@jlguardi but use the both layer and Send layer dont send the messages to whatsapp but Echo layer works as well

**Comment by jlguardi** [comment]
Be careful due to incoming acks are just managed if sent by send layer (if you copied demos/sensclient/layer as is). 
Answering your initial question: locks and queue are just to send a message without ack any other incoming messages/notifications. However, it avoids a continous running of your applications.
@minimaldev post your stack.py and layers.py or just send to me (mail in my profile).

**Comment by minimaldev** [comment]
@jlguardi  email sent
