### ISSUE TITLE
Problem (Re)registering

### ISSUE THREAD

**Issue by DumperJumper** [tgalal/yowsup#1480]
Hey I didnt work with yowsup for a while and today I tried to start it up again.

Of course I first had to update and run the setup.py again.

Now Im trying to reregister but I run into an Error:

```
pi@raspberrypi ~/yowsup-04-16 $ yowsup-cli registration -R 9S5WvZkEXXXXXXXXXXXXXX= -c config
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"missing"}

status: fail
reason: missing
```

config contains the following:

```
## Actual config starts below ##
  cc=49 #if not specified it will be autodetected
  phone=4917XXXXXXXX
  password=9S5WvZkEXXXXXXXXXXXXXX=
```

What does the fail reason 'missing' mean? What should I do?

Thanks

**Comment by jlguardi** [comment]
If you have a password, you are already registered. Don't use registration!
While registration, first use -r sms and then -R received_code (in the sms).
