### ISSUE TITLE
Problem in setup.py yowsup

### ISSUE THREAD

**Issue by haidarCheaito** [tgalal/yowsup#1482]
that's the error part of the log please help me with this issue

Writing /tmp/easy_install-pt8QeX/python-axolotl-curve25519-0.1/setup.cfg
Running python-axolotl-curve25519-0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pt8QeX/python-axolotl-curve25519-0.1/egg-dist-tmp-xpFvCX
In file included from /usr/include/python2.7/Python.h:44:0,
                 from curve25519module.c:3:
/usr/include/unistd.h:992:4105: error: macro names must be identifiers
                                                                                                                                                                99309 */
                                                                                                                                                                ^
In file included from /usr/include/python2.7/Python.h:44:0,
                 from curve25519module.c:3:
/usr/include/unistd.h:989:0: error: unterminated #if
 #if defined __USE_BSD || defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8
 ^
In file included from /usr/include/python2.7/Python.h:44:0,
                 from curve25519module.c:3:
/usr/include/unistd.h:22:0: error: unterminated #ifndef
 #ifndef _UNISTD_H
 ^
curve25519module.c: In function ‘calculateSignature’:
curve25519module.c:50:20: warning: pointer targets in passing argument 1 of ‘curve25519_sign’ differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                    ^
curve25519module.c:17:5: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:31: warning: pointer targets in passing argument 2 of ‘curve25519_sign’ differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                               ^
curve25519module.c:17:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:43: warning: pointer targets in passing argument 3 of ‘curve25519_sign’ differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                                           ^
curve25519module.c:17:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:64: warning: pointer targets in passing argument 5 of ‘curve25519_sign’ differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                                                                ^
curve25519module.c:17:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c: In function ‘verifySignature’:
curve25519module.c:76:36: warning: pointer targets in passing argument 1 of ‘curve25519_verify’ differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                    ^
curve25519module.c:22:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_verify(const unsigned char* signature,
     ^
curve25519module.c:76:47: warning: pointer targets in passing argument 2 of ‘curve25519_verify’ differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                               ^
curve25519module.c:22:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_verify(const unsigned char* signature,
     ^
curve25519module.c:76:58: warning: pointer targets in passing argument 3 of ‘curve25519_verify’ differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                                          ^
curve25519module.c:22:5: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 int curve25519_verify(const unsigned char* signature,
     ^
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by thundergreen** [comment]
I would day install gcc

Thorsten Fröhlich
Am 09.04.2016 05:52 schrieb "haidarCheaito" <notifications@github.com>:

**Comment by haidarCheaito** [comment]
i checked gcc is installed and it still the same problem

**Comment by tgalal** [comment]
nothing wrong with setup.y
