### ISSUE TITLE
wa16 Issues

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1486]
I had some issues with acks on wa16 branch, messages stopped coming because of missing acks etc... took the time and managed to make it work for me. It still crashes on some media files, otherwise works perfectly... Just modified some lines on axolotl layer.

#1485

**Comment by thundergreen** [comment]
@Gab0 can u share your modified repo?

Thorsten Fröhlich
Am 10.04.2016 10:10 schrieb "Gab0" <notifications@github.com>:

**Comment by schoerg** [comment]
@thundergreen click on #1485 you'll see the code there.

**Comment by Gab0** [comment]
It worked for some time, until got a stack of four messages which can't be acked..
