### ISSUE TITLE
EchoClient is sending extra characters to response.

### ISSUE THREAD

**Issue by larrysuarez** [tgalal/yowsup#1487]
Hi,
Recently the code i wrote using the echoclient as a sample is sending me back extra characters for each message sent.
For instance, when i send the msaage "hello" i get the echo "elloLLLLLLLLLLLLLLLLLLLLLLLLLLLL"

I've tested the program given in this page as an example (layer.py and run.py) getting the same result.

I don't know if this is related to the end-to-end encryption behavior, but if you know how to solve the issue or changes in code i have to do, please let me know.

![image](https://cloud.githubusercontent.com/assets/18376576/14409349/e847efb0-fed5-11e5-88eb-c6e0abedbeae.png)
Thanks in advance.

**Comment by SoumenDas** [comment]
Having same problem

**Comment by smartm13** [comment]
https://github.com/tgalal/yowsup/issues/1356

**Comment by jlguardi** [comment]
#1497.
