### ISSUE TITLE
Can't send messages

### ISSUE THREAD

**Issue by Falco33** [tgalal/yowsup#1488]
Not sure if this is the right place to ask, but I'm currently trying some things with yowsup, and can't seem to actually send a message via cli. It worked before, but now it doens't seem to work anymore. 

Here is the debug log: 

`[connected]:/message send xxxxxxxxxxx test
DEBUG:yowsup.layers.logger.layer:tx:
<message to="xxxxxxxxxxx@s.whatsapp.net" type="text" id="1460319796-14">
<enc type="msg" v="2">
3
!<9Xj▒▒▒dX▒▒O%▒@▒r▒s▒f▒▒/▒▒▒▒G;"▒[▒▒
▒#      ˁM▒Q▒   ▒▒*▒▒
HEX:330a21053c1739586a8ee2ca645882a0044f25d240ee72e9739e66b4e32fa3ecd4d1473b100218012210df5b928608db080ae2192309cb814d8d51ad09cde12a879b
</enc>
</message>

[connected]:PuTTYDEBUG:yowsup.layers.logger.layer:rx:
<ack t="1460319790" from="xxxxxxxxxxx@s.whatsapp.net" class="message" id="1460319796-14">
</ack>

Not sure if this is all you guys need, please let me know if more information is required. 

Sent: 1460319796-14
[connected]:
DEBUG:yowsup.layers.logger.layer:rx:
<receipt from="xxxxxxxxxxx@s.whatsapp.net" id="1460319796-14" t="1460319791">
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="xxxxxxxxxxx@s.whatsapp.net" id="1460319796-14" class="receipt">
</ack>
`

**Comment by jlguardi** [comment]
Start yowsup-cli demos -y -d -c config end pass /L. You should have too many acks unmanaged. If fails, post logs.
