### ISSUE TITLE
Can't Register - Old Version

### ISSUE THREAD

**Issue by wilsaad** [tgalal/yowsup#1489]
Error to register new number.
i've updated to last version and receive this response when try to register new number.

![captura de tela 2016-04-11 as 09 44 50](https://cloud.githubusercontent.com/assets/11995262/14429182/51c3c0dc-ffca-11e5-9e6e-672867013537.png)

**Comment by jlguardi** [comment]
You aren't up to date. Update and check the correct install.

**Comment by wilsaad** [comment]
You are correct.
i do now, but the answer is i'm blocked.
i'll try another number and post here again.

Thanks and best regards.
