### ISSUE TITLE
Documentation update for Signals

### ISSUE THREAD

**Issue by bmellink** [tgalal/yowsup#149]
The Yowsup library documentation has the wrong number of arguments for some signals. Until now I found:

notification_contactProfilePictureUpdated(str jid,long timestamp,int messageId,bool receiptRequested), has an addition argument pictureID between messageId and receiptRequested

notification_groupPictureUpdated(str jid,str author,long timestamp,int messageId,bool receiptRequested), has an addition argument pictureID between messageId and receiptRequested

group_messageReceived(int messageId,str jid,str author,str content,long timestamp,bool receiptRequested), has an additional argument pushName at the end.

group_addParticipantsSuccess(str gjid, str jid) - takes 2 args and not 1 as in doc

group_removeParticipantsSuccess(str gjid, str jid) takes 2 args and not 1 as in doc

Can you please update the doc file? thanks

**Comment by tigrom** [comment]
Yowsup has a long list of signals you can register to with callbacks. The signals are emit according to different messages received from Whatsapp. See full list of signals

the link is not set, please send link with full list of signals.

thx
