### ISSUE TITLE
Not connected

### ISSUE THREAD

**Issue by EliasinnKamachoo** [tgalal/yowsup#1491]
Hello, for a couple of days ago I've been working with yowsup . Accomplish register but when entering the command screen yowsup throws me that I am not connected . I have my login and my password , a way to enter and connect to yowsup .

cd /home/pi/yowsup 
yowsup-cli demos --yowsup --config config
/message send 507xxxxxxxx "hello"

Following the above command causes a erro and exit the command line yowsup .

yowsup-cli demos --config yowsup/config --send 5219999999999 “Hello”

While this command tells me that I am not connected. Greetings and thanks for your attention.

**Comment by freelo** [comment]
Have you tried "/L", which is meant to connect and log in? What is the error you get?

**Comment by jlguardi** [comment]
Report logs. Add -d flag to both commands.

**Comment by EliasinnKamachoo** [comment]
Hello jlguardi and freelo:

Here are the steps using the -d commands. I have been researching and find no solution to the problem . I attach a terminal file.txt command . I 'm working on a Raspbery Pi with Jessie based image. Greetings and thanks for your attention , any solution that gladly listen.

[xL.txt](https://github.com/tgalal/yowsup/files/220405/xL.txt)

**Comment by jlguardi** [comment]
Skmsg (group encrypted messages) aren't supported by master. Use my master or wa16 for that (both wit work in progress).
