### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by anativ** [tgalal/yowsup#1492]
Yesterday my two numbers just got banned after running without a problem for a few weeks.
Anyone know anything about changing in the "banned" algorithm?

Thanks,

**Comment by rami-dabain** [comment]
were you sending and receiving?

**Comment by blr246** [comment]
Does your app list groups frequently? I suspect this got me banned at one point.

**Comment by anativ** [comment]
Sorry, seems like a bug... sending to a wrong number

**Comment by marvinmarnold** [comment]
I also got banned after running the echo client and receiving just a few messages over a few hours.
