### ISSUE TITLE
pkmsg error ;O

### ISSUE THREAD

**Issue by K4CZP3R** [tgalal/yowsup#1493]
Hi, i've used yowsup month ago and it worked but today i updated it to newest version. 
And when i'm loging in, error `"assert encType in "pkmsg", "msg" AssertionError: msg"`.

I've deleted *.db from .yowsup.

**Comment by jlguardi** [comment]
Here it is missing square brackets around both ["pkmsg","msg"]. 

Anyway, group messages will be fail on master version (use my master or wa16. Both are  work in progress).

**Comment by K4CZP3R** [comment]
But they will work in groups?

**Comment by jlguardi** [comment]
My master is more or less working. No major issues reported.
I can't confirm about wa16
