### ISSUE TITLE
Number re-registration?

### ISSUE THREAD

**Issue by yniwly43** [tgalal/yowsup#1495]
Hi there,

I have a WA account which I use for a home hobbyist project. I control various controllers in my house via WhatsApp. I don't send any messages, only receive them. Never did Sync. I also installed this same system in my girlfriend's house.

I use the latest Yowsup, updating it every few months, and the connection remains open indefinitely, or until it gets disconnected. Usually with a:

```
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>
```
message, and then I know it's time to update the token. (I use the S40 env).

However, though this mostly works well, sometimes I get a Not Authorized: not-authorized error when I try to reconnect. And then I either have to re-register or sometimes wait 60 days (banned).

My questions are these:

* Why does this happen? I am certain my activity is not illegal nor abusive, I don't even send messages.
* Is it possible that I need to renew the password, or do some other action, every week or two, or based on a message received from the WhatsApp servers, and when I don't do that - I get disconnected/banned?

Thank you!

**Comment by yniwly43** [comment]
I am pretty certain this is related to the latest bans that everyone have been seeing, recently..

**Comment by jlguardi** [comment]
Third party software is not allowed by wa. And now they are banning a lot of people with any special reason.
