### ISSUE TITLE
Error: yowsup.layers.axolotl.layer: No Session

### ISSUE THREAD

**Issue by Matzoer** [tgalal/yowsup#1496]
Hi,

after upgrading yowsup to the latest version and changing these two lines:
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1447796090073{phone}"
_VERSION = "2.14.21"
in the env_s40.py file I get the following error when logging in:
http://imgur.com/BhXXwEZ

I hope you can help!

**Comment by jlguardi** [comment]
Send a messag to recipient a it will work next time.

**Comment by Matzoer** [comment]
Thanks for the quick answer, I will try this tomorrow around 9:00AM CEST. I will tell you if the problem is solved then.
