### ISSUE TITLE
Received messages are broken or cut off

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1497]
HI, 

if I send to my number "Ja" (German for Yes) , I receive "a▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"  
(J has been cut off and lots of strange characters following).

Or if I send "ll", I receive "l▒▒▒▒▒▒▒"
I send "Klll", I receive "KllRRRRRRRRRRRRRRRRRRRRRRRRRRR"

and so on.

Does anyone has an idea what is happening here? I am using Version "yowsup-Android_2.12.440"
 
Thanks you any help.

**Comment by McBacker** [comment]
Apply this "fix":

https://github.com/tgalal/yowsup/issues/1356

**Comment by kw005** [comment]
ok. worked. Thanks a ton!!!
