### ISSUE TITLE
Immediately blocked on latest version when requesting sms

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#1505]
Immediately blocked on latest version when requesting sms
tried 7 numbers, on 3 different IPs (Office, Home, Mobile Data) ..
always get the following:

```
root@XXX:XXX# ./yowsup-cli registration --requestcode sms --phone CCXXXXXXXXXX --cc CC
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

status: fail
reason: blocked
```

any reason why i get those twice ?
Thanks!

**Comment by jlguardi** [comment]
Numbers should be already blocked. Otherwise you can block all whatsapp numbers. They can't block you before code upload.

**Comment by rami-dabain** [comment]
Numbers were working fine, suddenly all of them got "Unauthorised", except few.

**Comment by jlguardi** [comment]
Yes, of course. So the issue subject is incorrect, they were blocked while running and you detected while sms request. However the request isn't the cause.

**Comment by rami-dabain** [comment]
Just tried 2 new numbers ... same

**Comment by rafaelpstein** [comment]
same problem

**Comment by jlguardi** [comment]
@all are you using tgalal/master (2.4.102) or my master/devel?
Related with https://github.com/jlguardi/yowsup/issues/75
and
https://github.com/jlguardi/yowsup/issues/74
I see a possibl cause but I need to know which version are you using.

**Comment by thundergreen** [comment]
@jlguardi I used your repo as it was well maintained ... Bit now I have
been f**** searching for an alternative to register for wa again. Only have
one number.

Thorsten Fröhlich
Am 15.04.2016 22:12 schrieb "jlguardi" <notifications@github.com>:

**Comment by yniwly43** [comment]
#1512
