### ISSUE TITLE
Send message not working.

### ISSUE THREAD

**Issue by gabriel2012** [tgalal/yowsup#1510]
Hi , again , sorry , but i have a litle problem , i can't send any message , this is the debug:

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="+++++++++++" mechanism="WAUTH-2">
���F�E�J��x����5{Tz�����|Ϊ�?�EY�������9
HEX:aed6038746f745984a88e778abc215ebc4357b54057ab0c3f3ad8c7cceaa9e3f8d4502591fa0a5fdb0be9d07af390f
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by jlguardi** [comment]
Try "yowsup-cli -y -d -c config" and login with /L.

**Comment by gabriel2012** [comment]
With that line y have this result  , I tested that with 2 numbers:

yowsup-cli demos -y -d -s xxxxxxxxxxxxx hola -c /root/AR.txt -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:

**Comment by gabriel2012** [comment]
With that line y have this result , but with other number the connection is successfully ,but the message never come when i send some message

DEBUG:yowsup.layers.network.layer:Connecting to e8.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="xxxxxxxx" mechanism="WAUTH-2">
ʭ�F�E�J��x����5{Tz�����|Ϊ�?�EY�������8
HEX:caad01c046f745984a88e778abc215ebc4357b54057ab0c3f3ad8c7cceaa9e3f8d4502591fa0a5fdb0bf9604a2380e
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
