### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by wilsaad** [tgalal/yowsup#1512]
Hi there.

every things gone normal, but a few hours ago, we receive this message.

yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Authentication Error: not-authorized

i need to request new register ?

**Comment by jlguardi** [comment]
Now you are banned :(

There are many comment with this topic.

**Comment by mvzeppelin** [comment]
Hello,

I have the same problem. I used to use a number to send messages in my servers. Today all of them stop working. 

I can't send messages and I can't register any more. My number was blocked.

So, I went straight to the store and bought another number. 
I cound register and send messages with my new number successfully. But after at most 20 messages, my new number was blocked as well.

There's anything we could do?

thanks.

**Comment by danf22** [comment]
I have the same problem

**Comment by jegue** [comment]
Same here just today happned

**Comment by MrDarkStone** [comment]
Same Problem my number is now blocked :(

**Comment by Cramac** [comment]
Тоже самое.

**Comment by tinet** [comment]
Hi,

This is a new problem.
It happens since yesterday (04/15/2016) 18:00 UTC.

**Comment by paivatulio** [comment]
I have the same problem. Why this issue was closed?

**Comment by yniwly43** [comment]
Relevant discussion with more explanations:
https://github.com/mgp25/Chat-API/issues/1840

Possible solution for personal users:
https://github.com/tgalal/yowsup/issues/1524
