### ISSUE TITLE
Problem_ AssertionError: msg

### ISSUE THREAD

**Issue by EliasinnKamachoo** [tgalal/yowsup#1515]
Here are the steps using the -d commands. I have been researching and find no solution to the problem . I attach a terminal file DEBUG.txt command . I 'm working on a Raspbery Pi with Jessie based image. Greetings and thanks for your attention , any solution that gladly listen.

[DEBUG.txt](https://github.com/tgalal/yowsup/files/222520/DEBUG.txt)

**Comment by tgalal** [comment]
Fixed in [wa16](https://github.com/tgalal/yowsup/tree/wa16) branch and merging it soon
