### ISSUE TITLE
Auto recover connection from stream:error

### ISSUE THREAD

**Issue by tgalal** [tgalal/yowsup#1518]
```xml
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
```
- Expose a property somewhere to allow auto reestablishment of the connection
- Reconnect if the property is set to True
- Raise an exception if the property is false , carrying the reason along.

**Comment by assegaf** [comment]
@tgalal not sure if this is the cause of the problem,  but it could be one of this.
1. When in process of getting inbound RX which the data not yet finished fetched, we send TX. which server block with reply stream error. So might need synchronous block between RX and TX.
2. when in proses of sending TX and not yet done, we send another TX (example when ack delivery report delivery/read) etc ..

**Comment by tgalal** [comment]
@assegaf you are right, it happens when 2 threads are sending at same time
