### ISSUE TITLE
general: Login Failed, reason: not-authorized

### ISSUE THREAD

**Issue by tinet** [tgalal/yowsup#1519]
Hi all,

Yowsup was working properly without errors till 04/15/2016 18:00 UTC, sending whatsapp messages each hour.

Version:
yowsup-cli v2.0.15
yowsup v2.4.102

From this date (04/15/2016 18:00 UTC) was not working anymore.
Trying the yowsup-cli, I get this error when I try to login (/L command):

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

Has something changed in the whatsapp server authentication algorithm?
Can anybody check if yowsup is working properly in his system?

Thanks,
Agusti

**Comment by tgalal** [comment]
You can also try and check the other issues before posting a new one

**Comment by yniwly43** [comment]
#1512
