### ISSUE TITLE
Plans for master branch update?

### ISSUE THREAD

**Issue by jroman** [tgalal/yowsup#1520]
Just wondering... Are there any plans for the update of the `master branch` so it becomes operative again?

Thanks all!

**Comment by tgalal** [comment]
no. master branch will be kept in non operative state FOREVER  -.-

**Comment by jroman** [comment]
Catch it.

So, now, the replacement and operative branch is... ?

Thanks!

**Comment by yniwly43** [comment]
#1512

**Comment by jroman** [comment]
Sorry @yniwly43 , I followed the link and did not find an answer to my question...

Should I go for ` wa16`?

Thanks
