### ISSUE TITLE
How to generate a proper random Id string?

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#1523]
Not a question related to yowsup directly, but i don't know where else to ask, so, if you can, help me with this:

I'm using a get call like this to check if a number is already banned on whatsapp or not:
https://v.whatsapp.net/v2/exist?cc=86&in=13076790604&id=em8%d4%ec%f7km%2c.%f1%e4%12%3E%403%0b%12ir&&lg=en&lc=CN

I'm not explaining the reason cause is not interesting, but i want to know how to generate a "proper formatted" random (yes, random) "id" parameter, that will be accepted by whatsapp (accepted mean that the query will not fail).
Which rules i should follow to properly generate a RANDOM correctly formatted "id" parameter?  
Thanks!!

**Comment by tgalal** [comment]
[generateIdentity](https://github.com/tgalal/yowsup/blob/master/yowsup/common/tools.py#L35)
