### ISSUE TITLE
Unblock number for wa

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1524]
Got an success in reactivation of my number ! Just send an email to the support and ask them what's going wrong there .I had to send screenshots of proper wa install and they will unblock my number

**Comment by t0rr3sp3dr0** [comment]
You just regular screenshots of WhatsApp, or there was some message/warning/error in WhatsApp screenshot?

**Comment by thundergreen** [comment]
I wrote like a victim ;) I just had to send t a screenshot which shows that
I try to activate wa with the original client.also the blocked message I
sent . waiting the response and will keep you  posted

Thorsten Fröhlich
Am 18.04.2016 20:51 schrieb "t0rr3sp3dr0" <notifications@github.com>:

**Comment by biji** [comment]
anybody else success unblocking?

**Comment by yniwly43** [comment]
#1512

**Comment by peret2000** [comment]
I am blocked using the number through yowsup. But it works in the official WA application. I am sharing the number in both systems (using the same passwords, it used to work days ago). So, how can you manage to ask Whatsapp to unblock your number if your number works ok in WA application? I cannot say that WA is blocking my number from yowsup...

**Comment by jlguardi** [comment]
@peret2000 how do you get a valid password fo yowsup and wa simultaneously? It is possible just with pw extractor. Otherwise, whenever you register your number, you invalidate the previous password, so not-auth message. 
I suggest you to us a number just for yowsup to avoid your personal number to be banned.

**Comment by peret2000** [comment]
There are ways to get WA password (www.digitalinternals.com/security/extract-whatsapp-password-android/374/ for example) . As long as you use the same one, I guess it should work; at least, it worked for me in the past. I have been banned from yowsup, but it continues to work from WA application, with the same password.
It is true that before sharing the password, I tried to register the phone number through yowsup as if it was not used in WA aplication, and I got blocked also in the WA application. Then, I repeated the registration through WA application and it worked okay. After that, I got the password, as I have described, and I got blocked from yowsup but okay with WA application

**Comment by jlguardi** [comment]
This method for password extract isn't valid for lastest apks. Use old wa version for that.

**Comment by peret2000** [comment]
Thanks for the info. You mean that I should install an older WA apk in my Android and the register through the application? in such case, I guess that the difference is that file 'pw' would be a different one. The problem is to get that older version :(

**Comment by jlguardi** [comment]
See #1584

**Comment by peret2000** [comment]
Thanks a lot. Now, I am wondering whether I can continue to have the same phone number active in both mi Android official WA apk and yowsup. According to what I have understood of the procedure you are saying, I must get a new password using an olf WA apk version. With such password, I must configure yowsup. Now, yowsup should work, and probably my WA apk will also work. But, if I then update WA apk to the latest version again, it will generate a new password. So, I do not think that yowsup will continue to work, Am I right?
thanks a lot again

**Comment by charanjit-singh** [comment]
```
    def Msgrecieved:
        double check
        time.sleep(random.randrange(1,3))
        double check blue

    def send_msg:
        double check
        time.sleep(random.randrange(2,5))
        Available Presence
        time.sleep(random.randrange(1,2))
        check blue
        time.sleep(random.randrange(1,2))
        STATE_TYPING
        time.sleep(random.randrange(2,3))
        send additional message
        time.sleep(random.randrange(5,7))
        STATE_TYPING
        time.sleep(random.randrange(2,3))
        STATE_PAUSED                            1778 tgalal
        time.sleep(random.randrange(1,2))
        STATE_TYPING
        time.sleep(random.randrange(4,5))
        send msg
        STATE_PAUSED
        Available Presence
        time.sleep(random.randrange(1,2))
        Unavailable Presence 

```


Use these steps to avoid blocking..
Works for me. 

And Don't connect and Disconnect WA more than 2-3 times....
