### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by Aydar77** [tgalal/yowsup#1525]
Hello, today again the problem started

/usr/local/share/zabbix/alertscripts/yowsup-master/yowsup/demos/sendclient/stack.py:33: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  print("Authentication Error: %s" % e.message)
Authentication Error: not-authorized

**Comment by tgalal** [comment]
[https://github.com/tgalal/yowsup/issues?utf8=%E2%9C%93&q=not-authorized](https://github.com/tgalal/yowsup/issues?utf8=%E2%9C%93&q=not-authorized)

**Comment by yniwly43** [comment]
#1512
