### ISSUE TITLE
2 numbers blocked

### ISSUE THREAD

**Issue by tdrimmelen** [tgalal/yowsup#1526]
Hi,

I am using YowSup to send messages out of Zabbix. This went fine for 2 weeks but over the last daya, 2 of my phone numbers got blocked.

I got in touch with WhatsApp support and their reply is:

_Hi,

It appears that you are using an unauthorized application of WhatsApp. Unauthorized applications are not supported; they contain source code which WhatsApp can not guarantee as safe. Your private information is potentially being passed to 3rd parties. In addition, these may not function correctly and may cease to work at any given time.

Please uninstall your application and install an authorized version from:

www.whatsapp.com/download

After installing the authorized version, please reply to this email with a screenshot or an image of your screen from inside the app.

You can refer to your phone's user manual for detail steps of taking screenshots on your device.

Please note WhatsApp only works on smartphones, non-telephony devices including tablets are not supported.

Best Regards, 

WhatsApp Support Team_

Has someone seen a similar issue / reaction? Any idea what to do to YowSup working without being blocked by WhatsApp?

Theo

**Comment by tgalal** [comment]
"Has someone seen a similar issue / reaction? Any idea what to do to YowSup working without being blocked by WhatsApp?"

You realize there is a search box for finding an answer to such a question, right ?

**Comment by yniwly43** [comment]
#1512
