### ISSUE TITLE
global name 'YowsupEnv' is not defined

### ISSUE THREAD

**Issue by dusking** [tgalal/yowsup#1531]
Hey,

I saw previous posts on the issue, and it did help me to run yowsup2-cli.
But when I'm trying to run the simple Yowsup Echo client, I keep getting it.

I tried to install yousup using pip install, using python setup.py install, added the yowsup code to my project, added to syspath /usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup..

Any help? 

Thanks!

**Comment by tgalal** [comment]
Please learn to use the search function
