### ISSUE TITLE
Receive incomplete WhatsApps 

### ISSUE THREAD

**Issue by MauricioAHM** [tgalal/yowsup#1532]
Hi, I was wondering that someone knows how to solve this, or where can I find information about it.
I annex a picture where i have the problem. I received the text but not the first letter and symbols that the program doesn't recognize.
I'm running the command

sudo yowsup-cli demos --yowsup --config config

![captura de pantalla 49](https://cloud.githubusercontent.com/assets/18564255/14681916/bd0ca9a6-06e8-11e6-9c17-8d8a61e79520.png)

**Comment by mabbashm110** [comment]
what is the command you are using to receive texts
say if I have a number 3333333 with a hash password, how do I use to retrieve messages in the pool?

**Comment by rafaelsilverioit** [comment]
@MauricioAHM edit <b>yowsup/layers/axolotl/layer.py</b> as follows:

```python
# Workaround: original code was printing human-not-readable chars...
  def unpadV2Plaintext(self, v2plaintext):
    #if len(v2plaintext) < 128:
    #    return v2plaintext[2:-1]
    #else: # < 128 * 128
    #    return v2plaintext[3: -1]
    
    # lenght  of right padding
    end = -ord(v2plaintext[-1])
    # first k bytes are the message's lenght
    start = 0
    length = 0
    while length + start < len(v2plaintext) + end:
      length *= 127
      start += 1
      length += ord(v2plaintext[start])

  return v2plaintext[start:end]
```

**Comment by jlguardi** [comment]
See #1497.
