### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EliasinnKamachoo** [tgalal/yowsup#1533]
when linux operating system perfectly mail yowsup 2 ?

**Comment by yniwly43** [comment]
when the moon is in the seventh house and jupiter aligns with mars

**Comment by EliasinnKamachoo** [comment]
I meant , if that operating system is stable Yowsup , in other words, what  system  I can  send a mesage .

**Comment by jlguardi** [comment]
Linux uses the latest yowsup version. It's as stable as possible.
