### ISSUE TITLE
How to catch "Disconnected, reason: Connection Closed" event?

### ISSUE THREAD

**Issue by sattva1** [tgalal/yowsup#1535]
After some time staying online, i'm getting the following message in the log:

```
layer.py        2016-04-21 00:33:51,612 DEBUG: rx:
<iq type="result" from="[BOT]@s.whatsapp.net" id="367" t="1461191631">
</iq>

layer.py        2016-04-21 00:34:01,624 DEBUG: rx:
<stream:error>
<ack id="042C222E5BD9E9DB5F">
</ack>
</stream:error>

layer.py        2016-04-21 00:34:02,624 DEBUG: Disconnected, reason: Connection Closed
layer.py        2016-04-21 00:34:03,125 DEBUG: stopping ping thread
layer.py        2016-04-21 00:34:03,535 DEBUG: YowPingThread-1 - ping thread stopped
```

It happens silently, i.e. without any exception raised, the bot just ceases to respond. What would be a proper way to detect such an event and initiate a reconnection?

**Comment by biji** [comment]
see #1518

**Comment by sattva1** [comment]
Ok, so there is no facility at the moment to do it? Or does the connection event produce a notification entity so a handler could be added in the NotificationsLayer?

**Comment by sattva1** [comment]
Seems to be adding an EventCallback method (with an event ID from the YowNetworkLayer class) into the custom layer class is a way to go:

```python
    @EventCallback(EVENT_STATE_CONNECTED)
    def is_connected(self, ev):
        logging.info('Connected to WhatsApp servers')
        return True

    @EventCallback(EVENT_STATE_DISCONNECTED)
    def is_disconnected(self, ev):
        logging.warning('Disconnected from WhatsApp servers')
        raise DisconnectedError
```

At least the is_connected() method is being triggered as intended.
