### ISSUE TITLE
status: fail reason: old_version

### ISSUE THREAD

**Issue by fluqueval** [tgalal/yowsup#1537]
When registering by SMS gives me this error:
any solution? Thnx

./yowsup-cli registration --requestcode sms --phone 34xxxxxxxxx --cc 34 --mcc 214 --mnc 03 --debug
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.440 Android/4.3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=34&in=xxxxxxxxx&lc=GB&lg=en&sim_mcc=214&sim_mnc=003&mcc=214&mnc=003&method=sms&mistyped=6&network_radio_type=                                          1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7839&rchash=bfa515534bfd99f55f1ebf7635878c7d4a17d248229f584c3f0a187d2c771df3&anhash=-P%BB%14%89%95                                          %BA0v%CBef%E3%B1%A2%B9%DCTH%DE&extexist=1&extstate=1&token=PJNIXfDN72vlOf3feFvyRs3aS7U%3D&id=%DE%B4%0D%F5%EB%06%FEY%BF%93%CA7%1D%82t%AB%F3%BD%B7%D0
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=34&in=xxxxxxxxx&lc=GB&lg=en&sim_mcc=214&sim_mnc=003&mcc=214&mnc=003&method=sm                                          s&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7839&rchash=bfa515534bfd99f55f1ebf7635878c7d4a17d248229f584c3f0a18                                          7d2c771df3&anhash=-P%BB%14%89%95%BA0v%CBef%E3%B1%A2%B9%DCTH%DE&extexist=1&extstate=1&token=PJNIXfDN72vlOf3feFvyRs3aS7U%3D&id=%DE%B4%0D%F5%EB%06%FEY                                          %BF%93%CA7%1D%82t%AB%F3%BD%B7%D0
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by maq123** [comment]
I am getting the same for Dutch (31) mobile phone number.
Tried to change version in the code 'Version 2.16.35' and got error about 'bad token'.

**Comment by joschi99** [comment]
I am getting the sam error in Italy (39)

yowsup: 2.4.102
yowsup-cli: 2.0.15

**Comment by rafaelsilverioit** [comment]
Same here. Brazilian (55) number. All other solutions found before are not working now!

yowsup: v2.4.102
yowsup-cli: v2.0.15

**Comment by rafaelsilverioit** [comment]
Guys, edit the <b>yowsup/env/env_android.py</b> file as below:

```python
_MD5_CLASSES = "ry9Xz6kVioQctwA3G9z62Q==" # 
_VERSION = "2.12.556"
```

Then, try to register. 

```
INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":64,"sms_wait":64,"voice_wait":64}

status: sent
retry_after: 64
length: 6
method: sms
```

Thanks : https://github.com/mgp25/Chat-API/commit/e3f994059ab466fee6732e99b826de4733c3e9b5

**Comment by joschi99** [comment]
This works for me, thank you very much @rafaelsilverioit

**Comment by revil-O** [comment]
works like a charm, thx @rafaelsilverioit

**Comment by ritu-kang** [comment]
could you please tell us after how many days or when we should update these two parameters ?
is there way to get info about this?

**Comment by paoloap** [comment]
I applied the patch above, this way:

```
/ » sudo vim usr/lib/python3.5/site-packages/yowsup/env/env_android.py 

    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
    _MD5_CLASSES = "ry9Xz6kVioQctwA3G9z62Q==" 
    _VERSION = "2.12.556"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True
```
Note that I don't have a Galaxy S3 mobile phone (but a Huaweii one). I just let the default value.
Anyway, trying again the registration, I still get the error:

```
/ » yowsup-cli registration --requestcode sms --phone 39########## --cc 39 --mcc 222 --mnc 99 -d
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.common.http.warequest:{'User-Agent': 'WhatsApp/2.12.440 Android/4.3 Device/GalaxyS3', 'Accept': 'text/json'}
DEBUG:yowsup.common.http.warequest:cc=39&in=##########&lc=GB&lg=en&sim_mcc=222&sim_mnc=099&mcc=222&mnc=099&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9794&rchash=82f917fe1901dee2b305609d836caa1654871f3b9f719f90cb7d5b6df14388b5&anhash=%AA%C5%F0%B2%EFD%BE%2B%D4%C1%BB%0CV%ACD%5C%D7%E7%C0%DD&extexist=1&extstate=1&token=rkqJBVOVTkH4BTABo1hVWEo8r5M%3D&id=%DE%13j%5C%7D%DA%B5%0A%93%3E%96EB%A4-%21%99%D7%A1%1E
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=39&in=3926906850&lc=GB&lg=en&sim_mcc=222&sim_mnc=099&mcc=222&mnc=099&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9794&rchash=82f917fe1901dee2b305609d836caa1654871f3b9f719f90cb7d5b6df14388b5&anhash=%AA%C5%F0%B2%EFD%BE%2B%D4%C1%BB%0CV%ACD%5C%D7%E7%C0%DD&extexist=1&extstate=1&token=rkqJBVOVTkH4BTABo1hVWEo8r5M%3D&id=%DE%13j%5C%7D%DA%B5%0A%93%3E%96EB%A4-%21%99%D7%A1%1E
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
reason: b'old_version'
status: b'fail'
```

Can anyone help me? Maybe am I doing some mistakes?

**Comment by jonatascalebe** [comment]
@rafaelsilverioit Thanks a Lot. Your soluction works fine for me.

**Comment by jlguardi** [comment]
@paoloap Are you using python 2.7? I mean, you have edited the correct file but while running, android version remains 2.12.440 (see your log).
I could be due to you are aditing yowsup installed for python 3.5 and probably you are running 2.7.

Check again your linux env and file edition. And take a look into debug output to verify correct version.

**Comment by paoloap** [comment]
Hi @jlguardi , I tried this:

```
~ » python -V
Python 3.5.1
```

This is the right way to find out the version of Python which is actually running, right?
Thanks very much

**Comment by jlguardi** [comment]
Old-version issue fixed in latest master.

**Comment by MPetrashev** [comment]
Hi @jlguardi , I'm getting the same error in latest master. Any idea?
Thank you

yowsup-cli registration -r sms -p 44xxx -C 44 -m 234 -n 20 -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302', 'Accept': 'text/json'}
DEBUG:yowsup.common.http.warequest:cc=44&in=xxx&lc=GB&lg=en&sim_mcc=234&sim_mnc=020&mcc=234&mnc=020&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8078&rchash=3b2b
1c20283657ae45893df6397cdbd3d29d9abc8f853a54e987c7cfd923eecd&anhash=%BA%26%EBogC%DF%7D%F6%FDp%91%94%97%11%CCs%F5%A2r&extexist=1&extstate=1&token=3a52dc293a8ce77ae90abfb0a49e8316&id=5%3D%07%8F%1A%EC%D4%2B%28kH%A9%5
Els%82%EAad%D2
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=44&in=xxx&lc=GB&lg=en&sim_mcc=234&sim_mnc=020&mcc=234&mnc=020&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=
1&rcmatch=1&pid=8078&rchash=3b2b1c20283657ae45893df6397cdbd3d29d9abc8f853a54e987c7cfd923eecd&anhash=%BA%26%EBogC%DF%7D%F6%FDp%91%94%97%11%CCs%F5%A2r&extexist=1&extstate=1&token=3a52dc293a8ce77ae90abfb0a49e8316&id=
5%3D%07%8F%1A%EC%D4%2B%28kH%A9%5Els%82%EAad%D2
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'

**Comment by onizukaek** [comment]
Hi,

I have the same issue even if I force the environment to android, I am also working with the latest master.

DEBUG:yowsup.env.env:Current env changed to android 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'User-Agent': 'WhatsApp/2.16.7 Android/4.3 Device/Xiaomi-armani', 'Accept': 'text/json'}
DEBUG:yowsup.common.http.warequest:cc=41&in=765756344&lc=GB&lg=en&sim_mcc=228&sim_mnc=002&mcc=228&mnc=002&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7635&rchash=56c95542e7d10db2c39ddc083fb6e655e993d530e45d51f03b36ceff726c253c&anhash=%A5V%3C%AB4%07U%8B%9Cp%8A%89%8A%08%8D%08%10%3D%13%B7&extexist=1&extstate=1&token=u5qIunalo1sCNxF5ptH%2BWc%2BOczY%3D&id=%BAD%EA%F4x%3Ej%C0%9Fd%3C%21%A8%B8%C7%DA%A0%E0%CE%CD
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=41&in=765756344&lc=GB&lg=en&sim_mcc=228&sim_mnc=002&mcc=228&mnc=002&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7635&rchash=56c95542e7d10db2c39ddc083fb6e655e993d530e45d51f03b36ceff726c253c&anhash=%A5V%3C%AB4%07U%8B%9Cp%8A%89%8A%08%8D%08%10%3D%13%B7&extexist=1&extstate=1&token=u5qIunalo1sCNxF5ptH%2BWc%2BOczY%3D&id=%BAD%EA%F4x%3Ej%C0%9Fd%3C%21%A8%B8%C7%DA%A0%E0%CE%CD
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'

**Comment by jlguardi** [comment]
See #1716 and #1725.

**Comment by onizukaek** [comment]
Thanks jlguardi it worked for me! 
...until the next version update :)

**Comment by lfajardo** [comment]
Same problem, using python 2.7
No files/directories under /usr/local/lib/python2.7/site-packages/
In installation directory file env_android.py already contains the sugested parameters.
Log is like follows:
# yowsup-cli registration -p 346######## -m 214 -n 01 -C 34 -r sms -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=34&in=6########&lc=GB&lg=en&sim_mcc=214&sim_mnc=001&mcc=214&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1753&rchash=28fcbb2e352362ab5c43bf4aaf6c24633005cd6dd3d1ebb13df80885d84d7b98&anhash=%3C%21k%91%DF%9C%80%25%84+%29%F1c%0A0%E3%E1%A8%F5V&extexist=1&extstate=1&token=51f91262edfc763cb0b1c2ea7eb0c0c4&id=%04%B9%D9%0AL%06%03T%8A%9Cp0%D8Jl%2C%CDm%05%5E
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=34&in=687925188&lc=GB&lg=en&sim_mcc=214&sim_mnc=001&mcc=214&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1753&rchash=28fcbb2e352362ab5c43bf4aaf6c24633005cd6dd3d1ebb13df80885d84d7b98&anhash=%3C%21k%91%DF%9C%80%25%84+%29%F1c%0A0%E3%E1%A8%F5V&extexist=1&extstate=1&token=51f91262edfc763cb0b1c2ea7eb0c0c4&id=%04%B9%D9%0AL%06%03T%8A%9Cp0%D8Jl%2C%CDm%05%5E
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by rajatkapoor** [comment]
Any fix for this?

**Comment by pippopippo69** [comment]
same problem

**Comment by wease1** [comment]
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.9 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=7&in=9859735493&lc=GB&lg=en&sim_mcc=250&sim_mnc=001&mcc=250&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2803&rchash=266acc2826067226c216fb89a27bcd8dbf1f6bb60c07b961782463db7030dafa&anhash=%25%CAY%F8%2F%D9%9B%0E%D2c%E1%EEAY%AF%9D%F3%868b&extexist=1&extstate=1&token=0e9a19270609350382c5c5c75a117a42&id=%D9%99%E2l%B9%8E%15%96A%94%7E%F6%B9E%07%2Ah%B0%98%AD
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=7&in=9859735493&lc=GB&lg=en&sim_mcc=250&sim_mnc=001&mcc=250&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2803&rchash=266acc2826067226c216fb89a27bcd8dbf1f6bb60c07b961782463db7030dafa&anhash=%25%CAY%F8%2F%D9%9B%0E%D2c%E1%EEAY%AF%9D%F3%868b&extexist=1&extstate=1&token=0e9a19270609350382c5c5c75a117a42&id=%D9%99%E2l%B9%8E%15%96A%94%7E%F6%B9E%07%2Ah%B0%98%AD
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
@wease1 Use s40 version 2.16.11. You can get env_s40.py file from my master. See other open/close issues.

**Comment by stefanstranger** [comment]
Hi @jlguardi I have in my env.py "s40" as default and I changed the env_s40.py to what you have in your env_s40.py

    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"
    _AXOLOTL = True

Still getting the fail message.

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

Any other ideas?

Thanks for all youre help here.

Stefan

**Comment by LeVadim** [comment]
Same issue

**Comment by Neurotec** [comment]
same issue

**Comment by nenadvulic** [comment]
+1

**Comment by tigerjack** [comment]
same here

**Comment by thmendes** [comment]
@tigerjack  https://github.com/tgalal/yowsup/pull/1889

**Comment by tigerjack** [comment]
@thmendes thanks, after changing the lines in env_s40 it works like a charm.

**Comment by charanjit-singh** [comment]
Please share those ones
