### ISSUE TITLE
Echo client demo issue

### ISSUE THREAD

**Issue by sidd-shah** [tgalal/yowsup#1542]
I just started exploring the yowsup lib and the registration worked like a charm. 
I am using the echoclient demo and for some reason the first letter of the message is being decoded incorrectly as below.
The message sent was Hi bot. I tried multiple times and once a while it does echo the correct message but majority of the times it prints the below.
Echoing i bot����������������������������������������������������������������������������������������������������������������������������������������������������������

Can you help what the issue might be?

**Comment by deval-maker** [comment]
Yes. I am also facing the same problem.

**Comment by jlguardi** [comment]
Already reported padding issue. Will be fixed with wa16 release or using my master.
