### ISSUE TITLE
message forward() doesn't work for media

### ISSUE THREAD

**Issue by msshapira** [tgalal/yowsup#1543]
Tested with echo client on the including the new merges on "develop" branch

**Comment by thundergreen** [comment]
Media only  works  in wa16 AFAIK

Thorsten Fröhlich
Am 24.04.2016 20:45 schrieb "msshapira" <notifications@github.com>:

**Comment by msshapira** [comment]
Wa16 merged to develop.

**Comment by jlguardi** [comment]
Encrypted media send isn't supported yet. So forward will fail. Wait for some days (I hope).

**Comment by jlguardi** [comment]
Working in develop or my master.

**Comment by msshapira** [comment]
I'll test, but I can't see any commit in develop that addresses this.

**Comment by msshapira** [comment]
tested (echo sample, develop branch) - media still not forwarded. Please reopen.
