### ISSUE TITLE
Port 5222 in Yowsup

### ISSUE THREAD

**Issue by 0xFlitz** [tgalal/yowsup#1545]
Hi,

I went over the code, and it seems the network layer works with e.whatsapp.net : 443 .. but doesn't whatsapp protocol works over 5222 ? 

I recorded an emulator network traffic and i see the traffic on 5222 ( unable to use the decoder to analyze it )..  What am i missing?

**1. WA uses 5222 port, how come yowsup use the 443 port ?
2. is the data in 5222 is encrypted? **

**Comment by tgalal** [comment]
@0xFlitz Is this an issue with yowsup ?

**Comment by assegaf** [comment]
wa use port 5222 or 443, which one can be openned, not many internet allow port 5222, so mostly port 443 is the common used.

**Comment by 0xFlitz** [comment]
@tgalal  - it was a question about yowsup usage and difference between yowsup and WA official client.
@assegaf  - Thanks. will research the bytecode to see how the official client decide which port to use. (probably test first port, then try the other)
