### ISSUE TITLE
No longer receiving messages

### ISSUE THREAD

**Issue by drmaposa** [tgalal/yowsup#1546]
Hi

My Yowsup was working fine until the last 4 hours.

When I login in from th commandline as

`yowsup-cli demos -y -l  USER:PASS`

I get this error

Yowsup Cli client
==================
`Type /help for available commands`

`[offline]:/L`
`Auth: Logged in!`
`[connected]:WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`Sent: 1461638646-1`
`[connected]:`
`WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`WARNING:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 31074`
`WARNING:yowsup.layers.axolotl.layer:Too many retries!! Going to send the delivery receipt myself!`

I did not change any code, I do not know what happened

**Comment by jlguardi** [comment]
Send a mess from yowsup to message sender. This is due he is sending a message encrypted with a shared key which you lost (probably you removed axolotl.db after last message of this person).

**Comment by drmaposa** [comment]
Ok thanks for the valuable info,
So do i need to reinstall yowsup and regenerate keys?

**Comment by tgalal** [comment]
Upgrade yowsup
