### ISSUE TITLE
general: Login Failed, reason: not-authorized DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure

### ISSUE THREAD

**Issue by jawadhussain** [tgalal/yowsup#1547]
hi ,
It was working fine last day but now i am unable to login . logs are below
general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

**Comment by tgalal** [comment]
Use the issues search box

**Comment by thundergreen** [comment]
Your number has been blocked  by WhatsApp

Thorsten Fröhlich
Am 26.04.2016 09:30 schrieb "jawadhussain" <notifications@github.com>:
