### ISSUE TITLE
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

### ISSUE THREAD

**Issue by tvcnando** [tgalal/yowsup#1548]
hello everyone, last updated yowsup and returned to work perfectly.
however today stopped sending the message and this error while trying to register.

------------------------------------
ola a todos, ontem atualizei yowsup e voltou a funcionar perfeitamente. 
porem hoje parou de enviar as mensagem e da este erro ao tentar registrar

**Comment by yniwly43** [comment]
You are yet another (innocent?) victim of Whatsapp changing their code and Yowsup not.. you can try again in a few months if things get ordered up somehow. We're working on it
