### ISSUE TITLE
PLEASE give us actual update if master works or still getting blocked

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1550]
since many users use different branches. (e.g. old or different branch) I would highly appreciate and call everybody who is using the actual master branch and give a short feedback if blocking issues appear.

Thanks guys! Just wanna avoid getting blocked again :+1:

**Comment by yniwly43** [comment]
there's the develop branch, but it still uses the old RC4 encrpytion and not the new Curve encryption, so it it barely functional.. but it does connect and sorta work.

**Comment by softcode2** [comment]
All my numbers getting blocked with VPS IP .
Problem still there
