### ISSUE TITLE
No routes issue while registering

### ISSUE THREAD

**Issue by kaptoxic** [tgalal/yowsup#1551]
Whatsapp is working fine both on my phone and on the web, but I get this error while registering (S60 device, tried adding country/operator codes that did not help, tried setting/changing some of the environment variables):
```
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}\n'
reason: b'no_routes'
retry_after: 3600
status: b'fail'
```

I have:
```
yowsup-cli  v2.0.15
yowsup      v2.4.103
```

**Comment by yniwly43** [comment]
Try registering from a different IP. You can't register VOIP numbers

**Comment by fnlopes** [comment]
Same problem here. 
Somebody ?

**Comment by thundergreen** [comment]
I tried again. Mcc and MNC are correct according to the wiki page.. but
error still persists :(


2016-05-07 19:23 GMT+02:00 fnlopes <notifications@github.com>:

**Comment by thundergreen** [comment]
osmc@osmc:~$ yowsup-cli registration --requestcode sms --phone
33781****** --cc 33 --mcc 208 --mnc 14
yowsup-cli  v2.0.15
yowsup      v2.4.103


                                                Copyright (c)
2012-2016 Tarek Galal
http://www.openwhatsapp.org


                                                This software is
provided free of charge. Copying and redistribution is
encouraged.


                                                If you appreciate this
software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate






INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}


                                                status: fail
retry_after: 3600
reason: no_routes


2016-05-09 9:19 GMT+02:00 Thorsten Fröhlich <thundergreen@googlemail.com>:

**Comment by jlguardi** [comment]
@thundergreen  Check your phone in https://www.twilio.com/lookup

**Comment by thundergreen** [comment]
"carrier": { "type": "mobile", "error_code": null, "mobile_network_code":
"15", "mobile_country_code": "208", "name": "FREE MOBILE"

2016-05-09 11:15 GMT+02:00 jlguardi <notifications@github.com>:

**Comment by thundergreen** [comment]
Still same problem. my credentials are correct

osmc@osmc:~$ yowsup-cli registration --requestcode sms --phone 33781852856 --
cc 33 --mcc 208 --mnc 15 -d
yowsup-cli  v2.0.15
yowsup      v2.4.103

      Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

      This software is provided free of charge. Copying and
redistribution is
encouraged.

      If you appreciate this software and you would like to support
future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


            DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'Wha
tsApp/2.16.6 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=33&in=781852856&lc=GB&lg=en&sim_mcc=208
&sim_mnc=015&mcc=208&mnc=015&method=sms&mistyped=6&network_radio_type=1&simnu
m=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9507&rchash=148b3e70c9fdafa856e3b4e
e4bc922679a5747ed267e55f322ac5bdeb0d25c04&anhash=%E7%23%99%B3%F3%97%E7%8F%E7%
DB%16a%F4%5E%AD%01%1BM%8E%ED&extexist=1&extstate=1&token=e576a2066d31847ef6ae
d194595375fe&id=u%17_zU%1D%89z%F0%88%2F%80%E5a%7D%601%FE%96%C2
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=33&in=7
81852856&lc=GB&lg=en&sim_mcc=208&sim_mnc=015&mcc=208&mnc=015&method=sms&misty
ped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=950
7&rchash=148b3e70c9fdafa856e3b4ee4bc922679a5747ed267e55f322ac5bdeb0d25c04&anh
ash=%E7%23%99%B3%F3%97%E7%8F%E7%DB%16a%F4%5E%AD%01%1BM%8E%ED&extexist=1&extst
ate=1&token=e576a2066d31847ef6aed194595375fe&id=u%17_zU%1D%89z%F0%88%2F%80%E5
a%7D%601%FE%96%C2
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retr
y_after":3600,"sms_wait":3600,"voice_wait":3600}

      status: fail
retry_after: 3600
reason: no_routes


2016-05-09 11:43 GMT+02:00 Thorsten Fröhlich <thundergreen@googlemail.com>:

**Comment by jlguardi** [comment]
sent message from my IP:
´´´
./yowsup-cli registration -r sms -p 33781852856 -C 33 -d 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Samsung-Galaxy S3'}
DEBUG:yowsup.common.http.warequest:cc=33&in=7818xxxxx&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=26024&rchash=cb838b35f04cd0eaxxx&anhash=c0cd8d060ca54xxxxxx&extexist=1&extstate=1&token=hquKS6lv1eOxxxxxx%3D&id=V%1Fi%D3%AE9%xxxxx
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=33&in=781xxxx&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=26024&rchash=cb838b35f04cd0ea453xxx&anhash=c0cd8d060cxxxx&extexist=1&extstate=1&token=hquKS6lv1eOQxxxxx%3D&id=V%1Fi%D3%Axxxx
INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":65,"sms_wait":65,"voice_wait":65}
´´´

Probalby IP banning but I've got usually temporary_unavailable on my home IP banning. If you are using a sever with static IP I don't know what kind of error is reported.

**Comment by thundergreen** [comment]
That's strange.just got a code from wa. It seemed to work will have to
verify now to get the password ..will keep u posted

Thorsten Fröhlich
Am 09.05.2016 12:40 schrieb "jlguardi" <notifications@github.com>:

**Comment by thundergreen** [comment]
Verifying the clode via cli not possible. why did i get the code? this
means it worked. but when i now try t o get the password yowsup tells me to
get the code first


2016-05-09 13:48 GMT+02:00 Thorsten Fröhlich <thundergreen@googlemail.com>:

**Comment by jlguardi** [comment]
@thundergreen I've sent to you the code but you can't use this code due to it's valid just for the Id that I've generated.
But I've tested that your number isn't the problem. At least without mmc, mnc. 
Try from scratch (remove Id file) in other IP.

**Comment by thundergreen** [comment]
Is it possible without MCC and MNC?  How can I remove this  ID file? Sorry
for this noob question

Thorsten Fröhlich
Am 09.05.2016 15:21 schrieb "jlguardi" <notifications@github.com>:

**Comment by jlguardi** [comment]
Yes, usually it works without network info. Remove $HOME/.yowsup/phone_number

**Comment by thundergreen** [comment]
how is this file called?

2016-05-09 16:42 GMT+02:00 jlguardi <notifications@github.com>:

**Comment by jlguardi** [comment]
Id

**Comment by thundergreen** [comment]
Hi sorry again.. i only have this in this filder:

osmc@osmc:~/.yowsup/33781852856$ ls

axolotl.db  nonce

2016-05-09 16:51 GMT+02:00 jlguardi <notifications@github.com>:

**Comment by jlguardi** [comment]
Sorry, nonce. But remove also axolotl.db to avoid future issues.

**Comment by thundergreen** [comment]
I removed both but it just doesn't work :( i will change IP again and try
again.... Thats weird

Thorsten Fröhlich
Am 09.05.2016 18:36 schrieb "jlguardi" <notifications@github.com>:

**Comment by jlguardi** [comment]
Related/duplicated with #1585.
