### ISSUE TITLE
issue with installing with python3.5 - curve25519

### ISSUE THREAD

**Issue by dusking** [tgalal/yowsup#1552]
Hey,

When I'm trying to install using python3.5 (sudo python3.5 setup.py install)
The installation failed on installing python-axolotl-curve25519, with error:
curve25519module.c:3:20: fatal error: Python.h: No such file or directory

Any idea how to solve it?

Thanks!

**Comment by tgalal** [comment]
@dusking Install python headers, if on ubuntu i think package is called python-dev

**Comment by dusking** [comment]
sudo apt-get install python3.5-dev solved it,
thanks :)
