### ISSUE TITLE
what's Iq_crypto?

### ISSUE THREAD

**Issue by jlguardi** [tgalal/yowsup#1557]
I was checking boot sequence and I find:
```
 self.toLower(CryptoIqProtocolEntity())
```
What's that? It's not called in Chat-API. Should it be called? every boot or just the first one?

**Comment by tgalal** [comment]
@jlguardi Experimental stuff, not sure if necessary at all

**Comment by jlguardi** [comment]
Thanks, I've removed from my boot sequence this Iq and also PrivacyListIqProtocolEntity and PushIqProtocolEntity. I'm no sure about their correct working and yesterday I got banned two passive lines.
