### ISSUE TITLE
question about proper contacts synchronization

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#1559]
Hi, guys.
What is the right way to call GetSyncIqProtocolEntity?
Only for newly added subscriber, or I have to pass  full contacts list to it every time for new subscriber adding?

**Comment by jlguardi** [comment]
You should pass full list after registration and a partial list for new people.
Use  first   MODE_FULL = "full" and  CONTEXT_REGISTRATION = "registration"
and then MODE_DELTA = "delta" and    CONTEXT_INTERACTIVE = "interactive"
