### ISSUE TITLE
Send and receive at the same time

### ISSUE THREAD

**Issue by johncordeiro** [tgalal/yowsup#1562]
I was using the SendStack to send messages and ListenStack to receive the messages separately. In this case when a new messages is sent, yowsup closes the listen connection. 

Now, I need to use the same connection to receive and send messages, without disconnection. Do I need a single stack for both? could you show me a sample of doing it?

**Comment by jlguardi** [comment]
Yes, you need just one stack. See yowsup/demos/cli/layer to see send/receive example.
