### ISSUE TITLE
yowsup-cli and EchoClient show as sending unencrypted messages in WhatsApp for Android

### ISSUE THREAD

**Issue by WindohsCrasher** [tgalal/yowsup#1567]
I installed yowsup2 using pip (Python 3) today and so far the library is working fine. However, although it has generated keys in ~/.yowsup/<phone number/ and python-axolotl is installed, my "bot" (using either yowsup-cli or the EchoClient demo) shows as sending unencrypted messages in WhatsApp for Android (when clicking on the contact). Is this a bug in the library or is there something wrong with my setup?

**Comment by jlguardi** [comment]
It is sending encrypted messages but yowsup current version doesn't support fully encrypted protocol (calls, video send...). So official client shows this message.
It will disappear in future releases.
