### ISSUE TITLE
Number blocked from the second contact sync

### ISSUE THREAD

**Issue by kobybm** [tgalal/yowsup#1571]
Hi and thank you for this great project.

(I'm going to write everything I've done since I don't know where is my problem)

I've created a new AWS (Amazon) instance with elastic IP ( region = North Virginia - BTW my n umber is not related to US at all (From Asia) ).
I have a new (Unused/untouched) SIM card.
OS type = Ubuntu 14.04

**Note: The phone numbers + MCC + MNC + CC was changed manually on this information (They were real number when I've done the procedure).**

Those are the commands that I've used to install yowsup and made the CLI work (Reminder - fresh ubuntu machine):
### Install yowsup:

   1  apt-get install git
    2  apt-get -y install git
    3  apt-get update
    4  apt-get -y install git
    5  apt-get -y install python-pip python-dev libjpeg-dev
    6  pip install yowsup2
### Apply hotFix 'hotfix/2.4.103':

   7  git clone https://github.com/tgalal/yowsup.git
    8  cd yowsup/
   15  cp **init**.py /usr/local/lib/python2.7/dist-packages/yowsup/**init**.py
   16  cp env/env_android.py /usr/local/lib/python2.7/dist-packages/yowsup/env/env_android.py_

Upgrade six:
   28  sudo pip install six --upgrade

Now I have a working yowsup-cli.
### So I will try to register:

(I've already done it with SMS and I got blocked before so I tought maybe Whatsapp will think I'm human when I will ask for Voice):
   38  ./yowsup-cli registration --mcc 123 --mnc 12  -r voice --cc 123 --phone 1234567890
   40  ./yowsup-cli registration --register 111111 --phone 1234567890 --cc 972
### I've got the password now! so I will try to sync my own phone with this new whatsapp account:

   43  ./yowsup-cli demos -S +1234567891  -c config
### Result was:

```
      INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
```
### So I will do it again:

root@ip-172-31-51-119:~/yowsup# ./yowsup-cli demos -S +1234567891  -c config
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Iq:
ID: 1
Type: result
from: 1234567890@s.whatsapp.net
Wait: 174665
Version: 1462432639411209
In Numbers: +1234567891
Out Numbers:
Invalid Numbers:

Yowsdown
root@ip-172-31-51-119:~/yowsup#
### Good! it's work! - Let try to sync another number:

root@ip-172-31-51-119:~/yowsup# ./yowsup-cli demos -S +1234567892  -c config
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

**Authentication Error: not-authorized**
_
Now it's blocked.
Any help will be much appreciate!!!

Thanks!

**Comment by tomerb15** [comment]
+1
Great Log! Hopefully it will help the community understand what is going on with all the blocking.

**Comment by ThomasMW** [comment]
I had two of my numbers blocked recently, I used them for messaging for an application I made to communicate with my users. They were working fine for a while. Then suddenly they got blocked and every other number I try to register get's blocked automatically (probably because they have banned the IP address associated with the platform I use).

So I emailed the support department and they say the numbers we're banned because I used an unofficial client. So I'm guessing they could already tell I wasn't using the official Whatsapp application.

**Comment by yniwly43** [comment]
Might be related, so I'm writing it here. I have one number that hasn't been blocked, out of like 10 that I tried when I was trying to figure it out. All ran exactly the same code. Same flow. Login, available, sync, subscribe (to like 10 numbers which have us synced), but with no incoming/outgoing messages. Banned after ~22-23 hours, all of them. (Exact same moment too, I think.)

The "surviving" number might be older, registered a longer time ago. (Was one of several 2nd hand SIM). I don't know. Might be they're only banning newer numbers. :)

**Comment by tomerb15** [comment]
@yniwly43 Did the survivor was activated now for the first time?

**Comment by Gab0** [comment]
@kobybm, you should use the develop branch, which got a a patch that may fix this banning problem.

7> git clone -b develop https://github.com/tgalal/yowsup.git

**Comment by chriso0710** [comment]
@Gab0  Can you reference the patch, which is supposed to fix the banning problem? Last commit on dev branch was 7 days ago.

**Comment by kobybm** [comment]
@yniwly43 Thanks for your insights, I think that you and me are testing the same stuff... (I can share with you my testing Excel if you want). I thinking about leaving Whatapp and use Telegram instead but I just can't stop thinking that it is solvable + I like the challenge (And also I don't want to spend any time on Telegram development from scratch LOL)
I guess that I will just reboot my servers / restart my programs (My use of Yowsup/ChatAPI is to those kind of stuff...) from ssh and not using Instant messaging hahaha
BTW, Is your "survivor number" still alive? when was the first time you ever connected it with Yowsup/Chat-Api?

@Gab0 , Thanks, I've registered a number with develop branch and I’m leaving  it online for the weekend (hopefully it will still be alive on Sunday)

**Comment by thundergreen** [comment]
Keep US updated for your number/ blocking ;)

Thorsten Fröhlich
Am 06.05.2016 14:21 schrieb "kobybm" <notifications@github.com>:

**Comment by Gab0** [comment]
@chriso0710 
https://github.com/tgalal/yowsup/commit/91e577624d052e6d5ff445002a4ba3de00a8f665

**Comment by kobybm** [comment]
@thundergreen, @tomerb15  @chriso0710 ,
Just wanted to update that currently the SIM I've activated last Friday still alive and able to send and to receive messages.
I will update if the situation will change or remain online on the following week.

Thanks you @Gab0 for the reference.

**Comment by iikhwan50** [comment]
@kobybm  keep update, and report if your number is blocked, thanks.

**Comment by Gab0** [comment]
@kobybm good to know your SIM is alive. I will buy a couple later and try myself.

**Comment by iikhwan50** [comment]
i use develop branch too, and now the number is blocked :(

**Comment by kobybm** [comment]
@Gab0 , @iikhwan50 , @thundergreen , @tomerb15 ,
Well, I've been playing with this yesterday night and everything worked fine BUT this evening I've tried to connect and continue playing with it but it got BLOCKED.

Again, the environment:
 
This is a clean ubuntu Desktop machine on my home (using my WiFi).
### The yowsup version - develop branch:

root@koby-HP-Compaq-dc7700-Small-Form-Factor:~/yowsup# git log -1
commit cf214af4787fa7296bbe5f61ab24494a7ff3d54f
Author: Tarek Galal <tare2.galal@gmail.com>
Date:   Fri Apr 29 12:21:26 2016 +0200

    Fixed utcTimestamp returning local timestamp


###  My log:

root@koby-HP-Compaq-dc7700-Small-Form-Factor:~/yowsup# yowsup-cli demos -c config -y -d
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f7d70eafcd0>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f7d70eaf590>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="00000000000000" mechanism="WAUTH-2">
▒F▒▒Z▒o▒h▒▒+G2J~▒
▒▒▒o?Hb
▒▒7▒▒▒)w▒▒ť▒▒J{z
                ▒w▒▒c▒▒▒▒
HEX:bf469befae5aec6ff368d1d42b47324a7e9a01200a998f121ffc6f3f48620c97d2033782ea061eb42977fd8c88e7a8c5a5e29c12ea0f064a177b7a0bde779edf63be8d07858d
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒▒▒nd▒▒▒▒}Ck'▒y▒
HEX:f9e7c26e64f4a31ca6abbf7d436b2707d1047988
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒IϋT▒j▒J▒▒▒▒
|e▒>▒y▒`▒▒:▒K\qX▒ĬI(ؓ,r▒▒
HEX:7fd749cf8b54e3126a864a8db5f0df0cb8006072bbdbaad9699b55fb3681bcaeafcf588a949ad5822c72a5e40d7c65b63ef0af79856086fe3ae94b5c710158a2c4ac4928d893
</response>







DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized
root@koby-HP-Compaq-dc7700-Small-Form-Factor:~/yowsup#

**Comment by thundergreen** [comment]
Shit ...... But  thanks for keeping us posted ;)

Thorsten Fröhlich
Am 09.05.2016 21:04 schrieb "kobybm" <notifications@github.com>:

**Comment by iikhwan50** [comment]
hv solution guys ? this issue make me crazy. 
4 my simcard has been blocked. 
sad.

**Comment by ThomasMW** [comment]
There won't be a solution untill we find an identifier which causes the blocks.

**Comment by Gab0** [comment]
@kobybm  :/.
I got blocked last week when I messaged a group on which a member had the last version of Android wpp on his phone. Anyone who got blocked knows if own case relates to this? It's bizarre, but who knows xD

**Comment by kobybm1** [comment]
@Gab0 , Any news?

**Comment by Gab0** [comment]
@kobybm The best news: no news :baby_chick: 
One week using develop branch, still operating. 
I never sync the contacts, and talk only in groups or with my phone whatsapp.

**Comment by sphaero** [comment]
I was blocked using @jlguardi master repo. I was only using the echo client or receiving text messages.
I got some weird errors when receiving messages before I was blocked. Unfortunately I didn´t keep those logs :(

**Comment by yniv** [comment]
My update: I use @jlguardi last repo. i can register a number but after a few hours (2 days max)
i get block even without sending anything. All my numbers got blocked this way.
Anyone knows a solution? I see that @tgalal just commited some changes. Anything related to that?
We need to understand what we're doing wrong that they block us.

**Comment by a7lan** [comment]
Whatsapp blocked my 2 number. I send them email. They reply
```

It appears that you are using an unauthorized application of WhatsApp. The use of unauthorized applications and/or unsupported devices (including third-party emulators) are not supported; they contain source code which WhatsApp can not guarantee as safe.

Please uninstall your application and install the authorized version on supported mobile devices from:

www.whatsapp.com/download

After installing the authorized version, please contact us again with an attached screenshot or an image of your screen from within the app support flow
```

Whatsapp sucks. I Going to telegram. I used Whatsapp from my zabbix system. Now i use Telegram

**Comment by sowerkoku** [comment]
guys [see here](https://github.com/tgalal/yowsup/issues/1661#issuecomment-228287130)
