### ISSUE TITLE
not-auzthorized

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1573]
Hi guys. just to let u know. with wa client it works but when i use password in cli it makes this: (reg also not possible. using newest commit

root@osmc:/home/osmc/yowsup# yowsup-cli demos --yowsup -l 33781852856:kK8Cyp5xqE3KVk0qzTuofWeJACs= -d -M
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="33781852856" mechanism="WAUTH-2">
!���jd
���-x��~s�JE:+�?�:'bL�_�ck�	׿
HEX:21c1e7ac6a640a148b9be82d787f9d8ee8fe7e7307ec1a4a453a2be9133f06a73a27624cb65fc2636bcf09d7bf
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�<�"�mI�8yml��5
HEX:fe028eaa3cb88e1d22fe6d498c38796d6ca1e635
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
rm��!���S�t�	�;��bק��L��]n��"u���XJ��
HEX:726df68021f5a7a48f051b53ba74ef09b33b17c6d562d7a783d84cadce5d6eb1df227582ced6584afe8e32bfcf
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized
root@osmc:/home/osmc/yowsup# exit
exit
osmc@osmc:~/yowsup$ yowsup-cli registration --requestcode sms --phone 33781852856 --cc 33 --mcc 208 --mnc 15 -d
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=33&in=781852856&lc=GB&lg=en&sim_mcc=208&sim_mnc=015&mcc=208&mnc=015&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1285&rchash=3c6fce5cbb8f8b6e86a9c7e9350be8703161147d1987b48550005a0299e4ec47&anhash=L%BE%1C%B2-%07t%D2%A79%D6VpK%1B.%E2%29%F6%A2&extexist=1&extstate=1&token=hquKS6lv1eOQWcMd1eCDbb6ywsI%3D&id=%9E%3E%D7%80%16%FD%3F%DB%EC%8E%0EM%E2%98Oc%96%95%22%CC
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=33&in=781852856&lc=GB&lg=en&sim_mcc=208&sim_mnc=015&mcc=208&mnc=015&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1285&rchash=3c6fce5cbb8f8b6e86a9c7e9350be8703161147d1987b48550005a0299e4ec47&anhash=L%BE%1C%B2-%07t%D2%A79%D6VpK%1B.%E2%29%F6%A2&extexist=1&extstate=1&token=hquKS6lv1eOQWcMd1eCDbb6ywsI%3D&id=%9E%3E%D7%80%16%FD%3F%DB%EC%8E%0EM%E2%98Oc%96%95%22%CC
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
)

**Comment by yniwly43** [comment]
no_routes --> IP issue

Also, the password in the latest WA databases cannot be used directly.

**Comment by thundergreen** [comment]
OK....so far so good.how should I change the IP if not bey reconnecting my
router? Is there maybe an IP range and I could make it via proxy aka tor to
chose a country?

Thorsten Fröhlich
Am 07.05.2016 02:06 schrieb "yniwly43" <notifications@github.com>:

**Comment by thundergreen** [comment]
Cause also by trying to reg via mobile IP it won't work ....same issue

Thorsten Fröhlich
Am 07.05.2016 09:13 schrieb "Thorsten Fröhlich" <thundergreen@googlemail.com

**Comment by thundergreen** [comment]
osmc@osmc:~$ yowsup-cli registration --requestcode sms --phone 33781852856
--cc 33 --mcc 208 --mnc 15
-d
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent':
'WhatsApp/2.12.556 Android/4.
3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=33&in=781852856&lc=GB&lg=en&sim_mcc=208&sim_mnc=015&mcc=208&mnc=
015&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=4472&rch
ash=992b5b603bed8083c57af0da5b598787f17baed6ccaf82e39896e8f80238c6eb&anhash=VR%3A%7FC%C0%8F%BA%21%C9t%
2F%94%D1%13%12%B1U%ADo&extexist=1&extstate=1&token=hquKS6lv1eOQWcMd1eCDbb6ywsI%3D&id=%0D%A0k%11%F3%9D%
87%04t%1D5c%CE%96%F0%F2%894t%AA
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to
/v2/code?cc=33&in=781852856&lc=GB&lg=en&sim_
mcc=208&sim_mnc=015&mcc=208&mnc=015&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&
hasinrc=1&rcmatch=1&pid=4472&rchash=992b5b603bed8083c57af0da5b598787f17baed6ccaf82e39896e8f80238c6eb&a
nhash=VR%3A%7FC%C0%8F%BA%21%C9t%2F%94%D1%13%12%B1U%ADo&extexist=1&extstate=1&token=hquKS6lv1eOQWcMd1eC
Dbb6ywsI%3D&id=%0D%A0k%11%F3%9D%87%04t%1D5c%CE%96%F0%F2%894t%AA
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":
3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
osmc@osmc:~$ yowsup-cli registration --requestcode voice --phone
33781852856 --cc 33 --mcc 208 --mnc 1
5
-d

yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

Thorsten Fröhlich
Am 07.05.2016 09:14 schrieb "Thorsten Fröhlich" <thundergreen@googlemail.com

**Comment by schoerg** [comment]
no_routes -> wrong mcc or mnc, or both.

**Comment by thundergreen** [comment]
@schoerg are u sure? Will try again with other MCC and mnc

Thorsten Fröhlich
Am 08.05.2016 15:58 schrieb "schoerg" <notifications@github.com>:

no_routes -> wrong mcc or mnc, or both.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/tgalal/yowsup/issues/1573#issuecomment-217720880>

**Comment by schoerg** [comment]
It's not an IP issue, if it were you wouldn't get so far.

**Comment by thundergreen** [comment]
Will check this out! Thanks so far !!! Cool ;)

Thorsten Fröhlich
Am 08.05.2016 18:50 schrieb "schoerg" <notifications@github.com>:

**Comment by kleberlyra** [comment]
I can I register and receive a password, but when I try to send a message, I get the warning Authentication Error: not-authorized.

[erro.txt](https://github.com/tgalal/yowsup/files/271407/erro.txt)

**Comment by kleberlyra** [comment]
yowsup-cli demos -s 5595991387979 "teste yowsup" -c /etc/yowsup/zap.conf --debug
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5595981198715" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�i��1Z�Ȼ}�S��K;��
HEX:cc69b4a2315a80c8bb7dbf53def84b3ba414b4c3
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
�$v�I�B�g�T�^{��I��M�W���A0���V ̥E�a�>��8�xX
HEX:ce2476dd49c842ed67a554cd5e7ba8fc4995d84dd11f5782949941309aaca4567f20cca5458c61c63ee59838c17858
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by kleberlyra** [comment]
I can I register and receive a password, but when I try to send a message, I get the warning Authentication Error: not-authorized.

yowsup-cli demos -s 559599138XXXX "teste yowsup" -c /etc/yowsup/zap.conf --debug
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="559598119XXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�i��1Z�Ȼ}�S��K;��
HEX:cc69b4a2315a80c8bb7dbf53def84b3ba414b4c3
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
�$v�I�B�g�T�^{��I��M�W���A0���V ̥E�a�>��8�xX
HEX:ce2476dd49c842ed67a554cd5e7ba8fc4995d84dd11f5782949941309aaca4567f20cca5458c61c63ee59838c17858
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by jlguardi** [comment]
You are banned. Important logs are the ones obtained before!

**Comment by thundergreen** [comment]
Would like an official statement from the devs of yowsup

1. How do u test yowsup (cause everybody here gets blocked but it seems
that u guys Not
2. This leads to my suggestion that u might use another code
3. Will this code be available for the rest too?

Thorsten Fröhlich
Am 19.05.2016 01:01 schrieb "jlguardi" <notifications@github.com>:

**Comment by schoerg** [comment]
Already back from Telegram?

**Comment by 0xTryCatch** [comment]
😂

**Comment by mgp25** [comment]
@thundergreen you have discovered us!




                                          `-.`'.-'
                                       `-.        .-'.
                                    `-.    -./\.-    .-'
                                        -.  /_|\  .-
                                    `-.   `/____\'   .-'.
                                 `-.    -./.-""-.\.-      '
                                    `-.  /< (()) >\  .-'
                                  -   .`/__`-..-'__\'   .-
                                ,...`-./___|____|___\.-'.,.
                                   ,-'   ,` . . ',   `-,
                                ,-'   ________________  `-,
                                   ,'/____|_____|_____\
                                  / /__|_____|_____|___\
                                 / /|_____|_____|_____|_\
                                ' /____|_____|_____|_____\
                              .' /__|_____|_____|_____|___\
                             ,' /|_____|_____|_____|_____|_\

**Comment by thundergreen** [comment]
Well guys.  Would just like to know of how the devs test all their yowsup
instances :)

Thorsten Fröhlich
Am 19.05.2016 12:44 schrieb "0xTryCatch" <notifications@github.com>:

**Comment by jlguardi** [comment]
No_routes problem is solved in other closed issues.
Banning problem is described in many other issues without effective solution by now. 
So, duplicated issue.
