### ISSUE TITLE
I can not send messages

### ISSUE THREAD

**Issue by eltanogol** [tgalal/yowsup#1574]
Hi,

I have a problem sending messages, copy the error.

 yowsup-cli demos -s XXXXXXXX "Test" -c config
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 315, in startSendClient
    credentials = self._getCredentials()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 283, in _getCredentials
    config = self.getConfig(self.args["config"])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 72, in getConfig
    val = prep[1].strip()
IndexError: list index out of range

-----------------------------------------------

in the config file, the code is:

#!/usr/bin/env python
__version__ = "2.0.15"
__author__ = "Tarek Galal"

import sys, argparse, yowsup, logging
from yowsup.env import YowsupEnv

HELP_CONFIG = """
############# Yowsup Configuration Sample ###########
#
# ====================
# The file contains info about your WhatsApp account. This is used during registration and login.
# You can define or override all fields in the command line args as well.
#
# Country code. See http://www.ipipi.com/help/telephone-country-codes.htm. This is now required.
cc=54
#
# Your full phone number including the country code you defined in 'cc', without preceding '+' or '00'
phone=549xxxxxxxxxxxx
#
# You obtain this password when you register using Yowsup.
password=dXILxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#######################################################
"""

please can you help me

**Comment by Vinpasso** [comment]
Good morning,

The issue is that your configuration file has some additional lines the do not belong in there, they are part of the yowsup cli.

Here is what your actual config should look like:

```
############# Yowsup Configuration Sample ###########
#
# ====================
# The file contains info about your WhatsApp account. This is used during registration and login.
# You can define or override all fields in the command line args as well.
#
# Country code. See http://www.ipipi.com/help/telephone-country-codes.htm. This is now required.
cc=49
#
# Your full phone number including the country code you defined in 'cc', without preceding '+' or '00'
phone=491234567890
#
# You obtain this password when you register using Yowsup.
password=NDkxNTIyNTI1NjAyMkBzLndoYXRzYXBwLm5ldA==
#######################################################
```

Notice that the config file does not include any python statements.

Have a nice day,
Vinpasso

**Comment by eltanogol** [comment]
Thank you, I can now send messages

**Comment by AnithaU** [comment]
What should we remove from existing code?? Import statements??

**Comment by Vinpasso** [comment]
@AnithaU The file posted by the OP is the python script that outputs an example configuration file. Your config should be a separate file containing only the information I posted above, no python snippets. This is equivalent to the information stored in HELP_CONFIG, everything between the three apostrophes excluding the apostrophes themselves. This template should be edited as required, replacing cc, phone, and password.

**Comment by AnithaU** [comment]
Thank you @Vinpasso for your valuable reply. Please help me out in solving registration issue that i am facing.. and I am new to python and raspberry so feeling little difficulty in installing yowsup. when i tried to register to yowsup got the below response:

http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 206, in handleRequestCode
    method
  File "/home/pi/yowsup/yowsup/registration/coderequest.py", line 41, in __init__
    self.addParam("token", YowsupEnv.getCurrent().getToken(p_in))
  File "/home/pi/yowsup/yowsup/env/env.py", line 52, in getCurrent
    env = envs[0]
IndexError: list index out of range

Is this error related to above discussed issue?? Please assist me on this. Thanks in advance.

**Comment by Vinpasso** [comment]
@AnithaU This error is probably unrelated, for some reason it is not finding the yowsup environment.
Try running `yowsupcli` with either `-E s40` or `-E android` to set the environment manually. If that doesn't work, please open a new issue and be sure to also post your yowsup and system version.

**Comment by AnithaU** [comment]
Thank you @Vinpasso for your assistance :)
