### ISSUE TITLE
Cannot able to register the mobile number in yowsup-cli it says older version even though new version is updated

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1581]
[root@IMS_Dev yowsup-master]# python yowsup-cli registration --debug  --requestcode sms --phone 919986117391 --cc 91
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.357 Android/4.3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=91&in=9986117391&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=yIijQKWPdCi9o7PNLS9LmRanYvI%3D&id=%EE%12%ABg%AE%B7%B2%09%AB%B4%80%05%27U%A6%E0%131_5
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=9986117391&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=yIijQKWPdCi9o7PNLS9LmRanYvI%3D&id=%EE%12%ABg%AE%B7%B2%09%AB%B4%80%05%27U%A6%E0%131_5
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
Check your installation and pythonpath. You are using ‎version 2.12.357 (see your log).

**Comment by abhiroock** [comment]
@jlguardi k thanks a lot ill see...
