### ISSUE TITLE
Cannot able to send image through yowsup-cli 

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1583]
[root@IMS_Dev yowsup-master]# python yowsup-cli demos --debug --unmoxie -c config.txt -x "91xxxxxxxxx" "/usr/src/imag1.jpg"
DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer - call Layer - Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
Traceback (most recent call last):
  File "yowsup-cli", line 390, in <module>
    if not parser.process():
  File "yowsup-cli", line 281, in process
    self.startMediaClient()
  File "yowsup-cli", line 358, in startMediaClient
    stack = mediaclient.SendMediaStack(credentials, [(self.args["media"][0], self.args["media"][1])])
  File "/usr/src/yowsup-master/yowsup/demos/mediaclient/stack.py", line 31, in __init__
    self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
AttributeError: 'module' object has no attribute 'CURRENT_ENV'

**Comment by jlguardi** [comment]
Check your installation and read old issues about error:

AttributeError: 'module' object has no attribute 'CURRENT_ENV'

Not related with topic!
