### ISSUE TITLE
No route after blocked number

### ISSUE THREAD

**Issue by fnlopes** [tgalal/yowsup#1585]
Hi,
My number was blocked last week, so i sent an e-mail to whatsapp suport, and today they unblock my number.
I can register in whatsapp with my cell, but when i try to register with yowsup gives this error:

root@localhost yowsup-master]# ./yowsup-cli registration -r sms -c whatsapp.config
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes

file whatsapp.config
cc=55
phone=55169XXXXXXXXX
id=XXX
password=

This happen with somebody ?

**Comment by thundergreen** [comment]
Yes! Exactly to me too!

Thorsten Fröhlich
Am 10.05.2016 02:32 schrieb "fnlopes" <notifications@github.com>:

**Comment by jlguardi** [comment]
@thundergreen  I sent the sms yesterday to your number and it worked! So the issue is not related with yowsup but Id (you can remove it) env (change device name/buid to other) or IP (it seems that the problem persists after renew).

**Comment by thundergreen** [comment]
How can I change device name / build? ....do u mean.and where do I have to
change it? What were u using?

Would love getting this working again ;)

Thorsten Fröhlich
Am 10.05.2016 10:25 schrieb "jlguardi" <notifications@github.com>:

**Comment by jlguardi** [comment]
Edit  yowsup/env/env_android.py and change constants for valid ones (I've sent a mail with the ones I used).

Remember to remove the whole $HOME/.yowsup/phone : 
 - Id: this is the Id of your android device and should differ from banned one
 - nonce: This is the string used in authentication layer and contains env_android.py info which should be changed too.
 - axolotl.db:  should be removed due to your registration differs from previous one

**Comment by thundergreen** [comment]
Hi.unfortunately I didn't receive your mail i have nonce and axolotl but no
id in the folder
Can unsend it again to thundergreen@gmail.com?

Will try this and let u knownifnit worked ;)

Thanks so far

Thorsten Fröhlich
Am 11.05.2016 10:53 schrieb "jlguardi" <notifications@github.com>:

**Comment by thundergreen** [comment]
All this didn't work :( I'm totally upset. It seems I won't get it running
again?

Thorsten Fröhlich
Am 11.05.2016 13:47 schrieb "Thorsten Fröhlich" <thundergreen@googlemail.com

**Comment by Josue-T** [comment]
Hello,

I have exactly the same problem than thundergreen.

Josué

**Comment by johntheknife** [comment]
Ok, so my theory is that, once they unblock the phone number, you can only register with the phone that you request the unblock from (the phone you tried to register when you sent the pics). I requested an unblock for my number a few weeks ago and I tried to register again from yowsup with "no_carrier" response. I thought that it was because of my carrier but earlier this week I tried again without issues.

The next question is, what environment configuration simulates the phone you requested the unblock from? I don't know the answer to that one.  Maybe @jlguardi does.

**Comment by chriso0710** [comment]
Yes, same here. WA support unblocked my number (I sent an iphone screen). But I can not register with the old number anymore. I am getting the same error as @fnlopes. I deleted $HOME/.yowsup before registering.
Maybe @johntheknife's theory is correct...

**Comment by lanzalibre** [comment]
Ok, I did manage to register with several different android environments. One of them a tablet. However, I am still unable to register with yowsup. I always get no_routes error. 
@jlguardi 
I did try to use the development branch, which uses s40 environment as default, but without success, so it is not the environment. 
I tried to register from a different network, no success either, so it is not the ip.  
I deleted $HOME/.yowsup/<phone>

**Comment by jlguardi** [comment]
@lanzalibre @chriso0710 I could try to send the sms to your phone as I done with @thunthergreen number to check if any of my personal branches work. If you agree, send the numbers to my mail.  (sms will not bw useful due to I have the Id and I could not registrate or block the numbers due to I will no have the code).

**Comment by chriso0710** [comment]
@jlguardi Thanks for the offer! I just sent you a mail with the details...

**Comment by thundergreen** [comment]
Anyway ..we won't  be able tinuse yowsup;)

Thorsten Fröhlich
Am 14.05.2016 22:36 schrieb "Christian Ott" <notifications@github.com>:

**Comment by johntheknife** [comment]
@jlguardi I did send it too. Thanks for offering!
@thundergreen I don't agree, if jlguardi finds a branch that can send registration sms, we can checkout that branch and use it to get the password. Then we can return to the branch we were using before.

**Comment by jlguardi** [comment]
I've found the solution! Just use a different env. I've tested:
 - Number never used with yowsup: registration worked with current s40-android env
 - Number currently blocked by wa: returns 'blocked' with both envs
 - Number unblocked by wa (like all send by you): no_routes with s40 env but worked with android env

In summary, if you are blocked using yowsup, probably you need to change your env to avoid no_routes. So use:
```
 yowsup-cli registration sms -C xx -p xxxxxxxx -E android
```
And remember to use -E android always to avoid detectable env changes!

**Comment by thundergreen** [comment]
That sounds awesome!!! I will try immediately and give a feedback.AFAIK i
already changed env.like this it should work;)

Thorsten Fröhlich
Am 16.05.2016 00:37 schrieb "jlguardi" <notifications@github.com>:

**Comment by thundergreen** [comment]
yowsup-cli registration -r sms -C xx -p xxxxxxxxxx -E android

You need the addition '-r' but I can confirm!!! Worked! Got my code!
Thorsten Fröhlich
Am 16.05.2016 08:16 schrieb "Thorsten Fröhlich" <thundergreen@googlemail.com

**Comment by thundergreen** [comment]
IT WORKS FELLAS! THANKS SO MUCH!! WILL  Register for my Transport now to
see .im actually using yowsup develop  tgalal

Thorsten Fröhlich
Am 16.05.2016 08:27 schrieb "Thorsten Fröhlich" <thundergreen@googlemail.com

**Comment by thundergreen** [comment]
osmc@osmc:~$ yowsup-cli registration -r sms -C 33 -p 33781852856 -E android                                                                                                                   
yowsup-cli  v2.0.15                                                                                                                                                                           
yowsup      v2.4.103                                                                                                                                                                          
                                                                                                                                                                                              
Copyright (c) 2012-2016 Tarek Galal                                                                                                                                                           
http://www.openwhatsapp.org                                                                                                                                                                   
                                                                                                                                                                                              
This software is provided free of charge. Copying and redistribution is                                                                                                                       
encouraged.                                                                                                                                                                                   
                                                                                                                                                                                              
If you appreciate this software and you would like to support future                                                                                                                          
development please consider donating:                                                                                                                                                         
http://openwhatsapp.org/yowsup/donate                                                                                                                                                         
                                                                                                                                                                                              
                                                                                                                                                                                              
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}                                                                                                                        
                                                                                                                                                                                              
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}                                                                                                                        
                                                                                                                                                                                              
status: fail                                                                                                                                                                                  
reason: blocked             

I have been blocked right away! I use zowsup tgalal develop branch.

**Comment by johntheknife** [comment]
It did work for me.
@thundergreen I would suggest that you remove the number from your comment. Please, keep us informed if you manage to release the block

**Comment by thundergreen** [comment]
Not necessary to remove the number as it's linked to my yowsup ID . I'm
blocked the second time.they won't unblock me again

Thorsten Fröhlich
Am 16.05.2016 13:06 schrieb "johntheknife" <notifications@github.com>:

**Comment by thundergreen** [comment]
Just a reminder. Put - E Android in your register command and it will work

Thorsten Fröhlich
Am 22.05.2016 13:28 schrieb "jlguardi" <notifications@github.com>:

**Comment by FWillems** [comment]
After updating yowsup to the latest version and with the mentioned hint by adding an "-E android" to the registration code everything works fine again! 

Thank you

**Comment by balasundaramc** [comment]
Thanks @jlguardi....you are awsome.. its worked for me

**Comment by SR12341** [comment]
Today, I tried s40 env and android, both getting both getting failed with the reason "no routes". Anybody able to register successfully?

**Comment by sendytiaprayoga** [comment]
@SR12341 i have same issue and i try:

yowsup-cli registration -r sms -C xx -p xxxxxxxx -E android

but i have message:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

any one can help?

**Comment by jeanRibeiro** [comment]
Hello @sendytiaprayoga !

Tracking solution that worked for me here:

// SOLUTION FOR ERROR: Status: OLD_VERSION
git clone git: //github.com/tgalal/yowsup.git
cd yowsup
sudo python setup.py install

**Comment by sendytiaprayoga** [comment]
thanks @jeanRibeiro,
Now i have other problem. my number blocked again.
