### ISSUE TITLE
grouplist details for development purpose

### ISSUE THREAD

**Issue by jerinzam** [tgalal/yowsup#1586]
I am able to get grouplist from yowsup-cli but how to get grouplist details for development purpose

kinda new to python

**Comment by jlguardi** [comment]
use /h in yowsup-cli to get all /group functions

You need to list all groups (/groups list) and get the info for each group (/group info group_jid).

for implementation details see:
 - yoswup/demos/cli/layer.py
 - yowsup/layers/protocol_groups/structs/group.py
 - yowsup/layers/protocol_groups/**
