### ISSUE TITLE
understand why Authentication Error: not-authorized

### ISSUE THREAD

**Issue by eltanogol** [tgalal/yowsup#1587]
Hello,
Install the library without problems.
I can send messages. (yowsup-cli demos -c config -s 54911xxxxxxx message)
I can access the demo command line. (Yowsup-cli-and demos -c config)
I can access the demo Echo Client. (Yowsup-cli demos -e -c config)

but after 10 minutes running the demo get the following message
**

> parking@umacroparking:~/yowsup$ sudo yowsup-cli demos -e -c config
> [sudo] password for parking:
> yowsup-cli  v2.0.15
> yowsup      v2.4.103
> 
> Copyright (c) 2012-2016 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> Echoing ahora llega? to 54911xxxxxxx
> Echoing sigue vivo ? to 54911xxxxxxx
> Authentication Error: Unhandled stream:error node:
> < stream:error >
> < system-shutdown >
> < /system-shutdown >
> < /stream:error >

**

after that message, WhatsApp does not allow me to send messages more

> parking@umacroparking:~/yowsup$ sudo yowsup-cli demos -y -c config
> yowsup-cli  v2.0.15
> yowsup      v2.4.103
> 
> Copyright (c) 2012-2016 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> Yowsup Cli client
> ==================
> Type /help for available commands
> 
> [offline]:/L
> general: Login Failed, reason: not-authorized
> Auth Error, reason not-authorized

not send messages

> parking@umacroparking:~/yowsup$ sudo yowsup-cli demos -c config -s 54911xxxxxxx message
> yowsup-cli  v2.0.15
> yowsup      v2.4.103
> 
> Copyright (c) 2012-2016 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> Authentication Error: not-authorized
> parking@umacroparking:~/yowsup$

I can not understand why wasap not authorize me.
could you please help me

Thz!!!

**Comment by ronromer** [comment]
soo many issue open about this, check this one https://github.com/tgalal/yowsup/issues/1516

**Comment by jlguardi** [comment]
Repeated
