### ISSUE TITLE
How many messages can be sent from the same number?

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1588]
How many messages can be sent from one number to blocking ?
blocking number temporarily or permanently?

**Comment by schoerg** [comment]
Sounds like spam if you need to ask something like that.

**Comment by thundergreen** [comment]
Please all! Don't support spamming requests! Yowsup is not meant for
spamming purposes

Thorsten Fröhlich
Am 11.05.2016 18:57 schrieb "schoerg" <notifications@github.com>:
