### ISSUE TITLE
bad_param

### ISSUE THREAD

**Issue by Toutydroid** [tgalal/yowsup#159]
hey
I'm trying to use yowsup-cli, but when I try 
"./yowsup-cli --requestcode sms --config yowsup-cli.config --debug"

i got the following:

*************************************************************************************************
*************************************************************************************************

GET
{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.10.750 Android/4.2.1 Device/GalaxyS3'}
cc=33&in=970779906&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=850e16e952f803aef70da67cc130cc6c&token=47b20bf40b93d7fc32801716b1063ecb
Opening connection to v.whatsapp.net
Requesting /v2/code?cc=33&in=970779906&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=850e16e952f803aef70da67cc130cc6c&token=47b20bf40b93d7fc32801716b1063ecb
WACodeRequest:  {"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param

*************************************************************************************************
*************************************************************************************************

where my config:

cc=33
phone=33970779906
id=MYIMEI
password=

**Comment by mutindaz** [comment]
Fixed the same problem by adding 0 before my phone no..
