### ISSUE TITLE
Cannot able to register mobile number when added new version 2.4.103

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1598]
yowsup-cli registration --debug --requestcode sms --phone 919986117391 --cc 91
yowsup-cli  v2.0.15
yowsup      v2.4.103

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=91&in=9986117391&id=%AB%D2%AD%15%D9%16%7C%B5%E3%5C%0B%D6v%01%2F%7C%CB%D2%8A%AB&lg=en&lc=GB&token=72747e808b819855225713b4239c133a&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=91&in=9986117391&id=%AB%D2%AD%15%D9%16%7C%B5%E3%5C%0B%D6v%01%2F%7C%CB%D2%8A%AB&lg=en&lc=GB&token=72747e808b819855225713b4239c133a&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/GalaxyS3'}
DEBUG:yowsup.common.http.warequest:cc=91&in=9986117391&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2984&rchash=2ecc398a8ff6682b7694a3413b6562d8661c97e2a4a9847b14735a8819fdd77e&anhash=%21Q%DB%7E%B3%9B%11eE%B1%E8%F5%EEw%E4%28D%B19i&extexist=1&extstate=1&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D&id=U%7F%81%0F%3E%CC%8B%CEC%BD%97%92%82%22%AA%95%7FY%ACB
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=9986117391&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2984&rchash=2ecc398a8ff6682b7694a3413b6562d8661c97e2a4a9847b14735a8819fdd77e&anhash=%21Q%DB%7E%B3%9B%11eE%B1%E8%F5%EEw%E4%28D%B19i&extexist=1&extstate=1&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D&token=%2FdQixsC49d%2FWW3PRjxui%2BT5QwFg%3D&id=U%7F%81%0F%3E%CC%8B%CEC%BD%97%92%82%22%AA%95%7FY%ACB
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"token"}

status: fail
param: token
reason: bad_param

Please provide any solution for this problem 
Thanks

**Comment by thundergreen** [comment]
Just tried your number.it's blocked
