### ISSUE TITLE
Number given to yowsup-cli is blocked while registration process please unblock these numbers

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1599]
Numbers are 1:-919986117931
2:-919591995560

**Comment by thundergreen** [comment]
Yowsup can't unblock.. It's wa related

Thorsten Fröhlich
Am 16.05.2016 12:51 schrieb "abhiroock" <notifications@github.com>:

**Comment by abhiroock** [comment]
@thundergreen Is their any solutions to unblock these number from wa

**Comment by thundergreen** [comment]
Write an email to the support .they will probably unblock your number.they
did it one time for me.second time they won't I guess

Thorsten Fröhlich
Am 16.05.2016 13:21 schrieb "abhiroock" <notifications@github.com>:

**Comment by abhiroock** [comment]
@thundergreen Thanks a lot
