### ISSUE TITLE
Erro register - old_version

### ISSUE THREAD

**Issue by benedict-erwin** [tgalal/yowsup#160]
I cannot register to whatsapp, i get reason:old_version.
this my debug log.

GET
{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.10.750 Android/4.2.1 Device/GalaxyS3'}
cc=62&in=811313105&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=f1b708bba17f1ce948dc979f4d7092bc&token=8a53a0228197f946dba7ab5cb88ae4ac
Opening connection to v.whatsapp.net
Requesting /v2/code?cc=62&in=811313105&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=f1b708bba17f1ce948dc979f4d7092bc&token=8a53a0228197f946dba7ab5cb88ae4ac
WACodeRequest:  {"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }

Kaan Karataç
