### ISSUE TITLE
status:fail, reason: no_routes, please retry after: 1 hour

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1601]
why happend this i got this error using my ovh server

**Comment by thundergreen** [comment]
Use -E android at the end of your registration line

Thorsten Fröhlich
Am 17.05.2016 01:32 schrieb "minimaldev" <notifications@github.com>:

**Comment by minimaldev** [comment]
@thundergreen hundergreen  im using WACodeRequest class how i can add this option?

**Comment by jlguardi** [comment]
Use 'yowsup-cli registration'
