### ISSUE TITLE
numbers blocked

### ISSUE THREAD

**Issue by fiveyears** [tgalal/yowsup#1602]
I can't recommend the use of yowsup anymore. All my numbers get blocked after some hours, even if I don't send messages, only update my status or echo some messages. The registration (per voice) is smooth, but later I get blocked.
I think WhatsApp wants to fight creative software like yowsup more intense

**Comment by WarMasterNL** [comment]
Yup.. Same deal.

**Comment by yniv** [comment]
Same here... We've got to find a solution for this... how do they detect us?

**Comment by assegaf** [comment]
its quite easy to detect actually, thats why tgalal return back to s40 credential at new update software, thanks tgalal. I wonder s40 2.16.7 is still WA1.6 protocol

android whatsapp 2.12.5XX is WA20 protocol, but we keep forcing login using 1.6 protocol, thats why blocked instantly ..

**Comment by assegaf** [comment]
Confimed, WA S40 2.16.7 still using WA1.6 protocol.


// this.f3654a.m5182write(new byte[]{(byte) 87, (byte) 65, (byte) 1, (byte) 6});

....
.....
public final synchronized void mo310C(String str, String str2) {
        m4700jT();
        this.f3654a.m5182write(new byte[]{(byte) 87, (byte) 65, (byte) 1, (byte) 6});
        m4699jS();
        C0847bcq[] c0847bcqArr = new C0847bcq[]{new C0847bcq("to", str), new C0847bcq("resource", str2)};
        m4694bx(5);
        this.f3654a.m5181write(1);
        m4676a(c0847bcqArr);
        m4682as(false);
    }
