### ISSUE TITLE
Trying to Get Register to whatapp notification

### ISSUE THREAD

**Issue by thatsk** [tgalal/yowsup#1606]
First of all appreciate for your project,But when I trying to register i have get an activation number. But password Does not get . Thats why i am not register with that . So can you help in getting this???
![screenshot from 2016-05-20 20-15-22](https://cloud.githubusercontent.com/assets/15324013/15431488/d2236d60-1ec7-11e6-88c2-ea1ecb71b2bc.png)

**Comment by tgalal** [comment]
And taking a screenshot, creating a new issue, and then waiting for someone to post you step by step instructions is easier than simply opening  the wiki and reading  documentation ?

**Comment by thatsk** [comment]
Ya I have Read all the things But new issues is what is password thing which i getting irritaing from this . I have received registration number but can't registered>>>>>>>>>>>

**Comment by thatsk** [comment]
So Your yowsup not fixing that issues Right????
