### ISSUE TITLE
"fail","reason":"old_version"

### ISSUE THREAD

**Issue by peterwup** [tgalal/yowsup#1609]
Hi, 
I am using: 
yowsup-cli  v2.0.15
yowsup      v2.4.103

when I try to register a new phone number I get the message: 

INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}

what I do: 

`python3.5 yowsup-cli registration -c /opt/yowsup-config/yowsup.config -r sms --debug`

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'User-Agent': 'WhatsApp/2.13.39 S40Version/14.26 Device/302', 'Accept': 'text/json'}
DEBUG:yowsup.common.http.warequest:cc=49&in=**MYPHONENUMER**&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8471&.... **deleted** 
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=49&in=**MYPHONENUMER**&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8471&rchash=.... **deleted**
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'

**Comment by tgalal** [comment]
This is outdated yowsup version

**Comment by peterwup** [comment]
Sorry for asking stupid questions, but how to get the current version for my raspi ? 
What I did:

`sudo wget -N https://github.com/tgalal/yowsup/archive/master.zip`

**Comment by schoerg** [comment]
Do it again.
