### ISSUE TITLE
Cannot send/receive message from a few phone numbers

### ISSUE THREAD

**Issue by yezgar** [tgalal/yowsup#1615]
Hi,

Currently my yowsup app works well. It's receive and send messages to many phone numbers but for few phone numbers (actually two) can´t send message and the message from these phone numbers never arrived.

Whatsapp works fine in these devices.

Some ideas or explanation what happen with these phone numbers?
How to fix it?

**Comment by Gab0** [comment]
Probably these contacts are using newer versions of whatsapp (iOS/Android/WPHONE are different). Updating yowsup to the latest branch may solve this.
