### ISSUE TITLE
3 number blocked after upgrading latest version v2.5.0

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1617]
My first number registered for yowsup-cli from so many days its working fine but yesterday its showing like status:-fail reason:-blocked.I upgraded the yowsup-cli with latest versiov v2.5.0 and registered with another mobile number after two days this number is also blocked.I didnt send any spam or any images but whatsapp blocked my 3 number reason is you are using an unauthorized whatsapp application.please any one provide solution for this problem.

**Comment by ronromer** [comment]
yowsup is not working anymore... it's not safe to use it at this time.

**Comment by sphaero** [comment]
https://blog.whatsapp.com/615/Making-WhatsApp-free-and-more-useful

> Starting this year, we will test tools that allow you to use WhatsApp to communicate with businesses and organizations that you want to hear from.

Guess what they don't need

**Comment by sowerkoku** [comment]
guys [see here](https://github.com/tgalal/yowsup/issues/1661#issuecomment-228287130)

**Comment by zenithanon** [comment]
I dont know if anyone else has noticed the frequent and aggressive way @whatsapp goes about blocking numbers. Even if you just register and dont even send a message after a while you will be blocked.

**Comment by sowerkoku** [comment]
whatsapp points that their new tools. businesses and corporations want to cover.

so it must be blocking.
