### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by CDNievas** [tgalal/yowsup#1619]
I have this error when trying to login. I did the number confirmation two times. and when I tried the number on a cellphone it is working...

[offline]:L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized.

Thx for any help that you can offer me :)

**Comment by jlguardi** [comment]
You need to register your number before:
- yowsup-cli registration -r sms -p phone -C cc
- yowsup-cli registration -R code -p phone -C cc
And set the password obtained into a config file. 

And read the wiki!!!

**Comment by CDNievas** [comment]
"You need to register your number before:

yowsup-cli registration -r sms -p phone -C cc
yowsup-cli registration -R code -p phone -C cc And set the password obtained into a config file.
And read the wiki!!!"

I did that!!! That is so obvious

**Comment by jlguardi** [comment]
If you done the second step and you got a password, your device should not work.

**Comment by CDNievas** [comment]
What do you want to say by "your device"?

**Comment by jlguardi** [comment]
You said that your account was still working in your cellphone. So, it means that your registration with yowsup didn't worked.
