### ISSUE TITLE
How to get Group JID

### ISSUE THREAD

**Issue by benedict-erwin** [tgalal/yowsup#162]
I want to send message in a group but i dont know the group JID, how to i find group JID?

**Comment by reus201** [comment]
How to create/send new line in message? "\n" doesn't seem to work

**Comment by doriancosentino** [comment]
hi, i don´t understand how to know the id of group...i config and can send message to phone but not group (i installed on windows server) thanks

**Comment by hassanalisalem** [comment]
thank you for your help
I want to ask how may I get all groups ids that I joining or created
thank you

**Comment by jlguardi** [comment]
@hassanalisalem You can get all groups you've created  with:
```
    def groups_list(self):
        def onGroupsListResult(successEntity, originalEntity):
            me = self.getLayerInterface(YowAuthenticationProtocolLayer).getUsername(True)
            logger.info(me)
            myGroups = [ group for group in successEntity.getGroups() if group.getOwner() == me]
            for group in myGroups:
                logger.info(group.getId() + '---->' + group.getSubject())
        def onGroupsListError(errorEntity, originalEntity):
            logger.info(error)

        if self.assertConnected():
            entity = ListGroupsIqProtocolEntity()
            successFn = lambda successEntity, originalEntity: onGroupsListResult(successEntity, originalEntity)
            errorFn = lambda errorEntity, originalEntity: ononGroupsListError(errorEntity, originalEntity)
            self._sendIq(entity, successFn, errorFn)
```

or groups that you joined if you remove the check ```if group.getOwner() == me```

**Comment by hassanalisalem** [comment]
@jlguardi the problem is when I use sendGetGroups nothing happened :(
thank you

**Comment by jlguardi** [comment]
Have you included group iq layer in the stack and included the python module?

**Comment by rohit1290** [comment]
I have created a group but i am not able to get the ID of that group.  I tried sendGetGroups but nothing happned.

How can I get the group ID using PHP?

**Comment by hazly92** [comment]
Hi all,

Im still not able to find group JID. How can I find it?


*Sorry Im totaly newbie in python.
Thanks in advanced~
