### ISSUE TITLE
Crashes when receive a location message

### ISSUE THREAD

**Issue by JoaquinGimenez1** [tgalal/yowsup#1623]
Yowsup crashes when receive a location message, this is the error 

`  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 252, in handleLocationMessage
    "longitude": locationMessage.degress_longitude,
AttributeError: 'LocationMessage' object has no attribute 'degress_longitude'`

Can you help me to solve this please?

**Comment by jlguardi** [comment]
There is a typo. Replace degress by degrees‎.

**Comment by JoaquinGimenez1** [comment]
Thank you very much! It works perfectly now!!
