### ISSUE TITLE
How to check if whatsapp number exist/not?

### ISSUE THREAD

**Issue by DaurenD** [tgalal/yowsup#1626]
I already tried to sync using this method:
`numbers = ['registered@s.whatsapp.net', ' 'not registered@s.whatsapp.net']
sync = GetSyncIqProtocolEntity(numbers)
self._sendIq(sync, self.onGetSyncResult, self.onGetSyncError)`

Result is the same, regardless to the numbers I use to sync. All numbers returned as **Out numbers** which means whatsapp server giving me a false results. 
But it's more likely that I'm doing something wrong.
How to use sync to get adequate results?

**Comment by jlguardi** [comment]
In this case, numbers should be numbers. Don't use jids. Also, use number for local number and +number fo international ones. Think like official app gets your contacts.
