### ISSUE TITLE
reason: no_routes

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1629]
Hi,
I searched all forum and not found solution, I tried to send another ip also does not work someone has a light to the error below

root@ip-172-31-12-239:/usr/src/yowsup-master# ./yowsup-cli registration -r sms -c config
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}

status: fail
retry_after: 3600
reason: no_routes

**Comment by wilsaad** [comment]
Same issue here.

**Comment by brunodskoo** [comment]
me too

**Comment by JaegerP** [comment]
+1 here

**Comment by janurag** [comment]
I am facing the same issue as well :(

**Comment by schoerg** [comment]
Try another phone number.

**Comment by josep112** [comment]
I've tried several numbers from 4 different operators, also tried many different ips q ue seems that there is not solution for this at the moment

**Comment by janurag** [comment]
@schoerg  i am facing the same issue as the @josep112 . I also tried 4-5 numbers and also used different ips (network) to register. But didn't workout. Below is my output from my last attempt.

yowsup-cli registration --requestcode sms --phone 919*******31 --cc 91 --mcc 4** --mnc 0** -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=91&in=9115888931&lc=GB&lg=en&sim_mcc=404&sim_mnc=088&mcc=404&mnc=088&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7321&rchash=e7d6756a6b6f18a1a97d64270d9055d5a7b1119c3a7c69f26231a9dbc8e2928b&anhash=%40%84%88%8E%CBd%2F5%07%C9%FE-y%F2%0B%13%0D%B6%07%D2&extexist=1&extstate=1&token=3e00ab19c1ab8bad36adb0ebcaf44f9a&id=z%F4%0C%25%875_%BE%BF_%F9%AB%3E%D7%25%10%B5%AEH%17
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=9115888931&lc=GB&lg=en&sim_mcc=404&sim_mnc=088&mcc=404&mnc=088&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7321&rchash=e7d6756a6b6f18a1a97d64270d9055d5a7b1119c3a7c69f26231a9dbc8e2928b&anhash=%40%84%88%8E%CBd%2F5%07%C9%FE-y%F2%0B%13%0D%B6%07%D2&extexist=1&extstate=1&token=3e00ab19c1ab8bad36adb0ebcaf44f9a&id=z%F4%0C%25%875_%BE%BF_%F9%AB%3E%D7%25%10%B5%AEH%17
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}

status: fail
retry_after: 3600
reason: no_routes

**Comment by Lynch07** [comment]
It's is necessary updated the **_'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}_**... someone knows how change nokia S40 for a valid android device??...

**Comment by sree0410** [comment]
hi 
 i face same issue status as no routes , i use the same version of yowsupcli and yowsup which is addressed above .

is there any update ??

**Comment by josep112** [comment]
Does anyone have a light to this problem?

**Comment by janurag** [comment]
@josep112 I am still trying to resolve the issue but good news is YET to come  :) Hopefully  contributors  can help us out here.

**Comment by jlguardi** [comment]
@janurag I've just tested your number with Android env and worked (However default s40 env failed):
```
./yowsup-cli registration -r sms -p 91911xxxxxxx -C 91 -d -E android
DEBUG:yowsup.env.env:Current env changed to android 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=91&in=911xxxxxxx&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=621&rchash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx95bf6&anhash=%BB+v%9C%F4-%D8%F4%96%40xxxxxxxxxxxx&extexist=1&extstate=1&token=hJ4xF2TbHEcxxxxxxxxxxBBDA%3D&id=%84%3C%25M%0Bn%80%84%F0%xxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by Lynch07** [comment]
using ** -E android_** at last works!!... but I don't know if is it necessary use this for every command.
Regards and thanks @janurag

**Comment by JaegerP** [comment]
@janurag -E android works for me as well. Thank you. @Lynch07 Yes, it seems like you have to add it to every command.

**Comment by josep112** [comment]
which has a tutorial that E android?

**Comment by jlguardi** [comment]
I just use "-E android" for registering since some time ago and my numbers are still working. But, of course, it isn't the official working flow.

**Comment by sree0410** [comment]
-E option worked for me 
thank you

**Comment by josep112** [comment]
Can you give an example of this option -E?

**Comment by wilsaad** [comment]
Work for me too.
Jose: yowsup-cli registration -E android -C 99 -p 999999999 -r sms

**Comment by josep112** [comment]
I was able to register with the -E but now can not send the the following error:  TypeError: 'NoneType' object is not iterable




./yowsup-cli demos -c config -s "55179XXXXXXXX" "teste" 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 272, in process
    self.startSendClient()
  File "./yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/src/yowsup-master/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/src/yowsup-master/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 156, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer_base.py", line 65, in onSuccess
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
    .setOurIdentityKey(self.identityKeyStore.getIdentityKeyPair())\
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 19, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 30, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable
root@ip-172-31-12-239:/usr/src/yowsup-master#

**Comment by josep112** [comment]
I managed to solve with the command:
./yowsup-cli demos -y -d -c config
/L
Thank you all, problem solved

**Comment by sree0410** [comment]
Hi ,

if i upgrade to python 2.7 do i have to register again or previously registerd login details would suffice

**Comment by jlguardi** [comment]
You can change python version without any problem. Login will continue working.

**Comment by sree0410** [comment]
Hi ,

for some reasons  i am not able to upgrade to python2,7 , setup tools keep pointing to default version of python2,6 
i have tried pythonbrew 
i have tried changing the environment PYTHONPATH 

nothing is working 
when i try in  /yowsup-master directory
 sudo python2.7 setup.py install 

its says setuptools not installed for 2.7 when i try to install by sudo apt-get python-setuptools install  it tries to fetch and download in python2,6 though environment variable is set to 2.7 version

so now my questiion can i have some help to avoid importer counter error which i pointed above with python2.6 version itself

Is python2,7 is really necessary 

please help me

**Comment by jlguardi** [comment]
@sree0410 is better to open a new issue for non-related topics.
Python2.7 is not a requirement but probably nobody tested python2.6. Probably you can install python2.7_setuptools or download directly from pypi.python.org and install using python2.7

**Comment by sree0410** [comment]
ok thanks
