### ISSUE TITLE
Line break on sendclient demo

### ISSUE THREAD

**Issue by paulospachi** [tgalal/yowsup#1634]
Is there anyway i can send messages with line break? i've already tried using \n or %0A with no success

Thanks in advance

**Comment by schoerg** [comment]
build a string like this:

`string = "some text\nin next\n line"`

**Comment by sree0410** [comment]
guys how are you able to authorize the login ?please share ,it would be helpful for me

**Comment by sowerkoku** [comment]
@sree0410 
read here #1648
