### ISSUE TITLE
Auth Error, reason Unhandled stream:error node:

### ISSUE THREAD

**Issue by sree0410** [tgalal/yowsup#1640]
After getting connected succesfully , before i could perform any operation like sending message or anything i get this message 

stream:error
<system-shutdown>
</system-shutdown>
/stream:error

Auth Error, reason Unhandled stream:error node:
stream:error
<system-shutdown>
</system-shutdown>
/stream:error

what could be the problem ?
Is there anything which i am missing here

please help me

Thanks,
sreelekha.N

**Comment by vityapro** [comment]
Same issue

**Comment by MrDinky** [comment]
sree0410, did you solve this problem?
