### ISSUE TITLE
Get Admins & Group Member list [Question: How to]

### ISSUE THREAD

**Issue by haxxorsid** [tgalal/yowsup#1641]
I need code/command for receiving list of Admins & Group Members of a particular Group. Please someone provide me with code/command.

**Comment by jlguardi** [comment]
Do something like:
```
        iq = InfoGroupsIqProtocolEntity(self.aliasToJid(group_jid))
        successFn = lambda successEntity, originalEntity: print(successEntity)
        errorFn = None
        self._sendIq(iq, successFn, errorFn):
```

**Comment by haxxorsid** [comment]
Ok ty I will try that. How can I promote/demote ? To make someone admin / remove adminship . I need code for that.

**Comment by haxxorsid** [comment]
:open_mouth:

**Comment by SweetShyGirl** [comment]
Same here
