### ISSUE TITLE
number blocked

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1642]
I had an open issue saying that the number is blocked after sending a few messages, but what I checked is that when I register a new number, even if I do not send any message after one day it is blocked, below the procedures I'm doing wrong?

Receive code
./yowsup-cli registration -E android -C 55 -p 55179XXXXXXXX -r sms

Receive Password
./yowsup-cli registration -R 559111CODIGO -C 55 -p 55179XXXXXXXX

Send message
./yowsup-cli demos -c config -s "55179XXXXXXXX" "Message ok"

**Comment by lironsher** [comment]
Have the same issue with the PHP API.

I am afraid that WA decide to close the support for API.

**Comment by rami-dabain** [comment]
Guys, if you are using it for support / customer notifications just use telegram API and tell your users to install telegram.
I did that, 100% of my users now use telegram to receive notifications and for support integration
Yowsup is an amazing API, but whatsapp made it useless, whatsapp will lose it's business-related things very soon. telegram to go!

**Comment by schoerg** [comment]
@rami-dabain The EULA of WA said "no commercial stuff", so they are not losing anything they did not  even want in the first place.

**Comment by rami-dabain** [comment]
No commercial stuff means not selling anything. but if you run a website
and provide support to your customers theough whatsapp. thats not against
the tos. you can still do it from mobile. but from a keyboard its faster
and more organized

**Comment by schoerg** [comment]
There is WhatsApp Web for this.

**Comment by rami-dabain** [comment]
Dont think small, you might have a whole helpdesk with customer support
staff working on one helpdesk software, all support messages from twitter,
facebook, email, web page, and whatsapp go to one place, then when the
staff replies, his reply go to the customer where the custimer did send the
message to. this enables you to FIFO, keeptrack of everything and search
for messages. now how can you get whatsapp web for that? seriously man...

**Comment by schoerg** [comment]
You just don't use Whatsapp for that.
You rely on an unofficial third-party API to get in contact with your customers. This is bad, for obvious reasons, which you felt yourself by getting blocked. All other services you mentioned have APIs and allow such usage.

Whatsapp may terminate your account on whatever reason they see fit.

**Comment by jlguardi** [comment]
Banning issues are already opened.
