### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by ManuelMolina97** [tgalal/yowsup#1643]
I always do:

> yowsup-cli registration -C 34 -r voice -p 34600... -m 214 -n 01

And get always the same answer:

> INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}
> status: fail
> retry_after: 3600
> reason: no_routes

Version:

> yowsup-cli  v2.0.15
> yowsup      v2.5.0

I've looking for this issue and still not get any real answer. So please if any of you can help me.

Thank you.

If any of you need more info, just ask.

**Comment by drmaposa** [comment]
try to use SMS via
`yowsup-cli registration -C 34 -r voice -p 34600... -m 214 -n 01`
instead of VOICE
`yowsup-cli registration -C 34 -r sms -p 34600... -m 214 -n 01`

**Comment by ManuelMolina97** [comment]
I still get the same answer :/

**Comment by drmaposa** [comment]
Are you sure you are using `--requestcode sms` in your command line. That usually happens if you request an activation code via Voice instead of SMS.
Keep trying after about an hour

**Comment by jlguardi** [comment]
Try without -m and -n and first with sms (just use voice after 3 min of a sms). If it fails, use other environment (-E android).

**Comment by ManuelMolina97** [comment]
I've tried with both of your options and still get the same error:

> INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":60,"voice_wait":60}
status: fail
retry_after: 3600
reason: no_routes

The same with -E android:

>  INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":5,"voice_wait":5}
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":60,"voice_wait":60}
status: fail
retry_after: 3600
reason: no_routes

**Comment by emiquey** [comment]
Hi, 
I've been facing the very same error, trying this:
> ./yowsup-cli registration --requestcode sms --phone 5989xxxxxxx --cc 598 -m 748 -n 07 -d
here is what I got in return:
> yowsup-cli  v2.0.15
> yowsup      v2.5.0
> 
> 
> DEBUG:yowsup.env.env:Env not set, setting it to s40
> DEBUG:yowsup.env.env:Current env changed to s40 
> DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
> DEBUG:yowsup.common.http.warequest:cc=598&in=95907659&lc=GB&lg=en&sim_mcc=748&sim_mnc=007&mcc=748&mnc=007&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6357&rchash=76a58ec3099d062e773c747635229e7b1213ab767df65f039ac786cf05982f6b&anhash=%89v%F79%BE%A2M%F27%A2%0D%85%F6%B8%9D%B8%EB%E2Gg&extexist=1&extstate=1&token=320880970a69ec6dfe637b70454e9923&id=%90%97v%02%D02%2F%ED%94%1A%12%AB%84R%C8%F8%F73%9E%CB
> DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
> DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=598&in=95907659&lc=GB&lg=en&sim_mcc=748&sim_mnc=007&mcc=748&mnc=007&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6357&rchash=76a58ec3099d062e773c747635229e7b1213ab767df65f039ac786cf05982f6b&anhash=%89v%F79%BE%A2M%F27%A2%0D%85%F6%B8%9D%B8%EB%E2Gg&extexist=1&extstate=1&token=320880970a69ec6dfe637b70454e9923&id=%90%97v%02%D02%2F%ED%94%1A%12%AB%84R%C8%F8%F73%9E%CB
> INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}
> 
> status: fail
> retry_after: 3600
> reason: no_routes
> 

Any clue of what I should do ?
Thanks !

**Comment by jorgedv** [comment]
Hi, I am getting the same error here...

>yowsup-cli registration --requestcode sms --phone 5491xxxxxxxxx --cc 54 --mcc 722 --mnc 010 -d
>
>yowsup-cli  v2.0.15
>yowsup      v2.5.0
>
>DEBUG:yowsup.env.env:Env not set, setting it to s40
>DEBUG:yowsup.env.env:Current env changed to s40 
>DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
>DEBUG:yowsup.common.http.warequest:cc=54&in=91xxxxxxxxx&id=%BF7%2FlJ%17%D6m%B5%A2m%1E%B1g%98Wf%21%E2%2A&lg=en&lc=GB&token=afb874c7503e3d7ea86604429f29e71c&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=21428&extexist=1&extstate=1
>DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
>DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=54&in=91xxxxxxxxx&id=%BF7%2FlJ%17%D6m%B5%A2m%1E%B1g%98Wf%21%E2%2A&lg=en&lc=GB&token=afb874c7503e3d7ea86604429f29e71c&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=21428&extexist=1&extstate=1
>INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}
>
>DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
>DEBUG:yowsup.common.http.warequest:cc=54&in=91xxxxxxxxx&lc=GB&lg=en&sim_mcc=722&sim_mnc=010&mcc=722&mnc=010&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2075&rchash=7d6d7f76f1e35565e0b4fb7d633dd4cc58ebdb4aecf826e3fa997efe8dcaaf26&anhash=I%00%81v%948%F6Y%B2%F77%BA%16%B6G%90%C5H+%C9&extexist=1&extstate=1&token=afb874c7503e3d7ea86604429f29e71c&id=%18%21%B2%A9U%F0%BE%A2Ru%CCF%17%BDM4%C1%5Ez%0C
>DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
>DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=54&in=91xxxxxxxxx&lc=GB&lg=en&sim_mcc=722&sim_mnc=010&mcc=722&mnc=010&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2075&rchash=7d6d7f76f1e35565e0b4fb7d633dd4cc58ebdb4aecf826e3fa997efe8dcaaf26&anhash=I%00%81v%948%F6Y%B2%F77%BA%16%B6G%90%C5H+%C9&extexist=1&extstate=1&token=afb874c7503e3d7ea86604429f29e71c&id=%18%21%B2%A9U%F0%BE%A2Ru%CCF%17%BDM4%C1%5Ez%0C
>INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}
>
>status: fail
>retry_after: 3600
>reason: no_routes

**Comment by emiquey** [comment]
I solved the problem by using the _-E android_ a suggested. I guess it fixes the issue.
By the way, when trying to use the account I registered in pidgin with whatsapp-purple, I also needed to specify a more recent version of the default phone (namely Android-2.31.151-443) to make it work.
