### ISSUE TITLE
Can´t register with reason "no_routes" and got blocked after my third try

### ISSUE THREAD

**Issue by bredmich** [tgalal/yowsup#1645]
Hi there,

just wanted to use yowsup to let my OpenHAB send me Whatsapp messages about actions in my Smart Home.
So i ordered a new prepaid SIM from Vodafone in Germany.
The SIM arrived today and i tried to register the yowsup service.
`sudo yowsup-cli registration --requestcode sms --phone 491520******* --cc 49 --mcc 262 --mnc 02`

I get the common error with "no_routes":
`INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":60,"voice_wait":60}

status: fail
retry_after: 3600
reason: no_routes`

After my third try, i got banned from whatsapp ...
I already send them a message to reopen my number for registration.

Any ideas ?

Cheers
Michael

**Comment by faizans-cuelogic** [comment]
Hey,
I had the same issue, these solved my issue.

sudo yowsup-cli registration --requestcode sms --phone 491520******* --cc 49 --mcc 262 --mnc 02 -E android
or 
sudo yowsup-cli registration --requestcode sms --phone 491520******* --cc 49 -E android

**Comment by bredmich** [comment]
Hi,
i´ll try that once my number is able to register again.

Thanks !

**Comment by pdocarmo** [comment]
this worked for me. thanks!!!

**Comment by bredmich** [comment]
I tried it again with the `-E android` trick and it worked fine !
Thanks !

Cheers
Michael
