### ISSUE TITLE
Error: Ping Timeout

### ISSUE THREAD

**Issue by sowerkoku** [tgalal/yowsup#1649]
@tgalal
I have problems with the "echoclient"

```
yowsup-cli v2.0.15
Using yowsup v2.5.0
```

`./yowsup-cli demos -c bot.config -e`

error:

```
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="478">
</iq>


DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="xxxxxxxxx@s.whatsapp.net" id="478" t="1465968304">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="479">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="xxxxxxxxx@s.whatsapp.net" id="479" t="1465968354">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="480">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 2
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Ping Timeout
```

**Comment by langioletto** [comment]
I just tried it and it works

yowsup-cli demos -c /root/.yowsup/config -e

**Comment by sowerkoku** [comment]
It works, but falls after a while.

**Comment by langioletto** [comment]
this is normal, you must kill and restart after a while

I put this command in cron

#Esegue un check Yowsup ogni minuto.
* * * * * root /usr/script/Yowsup_Check.sh > /dev/null 2>&

Yowsup_Check.sh

#!/bin/sh

#Questo script esegue un check di controllo sull'esecuzione di Yowsup

namebin="python /root/.yowsup/run.py"

#Controlla se $namebin è in esecuzione
if [ "$(pidof $namebin)" ]
 then
 echo "$namebin... ok"
 else
 echo "$namebin... down"
 $namebin &
fi

exit 0

**Comment by sowerkoku** [comment]
@langioletto 

modify this:
```
#Esegue un check Yowsup ogni minuto.
* * * * * root /usr/script/Yowsup_Check.sh > /dev/null 2>&
```

for this
```
#Esegue un check Yowsup ogni minuto.
* * * * * root /usr/script/Yowsup_Check.sh > /dev/null 2>&1
```

**Comment by langioletto** [comment]
Hi, thank you for the correction .. is already so, copy and paste error. :)
