### ISSUE TITLE
Set .

### ISSUE THREAD

**Issue by AlphaJack** [tgalal/yowsup#1651]
.

**Comment by yezgar** [comment]
Yesterday work for me in v2.4. 
Try in an Android device.

**Comment by AlphaJack** [comment]
>Try in an Android device
Thanks, trying with setPicture worked, but it also showed me my new status, like if it was waiting for me to emulate Android before applying both changes. Any idea about how to simply change the nickname (the one displayed in push notifications and instead of the phone number in groups)?

**Comment by langioletto** [comment]
See here

https://github.com/tgalal/yowsup/issues/1648#issuecomment-226345506

**Comment by AlphaJack** [comment]
>See here #1648 (comment)

What should I see? I don't get how to change the nickname

**Comment by langioletto** [comment]
#Set name presence

Read more and maybe download the file

**Comment by AlphaJack** [comment]
Where should I put the files? Expecially _run.py_

**Comment by sowerkoku** [comment]
/path/yowsup/run.py
/path/yowsup/layer.py

**Comment by AlphaJack** [comment]
Now if I try to restart yowsup with `sudo python yowsup-cli demos -c config -y`, where "config" is a configuration file with my credentials, it gives me this: Traceback (most recent call last):

>   File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 268, in process
    self.startCmdline()
  File "yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/home/pi/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/pi/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
ImportError: cannot import name YowsupCliLayer

where does this error come from?

**Comment by sowerkoku** [comment]
@AlphaJack 
ImportError: cannot import name YowsupCliLayer` --> this is the fault.
sudo it's not necessary

try deleting ~/.yowsup/number/axolotl.db

if this does not work. reinstall yowsup, probably fail a file in yowsup.
