### ISSUE TITLE
Need a developer to create a script to send Whatsapp messages

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#1652]
I'm looking for a script developer ( program ) send Whatsapp messages. I have a
working automatic channel creator for Whatsapp (number + hash). I need
a script with characteristics :
1. Send a text, picture + text
2. Send more than 50 messages from one channel .
3. Report on sending messages.
4. Sending more than 5,000 messages per hour with a single PC (Ubuntu 16.04)

Waiting for your suggestions. Interested in the development and
maintenance of the script .

I do not spam . in my country it is not legal . I am the owner of a
large travel company , I want to inform my customers about hot tours.
This is completely legal. These people have given their consent to
receive this information.

**Comment by cyberp1983** [comment]
My Skype: int-el

**Comment by minimaldev** [comment]
added

**Comment by minimaldev** [comment]
mm he dont pay the upfront payment maybe is a scammer
