### ISSUE TITLE
Image link broken in wiki

### ISSUE THREAD

**Issue by prakhar-goel** [tgalal/yowsup#1657]
On https://github.com/tgalal/yowsup/wiki/Architecture the Stacks and Layers diagram image is broken. The [image url](https://camo.githubusercontent.com/5650171b98448d8f071dde1849f1d33cd65f616e/687474703a2f2f696d616765736861636b2e636f6d2f612f696d673636312f373032322f6f41757231642e706e67) returns 404 Not Found error.

**Comment by langioletto** [comment]
and 'was removed, see here new working scripts

https://github.com/tgalal/yowsup/issues/1648#issuecomment-226345506

**Comment by ulybu** [comment]
dup of #1466

**Comment by Messiefee** [comment]
Hi @prakhar-goel How many days have been using the program ?? You don't be blocked.
