### ISSUE TITLE
Collection layer.py

### ISSUE THREAD

**Issue by langioletto** [tgalal/yowsup#1659]
I invite all users to put in download here their layer.py

It 'very interesting this project and it would be nice to learn new things from all of us

[**My project is here**](https://github.com/tgalal/yowsup/issues/1648#issuecomment-226345506)

Thank you all :+1:

**Comment by schoerg** [comment]
I think most of your `time.sleep()` are unnecessary.

**Comment by langioletto** [comment]
No, it emulates the human

Too much haste? :)

Put here your "layer.py" :+1:

**Comment by schoerg** [comment]
Yeah, but it is not needed I think, I don't use them. (Not banned or anything)

My layer.py would be a bit large.

**Comment by langioletto** [comment]
self.toLower(messageProtocolEntity.ack()) #Set received (double v)
            time.sleep(0.5)
            self.toLower(PresenceProtocolEntity(name = name)) #Set name Presence
            time.sleep(0.5)
            self.toLower(AvailablePresenceProtocolEntity()) #Set online
            time.sleep(0.5)
            self.toLower(messageProtocolEntity.ack(True)) #Set read (double v blue)

In this logical order, when accessing whatsapp first is the dual v Gray then double v blue, not together

**Comment by schoerg** [comment]
I am online.

**Comment by langioletto** [comment]
After that you're online
self.toLower(messageProtocolEntity.ack(True)) #Set read (double v blue)
Not before

You are always online 24/7 ?

**Comment by schoerg** [comment]
Yes.

I am online before that too, I could not receive messages if I were not.

**Comment by langioletto** [comment]
v04
Added log unauthorized phone number
Is logged: Sender, Number sender, Message text received

**Comment by schoerg** [comment]
https://gist.github.com/schoerg/330a5d7520034801bd9a93915def78a7

If you are interested. I removed the functions, but you get the idea I guess. Needs some refactoring and cleanup too.

**Comment by langioletto** [comment]
you have removed the the most beautiful part.... :)

**Comment by schoerg** [comment]
It was not really beautiful, that's why I removed it. :/

**Comment by langioletto** [comment]
can I ask you a question?

if I put a ping too long, waiting to run a script

            if message.lower() == 'ciao':
                answer = "Ciao "+namemitt+" "
                os.system('Find_SMS_SIM_CARD.sh')
                time.sleep(180)
                answer = "Ciao "+namemitt+" "
                self.toLower(textmsg(answer, to = recipient ))
                print answer

At the end of 180 seconds the answer "Ciao " will not is sent to me

but at the terminal I see the print answer, then the .py is not blocked

Now I send a new whatsapp the number does not respond until I do not kill and restart python

Max time.sleep(120) wotk

how do I fix?

Thanks

**Comment by schoerg** [comment]
`time.sleep()` will block, and I don't know if yowsup uses threads to do something different in the meantime, so keepalives might not be sent.

I don't know what `Find_SMS_SIM_CARD.sh` does but you could rearrenge stuff a bit.
Use `Popen()`, which will not block on waiting for the output and just send the "Ciao" message immediateley. Also you have `answer = "Cia..."` two times in there.

**Comment by sowerkoku** [comment]
such high values are not necessary.

I occupy something like this in my script:

```
       self.toLower(messageProtocolEntity.ack())
        time.sleep(random.randrange(4,13))
        self.toLower(AvailablePresenceProtocolEntity())
        time.sleep(random.randrange(2,3))
        self.toLower(messageProtocolEntity.ack(True))
        time.sleep(random.randrange(3,4))

        self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_TYPING, Jid.normalize(messageProtocolEntity.getFrom(False)) ))
        time.sleep(random.randrange(4,5))
        self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_PAUSED, Jid.normalize(messageProtocolEntity.getFrom(False)) ))
        time.sleep(random.randrange(2,3))
        self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_TYPING, Jid.normalize(messageProtocolEntity.getFrom(False)) ))
        time.sleep(random.randrange(5,6))
        self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_PAUSED, Jid.normalize(messageProtocolEntity.getFrom(False)) ))
        time.sleep(random.randrange(2,3))

        self.toLower(enviar)
        time.sleep(random.randrange(2,3))
        self.toLower(UnavailablePresenceProtocolEntity())
```

**Comment by Gab0** [comment]
@langioletto Fork yowsup with your code in order to show here, should be better than using mega.nz  :+1:

**Comment by langioletto** [comment]
Better to download the files, they avoid formatting errors

**Comment by controller-t** [comment]
Dear All, Could someone please add function to upload image/video file. eg If I send Photo then it should upload a file on specific path.

**Comment by sowerkoku** [comment]
We'll see when we have some time [here](https://github.com/tgalal/yowsup/issues/1648#issuecomment-231619850)
