### ISSUE TITLE
I can´t send a image. 

### ISSUE THREAD

**Issue by marcoarildo** [tgalal/yowsup#1663]
Auth: Logged in!
[connected]:/image send "55999999999" /tmp/teste1.png
[connected]:ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer write() argument 1 must be string or read-only buffer, not bytearray
Traceback (most recent call last):
  File "/u01/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 86, in run
    ssl_sock.write(bytearray(POST.encode()))
  File "/usr/lib64/python2.6/ssl.py", line 148, in write
    return self._sslobj.write(data)
TypeError: write() argument 1 must be string or read-only buffer, not bytearray
ERROR:yowsup.demos.cli.layer:Upload file /tmp/teste1.png to 
https://mmi464.whatsapp.net/u/RKEE_8ctvzvkgMPBAUYF06zYcFsABTXyx7KSdQ/AhAFMt1opBwguYzgYp6YwIIxDP2_ZdyTgrcVlLOgGGFK for 559999999999@s.whatsapp.net failed!

Has anyone ever experienced this ?

**Comment by marcoarildo** [comment]
Anybody got sucess to send image ? with this version:
yowsup-cli v2.0.15
Using yowsup v2.5.0

**Comment by Messiefee** [comment]
Man I have a cuestion, Are you Banned?? You don't have this problem,
How many messages you send per day and how many users ?

**Comment by marcoarildo** [comment]
@Messiefee 

Hi, I got sucess to send a message, but when try send a image i got this error. Takes a look 
Tks for help.

# python yowsup-cli demos -y -c config2
yowsup-cli  v2.0.15
yowsup      v2.5.0

[offline]:/L
Auth: Logged in!
[connected]:/message send 5511000000000 "hello word"
[connected]:Sent: 1466707115-1
[connected]:

[connected]:/image send 5511000000000 /tmp/teste1.png
[connected]:ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer write() argument 1 must be string or read-only buffer, not bytearray
Traceback (most recent call last):
  File "/u01/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 86, in run
    ssl_sock.write(bytearray(POST.encode()))
  File "/usr/lib64/python2.6/ssl.py", line 148, in write
    return self._sslobj.write(data)
TypeError: write() argument 1 must be string or read-only buffer, not bytearray
ERROR:yowsup.demos.cli.layer:Upload file /tmp/teste1.png to https://mmi464.whatsapp.net/u/RKEE_8ctvzvkgMPBAUYF06zYcFsABTXyx7KSdQ/AhAFMt1opBwguYzgYp6YwIIxDP2_ZdyTgrcVlLOgGGFK for 5511000000000@s.whatsapp.net failed!

[connected]:

**Comment by marcoarildo** [comment]
Guys, 
I did download with python3 and the problem was solved.

[root@server yowsup]# python3 yowsup-cli demos -y -c config2
[offline]:/L
Auth: Logged in!
[connected]:/image send 5511999999999 /tmp/teste1.png
[connected]:Sent: 1466715898-2
[connected]:

Tks guys

**Comment by MuhammadHuzaifah** [comment]
hii @marcoarildo do you compile the yowsup master using python3 before you running command above. i'am getting error when running yowsup using python3.

thanks

**Comment by xwanyiri** [comment]
@MuhammadHuzaifah try `sudo pip install six`

**Comment by MuhammadHuzaifah** [comment]
thankyou @xwanyiri 
i'am already had six 
`
pip install six
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
`

shoud i install on python3 ?? then how??

thanks
