### ISSUE TITLE
echoclient does not work

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1676]
HI I downloaded the latest version.However, I get the following error message:
I am using Python 2.7.6 (cannot upgrade to Version >= 3).
"pip install protobuf" etc. didn't work tough. I got the same error.

Can anybody help me out to fix that issue?

#./yowsup-cli demos -c config -e --unmoxie

Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 270, in process
    self.startEcho()
  File "./yowsup-cli", line 300, in startEcho
    from yowsup.demos import echoclient
  File "/yowsup/demos/echoclient/__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "/yowsup/demos/echoclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer
  File "/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import ImageDownloadableMediaMessageProtocolEntity
  File "/yowsup/layers/protocol_media/protocolentities/__init__.py", line 3, in <module>
    from .message_media_downloadable_image import ImageDownloadableMediaMessageProtocolEntity
  File "/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 4, in <module>
    from yowsup.layers.protocol_messages.proto.wa_pb2 import ImageMessage
  File "/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

**Comment by jlguardi** [comment]
Don't use --unmoxie or you will have problems with encrypted messages and install protobuf (it's a dependency of the project)

**Comment by kw005** [comment]
OK. What do you mean by "dependency of the project"? Is there a version of yowsup which is better for me, e.g. using compiles fine with python version < 3?

**Comment by kw005** [comment]
I have Python 2.7.6 and 3.3 on my system.
How can I force using python 3.3 ? Is it necessary?

**Comment by jlguardi** [comment]
I mean that run 'setup.p install' to get protobuf.
 If you want to to python 3.3 exec 'python3 setup.py install' or 'python2 setup.py install' for python2.7. 
I use python 2.7 an works and many people use python 3. It's up to you.

**Comment by kw005** [comment]
I already tried "python3 setup.py install" I already tried that, I get the same error tough ;(
I would go also for python2. 'setup.p install' - where should I run that command, in the yowsup dir ?

**Comment by kw005** [comment]
#python setup.py install
...
/usr/lib/python2.7/site-packages/python_axolotl-0.1.35-py2.7.egg
Searching for argparse==1.2.1
Best match: argparse 1.2.1
Adding argparse 1.2.1 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for python-dateutil==2.1
Best match: python-dateutil 2.1
Adding python-dateutil 2.1 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for protobuf==3.0.0b3
Best match: protobuf 3.0.0b3
Processing protobuf-3.0.0b3-py2.7.egg
protobuf 3.0.0b3 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg
Searching for python-axolotl-curve25519==0.1
Best match: python-axolotl-curve25519 0.1
Processing python_axolotl_curve25519-0.1-py2.7-linux-x86_64.egg
python-axolotl-curve25519 0.1 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/python_axolotl_curve25519-0.1-py2.7-linux-x86_64.egg
Searching for pycrypto==2.6
Best match: pycrypto 2.6
Adding pycrypto 2.6 to easy-install.pth file

Using /usr/lib64/python2.7/site-packages
Searching for setuptools==0.9.8
Best match: setuptools 0.9.8
Adding setuptools 0.9.8 to easy-install.pth file
Installing easy_install script to /usr/bin
Installing easy_install-2.7 script to /usr/bin

Using /usr/lib/python2.7/site-packages
Finished processing dependencies for yowsup2==2.5.0

---
Compiles fine like always. But after that I get the error mentioned above.

**Comment by kw005** [comment]
Why is yowsup always breaking up, auth errors and so on? It isn't stable at all. Every time when reinstalling it, those errors occur...

Now, I get: Doesn't make fun.

from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
