### ISSUE TITLE
can't send utf-8 messages to groups

### ISSUE THREAD

**Issue by abloch** [tgalal/yowsup#1678]
when sending a utf-8 message to a group it says: "message sent" although it didn't.

I tested this through many scenarios and here are my finding:
- the problem is not consistent, the longer the message - the more likely it is not to be sent. although, for the same message with about 20-30 characters - it's sometime been sent and sometimes not (maybe depending on how it's encrypted?)
- the problem only happens when sending to a group. sending the very same message to an individual works perfectly
- the problem happens on both python 2.7.6 and 3.4.3
- the problem only happens when sending with -s. the same message gets sent perfectly from the interactive cli (running with -y, then /message send ...)

for your convenience, here's an example of a command that fails:
`python ~/projects/yys/yowsup-cli demos -c ~/.yowsupConfig -s .....-....... 'ولد مايكل هارت في واشنطن في الثامن من آذار عام 1947 لأب عمل خلال الحرب العالمية الثانية في مجال فك الشفرات العسكرية، ثم أنتقل مع أسرته الى "ألينويز" ليعمل هو وزوجته أستاذين جامعيين'`

please find attached the (not very helpful) log files in which I sent the same message bot to a group ad to an individual

[group.txt](https://github.com/tgalal/yowsup/files/346830/group.txt)
[individual.txt](https://github.com/tgalal/yowsup/files/346829/individual.txt)

**Comment by sowerkoku** [comment]
ok, let me see

**Comment by sowerkoku** [comment]
the problem is here: `yowsup/demos/sendclient/layer.py`
fails to define a process to correct your problem

**Comment by abloch** [comment]
@sowerkoku - you say:

> fails to define a process to correct your problem

I'm not sure what do you mean by that

**Comment by janboll** [comment]
Are you using the latest yowsup version?
I also had problems with groups, mine where related to an old yowsup version and missing encryption.

**Comment by abloch** [comment]
yes, I'm using the oldest version of yowsup

**Comment by sowerkoku** [comment]
@abloch 

I occupy the updated master.
as you say, by the console (option -y) works well. debugged process costs there are clear differences in the treatment of the message.

The -s option does not encrypt the message.

I also tried with different encodings, but not going out there the solution.

**Comment by abloch** [comment]
that's odd because:
1. this only fails for group messages. private messages work just fine
2. the code that the -s uses the very same layers as the -y option. I really  think it is encrypted as well

**Comment by sowerkoku** [comment]
Easy. Run "-s" and "-y" with "-d". 
Sends the same message. You see that the structure is different.

**Comment by abloch** [comment]
@sowerkoku it is indeed different but reading the code there's no reason where the difference comes from.
Further more, why is this difference affecting only utf8 messages sent to groups?
