### ISSUE TITLE
installing yowsup

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1679]
Hi,

if I install yowsup, the installer is using the libs of "/usr/lib/python3.3/site-packages"

 Using /usr/lib/python3.3/site-packages
 Finished processing dependencies for yowsup2==2.5.0

However I would like to use "/usr/lib/python2.7/site-packages" instead. Using
# python setup.py build_ext --build-lib=/usr/lib/python2.7/site-packages install
doesn't work. How can I force to use that 2.7 lib, even if I compile it by python2.7 setup.py install
it uses 3.3 packages...thats driving me crazy

Thanks a ton for any help!!!!

**Comment by TheJens90** [comment]
use `pip install yowsup`
that will install yowsup into python2.7

**Comment by kw005** [comment]
pip install yowsup2
Requirement already satisfied (use --upgrade to upgrade): yowsup2 in /usr/lib/python3.3/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python3.3/site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python3.3/site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): python-axolotl>=0.1.7 in /usr/lib/python3.3/site-packages (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg (from yowsup2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python3.3/site-packages (from python-dateutil->yowsup2)
Collecting protobuf<3.0.0-alpha-2,>=2.6 (from python-axolotl>=0.1.7->yowsup2)
  Using cached protobuf-2.6.1.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1519, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/usr/lib/python3.3/site-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/usr/lib/python3.3/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named 'pkg_resources.extern'; pkg_resources is not a package
