### ISSUE TITLE
code=105

### ISSUE THREAD

**Issue by bduran78** [tgalal/yowsup#1680]
After Registring yowsup I obtain the following error:
```
DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized code="105" expire="84817" retry="42408">
</not-authorized>
</failure>
```
How to avoid it? any idea?

**Comment by bduran78** [comment]
not-authorized code="105" expire="84817" retry="42408"

**Comment by assegaf** [comment]
blocked for using unofficial apps, 24 hour bann, seem common.
