### ISSUE TITLE
setting profile image

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1681]
is it somehow possible to set the profile image using yowsup?

**Comment by jlguardi** [comment]
See demos/cli/layer.py

You can get almost everything from here.

**Comment by kw005** [comment]
can you get me the stuff more user friendly? ;) like how do I do it via bash command line?

**Comment by jlguardi** [comment]
It is not supported via bash command. So you need to implement your own stack/layer or use the cli. So I pointed you to this tool.
If you want an script for bash, you can extract the function from cli/layer.py‎ and parse input args.

**Comment by kw005** [comment]
OK, sounds complicated. What would be the steps using cli?
