### ISSUE TITLE
Price and expiration date

### ISSUE THREAD

**Issue by bredmich** [tgalal/yowsup#1684]
Hi there,

i just registered my yowsup-cli with whatsapp and got the following info:
`status: ok
kind: free
pw: ***
price: 0,89 €
price_expiration: 1471076306
currency: EUR
cost: 0.89
expiration: 4444444444.0
login: ***
type: new`

The price expiration date is: 2016-08-13 09:18:26

Do i have to pay the 0,89€ like i did when i first installed the app on my iPhone ?

Cheers
Michael

**Comment by jlguardi** [comment]
No, it's for free until expiration. I mean, forever.

**Comment by bredmich** [comment]
Ok thanks.
I was confused by the price information.

Cheers
Michael
