### ISSUE TITLE
English version for donation page 

### ISSUE THREAD

**Issue by yusufaly** [tgalal/yowsup#1687]
Donate button takes me into what it looks like a german page. I would like to donate to support this great effort but I want an English version to make it easier for me . 
Keep up the good work !

**Comment by jlguardi** [comment]
probably @tgalal could update to something like:
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=tarek%40wazapp%2eim&lc=US&item_name=yowsup&no_note=0&currency_code=EUR&bn=PP-DonationsBF%3abtn_donateCC_LG.gif%3aNonHostedGuest

From https://www.paypal.com/au/cgi-bin/webscr?cmd=_donate-intro-outside
