### ISSUE TITLE
can I get someone name with their number

### ISSUE THREAD

**Issue by omri1100** [tgalal/yowsup#1690]
maybe I am dumb but i just cant find full list of methods and attributes of objects in yowsup.
I want to make a bot that will remember people, if they send a message it will write their name and number in a database. now I just dont know how to get the name with a number.
I suppose it is possible since it can be done in the original whatsapp.

thank you very much and if there is a list of all the methods and attributes of objects in yowsup i will be glad to have it.

**Comment by jlguardi** [comment]
You can get the name by MessageProtocolEntity.notify

By now, there isn't a list of all methods or attributes ‎but you can see most of them in cli/layer.py

**Comment by sowerkoku** [comment]
probably with "messageProtocolEntity.getNotify()"
