### ISSUE TITLE
Old version error

### ISSUE THREAD

**Issue by icam0** [tgalal/yowsup#1695]
I just downloaded and installed the most recent version of yowsup (2.5) but i still get an error for regristration:

>DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.89 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=31&in=6XXXXXXXX&lc=GB&lg=en&sim_mcc=204&sim_mnc=008&method=sms&token=99942c8af9022f6d46727db4f760fd74&id=%25%91%C9%D53%C5%E6%CA%B5%84%B9S%9C%8B%B1%40%CA%2Bl%F8
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=31&in=681177955&lc=GB&lg=en&sim_mcc=204&sim_mnc=008&method=sms&token=99942c8af9022f6d46727db4f760fd74&id=%25%91%C9%D53%C5%E6%CA%B5%84%B9S%9C%8B%B1%40%CA%2Bl%F8
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
Whatsapp version 2.12.89????
You aren't update. Download, install and try again.
