### ISSUE TITLE
send a message without echoclient

### ISSUE THREAD

**Issue by icenach** [tgalal/yowsup#1697]
Hello!
I am very new to python and not handling well the library yowsup ....
I can send a message to a number, but only with a fact. I can help with a script that can send a message to a certain number ("123456789@s.whatsapp.net") without using the sample code echoclient. Thank you.

sorry for my English ... is a translator

**Comment by sowerkoku** [comment]
[see here](https://github.com/tgalal/yowsup/issues/1648) or [here](https://github.com/hoehermann/wxpyWha)

**Comment by rodrigolopezguerra** [comment]
This is not an issue , it should be closed. Please refer to the documentation : https://github.com/tgalal/yowsup/wiki/Sample-Application

**Comment by Dargmuesli** [comment]
Or just use the sendclient instead of the echoclient...
