### ISSUE TITLE
ImportError: No module named 'google'

### ISSUE THREAD

**Issue by alexisjk** [tgalal/yowsup#1700]
Hi All!
I am trying this fantastic Client so i followed all steps to make it work.
I am able to get the the code and then to get the special Password.
After i try to send a message :
-**python yowsup-cli demos --config yowsup-cli.config --send 15xxxxx “Message”**
I get in the console :
```
from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google'
```
Thank you very much in advance!

**Comment by senomuktiadji** [comment]
install protobuf module first.
how did you install yowsup?
if you're installing yowsup using 'python setup.py install' then it supposed to check all dependencies including protobuf, make sure you're connected to internet.

**Comment by alexisjk** [comment]
Hi!
I reinstalled all ,and i have not that problem again!
Anyway i am dealing with the famous python-axolotl-curve25519.
I followed all steps to install it on Windows,but after python setup.py install ,i get :

`unning python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir C:\Users\Silvina\AppData\Local\Temp\easy_install-rr0edq_r\python-axolotl-curve25519-0.1\egg-dist-tmp-740ewnmr
curve25519module.c: In function 'calculateSignature':
curve25519module.c:50:20: warning: pointer targets in passing argument 1 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                    ^
curve25519module.c:17:5: note: expected 'unsigned char *' but argument is of type 'char *'
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:31: warning: pointer targets in passing argument 2 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                               ^
curve25519module.c:17:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:43: warning: pointer targets in passing argument 3 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                                           ^
curve25519module.c:17:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c:50:64: warning: pointer targets in passing argument 5 of 'curve25519_sign' differ in signedness [-Wpointer-sign]
    curve25519_sign(signature, privatekey, message, messagelen, random);
                                                                ^
curve25519module.c:17:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_sign(unsigned char* signature_out,
     ^
curve25519module.c: In function 'verifySignature':
curve25519module.c:76:36: warning: pointer targets in passing argument 1 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                    ^
curve25519module.c:22:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char* signature,
     ^
curve25519module.c:76:47: warning: pointer targets in passing argument 2 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                               ^
curve25519module.c:22:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char* signature,
     ^
curve25519module.c:76:58: warning: pointer targets in passing argument 3 of 'curve25519_verify' differ in signedness [-Wpointer-sign]
     int result = curve25519_verify(signature, publickey, message, messagelen);
                                                          ^
curve25519module.c:22:5: note: expected 'const unsigned char *' but argument is of type 'const char *'
 int curve25519_verify(const unsigned char* signature,
     ^
curve25519module.c: At top level:
curve25519module.c:159:9: warning: initialization makes integer from pointer without a cast
         NULL,
         ^
curve25519module.c:159:9: warning: (near initialization for 'curve25519_module.m_size')
curve/ed25519/additions\curve_sigs.c: In function 'curve25519_keygen':
curve/ed25519/additions\curve_sigs.c:10:6: warning: unused variable 'ed_y' [-Wunused-variable]
   fe ed_y, ed_y_plus_one, one_minus_ed_y, inv_one_minus_ed_y;
      ^
curve/ed25519/additions\zeroize.c: In function 'zeroize':
curve/ed25519/additions\zeroize.c:6:17: warning: unused variable 'retval' [-Wunused-variable]
   unsigned long retval = 0;
                 ^
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x35): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x4d): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x58): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x73): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x7e): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0xb2): undefined reference to `_imp__PyBytes_FromStringAndSize'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x106): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x11e): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x129): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x15d): undefined reference to `_imp__PyBytes_FromStringAndSize'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x191): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x1a9): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x1b4): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x1e4): undefined reference to `_imp__PyBytes_FromStringAndSize'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x237): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x253): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x25e): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x279): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x284): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x2c0): undefined reference to `_imp___Py_BuildValue_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x31a): undefined reference to `_imp___PyArg_ParseTuple_SizeT'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x336): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x341): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x35c): undefined reference to `_imp__PyExc_ValueError'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x367): undefined reference to `_imp__PyErr_SetString'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x3ab): undefined reference to `_imp__PyBytes_FromStringAndSize'
build\temp.win-amd64-3.4\Release\curve25519module.o:curve25519module.c:(.text+0x3d2): undefined reference to `_imp__PyModule_Create2'
collect2.exe: error: ld returned 1 exit status
error: Setup script exited with error: command 'gcc' failed with exit status 1`


Could somebody give me a Clue? Thank you very much!

**Comment by alexisjk** [comment]
It s fixex using Python 3.5 ,i was using Python 3.7
