### ISSUE TITLE
AuthError: not-authorized

### ISSUE THREAD

**Issue by alexisjk** [tgalal/yowsup#1703]
Hi All !
With the last version,after :

**python yowsup-cli demos -l xxxxxxx:b'ZJwKwr98bfObfU9Y2UEtnfdo63k=' --send xxxxx “Mensaje” -E android**
I get:

`File "C:\xxxxxxx\yowsup-master\yowsup\layers\auth\layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "C:\ProyectosAle\Belasoft\Proyectos\yowsup\yowsup-master\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'`

Any Ideas?
I tried some solutions you suggested but they are not working.

Thanks!

**Comment by alexisjk** [comment]
I addes the -- debug and i get :

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure

Thanks!

**Comment by alexisjk** [comment]
When i Try to read the messages using **python yowsup-cli demos -e --config yowsup-cli.config--Debug** i Get:

`DEBUG:yowsup.layers.logger.layer:tx:
<auth user="xxxxxxxx" passive="true" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
\x90·\x9drÓ\x88]    °8,-\x99¤
HEX3:b'0590b7079d1672d388045d1c09b0382c1a2d99a4'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
»       ©¢9¢$ñBÙÊ\x8a>Ò{ÇÖ²\x8eâ
ñ\x98Fu\x88oóeÚêmn\x96(U¼\x94
HEX3:b'bb1b2b3209a9a239a21624f142d901ca8a3ed27bc71ad6b28ee20a2d57c17efa644606b5a1b91cf0d0ce43d1c11c1142b6907d0df1984675886f03f365daea6d6e962855bc94'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>`

**Comment by sowerkoku** [comment]
[see here](https://github.com/tgalal/yowsup/issues/1661)

**Comment by alexisjk** [comment]
The number is Blocked finally...
Thanks sowerkoku!

**Comment by alexisjk** [comment]
I dont understand why,i didnt even sent any message yet

**Comment by sowerkoku** [comment]
si el numero lo registras y lo dejas inactivo o sin uso dentro de las primeras 24hrs. lo bloquean.

**Comment by zenithanon** [comment]
I think its not worth developing anything serious on whatsapp anymore. This blocking/banning issue is becoming too rampant

**Comment by sowerkoku** [comment]
@zenithanon 
It depends, I have 2 bot working perfectly over 3 months ago.

**Comment by zenithanon** [comment]
@sowerkoku 
I wont build a COMMERCIAL application on whatsapp right now
