### ISSUE TITLE
How to unregister phone number on Yowsup?

### ISSUE THREAD

**Issue by apanimesh061** [tgalal/yowsup#1704]
Yesterday I registered on Yowsup in order to test the CLI but today I got banned from WhatsApp. I guess it is because I am using the same number on different clients.
I need to unregister from Yowsup and see if I get unbanned from WhatsApp.

How can I do that?

**Comment by armkof1** [comment]
Hi.

Maybe your phone not are banned...
I know whatsapp make some changes, now yowsup and chat-api does not work.

BR

**Comment by jlguardi** [comment]
Register directly in your phone. Unregister isn't required.

**Comment by apanimesh061** [comment]
@jlguardi I have already registered on Yowsup with my phone number but that number got banned from WhatsApp due to that. I don't think we can register with same number on different devices. I am not sure how to get unbanned. Only thing I thought was to unregister from Yowsup and retry registering on WhatsApp.

**Comment by jlguardi** [comment]
@apanimesh061 as I said unregister is not an option. In fact, when whatsapp bans you, they are 'unregistering' your account. 
Your best option: write to whatsapp support and ask for unblock. So they will require you an screenshot o o official app.
Next time, don't use your personal number!
