### ISSUE TITLE
yowsup-cli registration failing

### ISSUE THREAD

**Issue by doras100p** [tgalal/yowsup#1706]
When I try to register it says:
ImportError cannot import name 'WACodeRequest'

What should I do?

**Comment by jlguardi** [comment]
Repeat installation procedure carefully.

**Comment by doras100p** [comment]
@jlguardi You're right, I didn't notice the installation failed even when I tried to re-install.
It had a "couldn't fine vcvarsall.bat" error.
Solved, thank you!
