### ISSUE TITLE
Can't register: "bad param: number"

### ISSUE THREAD

**Issue by doras100p** [tgalal/yowsup#1709]
Hi!

I receive this error when I try to register:

`INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"bad_param","param
":"number"}\n'
status: b'fail'
reason: b'bad_param'
param: b'number'`

The number is a number I purchased from the service NEXMO, and it can receive text messages.
Thanks!

**Comment by Messiefee** [comment]
Men check the code area, and the mcc and mnc https://en.wikipedia.org/wiki/Mobile_country_code

**Comment by doras100p** [comment]
@Messiefee It's a landline with SMS capabilities. Is this the problem?
I can send SMS's to it.

**Comment by sowerkoku** [comment]
registration is only for voice
