### ISSUE TITLE
My number is always banned after 12 hours listening

### ISSUE THREAD

**Issue by marcoarildo** [tgalal/yowsup#1711]
Hello,

I change yowsup/demos/cli/layer.py and add one call

I change the "onMessage()" on file yowsup/demos/cli/layer.py to after receive the message to call my rotine

-- yowsup/demos/cli/layer.py
...
def onMessage(self, message):
	messageOut = ""
	if message.getType() == "text":
		#self.output(message.getBody(), tag = "%s [%s]"%(message.getFrom(), formattedDate))
		messageOut = self.getTextMessageBody(message)
	elif message.getType() == "media":
		messageOut = self.getMediaMessageBody(message)
	else:
		messageOut = "Unknown message type %s " % message.getType()
		print(messageOut.toProtocolTreeNode())

	formattedDate = datetime.datetime.fromtimestamp(message.getTimestamp()).strftime('%d-%m-%Y %H:%M')
	sender = message.getFrom() if not message.isGroupMessage() else "%s/%s" % (message.getParticipant(False), message.getFrom())
	output = self.__class__.MESSAGE_FORMAT.format(
		FROM = sender,
		TIME = formattedDate,
		MESSAGE = messageOut.encode('latin-1').decode() if sys.version_info >= (3, 0) else messageOut,
		MESSAGE_ID = message.getId()
		)

	self.output(output, tag = None, prompt = not self.sendReceipts)
	if self.sendReceipts:
		self.toLower(message.ack(self.sendRead))
		self.output("Sent delivered receipt"+" and Read" if self.sendRead else "", tag = "Message %s" % message.getId())

	# new lines
	if message.getType() == "text":
		vl_cel_posicao = sender.find("@")           # procura posição do @
		vl_cel_origem = sender[:vl_cel_posicao]     # recupera somente o numero do cel
		self.valida_celular(vl_cel_origem)
...
	
But after 12 hours my number is banned.
Yow can see below. Anybody can help me, because i can´t understand the reason.

...
Iq:
ID: 1225
Type: result
from: 5599988887777@s.whatsapp.net

Iq:
ID: 1226
Type: result
from: 5599988887777@s.whatsapp.net

Iq:
ID: 1227
Type: result
from: 5599988887777@s.whatsapp.net

Auth Error, reason Unhandled stream:error node:

**Comment by sowerkoku** [comment]
message.getFrom(False)   # recupera somente o numero do cel

**Comment by jlguardi** [comment]
I've experienced that too many pings without restart produces a banning.
