### ISSUE TITLE
Getting "reason":"old_version","status":"fail" exception while requesting for pin

### ISSUE THREAD

**Issue by sunny1974** [tgalal/yowsup#1717]
Hi i got {"reason":"old_version","status":"fail"} exception while requesting for pin generation. Please solve me out this and below is my configuration.

public static String RELEASE_TOKEN_CONST = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1462212402694{phone}";

    private static final String RELEASE_TIME = "";
    private final int PORT = 443;                                      
    private final int TIMEOUT_SEC = 2;                                  
    private final String WHATSAPP_CHECK_HOST = "v.whatsapp.net/v2/exist";  
    public static final String WHATSAPP_GROUP_SERVER = "g.us";                   
    private final String WHATSAPP_HOST = "c.whatsapp.net";                 
    private final String WHATSAPP_REGISTER_HOST = "v.whatsapp.net/v2/register"; 
    private final String WHATSAPP_REQUEST_HOST = "v.whatsapp.net/v2/code";      
    public static final String WHATSAPP_SERVER = "s.whatsapp.net";               
    public static String WHATSAPP_DEVICE = "S40";                      
    public static String WHATSAPP_VER = "2.16.7";
    public static String WHATSOS_VER = "14.26";
    public static String WHATSDEVICE_NAME = "Nokia302";

**Comment by habbim** [comment]
Try using this fork https://github.com/schoerg/yowsup 
You also have to use as the default android https://github.com/tgalal/yowsup/pull/1633/files

**Comment by Randl** [comment]
#1716 #1725

**Comment by jlguardi** [comment]
update your code.
