### ISSUE TITLE
Not all users in group get Message

### ISSUE THREAD

**Issue by Guselmur** [tgalal/yowsup#1722]
Hello,

I am member of the volunteer fire brigade in a small village in germany and try to use yowsub as an extra alert system. Normaly we get the alert via pager but sometimes the radio is in trouble and some people do not get it. The charging unit of the pager has a electrical relay which interconnect to pins so u can switch a lamp on if the alert arrive the pager. I put the pins on a raspberry pi, and send a message to a WhatsApp group. 

I have no practise on python so i try to do that via C++ in a very simple code:

    `
    int main() {
     string groupID = "491511***********-1470173817@g.us";

      // Starte die WiringPi-Api
      if (wiringPiSetup() == -1)
        return 1;
      pinMode(0, OUTPUT);
      pinMode(2, INPUT);

      bool msg_sended = false;

      string message = "System wurde gestartet!";
      string adminNumber = "491511***********";

      system(("/home/pi/yowsup/yowsup-cli demos -s "+ adminNumber +" \""+ message +"\" -c /home/pi/yowsup/config").c_str());
      // Dauerschleife
      while(1) {
        digitalWrite(0, 0);

    // GPIO lesen
    if(digitalRead(2)==1) {
	if (!msg_sended)
	{
		  message = "Melder ging so eben auf! Einsatz oder Probealarm!";
    // An die Gruppe senden
		const char* cmd2Send = ("./yowsup-cli demos -c config -s \""+ groupID +"\" \""+ message +"\"").c_str();
 
		system(cmd2Send);

    	}
          // LED und Beepersignal
          digitalWrite(0, 1);
          delay(100);
          digitalWrite(0, 0);
          delay(100);
        }else
	    {
	        msg_sended = false;
      	        delay(100);
	    }
      }
    }`

Now we get a few problems:

- Sometimes yowsub didn't send a message to the group but in commad line its look like, but LED is flashing so i get the alert (20% of all alerts)

- We did a test run with a few off our members and its usally works, now i invite the other member and in the group with 26 members 3 members dont resive the message.

Which other information do you need to help me with that? Are there any logs?

Is there a way to get the receipt? So i can check if there is no receipt from the other guys i resend the message?

Thanks for helping, sorry for my bad english

Tobias

**Comment by jlguardi** [comment]
Please, post debug logs and reopen the issue .

Please, try to limit this forum for reporting yowsup issues otherwise, it's impossible to answer everybody.
