### ISSUE TITLE
Received to a file

### ISSUE THREAD

**Issue by mrdamaia** [tgalal/yowsup#1724]
Hi folks,

How can I do to send the received messages to a txt file?

**Comment by Mantauwhite** [comment]
@mrdamaia until now you can't received or send file except image, audio, or video.
Because handler media type doesn't support except image, audio, or video.

CMIIW

**Comment by mrdamaia** [comment]
@Mantauwhite But my throuble is, save in someware the received messages.

**Comment by mrdamaia** [comment]
like a log from received messages

**Comment by ragowthaman** [comment]
```
f = open("incoming.txt", 'a') #append mode
f.writelines("%s,%s,%s,%s\n" %(messageId, messageFrom, messageBody, messageParticipant))
f.close()
```

will store the incoming text messages incrementally in a file called `incoming.txt`

**Comment by Mantauwhite** [comment]
@mrdamaia sorry about missunderstanding.
You can try correction answer @ragowthaman .

**Comment by mrdamaia** [comment]
Thank you guys!
