### ISSUE TITLE
character limit on group message

### ISSUE THREAD

**Issue by erjolb** [tgalal/yowsup#1728]
Hi,
I've set up the below command to send alerts via nagios. What I've noticed though is that when I send the message to a group, it is sent but it's not being received. If I shorten the message though then the message is received. But whe I use a single contact instead of a group the message then is sent without problems. Is there a limit on how many characters you can send for a group message?

thanks,
Erjol

Command:
yowsup-cli demos -c /etc/yowsup-cli.conf -s 49xxxxxxxxxx-1471509469@g.us "** NAGIOS Notification ** -- Type: PROBLEM -- Service: check_ntp_time -- Host:LogServer--Address: 10.15.100.200 -- State: CRITICAL--Date/Time: Mon Aug 22 09:13:40 CEST 2016--Additional Info: NTP CRITICAL: Offset 72.19936407 secs--Duration: 0d 0h 0m 4s"

**Comment by behali** [comment]
Hi,

same problem here. Messages which exceeds a a certain length (~140 characters, but depents on content) are not received by group members when sending it directly from the command line although response is successful ("INFO:yowsup.demos.sendclient.layer:Message sent"). 

When using the interactive mode (-y)  there is no problem, then the same long messages are received in the group. 

Is there maybe a problem with the encoding when using the command line mode?

Thanks,
Bernd

**Comment by jlguardi** [comment]
Please, post debug logs and then reopen the issue.

It seems easy to debug and fix so it would be appreciate to get a PR.
