### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by oregehr** [tgalal/yowsup#1729]
Hello,

I know that this issue has been discussed some times recently, but the registration currently does not seem to work, maybe due to outdated keys?

yowsup-cli  v2.0.15
yowsup      v2.5.0

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

Installed yowsup with

'git clone git://github.com/tgalal/yowsup.git'

and

'python setup.py install'.

Then tried the registration with 

'yowsup-cli registration --requestcode sms --phone 49170xxxxxxx --cc 49 --mcc 262 --mnc 01'

**Comment by rroqueCoddera** [comment]
I had the same problem with the same version.

Country Code:55 PHONE:1195411XXXX MCC:724 MNC:31

{'status': u'fail', 'kind': None, 'code': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': None, 'currency': None, 'length': None, 'cost': None, 'param': None, 'reason': u'old_version', 'login': None, 'type': None, 'method': None, 'expiration': None}

**Comment by jlguardi** [comment]
See #1716 and #1725.

**Comment by jlguardi** [comment]
See #1716 and #1725.

**Comment by jlguardi** [comment]
See #1716 and #1725.
