### ISSUE TITLE
Registration on Windows

### ISSUE THREAD

**Issue by CHS-Systems** [tgalal/yowsup#1734]
Running Windows 10 X64.
Opened CMD, and:
python
import yowsup
yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXX --cc 55

-> Press enter give me the error:
File "stdin", line 1
yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXX --cc 55
............................................^
SyntaxError: invalid syntax

-> Like "registration" isnt a parameter?
Thanks adv.

**Comment by jlguardi** [comment]
yowsup-cli is a command line application not a python command. Run directly from CMD.
