### ISSUE TITLE
Error INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by rfminelli** [tgalal/yowsup#1735]
/etc/yowsup/config.conf
cc=55
phone=55189xxxxxxxx
id=55189xxxxxxxx
password=

yowsup-cli registration --requestcode sms --config /etc/yowsup/config.conf
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

Please, how to solve this problem?

**Comment by jlguardi** [comment]
See #1716 and #1725
