### ISSUE TITLE
Few Reasons Whatsapp Blocking Numbers

### ISSUE THREAD

**Issue by brittson** [tgalal/yowsup#1736]
Hi Guys , this might be not related to the api particularly but here are few observations 

1. Whatsapp Banning policy is much strict now even from official apps 
2. They are blocking numbers which are previously registered and banned multiple times 
3. They are blocking numbers if your IP is blacklisted 
4. The bans are permanent not temporary 
5. If you send multiple similar messages from a new number to contacts who doesn't have your number saved on their phone  
6. So its a must now that your contacts have the number saved otherwise the number will be permanently banned.
spammers made difficult for other devs who are actually building something meaningful

**Comment by assegaf** [comment]
the message is end2end encrypted so there is no more rules : sending too many similar message to contacts.

**Comment by ftbarata** [comment]
HI @brittson  and @assegaf . I was testing with two numbers and they were blocked today. I was not sending messages. I was using the Echo client / Echo Layer demo code of @tgalal just to answer things from my database. So, I know the end2end encryption stuff but it seems it did not made any difference.
What do you think?

**Comment by assegaf** [comment]
example your number is +154216616216 , there is a list of number 154216616201 until 154216616299 (except your number 154216616216) which most of it is used for spammer by others example or other type of abuse, or false programming example still using WA 1.5 protocol

so basically 154216616216 is marked by statistics of their server as Banned Number, even you do nothing. 

nothing you can do, not even develop next version of WA protocol, or using Official Apps, also banned.

**Comment by ftbarata** [comment]
Thanks! In my case, I've just find out that was not block. Instead, was this issue:
#1716  and  #1725

**Comment by jlguardi** [comment]
Probably to be included in the wiki but it isn't actually an issue and it is too many times reported.
