### ISSUE TITLE
Status : fail, reason :Old Version

### ISSUE THREAD

**Issue by Mantauwhite** [tgalal/yowsup#1738]
At this morning i have problem with yowsup version 2.5. Before is fine :

> yowsup-cli  v2.0.15
> yowsup      v2.5.0

I get this error when i debug :
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

i see [https://github.com/tgalal/yowsup/issues/1367](url) and [https://github.com/tgalal/yowsup/issues/1335](url) but still not working or down version.
any idea for this problem ?

**Comment by nurnabi** [comment]
I got the same issue. why it is happening?

[root@centos yowsup]# yowsup-cli registration --requestcode sms --phone xx01xxxxxxxxx --cc xx
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by Mantauwhite** [comment]
Issue just solve ( i get this [#1716](https://github.com/tgalal/yowsup/pull/1716/commits/42261bf5aaa09db195d02e363c8eb1c6070822ca) and [#1725](https://github.com/tgalal/yowsup/pull/1725/commits/70fbe97de5d97b1ebf41fc4153e46463cdb432fe)
but i have new problem :

> yowsup.layers.auth.autherror.AuthError: not-authorized

i try with different number and same number but still not working 

when i reregister, i received this messages :

> status: ok
kind: free
pw: (sensor)
price: Rp9500
price_expiration: 1475223673
currency: IDR
cost: 9500.00
login: (sensor)
type: existing
expiration: 4444444444.0

> status: ok
kind: free
pw: (sensor)
price: Rp9500
price_expiration: 1475223673
currency: IDR
cost: 9500.00
login: (sensor)
type: new
expiration: 4444444444.0

any idea for this problem ?

**Comment by neunmm** [comment]
Same here

**Comment by mcbeathcpg** [comment]
same to me

 I thing that whatsapp change minimum version and we need a new version of yowsup. I hope that the project continuing alive.

**Comment by jlguardi** [comment]
Please, see latest pull requests.

**Comment by mcbeathcpg** [comment]
works for me thanks

**Comment by fernandomxm** [comment]
I managed to solve this issue as follows:

/yowsup-master/yowsup/env/env_s40.py

Line:
_VERSION = "2.16.7" changed to _VERSION = "2.16.9"

After recompiled:
python setup.py install

**Comment by mcbeathcpg** [comment]
need change 

-    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1462212402694{phone}"
 +    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"

to

**Comment by Mantauwhite** [comment]
i try: 
Recompile python setup.py install  (with different folder. (yowsup1 and yowsup2) )
last recompile in yowsup2.

then change in env_s40.py (yowsup2):
_VERSION = "2.16.7" changed to _VERSION = "2.16.9"
#_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1462212402694{phone}"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"

but i have same error..

**Comment by Mantauwhite** [comment]
Problem solved,

i do this :

1. change update (see #1716 and #1725 )
2. Recompile.

thanks for your helping.
