### ISSUE TITLE
"status":"fail","reason":"old_version"

### ISSUE THREAD

**Issue by gilos7752** [tgalal/yowsup#1740]
I have been getting this error lately while executing the following line:

> ` yowsup-cli.py registration --requestcode sms --phone xxxx --cc xx --mcc xx`

now I've looked over older issues from march witch are the same as mine,
and all of them were fixed by updating the env file, witch is already updated in my project
exactly as written in the answers. for example: https://github.com/tgalal/yowsup/pull/1336

Does anyone have an idea  why would it happen?

**Comment by jlguardi** [comment]
Try to use the latest pull request.

**Comment by ragowthaman** [comment]
Did you try #1716 or #1725 In my case #1725 did the trick

**Comment by cimba007** [comment]
I just installed the PIP version and got the same version? What is the fastest way to update to current dev branch with this problem fixed?

**Comment by gilos7752** [comment]
Last pull request solved it, thanks a lot!!
