### ISSUE TITLE
Fail no_routes

### ISSUE THREAD

**Issue by chaitu210** [tgalal/yowsup#1741]
yowsup-cli registration --requestcode sms --phone 91xxxxxxx --cc 91
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":60,"voice_wait":60}

status: fail
retry_after: 3600
reason: no_routes

Even not working for env change using -E android

env_android.py

_MD5_CLASSES = "Tep7KQJ/l92sD+/4yXPIWQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.16.243"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

env_s40.py:

_VERSION = "2.16.9"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"

**Comment by jlguardi** [comment]
Your IP is banned or your phone number is a landline or virtualline (not-supported by wa).
