### ISSUE TITLE
How to create password for credentials?

### ISSUE THREAD

**Issue by johnduxx** [tgalal/yowsup#1742]
from yowsup.stacks import  YowStackBuilder
from layer import EchoLayer
from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env                                import YowsupEnv

credentials = ("phone", "password") # replace with your phone and password

which password is it? and how to generate it?

**Comment by ragowthaman** [comment]
First, you need to install yowsup-cli (comes with yowsup2) and use cli to register your phone number with WA 

`
yowsup-cli registration --cc 91 --phone <country code><phone no> --requestcode sms --mcc xxxx
`
this will register your phone number with WA and will send you a 6 digit code via sms to your phone. FOllow next step to get the loging and passwd
`
yowsup-cli registration --cc <country code> --phone <country code><phone no> --register <code you got via sms>  --mcc xxxx
`
