### ISSUE TITLE
Can my wa number get banned for this few reasons?

### ISSUE THREAD

**Issue by Domeax** [tgalal/yowsup#1743]
Is there a risk to get blocked when too many people are using my bot day for day?
~Around 300 people

Can i send a message to my number, if somebody is using my bot?
~Bot is sending every message twice. (Too many messages = Block?)

And is there a risk if too many people are chatting with my bot while not having the bots number in their contact list?
~Because i only read about blocked numbers, because the bot was the first, who sent a message. But in my case the other users would be the first.

**Comment by schoerg** [comment]
How can people chat with your bot if they don't have the number saved? (Excluding groups)

**Comment by jlguardi** [comment]
As pointed @schoerg, the third option could not be the cause.
Probably the second one if no pause is set.
About the first one, it is an small number of people and I haven't problems with that.
Probably your application is not emulating correctly human interaction. Add some disconnections and wait times.
