### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by Dudelsack08** [tgalal/yowsup#1744]
Hi Guys, can anybody help me?

i tried to send a message with the following command
`sudo yowsup-cli demos -d -s NUMBER"hello" -l NUMBER:'PASSWORD=' --debug`
and get an
`Authentication Error: not-authorized`

I also tried it with a config-file. If i tried to LOGIN (/L) i also get the Authentication Error :-(

by the way: Why it switch to S40 ? I put `DEFAULT = "android"` in the env.py.

Here the Debug log:
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0xb62a8a90>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0xb62a86d0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="xxxx" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
?▒v b▒)▒Al÷
'▒▒▒▒6▒
HEX:3xxx
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒▒▒
   Q㡕▒▒▒d4>▒▒`▒▒Sa▒ǲz▒▒▒pرt▒6▒p▒M▒n▒▒▒▒▒>▒"▒i@B▒▒q▒ms
HEX:8xxx
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by drschlaumeier** [comment]
I have same problem.
Its since Whatsapp chnaged the legal terms (to connect contacts to facebook).
What I need to do?

**Comment by drschlaumeier** [comment]
Found solution in last pull request:

In case authentication error or old version we need to update version in
/usr/local/lib/python2.7/dist-packages/yowsup/env/env_s40.py
last version is now 2.16.9

**Comment by Dudelsack08** [comment]
i tried it with another Mobil-Number. 
Same error :-(

**Comment by albert-chin** [comment]
> Dudelsack08 commented 10 hours ago
i tried it with another Mobil-Number. 
Same error :-(

Compare and contrast with #1747

**Comment by jlguardi** [comment]
You can't use android env due to wa2.0 which has no implementation on yowsup. Use s40 env instead.
Check your version number and token update and if it is correctly installed.
