### ISSUE TITLE
IP Blocked

### ISSUE THREAD

**Issue by gilos7752** [tgalal/yowsup#1748]
Recently I've been getting errors while activating numbers, when requesting code and registering.
(.."number blocked").
So I'm suspecting my IP has been blacklisted or something like that..

* I've never spammed, never send bulk messages to multiple users at once and so..

Does anybody familiar with this kind of situation?

**Comment by vikasprogrammer** [comment]
I believe WhatsApp recently changed their version number and if you keep pining their servers with old version, they will block you.

**Comment by albert-chin** [comment]
> vikasprogrammer commented 22 hours ago
I believe WhatsApp recently changed their version number and if you keep pining their servers with old version, they will block you.

Not really that they changed their version number ...
The story is that (all ?) those official clients (say for Android, iOS, and etc.) all are time-limited, in the sense that:
1. older version, after a certain time (on android it is usually 4 months), CANNOT be used to register
    (a new user account).
2. even if already registered, one CANNOT use an older version forever, after a certain time
    (seems to be the same time-limit as noted above for android)
   it must be updated (that is, replaced with a new version one)

The above seems to be the observed pattern for the official client app (apk in the android case).

Now, these (un-official) api (or library) functions by imitating to be certain (phone) client,
and indeed, the version number is hard-coded in certain of the source files,
therefore, one must have to update its api source files accordingly.

**Comment by jlguardi** [comment]
You can get:
 - Banned: your number is blocked by wa. Wait for 70 days or email them.
 - no_routes: your IP or a rank of phone numbers are banned for a while (24h?)

Recommendations:
 - Be sure that your code is up to date (so version number will be correct)
 - Wait for wait_time (sms_wait, voice_wait, retry_after) returned on each register
 - Don't register too many numbers is a short period. While testing, I'm getting 'no_routes' if I try to register more than 2 lines in an hour.
