### ISSUE TITLE
IOS not receiving messages

### ISSUE THREAD

**Issue by jonatascalebe** [tgalal/yowsup#1749]
Hi.
I´m using yowsup in last version, and working fine sending messages for ANDRIOD devices.

But IOS devices are not receiving the messages, even yousup showing Yowsdown after sending a message.

Any help, or test to do ?

Thanks a lot.

**Comment by Mantauwhite** [comment]
between ios or android, any something different code ?

**Comment by jonatascalebe** [comment]
No. I just change de destination phone number, the android receives but ios dont receive.

**Comment by jlguardi** [comment]
Try with other IOs devices (to discard an encryption issue due to missing keys) and report debug logs.

**Comment by felipe010203** [comment]
Tengo el mismo problema en los dispositivos IOS no recibe los mensajes y en Android llegar correctamente. Hice la depuración y no tengo ningún error todo parece funcionar correctamente, pero el mensaje nunca llega a mi teléfono celular. Cualquier ayuda por favor
