### ISSUE TITLE
WhatsApp group messager dosen't work anymore

### ISSUE THREAD

**Issue by ffwraspi** [tgalal/yowsup#1750]
Hello guy's
I have a further problem regarding sending whats-app messanges with my raspberry pi.
Since a few days i don't receive whatsapp messanges anymore.
I have tried it today again (31.08.2016)
But there's the same failure again.

If I want to login to the Yowsup Cli client with the command 
yowsup-cli demos --yowsup --config config 
the Yowsup Cli client opens himself

The next step ist to login/connect
/login 49163XXXXXXXXXXX XXXXXXXXXXXXXXXXXX=
          (mobile phone number) (whatsapp registration)

After that normaly everything works

But now I get this failure message:

general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

Has anybody an idea what's wrong?

In Germany was an whatsapp-update a few days ago.
Maybe thats the mistake

Thanks a lot for your help and suggestions in advance

**Comment by jlguardi** [comment]
Update to the latest code.

Probably banned or incorrect version/token.

Please, Report logs if persists.
