### ISSUE TITLE
On about env

### ISSUE THREAD

**Issue by albert-chin** [tgalal/yowsup#1752]
According to @jlguardi, as mentioned in the [comment](https://github.com/tgalal/yowsup/issues/1744#issuecomment-243999379) to "Authentication Error: not-authorized" #1744 on 2016-09-01 :

> You can't use android env due to wa2.0 which has no implementation on yowsup. Use s40 env instead.
> Check your version number and token update and if it is correctly installed.

So now, only the s40 env can be used.

Is it that those s40 clients are still using the older (wa1.6(?) protocol) ?
By the way, support for those s40 phones seem to be going to be ended by end of this year (2016).

It seems that all those remaining supported phone OS would be with wa2.0 protocol.
Is it correct ?

Is there any hope to enhance the android env to adapt to wa2.0, say as what @poma did as he mentioned in #1723 ?

Is those he listed:

> authkey=0rf7ujBvFqs7n7FQo8hRxRqwmm8OmN8IigiARfv9Dzs
> e_regid=fVnwhw
> e_keytype=BQ
> e_ident=WOnnHZj_OLdfEnYqltF5-25Vj5OrelEjQNfDSwctTSo
> e_skey_id=AAAA
> e_skey_val=gs0eittTzGMUFRvUmVY-bvBprin6B07DB04gXK3sol0
> e_skey_sig=9-1wWgXGcWoduuJcFcTiT42TVpO2BrKUAMyo3g_tGyCaVKBXafm0jfcglwTx5xW4sjZA_d0nIBmgzus6HpVCjg

something related to the "noise-pipe" (at the transport layer) or the Axolotl/Signal (at still higher layer) ?

It seems that SSL/TLS may be (relatively!) easier for a mitm (man-in-the-middle).
With the full wa2.0 protocol, including noise-pipe, and signal end-to-end, and etc., is what @poma did as mentioned in [comment](https://github.com/tgalal/yowsup/issues/1723#issuecomment-241048761) in #1723 :

> I use MissVenom modified for full mitm (both http and xmpp). It worked while app was sending pass in http, but now I don't know how to connect to xmpp without password. I run WhatsApp on an emulator with fake SSL cert authority installed.

can bring one to know all the new variables introduced ? And about the whole process ?

In particular, the noise-pipe is with authenticated-encryption and etc. to counter for mitm

Would it be with hope to do something like running an (official) apk on the android side of [maru os](https://guthub.com/maruos/maruos/) and
at the same time running wireshark and something like [wireshark-whatsapp](https://github.com/davidgfnet/wireshark-whatsapp) on the linux side ?
(So that all the (stored) user secret(-keys) of the apk may be accessible to the dissector-plugin,
 so that all the bytes on the wire can be reviewed)

Is there any hope to have a good dissector-plugin for wireshark like [wireshark-whatsapp](https://github.com/davidgfnet/wireshark-whatsapp) from @davidgfnet
updated with capability for "noise-pipe", say using the above setup ?

However, now the [maru os](https://github.com/maruos/maruos/) only support nexus 5,
is there any hope to have it extend to other arm-phone, or even on x86, say with [android-x86](http://www.android-x86.org/) ?

Or, is there other easier to use platform setup for doing the analysis, so as to have enough information for implementing an enhanced version of yowsup ?

**Comment by biji** [comment]
> By the way, support for those s40 phones seem to be going to be ended by end of this year (2016).

Where is this mentioned?

**Comment by albert-chin** [comment]
> biji commented 2 hours ago
By the way, support for those s40 phones seem to be going to be ended by end of this year (2016).
Where is this mentioned?

see for example [WhatsApp Blog](https://blog.whatsapp.com/10000617/WhatsApp-support-for-mobile-devices)

**Comment by assegaf** [comment]
forget all thoose thing v16 v20 all the same, the only different is between official apps and unofficial api, is official apps sendFieldStats something like statistic after reg and after something else,
the prove on debug RX TX.

based on this, I think they bann number randomly for user that dont send stats .. , 
ehmm they prepare sendFieldStats version 2 after read this
