### ISSUE TITLE
How to check if a user is online ? 

### ISSUE THREAD

**Issue by abstatic** [tgalal/yowsup#1756]
How can I check if a user is online or not ? I only want to know if the user is online or not ?

**Comment by Dargmuesli** [comment]
With the **cli** you can subscribe to "*presence updates*" of a contact easily.

`/presence subscribe <contact>`

Look at the source if you want to include it in a personal project, as I currently don't have a piece of code for that.

**Comment by abstatic** [comment]
I am able to subscribe to "presence" of a contact. But in reply I am getting this data - 

[connected]:Iq:
ID: 16
Type: result
from: 918518097289@s.whatsapp.net

How can I know, if the contact is online or offline ?

**Comment by Dargmuesli** [comment]
Mate, it would be nice if you gave us some more information. What do you mean by "*I am getting this data*" for instance? What is the code you are currently using?

Anyway, looking at [this source file](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_presence/protocolentities/presence.py#L3) I suppose that `Type: result` is not always returned but swapped with `Type: unavailable` or something similar.

**Comment by Dargmuesli** [comment]
Was my suggestion the hint that led you to your goal? I'd love to hear your solution/some feedback :)

**Comment by abstatic** [comment]
yes!, Thank you for time and help!!

**Comment by YuvalPruss** [comment]
I am having the same issue, can you explain what was the solution?
