### ISSUE TITLE
What happens when whatsapp stops support for Nokia S40 client?

### ISSUE THREAD

**Issue by gullyy** [tgalal/yowsup#1757]
Hi,
According to whatsapp they are not going to support Nokia S40 after few more months.What happens then?
https://blog.whatsapp.com/10000617/WhatsApp-support-for-mobile-devices

**Comment by assegaf** [comment]
end2end encryption all, wa 20 protocol all, it seem other access that dont do that banned at login

**Comment by gullyy** [comment]
@assegaf sorry I couldn't make anything out of the previous sentence
