### ISSUE TITLE
Problem at the end of 2016

### ISSUE THREAD

**Issue by rroqueCoddera** [tgalal/yowsup#1760]
I send a message to WhatsApp, and a received that answer:

```
Hi,

Thanks for your message.

As we announced in our blog, WhatsApp will no longer be supported on Nokia S40 by the end of 2016. As such, we no longer offer customer support for inquiries related to Nokia S40 phones.

Please refer to our FAQ articles for an answer to your query: https://www.whatsapp.com/faq/en/s40
```

could it be a problem?

**Comment by mgp25** [comment]
Contamination is a problem, this not.

It won't be a problem, but we are considering wether to release or not the code.

Regards

**Comment by schoerg** [comment]
There is also the Android env which you can use.

**Comment by cmeerw** [comment]
@mgp25 it would, of course, be good to know what you end up doing... if you decide not to release the new code, I'll have to concentrate on reverse engineering the WA20 protocol myself (which I would like to avoid), otherwise I could work on something more useful instead...
