### ISSUE TITLE
Sending document

### ISSUE THREAD

**Issue by gilos7752** [tgalal/yowsup#1761]
Hi,
is there any way to send document via yowsup?

Thanks!

**Comment by Dargmuesli** [comment]
Currently there isn't. Only image, audio, video, vcards, and locations are (partly) supported.

**Comment by Dargmuesli** [comment]
Please have a look at @jlguardi's Fork of this project. [The Wiki says](https://github.com/jlguardi/yowsup/wiki) that Documents are supported there.

**Comment by gilos7752** [comment]
thanks!
