### ISSUE TITLE
Unable to connect https when upload imagefile [Errno 10060]

### ISSUE THREAD

**Issue by spkmn** [tgalal/yowsup#1764]
I was trying to send image via command yowsup-cli.
But it seems that there is an issue when you're behind firewall.
I have setup the http_proxy, as in the log, it's logged that it's using http_proxy.

I have try use the network that doesnt have firewall, and it works.
But what i need now is, i can send picture behind firewall/using https_proxy.

Can somebody help?

DEBUG:yowsup.env.env:registered env android => <class 'yowsup.env.env_android.AndroidYowsupEnv'>
DEBUG:yowsup.env.env:registered env s40 => <class 'yowsup.env.env_s40.S40YowsupEnv'>
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.layers.network.layer:HttpProxy initialize: ('xxx.xxx.xxx.xxx', 8080)
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer - call Layer - Authentication Layer - Messages Layer - Receipt
 Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:HttpProxy connect: e1.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:HttpProxy handle connect
DEBUG:yowsup.layers.network.layer:HttpProxy connected
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="62895354565267" mechanism="WAUTH-2">
│â▲⌂| ƒþ┘´ºìbM¸îãÞñûW¶ÕT®¶╠ à¨::↕▀ 6htÅá╣¡Ñî>ìIæ4[²k*─ý┌ßb
HEX:e902e72343b1417276a9b7957b4df78cc6e8a49657f4e554a914ccff85f93a3a12df203668748fa0b9ada58c3e8d4991345bfd6b2ac4ecdae1620db3831e7f7c009fe7d9efa78d62
</auth>

DEBUG:yowsup.layers.network.layer:HttpProxy handle read: HTTP/1.1 200 Connection established

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
┤ï§╝ç☼e▲ºè├­~°
E `¤f
HEX:b48b15bc870f651ea78ac3f07ef80a450060cf66
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
'._Ô£·V=gZ█H♦↓▬◄→®}1¡ sõRàíí¼Û↑³↨ÀÌ_î▒♠ì}¼s■Ù§░l┤¥╩/%âaµ[Q+ä↑↓@☻i◄
HEX:272e5f9608e29cfa563d675adb48041916111aa97d31ad2073e45285a1a1acea18fc17b7de5f8cb1068d7dac73fe1d2e08ebf5b06cb4beca2f07258361e65b512b84181940026911
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1473406667" expiration="4444444444" props="6" t="1473842631">
♂Aµw¨bÂ╔_▄☺<Î YòvÈÎ[
HEX:0b41e677f962b6c95fdc013cd7ff599576d4d75b
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.

 xxxxxxxxxxx

 ip.png

 image
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
<media type="image" hash="Ha2ZKSdKTQk048btEFHEeYKuDop0HQ3tSoszjmtBsYU=" size="30314">
</media>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1473842631" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="1">
<media url="https://mmi500.whatsapp.net/u/_KpTwoM36RMRmjcGINzc5hacHWoABTxzuoi8RA/AnSxWvcqz2v0bAuO3vxEz-ZSs7X8UwT7gqXninLmLYr1" ip="169.55.74.60">
</media>
</iq>

ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer [Errno 10060] A connection attempt failed because the connected party did not properly resp
r established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "E:\work\whatsaap\yowsup-master-2.5\yowsup-master\yowsup\layers\protocol_media\mediauploader.py", line 53, in run
    self.sock.connect((self.url, 443))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because
 respond
ERROR:test:Upload file ip.png to https://mmi500.whatsapp.net/u/_KpTwoM36RMRmjcGINzc5hacHWoABTxzuoi8RA/AnSxWvcqz2v0bAuO3vxEz-ZSs7X8UwT7gqXninLmLYr1 for 6281908058535@s
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="2">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="62895354565267@s.whatsapp.net" id="2" t="1473842681">
</iq>

Yowsdown

**Comment by jlguardi** [comment]
Registration process and upload/download media didn't work with proxies as far as I remember. At least, all my contributions didn't have in mind this feature. However, xmpp protocol works within a socket with this support. I guess that adapt missing parts could be easy.

**Comment by spkmn** [comment]
Ah....i guess it's answered now..
Thank you @jlguardi...i will try to check them..
