### ISSUE TITLE
"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by tairogriz** [tgalal/yowsup#1765]
I've installed yowsup, but i can't register, becouse i get the following message:
"INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version"

https://github.com/tgalal/yowsup/pull/1716/files This changes are already made.

**Comment by jlguardi** [comment]
You can use:
 -Android env with version 2.16.254 and MD5: 2HyVgxdR3JbO1vCuJBrSQQ==
 - S40 env with version 2.16.10 and token PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1472664005031

**Comment by tairogriz** [comment]
Works fine! 👍  thx
