### ISSUE TITLE
Error:  INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by marchezetti** [tgalal/yowsup#1767]
root@hq-tgl-zab-01:/usr/local/etc# yowsup-cli registration -r sms -c /usr/local/etc/whatsapp.conf
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

---

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Authentication Error: not-authorized

**Comment by jlguardi** [comment]
With out the debug log (-d) we can't see which version is used. However, see the latest PRS where you can find the updated version token/number.

**Comment by marchezetti** [comment]
This is the answer where used -d.

root@hq-tgl-zab-01:/usr/local/etc# yowsup-cli registration -r sms -c /usr/local/etc/whatsapp.conf -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=119******&id=%FC%B0Vtu%ACI%07%AB%3C%87%89u%5C%D1%7E+%F7%B5%E4&lg=en&lc=GB&token=48f4bb323be993f122787f71f5c19f0f&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=23311&extexist=1&extstate=1
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=55&in=119******&id=%FC%B0Vtu%ACI%07%AB%3C%87%89u%5C%D1%7E+%F7%B5%E4&lg=en&lc=GB&token=48f4bb323be993f122787f71f5c19f0f&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=23311&extexist=1&extstate=1
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=119******&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7149&rchash=b1d5e457a80e78764e5ff1ac237184ff680016974db476ea0dbd77732808860b&anhash=%E2Jow%13x%E8z6e%A0I%DDc%BA%14%F6%96%0B%F8&extexist=1&extstate=1&token=48f4bb323be993f122787f71f5c19f0f&id=%DCg%05%2F%3El%F7%2A%A2g%94%91c%F2%8D%8Ft%F7.%80
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=119******&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7149&rchash=b1d5e457a80e78764e5ff1ac237184ff680016974db476ea0dbd77732808860b&anhash=%E2Jow%13x%E8z6e%A0I%DDc%BA%14%F6%96%0B%F8&extexist=1&extstate=1&token=48f4bb323be993f122787f71f5c19f0f&id=%DCg%05%2F%3El%F7%2A%A2g%94%91c%F2%8D%8Ft%F7.%80
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
You are using an outdated master. Update it and try again.

**Comment by marchezetti** [comment]
I user the command "pip install yowsup2 --upgrade"


Requirement already up-to-date: yowsup2 in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from yowsup2)
Downloading/unpacking argparse from https://pypi.python.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl#md5=c37216a954c8669054e2b2c54853dd49 (from yowsup2)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Requirement already up-to-date: python-axolotl>=0.1.35 in /usr/local/lib/python2.7/dist-packages (from yowsup2)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from yowsup2)
Requirement already up-to-date: pycrypto in /usr/local/lib/python2.7/dist-packages (from python-axolotl>=0.1.35->yowsup2)
Requirement already up-to-date: python-axolotl-curve25519 in /usr/local/lib/python2.7/dist-packages (from python-axolotl>=0.1.35->yowsup2)
Requirement already up-to-date: protobuf>=3.0.0.b2 in /usr/local/lib/python2.7/dist-packages (from python-axolotl>=0.1.35->yowsup2)
Installing collected packages: argparse
  Found existing installation: argparse 1.2.1
    Not uninstalling argparse at /usr/lib/python2.7, owned by OS
Successfully installed argparse
Cleaning up...
root@hq-tgl-zab-01:/usr/local/etc# yowsup-cli registration -r sms -c /usr/local/etc/whatsapp.conf -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=11975822087&id=%FC%B0Vtu%ACI%07%AB%3C%87%89u%5C%D1%7E+%F7%B5%E4&lg=en&lc=GB&token=48f4bb323be993f122787f71f5c19f0f&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=25212&extexist=1&extstate=1
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=55&in=11975822087&id=%FC%B0Vtu%ACI%07%AB%3C%87%89u%5C%D1%7E+%F7%B5%E4&lg=en&lc=GB&token=48f4bb323be993f122787f71f5c19f0f&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=25212&extexist=1&extstate=1
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=11975822087&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6748&rchash=b19d5e77da9fc4a4ccaa6a1be231aef9952be7ca833c2c13e3da8dcc2fdcc0dd&anhash=M%A2%D7%EF%F5j%F5%2Ff%AE%F1%A8%B17v%BF%DF%F5%D1%01&extexist=1&extstate=1&token=48f4bb323be993f122787f71f5c19f0f&id=%F7%F4%3C%7Cy%FEF%F8c%3B%A5G%26%D3%BA%0D%0DQ%CD%15
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=11975822087&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6748&rchash=b19d5e77da9fc4a4ccaa6a1be231aef9952be7ca833c2c13e3da8dcc2fdcc0dd&anhash=M%A2%D7%EF%F5j%F5%2Ff%AE%F1%A8%B17v%BF%DF%F5%D1%01&extexist=1&extstate=1&token=48f4bb323be993f122787f71f5c19f0f&id=%F7%F4%3C%7Cy%FEF%F8c%3B%A5G%26%D3%BA%0D%0DQ%CD%15
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
Probably not updated for pip installation. Use github code instead.

**Comment by marchezetti** [comment]
Do you have the how to?

**Comment by jimisan** [comment]
I have the same problem.  maybe problem in the token.

**Comment by gangsthub** [comment]
Same problem here.
- Using the last version. Installed all packages...
- Using Windows (10).

This is my _output_:

```
yowsup-cli  v2.0.15                                                                                                                               
yowsup      v2.5.0                                                                                                                                
                                                                                                                                                  
Copyright (c) 2012-2016 Tarek Galal                                                                                                               
http://www.openwhatsapp.org                                                                                                                       
                                                                                                                                                  
This software is provided free of charge. Copying and redistribution is                                                                           
encouraged.                                                                                                                                       
                                                                                                                                                  
If you appreciate this software and you would like to support future                                                                              
development please consider donating:                                                                                                             
http://openwhatsapp.org/yowsup/donate                                                                                                             
                                                                                                                                                  
                                                                                                                                                  
DEBUG:yowsup.env.env:Env not set, setting it to s40                                                                                               
DEBUG:yowsup.env.env:Current env changed to s40                                                                                                   
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}                     
DEBUG:yowsup.common.http.warequest:cc=34&in=687636237&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=SMS&mistyped=6&network_radio_type
=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1546&rchash=ed4bd98b99089249623d80d99e84b1fab555763ba42d09c0428f04e895209d22&anhash=%E1%06%B8%BC
%19%CA%15%A2%98%22%3C6%E8ON%C9%29%8A%0EB&extexist=1&extstate=1&token=d5bc2bdc26ded207dc7b92324046413f&id=%2B%B3mG%A8%3AI%E5%117%C2O%DF%AF%DC%23%0F
%E7%0D%C9                                                                                                                                         
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net                                                                           
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=34&in=687636237&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=S
MS&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1546&rchash=ed4bd98b99089249623d80d99e84b1fab555763ba42d09c0428f
04e895209d22&anhash=%E1%06%B8%BC%19%CA%15%A2%98%22%3C6%E8ON%C9%29%8A%0EB&extexist=1&extstate=1&token=d5bc2bdc26ded207dc7b92324046413f&id=%2B%B3mG%
A8%3AI%E5%117%C2O%DF%AF%DC%23%0F%E7%0D%C9                                                                                                         
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}                                                                        
                                                                                                                                                  
status: fail                                                                                                                                      
reason: old_version
```

**Comment by shpotes** [comment]
Same problem 

```
$ yowsup-cli registration --requestcode voice --phone 1XXXXXXXX --cc 1 -d 

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=1&in=9093755959&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=voice&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5140&rchash=131b88e12a28b1d45105e6bbf3ae7372419e246f625cae05d23b700973d77d11&anhash=z%01a%A3%88%29c%E6%90n%1C%D4%AA%EB%7Ey%AF%D7%0Bf&extexist=1&extstate=1&token=BffcxdbZ%2BDtFSaLtQ4sJCuGycvU%3D&id=%03%C2%07%7C%FB%40%92%F2o%B9%00%B4%FA%2A%A3%7B%93%02D%91
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=1&in=9093755959&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=voice&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5140&rchash=131b88e12a28b1d45105e6bbf3ae7372419e246f625cae05d23b700973d77d11&anhash=z%01a%A3%88%29c%E6%90n%1C%D4%AA%EB%7Ey%AF%D7%0Bf&extexist=1&extstate=1&token=BffcxdbZ%2BDtFSaLtQ4sJCuGycvU%3D&id=%03%C2%07%7C%FB%40%92%F2o%B9%00%B4%FA%2A%A3%7B%93%02D%91
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
```

**Comment by Hasan084** [comment]
i have same problem

yowsup-cli registration --requestcode sms --phone 6285xxxxxxxxx --cc 62 --mcc 510 --mnc 01
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"6285xxxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 6285xxxxxxxxx


i want upgrade env s40 to 2.16.11 but i confusion how to upgrade step by step because i'm a beginer.

please help me to solving problem

**Comment by tgalal** [comment]
fixed

**Comment by dkiran** [comment]
Dear tgalal, am trying this since 5 days, no use, 
root@precise64:/home/vagrant/yowsup-2.5.0/yowsup# yowsup-cli registration --requestcode sms --phone 914XXXXXXX --cc 91 --mc 404 --mnc 45
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"914XXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 914XXXXXXX
root@precise64:/home/vagrant/yowsup-2.5.0/yowsup#

Help me.

**Comment by gangsthub** [comment]
It's been almost a year. I don't think this project is still mantained 😞

**Comment by dkiran** [comment]
Thanks, after long struggle.i got it. but how to run sending messages at scheduled time intervals and remaining time receiving message in a single program. any idea,

**Comment by ravesingh1983** [comment]
Hi @dkiran  can you let me know how you resolved the issue. I am struggling to send a message.

**Comment by Hasan084** [comment]
first change env_s40.py in lates version
and than try again registration yowsup-cli

**Comment by ravesingh1983** [comment]
@Hasan084  I tried doing that  but then i started getting bad token error See the env_s40.py which i have. I am not sure how to generate new token. If you know let me know

from .env import YowsupEnv
import hashlib
class S40YowsupEnv(YowsupEnv):
    **_VERSION = "2.17.188"**
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    **_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452æphoneå"**
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
        return self.__class__._DEVICE_NAME

    def getManufacturer(self):
        return self.__class__._MANUFACTURER

    def isAxolotlEnabled(self):
        return self.__class__._AXOLOTL

    def getToken(self, phoneNumber):
        return hashlib.md5(self.__class__._TOKEN_STRING.format(phone = phoneNumber).encode()).hexdigest()

    def getUserAgent(self):
        return self.__class__._USERAGENT_STRING.format(
            WHATSAPP_VERSION = self.getVersion(),
            OS_NAME = self.getOSName() + "Version",
            OS_VERSION = self.getOSVersion(),
            DEVICE_NAME = self.getDeviceName(),
            MANUFACTURER = self.getManufacturer()
        )

**Comment by Hasan084** [comment]
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

I think the token is version 2.16.11
not version 2.17.188

**Comment by ravesingh1983** [comment]
Yes correct but issue is token for 2.17.188 i am not able to generate and not able to find anywhere. No proper document how to generate the new token for newer versions.

BTW when i use 2.16.11 as version i get old version error. 

If you know how to generate the token let me know or if you have any other token which works let mw know. I tried using ChatAPI(https://github.com/mgp25/Chat-API) to generate the token but there also its looking for release time. I am not sure where to get it from.

I am struggling for past 1 week on this.

**Comment by Hasan084** [comment]
I use token version 2.16.11 until now still can work for my project.
I use sudo nano to generate it.
please check back your token, 
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452æphoneå" 
should 
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

**Comment by ravesingh1983** [comment]
Kool let me try this then. Happy to hear this is still working will try out.

**Comment by dkiran** [comment]
@ravesingh1983, i used command with -E android, changed version to
 _VERSION = "2.12.556"
deleted every thing, git cloned again. and just worked with commands registration with "-E android" 

yowsup-cli registration --requestcode sms --phone 91xxxxxxxxxx --cc 91 --mc 404 --mnc 45 -d -E android

**Comment by ravesingh1983** [comment]
@dkiran yes with andriod it works for me some part, means i able to request code and then using the code which i get i am able to register. But sending sms fails with the following error in bold.

Then i was reading some thread and some one suggested to switch to s40 so I went to s40

BTW ... Are you able to **send message** using andriod env ??

Or let me know the command you are using to send the message that is really helpful 


yowsup-cli demos -l 91XXXXXXXXX:XVVa/243edDiZUyWnXe8GH46oBE= -E android -s 91XXXXXXX "Hello" --debug
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli v2.0.15
yowsup v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x10548ebe0>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x103575320>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:

�
6Þ�Ûö¶ ªgëû¢�è_A
HEX3:b'920c36de9cdbf6b620aa67ebfba29201e8195f41'
DEBUG:yowsup.layers.logger.layer:tx:

av�]^¸Á�9��çîO,ô »d��ù�Sà��ÄR�
¼m¦Ì�ôäsMn°ÜÃ¹C­mCÙø|�,6|�úL%yÀzÛpèYr·¤�íà´
HEX3:b'156176945d065eb8c100118913399c9404e7eeb719084f112cf4a0bb648983f98553e0939bc452960cbc6da6cc8cf4e4734d6eb0dcc3b94301ad6d43d904f87c822c1c367c8dfa4c2579c07adb70e85972b7a49c18ede0b4'
**DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed**

**Comment by ravesingh1983** [comment]
@dkiran was i clear ??

**Comment by ravesingh1983** [comment]
@Hasan084 this 
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

still giving me the same old version error. Can you please attach your env_s40.py. I will compare it

**Comment by Hasan084** [comment]
okay, tonight I send it because its file is at home

**Comment by ravesingh1983** [comment]
O.k Sure @Hasan084. Again Thanks for helping me.

**Comment by Hasan084** [comment]
[env_s40.zip](https://github.com/tgalal/yowsup/files/1337413/env_s40.zip)

**Comment by ravesingh1983** [comment]
Thanks will try and tell the result.

**Comment by ravesingh1983** [comment]
Thanks @Hasan084 it worked for me !!!
