### ISSUE TITLE
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"blocked" ...

### ISSUE THREAD

**Issue by AndersonFirmino** [tgalal/yowsup#1768]
I'm getting this info. After some tests. 

How i fix this?

My two numbers, remains blocked. How I do to recover?

```
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"blocked","login":"xxxxxxxxxxxxxxx"}\n'
status: b'fail'
reason: b'blocked'

```

**Comment by schoerg** [comment]
Buy a new number.

**Comment by rsajdok** [comment]
@AndersonFirmino I have the same problem. I have lost two phone numbers in two days. I sent a few messages. I think, it is not possible to use this framework.

**Comment by rodrigolopezguerra** [comment]
@AndersonFirmino you can right to whatsapp trying to explain why you where blocked , and why your number should be in that situation , you can do this only if it's your personal number. (For obvious reason , don't teel something like "hi guys i was trying yowsup..." ). If is just another number , follow @schoerg advice. @rsajdok this framwork work just ok. Regards!
