### ISSUE TITLE
non-authorised

### ISSUE THREAD

**Issue by arseniypetrikor** [tgalal/yowsup#1769]
I keep getting AuthError with 'non-authorised' reason.
I'm using last version of yowsup and 's40' env.
I tried to change env to 'android' and got 'old version'.
I saw some previous issues about it and all advice didn't help me.

```
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth mechanism="WAUTH-2" user="89221073838" passive="false">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
´¹=zèaö%¹ÜO¨mÛñÁ
HEX3:b'b4b93d7ae88661f625b990928ddc4fa86ddbf1c1'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
ó>°R´ø°ÚÞ>#%)ôÖ¥3
Îú'§ueÊ×Ä·´¸z±¾+Ö(\Øv©Æö»mBLâÚ;;
HEX3:b'f31d01913eb05280b414f898b0dade8c3e232529f4d6a5330acefa9b0827a7137591186580ca96d7c481b7b4b87a11b1be2bd6285cd88e76a9c6f6bb916d424ce2da193b3b'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized
```

I hope you'll give me new advice about this so I can use your library and cli.
Sorry for my bad english :sweat_smile:

**Comment by jlguardi** [comment]
Probably your number is banned.
Update android env file to get the same error (not-authorized) with this env.

You can check if your number is banned trying to register it again.

**Comment by arseniypetrikor** [comment]
When I tried to register again it told me that it's too recent to register

**Comment by arseniypetrikor** [comment]
And it was a first time I tried to login

**Comment by assegaf** [comment]
not banned, it just too old protocol for android env,

**Comment by rodrigolopezguerra** [comment]
As @jlguardi mention you could be ban. Even if its your first login , the IP could be ban and that lead to the phone number being banned. So check. If not @assegaf is probably right , and you need to put up to date your branch. Hope it helps!
