### ISSUE TITLE
Auth response error

### ISSUE THREAD

**Issue by hypertech** [tgalal/yowsup#1770]
Hi guys.

If anyone has same issue? I use S40 env and now start to get "Auth response error" with disconnection after first pooling. Seems like whatsapp change something in protocol or nobody else has same issue ?

**Comment by jlguardi** [comment]
Yes, it happened last Thursday if you were using protocol 1.5 (deprecated long time ago but still working). Update your code.

**Comment by hypertech** [comment]
Thanks, @jlguardi, i update today and all works fine again
