### ISSUE TITLE
Problem with the authorization by the android version

### ISSUE THREAD

**Issue by Bodasia** [tgalal/yowsup#1773]
when you use the version for Android is not possible to establish a connection,
updating constant to a new version without correcting the problem.

presently constants:
`_MD5_CLASSES = "14w/wF67XBf2vTc+qALwKQ=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

_VERSION = "2.16.148"`

error log:
`DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.common.http.httpproxy:none proxy
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fd073514a50>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fd073514350>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e11.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="14508590914" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
4Ґѓvсq€¦%ѓUu'~Тв%ъ
HEX:34a58376f17188a62583171b5575277ed2e225fa
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
bЇЗХћЗтеїM:Я©O FёDЄ#q µb’
cЯbєѕь^њ\РЇЂД."2юbV;ќЗ•Ђ‚‹‰NЩ_з‡К†8}XіgWC
HEX:62afc7d5119ec7f2e5bf1b4d3adfa94f1c0946b844aa237120b562920d63df62babefc5e9c5cd0af80c42e22063215fe1c1b621e563b9dc7139580828b894ed95fe787ca86381d7d58b3675743
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`

**Comment by sendytiaprayoga** [comment]
i have same issue

**Comment by myprak** [comment]
I have the same issue. When I use s40, it says 
print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'

I can use the number on a mobile phone to send and receive messages so it is not a blocked number issue.

**Comment by jlguardi** [comment]
@myprak you can't use yowsup and official app simultaneously. Probably you registered your number again in a mobile and then your password became invalid.
If you are changing from android to s40 env, in careful due to banning. And remember to remove nonce file.

**Comment by myprak** [comment]
@jlguardi I don't think that is the issues. My workflow was:
- Linux - Yowsup register sms
- Linux - Yowsup send SMS code
- Linux - receive Whatsapp password
- Linux - try echo client, send message demos
- Linux - Auth Error
-> I repeated the above for android, and the difference was that I got a Connection Closed instead of AuthError
-> I then suspected the number was banned somehow, even though it was a pristine new number,
 and then tried to register through my phone. No issues and able to send and receive messages from my phone
