### ISSUE TITLE
Installation for Python3

### ISSUE THREAD

**Issue by tomatensuppe** [tgalal/yowsup#1776]
Hi together,

im wondering how to install Yowsup for Python3 - if i'm running the 

> pip install yowsup2

command, i cannont run the echoclient with python3 (python3 run.py). The Message

  _File "run.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
ImportError: No module named 'yowsup'_

appear.

It seems i have to add manual path for yousup modules - ist that correct ? if so how can I do that ?

How can I install yousup for python3 ?

**Comment by jlguardi** [comment]
Install with: python3 pip install yowsup2
Or setup python3 as default python interpreter.

**Comment by tomatensuppe** [comment]
Thanks, but it does not help.

python3: can't open file 'pip': [Errno 2] No such file or directory

**Comment by Dargmuesli** [comment]
You either `pip install yowsup2` or `python3 setup.py install`.
You don't `python3 pip install yowsup2`.

**Comment by kafffee** [comment]
I tried python3 setup.py install:

It also returns python3: can't open file 'pip': [Errno 2] No such file or directory

what to do I'm desperate?
