### ISSUE TITLE
how to get the list of already synced contacts

### ISSUE THREAD

**Issue by gullyy** [tgalal/yowsup#1779]
how to get the list of already synced contacts?

**Comment by rodrigolopezguerra** [comment]
@tgalal is there a way for this ?

**Comment by mgp25** [comment]
You can't. You need to have a track of them locally, by saving contacts in a database for example

**Comment by dpz3579** [comment]
@mgp25
Do I need to resync my contacts that were synced earlier?

**Comment by hgc2002** [comment]
good question

**Comment by rodrigolopezguerra** [comment]
as far as i understand no need of doing that. Yes you have to keep track if you want to know them.
