### ISSUE TITLE
No SMS while registration

### ISSUE THREAD

**Issue by enteritm** [tgalal/yowsup#1788]
Hi there.

I can't receive an SMS while registration. But WA server says that SMS was sent. It was not only once, it's happening in 80% cases while registration new number. What problem it can be?

**Comment by Adeoy** [comment]
Check your country code (CC) and your phone number, or with another number. It may even be that WA servers are busy.

**Comment by rodrigolopezguerra** [comment]
@enteritm same issue here with some numbers. I advice you to try voice registration on that numbers.
