### ISSUE TITLE
Get group participant's username

### ISSUE THREAD

**Issue by rodrigopa** [tgalal/yowsup#1792]
Hi,

I'm using the _InfoGroupsIqProtocolEntity_ to get group info, but this don't returns the participant's nickname. How can I do that?

Sorry for bad english.

**Comment by jlguardi** [comment]
Use GetSyncIqProtocolEntity

**Comment by rodrigopa** [comment]
@jlguardi 

I received:

Iq:
ID: 2
Type: result
from: ****@s.whatsapp.net
Wait: 179287
Version: 1475767387515502
In Numbers: 
Out Numbers: ****@s.whatsapp.net,****@s.whatsapp.net,****@s.whatsapp.net
Invalid Numbers:

What is the next step?

**Comment by rodrigopa** [comment]
@jlguardi Is this possible?

**Comment by jlguardi** [comment]
You should use phone numbers in your local format ("phone") or "+ccphone" format. Otherwise you will get them always out.
Answer returns jids ("ccphone")
