### ISSUE TITLE
Keep getting blocked by WhatsApp

### ISSUE THREAD

**Issue by peletiah** [tgalal/yowsup#1793]
I've been doing a few tests sending messages from a yowsup-account to other WhatsApp-accounts I own. Several times now I've been blocked within a few hours or on the next day.

WhatsApp's support has unblocked me on request (Which took a few days), but they have not given a reason other that their software has marked me for violating the usage terms and therefore blocked my account, without further details specifying what I'm violating.

I'm not doing anything particular aggressive in these tests, just sending < 5 messages a time to a few accounts (I'm working on a notification-subscription service). Might it be a problem that I've not implemented any functionality to receive messages?

**Comment by peletiah** [comment]
Should have used the search - plenty of threads on the topic: https://github.com/tgalal/yowsup/issues/1686#issuecomment-232521465

**Comment by kalijassy** [comment]
How to save WhatsApp getting ban contact me on WhatsApp +917347261998
