### ISSUE TITLE
Cannot get status online 

### ISSUE THREAD

**Issue by ibensam** [tgalal/yowsup#1795]
hi , i try to  get status other person (online/offline)  using command /presence subscrib contact , but no response.
please help ...thanks 

[connected]:/presence subscribe 628xxxxxxxxxxxx
[connected]:

**Comment by markbosshard** [comment]
Hi
I have the same problem, when using yowsup-cli I do
1) /contacts sync 4176xxxxxxx
2) /presence available #to get online myself
3) /presence subscribe 4176xxxxxxx

However when 4176xxxxxxx goes online or offline no output appears at all! can anyone help? thanks.

**Comment by markbosshard** [comment]
I have solved the issue myself. It seems the current yowsup is not catching the event for going online/offline anywhere. You can catch this event yourself:

go for example to the file yowsup-master/yowsup/layers/interface/interface.py and add the following lines there, e.g. after 1 empty line at the bottom of the file:

@ProtocolEntityCallback("presence")
def onUserOnlineHoweverYouWannaNameThisone(self,entity):
            print "User has changed state: %s" % entity

You can do whatever you want with the entity element, I will check which number comes before the @s.whatsapp.net and then I will also check whether or not "unavailable" is in it (for some reason the "available" one is not written..) and save this stuff to a database.

**Comment by jlguardi** [comment]
Contact sync uses the phone ‎number in 'human' notation. I mean: +4176xxxxxxx‎ or 6xxXxxxxx.

Presence subscribe uses whatsapp jid as param. I mean: 4176xxxxxxx‎@s.whatsapp.net

Any way, post debug logs for more info.

**Comment by SorenJans** [comment]
@ markbosshard
Can you please upload your source files somewhere so I have a working example? I'm attempting to do something similar what you are doing. I want to execute some command whenever a certain number is online and maybe also if the number is offline again. But I don't understand the whole concept with the 3 different files (run.py and so on). Your help would really be appreciated. Thanks!

**Comment by randomite** [comment]
@SorenJans I am trying to do the same thing as you, have you come across a solution? Need to execute a certain command when a contact comes online and goes offline.

**Comment by markbosshard** [comment]
@SorenJans @randomite  sorry guys didn't see this thread, I will upload the source files after my exams this weekend! it works perfectly and only a few lines of code to change from the version here on github =)

**Comment by markbosshard** [comment]
Oh but I have just seen that I already in detail explained all changes that are needed to make to the files!
can you tell me more exactly what is not clear? you just need to do these changes in interface.py:


go for example to the file yowsup-master/yowsup/layers/interface/interface.py and add the following lines there, e.g. after 1 empty line at the bottom of the file:

@protocolentitycallback("presence")
def onUserOnlineHoweverYouWannaNameThisone(self,entity):
print "User has changed state: %s" % entity

You can do whatever you want with the entity element, I will check which number comes before the @s.whatsapp.net and then I will also check whether or not "unavailable" is in it (for some reason the "available" one is not written..) and save this stuff to a database.

**Comment by markbosshard** [comment]
note that I could work for you on upwork.com against payment and solve your specific issues.

**Comment by tgalal** [comment]
b957249
