### ISSUE TITLE
Error when extracting key use the yowsup-cli

### ISSUE THREAD

**Issue by alberttriadrian** [tgalal/yowsup#1797]
Example: 
    `yowsup-cli registration -C 55 -r sms -p 554899998888`

Response:
`INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version`

Why this is happening and how to solve this problem?

**Comment by jlguardi** [comment]
Check if you have installed the latest version or post debug logs (run with -d option) to chech which version are you running.

**Comment by schmerlo** [comment]
The Version and the token string has to updated again. Change it to
 _VERSION = "2.16.10"
  _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1472663857500{phone}"
in your env_s40.py that should work

--

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.10 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=49&in=XXXXXXXXXX&lc=GB&lg=en&sim_mcc=262&sim_mnc=007&mcc=262&mnc=007&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7766&rchash=616756a586b85131b3b9488f7f9f4d4a33166a3d4e2f9d4f6bcc3884e68819e4&anhash=%C8%1F%BA%5Ek2%E9%DE%C9%06YJ%24%7FP%E2%A3%FEM%CC&extexist=1&extstate=1&token=fe3e70c8967fd1b17541f25d2adefe40&id=%10_%24%A3+%F3%EBg%8A%81%97%5D%9CY%00N%E6%D0%12%92
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=49&in=XXXXXXXXXX&lc=GB&lg=en&sim_mcc=262&sim_mnc=007&mcc=262&mnc=007&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=7766&rchash=616756a586b85131b3b9488f7f9f4d4a33166a3d4e2f9d4f6bcc3884e68819e4&anhash=%C8%1F%BA%5Ek2%E9%DE%C9%06YJ%24%7FP%E2%A3%FEM%CC&extexist=1&extstate=1&token=fe3e70c8967fd1b17541f25d2adefe40&id=%10_%24%A3+%F3%EBg%8A%81%97%5D%9CY%00N%E6%D0%12%92
INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":65,"sms_wait":65,"voice_wait":65}

status: sent
retry_after: 65
length: 6
method: sms

**Comment by jlguardi** [comment]
I've just tested _VERSION = "2.16.9" and it is still working. So master code should work.
