### ISSUE TITLE
sending massge

### ISSUE THREAD

**Issue by nmo0ory** [tgalal/yowsup#1800]
hello,
i have hosting company
and i have +3000 number i want to send to them a massage 
can i do that with yowsup 
if is is there any one can help me ? and i will pay for him

**Comment by Adeoy** [comment]
lol... Yowsup can do it but, your number can be banned due to sending messages to numbers who doesn't have you in their contact list. It's risky but can be done. And the marketing isn't an option, its something annoying.

**Comment by nmo0ory** [comment]
so is there any website that can send it from different number ?

**Comment by Adeoy** [comment]
I don't know web pages that do that. And about your problem, you can make that mass message sending, but it is recommended that these +3000 numbers already know the intentions of the messages that you will send, and add a time delay on  each message that you send to avoid the minimum possible that WA detected the mass sending.

**Comment by nmo0ory** [comment]
can you help me on making that ?

**Comment by jlguardi** [comment]
A bulk messaging action will be banned by wa.
