### ISSUE TITLE
yowsup.layers.network.layer:Disconnected, reason: Connection Closed (old_version)

### ISSUE THREAD

**Issue by camarin24** [tgalal/yowsup#1804]
Hello, I have a big problem.
Whatsapp made an update and suddenly stopped working.

This is the error:
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="57XXXXXXX" mechanism="WAUTH-2">
�C��֡G����H0��_�!�5�����e��F���+����~t��"
HEX:a043939fd6a147f5fda9af48300830a8b55ffd21ee35bee8d61d81c765e9fa46a104bcee2bd5c3f0b47e748bcd22
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

Please help me.

**Comment by camarin24** [comment]
the error is the old version.
as I can edit the file env_android.py?
The new version of WP is 2.16.310

please, help me.
Srry, my inglish is bad.

**Comment by Vuelos** [comment]
Use this https://github.com/tgalal/yowsup/pull/1716/commits/42261bf5aaa09db195d02e363c8eb1c6070822ca

**Comment by camarin24** [comment]
@Vuelos ty bro.

**Comment by lucienn3** [comment]
I get the same message while im trying to get registered.

DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=49&in=1751561364&lc=GB&lg=en&sim_mcc=262&sim_mnc=006&mcc=262&mnc=006&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6080&rchash=ab876ccb97a4deaba0407b936d712b07a985471745484c9c1e2ea36fa664b163&anhash=%9C%F0h%0F%9B%FA%0D%22%90%DA%A7%27%04%B6%03%7Bu%0A%AD%0F&extexist=1&extstate=1&token=ROohLFcypVuTEDwKFymphJqrDQU%3D&id=%AD%5B%3Fn%0E%3FGC%5B%EE%CBS5GX%9F%3Ft%F5%8B
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=49&in=1751561364&lc=GB&lg=en&sim_mcc=262&sim_mnc=006&mcc=262&mnc=006&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6080&rchash=ab876ccb97a4deaba0407b936d712b07a985471745484c9c1e2ea36fa664b163&anhash=%9C%F0h%0F%9B%FA%0D%22%90%DA%A7%27%04%B6%03%7Bu%0A%AD%0F&extexist=1&extstate=1&token=ROohLFcypVuTEDwKFymphJqrDQU%3D&id=%AD%5B%3Fn%0E%3FGC%5B%EE%CBS5GX%9F%3Ft%F5%8B
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'

**Comment by jlguardi** [comment]
You can try with pull request #1716. However I guess that this version uses whatapp protocol 2.0. I'm not sure if it supports wa 1.6.

**Comment by lucienn3** [comment]
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=49&in=1751561364&lc=GB&lg=en&sim_mcc=262&sim_mnc=006&mcc=262&mnc=006&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8469&rchash=ec374acc322e13d12024e88d1a1d54fb433a005889ce419922cab230b929e728&anhash=%18%DF%7D%F3%A3_%1D_%60%3B%AB%DD%A6%2B%A5%7C%A8%C1%91%A3&extexist=1&extstate=1&token=33200eb6c4be49116a6a94ccd1f98f01&id=%F6%FDj%92%60O%AE%F7%83++%ECp%DE%1D%5D%2C%ED%0A%17
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=49&in=1751561364&lc=GB&lg=en&sim_mcc=262&sim_mnc=006&mcc=262&mnc=006&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8469&rchash=ec374acc322e13d12024e88d1a1d54fb433a005889ce419922cab230b929e728&anhash=%18%DF%7D%F3%A3_%1D_%60%3B%AB%DD%A6%2B%A5%7C%A8%C1%91%A3&extexist=1&extstate=1&token=33200eb6c4be49116a6a94ccd1f98f01&id=%F6%FDj%92%60O%AE%F7%83++%ECp%DE%1D%5D%2C%ED%0A%17
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'


same issue

**Comment by jlguardi** [comment]
Update with master code wich uses versión 2.16.9.

**Comment by lucienn3** [comment]
Ok now it works...
Now it says


INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":60,"voice_wait":60}\n'
status: b'fail'
reason: b'no_routes'
retry_after: 3600

**Comment by jlguardi** [comment]
Missing mnc and mcc, banned IP or banned wa version for this number.

**Comment by lucienn3** [comment]
Do you have skype?

**Comment by jlguardi** [comment]
No, you can contact me by mail (see my profile) or here.

**Comment by lucienn3** [comment]
You have an email :) Thank you

**Comment by lucienn3** [comment]
Sent you another one :X

**Comment by johnduxx** [comment]
Is it possible to support using android configuration?

**Comment by arielimlauer** [comment]
Hello! I have the problem that when trying login in yowsup it shows error:

C: \ xampp \ yowsup-master> python yowsup-cli demos --yowsup --config details.txt
Yowsup Cli client
==================
Type / help for available commands

[Offline]: / L
General: Disconnected: Connection Closed

Any ideas? What could be the problem?
I'm with windows 7 32-bit, python 2.7, yowsup downloaded from here https://github.com/tgalal/yowsup.

I hope you can help me, thank you very much to the community

**Comment by fjrmaulana** [comment]
please sir.. 
i have error like this
D:\yowsup>python yowsup-cli demos --yowsup --config whatsapp_config.txt -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

any solution we'll appreciated
