### ISSUE TITLE
Banned Numbers all the time

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#1806]
Our numbers are getting banned all time time. using yowsup. This is NOT due to spam! Whatsapp recognizes yowsup as an unauthorized application. At this point, we cannot use yowsup anymore without getting banned sooner or later. How can we solve this?

Whatsapp worte:

Thanks for your message. 
Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application  and/or unsupported device. 
Please uninstall your application and install an authorized version on supported devices from:
www.whatsapp.com/download
Please note that we do not allow use of unofficial clients or jailbroken/rooted (including emulators), and unsupported devices.
To use WhatsApp on your computer, access our website from your computer’s browser. Then, open the app and scan the QR code using the WhatsApp app on your phone (look for WhatsApp Web menu under Settings). WhatsApp can only be installed on your computer if your operating system is Windows 8 (or newer) or Mac OSX 10.9 (or newer). If you are having issues installing WhatsApp on a supported operating system, turn off your anti-virus and try again.
For all other operating systems, you may use WhatsApp on your browser here 
Your account will be permanently banned if you continue to violate our Terms of Service, and there will be no possibility of an appeal.
Best Regards,

**Comment by jlguardi** [comment]
I've my numbers working for long time ago and I've also registered a new line 2 day ago and it is still up.
Check your workflow.

**Comment by yniv** [comment]
@jlguardi do you use this master branch of yowsup? what is your workflow if i may ask? because i also get blocked all the time, not spamming, syncing users before i send them any message, but still get banned even if i don't send any message

**Comment by jlguardi** [comment]
I use my master mixed with yowsup master.

No special or complex workflow but:
 - avoid to send messages to non existing recipients
 - ‎use delays
 - use typing state
 - update recipient info
 - update crypto keys if required
 - manage correctly acks

**Comment by yniv** [comment]
@jlguardi I'm doing all the things you mentioned here... maybe i'm doing something of them wrong???

this is how i handle acks:
`@ProtocolEntityCallback("ack")
    def onAck(self, entity):
        if entity.getClass() == "message":
            self.client.sendCommand(["message", "sent", entity.getId()])
 @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        if self.connected:
            ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", entity.getType(), entity.getFrom())
            self.toLower(ack)
`
this is how i update contacts:
`
    def contacts_sync(self, contacts):
        if self.assertConnected():                        
            entity = GetSyncIqProtocolEntity(contacts.split(','), mode="delta")
            self.toLower(entity)      
`

what do you mean by update crypto keys? this:
`
 # Get shared keys
    def keys_get(self, jids):
        if ModuleTools.INSTALLED_AXOLOTL():
            from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
            if self.assertConnected():
                jids = [self.normalizeJid(jid) for jid in jids.split(',')]
                entity = GetKeysIqProtocolEntity(jids)
                self.toLower(entity)
        else:
            logger.error("Axolotl is not installed")

    # Send prekeys
    def keys_set(self):
        if ModuleTools.INSTALLED_AXOLOTL():
            from yowsup.layers.axolotl import YowAxolotlLayer
            if self.assertConnected():
                self.broadcastEvent(YowLayerEvent(YowAxolotlLayer.EVENT_PREKEYS_SET))
        else:
            logger.error("Axolotl is not installed")
`
what am i missing?!

**Comment by Gab0** [comment]
@jlguardi Can you upload your mixed master for us to try? thanks

**Comment by yniv** [comment]
@jlguardi can you please see if miss something there or doing something wrong? please... :)

**Comment by jlguardi** [comment]
It seems ok however something should be incorrectly managed and so you have banned numbers. 
If you want, I can start your instance in my home and call a web service on each incomming event.

**Comment by KyleJr** [comment]
I've also started using Yowsup for about a week now, still haven't got banned! I'm just too careful I guess...

**Comment by ardhipoetra** [comment]
I got banned by using pidgin plugin long time ago.
