### ISSUE TITLE
Identifying a message from a group

### ISSUE THREAD

**Issue by lintoncaldecott** [tgalal/yowsup#1810]
How do I reliably identify if a message is from a group as opposed to from a single individual?

It has been suggested that you can identify them in the difference highlighted below.
*User*
27782542058@s.whatsapp.net

*Group*
27822152688-1476646471@g.us

Is it reliable to look for a '-' to identify a group message?

**Comment by jlguardi** [comment]
You can use messageProtocolEntity.isGroupMessage()
