### ISSUE TITLE
How download image enc?

### ISSUE THREAD

**Issue by pabloruan0710** [tgalal/yowsup#1811]
Hello, I'm using this yowsup with version 2.50 and Python 2.7, but not can make download of image for my disc, image url is encrypt.... Please, somebody can help me?

This is my scope 

> def getDownloadableMediaMessageBody(self, message):
>         filename = "%s/%s%s"%(tempfile.gettempdir(),message.getId(),message.getExtension())
>         with open(filename, 'wb') as f:
>             f.write(message.getMediaContent())
>         return "[Media Type:{media_type}, Size:{media_size}, URL:{media_url}]".format(
>             media_type = message.getMediaType(),
>             media_size = message.getMediaSize(),
>             media_url = filename
>             # media_url = message.getMediaUrl()
>             #media_file = message,
>             #fname = filename
>         )

**Comment by Nitin-jha2016** [comment]
Hello I cannot send image to the user. R you able to do that?

**Comment by manishbhatias** [comment]
@pabloruan0710 You can try using master branch from https://github.com/jlguardi/yowsup/

**Comment by chenwayne** [comment]
@manishbhatias I tried using Jlguardi's master branch, but still cannot get encrypted images. can you show how to get encrypted images?

**Comment by jlguardi** [comment]
To get encrypted media, use this method of my master: DownloadableMediaMessageProtocolEntity.getMediaContent()

or try #1713.
