### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by moades** [tgalal/yowsup#1814]
hi i installed to packages from synapic package manager 
python-yowsup and yowsup-cli

how do i run this program 

lol

sorry im vary new on linux

my linux is lubntu

Thanks

**Comment by endermrn** [comment]
send message in my skype endermrn_hacking or twitter endermrn_hacking i configure this for you are easy

**Comment by moades** [comment]
ok i will later this day

**Comment by rapha7** [comment]
@endermrn Hey there, I trying to make an automation, when it receives some message it has to answer some thing, I'm following  this tutorial : https://github.com/tgalal/yowsup/issues/647 
but the version is very old and I cannot do the script works :( May u help me pls?

**Comment by MrLuit** [comment]
Seems like it should work. Have you configured it correctly?

**Comment by rapha7** [comment]
Hey man,


Thank u for the attention I was trying make an automation, the way that is in #647 didnt work for me, then I tried use the echo layer to do that. Now it s working fine. Thank you


________________________________
De: MrLuit <notifications@github.com>
Enviado: sábado, 5 de novembro de 2016 10:01
Para: tgalal/yowsup
Cc: rapha7; Comment
Assunto: Re: [tgalal/yowsup] Installing on Linux (#1814)


Seems like it should work. Have you configured it correctly?

-
