### ISSUE TITLE
Echo Client and Message on External Event

### ISSUE THREAD

**Issue by wnew** [tgalal/yowsup#1818]
Hi Guys,

I have got the EchoClient example up and running and it works amazingly well. I am using it as a home automation system. Now I need to poll a GPIO and then send a message if it goes high. I am unsure how to add this functionality to the echoclient as the echoclient only runs on yowsup stack events and I cant run my own functions without a message being received first. How would I add my code to check the GPIO?

I have tried to copy the CLI demo and let my EchoLayer inherit from multiple classes (one of which is my  GPIO poller)

_class EchoLayer(GPIO_poller, YowInterfaceLayer):_

Is this the correct way to go about it?

@sowerkoku I have created a new thread, as I feel it was a different issue.

**Comment by sowerkoku** [comment]
That same @wnew 
GPIO_poller a script should be engaged to review a file or directly GPIO.
the file would have information on GPIO.
message depending on the file information is sent.
then the original data are compared with a new reading of the file.
If these values are equal, the file is written with a default message: "GPIO unchanged."
If these values are different, the process of validation and sending message is repeated.

this GPIO_poller must fulfill a function similar to Cli. the difference is that Cli feeds on a command line and GPIO_poller from a file.

I no longer count on WhatsApp numbers and not with a raspberry.
so I can not generate a code to prove it. I am sorry.

**Comment by johnduxx** [comment]
In run.py file

 stack = stackBuilder\
        .pushDefaultLayers(True)\
        .push(EchoLayer)\
        .build()

Here we pass EchoLayer object to stackBuilder. Instead of it, declare a global variable of EchoLayer , then create and store EchoLayer object into that variable and pass the variable to stackBuilder.

**Comment by sowerkoku** [comment]
@johnduxx, I think @wnew has another idea in mind.

the run.py your would you comment something.
```
from yowsup.stacks                             import YowStackBuilder
from yowsup.common                             import YowConstants
from yowsup.layers                             import YowLayerEvent
from bot_echo_layer                            import EchoLayer
#from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.env                                import YowsupEnv

#Uncomment to log
#import logging
#logging.basicConfig(level=logging.DEBUG)

CREDENTIALS = ("PHONE", "PASSWORD") #replace with your phone and password

if __name__==  "__main__":
    stackBuilder = YowStackBuilder()

    stack = stackBuilder\
        .pushDefaultLayers(True)\
        .push(EchoLayer)\
        .build()

    #stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)       #setting credentials
    stack.setCredentials(CREDENTIALS)       #setting credentials --need not YowAuthenticationProtocolLayer
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))          #sending the connect signal
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])           #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())  #info about us as WhatsApp client

    stack.loop( timeout = 0.5, discrete = 0.5 )                                       #this is the program mainloop
```

**Comment by johnduxx** [comment]
@sowerkoku 
seems i got his idea as he is trying to send message on demand basis.

I had the same requirement where i have used redis pubsub to publish and subcribe message.

from subscriber, i receive message and send over whatsapp to other end.
