### ISSUE TITLE
Can't make automation in v2.5

### ISSUE THREAD

**Issue by rapha7** [tgalal/yowsup#1819]
http://pastebin.com/etb0vB2w <== run.py & layer.py files

Hey there,
I installed Yowsup2 on Linux, and at the current moment it works fine, now im trying to do an automation, like when it receive a message it will answer it. But I was following this tuto #647,
then I had some troubles with EchoLayer. didnt found it.
I searched a lot in forums but I didnt found how to fix it.

When run.py is running i get this error, some one can help me please?

  File "run.py", line 15, in <module>
    from yowsup.layers.axolotl                     import YowAxolotlLayer
ImportError: cannot import name YowAxolotlLayer

**Comment by mxii** [comment]
Your fix?

**Comment by rapha7** [comment]
unfortunately, not yet
