### ISSUE TITLE
Can I make an automation for the yowsup client?

### ISSUE THREAD

**Issue by rapha7** [tgalal/yowsup#1822]
I typed in python a script to log in yowsup client, but log in, I cannot type any comands, like /L.
How can I do that? Some one can help me pls?

the script is basic => ./yowsup-cli demos -y --config yowsup-cli.conf
Then i will log in, but will be offline yet, I have to put /L, but when the script will do this, It doesnt work, the script try type it on linux command line. How can I type this on yowsup client?

**Comment by capsload** [comment]
Bump, any way for this?
