### ISSUE TITLE
Tagging doesn't read message

### ISSUE THREAD

**Issue by MrLuit** [tgalal/yowsup#1823]
In Whatsapp update 2.16.272 tagging people in groupchats was added. (You can type @Name to tag a person).

When you tag the bot, the message only delivers (two grey check marks), but doesn't get read (two blue check marks). Nothing crashes, just that. It is really annoying and I currently haven't found a fix.

Will investigate further.

**Comment by MrLuit** [comment]
I found out that this problem isn't only when tagging the bot, the problem persist when you tag another person.

**Comment by rapha7** [comment]
Could u help me abot how can i make an automatic response pls?

**Comment by MrLuit** [comment]
@rapha7 This is unrelated to the issue.

**Comment by rapha7** [comment]
Sure
