### ISSUE TITLE
Switching to Android fails

### ISSUE THREAD

**Issue by arjenduinhouwer** [tgalal/yowsup#1826]
New issue after a successful registration: [https://github.com/tgalal/yowsup/issues/1824](url)

Switching to Android doesn't work, I keep getting this error: 

```
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.9 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=31&in=6xxxxxxxx&id=%E5%25%2Ch%3F%C5%C1.%96%D1R%00%CC%14%5D%D8%F1%D4%01I&lg=en&lc=GB&token=b652ec63b88c1e7d432bf2661b049a65&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=53508&extexist=1&extstate=1
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request
```

I changed the DEFAULT var from s40 to Android in de env.py file. But this doesn't load the Android device. 

Any ideas?

**Comment by jlguardi** [comment]
Install your edited code.

**Comment by arjenduinhouwer** [comment]
Thanks jlguardi, it worked. 

I'm getting connection_closed responses, so that's a bummer. I'm trying to figure out what's happening now. With the S40 it was running by now, so the Android device poses new challenges.

**Comment by arjenduinhouwer** [comment]
I keep getting problems using the android device. 

`DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`

This is my env_android.py

```
    _MD5_CLASSES = "1I2weuZmVg+uL50+HXeSJw=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.16.328"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

```

messages sent to this phone are not arriving as well. 

Are the settings wrong?

**Comment by Dl0tt** [comment]
Also having this problem with both an old number and a fresh one.

**Comment by chenwayne** [comment]
Same problem met here, I changed to environment to s40 from anddroid again, but number got banned. And cannot register using s40 envrionment, got old version problem.
