### ISSUE TITLE
Any working example?

### ISSUE THREAD

**Issue by manugarciac** [tgalal/yowsup#1827]
I was able to send messages with the command line application, but I was eventually banned. I want to build a Pyhton script now to do the sending and manage acks and stuff like that. I'm quite new to Python, so I want to start from a working example and build from that, but the example in the Wiki seems to be outdated. There is a comment in the run.py part that says it must be modified.

Anyone has a working example I could use? I only want to be able to send messages, no need to be able to receive them, but I want to avoid banning as much as possible.

**Comment by manugarciac** [comment]
I've been launching the demo now, like this:

yowsup-cli demos -c my_config.txt -y

And was able not to get banned for a couple of hours. However, this morning I was already banned. Any tips how to avoid this?

**Comment by MrLuit** [comment]
Use new IP-addresses for every registration. Also, check out the [sample application](https://github.com/tgalal/yowsup/wiki/Sample-Application) for acks and receipts.

**Comment by hoehermann** [comment]
I use yowsup in my application [wxpyWha](https://github.com/hoehermann/wxpyWha). I still don't know if I do the message sending right, but it seems to work reasonably well.

**Comment by tgalal** [comment]
[demos](https://github.com/tgalal/yowsup/tree/master/yowsup/demos)
