### ISSUE TITLE
Yowup Integration Using java

### ISSUE THREAD

**Issue by Nitin-jha2016** [tgalal/yowsup#1828]
Hello Friends..

I needed to understand how i can integrate Yowsup in java. Also i am not able to send image from this application.

Please help

**Comment by MrLuit** [comment]
Please go in detail why sending images does not work. Have you checked out [the wiki](https://github.com/tgalal/yowsup/wiki/Upload-and-send-Media)?

For Java, you could use [this API](https://github.com/Margaruga/JavaWhatsApp).

**Comment by Nitin-jha2016** [comment]
Yes but its only sending sendsms api not media sending api. Please share code how to send media(image,audio) as well

**Comment by robbietjuh** [comment]
You might be able to integrate your Java application with the Yowsup Python library by using Jython. They have some excellent documentation on integrating Java and Python on their [wiki](http://www.jython.org/jythonbook/en/1.0/JythonAndJavaIntegration.html#using-jython-within-java-applications).
