### ISSUE TITLE
PHP API

### ISSUE THREAD

**Issue by rajitbansal** [tgalal/yowsup#1829]
As its the python API.. do you have one in Php too?

**Comment by ankitpise** [comment]
https://github.com/mgp25/Chat-API
Check this out

**Comment by rajitbansal** [comment]
@ankitpise  that one is dead

**Comment by MrLuit** [comment]
The PHP-library from mgp25 has reached end of support. There is no functional PHP library, however you could use yowsup and use a webhook to make a http request on every new message.

**Comment by rajitbansal** [comment]
can u help me in that?

**Comment by MrLuit** [comment]
Just download yowsup and fiddle around with the sample application. If you run into errors you can always email me.

**Comment by ranieresantos** [comment]
@rajitbansal ... conseguiu ? Estou tentando utilizar o metodo citado pelo @MrLuit até agora não consegui ...

**Comment by badinenisaivardhan** [comment]
Need php version of youwsup help..
