### ISSUE TITLE
Register not found any more.

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [tgalal/yowsup#1831]
I' can't register any more, i get the error: "lock". 
I get the error: "locked". I investigated and found this post:

Help me please

WHATSAPP: As we announced in our blog, WhatsApp will no longer be supported on Nokia S40 by the end of 2016.
In order to run WhatsApp, you must be using a supported phone.
For supported devices please see the list below:

**Comment by assegaf** [comment]
Where did you found those info locked ?

**Comment by rhernandez-itemsoft** [comment]
https://www.whatsapp.com/faq/en/s60/21099118
