### ISSUE TITLE
Auth error not authorized after registration

### ISSUE THREAD

**Issue by DarioBlanca** [tgalal/yowsup#1832]
I'm sorry but my inglish sucks.
The thing is that i've tried all after good registration to make api work. I've tried every solution that i saw at issues, but still throwing me auth error.
The weird thing is that the phone numbers registers ok. Time ago the programs goes ok, but when i start again to probe, it just register bit when i try to run run.py, after some seconds, it crash. 
I runing ubuntu 15.10, every library that yowsup needs i've installed ok. Pleaseeeeee
Aguante yowsup, me encanta, pero no lo puedo usar.. me bloqueo un monton de numeros.

The worst thing is that it trow error, i tried too to re-re-register the number, and it looks like its perfectly up.

Help. Estoy perdiendo mucha plata!

**Comment by jlguardi** [comment]
Probably you have incorrectly registered your number or you have registered your number in a phone device again so your password is invalidated. Please, read the documentation and follow the process step by step.
Then post debug logs (-d) if the issue persists.
