### ISSUE TITLE
Whatsapp number block issue

### ISSUE THREAD

**Issue by Nitin-jha2016** [tgalal/yowsup#1833]
Hey All

Any solution any one found on number banned/block issue? Whatsapp always block number
Any solution of this please?

**Comment by rhernandez-itemsoft** [comment]
WhatsApp will no longer be supported on Nokia S40 by the end of 2016.
 https://github.com/tgalal/yowsup/issues/1831

**Comment by Nitin-jha2016** [comment]
@rhernandez-itemsoft   I am trying to do this from yowsup. What change i do so that it should not block by whatsapp?

**Comment by matheuschimelli** [comment]
My number was blocked. I tryed yowsup today and today my number is blocked

**Comment by KyleJr** [comment]
It's funny how everyone is getting blocked except me, I've been on yowsup for weeks. What am I not doing wrong? Can you guys post your initial files or layer and stack?

**Comment by matheuschimelli** [comment]
@KyleJr i am using the getting started guide code

**Comment by aethemba** [comment]
@KyleJr , Could you perhaps share your layer.py and run.py? I've also used the example code in the getting started guide (using the Run I example code). I'm more than happy to stick to whatsapp rules using Yowsup if, however, I know what they are ;)

**Comment by ashishradadia** [comment]
can we use -E android
