### ISSUE TITLE
Unable to decrypt received video message

### ISSUE THREAD

**Issue by manishbhatias** [tgalal/yowsup#1845]
Hi,

I was trying to receive video messages using yowsup. I decoded the protocol buffers for video message after a number of tries based on protoc --decode_raw and implemented image message.

I am able to succesfully get the video details including the thumbnail, size, duration and media_key.

However, I am unable to decrypt the encrypted video after downloading it.

I used the same decrypt function for image and it works fine.

Could somebody help me figure out the video decryption?

**Comment by jlguardi** [comment]
Use my master.

**Comment by manishbhatias** [comment]
Thanks, it seems I was using the wrong crypt keys for video.

On a side note, it seems that the decrypted files have some extra bytes at the end of file. Seems to be padding due to AES block cipher.

```
def decrypt(self, encimg, refkey):
        derivative = HKDFv3().deriveSecrets(refkey, binascii.unhexlify(self.cryptKeys), 112)
        parts = ByteUtil.split(derivative, 16, 32)
        iv = parts[0]
        cipherKey = parts[1]
        e_img = encimg[:-10]
        AES.key_size=128
        cr_obj = AES.new(key=cipherKey,mode=AES.MODE_CBC,IV=iv)
        return cr_obj.decrypt(e_img)

```

Should we unpad the decrypted data before using it further?

**Comment by tgalal** [comment]
fixed

**Comment by ghsharm** [comment]
@tgalal  How did this issue get fixed?
