### ISSUE TITLE
Receiving onMessage from group

### ISSUE THREAD

**Issue by danielcardeenas** [tgalal/yowsup#1846]
When I send a message from a group it doesn't fire the callback. Works only when chatting one-to-one

My code:
```python
class EchoLayer(YowInterfaceLayer):
    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        #send receipt otherwise we keep receiving the same message over and over
        
        print("Got message");
```

Am I missing something here?

**Comment by KyleJr** [comment]
@danielcardeenas 
Try this:
```
class EchoLayer(YowInterfaceLayer):
    @ProtocolEntityCallback("message")
    def onMessage(self, message):     
        if (message.isGroupMessage()):
            print("(GROUP)[%s]-[%s]\t%s" % (message.getParticipant(), message.getFrom(), message.getBody()))
        else:
            print("(PVT)[%s]\t%s" % (message.getFrom(), message.getBody()))
```

**Comment by jlguardi** [comment]
@danielcardeenas Probably you have problems in the encryption layer. See debug logs to see if incoming message can't be read and then ack'd but not notified to the upper layers.
@KyleJr In fact, your code is the same than Daniel code but you print the group message correctly . With his code, he should print "Got message" on group messages.
