### ISSUE TITLE
Registration error: No script named 'yowsup-cli'

### ISSUE THREAD

**Issue by eLeeha** [tgalal/yowsup#1848]
Hi,

I am installing yowsup on my Ubuntu 14.04. 
With 
`python setup.py install`
I got no error.

So I try
`yowsup-cli registration --requestcode sms --phone xxxxxxx --cc xx --mcc 262 --mnc 01`
but I got an error

`Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/root/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1490, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'yowsup-cli'`

Like I understand yowsup-cli is not known. 
Can someone help me what I have to do? 

Thanks

**Comment by eLeeha** [comment]
/solved

I started from new and now it works perfect. Can't say what exactly the error was.

**Comment by ArturoGonzalezBecerril** [comment]
try reinstall packages
