### ISSUE TITLE
How to subscribe to profile picture updates?

### ISSUE THREAD

**Issue by el** [tgalal/yowsup#1852]
Hello, I am trying to get profile picture updates with an event.

I am aware that you can do:

```
entity = GetPictureIqProtocolEntity(self.aliasToJid(jid), preview=preview)
                self._sendIq(entity, onGetContactPictureResult)
```

to get a specific contact picture. When one of your contacts changes their picture the effect is immediate in the official app. I was wondering if we can have that functionality much like presence subscribe?

**Comment by gi097** [comment]
Just subscribe once to the contact (request their last seen), you will get all his/her updates.

**Comment by el-iz** [comment]
I tried with `logging.basicConfig(level = logging.DEBUG)` and it doesn't seem to get an update

**Comment by towarisch** [comment]
Hi, 
has someone been able to solve this issue? The Profile Picture Updates are not being pushed as event

**Comment by tgalal** [comment]
[SetPictureNotificationProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_notifications/protocolentities/notification_picture_set.py) is what you should receive when a contact updates their picture. Afterwards use GetPictureIq to get the picture
