### ISSUE TITLE
is possible to enter a group using a invitation link? in yowsup

### ISSUE THREAD

**Issue by jegue** [tgalal/yowsup#1854]

**Comment by KyleJr** [comment]
That's available on WA20 and yowsup uses WA16, but wait for further answers

**Comment by jlguardi** [comment]
No it isn't. I guess it doesn't depends on WA protocol version but application version. Anyway, it isn't implemented on yowsup.

**Comment by SweetShyGirl** [comment]
Can this be added please

**Comment by jlguardi** [comment]
For sure! Implement it and submit a PR.
