### ISSUE TITLE
Get both JID of remove/add group notification protocol entity! -_-

### ISSUE THREAD

**Issue by SweetShyGirl** [tgalal/yowsup#1855]
Hiiii

I'd like to know why I can't get the JID of the person who removed someone
And the person that was removed?

Same for add to group notification entity, regards! 👍 

Thanks

Other FAQs:

Why is contacts last seen throwing random seconds?
Why am I unable to use Iq results in other functions?

I want to check if the bot is admin, return true, then use it in another function but it's hard to return true :(

**Comment by KyleJr** [comment]
It's available, just create a new function and return "participant", also add it to self as a global variable.

**Comment by SweetShyGirl** [comment]
Thanks @KyleJr

Fixed!
