### ISSUE TITLE
my account been banned when login at my phone after tried yowsup-cli /message send 

### ISSUE THREAD

**Issue by bhui** [tgalal/yowsup#1858]
First, I tried yowsup-cli register sms and create group, it's ok.
and then,
[connected]:/message send  XXXXX nihao
[connected]:
[connected]:
[connected]:
[connected]:
[connected]:/message send  XXXXX nihao2
[connected]:
[connected]:
[connected]:/message send  XXXXX nihao3
[connected]:
[connected]:/message send  XXXXX nihao4
[connected]:
Sent: 1480560368-10
[connected]:
Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

I tried register again, it return 
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked","login":"xxx"}

when I tried login at my phone, the tips is "您的电话号码xxxx被禁止使用WhatsApp了.请联系客服服务寻求帮助".

What way do you test api ? and will not been banned.

**Comment by KyleJr** [comment]
You should only send messages to your contacts, you were banned because the number you sent a message to either doesn't have you as contact or you didn't sync it to your yowsup contacts.

**Comment by bhui** [comment]
what format does the number?  
Area number (china 86)+ phone number(chinese phone number ) is right or wrong?

**Comment by jlguardi** [comment]
your should sync your contacts with GetSyncIqProtocolEntity. This function requires the phone numbers without country code (CC) or full phone number including the '+'. I mean, it uses the same format as you use in your phone.
