### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Robotit** [tgalal/yowsup#1859]
I just installed **Yowsup2** and I'm trying to register my phone.

I don't find anywhere what I'm supposed to do, but after whole afternoon searching I reached this point. I'm entering my personal mobile number (with the country code), followed by all the details of this command (according to `python "C:/Python27/Scripts/yowsup-cli" registration --help`):

`python "C:/Python27/Scripts/yowsup-cli" registration --requestcode sms --phone XXXXXXXXXXX --cc XX --mcc XXX --mnc XX`

I'm getting the following error while executing it:

```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
```

**Comment by pippopippo69** [comment]
same problem here

**Comment by nedimhx** [comment]
I was able yesturday, but after I reinstall raspberry today, I get this problem.

https://github.com/tgalal/yowsup/issues/1861

**Comment by danjesus** [comment]
same problem here

**Comment by Fabi755** [comment]
Switch ENV to `android` and change 
`_MD5_CLASSES` to `1I2weuZmVg+uL50+HXeSJw==`
`_VERSION` to `2.16.328`

See issue #1824 for more details.

**Comment by vityapro** [comment]
@Robotit please close issue
