### ISSUE TITLE
How do I check if my number has been banned?

### ISSUE THREAD

**Issue by MarkMccl** [tgalal/yowsup#1860]
Is there any way to check (preferably without using a phone with whatsapp) whether a number I have been using with yowsup has been banned? It almost seems like my yowsup bot gets banned temporarily, at small hourly intervals?

**Comment by MarkMccl** [comment]
Running into errors listed above. Currently I am accepting incoming message, creating a string dependent on the body of the incoming message and passing it to be sent. The error seems to be stemming from trying to parse the outgoing message?

`@ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), $

        outgoingMessageProtocolEntity = TextMessageProtocolEntity(
            messageProtocolEntity.getBody(),
            to = messageProtocolEntity.getFrom()
        )

        myStr = self.doYogi(outgoingMessageProtocolEntity.body)
        print myStr

        if myStr is not None:
            print "In send condition"
            self.toLower(receipt)
            self.toLower(myStr)
`

**Comment by gi097** [comment]
When registering your number you will get an error with reason 'blocked'. If you already have a password and try to login you will get the error 'not-authorized'.
