### ISSUE TITLE
Unable to register reason old_version

### ISSUE THREAD

**Issue by nedimhx** [tgalal/yowsup#1861]
Hello,

I'm unable to register whatsupp number, I did the same steps like yesturday, but today I'm unable to register number.

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

What now ?

**Comment by danjesus** [comment]
I have same issue

**Comment by deepanz017** [comment]
me too.

**Comment by gokugiant** [comment]
Have the same problem here.

**Comment by mariuschicinas** [comment]
any fix for this ?

**Comment by nedimhx** [comment]
I have fix problem doing this
Changed yowsup/env/env.py

DEFAULT = "Android"
and changed yowsup/env/env_android.py

 _MD5_CLASSES = "1I2weuZmVg+uL50+HXeSJw=="
 _VERSION = "2.16.328"

From the https://github.com/tgalal/yowsup/issues/1824

Thanks everyone on help!

**Comment by nedimhx** [comment]
@tgalal can you please explain me how to send image trough run.py and layer.py from wiki page.
Everything is ok when I write "Temperature" and get temperature result from temerature sensors, "LED" I can turn on and off LED, But how to get image if I write "snap me" from folder /home/pi/images/IPcam.jpg

Please help me.

**Comment by spiritbrother** [comment]
thanks for your help <img src="http://www.warrenphotographic.co.uk/photography/bigs/37476-Ginger-cat-back-view-white-background.jpg"/>

**Comment by edgarsampson** [comment]
@tgalal I managed to fix the old version issue by changing the version to the latest Whatsapp version. However I am getting the bad token error. What is the process for resolving this?

Thanks

**Comment by Zer0ne83** [comment]
@tgalal Also failing to register with the 'old version' error. Have tried every combination of fixes/alterations to env.py, env_s40.py and/or env_android.py as per users' posts in #1824, #1869, #1875 (...and the rest), i.e. changing default envs, Version nos. and associated MD5 nos. All files re-pulled. Nothing doing. Is reg. suspended or something? Any help greatly appreciated.

**Comment by plepps** [comment]
same here in centos 6 - try all changes - no luck. It doesnt matter if I set android or s40 as Default env.

yowsup-cli  v2.0.15
yowsup      v2.5.2
INFO:yowsup.common.http.warequest:{"login":"49xxxxxxxxx","status":"fail","reason":"old_version"}

**Comment by Zer0ne83** [comment]
Wondering if the project has been abandoned given the 3rd party application drama/bans in March? @tgalal ?

**Comment by plepps** [comment]
I dont knpow why, but I got it running. I try a lot of hints and put them together:

mkdir tmp
cd tmp
wget https://github.com/tgalal/yowsup/archive/master.zip
unzip master.zip
cd yowsup-master
cp yowsup/env/env_android.py yowsup/env/env_android.py_org
wget https://raw.githubusercontent.com/colonyhq/yowsup/master/yowsup/env/env_android.py
cp env_android.py yowsup/env/env_android.py

vi yowsup/env/env.py
DEFAULT = "Android"

python setup.py install

then I was able to register the client:
./yowsup-cli registration --requestcode voice -p 49xxxxxxxxxx -C 49 --env android
./yowsup-cli registration --register xxx-xxx-p 49xxxxxxxxxx -C 49 --env android

put the recieved password and phone number in my config file.

Now I try to logon the client, but always stay offline. The solution for this is switch back env to s40 for sending messages:

./yowsup-cli demos -s 49xxxdestinationxxx "bla bla" -c /root/config.yowsup --env s40

works!

**Comment by Zer0ne83** [comment]
Omg. DAMN good work, plepps. I am actually struggling to isolate what in your 'recicpe' above differs from what I already tried but there must be something because, as you say, works! Bless you man. Thank you so much for sharing :1st_place_medal:

**Comment by pyVarad** [comment]
Are you sure @Zer0ne83 it works. I am still facing issues.

http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"91XXXXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 91XXXXXXXXXX

**Comment by Zer0ne83** [comment]
Yep, @pyVarad, deffo sure. I just registered another account on a different AU mobile phone number like 3 minutes ago just to make sure @plepps 'recipe' was still working and...

> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> INFO:yowsup.common.http.warequest:{"status":"ok","login":"61432296***","type":"new","pw":"37JEQouNRLT**************=","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"AUD","price_expiration":1505965840}
> 
> status: ok
> kind: free
> pw: 37JEQouNRLT**************=
> price: $0.99
> price_expiration: 1505965840
> currency: AUD
> cost: 0.99
> expiration: 4444444444.0
> login: 61432296203
> type: new
> root@kalipi2:~/tmp/yowsup-master#

And, even though I already had yowsup installed (obviously) as per @plepps recipe on my primary machine, I did a brand new install from scratch on my Kali 2.0 RPi using exactly the commands that @plepps provided. As per my last post, I honestly couldn't figure out what in @plepps' recipe/steps was different to what I had already tried - still can't. I just rm'd everything, rebooted and blindly followed @plepps' recipe and it worked... and still does for me.

**Comment by plepps** [comment]
I believe its all about the changes in env_android.py and the fact, that you have made the whole registration process with the android env settings, but the message sending with the env s40

`diff env_android.py_org env_android.py
20c20
<     _MD5_CLASSES = "1I2weuZmVg+uL50+HXeSJw=="
---
>     _MD5_CLASSES = "ox998VW0nBTueMVfjuZkmQ=="
23c23
<     _VERSION = "2.16.328"
---
>     _VERSION = "2.17.212"`

**Comment by Zer0ne83** [comment]
@pyVarad / @plepps - Yeah, I agree. What I was doing was madly editing/updating the VERSION numbers and MD5 hashes in the env_android.py and env_s40.py files after I had already run the 'python setup.py install' command. Rather, in @plepps recipe, we switch out (replace) the shoddy env files with the good ones (thanks @colonyhq) THEN run the setup. Perhaps this is where you are going wrong, like I was, @pyVarad ? 

Oh and @plepps, I'm sure you have figured this out, but if I run:
**root@kalipi2:~#** yowsup-cli demos -y -c /root/config.yowsup <- no -env switch at all and with -y
_. . ._
then at the Cli Client Interface run **/L** (quick login)
Yowsup Cli client
==================
Type /help for available commands
**[offline]:** /L
**Auth: Logged in!
[connected]:**

> 
### 
> /contacts      sync           <contacts>                    Sync contacts, contacts should be comma separated phone numbers, with no spaces
> /image         send           <number> <path> [caption]     Send an image with optional caption
> /audio         send           <number> <path>               Send audio file
> /video         send           <number> <path> [caption]     Send a video with optional caption
> /L                                                          Quick login
> /state         paused         <jid>                         Send paused state
> /state         typing         <jid>                         Send typing state
> /seq                                                        Send init seq
> /group         promote        <group_jid> <jids>            Promote admin of a group. Jids are a comma separated list
> /group         setSubject     <group_jid> <subject>         Change group subject
> /group         info           <group_jid>                   Get group info
> /group         kick           <group_jid> <jids>            Kick from group. Jids are a comma separated list
> /group         picture        <group_jid> <path>            Set group picture
> /group         leave          <group_jid>                   Leave a group you belong to
> /group         invite         <group_jid> <jids>            Invite to group. Jids are a comma separated list
> /group         demote         <group_jid> <jids>            Remove admin of a group. Jids are a comma separated list
> /help                                                       Print this message
> /profile       getPrivacy                                   Get profile privacy
> /profile       setStatus      <text>                        Set status text
> /profile       setPrivacy      [value] [names]              Profile privacy. value=all|contacts|none names=profile|status|last. Names are comma separated, defaults to all.
> /profile       setPicture     <path>                        Set profile picture
> /message       broadcast      <numbers> <content>           Broadcast message. numbers should comma separated phone numbers
> /message       send           <number> <content>            Send message to a friend
> /ping                                                       Ping server
> /groups        list                                         List all groups you belong to
> /groups        create         <subject> [jids]              Create a new group with the specified subject and participants. Jids are a comma separated list but optional.
> /contact       lastseen       <jid>                         Get lastseen for contact
> /contact       picture        <jid>                         Get profile picture for contact
> /contact       picturePreview <jid>                         Get profile picture preview for contact
> /account       delete                                       Delete your account
> /disconnect                                                 Disconnect
> /keys          get            <jids>                        Get shared keys
> /ib            clean          <dirtyType>                   Send clean dirty
> /presence      name           <name>                        Set presence name
> /presence      subscribe      <contact>                     Subscribe to contact's presence updates
> /presence      available                                    Set presence as available
> /presence      unavailable                                  Set presence as unavailable
> /presence      unsubscribe    <contact>                     Unsubscribe from contact's presence updates
> /statuses      get            <contacts>                    Request contacts statuses
> /login                        <username> <b64password>      Login to WhatsApp
> ----------------------------------------------
> [connected]:

**Weeeeee!!!** So many commands to play with and they all work!

**Comment by plepps** [comment]
I think you did not change the DEFAULT ENV in yowsup/env/env.py right?
In this case I would understand, that you can reach the demo shell without setting s40 env. Because thats the default ENV in the original setup. Otherwise I dont know why. I try it several times with diffrent ENV settings, always the same result:

The original env_s40.py is fine for sending messages an demo so there is no need to modify.
You only need the patched env_android.py for the registration process.
After modifying the py files, there is alwas "python setup.py install" necessary.

**Comment by kirthiss** [comment]
I get this error while regstering - 
Traceback (most recent call last):
  File "./yowsup-cli", line 5, in <module>
    from yowsup.env import YowsupEnv
  File "/home/ubuntu/tmp/yowsup-master/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/ubuntu/tmp/yowsup-master/yowsup/env/env.py", line 17, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases


Any help?

**Comment by nonna2010** [comment]
INFO:yowsup.common.http.warequest:b'{"login":"xxxxxxxxx","status":"fail","reason":"old_version"}\n
