### ISSUE TITLE
URGENT : ( Closing support for Nokia Symbian ,S40 ,BB 10 )

### ISSUE THREAD

**Issue by anishmenon** [tgalal/yowsup#1863]
https://blog.whatsapp.com/10000617/WhatsApp-support-for-mobile-devices

As we look ahead to our next seven years, we want to focus our efforts on the mobile platforms the vast majority of people use. So, by the end of 2016, we will be ending support for WhatsApp Messenger on the following mobile platforms:

BlackBerry OS and BlackBerry 10
Nokia S40
Nokia Symbian S60
Android 2.1 and Android 2.2
Windows Phone 7
iPhone 3GS/iOS 6

**Comment by spiritbrother** [comment]
kenapaaaaaaaaaaaaa <h1>whyyyy?????</h1>

**Comment by Stepkaa** [comment]
UPDATE: WhatsApp is extending support for BlackBerry OS, BlackBerry 10, Nokia S40 and Nokia Symbian S60 until June 30, 2017.

**Comment by anishmenon** [comment]
But its until June 30, 2017. Don't do serious apps with .. correct

**Comment by johnduxx** [comment]
WhatsApp users, rejoice. Despite having recently announced plans to kill support for hundreds of devices, the Facebook-owned messenger has had a last minute change of heart.

With support for BlackBerry and Nokia devices having been scheduled to be knocked on the head “by the end of 2016”, WhatsApp has now reversed its decision.

Instead, WhatsApp has confirmed that support for BlackBerry 10, BlackBerry OS, Nokia Series 40 and Sybian Series 60 based handsets will be extended until June 30, 2017.


Read more at http://www.trustedreviews.com/news/there-s-some-really-good-news-for-whatsapp-users#8EKo1UtrtQT0juoY.99

**Comment by KyleJr** [comment]
We're still able to create multiple applications on it anyways, the API can be changed to any other device by the end of support through reverse engineering, for those who's inexperienced in programming will have difficulties with new changes.

**Comment by schoerg** [comment]
@anishmenon you don't do serious apps anyway with this.

**Comment by anishmenon** [comment]
@schoerg  Yes i know . i'm just new to this repo and i shared an info i got . If any of its users uses for serious Apps they should be notified . Even parsing from a HTML is not good for Serious APPS . Every small small innovative apps based on these kind of helpful repos . They might know that was my motive . 

Cheers

**Comment by gi097** [comment]
Don't worry, I am releasing a third party app which will support the newer protocol.
