### ISSUE TITLE
"old_version" Error when requesting code via SMS

### ISSUE THREAD

**Issue by Par2ival** [tgalal/yowsup#1865]
When requesting code via SMS i get 
status: fail 
reason: old_version

I checked my version and it is the most current. 
Is this a bug or am i doing something wrong?
Please see attached text file for the sequence of steps i took.

Any help would be greatly appreciated.

Kind Regards
Par2ival

[ErrorMsg-old_version.txt](https://github.com/tgalal/yowsup/files/639331/ErrorMsg-old_version.txt)

**Comment by gushome7** [comment]
See https://github.com/tgalal/yowsup/issues/1824

**Comment by Par2ival** [comment]
@gushome7 sorry I was away for a few days, thanks allot for the quick & accurate reply. Really appreciate it!
