### ISSUE TITLE
Sms never come

### ISSUE THREAD

**Issue by hypertech** [tgalal/yowsup#1866]
Hi everyone.

Sms never come on s40 env on activation. Anybody has same issue that sms come only on android env ?

**Comment by Kurill** [comment]
have same issue, can't fix it

**Comment by Bodasia** [comment]
problem in alphanumeric sms sender name try use mnc code what don't support it

**Comment by hypertech** [comment]
Can you give any mnc witch don't support alphanumeric ?

**Comment by Kurill** [comment]
all in T-Mobile network operator like 260

**Comment by Bodasia** [comment]
but sumtime it come on second requst

**Comment by hypertech** [comment]
thanks guys, i will give it a try

**Comment by jlguardi** [comment]
Probably, it is due to a server IP banning.
