### ISSUE TITLE
Can't login to whatsapp or send a message reason: Connection Closed

### ISSUE THREAD

**Issue by anikan85** [tgalal/yowsup#1867]
I am not able to perform a login or send a message.
New installation from today. And a completly new numer. Not used by any other whatsappclients.
Here is the debug of sending a message:

`sudo yowsup-cli demos -s 49160XXXXXXX "Hallo Welt!" -c /etc/yowsup/config.yowsup -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fb7fb67f210>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fb7fb66a910>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="491577XXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒(-     ]P▒b6@h▒▒V▒N▒▒
HEX:c8282d095d501d8b6236406800be9456f54e92aa
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒▒▒▒ak▒▒▒"▒d▒0#6)4ũnxt!ʷi▒ӊ▒C▒▒▒t▒▒▒▒C▒▒?▒▒▒▒▒\C▒-T▒▒▒=▒/+L▒=▒~IJ▒
HEX:a08af70ff9616b9ab01d952285649f302336291a34c5a9156e78037421cab769acd38ac1944381bced7414829f99f9aa43fcc83fada5fd88e013905c43ad2d54a1adc53dba2f2b4ca13db27e494a82
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`

phone numbers are removed with X

Anybody a clou what is happening here?

**Comment by harishkumarv** [comment]
+1, facing the same issue for the past few days.

**Comment by rafaelsilverioit** [comment]
@anikan85 keep an eye on this thread: https://github.com/tgalal/yowsup/issues/1313

**Comment by jlguardi** [comment]
I've experienced a lot of issues with android env but S40 env still works. Try it.
Is wa1.6 still supported by android configuration? I guess you should use wa2.0 (unimplemented) for that.

**Comment by nhet** [comment]
+1, facing the same issue for the past few days.

**Comment by jlguardi** [comment]
@nhet have you used s40 env?

**Comment by nhet** [comment]
s40 was the default and a registration not possible. Therefore I have changed from s40 to android in /opt/yowsup-master/yowsup/env/env.py
The registration was after that possible but sending messages is not working.

**Comment by andischan** [comment]
@jlguardi I've switched to DEFAULT = "s40" and get the same error:

`yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f096dd86668>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f0971853898>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e7.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" mechanism="WAUTH-2" user="015774068060">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
¶·¦ÿ°Ùbä
HEX3:b'bbc791ca91ffb0d962859ae49d8b0db699b790a6'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
<To½Ç_wI° ¢³©ÄÜëlÿù»1§§««kÎ·Ò3¸åëpBR;x²>bé5bJâ,·ò>{ó
HEX3:b'3c1a546fbdc75f9d037749b0a01c1916a2b3a9c4dc8deb6c9096fff9bb3194a7a784abab6b94ce00b7d233b8e5eb709442523b78b23e6202e935629e4ae2978c2cb7f23e7bf3'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure`

**Comment by jlguardi** [comment]
Remove nonce file from .Yowsup/phone folder and try again.

**Comment by andischan** [comment]
I have removed all folders from .yowsup and it failed again.

**Comment by pctmudza** [comment]
I have the same issue "DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`"
Using env android as well and using these versions on yowsup
yowsup-cli v2.0.15
yowsup v2.5.0

**Comment by jlguardi** [comment]
@pctmudza you are getting connection closed due to Android env which uses wa2.0 protocol. Use s40 env instead.

**Comment by pctmudza** [comment]
@jlguardi Thanks tried this and got the same result , debug log below:

./yowsup-cli demos -l 6017XXXXXX:HyTybxXXXXXXBLpLPpTsMDQ4AJo= -E s40 -y -d
DEBUG:yowsup.env.env:Current env changed to s40
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x76096890>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x76096510>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="6017XXXXXX" mechanism="WAUTH-2">
▒▒1▒7(▒▒0▒▒?▒▒
▒▒▒.▒F▒▒嘗▒8▒▒▒▒e▒▒@֤▒▒g▒▒aT▒a̶▒▒▒▒Չ
HEX:b005be31d4371228999230c5fd3ffb06820ce7c1c62ee946dccde59897a7051b250ff23889a7d5dd1865a3ca1140d6a49ce00567b9b961549a61ccb6d4f319a4181fcad589
</auth>

PuTTYPuTTYPuTTYgeneral: Disconnected: Connection Closed
[offline]:
[offline]:PuTTYPuTTYPuTTY

**Comment by pctmudza** [comment]
@jlguardi hi thanks,changing to S40 solved it using below command:

python yowsup-cli demos -l 6017XXXXXX:HyTyXXXXXXIEBLpLPpTsMDQ4AJo= -E s40 -s 60162XXXXXX "Hello"

**Comment by pos-ei-don** [comment]
` error: unrecognized arguments: -E s40`

**Comment by pippopippo69** [comment]
same problem:

yowsup-cli demos -c /home/pi/yowsup/config -E s40 -s 39XXXXXXX "test" -d


DEBUG:yowsup.env.env:Current env changed to s40 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7608e330>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x761daf90>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="XXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
}XXXXX{??
HEX:7d1f73e5ce4bb83160d803d293a31d7b1616bea8
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">

??ti]?????^??r#
               G?y?`???\g?<"??U?n?jo$
i?x                                  ?X?N?z?[n???p?T?h+
HEX:0b96b874695d82c51a95b8cb5eddcf72230b479f79b460e9faf55c6796013c14228e9555aa6e926a6f0f240b915819ee4ea07a9b5b6eaece15a9030370df54f2682b0d699b78
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

**Comment by fjrmaulana** [comment]
look all command response cant be login...
I've been looking for trouble but not seen

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed

python yowsup-cli demos -l 6289624xxxxxx:v4qY/Zkr5m1w4aLEx0xxxxxxxxx= -E android -s 628999979934 "Hello"
python yowsup-cli demos -c whatsapp_config.txt -s 628999xxxxxx "Test WhatsApp..." -E s40
python yowsup-cli demos -E android -y -d --config whatsapp_config.txt
python yowsup-cli demos -d -y -c whatsapp_config.txt -E android
python yowsup-cli demos --yowsup -E android -y -d --config whatsapp_config.txt
python yowsup-cli demos -E android -y -d -l 6289624xxxxxx:v4qY/Zkr5m1w4aLxxxxxxxxxxxx= -E s40 -s 6289999xxxxx "Hello"
python yowsup-cli demos -d -l 628962xxxxxxx:v4qY/Zkr5m1w4aLEx0cGxxxxxxx= -E android -e
python yowsup-cli demos --yowsup --config whatsapp_config.txt --env android
python yowsup-cli demos -d -c whatsapp_config.txt -y -E android

python yowsup-cli demos -E android -y -d --config whatsapp_config.txt 	enter
/L									enter

any ide sir...?
