### ISSUE TITLE
general: Login Failed, reason: not-authorized Auth Error, reason not-authorized

### ISSUE THREAD

**Issue by nedimhx** [tgalal/yowsup#1868]
After reinstall system, changing yowsup/env/env.py DEFAULT = "Android" and yowsup/env/env_android to
_MD5_CLASSES = "1I2weuZmVg+uL50+HXeSJw=="
 _VERSION = "2.16.328"

Where I skip "old version" issue, now, after registration I have this problem
yowsup-cli demos --yowsup --config config
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

**Comment by molayac** [comment]
Hi, 

I am having the same issue, this project is still working?

Somebody have the solution?

**Comment by jlguardi** [comment]
Yes, it works! But don't use android env but s40 with version 2.16.10 or 2.16.11.

**Comment by molayac** [comment]
Yes, Thanks, 

I change environment after registration, from Android to s40 and now its working Thanks

**Comment by manan-agile** [comment]
@molayac  How to change environment after registration?
