### ISSUE TITLE
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_token"}

### ISSUE THREAD

**Issue by krdsx** [tgalal/yowsup#1870]
Hello, please help
https://github.com/tgalal/yowsup/issues/new

~/yowsup$ sudo yowsup-cli registration --requestcode sms --phone 90XXXXXXXXX --cc 90 --mcc 123 --mnc 456
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_token"}
status: fail
reason: bad_token

**Comment by rafaelsilverioit** [comment]
Can you try this, please? https://github.com/tgalal/yowsup/issues/1861#issuecomment-264792842

**Comment by krdsx** [comment]
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by krdsx** [comment]
thank you. solved change
yowsup/env/env_s40.py

old version
_VERSION = "2.16.9"

new version
_VERSION = "2.16.11"

**Comment by rafaelsilverioit** [comment]
@krdsx Could you please close this issue?

**Comment by magaro98** [comment]
Para solucionar el problema de bad_token en el archivo env_s40. py en el campo TOKEN_STRING debes reemplazar {phone} por tu numero de telefono 
ej: PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194472015L{phone}
PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194472015L{573001234567}
