### ISSUE TITLE
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"stale"}

### ISSUE THREAD

**Issue by moh1122** [tgalal/yowsup#1872]
I requested the code and i got it from whatsapp with this command
sudo yowsup-cli registration --requestcode sms --phone 49XXXXXXXXXX --cc 49 --mcc XXX --mnc XX
Now I want to register it with this command:
sudo yowsup-cli registration --register XXXXXX --phone 49XXXXXXXXXX --cc 49
but I get this error any clue ?
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"stale"}

status: fail
reason: stale

**Comment by jlguardi** [comment]
Your code has expired! Don't spent too much time from sms to registering process.
