### ISSUE TITLE
How to receive and save Pictures automatically

### ISSUE THREAD

**Issue by pbpxnwe** [tgalal/yowsup#1874]
Hello Github-Community,

im trying to make a present for my grandma. she should receive all pictures from whatsapp. she dont need to read anything or send anything. 
we put the raspi1 with osmc on an led-tv to make a 24/7 slideshow.

but my problems are:
how do i get yowsup to download the pictures automatically to an folder? 

thank you very much for helping :)

future problems: 
yawsup login every 4-12 hours automatically
yawsup autostart in the background

**Comment by viktor-sc** [comment]
Hi,
could you get it working?

**Comment by tgalal** [comment]
[mediasink demo](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/mediasink/layer.py)
