### ISSUE TITLE
status: fail reason: old_version

### ISSUE THREAD

**Issue by isIGOLman** [tgalal/yowsup#1875]
I tryed to register a number with this:
$ yowsup-cli registration --requestcode sms --phone 39329xxxxxxxx --cc 39 --mcc 222 --mnc 88

But i always get this:

yowsup-cli v2.0.15
yowsup v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

I tryed to solve with this: https://github.com/tgalal/yowsup/issues/1861
But it doesn't work for me! 
Anyone can help?

**Comment by JanHL** [comment]
Hi, I had the same issue like you.
This worked for me: https://github.com/jlguardi/yowsup/commit/6ea1319ec897f60962c66e0391f9eeccb4e7ab70

**Comment by isIGOLman** [comment]
Do i just need to change those 2 strings? (If yes, tryed it and it didn't work)

**Comment by jlguardi** [comment]
@isIGOLman have you checked the installation?
In debug logs you can see the used version.
