### ISSUE TITLE
Disconnected: Connection closed

### ISSUE THREAD

**Issue by isIGOLman** [tgalal/yowsup#1876]
I registered my number and got a password, then i try to do this:
$ yowsup-cli demos -d -c yowsup-cli.config -y

Then i get in the Yowsup cli Client
And i try with:
/login 39xxxxxxxx p7ukxxxxxxxxxxxxxxxxxxx=

And i always get:
general: Disconnected: Connection closed

**Comment by jlguardi** [comment]
Read other issues!
