### ISSUE TITLE
send video using the cli "/video         send"

### ISSUE THREAD

**Issue by jegue** [tgalal/yowsup#1879]
got this erro in a lot of mp4 files! Ping Timeout and then general: Disconnected: Ping Timeout

connected]:DEBUG:yowsup.layers.logger.layer:rx:
iq type="result" from="s.whatsapp.net" id="1"
media url="https://mmi499.whatsapp.net/u/3Iq02yGU5bKS8OJksEKoeLkCHE4ABUQlpOQm2g/As4TMMlNeG-Yd0O0xJ68VsicZwmm73_FaYqr6L_TCdVN" ip="169.55.74.46">
</media>
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="2">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 2
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Ping Timeout

thanks for your help.

**Comment by jegue** [comment]
cool

**Comment by xwanyiri** [comment]
Did you ever get to resolve this? Sorry to wake up sleeping ones

**Comment by jlguardi** [comment]
Without wa2.0 protocol (noise protocol) it makes no sense working on media or other issues. Yowsup will die in 20 days!!!

**Comment by Frzifus** [comment]
> Yowsup will die in 20 days!!!

Why?
