### ISSUE TITLE
Problems with Request Code

### ISSUE THREAD

**Issue by fclesio** [tgalal/yowsup#1880]
Hi!

I'm trying to register my phone using the script below:

`yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXXX --cc 55 --mcc 123 --mnc 456`

After executing this script returns this message:

```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
```

Do you guys know what I doing wrong?

**Comment by ShrekVoid** [comment]
You need to upgrade the values in env_s40.py - to 2.16.11 and PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}
Recompile and enjoy

**Comment by munknex** [comment]
Not working for me

**Comment by vityapro** [comment]
@fclesio I think you may close issue
