### ISSUE TITLE
Registration: {"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by munknex** [tgalal/yowsup#1885]
Can not register. Please help. 
Tried to change values to
```
2.16.11
PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}
```

Don't work.

**Comment by jacobSingh** [comment]
I tried this, got the same error with -E android

**Comment by Mailaender** [comment]
Same here with
```
yowsup-cli  v2.0.15
yowsup      v2.5.0
```

**Comment by sebastianancho** [comment]
Hi,

I solved issue changin env_s40.py whith this values:
_VERSION = "2.16.11"
_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    
My Version:
yowsup-cli  v2.0.15
yowsup      v2.5.0

Do not forget to recompile!

**Comment by munknex** [comment]
@sebastianancho, as I wrote in the header, I've already tried these values. Same result. 

> Do not forget to recompile!
What do you mean? Tried removing *.pyc files. Nothing changed.

**Comment by munknex** [comment]
> Do not forget to recompile!

**Thanks!** Running ./setup.py install is what I needed!

**Comment by sylvainblot** [comment]
same here issue fixed

**Comment by MarcoBuster** [comment]
@sebastianancho where is the file env_s40.py?

**Comment by Mailaender** [comment]
@MarcoBuster See my patch at https://github.com/tgalal/yowsup/issues/1889 or install https://software.opensuse.org/package/python-yowsup2 which is already patched.

**Comment by MarcoBuster** [comment]
@Mailaender Thanks!

**Comment by netofontess** [comment]
Hi,

I change the file, but how i recompile?

Tk's!

**Comment by MarcoBuster** [comment]
@netofontess `python setup.py install`

**Comment by netofontess** [comment]
Don't exist the setup.py

**Comment by MarcoBuster** [comment]
@netofontess What? Do `cd yowsup-master`and `python setup.py install`

**Comment by netofontess** [comment]
@MarcoBuster The folder is in '/usr/lib/python2.6/site-packages/yowsup'
But dont have any file call setup.py... I tried find by the name.

**Comment by MarcoBuster** [comment]
@netofontess Idk. Try to download from GitHub the repo, unzip it, edit the file env_s40.py, `cd yowsup-master` and `python setup.py install`.

**Comment by netofontess** [comment]
@MarcoBuster I try download from GitHub and now i find the setup.py....
But now I received this message when command 'yowsup-cli registration':
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'yowsup-cli'

**Comment by netofontess** [comment]
I deleted all the yowsup folders and ran the setup.py command again. It worked!

Thank's!

**Comment by b10w60** [comment]
Did all that, still not working for me.

**Comment by b10w60** [comment]
Still not working.

**Comment by vityapro** [comment]
@munknex please close issue

**Comment by Jan2220** [comment]
status: fail
reason: bad_token

Nothing worked.

**Comment by Neurotec** [comment]
thanks work's

**Comment by umeshrege** [comment]
thanks...it works!

**Comment by handflucht** [comment]
Thank you @sebastianancho for providing these values. Can you please inform me about the necessary steps to these values, so the next time it breaks we can fix it on our own?

**Comment by eldimar** [comment]
No work, version 2.6.19
yowsup-cli registration --requestcode sms --phone 5561XXXXX --cc 55 --mcc 724 --mnc 05
INFO:yowsup.common.http.warequest:{"login":"5561XXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5561XXXXXXX

**Comment by Aranad** [comment]
Doh! I did ./setup.py build but not install! Working with 2.6.11 :-)

**Comment by eldimar** [comment]
@Aranad No work, How do I solve it? Which file should I edit?

**Comment by Aranad** [comment]
@eldimar The file is env/env_s40.py you set the _VERSION to "2.16.11" and "_TOKEN_STRING" to "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}". Then you must run ./setup.py build and ./setup.py/install and then try registration again.

**Comment by eldimar** [comment]
@Aranad Thanks,  working perfectly!

**Comment by Aranad** [comment]
@eldimar I've registered a number on the network, but I can't get pidgin to connect - I'm guessing its because whatsapp.purple's not being developed anymore - do you know of any alternative clients?

**Comment by giuseppepaolo** [comment]
@Aranad No work registration in my environment with these Token and Version. 

Show the error: BAD_TOKEN. This problem occurred after yesterday. In another days, that's ok.

Can you test a new registration with env_S40 in Version 2.16.11 please?

**Comment by Aranad** [comment]
I don't have yowsup installed any more, can you show me the exact token string you have?

**Comment by giuseppepaolo** [comment]
Sure:

```
    _VERSION = "2.16.11"
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
```

**Comment by Aranad** [comment]
Strange, I never got a bad token error with that :-/

**Comment by giuseppepaolo** [comment]
@aranad, with yowsup from tgalal its ok. But with yowsup fork jlguardi no. Thanks.

**Comment by Rahulyennu** [comment]
Did all the above it doesnt work.

**Comment by ravesingh1983** [comment]
Done any one know the token for 2.17 version as 2.16 is giving old version error

**Comment by 83lipe** [comment]
@Aranad i use ./setup.py but show "bash: ./setup.py: No such file or directory"

**Comment by DavidPrada23** [comment]
Help!
Failed, reason old_version. Checking for a new token..
Traceback (most recent call last):
File "yowsup-cli", line 274, in <module>
 result = wc.send()
File "/home/pi/yowsup/src/Yowsup/Registration/v2/coderequest.py", line 75, in send
 parsed = jParser.parse(tokenData.decode(), pvars)
File "/home/pi/yowsup/src/Yowsup/common/Http/waresponseparser.py", line 132, in parse
 d = json.loads(jsondata)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
 return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
 raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by kurokirasama** [comment]
hello, i installed yowsup-cli with `apt` on ubuntu 18.04. Where is this `env_s40.py` file located?
