### ISSUE TITLE
Add a contact

### ISSUE THREAD

**Issue by JoCar10** [tgalal/yowsup#1886]
Hello!

I would like to know how contacts are added using the command line client. I already wrote / help but I do not know which command I have to write.

Regards.

**Comment by mgp25** [comment]
There is no such thing as add contact in WhatsApp, what it is done instead is a `Sync`, this is stored in server side, it is used by Facebook & WhatsApp to detect and analyze people and trying to figure who they are, they match numbers to facebook profiles: more data is equal to more proffit, it also works as anti-spam measures.

Also, contact list is stored locally in the device, you can use any database to keep a track of your contact.

Before sending a message you always need to sync the contact, but once. If the other user started the conversation, there is no need to sync it.

All information can be found in the wiki: https://github.com/tgalal/yowsup/wiki/Command-line-client

And just by spending 1 minute of your life in the top search bar you will foind solutions, like the one i just found:
```
./yowsup-cli --config num --sync <number>
```

There is more info in closed issues + wiki

Regards

**Comment by KyleJr** [comment]
Additional information on top of mgp25's response. If you want to add contacts, you would need to create your own contact list database, then you can sync only numbers from that database.

The question you should be asking is, how to create a database preferably through mysql or a python dictionary.

**Comment by vityapro** [comment]
@JoCar10 i think you may close your issue
