### ISSUE TITLE
can´´t send messages

### ISSUE THREAD

**Issue by jabertwo** [tgalal/yowsup#1887]
after some time i was able to register to yowsup, but i can´t find a config file.
when i try to use the login command
 ` yowsup-cli demos --yowsup --login phone:b64password`
i get
 `Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))
`
can someone tell me how to create a config file or use the login command?

Merry Christmas from Germany
Jannik

**Comment by Domeax** [comment]
Hallo Jannik,
die Config musst du selber erstellen.
Alternativ kannst du aber den Parameter für den Login benutzen.

yowsup-cli demos -s (RUFNUMMER) -l (DEINE RUFNUMMER):(DEIN PASSWORT) (TEXT)

Mit diesem Befehl sollte es funktionieren. Bei der Registrierung hast du (DEIN PASSWORT) erhalten, ich hoffe du hast es behalten. Sonst kannst du dich selbstverständlich erneut registrieren und ein neues Passwort erhalten.
