### ISSUE TITLE
Download PDF in document_message

### ISSUE THREAD

**Issue by pabloruan0710** [tgalal/yowsup#1890]
somebody please help me!!! I need download pdf, and receive event 

`document_message {
 url: "https://mme.whatsapp.net/d/HnA4jAvzWcr1HrlZJUMvSFhj2a0/AkTzF0y-jF6LXG_SpT9w-MG7hRsM9SToKnLor5-t3ryx.enc"
 mimeType: "application/pdf"
 title: "Certificado_Palestrante.pdf"
 file_sha256: "\004\021fa\212+\237\021&,\032\315\373\312\251\313\216\001\032\206\0071\007\221));\035!\363Q\331"
 file_length: 433996
media_key: "\365\263\202\271i\325\273m\021\2363\311\225\307\310\333\325\346\330y\356\357\020\257<\\nym0\236\300"
 }`

but, i have error

**Comment by brunodeandrade** [comment]
Need help with this too

**Comment by tgalal** [comment]
2fe65132257eb37c2dfbe82de7bd93a1707c276e
