### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by netofontess** [tgalal/yowsup#1893]
Hi!

I get this error when I try to send a message:
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
/usr/lib/python2.6/site-packages/yowsup2-2.5.0-py2.6.egg/yowsup/demos/sendclient/stack.py:33: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  print("Authentication Error: %s" % e.message)
Authentication Error: not-authorized

I tried re-registering and updating the password, but the error continues

Can someone help me?

Thank you!

Regards,

Neto

**Comment by mustekito** [comment]
I solved it following these steps: https://github.com/tgalal/yowsup/issues/1885#issuecomment-269139157

**Comment by vityapro** [comment]
@netofontess if your issue resolved, please close it

**Comment by netofontess** [comment]
I solved. In my country a new digit was implemented recently, but I had to remove it to work.

Tk's!
