### ISSUE TITLE
	DEBUG:yowsup.env.env:Env not set, setting it to s40

### ISSUE THREAD

**Issue by elidrissizack** [tgalal/yowsup#1894]
sudo python yowsup-cli registration --requestcode sms --phone 212067xxxxxxxx --cc 212 --mcc 604 --mnc 00 -d
	yowsup-cli  v2.0.15
	yowsup      v2.5.0

	Copyright (c) 2012-2016 Tarek Galal
	http://www.openwhatsapp.org

	This software is provided free of charge. Copying and redistribution is
	encouraged.

	If you appreciate this software and you would like to support future
	development please consider donating:
	http://openwhatsapp.org/yowsup/donate

	DEBUG:yowsup.env.env:Env not set, setting it to s40
	DEBUG:yowsup.env.env:Current env changed to s40 
	DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.9 S40Version/14.26 Device/Nokia-302'}
	DEBUG:yowsup.common.http.warequest:cc=212&in=067xxxxxxxx&lc=GB&lg=en&sim_mcc=604&sim_mnc=000&mcc=604&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5368&rchash=14888c77067039a93416f7cd723b6e6be7746fcc34c91a5c9ef99fd85ae643b9&anhash=%C0Z%D7%2C%90%AD%A7%D93%92q%11%AC%E8%7B%DE%1F%ED%86%A4&extexist=1&extstate=1&token=2bf1434b897091aa26b799e93e90c58f&id=%8C%3C%7BBEqb%D8h%BDv%0E%CE%0FMX%8F%3Fe%5B
	DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
	DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=212&in=067xxxxxxxx&lc=GB&lg=en&sim_mcc=604&sim_mnc=000&mcc=604&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5368&rchash=14888c77067039a93416f7cd723b6e6be7746fcc34c91a5c9ef99fd85ae643b9&anhash=%C0Z%D7%2C%90%AD%A7%D93%92q%11%AC%E8%7B%DE%1F%ED%86%A4&extexist=1&extstate=1&token=2bf1434b897091aa26b799e93e90c58f&id=%8C%3C%7BBEqb%D8h%BDv%0E%CE%0FMX%8F%3Fe%5B
	INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

	status: fail
	reason: old_version
######################
 python -V
Python 2.7.12

**Comment by Domeax** [comment]
Add -E android to your terminal command. Standard s40 won't work for registration.
But for a program with layer.py and run.py you have to change the standard env to s40.

**Comment by elidrissizack** [comment]
i have changed in env.py  to android and s40 but i have again the same probleme 
env_s40.py ;
_VERSION = "2.16.9"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"
