### ISSUE TITLE
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by yaolau** [tgalal/yowsup#1898]
the newest version of android  is 2.16.396 , the error like INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.0

please help, is that yowsup still can use now?

**Comment by yaolau** [comment]
how to get the MD5_code with the version number?!

**Comment by languitar** [comment]
#1889 will resolve this for registration when using the default nokia environment.

**Comment by b10w60** [comment]
Well, no it doesnt. At least not for me. Sorry. :/

**Comment by vityapro** [comment]
@b10w60 , do you switch youwsup-cli for using s40 version, not android?

**Comment by b10w60** [comment]
@vityapro Yes, i do. `-E s40`

**Comment by vityapro** [comment]
@b10w60 You use demo or full version of yowsup ?

**Comment by b10w60** [comment]
Full.

**Comment by vityapro** [comment]
Can you give exemple of comand what you use to run yowsup cli?

**Comment by b10w60** [comment]
`yowsup-cli -E s40 registration -c config.yowsup --requestcode sms`

**Comment by vityapro** [comment]
But command must be like that:
yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456
why you use this command?

**Comment by MrTuTu** [comment]
Hi,
I have the same problem.
I tested without -E  or with and value s40 or android
An example with debug:
./yowsup-cli registration -d -E android --requestcode sms --phone 41XXXXXXXX --cc 41 --mcc 228 --mnc 02
DEBUG:yowsup.env.env:Current env changed to android 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=41&in=XXXXXXXX&lc=GB&lg=en&sim_mcc=228&sim_mnc=002&mcc=228&mnc=002&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=3470&rchash=a55e7e705a9600b568e8d4edb2165d3e6fc2742176f6c2ccb207e344d5f1e5a4&anhash=%CD%B6k%FE%D6%C4+%80%F6a%B1%DAx%906-%B9mC%CD&extexist=1&extstate=1&token=AOeoMAe0%2FWOgSKxPJwlIVVUuO6U%3D&id=%E5h%BC%F1%ACN%EA%19%D9i%ECD%1As%12Dhz%B2o
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=41&in=XXXXXXXX&lc=GB&lg=en&sim_mcc=228&sim_mnc=002&mcc=228&mnc=002&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=3470&rchash=a55e7e705a9600b568e8d4edb2165d3e6fc2742176f6c2ccb207e344d5f1e5a4&anhash=%CD%B6k%FE%D6%C4+%80%F6a%B1%DAx%906-%B9mC%CD&extexist=1&extstate=1&token=AOeoMAe0%2FWOgSKxPJwlIVVUuO6U%3D&id=%E5h%BC%F1%ACN%EA%19%D9i%ECD%1As%12Dhz%B2o
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by vityapro** [comment]
@MrTuTu And you update constant to last version to ?

**Comment by MrTuTu** [comment]
@vityapro  Yes. I created a new virtualenv and did a clone of the github repository.

**Comment by MrTuTu** [comment]
ohhh. I didn't see the post from languitar. After an update of env_s40.py, it worked for me.
Thank you

**Comment by vityapro** [comment]
Your welcome.

**Comment by Bodasia** [comment]
@yaolau if your issue resolved, please close it

**Comment by b10w60** [comment]
@vityapro Oh my god, it worked with your command. My one was from a german website. Was an older article, maybe outdated.
It worked and i thank you very much!

**Comment by yaolau** [comment]
yowsup-cli registration --env s40 --requestcode sms --phone 86xxxxxxxxxxx --cc 86 --mcc 460 --mnc 01 --debug

it works!, thx all

**Comment by DavidPrada23** [comment]
Help!
Failed, reason old_version. Checking for a new token..
Traceback (most recent call last):
File "yowsup-cli", line 274, in <module>
 result = wc.send()
File "/home/pi/yowsup/src/Yowsup/Registration/v2/coderequest.py", line 75, in send
 parsed = jParser.parse(tokenData.decode(), pvars)
File "/home/pi/yowsup/src/Yowsup/common/Http/waresponseparser.py", line 132, in parse
 d = json.loads(jsondata)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
 return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
 raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ByzDraft** [comment]
Please can someone help me? I have the same problem wit the same error. I use an Apple. Can this be the problem?

**Comment by danielsouzasp** [comment]
For me, it worked only after seting the lastest Whatsapp version at yowsup/env/env_android.py
_VERSION = "2.20.142"
