### ISSUE TITLE
Receiving Audio Message

### ISSUE THREAD

**Issue by cr41n** [tgalal/yowsup#1899]
Hello, im getting an error when im receiving an audio message in yowsup cli.

at the end something like "layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])..."

Is it possible to receive audio messages?

Thanks

**Comment by vityapro** [comment]
Unfortunately, in yowsup-2 resiving of media message not finished yet, but it have sum helpfuk function that help you to finish it.

**Comment by Bodasia** [comment]
you can try https://github.com/jlguardi/yowsup from @jlguardi

**Comment by cr41n** [comment]
ill give it a try, thanks

**Comment by Bodasia** [comment]
@cr41n please close issue

**Comment by cr41n** [comment]
there is a problem with the branch from @jlguardi 

when i want to login in the cli i get the following output:

[offline]:/login xxxxxx PASSWORD
general: Disconnected: Connection Closed
[offline]:
[offline]:

The original branch from @tgalal is working, so the number isnt blocked.
