### ISSUE TITLE
Branch @jlguardi login error

### ISSUE THREAD

**Issue by cr41n** [tgalal/yowsup#1900]
there is a problem with the branch from @jlguardi

when i want to login in the cli i get the following output:

[offline]:/login xxxxxx PASSWORD
general: Disconnected: Connection Closed
[offline]:
[offline]:

The original branch from @tgalal is working, so the number isnt blocked and the login with number and password is ok

**Comment by RupinC** [comment]
Experiencing the same error in that very branch

**Comment by CarlosLannister** [comment]
Same error here
