### ISSUE TITLE
yowsup-cli window 7 is not recognize

### ISSUE THREAD

**Issue by jemjov** [tgalal/yowsup#1902]
anyone can help me?
why i cant run yowsup-cli on windows7 its always say that 'yowsup-cli' is not recognized as an internal or external command,operable program or batch file.'

ty b4

**Comment by Bodasia** [comment]
Please try to add yowsup-cli to path constant

**Comment by jemjov** [comment]
thanks for reply @Bodasia 
i already did it, and im still get that error
even i try to run yowpsup-cli inside yosup-master its still get same output

**Comment by raviranjankarn** [comment]
I am also getting the error:'yowsup-cli' is not recognized as an internal or external command,
operable program or batch file.

@Bodasia: What to add in Path?

**Comment by joko3ana** [comment]
run yowpsup-cli inside yosup-master folder
and run with 
try to run 
python yowsup-cli

**Comment by Krprashant94** [comment]
What is the path for yowsup-cli. I am facing same problem

**Comment by mrkhanakia** [comment]
1. Path of yousub cli C:\Python27\Scripts
2. cd to C:\Python27\Scripts via command prompt
3. Run it like **python yowsup-cli**

Happy Coding !!!!
[Aman Khanakia](https://www.linkedin.com/in/khanakia/)

**Comment by joaqhoc** [comment]
Remember rename this file yowsup-cli for yowsup-cli.py 

👍

**Comment by viratvarma** [comment]
could you please any one help me.
how to install yowsup in windows if any one knows please give me step by step process.

**Comment by setanallas** [comment]
@viratvarma you can read it in readme

https://github.com/tgalal/yowsup
