### ISSUE TITLE
not authorized error

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1906]
I have 2 wa bots in my wlan runnning.
By night my wa bots turned offline and at the morning there was this not authorized error.

When i try to register again i get a code but the code isn't working. I tested the code in the demo client and in a run.py/layer.py program but it shows me the not authorized error agin and again.

For registration i am using the android env with version 2.16.148
and for running an instance i am using the s40 env with version 2.16.9.

**Comment by Domeax** [comment]
I had to update the env_s40.py. :)

**Comment by mbroeken** [comment]
I have exactly the same issue, looks like whatsapp is blocking s40 now.

When I send a message, I currently get (as from this morning)
root@domoticz:/home/mbroeken/yowsup# yowsup-cli demos -c /home/xxx/yowsup/config -s 31xxxxxxxxx "bericht"
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

**Authentication Error: not-authorized**

when I try to register again:
INFO:yowsup.common.http.warequest:{"login":"31xxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by Domeax** [comment]
I think you have to use the s40 version from the pull requests.
I hope this can fix the problem, i am using the code from the pull request.
And make sure you are using the s40 version and not the android with
changing the standard env in ../env/env.py

**Comment by mbroeken** [comment]
Looks like it worked

Had to recompile after changing the code

**Comment by Seiler1983** [comment]
I habe this problem as well.
Can somebody explane what exacly do i have to change or how i have to recompile...

**Comment by stefanogalizia** [comment]
I have the same problem and not understood what to modify.

**Comment by mbroeken** [comment]
It was a faily simple process
change your yowsup/yowsup/env/env_s40.py to look like the code below:

    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

after that, recomile with the command below:
./setup.py install

yowsup should be working again.

**Comment by stefanogalizia** [comment]
i can confirm it works! thanks a lot

**Comment by yosefmachluf2011** [comment]
thats true.. it works  BUT 
I am using  2 accounts for half a year, this update made my acounts UNAUTHORIZED!! so i registered them again and it worked very good for few hours ,it looked like all the functions work and the login was good and everything, BUT then again it became UNAUTHORIZED, I logged in using debug mode and saw it got BLOCKED !!!

**Comment by mbroeken** [comment]
You get blocked when sending more than 50 messages per day (I have been reading that somewhere, don't know if it's true...

never use your own mobile phone, use a prepay number for this

**Comment by yosefmachluf2011** [comment]
i didnt send any messages ,i think they changed something in this version in addition to the timestamp and the version change. i put some console printing and saw that after loggin i recive 

Login success. Next password:
GToYWynY.......c1Mj7bKZi2I=

which look very similiar the password i put for the credentials.
but it wont work if ill try to replace it.

i am using this version for 3 days and got blocked..
i used the older versions for 6 months and never got blocked..

something changed.

**Comment by mbroeken** [comment]
Weird one,

I'm using yowsup for 7 months now in my domoticz environment, 
never got blocked. Changed the version and things got working again sunday.

**Comment by stefanogalizia** [comment]
same here, using it and never get blocked

**Comment by yosefmachluf2011** [comment]
thats what i am saying... i never got block before.. but now things seems to be different :(

**Comment by cjaburto** [comment]
i had used it for 3 months and send over 100 messages, it works flawlessly until yesterday when update the version and token. maybe its getting massive.

**Comment by rudimuc** [comment]
I changed the Version to _VERSION = "2.16.11" - like mbroeken said...
It works well, thank you very much!

**Comment by ace02000** [comment]
Thanks for your help @mbroeken =)

**Comment by YUSTINUS80** [comment]
I Already change the default to s40 and the version, but still get error: Login fail and Not authorized.
Please advice for this problem.

**Comment by jlguardi** [comment]
Are you using version s40 2.16.11?‎ Have you instaled the change (python setup.py install)?

**Comment by YUSTINUS80** [comment]
@jlguardi : yes, i already compiled. Any other matter that i have to change?
![image](https://cloud.githubusercontent.com/assets/24423338/22166846/b4743ae4-df95-11e6-8b5e-f620355ed396.png)

**Comment by YUSTINUS80** [comment]
@jlguardi : yes, i already compiled  (python setup.py install). Any other matter that i have to change?
![image](https://cloud.githubusercontent.com/assets/24423338/22167005/89c4c416-df96-11e6-8472-0ac3db7385cf.png)

**Comment by Kurill** [comment]
have same problem, can some body help?

**Comment by MarcelS04** [comment]
today it stoped working for me with 2.16.11 env

is there any kind of instruction how to get those token for the env?

**Comment by jlguardi** [comment]
@MarcelS04 Are you sure? I've tested on my computer and worked like a charm. Probably you started with other env file.

**Comment by MarcelS04** [comment]
@jlguardi Yes I tried with this

`_VERSION = "2.16.11"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "302"
_MANUFACTURER = "Nokia"
_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"`

and ran

`sudo python setup.py install`

but when I try /L I get

`[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized`

**Comment by jlguardi** [comment]
@MarcelS04 Good new for us: S40 env is still working. Bad news for you: your number was banned by whatsapp.

**Comment by Jayanthi-D** [comment]
[offline]:/L general: Login Failed, reason: not-authorized Auth Error, reason not-authorized

Is this denoting that my number is banned??

**Comment by ashishradadia** [comment]
Today i send only 4 message from s40 - 2.6.11 
it's blocked

**Comment by vinicius-ianni** [comment]
Today i send only 3 messages from s40 - 2.16.11 and i got this when i tried to send 4th:

Authentication Error: not-authorized

this means my number was bloqued ? 
or i must try recompile / install and try again ?

**Comment by ashishradadia** [comment]
From this version we block my 3 number
And after this it's don't work

**Comment by thmendes** [comment]
After 4k msgs in 2 weeks I was blocked.

**Comment by jegue** [comment]
after some 7 months work fine and no unnormal  used i got block today!
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized
See you  soon yowsup new sim card...
