### ISSUE TITLE
When yowsup receive a message: WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId

### ISSUE THREAD

**Issue by Jan2220** [tgalal/yowsup#1910]
Hi,
When my yoqsup receives a message and i log me into it i get secondly this error message:
`WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 49##########, going to send a retry`

how can i fix this? i tried to disable encryption but that didn´t work

~Jan (Jan2220)

**Comment by Domeax** [comment]
You can use the send demo to send a message to the number. Then this should be fixed.
Usually you can wait 3-20 minutes and yowsup should restore keys.

And maybe set the base encoding in your python program to utf-8.

**Comment by althafas** [comment]
got any update?
