### ISSUE TITLE
[Question] integrated sending api function

### ISSUE THREAD

**Issue by georg90** [tgalal/yowsup#1913]
Hi!

I am using my whatsapp bot for while now. I can text the bot and it will reply according to the defined logic. 

Now I want to implement an "API-like" function, where I can send any given `message` and `number` to the running bot (python script with `run.py` and `layer.py`) while keep listening for incoming messages. I tried with unix sockets but I think this might be a bit overkill, since I only need a function which is listening for input from another script on the same machine.

Anybody has a few topics which might suit this issue? I am happy to help myself, but I'm short of an idea to start off.. Is there already an implementation for an (rest?) API?

Thanks a lot!

**Comment by Domeax** [comment]
I got the idea of using the send demo while the listener is running.
Do you think this can ban my number from WhatsApp?

**Comment by georg90** [comment]
In this scenario the listener will disconnect from the whatsapp network & the send demo will send the message.

**Comment by georg90** [comment]
I don't think the appropriate way of integrating sending and receiving functionality is to restart yowsup every time after I sent something.

I'm confident there is a way to implement a method which accepts some parameters and send them in a message. But the tricky part is to implement some kind of API which you can call from another script etc.

**Comment by georg90** [comment]
I found this https://github.com/EliasKotlyar/yowsup-microservice - but it's using the yowsup demo client. Any way to integrate an small API to the layer.py/run.py example? 
My issue is to run the yowsup loop (and keep receiving) but also run a "listening" loop which provides a send-API to send messages.
