### ISSUE TITLE
old_version fail

### ISSUE THREAD

**Issue by derevandal** [tgalal/yowsup#1920]
Hi, i'm getting an error.
```bash
derevandal@DEREVANDAL-W10:~/yowsup/build$ yowsup-cli registration --requestcode sms --phone x --cc y
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"x","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: x
````
I read this [pull request](https://github.com/tgalal/yowsup/pull/1725) and I couldn't resolve.
Could anyone help me?
I'm try use bash interface in windows 10, windows 10 native and ubuntu 16.04.

**Comment by juanefren** [comment]
Same for me, firts installed it via pip, then used "pip uninstall youwsup2" and installed from the repo with "python setup.py install"

**Comment by juanefren** [comment]
I had same problem, SMS sent after changed this file to this values:

https://github.com/jlguardi/yowsup/blob/master/yowsup/env/env_s40.py

**Comment by thmendes** [comment]
Did you build/install setup.py again?

**Comment by DagoW** [comment]
Hi Juan and all.
I used the (two) modified parameters in env_s40.py.
That fixed the "reason":"old_version", but now I get "reason":"incorrect" and "reason":"no_routes".
Is there anything I can do to solve this?
Everything is up to date and yowsup from GIT repository today (Feb,10th)

```
./yowsup-cli registration --requestcode sms --phone 150xxx504xx --cc 1 --mcc 310 --mnc 150
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"150xxx504xx","status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"login":"150xxx504xx","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
login: 150xxx504xx

```

**Comment by DagoW** [comment]
After reading other posts, I ran 
`./setup.py build`
and then registered a different number. It worked! Sending and receiving messages also works.
In summary, I used these parameters in env_s40.py.

```
    _VERSION = "2.16.11"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
```
and I registered an Israeli number, so the command line arguments were not as shown in
my previous post.

**Comment by Aranad** [comment]
I'm getting the old_version problem too, tried the changes above, rebuilt, still got the error, tried a different number still got error :-(

**Comment by jacargentina** [comment]
Getting this too. @Randl How to do got those "magic numbers" from #1725 ?

**Comment by Randl** [comment]
See https://github.com/tgalal/yowsup/pull/1726

**Comment by Aranad** [comment]
No I still get the same problem after using the "magic numbers" from whatsapp_scratch and rebuilding :-(

**Comment by Aranad** [comment]
I have 2.16.11 with "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

**Comment by tgalal** [comment]
fixed
