### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by AragurDEV** [tgalal/yowsup#1921]
Hey,
today I registered my number and configured yowsup. After tons of testing and coding I recognized that I can't connect to my account any more. -> Account blocked

So my Question is, if this project is still alive. And if I should get me a other number and test it again?
(I only send ~10 messages back and forth)

Thanks for you answers :+1:

**Comment by eledumen** [comment]
I'm not sure it stills alive, but  whatsapp check receiver contacts to check for spammers and block them.

**Comment by jlguardi** [comment]
I've it working and my numbers aren't banned. It 's still working!!!

**Comment by ashishradadia** [comment]
my number is also blocked ,
it's unblock or not 
can we use android instead of S40

**Comment by AragurDEV** [comment]
I think I can now close this issue.
Tested again with an other number and I didn't got the ban.
At my first attempt I mixed the WhatsApp versions.
