### ISSUE TITLE
Howto send a document message?

### ISSUE THREAD

**Issue by gemx** [tgalal/yowsup#1922]
I succeeded in receiving all types of messages and sending all types of messages except a document.
A pdf in particular.
After uploading i get a "BAD Request" return code.
Anybody got it running?

**Comment by brunodeandrade** [comment]
Need help with this too!

**Comment by charanjit-singh** [comment]
I too need help..
Tgalal...
help

**Comment by tgalal** [comment]
see mediasink demo

**Comment by tgalal** [comment]
2fe65132257eb37c2dfbe82de7bd93a1707c276e
