### ISSUE TITLE
Banned after get Notification

### ISSUE THREAD

**Issue by Bodasia** [tgalal/yowsup#1924]
Hello,
faced with the issues

after login in yowsup i'm get in console yowsup-cli
```
Notification: Notification
From: 967700516397@s.whatsapp.net
Type: status
```
or
```
Notification: Notification
From: 967735460792@s.whatsapp.net
Type: picture
```
after that any action of mine, for example: `/profile setStatus 'bla bla'`
resulting in an account ban, can somebody help, I'm lost over 5 numbers.

P.S.: Sorry for my english.
Thanks.

**Comment by jlguardi** [comment]
You'll get a notification status and picture whenever a someone bans you (report as spam or ban you).
You can also get status/picture notification in other cases but always when someone blocks your number.

If you have more than 5-10? people blocking you in a short period you will be banned by whatsapp.

So you are always getting this notifica‎tions before number banning.

**Comment by Bodasia** [comment]
I'm know abaut this, but this number did not write any message nobody, this account only sync whith this numbers, so nowbody can to buned it manualy

**Comment by Bodasia** [comment]
Maybe i need add getting status and picture on this notification in my code?

**Comment by Bodasia** [comment]
@jlguardi if I'm wrong tell me, I will close issues
