### ISSUE TITLE
This project working?

### ISSUE THREAD

**Issue by pogran** [tgalal/yowsup#1928]

**Comment by DagoW** [comment]
Yes, it is working for me. Just today, I did the 2 step registration with SMS via
a direct internet connection and can now send and receive messages with the 
same connection and also via an http_proxy.

I used up-to-date packages
`pip install yowsup2 --upgrade`
and
`git clone https://github.com/tgalal/yowsup.git yowsup2017`
and had to update 2 parameters from here
`wget https://raw.githubusercontent.com/jlguardi/yowsup/master/yowsup/env/env_s40.py`

**Comment by yugalahir** [comment]
can you show live demo for your api ? 

Thanks
