### ISSUE TITLE
reason: b'old_version' status: b'fail'

### ISSUE THREAD

**Issue by tusharsingh8** [tgalal/yowsup#1930]
I am encountering this error while setting up. I am a newbie and any kind of help would do.

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:b'{"login":"*************","status":"fail","reason":"old_version"}\n'
reason: b'old_version'
status: b'fail'
login: b'**************'

**Comment by JoeRu** [comment]
+1 same error:
INFO:yowsup.common.http.warequest:{"login":"49xxx","status":"fail","reason":"old_version"}

**Comment by Gab0** [comment]
Try this: #1889
(modify the file and reinstall yowsup)

**Comment by althafas** [comment]
Any help on this case ?

**Comment by dharampal123** [comment]
Did the below changes and worked for me:

Change in env.py file
set DEFAULT="android"

Change on env_android.py
_MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
_VERSION = "2.18.339"

python setup.py build

python setup.py install

yowsup-cli registration -r sms -m 000 -n 00 -p 91XXXXXXXXXX -C 91 -E android
