### ISSUE TITLE
cancel registration or delete phone number for registration

### ISSUE THREAD

**Issue by ngenglala** [tgalal/yowsup#1932]
please help ASAP...

how to delete the phone number that i register for yowsup...

 i made a huge mistake that i regis the wrong number ..

please please help, how to delete the wrong number, or cancel the regis?? 
or anything else..

thank you, 
regard

**Comment by ngenglala** [comment]
[https://drive.google.com/drive/u/0/my-drive](url)

the ss

**Comment by ngenglala** [comment]
[https://drive.google.com/open?id=0B1w84umGVktEdWNreWJXaWFLcDg](url)

**Comment by mgp25** [comment]
As simple as register the number on other phone

Regards

**Comment by schrisander** [comment]
Kalo mau delete, yang gampang tinggal regis di hp dengan nomor yang sama, trus delete my account di bagian settings.

Kalo dari command line, itu harus login dulu. Pake program demonya dulu aja

yowsup-cli demos --yowsup --login phone:b64password

phone & password yang tadi ada di screenshot (phone nya 62..., passwordnya yang bawahnya)

**Comment by schrisander** [comment]
Trus nanti setelah online dan connected, pake command 

/account delete

**Comment by ngenglala** [comment]
oke tapi sekarang pada saat gw ingin login muncul [https://drive.google.com/open?id=0B1w84umGVktER0xTcGVZVmtiRlU](url)

menurut lu apa yang salah???
