### ISSUE TITLE
Not able to login at all

### ISSUE THREAD

**Issue by sugannathan** [tgalal/yowsup#1935]
I am working with Amazon Alexa to create a Messenger for Whatsapp, by Building an Amazon Echo using Raspberry Pi.I am using the Yowsup library but every time I try to login to send a message,the connection closes.Can someone help me?
![capture](https://cloud.githubusercontent.com/assets/25498690/22542919/339ff99e-e954-11e6-9f0b-b39fd75cdf43.JPG)

**Comment by ngenglala** [comment]
same to me.. but i cant login with this command

yowsup-cli demos --yowsup --login phone:b64password

it give me eror like this one
[https://cloud.githubusercontent.com/assets/25474935/22633507/bb638258-ec54-11e6-9eae-1da88d8bc40a.jpg](url)

**Comment by marcraspi** [comment]
Same to me, 
I have install yowsup on Ubuntu 16.04,
number registed but i can not sign in.

**Comment by fwmarcel** [comment]
I have the same problem. #1939

**Comment by shubhamDTU007** [comment]
@fwmarcel 
@marcraspi 
@ngenglala 
@sugannathan 
Hi..Does anyone able to resolve this error. Pls help!

**Comment by ngenglala** [comment]
@shubhamDTU007  actually ia already can send message using this command
" yowsup-cli demos -c yowsup-cli.config -s phonenumber "text"  "

just like that,
