### ISSUE TITLE
Registration fails with bad_param

### ISSUE THREAD

**Issue by bazajate** [tgalal/yowsup#1936]
Hi guys, i hope you can help me. I'm trying to Register my landline number with voice registration, but i always receive a bad_param: number error...
Below you can find the output from registration debug, my config file looks like this:

cc=43
phone=43316992023
id=0000000000
password=

yowsup-cli  v2.0.15
yowsup      v2.5.0

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.11 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=43&in=316992023&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=voice&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2748&rchash=ad5d3ec6eaaca5ae237fe9c7adb7f000a1a80fbb7eef277b2f2af3b56ab4359e&anhash=%95M%CA%D4%82%21%7Bm%7D%EC%F6g%3E%3Ei%D6Sc%5B%87&extexist=1&extstate=1&token=1549a4c9f9be2845c3c3375d0723db70&id=%AF%D9P%85%3D3%A3%7B%E6%EC%E5%0D%DD%1DS%D74%3A%83-
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=43&in=316992023&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=voice&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=2748&rchash=ad5d3ec6eaaca5ae237fe9c7adb7f000a1a80fbb7eef277b2f2af3b56ab4359e&anhash=%95M%CA%D4%82%21%7Bm%7D%EC%F6g%3E%3Ei%D6Sc%5B%87&extexist=1&extstate=1&token=1549a4c9f9be2845c3c3375d0723db70&id=%AF%D9P%85%3D3%A3%7B%E6%EC%E5%0D%DD%1DS%D74%3A%83-
INFO:yowsup.common.http.warequest:{"login":"43316992023","status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param
login: 43316992023

**Comment by bazajate** [comment]
I tried it with a mobile number, this works fine...

**Comment by jlguardi** [comment]
@bazajate landlines don't work. They are identified by whatsapp servers.
