### ISSUE TITLE
yowsup-cli not answering

### ISSUE THREAD

**Issue by Ziden** [tgalal/yowsup#1937]
Im tryng a simple register to try out the API, however i aint gettin responses. Am i doing something wrong ?

Heres my trial :

`python yowsup-cli registration --requestcode sms --phone (country)(region)(phone) --cc 55 --mcc 724 --mnc 05
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate`

**Comment by DagoW** [comment]
Does it hang forever or does the network connection time out after 30 seconds or so?
