### ISSUE TITLE
Account suspended

### ISSUE THREAD

**Issue by gnovelli** [tgalal/yowsup#1938]
You should say that your library violates WhatsApp TOS and that is really easy to get suspended.
I got suspended just with one message even if I do sync before sending message.
That costed me a lot of time and even some money, that for the sim.

Regards,
Giovanni

**Comment by rafaelsilverioit** [comment]
From the readme:
> ...Yowsup has been used to create an **unofficial WhatsApp client**... [more](https://github.com/tgalal/yowsup/blob/master/README.md)

Also, since Yowsup is distributed under GPLv3+ license:
> For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software. [more](https://github.com/tgalal/yowsup/blob/master/LICENSE#L45)

Lastly, the Yowsup library by itself doesn't violates the WhatsApp TOS as long as you don't do these things:
> ...(e) involve sending illegal or impermissible communications such as bulk messaging, auto-messaging, auto-dialing, and the like; or (f) involve any non-personal use of our Services unless otherwise authorized by us. [more](https://www.whatsapp.com/legal/?l=en#terms-of-service)

**Comment by gnovelli** [comment]
Sorry, I forgot to give you the original info:

Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.

Please uninstall your application and install an authorized version on supported devices from:

www.whatsapp.com/download

Please note that we do not allow use of unofficial clients or jailbroken/rooted (including emulators), and unsupported devices.

To use WhatsApp on your computer, access our website from your computer’s browser. Then, open the app and scan the QR code using the WhatsApp app on your phone (look for WhatsApp Web menu under Settings). WhatsApp can only be installed on your computer if your operating system is Windows 8 (or newer) or Mac OSX 10.9 (or newer). If you are having issues installing WhatsApp on a supported operating system, turn off your anti-virus and try again.

For all other operating systems, you may use WhatsApp on your browser here

Your account will be permanently banned if you continue to violate our Terms of Service, and there will be no possibility of an appeal.
