### ISSUE TITLE
Status: Disconnect & Closed after that Authentication failure

### ISSUE THREAD

**Issue by ngenglala** [tgalal/yowsup#1939]
this is how i install yowsup 2.5 on ubuntu server 14.04 i386 (32 bit) on virtualbox
first enter as super user wth this command
" su " 
then follow the command line right bellow...

1. apt-get install python python-dateutil python-argparse python-dev python-setuptools
and then install
apt-get install libpython2.7-stdlib

2. git clone https://github.com/tgalal/yowsup
( i download it in dir: /home/server )
3. cd yowsup

4. chmod +x setup.py

5. chmod +x yowsup-cli

6. i edit all the file from dir env
(env.py  ,   env_android.py  , env_s40.py)
from env.py=  i change ( DEFAULT = "Android"  )
from env_android.py = i edit MD5 Class & _Version
			MD5 = "1I2weuZmVg+uL50+HXeSJw==" 
			Version = "2.16.328" 
from env_s40.py = i edit the _VERSION
			Version = "2.16.11" 
after all of that

7. install python setup.py install

8. and then i register, using this command
yowsup-cli registration --requestcode sms --phone xxxxxxxx --cc 62 --mcc 510 --mnc 11
(phone number = xxx)
9. i got the code then entr this command
yowsup-cli registration --register yyy-yyy --phone xxxxxxxx --cc 49
(requestcode = yyy)
10. then i got a reply about status, kind, pw, price,price_expiration, currency,cost,login,type,expiration

11. after that i create a conf like this
nano yowsup-cli.conf

12. and then i type this
into that conf
cc=62 #Your country code
phone=xxxxxxxxxxxx #Your phone number
id= #This is where you insert your IMEI number (not needed)
password=blablablablablabla= #your password which you got from registration command

13. after that i want to send a message but always a reply error, status disconnect or status : authentication failure.

here is my command

yowsup-cli demos -l 6212XXXXXX:blablablabla= -s 6298XXXXXX "Hello"

even when i enter yowsup-cli
when i login, always status: disconnected or closed
i using this command to enter yowsup-cli
  yowsup-cli demos -l 6212XXXXXX:blablablabla=
when i enter yowsup-cli
i type this command to login
   /login 6212xxxxx blablabalabla

the result is status disconnected or closed

where is my mistake??
and what command line that i missed???

i say this again. this is a beautifull project and work
If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

thank you very much
best regards

**Comment by fwmarcel** [comment]
Hey. I have the same problem. Can somebody solve it pls

**Comment by ngenglala** [comment]
i think this issue should merge with #1935 ..  but i dont know how

**Comment by xhcardoza** [comment]
Hello, I have the same problem. Please help.

**Comment by ngenglala** [comment]
actually ia already can send message using this command
" yowsup-cli demos -c yowsup-cli.config -s phonenumber "text" "

just like that,

**Comment by ngenglala** [comment]
okey i will close it
