### ISSUE TITLE
Sending messages in a whatsapp group

### ISSUE THREAD

**Issue by claudiorafaels** [tgalal/yowsup#1940]
I send messages one by one, no problem. When I send messages in a whatsapp group I get the following: INFO: yowsup.layers.axolotl.layer_send: Got retry to message 144545433-1, and Axolotl layer has the message. The problems began today.

**Comment by ngenglala** [comment]
what command line that you use to send a message????
@claudiorafaels

**Comment by claudiorafaels** [comment]
Using echo client demo. 
yowsup-cli demos -l number:key -e

**Comment by ngenglala** [comment]
isnt 
yowsup-cli demos -d --yowsup --login xxxx:ccccc 
xxx=phone number
ccc=password

@claudiorafaels
