### ISSUE TITLE
Cron @reboot for execute a python script not working

### ISSUE THREAD

**Issue by Cristopher2** [tgalal/yowsup#1944]
Im trying to run a python script every time that the system is started with Cron but this doesn't seems to work:
@reboot /path/script.py
the script is executable, if i use the * * * * * format of cron its work but no whit @reboot

**Comment by fwmarcel** [comment]
I have a Cron Job with this task. upload ur script here

**Comment by Cristopher2** [comment]
The operative system is raspbian and the scrip works with poplib and email to send and receive emails and trurn some leds on or off. PS: sorry for the code mess it is on development

``#!/usr/bin/env python
# -*- coding: 850 -*-
# -*- coding: utf-8 -*-

import getpass, poplib
import time
import RPi.GPIO as GPIO
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage


GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False) 
GPIO.setup(21,GPIO.OUT)
GPIO.setup(23,GPIO.OUT)
GPIO.setup(24,GPIO.OUT)
GPIO.setup(25,GPIO.OUT)
GPIO.setup(26,GPIO.OUT)

def buzz(pitch, duration):  
	period = 1.0 / pitch     #in physics, the period (sec/cyc) is the inverse of the frequency (cyc/sec)
	delay = period / 2     #calcuate the time for half of the wave
	cycles = int(duration * pitch)   #the number of waves to produce is the duration times the frequency

	for i in range(cycles):   
		GPIO.output(21, True)   #set pin 18 to high
		time.sleep(delay)    #wait with pin 18 high
		GPIO.output(21, False)    #set pin 18 to low
		time.sleep(delay)    #wait with pin 18 low
		
		
		
def enviar_correo(tipo,To,veces=0,ordenes=''):
	
	# Establecemos conexion con el servidor smtp de gmail
	mailServer = smtplib.SMTP('smtp.gmail.com',587)
	mailServer.ehlo()
	mailServer.starttls()
	mailServer.ehlo()
	mailServer.login("cris.raspberry@gmail.com","holacomoestan")
	
	# Construimos un mensaje Multipart, con un texto y una imagen adjunta
	mensaje = MIMEMultipart()
	mensaje['From']="Tu servidora la RaspBerry Pi"
	mensaje['To']=To
	
	if tipo=='contra_inc':
		mensaje['Subject']="Clave incorrecta"
		# Adjuntamos el texto
		mensaje.attach(MIMEText("""Clave incorrecta, la clave debe ir en el espacio para el Asunto del correo"""))
		
	if tipo=='contra_y_orden':
		mensaje['Subject']="Clave incorrecta"
		# Adjuntamos el texto
		mensaje.attach(MIMEText("""Clave incorrecta, la clave debe ir en el espacio para el Asunto del correo, tambien recuerde que para ejecutar las acciones debe escrs de la siguiente manera \'Ordenes: orden1, orden2, etc\'. Se recomienda usar la aplicacion oficial de Gmail"""))
		
	if tipo=='orden_inc':
		mensaje['Subject']="Formato de orden incorrecta"
		# Adjuntamos el texto
		mensaje.attach(MIMEText("""Para ejecutar las acciones debe escribirlas de la siguiente manera \'Ordenes: orden1, orden2, etc\', esto me ayuda a entender mejor lo que debo hacer. Se recomienda usar la aplicacion oficial de Gmail"""))	
	
	if tipo=='multi':
		
		Correo_final="""Se han realizado las siguientes ordenes: """
		#print Correo_final
		for n_tipo in ordenes:
			if n_tipo=='buzz':
			
				# Adjuntamos el texto
				Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha hecho sonar el buzz """+str(veces)+""" veces"""
			
			if n_tipo=='rojo':
				if GPIO.input(23)==	True:
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha prendido el led rojo"""	
				else:
				
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha apagado el led rojo"""
					
			if n_tipo=='verde':
				if GPIO.input(25)==	True:
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha prendido el led verde"""	
			
				else:
						# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha apagado el led verde"""
					
		
				
				
			if n_tipo=='blanco':
				if GPIO.input(26)==	True:
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha prendido el led blanco"""
							
				else:
				
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha apagado el led blanco"""	
				
			if n_tipo=='amarillo':
				if GPIO.input(24)==	True:
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha prendido el led amarillo"""
					
				else:
			
					# Adjuntamos el texto
					Correo_final+="""\n"""+time.strftime("%H:%M:%S")+""": Se ha apagado el led amarillo"""
		#print Correo_final
	# Enviamos el correo, con los campos from y to.
		mensaje['Subject']="Orden realizada"
		mensaje.attach(MIMEText(Correo_final))	
	mailServer.sendmail("cris.raspberry@gmail.com",To,mensaje.as_string())		
			
n_buzz=0			
			


contr_incorr=False
orden_incorr=False
#HOLA=1
while True:
	try:
		aux1=False
		aux2=False
		aux3=False
		evita_rep=False
		evita_rep_msg=False
		
		user = 'cris.raspberry@gmail.com' 
		Mailbox = poplib.POP3_SSL('pop.gmail.com', 995) 
		Mailbox.user(user) 
		Mailbox.pass_('holacomoestan') 

		numMessages = len(Mailbox.list()[1])
		#print numMessages
		if numMessages!=0:
			evita_rep=False
			evita_rep_msg=False
		for i in range(numMessages):
			for msg in Mailbox.retr(i+1)[1]:
				
				
					
				
				
				
				
				From_prev_locate=msg.find('From')
				if From_prev_locate!=-1:	
					aux3=True			
					From_prev=msg[From_prev_locate+6:From_prev_locate+3000]			
					From_locate1=From_prev.find('<')
					From_locate2=From_prev.find('>')
					From=From_prev[From_locate1+1:From_locate2]
					
				
				
				
				Msg_locate=msg.find('Orden')
				msg_locate=msg.find('orden')
				if (msg_locate!=-1 or Msg_locate!=-1) and evita_rep_msg==False:
					evita_rep_msg=True
					no_orden=0
					if msg_locate==-1:
						mensaje=msg[Msg_locate:Msg_locate+3000]	
					else:
						mensaje=msg[msg_locate:msg_locate+3000]					
				
					mensaje=mensaje.lower()
					mensaje=mensaje.strip()
					mensaje=mensaje.replace(' ','')
					mensaje=mensaje.replace('ordenes','')
					mensaje=mensaje.replace('orden','')	
					mensaje=mensaje.replace(':','')
					mensaje=mensaje.split(',')
					print mensaje
					
					aux1=True
					#print 'Orden::'+str(mensaje)
					
				
				Subject_locate= msg.find('Subject')
			
				if Subject_locate!=-1:
					#print msg[a:a+3000]		
					Subject=msg[Subject_locate+9:Subject_locate+3000]
					Subject=Subject.lower()
					Subject=Subject.strip()
					Subject=Subject.replace(' ','')
					Subject=Subject.replace('_','')
					Subject=Subject.replace('?','')
					Subject=Subject.replace('=c3=b1a=3','')
					Subject=Subject.replace('utf-8q','')
					Subject=Subject.replace('=','')
					Subject=Subject.replace('c3b1','')
					Subject=Subject.replace('contrasea','')
					
					#print 'Subject::'+str(Subject)
					aux2=True
					
				
				if aux1==True and aux2==True and evita_rep==False and aux3==True:

					evita_rep=True
						#msg=msg.replace('Ordenes','Orden')
					if Subject=='123' :
						
						
						
						
						
						#antiguo mensaje
					
						
						for n in range(len(mensaje)):
							#print len(mensaje)
							mensaje[n]=mensaje[n].strip()
							print mensaje[n]
							
							if mensaje[n][0:4]=='buzz':
								mensaje[n]=mensaje[n].replace(' ','')
								
								digitos=len(mensaje[n])-4
							
								if digitos==0:
									n_buzz=1
									
								else:
									n_buzz=int(mensaje[n][4:4+digitos]) 
									mensaje[n]='buzz'
									
						mensaje_len=len(mensaje)#######################################
						
						for orden_N in mensaje:
							if orden_N=='buzz': #BUZZ
								for n in range(n_buzz):
									buzz(1500, 0.1)									
									time.sleep(0.1)
								
								
							if orden_N=='rojo': #ROJO
								if GPIO.input(23)==	False:
									GPIO.output(23, GPIO.HIGH)
								
						
								else:
									GPIO.output(23, GPIO.LOW)
								
								
									
							if orden_N=='verde': #VERDE
								if GPIO.input(25)==	False:
									GPIO.output(25, GPIO.HIGH)
									
									
								else:
									GPIO.output(25, GPIO.LOW)
								
							
										
							if orden_N=='amarillo': #Amarillo
								if GPIO.input(24)==	False:
									GPIO.output(24, GPIO.HIGH)
								
							
								else:
									GPIO.output(24, GPIO.LOW)
								
							
						
							if orden_N=='blanco':#BLANCO
								if GPIO.input(26)==	False:
									GPIO.output(26, GPIO.HIGH)
								
							
								else:
									GPIO.output(26, GPIO.LOW)
								
							time.sleep(0.01)
									
						enviar_correo('multi',From,veces=n_buzz,ordenes=mensaje)
							
					
				
		if numMessages!=0:											

				if aux1==False and Subject!='123':				
					#print 'verifique contrasena y orden'
					enviar_correo('contra_y_orden',From)
					contr_incorr=False
					print 'El correo '+str(From)+' ha errado la orden y contra'
				else:	
					if aux1==False:
						enviar_correo('orden_inc',From)
						print 'El correo '+str(From)+' ha errado la orden '
					if Subject!='123':	
						enviar_correo('contra_inc',From)
						print 'El correo '+str(From)+' ha errado la contra'
						contr_incorr=False
				
	except KeyboardInterrupt:
		GPIO.output(23, GPIO.LOW)
		GPIO.output(24, GPIO.LOW)
		GPIO.output(25, GPIO.LOW)
		GPIO.output(26, GPIO.LOW)
		exit				
		time.sleep(1)
	Mailbox.quit()
	#HOLA=2
