### ISSUE TITLE
s40 version or signature changed?

### ISSUE THREAD

**Issue by gushome7** [tgalal/yowsup#1946]
Can register numbers but cannot login. I'm using the codreus info (https://coderus.openrepos.net/whitesoft/whatsapp_scratch) and until today worked fine, but my user cannot login since 1AM GMT Feb 15 and if I register a new user can do it but cannot login.

Ideas?

**Comment by Edison-nts** [comment]
What is current version parameters for s40?

**Comment by thmendes** [comment]
I don't now what happened, but my bot and my personal number was blocked. Even my personal number just receiving the messages.

**Comment by silasneo** [comment]
A friend is also experiencing a similar issue...
any feedback on this matter please?

**Comment by gushome7** [comment]
@Edison-nts :  "e":"2.16.11", "f":"2.11.634", "g":"PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk", "h":"1478194472015L"

**Comment by gushome7** [comment]
@thmendes tell me, your personal was also yowsup, or whatsapp official client?

**Comment by gushome7** [comment]
After a new tests, I get new client registration and successful login. I don't know what's happened.

**Comment by thmendes** [comment]
@gushome7 official client
