### ISSUE TITLE
All the numbers used are being blocked

### ISSUE THREAD

**Issue by FUNk31r0** [tgalal/yowsup#1947]
Could whatsapp be blocking because it's not an official app like the whatsapp plus app?

**Comment by DagoW** [comment]
I ran yowsup-cli just now a was not blocked. Or do I misunderstand?

I think I got disconnected, because a "delivery receipt" was not sent,
but was allowed to reconnect. (due to #1948)

**Comment by handflucht** [comment]
My number has been blocked and I wrote the support. Here is the answer:

> Hi,
> 
> Thanks for your message.
> 
> Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.
> 
> Please uninstall your application and install an authorized version on supported devices from:
> 
> www.whatsapp.com/download
> 
> Please note that we do not allow use of unofficial clients or jailbroken/rooted (including emulators), and unsupported devices.
> 
> To use WhatsApp on your computer, access our website from your computer’s browser. Then, open the app and scan the QR code using the WhatsApp app on your phone (look for WhatsApp Web menu under Settings). WhatsApp can only be installed on your computer if your operating system is Windows 8 (or newer) or Mac OSX 10.9 (or newer). If you are having issues installing WhatsApp on a supported operating system, turn off your anti-virus and try again.
> 
> For all other operating systems, you may use WhatsApp on your browser here
> 
> Your account will be permanently banned if you continue to violate our Terms of Service, and there will be no possibility of an appeal.
> 
> Best Regards, 
> ...
> WhatsApp Support Team
> 
> Take a look at our FAQ!

Now I can use my number again (on the original client). I think I will not try to use yowsup again in the near future.

**Comment by Aranad** [comment]
Yeah they suck, best to use something like Twilio so you can use throw-away numbers to register with (note that only some countries numbers work).

**Comment by MuhammadHuzaifah** [comment]
hii @handflucht ,

how many messages you're sending using yowsup per second? i thought Official WhatsApp detected your number based on messege sent intensity. 

anyone here knew the parameter Official WhatsApp ban our number by using this Wonderfull Library?

is WhatsApp verify the IMEI number? or they  (i've no idea.........)

**Comment by handflucht** [comment]
@MuhammadHuzaifah I just send two/three messages, received an error that something went wrong and minutes I realized on my mobile that my number was blocked.

**Comment by handflucht** [comment]
@MuhammadHuzaifah I used the second command.
As far as I understand you can just try. If you get blocked, write the support and they will unblock you again. But after doing so, as far as I understand, a new block will be permanently.

**Comment by MuhammadHuzaifah** [comment]
@handflucht till now i've sent hundreds of messages using yowsup-cli demos -c configfile.config -s 8989898xxx "messages" and nothing get bocked. which environment do you use? s40 or Android environment?

**Comment by handflucht** [comment]
@MuhammadHuzaifah I am sorry, what do you exactly mean with environment in this context?

**Comment by MuhammadHuzaifah** [comment]
@handflucht by default, yowsup using s40 as environment. take a look in env directory in yowsup source code.

**Comment by FoxMiner** [comment]
@MuhammadHuzaifah How do you create the account using android? And to send messages using S60?
What hourly limits do you use to send

thanks

**Comment by idemenef** [comment]
hi everyone,
to register using default environment use command bellow
$ yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456

to specifically using one of environment use bellow
$ yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456 -E android

default environment it setup on /yowsup/env/env.py

import abc
import logging
from six import with_metaclass

logger = logging.getLogger(__name__)

**DEFAULT = "s40"** #you can edit to adroid to make it as default

class YowsupEnvType(abc.ABCMeta):
    def __init__(cls, name, bases, dct):
        if name != "YowsupEnv":
            YowsupEnv.registerEnv(cls)
        super(YowsupEnvType, cls).__init__(name, bases, dct)


i also still learn about this awesome API.

**Comment by Kanhavishva** [comment]
Finally I got blocked today after using it for 3 days :( . I will not lose hope and gonna sacrifice one more number.
I am developing a GUI for the great yowsup library.
![screenshot from 2017-08-27 14-34-36](https://user-images.githubusercontent.com/24961687/29748659-2ef69aa2-8b38-11e7-83db-71c23129f9f9.png)
