### ISSUE TITLE
Replies to specific messages are never received

### ISSUE THREAD

**Issue by DagoW** [tgalal/yowsup#1948]
In the official WhatsApp one can reply to a specific message in a chat 
(by selecting it and replying or by using the drop-down menu in WhatsApp Web).

I noticed that such replies are never received by yowsup-cli and missing from 
the chat.  The several seconds later, I get this
```
ERROR:yowsup.layers.interface.interface:Stream Error type: ack
{'ack': None}
```
Is this a known limitation?
Can somebody here fix this?

With best regards, Dago

**Comment by evertonrenne** [comment]
DagoW,
Did you fix this? Found a workaround? I've same problem when my number receives a reply message.

@tgalal Do you have any tip how should we handle with this error?

**Comment by DagoW** [comment]
No, I lack the knowledge to fix it and I have no workaround.

I guess tgalal is busy with other things. The last commit to this project was 7 months ago.

Does anybody know if there is an active fork of "yowsup"?

**Comment by mikkelam** [comment]
did you end up finding a solution for this? I have this same problem

**Comment by DagoW** [comment]
No, I didn't.

**Comment by manusreload** [comment]
I've noticed that the error occurs when the message is being decoded to UTF-8 by the axolotl lib:

(https://github.com/tgalal/python-axolotl/blob/master/axolotl/groups/groupcipher.py#L104)
```
return plaintext.decode()
```
And the exception raised is:

`'utf-8' codec can't decode byte 0x8a in position 8: invalid start byte`

Can it be an issue in axolotl library? I think that the messages are treated as plain text, and have an XML structure when is a reply or mention.

**Comment by fsarihan** [comment]
any news ? we need a solution

**Comment by subins2000** [comment]
yeah, solution please @tgalal

**Comment by sachin2625** [comment]
I registered the number in Whatspp but i am not able to get the password,
I get this msg
{
    "__version__": 1,
    "cc": "91",
    "client_static_keypair": "XXXXXXXXXXX",
    "expid": "XXXXXXXXXX",
    "fdid": "XXXXXXXX",
    "id": "XXXXXXXXXXX",
    "login": "91XXXXXXXXX",
    "mcc": "405",
    "mnc": "863",
    "phone": "91XXXXXXXXXX",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
But i am using pywhatsapp, password is required.
So how to get the password?
