### ISSUE TITLE
old_version error

### ISSUE THREAD

**Issue by Cholowao** [tgalal/yowsup#1952]
I have been registering a new WhatsApp number and got that error

```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"MYPHONENUMBER","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: MYPHONENUMBER
```
I have tried to modify s40.py and `android.py` all seem not to work.

Can someone tell me how to update version by myselft

**Comment by Aranad** [comment]
The current working version for env_s40.py I've been using is "2.16.11" with token "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452"

**Comment by Cholowao** [comment]
First I changed file. This is my file

```
import hashlib
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452"
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
        return self.__class__._DEVICE_NAME

    def getManufacturer(self):
        return self.__class__._MANUFACTURER

    def isAxolotlEnabled(self):
        return self.__class__._AXOLOTL

    def getToken(self, phoneNumber):
        return hashlib.md5(self.__class__._TOKEN_STRING.format(phone = phoneNumber).encode()).hexdigest()

    def getUserAgent(self):
        return self.__class__._USERAGENT_STRING.format(
            WHATSAPP_VERSION = self.getVersion(),
            OS_NAME = self.getOSName() + "Version",
            OS_VERSION = self.getOSVersion(),
            DEVICE_NAME = self.getDeviceName(),
            MANUFACTURER = self.getManufacturer()
        )
```

then I ran the following command
`$ sudo python setup.py build`

after that I ran 
`$ sudo python setup.py install`

And finally this...
`$ yowsup-cli registration -E s40  -d --requestcode sms --phone 255716xxxxxx --cc 255 --mcc 640 --mnc 02`
Can you spot the error?

**Comment by Cholowao** [comment]
@Aranad

**Comment by Aranad** [comment]
@Cholowao you mean that's still giving the old_version error? or a different error now?

**Comment by Aranad** [comment]
oh wait there is an error - you don't have {phone} at the end of the token string - sorry should have mentioned that.

**Comment by Cholowao** [comment]
@Aranad 
I have `old_version` error even after adding `{phone}` at the end. Did you tried this method recently?

**Comment by Aranad** [comment]
Yep I tried just now and it's still working - although I can't use the number for anything because I just wanted to use it with pidgin but they block it when I do that :-(

**Comment by Cholowao** [comment]
Oh! Sorry :(

Do you think I have to re-install something? like pip or any other package.
Because I installed everything today. Everything. But using  pip install yowsup2

**Comment by Aranad** [comment]
No idea sorry, I'm a noob as well I only found yowsup after trying to figure out how to run whatsapp without a phone a few days ago.

**Comment by Reudi** [comment]
The _Version in env_s40.py  is corresponding to the Whatsapp version right?
Because I changed it to the Whatsapp version I found on my phone which is 2.17.24
Now i get a "bad_token" message when i request a sms for regestration.
Does someone know how to modify the token?

**Comment by Cholowao** [comment]
Can you paste your `env_s40` code here?

**Comment by rakeshmane** [comment]
Thanks for that token string @Aranad 
I was facing the same problem but changing the token and whatsapp version worked for me.

**Comment by Varal7** [comment]
Worked for me as well.

**Comment by fipso** [comment]
Tried it today. Not working. Getting the same error.

**Comment by gnow1** [comment]
change this in env.py

DEFAULT = "Android"

**Comment by fipso** [comment]
Still getting the same error. I changed my env.py and rebuild.

**Comment by zippo81** [comment]
Hi,

I got the same issue. I also tried different changes and rebuild every time but nothing seems to work.

**Comment by tonystark96** [comment]
i have same error too, i updated to version "2.16.11", and token "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}" but not working.

**Comment by fipso** [comment]
Worked without any changes on a different pc. Maybe ovh is just ip banned from whatsapp.
I used -E s40
