### ISSUE TITLE
Discovering version/token for env S40/S60

### ISSUE THREAD

**Issue by giuseppepaolo** [tgalal/yowsup#1953]
Hello, Anybody knows what are the necessary steps to get the values version and token, for env_s40.py?

I think that I can help updating this information, or creating a new s60 environment.

**Comment by Aranad** [comment]
There is this suggestion about auto updating
https://github.com/tgalal/yowsup/pull/1726/commits/5fe3086645dfbbf0ae4a8dd8c37b4d7db6c60869
It gets the s40 token info from:
https://coderus.openrepos.net/whitesoft/whatsapp_scratch
Gets the version from "e", and makes the token from "b" appended with the numbers part of "c" and "{phone}"

**Comment by giuseppepaolo** [comment]
Ok, but if I need to update manually these variables, do you know the steps for this?
