### ISSUE TITLE
Can't rebuild s40 version 

### ISSUE THREAD

**Issue by Cholowao** [tgalal/yowsup#1956]
After changing version number and token in s40.py folder, and run `build.py`, the terminal still shows previous version on user agent
`
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}`

**Comment by giuseppepaolo** [comment]
Hi @Cholowao, delete Build folder, and execute again:

python setup.py build
python setup.py install (if necessary)

**Comment by Cholowao** [comment]
@giuseppepaolo I deleted it and still showed same error

**Comment by giuseppepaolo** [comment]
Ok, try to exclude yowsup in python lib too... and reinstall again.

**Comment by Cholowao** [comment]
@giuseppepaolo  CAN you explain how I can do it?

**Comment by giuseppepaolo** [comment]
My yowsup is at /usr/local/lib/python2.7/dist-packages/yowsup. Is yours too? If yes, exclude only this folder (with caution)

**Comment by Cholowao** [comment]
The same, but folder name is `yowsup2-2.5.0-py2.7.egg`

**Comment by Cholowao** [comment]
Debug message 

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=255&in=716343889&lc=GB&lg=en&sim_mcc=640&sim_mnc=000&mcc=640&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1757&rchash=bf82425daaf22488d2038902de91b0e251f9b649d323b9f48093ce3988c0c61c&anhash=%AE%9F%26%F0%E4%94%1EzQrXy%C4%95%19%0AN%E4%E4%96&extexist=1&extstate=1&token=fe234b378d154c6dcca365d264ed96cf&id=%03%FA%5B-s%CE%1DE6%0E%E4N%FDV%3DhH%F4%9E%2F
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=255&in=716343889&lc=GB&lg=en&sim_mcc=640&sim_mnc=000&mcc=640&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=1757&rchash=bf82425daaf22488d2038902de91b0e251f9b649d323b9f48093ce3988c0c61c&anhash=%AE%9F%26%F0%E4%94%1EzQrXy%C4%95%19%0AN%E4%E4%96&extexist=1&extstate=1&token=fe234b378d154c6dcca365d264ed96cf&id=%03%FA%5B-s%CE%1DE6%0E%E4N%FDV%3DhH%F4%9E%2F
INFO:yowsup.common.http.warequest:{"login":"255716343889","status":"fail","reason":"old_version"}

**Comment by giuseppepaolo** [comment]
Show your env_s40.py please...

**Comment by Cholowao** [comment]
```
from .env import YowsupEnv
import hashlib
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
        return self.__class__._DEVICE_NAME

    def getManufacturer(self):
        return self.__class__._MANUFACTURER

    def isAxolotlEnabled(self):
        return self.__class__._AXOLOTL

    def getToken(self, phoneNumber):
        return hashlib.md5(self.__class__._TOKEN_STRING.format(phone = phoneNumber).encode()).hexdigest()

    def getUserAgent(self):
        return self.__class__._USERAGENT_STRING.format(
            WHATSAPP_VERSION = self.getVersion(),
            OS_NAME = self.getOSName() + "Version",
            OS_VERSION = self.getOSVersion(),
            DEVICE_NAME = self.getDeviceName(),
            MANUFACTURER = self.getManufacturer()
        )
```

**Comment by Cholowao** [comment]
@giuseppepaolo

**Comment by giuseppepaolo** [comment]
That's right, try to change:

```
    _OS_VERSION = "14.28"
    _DEVICE_NAME = "306"
```

only to test, and reinstall again. Check if these variables change in your environment.

**Comment by Cholowao** [comment]
They do not change. `{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}`

and I run build and install

**Comment by Cholowao** [comment]
@giuseppepaolo

**Comment by giuseppepaolo** [comment]
Are you sure that you delete folder build and reinstall again?? Try:

1 - Delete build folder;
2 - Delete yowsup inside python library;
3 - exec "python setup.py install".
