### ISSUE TITLE
Error: AttributeError: 'module' object has no attribute 'Default'

### ISSUE THREAD

**Issue by geetanshjindal** [tgalal/yowsup#1958]
Hi,
i was able to register the yowsup but when i am trying to send message to specific number i am getting following error
**Command** : ./yowsup-cli demos -c config -E s40 -s 91xxxxxxxxxx hi  
**Error**

> File "./yowsup-cli", line 368, in <module>
>     if not parser.process():
>   File "./yowsup-cli", line 272, in process
>     self.startSendClient()
>   File "./yowsup-cli", line 314, in startSendClient
>     from yowsup.demos import sendclient
>   File "/home/desk/Desktop/yowsup2017/yowsup/demos/sendclient/__init__.py", line 1, in <module>
>     from .stack import YowsupSendStack
>   File "/home/desk/Desktop/yowsup2017/yowsup/demos/sendclient/stack.py", line 1, in <module>
>     from yowsup.stacks import  YowStackBuilder
>   File "/home/desk/Desktop/yowsup2017/yowsup/stacks/__init__.py", line 1, in <module>
>     from .yowstack import YowStack, YowStackBuilder
>   File "/home/desk/Desktop/yowsup2017/yowsup/stacks/yowstack.py", line 10, in <module>
>     from yowsup.layers.protocol_media              import YowMediaProtocolLayer
>   File "/home/desk/Desktop/yowsup2017/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
>     from .layer import YowMediaProtocolLayer
>   File "/home/desk/Desktop/yowsup2017/yowsup/layers/protocol_media/layer.py", line 2, in <module>
>     from .protocolentities import ImageDownloadableMediaMessageProtocolEntity
>   File "/home/desk/Desktop/yowsup2017/yowsup/layers/protocol_media/protocolentities/__init__.py", line 3, in <module>
>     from .message_media_downloadable_image import ImageDownloadableMediaMessageProtocolEntity
>   File "/home/desk/Desktop/yowsup2017/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 4, in <module>
>     from yowsup.layers.protocol_messages.proto.wa_pb2 import ImageMessage
>   File "/home/desk/Desktop/yowsup2017/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 9, in <module>
>     from google.protobuf import symbol_database as _symbol_database
>   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 165, in <module>
>     _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
> AttributeError: 'module' object has no attribute 'Default'

need help, TIA

**Comment by MuhammadHuzaifah** [comment]
try this: ./yowsup-cli demos -c config -E s40 -s 91xxxxxxxxxx "hi"

**Comment by geetanshjindal** [comment]
i am getting the same error.

On Mar 1, 2017 8:17 PM, "MuhammadHuzaifah" <notifications@github.com> wrote:

try this: ./yowsup-cli demos -c config -E s40 -s 91xxxxxxxxxx "hi"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgalal/yowsup/issues/1958#issuecomment-283359568>, or mute
the thread

**Comment by geetanshjindal** [comment]
i am getting the same error.

**Comment by MuhammadHuzaifah** [comment]
i used ./yowsup-cli demos -c config.config -s 91xxxxxxxxxx "hi"
and so far no problem.

find out the problem any module you missed.

reinstall the protobuf please.

sudo pip install protobuf==3.0.0b2

hope that solved your problem
