### ISSUE TITLE
Lot of numbers blocked

### ISSUE THREAD

**Issue by gauchoarg** [tgalal/yowsup#1960]
Hi guys, we have been using yowsup during the last 6 months without problems, a week ago we register a new number and after 24 hs more or less it's blocked. We tried with 3 others numbers and it's blocked too.

We are using env S40 with the last version. In all those cases the only person who have the number is me so it couldn't be blocked by others, also in the same server we have another number registered that is working fine.

Also every number blocked at the same hour +/- 5 pm central time

Any idea? Is this start happend when whatsapp start changing the status and the new stuff.

Waiting to hearing your comments

Gaucho

**Comment by MuhammadHuzaifah** [comment]
hii @gauchoarg we all here have a same issues, by 30 june 2017 env S40 is not longer support by WhatsUp, so have to prepared what we should do. 

about the blocked number, till now i dont even know the parameter of WhatsUp to block our number. i just guess the whatsup see our freqwenly message that we've send. How many messages that you send via yowsup per second??

**Comment by gauchoarg** [comment]
Nothing, just registered the number, try with 1 or 2 messages and get blocked after 24 hs...

**Comment by gauchoarg** [comment]
Hi @MuhammadHuzaifah  we try to change the environment to Android, we can registered the number but then we couldn't sent any message the error is connection closed... Do you have any idea if we need to update Android version to work?

**Comment by MuhammadHuzaifah** [comment]
i used s40 environment. i dont even try the android env, last time i tried, my number got blocked.
hope somebody tell us how to solved our problem @gauchoarg

**Comment by vityapro** [comment]
It`s new fitch of whatsapp, this action in official version of whatsapp olthow, to solve this problem you need think old account with new what you register and chat with him 10 - 20 minutes (Old account must write first) after that you can write other accounts
