### ISSUE TITLE
no_routes error

### ISSUE THREAD

**Issue by halukunal** [tgalal/yowsup#1962]
Hello,

I updated env_s40.py but I get no_routes error. Is there any solution?

Thanks. 

used command: yowsup-cli registration --requestcode sms --phone 905_________ --cc 90 --mcc 286 --mnc 01  
request user agent: {'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.11 S40Version/14.26

**Comment by PatrickFelber** [comment]
Hi all,
I'm facing the same problem... I'm using the current master (commit d69c1ff).
I've updated env_s40.py and set "_VERSION" to "2.16.11". Then I rebuilt the files with "python setup.py build".

I tried to register the number with the following command:
yowsup-cli registration --requestcode sms --phone 49XXXXXXXXXX --cc 49 --mcc 262 --mnc 07

Getting the following result:
yowsup-cli  v2.0.15
yowsup      v2.5.0
INFO:yowsup.common.http.warequest:{"login":"49XXXXXXXXXX","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}
status: fail
retry_after: 3600
reason: no_routes
login: 49XXXXXXXXXX

Does anybody know about this issue?
Thanks and best regards

**Comment by netofontess** [comment]
Hi!

I have the same problem. I tried to register for 'android_env', but I got the message: old_version
Anyone solved this?

Tk's

**Comment by gauchoarg** [comment]
try with android environment https://github.com/colonyhq/yowsup

**Comment by PatrickFelber** [comment]
@gauchoarg Thanks for your reply. Using the latest master from clonyhqs fork and Android environment (!) the registration worked for me now. I'm using the Android environment by setting the variable DEFAULT in env.py from "s40" to "android".
Unfortunately I'm facing issue #1313 now.

**Comment by gauchoarg** [comment]
Yes it's a workaround... to use android env someone need to develop the WA20 protocol as is developed in S40 o wait until WA give us an official API.

Cheers

**Comment by JohnnyHurt** [comment]
Hi Guys,

I have the same issue: 
INFO:yowsup.common.http.warequest:{"login":"1809XXXXXXX","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}

status: fail
retry_after: 3600
reason: no_routes
login: 1809XXXXXXX

I made the suggestions using android environment:

./yowsup-cli registration --requestcode sms -p 1809XXXXXXX -C 1 --env android -d

any idea??

**Comment by dietzi** [comment]
I had the same problem while trying to register from my public root-server. It seem's the IP is blocked. I had to register from my home-server and everything went fine even without mcc and mnc

**Comment by thatskriptkid** [comment]
@PatrickFelber  Hi! Could you provide s40 settings for log in? Mine is not working *(

_VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True
