### ISSUE TITLE
WhatsApp will no longer be supported on s40

### ISSUE THREAD

**Issue by nedimhx** [tgalal/yowsup#1963]
Hello, 
after I try to register phone number with this whatapp client, by the mistake, I enter my second number, and I try again with correct nuber, but I get error someting like no route.
So I think number is blocked by whatsapp and I opened support ticket... explain that I'm using s40.. this is what I get from whatsapp support:

##- WhatsApp Support -##

Hi,

WhatsApp will no longer be supported on Nokia S40 by June 30, 2017. As such, we no longer offer customer support for inquiries related to Nokia S40 phones.

Please refer to our FAQ articles for an answer to your query: https://www.whatsapp.com/faq/en/s40

Thank you for being a loyal WhatsApp user. Rest assured, if WhatsApp works on your Nokia S40 mobile device now, it will be fully functional through June 30, 2017. We recommend upgrading to a newer Android, iPhone, or Windows Phone before June 30, 2017 to continue using WhatsApp.

Note: It is not possible to transfer your history to another phone, but you can export it via email: https://www.whatsapp.com/faq/en/s40/21055286

Does ANDROID work for this client ?

**Comment by MuhammadHuzaifah** [comment]
why you just tried used the ANDROID as environment? i am personally used s40 env, so far not problem.

thankyou for your information about the WhatsApp will no longer support for s40 env. so, we all here got the homework to solve this problem. :)

**Comment by nedimhx** [comment]
What is the latest android version ?
