### ISSUE TITLE
Storing debug log for failure in /root/.pip/pip.log

### ISSUE THREAD

**Issue by EiderDiaz** [tgalal/yowsup#1964]
I tried to start yowsup-cli demos with the command
`yowsup-cli demos --yowsup --config config.txt`

![2017-03-01](https://cloud.githubusercontent.com/assets/17805140/23495390/aec8ddca-fed5-11e6-96fa-b55d899be059.png)

my config.txt looks like this:
` phone=521xxxxxxxxxx
  password=xxxxxxxxxxxxxxx=`

does anyone how to fix it?
thanks in advance 😀

**Comment by Bodasia** [comment]
tpy change ovner or permissions  for file /usr/local/lib/..../requires.txt

**Comment by MuhammadHuzaifah** [comment]
@EiderDiaz use this: chmod +x /usr/local/lib/**/EGG-INFO/required.txt

**Comment by EiderDiaz** [comment]
@Bodasia @MuhammadHuzaifah  I changed the permissions as you guys said,
![53fa189d-3de1-4ed8-927b-9ad8d6e05186](https://cloud.githubusercontent.com/assets/17805140/23530619/c179ee8e-ff5f-11e6-84fd-e5f8fe27646d.jpg)

but now it shows me this.
![2017-03-02](https://cloud.githubusercontent.com/assets/17805140/23530628/cb099a80-ff5f-11e6-8f35-ad9fa428aefc.png)


😞

**Comment by MuhammadHuzaifah** [comment]
@EiderDiaz install the axolotl module. use this command `pip install python-axolotl`

**Comment by EiderDiaz** [comment]
@MuhammadHuzaifah  I tried to install axolotl but now shows me this
![2017-03-03](https://cloud.githubusercontent.com/assets/17805140/23564594/b97e03b6-0007-11e7-9e26-9908a4722146.png)

![2017-03-03 1](https://cloud.githubusercontent.com/assets/17805140/23564614/d0ce18c6-0007-11e7-8bd8-2fe1a90a1b32.png)

I think it's a pip error but I still don't know how to fix it, I also tried to update pip , nose, and libevent ,
like this guy with the same error:
Storing debug log for failure
[https://github.com/openannotation/annotateit/issues/23](url)

again thanks in advance.
😀

**Comment by EiderDiaz** [comment]
I also tried with 
`pip install yowsup2`
 and shows me something very alike 
![2017-03-03 2](https://cloud.githubusercontent.com/assets/17805140/23565286/295ee162-000a-11e7-9450-252194224e5b.png)
![2017-03-03 3](https://cloud.githubusercontent.com/assets/17805140/23565288/2b9563d4-000a-11e7-8ebd-863ffcf0b9d7.png)

**Comment by MuhammadHuzaifah** [comment]
hii @EiderDiaz try this:
sudo apt-get install gcc-arm*
or
sudo apt-get install lib32z1-dev

take a look at this : http://stackoverflow.com/questions/14180185/gcc-arm-linux-gnueabi-command-not-found

**Comment by EiderDiaz** [comment]
@MuhammadHuzaifah I did it the real problem was I wasn't installed python-dev 😆 
thanks a lot, @MuhammadHuzaifah

**Comment by MuhammadHuzaifah** [comment]
Ok Then, please close the issue @EiderDiaz
