### ISSUE TITLE
Auth Error, reason Unhandled stream

### ISSUE THREAD

**Issue by fedorenkodev** [tgalal/yowsup#1966]
Hello everyone,  today I had this error after ping to whatsapp server, ping set on average within 2 seconds.
In result account was banned. I use proxy, can there be a problem in this?
Has anyone encountered this problem?
```
Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>
```

**Comment by ACE2xxx** [comment]
Same here :(

**Comment by MrDinky** [comment]
ACE2xxx, account has been already blocked. Look for this https://github.com/tgalal/yowsup/issues/1960#issuecomment-284671143
