### ISSUE TITLE
Android Env WA20

### ISSUE THREAD

**Issue by gauchoarg** [tgalal/yowsup#1970]
Hi there!

Reading and reading about Env_S40, blocking, Android env, etc..Just wanted to know if someone develop the WA20 for android env? or if someone know how to make Android Env work?

It seams that S40 is being detected new registrations and then WA block it...

Cheers
gaucho

**Comment by Bodasia** [comment]
Env_Android is correct, as I now problem in noise and count of preKeys in original WhatsApp aplication 812 in yowsup 200
