### ISSUE TITLE
Failed to registration 

### ISSUE THREAD

**Issue by anhtv08** [tgalal/yowsup#1972]
Hi,

I tried to get registration code fro my number in Singapore but I got following issue, I am using ma Os

anhs-MBP:yowsup anhtrang$ sudo yowsup-cli registration --requestcode sms --phone 65xxxxxxxx --cc 65 --mcc 525 --mnc 01
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"65xxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version

Any  advice?

**Comment by angeldelrio** [comment]
Please read older issues and youll find the answer, you need to do some changes in your code, code provided by this repo is outdated

**Comment by meshileya** [comment]
but, is it still possible to walk through the code to carry out its main functionality? @angeldelrio @tgalal

**Comment by angeldelrio** [comment]
At this moment yes, you can take a look to this fork, https://github.com/jlguardi/yowsup there many fixes that have been applied

**Comment by tgalal** [comment]
fixed
