### ISSUE TITLE
Decryption of new Features not working

### ISSUE THREAD

**Issue by AragurDEV** [tgalal/yowsup#1976]
Decryption of newly featured messages is not working. (@ - Mention Feature, URL-Preview, Answer Feature)

Error message for all the same: InvalidMessage or KeyId for XXX, going to send a retry _(Replaced my number with XXX)_

Debug Output of @ - Mention Feature: http://pastebin.com/8aUd6Fii

**Comment by AragurDEV** [comment]
Still not working. Any fixes?

**Comment by tgalal** [comment]
820f539da9b549c099e1f0f5af837c8b032e9b2f
