### ISSUE TITLE
Possibility of multiple clients on same device

### ISSUE THREAD

**Issue by deepanshu1212** [tgalal/yowsup#198]
Hi All,

I am trying to create a whatsapp client on a device without disturbing the original installed whatsapp messanger. Given that whatsapp allows one number to work only on one device, is this even possible?

**Comment by deed02392** [comment]
Does this essentially mean we cannot have yowsup logged in with a number that our mobiles already have a registered WhatsApp client on?

I.e. there may only be one logged in session of a given phone number at a time?

**Comment by gaggle** [comment]
Yep. 2nd device disconnects the 1st.
