### ISSUE TITLE
Failed to registrer. bad_param, number

### ISSUE THREAD

**Issue by roigreenberg** [tgalal/yowsup#1980]
I tried to register a number, but it always failed.
I tried everything I could find here, but it still failed:

python3.5 yowsup-cli  registration -d -E android -r sms -p 927XXXXXXXXX -C 927 -m 425 -n 008
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup  	v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.common.http.warequest:{'User-Agent': 'WhatsApp/2.17.106 Android/4.3 Device/Xiaomi-armani', 'Accept': 'text/json'}
DEBUG:yowsup.common.http.warequest:cc=927&in=XXXXXXXXX&lc=GB&lg=en&sim_mcc=425&sim_mnc=008&mcc=425&mnc=008&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=894&rchash=f2c09b5657d501a46efc26903c80cd7974812e39f874f86708eca7e59caab343&anhash=%A1%D4%60Oy%85%D4%B2%11%CD%3D%0B%83%EAFM%FC%C7%F4%0C&extexist=1&extstate=1&token=41uC2l442ZIFv4jmppJ4R43PxB8%3D&id=%85S%0C%22%8Cj%B2%1BA%C55%ED%10%0A%D2%3A%11%0Ev%B2
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=927&in=XXXXXXXXX&lc=GB&lg=en&sim_mcc=425&sim_mnc=008&mcc=425&mnc=008&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=894&rchash=f2c09b5657d501a46efc26903c80cd7974812e39f874f86708eca7e59caab343&anhash=%A1%D4%60Oy%85%D4%B2%11%CD%3D%0B%83%EAFM%FC%C7%F4%0C&extexist=1&extstate=1&token=41uC2l442ZIFv4jmppJ4R43PxB8%3D&id=%85S%0C%22%8Cj%B2%1BA%C55%ED%10%0A%D2%3A%11%0Ev%B2
INFO:yowsup.common.http.warequest:b'{"login":"927524239671","status":"fail","reason":"bad_param","param":"number"}\n'
status: b'fail'
param: b'number'
reason: b'bad_param'
login: b'927XXXXXXXXX'
root@roi-lg-pc:/home/roi/yowsup#

**Comment by vityapro** [comment]
becose number is invalid, for check it use https://www.twilio.com/lookup
API

**Comment by vityapro** [comment]
Pleas close issue.

**Comment by roigreenberg** [comment]
What do you mean invalid? That a cellphone number someone is using. 
I also tried another number with the same results.

**Comment by roigreenberg** [comment]
I tried my own number in the site you gave, and it's also claim to be invalid. 

Am I missing something?

**Comment by vityapro** [comment]
From what you country? Perhaps the problem is that you have incorrectly entered a phone number (without a country code at the beginning)?

**Comment by roigreenberg** [comment]
Israel.
The country code is 927.
if my local number is 0xxxxxxxxx I checked 927xxxxxxxxx.

**Comment by vityapro** [comment]
Can you register using oficial whatsapp?

**Comment by vityapro** [comment]
I think that this is a problem in a specific format recording number of your country. At moments I have no idea to solve this problem.

**Comment by roigreenberg** [comment]
I'm using whatsapp in my phone for years.. 

Is there a way to see how whatsapp see my number? 
Maybe send a message to working bot?

**Comment by vityapro** [comment]
See the youwsup cod maybe it is truble with youwsup parametrs validation
