### ISSUE TITLE
reason: no_routes

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1987]
I can not get the SMS code to register what I'm doing wrong? Thanks

./yowsup-cli registration -E android -C 55 -p 5517981246XXX -r sms
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"5517981246XXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5517981246170
root@debian8-7:/usr/src/yowsup-master# ./yowsup-cli registration --requestcode sms --phone 5517981246XXX --cc 55 --mcc 724 --mnc 16
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"5517981246XXX","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
login: 5517981246XXX

**Comment by vityapro** [comment]
try other phone number

**Comment by josep112** [comment]
Hello vityapro
Already tried with 5 chips gives the same message

**Comment by vityapro** [comment]
check other issues

**Comment by josep112** [comment]
I do not know what to check, the internet works the codes are correct

**Comment by josep112** [comment]
Does anyone have a light to help me?

**Comment by vityapro** [comment]
Try other ip, whatsapp can banned ip to.

**Comment by josep112** [comment]
vitapro ok solved thanks
