### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by emretekince** [tgalal/yowsup#1988]
It was working well untill today.
Now can't login. when I trying to login nothing happens. No response?

From WhatsApp Team:

> Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.

> Please uninstall your application and install an authorized version on supported devices from:

> Please note that we do not allow use of unofficial clients or jailbroken/rooted (including emulators), and unsupported devices.

> Your account will be permanently banned if you continue to violate our Terms of Service, and there will be no possibility of an appeal.

**Comment by mikkelam** [comment]
You were banned bro

**Comment by emretekince** [comment]
I just subscribe users to track their online presence. I didn't even send a message.
What should I do to not be banned?

**Comment by mikkelam** [comment]
Use the real whatsapp app

**Comment by vityapro** [comment]
You must do a lot of thinck to be not bunned, jusy reade this subscribe of work that you must imitate, https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation and keep in minde that some info are outdated
