### ISSUE TITLE
Getting a new environment

### ISSUE THREAD

**Issue by mikkelam** [tgalal/yowsup#1989]
I honestly believe people are being banned left and right because everybody is using the S40 env. It's easy for the whatsapp team to detect a yowsup user if 99% of people on nokia s40 are yowsup people.

What is the effort for getting a new env from some phone? If someone can tell me about this process i'd like to try.

**Comment by vityapro** [comment]
You can use this link https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by vityapro** [comment]
But your yowsup will not work on android, for more infor just look older issues

**Comment by emretekince** [comment]
Why don't use Android env?

**Comment by mikkelam** [comment]
Android env is not working for me

**Comment by mikkelam** [comment]
> You can use this link https://coderus.openrepos.net/whitesoft/whatsapp_scratch
> But your yowsup will not work on android, for more infor just look older issues

Im not able to find this anywhere, do you know what the problem is?

In any case, i'm looking to gather new envs, for other phones

**Comment by emretekince** [comment]
Hmm yes you are right. I just tried Android and its disconnecting at login step.
But anyone knows exactly why android is not working? I also tried to update env with these datas: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by mgp25** [comment]
Because of the new protocol. It is active for 1 year now.

**Comment by vityapro** [comment]
@mgp25 Hello, would like to thank you for your greate work on the Chat-API

**Comment by neurobin** [comment]
@mikkelam : Have you found any ways to get new env info?
