### ISSUE TITLE
[BUG] Error, phone number does not start with the specified country code

### ISSUE THREAD

**Issue by dragonxtek** [tgalal/yowsup#1990]
If I put the phone number and country code by separate, it doesn't work.

> python yowsup-cli registration -p 9xxxxxxxx -C 56 -r sms

**Error, phone number does not start with the specified country code**

If you put the country code before the phone number it doesn't work too:

> python yowsup-cli registration -p 569xxxxxxxx -r sms    

  
**Must specify cc (country code)**

To fix it, you need to repear the country code in phone number like this:

> python yowsup-cli registration -p 569xxxxxxxx -C 56 -r sms

**Comment by jlguardi** [comment]
This isn't a bug. It is the expected working mode.
