### ISSUE TITLE
group

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1992]
I use the command:/usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config -s "5517988XXXXXX" "A Porta foi Aberta"
How do I send a message to a group of numbers?

**Comment by vityapro** [comment]
you may use this type of message
/message       broadcast      <numbers> <content>           Broadcast message. numbers should comma separated phone numbers
but if i right not all user reciv message but only who have your number in contact book
