### ISSUE TITLE
'No such prekeyRecord!' and 'InvalidMessage or KeyId' messages

### ISSUE THREAD

**Issue by claudiorafaels** [tgalal/yowsup#1996]
For some time now I have done some tests using the echoclient demo.

From time to time the frequency of the following problems has increased:
1) Exception: No such prekeyRecord!
2) WARNING: yowsup.layers.axolotl.layer_receive: InvalidMessage or KeyId

Something changed on Whatsapp servers?
What could have happened?
What is the best way to handle these issues without ever returning the message to the sender?

**Comment by renatoornelas** [comment]
Have the same issue.. About 50% of the sent group messages doesn't get delivered. I got "Waiting for this message, this may take a while." on the phone.

**Comment by claudiorafaels** [comment]
Does anyone else have this problem in groups? Did you succeed in solving it?

**Comment by Zyrix** [comment]
I also have the same problem, some people can't receive a group message, others can. Haven't found a solution yet unfortunately.

**Comment by claudiorafaels** [comment]
@tgalal, @jlguardi  what about the above comments?

**Comment by angeldelrio** [comment]
Same issue here, not only for groups, this happens to me even in single contact conversations, I think keys are not syncing properly or something. Havent found a solution yet

**Comment by pabloruan0710** [comment]
I have same issue too.

**Comment by jlguardi** [comment]
1.- On group changes (someone is added) update the Keys.
2.- don't run yowsup in other machines/users or keep updates axolotl.db
3.- don't delete axolotl.db

**Comment by renatoornelas** [comment]
@jlguardi 

What if i have 2 axolotl.db (run with 2 different users on the same machine). Do I need to remove the account and start again?

**Comment by angeldelrio** [comment]
@jlguardi could you explain the procedure to update the keys? I have tried two things:

- raise `AxolotlControlLayer.EVENT_PREKEYS_SET` event
- used `GetKeysIqProtocolEntity` passing my entire contact list as constructor parameter

none of those solved my issue

Thanks in advance!

**Comment by claudiorafaels** [comment]
@jlguardi's recommendations were helpful. As apparently no one else will comment, I will close the issue.

**Comment by pabloruan0710** [comment]
I've never been able to solve this problem, has anyone? Thank you very much in advance. @claudiorafaels or @angeldelrio

**Comment by coolnickname** [comment]
Update the keys for the group/chat, sync the contact if it's a private chat.

If the problem still persist, consider deleting your Whatsapp account, that way all keys are reset.


Also, keys are stored per user, so be sure to always run Yowsup from the same user.

**Comment by pabloruan0710** [comment]
@coolnickname do you have an code example of how make update the keys for the group/chat?

**Comment by coolnickname** [comment]
I currently can't access my Git server, and I'm not even sure if I have the code myself.

**Comment by SPWC** [comment]
Anyone solved this yet? I'm still getting the same "Waiting for this message, this may take a while."

**Comment by SpEcHiDe** [comment]
``` No such prekeyRecord! ```

I am getting this message and then getting ```[Errno 9] Bad file descriptor```

Please help!
