### ISSUE TITLE
Autorestart echoclient demo

### ISSUE THREAD

**Issue by claudiorafaels** [tgalal/yowsup#1997]
For some time now I have done some tests using the echoclient demo.

I would like to automate the restart of the program, when there is some error.
I created the script below for this:

until sudo yowsup-cli demos -l 123456789: XXXXXXXXX -e; do
  echo "error ... exit code $ ?. Restart .."> & 2
  sleep 1
done

It works well in most cases. But when the connection defies the script exits the loop ...

Also, I put the above script scheduled in crontab, but it does not seem to work well ...

Has anyone ever had a similar need and was successful?

**Comment by Domeax** [comment]
/home/YowsupBot/start.sh:
#!/bin/bash
while true :
    do
    sudo python /home/YowsupBot/run.py
    done

sudo nano /etc/rc.local:
#!/bin/sh
bash /home/YowsupBot/start.sh

PS: I did it, because of the error of the audio messages

**Comment by claudiorafaels** [comment]
@Domeax, thanks for your cooperation!
