### ISSUE TITLE
Unable to exit cli demo client

### ISSUE THREAD

**Issue by Gonzo2028** [tgalal/yowsup#2000]
Hello, is there a command to quit the client?

I need a simple demo to echo incoming messages and quit. This is currently impossible because you cannot control the demo by exec functions of php. You could make the world a lot easier if you implement the following:
1) A quit command
2) A shwll switch --receiveAndQuit to just connect, echo message and leave again.

Regards

**Comment by Bodasia** [comment]
@clicmd("Exit")
    def exit(self):
        if self.connected:
            self.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_DISCONNECT))
        print("\nYowsdown")
        os._exit(os.EX_OK)

add comand

**Comment by Gonzo2028** [comment]
I am not a PyDev, so i understand this code snippet, but dont know where to add it.
If you could add a switch to receive and print and quit, or better receive, write to file and quit, that would be awesome and allow to use this demo by php in exec. Thanks

**Comment by Bodasia** [comment]
https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L437

**Comment by Gonzo2028** [comment]
Thanks for the advise, but its not working.
I am then getting: demos: error: argument -E/--env: invalid choice: 'xit' (choose from 'android', 's40')
When using yowsup-cli demos .... -Exit.
