### ISSUE TITLE
receive message

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#2002]
I'm using yowsup to receive messages in the /demo/echoclient of whatsapp and send it to a text file, the problem is that after about 6 minutes the file is shut down what may be happening my start file is pretty simple as below

#!/usr/bin/env python
import stack
credentials = ("551799201XXXX", "ks6LTSACZzke2PVvHtyVCwRkxxx=") 
if __name__==  "__main__":    
	receive = stack.YowsupEchoStack(credentials)
	receive.start()

**Comment by AragurDEV** [comment]
Do you have any log files? It's very difficult to help you with your given information at the moment.

**Comment by josep112** [comment]
I managed to solve it like this:

#!/usr/bin/env python
import stack
credentials = ("551799201XXXX", "ks6LTSACZzke2PVvHtyVCwRkxxx=")
if name== "main":
if __name__==  "__main__":    
	while True : 
		try :
			jose = stack.YowsupEchoStack(credentials)
			print "start run.py"			
			jose.start()
		except Exception as err :
			print "falhou"
