### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#2006]
I want to do a chatbot in whasapp only as an initial message would be a menu for each number that send a message to me, my question is will I be blocked by whatasapp even sending a single message to each number that contact me?

**Comment by AragurDEV** [comment]
Just test it. Nobody knows how WhatsApp is blocking numbers.
I experienced that if nobody will report you all should be fine. (A report is impossible if a contact sends you a message first) so what you try to achive is a good route.

**Comment by josep112** [comment]
I'll test and write here, thanks

**Comment by sanniv** [comment]
Hello @josep112 , just curious about your test results. please share..

**Comment by josep112** [comment]
Hello Sanniv, after I send out about 5 times the chip is blocked
