### ISSUE TITLE
noise protocol

### ISSUE THREAD

**Issue by hstarmans** [tgalal/yowsup#2007]
Dear all,

I am wondering whether Yowsup uses the noise [protocol](http://noiseprotocol.org/#resources)!?
I have been using [loqui im ](https://github.com/loqui/im) on my ubuntu phone. It, however, does not seem to support the noise protocol and no longer works. The support for S40 devices, which use protocol v1, will be discontinued by WhatsApp by July 30 (?)
So i wonder did you fix it!? The only details , I could find on whatsapp encryption are [here ](https://www.whatsapp.com/security/WhatsApp-Security-Whitepaper.pdf). You [encryption page ](https://github.com/tgalal/yowsup/wiki/End-to-End-encryption)does not outline whether you support it or not.

**Comment by jlguardi** [comment]
Yowsup (and also chatAPI) doesn't implement whatsapp protocol 2.0 (based on noise protocol) but whatsapp protocol 1.6. 
The support for wa1.6 will stop on Jun'30. By now, any public release of wa2.0 protocol is available for yowsup or chatAPI and I guess that this release isn't planned by now.
So: yowsup will stop working on this date.

**Comment by assegaf** [comment]
> By now, any public release of wa2.0 protocol is available for yowsup or chatAPI and I guess that this release isn't planned by now.

what you mean "by now wa2.0 protocol is available for yowsup or chatapi" ? do you mean "is unavailable" ?

**Comment by pabloruan0710** [comment]
Yowsup not worked more in Jun'30? Someone will make new version WA20?? 😢

**Comment by jlguardi** [comment]
As far as I know, no body is working on it.

**Comment by hstarmans** [comment]
Great; I have been able to get a deobfuscated APK of Whatsapp using a statistical analysis see [apkdeguard](http://www.apk-deguard.com/).
The results are [here](https://drive.google.com/file/d/0BySqlwNSfKlRYkw1U1lMODc4djA/view?usp=sharing); 
It's looks more readable but haven't looked at it for a long time yet.

**Comment by danipolo** [comment]
there's no alternatives actually?

**Comment by hstarmans** [comment]
The protocol needs to be reverse engineered.

**Comment by claudiorafaels** [comment]
Has anyone found any other way?
Chat-API has WA 2.0 implemented, right?

**Comment by hstarmans** [comment]
@claudiorafaels, correct following the [docs](https://github.com/mgp25/Chat-API/wiki/Authentication-Overview-%28WA-2.0%29) is has.

**Comment by JulioImolesi** [comment]
@claudiorafaels yes, but Chat-API was discontinued in aug/2016 =/
