### ISSUE TITLE
Mentions and probably Replies in WhatsApp groups are not being deciphered

### ISSUE THREAD

**Issue by kidynamit** [tgalal/yowsup#2011]
I am running a chatbot on a WhatsApp group. If I mention the chatbot directly in the group i get an `InvalidMessageException` from the `yowsup/layers/axolotl/layer_receive.py:95`

I have narrowed the problem down to the AES Deciphering of the message body in `axolotl/groups/groupcipher.py` in the `getPlainText` function.

Please assist.

**Comment by AragurDEV** [comment]
Having same problem in #1976

**Comment by angeldelrio** [comment]
I think that is not implemented in yowsup

**Comment by manusreload** [comment]
The error raised by axolotl is:

`'utf-8' codec can't decode byte 0x8a in position 8: invalid start byte` when is a reply

**Comment by tgalal** [comment]
820f539da9b549c099e1f0f5af837c8b032e9b2f
