### ISSUE TITLE
install error on linux

### ISSUE THREAD

**Issue by calilinus** [tgalal/yowsup#2015]
building 'Crypto.PublicKey._fastmath' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/ -I/usr/include/python3.5m -c src/_fastmath.c -o build/temp.linux-x86_64-3.5/src/_fastmath.o
    src/_fastmath.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6btib4ep/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pewpha6j-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6btib4ep/pycrypto/
 

im using kali linux on a 64bit. i get error everytime i try to run the setup.py can i get anyhelp please

**Comment by jlguardi** [comment]
Install python-dev package.

**Comment by calilinus** [comment]
i already did but still doesnt work @jlguardi

**Comment by StigP1337** [comment]
@calilinus Make sure you installed the dev package for python 3 and not python 2. Sometimes it is called "python3-dev"
