### ISSUE TITLE
Does not send image

### ISSUE THREAD

**Issue by prajeshmadhavi** [tgalal/yowsup#2016]
I am able to login to command line client.
/L shows Connected
/image send XXXXX /root/test/sample.jpg  shows  Sent.
but image is not delivered to target number, I am not able to figure out even after checking the debug log.

Have anybody faced such issue before?

**Comment by leogaletti** [comment]
Hi, I'm going through the same thing too.

When I send to an android device the image arrives however for an iphone does not arrive, is there any problem?

Sorry for english, google translate

**Comment by duarteleme** [comment]
I'm the same problem. Some iphone's device receive the image other not.

**Comment by jlguardi** [comment]
Please, try with jpeg and also with png images.

**Comment by leogaletti** [comment]
I tried with jpeg and png but neither worked

**Comment by duarteleme** [comment]
@jlguardi I tryed both. If I use a caption with the image, only the caption is send. Just on Iphone Device. Android is ok.

**Comment by leogaletti** [comment]
@jlguardi I tried with jpeg and png but neither worked
I tried to send a video and audio but it returns me this error: AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'

**Comment by langioletto** [comment]
I have the same problem

I updated whatsapp yesterday (iphone) to version 2.17.20

And now images sent by the bot do not arrive anymore

Same for geolocation

**Comment by AragurDEV** [comment]
Same for newest Android Version

**Comment by langioletto** [comment]
How can you solve it?

**Comment by jlguardi** [comment]
Could you provide debug logs with receipt, ack and read entities?

**Comment by AragurDEV** [comment]
All loking normal, nothing fails. But Mobile Client isn't recieving anything

jlguardi <notifications@github.com> schrieb am Mi., 26. Apr. 2017, 15:10:

**Comment by langioletto** [comment]
Ack is not received when you send an image, because the recipient receives nothing

As if the message was not sent

**Comment by leogaletti** [comment]
@AragurDEV @langioletto The same happens to me, I do not get ack because the application did not receive anything. The log is perfect, I executed the example with -d and everything is normal

**Comment by langioletto** [comment]
@tgalal 

I tried with iPhone and WhatsApp 2.17.7 and everything works regularly.

Image and position are received regularly.

**Comment by leogaletti** [comment]
With me just messages are coming in iphone version 2.17.20

**Comment by jlguardi** [comment]
You said that official app receives nothing. How do you know? Probably it receives an invalid message and discards it.

**Comment by leogaletti** [comment]
@jlguardi And how can we proceed? What can we do?

**Comment by pabloruan0710** [comment]
debug:

[debugfile.txt](https://github.com/tgalal/yowsup/files/958978/debugfile.txt)

**Comment by duarteleme** [comment]
Guys, the current version (2.17.20) of whatsapp for iphone has changed the photo structure (I think), as it will allow grouping of images in the chat. Should be why it gives error when sending photo to whatsapp on iphone and android works normally. https://goo.gl/vVmpM5

The message are coming, but the images not. Any solution about this?

**Comment by langioletto** [comment]
If you update whatzapp on android does not work anymore there

Geolocation also does not work!!!

Not just the pictures!!

**Comment by leogaletti** [comment]
What is your version of whatsapp on android? Because my version is up to date and working, I even opened the play store to see if it had an update

**Comment by duarteleme** [comment]
A friend of Mine tryed on Iphone (whatsapp version 2.17.11) and works. But 6 Iphones with 2.17.20 version dont receive the image. Only text.

**Comment by langioletto** [comment]
WhatsApp 2.17.7 works

**Comment by leogaletti** [comment]
WhatsApp 2.17.146 It's my version in Android

**Comment by duarteleme** [comment]
@langioletto do you mean about the android ou iphone version? And @leogaletti thats version is work on android?

**Comment by leogaletti** [comment]
This version is working on Android

**Comment by langioletto** [comment]
https://github.com/tgalal/yowsup/issues/2016#issuecomment-297167661

**Comment by leogaletti** [comment]
my debug, send to iphone in version 2.17.20:

[debug.txt](https://github.com/tgalal/yowsup/files/959413/debug.txt)

**Comment by AragurDEV** [comment]
So on the latest Android Beta 2.17.160 this feature is also not working.

**Comment by dragoncool** [comment]
I've been sending text only (decrypted) messages and it does not receive by Iphone  Whatsapp version 2.17.20? Is there any solution to this? Appreciate if anyone could kindly share the codes if there is a solution to this issue.

**Comment by fwmarcel** [comment]
Hey guys. I have tested that this error is only there when u use this Parameter "-M" 
Without it works.

**Comment by leogaletti** [comment]
I updated my whatsapp to version 2.17.160 (android) and now it only works the messages. Any solution?

**Comment by langioletto** [comment]
@fwmarcel 

Where to remove parameter M?

**Comment by duarteleme** [comment]
@fwmarcel, here dont work without the "-m" parameter. Dont receive message on Android or iOS (whatsapp updated with last version)

**Comment by langioletto** [comment]
If I kill whatsapp and send a picture I get the notification that I have received a new image

But when I open whatsapp in chat there is no new image

**Comment by CantuOSS** [comment]
How can we figure out the possibly new message protocol? it seems to only affect multimedia messages, text seems to be fine, so it doesn't seem to be a complete overhaul of the protocol communication or structure

**Comment by mniak** [comment]
The exact same thing here. The notification comes but there is no image at all.
Using iPhone.

**Comment by mniak** [comment]
@CantuOSS maybe logging the data for a received image.

**Comment by mniak** [comment]
This is the message the library is sending:
```
<message type="media" id="1234" to="...@s.whatsapp.net">
<media type="image" mimetype="i" filehash="..." url="https://..." size="..." file="img.png" encoding="raw" width="100" height="100">
...binary data...
</media>
</message>
```

And this is the message that is received when there is a message when an image is received:
```
<message from="5519984560326@s.whatsapp.net" type="media" id="1234" t="5678" notify="Andre Guilherme">
<enc mediatype="image" v="2" type="msg">
...binary data...
</enc>
</message>
```

I'll try to tweak and send messages in this format. And see what happens.

**Comment by CantuOSS** [comment]
@mniak I was thinking the same thing, i'll try to send messages with the new iOS client and check the recieved structure and post it when i can

**Comment by fwmarcel** [comment]
@mniak @CantuOSS please test some group messages with the new iOS and Android Client. I cant receive messages from yowsup client in group. In normal chats i can receive it. I use yowsup from console and start it with a python script without the Parameter -M. When i use it with this Parameter the iOS client recieve nothing.

**Comment by victorgt26** [comment]
This problem occurs with the latest version of Whatsapp, in IOS and Android. Any solution?

**Comment by CantuOSS** [comment]
@victorgt26 we are trying to figure out the changes in the media messsaging structure. Until we can figure out the new structure there is no way to send other than text messages

**Comment by fwmarcel** [comment]
@CantuOSS normal text messages in groups arent working now.

**Comment by CantuOSS** [comment]
@fwmarcel ok, didn't know that, individual text messages are working tho

**Comment by fwmarcel** [comment]
@CantuOSS yeah. Normal private text messages are working, but text messages in groups not

**Comment by mniak** [comment]
My pull request above enables echoing messages.

**Comment by langioletto** [comment]
I applied the changes and I launched the layer again

`  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 34, in send
    self.toLower(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/logger/layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/structs/protocoltreenode.py", line 90, in __str__
    return self.toString()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/structs/protocoltreenode.py", line 56, in toString
    val = ''.join(['%' + hex(b)[2:] for b in val])
TypeError: hex() argument can't be converted to hex
`

**Comment by fwmarcel** [comment]
@mniak it would be great if u can check yowsup messages in Groups. It is not working now

**Comment by fwmarcel** [comment]
#2032

**Comment by Simonwcm** [comment]
i still can't display the message under updated whatsapp client.

**Comment by settiseb2711** [comment]
please help me the same problem. the image send and dont receive in whatsapp version 2.17.19 and post.

**Comment by victorgt26** [comment]
same problem!!! please help

**Comment by victorgt26** [comment]
@CantuOSS Is there any news regarding the solution of this problem?

**Comment by stejesh** [comment]
facing same issue, yowsup says image is sent.. but not received on the recipient side

**Comment by rodrigoorrego** [comment]
So, sending or receiving images are not working in yowsup right now?

**Comment by rodrigoorrego** [comment]
https://github.com/tgalal/yowsup/issues/2086

**Comment by stejesh** [comment]
nope, not working, image is getting sent with no telltale signs of error in
the debugging output but the image never gets received

**Comment by jlguardi** [comment]
Images and all other media should be sent with protobuf protocol and encrypted instead of plain mode.
Otherwise, new official app will ignore media content.

**Comment by settiseb2711** [comment]
Image send
how can i do to work??


2017-05-30 13:49 GMT-03:00 jlguardi <notifications@github.com>:

**Comment by rodrigoorrego** [comment]
please @jlguardi can you instruct us (or send documentation) on how to do this?

thanks in advance :)

**Comment by ajaygarg2006** [comment]
@jlguardi waiting for your help.

thanks

**Comment by magdalia2016** [comment]
I could not send image using yowsup in python
While sending image there is no error but not received on device.

Follow code

def request_image_upload(self, imagePath):
    self.filePath = imagePath  # only for the sake of simplicity of example, shoudn't do this
    requestUploadEntity = RequestUploadIqProtocolEntity("image", filePath=imagePath)
    self.layer._sendIq(requestUploadEntity, self.on_request_upload_result, self.on_request_upload_error)

def onRequestUploadError(self, errorRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
    print("Error requesting upload url")

def onUploadSuccess(self, filePath, jid, url):
    #convenience method to detect file/image attributes for sending, requires existence of 'pillow' library
    entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, None, to)
    self.toLower(entity)

def onUploadError(self, filePath, jid, url):
    print("Upload file failed!")

def on_request_upload_result(self, resultRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):

    if resultRequestUploadIqProtocolEntity.duplicate:
        self.on_upload_success(
            self.filePath,
            None,
            resultRequestUploadIqProtocolEntity.getUrl()
        )
    else:
        uploader = MediaUploader(
            self.messageProtocolEntity.getFrom(),
            self.layer.getOwnJid(),
            self.filePath,
            resultRequestUploadIqProtocolEntity.getUrl(),
            resultRequestUploadIqProtocolEntity.getResumeOffset(),
            self.on_upload_success,
            self.on_upload_error,
            self.on_upload_progress,
            async=False
        )
        uploader.start()
  

def on_request_upload_error(self, errorRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
    logging.error("Error requesting upload url")

def on_upload_success(self, filePath, jid, url):

    # convenience method to detect file/image attributes for sending, requires existence of 'pillow' library
    entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(
        filePath,
        url,
        None,
        self.messageProtocolEntity.getFrom()
    )
    self.layer.toLower(entity)

def on_upload_error(self, filePath, jid, url):
    logging.error("Upload file failed!")

def on_upload_progress(self, filePath, jid, url, progress):
    pass

**Comment by BRNALX** [comment]
There is some more information here #2123

**Comment by emiliojazz** [comment]
I have solved this problem.
It seems that the official Whatsapp client now delivers only encrypted media messages.
In layers/axolotl/layer_send.py you have to remove the conditions that prevents media messages being processed by the axolotl layer.
Look at the "send" and "processPlaintextNodeAndSend" functions and remove the "media" type check.
After that I am able to send media messages (images, location, ecc) successfully.

**Comment by mikesalmonuk** [comment]
Thanks @emiliojazz - I'll take a look at it now as I've got the same issue as everyone else.

Any chance you could paste your code of those two functions here to make it clearer for anyone else with the same issue? Just so we're not removing/commenting out incorrect or additional code blocks there?

Thanks again!

**Comment by AragurDEV** [comment]
I'm getting following error:
Error requesting upload url

**Comment by langioletto** [comment]
Kindly you can have an example of the lines to comment or make?

Thank you

@AragurDEV 

You can kindly tell me the lines commented?

Maybe I've solved the mistake

Error requesting upload url

Thanks

**Comment by emiliojazz** [comment]
@mikesalmonuk This is the output of my diff file after the changes:

`diff --git a/yowsup/layers/axolotl/layer_receive.py b/yowsup/layers/axolotl/layer_receive.py
index 5ec3293..bf519a2 100644
--- a/yowsup/layers/axolotl/layer_receive.py
+++ b/yowsup/layers/axolotl/layer_receive.py
@@ -249,7 +249,7 @@ class AxolotlReceivelayer(AxolotlBaseLayer):
         messageNode["type"] = "media"
         mediaNode = ProtocolTreeNode("media", {
             "latitude": locationMessage.degrees_latitude,
-            "longitude": locationMessage.degress_longitude,
+            "longitude": locationMessage.degrees_longitude,
             "name": "%s %s" % (locationMessage.name, locationMessage.address),
             "url": locationMessage.url,
             "encoding": "raw",
diff --git a/yowsup/layers/axolotl/layer_send.py b/yowsup/layers/axolotl/layer_send.py
index bbeacd8..6aa395b 100644
--- a/yowsup/layers/axolotl/layer_send.py
+++ b/yowsup/layers/axolotl/layer_send.py
@@ -44,7 +44,7 @@ class AxolotlSendLayer(AxolotlBaseLayer):
 
 
     def send(self, node):
-        if node.tag == "message" and node["to"] not in self.skipEncJids and not node.getChild("enc") and (not node.getChild("media") or node.getChild("media")["mediakey"]):
+        if node.tag == "message" and node["to"] not in self.skipEncJids and not node.getChild("enc"):
             self.processPlaintextNodeAndSend(node)
         # elif node.tag == "iq" and node["xmlns"] == "w:m":
         #     mediaNode = node.getChild("media")
@@ -87,9 +87,7 @@ class AxolotlSendLayer(AxolotlBaseLayer):
         recipient_id = node["to"].split('@')[0]
         isGroup = "-" in recipient_id
 
-        if node.getChild("media"):
-            self.toLower(node) # skip media enc for now, groups and non groups
-        elif isGroup:
+        if isGroup:
             self.sendToGroup(node, retryReceiptEntity)
         elif self.store.containsSession(recipient_id, 1):
             self.sendToContact(node)
@@ -252,12 +250,12 @@ class AxolotlSendLayer(AxolotlBaseLayer):
     def serializeLocationToProtobuf(self, mediaNode, message = None):
         m = message or Message()
         location_message = LocationMessage()
-        location_message.degress_latitude = float(mediaNode["latitude"])
-        location_message.degress_longitude = float(mediaNode["longitude"])
+        location_message.degrees_latitude = float(mediaNode["latitude"])
+        location_message.degrees_longitude = float(mediaNode["longitude"])
         location_message.address = mediaNode["name"]
         location_message.name = mediaNode["name"]
         location_message.url = mediaNode["url"]
-
+        location_message.jpeg_thumbnail = b''
         m.location_message.MergeFrom(location_message)
 
         return m
diff --git a/yowsup/layers/protocol_messages/proto/wa_pb2.py b/yowsup/layers/protocol_messages/proto/wa_pb2.py
index 528c1f7..37d9ca8 100644
--- a/yowsup/layers/protocol_messages/proto/wa_pb2.py
+++ b/yowsup/layers/protocol_messages/proto/wa_pb2.py
@@ -265,7 +265,7 @@ _LOCATIONMESSAGE = _descriptor.Descriptor(
     _descriptor.FieldDescriptor(
       name='jpeg_thumbnail', full_name='com.whatsapp.proto.LocationMessage.jpeg_thumbnail', index=5,
       number=16, type=12, cpp_type=9, label=2,
-      has_default_value=False, default_value=_b(""),
+      has_default_value=True, default_value=_b(""),
       message_type=None, enum_type=None, containing_type=None,
       is_extension=False, extension_scope=None,
       options=None),`

**Comment by langioletto** [comment]
Hi  @mikesalmonuk 

With your changes, the geolocation send has returned to work

But with the image I get the following error

/root/xxxxxx.jpg for xxxxxxxxxxxxx@s.whatsapp.net failed

You have some suggestion?

I use python2.7

**Comment by AragurDEV** [comment]
Okay so debug log is returnung "Feature not Implemented (501)"

https://pastebin.com/6SsHG4v7

**Comment by Bennik2000** [comment]
Hi with the hint of @emiliojazz I am able to upload the image.
Here is my diff:
[https://pastebin.com/Kzb1ZVVP](https://pastebin.com/Kzb1ZVVP)
However, I always get a HTTP 400 error code in mediauploader.py line 122

I hope this information helps. Do you have any suggestions?

Thanks!

**Comment by pabloruan0710** [comment]
Hello @Bennik2000 i changed my code and too have error in line 134 mediauploader.py

>  [connected]:[connected]:
4.png => 55628226*****@s.whatsapp.net, 2%
4.png => 55628226*****@s.whatsapp.net, 27% app.net, 5%
4.png => 55628226*****@s.whatsapp.net, 43% app.net, 29%
4.png => 55628226*****@s.whatsapp.net, 48%sapp.net, 46%
4.png => 55628226*****@s.whatsapp.net, 59% app.net, 51%
4.png => 55628226*****@s.whatsapp.net, 97% app.net, 62%
lines102]: | 4.png => 55628226*****@s.whatsapp.net, 100%
[u'HTTP/1.1 400 Bad Request', u'Content-Type: application/json', u'Date: Tue, 01 Aug 2017 14:49:55 GMT', u'Connection: close', u'Content-Length: 0', u'']
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer json data not found
Traceback (most recent call last):
  File "/home/user/web/host/whatsapp/config/yowsup/layers/protocol_media/mediauploader.py", line 134, in run
    raise Exception("json data not found")
Exception: json data not found
ERROR:yowsup.demos.cli.layer:Upload file /home/user/web/host/whatsapp/10102/img_send/4.png to https://mmg.whatsapp.net/u/f/sP86c5Iyg_30IEnfbfgbOVmAlRMABVWyQrOt7Q/AtZTttpJnYOstD0ZRNDWEgfKpTXlMnMrpVQFUHc7PvbT for 55628226*****@s.whatsapp.net failed!
Data e Hora: Tue Aug 01 2017 11:49:49 GMT-0300 (-03)
Traceback most! Reconectando...
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer json data not found
Traceback (most recent call last):
  File "/home/user/web/host/whatsapp/config/yowsup/layers/protocol_media/mediauploader.py", line 134, in run
    raise Exception("json data not found")
Exception: json data not found
ERROR:yowsup.demos.cli.layer:Upload file /home/user/web/host/whatsapp/10102/img_send/4.png to https://mmg.whatsapp.net/u/f/sP86c5Iyg_30IEnfbfgbOVmAlRMABVWyQrOt7Q/AtZTttpJnYOstD0ZRNDWEgfKpTXlMnMrpVQFUHc7PvbT for 55628226*****@s.whatsapp.net failed!

**Comment by pabloruan0710** [comment]
**Send image with yowsup mediauploader.py hBAOS is:** 
>--zzXXzzYYzzXXzzQQ
Content-Disposition: form-data; name="to"

>5562982****@s.whatsapp.net
--zzXXzzYYzzXXzzQQ
Content-Disposition: form-data; name="from"

>556293****@s.whatsapp.net
--zzXXzzYYzzXXzzQQ
Content-Disposition: form-data; name="file"; filename="09dd8c2662b96ce14928333f055c5580.png"
Content-Type: image/png


**Send image with WhatsappWeb is:** 

>------WebKitFormBoundaryAhnsYgUAoXwL7s45
Content-Disposition: form-data; name="**hash**"

>HC4tq0OCjBMrA*3ch*b+/VPQ6cfa252G3ls5G7XSNw=
------WebKitFormBoundaryAhnsYgUAoXwL7s45
Content-Disposition: form-data; name="**refs**"

>NYWVQNBn*FAt5G*3recOAWYiCU0=
jNa-5uY_0e9qw*ACg*a1nsDH3kk=
------WebKitFormBoundaryAhnsYgUAoXwL7s45
Content-Disposition: form-data; name="file"; filename="**blob**"
Content-Type: application/octet-stream

**Comment by dazzzl** [comment]
Have you ever tried to upload an encrypted image? I think that WA is checking if the uploaded file is a plain image and if this is the case, the upload will fail.

**Comment by Bennik2000** [comment]
No, I didn't try to upload an encrypted image since I did not have enough time to dig deeper into this problem, sorry.

**Comment by AragurDEV** [comment]
Any references how to encrypt a image?

Bennik2000 <notifications@github.com> schrieb am Mi., 2. Aug. 2017, 17:15:

**Comment by dazzzl** [comment]
same like decrypt. The whole image inclusive the header will be encrypted with AES

**Comment by AragurDEV** [comment]
Do you have any example?

**Comment by Bennik2000** [comment]
I will give this a try, but since I'm not at work right now it will take a moment

**Comment by dazzzl** [comment]
no, but it should be easy. Just look at the decryption. You need only the plain text, it is your image, and a random key.

**Comment by AragurDEV** [comment]
@dazzzl which description? 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bennik2000** [comment]
Look at the deCRYption in the source files. Somwere the image is decrypted and look what is done there. Then the encryption _should_ be straight forward

**Comment by dazzzl** [comment]
This is the decrypt routine from jlguardi in message_media_downloadable.py
` def decrypt(self, encimg, refkey):
        derivative = HKDFv3().deriveSecrets(refkey, binascii.unhexlify(self.cryptKeys), 112)
        parts = ByteUtil.split(derivative, 16, 32)
        iv = parts[0]
        cipherKey = parts[1]
        e_img = encimg[:-10]
        AES.key_size=128
        cr_obj = AES.new(key=cipherKey,mode=AES.MODE_CBC,IV=iv)
        return cr_obj.decrypt(e_img)`

**Comment by AragurDEV** [comment]
Where do I get the refkey from?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dazzzl** [comment]
you have to generate a new random key ... or you can use a constant ... but that is not secure ;-)

**Comment by msd86911** [comment]
Were you able to solve this issue?
I am still getting 400 bad request.

**Comment by AragurDEV** [comment]
@dazzzl Did you got image send working?

**Comment by hgc2002** [comment]
See [issue 2149](https://github.com/tgalal/yowsup/issues/2149)
It's not solved yet, but coming.

**Comment by AragurDEV** [comment]
Okay so the issue got fixed.
Just see: https://github.com/tgalal/yowsup/issues/2149#issuecomment-329210637
