### ISSUE TITLE
Whatsapp version 2.17.20 cannot received decrypted message for iphone

### ISSUE THREAD

**Issue by dragoncool** [tgalal/yowsup#2017]
Dear all,

Whatsapp cannot received a decrypted messages from yowsup for iphone. Only android can received a message from yowsup using a decrypted messages. Can you please help what else I can do to fix the error for iphone.

Thanks

**Comment by pabloruan0710** [comment]
For me worked fine with version 2.17.20

**Comment by langioletto** [comment]
[](https://github.com/tgalal/yowsup/issues/2016)

**Comment by fwmarcel** [comment]
Hey there, 
i have the same Errors with receiving messages from yowsup clients. On my IPhone i get only the Notification of a Message. And i cant see it in WhatsApp. (Version 2.17.20)

With the new beta Version of WhatsApp for Android i cant completly receive this messages. So these mistakes also appear in the next versions.

Thanks
