### ISSUE TITLE
Not receiving SMS code

### ISSUE THREAD

**Issue by sms125** [tgalal/yowsup#2020]
send: 
python yowsup-cli registration --requestcode sms --phone 79091507792 --cc 7 --mcc 250 --
mnc 28
answer: 
INFO:yowsup.common.http.warequest:{"login":"79091507792","status":"sent","length":6,"method":"sms","retry_after":1805,"sms_wait":1805,"voice_wait":65}

status: sent
retry_after: 1805
length: 6
login: 79091507792
method: sms

But the SMS code does not get. 
If I ask for a voice confirmation message in English, but I enter Russian phone number

**Comment by CantuOSS** [comment]
Check your phone number, cc and mnc to be correct, it's most likely that one of those are wrong, there aren't recent reports of the registration being blocked or not able to be done, so it's most likely working correctly

**Comment by sms125** [comment]
cc and mnc are correct for my operator, but SMS is not get

I'll pay for the help in solving this problem!

**Comment by sms125** [comment]
100$ If you can not help with the registration on Russian numbers (mcc 250, mnc 99 or 28)

**Comment by CantuOSS** [comment]
this place is not for help on how to use the platform specifically, the issues are for bugs/feature request, offering money probably won't help you get better answers here

**Comment by pablosharper** [comment]
Maybe the problem is in your SMS SERVICE country.

**Comment by sms125** [comment]
if I use the emulator everything works fine. Maybe someone knows a way to convert the channel emulator to Hash?
