### ISSUE TITLE
Is this utility work from India - Its working for me

### ISSUE THREAD

**Issue by techtutorials** [tgalal/yowsup#2024]
yowsup-cli registration --requestcode sms --phone 970XXXXXXX --cc 91 --mcc 404 --mnc 13

its not sending any sms code to mobile, again its asking me to provide options.

**Comment by ritesh24** [comment]
facing the same issue. Tried more than 20 times since last 10 days

**Comment by CantuOSS** [comment]
Please share the commands and the output you get, so we can get better context

**Comment by abdul-nine7** [comment]
Same here too! I have been trying to make this library work since past month. I am still not able to resolve the issue. It says,

INFO:yowsup.common.http.warequest:{"login":"918624807790","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 91XXXXXXXXXX

**Comment by CantuOSS** [comment]
@abdul-nine7 `reason: old_version` is caused because env variables are out to date, are you using the latest release?

**Comment by abdul-nine7** [comment]
Thanks a lot bro @CactuOSS I was able to resolve my issue by re installing everything... ☺

**Comment by CantuOSS** [comment]
@abdul-nine7 No problem, don't forget to check issue #2016. Right now we can't send group or media messages

**Comment by technocode** [comment]
no, its not working..
