### ISSUE TITLE
Decrypt contact image with CLi

### ISSUE THREAD

**Issue by angezanetti** [tgalal/yowsup#2025]
I'm trying to use the CLi to get the profile picture of my contacts.
I use the ```/contact       picture        <jid>```

It works but the return seems to be encrypted. Is there a way to decrypt this image or to store it locally?

**Comment by angezanetti** [comment]
Ok, i achieved it with uncomment the line 581 in yowsup/cli/layer.py. I close this issue

**Comment by jlguardi** [comment]
So, it ins't encrypted.

**Comment by hgc2002** [comment]
@angezanetti I could not make it to work. From /contact picture I get a file (or so) that looks to be an image but I have not been able to open it with anything. It should be a JPEG formatted image but all viewers reject it.
Any help?
Thanks
