### ISSUE TITLE
Whatsapp New version can not display message by yowsup

### ISSUE THREAD

**Issue by Simonwcm** [tgalal/yowsup#2029]
after iOS and Android update the last version can not display the message by yowsup. but the old version can display message. who have this issue? how to fix it?

**Comment by felipe010203** [comment]
It happens to me the same, I manage to find this latest version of yowsup, but it does not receive or send messages. 

env.py 
DEFAULT:"Android"

yowsup/env/env_android.py:  

 +    _MD5_CLASSES = "14w/wF67XBf2vTc+qALwKQ=="
      _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
  
 +    _VERSION = "2.16.148"
      _OS_NAME = "Android"
      _OS_VERSION = "4.3"
      _DEVICE_NAME = "GalaxyS3"


yowsup/env/env_s40.py

 +    _VERSION = "2.16.9"
      _OS_NAME= "S40"
      _OS_VERSION = "14.26"
      _DEVICE_NAME = "Nokia302"
      _MANUFACTURER = "Nokia"
 +    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1471306425030{phone}"
      _AXOLOTL = True

Re install the application with the command python setup.py install

some help

**Comment by CantuOSS** [comment]
See issue #2016. Whatsapp changed something in the new update, probably regarding the message structure/protocol

**Comment by Simonwcm** [comment]
CantuOSS but how can fix it? if remove the -M. i can't send the message. show as below error.

raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by CantuOSS** [comment]
@Simonwcm right now nobody can send other than simple direct text messages with yowsup. This place is not for how-to or for tips. Please read #2016. If you are asking for a fix rather than helping solve it, this thread has no purpose existing here.

**Comment by CantuOSS** [comment]
@felipe010203 the issue probably has nothing to do with the environment variables, there seems to be a change in the protocol/message structure on media messages. It probably has to do with whatsapp implementing new features such as media grouping, location tracking and other stuff. Right now the objective is to try and figure the new structures and implementing them so we can once again send messages.

**Comment by technocode** [comment]
Install AV soft... its will working..

**Comment by schoerg** [comment]
@CantuOSS I can send group messages too. (If "direct text messages" does not include this for you)

**Comment by Simonwcm** [comment]
@technocode  what is AV soft? how to do it?

**Comment by Simonwcm** [comment]
who can fix this issue? i still can't display the message under whatsapp new version.

**Comment by Jan2220** [comment]
Hey,
For everyone who still gets the outdated error. I scraped the md5 hash out of my whatsapp apk from my real phone and used my phones whatsapp version:

File: yowsup/env/env_android.py
_MD5_CLASSES = "YvTW8jOvV1/L68dYte3YVQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.190"
    _OS_NAME = "Android"
    _OS_VERSION = "4.4"
    _DEVICE_NAME = "GalaxyS3"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"

I know the GalaxyS3 with the Xiaomi manufacturer makes no sence but i tried this only like this and i think the old device name thats normaly there works perfecly too. The OS Version 4.3 should work too.
After editing the file you can just reinstall yowsup with the setup file:
~ 'python setup.py install'
You can then use  'yowsup-cli registration -E android ....' to use android as "device"

Now it should work! 👍 


Best Regards,
Jan (Jan2220)
