### ISSUE TITLE
Whatsapp Challenge Response Authentication

### ISSUE THREAD

**Issue by GregSithole** [tgalal/yowsup#2031]
Hi Guys

Just wanted to find out if anyone knows how WhatsApp does the challenge response authentication?

**Comment by magdalia2016** [comment]
same problem

**Comment by thaihau** [comment]
@GregSithole can share you u solve this ?

**Comment by GregSithole** [comment]
@thaihau I used https://github.com/tgalal/yowsup it's a Python version so I just used the cli, but it blocks your number after a certain point.
