### ISSUE TITLE
Not Receiving SMS for twilio number

### ISSUE THREAD

**Issue by Sumitforyou** [tgalal/yowsup#2034]
I have got a twilio number (mobile) and when i try to register it on whatsapp , it shows code has been sent to the number but i never receive the same in admin panel of twilio.

How can i verify my twilio number on whatsapp?

**Comment by AragurDEV** [comment]
Please check twilio on that part.
WhatsApp is sending SMS like every other service.

**Comment by janknobloch** [comment]
that comes due to the fact twilio is not roaming.
simple solution: 
1) use voice
2) create TwiML Bin
```
<Response>
  <Dial>
    +XXXXXXX (YOUR PHONE NUMBER)
  </Dial>
</Response>
```
3) Link that TwiML Bin to your incoming voice for your number -> call ends up at your phone note the code ready to go.

**Comment by giopf** [comment]
@janknobloch's solution didn't work for me. I tried 
`yowsup-cli registration --requestcode voice --phone 49xxxxxxxxxxxx --cc 49 --mcc 262
`
after creating and setting the twiml bin but no call received.

**Comment by JKalash** [comment]
@giopf won't work with twilio numbers
