### ISSUE TITLE
no_routes and old_version ?

### ISSUE THREAD

**Issue by xmaxmex** [tgalal/yowsup#2036]
Just see:

[root@track yowsup-2.5.2]# yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXX --cc 55 --mcc 724 --mnc 05 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"55XXXXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 55XXXXXXXXXX
[root@track yowsup-2.5.2]# yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXX --cc 55 --mcc 724 --mnc 05 -E s40
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"55XXXXXXXXXX","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}

status: fail
retry_after: 3600
reason: no_routes
login: 559184681130

**Comment by manojrao** [comment]
Please try below as:-
First  Stap:-
from yowsup.registration import WACodeRequest
method='sms'
config={'cc': '91', 'mcc': '404', 'sim_mcc': '000', 'phone': '7877200108', 'sim_mnc': '000', 'mnc': '18'}
codeReq = WACodeRequest(config["cc"],
                        config["phone"],
                        config["mcc"],
                        config["mnc"],
                        config["mcc"],
                        config["mnc"],
                        method
)
result = codeReq.send()
print result
Second Stap:-
from yowsup.registration import WARegRequest
code='808-008'
code = code.replace('-', '')
req = WARegRequest('91', '7877200108', code)
result = req.send()
print result

**Comment by xmaxmex** [comment]
Sorry ? This is python code ?

yowsup-cli, doesnt work ?


Em 15 de mai de 2017 03:54, "manojrao" <notifications@github.com> escreveu:

**Comment by Jan2220** [comment]
Hey,
For everyone who still gets the outdated error. I scraped the md5 hash out of my whatsapp apk from my real phone and used my phones whatsapp version:

File: yowsup/env/env_android.py
```
_MD5_CLASSES = "YvTW8jOvV1/L68dYte3YVQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.190"
    _OS_NAME = "Android"
    _OS_VERSION = "4.4"
    _DEVICE_NAME = "GalaxyS3"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
```

I know the GalaxyS3 with the Xiaomi manufacturer makes no sence but i tried this only like this and i think the old device name thats normaly there works perfecly too. The OS Version 4.3 should work too.
After editing the file you can just reinstall yowsup with the setup file:
`python setup.py install`
You can then use  '`yowsup-cli registration -E android ....`' to use android as "device"

Now it should work! 👍 


Best Regards,
Jan (Jan2220)

**Comment by 26196008** [comment]
@manojrao This doesn't solve the problem for me. Any other recommendations?

**Comment by manojrao** [comment]
sorry sir,
 i can not solve your problem i am working on python code for develop whatsapp .
