### ISSUE TITLE
trigger on open chat window

### ISSUE THREAD

**Issue by tigrom** [tgalal/yowsup#2037]
not an issue i guess but i'm trying to figure what is the event when somebody opens a chat window with me (without typing a message). 
I'm trying to pop a message on this event.
please help sharing info with this particular event, i could not find it.
thank you in advance.
regards.

**Comment by AragurDEV** [comment]
Why should there exist an event?

**Comment by tigrom** [comment]
To auto send info message. 
Can you help?

**Comment by AragurDEV** [comment]
Just response to a client message.
