### ISSUE TITLE
WhatsApp account unregistration

### ISSUE THREAD

**Issue by xanvfr** [tgalal/yowsup#204]
Hi, everyone

First of all, I'd like to apologize if this isn't the right place to ask for a new feature (I'm new to git).

I've tried yowsup-cli to setup an WhatsApp account using Pidgin in Linux, and now I would like to unregister my phone number in WhatsApp, but I don't see any option in yowsup-cli.

I would really appreciate if that feature would be included in yowsup-cli.

Congrats for your great work
##

**Comment by nico81** [comment]
Account deletion seems not working here. It requires I'm logged, so I can delete my account even if I'm logged in?
After sending delete account command (3-4 times), I still can send messages

**Comment by ngenglala** [comment]
guys, can you give me the command line how to unregister your number from yowsup???
or how to delete it, cause i enter the wrong number...
i using ubuntu 14.04 lts i386

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.
