### ISSUE TITLE
Contact Sync 

### ISSUE THREAD

**Issue by GregSithole** [tgalal/yowsup#2040]
Hey Guys...

Just wanted to find out regarding contact-sync, how many contacts can I sync per hour with the same number? What's the maximum before I'm blocked?

**Comment by AragurDEV** [comment]
What contact-sync are you talking about?

**Comment by GregSithole** [comment]
The one you use to check if a number is on Whatsapp...this one:
`yowsup-cli demos -c yowsup_config -S`
