### ISSUE TITLE
Registration issue while using yowsup-cli

### ISSUE THREAD

**Issue by avinashajith** [tgalal/yowsup#2041]
I am getting no_routes if I use "s40" as Environment and "old_version" when environment is android. My current version of yowsup is 2.5.2 and yowsup-cli is 2.0.15.

**Comment by progressify** [comment]
me too

**Comment by Jan2220** [comment]
Hey,
For everyone who still gets the outdated error. I scraped the md5 hash out of my whatsapp apk from my real phone and used my phones whatsapp version:

File: yowsup/env/env_android.py
_MD5_CLASSES = "YvTW8jOvV1/L68dYte3YVQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.190"
    _OS_NAME = "Android"
    _OS_VERSION = "4.4"
    _DEVICE_NAME = "GalaxyS3"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"

I know the GalaxyS3 with the Xiaomi manufacturer makes no sence but i tried this only like this and i think the old device name thats normaly there works perfecly too. The OS Version 4.3 should work too.
After editing the file you can just reinstall yowsup with the setup file:
~ 'python setup.py install'
You can then use  'yowsup-cli registration -E android ....' to use android as "device"

Now it should work! 👍 


Best Regards,
Jan (Jan2220)

**Comment by suvit** [comment]
+1

**Comment by 26196008** [comment]
+1

**Comment by suvit** [comment]
solved by android env from this PR https://github.com/tgalal/yowsup/pull/2030
