### ISSUE TITLE
Getting Blocked

### ISSUE THREAD

**Issue by GregSithole** [tgalal/yowsup#2047]
Bought a new Sim Card today, after my other Sim Cards got blocked and now that new Sim Card is also blocked. Can anyone else confirm that it's working fine for them? Or Is Yowsup out of date?

**Comment by angeldelrio** [comment]
Its outdated but its working, you have to develop carefully. for example NEVER run two yowsup instances with the same phone number at same time, also take care your program behaves like whatsapp official client (dont do things you cant with official whatsapp client)
