### ISSUE TITLE
Error in code stack.py line 33

### ISSUE THREAD

**Issue by carlosen14** [tgalal/yowsup#2049]
There is an error throwing in file `/yowsup/demos/sendclient/stack.py`, at line 33 

```
    print("Authentication Error: %s" % e.message)
   AttributeError: 'AuthError' object has no attribute 'message'
```

It works if you change it to 
`    print("Authentication Error: %s" % e)`

**Comment by dragoncool** [comment]
Hi can anyone help.

I got the issue cannot login reason not authorized as image below

![screenhunter_02 may 23 11 07](https://cloud.githubusercontent.com/assets/28051660/26336973/443e5a52-3fa8-11e7-98be-ce0ce9fedd49.gif)

Thanks

**Comment by tgalal** [comment]
obsolete
