### ISSUE TITLE
Can´t see message with encryption disabled and if enabled it shows "waiting for this message"

### ISSUE THREAD

**Issue by Jan2220** [tgalal/yowsup#2050]
Hello,
If i send a message with the demo, i only recieve the message "waiting for this message" but i can wait forever and nothing happens.... If i disable the encryption with "-M" i recieve NO message but a friend in the group does recieve the message... If i send messages with the 'yowsup-cli demos --yowsup' it is working with no problem...
I hope somebody can help me :c

~Jan (Jan2220)

**Comment by Simonwcm** [comment]
i have same issue. but i still haven't any idea for this....

**Comment by rafsiq** [comment]
same problem here.
with -M : no receive the message
without -M : receive the message "waiting for this message"

**Comment by gustavors01** [comment]
Hello all,
I have similar issues here.
My python knowledge is 0%.
Basically I use “yowsup-cli demos --send” to send message on bash script’s.

1-	When I send message to phone number, with below command, work 100%, with any length or lines quantity and also special chars:
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx "test message"``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx "Some Brazilian words like: Água, Não, Pescoço"``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx "`for i in {1..50}; do echo "Line${i}"; done`"``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx "`cat TextFileWithSpecialChar.txt`"``


2-	When I send message to groups, with below command, with short messages with or without special chars arrive fine:
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx -xxxxxxxxx "test message"``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx -xxxxxxxxx "Some Brazilian words like: Água, Não, Pescoço "``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx -xxxxxxxxx "`for i in {1..5}; do echo "Line${i}"; done`"``


3-	When I send LONG message to groups, with or without special char, like single line with around 50 characters, or around 15 lines, arrive 30% of the messages, but when I send with more then 60 char or 20 lines, no arrive and get “Waiting...”, commands:
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx -xxxxxxxxx "Some Random char: 2328052flkjvslkkvjs kjsfljvu8 lkjlj 88wefvcsdv kkjhvishkv 8wefhjsd 8ewjksd egwergfer jgrsgd"``
``yowsup-cli demos -c configfile -s 55xxxxxxxxxx -xxxxxxxxx "`for i in {1..20}; do echo "Line${i}"; done`"``

4-	When I send UNCRYPTED  messages, to groups or phone, WITHOUT special char, work 100%, on any length/lines, with below commands:
``yowsup-cli demos -c configfile –M -s 55xxxxxxxxxx -xxxxxxxxx "test message"``
``yowsup-cli demos -c configfile –M -s 55xxxxxxxxxx "` for i in {1..50}; do echo "Line${i}"; done`"``
``yowsup-cli demos -c configfile –M -s 55xxxxxxxxxx -xxxxxxxxx "`for i in {1..50}; do echo "Line${i}"; done`"``


5-	When I send UNCRYPTED messages, to groups or phone, WITH special char, not work, only arrive an empty message, below commands:
``yowsup-cli demos -c configfile –M -s 55xxxxxxxxxx "Some Brazilian words like: Água, Não, Pescoço"``

For me groups messages, still are difficult to manage, I use –M command, but I need first to clean the message and remove all special characters used in our Brazilian Portuguese.

tks.

**Comment by rafsiq** [comment]
I solved problem "waiting for this message" removing the -M and delete /root/.yowsup/<telNumber>/axolotl.db


------
gustavors01, vc é brasileiro?
vi que esse erro de caracteres é resolvido usando o python 2.7, não testei.
ou vc pode testar essa solução: https://github.com/tgalal/yowsup/issues/1942

**Comment by Jan2220** [comment]
> I solved problem "waiting for this message" removing the -M and delete /root/.yowsup/[telNumber]/axolotl.db

Still same problem... :c

**Comment by rafsiq** [comment]
> Still same problem... :c

the firt message will create a new axolotl.db
And the second will send correctly

if using another User to send messages, the path is /home/[user]/.yowsup/[tel]/axolotl.db

**Comment by Jan2220** [comment]
> the firt message will create a new axolotl.db
> And the second will send correctly
> 
> if using another User to send messages, the path is /home/[user]/.yowsup/[tel]/axolotl.db

I know ^^ First time:
`INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys`
second time:
`INFO:yowsup.demos.sendclient.layer:Message sent`
but no visible message...

**Comment by Simonwcm** [comment]
i still have same issue. the message send to group. show "waiting for this message". who have any idea?

**Comment by JuliB15** [comment]
> I solved problem "waiting for this message" removing the -M and delete 
> /root/.yowsup/[telNumber]/axolotl.db

Worked for me! Thanks!

**Comment by rramonsg** [comment]
Hey guys i have the same problem, for this case has one solution ?

**Comment by fwmarcel** [comment]
Same Problem ...

**Comment by vichogerman** [comment]
. follop up.

**Comment by al2389** [comment]
> I solved problem "waiting for this message" removing the -M and delete /root/.yowsup/[telNumber]/axolotl.db

work for me, thanks.

**Comment by danpe** [comment]
Same here
