### ISSUE TITLE
Cant Open .enc Files - Encrypted media

### ISSUE THREAD

**Issue by sealabr** [tgalal/yowsup#2051]
Hello I'm Trying to download the media image from Echo Layer... but only returns .enc URL:

https://mmi331.whatsapp.net/d/zKdswFDZ-GRwEdUahktd6Fkc6Ow/AgtvVD7t_p7X308Y0eq-WeXI7iqsOxGiA5Bo6tcfRUhQ.enc

how it's possible now to decrypt this file? Why my media type is NONE?? Somehow my yowsup shows that my file is not encrypted...

Here's my code........
protocol_media\layer.py

    def recvMessageStanza(self, node):
        if node.getAttributeValue("type") == "media":
            mediaNode = node.getChild("media")
            if mediaNode.getAttributeValue("type") == "image":
                mediaNode = node.getChild("enc") #change media to enc
                print DownloadableMediaMessageProtocolEntity.fromProtocolTreeNode(node)

result of DownloadableMediaMessageProtocolEntity.fromProtocolTreeNode
message_media_downloadable.py

protocol_media/layer.py recv image from XXXXXXXXXXX@s.whatsapp.net
Message:
ID: FACF32EB15D650FA04
From: XXXXXXXXXXX@s.whatsapp.net
Type:  media
Timestamp: 1495072226
Media Type: None
Has Preview: False
MimeType: image/jpeg
File Hash: Ol2iDa4HAZ5eVfLu6MG6wyiSsKMqK+VEJM5Kasi7/mk=
URL: https://mmi662.whatsapp.net/d/XKRWbWZLUY9fCHch81LcSFkbqog/AohFii4-YvugVMVKVyvFjWkK6dcHpWRsY3-82U3TbXZP.enc
IP: 0
File Size: 50630
File name: enc
mediaKey: None
is NOT

**Comment by brunodeandrade** [comment]
Anyone please can help with this issue? Same problem here...

**Comment by sealabr** [comment]
@tgalal @jlguardi Can you guys help me?

**Comment by tgalal** [comment]
see mediasink demo
