### ISSUE TITLE
Whatsapp send and receive message process.

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2053]
hello team,
please guide me for that how to write process send and receive message in python.
can i use like mentioned steps :-
1.login signal send. (/L)
2. presence (/presence available)
3. contacts sync (/contacts sync <some_phone_number>)
4.presence subscribe (/presence subscribe <some_phone_number>)
would be not blocked my register number of write above as  my code stop flow.

**Comment by langioletto** [comment]
https://github.com/tgalal/yowsup/issues/1648#issuecomment-226345506
