### ISSUE TITLE
Can I migrate my installation 

### ISSUE THREAD

**Issue by carlosen14** [tgalal/yowsup#2059]
I installed all this and successfully registered a number and it works at least until my needs.

My question is. Can I just reinstall in other PC, MacOS or Raspberry and move my config file? Will it work?, Or I do have to make the registration all again from zero and get a new passwd?, I have read in some place somebody says:

> You have to do 'all' like you were using it on any phone.

So I don't want to get banned and thats why I ask.

**Comment by Domeax** [comment]
With another IP Address (other PC) you have to get a new password. But you can reinstall your operating system and it will work with the same config file.

You can will get banned if you run two yowsup instances with the same number on different computers.

**Comment by carlosen14** [comment]
I just want to keep one installation, but it is now clear, i have to reinstall and modify config file and put the new passwd
