### ISSUE TITLE
reason":"old_version"

### ISSUE THREAD

**Issue by sms125** [tgalal/yowsup#2060]
python yowsup-cli registration --requestcode sms --phone 7762152192 --cc 7 --mcc 401 --mnc 01 -E android

INFO:yowsup.common.http.warequest:{"login":"7762152192","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 7762152192

yowsup-cli v2.0.15
Using yowsup v2.5.2

Who knows the solution?

**Comment by cristopher29** [comment]
Same :/

**Comment by dstollie** [comment]
same

**Comment by cristopher29** [comment]
@sms125 When you use the "yowsup-cli --register 123456 --phone..." after "yowsup-cli --requestcode..." , do you also use "-E android" parameter?

**Comment by sms125** [comment]
if s40 old_version

**Comment by sms125** [comment]
but after upgrading the error occurred:
yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by juniorhero** [comment]
Same error tried with -E with android and s40

still not working

**Comment by sms125** [comment]
#2030

**Comment by sms125** [comment]
https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py

**Comment by juniorhero** [comment]
thanks got it working

need to replace the env_android.py in the python packages  to get it working

**Comment by 26196008** [comment]
This works for me!

**Comment by FabHenkel** [comment]
Worked for me as well! Thank you!

**Comment by darkane188** [comment]
not working :(

**Comment by FabHenkel** [comment]
@darkane188 Did you use the android environment? Removed the env_android.pyc file?

**Comment by razikhshaik** [comment]
@juniorhero Hi, could you please explain a bit more, how you got it working?

**Comment by cristopher29** [comment]
@FabHenkel can you use `yowsup-cli --register XXXXXX --phone......`  with `-E android` parameter after modifying the file?

**Comment by razikhshaik** [comment]
Update
 +    _MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
 +    _VERSION = "2.17.16"

in file yowsup/env/env_android.py and run with -E android

**Comment by rodrigoorrego** [comment]
Hello! I'm new here but already a fan of yowsup! but I'm and also having some issues....

I can request a SMS code with these instructions.. thank you guys for that

but I cannot register... I'm still receiving "old version" error....

any ideas? since now, thanks for the attention! :)

--

yowsup-cli registration --register XXX-XXX --phone 5553XXXXXXXXX --cc 55 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"5553XXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5553XXXXXXXX

**Comment by FabHenkel** [comment]
@cristopher29 What I actually did was completely removing the yowsup directory (after countless unsuccessfull attempts), recloning it from the repository, updating the /yowsup/yowsup/env/env_android.py file with this one: [https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py](https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py). Afterwards remove the byte code file env_android.pyc and registered like you mentioned.

**Comment by cristopher29** [comment]
@FabHenkel `yowsup-cli registration -E android --requestcode sms...` is working
but cannot register... `yowsup-cli registration -E android --register 123456...`  :(

**Comment by FabHenkel** [comment]
@cristopher29 Did the registration without the android environment: `yowsup-cli registration --register xxx-xxx --phone 123456 --cc 12`

**Comment by cristopher29** [comment]
@FabHenkel 
```
status: fail
retry_after: 300
reason: temporarily_unavailable
login: xxxxxxxx
```
doesn't work :(

**Comment by shubhamivane** [comment]
Please, anyone help me.
shubham@shubham-Vostro-2520:~/Desktop/yowsup-2.5.2/yowsup$ yowsup-cli registration --requestcode sms --phone 919039546421 --cc 91 --mcc 405 --mnc 038
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/home/shubham/.local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/shubham/.local/bin/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/home/shubham/.local/bin/yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/registration/coderequest.py", line 62, in send
    res = super(WACodeRequest, self).send(parser)
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 70, in send
    return self.sendGetRequest(parser)
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 108, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 164, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by rodrigoorrego** [comment]
if I use -E android i'm getting: old version

if I dont use i'm getting: temporarily unavailable

:(

**Comment by rodrigoorrego** [comment]
anyone has ideas? is yowsup still working?

**Comment by rodrigoorrego** [comment]
weird... it worked in a new cellphone number I've bought here to test

but in the number I was using (and that was registered once before) it just didn't work (always "temporarily unavailable" error)

**Comment by EdgarCespedes** [comment]
yowsup/env/env.py
DEFAULT ="s40"   
update 
DEFAULT ="android"

**Comment by shubhamivane** [comment]
I was facing the same thing but I deleted existing account and again
register it with yowsup and now it works. You should do the same thing.

**Comment by kadimi** [comment]
Using file referenced by @sms125:

     wget http://cdn.rawgit.com/colonyhq/yowsup/master/yowsup/env/env_android.py -O /usr/lib/python2.7/site-packages/yowsup/env/env_android.py

**Comment by juasmilla** [comment]
Still doesn't work  :(
My test:
yowsup-cli v2.0.15
yowsup       v2.5.2

Status: fail
Reason:  old_version
Login: .....

I've tried updating the .py file from COLONYHQ into /home/pi/yowsup/yowsup/en

Same results. I think it doesn't work anymore.
Any help?
Many thanks,

**Comment by dezember** [comment]
#2237

**Comment by zenonktea** [comment]
yowsup-cli  v2.0.15
yowsup      v2.5.7

status: fail
reason: old_version

still fail

**Comment by mateusliderprojetos** [comment]
I have problem

**Comment by Xrizolin** [comment]
_MD5_CLASSES = "Yx1eJey2+7aUn5kJBizSAg=="
    _VERSION = "2.18.369"

**Comment by Xrizolin** [comment]
MD5 class = https://github.com/mgp25/classesMD5-64/blob/63a7b09ede7e5ad5d3e3865d6344cfa6f6128003/dexMD5.py on https://www.whatsapp.com/android/

_VERSION = https://www.whatsapp.com/android/

**Comment by wesam** [comment]
Same issue 

status: fail
reason: old_version
login: 962798949896


@Xrizolin can you help us and upload the full yowsup directory

**Comment by Xrizolin** [comment]
> Same issue
> 
> status: fail
> reason: old_version
> login: 962798949896
> 
> @Xrizolin can you help us and upload the full yowsup directory

    _MD5_CLASSES = "Yx1eJey2+7aUn5kJBizSAg=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.18.369"
    _OS_NAME = "Android"
    _OS_VERSION = "9"
    _DEVICE_NAME = "Pixel"
    _MANUFACTURER = "Google"
    _BUILD_VERSION = "IMM76D"
    _AXOLOTL = True

**Comment by wesam** [comment]
@Xrizolin, please can i have your skype id

**Comment by Xrizolin** [comment]
> @Xrizolin, please can i have your skype id

Do you change yowsup/env/env_android.py ?

**Comment by wesam** [comment]
@Xrizolin  Yes ...

    _MD5_CLASSES = "Yx1eJey2+7aUn5kJBizSAg=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.18.369"
    _OS_NAME = "Android"
    _OS_VERSION = "9"
    _DEVICE_NAME = "Pixel"
    _MANUFACTURER = "Google"
    _BUILD_VERSION = "IMM76D"
    _AXOLOTL = True

**Comment by Xrizolin** [comment]
if this is **env_android.py** and you use **-E android**, should be fine.

**Comment by wesam** [comment]
**unfortunately it's not working**

yowsup-cli registration --requestcode sms --phone XXXXXXXXXXXX --cc XXX -E android
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"XXXXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: XXXXXXXXXX

**Comment by wesam** [comment]
@Xrizolin if you can compress yowsup directory and share it with us

**Comment by ugurcemozturk** [comment]
Hey,
Finally found a way to work with. Please follow these steps in order. I assume that you download the repo and its dependencies.

1. Navigate to the root folder of the repo then `$ sudo python setup.py`
2. Create a new file named dexMD5.py `$ touch dexMD5.py`
3. Paste the following code to the dexMD5.py. 
`import sys
import base64
import zipfile
import hashlib

if len(sys.argv) < 2:
    print("Usage: python dexMD5.py <WhatsApp.apk>")
    exit()
else:
    apkFile = sys.argv[1]
try:
    zipFile = zipfile.ZipFile(apkFile,'r')
    classesDexFile = zipFile.read('classes.dex')
    hash = hashlib.md5()
    hash.update(classesDexFile)

    version = classesDexFile.decode("utf-8", errors = 'ignore').partition('App: ')[-1].partition(',')[0]

    print("Version: " + version)
    print("ClassesDex: " + base64.b64encode(hash.digest()).decode("utf-8"));
except Exception as e:
    print(sys.argv[1] + " not found.")`

4. Download the Whastapp.apk from [HERE](https://www.whatsapp.com/android/) in the root directory of the repository.

5. Run `python dexMD5.py`
6. There should be an output with the version and classesDex keys.
7. Replace these key-value pairs with the ones on `yowsup/env/env_android.py` (_MD5_CLASSES and _VERSION keys)
8. Run `python setup.py build`
9. One more, setup.py install

All set.
I created a PR that worked on me. #2618 

Cheers,
Ugur Cem.

> Do not forget to add -E android on registration. Sample: `python yowsup-cli registration --requestcode sms --phone 41xxxxxxxxxx --cc 41 --mcc 100 --mnc 5 **-E android**
`

**Comment by wesam** [comment]
@ugurcemozturk 

**Successfully registered but does not send the message**

```
root@:# python yowsup-cli demos -E android -c .config_file -s XXXXXXXXXXX "Testing WhatsApp..."

yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
root@:# 

```

**Comment by ugurcemozturk** [comment]
Hey @wesam,

Can you explain a bit more? You've been registered your phone number successfully but it's not working properly right?

- [ ] Ensure that the phone number not blocked by Whatsapp servers.

- [ ] The number you registered is a real number.

Thanks.

**Comment by wesam** [comment]
@ugurcemozturk 

Yes i registered my phone number successfully and it is a real number and it's not blocked by whatsapp servers.

the issue when i tried to send message nothing received and when i enabled the debug this error appears 

`DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`

**Comment by wesam** [comment]
@ugurcemozturk do you have skype id so we can debug the issue?

**Comment by ugurcemozturk** [comment]
I prefer to talk on the Teams for work. 
It's uco@emakina.com

**Comment by wesam** [comment]
@ugurcemozturk  Thanks

**Comment by ugurcemozturk** [comment]
Wait, 
Just I've just read that Teams are only for the domain of co-workers, and not able to invite or chat through it.
Can you send me your email? I'll send a link of appear.in

**Comment by wesam** [comment]
@ugurcemozturk  wesamcis@gmail.com

**Comment by adewilt8** [comment]
> Hey,
> Finally found a way to work with. Please follow these steps in order. I assume that you download the repo and its dependencies.
> 
> **1.** Navigate to the root folder of the repo then `$ sudo python setup.py`
> **2.** Create a new file named dexMD5.py `$ touch dexMD5.py`
> **3.** Paste the following code to the dexMD5.py.
> 
> ```python
> import sys
> import base64
> import zipfile
> import hashlib
> 
> if len(sys.argv) < 2:
>     print("Usage: python dexMD5.py <WhatsApp.apk>")
>     exit()
> else:
>     apkFile = sys.argv[1]
> try:
>     zipFile = zipfile.ZipFile(apkFile,'r')
>     classesDexFile = zipFile.read('classes.dex')
>     hash = hashlib.md5()
>     hash.update(classesDexFile)
> 
>     version = classesDexFile.decode("utf-8", errors = 'ignore').partition('App: ')[-1].partition(',')[0]
>     print("Version: " + version)
>     print("ClassesDex: " + base64.b64encode(hash.digest()).decode("utf-8"));
> except Exception as e:
>     print(sys.argv[1] + " not found.")
> ```
> 
> **4.** Download the Whastapp.apk from [HERE](https://www.whatsapp.com/android/) in the root directory of the repository.
> **5.** Run `python dexMD5.py`
> **6.** There should be an output with the version and classesDex keys.
> **7.** Replace these key-value pairs with the ones on `yowsup/env/env_android.py` (_MD5_CLASSES and _VERSION keys)
> **8.** Run `python setup.py build`
> **9.** One more, setup.py install
> 
> All set.
> I created a PR that worked on me. #2618
> 
> Cheers,
> Ugur Cem.
> 
> > **Do not forget to add -E android on registration. Sample:** `python yowsup-cli registration --requestcode sms --phone 41xxxxxxxxxx --cc 41 --mcc 100 --mnc 5 **-E android** `

I do get a ClassesDex key when running 'python dexMD5.py WhatsApp.apk' but at Version it's empty. Any clue?

**Comment by wesam** [comment]
@ugurcemozturk please if you can send me compressed version of the your running code via email as we agreed.

Thanks,
Wesam

**Comment by nebrassJaffar** [comment]
What is repo and it's dependancies

**Comment by daviduarte** [comment]
> y WhatsApp.apk' but at Version it's empty. Any clue?

You can see the version under the button "Download Now" in the [download page](https://www.whatsapp.com/android/). This solution works for me

**Comment by wesam** [comment]
is it working with anyone? please if yes can you compress the project files and share it with us

**Comment by scheilch** [comment]
Change file env_android.py as followed:

_MD5_CLASSES = "JfoS1T2x3koJVaLtqWRpAA=="
_VERSION = "2.18.379"

and call the script with that environment

python yowsup-cli registration -c /opt/yowsup-config/yowsup.config -r voice -E android

instead of configuration you cann pass your phe number etc. as described here

**Comment by mariofchogllo** [comment]
> Wait,
> Just I've just read that Teams are only for the domain of co-workers, and not able to invite or chat through it.
> Can you send me your email? I'll send a link of appear.in

Can you helpe me i have the error
