### ISSUE TITLE
Disconnected, reason: Connection Closed

### ISSUE THREAD

**Issue by sms125** [tgalal/yowsup#2061]
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed 

anyone knows a solution?

**Comment by Domeax** [comment]
Make sure your numbers isn't blocked.

**Comment by sms125** [comment]
The number is normal

**Comment by viktor077** [comment]
i have registered with env_android, but can send message only with env_s40
`yowsup-cli demos -c yowsup.config -s 7**********2 "test" -d -E s40`

**Comment by vteccomm** [comment]
any solution i have the same issue 
i m newbie plz guide step by step if possible. my number is not blocked as i am using it on my mobile as well. 
![yowsup2](https://user-images.githubusercontent.com/17412380/29248603-9bd2a6ec-8035-11e7-851d-05cfe1620bdb.png)

**Comment by viktor077** [comment]
Hi mate,
Your account is blocked.
Now i am not using this app because whatsapp everytime blocked accounts if these use not official apps.. I was looking for app for sendindg message triggered on zabbix. The best what i found it is Telegram.

**Comment by fjrmaulana** [comment]
not work sir 
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "D:\yowsup\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'

**Comment by ildar** [comment]
https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670 ?

**Comment by heetu** [comment]
> any solution i have the same issue
> i m newbie plz guide step by step if possible. my number is not blocked as i am using it on my mobile as well.
> ![yowsup2](https://user-images.githubusercontent.com/17412380/29248603-9bd2a6ec-8035-11e7-851d-05cfe1620bdb.png)

I have Same Issue Any One can help

**Comment by ansarifaisal** [comment]
![whatsapp](https://user-images.githubusercontent.com/21176173/51833870-b0942280-231e-11e9-9429-92ab637073db.jpg)

Can anyone help me with this please.

**Comment by kapil-raj** [comment]
does anyone got any solution?

**Comment by alejandroguille** [comment]
any solution? @ansarifaisal Same problem !!!

**Comment by ansarifaisal** [comment]
Not Yet, Sorry..!!

**Comment by lucasbosco** [comment]
hi! Any solution?

Whatsapp launched some version, and this way to login was blocked.

@ansarifaisal, Can we help to solve it together?
Thanks!

**Comment by gcastrot82** [comment]
I have the same problem.


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack


DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="57+XXXXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by julioneto08** [comment]
Hello guys !! 
i have the same problem =( 

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="xxxxxxxxxxxxxx" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
