### ISSUE TITLE
Is yowsup still working?

### ISSUE THREAD

**Issue by ezaratemx** [tgalal/yowsup#2065]
hi! 

Does anybody know if yowsup is still working ? i haven't been able to make it register

**Comment by rodrigoorrego** [comment]
me neither...

**Comment by rodrigoorrego** [comment]
if I use -E android i'm getting: old version

if I dont use i'm getting: temporarily unavailable

:(

**Comment by rodrigoorrego** [comment]
anyone has ideas? is yowsup still working?

**Comment by Risthart** [comment]
Have you tried to replace env_android with this code? https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py

**Comment by Risthart** [comment]
Registration works fine to me. But authorization seems broken. Does enyone have the same issues?

**Comment by Risthart** [comment]
For me it works only if I register as android device but authorize as S40 device.

**Comment by rodrigoorrego** [comment]
weird... it worked in a new cellphone number I've bought here to test

but in the number I was using (and that was registered once before) it just didn't work (always "temporarily unavailable" error)

**Comment by ezaratemx** [comment]
Sorry for the lame question, does anyone know how to change en en_android? do i just change the script file?

**Comment by Risthart** [comment]
Download source files, download env_android you need, replace it in the source files

**Comment by ezaratemx** [comment]
i did replace the android_env.py, with the same result. 

should i do the setup again ?
