### ISSUE TITLE
Messages do not arrive

### ISSUE THREAD

**Issue by felipe010203** [tgalal/yowsup#2067]
Messages sent from yowsup to the cell phone do not arrive. I have the latest version of yowsup https://github.com/tgalal/yowsup
Yowsup is working?

My code to send the messages is this:

from whatsapp import Client

@app.route("/sendLocalMessage")
def sendLocalMessage():
        message = request.args.get('message')
        client = Client(login='573105678909', password='dTJRadsfghgbvfghjhgbhggasdf=')
        print message.encode('utf-8')
        client.send_message("573123456770", message ).encode('utf-8'))
        return "ok"

**Comment by pcortizona** [comment]
Do you mean media messages or text also?

**Comment by sbhayana26** [comment]
How do I initiate the chat with Yowsup? I am currently able to handle the scenario when the user texts first and I am able to reply with a customised response, but what if I want to initiate the chat?
