### ISSUE TITLE
Getting blocked

### ISSUE THREAD

**Issue by shubhamivane** [tgalal/yowsup#2069]
I sent messages to a person three times without seeing his reply is this a problem, why whatsapp blocked my number.Or any other issue.

**Comment by manojrao** [comment]
Please follow below rule before send mail:-
self.toLower(messageProtocolEntity.ack())
self.toLower(AvailablePresenceProtocolEntity())
self.toLower(messageProtocolEntity.ack(True))
self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_TYPING, Jid.normalize(messageProtocolEntity.getFrom(False)) ))
self.toLower(OutgoingChatstateProtocolEntity(OutgoingChatstateProtocolEntity.STATE_PAUSED, Jid.normalize(messageProtocolEntity.getFrom(False)) ))

**Comment by shubhamivane** [comment]
I am using demo app to send messages, so what changes I need to made in demo app.
