### ISSUE TITLE
number not register

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2070]
hello team i need register a new number on whatsapp from yowsup i feact below as problem:-
status: fail
reason: old_version
login: 918955008099

**Comment by danfsd** [comment]
Try going to your Yowsup package directory and modifying `env/env_android.py`
Replace `_MD5_CLASSES` with
```
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
```
Replace `_VERSION` with
```
_VERSION = "2.17.16"
```

Then try running your `yowsup-cli registration` command with the flag `--env android`

See if it works

**Comment by manojrao** [comment]
thank you very much.

**Comment by I0Error** [comment]
this didn't work for me, I am still getting status: b'fail'
reason: b'old_version'

**Comment by danfsd** [comment]
@I0Error Did you tried running both `--requestcode` and `register` commands with the `--env android`?

**Comment by I0Error** [comment]
@danfsd I was running the `--requestcode` and get the old_version error. Dont I need the registration code to run the `register`?

**Comment by danfsd** [comment]
@I0Error first run `--requestcode sms --env android` and then `--register CODE --env android`. That's what you did?

**Comment by I0Error** [comment]
Yes See below:
![yowsup](https://cloud.githubusercontent.com/assets/4338948/26362827/7f1f631e-3fdf-11e7-8013-98cbcb9229f3.PNG)

**Comment by danfsd** [comment]
Hmm awkard, I stumbled into this issue yesterday and that change of parameters on `env_android.py` got it working again. Seems like it did it too for @manojrao. Maybe your problem is something similar but that requires a different fix.

**Comment by I0Error** [comment]
hmm, this is my env_android.py file:
![yowsup](https://cloud.githubusercontent.com/assets/4338948/26365577/437f1a30-3fe8-11e7-9aaf-46f1e2329185.PNG)

**Comment by felipe010203** [comment]
try this:

*in env_s40.py
class S40YowsupEnv(YowsupEnv):
_VERSION = "2.16.11"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "302"
_MANUFACTURER = "Nokia"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
_AXOLOTL = True

sudo python yowsup-cli registration --requestcode sms --phone 57346789234 --cc 57 --mcc 732 --mnc 101 -E android
sudo yowsup-cli registration --register 149210 --phone 57346789234 --cc 57

*in env.py
DEFAULT="Android"

**Comment by felipe010203** [comment]
My problem is when messages are sent and they do not reach the recipient. Can someone tell me if the configuration of env_android.py is the cause. Will it be the MD5 token or the Android version?

Thank you

**Comment by I0Error** [comment]
@felipe010203 didnt work either, this version is even older than the one I was previously testing with

**Comment by alvaarengaaa** [comment]
@danfsd I did register my number using the --env android and the full number, but I can't send messages, because somehow the api eats the extra 9 from brazilian numbers. Did you have the same problem?

**Comment by danfsd** [comment]
Yes @alvaarengaaa I had this issue. When you're registering (SMS, etc) use the additional digit 9.
After you authenticate, start using all phone numbers without the 9th digit.

There's a document regarding this issue and how to handle this situation in each state of Brazil. I can't get it to you now but I'll definitely post it here later

**Comment by flint27** [comment]
@danfsd   how do you calculate this value:
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="

**Comment by danfsd** [comment]
@flint27 I don't know how to get it. I saw it on some other issue here on this repo. It seems that this token is obtained through reverse engineering and that this hashes are changed in a version basis. So if the Whatsapp version changes in Android, the hashes changes.

**Comment by flint27** [comment]
@danfsd ok thanks

**Comment by ceciliacsilva** [comment]
Hello,

I using the Yowsup API with this _MD5_CLASSES. This worked until this mornig, now when I try send a message I get "Authentication error: not-authorized". My number is blocked (tried in real phone). I think that they are banning numbers based on this Key. Does anyone know how to generate a new md5_classes key? Or have a new one?
