### ISSUE TITLE
New token for Nokia s40 v2.16.12

### ISSUE THREAD

**Issue by for2ne** [tgalal/yowsup#2072]
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

````
{
    a: "Ymq77xUybBCyFLvKaLTqRw==",
    b: "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
    c: "1478194306452L",
    d: "2.17.188",
    e: "2.16.12",
    f: "2.11.634",
    g: "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
    h: "1478194472015L",
    i: "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
    j: "1478194472015L"
}
````

Now Nokia s40 version is 2.16.12.
and 
`
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
`
is wrong

```
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True
```

register result:
```
status: fail
reason: bad_token
login: xxxxxxxxxxxx
```

Can anybody help with this?

**Comment by rodvan** [comment]
Anyone?

**Comment by for2ne** [comment]
Maybe someone can get **release time** for [WhatsApp_2_16_12.jar](http://www.whatsapp.com/s40/WhatsApp_2_16_12.jar) ?

For example:
[WhatsApp_2_16_11.jar](http://www.whatsapp.com/s40/WhatsApp_2_16_11.jar) release time is **1478194306452**. 
[WhatsApp_2_13_30.jar](http://www.whatsapp.com/s40/WhatsApp_2_13_30.jar) release time is **1452554789539**. 

**Release time** unique for each version and used for token generation:
```
version 2.16.11
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

version 2.13.30
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1452554789539{phone}"
```

I would be grateful if someone can get **release time** for [WhatsApp_2_16_12.jar](http://www.whatsapp.com/s40/WhatsApp_2_16_12.jar)

Thanks!

**Comment by for2ne** [comment]
ok. It was easy.

release time for 2.16.12: **1494451854337**
```
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
```

**Comment by saczuac** [comment]
@for2ne how did you get the release time?. https://coderus.openrepos.net/whitesoft/whatsapp_scratch give me wrong params

**Comment by rodgasp** [comment]
@saczuac  @for2ne @rodvan  I'm with the same error, bad token, my s40 is:

    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True

can anyone tell me the correct token? Thanks!
