### ISSUE TITLE
Still old version

### ISSUE THREAD

**Issue by Fraesen** [tgalal/yowsup#2073]
Hi there,

i tried to run yowsup but getting the well know "old version" fail at registration. I changed the env_android.py file as described in #2070 for instance but keep getting der "old version" fail.

Is there anything else i could do? My registration command is:

yowsup-cli registration --requestcode sms --phone 49x...x -cc xx -mcc 262 --mnc XX

Thanks for your help in advance

**Comment by danipolo** [comment]
same problem here... old version :(

**Comment by pabloruan0710** [comment]
worked for me using 

> -C 55 -E android

**Comment by Flexmaen** [comment]
Get "old_version" too, even with "-E android".
