### ISSUE TITLE
Yowsup echo client does not echo image 

### ISSUE THREAD

**Issue by zoraf** [tgalal/yowsup#2075]
When using echo client in yowsup , i find that it echo both text and emoji but cannot echo image. What can i do??

**Comment by abhishekdeshkar** [comment]
https://github.com/tgalal/yowsup/issues/2071

**Comment by rodrigoorrego** [comment]
https://github.com/tgalal/yowsup/issues/2086

**Comment by tgalal** [comment]
fixed
