### ISSUE TITLE
Can not send messages to whatsapp groups on android or ios

### ISSUE THREAD

**Issue by majamatwo** [tgalal/yowsup#2078]
I can not send messages to whatsapp groups on android or ios, does anyone know what happens?
So I do and I was working until yesterday
yowsup-cli demos -s -c mydetails 521xxxxxxx-xxxxxxxxxx@g.us "----> Test"

Also probe
yowsup-cli demos -c mydetails -s 521xxxxxxx-xxxxxxxxxx@g.us "----> Test" -M

Neither form of work today on both android and ios
Messages to direct numbers if it Works

I'm using 
yowsup-cli  v2.0.15
yowsup      v2.5.2

**Comment by majamatwo** [comment]
i did the following for the problem ios and android "waiting for this message" 
#2050 
i removed the -M and delete /root/.yowsup/[telNumber]/axolotl.db

but the service is intermittent sometimes works sometimes not
![captura](https://cloud.githubusercontent.com/assets/28927998/26469477/b70f620c-415f-11e7-917a-19b4af05c8dc.PNG)

**Comment by vichogerman** [comment]
I have the same problem

**Comment by tgalal** [comment]
97e915691bf8272f9d2e2a87a62e82fb034ed4d5
