### ISSUE TITLE
No handlers could be found for logger "yowsup.layers.interface.interface"

### ISSUE THREAD

**Issue by rodrigoorrego** [tgalal/yowsup#2081]
I can send messages with yosupcli-demos, but when I try to run python run.py I'm getting:

No handlers could be found for logger "yowsup.layers.interface.interface"

ps: i ran this script today earlier normally but it isn't working anymore :(

any ideas? someone went through this? thanks for the attention! :)

**Comment by rodrigoorrego** [comment]
nvm, it went back to work lol

sorry about that

**Comment by kndone** [comment]
Hi, I'm facing the same problem, how did you fix it?

**Comment by ibgithub** [comment]
I met similar warning, in run.py I add this line:

```
import logging

logging.basicConfig(level=logging.DEBUG)

```
