### ISSUE TITLE
Why a valid registarion code is not accepted

### ISSUE THREAD

**Issue by cijo7** [tgalal/yowsup#2082]
I am getting the following error even when i am using a valid token.

INFO:yowsup.common.http.warequest:{"login":"1217XXXXXXX","status":"fail","reason":"security_code","guess_wait":0,"guesses_left":14,"email_wait":0,"wipe_wait":589529,"wipe_type":"offline","wipe_token":XXXXX,"server_time":XXXX,"min_poll":5}

status: fail
reason: security_code

**Comment by assegaf** [comment]
it seem its using two step verification code. so you need it. not sure how, but its better use official apps first,  disable  two step verification code. then reg it

**Comment by cijo7** [comment]
What about reason:temporarily_unavailable
What does that mean?

**Comment by assegaf** [comment]
its mean your number is banned
