### ISSUE TITLE
Erro on try to register "old_version"

### ISSUE THREAD

**Issue by relson** [tgalal/yowsup#2085]
Someone with the same problem?

**Comment by Linuxsysymas** [comment]
git clone https://github.com/colonyhq/yowsup.git   

this works for me! 

owsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"xxxx","status":"sent","length":6,"method":"sms","retry_after":65,"sms_wait":65,"voice_wait":65}

status: sent
retry_after: 65
length: 6
login: xxxxx
method: sms

**Comment by relson** [comment]
remais even src or pip version
