### ISSUE TITLE
temporarily_unavailable at Register

### ISSUE THREAD

**Issue by ds2k5** [tgalal/yowsup#2089]
Hello,
I did the following.

1. git clone https://github.com/tgalal/yowsup/

2. cd yowsup

3. sudo python setup.py install

4. touch ~/config.yowsup
    an fill with

cc=49                         
phone=4912345678987
id=                         
password=             

5. replace env_android.py in yowsup/yowsup/env with this
    https://raw.githubusercontent.com/colonyhq/yowsup/master/yowsup/env/env_android.py
    because: got this error " reason: b'old_version' "

6. yowsup-cli registration -c ~/config.yowsup --requestcode sms

7. yowsup-cli registration -c ~/config.yowsup -p 4912345678987 -E android --requestcode sms

 But got this error:

INFO:yowsup.common.http.warequest:b'{"login":"4912345678987","status":"fail","reason":"temporarily_unavailable","retry_after":300}\n'
status: b'fail'
login: b'4912345678987'
reason: b'temporarily_unavailable'
retry_after: 300

yowsup-cli registration -E android --register 783-036 -c ~/config.yowsup
INFO:yowsup.common.http.warequest:b'{"login":"4912345678987","status":"fail","reason":"old_version"}\n'
status: b'fail'
login: b'4912345678987'
reason: b'old_version'

What did i wrong ?
How to fix it ?

Using: Python 3.6.1
yowsup-cli v2.0.15
Using yowsup v2.5.2

**Comment by prats69** [comment]
replace your env_android.py file with this one https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py

**Comment by ds2k5** [comment]
thanks prats69, 
but a diff say no difference in the file

**Comment by prats69** [comment]
the _VERSION is different

**Comment by ds2k5** [comment]
OK, but if you can see at Point: 5
that i use this file

**Comment by prats69** [comment]
ahh okay..sorry I didn't notice that. I registered a new number today morning itself. It was working fine.

**Comment by ds2k5** [comment]
ok thanks a lot.... may be there is a problem with the number i use...

**Comment by rajatsawant** [comment]
Where can I find the file "yowsup/yowsup/env/env_android.py" to replace it?

**Comment by prats69** [comment]
You can find the location using this

Sudo find / -name yowsup

**Comment by xwanyiri** [comment]
I have tried all this here but i still get status failed reason 'old_version' error. Someone please help with a solution that is working

**Comment by ds2k5** [comment]
Hi ,
did you changed the file in for example: /usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/env

or did you replaced it in the directory you got from git ?
If in git, do the install again. or copy the file to "where it is on your system in /usr"

find /usr -name env_android.py


try this:
yowsup-cli registration -c ~/config.yowsup -p +991234567891234 -E android --requestcode sms

**Comment by xwanyiri** [comment]
Thank you @ds2k5 It worked! I had replaced the in the directory from git but had not installed.
