### ISSUE TITLE
old_version error

### ISSUE THREAD

**Issue by fsarihan** [tgalal/yowsup#2090]
i tried every solutions for old version error, But the problem is still going on

**Comment by wwsilin** [comment]
Same problem(
How to uninstall this app correctly ?

**Comment by lbernardo** [comment]
Wait response

**Comment by lbernardo** [comment]
--- Fixing the version error ---
* Modify the file yowsup/env/env.py
**Line:**
_DEFAULT = "s40"_
**For:**
_DEFAULT = "android"_

* Modify the file yowsup / env / env_android.py
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_VERSION = "2.17.16"

How: https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_s40.py

**Comment by fsarihan** [comment]
> 
>  --- Fixing the version error ---
> 
>     Modify the file yowsup/env/env.py
>     Line:
>     DEFAULT = "s40"
>     For:
>     DEFAULT = "android"
> 
>     Modify the file yowsup / env / env_android.py
>     _MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
>     _VERSION = "2.17.16"
> 
> How: https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_s40.py
> 
> I hope I have helped

status: fail
retry_after: 3600
reason: no_routes

**Comment by lbernardo** [comment]
Sorry, You need to recompile code

**Comment by lbernardo** [comment]
Your code is compile?

**Comment by fsarihan** [comment]
Yes, when I build and tried it I got this result.

**Comment by lbernardo** [comment]
Can I know the number you are using?

**Comment by fsarihan** [comment]
905536873656   cc: 90 mcc: 286 mnc: 01

**Comment by wwsilin** [comment]
> --- Fixing the version error ---

Modify the file yowsup/env/env.py
Line:
DEFAULT = "s40"
For:
DEFAULT = "android"

Modify the file yowsup / env / env_android.py
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_VERSION = "2.17.16"

How: https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_s40.py

I hope I have helped

Thanks! it's helps for me!

**Comment by lbernardo** [comment]
You're welcome! @wwsilin

**Comment by debasishdebs** [comment]
Hi, I did as suggested, note that changes are just to env_android.py. I get bad_token error. and if I manually set the env to s40 by using "--env s40" I get old_version again!

**Comment by debasishdebs** [comment]
Okay, I simply copied your env directory, replaced mine, and it works, but with flag "-E android" in end, and my default is still "s40".

A quick doubt, how do in future, do I get MD5 classes?

Thanks

**Comment by mi-gri** [comment]
I tried the solution (changing to android environment, building new) but now I get the "no_routes" error. Any hints, how to solve that?
@debasishdebs where did you get the env directory, you are referring to?

**Comment by SaskuAc3** [comment]
Hi, I am new in Linux World. I changed the default entrys but how can I build new? 

thanks for helping!

**Comment by efendimansur** [comment]
Try this solution. It's worked for me.

https://github.com/tgalal/yowsup/issues/1905#issuecomment-306049877

**Comment by mi-gri** [comment]
@efendimansur Unfortunately it does not work for me:

$ python yowsup-cli registration -r sms --p 4917xxxxxxxx -C 49 -m 262 -n 01 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"4917xxxxxxxx","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
login: 4917xxxxxxxx

**Comment by fsarihan** [comment]
If you are getting this error, the problem may be related to the firewall. I received the error in my server, and then when I made the request from the local server, the sms was sent without any problem.

**Comment by tropit** [comment]
What it's mean by recompile?
After I made the change of android file and choose the android as default what should I do next?
I'm still get the old version error

**Comment by rezendemais** [comment]
Working Today !!!

 ```
   _MD5_CLASSES = "ox998VW0nBTueMVfjuZkmQ=="
    _VERSION = "2.17.212"
    _OS_NAME = "Android"
```

**Comment by debasishdebs** [comment]
@mi-gri : Please refer to the following link to get the env directory I'm referring to. : https://github.com/tgalal/yowsup/tree/master/yowsup/env

**Comment by Jnsa** [comment]
@rezendemais Hi guy! how i can get those info by myself? Thanks a lot :D

**Comment by rezendemais** [comment]
i don't know, don't remember where i see this code, but is a good idea know how do it !!!

**Comment by jeanggi90** [comment]
@Jnsa @rezendemais I guess here: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by debasishdebs** [comment]
@jeanggi90 but the link you provided returns a JSON like response. Which key represents what? I meant have you used it personally? Thanks

**Comment by debasishdebs** [comment]
I had to format my system, and somehoe forgot how I made it work last time :-P
Can someone help out again, as in, which version and MD5 classes working now?

**Comment by jeanggi90** [comment]
@debasishdebs `a`: MD5, `p`, `g`, `i`: Token Strings,`d`, `e`, `f`: Versions i guess.
But it did not work for me... I ended up using: 
```
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
 _VERSION = "2.17.16"
```

**Comment by debasishdebs** [comment]
@jeanggi90 that still gives me old_version error. What I did was that, I clonned the Git directory, replaces the credentials you provided, and then ran setup.py install. DOesnt seem to work. 

Did anyone else get it working recently? Also, if this credentials worked for you, then when did you set it up last, and what process did you follow?

**Comment by jeanggi90** [comment]
@debasishdebs I did it like 4 days ago. When running the instalation command you have to make sure that the env_android file is run and not the env_s40 by changind the default in the env file or by telling it in the registration command.

**Comment by debasishdebs** [comment]
@jeanggi90 I got it working, as in atleast I'm getting different error now. but the error cant be resolved I guess as I'm getting "Number is banned by Whatsapp"

**Comment by jeanggi90** [comment]
@debasishebs Probably you registered the number twice. You might want to try to contact the whatsapp suport and play stupid... I have heard that that works sometimes

**Comment by netovs** [comment]
Changing the _KEY or _MG5 **old_version** or **bad_token**

**Comment by xaviercobain88** [comment]
thank u @aslobo46

**Comment by vizuet** [comment]
thanks @aslobo46 
works for me 👍

**Comment by caldep** [comment]
I have the same error. I applied unsuccessfully all the suggestions given.

The versions that I have installed are the following:

OS: Fedora 27 64bits
Python 2.7.14
yowsup-cli v2.0.15
Using yowsup v2.5.7

but when trying to register the phone number, then it throws the error:

$ yowsup-cli registration --requestcode sms --phone 57########## --cc 57 --mcc 732 --mnc 102 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"57##########","status":"fail","reason":"old_version"}

**status: fail
reason: old_version
login: 57##########**


Please, help me.

Thanks.

**Comment by caldep** [comment]
hey! works!

I solved it with the following steps:

1. I cloned the yowsup repository again.
2. recompile with sudo python setup.py install
3. Finally I executed the registration command adding as last parameter -E android, being as follows:

yowsup-cli registration --requestcode sms --phone 57########## --cc 57 --mcc 732 --mnc 102 **--E android**

Thanks

**Comment by LaloRys** [comment]
I solved it by following these instructions 
[https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/#step2](url)

**Comment by MilanPrasad** [comment]
I am getting bad version error 

![error](https://user-images.githubusercontent.com/31763724/52530344-f17e3500-2d29-11e9-97d8-80456bea0570.JPG)
](url)
