### ISSUE TITLE
Registration fail old_version bad_token no_routes

### ISSUE THREAD

**Issue by debasishdebs** [tgalal/yowsup#2092]
Hi all,

So, I tried setting up yowsup to register my mobile number with whatsapp, so that I can use it from python, but I got all sorts of error after goign through numerous debug methods provided on various posts. some of things I tried and then successive errors are:
yowsup-cli registration --env s40 --requestcode sms --phone 9174xxxxxxxx --cc 91 --mcc 404 --mnc 86 --debug
I got the error that old version.

So I updated version to "2.17.210". as that was most latest version, and by just changing version, in env_android.py, I get error as 

BAD_TOKEN.

That maybe because I dont know MD5 corresponding to most recent version (2.17.210). 

I retried again the following command 
yowsup-cli registration --env s40 --requestcode sms --phone 9174xxxxxxxx --cc 91 --mcc 404 --mnc 86 --debug
and got NO_ROUTES.

After going through a lot many posts, it was suggested, I will need to add -E android in end, and did that also.

Once I did that, I'm back to bad_token.

Somehow I feel I need to update MD5 each time a new version is out. How do I know MD5 for each new version. ?

I saw a thread reply where it said to go and check https://github.com/mgp25/classesMD5-64 but I dont know how to use it?

Is there any easier way around?

Any help will be appreciated.

PS: If more information is required do let me know. I need to setup whatsapp for my python webapp, as I'm building my own Personal assistant!

Thanks

**Comment by lbernardo** [comment]
Hi, I'm posted soluction https://github.com/tgalal/yowsup/issues/2090

**Comment by debasishdebs** [comment]
Hi, I posted my comment on the same thread! The error still persists but with different issue. Hope we can continue our discussion over there, or here as you wish!

Thanks

**Comment by efendimansur** [comment]
@debasishdebs 
Try using this solution. It's worked for me.

https://github.com/tgalal/yowsup/issues/1905#issuecomment-306049877
