### ISSUE TITLE
general: Disconnected: Connection Closed

### ISSUE THREAD

**Issue by mijkenator** [tgalal/yowsup#2093]
i am able to request sms, and verify sms code, but cannot login

any suggestions?

`
[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e9.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="7953XXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
���c3:��5��
HEX:2409eded69eb81030de07fb99863333ae5f635f2
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
�*&����9^��̀1�H�)i����6���Ԋ'��q(=7%�O�W�Y�zX���p�.qPc��V���
HEX:96112a2690a1ee02ad395eaeaecc8031b848872969b483e913d836f44b08cf14a7d48a0327cbe78871283d3725854fc91bc15714f0591b46d27a1558dfe1e59270c52e715063c2e88056b6c5f9
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed

`

**Comment by brayanesc** [comment]
Same Problem

[offline]:/login 591########## lzK8chGn33WOQcUF3nShXls5jPY=
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="591########" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
٣��Ҫ�Ĵ����T��DE
HEX:d9a3dbd8d2aaccc4b482c0b18d541aa795114445
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
������SᴓgSa^�^��O�e�!���iU� �6nI��4_l���
                                              �N1#VG����>
�M�m��fk��H��
HEX:f1d9c5fe129dfb53e1b49367531c61101f5eb95eafc64fec659121ea19a6936955d52000b900366e49c2f634135f6cbfc2c20c824e3123561347ac1efda8ee3e0a994dfe6df491666bd8d71548e9dcf1
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed

**Comment by mijkenator** [comment]
what i found if i choose "s40" enviroment i can to login and send/recieve messages, but i cannot request sms-code and to verify code.

with "android" enviroment i can request sms code and verify this code. After i have switch enviroment to s40 and login.

Is it normal behavior or i am doing something wrong?

**Comment by simranjyotgill** [comment]
I might be wrong but as per my understanding, in env.android.py the version and _MD5_CLASSES are old values and need to be updated. The current whatsapp version is 2.17.79. But I don't know how to get corresponding value of _MD5_CLASSES.

**Comment by schlaubstar** [comment]
@simranjyotgill - could you please be so kind to give us some hints how to decode the content of your link?
You're telling that the latest version is 2.17.79 - in your link I just find some "array" with  "d":"2.17.215", "e":"2.16.12", "f":"2.11.634" which look like version numbers - but none of them matches the .79 - and If I assume that we're at 2.17.215 now - which of the keys is the corresponding _MD5_CLASS ? ;-)
Thanks a lot !

**Comment by emmekappa** [comment]
@schlaubstar are you registering with android and using the cli with S40? I ask this because I got banned yesterday using the same pattern.

**Comment by schlaubstar** [comment]
@emmekappa Sorry for the late reply: I actually use youwsoup only in the summertime when the temperature outside falls below the indoor temperature (at night) so I immediately get an information to open all the windows ;-) As it's getting cold in germany my raspi hasn't send a whatsapp for some time, but I just tested it by manually sending a message - and it works flawlessly.
As you said: I registered as android and did send as s40, but I assume they monitor behaviours (frequency and length of messages, as well as replys) and block you based on this. If you're just sending some messages a week, they most likely don't care. I don't know why this guys are so stupid excluding the IoT world from using Whatsapp

**Comment by gdperellon** [comment]
Hi, thank you for your work! Is great.
But I am geting now the same errors than others with _VERSION "2.17.426":

DEBUG:yowsup.layers.logger.layer:tx:",
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">



HEX3:b'0a8ab30c0093930af427a8cd75bcc9ee370722eb7edd81f4e5c9b8f88715149e37562c4b470f1d61e02c193c292db1ee284800384ce0342b5abbe436d8dcb5d90576e8ef6ade8415aa64685ba2'
</response>

PuTTYDEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
g than others:

**Comment by shreejayp95** [comment]
Getting same issue....

Have you guys resolved the problem?

This is my output while I tried to get connected:

	[offline]:/login 91xxxxxxxxxx W2zCtsJpU7CxA/xvAaeXxxV453E=
	DEBUG:yowsup.layers.network.layer:Connecting to e11.whatsapp.net:443
	DEBUG:yowsup.layers.logger.layer:tx:
	<stream:features>
	</stream:features>

	DEBUG:yowsup.layers.logger.layer:tx:
	<auth passive="true" user="91xxxxxxxxxx" mechanism="WAUTH-2">
	</auth>

	DEBUG:yowsup.layers.logger.layer:rx:
	<stream:features>
	</stream:features>

	DEBUG:yowsup.layers.logger.layer:rx:
	<challenge>
	��-�R
		  �|�P�K��
	HEX:fceb2daa521e0cf894087cd350c04ba60789e0a6
	</challenge>

	DEBUG:yowsup.layers.logger.layer:tx:
	<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
	�q��-1���`��a	�6PT�i9!~K�0��q�ɶ֛ң����ʒĢr'�e�~de���B8+N��X���x
	HEX:9571f6ac01082d31f7a3bd60e0c3610f09d11003365054e76939217e4bc53081b471a3c9b6d69bd2a38d02c0a9faca92c4a27216188fac27d60b65947e6465a08ba742382b4ea1af165899a5b578
	</response>

	DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
	general: Disconnected: Connection Closed

Thank You... :)

**Comment by igorznt** [comment]
Same problem. S40 registration does not work anymore and android keeps disconnecting =(
