### ISSUE TITLE
Sending video/images using yowsup-cli

### ISSUE THREAD

**Issue by xwanyiri** [tgalal/yowsup#2094]
Hello all, is there an easy way of sending video/image using yowsup-cli, or even yowsup itself?

**Comment by cristopher29** [comment]
#2071 #2086

**Comment by paulocoehlo1992** [comment]
import os
import subprocess

def login_1(num,user):

      subprocess.Popen("",os.chdir('D://whatsapp//Yowsup2//yowsup-master'),shell=True)

      os.popen("python ./yowsup-cli  demos -l 919191901223:7OBZ+ZuRzTLZDfq/oXMWseLlOqs=' -s "+num+"  \""+user+"\" ")
      print("it works")
      

how to modify above codefor sending media file?
