### ISSUE TITLE
Not getting Password "bad-param"

### ISSUE THREAD

**Issue by sushilm2011** [tgalal/yowsup#2095]
I tried registering I got the sms with verification code but when I am sending RegRequest getting a message as 
status:  fail
reason: bad-param 
login: 91XXXXXXXXXX (my number)
How can I fix this?

**Comment by efendimansur** [comment]
@sushilm2011 
try using this command: 
sudo yowsup-cli registration --register <yourcode> --mcc xxx --mnc xxx --cc xx --phone <yournumber> -d

**Comment by sushilm2011** [comment]
Worked!!
