### ISSUE TITLE
Cant Register

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#2099]
Hi, 
Problem solved.

**Comment by SaskuAc3** [comment]
[pip.txt](https://github.com/tgalal/yowsup/files/1050683/pip.txt)


i uploaded the pip.log as txt, that you can recognice the error  ( i think it is in the installation )

**Comment by mevinbabuc** [comment]
How ?

**Comment by samme13** [comment]
@SaskuAc3 Hi, how did you solve the problem??
