### ISSUE TITLE
Not receiving the messages

### ISSUE THREAD

**Issue by pablodlm** [tgalal/yowsup#2107]
I run the script in the tests and it seems to run fine but I am not receiving any message in WA

The command I am running is:

pmv@ubuntu:~/Desktop/django/estadoAvance/estado-avance$ yowsup-cli demos --config whatsapp_config.txt --send 5531490407 "Prueba"

And the result:

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

**Comment by destornillador** [comment]
Hi,

What is the content of your config file?

Have you registered the number correctly?

**Comment by schlaubstar** [comment]
Have a look at : #2093 and try to add -E s40 ! It seems that android/default are not working properly, when sending/receiving messages.
