### ISSUE TITLE
What will we do after June 30, 2017

### ISSUE THREAD

**Issue by majamatwo** [tgalal/yowsup#2108]
**Houston we are in trouble!!!**

#2079 
@tgalal
@mgp25 
Someone

**Comment by MuhammadHuzaifah** [comment]
i am in!

**Comment by angeldelrio** [comment]
I don't think repo owners will answer something here, this project is really abandoned in despite fancy readme updates that makes the look and feel this is a live project

**Comment by rodrigoorrego** [comment]
yowsup is abandoned? :(

i have hopes that they're working on it (new protocol) and not yet abandoned this project.. :/

i know it's just hopes... but i hope i'm right...

**Comment by themaddoctor** [comment]
Why? What happens june 30?

**Comment by lallex1848** [comment]
maybe there is still hope:
[Source: whatsappen.com](https://whatsappen.com/news/5087/whatsapp-extends-support-for-blackberry-and-nokia-s40-until-end-of-2017)

from that article:

> **Update 20/06/2017 08:35 CET:** After some speculation on Twitter, we’ve reached out to WhatsApp again. Co-founder Brian Acton confirms to Whatsappen.nl that Nokia S40 has end of life date 12/31/2018 and that this is for S40 only. BB/BBX = 12/31/2017

**Comment by JulioImolesi** [comment]
Great @lallex1848 .. Then next year we back to this discussion.. (:

**Comment by pabloruan0710** [comment]
https://faq.whatsapp.com/en/general/26000006/?category=5245235

**Comment by claudiorafaels** [comment]
Is it not necessary to make any changes to continue working after day 30?

**Comment by francwalter** [comment]
As I understand now, we have time up to December 31, 2018 when Nokia S40 support stopps.
