### ISSUE TITLE
Getting old version error.. 

### ISSUE THREAD

**Issue by HellowithShivamAgrawal** [tgalal/yowsup#2110]
ShivamAgrawal:~ shivamagrawal$ yowsup-cli registration --requestcode sms --phone 919033823189 --cc 91 --mcc 405 --mnc 30
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"919033823189","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 919033823189

**Comment by selfphp** [comment]
Same.....

env.py
---------
DEFAULT = "android"

env_android.py
----------------
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

_VERSION = "2.17.16"

**Comment by selfphp** [comment]
works...

used wrong env_android.py

**Comment by selfphp** [comment]
but cant't send messages.....

Error
#######################

DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f1fe0a59ad0>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f1fe0a59390>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="49XXXXXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
kyʓ$o▒t3▒7|▒▒=▒R▒▒
HEX:6b79ca93246f059a7433b0377cabfb3d8452a8ce
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
1<[▒㺚▒g▒2
          ▒x¬▒▒▒ݩE▒▒▒.cʴ▒H▒f{▒▒r▒cEe▒▒▒}▒▒.@▒▒D~Yi▒/عCU\▒▒$▒b▒
HEX:313c5bece3ba9a15c767f6320be48f78c2acc4ddf9dda945b8ad0eae2e63cab495481dde667bcceb729811634565ba1fc51de47d11b78f2e4080e3447ee87f5969be2fd8b94355195cd5f424c262f8
</response>

PuTTYDEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by nathanprins** [comment]
I've got the exact same problem

**Comment by wellscorp** [comment]
in my case still got "old_version" error
there is a new version?

**Comment by AlexSMGr54** [comment]
https://github.com/tgalal/yowsup/pull/2119

**Comment by althafas** [comment]
@gauravssnl  registration all worked weel.. but unable to send message any help ?

**Comment by gauravssnl** [comment]
Did you try sending message by using s40 env??? @althafas

**Comment by Hubobel** [comment]
many thanks, I did it on this way: I use your fork, register my Number with -E android and now I can send Messages via -E s40

1. I use not a mobile number, but my home number and the voice argument...here are the steps:
2. python yowsup-cli registration --requestcode voice --phone 49xxxxxxxxxx --cc 49 -E android
3. the phone rings and a woman tell you a 6 number code
4. python yowsup-cli registration --register THECODEFROMTHEWOMAN --phone 49xxxxxxxxxx --cc 49 -E android
5. the terminal (cli) give a password

nano config.bsp

you type:

cc=49 # Länderkennung 
phone=4912345678987 # Handynummer 
id= #not 
password= # thepasswordfrom cli

ctrl+c

and now, you be able to send messages:

sudo python yowsup-cli demos -c config.bsp -d -s 49xxxxxxxxxx "Ich bin ROOT, ich habs eben einfach drauf! WhatApp Nachrichten auf einem OrangePI mit Armbian aus der shell vom Mac aus gesendet" **-E s40**

**Comment by althafas** [comment]
@Hubobel did this worked for you ?

**Comment by althafas** [comment]
![untitled](https://user-images.githubusercontent.com/31475064/30105511-77ced0ba-9316-11e7-9772-1db969c9b699.png)

Please help

**Comment by althafas** [comment]
HI Brother. It worked thanks

**Comment by Hubobel** [comment]
👍

**Comment by althafas** [comment]
HI Hubobel, I was able to send txt messages successfully.. Have you tried sending images ? videos ?. If you could help it will be nice.
