### ISSUE TITLE
Unable to request code for Iphone

### ISSUE THREAD

**Issue by SonalOjha** [tgalal/yowsup#2115]
I am trying to request code for an Iphone device with following version

Iphone6S IOS version -- 10.3.2
Whatsapp Version -- 2.17.30

What environment specific details should be provided for it to work? 

    _VERSION = ""
    _OS_NAME= ""
    _OS_VERSION = ""
    _DEVICE_NAME = ""
    _MANUFACTURER = ""
    _TOKEN_STRING  = ""
    _AXOLOTL = True

**Comment by gauravssnl** [comment]
you can use "android" environment of yowsup for getting request code.i just tested it now.I just tested it now.
Edit env.py file & set DEFAULT = "android"
Set  env_android.py settings as : 
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.16"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

For sending messages ,use "s40" environment  by using option : -E s40 
@SonalOjha

**Comment by SonalOjha** [comment]
@gauravssnl : Thanks for the reply, I am now getting the following error while registering the request code

`# yowsup-cli registration --register xxxxxx --phone 91xxxxxxxxxx --cc 91 -E s40
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"91xxxxxxxxxx","status":"fail","reason":"temporarily_unavailable","retry_after":300}

status: fail
retry_after: 300
reason: temporarily_unavailable
login: 91xxxxxxxxxx`

**Comment by SonalOjha** [comment]
What if I have a number already registered via mobile app and want to use the same to run the demos. Will I be able to use it ? Believe yowsup needs login credentials, is there a way to retrieve / set one from existing whatspp profile?

**Comment by gauravssnl** [comment]
you can only use whatsapp at only one device at a time.if you login into phone,then registrattion code will not work in yowsup.which environment you are using for registeration ??

**Comment by SonalOjha** [comment]
@gauravssnl : I have created a config file with following details

`
cc=91
phone=91xxxxxxxxxx
id=
password=

`

**Comment by gauravssnl** [comment]
i do not use config file.you need to first get a request code then use these commands : 
yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456
After getting request code ,use this command  to get password (pw ) : 
yowsup-cli registration --register 123456 --phone 49XXXXXXXX --cc 49
now,use this password pw as password in yowsup-cli

**Comment by SonalOjha** [comment]
@gauravssnl 

This is what I am getting

INFO:yowsup.common.http.warequest:{"login":"91xxxxxxxxxx","status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":1534,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"login":"91xxxxxxxxxx","status":"fail","reason":"too_recent","retry_after":1588,"sms_wait":1588,"voice_wait":0}

status: fail
retry_after: 1588
reason: too_recent
login: 91xxxxxxxxxx

**Comment by SonalOjha** [comment]
@gauravssnl 

was seeing 

===========================================================
INFO:yowsup.common.http.warequest:{"login":"91xxxxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 91xxxxxxxxxx
===========================================================

On this changed the env_s40.py with 

    _VERSION = "2.17.76"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk{phone}"
    _AXOLOTL = True

And now I see 

===========================================================
INFO:yowsup.common.http.warequest:{"login":"91xxxxxxxxxx","status":"fail","reason":"temporarily_unavailable","retry_after":300}

status: fail
retry_after: 300
reason: temporarily_unavailable
login: 91xxxxxxxxxx
===========================================================

**Comment by jlguardi** [comment]
Your IP is banned. Try to renew IP or Just wait for an hour.

**Comment by SonalOjha** [comment]
@jlguardi  I tried after 14 hours and even changed the IP of the server which sends the request, no luck :( . I still see the same issue.

**Comment by gauravssnl** [comment]
well,i can not say,then.For me,yowsup is workinh on Terminal.Seee screenshot here : http://imgur.com/a/EFjX3

**Comment by SonalOjha** [comment]
@gauravssnl ok, thanks anyway.

**Comment by bhatasif17** [comment]
Hi
I am trying to use the C# version of WhatsAppAPI with IPhone 6. I am getting bad_token response. I am confused how can I see the timestamp appended to the token. How can I setup my IPhone 6 to successfully register my number?
Thanks
