### ISSUE TITLE
receiving encrypted images... is there a way to desencrypt?

### ISSUE THREAD

**Issue by rodrigoorrego** [tgalal/yowsup#2116]
i can now receive images... but the images I receive are always encrypted (i think so, since i can't open any)

how is the main procedure to proccess these images that yowsup developers usually do?

thanks in advance, if I get any answer....

**Comment by jlguardi** [comment]
Try to merge this part of code from my master.

**Comment by TheProKiller756** [comment]
@jlguardi I'm having the same problem, what part i have to merge?

**Comment by jlguardi** [comment]
@TheProKiller756 merge the protocol_media_dowloadable and all his children.

**Comment by TheProKiller756** [comment]
How can I do that? Sorry for my ignorance.
Thanks

**Comment by TheProKiller756** [comment]
@jlguardi How can I do that? Sorry for my ignorance.
Thanks

**Comment by rodrigoorrego** [comment]
@jlguardi I'm having the same problem, what part i have to merge?

i have the same question...

@TheProKiller756 merge the protocol_media_dowloadable and all his children.

where is it?

thanks! :)

**Comment by cinatic** [comment]
@jlguardi 
i merged it several days ago and everything worked fine but the written file is not an image.

i wonder where the cryptKey (576861747341707020566964656f204b657973) do you know where it was taken from?

**Comment by rodrigoorrego** [comment]
AND

INFO:yowsup.common.http.warequest:{"login":"555384354139","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 555384354139

trying to register I'm getting old version... it is just me?

thanks in advance! :)

**Comment by cinatic** [comment]
@rodrigoorrego 
for registration you can replace the values in ".../yowsup/env/env_android.py" with that:
```
    _MD5_CLASSES = "Ymq77xUybBCyFLvKaLTqRw=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.188"
```

then use this to create registration request (replace countrycode etc with your data):

`./yowsup-cli registration -E android --requestcode sms --phone xxxx --cc 49 --mcc 232 --mnc 10`

**Comment by jlguardi** [comment]
'576861747341707020566964656f204b657973'' key is for video
'576861747341707020496d616765204b657973' key is for image

**Comment by cinatic** [comment]
eh i am so stupid, and i also wondered why cryptKey is not set in the base class.
works very good now, to bad it maybe will stop working soon

@jlguardi 
if you are working on another version someday, i would really like to help i am very familiar with python and network protocolls

**Comment by TheProKiller756** [comment]
@cinatic @jlguardi So, how can i get working the echo demo to echo images? Thanks

**Comment by rodrigoorrego** [comment]
quoting @cinatic "if you are working on another version someday, i would really like to help i am very familiar with python"

me too... i'm very familiar with python (but not so much in internet protocols)

but i would like to help if needed

**Comment by rodrigoorrego** [comment]
where do i change the cryptkeys? thanks! :)

**Comment by tgalal** [comment]
yowsup 3.2.0+
