### ISSUE TITLE
Error: bad_token

### ISSUE THREAD

**Issue by leo9595** [tgalal/yowsup#2122]
I'm trying to install in Centos 6.7 and got the following:
When trying to install I run the following command:
Yowsup-cli registration -r sms -c /etc/zabbix/zap.conf

The **/etc/zabbix/zap.conf** file has the following settings:
```
Cc = 55
Phone = 553199xxxxxx
Id = My Test
Password =
```

And I get the following error:

> INFO: yowsup.common.http.warequest: {"login": "55xxxxxxx", "status": "fail", "reason": "bad_token"}

Before the bad_token error, I was giving the old_version error.
After I fix it using the solution I found here: [Here](https://github.com/tgalal/yowsup/issues/2090)
I'm getting the bad_token error.

How do I fix it?

**Comment by rgajjar** [comment]
Please explain more with commands

**Comment by leo9595** [comment]
@rgajjar I edited my comment by attaching new information! I hope you will help me.
