### ISSUE TITLE
yowsup old version issue while registering

### ISSUE THREAD

**Issue by ashokv54** [tgalal/yowsup#2128]
Hello all ,

i"m facing issue while registering my number and getting below error please help 

yowsup-cli registration -E android --requestcode sms --phone 91xxxx --cc 91 --mcc 404 --mnc 73 --debug
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.2

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=91&in=xxxxxxx&lc=GB&lg=en&sim_mcc=404&sim_mnc=073&mcc=404&mnc=073&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6790&rchash=098d0cf2b7568c99c6f04d8b41f6506bffc454be5ba7f5d24c6f0bf927d53019&anhash=%02%DA%F4%00%E9%19%C3%E4%C5%22%FA%9A%60%98je%03%3AH%CB&extexist=1&extstate=1&token=x2%2FYf5qLYN9DQrFbhj8SjzcPwEs%3D&id=%1C%EF%FAF%E4%15%AF%1E%D8%17%E4y%F1%88%13%F1%AA%9D%3B%2F
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=8500xxxxx&lc=GB&lg=en&sim_mcc=404&sim_mnc=073&mcc=404&mnc=073&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6790&rchash=098d0cf2b7568c99c6f04d8b41f6506bffc454be5ba7f5d24c6f0bf927d53019&anhash=%02%DA%F4%00%E9%19%C3%E4%C5%22%FA%9A%60%98je%03%3AH%CB&extexist=1&extstate=1&token=x2%2FYf5qLYN9DQrFbhj8SjzcPwEs%3D&id=%1C%EF%FAF%E4%15%AF%1E%D8%17%E4y%F1%88%13%F1%AA%9D%3B%2F
INFO:yowsup.common.http.warequest:{"login":"9xxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 91xxxx

**Comment by b3zi** [comment]
Hi

Fixing the version error:

   - Modify the file yowsup/env/env.py
    Line:
    DEFAULT = "s40"
    For:
    DEFAULT = "android"

  -  Modify the file yowsup / env / env_android.py
    _MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
    _VERSION = "2.17.16"

**Comment by luciusbsd** [comment]
Hi.
Dont work for me.
Some ideia?

INFO:yowsup.common.http.warequest:{"login":"55xxxxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 55xxxxxxxxxxx

**Comment by b3zi** [comment]
Did you get the latest update?

**Comment by alexandreheidemann** [comment]
I changed the version and md5 as commented. I received the SMS.
But the persistent error at the time of registration:
Registration yowsup-cli --register xxx-xxx --phone 55xxxxxxxxxx --cc 55 --mcc 228 --mnc 02

Status: failed
Reason: old_version
Login: 55xxxxxxxxxx

**Comment by Vancer** [comment]
Same issue here, even after modifying what @b3zi said.

**Comment by luciusbsd** [comment]
Helo,
I can get code, but i cant send message.

root@dev:~/yowsup# ./yowsup-cli demos -s 559291700550 "teste" -c zap.conf  --debug
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module yowsup was already imported from /root/yowsup/yowsup/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0xa1b2b6c>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0xa1adfec>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="559294192274" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
????՗???n??5U
HEX:bb82cde6d5978ab8986e121be4b916d202e93555
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
?ǜ;??ￎ????X??i-????ՂP?
?q??g?J??g?%U
pu???ֿ ?_??:F?'yG.,?S´?;?&_
HEX:cec79c3b07adc0efbf8e8afea3ff58faac692dddcceaced58250810aa87183e767904afbae67bc25550a0f7075fcf3ded6bf200700aa0f5f8d178d3a469f7f2779472e2cbd0553c2b4ba3b8a265f
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by Vancer** [comment]
Okay so I think i figured the issue out, it has nothing to do with the version or either "s40" or "android". **It is the way of execution** 
Make sure you execute it like that `**./**_yowsup_ `

**Comment by luciusbsd** [comment]
It works. For the registration I use "android" env, to send/receive messages I use "s40".
Thnks.

**Comment by ashokv54** [comment]
still getting same issue can anyone help here

**Comment by shubhamivane** [comment]
@ashokv54 change yowsup/env/env_android.py file with this https://drive.google.com/open?id=0BxKVizAlO_Fwa2EtMF9fNW96NFE and add -E android at the end of command then run I think it should work.

**Comment by CH1989** [comment]
i have the same problem. But the file from your cloud doesn't fix it...
Somebody an other idea?

**Comment by ashokv54** [comment]
Thank you bro the issue is resolved now .

**Comment by ashokv54** [comment]
but unable to register getting below error

[yowsup-master]# ./yowsup-cli registration -c ./yowsup.config -R 542-669 --deb                                                                ug

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.11 S40Version/14                                                                .26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=91&in=8500257454&id=NT%F7%A1%96%B5%82p%F7%DE%3F%17%13EQ%89gZ%DEE&c                                                                ode=542669&lc=GB&lg=en&mistyped=6&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=20625&rchash=85363d50f1                                                                1bbfff3d44bd90da44650f8e9f4c614e9e8d7ed9216e3cadf5619a&anhash=b9b182d797ee96689b4c5e2b2c3e593d&extexist=                                                                1&extstate=1
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=91&in=8500257454&id=NT%F7%A1%9                                                                6%B5%82p%F7%DE%3F%17%13EQ%89gZ%DEE&code=542669&lc=GB&lg=en&mistyped=6&simnum=1&s=&copiedrc=1&hasinrc=1&r                                                                cmatch=1&pid=20625&rchash=85363d50f11bbfff3d44bd90da44650f8e9f4c614e9e8d7ed9216e3cadf5619a&anhash=b9b182                                                                d797ee96689b4c5e2b2c3e593d&extexist=1&extstate=1
INFO:yowsup.common.http.warequest:{"login":"918500257454","status":"fail","reason":"temporarily_unavaila                                                                ble","retry_after":300}

status: fail
retry_after: 300
reason: temporarily_unavailable
login: 91123123123

**Comment by yerunkar11** [comment]
I am having the same issue
