### ISSUE TITLE
Nokia Symbian S60 will no longer be supported by Whatsapp 

### ISSUE THREAD

**Issue by claudiorafaels** [tgalal/yowsup#2132]
As of next Friday the Nokia Simbian S60 will no longer be supported by Whatsapp (https://faq.whatsapp.com/en/general/26000006/?category=5245235). How does yowsup work? Will it stop working? Or can we make some changes that will let you in the air for some more time?

**Comment by JulioImolesi** [comment]
Im literally waiting for tomorrow...

**Comment by Domeax** [comment]
Im pretty sure yowsup works with Nokia S40, which won't be able to use after December 31, 2018.

**Comment by schoerg** [comment]
Still working here.

@claudiorafaels you could just use yowsup, then you'll see when it stops working.
