### ISSUE TITLE
Subscribe Problem!!

### ISSUE THREAD

**Issue by ekartal** [tgalal/yowsup#2136]
Hello there;

I have a problem about subscription. We have login successfully, after we sync numbers. and then i do presence available. after I send subscribe request for numbers.. my problem is in this point. If these number count is higher then 300, i get receive some numbers, not all.. i can get data(when the number is online or unavailable) for 50-60 numbers (maybe).. 

this api does not work a lot of number?

is there any people who have same problem?

Best.

**Comment by thatskriptkid** [comment]
@ekartal Hi! You do it by using cli or written python script?

**Comment by vjyanand** [comment]
@ekartal Do you manage to resolve this issue?
