### ISSUE TITLE
yowsup.layers.interface.interface:Stream Error

### ISSUE THREAD

**Issue by fsarihan** [tgalal/yowsup#2139]
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
ERROR:yowsup.layers.interface.interface:Stream Error type: xml-not-well-formed
{'xml-not-well-formed': None}

what that mean? and what function triggered this?

**Comment by pabloruan0710** [comment]
i have this issue too.

**Comment by fsarihan** [comment]
any?

**Comment by MaXL130** [comment]
Im am also facing this problem.
