### ISSUE TITLE
Anyone use Virtual Number Service?

### ISSUE THREAD

**Issue by CalipsX** [tgalal/yowsup#2141]
Hi ,

Anyone use virtual number service which company best ?? (after register Non-block problem )

Thanks

**Comment by coolnickname** [comment]
I use Hollandsnieuwe.

**Comment by hyaslan** [comment]
@coolnickname Hollandsnieuwe virtual number service ? This company have just sim card i check web site

**Comment by coolnickname** [comment]
Oh, I see what you mean. They don't sell those. Sorry.

**Comment by inancatil** [comment]
I used textnow.com with the "539" area code. And chose voice option while registering.

**Comment by dawidvdh** [comment]
@inancatil also attempting to use textnow could you tell me what details are you using for the Country and Network code? been trying this:

`yowsup-cli registration -r voice --p 539xxxxxxx  -C 539 -m 310 -n 260`

with no luck

**Comment by inancatil** [comment]
You should use +1 for -C so number is +1539xxxxxxx and -C is 1. Not remember what i wrote for -m and -n sorry. I spend 1 week to register trying almost all "old version" problem solutions.

**Comment by rgajjar** [comment]
@inancatil Number is showing banned !, Don't try
