### ISSUE TITLE
INFO:yowsup.common.http.warequest{"login":"5535XXXXXXXX","status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by Eduardo-Cezar** [tgalal/yowsup#2142]
INFO:yowsup.common.http.warequest{"login":"5535XXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5535xxxxxxxx

Who knows how to solve this mistake?

**Comment by geovannyAvelar** [comment]
Please check @lbernardo reply to #2090
