### ISSUE TITLE
{"login":"880xxxxxxxxxxx","status":"fail","reason":"old_version"}

### ISSUE THREAD

**Issue by arsohel** [tgalal/yowsup#2143]
yowsup-cli  v2.0.15
yowsup      v2.5.2

{"login":"880xxxxxxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 880xxxxxxxxxxx

Please help someone to fix this issue......

**Comment by dzfweb** [comment]
+1

**Comment by geovannyAvelar** [comment]
Please check @lbernardo reply to #2090

**Comment by arsohel** [comment]
Finally its working... thanks a lot@geovannyAvelar

**Comment by arsohel** [comment]
status: ok
kind: free
pw: 8+Mt3SqArZ7E9+xVXPXOk4FS95k=
price: US$0.99
price_expiration: 1502658483
currency: USD
cost: 0.99
expiration: 4444444444.0
login: 8801708166608
type: new



now how to login every time and send msg

**Comment by Mbonea-Mjema** [comment]
its not working for me

**Comment by caikpigosso** [comment]
yowsup it's working ?
