### ISSUE TITLE
Discarding queued node without receipt

### ISSUE THREAD

**Issue by soyungenio** [tgalal/yowsup#2151]
When i send to group chat some people get message without any problems, but some people get message with the text "Waiting for this message this may take a while". And in the logs much of sending acks and сontinuously "Discarding queued node without receipt". And in logs it swears on some number with error "('7**********', <axolotl.identitykey.IdentityKey object at 0x7fe7b8e61080>)".

**Comment by eirmd** [comment]
Still having this problem? any solution for this?

**Comment by soyungenio** [comment]
Yes, still have

**Comment by gsmsepp** [comment]
still have exactly this problem...

**Comment by tgalal** [comment]
97e915691bf8272f9d2e2a87a62e82fb034ed4d5
