### ISSUE TITLE
Some questions about simulating Whatsapp correctly

### ISSUE THREAD

**Issue by coolnickname** [tgalal/yowsup#2154]
I decided to number them to make it easier to read.

1. I've heard that whenever a group is updated (A participant added or removed) I should update the keys. That raises the questions; How can I detect this happening? And how can update the keys?

2. How can I set my presence as online/offline? And what is a recommended maximum online time without Whatsapp getting suspicious?

3. How can I set my presence as typing or paused from typing to a certain chat? And can I set myself un-typing manually, or do I have to actually send a message to do that automatically?

4. On a slightly unrelated note, if I have the JID of a user, how can I get the username they gave themselves when registering their Whatsapp account? And if I have the JID of a group, how can I get the participants and see who is an admin?

If anyone could point me to any documentation that migh have this info I'd greatly appriciate that too.

**Comment by Alejandro94elx** [comment]
I have 10 blocked numbers. Today: I only registered the number and they have blocked.

It's a lottery.

**Comment by coolnickname** [comment]
Maybe they noticed a lot of suspicious activity from your IP and flagged it?

**Comment by Domeax** [comment]
This does not answer all your question but i think it can help you:
This code is running since mid 2016.
```
layer.py:

# -*- coding: utf-8 -*-

from yowsup.layers.interface												import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_messages.protocolentities						import TextMessageProtocolEntity
from yowsup.layers.protocol_receipts.protocolentities						import OutgoingReceiptProtocolEntity
from yowsup.layers.protocol_acks.protocolentities							import OutgoingAckProtocolEntity
from yowsup.layers.protocol_presence.protocolentities.presence_available	import AvailablePresenceProtocolEntity

class EchoLayer(YowInterfaceLayer):
    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        self.toLower(AvailablePresenceProtocolEntity())
        self.toLower(messageProtocolEntity.ack(read=True))
        outgoingMessage = TextMessageProtocolEntity("The answer to life the universe and everything", to = "###")
        self.toLower(outgoingMessage)
        return

    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        self.toLower(entity.ack())

run.py:

from yowsup.stacks import  YowStackBuilder
from layer import EchoLayer
from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env import YowsupEnv
      
credentials = (####, ###)

if __name__==  "__main__":
    stackBuilder = YowStackBuilder()

    stack = stackBuilder\
        .pushDefaultLayers(True)\
        .push(EchoLayer)\
        .build()

    stack.setCredentials(credentials)
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
    stack.loop() #this is the program mainloop

```

**Comment by coolnickname** [comment]
@Domeax Interesting it's managed to run for so long without getting banned. Does
`stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))`
Show the bot as online?

**Comment by Domeax** [comment]
@coolnickname 
I think it is the AvailablePresenceProtocolEntity which shows WA that the client is online.
*self.toLower(AvailablePresenceProtocolEntity())* (in def onMessage)

**Comment by coolnickname** [comment]
Ah, cheers!

**Comment by nurdan** [comment]
For question number 2 => Just Login to yowsup then use "/presence available" command
, question number 3 => Same like number two but use "/state typing" command
, question number 4 => use "/groups list" command
and, question number 1 => I don't know the answer

**Comment by coolnickname** [comment]
@nurdan I'm not using Yowsup-cli, I'm using the Yowsup library.

**Comment by coolnickname** [comment]
To answer my own questions,

1. Getting the group chat info could probably be done with this:
https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_groups/protocolentities/iq_groups_info.py

2. Setting online/offline:
https://github.com/tgalal/yowsup/tree/master/yowsup/layers/protocol_presence/protocolentities

3. Setting composing/paused:
https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_chatstate/protocolentities/chatstate_outgoing.py

4.  Maybe getting contact info? I haven't looked into this yet:
https://github.com/tgalal/yowsup/tree/master/yowsup/layers/protocol_contacts/protocolentities
