### ISSUE TITLE
Whats the problem?

### ISSUE THREAD

**Issue by murciaelx** [tgalal/yowsup#2155]
> general: Login Failed, reason: not-authorized
> Auth Error, reason not-authorized
> 

The password is OK, the number OK, the ID ok..
Not is banned because after see this message i  put the account in my mobile phone and works fine

**Comment by xwanyiri** [comment]
try requesting new password by reregistering

**Comment by coolnickname** [comment]
As far as I know 
> not-authorized
means you're banned. Could perhaps the IP be banned? Have you registered/botted with multiple numbers from the same IP?

**Comment by xwanyiri** [comment]
Confirmed! Tried to register a number showing the 'not authorized'
error, got a reply that it's banned :(

**Comment by nurdan** [comment]
Just from my old experience (one year ago). Just wait about a half or one day before you use your registered number, then it will ok to login/online/sending messages
