### ISSUE TITLE
not-authorized when using demo sendmessage (landline number)

### ISSUE THREAD

**Issue by SEBv15** [tgalal/yowsup#2156]
When I tried using the yowsup-cli demo sendmessage tool right after the registration, I got an `Authentication Error: not-authorized`. 
Like I said in the title, my number is a landline and the registration worked (I think) after I spend some time to figure out how to use android for it.

The demo command is
`yowsup-cli demos -s "1XXXXXXXXXX" "Message test" -E android -c ~/config.yowsup`

And for the registration I got this back
```
INFO:yowsup.common.http.warequest:{"status":"ok","login":"49XXXXXXX","type":"new","pw":"xxxxxxxxxxxxxxxx=","expiration":4444444444.0,"kind":"free","price":"0,89 \u20ac","cost":"0.89","currency":"EUR","price_expiration":1503395192}

status: ok
kind: free
pw: xxxxxxxxxxxxxx=
price: 0,89 €
price_expiration: 1503395192
currency: EUR
cost: 0.89
expiration: 4444444444.0
login: 49XXXXXXXXXX
type: new
```
Also I suppose the number isn't blocked since I was able to register it on my phone afterwards

**Comment by etinin** [comment]
you've been banned

**Comment by nurdan** [comment]
Just from my old experience (about one year ago). Just wait about a half or one day before you use your registered number, then it will ok to login/online/sending messages

**Comment by SEBv15** [comment]
Thank you.
After I waited some hours and removed a zero after the country code it worked.

**Comment by weberxw** [comment]
I'm getting 'not authorized' error after succesfuly register ... I'm not banned either... any tips?

**Comment by SEBv15** [comment]
For me it was, like I already wrote just waiting, but you also have to use the right number for authentication. When you register your number WhatsApp returns it and removes unnecessary zeros. You have to use that number.

btw. I'm not suddenly an expert. That's just what worked for me.

**Comment by weberxw** [comment]
in Brazil we have 9 digits number.... I'm thinking this is the problem.... but idk about this zero issue.... i'm registering like this 5548988xx22xx
