### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by supertim123** [tgalal/yowsup#2160]
Hi Gents

When I try to register, I get an error saying:

INFO:yowsup.common.http.warequest:{"login":"xxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version

Any advise please?

Thanks!

**Comment by coolnickname** [comment]
Go to yowsup/env/env_android.py and change:

> _VERSION = "2.17.251"
_MD5_CLASSES = "KoK/8Dy+k1yOP80RObNznw=="

then add 

> -E Android

at the end of the command you're using to register.

**Comment by ruanduarte** [comment]
@coolnickname , this worked for me. Thank you.

**Comment by Neeeff** [comment]
my whatsapp version is... 2.17.265 how do i know md5 classes?

**Comment by supertim123** [comment]
Thanks!

**Comment by BenoTamales** [comment]
@coolnickname  can you help me
i'm trying to do this proyect to the school
and i have the same probleam

**Comment by BenoTamales** [comment]
@supertim123 
@ruanduarte 
i'm trying to do it

can you help me please???

**Comment by ruanduarte** [comment]
@BenoTamales i just did what @coolnickname sad and then run in command line:

python yowsup-cli.py registration --requestcode sms --phone xxxxxxxxxxxxxx --cc xx --mcc xxx --mnc xx

where you should replace "x" for your correct information.

**Comment by BenoTamales** [comment]
@ruanduarte i think i dont do correctly 
the part of @coolnickname 

i need to remplace this..
_VERSION = "2.17.251"
_MD5_CLASSES = "KoK/8Dy+k1yOP80RObNznw=="
for this...
-E Android????

the original file is ...
from .env import YowsupEnv
import base64
import hashlib


class AndroidYowsupEnv(YowsupEnv):
    _SIGNATURE = "MIIDMjCCAvCgAwIBAgIETCU2pDALBgcqhkjOOAQDBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNV" \
        "BAcTC1NhbnRhIENsYXJhMRYwFAYDVQQKEw1XaGF0c0FwcCBJbmMuMRQwEgYDVQQLEwtFbmdpbmVlcmluZzEUMBIGA1UEAxMLQnJ" \
        "pYW4gQWN0b24wHhcNMTAwNjI1MjMwNzE2WhcNNDQwMjE1MjMwNzE2WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5" \
        "pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExFjAUBgNVBAoTDVdoYXRzQXBwIEluYy4xFDASBgNVBAsTC0VuZ2luZWVyaW5nMRQwEg" \
        "YDVQQDEwtCcmlhbiBBY3RvbjCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+AtlEm" \
        "aUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb+DtX58aophUPBPuD9tPFHsMCN" \
        "VQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jr" \
        "qgvlXTAs9B4JnUVlXjrrUWU/mcQcQgYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO" \
        "8yk8b6oUZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GFAAKBgQDRGYtLgWh7zyRtQainJfCpiaUbzjJuhMgo4fVWZIvXHaS" \
        "HBU1t5w//S0lDK2hiqkj8KpMWGywVov9eZxZy37V26dEqr/c2m5qZ0E+ynSu7sqUD7kGx/zeIcGT0H+KAVgkGNQCo5Uc0koLRW" \
        "YHNtYoIvt5R3X6YZylbPftF/8ayWTALBgcqhkjOOAQDBQADLwAwLAIUAKYCp0d6z4QQdyN74JDfQ2WCyi8CFDUM4CaNB+ceVXd" \
        "KtOrNTQcc0e+t"

    _MD5_CLASSES = "ry9Xz6kVioQctwA3G9z62Q=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.12.556"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
        return self.__class__._DEVICE_NAME

    def getBuildVersion(self):
        return self.__class__._BUILD_VERSION

    def getManufacturer(self):
        return self.__class__._MANUFACTURER

    def isAxolotlEnabled(self):
        return self.__class__._AXOLOTL

    def getToken(self, phoneNumber):
        keyDecoded = bytearray(base64.b64decode(self.__class__._KEY))
        sigDecoded = base64.b64decode(self.__class__._SIGNATURE)
        clsDecoded = base64.b64decode(self.__class__._MD5_CLASSES)
        data = sigDecoded + clsDecoded + phoneNumber.encode()

        opad = bytearray()
        ipad = bytearray()
        for i in range(0, 64):
            opad.append(0x5C ^ keyDecoded[i])
            ipad.append(0x36 ^ keyDecoded[i])
        hash = hashlib.sha1()
        subHash = hashlib.sha1()
        try:
            subHash.update(ipad + data)
            hash.update(opad + subHash.digest())
        except TypeError:
            subHash.update(bytes(ipad + data))
            hash.update(bytes(opad + subHash.digest()))
        result = base64.b64encode(hash.digest())
        return result

________________________________________________
is env_android.py

i need to close Terminal when i do changes?

**Comment by BenoTamales** [comment]
@ruanduarte thanks to repply 
i really need help 
and make this...

**Comment by ruanduarte** [comment]
@BenoTamales You have to change the values of the _VERSION and _MD5_CLASSES var.
find the line with _VERSION var and replace this line by:
_VERSION = "2.17.251"

And then, find the line with the _MD5_CLASSES var and replace this line by:
_MD5_CLASSES = "KoK/8Dy+k1yOP80RObNznw=="

Then save the file and go to Terminal and do:
python yowsup-cli.py registration --requestcode sms --phone xxxxxxxxxxxxxx --cc xx --mcc xxx --mnc xx

search in the manual on this project, if you don't know what replace in theses "x".

the codes of your phone or/and country you will find with a quick search in google.

**Comment by BenoTamales** [comment]
@ruanduarte  
:( again fail, old_version
if you can contact me this is my email
al114998@alumnos.uacj.mx
