### ISSUE TITLE
Having problem sending message to group

### ISSUE THREAD

**Issue by eirmd** [tgalal/yowsup#2162]
Hello, anyone having problem sending message to group? 

Sending message to the group with only 2 participants:
Message received.

Sending message to the group with 23 participants:
"_Waiting for this message. This may take a while. Learn more._" 
 
Sending message to the group with 200 participants:
**yowsup-cli demos -c yowsup.config -s xxxxx-xxxxx Hello -E s40**
```
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
```

With --moxie, _INFO:yowsup.demos.sendclient.layer:Message sent_
No error, but cannot see the message:
**yowsup-cli demos -c yowsup.config -M -s xxxxx-xxxxx Hello -E s40**
```
INFO:yowsup.demos.sendclient.layer:Message sent
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate



Yowsdown
```

Any idea guys? Thanks.

**Comment by soyungenio** [comment]
The same problem with "Waiting for this message. This may take a while. Learn more." while sending to group

**Comment by marcoblacks** [comment]
For me the same problem with "Waiting for this message..." but also for a single destination number !! Not a group... Can you help me please! Thanks in advance!
Marco

**Comment by coolnickname** [comment]
Try to update the key, and if it's a single person sync the contact.

**Comment by soyungenio** [comment]
I tried to delete .yowsup folder but it didn't help(:

**Comment by eirmd** [comment]
Have you try register and using different number?

**Comment by soyungenio** [comment]
Yes, i tried

**Comment by eirmd** [comment]
@soyungenio have you try login with command line interface?

**Comment by soyungenio** [comment]
@eirmd yes, i tried. I tried with yowsup-cli and without, there is also problem with sending to big groups 50-200 members with "Waiting for this message......" and "Discarding queued node without receipt". I described it here #2151.

**Comment by eirmd** [comment]
Hope someone can clarify this for us.

**Comment by gsmsepp** [comment]
Also have the problem: message to one person works, if the person is in a group of 4 peoples it doesn't work. When sending a (short) message to the group only the administrator and one other person receive it.
Always the same two person get "waiting for ....". Around 3 month ago I had no problems..

**Comment by coolnickname** [comment]
> Also have the problem: message to one person works, if the person is in a group of 4 peoples it doesn't work. When sending a (short) message to the group only the administrator and one other person receive it.
Always the same two person get "waiting for ....". Around 3 month ago I had no problems..

Try sync the keys of the group and the people in the group. Also, I really recommend using jut Yowsup and not Yowsup-cli.

**Comment by gsmsepp** [comment]
hi coolnickname,
sorry for my question, what du you mean with sync the keys(how can I do it?).
And I only know registration or sending messages with yowsup-cli commands.

**Comment by gsmsepp** [comment]
..new facts:
-first I checked number and get output number(is OK), but problem still there
   sudo yowsup-cli demos -c /yowsup/config -S 43664xxxxxxx

-then I connect interactiv and send a message to the Group:
                     sudo yowsup-cli demos --yowsup -c /yowsup/config
                     /L    (for Login)
                     /message send 43664xxxxxxx-1458418519 "test message"
        ->Messages received by all Group members!

And now my old way to send messages works again:
                 sudo yowsup-cli demos -s 43664xxxxxxx-1458418519 "test 15:20" -c /yowsup/config

I don't know why, maybe someone has an explanation for it....

**Comment by coolnickname** [comment]
Maybe the send demo synces the keys

**Comment by gsmsepp** [comment]
...finally I have only a small issue:
 every 10 til 15 messages  all members of the group get once "waiting for..." (all get it at the same time)

->see also  #2078

**Comment by soyungenio** [comment]
Also i tried use only yowsup, not yowsup-cl, all the same problem(; coolnickname, could you tell how to send demo synces the keys?

**Comment by coolnickname** [comment]
I never really used the demos, so I don't know.On 5 Sep 2017 7:56 pm, Marat Gaptullin <notifications@github.com> wrote:Also i tried use only yowsup, not yowsup-cl, all the same problem(; coolnickname, could you tell how to send demo synces the keys?

**Comment by holgerschochwitz** [comment]
Hi,
i insert in the sendclient/layer.py this:
@ProtocolEntityCallback("receipt")
def onReceipt(self, entity):
    self.toLower(entity.ack())
and now all get the massages
Who can test it?

**Comment by majamatwo** [comment]
@holgerschochwitz  I tried your code but I do not work

**Comment by eirmd** [comment]
@holgerschochwitz Tried but still not working. With -M, no message at all and without -M, "Waiting for this message. This may take a while"

**Comment by coolnickname** [comment]
SYNC THE FUCKING KEYS ITS NOT THAT HARD

**Comment by eirmd** [comment]
oh, thanks @coolnickname
btw, how to sync? kindly if anyone know how to sync using demo, please share with me. find on the net, but show nothing. i am sorry, totally noob here. delete axol db, and send msg.. still same. thanks for you help..

**Comment by fwmarcel** [comment]
#2244

**Comment by coolnickname** [comment]
@eirmd Deleting the axolotl database is the _LAST_ thing you should ever do! It's positively the opposite of syncing keys!

**Comment by fwmarcel** [comment]
I still have this problem

**Comment by eirmd** [comment]
@fwmarcel yup, me too. we still having this problem. related with sign keys. tried with yowsup-cli demos and yowsup only, still same. cannot send long messages. but no problem with interactive yowsup. anyone can send us working layer script, thanks.

**Comment by fwmarcel** [comment]
@eirmd my question is: Why are some Messages are working and why some not ?
I guess its a problem in groups with many people ...

**Comment by eirmd** [comment]
@fwmarcel no for me.. even with 2 people in the group still having problem to send long msg.. as you know, this is about encryption and sign key problem. you can pm me and we can try it out on whatsapp..

**Comment by nurdan** [comment]
BTW.. Where is Mr.T.Galal yo? this is old probem but still no solver.. I have the same problem lho..

**Comment by eirmd** [comment]
tried with layer script..the result, same...
