### ISSUE TITLE
Paying for your help with this question! Please assist!

### ISSUE THREAD

**Issue by supertim123** [tgalal/yowsup#2168]
Hi,

What is the quickest automatic way that is least instructive, ie: not sending a message - to verify a phone number has whatsapp?

I can pay you for your help with this question!

Thanks!

**Comment by Nicos-git** [comment]
Have you had a look at this?
https://www.lorankloeze.nl/2017/05/07/collecting-huge-amounts-of-data-with-whatsapp/

**Comment by supertim123** [comment]
@Nicos-git thank you for your response, I have had a look at this but I cannot make this work on the command line,

I have almost all I need for the "project" of confirming WhatsApp users - but I need to know which  is the best direction to go in.

**Comment by sealabr** [comment]
post this on bountysource.com, I can help you.
