### ISSUE TITLE
registration: no_routes

### ISSUE THREAD

**Issue by plehr** [tgalal/yowsup#2170]
After problem #2163 I've the following problem:

`status: fail
retry_after: 3600
reason: no_routes
login: 4917461xxxxx`

My network carrier is vodafone: MCC: 262 and tried mnc 02, 42, 04, 09.
Do you have a solution? After each request I get 'no_routes'.

Version:
yowsup-cli  v2.0.15
yowsup      v2.5.2

**Comment by rmarcenaro** [comment]
@plehr Same case, same version. Did you solve it?
