### ISSUE TITLE
how to re register my mobile no.

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2171]
Greetings of the day.
hello everyone my no register now and how can i re register my no. please guide me. 
Thanks
Manoj Rao.

**Comment by eirmd** [comment]
Please read here first: https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0

Example:
```
yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456
yowsup-cli registration --register 123456 --phone 49XXXXXXXX --cc 49
```

**Comment by coolnickname** [comment]
You just register it exactly the same as the first time. Once you generate a new password, the old one is voided.
