### ISSUE TITLE
Yowsup Client removed from the Group soon after being added

### ISSUE THREAD

**Issue by drmaposa** [tgalal/yowsup#2172]
HI

I developed a bot using Yowsup. All is working well. I can create a Group using the bot account, add people and interact withing that group. 

However if I ask other people to add the bot number, or myself adding the bot number to other groups, it will leave upon being added in a fraction of a second.

What normally causes this?

**Comment by coolnickname** [comment]
You might need to send some sort of response protocolentity to confirm the bot is being added, similar to an ack. Try to look into the protocolentity class of the entity that is received when the bot is added to a group and see if there are any methods that return another protocolentity.On 26 Jul 2017 4:42 pm, drmaposa <notifications@github.com> wrote:HI
I developed a bot using Yowsup. All is working well. I can create a Group using the bot account, add people and interact withing that group.
However if I ask other people to add the bot number, or myself adding the bot number to other groups, it will leave upon being added in a fraction of a second.
What normally causes this?

**Comment by drmaposa** [comment]
How Do I do that

The server output if I monitor is is just saying

_layer.py_      [INFO][2017-07-26 15:09:12,873] Group leave success

The Yowsup will leave the group when it starts running. That is nothing will happen until i run the run.py

**Comment by coolnickname** [comment]
Could you post your code?On 26 Jul 2017 5:14 pm, drmaposa <notifications@github.com> wrote:How Do I do that
The server output if I monitor is is just saying
layer.py      [INFO][2017-07-26 15:09:12,873] Group leave success
The Yowsup will leave the group when it starts running. That is nothing will happen until i run the run.py
