### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by endermrn2** [tgalal/yowsup#2174]
root@endermrncontrol:~/bot/yowsup# yowsup-cli registration --requestcode call --phone 17162722531 --cc 1 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"17162722531","status":"fail","reason":"bad_param","param":"method"}

status: fail
param: method
reason: bad_param
login: 17162722531
root@endermrncontrol:~/bot/yowsup#

**Comment by endermrn2** [comment]
yowsup-cli registration --requestcode call --phone 17162722531 --cc 1
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"17162722531","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 17162722531
root@endermrncontrol:~/bot/yowsup#

**Comment by coolnickname** [comment]
Your forgot your mcc and mnc. Please check out the example command on the wiki.

Op 27 juli 2017 20:34:31 +02:00, schreef endermrn2 <notifications@github.com>:

**Comment by endermrn2** [comment]
this number is online i dont know
