### ISSUE TITLE
Block problem if solve this i paid 

### ISSUE THREAD

**Issue by CalipsX** [tgalal/yowsup#2177]
Hi All ,

I have  new 20 numbers from local gsm company. I am using proxy for this. I am changing the ip address daily .I am checking just last seen . But my numbers are blocked after register  2-4 days.

I'm looking for a solution for this. ?? 

If you solve this problem i paid 

Thanks

**Comment by coolnickname** [comment]
Switching IP daily is not normal. Also, whatsapp might be able to detect proxies.For the rest, we can't say anything without seeing your code.On 29 Jul 2017 9:51 pm, hyaslan <notifications@github.com> wrote:Hi All ,
I have  new 20 numbers from local gsm company. I am using proxy for this. I am changing the ip address daily .I am checking just last seen . But my numbers are blocked after register  2-4 days.
I'm looking for a solution for this. ??
If you solve this problem i paid
Thanks

**Comment by CalipsX** [comment]
@coolnickname We not change ip after then block .You try multiple number ?Are you solve this problem ?

**Comment by coolnickname** [comment]
Whatsapp detects anomalities. It's not normal for 20 people to register from the same IP around the same time, and then all change IP around the same time each day too.On 30 Jul 2017 12:22 am, CalipsX <notifications@github.com> wrote:@coolnickname We not change ip after then block .You try multiple number ?Are you solve this problem ?

**Comment by CalipsX** [comment]
I understand i use multi ip But if use proxy server understand  Whatsapp  proxy, Which company to propose as a proxy or any  solutions about ip ?

**Comment by BRNALX** [comment]
@coolnickname do you solved your problem? I have numbers that work for 3 months, this is the max success got for my code.

**Comment by 10p30pl3** [comment]
I used to have 3 numbers running with different versions of yowsup for a couple of weeks, but suddenly 2 out of 3 accounts just got banned. 
Anyone else have similar problems recently or is it just me?

**Comment by coolnickname** [comment]
@BRNALX 
They API is supposed to be undetectable, so the problem is your code. All you can do is try to make it more human-like.

**Comment by neerajnegidev** [comment]
Hi @BRNALX ,
Few Quick questions 
1) How you setting the message frequency i mean how many messages you are sending per hour.
2) Are you using proxy as well?

**Comment by BRNALX** [comment]
@neerajnegidev 

I dont use proxy and not implemented limit for send messages.

**Comment by neerajnegidev** [comment]
Hi @CalipsX , @BRNALX, @coolnickname 

Does any one know that how to switch channel to send messages without stooping script. Means suppose i have 2 channel (channel A, channel B) now i want to switch to channel (B) automatically once channel (A) has send 10 messages.

Any help will be appreciated.

**Comment by coolnickname** [comment]
Have both channels on a different Thread and communicate back to the main thread to check which Thread should do what.On 15 Dec 2017 08:11, neerajnegidev <notifications@github.com> wrote:Hi @CalipsX , @BRNALX, @coolnickname
Does any one know that how to switch channel to send messages without stooping script. Means suppose i have 2 channel (channel A, channel B) now i want to switch to channel (B) automatically once channel (A) has send 10 messages.
Any help will be appreciated.

**Comment by customdeve** [comment]
Hey, @coolnickname , @BRNALX 

I want to switch channels after sending each 10 messages i am using below approach

 I have below three main files. There are two thread one for sending the message and another one is for receiving the message. I took same functionality and structure as its in yowsup cli demo and I have changed the code according my needs.

1. layer.py
2. stack.py
3. cli.py

inside stack.py we have 

<code>
def __init__(self, credentials,  encryptionEnabled = True):
      stackBuilder = YowStackBuilder()

      self.stack = stackBuilder\
          .pushDefaultLayers(encryptionEnabled)\
          .push(YowsupCliLayer)\
          .build()

      # self.stack.setCredentials(credentials)
      self.stack.setCredentials(credentials)
      self.stack.setProp(PROP_IDENTITY_AUTOTRUST, True)

  def start(self):
      self.stack.broadcastEvent(YowLayerEvent(YowsupCliLayer.EVENT_LOGIN))
      try:
          self.stack.loop(timeout = 0.5, discrete = 0.5)
      except AuthError as e:
          print(("Auth Error, reason %s" % e))
      except KeyboardInterrupt:
          print("\nYowsdown")
          sys.exit(0)
<code>

**Comment by coolnickname** [comment]
@customdeve Stop hijacking issues and mentioning random people.

**Comment by neerajnegidev** [comment]
@tgalal is this fixed .
