### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by MinoMex** [tgalal/yowsup#2178]
python env_android.py
Traceback (most recent call last):
  File "env_android.py", line 1, in <module>
    from .env import YowsupEnv
ValueError: Attempted relative import in non-package

**Comment by coolnickname** [comment]
I think you don't have Yowsup installedOn 31 Jul 2017 10:47 am, MinoMex <notifications@github.com> wrote:python env_android.py
Traceback (most recent call last):
File "env_android.py", line 1, in 
from .env import YowsupEnv
ValueError: Attempted relative import in non-package
