### ISSUE TITLE
Successfully registered but does not send the message

### ISSUE THREAD

**Issue by dbemfica** [tgalal/yowsup#2183]
I did the entire registration process to get the password and everything worked. But using ./yowsup-cli demos -s 55519xxxxxxxx "Test" -c config.conf, no error appears on the terminal.

What is missing?

**Comment by sealabr** [comment]
run with -d paramater, and please post debug output here...

**Comment by dbemfica** [comment]
Now a message appears, but is giving "Disconnected, reason: Connection Closed".

**Comment by anandreddyks** [comment]
I have the same issue, Can anyone please help. 


Command I'm using

`yowsup-cli demos -s  "91810XXXXXXX" "welcome" -c yowsup-cli.config -d`

This is how my config file looks 

```
cc=91
phone=9196XXXXXXX
id= 
password=I9vsojtwIVI9EAad/leXXXXXXX
```
Message 

```
DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f40e4b3e0d0>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f40e4b24950>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="919XXXXXXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
?z?JWk?T{????o-~b
HEX:e87a824a57116bc2547be4a1c711ebdb6f2d7e62
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
O?d??-??????`?"4??7?r?|˿k???8Ƶ鴒??????G??#i
0e?,?s?????0                               ??h
HEX:4fd56417b5c02d82d0d6f2110e9cb87f60860e227f34c51b35d737fe72dc7ccbbf6b3f1da8aa38c6b5e9b492d408b2b73fc2c2cc47c2e623690ccdfa1b17d3680d3065e42cc073dff0d211b1e130
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
```

**Comment by jlguardi** [comment]
Try with "yowsup-cli demos -y -d ..." instead of -s to get all pending messages/notifications/acks...

**Comment by FieldOfRice** [comment]
I have the same issue.
If i enter "yowsup-cli demos -y -d -c ..." i get the following:
>> yowsup      v2.5.2
>> Copyright (c) 2012-2016 Tarek Galal
>> http://www.openwhatsapp.org
>> This software is provided free of charge. Copying and redistribution is encouraged.
>> If you appreciate this software and you would like to support future development please consider
>> donating: http://openwhatsapp.org/yowsup/donate
>> Yowsup Cli client
>> ==================
>> Type /help for available commands
>> [offline]:

Seems like the yowsup cli doesn't connect. How to proceed. 
/L doesn't work and
/login what username/password to use?

**Comment by FieldOfRice** [comment]
Never mind, i had to use the s40 environment, instead of android.
Now it's working...

**Comment by gpsks** [comment]
Can u send the config file of s40 you are using
