### ISSUE TITLE
Whatsapp scratch to update _MD5_CLASSES, _KEY, _VERSION "Bad Gateway"

### ISSUE THREAD

**Issue by deddysetyadi** [tgalal/yowsup#2184]
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

That website is currently down, any suggestions where i should find alternative to update my _MD5_CLASSES, _KEY , and _VERSION when i'm getting error "old_version" ? 

Thanks

**Comment by zhorzh** [comment]
I had the same problem. Make this changes to get the password:
yowsup/env/env_android.py

-    _MD5_CLASSES = "ry9Xz6kVioQctwA3G9z62Q=="
+    _MD5_CLASSES = "ziYneeSZm5qExsEFX/AoMQ=="

-    _VERSION = "2.12.556"
+    _VERSION = "2.17.242"

but still even after i've registered with yowsup and got the password i am still getting the AuthError when trying to send message.

**Comment by sealabr** [comment]
use env S40 to send message, check if your layer is loading S40 Env

**Comment by deddysetyadi** [comment]
@zhorzh @sealabr thanks. It's worked now.
