### ISSUE TITLE
Old version error

### ISSUE THREAD

**Issue by aaronpr95** [tgalal/yowsup#2186]
My version of WhatsApp is 2.17.254, what is the md5 classes for this version?

**Comment by rlimaeco** [comment]
I have the same error, I cannot register

![image](https://user-images.githubusercontent.com/1217117/28944484-1a1fe31c-7879-11e7-8b48-92dc90a1da6f.png)


I just need yowsup to validate if a number is has an activated account in whatsapp or not. Anyone could help? 
My version of yowsup is v2.5.2 , I'm using linux mint 18.2.

**Comment by gromencode** [comment]
i generated md5 for version 2.17.287, its KoK/8Dy+k1yOP80RObNznw==  but still get the "old_version" error

**Comment by sealabr** [comment]
@gromencode  how you know what's the latest version for whatsapp for Yowsup?

**Comment by DataGreed** [comment]
@gromencode where do I have to declare this variables?

**Comment by DataGreed** [comment]
Changed it in yowsup/env/env_android.py and it worked! @gromencode thanks! But how can you know the actual version number and _MD5_CLASSES string?

**Comment by manojrao** [comment]
hello @sealabr  i got the old version error plase help me below as error:-
{'status': u'fail', 'kind': None, 'code': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': None, 'currency': None, 'length': None, 'cost': None, 'param': None, 'reason': u'old_version', 'login': u'918824166199', 'type': None, 'method': None, 'expiration': None}

**Comment by sealabr** [comment]
you changed your md5 class and version in env_android?

**Comment by rafaelsandroni** [comment]
@gromencode thanks a lot!! what you do to get this MD5_CLASSES at each app version released?

**Comment by sealabr** [comment]
https://github.com/mgp25/classesMD5-64
