### ISSUE TITLE
Help to find a quick way to check a large database of numbers for whatsapp

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#2188]
Help to find a quick way to check a large database of numbers for whatsapp

**Comment by cyberp1983** [comment]
What request do I need to send to determine availability of whatsapp

**Comment by sealabr** [comment]
with yowsup? probably not.

maybe this article will help you.
https://www.lorankloeze.nl/2017/05/07/collecting-huge-amounts-of-data-with-whatsapp/

**Comment by jlguardi** [comment]
I seems SPAM purpose.
