### ISSUE TITLE
old version error 

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2191]
hello yowsup developer  i got the below as error ro whatsapp number registration time please help me
{'status': u'fail', 'kind': None, 'code': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': None, 'currency': None, 'length': None, 'cost': None, 'param': None, 'reason': u'old_version', 'login': u'918824166199', 'type': None, 'method': None, 'expiration': None}

**Comment by KonstiPation** [comment]
If on linux try [this](https://github.com/KonstiPation/classesMD5-64/blob/master/dexMD5.py).
Download your current WhatsApp apk and it **should** work.

**Comment by tgalal** [comment]
fixed
