### ISSUE TITLE
Bad token and old version

### ISSUE THREAD

**Issue by netovs** [tgalal/yowsup#2196]
With the new version 2.17.293 and changing the android version to 6.0 the response is: bad_token
 With the example info i got the old_version message . . .  

How i can change the KEY. MD5 and signatura for get a new TOKEN valid.

**Comment by sealabr** [comment]
#2186 see this issue

**Comment by Nikovr4** [comment]
sealabr, I 2 day edit env_android.py but always get the result "old_version", already desperate. Can anyone help please.

**Comment by dickbutt2** [comment]
same problem

**Comment by ArseniyChern** [comment]
Tested working

**Comment by caikpigosso** [comment]
@ArseniyChern 
Good morning 

You'r yowsup-cli it's working ?

**Comment by ArseniyChern** [comment]
Yes

**Comment by caikpigosso** [comment]
I have problem with Yowsup he is giving bad token

**Comment by ArseniyChern** [comment]
Just find another token and change it in s40.py

**Comment by caikpigosso** [comment]
Where can I find another token?

**Comment by ArseniyChern** [comment]
3jYxFPSrhqjabEm5b2sXhA==

Also make sure to use android env

**Comment by caikpigosso** [comment]
![erro](https://user-images.githubusercontent.com/17514768/31125033-47e52770-a81d-11e7-89fc-60db3289f037.png)

still giving bad_token

you'r help-me ?

**Comment by ArseniyChern** [comment]
You most likely need to set android env variables correctly.

**Comment by caikpigosso** [comment]
Which variables do I have to change?

**Comment by ArseniyChern** [comment]
Md5 class & version

**Comment by caikpigosso** [comment]
would it be with the parameters obtained in this site?
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by ArseniyChern** [comment]
Yes

**Comment by caikpigosso** [comment]
![no_routes](https://user-images.githubusercontent.com/17514768/31130279-5508def0-a82d-11e7-87ff-9e287165d1b3.png)

No_routes error now

**Comment by caikpigosso** [comment]
Good Morning @ArseniyChern 

Please help-me

**Comment by ArseniyChern** [comment]
I personally haven’t had the no routes error show up. Perhaps it blocked you out of the system?

**Comment by caikpigosso** [comment]
Could you access and see if you have any blockages or something wrong?

**Comment by caikpigosso** [comment]
@ArseniyChern 
Is there any possibility of being my problem number?

**Comment by caikpigosso** [comment]
@ArseniyChern 

you'r help-me ?

**Comment by tgalal** [comment]
fixed
