### ISSUE TITLE
Is possible to use Yowsup on Windows Embedded Compact?

### ISSUE THREAD

**Issue by Andermutu** [tgalal/yowsup#2197]
Hello;
I have installed Yowsup on Windows 10, and now I want to install it on Windows Embedded Compact 7. I dont know is it is possible, but as it is working well on a Raspberry Pi maybe can run on WinCe 7. On windows 10 I run it only in the command prompt and in Embedded compact the idea is the same. Thanks in advance, any idea or suggestion is a great help for me.

**Comment by AragurDEV** [comment]
As long as it can run python it should run smoothly

**Comment by Andermutu** [comment]
If i install python is enough? On windows 10 other packages or libraries are also needed. Thanks a lot.

**Comment by AragurDEV** [comment]
Just test it :) and report any errors
