### ISSUE TITLE
Send and Listen at the same time

### ISSUE THREAD

**Issue by brayanesc** [tgalal/yowsup#2199]
Hi! I was trying to use the example of sendclient with flask, it works perfectly but i dont know how to add the listen part to receive the messages can you guys help me with that part, should i create a layer with both? right now I can use them separately.
Thanks.

**Comment by Domeax** [comment]
I solved the problem by creating this method in the EchoLayer in layer.py:

```
@ProtocolEntityCallback("iq")
def onIq(self, entity):
    for news in NewsletterManager.getNews():
        outgoingMessage = TextMessageProtocolEntity(news.text, to = news.number)
        self.toLower(outgoingMessage)
```

**Comment by brayanesc** [comment]
Thanks for the answer @Domeax can you please show me how to make a simple script for this, I am new in python and I would really appreciate your help.

**Comment by brayanesc** [comment]
I tried that code but it doesnt seem to change anything :( 
What should I modify in sendclient example in order to receive messages too?

**Comment by tgalal** [comment]
see cli demo
