### ISSUE TITLE
Send message in python.

### ISSUE THREAD

**Issue by Andermutu** [tgalal/yowsup#2200]
Hello;
I have a piece of code in python to send a message but it is not working. I think that the code is old and the  import are bad. I try to look for another codes that are newer but I could not find anything. Can anyone pass me a code in python to send a simple message. If the code is simple better for me. Thanks in advance.

This is my old code;

`import base64
#Importa la Clase WhatsappEchoClient, dedicada a envio de mensajes.
from demosechoclient import WhatsappEchoClient   
password = "***********************"                           
password = base64.b64decode(bytes(password.encode('utf-8')))   #Codificacion de Password para envio a los servidores de whatsApp.
username = '34645XXXX77888'                                
keepAlive= False                                              
whats = WhatsappEchoClient("TelefonoDestino", "Aqui tu mensaje", keepAlive)     
whats.login(username, password) '                                                

I cant import WhatsappEchoClient

**Comment by AragurDEV** [comment]
You can't use the Echoclient Demo

Look at the wiki for instructions: https://github.com/tgalal/yowsup/wiki/Sample-Application

**Comment by viratvarma** [comment]
Dear Andermutu ,
Could you please tell.
How to install yowsup in windows step by step.
