### ISSUE TITLE
old version 

### ISSUE THREAD

**Issue by KariyakiLP** [tgalal/yowsup#2201]
_MD5_CLASSES = "3jYxFPSrhqjabEm5b2sXhA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.287"

Not working anymore

**Comment by azacchino** [comment]
The same for me. "status: fail  old_version"

**Comment by KariyakiLP** [comment]
Its Working!
Just remove yousup2 and execute ./setup.sh 

```sh
$ pip uninstall yousup2
$ sudo ./setup.sh
```

**Comment by Rimander** [comment]
INFO:yowsup.common.http.warequest:{"login":"34xxxxxxxxxxx","status":"fail","reason":"old_version"}
