### ISSUE TITLE
s40 env throwing old_version error

### ISSUE THREAD

**Issue by himanshushakya** [tgalal/yowsup#2202]
Hi,
I want to register with s40 env but getting old_version error.
I can register with android env but cannot send message with that env.
I can send message registering with android env and sending through s40 env but I think this approach is leading to whatsapp number ban.
Please help me out.

Thanks

**Comment by betonetotbo** [comment]
Same problem here.

**Comment by leandroafonso** [comment]
too

**Comment by bhpachulski** [comment]
Look at my fork.

**Comment by dickbutt2** [comment]
same problem

changed version and md5 still getting the error

**Comment by gschanuel** [comment]
>  Look at my fork. -- (bhpachulski)
Same problem on your fork

**Comment by SEBv15** [comment]
I think whatsapp only supports android since july

**Comment by eirmd** [comment]
yowsup/env/env_android.py:
_MD5_CLASSES = NaFIPUxhFlZL1JVYH7UWPw==
_VERSION =2.17.314

yowsup/env/env_s40.py:
_VERSION = 2.16.12
_TOKEN_STRING = PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194472015L{phone}

**Comment by himanshushakya** [comment]
still getting the error
