### ISSUE TITLE
message send but not recived for user

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2213]
Hello guidance,
i send message from yowsup to whatsapp group user.Message send successfully.But user not found from yowsup message .belows as error show in user mobile:-

> `Wating for this message.This may take a while`
Please guide me for send message in group.

**Comment by AragurDEV** [comment]
There is no real difference for sending messages in group.
Just follow the guide in the wiki.

**Comment by galaxyitcenter** [comment]
how can you send messages in group?

**Comment by tgalal** [comment]
fixed
