### ISSUE TITLE
old version error

### ISSUE THREAD

**Issue by idansuper** [tgalal/yowsup#2214]
I'm also receiving the old version error whilst trying to register.
Also tried with bhpachulski's fork

Shalom Aleichem,
Live long and prosper
Idan

**Comment by dickbutt2** [comment]
same problem

changed version and md5 still getting the error

**Comment by azacchino** [comment]
The same for me

``` sh
root@debian:/home/me/yowsup-master# python yowsup-cli version
yowsup-cli v2.0.15
Using yowsup v2.5.2
root@debian:/home/me/yowsup-master# python yowsup-cli registration -d -E android --mcc 722 --mnc 341 --phone 543410000000 -C 54 --requestcode sms 
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=54&in=543410000000&lc=GB&lg=en&sim_mcc=722&sim_mnc=341&mcc=722&mnc=341&method=sms&mistyped=6&network_radio_type=1&simnum=1&s                                                                                        =&copiedrc=1&hasinrc=1&rcmatch=1&pid=8051&rchash=cadac65c6e5d6b37abf607ffcad7ef8                                                                                        cb2cb55b836878107be6007831a2dbfc1&anhash=%90%AE%2B%2B7z%3C%F0%28%1E%1F0a%02%EB_%                                                                                        7E5l%E5&extexist=1&extstate=1&token=n%2FIyOwJYLGYsyLY0OZ1ItsskOUw%3D&id=j%A3%C0%                                                                                        DC%FE%13%83%BF%21%9B%AB%3E%05%CF%F0%5E%5D%2Bl%DF
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=54&in=543410000000&lc=GB&lg=en&sim_mcc=722&sim_mnc=341&mcc=722&mnc=341&method=sms&mistyped=6                                                                                        &network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=8051&rchash                                                                                        =cadac65c6e5d6b37abf607ffcad7ef8cb2cb55b836878107be6007831a2dbfc1&anhash=%90%AE%                                                                                        2B%2B7z%3C%F0%28%1E%1F0a%02%EB_%7E5l%E5&extexist=1&extstate=1&token=n%2FIyOwJYLG                                                                                        YsyLY0OZ1ItsskOUw%3D&id=j%A3%C0%DC%FE%13%83%BF%21%9B%AB%3E%05%CF%F0%5E%5D%2Bl%DF
INFO:yowsup.common.http.warequest:{"login":"5493410000000","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 543410000000
```

**Comment by stevie86** [comment]
Same for me!
python yowsup-cli registration -d -E android -c config -r sms
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=43&in=68860563670&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9327&rchash=7c2d2f945a09156c15f1460bc6041a151b78ec4e4c036589e8dcbd6981a12a44&anhash=%7B%06%21.j%3ES%60V%A2%10%EE%3B%8D%3De%A8%E2e%E2&extexist=1&extstate=1&token=38X0MyiThMTX85QUT%2FrodAQxlT8%3D&id=l%E1%BA%EE%7C%7B%DF%2Fa%88%E1%40%1Cc%9E%11%FA%F6%F6%13
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=43&in=68860563670&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9327&rchash=7c2d2f945a09156c15f1460bc6041a151b78ec4e4c036589e8dcbd6981a12a44&anhash=%7B%06%21.j%3ES%60V%A2%10%EE%3B%8D%3De%A8%E2e%E2&extexist=1&extstate=1&token=38X0MyiThMTX85QUT%2FrodAQxlT8%3D&id=l%E1%BA%EE%7C%7B%DF%2Fa%88%E1%40%1Cc%9E%11%FA%F6%F6%13
INFO:yowsup.common.http.warequest:{"login":"4368860563670","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 4368860563670

**Comment by RussH** [comment]
this fix worked for me;
https://github.com/tgalal/yowsup/issues/2180#issuecomment-319354590

**Comment by stevie86** [comment]
This didn't work for me:
yowsup-cli registration -d --requestcode sms -c config -E android
DEBUG:yowsup.env.env:Current env changed to android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=43&in=68860563670&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5426&rchash=df0deb4a5fe59b21fe932011a273359f092d8f542f71348bbb5bd9c5e2a7ad5c&anhash=F%2BN%91%B7%84%89%DE%7Eb%10%9D%C7%8A%D3t%B6%C1%8D%3E&extexist=1&extstate=1&token=38X0MyiThMTX85QUT%2FrodAQxlT8%3D&id=%C9%F9%D6%FE%90%EF%02%C0%FF%02%F3%CC_%D6m%80%CC%B5%04%FF
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=43&in=68860563670&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=5426&rchash=df0deb4a5fe59b21fe932011a273359f092d8f542f71348bbb5bd9c5e2a7ad5c&anhash=F%2BN%91%B7%84%89%DE%7Eb%10%9D%C7%8A%D3t%B6%C1%8D%3E&extexist=1&extstate=1&token=38X0MyiThMTX85QUT%2FrodAQxlT8%3D&id=%C9%F9%D6%FE%90%EF%02%C0%FF%02%F3%CC_%D6m%80%CC%B5%04%FF
INFO:yowsup.common.http.warequest:{"login":"4368860563670","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 4368860563670

**Comment by hgc2002** [comment]
fix didn't work today. 
old_version message too.

**Comment by hgc2002** [comment]
I've just used https://github.com/mgp25/classesMD5-64 to get a new  md5 with the apk version 2.17.310 downloaded directly from wasap and using Android as platform.
ClassesMD5: AvhxpxXsm4F7dh84uXExDA==
Still getting old_version issue, so it's not only this what is failing.
Any idea?

**Comment by pablosharper** [comment]
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

But when I connect the same number with S40 it's work for a few days, then
become blocked.

So why we get "Connection Closed" with -e android?

Saludos,
Pablo

**Comment by hgc2002** [comment]
I've made it to work. The wasap version must be updated too, not only the md5.
The wasap version goes into file env/env.py
And it sends the code by sms. Eureka!!!

**Comment by mikuloff** [comment]
Also tried change env to android, versions 2.17.279 and 2.17.310, but alwais gets disconnect after authentication when try to set presence = available or try send message in cli (without results):
`yowsup-cli demos -l 7925xxxxxxx:xxx= -E android -d -s 7925xxxxxxz Testik
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f099ba2eba8>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f099f1207f0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e7.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth mechanism="WAUTH-2" passive="true" user="7925xxxxxxx">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
xxx
HEX3:b'xxx'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
xxxxxx
HEX3:b'xxxxxx'
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
`
Also I drew attention to the fact that in the database axolotl.db is fully empty.

**Comment by dietzi** [comment]
Maybe there are no rights for writing in file. Try as root and see what will happen

**Comment by mikuloff** [comment]
I run from root. File was created, but have no records in database. May be because Whatsapp server disconnects client immediately after authentication, before any other requests from yowsup.

**Comment by BRNALX** [comment]
Try This

file: env_android.py
class: AndroidYowsupEnv

_SIGNATURE = "MIIDMjCCAvCgAwIBAgIETCU2pDALBgcqhkjOOAQDBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNV" 
"BAcTC1NhbnRhIENsYXJhMRYwFAYDVQQKEw1XaGF0c0FwcCBJbmMuMRQwEgYDVQQLEwtFbmdpbmVlcmluZzEUMBIGA1UEAxMLQnJ" 
"pYW4gQWN0b24wHhcNMTAwNjI1MjMwNzE2WhcNNDQwMjE1MjMwNzE2WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5" 
"pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExFjAUBgNVBAoTDVdoYXRzQXBwIEluYy4xFDASBgNVBAsTC0VuZ2luZWVyaW5nMRQwEg" 
"YDVQQDEwtCcmlhbiBBY3RvbjCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+AtlEm" 
"aUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb+DtX58aophUPBPuD9tPFHsMCN" 
"VQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jr" 
"qgvlXTAs9B4JnUVlXjrrUWU/mcQcQgYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO" 
"8yk8b6oUZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GFAAKBgQDRGYtLgWh7zyRtQainJfCpiaUbzjJuhMgo4fVWZIvXHaS" 
"HBU1t5w//S0lDK2hiqkj8KpMWGywVov9eZxZy37V26dEqr/c2m5qZ0E+ynSu7sqUD7kGx/zeIcGT0H+KAVgkGNQCo5Uc0koLRW" 
"YHNtYoIvt5R3X6YZylbPftF/8ayWTALBgcqhkjOOAQDBQADLwAwLAIUAKYCp0d6z4QQdyN74JDfQ2WCyi8CFDUM4CaNB+ceVXd" 
"KtOrNTQcc0e+t"

_MD5_CLASSES = "ox998VW0nBTueMVfjuZkmQ=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

_VERSION = "2.17.212"
_OS_NAME = "Android"
_OS_VERSION = "4.3"
_DEVICE_NAME = "armani"
_MANUFACTURER = "Xiaomi"
_BUILD_VERSION = "JLS36C"
_AXOLOTL = True
Get the sms cod and registre yow number with env android, but, the yowsup login change env for s40.

**Comment by sowerkoku** [comment]
@pablosharper [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)
