### ISSUE TITLE
How can send image, I get fail send.!

### ISSUE THREAD

**Issue by Facho** [tgalal/yowsup#2215]
[connected]:/image send 59177879769 C:\\Users\\aaruquip\\Desktop\\g.png "Imagen
1"
DEBUG:yowsup.layers.logger.layer:tx:`
iq to="s.whatsapp.net" xmlns="w:m" type="set" id="79">
media type="image" hash="brXuGoSawiNMIbaJcL2Q1oqwHiTgtdTjS1j7ZaMjW+Q=" size="11
8548">/media>
iq

DEBUG:yowsup.layers.logger.layer:tx:
iq to="s.whatsapp.net" xmlns="w:m" type="set" id="79">
media type="image" hash="brXuGoSawiNMIbaJcL2Q1oqwHiTgtdTjS1j7ZaMjW+Q=" size="11
8548">
media>
iq>"

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
iq type="error" from="s.whatsapp.net" id="79">
error text="feature-not-implemented" code="501">
error>/iq

ERROR:yowsup.demos.cli.layer:Request upload for file C:\Users\aaruquip\Desktop\g
.png for 59177879769@s.whatsapp.net failed
DEBUG:yowsup.layers.logger.layer:rx:
iq type="error" from="s.whatsapp.net" id="79">
error text="feature-not-implemented" code="501">
/error>
/iq>

**Comment by AragurDEV** [comment]
Please use the search.
This is a duplicate again...
See #2149 for further assistance.
