### ISSUE TITLE
Stream Error type: ack

### ISSUE THREAD

**Issue by fsarihan** [tgalal/yowsup#2216]
Hello,

If someone posts a message using the "answer" feature on WhatsApp, I get an error within 5 minutes. It is not the moment.

<stream:error>
<ack id="96702439AFC681A924">
</ack>
</stream:error>
ERROR:yowsup.layers.interface.interface:Stream Error type: ack
{'ack': None}
INFO:yowsup.layers.interface.interface:Initiating reconnect
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Requested
general: Disconnected: Requested
[connected]:
DEBUG:yowsup.layers.protocol_iq.layer:YowPingThread-2 - ping thread stopped

**Comment by jlguardi** [comment]
You should ack all incoming messages. Answer messages aren't managed by axolotl layer in the master code. So your code doesn''t ack the message. Try to fix it at axolotl layer.

**Comment by fsarihan** [comment]
Thank you. I understood the logic of working on the issue. I'll work on Axolotl. I do not think I can, but i hope i will 👍 
Do you have another hint :) ?

How i catch is it answer msg, voice msg or normal msg? 


I also get the same error in voice messages, I guess I have to do it for that.

**Comment by strafun** [comment]
@fsarihan you can check demo echoclient - there is code for casing type of messages. 

@jlguardi i got same error - but i have function 
` @ProtocolEntityCallback("receipt")
  def onReceipt(self, entity):
        self.toLower(entity.ack())`
but seems it is not helps me...

**Comment by Lafard** [comment]
@jlguardi but how do I fix the axolotl layer

**Comment by Lafard** [comment]
@fsarian you need to implement the function handleUrlMessage of yowsup/layers/axolotl/layer_recieve.py
What I did in my own case was change it from
```
def handleUrlMessage(self, originalEncNode, UrlMessage):
    pass
```
to
```
def handleUrlMessage(self, originalEncNode, UrlMessage):
    self.handleConversationMessage(originalEncNode, UrlMessage.text)
```
So it recieves it as a normal text message

**Comment by Lafard** [comment]
@fsarihan
Did you try that

**Comment by marcipriano** [comment]
hi @Lafard,
I did as you said by changing handleUrlMessage but it did not work. the same error continues. Is there anything else to do?

**Comment by Lafard** [comment]
Hello @marcipriano, can you show what your errors look like ?

**Comment by tgalal** [comment]
fixed
