### ISSUE TITLE
Always shows offline status. Registered Successfully

### ISSUE THREAD

**Issue by galaxyitcenter** [tgalal/yowsup#2223]
[offline]:/message send 91xxxxxxxxxx "hii"

Error: Not connected

But it send message with below command

yowsup-cli demos --login 91xxxxxxxxxx:xxxxxxxxxxxxxxx= --send 91xxxxxxxxxx "Hello World"

Please help me out i am using android env.
Thanks in advance

**Comment by mikuloff** [comment]
Always disconnects after login, and no sends messages:
`[offline]:/login 7925xxx xxx=
DEBUG:yowsup.layers.network.layer:Connecting to e9.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
< stream:features>
< /stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
< auth passive="true" user="7925xxx" mechanism="WAUTH-2">
< /auth>

DEBUG:yowsup.layers.logger.layer:rx:
< stream:features>
< /stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
< challenge>
HEX3:b'c78fd87e6da0c5e710de7587d11a82158db0d772'
< /challenge>

DEBUG:yowsup.layers.logger.layer:tx:
< response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
HEX3:b'543bc45008b53940603b02c722040e302f7b7e16d8093af5b882273c8c5fce58866a30efb7ff008ac534fbe7372c6bbe09b9c8319304ead803835c4e916fee82b27ca94bc73ce94c7caa26bc9e'
< /response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
[offline]:
`

**Comment by galaxyitcenter** [comment]
i Found solution for this issue.
I am using in Windows 10. Here it working but in Ubuntu not working.
First of all use -E s40
Then /L
And it will connected
Thanks

**Comment by pablosharper** [comment]
But with s40 you will be banned

Saludos,
Pablo

**Comment by mikuloff** [comment]
Yes, my number also locked on s40, after try to register again I received error with old version, I used solution with update version and md5 sum, registered again normally with android env, but always disconnects on authentication. I use Ubuntu and can't use Windows.

**Comment by thaihau** [comment]
@mikuloff I am using ubuntu also, register using android, also encounter same problem like, always discounnect after authentication.

yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" mechanism="WAUTH-2" user="XXXXXXXXXXX">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
Pð¯0p¶¼m²än7'e
HEX3:b'50f0d0089aaf3070b6bc6db2131c07e46e372765'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
âÂºbbc¥f÷!LOÍ½#>ÆãÞÓã÷0ËW
sÒðT
HEX3:b'd9ffe00d04f110faa0c6de951de9d3e6e0fbf641b5ac5a5b568a3ec693e3ded3e3f79f30cb8d570dd92b6b0493b99d63a514669df705214c4fcd10bd239b0de2c29218ba62620a7391d2f05410'
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by karimQasem** [comment]
try 
`yowsup-cli demos -c /path for your config -y`
it is working
