### ISSUE TITLE
can not connect the whatsapp servers

### ISSUE THREAD

**Issue by juan-peterson** [tgalal/yowsup#2224]
Yowsup throws this error:
DEBUG:yowsup.layers.logger.layer:rx:
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

It was also working correct couple of weeks ago but i dont know why it is not working now.

**Comment by dietzi** [comment]
Maybe your number was deleted na WhatsApp because of inactivity

**Comment by juan-peterson** [comment]
@dietzi I dont think so because I already sent some messages 3 days ago over the phone.

**Comment by dietzi** [comment]
You can only registered once. Phone OR yowsup

**Comment by pablosharper** [comment]
Anyone have connected a number with -E android?

Saludos,
Pablo

**Comment by dietzi** [comment]
Sure. See here https://github.com/tgalal/yowsup/pull/2164
