### ISSUE TITLE
Error registering number

### ISSUE THREAD

**Issue by darode** [tgalal/yowsup#2227]
I'm getting the old_version error when trying to register a number

```
INFO:yowsup.common.http.warequest:{"login":"34618397016","status":"fail","reason":"old_version"}
INFO:yowsup.common.http.warequest:{"login":"34618397016","status":"fail","reason":"old_version"}

status: fail
reason: old_version
```

Some details of my installation:
```
yowsup-cli  v2.0.15
yowsup      v2.5.2
```

Environment configuration (env_s40.py)
```
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
```

I tried:

- Two different numbers
- Reinstall master branch

I read another issues and it seems the code is up to date, so I think I'm missing something...

Anyone knows what can I do/look at to solve it?

Thanks in advance!

**Comment by eirmd** [comment]
yowsup/env/env_android.py:
_MD5_CLASSES = NaFIPUxhFlZL1JVYH7UWPw==
_VERSION =2.17.314

yowsup/env/env_s40.py:
_VERSION = 2.16.12
_TOKEN_STRING = PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194472015L{phone}

**Comment by danieleliberti** [comment]
yowsup-cli  v2.0.15
yowsup      v2.5.2

status: fail
reason: old_version

**Comment by dpvenkatesh** [comment]
Tried 
`yowsup-cli registration --requestcode sms --phone XXXXXXX --cc 91 --mcc 123 --mnc 456 -E android`

yowsup-cli  v2.0.15
yowsup      v2.5.2

INFO:yowsup.common.http.warequest:{"login":"XXX","status":"fail","reason":"old_version"}

**Comment by dezember** [comment]
#2237
