### ISSUE TITLE
reason: b'old_version' status: b'fail'

### ISSUE THREAD

**Issue by althafas** [tgalal/yowsup#2228]
Hey guys im trying to register with yowsup2.
But im getting the error with registration. Any help on sending message with whatsapp will be of great help.

**Comment by galaxyitcenter** [comment]
Change whatsapp version and MD5_Class as below
env file located at : yowsup/env/env_android.py

_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_VERSION = "2.17.16"

**Comment by dpvenkatesh** [comment]
@galaxyitcenter 
I tried the below options, still same error.

**Comment by althafas** [comment]
ya i was able to register..

**Comment by althafas** [comment]
But while trying to send message getting error as 
AttributeError : 'AuthError' object has no attribute 'message'
