### ISSUE TITLE
Message send but not recived for one user

### ISSUE THREAD

**Issue by KikeMuller** [tgalal/yowsup#2229]
Hello:

`yowsup-cli demos -c yowsup-cli.conf -s xxxxxxxxxxxxx "Test" -M`

`INFO:yowsup.demos.sendclient.layer:Message sent`

But not recived message.

**Comment by KikeMuller** [comment]
Debug:

```
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer -                                         Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="xxxxxxxxxxxxx" mechanism="WAUTH-2">
^▒b}▒▒▒\▒▒'▒▒tdv s▒}|k▒▒93▒2▒i䫚▒▒yB�v٩v▒▒▒▒▒▒▒▒▒▒;g<&@7
HEX:5ebf62057d93e2f95c1bb892ef27cec474647620731ead7d7c6bbbeb3933b932cd0069e4ab9abccc7942c29a76d9a976931ba9f1e2ea19bcc3048cb28ca9143b673c264037
</auth>

xtermDEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1496805881" expiration="4444444444" props="17" t="1504191620">
@▒D9▒C▒W?"▒▒▒▒)6C▒
HEX:4000e34439ab43cd573f22e50fd3cbe1293643ad
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:tx:
<message to="xxxxxxxxxxxxxxxxx@s.whatsapp.net" type="text" id="1504191620-1">
<body>
Test Col
HEX:5465737420436f6c
</body>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1504191620" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1504191620" from="xxxxxxxxxx@s.whatsapp.net" class="message" id="1504191620-1">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown

```

**Comment by hgc2002** [comment]
You must use the command line version of yowsup with your registered phone, then do a quick login to load your keys, and finally try again sending the message.

**Comment by VictorGil** [comment]
What do you mean by "You must use the command line version of yowsup with your registered phone" 
I have the same issue as KikeMuller, I am able to successfully register the number I want to use with the yowsup CLI, and then? What should I do before trying to send a message using 
$ yowsup-cli demos -d  -c myconfig.txt -M  -s +xxxxxxxxxxxx "a message"
command? 
And what do you mean by "do a quick login?"

Thanks in advance

**Comment by VictorGil** [comment]
Ok, I finally got it working!!!
So, after successfully registering my number, then I need to start the yowsup CLI in **interactive** mode:
``$ yowsup-cli demos -c myconfig.txt  -y ``

Then, while inside the yowsup interative mode, I do the "quick login" using "**/L**":
[offline]:/L 
INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Auth: Logged in!
general: Disconnected: Requested
[connected]:
Auth: Logged in!

Then I can send a message, and I actually received it (finally) while still inside the yowsup CLI "interactive" mode:
/message send xxxxxxxxxxxx hello 
Iq:
ID: 8
Type: result
from: yyyyyyyyyyyy@s.whatsapp.net
[connected]:
Sent: 1505769738-9
[connected]:

And now, I can disconnect from the "yowsup interactive CLI" and send messages in non-interacitve mode, for example:
$ yowsup-cli demos -c myconfig.txt -s xxxxxxxxxxxx "hello again"
