### ISSUE TITLE
Connection error: ib handler for edge_routing

### ISSUE THREAD

**Issue by usinadeideia** [tgalal/yowsup#2230]

**Comment by jlguardi** [comment]
I've just ignored this ib and it is still working but we should search for a better management.

**Comment by usinadeideia** [comment]
Okay. I'll try to do this and put the result here. For now thank you. If you want to add me on Skype, we can go and exchange experiences. My API is PHP, new and functional version. But I'm thinking of migrating to Python

My Skype: usinadeideia

thanks
