### ISSUE TITLE
Solution for "old_version" problem.

### ISSUE THREAD

**Issue by SrJoobs** [tgalal/yowsup#2231]
Hello, today i will report one problem.

INFO:yowsup.common.http.warequest:b'{"login":"number_private","status":"fail","reason":"old_version"}\n'

I saw others issues and changed my env_android.

    _MD5_CLASSES = "3jYxFPSrhqjabEm5b2sXhA=="
    _VERSION = "2.17.279"

Help and sorry my english :p

Edit¹:I tried use classesMD5-64 script, but i no received solution. (https://github.com/mgp25/classesMD5-64) and i am in linux

**Comment by SrJoobs** [comment]
I tried use classesMD5-64 script, but i no received solution. (https://github.com/mgp25/classesMD5-64)

**Comment by SrJoobs** [comment]
I solved this problem. Follow:
  chmod 777 -R yowsup-cli

Create file configuration "yowsup-cli.config" and edit he.
cc=55 > country code
phone=55XXXXXXXXX > phone number
id= > IMEI number ( http://www.wikihow.com/Find-the-IMEI-or-MEID-Number-on-a-Mobile-Phone )
password= 

and launch command:
  ./yowsup-cli --requestcode sms --config yowsup-cli.config -E android

**Comment by pablosharper** [comment]
Solution for closed connection?

Saludos,
Pablo

**Comment by caiovictormc** [comment]
Thanks! Solved my problem

**Comment by sowerkoku** [comment]
[tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed

**Comment by siddheshghadi** [comment]
using sudo, solved the problem for me.
