### ISSUE TITLE
Multiple receipts?

### ISSUE THREAD

**Issue by h1rule** [tgalal/yowsup#2233]
Hey,

is there any way to insert multiple numbers instead of just one per command?

Currently its:

 ./yowsup-cli demos -c config -s 123456789 "hey!"

I'd like to send it to 3 receipts at one line, since Group Messaging is very buggy for me, specially when the message has a lot of characters. (Waiting for the Message to receive...)

**Comment by tgalal** [comment]
there is no way, and group messaging works fine again
