### ISSUE TITLE
Why are long messages not sent to groups?

### ISSUE THREAD

**Issue by h1rule** [tgalal/yowsup#2234]
Hey!

When i use yowsup-cli -s group, and have a LONG message, its not delivered by the group, i tried all issue-fixes here in the repo, nothing helped.

short messages are working, long messages are doing the "Waiting for message to arive" popup.
When i send the excat same message to a private chat, its working.

**Comment by tgalal** [comment]
97e915691bf8272f9d2e2a87a62e82fb034ed4d5
