### ISSUE TITLE
How to send a test message full code not by saying config part i f***ing hate it 

### ISSUE THREAD

**Issue by syedmustafa54** [tgalal/yowsup#2238]
# How to send a test message a hole command I tried a lot of them but nothing is working.if you know how to send a demo message the please reply don't reply for any other

**Comment by syedmustafa54** [comment]
Why the fuck did you closed  jlguardi

**Comment by jlguardi** [comment]
@syedmustafa54 respect all other people who reads your issue. Use a polite language. 
More over, you shoud read wiki and all other issues to avoid to repeat an already answered question.
