### ISSUE TITLE
Can't get echo demo working

### ISSUE THREAD

**Issue by victor141516** [tgalal/yowsup#2241]
Hi, I have been learning about this library a couple of days, I successfully got my WhatsApp password but if I launch:
`yowsup-cli demos --config yowsup-cli.config -e -E android`

Having this on yowsup-cli.config:
```
cc=34
phone=*****
id=
password=*****
```

Or running:
`yowsup-cli demos -l *****:******* -e`

I have tried using `-E android` in both cases, same result.

Doesn't work at all, always the same output:
```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
```

Then it  ends. I have tried sending messages to WhatsApp before, after and rapid fire while running the command and got nothing.

**Comment by Lafard** [comment]
Make you have the correct info in your env_android.py

**Comment by victor141516** [comment]
I have stock but changed:
```
_MD5_CLASSES = "hCVm2MkI65iB5RRa6m7t1g=="
_VERSION = "2.17.322"
```

I got these using [this](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py).
Should I change anything else?

**Comment by Lafard** [comment]
After trying many _MD5_CLASSES
I resorted to env_s40.py with

```
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = False #True

```

And it's working

**Comment by victor141516** [comment]
Thank you! I will try it ASAP and comment again.
Do you know why it doesn't work using Android? I have read S40 support will end soon and although I'm using this lib for personal purposes only, it would be sad that all the effort inverted in this lib is

**Comment by victor141516** [comment]
Just tries and now it working correctly. Thanks @Lafard !
