### ISSUE TITLE
Forward image files 

### ISSUE THREAD

**Issue by azizasm** [tgalal/yowsup#2242]
I noticed that sending image files require encryption at first. But is this possible to forward existing encrypted image to other recipient ?  Any sample code will help. Thanks.

**Comment by azizasm** [comment]
Found solution here https://github.com/dietzi/yowsup

**Comment by pedritopy** [comment]
Como puedo hacer para recibir las imagenes en el yowsup?

**Comment by pedritopy** [comment]
How can I do to receive the images in the yowsup?

**Comment by tgalal** [comment]
yes, see echo demo
