### ISSUE TITLE
Yowsup Support

### ISSUE THREAD

**Issue by Andermutu** [tgalal/yowsup#2243]
Hello everybody,

FirstIy congratulations for such a good library/project. Secondly I am thinking to make a project of home automation using Yowsup library. But I am concerned about the support of Yowsup. I have understood that Yowsup will be supported as long as Nokia S40 is supported, so until 2019. Am I correct?

What is planned to happen after, I mean is there any intention to use other platform or something like that? 

Thanks in advance. Have a good day.

**Comment by fwmarcel** [comment]
I got the same error ..
