### ISSUE TITLE
sudo yowsup-cli registration --requestcode sms --phone 91xxxxxxxxx --cc 91 --mcc 405 --mnc 06 -E android -d

### ISSUE THREAD

**Issue by galaxyitcenter** [tgalal/yowsup#2247]
sudo yowsup-cli registration --requestcode sms --phone 91xxxxxxxxx --cc 91 --mcc 405 --mnc 06 -E android -d
registration: error: unrecognized arguments: -E android

**Comment by galaxyitcenter** [comment]
issue solved by performing blocking test.
It occurred because my number is blocked.

**Comment by ykguCoder** [comment]
@galaxyitcenter How solved by performing blocking test?
