### ISSUE TITLE
 Unimplemented notification type

### ISSUE THREAD

**Issue by victorgt26** [tgalal/yowsup#2251]
yowsup crash and display the follow message:
```
File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 141, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification from="591XXXXXXXX@s.whatsapp.net" t="1505229085" offline="3" type="location" id="1505225384-277" notify="XXXXX  - CONSTRUMAR">
<disable id="150522906500000">
</disable>
</notification>
```
Somebody idea?

**Comment by nnapster** [comment]
hi ,
Go to your /usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_notifications/layer.py and got recvNotification function and add following condition 

        elif node["type"] == "location":
            # Not implemented
            pass
Your complete function will be looked like following 

`    def recvNotification(self, node):
        if node["type"] == "picture":
            if node.getChild("set"):
                self.toUpper(SetPictureNotificationProtocolEntity.fromProtocolTreeNode(node))
            elif node.getChild("delete"):
                self.toUpper(DeletePictureNotificationProtocolEntity.fromProtocolTreeNode(node))
            else:
                self.raiseErrorForNode(node)
        elif node["type"] == "status":
            self.toUpper(StatusNotificationProtocolEntity.fromProtocolTreeNode(node))
        elif node["type"] == "features":
            # Not implemented
            pass
        elif node["type"] in [ "contacts", "subject", "w:gp2" ]:
            # Implemented in respectively the protocol_contacts and protocol_groups layer
            pass
        elif node["type"] == "contacts":
            pass
        elif node["type"] == "web":
            # Not implemented
            pass
        elif node["type"] == "location": #added new line 
            # Not implemented
            pass
        else:
            self.raiseErrorForNode(node)`

**Comment by tgalal** [comment]
9d8d13b68f1704c2deecf6fde1e0118fa30ebd38
