### ISSUE TITLE
Can anyone edit GB WhatsApp source code in such a way that it also shows toast when someone sees your profile picture or profile, like it shows toast when someone sees your story

### ISSUE THREAD

**Issue by Harsh8080** [tgalal/yowsup#2252]

**Comment by v1nc** [comment]
Every WhatsApp app have to send something to the server when the user whatches a profile picture to realize this feature. You can try to request it from whatsapp, but changing the source code can not realize this, even if you had the original code.

**Comment by Harsh8080** [comment]
So there is no way i can see who sees my profile??

**Comment by Harsh8080** [comment]
Isn't there a possibility by which profile picture itself can be changed to story feature??

**Comment by v1nc** [comment]
You can do this for you own app, but it will not work with any of your friends. All would need your modified app.

**Comment by Harsh8080** [comment]
O.k. , but why wouldn't I be able to see who saw my DP when i change its functionality in a similar way as that of WhatsApp story?

**Comment by Harsh8080** [comment]
Also, couldn't the data logs be stolen from their server?

**Comment by AragurDEV** [comment]
That's no topic on yowsup. Please close this issue.
