### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by alissonx** [tgalal/yowsup#2255]
somebody can help me?

last version, tried a lot of changes, using s40 and android

yowsup-cli version
yowsup-cli v2.0.15
Using yowsup v2.5.2

status: fail
reason: old_version

yowsup-cli registration -E android --requestcode sms --phone XXXXXX --cc 55 --mcc 724 --mnc 13

status: fail
retry_after: 3600
reason: no_routes
login: XXXX

yowsup-cli registration -E s40 --requestcode sms --phone XXXXXX --cc 55 --mcc 724 --mnc 13

status: fail
reason: old_version
login: XXX

**Comment by AragurDEV** [comment]
Edit your 
_VERSION and _MD5_CLASSES in yowsup/env/env_android.py
to match: https://coderus.openrepos.net/whitesoft/whatsapp_scratch (use a and d)
Rebuild and reinsall your yowsup and it should work.

**Comment by alissonx** [comment]
Hi

can't find "_MD5_CLASSES"

how to rebuild and reinstall yowsup?

**Comment by AragurDEV** [comment]
git clone https://github.com/AragurDEV/yowsup.git
Edit yowsup/env/env_android.py:
Change _MD5_CLASSES = "ry9Xz6kVioQctwA3G9z62Q==" to _MD5_CLASSES = "uts7K11+PDyZE5R0ou+2Sw=="
and _VERSION = "2.12.556" to _VERSION = "2.17.337"
after that run python (linux use pyhton3) setup.py install

**Comment by alissonx** [comment]
I`ve done everything you said 

root@git:~/yowsup# ./yowsup-cli registration -E android  --requestcode sms --phone XXXXXX --cc 55 --mcc 724 --mnc 13 -d


status: fail
retry_after: 3600
reason: no_routes
login: XXXX

**Comment by AragurDEV** [comment]
@alissonx your IP is banned, retry in 1 hour again

**Comment by alissonx** [comment]
I`ve changed my IP address to another...

status: fail
retry_after: 3600
reason: no_routes
login: XXXX

same error "no routes"

**Comment by alissonx** [comment]
I`ve tried with 5 numbers never used on yowsup...

same error

status: fail
retry_after: 3600
reason: no_routes

**Comment by AragurDEV** [comment]
Dude, just chill!

**Comment by alissonx** [comment]
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.17.337 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=55&in=xxxxxxx&lc=GB&lg=en&sim_mcc=724&sim_mnc=023&mcc=724&mnc=023&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=3306&rchash=fa7b6abe483c022bcb6fb8786580b11e046170f42408ca5bba5460fd188f9f9e&anhash=%A0%0C%B8%15%86BA%CE%D8Z%90+%D9%A0%29%85%C9%DE%A6%14&extexist=1&extstate=1&token=2CJ4eVOPjqI1UwpSdXykFXUsxxU%3D&id=%3E7%14%C3%C5%0A%CE%AE%9E%E0%BC%C8%DA%93AIIZ%9AH
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=67996943243&lc=GB&lg=en&sim_mcc=724&sim_mnc=023&mcc=724&mnc=023&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=3306&rchash=fa7b6abe483c022bcb6fb8786580b11e046170f42408ca5bba5460fd188f9f9e&anhash=%A0%0C%B8%15%86BA%CE%D8Z%90+%D9%A0%29%85%C9%DE%A6%14&extexist=1&extstate=1&token=2CJ4eVOPjqI1UwpSdXykFXUsxxU%3D&id=%3E7%14%C3%C5%0A%CE%AE%9E%E0%BC%C8%DA%93AIIZ%9AH
INFO:yowsup.common.http.warequest:{"login":"xxxxxx","status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":0,"voice_wait":0}

status: fail
retry_after: 3600
reason: no_routes
login: xxxx

**Comment by alissonx** [comment]
2 hours later


status: fail
retry_after: 3600
reason: no_routes
login: XXXX

**Comment by AragurDEV** [comment]
Test my fork
Test S40 and Android 
https://github.com/AragurDEV/yowsup

**Comment by alissonx** [comment]
already tested on git clone https://github.com/AragurDEV/yowsup.git

**Comment by AragurDEV** [comment]
Yes clone it again....

**Comment by pablosharper** [comment]
Disconnected: Connection Closed

Saludos,
Pablo

**Comment by alissonx** [comment]
ok...

i`ve done again...

with android

status: fail
retry_after: 3600
reason: no_routes
login: XXXX


with s40

status: fail
reason: old_version
login: XXXXX

**Comment by pablosharper** [comment]
TypeError: hex() argument can't be converted to hex


Saludos,
Pablo

**Comment by AragurDEV** [comment]
@alissonx
use Python 3, pls read the README.md...

**Comment by alissonx** [comment]
root@git:~/yowsup# python3 yowsup-cli registration -E s40  --requestcode sms --phone XXXXXX --cc 55 --mcc 724 --mnc 23 -d
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/root/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/root/yowsup/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/root/yowsup/yowsup/env/env.py", line 12, in __init__
    YowsupEnv.registerEnv(cls)
NameError: name 'YowsupEnv' is not defined

**Comment by AragurDEV** [comment]
Seems wired,
working fine on my test servers.
Make sure you have all dependencies installed.
Also use the android device.

**Comment by SrJoobs** [comment]
Hello, you can try use this:

https://github.com/tgalal/yowsup/issues/2231

**Comment by ykguCoder** [comment]
@AragurDEV What's the limit of register? Why temporarily_unavailable?

**Comment by alissonx** [comment]
@AragurDEV  How much do you charge to make it work?

**Comment by sowerkoku** [comment]
@alissonx [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed

**Comment by Suresh317437** [comment]
I've registered with Yowsup WhatsApp successfully. But I am getting "[offline]" message always. For "/L" command it is showing "general: Disconnected: Connection closed"

**Comment by MSKouli** [comment]
I've registered yowsup WhatsApp, later I got an issue with Login. It is showing "[Offline]" and for a command of "/L", it generates "general:Disconnected: connection closed". 
Can you help me with that please?
@AragurDEV
