### ISSUE TITLE
Is there anybody can login in android env?

### ISSUE THREAD

**Issue by CoderJ** [tgalal/yowsup#2261]
When I login (/L) in android env , it always says 'Connection Closed'
```
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="49*************(my phone number)" mechanism="WAUTH-2">
����M)�G�I�LZ6�{t����Yb����P��'���P�S^���֭�eE�F��2oE�
HEX:1d1891f8cac64d29ea470eeea049efb34c1d5a368216127b7412ecc401a9845962c7c8fed45080f4278417a1c150c953005e8a9c1fe2d6add56518458346f00000fe07326f45f2
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
```
And I have change the `_VERSION` and `_MD5_CLASSES` to `2.17.337`, `uts7K11+PDyZE5R0ou+2Sw==`

When I want to find the solution on github, many people face the same problem but there is only one way to solve it: change the env to s40. but i don't think it is a good solution. I want to run it in android env, Anybody can help me?

**Comment by CoderJ** [comment]
UPDATE : 
I tried many way but no result.
When I removed 
```
#nums.extend(list(map(ord, strCat)))
```
in `generateAuthBlob`, I got 
```
rx <failure>
rx   <not-authorized></not-authorized>
rx </failure>
```

**Comment by AragurDEV** [comment]
Use my fork. It should work fine.
If you need any assistance jump on our discord.
https://github.com/AragurDEV/yowsup

**Comment by tgalal** [comment]
fixed
