### ISSUE TITLE
Sqlite axolotl.db location

### ISSUE THREAD

**Issue by technocode** [tgalal/yowsup#2266]
Hello,

Does anyone know where is sqlite session data stored (axolotl.db) location?

My operation system is windows.

Thanks

**Comment by tgalal** [comment]
- Win XP (not roaming):   C:\Documents and Settings\<username>\Application Data\yowsup\yowsup\PHONE\axolotl.db
- Win XP (roaming):       C:\Documents and Settings\<username>\Local Settings\Application Data\yowsup\yowsup\PHONE\axolotl.db
- Win 7  (not roaming):   C:\Users\<username>\AppData\Local\yowsup\yowsup\PHONE\axolotl.db
- Win 7  (roaming):       C:\Users\<username>\AppData\Roaming\yowsup\yowsup\PHONE\axolotl.db
