### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by mar-celohenrique** [tgalal/yowsup#2275]
I have tried all the solutions that could solve the problem of registering my number. However, when I change the MD5 or version, I still get the following errors:

status: fail
reason: bad_token

OR

status: fail
reason: old_version

Does anyone have an effective solution?

**Comment by llongoria** [comment]
I have the same problem, Is there any solution?

**Comment by Goeste** [comment]
I can second this behavior:

`~/yowsup $ python3 yowsup-cli registration -c mydetails --requestcode sms
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:b'{"login":"49xxxxxxxxxxx","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'49xxxxxxxxxxx'`

**Comment by no-faker** [comment]
Hello!
I have the same problem as Goeste.
Can anyone help use?

**Comment by Goeste** [comment]
I was able to resolve the issue. Am on track right now and will post my method and sources later on.
Hint: python3, Register as android and connect as s40, After installing Python 3 reinstall yowsup

**Comment by mamluka** [comment]
+1

**Comment by mar-celohenrique** [comment]
@Goeste I have python3 installed and it still does not work

**Comment by Goeste** [comment]
or installation i installed python3 anf rerun the install procedure (i.e. python3 xxx.py install)
regarding registration the following post was helpful:
*[https://github.com/tgalal/yowsup/issues/2249#issuecomment-329109099]

after that everything was compiled sucessfully and i was able to register, login and send messages.

I also installed these packages:

- python-dateutil
- python-setuptools
- python-dev
- libevent-dev
- ncurses-dev

hope that helps... any further coding, i, unfortunately, cannot help with as i am just a hack'n'slay-method-guy that tries to get things running ;)

Best,
goeste

**Comment by TimZ99** [comment]
Adding `-E android` worked for me.

**Comment by mar-celohenrique** [comment]
@TimZ99 Where?

**Comment by TimZ99** [comment]
At the end. For most after the -c CC.

**Comment by emmekappa** [comment]
@TimZ99 it works for registration but when you start using the cli you cannot login by using Android environment 

you'll get a 
```
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
``` 

when you try to login with `/L`
