### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by Bunder99** [tgalal/yowsup#2276]
Hi! I successfully register in WhatsApp via yowsup, create the config and try to enter into my account to read messages, but I constantly get the following error after ./yowsup-cli demos --config /root/whatsapp_config.txt --echo -d:

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

Session in my phone closes during the registration in yowsup. Is it normally? Where is my mistake?

**Comment by sowerkoku** [comment]
@Bunder99 [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed
