### ISSUE TITLE
Can't connect or send message

### ISSUE THREAD

**Issue by ik3umt** [tgalal/yowsup#2287]
Debian 9.1 Stretch
For a "classic" installation I give up apt-get install , just unzipped yowsup-master, and then "python setup.py install"
I've modified yowsup/env/env.py with 

**DEFAULT = "android"**

and modified yowsup/env/env_android.py with

**_MD5_CLASSES "IdHZifpmNTVVCJ50Cu7RMA=="**

**_VERSION "2.17.350"**

I have obtained a new code via sms and registered with new password (added in config file)

When I issue the command : 

**yowsup-cli demos -l phonenumber:password -s destnumber "Hello"**

the linux prompt is back without errors but without any message delivered too.....

with **yowsup-cli demos -y -c "path_to_config_file"**

The cli prompt is **[offline]:**

Typing /L I cannot login and the answer is : 

**general: Disconnected: Connection Closed**

My number is not banned as if I enable a regular android device with whatsapp and a new code, it works 100%

Any hint please ?

**Comment by dpointk** [comment]
I have the same issue.

**Comment by danielcardeenas** [comment]
Do you have android env enabled?. You need to use S40 env to login since android env need wa protocol 2.0 and its not implemented. S40 Uses protocol 1.6

**Comment by dpointk** [comment]
It worked for me a day later.

**Comment by ik3umt** [comment]
Ok it works with s40 , so : 

Install yowsup once unzipped with "python setup.py install"
Modify  **yowsup/env/env.py** with  
**DEFAULT = "android"**

Modify **yowsup/env/env_android.py** with
**_MD5_CLASSES "IdHZifpmNTVVCJ50Cu7RMA=="**
**_VERSION "2.17.350"**

Then "python setup.py install" again

Ask for verification code : 

**yowsup-cli registration --requestcode sms --phone XXyyyyyyy --cc XX**

register : 

**yowsup-cli registration --register AAABBB --phone XXyyyyyyy --cc XX**

Once correctly registered, modify again  yowsup/env/env.py with  
**DEFAULT = "s40"**
"**python setup.py install**" again

Check with 
**yowsup-cli demos -l XXyyyyyyy:yourpassword= -s destination_number "Test msg"**

I have solved this way
Hope it helps

**Comment by yerunkar11** [comment]
@ik3umt I have followed your steps, I still cannot send messages and login

**Comment by kapil-raj** [comment]
me too man

**Comment by kapil-raj** [comment]
> @kapil-raj , Can you solved it?

@rafaelbusonid No, I couldn't. but let me know if you managed to send messages, :)

**Comment by rafaelbusonid** [comment]
No, I think that yowsup die 😧

Em sex, 1 de fev de 2019 às 13:22, Kapil Raj <notifications@github.com>
escreveu:
