### ISSUE TITLE
stream:error

### ISSUE THREAD

**Issue by 0xFlint** [tgalal/yowsup#2288]
Hi,

In the last week i've been getting the following errors:
`<stream:error> <ack id=PSAS1487100006><ack><stream:error>`

i'm getting the following before hand:

```<notification from=status@broadcast type=psa id=PSAS1487100006 participant=0@s.whatsapp.net mode=status notify=WhatsApp t=1507820228> <message type=media id=PSAS1487100001 order=1487100001> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100002 order=1487100002> <media type=msg mediatype=gif><media><message> <message type=media id=PSAS1487100003 order=1487100003> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100004 order=1487100004> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100005 order=1487100005> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100006 order=1487100006> <media type=msg mediatype=image><media><message><notification>```

And i see the following reply

```
<receipt to=status@broadcast id=PSAS1487100001 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100002 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100003 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100004 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100005 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100006 participant=0@s.whatsapp.net><receipt>
```

I also tried sending ack for:
`"<ack id=PSAS1487100006><ack>"`

and also tried to send double time the receipts again.

Any idea? Please.

@tgalal  @mgp25  @CODeRUS  - Can you maybe assist with your vast knowledge?

**Comment by tgalal** [comment]
9d8d13b68f1704c2deecf6fde1e0118fa30ebd38
