### ISSUE TITLE
Presence subscription

### ISSUE THREAD

**Issue by hiwaleakshay** [tgalal/yowsup#2290]
i subscribe for contacts presence using
/L
/presence available
/contacts sync <phone_number>
/presence subscribe <phone_number>

So far so good, i am receiving the presence for the user but my problem is whenever i disconnects from whatsapp and log in again, i have to subscribe for that <phone_number> again.
I think once we subscribe there shouldnt be a need to subscribe for that number every time unless we unsubscribe it.

any help on how i can avoid this? 

but what the strange thing is there is one contact which i synced and subscribed , i am getting presence from it without subscribing to it on every log in. Now i am really confused with this presence thing..!

PLEASE SOLVE MY ISSUE!!!

**Comment by emmekappa** [comment]
@hiwaleakshay I cannot either receive the presence notification. what environment are you using? android or s40?

**Comment by hiwaleakshay** [comment]
@emmekappa I am using s40 for login and further purpose. I don't think we can use android environment for login , has to do something with WA2.0 protocol.
I am receiving presence updates. also, what do you mean by notifications? Yowsup wont notify you, though you can check tx, rx in debug log.
just use -d while running cli.

**Comment by thatskriptkid** [comment]
@hiwaleakshay Hi! Could u provide s40 settings for successful log in?

**Comment by hiwaleakshay** [comment]
_VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True


As of today these setting are working for me.

**Comment by thatskriptkid** [comment]
@hiwaleakshay Your settings don't work for me :( I use console cli. I edited /usr/local/lib/python2.7/dist-packages/yowsup/env/env_s40.py

yowsup-cli demos -E s40 -d --yowsup --login XXXXXX:YYYYY

DEBUG:yowsup.env.env:Current env changed to s40 
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0xb67e176c>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0xb67d9bec>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="XXXXXXXXXXXX" mechanism="WAUTH-2">
K �O����s�����g�C�c_��3����#��c�<���$� ��
HEX:cd173e597388e54ec818a92f40dfd098c2f89e303797990d4b20804f15977fd4f7d373b980a1c60ee7671ba143d1635ffaf533c3e1add523f1f763a73ce183df24c0209dd7
</auth>

general: Disconnected: Connection Closed
[offline]:
[offline]:

**Comment by hiwaleakshay** [comment]
have you tried updating s40 env to latest one?
and save your login and password in a file and use this command
yowsup-cli demos -E s40 -y your-file.txt
check if it works.

**Comment by v1v3kgithub** [comment]
@hiwaleakshay  Did you ever get banned using that sequence of events /L /presence ...etc.
