### ISSUE TITLE
Account block on CLI number sync

### ISSUE THREAD

**Issue by 10p30pl3** [tgalal/yowsup#2298]
Hi I'm experiencing recurrent blocking problems while syncing numbers, using CLI demo.
The steps to reproduce the error are the following:
0-use brand new sim chip
1-register with env android
2-register with env s40
3-connect to CLI demo with s40
4-set presence available
5-sync contact 1st, ok, 2nd, ok. 3th error-block....

Any ideas? Help!

/contacts sync 5511967894059
DEBUG:yowsup.layers.logger.layer:tx:
<iq type="get" id="27" xmlns="urn:xmpp:whatsapp:sync">
<sync mode="full" last="true" sid="131528296660000000" context="interactive" index="0">
<user>
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</sync>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="5511943175908@s.whatsapp.net" type="result" id="27">
<sync last="true" wait="454271" sid="131528296660000000" version="1508348299077556" index="0">
<out>
<user jid="551967894059@s.whatsapp.net" is_biz="false">
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</out>
</sync>
</iq>

Iq:
ID: 27
Type: result
from: 5511943175908@s.whatsapp.net
Wait: 454271
Version: 1508348299077556
In Numbers:
Out Numbers: 5511967894059
Invalid Numbers:

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

**Comment by emmekappa** [comment]
I have the same issue.

**Comment by hiwaleakshay** [comment]
Looking at your debug log I don't think whatsapp is banning your account.
If whatsapp has banned you will get 
"Auth Error, not-authorized"

P.S why are you registering using both enviornment?

**Comment by 10p30pl3** [comment]
Answering your question, I believed I have to register S40 because only S40 is working on yowsup to send and receive messages. Any suggestion?


Yes if I try to login again, I get the error:

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
¸A»�©V
-y¿Þê4A4p¿´ÊýñÐF;SÁ=ð�)1Ê�
ÿ½×)�×�8£�
HEX3:b'b841bb8fa9560ad312c83799fe45d330139a5f20214f3dce21694e6edbaabc2931ca0692070d2d79bfdeea34413470bfb4cafdf1d0463b53c13df0970affbdd7299ed79238a397'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

**Comment by hiwaleakshay** [comment]
DId you send message to a number without syncing the contact? if so whatsapp will flag your number.
Also , are u able to register with another number?

**Comment by 10p30pl3** [comment]
No, in fact, I only synced the numbers, no messages at all. 
Yes I registered a couple of numbers and all with same results.
Anyone any ideas?

**Comment by sealabr** [comment]
Hi, got two numbers yesterday blocked at the same time.... at the same hour

```
19-10-2017 21:02:43 root         INFO     Login Failed, reason: not-authorized
19-10-2017 21:02:43 root         DEBUG    Disconnected, reason: Authentication Failure
```

also, @hiwaleakshay  I dont sync contacs to send messages, this maybe by the problem for whatsapp flag my numbers?

**Comment by hiwaleakshay** [comment]
@10p30pl3 honestly, i dont know whats causing the issue then. Because i had synced more than 30 numbers and using same account since last week.
I assume you had updated env for md5 classes and app version to the current before registering. 
Also, another thaught, maybe due to multiple registration whatsapp banned your ip. Try using vpn for next registration. Hope ot will help, not sure though.

**Comment by hiwaleakshay** [comment]
@sealabr yes , infact you have to follow the normal sequence before sending a message. 
1 sync contact
2 presence available
3 presence subscribe
4 send typing status
5 pause typing status
6 Send message.
7 recv ack 
8 presence unavailable
9 disconnect


Otherwise whatsapp server will mark it as malicious activity and block your number.

**Comment by 10p30pl3** [comment]
@hiwaleakshay doublechecking:
Do you use s40 or android to send messages? If using s40, you don't register as s40 before sending messages?
Thanks !

**class S40YowsupEnv(YowsupEnv):**
    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
    _AXOLOTL = True



**class AndroidYowsupEnv(YowsupEnv):**    
    _MD5_CLASSES = "IdHZifpmNTVVCJ50Cu7RMA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.350"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

**Comment by hiwaleakshay** [comment]
I am using android for registration, S40 for login and other purposes
BTW,
mine android cleasses is diffrent i am using 2.17.351
`    _MD5_CLASSES = "zviZxGYlzifSqmoeCNJavw=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.351"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"`

and for S40
`    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True`

These are latest to best of my knowledge.

**Comment by 10p30pl3** [comment]
Excellent thank you.
I found a place where supposedly the latest versions are updated.
https://coderus.openrepos.net/whitesoft/whatsapp_scratch
There, it seems like that the latest version for android is:
 2.17.382 / U8YKQz7RmCqya+X4wzQRtw==
For s40 I was ok.
I updated my environment, lets see, fingers crossed...
Just another check:
Do you use the yowsup/tgalal version with python 2.7x?

**Comment by sealabr** [comment]
@hiwaleakshay , how to send event "9 disconnect" in yowsup? If i disconect I will be unable to receive messages?

**Comment by hiwaleakshay** [comment]
@10p30pl3  opps!!!, look like even i need to update. Thank you for sharing.
and yes i use yowsup with 2.7.

**Comment by hiwaleakshay** [comment]
@sealabr yeah, my bad u i thought u just want to send a message.
in case if you want to keep listening for incoming messages stay connected.
But remember each time you send message you need to follow those steps.

**Comment by 10p30pl3** [comment]
Unfortunately I activated another sim and I was blocked again, even with updated envs. 
Do you think my testing method is correct? It's should be as simple as possible, register, open CLI, syncing some numbers I'm blocked. I wonder if CLI has any bug on the syncing process?

**Comment by DwarfKiller** [comment]
@hiwaleakshay 
You commented on the nine steps, about the contact of 1 synchronization.
Every time I send a message I have to synchronize or have a period to send?

**Comment by hiwaleakshay** [comment]
@10p30pl3 no i dont think cli has bug and testing method is also correct. Maybe ip issue.. dont know for sure now. 
Yet another thaught, dont try to use account on mobile as well as yowsup simultaneously. If you are registering a number from yowsup then you must have that account deleted from mobile.

**Comment by hiwaleakshay** [comment]
@DwarfKiller
Once synced, you dont have to sync it again unless you are using another account.

**Comment by 10p30pl3** [comment]
I used to have 3 numbers running with different versions of yowsup for a couple of weeks, but suddenly 2 out of 3 accounts just got banned. 
Anyone else have similar problems or is it just me?

**Comment by DwarfKiller** [comment]
@10p30pl3 

I had found that number had been banned too, but I looked at this forum and then update the version of s40 returned to work the same number.

https://github.com/tgalal/yowsup/issues/2319

**Comment by 10p30pl3** [comment]
@DwarfKiller my s40 was already on the latest version... and my numbers were really blocked. Any thoughts?

**Comment by DwarfKiller** [comment]
@10p30pl3 Unfortunately, I have no idea.

**Comment by 10p30pl3** [comment]
@DwarfKiller, lets go back to the basics. Do you have any working number?
