### ISSUE TITLE
Echoclient crashes when sharing the location in real time

### ISSUE THREAD

**Issue by fcorrales** [tgalal/yowsup#2300]
With the new update of the application in which they added the possibility of sharing the location in real time, the echoclient crashes.
This is a new feature of the application so the issue is recent.

If anyone knows how to prevent this crash please let us know.

Thanks!

**Comment by renemendoza** [comment]
this also happens to me, i guess we need to provide at least a temporary fix to ignore realtime location messages

**Comment by Nicos-git** [comment]
Maybe this already solves your problem, #2208

**Comment by albertosl01** [comment]
The fix #2208 dont resolve the issue

**Comment by Nicos-git** [comment]
It's true.
You also need to insert 

```
        elif node["type"] == "location":
            # Not implemented
            pass
```
in https://github.com/tgalal/yowsup/blob/9384462e8d250e58ab26c648e6174392416c326b/yowsup/layers/protocol_notifications/layer.py#L40

**Comment by tgalal** [comment]
9d8d13b68f1704c2deecf6fde1e0118fa30ebd38
