### ISSUE TITLE
Is this working now ?

### ISSUE THREAD

**Issue by richardm47** [tgalal/yowsup#2301]
Want to now that as of this day is this project working and compatible with the current versions of whatsapp ?

I am stuck at 

status: fail
reason: old_version
login: 9198XXXXXXXX

Tried almost every fix but still at this status.

**Comment by deepakjeena** [comment]
@blackunicorn47 
yes it working,
open file env/env_android.py 
and update value with below lines.
_MD5_CLASSES = "IdHZifpmNTVVCJ50Cu7RMA=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
_VERSION = "2.17.350"

reinstall it
and run command again with android environment.

**Comment by blackunicorn47** [comment]
by reinstall you mean "setup.py install" ?

**Comment by deepakjeena** [comment]
@blackunicorn47 
yes setup.py install
or you can search env_android.py file in system and update values.

**Comment by BetaUliansyah** [comment]
working fine here.

**Comment by blackunicorn47** [comment]
Got the verification code on my mobile number but when registering I get this error -

yowsup-cli registration --register 115XXX --phone 9198XXXXXXXX --cc 91

status: fail
reason: old_version
login: 9198XXXXXXXX

Any leads ?

**Comment by ykguCoder** [comment]
@BetaUliansyah the phone is blocked without send message,why?

**Comment by deepakjeena** [comment]
@blackunicorn47  while running this command please set environment to android #

**Comment by blackunicorn47** [comment]
@deepakjeena working !
just a curious question, how/where did you get the compatible values for _MD5, _KEY and _VERSION ?

**Comment by afonsolage** [comment]
I'm asking myself the same, where to get those infos from?

**Comment by deepakjeena** [comment]
@blackunicorn47 
@afonsolage 

hit url 
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

**Comment by afonsolage** [comment]
@deepakjeena Thanks for your reply, but this url didn't tell me where those infos come from.

**Comment by iamjagjeetubhi** [comment]
Please read [this](https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/) blog. Everything explained very well!

**Comment by tgalal** [comment]
fixed

**Comment by MSKouli** [comment]
@deepakjeena 
> hit url
> https://coderus.openrepos.net/whitesoft/whatsapp_scratch
I have registered successfully but It's not connecting to Whatsapp server showing 
"general: Disconnected: Connection Closed"
I changed my env.py to android also
