### ISSUE TITLE
anyone can help?

### ISSUE THREAD

**Issue by gittempo** [tgalal/yowsup#2302]
Actually i don't know python and i could not find any working PHP api for whatsapp.

This one is only working on but sadly it is in python :-(

Anyone can help me to install it on server and make it work for me?

or if any of you have any PHP working API please share with me.

**Comment by antonid08** [comment]
Hi!
Use github search. 
https://github.com/mgp25/Instagram-API

Regards.

**Comment by gittempo** [comment]
@antonid08 i need to go with whatsApp api.
I used mgp25 whatsapp api but there is no support available

**Comment by dineshobjects** [comment]
I have same issue. Please help

**Comment by schoerg** [comment]
@antonid08 that's instagram...
@gittempo try this https://github.com/mgp25/Chat-API

**Comment by gittempo** [comment]
@schoerg i spent ages in the php Chat-API but it does not work now. It used to work before two years.

I have no python knowledge and yousup is only working api i have found on internet.

Can you please help me to install it on my server? And get my phone number registered? Ans give me an example of sending text message to my friends in the correct sequence so my number does not get blocked.

I think this is not more than 20 minute task because everything exists in api. I only have to learn how to use them

**Comment by schoerg** [comment]
Look at the echoclient example. Works for me. I use the S40 env, no ban as of yet. Not sure on what I used to register that number, was some time ago.

**Comment by gittempo** [comment]
I will try it 
Can i have your skype?

Thank you

**Comment by schoerg** [comment]
No.
If you have questions you can ask them here.

**Comment by gittempo** [comment]
No problem
But i asked my questions here and nobody helped.

**Comment by schoerg** [comment]
Because your questions are too generic and contain little info.
Lile this issue: Server install? What have you tried? Which OS, any error messages?

**Comment by gittempo** [comment]
For registering my number in env files what changes do i have to make?

I tried token and md5Classes variable but they didnot work.

Evevrytime it returns bad_token

**Comment by r0alt** [comment]
yowsup/env/env_android.py

_MD5_CLASSES = "5h7dTJYD1ogHDxfiIXIZxg=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvs$

    _VERSION = "2.17.286"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True


it works for me ;)
