### ISSUE TITLE
How to resolve the enc image issue?

### ISSUE THREAD

**Issue by bachoo786** [tgalal/yowsup#2310]
Hi 

I have installed yowsup all working well but I cannot receive any images I get a link with .enc ending which is encrypted. 

How can I get this to be the normal .jpeg file?

My yowsup details are :
yowsup-cli  v2.0.15
yowsup      v2.5.2

PS: Please let me know which files I need to change the code in as I am abit of a NOOB. 

Thanks.

**Comment by tgalal** [comment]
yowsup 3.2.0+
