### ISSUE TITLE
YowSup registration don‘t work. :/

### ISSUE THREAD

**Issue by Marvin-Media** [tgalal/yowsup#2313]
```
./yowsup-cli registration --requestcode sms --phone 49xxxxxx --cc 49 --mcc 262 --mnc 03 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"4915xxxxxxx","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 491xxxxxxx
```

I have env_android.py also changed in The new Version, but it dosn‘t work.

**Comment by blackunicorn47** [comment]
#2301

**Comment by antonid08** [comment]
Whatsapp cant work with old android apk.

To force it to work you need:
1) clone repo from git
2) change values in yowsup/env/env_android.py
 _VERSION, _MD5_CLASSES  to values from this site: https://coderus.openrepos.net/whitesoft/whatsapp_scratch
'd' and 'a'.
3) install library from changed sources
4) add '-E android' when register

**Comment by Marvin-Media** [comment]
I have changed the env_android.py, but same error.
3. python setup.py install (ist that right ?)

**Comment by antonid08** [comment]
It's strange. Check is your version equals to version from whatsapp site https://www.whatsapp.com/android/.

3. yes

do u use library from terminal? you are sure that you use option "-E android"?

**Comment by Marvin-Media** [comment]
But when I run the befhel "python setup.py install" the env_android.py is changed back to the original one.

**Comment by Marvin-Media** [comment]
I have fixed it thank you so much.

**Comment by jsomission** [comment]
Hello,
What did you do to fix it? I have the same problem.

**Comment by Marvin-Media** [comment]
So you go to the path `cd yowsup/yowsup/env` and change the file there as described above.
With me it was so that I did not have to execute the `python setup.py install` command.

**Comment by fernajuf** [comment]
Hello:

I follow the instructions regarding the modification of env_android.py.
Register my number with the parameter -E android.
I returned:
```
status: ok
kind: free
pw: my password
price: $ 0.99
price_expiration: 1511267169
currency: USD
cost: 0.99
expiration: 4444444444.0
login: my number
type: existing
```
But when I try to send a message, it returns me:
`Authentication Error: not-authorized`

Any idea?.
Thanks on advance.

**Comment by antonid08** [comment]
@fernajuf 
Hello. 
First of all, try to change version in `env/env_s40.py`  to `2.16.12`. It has been upgraded about a week ago. Don't forget reinstall yowsup after that. And, propaply, you will need to register new account (but try with this first).
  
If not help, write here, i have some extra variants.

**Comment by fernajuf** [comment]
¡It works!
Thank you.

**Comment by MSKouli** [comment]
> @fernajuf
> Hello.
> First of all, try to change version in `env/env_s40.py` to `2.16.12`. It has been upgraded about a week ago. Don't forget reinstall yowsup after that. And, propaply, you will need to register new account (but try with this first).
> 
> If not help, write here, i have some extra variants.

Yes I need some extra variants, registration has done perfectly but I am getting
 "general: Disconnected: Connection Closed"
I've changed env.py to android also
