### ISSUE TITLE
Anyone can send image just in one command, not into the client mode

### ISSUE THREAD

**Issue by kitsontam** [tgalal/yowsup#2315]
Because i'm writing the script using python, I can send message via below command. but not sending image.

`os.system("python3 ~/yowsup/yowsup-cli demos -c ~/yowsup-cli.conf -s xxxxxxx 'Motion Detected a$`

**Comment by deepakjeena** [comment]
@kitsontam 
use yowsup as python library not as system call with cli.

**Comment by kitsontam** [comment]
@deepakjeena would you mind with the example?

**Comment by kafffee** [comment]
I also tried os.system and s
ubprocess.call and it wont work.
Whereas using the yowsup library returns:
from yowsup import env
Import error: no module named 'yowsup'

Would be cool if you gave me a hint

**Comment by kafffee** [comment]
For deepakjena: You can find the example also on github.com:
https://github.com/tgalal/yowsup/blob/master/yowsup%2Fdemos%2Fcli%2Flayer.py

**Comment by kafffee** [comment]
Then just add the following to the code:
from whatsapp import Client
phone_to = '49xxxxxxxx'
client = Client(login='49yyyyyy', password='mypassword')
client.send_message(phone_to,'Hello World')
client.send_media(phone_to,'media.jpg')


Xxxxx is your target phone number, yyyy is your phone number

**Comment by kafffee** [comment]
If you need help installing yowsup library give me a hint

**Comment by the-jojo-jj** [comment]
@kafffee hi, can you help me to install yowsup library?
