### ISSUE TITLE
Demo fails with reason: old_version

### ISSUE THREAD

**Issue by zavitax** [tgalal/yowsup#2316]
Trying to register with yowsup-cli on Windows 10.

>python yowsup-cli registration --requestcode sms --mcc 972 --mnc 19 --cc 972 --phone 972XXXXXXXXX
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution isencouraged.

If you appreciate this software and you would like to support futuredevelopment please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:b'{"login":"972XXXXXXXXX","status":"fail","reason":"old_version"}\n'
reason: b'old_version'
login: b'972XXXXXXXXX'
status: b'fail'

**Comment by zecjy** [comment]
Did you updated android env?

**Comment by zavitax** [comment]
Yes, this was not immediately clear, apologies.
