### ISSUE TITLE
s40 login not working?

### ISSUE THREAD

**Issue by rahul1996** [tgalal/yowsup#2319]
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

Number not blocked. Tried re-registering.

**Comment by bahtiarp** [comment]
same issue, all number not authorized since 4 hours ago.
Not blocked.

**Comment by cyberp1983** [comment]
yes. not-authorized

**Comment by VaniaAntoshkin** [comment]
Confirm. Login Failed, reason: not-authorized

**Comment by HeinzFo** [comment]
same issue!
On different Windows 7/10 PCs with different phone numbers.

Output in cmd window:

> C:\Yowsup>c:\python27\python.exe C:\Yowsup\yowsup-cli demos -s 491xxxxxxx "send message" -c c:\Yowsup\yowsup-config/yowsup.config
yowsup-cli  v2.0.15
yowsup      v2.5.2
Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org
This software is provided free of charge. Copying and redistribution is encouraged.
If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
Authentication Error: not-authorized
C:\Yowsup>

**Comment by KundKMC** [comment]
Same here, on ALL channel - exactly the same time. We already tries to log in from various locations - always the same. When trying to reregister we get the:

INFO:yowsup.common.http.warequest:{"login":"XXXXXX","status":"fail","reason":"old_version"}

thing. Maybe Yowsub API on Whatsapp's side is gone? They wanted to keep it up till december 2018?!

**Comment by HeinzFo** [comment]
Hello KundKMC

In Line 4 of your post I read ..."old_version"

May be related to the VERSION string in yowsup/env/env_s40.py ?

This was in the past a problem and a update to __VERSION = "2.16.11"_ was the solution.
May be a newer version number can solve the problem?

Regards

**Comment by KundKMC** [comment]
Hey Heinzfo, thanks for the advice - but my env_s40.py reads like:

class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"

Before this night, yowsup was working fine. I think they did something on WhatsApp side ;(

**Comment by rahul1996** [comment]
I think whatsapp have either updated the **version** or **token**

**Comment by HeinzFo** [comment]
Hi KundKMC

I mean must higher then 2.16.11
Or the _TOKEN_STRING needs a update like posted from rahul1996
But the _AXOLOTL was also affected in the past.

**Comment by KundKMC** [comment]
Hmmm, that's worth a shot. Can someone provide a suggestion for different setting than:

class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True

**Comment by RaistlenM** [comment]
This seems to sort it out..

_VERSION = "2.16.12"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "302"
_MANUFACTURER = "Nokia"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
_AXOLOTL = True

**Comment by bahtiarp** [comment]
@RaistlenM , how to generate such string, for next time if it become old_version again?

**Comment by HeinzFo** [comment]
Hi RaistlenM 

I change from _VERSION = "2.16.1**1**" to _VERSION = "2.16.1**2**"

Now it works ;-)

Tanks!

**Comment by RaistlenM** [comment]
I didnt, found it in the issues

**Comment by VaniaAntoshkin** [comment]
RaistlenM version works! Thank you!

**Comment by KundKMC** [comment]
It's crazy but it really works. Just changing to 2.16.12 @RaistlenM you just made my day ;)

**Comment by RaistlenM** [comment]
:)

**Comment by YuvalPruss** [comment]
Thanks @RaistlenM !

**Comment by fangfufu** [comment]
@RaistlenM 's solution works.

**Comment by D0m3L** [comment]
@HeinzFo @RaistlenM thanks guys for saving the day!

**Comment by lesimoes** [comment]
Hello,
I change to VERSION = "2.16.12" but doesnt work. :(

**Comment by HeinzFo** [comment]
Hi

On my Windows PCs no restart required but my Raspberry Pi needs an restart!

**Comment by rahul1996** [comment]
@HeinzFo how do you autorun the python script in Raspberry Pi?

**Comment by HeinzFo** [comment]
Hi rahul1996

On the RPi I use FHEM www.fhem.de this is a perl application.
There is a module with that functions you can use yowsup.
I have no deeper knowledge about that.

Regards

**Comment by Retsim** [comment]
Hey,
Thanks @RaistlenM !
Did someone got the corresponding working change for env_android too ?

**Comment by BRNALX** [comment]
@RaistlenM

Thanks! Work for me.

How do you know the new token for the S40?

**Comment by nked** [comment]
@bahtiarp #1726 You can use this code to automatically update version and token string.

**Comment by r0alt** [comment]
this works for me on:
env_android.py
```
_MD5_CLASSES = "5h7dTJYD1ogHDxfiIXIZxg=="
_VERSION = "2.17.286"
```

**Comment by mathslimin** [comment]
i get the error
status: fail
retry_after: 3600
reason: no_routes
$python yowsup-cli registration --requestcode sms --phone 86********* --cc 86 --mcc 460 --mnc 01 -E s40
status: fail
retry_after: 76
reason: too_recent
login: 86*********

**Comment by eladhay** [comment]
@RaistlenM Works. Thanks a lot.

**Comment by dpz3579** [comment]
Hi do look at 
[Whatsapp version API](https://coderus.openrepos.net/whitesoft/whatsapp_scratch
)

this gives dex md5 of latest android version & version number of s40 running live.

For the android look at keys a & d. (a=> dex code , d=> version)

For s40 look at "e" for version.

**Comment by alejandrosofter** [comment]
not is a solution stable to develop with yowsup.. more than 10 sim blocked in 2 days with diferents IP's .. is a wasted time

**Comment by KundKMC** [comment]
The whole WhatsApp thing is not very stable. I think this is nothing sepcial about yowsub - it's the creepy Facebook strategy for WhatsApp that is doing the harm. I always wonder why WhatsApp is so successful and crappy at the same time. 

@alejandrosofter what else to use to communicate with the WhatsApp world?

**Comment by 10p30pl3** [comment]
@alejandrosofter this seems to be the rule. Anyone else is getting better results?

**Comment by Mega4alik** [comment]
Hi, getting old_version error on registration with configurations: 
_VERSION = "2.16.12"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "302"
_MANUFACTURER = "Nokia"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
_AXOLOTL = True

**Comment by dpz3579** [comment]
try

_VERSION = "**2.16.12**"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "302"
_MANUFACTURER = "Nokia"
_TOKEN_STRING  = "**PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}**"
_AXOLOTL = True

**Comment by dpz3579** [comment]
someone please deduce this & help me.
Hope this will solve the issue for Old version.

[Whatsapp token generation](https://github.com/mgp25/Chat-API/wiki/Token-Generation)

**Comment by Mega4alik** [comment]
@dpz3579 Thanks for help, 
I have a question
How to get the latest timestamp? 

Thanks in advance

**Comment by dpz3579** [comment]
Hi @Mega4alik,

Sorry man,
I'm even trying to figure out the same.
will update you as soon as I come across a solution.

**Comment by hgc2002** [comment]
solved. see #2350

**Comment by niaomingjian** [comment]
@lesimoes 
Hi, have you solved this issue? I met the same error, and changing version doesn't work for me.

**Comment by tgalal** [comment]
update yowsup, register using android env, login using s40 env
