### ISSUE TITLE
Cant Login Env S40 - Not Blocked or Banned

### ISSUE THREAD

**Issue by sealabr** [tgalal/yowsup#2320]
hello I'm facing a problem with youwsup, cant login in ANY env S40 or Android by CLI.

```
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

```

Already tried:
- updated the env S40 VERSION  and _TOKEN_STRING to version "2.16.12"
- Updated the env Android to latest 2.17.242
- Change ip of the machines
- Used another numbers

**Comment by sealabr** [comment]
Loqui.im Works allright.

**Comment by Jeronimo17** [comment]
The same thing happens to me today with "wxpyWha"

**Comment by sealabr** [comment]
solved here.. with https://github.com/AragurDEV/yowsup with python3.. I will close this issue.
