### ISSUE TITLE
Messages do not arrive

### ISSUE THREAD

**Issue by leoteixeira2016** [tgalal/yowsup#2321]
I can send the messages, but they do not reach the destination.
help!!! please

INFO:yowsup.demos.sendclient.layer:Message sent
http://openwhatsapp.org/yowsup/donate

Log 
shows that it was sent

**Comment by hdiazvertical** [comment]
me too :(

**Comment by afonsolage** [comment]
Same here

**Comment by hmrasi** [comment]
I'm getting the error regarding the axolotl curve i.e, ModuleNotFoundError : No Module Name 'axolotl_curve25529'.
while sending the message. 
anybody help?
