### ISSUE TITLE
How do you check for bans ?

### ISSUE THREAD

**Issue by Retsim** [tgalal/yowsup#2324]
Hi,

Currently trying to understand how I can check for banned number(s).
"not-authorized" message is not reliable as for example s40 or android login can be misconfigured.
How do you make sure the current number is banned, or not ?

Thanks for sharing

**Comment by PedroFcul** [comment]
launch the cli with python yowsup-cli demos -l [phone]:[password] -E s40 --yowsup --debug
if the answer contains something like reason: blocked (i dont remember the whole message), then the number is banned
