### ISSUE TITLE
registration status: fail reason: old_version 

### ISSUE THREAD

**Issue by mathslimin** [tgalal/yowsup#2327]
yowsup-cli registration --requestcode sms --phone 86XXXXXXXX --cc 86 --mcc 460 --mnc 01

**Comment by StrangeGamerHD** [comment]
have that issue too

**Comment by StrangeGamerHD** [comment]
I think i know why:
In the wiki:

> If you can't obtain the IMEI/MAC, or using an unsupported phone, or if you have recently updated your phone's Whatsapp client, then this would not work

**Comment by ericksode** [comment]
Open file yowsuo/env/
nano env_android.py
and update value with below lines.
_MD5_CLASSES = "IdHZifpmNTVVCJ50Cu7RMA=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
_VERSION = "2.17.350"

reinstall it 

AND add -E android

yowsup-cli registration --requestcode sms --phone 86XXXXXXXX --cc 86 --mcc 460 --mnc 01 -E android

and that's it

**Comment by mathslimin** [comment]
@ericksode  it works, thank you
