### ISSUE TITLE
fail reson no_routes

### ISSUE THREAD

**Issue by mathslimin** [tgalal/yowsup#2328]
./yowsup-cli registration --requestcode sms --phone 86186******** --cc 86 --mcc 460 --mnc 01 -E android

status: fail
retry_after: 3600
reason: no_routes
login: 86****

**Comment by alexislg2** [comment]
What was the cause/solution?

**Comment by mathslimin** [comment]
@aiexisig2 env/env_android.py upgrade to latest version, fix this issue
