### ISSUE TITLE
general: Disconnected: Connection Closed

### ISSUE THREAD

**Issue by masterwaqar** [tgalal/yowsup#2329]
I am kind of stuck. 

Already go SMS and have registered but when ever i am trying to connect getting message

general: Disconnected: Connection Closed

I have used yowsup in past 2014, it was working like a charm. But this time i am not able to make it work. 

tried
/L

/login 968xxxxx xxxxx

but all getting same :-s

I am using android, s40 seems like not working anymore.

**Comment by masterwaqar** [comment]
Not sure what happened but i change the version for s40 and added -E s40 into the command now it is working.

**Comment by dpz3579** [comment]
hi, @masterwaqar what have you changed?

I was able to login to yowsup-cli,
but later was getting, I tried /L, but is showing connection-closed,
can you please help me.

```
[offline]:/L
general: Disconnected: Connection Closed
[offline]:
[offline]:/L
general: Disconnected: Connection Closed
[offline]:
```

**Comment by masterwaqar** [comment]
Hi I add -E s40 in command and changed the version at env_s40.py to .212.

Best regards
Waqar Latif
