### ISSUE TITLE
Different database back-end for axolot layer

### ISSUE THREAD

**Issue by pavlodvornikov** [tgalal/yowsup#2330]
I'm facing problems using yowsup with well-known PaaS which does not support SQLite. Will it take much efforts to allow yowsup users to choose which database back-end to use ?

**Comment by BRNALX** [comment]
Leave the yowsup database (axolot.db) unique to what was designed, create a separate database on the platform you want to work with the particularities of your application.

**Comment by pavlodvornikov** [comment]
I will close it as it is not valid for me anymore.
