### ISSUE TITLE
How to receive URL with preview

### ISSUE THREAD

**Issue by rahul1996** [tgalal/yowsup#2332]
Is there any way to receive URL with preview or throw an error for it. Currently I am getting this error. 

UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte in field: com.whatsapp.proto.UrlMessage.jpeg_thumbnail

Please help me fix it

**Comment by danielcardeenas** [comment]
You want to ignore the image or get the image?

**Comment by rahul1996** [comment]
Want to get the image.

**Comment by msm2k11** [comment]
looking also for a solution to receive preview of og-Tags from a URL

**Comment by tgalal** [comment]
0acd4400e35cf7921def5162a92fcd5d0f64b806
