### ISSUE TITLE
Whatsapp Connection Closed although using new mobile number

### ISSUE THREAD

**Issue by spt-shwetech** [tgalal/yowsup#2333]
It works previous day but I can't login to whatsapp. So that i try to login with new phone number but the following error message shows again. 

```
DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
®w±/R¬£ÃvÿðdõF
HEX3:b'93ae77998bb1821f2f52aca3c376fff064f58646'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
´*ÅGqØ}3·û@³&Å»@ZÊ1#Pli/bÌ                      Ûw¿/z;_pNÙ
HEX3:b'07b42ac5478a71d87d3381b7fb827f4013b32606c5bb405a00ca31072350016c82692f629a16cc0c9a4df8d8a15121ac4dd5c46f6fa91efcf0a66aed31e34e8ddb77bf80962f7a3b5f999d704ed9'
</response>

^[[?62;c^[[?62;cDEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
```

**Comment by dgazotto** [comment]
I'm having the same problem. I registered a new number with android environment (because s40 was returning the old version error), also I delete the folder .yowsup and I can't send or receive messages (connection closed). I tried to change the environment to s40 to send the message and avoid this error, but the response was: not-authorized. Any solutions?

**Comment by fjrmaulana** [comment]
me.. to, how function a folde phone name/number located on home/user/ there are oxolotl.db for whats this?

**Comment by gdperellon** [comment]
Same for me. I get it working last month in another platform (PI Nano) but now in PI ZERO do not work.

**Comment by tgalal** [comment]
update yowsup, register using android env, login using s40 env

**Comment by soulhunter32** [comment]
> update yowsup, register using android env, login using s40 env

Does this works ? I've read in other places that doing this you get banned, it seems logic, you register with one device and send menssages from another. Can you please confirm this @tgalal my friend ?

Regards.-
