### ISSUE TITLE
bad_token, token Expired

### ISSUE THREAD

**Issue by wengoooooooo** [tgalal/yowsup#2334]
_VERSION = "2.16.12"
token = PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194472015{phone}

status: fail
reason: bad_token
login: 8521234456

Who has a new token??

**Comment by danielcardeenas** [comment]
Register using android env

**Comment by vinayakvasu** [comment]
$classesMd5 = 'o17G0Imoh/pOmI5FpLpKHQ=='; // 2.17.420

**Comment by hmrasi** [comment]
I'm getting the problem regarding the axolotl_curve25519 installation.
it is displaying the error like

 NoModuleFound error: No Module Found for "Axolotl_curve25519".

can anyone help please!

**Comment by vinayakvasu** [comment]
did u followed the installation in the readme?

pip install yowsup2

**Comment by hmrasi** [comment]
yeah i have installed all the mentioned steps in the README. Even im getting the same error while sending the message.
Can you check the syntax:
python yowsup-cli demos --config c:/yowsup/yowsup_config.txt --send 911xxxxxxxxxx "hi"

**Comment by hmrasi** [comment]
This is what i'm getting when i'm trying to send a message. 
Can u please help me with the issue?

**Comment by vinayakvasu** [comment]
can u try with python2.7

**Comment by hmrasi** [comment]
Presently I'm using python 3.6
Is it possible by using virtual environment?

**Comment by hmrasi** [comment]
Is it necessary to install mingw compiler?
I haven't installed during the process, can somebody help me fixing the issue?

**Comment by danielcardeenas** [comment]
You need to register using the -E android flag. Check this

**Comment by danielcardeenas** [comment]
Registration part described in the README.md of this repo

https://github.com/danielcardeenas/whatsapp-framework

**Comment by hmrasi** [comment]
I'm using windows. After following your steps, im getting the error like old version. how can i send a message rectifying this?

**Comment by danielcardeenas** [comment]
You need to update your android_env.py file. And compile yowsup again.
The file should look like this:
https://github.com/danielcardeenas/whatsapp-framework/blob/master/libs/yowsup/yowsup/env/env_android.py

**Comment by tgalal** [comment]
update yowsup, register using android env, login using s40 env

**Comment by hmrasi** [comment]
![image](https://user-images.githubusercontent.com/33692337/36091130-bf9d5fbe-1008-11e8-9565-ad84aa1bc25c.png)
Still getting the same error.

**Comment by hmrasi** [comment]
I have the error while im trying to login

![image](https://user-images.githubusercontent.com/33692337/36092969-353c6cb4-100f-11e8-9934-ffc17c27d6e5.png)
