### ISSUE TITLE
Getting banned on checking presense

### ISSUE THREAD

**Issue by Silkroad1337** [tgalal/yowsup#2339]
`python yowsup-cli demos --config whatsapp_config.txt -E s40 --yowsup`

`/presence available
/contacts sync <contact>
/presence subscribe <contact>`

I get all my accounts banned on using this. I dont want to send any msg. All i need is check someone's (online/offline) status. Since i heard people only use android_env for registration i use s40 with yowsup-cli.

Here is my android and s40 env.

Android:
`    _MD5_CLASSES = "5h7dTJYD1ogHDxfiIXIZxg=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.286"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True`

s40 env:

    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
    _AXOLOTL = True

whats wrong?

**Comment by hmrasi** [comment]
python yowsup-cli demos --config whatsapp_config.txt -E s40 --yowsup

use android in the place of s40.

**Comment by 10p30pl3** [comment]
@hmrasi android env does not work, only for registration

**Comment by thatskriptkid** [comment]
@Silkroad1337 Hi! I'm getting banned too after 1 day use. My env s40 same as your. Do we need to sync and subscribe every time we start presence checking script? I thought we should subscribe only once. If we must subscribe every time then do we need to unsubscribe every time we disconnect?

**Comment by hassaan-dev** [comment]
@thatskriptkid does your account unbanned?
