### ISSUE TITLE
Extracting WhatsApp password from Android devices

### ISSUE THREAD

**Issue by whatsappnomedia** [tgalal/yowsup#234]
This may be useful for someone:

WhatsApp stores the user credentials in a 'pw' file within the sandbox, while the 'me' file contains the Jabber ID.
In addition, it stores on the SD card (in "Exteranal Storage/WhatsApp/Profile Pictures/.nomedia") a token that can be used for registration without confirmation via SMS.

Here's a small Python program to get you started:

from pbkdf2 import PBKDF2
from Crypto.Cipher import AES
import base64
import time
import javaobj
import re

sauce1 = '\xc2\x99\x1e\xc2\x9b\x1d\x0c\xc2\xb8\xc3\xb7UdX\xc2\x98\xc2\x92\x03\xc2\x8bE\xc2\x97>x\xc3\x86\xc3\x95'
sauce2 = 'S\x16\x0fR\x03\nD\xc2\x83\x10\xc2\x82\xc2\x9a\xc2\x8d\xc2\x8cF:!i)WA'

def do_decode(special_sauce, jabber_id, pw_file_content):
    salt = pw_file_content[2:6]
    iv = pw_file_content[6:22]
    encrypted_key = pw_file_content[22:]
    file_enc_key = PBKDF2(special_sauce + jabber_id, salt, 16).read(16)
    crypt = AES.new(file_enc_key, AES.MODE_OFB, iv)
    return crypt.decrypt(encrypted_key + '1'*12)[:20]

def decode_pw(mefname, pwfname):
    jabber_id = javaobj.JavaObjectUnmarshaller(open(mefname)).readObject().jabber_id
    pw = javaobj.JavaObjectUnmarshaller(open(pwfname)).readObject()
    pw_file_content = "".join([chr(c) if c>=0 else chr(c+256) for c in pw])
    wa_key = do_decode(sauce1, jabber_id, pw_file_content)
    return base64.b64encode(wa_key)

C = re.compile("^([17]|2[07]|3[0123469]|4[013456789]|5[12345678]|6[0123456]|8[1246]|9[0123458]|\d{3})\d*?(\d{4,6})$")

def decode_nomedia(nomedia, pn, account):
    g = C.match(pn)
    e = g.group(1) + g.group(2)
    jabberid = e + account
    pw = javaobj.JavaObjectUnmarshaller(open(nomedia)).readObject()
    pw_file_content = "".join([chr(c) if c>=0 else chr(c+256) for c in pw])
    return do_decode(sauce2, jabberid, pw_file_content)

print "%r" % (decode_nomedia(".nomedia", "12125551234", "your.google.account@gmail.com"),)
##

**Comment by nephilim1973** [comment]
Probaly it would be possible to post the final version of the python code here with the CODE view (just place 4 spaces in front of each line)

    This is a code example line

So we all could share your experience and probably could improve some things better.
Regards

**Comment by ahmadjmal** [comment]
Please.can anyone generate a nomedia file for me.
and I will give him my number and my email
or,please make a video for this
thank you

**Comment by pythonimus** [comment]
Does the "adb backup -apk -share com.whatsapp" code still work?
On my Nexus 5 I get a 1KB file which i cannot decompress.

**Comment by ahmadjmal** [comment]
@mgp25 I need to registration an old account in whatsapp and I don't have the password .is this way help me now???

**Comment by nephilim1973** [comment]
@ ahmadjmal:
You could try our tool:    http://www.mailmymessenger.com/register/register.php

**Comment by jasmine758** [comment]
Has anyone got the password using the script at the top of the page with Python 3.4?

**Comment by ildar** [comment]
the files layout is changed a bit. `pw` file is vanished, `key` file appeared. And both are now "Java serialization data, version 5".
Could anybody refresh the script please?

**Comment by netfiretec** [comment]
Good evening @tgalal, how do I extract the PW Hash from a whatsapp account created in android without performing recovery of the Whatsapp account.

This without using RCKey

**Comment by luisaugustos** [comment]
This new version with Noise protocol can extract a whatsapp account from Android? I have a lot of accounts in Nox Emulator.
