### ISSUE TITLE
not-authorized

### ISSUE THREAD

**Issue by darkane188** [tgalal/yowsup#2342]
yowsup-cli demos  --config whatsapp_config.txt --echo -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Authentication Error: not-authorized

**Comment by armansaa** [comment]
same like me, need help :(

**Comment by enricomugoy** [comment]
It seems that this library is not working anymore, I have this error:

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

This is what I've got after logging in with s40 environment. It seems that the latest issues are the same as mine, yet no one solved the problem. Maybe this library isn't supported anymore?

**Comment by maiconcosta** [comment]
With me it does not work anymore, I had 4 numbers banned, who has a solution please inform us.

**Comment by tgalal** [comment]
fixed

**Comment by vjyanand** [comment]
@tgalal not sure how it got fixed?
