### ISSUE TITLE
How many days in a row does yowsup manage to work without getting banned?

### ISSUE THREAD

**Issue by PedroFcul** [tgalal/yowsup#2343]
I'm using yowsup and with the behavior i have i don't get banned on a daily basis. But when i leave my number online on yowsup for like 5 days in a row (it varies) i get banned, is this kind of ban occured to anyone?
I think the problem is about the way i manage the presence (i tried always on and only on when i want to send a message), can this possibly be the problem?

**Comment by antonid08** [comment]
My accounts get banned after 1 day sending messages on my real number (not spam).
The problem may be in difference between registration and sending messages environment (android for registration, s40 for sending messages), or maybe accounts get banned because i don't use presence.

**Comment by 10p30pl3** [comment]
I was able to run a application for 3 months using regular yowsup installation, talking to thousands of users. After that, the number was banned and since then ( one month ago ) I cannot reproduce the same performance. I suppose whatsapp changed the protocol and / or improved ban process mechanism.

**Comment by masterwaqar** [comment]
My number got banned after 3 days, while only chatting to myself using CLI. 

I also had same problem number registered with android but was not working so I tried S40. 

I think it's a catch from WhatsApp. Rest all chat was perfectly normal should get banned for it.

Does anyone has working code for android? Since it wasn't working for me, even putting new checksum

**Comment by charanjit-singh** [comment]
My all numbers got banned after 10 min.s of their registration [crying_emoji].

I think I was not sending states like STATE_TYPING or stuff , that's why I was getting blocked.

Shoot-ed mails to WA but they haven't responded yet.

**Comment by Arnauec** [comment]
How do you get new numbers when old get banned? It is difficult in my country.

**Comment by charanjit-singh** [comment]
Textnow.com

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp
