### ISSUE TITLE
yowsup registration issue

### ISSUE THREAD

**Issue by AnithaU** [tgalal/yowsup#2344]
Hi,

I have installed yowsup in raspberry pi 3 and tried to register with an airtel mobile number for sending alert message for my IOT project. Since I am new to python and raspberry  pi, I am not able to understand why it is showing below error. Kindly assist me on this.

>sudo python yowsup-cli registration --requestcode sms --phone 919513122227 --cc 91 --mcc 404 --mnc 45
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 206, in handleRequestCode
    method
  File "/home/pi/yowsup/yowsup/registration/coderequest.py", line 41, in __init__
    self.addParam("token", YowsupEnv.getCurrent().getToken(p_in))
  File "/home/pi/yowsup/yowsup/env/env.py", line 52, in getCurrent
    env = envs[0]
IndexError: list index out of range

**Comment by BRNALX** [comment]
Tell env that the program should use (android or s40).

look:
yowsup-cli registration --requestcode sms --phone 919513122227 --cc 91 --mcc 404 --mnc 45 --e android

**Comment by tgalal** [comment]
please add -d and post the full logs

**Comment by AnithaU** [comment]
The registration issue has been resolved.. Thank you.
Can you please provide a python code to send an image through yowsup.
