### ISSUE TITLE
How to sync keys (group keys) in layer.py

### ISSUE THREAD

**Issue by SPWC** [tgalal/yowsup#2346]
Got an issue with some numbers not receiving any messages (in a group - says "waiting for this message" )  due to altered keys that need to be re-synced. How can I do this without deleting axototl.db and not using the cli.
Is there a function I can place in the layer.py ? How do I do that?

**Comment by BRNALX** [comment]
Check the demo, we have the command to synchronize (/sync) messages and to get keys from a Jid (/keys get).

**Comment by SPWC** [comment]
@BRNALX i am afraid that won't work in this case as I'm not using the cli. I just want a sync function in the layer.py that can be called on connection/invalid key

**Comment by BRNALX** [comment]
You should understand how Cli's Sync and Keys methods work and create in your project

**Comment by BRNALX** [comment]
Try:

In layers\protocol_contacts\protocolentities\iq_sync_get.py

call GetSyncIqProtocolEntity

**Comment by SPWC** [comment]
For now I have solved the issue by using an upgraded framework https://github.com/danielcardeenas/whatsapp-framework
In there you will find GetSyncIqProtocolEntity in the layer.py called onSucess. There's also a shell script clean.sh to find and delete the axototl.db if need be as a last resort.
