### ISSUE TITLE
old version on s40

### ISSUE THREAD

**Issue by Mega4alik** [tgalal/yowsup#2349]
Hi, I'm getting "status: fail, reason: old_version" on registering new number (not used before):

./yowsup-cli registration  --requestcode sms  --phone 7707*****  --cc 7  --mcc 401 --mnc 77  -E s40

My env_s40.py configuration:
```
    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{pho$
    _AXOLOTL = True
```

Hope Im doing this properly:
1) clone source code as "git clone https://github.com/tgalal/yowsup/"
2) modify env_s40.py
4) build it by "python setup.py build"
4) install it by "python setup.py install"
5) register number with cli "./yowsup-cli registration  --requestcode sms  --phone 7707*****  --cc 7  --mcc 401 --mnc 77  -E s40"

My python version is 2.7

I would appreciate any kind of help,
Thanks in advance

**Comment by danielcardeenas** [comment]
Register using andorid env

**Comment by Mega4alik** [comment]
@danielcardeenas  register using android then use as s40 ? Isnt this dangerous ?

**Comment by Mega4alik** [comment]
Or there's no such option?

**Comment by danielcardeenas** [comment]
Register using Android env and login using s40 env. Theres no other option right now

**Comment by hgc2002** [comment]
solved. see #2350

**Comment by dbsdenis** [comment]
python yowsup-cli registration --requestcode sms --phone 55XXXXXXXXXX --cc 55 --mcc 724 --mnc 03 -E android
