### ISSUE TITLE
Registration complete, but I can not send message

### ISSUE THREAD

**Issue by BondFx** [tgalal/yowsup#2353]
DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.Ax
olotlControlLayer object at 0x0000000004221390>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.
layer_receive.AxolotlReceivelayer object at 0x0000000001271160>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer -
 Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification
 Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media La
yer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth mechanism="WAUTH-2" user="3XXXXXXXXX" passive="true">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
♥♦\xce;\xe7\xed\xc7\xc1\xaf\xf1\xd2\xb2 \xb1\xec\xdfO\x8b
HEX3:b'd30d0304ce3be7edc7c1aff1d2b209b1ecdf4f8b'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
\x8d\xe2\xb9\xfd2ac\xf1\xf5\xa1\xff\xfd\xa7\xf1xa9-\xbc↕o§\xc4\xb8\xad5\x9e
L3\xa8♣\x8f\xea\xb25\x94▬\x9fxt
HEX3:b'8c89da0c0d1ebfd4e28fabcb9c6e39e40d1228c17785e9027d52d3c876a4b56208f813e88
053a92dbc126f15c4b8ad359e0d8de2b9fd326163f1f5a1fffda7f10a4c33a8058feab23594169f7
874'
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by towarisch** [comment]
I have the same Problem. Can anyone help?

**Comment by rlljorge** [comment]
I have the same issue here.

**Comment by jucedogi** [comment]
Same... number not blocked also since it works on phone. All I get is the "Connection Closed" message.

**Comment by tgalal** [comment]
update yowsup, register using android env, login using s40 env
