### ISSUE TITLE
Not reconnecting because you signed in in another location

### ISSUE THREAD

**Issue by thatskriptkid** [tgalal/yowsup#2357]
I have following error but I connect only from one place. Someone had the same ?

ERROR:yowsup.layers.interface.interface:Stream Error type: conflict
{'text': 'Replaced by new connection', 'conflict': None}

WARNING:yowsup.layers.interface.interface:Not reconnecting because you signed in in another location
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Requested
DEBUG:yowsup.layers.protocol_iq.layer:YowPingThread-1 - ping thread stopped
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Requested

**Comment by dpz3579** [comment]
hi @thatskriptkid 

this will happen if you are trying to access WhatsApp from 2 phones at the same time.
is this number of yours registered elsewhere?

**Comment by edsondario** [comment]
When register and send messages, yowsup make files in localhost. It's stored in 

> **/USERHOME/.yowsup/**

Try copys files between PC's.

**Comment by thatskriptkid** [comment]
@dpz3579 Thanks for answer but I don't use phone instead I connect prommatically from my script, so @edsondario answered right.
