### ISSUE TITLE
"reason":"old_version"}\n

### ISSUE THREAD

**Issue by Alellandrou** [tgalal/yowsup#2361]
Hi, when i register a number phone appears an this error "INFO: yowsup.common.http.warequest:b'{"login":"34*********","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'34*********'

I has been looking another posts of people with the same problem and I changed the next:

env_android.py

_MD5_CLASSES = "0yTf9XK7xoJkKlxLgY6/Lw=="
_VERSION = "2.17.427"

env_s40.py

_VERSION = "2.16.12"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"

env.py

DEFAULT = "android"

and I commented this line

# __metaclass__ = YowsupEnvType

but the error stills appearing, what can i do?

**Comment by saulhidalgoaular** [comment]
Please, check the following solution. It worked for me
https://github.com/tgalal/yowsup/issues/2350
