### ISSUE TITLE
'ImageDownloadableMediaMessageProtocolEntity' object has no attribute 'getMediaContent'

### ISSUE THREAD

**Issue by charanjit-singh** [tgalal/yowsup#2365]
```
    data = messageProtocolEntity.getMediaContent()
AttributeError: 'ImageDownloadableMediaMessageProtocolEntity' object has no attribute 'getMediaContent'

```

Somebody Please Help...

**Comment by charanjit-singh** [comment]
Thanks in Advance

**Comment by tapankumar** [comment]
I think this method is not implemented on @tgalal master branch. You should try below repo which i am using and able to save images and text both. 

https://github.com/jeremiash/yowsup.git
