### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2367]
hello, i have registered my number on yowsup successfully but login time error:-

> Authentication Error: not-authorized
and i am using below youwsup version and android:-

{'org.openwhatsapp.yowsup.prop.endpoint': ('e13.whatsapp.net', 443), 'org.openwhatsapp.yowsup.prop.domain': 's.whatsapp.net', 'org.openwhatsapp.yowsup.prop.auth.credentials': ('c0VwaQlEOwsQPHJgsf1d6C2eXp4=', '919694002962'), 'org.openwhatsapp.yowsup.prop.resource': 'Android-2.17.279'}

**Comment by thatskriptkid** [comment]
@manojrao Hi. You should use S40 env vars when log in.

**Comment by manojrao** [comment]
but i am also use S40 env.

**Comment by tgalal** [comment]
update yowsup, register using android env, login using s40 env
