### ISSUE TITLE
Using a yowsup just for receiving

### ISSUE THREAD

**Issue by facundomedica** [tgalal/yowsup#2373]
I'm planning to use yowsup just for receiving messages and executing actions on my server without giving any response to the sender.

Is this project the right one for me? If I never send a message, will it lower my chances of getting banned? Or it will look too suspicious and get banned anyways?

Context: I want to use WhatsApp as a method of validation for phone numbers in an app that I'm working on. Currently we use Firebase but it goes down quite frequently, and using a WA bot would be an alternative to this method.

**Comment by lBHJSDVF** [comment]
+

**Comment by nnapster** [comment]
hi,
Yes this is right for  you and you can implement this just only for receiving.

**Comment by facundomedica** [comment]
And what about the chances of being banned? Are they higher or lower than using this to send messages?

**Comment by schoerg** [comment]
Just try it. A new phone number is like 2€.

**Comment by facundomedica** [comment]
I'm testing it right now in production, but just wanted to have more info. Btw, here phone numbers are less than 0.66€ or 0.79 USD lol

**Comment by Arnauec** [comment]
How do you get phone numbers so cheap OxO, I would like to know since I might need some for some project. Thanks!

**Comment by facundomedica** [comment]
@Arnauec I live in Argentina! I forgot to close this issue. It's working and I haven't been blocked, but I had to restart the process a couple of times.
