### ISSUE TITLE
Real Time Location Error

### ISSUE THREAD

**Issue by brayanesc** [tgalal/yowsup#2376]
Hello!
I got this error when someone send me a real time location message
`  File "/home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 420, in sendKeys
    signedKeyTuple, preKeysDict, Curve.DJB_TYPE, self.adjustId(registrationId))
NameError: name 'Curve' is not defined`

Does someone else got this error?
It makes my client crash :(

**Comment by dvdhellin** [comment]
Hi, try in /home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_receive.py top add:

`from axolotl.ecc.curve import Curve`

And before "def SendKeys....." add:

```
def onSentKeysError():
       logger.error("Error SendKeys")
```

**Comment by tgalal** [comment]
@brayanesc how is it that in your installation's yowsup/layers/axolotl/layer_receive.py throws the error at line number 420,  while the source code of this file is less than 300 lines?

**Comment by schoerg** [comment]
Because it is the wrong repo. Should have opened the issue at https://github.com/AragurDEV/yowsup

**Comment by brayanesc** [comment]
`  File "/home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.7-py3.5.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.7-py3.5.egg/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.7-py3.5.egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "/home/ubuntu/workspace/env/lib/python3.5/site-packages/yowsup2-2.5.7-py3.5.egg/yowsup/layers/__init__.py", line 146, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification offline="1" notify="DA" id="00" participant="77xxxxxxxxx@s.whatsapp.net" from="location@broadcast" type="location" t="1514988224">
<enc type="msg" v="2">
3
íµêØ%f$ÙL" 5s8"h
               «
                ¢DÎHiV¥`8MWeÓ4vG?ú@D    p
                                         ª4+~¼UØ3f<¼W}ð¢>½
                                                                ÑÇ*8Ðèpþ93±¹,Q÷ FAÎhiëRq:±h³àY¼çä[ìJ+ßáC¸r òý<OOåsÌ®"Î!«Ï
HEX3:b'330a21053eea99929b11d8258c6624d9cdb37da84bd2d5680dedb58b094c222035837338100018002290010b7fab04030ba244ce10486956a560384d5765d334899f7601473ffa404409700caa342b9d7e83bc1b5c55d833669e103cbc577d17f0a23e0fbd0c1309d18b1dc72a891e988d38d0e870fe1b333933b1b92c51f71509964641ce6869eb521b04fc5f91372a0aef81f7211b4c19713ab168b3e059bce702e45bec4a2bdfe143b8721583a0f2fd3c879c4f4fe5c0088d73ccae22ce219aabcf'
</enc>
</notification>`

@tgalal this was the real one, sorry i was testing with another code

**Comment by tgalal** [comment]
9d8d13b68f1704c2deecf6fde1e0118fa30ebd38
