### ISSUE TITLE
general : Disconnected : Connection Closed

### ISSUE THREAD

**Issue by dkiran** [tgalal/yowsup#2384]
Can some one give me reason for this error while [offline]:/L
Any solution for this

**Comment by suvadipg** [comment]
If my terminal is open with /L , and from another command window I send a message by using demos, mt receiving session getting disconnected . Any solution to keep receiving session un-impacted?

**Comment by shanmugachu** [comment]
same here,can any one help....

**Comment by badinenisaivardhan** [comment]
If You need help do message me at on whatsapp , i will help you to sort out this

**Comment by sowerkoku** [comment]
@dkiran [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed
