### ISSUE TITLE
Does Yowsup uses multiple cores? 

### ISSUE THREAD

**Issue by cijo7** [tgalal/yowsup#2387]
I want to know if the update or notification from WhatsApp server will drop if I do a blocking job on the main thread.

Also, does Yowsup make use of the multiple cores of cpu available?

**Comment by PhilipHiet** [comment]
When I used the `sleep()` function in one of my layers, it blocked the recieving of messages.

Yowsup uses (as far as I know) asyncore, 'that lets you have nearly all the advantages of multithreading, without actually using multiple threads.'
