### ISSUE TITLE
Trying to dump the ProtocolTreeNode for the yowsup-cli demos but failed

### ISSUE THREAD

**Issue by hgc2002** [tgalal/yowsup#2391]
I need some help to incorporate a dumping routine for the nodes of every data received.
I'm using the yowsup-cli commandline, trying to understand what is received, but no way to make it work.
Please advice.
Thanks.

**Comment by unknownguy2002** [comment]
Any logs? :3

**Comment by unknownguy2002** [comment]
Please elaborate your problem

**Comment by hgc2002** [comment]
simple: I want to see the content of the tree, I mean the communication, received from whatsapp in every data reception after is it completed enough (stanza), some kind of visual dump of the nodes coming in the responses, in text.

**Comment by hgc2002** [comment]
Closing. I've found that running yowsup from command line with debug option is good enough.
