### ISSUE TITLE
Dissconnecting...

### ISSUE THREAD

**Issue by unknownguy2002** [tgalal/yowsup#2392]
After 1 sec if connecting, the connection is closed. I am using python code with run.py and layer.py

**Comment by unknownguy2002** [comment]
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x74f46270>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by badinenisaivardhan** [comment]
Change the default env to "andriod" , you will get the registration and password , run ithe command from yowsup-cli it worked for me !!

**Comment by unknownguy2002** [comment]
I doubt you understand, what I mean is when I run my code(I have already registered) I get the error.

**Comment by badinenisaivardhan** [comment]
Have installed all , the pytho libs ?, try installing all the required lib files and run it again, it will work..!! #may b ithink so

**Comment by vjyanand** [comment]
I have the same issue, it disconnects after a while (xml error)

**Comment by badinenisaivardhan** [comment]
If there is any problem..!! Contact me using whatsapp , my number 918919552023 , hire me for this project

**Comment by vjyanand** [comment]
@unknownguy2002  did you resolve? Try changing the ip?

**Comment by unknownguy2002** [comment]
How do I do that @vjyanand

**Comment by unknownguy2002** [comment]
How doI change the IP?

**Comment by sowerkoku** [comment]
@unknownguy2002 [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed
