### ISSUE TITLE
GETTING Banned By using It! 

### ISSUE THREAD

**Issue by badinenisaivardhan** [tgalal/yowsup#2393]
Getting Banned After Sending 200-300 Sms , By whatsapp , Y?

**Comment by unknownguy2002** [comment]
SMS? You meant whatsapps. Whatsapp checks if you u sent too many messages too unhumanly

**Comment by badinenisaivardhan** [comment]
Typo mistake * not sms its mesaages, and sendings, ihave send messages only to test , whether it is workin or not, but i got banned bro :(

**Comment by schoerg** [comment]
200-300 messages in what timeframe?

**Comment by badinenisaivardhan** [comment]
10 sec Intervtal :( but got banned

**Comment by schoerg** [comment]
Could be too much, I don't know.

**Comment by qvs5010** [comment]
https://github.com/tgalal/yowsup/issues/2413

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
