### ISSUE TITLE
What happen if i use my old credentials in a new version of yowsup?

### ISSUE THREAD

**Issue by HumGuz** [tgalal/yowsup#2398]
Hi!, hope someone can exlaime this, i have a bot whit a old version of youwup, exactly since june 2017, and it works fine, but las week i tried to get loged in command line and got an error, so i think if i use the last version, it will get fixed and i can use the command line, i want to restore the keys of encriptation for a couple of users with a "Waiting for this message. This may take a while." error

thanks!!!

**Comment by tgalal** [comment]
this looks like a stackoverflow question and not an issue in the project
