### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by vjyanand** [tgalal/yowsup#2400]
DEBUG:yowsup.layers.logger.layer:rx:

```
<stream:error code="503">
</stream:error>
```

Have anyone encountered this? How to mitigate? Thanks in advance.

**Comment by vjyanand** [comment]
@tgalal Also, this is not handled in StreamError and throws unhandled error. Can we gracefully ignore and continue without closing the connection?

**Comment by devops35** [comment]
@vjyanand did you solve the problem? I have the same problem. Can you help me?

**Comment by vjyanand** [comment]
@devops35 No fix yet as this is discontinued

**Comment by devops35** [comment]
Don't you have this error anymore?
