### ISSUE TITLE
Error: not-authorized & Error: old_version

### ISSUE THREAD

**Issue by Alellandrou** [tgalal/yowsup#2402]
Hi, today I tried to send a message with the whatsapp bot but appears the next error:

Authentication  Error: not-Authorized

This is the command that i wrote:

yowsup-cli demos --config whatsapp_config.txt --send 34XXXXXXXXX  "Good Morning"

And the whatsapp_config.txt document contents:

cc=34
phone=34XXXXXXXXX
password= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

After this I tried to register again my phone number but now appears this error:

INFO: yowsup:common.http.warequest:{"login":"34XXXXXXXXX", "status":"fail","reason":"old_version"}

**Comment by vjyanand** [comment]
Probably, you might need to upgrade/update yowsup

**Comment by qvs5010** [comment]
Also make sure you number is unique, I tried with a online google number and failed, got a new sim with number and it registered quickly

Put your new SIM card in a phone to receive sms

check your --mcc -mnc @ https://en.wikipedia.org/wiki/Mobile_country_code

`python3 yowsup-cli registration --requestcode sms --phone ABCXXXXXXX --cc=ABC --mcc=XXX --mnc=XX`

Once run check the code that was sms'd to you

`python3 yowsup-cli registration --register SMSCODE --phone ABCXXXXXXX --cc ABC`

**Comment by Alellandrou** [comment]
okay, thank guys ^^
