### ISSUE TITLE
InvalidKeyIdException 

### ISSUE THREAD

**Issue by qvs5010** [tgalal/yowsup#2403]
what does this mean?

WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for xxxxxxxxxx, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for xxxxxxxxxx, getting keys now
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for xxxxxxxxxx, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for xxxxxxxxxx, getting keys now
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for xxxxxxxxxx, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for xxxxxxxxxx, getting keys now
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for xxxxxxxxxx, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for xxxxxxxxxx, getting keys now
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for xxxxxxxxxx, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for xxxxxxxxxx, getting keys now

**Comment by qvs5010** [comment]
This happened because I ran the script on 2 different server. you must only have  one WhatsApp number per server.

to fix the issue do the following.

```
find / -name ".yowsup"
rm -Rf /root/.yowsup
```

**Comment by naushrambo** [comment]
did you find any solution, if i register completely new number then it works, otherwise InvalidKeyIdException

**Comment by tgalal** [comment]
not an issue
