### ISSUE TITLE
require six==1.10

### ISSUE THREAD

**Issue by b0yasyik** [tgalal/yowsup#2405]
i get error module six
but i have module six in my python
i try to edit setup.py to edit requirment but still get the problem

Searching for six==1.10
Reading http://pypi.python.org/simple/six/
Couldn't retrieve index page for 'six'
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for six==1.10
error: Could not find suitable distribution for Requirement.parse('six==1.10')

**Comment by altmas5** [comment]
Did you try in another box?
I got similar behavior once in an old system.

**Comment by johnrosexx** [comment]
I have little programming expertise. Trying to install yowsup under Ubuntu 14.04 LTS. The installation and registration process seemed OK (https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/), but when I got to the test I got an error: "DistributionNotFound: six==1.10". I'm using python 2.7.6 and have the lastest Ubuntu python3-six package installed (1.5.2-1ubuntu1). Seems like a similar problem, can you advise?

**Comment by johnrosexx** [comment]
Sorry, I meant to say python-six, seems that version 1.5.2 is the latest foreseen in Ubuntu 14.04 LTS (I also installed python 3.5.5 but am not using it here).
