### ISSUE TITLE
layer.py

### ISSUE THREAD

**Issue by Alellandrou** [tgalal/yowsup#2410]
My layer.py doesn't let me write more than one

@ProtocolEntityCallback("message")

if i write more than one appears the next error: Traceback (most recent call last):

File "run.py", line 2, in <module>
    from layer import EchoLayer

IndentationError: unexpecte indent

**Comment by tgalal** [comment]
Hey, this is a last warning, next time you post irrelevant issues you will be banned

**Comment by Alellandrou** [comment]
ARE YOU FUCKING KIDDING ME? THIS IS A PROBLEM WITH YOWSUP
