### ISSUE TITLE
Temporarily unavailable when register and then immediately got banned

### ISSUE THREAD

**Issue by hanipcode** [tgalal/yowsup#2411]
i got this response. when i try to confirm and send confirmation code after i register my number
{
  "status": "fail",
  "kind": null,
  "pw": null,
  "price": null,
  "price_expiration": null,
  "retry_after": 300,
  "currency": null,
  "reason": "temporarily_unavailable",
  "cost": null,
  "expiration": null,
  "login": "xxxxxx05147192",
  "type": null
}
and not only that. after that failed attempt i try to register from the official app it said that my number is banned.  it's a brand new number.

**Comment by qvs5010** [comment]
https://github.com/tgalal/yowsup/issues/2413
