### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by Alellandrou** [tgalal/yowsup#2413]
Today I was turning on my whatsapp bot using the python run.py command but appears the next error

Authentication Error: not-authorized

Yesterday, I did the same and it worked

**Comment by lippih** [comment]
Perhaps your number has been banned

**Comment by qvs5010** [comment]
you need run reregister, it will show if you are blocked/ banned.

if so, send an email to support@support.whatsapp.com to unblock the number.

the reason I got block was I registered with the `-E android` and was sending and receiving with the `-E s40` environment.


```
Hi,


Thanks for your message.

We apologize for any confusion and inconvenience this may have caused. Our system flagged your account activity as a violation of our Terms of Service and subsequently banned your number.

To ensure access, please reverify your number with our official WhatsApp client, which can be downloaded from our website: www.whatsapp.com/download

Please note that we do not provide support for unofficial clients or for jailbroken/rooted (including emulators), and unsupported devices.
```

After it was unblocked I had to register with the -E s40 environment, and make sure all my sending and receiving scripts are in the same environment. -E s40

if you register with -E s40 and you get a Bad token error check the following token is correct.

yowsup-master/yowsup/env/env_s40.py

`_TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"`


after I did all this I everything seems to be ok and running without being blocked.

Hope this helps

**Comment by Alellandrou** [comment]
oh fuck, I see...

Thanks Guys ^^

**Comment by emretekince** [comment]
@qvs5010 I still get bad_token error..

**Comment by dazzzl** [comment]
@qvs5010 You have successfully registered with the s40 environment? Unfortunately, this is not working anymore, even with the new token  ... :-( 

Registering with android environment and login with s40 works ... but I get banned in only few hours ...

**Comment by lippih** [comment]
Perhaps [Telegramm](https://play.google.com/store/apps/details?id=org.telegram.messenger) is an alternative to you. It has a good API to make some useful bots.

**Comment by qvs5010** [comment]
@dazzzl with s40, before you regester, plage your sim in a phone, go through the WhatsApp setup process, then do a test mess, after it goes through, take the sip out.

Then try to reg with s40
