### ISSUE TITLE
Unable to Register. Getting blocked aggressively.

### ISSUE THREAD

**Issue by cijo7** [tgalal/yowsup#2415]
Unable to register at all. I lost about 6 of my numbers trying this. The numbers are getting blocked in the final step.

The code is successfully sent to the phone. But, on registration using the code, all numbers are getting blocked instantly.

status: b'fail'
login: b'4xxxxxx'
retry_after: 300
reason: b'temporarily_unavailable'

After that, it will just show as blocked.

I am using Android env for registration.
_yowsup-cli registration --requestcode sms --phone 4xxxxxx --cc 4x --mcc 310 --mnc 16 -E android_
_yowsup-cli registration --register 2xxxx7 --phone  4xxxxxx --cc 4x  -E android_

**env_android.py**
\# Updated it to the latest whatsapp release. 2.17.426 also doesnot work.
_MD5_CLASSES = "27dOpdyJqdtBVlcrXE1MTQ=="
_VERSION = "2.18.25"
 
Tried using **env_s40.py**
_ _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"_
Getting old_version on this.

Are there any other variables that result in blocking. What am I missing? Any help is really appreciated. This is really bugging me.

**Comment by cijo7** [comment]
Anyone knows about it?

**Comment by ZetDeveloper** [comment]
Check this 
https://github.com/ZetDeveloper/WebWhatsappBot

**Comment by sealabr** [comment]
env android is blocking, use s40

**Comment by munknex** [comment]
@cijo7 Did you figured this out?

@sealabr How to register number using only s40?

**Comment by runasas2017** [comment]
Could somebody tell working configuration which is working now?
My account was blocked after first message. Manual from this- https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/. Man from this (look above) site is asking about 150$ for help))))) so don't follow this. Please tell the right way!
