### ISSUE TITLE
TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by AlwaysLearn1ng** [tgalal/yowsup#2416]
After installing everything which was mentioned at https://github.com/tgalal/yowsup under Installation
I typed the following command `yowsup-cli registration --help`
```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
can somebody help me please?

**Comment by ZetDeveloper** [comment]
check this
https://github.com/ZetDeveloper/WebWhatsappBot

**Comment by Infinisil** [comment]
Same error as reported in #2351, #2325 and #2259. Solutions include:

- Using python3 instead (See https://github.com/tgalal/yowsup/issues/2325#issuecomment-343516519)
- Patch setup.py to use six version 1.10
- Apply this PR: https://github.com/tgalal/yowsup/pull/2379

**Comment by AlwaysLearn1ng** [comment]
@Infinisil Thank you for your help, it was very useful.
