### ISSUE TITLE
Is there a gotPictureReceipt signal?

### ISSUE THREAD

**Issue by shibumi** [tgalal/yowsup#242]
Hello,
I am implementing a "get Picture" function in the yowsup-cli. But I can't any Receipt signal for the "Picture"-methods. Is there such a "you got the picture"-signal? 

 I did this to solve the problem but this is very ugly:
```
	print("getting picture..please press strg+c in case you got the picture")
		while True:
			input()
 ```

Feel free to check my PictureClient.py 

https://github.com/shibumi/yowsup/blob/master/src/Examples/PictureClient.py

thx and best regards

Chris

**Comment by jlguardi** [comment]
Deprecated.
