### ISSUE TITLE
best practices of running yowsup on server

### ISSUE THREAD

**Issue by Mega4alik** [tgalal/yowsup#2421]
I have noticed that yowsup can run on personal computer and handle a dialog with several users at the same time with no problem

But when I try on a server, get banned in 1-3 days even though I'm using a new phone number every time.

What might cause these problems:
- Google Cloud Engine IP address. Maybe WhatsApp knows that the IP address belongs to GCE.

- Connecting from the same IP several times. When a phone connects to the internet via cellular network or wifi a new IP gets generated. Using the same IP several times might look suspicious.

- Staying connected for 12 hours straight. By connected, I don't mean online, but being able to receive messages

Has anyone experienced such problems? how did you handle them?

Would appreciate if you shared your experience

Thanks

**Comment by vjyanand** [comment]
Same here, adding to it, there are some inconsistencies. When subscribe to presence some numbers(user's number ) doesn't get any presence update. Sometimes, presence stops after 12-24 hours for some numbers. No way to detect if the presence update reliably (this happens only when you have presence subscription for more than 200 numbers)

**Comment by v1v3kgithub** [comment]
@vjyanand I am not sure from a Wassup user workflow perspective can you subscribe simultaneously for more than one user? Since when using the app you subscribe to a single user (i.e open the chat with a single user) and then move on to the next user - in effect unsubscribing from the 2nd user

**Comment by Mega4alik** [comment]
@v1v3kgithub  thank you for the comment. Do you mean that before sending a message to a user, you need to subscribe to him? And before sending a message to another user, unsubscribe from previous one? I dont't use subscribing at all. Is it the possible reason of getting bans

Thank you

**Comment by vjyanand** [comment]
@v1v3kgithub You have to have a number synced before sending the number a message

**Comment by v1v3kgithub** [comment]
@vjyanand Do you have a script in place for subscription multiple contacts and logging the results to say a file ?

**Comment by tombaki** [comment]
@vjyanand do u find any way to keep it presence without unsubscribe and subscribe it again

**Comment by vjyanand** [comment]
@tombaki So far no.

**Comment by nitinjs** [comment]
> 
> 
> @v1v3kgithub You have to have a number synced before sending the number a message

so while sending message using yowsup
if the message does not exist in the contacts then it can be added and then syncd

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
