### ISSUE TITLE
Installation of yowsup modules

### ISSUE THREAD

**Issue by kafffee** [tgalal/yowsup#2428]
Hi everyone!

I am a newbie so can somebody tell me how to install yowsup in easy steps. I'm using Python 3.5.3 on my Raspbian system.

**Comment by kafffee** [comment]
What does it mean closed issue? Did I do something wrong? Is there another thread about this topic?

**Comment by tgalal** [comment]
please read the readme

**Comment by kafffee** [comment]
I already did and it wont work. As I was messing around a lot trying to fix this, I could try to format my sd and re-install Raspbian.. Do you think this might help?
