### ISSUE TITLE
Cannot send whatsapp message

### ISSUE THREAD

**Issue by sulz47** [tgalal/yowsup#2434]
Hey guys i m using windows 10 and powershell for sending whatsapp messages
but when i tried to send whatsapp message with the following command

python yowsup-cli demos --config  yowsup_config.txt --send XXXXXXX "Hey" -E android

i got following error
ModuleNotFoundError: No module named 'axolotl'

and when i tried this command

pip install python-axolotl

i got following error
Failed building wheel for python-axolotl-curve25519

please help me guys :(

i m using latest yowsup-cli 2 version

**Comment by sulz47** [comment]
@tgalal

**Comment by tgalal** [comment]
"Failed building wheel for python-axolotl-curve25519"
