### ISSUE TITLE
Any working way to register?

### ISSUE THREAD

**Issue by munknex** [tgalal/yowsup#2436]
Is it possible to register right now? 

Request number number via `-E Android` and confirm code using `-E s40` don't work any more: `old_version`

Both requesting and confirming via `-E Android` results in almost immediate block.

**Comment by emretekince** [comment]
+1

**Comment by flavionegrao** [comment]
You have to request and confirm using -E Android.
Then get the password and run it using s40 and the latest token and version.
However seems that you will get blocked after couple of days anyway, we need more info to confirm it.

env_s40.py
```
    _VERSION = "2.16.12"
    _OS_NAME= "S40"
    _OS_VERSION = "14.26"
    _DEVICE_NAME = "302"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1494451854337{phone}"
    _AXOLOTL = True

**Comment by munknex** [comment]
@flavionegrao actually accounts are blocked after a couple of *hours*, not days. Even if just register and never login.

**Comment by WanKapef** [comment]
Whatsapp ceased its support for S40 earlier this year, did not it? So I think it was impossible to register using envs of the S40, however using the Android env is still possible, an alternative would be to use the Android env to login and send messages too, is it possible? Has anyone ever had any resolution to this problem? :(

**Comment by Gianluke** [comment]
This work form me: https://github.com/tgalal/yowsup/issues/2536 (on Centos).
