### ISSUE TITLE
Whatsapp Business???

### ISSUE THREAD

**Issue by lucasgcaro** [tgalal/yowsup#2437]
How to integrate with whatsapp business? How is the correct registration process? Any ideas? Is it possible? '

**Comment by BodduSatya** [comment]
i too looking for yowsup for  whatsapp business.

**Comment by pablogus** [comment]
Hi All, I have the same question! Thanks in advance.

**Comment by eugenioclrc** [comment]
same here! i have haerd that som use a middle app that provides an api to manage the whatsapp for business app via an api.

**Comment by netfiretec** [comment]
@tgalal Good afternoon my dear, would it be possible to connect to the Whatsapp Business servers using the same Yowsup?
The reality is that the WhatsApp Enterprise API was not designed to meet the needs of small and medium businesses.

I can extract the RCKey by registering with the android, and later performing a PWHash Recovery.

So would it be possible to connect to the Business using Yowsup?

**Comment by tgalal** [comment]
no plans
