### ISSUE TITLE
Two devices at the same time (2018)

### ISSUE THREAD

**Issue by chatterbro** [tgalal/yowsup#2438]
This has been asked before but I just wanted to check which chances we got to have it running with 
1) phone + whatsapp app
2) computer + yowsup
without having to re-register?

Not being able to use them at the same time would be ok but re-registering every time sucks

**Comment by SaadeMotion** [comment]
You can't, when you register (using yowsup or whatsapp app), whatsapp changes your password, so the other method can't login/stay connected.

There's an ping sent from whatsapp that informs that your password changes, so you cant do anything about it
