### ISSUE TITLE
how reliable the library is?

### ISSUE THREAD

**Issue by alloanva** [tgalal/yowsup#2439]
can be the library used for producction? can you give me your feedback if you are a heavy user. We are thinking of whatsapp side.

**Comment by vjyanand** [comment]
fairly stable, depends on what you want to do with it

**Comment by alloanva** [comment]
Thanks vjyanand. Imagine i have a app based on yowsup library and whatsapp banned me, obviously my getting unavailable there are anyaway to remove banned easily?

**Comment by vjyanand** [comment]
#1329

**Comment by jinfeei** [comment]
It seems that this is not being maintained anymore. I tried: registration all went OK (after changing this MD5 hash), tried running echo demo, it was OK for one day only. The next day, the number was blocked. I tried another SIM card, this new number also got blocked.

Echo doesn't work for photos and locations.

It seems there are forks of this repository that work "somewhere else". I'm going to try and see if I get blocked again using this other fork. But I don't think this library should be used at all in its current form.

**Comment by jinfeei** [comment]
vjyanand, when you say "fairly stable" - which particular version do you use? thanks :-)

**Comment by vjyanand** [comment]
@jinfeei  The latest, I build it from source (master branch)

**Comment by jinfeei** [comment]
@vjyanand, but the master branch doesn't work... Without doing a little modification, you can't even register. And it can't send images, for example. New numbers invariably get barred after a few hours...

Any advice? Thanks friend... :-)

**Comment by vjyanand** [comment]
@jinfeei I too face the same issue of getting banned
