### ISSUE TITLE
Payment via Whatsapp

### ISSUE THREAD

**Issue by dkdndes** [tgalal/yowsup#2446]
Hi @tgalal ! Whatsapp is in Beta Test of the UPI Payment feature in India. Is it planned to integrate this here, too?

**Comment by dkdndes** [comment]
Reference: 

* https://www.hindustantimes.com/tech/whatsapp-upi-payment-feature-how-to-get-it-right-now/story-GrCTx7CnEbAZGoES1o5buI.html

**Comment by BasanthVerma** [comment]
It's only for India and Indian phone numbers.

**Comment by tgalal** [comment]
no plans
