### ISSUE TITLE
Android env login

### ISSUE THREAD

**Issue by WanKapef** [tgalal/yowsup#2448]
Has anyone ever been able to log in using env android? Since in the last few weeks everyone who is registering using s40 and logging on using android is being banned, I think this would be the only solution.

**Comment by emretekince** [comment]
I will work on WA 2.0

**Comment by HumGuz** [comment]
I got the same problem, i got registered succesfully using  android but i cant login, when use: /L i get:
Disconenected: Connection Closed

**Comment by WanKapef** [comment]
@emretekince will you develop from the beginning or will you use any project as a basis? I am willing to help in this new project of WA2.0

**Comment by sowerkoku** [comment]
@WanKapef [tagalal indicates solution here](https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670)

please issue closed

**Comment by WanKapef** [comment]
@sowerkoku the tgalal solution is login using S40 env, my goal is just the opposite.

**Comment by sowerkoku** [comment]
@WanKapef 
sorry, I read your initial comment and understand.
you could try [whatsapp web api](https://github.com/mukulhase/WebWhatsAPI)
