### ISSUE TITLE
Convert virtual number from emulator to hash for yowsup -$150

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#2449]
Need HELP. on the emulator in Whatsapp registered virtual number, it is very necessary to convert it into hash for work with yowsup.

**Comment by SaadeMotion** [comment]
I can help you with this. Message me at: saade@outlook.com.br

**Comment by RakeshKumar1684** [comment]
i can provide you tool to extract hash.. mail me: rakeshkumar1684@yahoo.com
