### ISSUE TITLE
general : Blocked number after first message

### ISSUE THREAD

**Issue by DavidPC85** [tgalal/yowsup#2452]
Download the version Yowsup v2.5.7 and 5 days ago it was possible to send more than 2 messages with the same number, however from March 8 of this year, I can only send a message and the next message whatsapp blocks the number and you get the status 'not authorized'. I am giving a margin of 5 minutes between each message, I send to different numbers and with the content of the message is different.
Someone has experienced this situation. ?

**Comment by hncvj** [comment]
Same happened with me. Exact same thing.. Waiting for a solution from @tgalal

**Comment by ykguCoder** [comment]
Same happened with me.How to solve?

**Comment by vallejosfj** [comment]
Same happened with me.How to solve?

**Comment by rHohith** [comment]
same happened I just sent a message and immediately within a 5 mins I get blocked

**Comment by Gloome** [comment]
Same happened with me...

**Comment by RakeshKumar1684** [comment]
#2456 ... extract password from whatsapp apk

**Comment by DwarfKiller** [comment]
Did anyone get the solution?

**Comment by agusibrahim** [comment]
me too, blocked after sending first message :(

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

**Comment by 3dluis** [comment]
I see that the community of Yowsup is very growing, my recommendation is that we adapt to the library to avoid excessive abuse of the tool. Limiting shipping quantities for a limited time, avoid sending images with marketing reasons, do not initialize conversations with people who do not have you as a contact, do not initialize conversations with a number that is not within your contacts. I understand that giving a good use to this tool can evolve until you get to look for financing to become an official API. This has a lot of potential for doing business both for whatsapp and for the Yowsup community.

**Comment by ahll** [comment]
me too, two numbers blocked

**Comment by Yamilquery** [comment]
In a few moment I will buy some SIM Card, but reading all your comments I'm very doubtful, but still I think I'll do it!

I want to build some interesting app to search in Google through whatsapp, because in my Country only we have WhatsApp and Facebook for free in our phone basic plan.

I'll tell you my experience!
