### ISSUE TITLE
Instantly Banned

### ISSUE THREAD

**Issue by hncvj** [tgalal/yowsup#2455]
Hello tgalal, I got instantly banned after registration and sending 1 Message. 
The error i got on sending 1st message was this : 
Auth Error, reason Unhandled stream:error node:
<stream:error code="503">
</stream:error>

and it got disconnected, then I tried logging in again and I got this message : 

[offline]:general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized. 

Do have a look and let me know why it happened. 
btw i'm running it on Google cloud server.

**Comment by WanKapef** [comment]
unfortunately yowsup is currently dead for new registered numbers :(

**Comment by hncvj** [comment]
:(

**Comment by RakeshKumar1684** [comment]
If you using normal wart to register number.. it will be banned. if you extract hash  from whatsapp apk it will work.

**Comment by hncvj** [comment]
I extracted it from latest version and used it but i still got banned. I got 2 numbers banned even after using latest Hash from latest apks.

**Comment by RakeshKumar1684** [comment]
which tool you are using to extract?

**Comment by hncvj** [comment]
DexMD5

**Comment by hncvj** [comment]
https://github.com/mgp25/classesMD5-64/edit/master/dexMD5.py  

This one.

**Comment by RakeshKumar1684** [comment]
this is for token generation.

Just do one thing.. extract id from whatsapp .. which is caculated by me and rc2 file  in /data/data/com.whatsapp. then use that id in url 
https://v.whatsapp.net/v2/exist?cc={0}&in={1}&id={2}&&lg={3}&lc={4}
you will get pw here
try test that

**Comment by ykguCoder** [comment]
@RakeshKumar1684 the id and rc2 file,how to get?Can you elaborate on this?

**Comment by WanKapef** [comment]
@hncvj When was the last time you registered a number through yowsup? Have you tried this last month? Have not you been banned?

**Comment by hncvj** [comment]
@RakeshKumar1684 i'm using yowsup to generate password.

**Comment by RakeshKumar1684** [comment]
As I said don't use API to register number. Extract from app.. if anyone want to test channel created with my wart.. let me know. My email rehaaan0711@gmail.com.

**Comment by WilliamCampolina** [comment]
I am being banned ... they said that I am logging on devices that are not authorized or compatible ....

**Comment by DwarfKiller** [comment]
Did anyone get the solution?

**Comment by rafaelfelype** [comment]
Any solution?

**Comment by Antorai78** [comment]
The same for me. After the first message now i have this {"status":"fail","reason":"blocked","login":"XXXXXXXXXXXX"}
Can I do something?

**Comment by pabloruan0710** [comment]
_MD5_CLASSES = "TNr5/Xc1X1RV3vHoHWpXgg=="
_VERSION = "2.18.99"

update version android.

**Comment by WhiteShin** [comment]
Don't worked for me.
Message after send 1 message:
blocked

Version extracted from last apk: 2.18.99

**Comment by dazzzl** [comment]
@RakeshKumar1684 Do you know how to calculate the id from me and rc2? Do you not need the content of the key file?

**Comment by tombaki** [comment]
you can register number with wart i'v edit it with new version and work great [https://files.fm/u/z5ux2g8p#_](Wart download)

**Comment by hncvj** [comment]
The link showing 404 error

**Comment by dazzzl** [comment]
@tombaki No Voice registration :-(

**Comment by dazzzl** [comment]
BTW: the id is stored in the rc2 file ... from the me file, you need only your login number ...

**Comment by WhiteShin** [comment]
@RakeshKumar1684 How can i calculate the ID and RC2 ??

**Comment by fabiovaz3** [comment]
I'm having the same problem here. Anyone have a solution or is it a Game Over?

**Comment by dazzzl** [comment]
@RakeshKumar1684 Thanks, it is working :-) ... I will see how long ...
@WhiteShin https://github.com/tgalal/yowsup/issues/234 is still valid. However, a) filenames have changed and b) forget about the google account... it is not used anymore.

**Comment by hncvj** [comment]
@dazzzl can you please tell me how you made it to work ?

**Comment by dazzzl** [comment]
@hncvj What is your problem? Have you read #234 and this thread?

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

**Comment by fmachadodev** [comment]
@tombaki 
I coul'd register a number, but I can't login using yowsup, can u help me with this?

thanks

**Comment by andreazevedobauru** [comment]
@fmachadodev i had the same problem a time ago, you have to follow this:
Note:

If you use the yowsup-cli command for registration of a new number, you run the risk of being black-listed by WhatsApp after sending your first message. To avoid this, register using an actual mobile device with WhatsApp installed, send a few messages, and then to be safe wait for 12-24 hours before removing your WhatsApp installation and registering the same number using the yowsup-cli as above. See [issue 2482](https://github.com/tgalal/yowsup/issues/2482) for reference.

Good luck.

**Comment by hncvj** [comment]
Followed that it's working like a miracle. I'm building something awesome on top of this library.

**Comment by fmachadodev** [comment]
@andreazevedobauru 
Thanks for your tips, but my problem is i can't activate the number with yowsup, I always get the "temporarily_unavailable" error :(
I don't want to send messages, just receive btw.

are u From Brasil, right?

**Comment by andreazevedobauru** [comment]
Yes i'm, this problem is the same, to activate and to register.
I you send to you some ideas

**Comment by tombaki** [comment]
@fmachadodev register number with my edit Wart version then login with S40

**Comment by WanKapef** [comment]
@tombaki your wart version still working? Here is a bug "bad param"

**Comment by aramirezg1986** [comment]
any solutions?

**Comment by tgalal** [comment]
don't run on google cloud server

**Comment by weechatfly** [comment]
> Just do one thing.. extract id from whatsapp .. which is caculated by me and rc2 file in /data/data/com.whatsapp. then use that id in url
> [https://v.whatsapp.net/v2/exist?cc={0}&in={1}&id={2}&&lg={3}&lc={4}](https://v.whatsapp.net/v2/exist?cc=%7B0%7D&in=%7B1%7D&id=%7B2%7D&&lg=%7B3%7D&lc=%7B4%7D)
> you will get pw here
> try test that

hi,RakeshKumar1684
i try it ,but only get:
status: b'ok'
login: b'xxxxxxxxxxxx'
type: b'existing'
chat_dns_domain: b'fb'
edge_routing_info: b'CAgIBQ=='
how can i get pw? 
thanks!

**Comment by tgalal** [comment]
@weechatfly please don't comment random stuff on random issues
