### ISSUE TITLE
Bloqueo

### ISSUE THREAD

**Issue by javy1989** [tgalal/yowsup#2458]
Al enviar el mensaje todo estuvo bien al intentar de nuevo otro mensaje la respuesta fue que la cuenta esta bloqueada, como puedo arreglar esto...

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.
