### ISSUE TITLE
is this library free or Paid as a services ?

### ISSUE THREAD

**Issue by albaizzz** [tgalal/yowsup#2460]
When I registered the number with yowsup-cli, there is info about price_expiration, 
price_expiration: 1521991294
currency: USD
cost: 0.99
expiration: 4444444444.0

is this library use for free or paid as a services ?

**Comment by altmas5** [comment]
Hello @albaizzz 

This library interacts with Whatsapp webservice.
The answer you are getting it's directly from Whatsapp, so that's their subscription fee.

Regards.

**Comment by albaizzz** [comment]
is is connect via whatsapp or whatsapp for business service ?

**Comment by altmas5** [comment]
Just WhatsApp

**Comment by ri7nz** [comment]
this is library its free


Pada tanggal Sel, 20 Mar 2018 pukul 21.23 Jorge Vallecillo <
notifications@github.com> menulis:

**Comment by albaizzz** [comment]
Is this library able to request to whatsapp api with proxy server ? any body try it before?

**Comment by albaizzz** [comment]
hai bro @altmas5 could I have your email, I wanna ask something about this library

**Comment by altmas5** [comment]
Hello,

It should work behind a proxy (when it use to work).

Right now there is a major issue with this library, it is been recognized by Whatsapp and they are banning users.

**Comment by Kudlaty01** [comment]
> When I registered the number with yowsup-cli, there is info about price_expiration,
> price_expiration: 1521991294
> currency: USD
> cost: 0.99
> expiration: 4444444444.0
> 
> is this library use for free or paid as a services ?

Is user obliged to pay after receiving such message?
