### ISSUE TITLE
Error trying to register the WhatsApp account (--register). Error: old_version

### ISSUE THREAD

**Issue by javichuteck** [tgalal/yowsup#2462]
I just cloned the repository.

I have executed the command to get the registration code and it arrives correctly

`yowsup-cli registration -r sms -C 34 -p 34XXXXXXXXX -m 214 -n 01 -E android -d`

Trying to register the number, using this command

`yowsup-cli registration -R 818-270 -p 34XXXXXXXXX -C 34`

I have the error:

> yowsup-cli  v2.0.15
yowsup      v2.5.7
Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org
This software is provided free of charge. Copying and redistribution is
encouraged.
If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
INFO:yowsup.common.http.warequest:{"login":"34XXXXXXXXX","status":"fail","reason":"old_version"}
status: fail
reason: old_version
login: 34XXXXXXXXX

How can I solve that?

(logically, where are the XXXXX there is a correct phone number)

Thanks!!

PD: It is installed and working on OSx

**Comment by altmas5** [comment]
Hello,

It's a general issue. There are a lot of issues related to that.
No solution yet.

Regards

**Comment by ydennisy** [comment]
@altmas5  I have the same issue, is there a workaround?

**Comment by anoopgpr** [comment]
Yes there is a workaround...open env.py inside yowsup\env directory and comment s40 add Android as default like this
#DEFAULT = "s40"
DEFAULT = "android"

Make sure uncomment s40 and remove android aftrer registration process completed

**Comment by javichuteck** [comment]
It worked correctly.

I have connected within my WhatsApp, I have been able to send messages, see the list of my groups, etc.

Thank you very much

**Comment by Berser6523** [comment]
@anoopgpr 
run python setup.py install after or do not need it?

**Comment by Berser6523** [comment]
@javichuteck 

Okay, let's refactor this and leave it a step by step to the guys who have the same problem

1st change yowsup / yowsup / env env.py

#DEFAULT = "s40"
DEFAULT = "android"

2nd run python installation setup.py to recompile change fair on env.py

3rd request the WhatsApp verification code

using yowsup-cli registration -r sms -C 55 -p 55XXXXXXXXX -m XXX -n XX -E android -d

4th Perform the validation of the phone number with the code received

using yowsup-cli registration -R XXX-XXX -p 55XXXXXXXXX -C 55

5th install python setup.py

6th yowsup-cli demos -s 5535XXXXXXXX "test" -c
-> config file location /etc/yowsup/config.conf


right

**Comment by javichuteck** [comment]
No. Information is missing, one step is missing before 5

**Comment by Berser6523** [comment]
?

**Comment by javichuteck** [comment]
1 -  Change yowsup/env/env.py
Set `DEFAULT = "s40"` to `DEFAULT = "android"`

2 - Execute `python setup.py install`

3 - Request the WhatsApp verification code
`yowsup-cli registration -r sms -C 34 -p 34XXXXXXXXX -m 214 -n 01 -E android -d`

4 - Perform the validation of the phone number with the code received
`yowsup-cli registration -R XXX-XXX -p 34XXXXXXXXX -C 34`

Here, a lot of data will appear on the screen, but the most important one is a password.

5 - Save the configuration for later use. It will be saved in a file with the following format:
`cc=34t`
`phone=xxxxxxxxxt`
`password=xxxxxxxxxxxxxxxx`
Example of file name: `whatsapp_config.txt`

6 -  Change yowsup/env/env.py
Set `DEFAULT = "android"` to `DEFAULT = "s40"`

6 - Execute `python setup.py install`

7 - Start the WhatsApp client with the configuration data
`yowsup-cli demos --yowsup --config whatsapp_config.txt`

8 - With step **7** we will be initiating session. Now you have to connect: `/L`

9 - We can send a message from the terminal to see that everything works fine:
`/message send 34XXXXXXXX hola`

10 - See the list of groups we have with that WhatsApp line
`/groups list`


11 - Etc.

**Comment by Berser6523** [comment]
very good thank you very much

**Comment by altmas5** [comment]
Hello @javichuteck 

You aren't getting banned?

Regards

**Comment by altmas5** [comment]
Hello @javichuteck

Aren't you getting banned yet?

Regards

**Comment by Berser6523** [comment]
@javichuteck  
I think it's the same as linux if you did not complain because it worked

**Comment by maiconcosta** [comment]
Has the @javichuteck solution been running? 
Does the application stay in the air without being banned?

**Comment by Berser6523** [comment]
@magicgoose 
I just bought a chip so far everything worked out tomorrow I'll come back with information

**Comment by magicgoose** [comment]
@Berser6523 hmm?

**Comment by Berser6523** [comment]
@magicgoose 
so far I have not been banned bot is running normal

**Comment by magicgoose** [comment]
@Berser6523 perhaps you wanted to mention someone else and not me? Please look carefully. Hopefully I won't need to block you on GH.

**Comment by maiconcosta** [comment]
@Berser6523 Please keep me informed.

**Comment by Antorai78** [comment]
After doing the new registration everuthing worked but after the first message.. 
{"status":"fail","reason":"blocked","login":"XXXXXXXXXXX"}
Can I do something?

**Comment by Berser6523** [comment]
It's normal, it's working, I block it, I'll tell you

**Comment by maiconcosta** [comment]
After doing the process I was banished immediately.

**Comment by Berser6523** [comment]
I did exactly what it worked for me to make sure your configuration file is correct

**Comment by anoopgpr** [comment]
Make sure not more than 2 registration from same ip...A phone can have maximum 2 sim same thing goes with ip..but yes i m not 100% sure on this but my experience force me to draw this conclusion

**Comment by AdamSorrel** [comment]
hey! this is not very creative, but after attempting the workaround, I went from error `old_version` to:
```
status: b'fail'
reason: b'too_recent' 
```

I feel that whatsapp is trolling me by now :-).

**Comment by altmas5** [comment]
It-s hard to say @ydennisy 
I was using a kind of event-based whatsapp response to users on a call system and got blocked.

**Comment by nestorb86** [comment]
It's definitely hard to say. 
I just got 2 SIMs blocked yesterday but I still have one working. Same yowsup version, same steps.
The difference is that I "installed" the one that's working like 3 weeks ago.

**Comment by Berser6523** [comment]
My bot just received being banned.

**Comment by joaqhoc** [comment]
Auth: Logged in!
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, getting their keys now
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:No session for xxxxxxxxxxxx, getting their keys now

Traceback (most recent call last):
  File "C:\yowsup-master\yowsup-cli.py", line 368, in <module>
    if not parser.process():
  File "C:\yowsup-master\yowsup-cli.py", line 268, in process
    self.startCmdline()
  File "C:\yowsup-master\yowsup-cli.py", line 297, in startCmdline
    stack.start()
  File "C:\yowsup-master\yowsup\demos\cli\stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "C:\yowsup-master\yowsup\stacks\yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\yowsup-master\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "C:\yowsup-master\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\yowsup-master\yowsup\layers\axolotl\layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "C:\yowsup-master\yowsup\layers\protocol_notifications\layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 146, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)

what is this?

**Comment by nitoniso** [comment]
i am still having the same problem. help please

**Comment by rafaelsachetto** [comment]
This weekend works fine now I've the same error of "old_version"
