### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by maiconcosta** [tgalal/yowsup#2465]
Has anyone managed to use the library for more than months without being banned? I record a number and it only works for a few hours. Does the library still work? If so, how can I make it stable?

**Comment by cijo7** [comment]
An attempt to save it is being made on #2442. Please contribute.

**Comment by lddd** [comment]
Go build your own API, don't make it public. Do not spam people e.g sending bulk messages to contacts don't want to receive messages and you are save.

**Comment by hgc2002** [comment]
It works, but it takes time to get used to how to manage it, as everything that deserves to be done.

**Comment by maiconcosta** [comment]
@hgc2002 How did it keep running without being banned?

**Comment by ykguCoder** [comment]
@hgc2002 how to manage it?
