### ISSUE TITLE
banned all numbers!! what is happen to Yowsup?? it's because  WA 2.0 protocol  ??

### ISSUE THREAD

**Issue by zablah** [tgalal/yowsup#2466]
as all you know android environment has stop connecting to WhatsApp server maybe because WhatsApp force all clients to use WA 2.0 protocol and yowsup do not support this protocol.
this is a big problem for yowsup user and some people say this is the end of yowsup!!
also, we can't set a new registration using s40 env, but we can connect using s40 env at the moment and nobody knows when this stop
what we can do about that? 
what is the solution?

**Comment by cijo7** [comment]
#2422

**Comment by hgc2002** [comment]
Still working, no issue on registering new numbers

**Comment by vjyanand** [comment]
@hgc2002 do you register as android (env) and use it as s40? Thanks
