### ISSUE TITLE
Number banned after sending the first message

### ISSUE THREAD

**Issue by DwarfKiller** [tgalal/yowsup#2467]
Hello
I registered 2 numbers with the current version of yowsup and after registering and sending the first message the numbers were banned.
Would anyone know if there are any more updates that should be made in this version so it does not happen?

**Comment by ykguCoder** [comment]
The same to me.How to deal with it?

**Comment by DwarfKiller** [comment]
@tgalal do you have any idea?

**Comment by gsahbi** [comment]
yowsup is over, Whatsapp came up with a way to detect bots

**Comment by lddd** [comment]
@gsahbi. They not "came up with", they fighting against any public available non-official API for years. And its really not wonder its not working and getting your number banned if using something stupid like Yowsup. Go build your own API based on WhatsApp Web and you are save as long as you not sending messages to people don't want to receive it, e.g sending bulk spam shit. There is no problem with doing a Chat Bot based on WhatsApp Web. This can be done in a few minutes through WhatsApp Web.

**Comment by Twister21** [comment]
Do you have any code snippet for connecting to WhatsApp web? I would like to implement a Java WhatsApp bot for sending status updates. Unfortunately, it seems like there is no update for yowsu in the future.

**Comment by lddd** [comment]
Just create your own API making use of WhatsApp Web....

**Comment by Twister21** [comment]
Yes, but how to start? I think there is needed a QR-Code.

**Comment by ydennisy** [comment]
@lddd please provide some idea of how to do that instead of saying "just make it"

**Comment by lddd** [comment]
Learn how to code or hire some freelancer?

**Comment by ydennisy** [comment]
Ok thanks @lddd for proving you know nothing about how to actually build on whatsapp web.

**Comment by lddd** [comment]
@ydennisy Thanks for proving you have no idea of how to use the search function here or even doing a simple Google Search for something like "WhatsApp Web" "WhatsApp Web + APi "Whatsapp Web + automation" or similar. 

You should do some research before blaming on me. Or ask some more specific question to a problem you face...

**Comment by hgc2002** [comment]
you must do other stuff before sending messages, as anybody with the app would do, like registering contacts, getting statuses, updating yours, etc. Simply make your program behave more like a human, if you know what I mean. This is why creating bots is difficult.

**Comment by Twister21** [comment]
I thought that the main problem would be that the environment for sending a message compared to the environment used for the registration of the number changed. Unfortunately, I cannot try something because the risk of getting blocked another time is too high.

**Comment by chriso0710** [comment]
Just take a look at https://github.com/mukulhase/WebWhatsapp-Wrapper
Works great!

**Comment by Twister21** [comment]
Thank you for the hint. But is it true that the smartphone needs to be online all the time? That's the main point.

**Comment by chriso0710** [comment]
Yes, but there is no real Whatsapp API, so you will have to make some tradeoffs.
Unstable/dead yowsup with high risk of getting banned vs. working solution with whatsapp web automation and QRcode. Your choice :-)

**Comment by lddd** [comment]
@WebWhatsapp-Wrapper is very bad documented and missing a lot of important things. It gives you at most a small entry on how you can automate WhatsApp through browser automation. However its miles away from anything i would want to use in production.

**Comment by chriso0710** [comment]
> However its miles away from anything i would want to use in production.

Which of course is also true for yowsup.

**Comment by lddd** [comment]
@chriso0710 

Yes. 100% agree :-)

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

> I see that the community of Yowsup is very growing, my recommendation is that we adapt to the library to avoid excessive abuse of the tool. 

- Limiting shipping quantities for a limited time.
- Avoid sending images with marketing reasons.
- Do not initialize conversations with people who do not have you as a contact.
- Do not initialize conversations with a number that is not within your contacts. 

**I understand that giving a good use to this tool can evolve until you get to look for financing to become an official API**. This has a lot of potential for doing business both for whatsapp and for the Yowsup community.

**Comment by pickyassist** [comment]
Majority of the Github repositories and resources becomes dead after WhatsApp officially stop support all symbian and old windows phones as the core of the repositories are based on the Nokia & Blackberry phones, WhatsApp also start blocking numbers who are activating the numbers in modded devices or virtual devices.

We have experimented majority of the projects available in the internet and found all are based on the same logic that is known to whatsapp as a result the number keep blocking.
 
 
Keeping all these facts in mind we a group of developers from UK, US, India & Singapore expertise in many technology starts thinking to make a stable solution.
 
After many months of research and development we have developed a stable solution for interacting with whatsapp through server, especially through web services or API’s.
 
We have just released a beta testing version with LIVE Demo for developers , please check https://pickyassist.com and experience the innovation.
 
Using this API you can build innovative application over whatsapp without worry about getting it blocked, your customers can use their own whatsapp personal or business number with our services ( no need to share any OTP to us) 
 
Please note we don't have any official association with Whatsapp / Facebook, we are trying to solve a painful problem for developers with the full consent of the whatsapp users who intended to use their whatsapp as Robots
