### ISSUE TITLE
presence subscribe stoped after 2 days

### ISSUE THREAD

**Issue by tombaki** [tgalal/yowsup#2468]
when i subscribe number i got it work after 2 days stoped notify any presence 
if i add new number it's work  
but the old one not work until unsubscribe and subscribe it again ... 
any method to keep it subscribed

**Comment by hgc2002** [comment]
no

**Comment by tombaki** [comment]
@hgc2002 @tgalal 
okey when it stoped did i get message before stoped or it stoped without any message

**Comment by victorgt26** [comment]
Hello everyone, I have the same problem, when the presence_subscribe command is sent, no response is received, but when a new number is registered, the response to the command is received the first 20 times approximately

**Comment by vjyanand** [comment]
I think it is by design by whatsapp
