### ISSUE TITLE
Presence subscribe not working for me

### ISSUE THREAD

**Issue by infahash** [tgalal/yowsup#2470]
I have added these lines to demos/cli/layer.py

`
@ProtocolEntityCallback("presence")
    def onPresenceChange(self, entity):
          now = datetime.datetime.now()
        if "unavailable" in str(entity.getType()):
            print("number" + str(entity.getFrom(False)) + " not available at " + str(now))
        else:
            print("number " + str(entity.getFrom(False)) + " available at " + str(now))`

and then run 
`/contacts sync 94XXXXXXXXX`

then I got this output
`
ID: 15
Type: result
from: 94XXXXXXXXX@s.whatsapp.net
Wait: 437822
Version: 1522428339638247
In Numbers: 
Out Numbers: 94XXXXXXXXX
Invalid Numbers:
`
after I try to subscribe presence with `/presence subscribe 94XXXXXXXXX`

But nothing showing when I goes online/offline from my number

**Comment by hgc2002** [comment]
working fine here. I suppose the number you are suscribing too is not blocking any information, that can happen in the new app versions since some time ago

**Comment by tgalal** [comment]
Out numbers from sync means number is not a registered whatsapp user, hence no presence
