### ISSUE TITLE
Login Failed, reason: not-authorized

### ISSUE THREAD

**Issue by NicolaKr** [tgalal/yowsup#2472]
yowsup-cli demos --yowsup --config config
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

I always get this message. Login Failed, reason: not-authorized. What should I do?
Please Help

**Comment by o---** [comment]
You password is incorrect. Re-register and use new password.

**Comment by NicolaKr** [comment]
Thanks, I'll try it.

**Comment by NicolaKr** [comment]
It's now working.

**Comment by ydennisy** [comment]
@NicolaKr how did you fix this issue?

**Comment by NicolaKr** [comment]
My problem was that I took the wrong form of the phone number.

**Comment by vjyanand** [comment]
@NicolaKr Which means, you could run it without getting blocked?

**Comment by hncvj** [comment]
Can you please share how you fixed this issue?

**Comment by Painkiller1991** [comment]
@NicolaKr can you explain more? what is the wrong and true number? can you give us an example?

**Comment by Nanda-kumaran** [comment]
@NicolaKr , i also facing the same issue. could you please update on what is the issue fix?

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

**Comment by 3dluis** [comment]
I see that the community of Yowsup is very growing, my recommendation is that we adapt to the library to avoid excessive abuse of the tool. Limiting shipping quantities for a limited time, avoid sending images with marketing reasons, do not initialize conversations with people who do not have you as a contact, do not initialize conversations with a number that is not within your contacts. I understand that giving a good use to this tool can evolve until you get to look for financing to become an official API. This has a lot of potential for doing business both for whatsapp and for the Yowsup community.

**Comment by Nacho223** [comment]
Check my comments here and try your own tests.

https://github.com/tgalal/yowsup/issues/2482#issuecomment-381967382

**Comment by pickyassist** [comment]
This error Login Failed, reason: not-authorized is because of whatsapp identified an unauthorised login attempt from non supported device or modded device.  

If you are looking for 2 way engaging conversation through whatsapp then try Try Picky Assist https://pickyassist.com an interactive 2 way messaging solution for developers (no bulk sending , no spam and no blocking)
