### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by magnussolution** [tgalal/yowsup#2474]
_MD5_CLASSES = "TNr5/Xc1X1RV3vHoHWpXgg=="
_VERSION = "2.18.99"

anyone have new version??

Best regards

**Comment by jsuceir** [comment]
vc conseguiu ?

**Comment by magnussolution** [comment]
sim

**Comment by jsuceir** [comment]
o que fez to com o mesmo problema da um help

**Comment by sbru** [comment]
I was able to register but after the first message I was blocked

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________

**Comment by jsuceir** [comment]
nao consegui abrir esse link =/

**Comment by jsuceir** [comment]
ah intendi vc mas está enviado ?

**Comment by jsuceir** [comment]
mas vc que tá enviado a mensagem ou só tá recebendo ?
