### ISSUE TITLE
Using personal number, but then registered new number and banned.

### ISSUE THREAD

**Issue by ydennisy** [tgalal/yowsup#2475]
Hello,
I was using my own number which I have used with whatsapp for years and I was not banned.
Then I bought a special purpose number and it was blocked after a single message.
Does anyone know which types of numbers are blocked, any reason i.e IPs etc?
Thanks,
Dennis

**Comment by MartinAbilev** [comment]
use of this lib`s is against whatsapp, and they will ban you numbers every time , i already got 3x numbers blocked. last block-case happens when i try send msg to number without whatsap installed.

**Comment by MartinAbilev** [comment]
i bet this project is dead ... i agree it must be in readme.md !!!

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

**Comment by 3dluis** [comment]
I see that the community of Yowsup is very growing, my recommendation is that we adapt to the library to avoid excessive abuse of the tool. Limiting shipping quantities for a limited time, avoid sending images with marketing reasons, do not initialize conversations with people who do not have you as a contact, do not initialize conversations with a number that is not within your contacts. I understand that giving a good use to this tool can evolve until you get to look for financing to become an official API. This has a lot of potential for doing business both for whatsapp and for the Yowsup community.

**Comment by Nacho223** [comment]
Check my comments here and try your own tests.

https://github.com/tgalal/yowsup/issues/2482#issuecomment-381967382
