### ISSUE TITLE
Register Virtual/Online Mobile Number

### ISSUE THREAD

**Issue by ydennisy** [tgalal/yowsup#2476]
Hello, any ideas on a good place to register an online virtual mobile number to use with yowsup?

**Comment by hiwaleakshay** [comment]
https://www.virtualphone.com/

**Comment by jicsalas** [comment]
Hay app como NextPlus que te da un número gratis. Después puedes registrarlo por sms o voz (comand voice).
Hay formas para el registro que no te pide los mcc o mnc:
python yowsup-cli registration -p 569xxxxxxx -C 56 -r sms

**Comment by SpEcHiDe** [comment]
@ydennisy This [video](https://youtu.be/Nv2lc5jjTVA) works.
