### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by magnussolution** [tgalal/yowsup#2478]
I need filter active numbers. I can pay 100 USD.

thanks

**Comment by 3dluis** [comment]
How many numbers are you talking about and from what location?

**Comment by magnussolution** [comment]
500 numbers each 10 seconds 24 hour per day. 

The numbers are in mysql table. I'm a developer, PHP, javascript to backend.

**Comment by magnussolution** [comment]
magnusadilson@gmail.com contact me

**Comment by tgalal** [comment]
@magnussolution if you do this again you are banned
