### ISSUE TITLE
New Whatsapp API SaaS - Avoid bans

### ISSUE THREAD

**Issue by rhuantac** [tgalal/yowsup#2479]
Hi guys, I'm bringing to you an yowsup alternative for your business. You only need Whatsapp app installed on your phone! You scan the QR Code for web and it's working! :D Simple as that [http://waconnect.me](http://waconnect.me)

PS: Give it a try, we have a 3-day trial!

**Comment by gvn182** [comment]
Hey man is there any way I can contact you? I have some questions about this api.

**Comment by rhuantac** [comment]
Sure! Reach me on telegram: [https://t.me/rhutac](https://t.me/rhutac)

**Comment by tgalal** [comment]
@rhuantac if you do this again you are banned
