### ISSUE TITLE
Login failed, reason: not authorized

### ISSUE THREAD

**Issue by ande4485** [tgalal/yowsup#2482]
Hi.
I know there're issues about this problem. But I can't figure out. Could you explain how to fix it.
I registered with env=android
And after sending a message I have this error.

I work with rapsberry pi.
Thanks

**Comment by vjyanand** [comment]
Probably got banned. Try re-registration.

**Comment by 3dluis** [comment]
WhatsApp has implemented some automatic processes to detect bot and a human team for possible behavior. The bad management in the implementation of bot has it that the platform of whatsapp was blackoff for this reason, it does not matter if you implement a Bot by Whatsapp Web or direct connection to the server funxmpp and your behavior is like a Bot is 100% that your number and IP be banned.

**Comment by 3dluis** [comment]
I see that the community of Yowsup is very growing, my recommendation is that we adapt to the library to avoid excessive abuse of the tool. Limiting shipping quantities for a limited time, avoid sending images with marketing reasons, do not initialize conversations with people who do not have you as a contact, do not initialize conversations with a number that is not within your contacts. I understand that giving a good use to this tool can evolve until you get to look for financing to become an official API. This has a lot of potential for doing business both for whatsapp and for the Yowsup community.

**Comment by Nacho223** [comment]
I've done some tests and come to some conclusions: 

1 - If you register a number directly via yowsup, the number is banned after one message (tested with 3 numbers)

2 - If you register a phone in your android, chat a bit, and then, after 12 - 14h you close whatsapp client and register the number on yowsup, it works. 

3 - ONLY ONE TEST: 72h after registration on Android, and created profile via WApp Web, it fully worked for two weeks until I sent a friend one link that was banned in FB (and I didn't know).

**Comment by Nacho223** [comment]
The key, as I have been able to deduce, is that you must let whatsapp make the first start and synchronization of contacts. Then contacts can be extracted with applications like: 

https://play.google.com/store/apps/details?id=com.ebizzinfotech.whatsappCE

Or:

https://play.google.com/store/apps/details?id=plugin.checkwhats.com.checkwhatsapp

First one only let you extract 100, second claims it has no limit (I've exported almost 2000 from my phone, no further tests made).

Then, you can load your db and use it with your yowsup client.

**Comment by BenSchZA** [comment]
I've added the solution of @Nacho223 to the yowsup Wiki at [https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0](https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0). I successfully used this method to avoid black-listing, and have done some stress testing sending multiple successive and parallel messages to multiple numbers.

**Comment by andreazevedobauru** [comment]
@BenSchZA  I had to learn it after blocked five numbers. I was always tried to register before installing on mobile device.
Thank you.

**Comment by Nacho223** [comment]
Just in case, to be safer, I also modified the env_android.py (and recompiled) with this data:

_MD5_CLASSES = "YlajJPPGUUP1Ptcic2XKNA=="

_VERSION = "2.18.105"

**Comment by leocsg** [comment]
@Nacho223 how do you get new _MD5_CLASSES and _VERSION?

**Comment by Nacho223** [comment]
Version is on Whatsapp app in the menu where you can stop/unistall it. For MD5 Classes, use this:

https://github.com/mgp25/classesMD5-64

**Comment by vjyanand** [comment]
This gets latest APK https://gist.github.com/vjyanand/92c062f26b2235bc150062731ae2da63

**Comment by andresmmujica** [comment]
I followed the workaround procedure but I got  a unavailable message.  Didn't retry from yowsup but from an actual wp cliente and it says the number is suspended (not blocked)  I'm gonna wait a few days to retry again.

However I want to have clearer the contacts sync workaround and the md5sum and version one.

I mean, which would be the steps in order to minimize the risk of getting banned??

Thanks!

**Comment by BenSchZA** [comment]
Despite the workaround by @Nacho223 working initially, after a few days of using yowsup for a bot WhatsApp banned my number. The risk I think is impossible to avoid - WhatsApp will find out if they want to, probably just depends on how you're using the bot and how natural it seems.

**Comment by andresmmujica** [comment]
hmm.. ok, I just want to send key alerts from nagios.

**Comment by Nacho223** [comment]
Yes, Whatsapp has it very easy to block, as we are registering with Android and sending as a S40. And bots must be "natural", I agree with that: Login, send typing, send pause, etc.

**Comment by pickyassist** [comment]
This library is based on Nokia & Blackberry OS which whatsapp officially stopped recently , so chances of getting blocked is very high.

Majority of the users want to send unsolicited or spam communication using this tool which is against whatsapp polices.

Try Picky Assist https://pickyassist.com an interactive 2 way messaging solution for developers (no bulk sending , no spam and no blocking)

**Comment by BRNALX** [comment]
I think the problem may be the md5_classes.

So I looked at the site where I updated my md5: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Note that on this site the whats version points to 2.18.154, equal to: https://www.whatsapp.com/android/

But I looked at some devices and the installed version is 2.18.156, even the version available in the play store is version 2.18.156.

I generated the following MD5 for version 2.18.156 (GwmuFlEWPMKg9ojOJn4HLA ==).

But I still have not had success registering.

**Comment by anoopgpr** [comment]
Thanks Nacho223 and vjyanand i am able to fix old version issues..vjyanand your code is awesome to get version and _mds_classes

**Comment by andresmmujica** [comment]
@anoopgpr how?

**Comment by anoopgpr** [comment]
Just by changing env_android.py as per Nacho223 suggestion.

**Comment by wz343450860** [comment]
Hi , 
    I registered the phonenum  but I tried to login it return yowsup.layers.auth.autherror.AuthError: not-authorized, how can I solve this issue?

**Comment by leopoldobrines7** [comment]
Hi!
I updated the @vjyanand script because I had problems with that.
https://gist.github.com/leopoldobrines7/cd0ac04a8427dcf6f01deebb10af89eb

My script use other method to get WhatsApp version, via AndroidManifiest.xml 
Enjoy!

**Comment by aHVzY2g** [comment]
@Nacho223 can confirmt hat your method is still working? I followed your advice but got blocked after two messages

**Comment by BenSchZA** [comment]
@aHVzY2g I ended up moving on to developing my own projects based on Selenium and an Android VM, after being blocked a number of times. Here they are, they might be a good reference, or be useful to you: https://github.com/BenSchZA/wattie-whatsapp-bot https://github.com/BenSchZA/docker-android-avd

We're using the above projects in a production system, with 5000 users messaged weekly.

**Comment by aHVzY2g** [comment]
@BenSchZA Thanks I will have look into it

**Comment by isccha** [comment]
Is there any chance that using this library for testing won't get my number banned from Whatsapp? What's the current status?. Thanks!
