### ISSUE TITLE
How to use yowsup library for Android App

### ISSUE THREAD

**Issue by hiteshcla00** [tgalal/yowsup#2483]
I am building android app for auto reply .so how i will use this library for android app to send auto messages.

thanks.

**Comment by hncvj** [comment]
Hello Hitesh i can help you with the basic idea to achieve your goal. do let me know how we can reach each other. You can whatsapp me on 9610746167

**Comment by hiteshcla00** [comment]
@hncvj  help here plz

**Comment by hncvj** [comment]
@hiteshcla00 are you having a working yowsup? cause that is the first requirement.

**Comment by hiteshcla00** [comment]
@hncvj yes im working with yowsup.

**Comment by hiteshcla00** [comment]
@hncvj  so plz help me

**Comment by soulhunter32** [comment]
Hi, it's simple, you can use REST services. In my case, I'm working on a personal project, it's an app that sends messages, it communicates via REST to a Nodejs server that executes the yowsup-cli, asi easy as that.

**Comment by subhamsuthar** [comment]
> Hi, it's simple, you can use REST services. In my case, I'm working on a personal project, it's an app that sends messages, it communicates via REST to a Nodejs server that executes the yowsup-cli, asi easy as that.

Can You send me example code of Nodejs and yowsup-cli or send code for RAF idea...

Thanks Advance
