### ISSUE TITLE
I need send Message on PHP

### ISSUE THREAD

**Issue by EmersonHenriique** [tgalal/yowsup#2484]
I'm trying to make php run the command and so far nothing, can anyone give me a light?

yowsup-cli demos -c /yowsup/config  -s "55XXXXXXXXXX" "Hello World"

And it does not run for nothing.

`<?php
$cmd = 'yowsup-cli demos -c /yowsup/config  -s "55XXXXXXXXXX" "Hello World"';
echo shell_exec ($cmd);
?>`
Return 
`yowsup-cli v2.0.15 yowsup v2.5.7 Copyright (c) 2012-2016 Tarek Galal http://www.openwhatsapp.org This software is provided free of charge. Copying and redistribution is encouraged. If you appreciate this software and you would like to support future development please consider donating: http://openwhatsapp.org/yowsup/donate`

But the message is not sent.

@tgalal

**Comment by jicsalas** [comment]
$salida = shell_exec(yowsup-cli demos -c /yowsup/config -s "55XXXXXXXXXX" "Hello World");
echo "<pre>$salida</pre>";

asegurate de poner bien la ruta absoluta cuando ejecutes el shell, porque varía de pende donde crees tu archivo php.

**Comment by netfiretec** [comment]
Good afternoon my dear, the API you say you have and in what language?
Own Development?
What country are you from?

Answer me at netfiretecc@gmail.com please.
