### ISSUE TITLE
Stream Error type: ack {'ack': None}

### ISSUE THREAD

**Issue by shubhamparamhans** [tgalal/yowsup#2486]
I am getting this error again and again, any idea what may have causing this??

> Stream Error type: ack
{'ack': None}

**Comment by vjyanand** [comment]
What was XML response?

**Comment by shubhamparamhans** [comment]
<stream:error>
        <ack></ack>
     </stream:error>

**Comment by shubhamparamhans** [comment]
```
<stream:error>
        <ack></ack>
     </stream:error>
```

**Comment by Elintondm** [comment]
The same here.

**Comment by shubhamparamhans** [comment]
All i know about this error is that its coming because of not acknowledging some message sent by whatsapp server!
Probably some new type of message sent, which is not supported by yowsup currently.

**Comment by Elintondm** [comment]
My yowsup is stopping all time due this error. Any workaround?

**Comment by SpEcHiDe** [comment]
This response is coming when the "reply" message feature is used.

**Comment by shubhamparamhans** [comment]
@SpEcHiDe  yeah you are right!
I think what we need to do is to handle this message type @tgalal

**Comment by pkeuter** [comment]
Has anyone been able to find out a workaround for this? I'm running into this issue as well!
