### ISSUE TITLE
Problems registering a number in yowsup

### ISSUE THREAD

**Issue by lukasMacedo06** [tgalal/yowsup#2493]
I'm trying to register my no on yowsup, but it's failed and I received that response:

**{'status': u'fail', 'kind': None, 'code': None, 'pw': None, 'price': None, 'price_expiration': None, 'retry_after': 3600, 'currency': None, 'length': None, 'cost': None, 'param': None, 'reason': u'no_routes', 'login': u'554792563479', 'type': None, 'method': None, 'expiration': None}**

This is my current *env_android* file settings:

    #_MD5_CLASSES = "Cqr16m+5VgR6UphpO5ecCg=="
    #_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g==" ULTIMO
    _MD5_CLASSES = "GPZ3TUV8wkLof+xn8YMERg=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    #_VERSION = "2.17.16" ULTIMO 442
    _VERSION = "2.18.46"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    #JLS36C
    _AXOLOTL = True`

I was looking for an update to **env android**, but I didn't find anything.... Somebody here had the same problem or found an update?

Thanks in advance

**Comment by smsaurabhv** [comment]
same here

**Comment by georg90** [comment]
yup, same! using `--env android` Worked two days ago.

**Comment by andreazevedobauru** [comment]
I have the same problem,
I can send messages with 2 number that i have registered, but when i try register a new one, i cant : "reason: no_routes".

I tried with, python 2 and 3, with 2 chips, i changed the server, but nothing.

**Comment by andreazevedobauru** [comment]
I found the problem, i changed my ip to an ip on EUA, my old ip was in England.
Now can i register again.

**Comment by PanderMusubi** [comment]
See also https://bugs.launchpad.net/ubuntu/+source/yowsup/+bug/1769402

Indeed putting your phone on other IP via data connection will prevent getting logged off on your phone. Or, run yowsup on a server that has another IP and leave your phone on your wifi.

**Comment by emretekince** [comment]
@georg90 did you solve this?

**Comment by andreazevedobauru** [comment]
@lukasMacedo06 i understood in my case i used a proxy, so i don't changed the machine's ip.
But good luck, if you want talk more about this add my number: 5514998746189, feel free to send me a whatsapp

**Comment by RakeshKumar1684** [comment]
For fixing registration issue contact me. Email id: rehaaan0711@gmail.com

**Comment by ferpujol** [comment]
@georg90 I have exactly the same issue. Did you solve it?

**Comment by ignertic** [comment]
download whatsapk of version of your choice and the download this script from https://gist.github.com/masbog/dc809d6dc6568d729e3cca88b82d3bd0.
Change the file name inside script to the whatsapp apk you downloaded
Use the MD5 produced

Make sure your system date is correct.
