### ISSUE TITLE
Subscribing presence no longer works

### ISSUE THREAD

**Issue by emretekince** [tgalal/yowsup#2495]
Hi, I can't receive presence information since 6th May. I think WhatsApp changed their algorithm.
Anyone else facing the same issue?

**Comment by vjyanand** [comment]
it works for me, as of now

**Comment by emretekince** [comment]
With S40? How many numbers are you subscribing for an account? @vjyanand

**Comment by vjyanand** [comment]
Yes with s40. I have just started with 10. Previously it used to work upto 1000

**Comment by jrrpm** [comment]
@vjyanand any idea how to wireshark the msgs to implement new protocolentities in this project?  I want to send whatsapp web QR code from yowsup app.

**Comment by vjyanand** [comment]
@emretekince I doesnt work for me too. It stopped.

**Comment by emretekince** [comment]
@vjyanand Yes we need to do reverse engineering for Whatsapp apk. It sends encrypted requests to server which has only "ENC" field and its fully encrypted. I also tried to sniff socket connection but sniffer didn't capture..

**Comment by karopass** [comment]
Hi!
Anyone have got fix of this issues?
Thanks

**Comment by mayankjain05** [comment]
@vjyanand What is the maximum limit on the number you can subscribe?
Did you get banned when you subscribed to multiple numbers ?

**Comment by sgheith** [comment]
I noticed the following behavior for the presence when using yowsup-cli (and my own application as well)
1) I set my presence to available 
2) I sync contacts using /contacts sync +44XXXXX,+44YYYYYY
3) I subscribe to the above contacts by calling /presence subscribe 44XXXXX, /presence subscribe 44YYYYY etc...

If the list of contacts is 40 or less then everything works fine and I get the presence information for all the 40 contacts.

If the list of contacts is over 40 then I stop getting presence information for most (and sometimes all) contacts.
The problem occurs exactly when I subscribe the 41st number in step 3 above. Immediately I stop getting presence information for contacts.
In fact once this happen I cannot fix the issue by unsubscribing any contact to make the number less than 40. I actually cannot use the number to check presence again.
I noticed that the only way to get any contact to send me presence after that is by sending him a message.
I appreciate any help in this as it is blocking me. At least is their a way to fix the number and use it for less than 40 contacts?

Regards

**Comment by tgalal** [comment]
works fine

**Comment by fevzican** [comment]
> I noticed the following behavior for the presence when using yowsup-cli (and my own application as well)
> 
> 1. I set my presence to available
> 2. I sync contacts using /contacts sync +44XXXXX,+44YYYYYY
> 3. I subscribe to the above contacts by calling /presence subscribe 44XXXXX, /presence subscribe 44YYYYY etc...
> 
> If the list of contacts is 40 or less then everything works fine and I get the presence information for all the 40 contacts.
> 
> If the list of contacts is over 40 then I stop getting presence information for most (and sometimes all) contacts.
> The problem occurs exactly when I subscribe the 41st number in step 3 above. Immediately I stop getting presence information for contacts.
> In fact once this happen I cannot fix the issue by unsubscribing any contact to make the number less than 40. I actually cannot use the number to check presence again.
> I noticed that the only way to get any contact to send me presence after that is by sending him a message.
> I appreciate any help in this as it is blocking me. At least is their a way to fix the number and use it for less than 40 contacts?
> 
> Regards

is it still like that ? Or is there an improvement about that ?
