### ISSUE TITLE
How to find our own mobile specification for using in android.env

### ISSUE THREAD

**Issue by Painkiller1991** [tgalal/yowsup#2497]
How to find our own mobile specification like MD5, key and extra to use in android.env and get login in yowsup

**Comment by tombaki** [comment]
@Painkiller1991 
[https://coderus.openrepos.net/whitesoft/whatsapp_scratch ](https://coderus.openrepos.net/whitesoft/whatsapp_scratch ) 
env for register

**Comment by Painkiller1991** [comment]
@tombaki what is a, b, c, ...?

**Comment by Tinocoo** [comment]
The problem was solved?

**Comment by Painkiller1991** [comment]
@Tinocoo  not completely, some item do not know what, i mention it above

**Comment by Tinocoo** [comment]
Do not. I have the same problem and I'm following up.

**Comment by Painkiller1991** [comment]
@tombaki can help more??

**Comment by Painkiller1991** [comment]
@Tinocoo 

For s40:
gets token info from:
https://coderus.openrepos.net/whitesoft/whatsapp_scratch
Gets the version from "e", and makes the token from "b" appended with the numbers part of "c" and "{phone}"

For Android:
gets token info from:
https://coderus.openrepos.net/whitesoft/whatsapp_scratch 
and then copy "a" y "d" _VERSION and _MD5_CLASSES in yowsup/env/env_android.py
