### ISSUE TITLE
Best practices foir avoiding being banished

### ISSUE THREAD

**Issue by williamneto** [tgalal/yowsup#2500]
Hello everybody,
Im usin yowsup for massive sent of messages, and got the problem of being banished. The first time it heppened i just changed the line for another one that i was using on my celphone from a couple of days.
Now, on the last time, i sent more than 1500 messages, and got banished but doing the same process (changing the line for another one that was chating via phone for one day) i got banished at registering.
So I noted that it is necessary some precautions like
- set an aleatory time interval betwen the every message i sent
- do not send too many messages in short time period (1500 like i did)

And I wanna know if anyone has any other recommendations. For example, I do not know if the banishment is only for the number or even my ip. Should I use proxy? How much time is recommended to use a new line on the phone (chating usualy, simulating human behavior) before register on yowsup?

Thanks a lot

**Comment by andreazevedobauru** [comment]
Hey @williamneto , i'll write in portuguese.

Cara, vc conseguiu utilizar proxy para enviar whats? Eu tive meu ip bloqueado pelo Whats, agora nao consigo registrar mais nenhum numero com esse IP, mesmo utilizando proxy.
Hoje eu tenho uma fila para enviar as mensagens, deixei intercalado entre 6 e 8  segundo para enviar as mensagens.
Antes de registrar novos números eu sempre utilizo eles por uns 3 ou 4 dias em um celular.

Fique a vontade para me enviar email ou adicionar no linkedin: andre.felipe.az@gmail.com

**Comment by williamneto** [comment]
Cara, nao usei proxy ainda. Cogitei essa hipotese quando desconfiei que meu IP estava banido. No caso, se estiver mesmo com IP banido, como consigo registrar novamente?

Bom ver programadores brasileiros por aqui, te mandei um e-mail

**Comment by BRNALX** [comment]
At the moment of registering the number you are receiving the message "Temporarily unavailable"?

I already tried different output IPs but I did not succeed.

**Comment by williamneto** [comment]
First e receive this "Temporarily unavailable" but after the block

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp
