### ISSUE TITLE
Receive messages

### ISSUE THREAD

**Issue by leoteixeira2016** [tgalal/yowsup#2501]
Hello people.
I can send messages perfectly with yowsup, but I can only receive messages when I use the yowsup-cli demos command --yowsup --config /yowsup/canal1.conf

and I connect with / L

and loaded everything that was sent to the number
Do you have any other way of seeing what is being received?

**Comment by theoneandonly-vector** [comment]
hey there.. as you can send (I can't) pls. could you give me advice?
what system do you use? what packahes did you install?

as I everytime get the following error (whe  I try to send):
AttributeError: 'NoneType' object has no attribute 'getChild'

I tried debian in different versions using the git and also the pip install-method..

**Comment by iamjagjeetubhi** [comment]
@theoneandonly-vector 
 
Please follow the following link for installation of YOWSUP

[Installation of YOWSUP in debian](https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/)

I hope it will works for you.

**Comment by iamjagjeetubhi** [comment]
@leoteixeira2016 

Hey!
It is possible with YOWSUP to receive messages but requires some knowledge about coding.
I can make it work on your server. Contact me using email in my profile.
