### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by imTDB** [tgalal/yowsup#2502]
Hi i've the following error:

```
INFO:yowsup.common.http.warequest:{"login":"xxxxxxxxxxx","status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param
login: xxxxxxxxxxx
```
Anyone has a idea of how to solve it? I write my number like this 1434xxxxxxx . Thanks in advance

**Comment by iamjagjeetubhi** [comment]
This is due to you have not provided right parameters like MNC & MCC of your network.
Here it the example for registering a number:

`python yowsup-cli registration --requestcode sms --phone 91xxxxxxxxxx --cc 91 --mcc 222 --mnc 10 -E android
`

Kindly change the CC, MNC & MCC with your network.

**Comment by bitmurder** [comment]
This is solved by registering the number first with the official application, and then requesting the registration from youswup, this is because whatsapp can not validate the phone number, it usually goes with land lines that do not have a mmc mcc
