### ISSUE TITLE
Error while registering even after changing environment in env.py from s40 to android

### ISSUE THREAD

**Issue by jagreetdg** [tgalal/yowsup#2506]
Initially I got old_version error while registering my number.
After reading previous issues , Here is what I did
1) Replace`DEFAULT=s40` to `DEFAULT=android` in env.py
2) Reinstalled by running `python setup.py install`
3) Run `python yowsup-cli registration --requestcode sms --phone 91XXXXXXXXXX --cc=91 --mcc=405 --mnc=53`

Here is the error message I get : 

python yowsup-cli registration --requestcode sms --phone 91XXXXXXXXXX --cc=91 --mcc=405 --mnc=53 
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:b'{"login":"91XXXXXXXXXX","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'91XXXXXXXXXX'

**Comment by eugenioclrc** [comment]
same here

**Comment by anoopgpr** [comment]
same here

**Comment by anoopgpr** [comment]
I am able to fix by changing version and _mds_classes in env_android.py

**Comment by eugenioclrc** [comment]
For what version did you change it?

**Comment by jagreetdg** [comment]
@anoopgpr Please Elaborate how did you change the version and _mds_classes. If possible provide the previous and new values you replaced and a section of env_android.py with the above changes

**Comment by williamneto** [comment]
I have the same problem. I replaced version on env_android.py for 2.18.156, but then i got fail for "bad_token" reason.

**Comment by anoopgpr** [comment]
U need to change _mds_classes as well

**Comment by williamneto** [comment]
change to what? What have you did?

**Comment by williamneto** [comment]
I found this https://coderus.openrepos.net/whitesoft/whatsapp_scratch in another issue, but it wasnt very clear which field to use.

**Comment by anoopgpr** [comment]
Here is my settings

 _MD5_CLASSES = "YlajJPPGUUP1Ptcic2XKNA=="
 _VERSION = "2.18.105"

**Comment by anoopgpr** [comment]
You can also use
_VERSION  2.18.165
_MD5_CLASSES : ARoKGN6FsfvIc/F6C+XGnQ==

**Comment by anoopgpr** [comment]
You can also use
_VERSION  2.18.165
_MD5_CLASSES : ARoKGN6FsfvIc/F6C+XGnQ==

**Comment by williamneto** [comment]
Thanks man, the first combination worked fine for me.
I was already trying version 2.18.165 and the MD5 ARoKGN6FsfvIc/F6C+XGnQ==  that i have found on the link i quoted before, but didnt work.

But using version 2.18.108 and MD5 YlajJPPGUUP1Ptcic2XKNA== worked!

**Comment by saulo3k** [comment]
work here now
    _VERSION = "2.18.165"
    _MD5_CLASSES = "ARoKGN6FsfvIc/F6C+XGnQ=="
last week i dont change this code, today is need

**Comment by xmsid** [comment]
to get a new `_VERSION` and `_MD5_CLASSES`, download the latest WhatsApp apk and use this script on it https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py
usage:
`python dexMD5.py whatsapp.apk`
or change `whatsapp.apk` to the apk name
you will get an output similar to this:
```
Version: 2.17.344
ClassesDex: OxVSHnBDYNBZmSiYzwF9+A==
```
you know the rest.
source: https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/
