### ISSUE TITLE
general: Disconnected: Connection Closed

### ISSUE THREAD

**Issue by hgfdjwkuhx** [tgalal/yowsup#2515]
please can someone help me ?
I'm not very well in english to explain my issue !
but I hope I have explained it !
in yowsup 
I have problem with connect with whatsapp !

two days ago my project didn't work like before, the problem it with connection with whatsapp server , the response it show under !

---------------------------------
<receipt_acks>
</receipt_acks>
<w:profile:picture>
</w:profile:picture>
<w:profile:picture>
</w:profile:picture>
<notification>
</notification>
<status>
</status>
</stream:features>

general: Disconnected: Connection Closed

**Comment by pabloruan0710** [comment]
I have same problem, somebody can help?

**Comment by lucasmarsola** [comment]
Did anyone get any progress with this problem?

**Comment by ildar** [comment]
https://github.com/tgalal/yowsup/issues/2333#issuecomment-354533670 ?

**Comment by chbinghu** [comment]
@pabloruan0710 Login with env android and send message with s40.

**Comment by kapil-raj** [comment]
done that but still not working
