### ISSUE TITLE
onMessage doesnt receive

### ISSUE THREAD

**Issue by williamneto** [tgalal/yowsup#2516]
Hello, im facing a problem that is piccing me off.
Im just tring to receive messages. I have did it before, but simply stoped working. I wil put the code here, yesterday was working. But now, i send a message to the yowsup number and the onMessage event isnt triggerd. 

`class ReadLayer(YowInterfaceLayer):
	@EventCallback(YowNetworkLayer.EVENT_STATE_CONNECTED)
	def onConnected(self, yowLayerEvent):
		print "----- CONECTADO ----- \n"

	@ProtocolEntityCallback("message")
	def onMessage(self, messageProtocolEntity):
		if messageProtocolEntity.getType() == 'text':
			frm = messageProtocolEntity.getFrom()
			body = messageProtocolEntity.getBody()
			
			print ("- Mensagem de %s \n>>> %s \n\n" % (frm, body))
		
		if messageProtocolEntity.getType()	== 'media':
		 	if messageProtocolEntity.getMediaType() == 'image':
		 		frm = messageProtocolEntity.getFrom()
		 		url = messageProtocolEntity.url

		 		print ("- Imagem de %s \n>>> %s\n\n" % (frm, url))

		self.toLower(messageProtocolEntity.ack())
		self.toLower(messageProtocolEntity.ack(True))
 		
	@ProtocolEntityCallback("receipt")
	def onReceipt(self, entity):
		self.toLower(entity.ack())`

**Comment by williamneto** [comment]
full log
`DEBUG:yowsup.env.env:registered env android => <class 'yowsup.env.env_android.AndroidYowsupEnv'>
DEBUG:yowsup.env.env:registered env s40 => <class 'yowsup.env.env_s40.S40YowsupEnv'>
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f3c274e4090>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f3c274cd790>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e9.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="5521992436545" mechanism="WAUTH-2">
bn�����p���FP�P�+"�h��_��)p�҃l�*sG��n-�����n>���p	
                                                       s;����8FN�
HEX:11626e9a88bcc4fc708b8fb74650c750e52b22b868fccb015f9ea7297015ed04d2836c11a12a7347f5ba6e2d8ebdc9d2d26e3ee2eab67009080b731e3bc5ff9ba8380446114ee2
</auth>

----- CONECTADO ----- 

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" expiration="4444444444" creation="1527101496" location="wdc" props="24" t="1528724204">
���p.���pLtŹ���
HEX:fc9800de1f702e82ffe10f06704c74c5b9c2c3c6
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1528724204" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<notification participant="5521981227587@s.whatsapp.net" notify="~milena 🌵" from="5521992436545-1528637505@g.us" offline="3" type="w:gp2" id="2355133555" t="1528638740">
<remove>
<participant jid="5521981227587@s.whatsapp.net">
</participant>
</remove>
</notification>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="5521992436545-1528637505@g.us" type="w:gp2" id="2355133555" class="notification">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<notification participant="5521981227587@s.whatsapp.net" notify="~milena 🌵" from="5521992436545-1528630307@g.us" offline="3" type="w:gp2" id="146629056" t="1528638740">
<remove>
<participant jid="5521981227587@s.whatsapp.net">
</participant>
</remove>
</notification>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="5521992436545-1528630307@g.us" type="w:gp2" id="146629056" class="notification">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<notification participant="5521981227587@s.whatsapp.net" notify="~milena 🌵" from="5521992436545-1528633405@g.us" offline="3" type="w:gp2" id="734179126" t="1528638740">
<remove>
<participant jid="5521981227587@s.whatsapp.net">
</participant>
</remove>
</notification>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="5521992436545-1528633405@g.us" type="w:gp2" id="734179126" class="notification">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<notification participant="5521981227587@s.whatsapp.net" notify="~milena 🌵" from="5521992436545-1528638606@g.us" offline="3" type="w:gp2" id="2056034800" t="1528638740">
<remove>
<participant jid="5521981227587@s.whatsapp.net">
</participant>
</remove>
</notification>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to="5521992436545-1528638606@g.us" type="w:gp2" id="2056034800" class="notification">
</ack>

`

**Comment by williamneto** [comment]
now i notice this line several times on debug
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for xxxxxxxxxxx, going to send a retry
when login via cli raise the same warning
searched around, but nothing. already deleted axolotl.db

**Comment by qeternity** [comment]
@williamneto I am receiving this same issue today, I think WhatsApp finally killed this

**Comment by pabloruan0710** [comment]
I have same problem @williamneto, the sending is normal, the receipt is locked, sometimes it returns to normal and then to again.

**Comment by iamjagjeetubhi** [comment]
Hey just install these packeges:

`sudo apt-get install build-essential autoconf libtool pkg-config python-pyrex idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-dev libssl-dev libffi6 libffi-dev
`

than apply the following commands in your YOWSUP directory:

`sudo python setup.py build
`
`sudo python setup.py install
`

Now again login and I hope it will fix your problem.

**Comment by williamneto** [comment]
Thanks @iamjagjeetubhi , but didnt solved the problem. I'ts also apearing in the log an ERROR:yowsup.layers.axolotl.layer_receive:Ignoring message with untrusted identity

@qeternity i dont think whatsapp killed because the core of the "violation" of yowsup is the possibility of automatize messageand dont read messages in another device. 

I'm thinking thats something about the encriptation, something that we are missing or some bug created with recent updates on whatsapp. Only especulating here, the way to be sure is wait for more people come here and coment

**Comment by d4rk5eed** [comment]
The same. "InvalidMessage or KeyId" on incoming but outgoing are ok. Removing ~/.yowsup/ and resetting to new password didn't help

**Comment by d4rk5eed** [comment]
You know... Eventually it was resolved on whatsapp side. Service were stormed for a couple of days and now it looks to be fine

**Comment by d4rk5eed** [comment]
pushed PR for new md5 classes https://github.com/tgalal/yowsup/pull/2518

**Comment by gauchoarg** [comment]
guys, any news on this? we are experience the same issue.

**Comment by d4rk5eed** [comment]
@gauhoarg try removing .yowsup dir under home and restart app

**Comment by lok419** [comment]
It happened after I ran the code on other computer without having the same .yowsup

**Comment by pabloruan0710** [comment]
Power should join the lifting for the problem that is ready a help, not ready, not made in the problem, has not done to problem with chaves.

**Comment by Jeronimo17** [comment]
> It happened after I ran the code on other computer without having the same .yowsup

The same thing happened to me, running on Linux without passing the Windows key database

**Comment by franquitt** [comment]
bellow is the exception code
	
	except (InvalidMessageException, InvalidKeyIdException) as e:

		logger.warning("InvalidMessage or InvalidKeyIdException for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))

		from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
		logger.info("Trying GetKeys for %s, getting keys now", encMessageProtocolEntity.getAuthor(False))
		entity = GetKeysIqProtocolEntity([encMessageProtocolEntity.getAuthor(False)])
		retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
		self.toLower(retry.toProtocolTreeNode())`

But i don't quite understand what's the purpose of entity object

**Comment by lok419** [comment]
So far I found 3 solutions.
1. Send a receipt under the exception, pretending you received the message
2. Send a random message to the sender
3. login by whatsapp apk

**Comment by hbhoyar** [comment]
@lok419 What to write in code
