### ISSUE TITLE
waiting message when use yowsup_cli demos -s command to send message in group 

### ISSUE THREAD

**Issue by wilsonZWS** [tgalal/yowsup#2519]
After looking for all the solutions to the similar issue  and test all the potential solutions. I still can't solve the problem. Many comments said we need to sync the contacts in the groups first. I guess it should be the core problem to this issue. Anybody can kindly posts me some code to sync the contacts in either yowsup or  yowsup_cli.

**Comment by gauchoarg** [comment]
same here.... any solution on this?
