### ISSUE TITLE
Cloned git from master but get old_version

### ISSUE THREAD

**Issue by nedimhx** [tgalal/yowsup#2520]
I have cloned git from master, change to android and then recompile, but still getting this
status: fail
reason: old_version

**Comment by nedimhx** [comment]
After changing to android and set this in env_android
_MD5_CLASSES = "YqW9KfOVL6cRD8aiNh8l6w=="
_VERSION = "2.18.45"

then recompile i have sucessfully get code, but after try to verify code I get 
status: fail reason: security code
and after trying about 3-4 times now i get 
status: fail
retry_after: 3600
reason: no_routes

**Comment by PurinLord** [comment]
had the same problem
just did the same thing:
```_MD5_CLASSES = "YqW9KfOVL6cRD8aiNh8l6w=="
_VERSION = "2.18.45"```
Recompile an install
and ran:
```
yowsup-cli registration --request sms --phone XXXX --cc XX --mcc XXX --mnc XXX -E android
```
after that i got the sms and did:
```
yowsup-cli registration --register <code> --phone XXX --cc XX -E android 
```
and the registration was successful

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp
