### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by lucasmarsola** [tgalal/yowsup#2524]
What am I doing wrong? I have registered my number; received the return "status: ok" with the pw.
But when I run `yowsup-cli demos -c ~/.yowsup/config -s 5514XXXXXXX 'blablabla' --debug -E android`, yowsup return `DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`.
What I have to do?!
Thanks!

**Comment by bleakas** [comment]
Same problem in all demos

**Comment by bleakas** [comment]
try this on python 3.X  . Python 2 have problems with this module

**Comment by bleakas** [comment]
or try python 2.7

**Comment by lucasmarsola** [comment]
Help me on this please... I've downloaded youwsup, changed the env, compiled again and did the registration... Then, i've run yowsup-cli demos... 
When you said chaning python version, are to run "cli" or coding some new using yowsup lib?

**Comment by bleakas** [comment]
try to create virtual machine with python 2.7(i reccomend centos 7). if not working then try python 3x. Whats your system?

**Comment by lucasmarsola** [comment]
Debian 10. But are you still running yowsup today? The "closed connection" is not happening to you?

**Comment by bleakas** [comment]
i tryed on ubuntu 17, but didnt updated version and md5, i managed to send something, but then i got banned(i think its my fault and its old version). Now i installing centos 7 and will test more, i think this lib works

**Comment by bleakas** [comment]
on ubuntu i couldnt change md5 classes in yowsup-cli

**Comment by lucasmarsola** [comment]
apparently, on debian worked... i'm using this md5: _MD5_CLASSES = "7/+9fBNI2d4/UxUiSUd+OQ==" and this version: _VERSION = "2.18.190"

**Comment by lucasmarsola** [comment]
when I said "worked", it worked for not to be banned.... I'm running and only gets "Connection Closed..."

**Comment by lucasmarsola** [comment]
`$ update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python3.6   2         auto mode
  1            /usr/bin/python2.7   1         manual mode`

Both, but now my env is set to 3.6

**Comment by diegohdk** [comment]
Same thing here if using Android env. I'm running the following:

    OS           Ubuntu 18.04
    python       2.7.15rc1
    yowsup-cli   2.0.15
    yowsup       2.5.7

With s40 it works as intended, but I guess I'll be banned 'cause I registered with Android. Is that right?

**Comment by chbinghu** [comment]
change env to  s40 could send message, android env could not.
