### ISSUE TITLE
How can I check online status of a number?

### ISSUE THREAD

**Issue by antonio9213** [tgalal/yowsup#253]
How can I check "online"/"not online" status of a number? WhatsApp still shows this info when talking to a buddy who has hidden last time seen, but I did not found any way to check online status with Yowsup.

**Comment by zeroby0** [comment]
@antonio9213 Hey! You found any solution?

**Comment by Kurill** [comment]
yowsup-cli 
comand:
/presence available

**Comment by zeroby0** [comment]
but that only gave me the following output
```
Available commands:
===================
demos, version, registration
```
Nothing else. I even tried with number after that `yowsup-cli /presence available 91xxxxx...`
Incase I was not clear, how do I get last seen or online status of a number.
Thanks :)

**Comment by jlguardi** [comment]
Use /presence subscribe jid
