### ISSUE TITLE
How to send message in java / python

### ISSUE THREAD

**Issue by rushix123** [tgalal/yowsup#2535]
How can send message to any number using this api. Where is sample code to send a message to a given number? I am not able to find this sample code here... Thanking you.

**Comment by schoerg** [comment]
You can look at `yowsup-cli` with the `-s` option.

**Comment by rushix123** [comment]
@schoerg Thank you so much. I will look over it and thanks again for the help and reply.

**Comment by tgalal** [comment]
` I am not able to find this sample code here` did you ever try take a look at the wiki?
