### ISSUE TITLE
old_veriso error 

### ISSUE THREAD

**Issue by wz343450860** [tgalal/yowsup#2536]
Hi ,  
    I tried this steps: 
1 - Change yowsup/env/env.py
Set DEFAULT = "s40" to DEFAULT = "android"

2 - Execute python setup.py install

3 - Request the WhatsApp verification code
yowsup-cli registration -r sms -C 34 -p 34XXXXXXXXX -m 214 -n 01 -E android -d

 but in the 3rd step it always return old_verison,  please help me to solve this issue.

thanks

**Comment by lucasmarsola** [comment]
1) You have to download a new whastapp apk: https://www.whatsapp.com/android/ and save the version wrote on website (ex: Version 2.18.213)
2) Run this https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py file.apk,
3) The MD5 and the version, you have to change the file yowsup/env/env_android.py:
```
_MD5_CLASSES = "NEW_VALUE"
_VERSION = "NEW_VALUE"
```

**Comment by n0a** [comment]
Latest working hash:

$ python dexMD5.py WhatsApp.apk
Version: 2.18.213
ClassesDex: fZx7nSGKnEvfjUTdr1+ohA==
