### ISSUE TITLE
Export Received Message

### ISSUE THREAD

**Issue by goparklubanic** [tgalal/yowsup#2545]
Hi. There are a lot of discussion and tutorial how to send whatsapp message using yowsup. But I can't find good discussion or tutorial about how to handle received messages, especially text messages. So I have two questions about it.
1. Which part of youwsup's core scripts that handle received / incoming message ?
2. Is there any example storing received message into a variable? I hope I can export the message ( in csv format ) after store it into a variable.

Thank's for any responses.

**Comment by franquitt** [comment]
Please read the wiki: https://github.com/tgalal/yowsup/wiki/Sample-Application

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.
