### ISSUE TITLE
Still working

### ISSUE THREAD

**Issue by traderdata** [tgalal/yowsup#2546]
Hi is this library still working?

**Comment by thikino** [comment]
I've used this library some months ago and today I'm returning to my projects with it. I'm failing to register a new number, the error message is "old_version" but I'm using yowsup-cli v2.0.15 and yowsup  v2.5.7 (what I supposed to be the newest).

So, I'm a little confused if I'm doing something wrong or if the library isn't working anymore :(

**Comment by thikino** [comment]
It's not working here, but I guess it's something that I need to set. I'm facing the "old_version" error.

I ran the script from this post: [https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py](url)
And got:
        Version: 2.18.223
        ClassesDex: PhiC6I6D3QXH67H6oPUv5A==

So I've changed the _MD5_CLASSES and _VERSION values from /yowsup-master/yowsup/env/env_android.py:

`_MD5_CLASSES = "PhiC6I6D3QXH67H6oPUv5A=="`
`_VERSION = "2.18.223"`

Than I ran:
`sudo python setup.py build`(not sure if this is necessary)
and
`sudo python setup.py install`

And finally I tried to register my number:
`yowsup-cli registration --requestcode sms --phone xxxxxxxxxxxx --cc xx --mcc xxx --mnc xx --env android`

But: 
status: fail
reason: old_version

Is there any step that I'm missing? Did you guys face this problem as well?

**Comment by thikino** [comment]
I've followed these steps and managed to work
[https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/#step2](url)

**Comment by 0rC0** [comment]
pull request  #2518 solve this

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.

**Comment by tgalal** [comment]
yes
