### ISSUE TITLE
Broadcast doesnt work for more than 1 recepient

### ISSUE THREAD

**Issue by mrtass** [tgalal/yowsup#255]
Hello all
any idea why the broadcast parameter doesnt work when sending to 2 recepients?
the numbers are comma seperated and auth success is returned...
ps : broadcast to 1 recepient works fine

**Comment by niravtrivedi** [comment]
same here. To find issue on broadcast we have extract template method of whatsapp how it combine phones,what headers it send(IF sending headers) and etc...
May be ;)

**Comment by Ankur-Jat** [comment]
Same issue when I'm using
""" /message send 91********** "testing message" """
it works fine but when I'm trying broadcast by 
""" /message broadcast 91**********,91********** "testing message" """
It didn't work!
Am I doing something wrong or its a bug?

**Comment by niravtrivedi** [comment]
broadcast is not working try in loop

**Comment by ale-rinaldi** [comment]
Working fine here. I use the normalizeJid function from the demos:
```python
def normalizeJid(self, number):
    if '@' in number:
        return number
    elif "-" in number:
        return "%s@g.us" % number
    return "%s@s.whatsapp.net" % number
```
So my list is something like:
```python
destinations=["39123456794@s.whatsapp.net", "399887654321@s.whatsapp.net"]
```
then I use
```python
outgoingMessage = BroadcastTextMessage(destinations, msgtext)
self.toLower(outgoingMessage)
```
and works like a charm!
*NOTE: * to receive a broadcast message, your contact needs to have your number in his address book!

**Comment by tobilektri** [comment]
@ale-rinaldi could you send me your full script? 
I dont get it to send a broadcast per script... 
Thanks

**Comment by jlguardi** [comment]
Already fixed long time ago!
