### ISSUE TITLE
Presence information in yowsup-cli stop comming when the numbererd of subscribed contatcs is over 40

### ISSUE THREAD

**Issue by sgheith** [tgalal/yowsup#2553]
Hi Friends

I noticed the following behavior for the presence when using yowsup-cli (and my own application as well)
1) I set my presence to available 
2) I sync contacts using /contacts sync +44XXXXX,+44YYYYYY
3) I subscribe to the above contacts by calling /presence subscribe 44XXXXX, /presence subscribe 44YYYYY etc...

If the list of contacts is 40 or less then everything works fine and I get the presence information for all the 40 contacts.

If the list of contacts is over 40 then I stop getting presence information for most (and sometimes all) contacts.
The problem occurs exactly when I subscribe the 41st number in step 3 above. Immediately I stop getting presence information for contacts.
In fact once this happen I cannot fix the issue by unsubscribing any contact to make the number less than 40. I actually cannot use the number to check presence again.
I noticed that the only way to get any contact to send me presence after that is by sending him a message.
I appreciate any help in this as it is blocking me. At least is their a way to fix the number and use it for less than 40 contacts?

Regards
Shadi

**Comment by karopass** [comment]
@sgheith I am using Chat-API and it have also same issue. I am not able to subscribe more than 35 numbers in it for presence.
Thanks

**Comment by netfiretec** [comment]
@karopass Good morning my friend, my name is Leandro and I'm talking about Brazil, do you have the new version of Chat-API?

For infoma that is discontinued in the official repository.

Anything if possible give me a ring through skype or email please.

netfiretecc@gmail.com
skype: netfiretec

**Comment by leemilun** [comment]
@sgheith did you fix this issue?

**Comment by vjyanand** [comment]
@sgheith Any luck?

**Comment by tgalal** [comment]
Works with non-mass use of subscriptions, which is what is and what will only be supported
