### ISSUE TITLE
"login":"x","status":"fail","reason":"bad_token"

### ISSUE THREAD

**Issue by CustomETB** [tgalal/yowsup#2558]
INFO:yowsup.common.http.warequest:{"login":"x","status":"fail","reason":"bad_token"}
yowsup-cli registration --requestcode sms -E android --phone x --cc xx

**Comment by MatijaNovosel** [comment]
Probably caused by the wrong MD5 token.

Check here: [#2564](https://github.com/tgalal/yowsup/issues/2564)

**Comment by dharampal123** [comment]
Did the below changes and worked for me:

Change in env.py file
set DEFAULT="android"

Change on env_android.py
_MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
_VERSION = "2.18.339"

python setup.py build

python setup.py install

yowsup-cli registration -r sms -m 000 -n 00 -p 91XXXXXXXXXX -C 91 -E android

**Comment by tomaskutaj** [comment]
just fyi still works!

**Comment by strongpapazola** [comment]
not works :(

**Comment by strongpapazola** [comment]
still bad token :(
