### ISSUE TITLE
OLD VERSION  HELP!! 

### ISSUE THREAD

**Issue by darkane188** [tgalal/yowsup#2566]

**Comment by MatijaNovosel** [comment]
Please look around the closed issues, I'll paste my solution here.
_____________________________________________________________________________________

I fixed the issue while digging around some old posts.

Go to the yowsup/env folder and find the env_android.py and env.py files.

In env.py change the line:

default = "s40" to default = "android"

In env_android.py find the the lines:

_MD5_CLASSES = "xxxxxxxxxxxxxxxxxxxxxx"
_VERSION = "x.xx.xxx"

Change them to the data found at this link, more specifically the parameters A and D.

A is for the _MD5_CLASSES and D is for the _VERSION.

For the current version to work, you need to set them up like this:

_MD5_CLASSES = "0R9F4U5fzdwVvn06wLe1JA=="
_VERSION = "2.18.255"

Hope for the best.

**Comment by darkane188** [comment]
don't work :'[

**Comment by MatijaNovosel** [comment]
Run setup.sh through bash again. Make sure you edited the env files right.

**Comment by alexvong1995** [comment]
Does it work now?

**Comment by darkane188** [comment]
NO I DONT WORK :(

**Comment by darkane188** [comment]
DON'T WORK I DON´T WHY

**Comment by alexvong1995** [comment]
I followed the instruction in https://github.com/tgalal/yowsup/issues/2564 and it works. You need to change `_MD5_CLASSES` in `yowsup/env_android.py` to the value of the key `"a"` (which is `1hYQlT8GVh7Er9XO431RoQ==` for now) and also change `_VERSION` to the value of key `"d"` (which is `2.18.266` for now). Finally we can register by running:
```
$ python3 yowsup-cli registration -E android -C $CC -p $PHONE
```
