### ISSUE TITLE
When trying to register my phonenumber in whats-app registration tool it throwing error

### ISSUE THREAD

**Issue by flextrio-gandhi** [tgalal/yowsup#2567]
After entering phonenumber in  WART Tool and when i click on  request-code it throwing below error.
 error :
 sms: {"login":"phonenumber","status":"failed","reason":"old_version"}
 voice: {"login":"phonenumber","status":"failed","reason":"old_version"}
![wart](https://user-images.githubusercontent.com/28822452/44912135-e66cb500-ad46-11e8-94ea-344420c5b7c3.PNG)

**Comment by lfdelphino** [comment]
WART uses an old protocol that whatsapp doesn't accept anymore, so it drops the connection.
I have no idea of how you found that, it's so old..

**Comment by flextrio-gandhi** [comment]
@lfdelphino can you suggest the new version

**Comment by lfdelphino** [comment]
The wiki of this project says that it's recommended to activate a new number on a real phone first, text a few people and then change to yowsup-cli after **12-24h.**
This COULD avoid getting you banned on the first message

**Comment by Chat-API18** [comment]
Hi!
Build Your WhatsApp Bot using Latest Chat-API.
-> Easy to use with PHP
-> Latest Android Environment 
-> Latest WA 2.0 Protocol
-> No More Blocking Number
Try Now on: https://chat-api.net
Thanks

**Comment by m3nu** [comment]
Changes the version and md5 helped.
