### ISSUE TITLE
ERROR:yowsup.layers.interface.interface:Stream Error type: ack

### ISSUE THREAD

**Issue by prototyqe** [tgalal/yowsup#2570]
This program close 5 min after give this error 

ERROR:yowsup.layers.interface.interface:Stream Error type: ack

**Comment by alejandroguille** [comment]
Same error

``Stream Error type: ack
{'ack': None}

**Comment by alejandroguille** [comment]
I fix this error with is

change layers/protocol_iq/protocolentities/iq_crypto.py" line 11 from
`
googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34".decode('hex'))`

to

`googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34")`

fixes the issue

**Comment by alejandroguille** [comment]
AND
```
        except (InvalidMessageException, InvalidKeyIdException) as e:
            logger.warning("InvalidMessage or InvalidKeyIdException for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))
            logger.warning("hace nada")
        #    from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
        #    logger.info("Trying GetKeys for %s, getting keys now", encMessageProtocolEntity.getAuthor(False))
        #    entity = GetKeysIqProtocolEntity([encMessageProtocolEntity.getAuthor(False)])

        #    retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
        #    self.toLower(retry.toProtocolTreeNode())
```

**Comment by gabrieru** [comment]
> AND
> 
> ```
>         except (InvalidMessageException, InvalidKeyIdException) as e:
>             logger.warning("InvalidMessage or InvalidKeyIdException for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))
>             logger.warning("hace nada")
>         #    from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
>         #    logger.info("Trying GetKeys for %s, getting keys now", encMessageProtocolEntity.getAuthor(False))
>         #    entity = GetKeysIqProtocolEntity([encMessageProtocolEntity.getAuthor(False)])
> 
>         #    retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
>         #    self.toLower(retry.toProtocolTreeNode())
> ```

i need to add it to the final of the file?

**Comment by leemilun** [comment]
I fixed it with adding axolotl layer

**Comment by alejandroguille** [comment]
> @prototyqe I fixed it with adding axolotl layer

Could you explain better?

**Comment by 0x1999** [comment]
> 
> 
> AND
> 
> ```
>         except (InvalidMessageException, InvalidKeyIdException) as e:
>             logger.warning("InvalidMessage or InvalidKeyIdException for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))
>             logger.warning("hace nada")
>         #    from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
>         #    logger.info("Trying GetKeys for %s, getting keys now", encMessageProtocolEntity.getAuthor(False))
>         #    entity = GetKeysIqProtocolEntity([encMessageProtocolEntity.getAuthor(False)])
> 
>         #    retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
>         #    self.toLower(retry.toProtocolTreeNode())
> ```

working for me

**Comment by 0x1999** [comment]
> 
> 
> I fix this error with is
> 
> change layers/protocol_iq/protocolentities/iq_crypto.py" line 11 from
> ` googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34".decode('hex'))`
> 
> to
> 
> `googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34")`
> 
> fixes the issue

great, working for me
