### ISSUE TITLE
Please Help: Latest Yowsup as at November 2018

### ISSUE THREAD

**Issue by rudie123** [tgalal/yowsup#2597]
Good day
Apologies I am a newbie. I have tried lots of different things to get Yowsup working on my Raspberry PI (Model 2B), and I just cannot get it right. old_version error thingy. Can you please guide me to get the latest version of Yowsup ? (PS do I still have to modify the env_android.py file to get the correct results without an old_version error. Thanks much appreciated.

**Comment by modcastro** [comment]
just update:

_MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
_VERSION = "2.18.339"

and setup.py install again after change.

**Comment by MikeaReyes** [comment]
> just update in env_android.py:
> 
> _MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
> _VERSION = "2.18.339"
> 
> and setup.py install again after change.

if you are absolutely right ... you also have to modify the env.py file

**Comment by matheushirota** [comment]
> just update in env_android.py:
> 
> _MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
> _VERSION = "2.18.339"
> 
> and setup.py install again after change.

WORK PERFECT! - 02 December 2018

**Comment by stanforddesi** [comment]
I just tried the above to try to get yowsup working on my ubuntu setup. I also pre-warmed by number as suggested in the wiki (sending messages, waiting 24 hours, etc.)

The requestcode step works fine but I get an old_version error when I run the register step with the code provided. What gives?

**Comment by alexvong1995** [comment]
@stanforddesi

Does the instruction in #2566 work for you?

**Comment by dharampal123** [comment]
Did the below changes and worked for me:

1. Change in env.py file
set DEFAULT="android"

2. Change on env_android.py
_MD5_CLASSES = "DAPy33TbNMg0Yuplp2II0A=="
_VERSION = "2.18.339"
 
3. python setup.py build

4. python setup.py install

5. yowsup-cli registration -r sms -m 000 -n 00 -p 91XXXXXXXXXX -C 91 -E android
