### ISSUE TITLE
Not working with Python 3.7+ | async keyword error

### ISSUE THREAD

**Issue by jafrancov** [tgalal/yowsup#2605]
I got this error:
```
  File "/Users/jafrancov/dev/python/whatsapp-bot/lib/python3.7/site-packages/yowsup/layers/protocol_media/mediauploader.py", line 12
    def __init__(self, jid, accountJid, sourcePath, uploadUrl, resumeOffset = 0, successClbk = None, errorClbk = None, progressCallback = None, async = True):
                                                                                                                                                    ^
SyntaxError: invalid syntax
```
Researching I found out that with Python 3.7+ the word `async` is a keyword, https://docs.python.org/3/reference/lexical_analysis.html#keywords and it is used on the core of yowsup.

**Comment by kuarad** [comment]
yowsup was written with previous python version. you can do a new branch for you with this correction or search previous issues in this repo.

**Comment by alexvong1995** [comment]
I run into the same problem just now. PR #2579 (plus a trivial change) fixes it for me.

**Comment by gascarcella** [comment]
Im having the same issue

**Comment by tgalal** [comment]
fixed
