### ISSUE TITLE
Stream error Ack : None

### ISSUE THREAD

**Issue by homenisi** [tgalal/yowsup#2615]
Hi, I've problem with the error in the title.
It happens every time after I receive 9 iq events. I've tried to implement all the ack. I've used either the sample application either the CLI demos with the same result.
Please, can you give me any hints how to solve it? Or perhaps can you give me a working example that only handle this type of problem?
Thank you!

**Comment by alexvong1995** [comment]
See #2570. I haven't tested it though. I may test it later when I have time.
