### ISSUE TITLE
Bug report - Yowsup no longer receiving messages

### ISSUE THREAD

**Issue by kaykyr** [tgalal/yowsup#2623]
After sent or receive some messages the encryption key changes. Now I cannot receive more notifications/messages, but I can send messages without any problem.

How fix this trouble? Thanks.

**Comment by modcastro** [comment]
The same here. But receive whith using /L after login. 

WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for...

**Comment by modcastro** [comment]
I try delete all info and register the number again. But don't work.
Last try register again in WhatsApp App in mobile and back here.

news... please update...
