### ISSUE TITLE
Is it legal to use Yowsup for internal apps?

### ISSUE THREAD

**Issue by taggy** [tgalal/yowsup#2625]
**Is it legal to use Yoswup for internal apps?**
Hello, I'm planning to use Yowsup for strictly internal bots. Does that violate whatsapp terms? or is it considered OK. It would be super useful if someone can clarify

**Comment by Laur121** [comment]
"whatsapp terms" are not laws to make things illegal. You have to break the law in order to be illegal.
However, yowsup is forbidden according to whatsapp terms.
