### ISSUE TITLE
Cannot register 

### ISSUE THREAD

**Issue by MelanX** [tgalal/yowsup#2626]
Hi :) I just tried to register my Number with Yowsup. I'm using this number with my mobile phone. When I tried to register this was (the important part from the output) shown:
______________________________________________
INFO:yowsup.common.http.warequest:{"login":"49XXXXXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 49XXXXXXXXXXX
____________________________________________

Do you know whats wrong? Do you need more information to reproduce this?

**Comment by alexvong1995** [comment]
Please see instruction in #2566 and #2564.
