### ISSUE TITLE
Keep getting :general: Disconnected: Connection Closed

### ISSUE THREAD

**Issue by taggy** [tgalal/yowsup#2627]
**Unable to login to whatsapp*
I have successfully registered using env android but /L keeps throwing the same error.
**general: Disconnected: Connection Closed**

What am i missing? Any help is appreciated

**Comment by Zebreus** [comment]
Have you tried using env S40 for logging in?

**Comment by taggy** [comment]
Can you help me on how do i do that?
I created my config using -env android . I should re-register?

**Comment by taggy** [comment]
Works. Thank you so much!

**Comment by ersinayaz** [comment]
Hi @taggy,
how do you solve the problem?
i am having the same problem, help pls.
