### ISSUE TITLE
[self-promotion] fork with minimal maintenance (should work out of the box, only support command line client, python 3 or later)

### ISSUE THREAD

**Issue by alexvong1995** [tgalal/yowsup#2631]
**Is your feature request related to a problem? Please describe.**
The master branch doesn't work out of the box.

**Describe the solution you'd like**
A fork with minimal maintenance which should work out of the box:
https://notabug.org/alexvong1995/yowsup-maint

**Describe alternatives you've considered**
The master branch here works out of the box again or a better fork than mine.

**Additional context**
Hello everyone,

Firstly, I agree what the OP said in #2630. This is indeed a wonderful project
and I thanks Tagal et al. for making this possible!

Personally, I dislike whatapps because of reasons mentioned by falbani in
#1516. However, I need to use it for my work and this project comes to rescue -
I don't need to install the whatapps blob!

We all know that there has been slowdown in the development and this is okay.
Everyone is busy sometimes. The real issue for me is that the master branch
doesn't work out of the box. One has to look at the error message and locate
the right PR or to fix the error themselves.

In fact, this is what I've been doing for a while now, on a fork with minimal
maintenance: https://notabug.org/alexvong1995/yowsup-maint I've been dogfooding
it for several months and it works provided that some conditions are met (see
below). I've also made a yowsup-mode for Emacs which will be released when it's
ready. Since this is F/LOSS, I hope to share this to you.

Please tell me if you've any suggestions / bug reports / PRs / new features /
better forks in https://notabug.org/alexvong1995/yowsup-maint since I know
almost nothing about networking and all the solutions I found are from here /
stackoverflow / basic python. Also, I am happy to send back my improvements
here if they are needed.

By the way, since python 2 is going [EOL](https://pythonclock.org/) on 2020, I
see no point in maintaining the python 2 version anymore. Everyone please
switch to the python 3 version!

To further reduce maintenance burden, I remove the option of using the echo /
send client. They aren't very useful to begin with and their functionalities
can easily to added to the command line client.

Happy New Year!
Alex

Conditions for making yowsup works based on my experience
=========================================================
1. Make sure your internet connection is stable. `ping` should give a low
latency.

2. Don't message too quickly. A rule of thumb is to send a message after
receiving:
```
ID: x
Type: result
from: xxxxxxxxxxx@s.whatsapp.net
```

3. Make sure your message isn't too long. A rule of thumb is that
`/message send xxxxxxxxxxx ...` should not span more than one line (80
characters).

**Comment by vnoxygen** [comment]
Why are you not hosting the repo on Github?

**Comment by alexvong1995** [comment]
Vnoxygen Spike <notifications@github.com> writes:

> Why are you not hosting the repo on Github?
>
In general, I try to support community projects if I can, and notabug is
such a project. I made the switch back in late 2016.
In 2018, the microsoft acquisition of github
https://www.dailydot.com/debug/microsoft-github-gitlab/
made many worried about the future of github, and they as well switched
to gitlab / notabug / ...

These are some possible reasons why you may not want to host the repo on
github. If people find this too inconvenient, gitlab maybe is a good
middle ground.

**Comment by modcastro** [comment]
Hi @alexvong1995 I see your update only relations to save images. 

So yowsup stopped receive messages in #2623 , do you have the same in your side ?

**Comment by alexvong1995** [comment]
Hi modcastro,

Can you please post the complete error message?

Sometimes I get the error:
> WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for xxxxxxxx, going to send a retry
where xxxxxxxx is a phone #

The retry sometimes works and sometimes doesn't. The way I deal with it
is mentioned in "Conditions for making yowsup works based on my
experience" section above. But I don't know if the error I got is the
same as yours, because I can still receive messages.

**Comment by ciclanoio** [comment]
@alexvong1995   Only this in terminal -y

[offline]:/L
Auth: Logged in!
[connected]:WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 55xxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 55xxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 55xxxx, going to send a retry
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 55xxxx, going to send a retry

**And if in another number if I receive a sticker image the code broken:**

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "run.py", line 42, in Bot
    stack.loop(timeout = 0.5, discrete = 0.5)
  File "/Library/Python/2.7/site-packages/yowsup/stacks/yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/Library/Python/2.7/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/Library/Python/2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/Library/Python/2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 204, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled

**Comment by alexvong1995** [comment]
Hello Ciclano,

From your stack trace, it appears you're running python 2. Can you try
running yowsup with python 3 with the following command?

> python3 ./yowsup-cli demos --config CONFIG --yowsup

where CONFIG is the location of your config file

**Comment by alexvong1995** [comment]
@modcastro

I think the problem is that you're running the echo client (-e) instead
of the command line client (-y). I don't think the echo client works at
the moment. You'll have to use the command line client.

To implement auto-reply in the command line client, you'll have to
modify the
> onMessage(self, message)
function in the
> ./yowsup/demos/cli/layer.py
file.

E.g. In my fork,
> fix_encoding(messageOut)
is the message received and
> message.getFrom()
is the sender of the message.
So to send back the message received, write:
> message_send(message.getFrom(), fix_encoding(messageOut))

Be careful though, I haven't test it! Also, auto-reply may get you
banned. If I were really implementing it, I would add some random and
sufficiently long delay between replies to reduce the chance of getting
banned. Also, I would use some other IP instead of my home IP to
register a new number and to test it.

Finally, I decide to remove the option of using the echo / send client
from my fork. They do not work / not very useful and their
functionalities can easily be added to the command line client. I would
rather not have to maintain them.

**Comment by modcastro** [comment]
Thanks @alexvong1995  I my case, I use your REPO and my script:

    def ReceiveMessage(self):
            rec = dict((k, self.messages.pop(k)) for k in list(self.messages.keys()))
            logger.info(json.dumps(rec))

And Use Native Yowsup Handling on layer_receive.py:

  ##### handling received data #####

    def onMessage(self, protocolTreeNode):
        encNode = protocolTreeNode.getChild("enc")
        if encNode:
            self.handleEncMessage(protocolTreeNode)
        else:
            self.toUpper(protocolTreeNode)


    def handleEncMessage(self, node):
        encMessageProtocolEntity = EncryptedMessageProtocolEntity.fromProtocolTreeNode(node)
        isGroup =  node["participant"] is not None
        senderJid = node["participant"] if isGroup else node["from"]
        if node.getChild("enc")["v"] == "2" and node["from"] not in self.v2Jids:
            self.v2Jids.append(node["from"])
        try:
            if encMessageProtocolEntity.getEnc(EncProtocolEntity.TYPE_PKMSG):
                self.handlePreKeyWhisperMessage(node)
            elif encMessageProtocolEntity.getEnc(EncProtocolEntity.TYPE_MSG):
                self.handleWhisperMessage(node)
            if encMessageProtocolEntity.getEnc(EncProtocolEntity.TYPE_SKMSG):
                self.handleSenderKeyMessage(node)
        **except (InvalidMessageException, InvalidKeyIdException) as e:**
            logger.warning("InvalidMessage or KeyId for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))
            retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
            self.toLower(retry.toProtocolTreeNode())
        except NoSessionException as e:
            logger.warning("No session for %s, getting their keys now", encMessageProtocolEntity.getAuthor(False))

            conversationIdentifier = (node["from"], node["participant"])


Stopped on: InvalidMessageException, InvalidKeyIdException

I try use your fix_encode but return the same.   I don't use echo command.

The most crazy here is for the new numbers work perfect. But for the more active number I have the problem with the keys.

If is possible, add in skype:   mauricio@ciclano.io 

Thanks Brother
