### ISSUE TITLE
¿How actual WHATSAPP blacklist?

### ISSUE THREAD

**Issue by jerco3000** [tgalal/yowsup#2637]
Hi, I'm sorry post here, but see many people have the same problems I do.

Currently someone has experience in which variables it takes whatsapp for blocking?

The first thing that occurred to me, with IP blocking is to use VPN to hide me, the detail is that even then, after 3 blocked CHIPs and changing to another VPN server, they blocked 4 instantly.

I think there are other variables that take into account for blocking, mac address, IMEI + IP or something else.

Someone can tell me where there is a forum to share these types of questions and experiences in this regard.

Thank you.

**Comment by devalexanderdaza** [comment]
Duplicate post... Delete this and wait responses in the other!
