### ISSUE TITLE
 Variables WhatsApp uses to ban IP

### ISSUE THREAD

**Issue by jerco3000** [tgalal/yowsup#2638]
Hi, I'm sorry post here, but see many people have the same problems I do.

Currently someone has experience in which variables it takes whatsapp for blocking?

The first thing that occurred to me, with IP blocking is to use VPN to hide me, the detail is that even then, after 3 blocked CHIPs and changing to another VPN server, they blocked 4 instantly.

I think there are other variables that take into account for blocking, mac address, IMEI + IP or something else.

Someone can tell me where there is a forum to share these types of questions and experiences in this regard.

Thank you.

**Comment by sanjeetunited100** [comment]
WHy duta.in bot is working, does anyone have any Idea?

**Comment by brunovribeiro** [comment]
@jerco3000 Is Yowsup working out there?

**Comment by alexvong1995** [comment]
@brunovribeiro No, it is not. See #2635.

**Comment by ivanber77** [comment]
Close issue. The problem is  [https://github.com/tgalal/yowsup/issues/2635](url)
