### ISSUE TITLE
Registrationscodeanforderung schlegt fehl.

### ISSUE THREAD

**Issue by Bigwin002** [tgalal/yowsup#2645]
Ich kann keine Registrierungscode-Anfrage absetzten.

python3 yowsup-cli registration --requestcode sms --phone 4177xxxxxx --cc 41

danach kommt:

INFO:yowsup.common.http.warequest:b'{"login":"4177xxxxxx","status":"fail","reason":"old_version"}\n'
reason: b'old_version'
login: b'4177xxxxxx'
status: b'fail'

Alles auch schon neu installiert und das System updatet.

Kann mir da jemand helfen?

**Comment by schoerg** [comment]
>reason: b'old_version'

**Comment by topteamc** [comment]
dead project

**Comment by tgalal** [comment]
see last comment https://github.com/tgalal/yowsup/issues/2635

**Comment by tgalal** [comment]
fixed
