### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by redrux** [tgalal/yowsup#2665]
Hello,

I'm using latest version of yowsup. Trying to connect whatsapp:

Image: https://i.imgur.com/YBjk28L.png

**With this command:**
 yowsup-cli demos --yowsup --config config --debug -E android

**With this config file:**
phone=XX53XX72X3X2
password=yHYtpsr4o8XXXXXXmXxbK8=

I sent verification code and got the password. I don't know why is not working. Anybody can explain me how it works?

By the way.. Thank you @tgalal for this great repository!

**Comment by tgalal** [comment]
picture shows yowsup2, you to update to yowsup 3 and register again
