### ISSUE TITLE
About Config Credentials

### ISSUE THREAD

**Issue by redrux** [tgalal/yowsup#2667]
When i try to log in with CLI

There are some errors:
2019-04-23 23:04:06,202 yowsup.layers.network.dispatcher.dispatcher_socket - 'NoneType' object has no attribute 'edge_routing_info'

like edge_routing_info, What is this? Can you publish an example config file? And which structure, is it needed to be JSON? @tgalal

**Comment by jowiemann** [comment]
Hello,

I was able to start and finish registration with a config file with following content:
```
cc=49
phone=49xxxxxxxxxxxx
```

The config file has to be named without extention. I namd it "yowsup"

At the end of registration you will get some informations including a json block. I have put this block in a new config file named yowsup.json.

Jörg

**Comment by redrux** [comment]
@jowiemann Thank you so much jowiemann so where are you keeping your password? And did you tried to login with CLI?

**Comment by jowiemann** [comment]
Password is not longer needed. As I mentioned, in the replay when finishing Registration al informtion ar stored in the displyed json block. It Looks like:

```
{
    "__version__": 1,
    "cc": "49",
    "client_static_keypair": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "expid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "fdid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "mcc": "000",
    "mnc": "000",
    "phone": "49xxxxxxxxxxxx",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

```

**Comment by redrux** [comment]
Tried with this code:

yowsup-cli registration --register XXXXX --phone 85XXXXXXXXX --cc 85 -E android

 when i try to validate my account with request code i got this error.

```
yowsup-cli  v2.0.15
yowsup      v3.0.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/Users/AAAA/.local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.7', 'yowsup-cli')
  File "/Users/AAAA/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/AAAA/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/Users/AAAA/.pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup2-2.5.7-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 357, in <module>
    if not parser.process():
  File "/Users/AAAA/.pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup2-2.5.7-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 191, in process
    self.handleRegister(self.args["register"], config)
  File "/Users/AAAA/.pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup2-2.5.7-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 215, in handleRegister
    req = WARegRequest(config["cc"], config["phone"], code)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by luisaugustos** [comment]
your yowsup-cli  was on v2.0.15 try v3.

**Comment by redrux** [comment]
I'm pretty sure using latest version. I removed all python environment and pulled repository.

**Comment by jowiemann** [comment]
Give it a try without: -E android

**Comment by tgalal** [comment]
If you register with yowsup-cli 3, you don't need to explicitly specify a config file anymore. The json output during registration is already stored in yowsup's config directory (on linux that would be `~/.config/yowsup` ) and will be used the next time you specify only a phone number matching that config. Therefore you don't need to worry about edge_routing_info and other stuff the config contains.

@redrux your logs are full of "yowsup2-2.5.7"
