### ISSUE TITLE
error in Registration  (missing)

### ISSUE THREAD

**Issue by manufuentescr** [tgalal/yowsup#267]
I try to register an account, but I get the following error

{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.15 S40Version/14.26 Device/Nokia302'}
cc=xxx&in=xxxxxxxx&id=d41d8cd98f00b204e9800998ecf8427e&code=123456
Opening connection to v.whatsapp.net
Sending GET request to /v2/register?cc=xxx&in=xxxxxxxx&id=d41d8cd98f00b204e9800998ecf8427e&code=960298
WARegRequest:   {"status":"fail","reason":"missing"}

status: fail
reason: missing

anyone can help me? 

seems to be missing a parameter
##

**Comment by EralpB** [comment]
same problem.. what's missing?

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.
