### ISSUE TITLE
Waiting for this message. This may take a while.

### ISSUE THREAD

**Issue by Sharissa90** [tgalal/yowsup#2680]
![image](https://user-images.githubusercontent.com/49893897/56675532-83210000-66e6-11e9-92c5-9cc331dc9ad8.png)

when I send message to group this issue show up.. in the past we fix this by update python-axolotl but I check python-axolotl this up to date version but this issue come up.. please assist me to resolve this issue..

**Comment by shekar3110a** [comment]
Hi, Manage to get this working by creating the group from the yowsup command line, the messages are getting delivered, however when you create the group outside of yowsup it doesn't work. Something to do with key sync when created outside i guess.
