### ISSUE TITLE
Send demo does not properly shutdown

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2681]
fhem@raspberrypi:~/yowsup-master$ yowsup-cli demos --config-phone 49xxxxxxxxxx  -s 49xxxxxxxxxx "Das ist ein Test"
yowsup-cli  v3.0.0
yowsup      v3.0.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2019-04-24 21:12:19,205 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
I 2019-04-24 21:12:23,115 yowsup.axolotl.manager - Loaded 0 unsent prekeys
W 2019-04-24 21:12:24,972 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
I 2019-04-24 21:12:25,307 yowsup.demos.sendclient.layer - Message sent

Yowsdown
Exception in thread YowPingThread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/protocol_iq/layer.py", line 98, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
fhem@raspberrypi:~/yowsup-master$

**Comment by tgalal** [comment]
fixed in [v3.1.0](https://github.com/tgalal/yowsup/releases/tag/v3.1.0)
