### ISSUE TITLE
Version 3.1.0: 'NoneType' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2687]
fhem@raspberrypi:~$ yowsup-cli demos --config-phone 49xxxxxxxxxx  -s 49xxxxxxxxxx                           2 "Das ist ein Test"
yowsup-cli  v3.0.0
yowsup      v3.1.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2019-04-25 08:58:02,739 yowsup.layers.network.layer - Connecting to e12.whatsa                           pp.net:443
I 2019-04-25 08:58:06,704 yowsup.axolotl.manager - Loaded 0 unsent prekeys
W 2019-04-25 08:58:09,232 yowsup.layers.protocol_ib.layer - ignoring edge_routin                           g ib node for now
I 2019-04-25 08:58:09,608 yowsup.demos.sendclient.layer - Message sent

Yowsdown
Exception in thread YowPingThread-2 (most likely raised during interpreter shutd                           own):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/lay                           ers/protocol_iq/layer.py", line 98, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
fhem@raspberrypi:~$ exit

**Comment by tgalal** [comment]
also #839

**Comment by jowiemann** [comment]
Seems to be fixed with 3.2.0
