### ISSUE TITLE
No such prekeyRecord issue

### ISSUE THREAD

**Issue by Sharissa90** [tgalal/yowsup#2692]
Hi, I get this problem below the debug result

W 2019-04-26 08:29:56,045 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
D 2019-04-26 08:29:56,046 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1556242xxx" type="groups">
</dirty>
</ib>

D 2019-04-26 08:29:56,061 yowsup.layers.logger.layer - rx:
<message id="2ABEE0BD739F1DF611356D0BDDXXXXX" notify="xxxxxxxxxx" offline="9" from="xxxxxxxxxx@s.whatsapp.net" t="15562xxxxxx" type="text">
<enc type="pkmsg" v="2">
e?\x9e\xa0w\xf4Z\xd0g\xcf8\xc1\x9e\xfd\xfa3|v\xb0"AOxce\xac\xd1\xaa\xf3\x8f\xcd\xca#h
                                                    \xf5\xd9'\x9b."R3
!V4RI\xdd\xdd\xde\xa5\xbf#W\xa1\x89\x9eFC,      >K\xb0\x82\x8f\x95pD\xfci\xd5zz-xac\xd4\xd3c\xc9\x98I\xf\x9e\x96\xbdx\xff\xc9:s\x9c3\xcd\x90-;\x91\xfam\xe0(\xe3\xad\xae]0
HEX3:b'3308a087fa05122105f96cb7273efff258b67c799ec6148ece12acd1aaf38fcdca23680d816cf860041a2105410d6513133f9ea077f45ad067cf38c19efdfa337c76b022414f0bf5d9279b2e2252330a2105561934061d5249dddddea5bf2357a100899e1946432c093e4b0fb0828f957044101b1800222065fc69d57a7a2d1bacd4d30763c9984905f51b3a089e96bd78ffc93a739c33cd902d3b9103fa6de028e3adae5d3000'
</enc>
</message>

D 2019-04-26 08:29:56,062 yowsup.axolotl.manager - decrypt_pkmsg(senderid=xxxxxxxxxx, data=(omitted), unpad=True)
D 2019-04-26 08:29:56,062 yowsup.axolotl.manager - get_session_cipher(recipientid=xxxxxxxxxx)
E 2019-04-26 08:29:56,063 yowsup.layers.network.dispatcher.dispatcher_socket - No such prekeyRecord!
D 2019-04-26 08:29:56,063 yowsup.layers.network.layer - Disconnected
D 2019-04-26 08:29:56,064 yowsup.layers.protocol_iq.layer - stopping ping thread
D 2019-04-26 08:29:56,165 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-04-26 08:29:56,237 yowsup.layers.protocol_iq.layer - YowPingThread-2 - ping thread stopped

how I can ignore prekeyRecord and send receipt?

**Comment by tgalal** [comment]
is this different from #2672 that you also opened?

**Comment by Sharissa90** [comment]
#2672 using v3.0.0 this using v3.1.0 thank you for your response...

**Comment by tgalal** [comment]
duplicate #2672
