### ISSUE TITLE
[Error 9] Bad file description

### ISSUE THREAD

**Issue by magnussolution** [tgalal/yowsup#2698]
hi. really thanks for version 3.

I install and register a new phonenumber.

add in whats.conf file

cc=55
phone=555198058XXXX

yowsup-cli demos --yowsup --config /usr/src/yowsup/whats.conf 

general: Login Failed, reason: 401
E 2019-04-27 07:59:39,288 yowsup.layers.network.dispatcher.dispatcher_socket - [Errno 9] Bad file descriptor

I see the configuration now is in /root/.config/yowsup/5551980587597/config.json

**Comment by tgalal** [comment]
"Login Failed, reason 401", try register again to check if your number got blocked

**Comment by magnussolution** [comment]
sorry, the number was worn
