### ISSUE TITLE
running run.py:  'NoneType' object has no attribute 'edge_routing_info'

### ISSUE THREAD

**Issue by iy7u6le2** [tgalal/yowsup#2700]
Is there a way i can start the new yowsup version with my old config file which is in the following format?

cc=49
phone=49XXXXXXXXXX
password=XXXXXXXXXXXXXXXXXXXX=

I have no access to the phone number so i cannot register it again.

Thanks in advance

**Comment by ignertic** [comment]
No

Whatsapp changed their protocols hence that method is deprecated 
/close
