### ISSUE TITLE
yowsup.layers.network.dispatcher.dispatcher_socket - 'NoneType' object has no attribute '__getitem__' 

### ISSUE THREAD

**Issue by Wedmal** [tgalal/yowsup#2701]
Call:
[root@localhost /]# yowsup-cli demos -e --config-phone 7983******* 

> Copyright (c) 2012-2019 Tarek Galal                                                                                                                                       
> http://www.openwhatsapp.org                                                                                                                                               
>                                                                 
> This software is provided free of charge. Copying and redistribution is                                                                                                   
> encouraged.                                                                                                                                                               
>                                                                                                                                                                           
> If you appreciate this software and you would like to support future                                                                                                      
> development please consider donating:                                                                                                                                     
> http://openwhatsapp.org/yowsup/donate   

> I 2019-04-29 05:03:55,490 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443                                                                                
> I 2019-04-29 05:03:55,721 yowsup.axolotl.manager - Generating 812 prekeys                                                                                                 
> I 2019-04-29 05:03:56,134 yowsup.axolotl.manager - Storing 812 prekeys                                                                                                    
> I 2019-04-29 05:04:43,491 yowsup.axolotl.manager - Loaded 812 unsent prekeys                                                                                              
> W 2019-04-29 05:04:44,661 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now                                                                         
> W 2019-04-29 05:04:44,662 yowsup.layers.protocol_ib.layer - ignoring attestation ib node for now                                                                          
> E 2019-04-29 05:04:45,826 yowsup.layers.network.dispatcher.dispatcher_socket - [Errno 9] Bad file descriptor                                                              
> I 2019-04-29 05:04:45,827 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443                                                                                
> I 2019-04-29 05:04:46,058 yowsup.axolotl.manager - Loaded 0 unsent prekeys                                                                                                
> W 2019-04-29 05:04:46,592 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now                                                                         
> E 2019-04-29 05:04:46,598 yowsup.layers.network.dispatcher.dispatcher_socket - 'NoneType' object has no attribute '__getitem__'   

Strange. Just yesterday, it worked, but not now. I can not determine the cause of the error. Reinstalling did not help
This number is not blocked, and messages are successfully sent from it. I tried to re-register, but it gave no result
My inner ip server - 192.168.100.100

**Comment by tgalal** [comment]
yowsup version, python version, run with '-d' for debug.

**Comment by Wedmal** [comment]
Python 2.7.5  
----
yowsup-cli v3.0.0                                                                                                                                                         
Using yowsup v3.1.0    
----

> D 2019-04-29 09:53:17,524 yowsup.stacks.yowstack - Initializing stack                                                                                                     
> D 2019-04-29 09:53:17,524 yowsup.stacks.yowstack - Constructed Network Layer                                                                                              
> D 2019-04-29 09:53:17,525 yowsup.stacks.yowstack - Constructed Noise Segments Layer                                                                                       
> D 2019-04-29 09:53:17,527 yowsup.stacks.yowstack - Constructed Noise Layer                                                                                                
> D 2019-04-29 09:53:17,527 yowsup.stacks.yowstack - Constructed Coder Layer                                                                                                
> D 2019-04-29 09:53:17,527 yowsup.stacks.yowstack - Constructed Logger Layer                                                                                               
> D 2019-04-29 09:53:17,528 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fee7bbc4dd0>                         
> D 2019-04-29 09:53:17,528 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fee7bba98d0>         
> D 2019-04-29 09:53:17,528 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - 
> notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer                                          
> D 2019-04-29 09:53:17,529 yowsup.stacks.yowstack - Constructed Interface Layer                                                                                            
> D 2019-04-29 09:53:17,529 yowsup.layers.network.layer - Created socket dispatcher                                                                                         
> I 2019-04-29 09:53:17,529 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443                                                                                 
> D 2019-04-29 09:53:17,756 yowsup.layers.network.layer - Connected                                                                                                         
> D 2019-04-29 09:53:17,756 yowsup.axolotl.factory - get_manager(username=79833924478)                                                                                      
> D 2019-04-29 09:53:17,758 yowsup.axolotl.manager - Initialized AxolotlManager [username=79833924478, db=/root/.config/yowsup/79833924478/axolotl.db]                      
> D 2019-04-29 09:53:17,758 yowsup.axolotl.manager - level_prekeys(force=False)                                                                                             
> D 2019-04-29 09:53:17,768 yowsup.axolotl.manager - len(pending_prekeys) = 812                                                                                             
> D 2019-04-29 09:53:17,768 yowsup.axolotl.manager - load_unsent_prekeys                                                                                                    
> I 2019-04-29 09:53:17,769 yowsup.axolotl.manager - Loaded 0 unsent prekeys                                                                                                
> D 2019-04-29 09:53:17,769 yowsup.axolotl.factory - get_manager(username=79833924478)                                                                                      
> D 2019-04-29 09:53:17,770 yowsup.axolotl.manager - Initialized AxolotlManager [username=79833924478, db=/root/.config/yowsup/79833924478/axolotl.db]                      
> D 2019-04-29 09:53:17,771 yowsup.axolotl.factory - get_manager(username=79833924478)                                                                                      
> D 2019-04-29 09:53:17,772 yowsup.axolotl.manager - Initialized AxolotlManager [username=79833924478, db=/root/.config/yowsup/79833924478/axolotl.db]                      
> D 2019-04-29 09:53:17,772 yowsup.layers.noise.layer - Received auth event                                                                                                 
> D 2019-04-29 09:53:17,772 yowsup.config.manager - Detecting config for username=79833924478, dir=/root/.config/yowsup/79833924478/                                        
> D 2019-04-29 09:53:17,772 yowsup.config.manager - Trying /root/.config/yowsup/79833924478/config.json                                                                     
> D 2019-04-29 09:53:17,772 yowsup.config.manager - load_path(path=/root/.config/yowsup/79833924478/config.json)                                                            
> D 2019-04-29 09:53:17,773 yowsup.config.manager - Detected config type: json                                                                                              
> D 2019-04-29 09:53:17,773 yowsup.config.manager - Opening config for reading                                                                                              
> D 2019-04-29 09:53:17,773 yowsup.config.manager - Loading config                                                                                                          
> D 2019-04-29 09:53:17,774 yowsup.env.env - Env not set, setting it to android                                                                                             
> D 2019-04-29 09:53:17,774 yowsup.env.env - Current env changed to android                                                                                                 
> D 2019-04-29 09:53:17,774 yowsup.layers.noise.layer - Performing handshake [username= 79833924478, passive=False]                                                         
> D 2019-04-29 09:53:17,774 yowsup.layers.noise.layer - Starting handshake worker                                                                                           
> D 2019-04-29 09:53:18,264 yowsup.config.manager - Detecting config for username=79833924478, dir=/root/.config/yowsup/79833924478/                                        
> D 2019-04-29 09:53:18,265 yowsup.config.manager - Trying /root/.config/yowsup/79833924478/config.json                                                                     
> D 2019-04-29 09:53:18,265 yowsup.config.manager - load_path(path=/root/.config/yowsup/79833924478/config.json)                                                            
> D 2019-04-29 09:53:18,265 yowsup.config.manager - Detected config type: json                                                                                              
> D 2019-04-29 09:53:18,265 yowsup.config.manager - Opening config for reading                                                                                              
> D 2019-04-29 09:53:18,265 yowsup.config.manager - Loading config                                                                                                          
> D 2019-04-29 09:53:18,266 yowsup.common.tools - writePhoneData(phone=79833924478, name=config.json, val=[omitted])                                                        
> D 2019-04-29 09:53:18,266 yowsup.common.tools - Writing /root/.config/yowsup/79833924478/config.json                                                                      
> D 2019-04-29 09:53:18,268 yowsup.layers.logger.layer - rx:                                                                                                                
> <success location="atn" creation="1552926837" t="1556520798" props="25">                                                                                                  
> </success>                                                                                                                                                                
>                                                                                                                                                                           
> D 2019-04-29 09:53:18,268 yowsup.layers.protocol_iq.layer - starting ping thread.                                                                                         
> D 2019-04-29 09:53:18,281 yowsup.layers.logger.layer - rx:                                                                                                                
> <ib from="s.whatsapp.net">                                                                                                                                                
> <edge_routing>                                                                                                                                                            
> <routing_info>                                                                                                                                                            
>                                                                                                                                                                          
> HEX:08050802                                                                                                                                                              
> </routing_info>                                                                                                                                                           
> <dns_domain>                                                                                                                                                              
> fb                                                                                                                                                                        
> HEX:6662                                                                                                                                                                  
> </dns_domain>                                                                                                                                                             
> </edge_routing>                                                                                                                                                           
> </ib>                                                                                                                                                                     
>                                                                                                                                                                           
> W 2019-04-29 09:53:18,282 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now                                                                         
> D 2019-04-29 09:53:18,282 yowsup.layers.logger.layer - rx:                                                                                                                
> <ib from="s.whatsapp.net">                                                                                                                                                
> <dirty timestamp="1556520798" type="groups">                                                                                                                              
> </dirty>                                                                                                                                                                  
> </ib>                                                                                                                                                                     
>                                                                                                                                             

                              
D 2019-04-29 09:53:18,289 yowsup.layers.logger.layer - rx:                                                                                                                
<notification type="encrypt" offline="7" from="### 79237484080@s.whatsapp.net" id="2400371822" t="1556500320">                                                                

> <identity>                                                                                                                                                                
> </identity>                                                                                                                                                               
> </notification>                                                                                                                                                           
>                                                                                                                                                                           
> E 2019-04-29 09:53:18,289 yowsup.layers.network.dispatcher.dispatcher_socket - 'NoneType' object has no attribute '__getitem__'                                           
> D 2019-04-29 09:53:18,289 yowsup.layers.network.layer - Disconnected                                                                                                      
> D 2019-04-29 09:53:18,290 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False                                                                     
> D 2019-04-29 09:53:18,290 yowsup.layers.protocol_iq.layer - stopping ping thread                                                                                          
> D 2019-04-29 09:53:19,270 yowsup.layers.protocol_iq.layer - YowPingThread-2 - ping thread stopped

**Comment by Wedmal** [comment]
The new number works as it should. All old numbers refuse. Apparently, these phone numbers are somehow blocked, but not fully. Is it possible?

**Comment by stv0g** [comment]
Try to delete your Yowsup config files.

**Comment by Wedmal** [comment]
I clear
/root/.config/yowsup
but there is no result. On another computer, a new installation causes the same problem. Apparently, the problem is on the server side and not on the client.

**Comment by Wedmal** [comment]
After the update, this problem turned into a
>  InvalidMessage or KeyId for 79237484080, going to send a retry

Inside the axolotl.db file there is no necessary record in the identities and sessions table for the number from which I listen to messages.

**Comment by tgalal** [comment]
great, invalidmessage warning is not a problem, fixed
