### ISSUE TITLE
Unable to get password

### ISSUE THREAD

**Issue by nitinjs** [tgalal/yowsup#2704]
Hi,

I requested code with following command
`python yowsup-cli registration --requestcode sms --phone 918X8X25253X --cc 91 --mcc 405 --mnc 799 -E android`

I recieved the code,
then with following command I try to get the password
`python yowsup-cli registration --register 473-586 --phone 918X8X25253X --cc 91 -E android`

but instead of getting password I get following response:
```
I 2019-04-30 21:45:12,345 yowsup.common.http.warequest - b'{"status":"ok","login":"918080252530","type":"existing","edge_routing_info":"CAIIBQ==","chat_dns_domain":"fb","security_code_set":false}\n'
{
    "__version__": 1,
    "cc": "91",
    "client_static_keypair": "[omitted]",
    "expid": "tX2x65PCTiuXIDFebCYULw==",
    "fdid": "98c2ed2f-939b-4c81-a57c-82ce3a58af1d",
    "id": "[omitted]",
    "mcc": "405",
    "mnc": "799",
    "phone": "918X8X25253X",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
status: b'ok'
login: b'918080252530'
type: b'existing'
edge_routing_info: b'CAIIBQ=='

am I missing something?

thanks,
nitin
```

**Comment by tgalal** [comment]
there is no password, your client_static_keypair is used for authentication, after successful registration just login, you don't need to specify it yourself. And keep 'id' secret as well.

**Comment by subhamsuthar** [comment]
is there way to create apis for get last seen...?

**Comment by cremiro** [comment]
on the sample that's in: https://github.com/tgalal/yowsup/wiki/Sample-Application
asks for a password, like this would be with the client_static_keypair?
Thank you
