### ISSUE TITLE
YowCoderLayer class missing properties

### ISSUE THREAD

**Issue by jtig2019** [tgalal/yowsup#2710]
Hi together,

I use the code from the sample application to build the stack in run.py:

```python
stack = YowStack(layers)
stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource()) 
```
When running run.py I get the following error message:
```python
E 2019-05-01 20:37:22,305 yowsup.layers.network.dispatcher.dispatcher_socket - 
ERROR:yowsup.layers.network.dispatcher.dispatcher_socket:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 64, in YowThread
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
AttributeError: type object 'YowCoderLayer' has no attribute 'PROP_DOMAIN'
```

In the layer class "YowCoderLayer" the properties are no longer available. Does the stack in yowsup 3.x have to be build differently?

Thx for help!

**Comment by tgalal** [comment]
Yes the examples are outdated, try ignore those properties and also use your client_static_keypair instead of password. You could also leave password as None and the client_static_keypair will be fetched from your config if you have registered using yowsup.

**Comment by jtig2019** [comment]
Ok, thanks for the note. I commented out the lines with the properties.

For the registration I used yowsup and I got a valid client static keypair. I could also successfully send a message via yowsup-cli. 

The sending via run.py does not work. There I set the credentials as follows:
```python
credentials = ("phonenumber", "client_static_keypair")

stackBuilder = YowStackBuilder()
stack = stackBuilder .pushDefaultLayers().push(EchoLayer).build()
stack.setCredentials(credentials)
```

After running run.py I get the following error message, more will unfortunately not be output:
```python
E 2019-05-02 00:18:22,820 yowsup.layers.network.dispatcher.dispatcher_socket - 
ERROR:yowsup.layers.network.dispatcher.dispatcher_socket:
INFO:transitions.core:Exited state init
INFO:transitions.core:Entered state init
```

**Comment by bidaian** [comment]
Try setting the password to None. It works for me  (as tgalal said, it will be picked up from the configuration). By the way, it's a great idea, the configuration makes many things a lot easier.

**Comment by joaomdmoura** [comment]
Commenting the lines didn't work for me for some reason, the messages never get read, but the applications runs. :thinking:

**Comment by bidaian** [comment]
Then it's probably working. The example code doesn't do much. I added a print (to see the incoming messages) and the the echo (an actual forward) and it works. This is the code:

(no idea why there are so many tolower ..., but I'm only starting to grasp the code)

```
def onMessage(self, messageProtocolEntity):
        #send receipt otherwise we keep receiving the same message over and over

        if True:
            receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom(), 'read', messageProtocolEntity.getParticipant())
            print("Echoing %s to %s" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False)))
            outgoingMessageProtocolEntity = TextMessageProtocolEntity(
                messageProtocolEntity.getBody(),
                to = messageProtocolEntity.getFrom())

            self.toLower(receipt)
            self.toLower(outgoingMessageProtocolEntity)

        self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
        self.toLower(messageProtocolEntity.ack())
        self.toLower(messageProtocolEntity.ack(True))
```

**Comment by jtig2019** [comment]
@bidaian 

I have the following project structure:  /yowsup/demos/testProject/run.py

If I use a config file, how do I use it in my run.py?

**Comment by joaomdmoura** [comment]
I'm not sure what the problem might be in my case specifically. I decided to give the demo CLI a try to make sure everything is working but I keep getting the `No such prekeyRecord!` exception. Maybe related to #2672

**Comment by bidaian** [comment]
> I have the following project structure: /yowsup/demos/testProject/run.py
> 
> If I use a config file, how do I use it in my run.py?

Yowsup will pickup the password from the config file. Tgalal said so a couple of comments above. It will use the phone number to get the right config file (it searches in a couple of places)

This is how I have it now ('pip install --user' version, I'm not working with master)

```
CREDENTIALS = ("MYTELEFPHONE", None) # replace with your phone and password

if __name__==  "__main__":
    layers = (
        EchoLayer,
        YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer,
                          YowAckProtocolLayer]),
        AxolotlControlLayer,
        YowParallelLayer((AxolotlSendLayer, AxolotlReceivelayer)),
    ) + YOWSUP_CORE_LAYERS

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    #stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    #stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())          #info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal

    stack.loop() #this is the program mainloop
```

**Comment by jtig2019** [comment]
Ok thx, for the example code. Its working now with the config file. Thx to all!

**Comment by langioletto** [comment]
> Ok, thanks for the note. I commented out the lines with the properties.
> 
> For the registration I used yowsup and I got a valid client static keypair. I could also successfully send a message via yowsup-cli.
> 
> The sending via run.py does not work. There I set the credentials as follows:
> 
> ```python
> credentials = ("phonenumber", "client_static_keypair")
> 
> stackBuilder = YowStackBuilder()
> stack = stackBuilder .pushDefaultLayers().push(EchoLayer).build()
> stack.setCredentials(credentials)
> ```
> 
> After running run.py I get the following error message, more will unfortunately not be output:
> 
> ```python
> E 2019-05-02 00:18:22,820 yowsup.layers.network.dispatcher.dispatcher_socket - 
> ERROR:yowsup.layers.network.dispatcher.dispatcher_socket:
> INFO:transitions.core:Exited state init
> INFO:transitions.core:Entered state init
> ```

Hi jtig2019 

python3 /root/.yowsup/run.py
INFO:transitions.core:Exited state init
INFO:transitions.core:Entered state init

I have the same problem as you.

How did you solve it?

You can paste here yours run.py ?

My is:

`from yowsup.stacks                             import YowStackBuilder
from yowsup.common                             import YowConstants
from yowsup.layers                             import YowLayerEvent
from layer                                     import EchoLayer
#from layerDEV                                     import EchoLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.env                                import YowsupEnv

from server                                    import make_app
from sys                                       import argv

import threading, time
import tornado.ioloop, tornado.web


#Uncomment to log
import logging
logging.basicConfig(level=logging.CRITICAL)

if len(argv) > 1:
    credentials = ( argv[1], argv[2])
    if len(argv) >= 4:
        port = argv[3]
    else:
        port = 8888
else:
    credentials = ("430000000000", None) #replace with your phone and password
    #port = 23789
    port = 8888

if __name__==  "__main__":

    messages = dict()

    stackBuilder = YowStackBuilder()
    stack = stackBuilder\
        .pushDefaultLayers()\
        .push(EchoLayer)\
        .build()

    stack.setProp("messages", messages)

    app = make_app(stack, messages)

    def YowThread():
        stack.setCredentials(credentials)
        stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))          #sending the connect signal
        stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])           #whatsapp server address
        #stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
        #stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())  #info about us as WhatsApp client
        stack.loop(timeout = 0.5, discrete = 0.5 )                                        #this is the program mainloop

    def TornadoThread():
        app.listen(port)
        tornado.ioloop.IOLoop.current().start()

    AppThread = threading.Thread( target=TornadoThread )
    AppThread.daemon = False
    AppThread.start()


    WaThread = threading.Thread( target=YowThread )
    WaThread.daemon = True
    WaThread.start()
`

Very thanks!!

**Comment by langioletto** [comment]
UP
