### ISSUE TITLE
Segmentation Fault / Bus Error when running yowsup-cli

### ISSUE THREAD

**Issue by markus7017** [tgalal/yowsup#2715]
After installing Python 3.6.5 and the mentioned modules with the required versions on my RPi3 with Stretch I was able to complete the registration process. I could send a message with yowsup-cli -s, but I can't use the cli (-y). I tried version 3.1.0 and 3.2.0

yowsup-cli demos --config /root/.config/yowsup/1234567/config.json -y
yowsup-cli  v3.0.0
yowsup      v3.1.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:
Bus error

**Comment by tgalal** [comment]
run with --debug only ony yowsup 3.2.0 and post output

**Comment by markus7017** [comment]
yowsup-cli demos --config-phone 491234567config.json --debug -y

D 2019-05-05 11:44:25,722 yowsup.config.manager - load_path(path=/root/.config/yowsup/491756614372/config.json)
D 2019-05-05 11:44:25,723 yowsup.config.manager - Detected config type: json
D 2019-05-05 11:44:25,723 yowsup.config.manager - Opening config for reading
D 2019-05-05 11:44:25,726 yowsup.config.manager - Loading config
D 2019-05-05 11:44:25,727 yowsup.config.manager - Detecting config for username=491756614372, dir=/root/.config/yowsup/491756614372/
D 2019-05-05 11:44:25,728 yowsup.config.manager - Trying /root/.config/yowsup/491756614372/config.yo
D 2019-05-05 11:44:25,728 yowsup.config.manager - Trying /root/.config/yowsup/491756614372/config.json
D 2019-05-05 11:44:25,729 yowsup.config.manager - load_path(path=/root/.config/yowsup/491756614372/config.json)
D 2019-05-05 11:44:25,729 yowsup.config.manager - Detected config type: json
D 2019-05-05 11:44:25,730 yowsup.config.manager - Opening config for reading
D 2019-05-05 11:44:25,731 yowsup.config.manager - Loading config
D 2019-05-05 11:44:25,732 yowsup-cli - starting cmd
yowsup-cli  v3.2.0
yowsup      v3.2.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2019-05-05 11:44:27,074 yowsup.stacks.yowstack - Initializing stack
D 2019-05-05 11:44:27,076 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-05-05 11:44:27,077 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-05-05 11:44:27,088 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-05-05 11:44:27,089 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-05-05 11:44:27,090 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-05-05 11:44:27,092 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x750de470>
D 2019-05-05 11:44:27,092 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x75cb9350>
D 2019-05-05 11:44:27,093 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-05-05 11:44:27,116 yowsup.stacks.yowstack - Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Segmentation fault

**Comment by markus7017** [comment]
Setup:
- Raspberry Pi with openHABIAN
- Python 3.6.5
- yowsup 3.2.0

Modules installed:
pip3.6 install --upgrade pip
pip3.6 install cryptography==2.5
pip3.6 install consonance==0.1.2
pip3.6 install python-axolotl>=0.1.39
pip3.6 install protobuf>=3.6.0
pip3.6 install six==1.10
pip3.6 install certifi
pip3.6 install config.manager
pip3.6 install yowsup==3.2.0

Runs on macOS without those problems.

**Comment by markus7017** [comment]
Version 3.2.3 produces the following errors
- Segmentation Fault
- Bus Error
- *** Error in `/usr/local/bin/python3': double free or corruption (out): 0x75f13eb8 ***
Aborted

**Comment by tgalal** [comment]
I dont think the errors are relevant to yowup, but rather to something in your python installation, or even system C libraries is messed up/ corrupt. I'll close this and reopen if I get similar reports or steps to reproduce.
