### ISSUE TITLE
Request upload for file xxx failed - yowsup 3.1.0 and 3.2.0

### ISSUE THREAD

**Issue by markus7017** [tgalal/yowsup#2717]
I'm trying to send an image (yowsup 3.2.0, macOS, Python 3.6.5) and get an error:
/image send 49xxxxxxx "/Users/markus/Downloads/test.png"  "Picture from openHAB"'

yowsup.layers.logger.layer - tx:'
&lt;iq id="3" type="set" xmlns="w:m" to="s.whatsapp.net"&gt;'
&lt;media hash="f4/1jf2wiRE+hc/jCv0hHR9XT9IbqWvTkZw0zhoF5Xg=" type="image" size="113798"&gt;'
&lt;/media&gt;'
&lt;/iq&gt;'
yowsup.layers.logger.layer - tx:'
&lt;iq id="3" type="set" xmlns="w:m" to="s.whatsapp.net"&gt;'
&lt;media hash="f4/1jf2wiRE+hc/jCv0hHR9XT9IbqWvTkZw0zhoF5Xg=" type="image" size="113798"&gt;'
&lt;/media&gt;'
&lt;/iq&gt;'
[connected]:D 40,313 yowsup.layers.logger.layer - rx:'
&lt;iq from="s.whatsapp.net" type="error" id="3"&gt;'
&lt;error code="501" text="feature-not-implemented"&gt;'
&lt;/error&gt;'
&lt;/iq&gt;'
E 40,313 yowsup.demos.cli.layer - Request upload for file /Users/markus/Downloads/test.png for 49xxxxxxx@s.whatsapp.net failed'
D 40,313 yowsup.layers.logger.layer - rx:'
&lt;iq from="s.whatsapp.net" type="error" id="3"&gt;'
&lt;error code="501" text="feature-not-implemented"&gt;'
&lt;/error&gt;'
&lt;/iq&gt;'
D 21,822 yowsup.layers.protocol_iq.layer - ping queue size: 1'
D 21,822 yowsup.layers.logger.layer - tx:'
&lt;iq id="4" type="get" xmlns="w:p"&gt;'
&lt;/iq&gt;'
D 22,330 yowsup.layers.logger.layer - rx:'
&lt;iq from="491702985135@s.whatsapp.net" type="result" id="4" t="1557055822"&gt;'
&lt;/iq&gt;'
Iq:'
ID: 4'
Type: result'
from: 491702985135@s.whatsapp.net'

**Comment by tgalal** [comment]
duplicate #2682
