### ISSUE TITLE
Version 3.2.2 | received message will not be decrypted

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2727]
When I sent a message to yowsup, the message will not longer be decrypted in demos. Behavior since Version 3.2.1

**Comment by tgalal** [comment]
what does that mean?

**Comment by luetty** [comment]
jowiemann means decrypted, i think!

Sending a text like "Status" from WhatsApp to yowsup will be displayed as "58FFB669E0540CE071DF2A5A73385FA3" (or similar)

**Comment by jowiemann** [comment]
luetty, that's correct. Thank you.

**Comment by tgalal** [comment]
@luetty this looks to me like the message id which is supposed to be printed next to the received text. Are you having this problem too? And which demo? 

@jowiemann would be great if you post information like output with debug activated and which demo are you talking about

**Comment by HeinzFo** [comment]
I send the keyword **Ip**.
It seams **IP** is received but also **095614D82653DA2AF571C99E5677AC81**
and the Echo client will react regarding 095614D82653DA2AF571C99E5677AC81

```
2019.05.07 18:20:17 4: WhatsApp: parse:
[49171xxx6@s.whatsapp.net(07-05-2019 18:20)]:[Ip]    095614D82653DA2AF571C99E5677AC81
Message 095614D82653DA2AF571C99E5677AC81: Sent delivered receipt and Read
[connected]:
```

**Comment by jowiemann** [comment]
HeinzFo was faster. We are useing echo client in the Smart Home Fhem environment. There has something be changed in the output of the echo client since Version 3.2.1, when receiving messages.

I 2019-05-07 18:37:53,736 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
Auth: Logged in!
[connected]:[491622846962@s.whatsapp.net(07-05-2019 18:38)]:[set Dachgeschoss on]        3A14D7AEF9A0FC23CEB1
Message 3A14D7AEF9A0FC23CEB1: Sent delivered receipt and Read
[connected]:

**Comment by tgalal** [comment]
I think I accidentally swapped the order in which message parameters is printed, where the message id (hex string) is printed in place of the message content and vice versa. Fixing it now.

**Comment by HeinzFo** [comment]
Yes!

This was in an good condition yesterday.
Keyword was **Rpi**
```
2019.05.06 18:16:14 4: WhatsApp: parse: 
[49171xxx@s.whatsapp.net(06-05-2019 18:16)]:[48558C013DAC7E2D1FA0A9AD07A87625]	 Rpi
Message 48558C013DAC7E2D1FA0A9AD07A87625: Sent delivered receipt and Read
[connected]:
```

**Comment by HeinzFo** [comment]
Works fine now!
Thanks for the fast fix ;-)
