### ISSUE TITLE
How to disconnect and reconnect after sometime?

### ISSUE THREAD

**Issue by cijo7** [tgalal/yowsup#2736]
I am trying to disconnect with:

`self.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_DISCONNECT))`
```

    @EventCallback(YowNetworkLayer.EVENT_STATE_DISCONNECTED)
        def disconnect(self, extra=None):
            pass
```

But getting some new logs.
 DEBUG: handle_close
 DEBUG: Disconnected
 INFO: Exited state transport
 INFO: Entered state init
 DEBUG: Disconnected, reboot_connect? = False
 DEBUG: stopping ping thread

It just gets stuck on that. I am not sure why.

What do these mean?

How can I just do a reconnect?

**Comment by tgalal** [comment]
you have disconnected as you requested. Your disconnect method should be called now as it's listening to "EVENT_STATE_DISCONNECTED", isn't that the case?

**Comment by cijo7** [comment]
Yeah. It works fine.

What does Entered/Exited state transport mean? I see it a lot of time now.

**Comment by tgalal** [comment]
did you by an chance activate logging on all libraries by calling logging.config? If so then you should config a logger and not the logging module itself. This log message you see is coming from an underlying library and not from yowsup.
