### ISSUE TITLE
config.json blank

### ISSUE THREAD

**Issue by fhartavi** [tgalal/yowsup#2740]
~/.config/yowsup/49xxxxx/config.json its created as folder and its blank

**Comment by tgalal** [comment]
l will reopen the issue if you post proper information, what the error is, and steps to reproduce

**Comment by fhartavi** [comment]
Sir i registered phone taken request sms and activate number response is here but i cant using number because of config file not created.

I 2019-05-12 12:31:19,862 yowsup.common.http.warequest - b'{"status":"ok","login":"XXX","type":"new","edge_routing_info":"XXX==","chat_dns_domain":"fb","security_code_set":false}\n'
{
    "__version__": 1,
    "cc": "44",
    "client_static_keypair": "XXXX",
    "expid": "XXX",
    "fdid": "XXXX",
    "id": "XXX",
    "mcc": "405",
    "mnc": "799",
    "phone": "XXX",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
status: b'ok'
login: b'XXX'
type: b'new'
edge_routing_info: b'XXX'

**Comment by fhartavi** [comment]
@tgalal
