### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by khaled-s** [tgalal/yowsup#2742]
Hello,
and thanks for your work. can you provide us with working example. I'm having a hard time finding the right way to receive messages and replay to it
the provided example is not working and raises a lot of error
especially after you upgraded the library to v3
can you update the example?
hope to hear from you soon
Regards

**Comment by tgalal** [comment]
see [demo](https://github.com/tgalal/yowsup/tree/master/yowsup/demos)
