### ISSUE TITLE
yowsup-cli cannot terminate when send message 

### ISSUE THREAD

**Issue by weechatfly** [tgalal/yowsup#2744]
hello,
when I use yowsup-cli to send message, i got:
python yowsup-cli demos -c "xxx\xxxx\config.json" -s xxxxxxxxx "hello"
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2019-05-13 15:48:35,481 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
I 2019-05-13 15:48:36,230 yowsup.axolotl.manager - Loaded 812 unsent prekeys

the program cannot terminate, then i use:
python yowsup-cli demos -c "xxx\xxxx\config.json" -y
send /L, the phone is cannot login in.
so,I think yowsup-cli send message cannot terminate if the phone is blocked!
please fix it
thanks!

**Comment by tgalal** [comment]
those are just demos to use for reference and shouldnt be considerd reliable working apps. nothing to fix
