### ISSUE TITLE
instalation

### ISSUE THREAD

**Issue by monica-delcastillo** [tgalal/yowsup#2751]
Hi. Thanks for this fantastic project. I known recently and it will resolve my life.

"I THINK IT IS NOT A YOWSUP ISSUE, BUT I NEED HELP"

I needed reinstall my server, i use Centos 7, but now I cant install

I execute pip install yowsup and I not see any error.

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: yowsup in /usr/lib/python2.7/site-packages (3.2.3)
Requirement already satisfied: argparse in /usr/lib/python2.7/site-packages (from yowsup) (1.4.0)
Requirement already satisfied: protobuf>=3.6.0 in /usr/lib64/python2.7/site-packages (from yowsup) (3.7.1)
Requirement already satisfied: python-axolotl==0.2.2 in /usr/lib/python2.7/site-packages (from yowsup) (0.2.2)
Requirement already satisfied: appdirs in /usr/lib/python2.7/site-packages (from yowsup) (1.4.3)
Requirement already satisfied: consonance==0.1.2 in /usr/lib/python2.7/site-packages (from yowsup) (0.1.2)
Requirement already satisfied: six==1.10 in /usr/lib/python2.7/site-packages (from yowsup) (1.10.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from protobuf>=3.6.0->yowsup) (41.0.1)
Requirement already satisfied: python-axolotl-curve25519>=0.4.1 in /usr/lib64/python2.7/site-packages (from python-axolotl==0.2.2->yowsup) (0.4.1-2)
Requirement already satisfied: cryptography in /usr/lib64/python2.7/site-packages (from python-axolotl==0.2.2->yowsup) (2.6.1)
Requirement already satisfied: dissononce>=0.34.3 in /usr/lib/python2.7/site-packages (from consonance==0.1.2->yowsup) (0.34.3)
Requirement already satisfied: transitions in /usr/lib/python2.7/site-packages (from consonance==0.1.2->yowsup) (0.6.9)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->python-axolotl==0.2.2->yowsup) (1.0.4)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->python-axolotl==0.2.2->yowsup) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/lib64/python2.7/site-packages (from cryptography->python-axolotl==0.2.2->yowsup) (1.12.3)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->python-axolotl==0.2.2->yowsup) (1.0.16)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->python-axolotl==0.2.2->yowsup) (2.14)`

but when I try use yowsup-cli command it show 

`Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.2.3', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/yowsup-cli' not found in metadata at '/usr/lib/python2.7/site-packages/yowsup-3.2.3.dist-info'`

**Comment by tgalal** [comment]
doesn't look installed properly, closing

**Comment by monica-delcastillo** [comment]
if I execute 

./yowsup-cli registration XXXX work ok

only  yowsup-cli registration xxxx no work


thanks
