### ISSUE TITLE
How to receive media

### ISSUE THREAD

**Issue by bidaian** [tgalal/yowsup#2756]
I received a picture. This is the content:

[media_type=image, length=161232, url=https
://mmg-fna.whatsapp.net/d/f/AiDX2c5tZGx4wakTL0V26XTHwr8ikcNH3BL61FrGqbEA.enc, key=4KwFCuWhwYnZwCSYUjJWD/q6AokVo6/iifG00AtH7nk=]

Does anybody know, or can point me to documentation on, how to download the actual image?

**Comment by tgalal** [comment]
[media sink demo](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/mediasink/layer.py)

**Comment by ersinayaz** [comment]
> media sink demo

Can you share a sample to help us further.
