### ISSUE TITLE
problem with message reception/read receipt after moving client to another machine

### ISSUE THREAD

**Issue by jpmorrison** [tgalal/yowsup#2761]
I had yowsup-cli demos --config-phone 1xxxxxxxxxx -y working on Linux (x64) then I tried on cygwin. 

I copied all of .config/yowsup/1xxxxxxxxxx/  to cygwin and it worked. 

Then I tried building for Raspberry Pi - had to upgrade pip cryptography but got it to install.
I copied the .config from Linux not from Cygwin. 

I was able to send messages but receiving messages gave errors like this:
W 2019-05-18 15:16:09,233 yowsup.layers.axolotl.layer_receive - InvalidMessage or KeyId for 1yyyyyyyyyy, going to send a retry

Since I had some build problems on the Pi, I thought it might be from that. 

I went back to Cygwin and connected - then I started seeing (some) incoming messages:
[connected]:W 2019-05-18 15:33:07,223 yowsup.layers.axolotl.layer_receive - Received a message that we've previously decrypted, goint to send the delivery receipt myself

[1yyyyyyyyyy@s.whatsapp.net(18-05-2019 15:13)]:[3A13585D86655909AC10]    Ok
Message 3A13585D86655909AC10: Sent delivered receipt and Read
[connected]:

Along the way realized that axolotl.db gets updated 

I see the "Ok" but not subsequent messages from the sender 1yyyyyyyyyy and that sender is not seeing the read receipts. 

At this point I can't properly receive messages on yowsup-cli  but it seems to keep retrying 

Is there some way to reset this?

**Comment by jpmorrison** [comment]
Seems like a common problem

Deleted axolotl.db and restarted - not sure if this is a required

The fix seems to be:
Repeatedly /disconnect  /L  a few times

- tried this and a backlog of messages came in and it seemed to clear temporarily
- it seemed to get stuck again for bit. I don't know if anything I did eventually reset it or it was just a matter of time but I rebooted my whatsapp phone client
- seems to have gone back to normal now

**Comment by tgalal** [comment]
```InvalidMessage or KeyId for 1yyyyyyyyyy, going to send a retry```

you didn't copy the axolotl.db, so when you received a message yowsup was not able to successfully decrypt and sent a request to sender to re-encrypt and re-send the message again. This is normal procedure. However the sender must go online to be able to resend the message again so don't expect to receive it until then.

```Received a message that we've previously decrypted, going to send the delivery receipt myself```; normal procedure when you receive a message twice, for whatever reasons receipts for first one were never sent. 

It's not a common problem. I'd say your use here is what's causing this mess, switching between different axolotl database will cause non-smooth behaviors like duplicate messages, message delays, retries..etc which are expected given how E2E works.
