### ISSUE TITLE
Yowsup 3.2.3 some mobile numbers are blocked by WhatsApp

### ISSUE THREAD

**Issue by HeinzFo** [tgalal/yowsup#2764]
Hello Tgalal

Yowsup 3.2.3 some mobile numbers are blocked by WhatsApp.

In the last 3 Weeks some Mobile numbers are blocked by WhatsApp.
The answer from WhatsApp Suppot Team is folows.

_**Thanks for your message.**_ 

_**We apologize for any confusion and inconvenience this may have caused. Our system flagged your account activity as a violation of our Terms of Service and subsequently banned your number.**_ 

_**To ensure access, please reverify your number with our official WhatsApp client, which can be downloaded from our website: www.whatsapp.com/download**_

**_Please note that we do not provide support for unofficial clients or for jailbroken/rooted (including emulators), and https://faq.whatsapp.com/general/26000006_**

**_WhatsApp Support Team_**

What can we do in additionally to the registration to avoid this?

Regards
Heinz

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
