### ISSUE TITLE
My number was blocked

### ISSUE THREAD

**Issue by Arlington1985** [tgalal/yowsup#2765]
Although I didn't spam, just for testing send few messages to myself, after a few days the number just blocked. Does it mean that using this library really doesn't make sense anymore? :(

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account

**Comment by Arlington1985** [comment]
Sorry but what is the difference between setting up on a server and own device? what does it means here device? I were using it on Google Cloud, was it an issue?
