### ISSUE TITLE
Can not register using sms or voice.

### ISSUE THREAD

**Issue by nightcoder22** [tgalal/yowsup#2766]
Whenever i try to register, code is sent successfully to my mobile but when i enter 6 digit code, i get either of the following error,
`status: fail
retry_after: 3600
login: 1269399XXXX`

or no_routes sometimes.
my 6 digit security code is correct.
I even tried after 3600 sec, but then my number gets blocked by whatsapp after trying to send the code.
Any help will be appreciated.

**Comment by devalexanderdaza** [comment]
Check if your line has block!

**Comment by nightcoder22** [comment]
No, that's what i am saying, I receive 6 digit code then i enter it and it gives fail status. and when i retry after the given time, it says number is blocked.

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
