### ISSUE TITLE
I can not register whatsapp yowsup

### ISSUE THREAD

**Issue by digobo** [tgalal/yowsup#2767]
Hello,

I'm trying to register with the code but it gives me an error, can you help me? Copy the error:
```
[root@nagios yowsup]# ./yowsup-cli registration --register XXX-XXX --phone XXXXXXXXXXX --cc XXX
I 2019-05-21 15:08:07,462 yowsup.profile.profile - Constructed Profile(profile_name=XXXXXXXXXXX)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2019-05-21 15:08:07,553 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2019-05-21 15:08:07,553 yowsup.profile.profile - Constructed Profile(profile_name=XXXXXXXXXXX)
I 2019-05-21 15:08:08,330 yowsup.common.http.warequest - {"status":"ok","login":"XXXXXXXXXXX","type":"existing","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","security_code_set":false}

{
    "__version__": 1,
    "cc": "XXX",
    "chat_dns_domain": "fb",
    "client_static_keypair": "KCPd5OFyJxtdbbLnqzqPTUH67MyTE6Qvb1jCYlILQlT6UwmGiq6y2s9/hr4EHcLqS2/lMyjAXdNpvfJojMkQIA==",
    "edge_routing_info": "CAUIAg==",
    "expid": "zsZSui0mTFSXxHc4zRSlug==",
    "fdid": "cfd3e789-451c-4859-8fb0-adc23f38b2f5",
    "id": "NAQXaPX54xKegToly48g20HN6SY=",
    "login": "XXXXXXXXXXX",
    "mcc": "XXX",
    "mnc": "XX",
    "phone": "XXXXXXXXXXX",
    "sim_mcc": "XXX",
    "sim_mnc": "XXX"
}
Traceback (most recent call last):
  File "./yowsup-cli", line 672, in <module>
    if not parser.process():
  File "./yowsup-cli", line 359, in process
    self.handleRegister(self.args["register"], config)
  File "./yowsup-cli", line 399, in handleRegister
    self._profile.write_config(self._config)
  File "/root/yowsup/yowsup/profile/profile.py", line 39, in write_config
    self._config_manager.save(self._profile_name, config)
  File "/root/yowsup/yowsup/config/manager.py", line 127, in save
    outputdata = self.config_to_str(config, serialize_type)
  File "/root/yowsup/yowsup/config/manager.py", line 122, in config_to_str
    return transform.transform(ConfigSerialize(config.__class__).serialize(config))
  File "/root/yowsup/yowsup/config/base/serialize.py", line 14, in serialize
    config = transform.transform(config)
  File "/root/yowsup/yowsup/config/transforms/config_dict.py", line 16, in transform
    for prop in vars(config):
TypeError: vars() argument must have __dict__ attribute
```

**Comment by digobo** [comment]
Hi, @tgalal 

Make the modifications in the yowsup, I do not get the error but it shows me the following configuration:

[root@nagios yowsup]# ./yowsup-cli registration --register XXX-XXX --phone XXXXXXXXXX --cc XXX
I 2019-05-22 09:17:23,414 yowsup.profile.profile - Constructed Profile(profile_name=XXXXXXXXXX)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2019-05-22 09:17:23,587 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2019-05-22 09:17:23,587 yowsup.profile.profile - Constructed Profile(profile_name=XXXXXXXXXXX)
I 2019-05-22 09:17:24,302 yowsup.common.http.warequest - {"status":"ok","login":"XXXXXXXXXX","type":"existing","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","security_code_set":false}

{
    "__version__": 1,
    "cc": "XXX",
    "chat_dns_domain": "fb",
    "client_static_keypair": "KCPd5OFyJxtdbbLnqzqPTUH67MyTE6Qvb1jCYlILQlT6UwmGiq6y2s9/hr4EHcLqS2/lMyjAXdNpvfJojMkQIA==",
    "edge_routing_info": "CAUIAg==",
    "expid": "zsZSui0mTFSXxHc4zRSlug==",
    "fdid": "cfd3e789-451c-4859-8fb0-adc23f38b2f5",
    "id": "NAQXaPX54xKegToly48g20HN6SY=",
    "login": "XXXXXXXXX",
    "mcc": "XXX",
    "mnc": "XX",
    "phone": "XXXXXXXXXX",
    "sim_mcc": "XXX",
    "sim_mnc": "XXX"
}
status: ok
edge_routing_info: CAUIAg==
login: XXXXXXXXXXX
type: existing

-----------------------------------------------------------------------------------------------------------------

I add that configuration to a yowsup-cli.config file and then I run the following command but it does not send me anything because it gives the error that I copy below

./yowsup-cli demos -c yowsup-cli.config -s XXXXXXXXXXX Prueba
W 2019-05-22 09:23:02,040 yowsup.config.manager - load_path couldn't find the path: yowsup-cli.config
E 2019-05-22 09:23:02,041 yowsup.config.manager - Could not find a config for profile=yowsup-cli.config, paths checked: /root/.config/yowsup/yowsup-cli.config/config.json:/root/.config/yowsup/yowsup-cli.config/config.yo
I 2019-05-22 09:23:02,041 yowsup.profile.profile - Constructed Profile(profile_name=yowsup-cli.config)
E 2019-05-22 09:23:02,041 yowsup.config.manager - Could not find a config for profile=yowsup-cli.config, paths checked: /root/.config/yowsup/yowsup-cli.config/config.json:/root/.config/yowsup/yowsup-cli.config/config.yo
E 2019-05-22 09:23:02,041 yowsup.config.manager - Could not find a config for profile=yowsup-cli.config, paths checked: /root/.config/yowsup/yowsup-cli.config/config.json:/root/.config/yowsup/yowsup-cli.config/config.yo
I 2019-05-22 09:23:02,041 yowsup.profile.profile - Constructed Profile(profile_name=yowsup-cli.config)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2019-05-22 09:23:02,295 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
I 2019-05-22 09:23:02,730 yowsup.axolotl.manager - Generating 812 prekeys
I 2019-05-22 09:23:03,098 yowsup.axolotl.manager - Storing 812 prekeys
I 2019-05-22 09:23:27,477 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2019-05-22 09:23:27,486 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib64/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib64/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/root/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/root/yowsup/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/root/yowsup/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/root/yowsup/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/root/yowsup/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/root/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/root/yowsup/yowsup/layers/noise/layer.py", line 59, in on_auth
    username = int(self._profile.username)
ValueError: invalid literal for int() with base 10: 'yowsup-cli.config'

**Comment by facundonapal** [comment]
Did you solve it @digobo ?

**Comment by digobo** [comment]
Yes, I solved it.

**Comment by dd0129** [comment]
@digobo how?

**Comment by zilverback** [comment]
@digobo How did you solve this issue?

May you  share your history command line?

**Comment by digobo** [comment]
Yes, I solved it with the following link: https://github.com/tgalal/yowsup/commit/1df09d969f362cb7e58ba2a85b05e3983dea3584
