### ISSUE TITLE
method "profile_setPicture"

### ISSUE THREAD

**Issue by Marcorele** [tgalal/yowsup#277]
Hello,

i try change my profil picture using method :
profile_setPicture(str filePath)

my code : 

methodsInterface.call("profile_setPicture",("pic.jpg"))

i have an error message : TypeError: sendSetProfilePicture() takes exactly 2 arguments (9 given)

What is wrong? thx you

**Comment by PoMkaNik** [comment]
@Marcorele As sed in https://github.com/tgalal/yowsup/wiki/%5BLegacy%5D-Yowsup-Documentation#methods 
You should put "," after single parameters. Otherwise python will parse them as individual chars
