### ISSUE TITLE
ImportError: cannot import name x25519

### ISSUE THREAD

**Issue by PlanB007** [tgalal/yowsup#2770]
Hi, I saw @jowiemann with the same problem. Only the fix for him didn't work for me.

I'm getting the next error:
```Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.config.manager import ConfigManager
  File "/home/pi/Documents/yowsup/yowsup/config/manager.py", line 4, in <module>
    from yowsup.config.v1.serialize import ConfigSerialize
  File "/home/pi/Documents/yowsup/yowsup/config/v1/serialize.py", line 8, in <module>
    from consonance.structs.keypair import KeyPair
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/structs/keypair.py", line 4, in <module>
    from dissononce.dh.x25519.x25519 import X25519DH
  File "build/bdist.linux-armv7l/egg/dissononce/dh/x25519/x25519.py", line 1, in <module>
ImportError: cannot import name x25519
```

I installed the latest version of _cryptography_ and still having the problem. I'm getting this error when running the next command: `python yowsup-cli registration --config [MyDetailsFile] --requestcode sms` after I ran the install.

**Comment by tgalal** [comment]
ok which cryptography  version? please also show sequence of steps/commands used to find the version

**Comment by PlanB007** [comment]
I installed Cryptography by using the installation guide on site of [Cryptography](https://cryptography.io/en/latest/installation/) then I run `pip freeze | grep cryptography` output: `cryptography==2.6.1`

So I'm on version 2.6.1

**Comment by tgalal** [comment]
can you see if it works if you install and run using a vritualenv that doesn't have access to system packages?

**Comment by PlanB007** [comment]
I've looked into Virtualenv, couldn't get it working on the Raspberry PI where I'm trying to run yowsup

**Comment by tgalal** [comment]
ok obviously you are having difficulties setting this up and is not a yowsup issue, closing

**Comment by PlanB007** [comment]
I think it's still a yowsup issue since my Cryptography version is 2.6.1. When I'm trying to install yowsup using:
`sudo python setup.py install`
It said _cryptography 1.7.1 is installed but cryptography>=2.5 is required by set(['dissononce'])_ and that's not true.

**Comment by tgalal** [comment]
if it tells you your cryptography version is 1.7.1, it is 1.7.1

**Comment by PlanB007** [comment]
Still, disagree I've used `pip freeze | grep cryptography` to check the version, and I've used `pip list` which shows you the installed packages, both showing me `cryptography (2.6.1)`. Is it possible yowsup cached the cryptography package version?
