### ISSUE TITLE
Recommendations to avoid blocking numbers

### ISSUE THREAD

**Issue by Wedmal** [tgalal/yowsup#2772]
The search did not give the expected result. I see a lot of topics with locks, but I haven’t found any recommendations that should be followed to avoid blocking the number. I used the yowsup for Zabbix alerts, an accident occurred, and 100500 messages flew. The number is blocked. Yes. I can avoid this by setting the delay. But I would like to listen to your recommendations, taking into account your experience.

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
