### ISSUE TITLE
yowsup.layers.logger.layer - rx: <failure reason="403" location="atn">

### ISSUE THREAD

**Issue by hf31** [tgalal/yowsup#2774]
Hello, 
i have the problem with yowsup-cli.  any ideas?
Debug Output here:
 python3 yowsup-cli demos --debug --config-phone 49xxxxx86 -s 49yyyyy45 "das ist ein Test"
D 2019-05-24 20:57:43,217 yowsup.config.manager - Detecting config for profile=49xxxxx86, dir=/opt/fhem/.config/yowsup/49xxxxx86/
D 2019-05-24 20:57:43,218 yowsup.config.manager - Trying /opt/fhem/.config/yowsup/49xxxx86/config.yo
D 2019-05-24 20:57:43,220 yowsup.config.manager - Trying /opt/fhem/.config/yowsup/49xxxxx86/config.json
D 2019-05-24 20:57:43,222 yowsup.config.manager - load_path(path=/opt/fhem/.config/yowsup/49xxxxx86/config.json)
D 2019-05-24 20:57:43,223 yowsup.config.manager - Detected config type: json
D 2019-05-24 20:57:43,224 yowsup.config.manager - Opening config for reading
D 2019-05-24 20:57:43,227 yowsup.config.manager - Loading config
I 2019-05-24 20:57:43,230 yowsup.profile.profile - Constructed Profile(profile_name=49xxxxx86)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2019-05-24 20:57:46,377 yowsup.stacks.yowstack - Initializing stack
D 2019-05-24 20:57:46,380 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-05-24 20:57:46,382 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-05-24 20:57:46,393 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-05-24 20:57:46,395 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-05-24 20:57:46,398 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-05-24 20:57:46,400 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x75b0c850>
D 2019-05-24 20:57:46,402 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x75d6aad0>
D 2019-05-24 20:57:46,403 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-05-24 20:57:46,408 yowsup.stacks.yowstack - Constructed Interface Layer
D 2019-05-24 20:57:46,409 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=49xxxxx86))
D 2019-05-24 20:57:46,411 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-05-24 20:57:46,412 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443
D 2019-05-24 20:57:46,413 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e4.whatsapp.net', 443))
D 2019-05-24 20:57:46,530 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-05-24 20:57:46,531 yowsup.layers.network.layer - Connected
D 2019-05-24 20:57:46,532 yowsup.axolotl.factory - get_manager(profile_name=49xxxxx86, username=49xxxxx86)
D 2019-05-24 20:57:46,578 yowsup.axolotl.manager - Initialized AxolotlManager [username=49xxxxx86, db=/opt/fhem/.config/yowsup/49xxxxx86/axolotl.db]
D 2019-05-24 20:57:46,579 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-05-24 20:57:46,808 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-05-24 20:57:46,815 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-05-24 20:57:46,819 yowsup.layers.noise.layer - Received auth event
D 2019-05-24 20:57:46,820 yowsup.env.env - Env not set, setting it to android
D 2019-05-24 20:57:46,821 yowsup.env.env - Current env changed to android
D 2019-05-24 20:57:46,822 yowsup.layers.noise.layer - Performing handshake [username= 49xxxx86, passive=True]
D 2019-05-24 20:57:46,823 yowsup.layers.noise.layer - Starting handshake worker
D 2019-05-24 20:57:51,154 yowsup.layers.logger.layer - rx: 
failure reason="403" location="atn"
/failure

D 2019-05-24 20:57:51,155 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2019-05-24 20:57:51,156 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-05-24 20:57:51,158 yowsup.layers.network.layer - Disconnected
D 2019-05-24 20:57:51,161 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by tgalal** [comment]
probably blocked, try register again and see

**Comment by clown16** [comment]
help

Perform the yowsup installation and register my phone, but when sending a message via yowsup it throws the following error in debugging

yowsup-cli demos -c onfig.txt -s 57********** "Probando WhatsApp ..." -d -E android
/usr/local/lib/python2.7/site-packages/cryptography-3.0-py2.7-linux-x86_64.egg/cryptography/init.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
CryptographyDeprecationWarning,
D 2020-08-06 17:15:06,158 yowsup.env.env - Current env changed to android
D 2020-08-06 17:15:06,159 yowsup.config.manager - load(path_or_profile_name=onfig.txt, profile_only=False)
D 2020-08-06 17:15:06,159 yowsup.config.manager - _load_path(path=onfig.txt)
D 2020-08-06 17:15:06,159 yowsup.config.manager - Trying auto detect config type by parsing
D 2020-08-06 17:15:06,159 yowsup.config.manager - Trying to parse as keyval
D 2020-08-06 17:15:06,159 yowsup.config.manager - onfig.txt was not parseable as keyval, reason: list index out of range
D 2020-08-06 17:15:06,159 yowsup.config.manager - Trying to parse as json
D 2020-08-06 17:15:06,159 yowsup.config.manager - Successfully detected json as config type for onfig.txt
D 2020-08-06 17:15:06,159 yowsup.config.manager - Detected config type: json
D 2020-08-06 17:15:06,159 yowsup.config.manager - Opening config for reading
D 2020-08-06 17:15:06,160 yowsup.config.manager - Loading config
D 2020-08-06 17:15:06,160 yowsup.config.manager - load(path_or_profile_name=57**************, profile_only=True)
D 2020-08-06 17:15:06,160 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-08-06 17:15:06,160 yowsup.config.manager - Detecting config for profile=57***************, dir=/root/.config/yowsup/57*************
D 2020-08-06 17:15:06,160 yowsup.config.manager - Trying /root/.config/yowsup/57**********/config.json
D 2020-08-06 17:15:06,160 yowsup.config.manager - _load_path(path=/root/.config/yowsup/57*******/config.json)
D 2020-08-06 17:15:06,161 yowsup.config.manager - Detected config type: json
D 2020-08-06 17:15:06,161 yowsup.config.manager - Opening config for reading
D 2020-08-06 17:15:06,161 yowsup.config.manager - Loading config
D 2020-08-06 17:15:06,161 yowsup.profile.profile - Constructed Profile(profile_name=57*************)
yowsup-cli v3.2.0
yowsup v3.2.3
consonance v0.1.3-1
dissononce v0.34.3
python-axolotl v0.2.2
cryptography v3.0
protobuf v4.0.0rc2

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2020-08-06 17:15:06,247 yowsup.stacks.yowstack - Initializing stack
D 2020-08-06 17:15:06,247 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-08-06 17:15:06,247 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-08-06 17:15:06,248 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-08-06 17:15:06,249 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-08-06 17:15:06,249 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-08-06 17:15:06,249 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f29c572a410>
D 2020-08-06 17:15:06,249 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f29c60d0f90>
D 2020-08-06 17:15:06,249 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-08-06 17:15:06,250 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-08-06 17:15:06,250 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=57**************))
D 2020-08-06 17:15:06,250 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-08-06 17:15:06,250 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
D 2020-08-06 17:15:06,250 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e2.whatsapp.net', 443))
D 2020-08-06 17:15:06,347 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-08-06 17:15:06,347 yowsup.layers.network.layer - Connected
D 2020-08-06 17:15:06,348 yowsup.axolotl.factory - get_manager(profile_name=57***********, username=57**********)
D 2020-08-06 17:15:06,350 yowsup.axolotl.manager - Initialized AxolotlManager [username=57***************, db=/root/.config/yowsup/57***********/axolotl.db]
D 2020-08-06 17:15:06,350 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-08-06 17:15:06,398 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-08-06 17:15:06,398 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-08-06 17:15:06,421 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-08-06 17:15:06,422 yowsup.layers.noise.layer - Received auth event
D 2020-08-06 17:15:06,422 yowsup.layers.noise.layer - Performing handshake [username= 57***************, passive=True]
D 2020-08-06 17:15:06,422 yowsup.layers.noise.layer - Starting handshake worker
D 2020-08-06 17:15:06,720 yowsup.profile.profile - write_config for 573174302712
D 2020-08-06 17:15:06,721 yowsup.common.tools - writeProfileData(profile_name=57*************, name=config.json, val=[omitted])
D 2020-08-06 17:15:06,721 yowsup.common.tools - Writing /root/.config/yowsup/57***********/config.json
D 2020-08-06 17:15:09,718 yowsup.layers.logger.layer - rx:
#failure reason="401" location="vll" /#
D 2020-08-06 17:15:09,718 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2020-08-06 17:15:09,718 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-08-06 17:15:09,719 yowsup.layers.network.layer - Disconnected
D 2020-08-06 17:15:09,719 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

my file config
{
"version": 1,
"cc": "57",
"client_static_keypair": "$
"expid": "lnZtIx",
"fdid": "34b90**--",#
"id": "",
"login": "57******",
"mcc": "000",
"mnc": "000",
"phone": "57**********",
"sim_mcc": "000",
"sim_mnc": "000"
}

please help!!!!!
