### ISSUE TITLE
<lambda>() takes 0 positional arguments but 2 were given

### ISSUE THREAD

**Issue by khaled-s** [tgalal/yowsup#2778]
Hello,
I'm getting this error while the applicatioin is running
```
File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_send.py", line 42, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_base.py", line 74, in onError
    errorClbk(errorNode, getKeysEntity)
TypeError: <lambda>() takes 0 positional arguments but 2 were given
```

system information:
Ubuntu 18.4
yowsup-cli v3.2.0
yowsup v3.2.3

**Comment by tgalal** [comment]
While this in fact a bug, it is triggered because you are sending a message to a number that is not a valid whatsapp user

**Comment by khaled-s** [comment]
actually, I'm not sending messages to numbers that I don't know, I'm just replying to the numbers that I'm receiving

**Comment by tgalal** [comment]
are you using a phone number when creating the reply or did you obtain a jid (username@s.whatsapp.net) somehow else? For example directly from the incoming message, or my syncing the number. A user's jid is not necessarily their phone number, it might be (slightly) different and therefore obtaining and using info from jid is essential.

If the number does match what's in the jid, then I'd say wait for the update which will properly display the error information

**Comment by khaled-s** [comment]
I'm using messageProtocolEntity.getFrom() to get the numbers. it's giving the number itself not the jid I'm using the TextMessageProtocolEntity to create the message

**Comment by tgalal** [comment]
getFrom gets the number from the jid which is also fine. In any case, master branch now has a fix that will log the actual problem, please try it out and open a new issue with the new info

**Comment by khaled-s** [comment]
ok, I will try it
thanks
