### ISSUE TITLE
configs are not saving in ubuntu 

### ISSUE THREAD

**Issue by kautubh** [tgalal/yowsup#2781]
Hello,
I have  tried changing the permission but i cannot save the configs to +777 for the time being but i can't save any configs

`yowsup-cli registration --requestcode sms --phone 919677****** --cc 91 -E android -c config2 --config-pushname "test user"`

to receive the otp:
`yowsup-cli registration --register ****** --phone config2 --cc 91 -E android -c config2`

so the **config 2 is not getting saved** ,even tried the directory method but only the folder gets created not the json file 

**A a result when we run** 
yowsup-cli demos -c config2 -s 91******** "hello"

we get error as none object
```
 File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by tgalal** [comment]
please run registration and login with --debug and post output

**Comment by tarikhagustia** [comment]
hi @kautubh , i have same problem, you need save config manually to json file
