### ISSUE TITLE
Exception raised while sending messages

### ISSUE THREAD

**Issue by kautubh** [tgalal/yowsup#2788]
Hello,
`yowsup-cli demos -c 856_2056746955 -s 91********* "hello "  --debug`

I am posting the `--debug `generated logs here 

**Sometimes i get this:** 

`D 2019-06-02 20:26:06,280 yowsup.config.manager - load_path(path=856_2056730083)
W 2019-06-02 20:26:06,281 yowsup.config.manager - load_path couldn't find the path: 856_2056730083
D 2019-06-02 20:26:06,281 yowsup.config.manager - Detecting config for profile=856_2056730083, dir=/home/kaustubh/.config/yowsup/856_2056730083/
D 2019-06-02 20:26:06,281 yowsup.config.manager - Trying /home/kaustubh/.config/yowsup/856_2056730083/config.json
D 2019-06-02 20:26:06,281 yowsup.config.manager - load_path(path=/home/kaustubh/.config/yowsup/856_2056730083/config.json)
D 2019-06-02 20:26:06,281 yowsup.config.manager - Detected config type: json
D 2019-06-02 20:26:06,282 yowsup.config.manager - Opening config for reading
D 2019-06-02 20:26:06,282 yowsup.config.manager - Loading config
D 2019-06-02 20:26:06,283 yowsup.profile.profile - Constructed Profile(profile_name=856_2056730083)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.5
protobuf       v3.8.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2019-06-02 20:26:06,358 yowsup.stacks.yowstack - Initializing stack
D 2019-06-02 20:26:06,358 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-06-02 20:26:06,358 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-06-02 20:26:06,359 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-06-02 20:26:06,359 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-06-02 20:26:06,359 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-06-02 20:26:06,359 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fc5f275bc50>
D 2019-06-02 20:26:06,359 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fc5f2745790>
D 2019-06-02 20:26:06,360 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-06-02 20:26:06,360 yowsup.stacks.yowstack - Constructed Interface Layer
D 2019-06-02 20:26:06,360 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=856_2056730083))
D 2019-06-02 20:26:06,360 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-06-02 20:26:06,360 yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
D 2019-06-02 20:26:06,360 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e14.whatsapp.net', 443))
D 2019-06-02 20:26:06,768 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-06-02 20:26:06,769 yowsup.layers.network.layer - Connected
D 2019-06-02 20:26:06,769 yowsup.axolotl.factory - get_manager(profile_name=856_2056730083, username=8562056730083)
D 2019-06-02 20:26:06,771 yowsup.axolotl.manager - Initialized AxolotlManager [username=8562056730083, db=/home/kaustubh/.config/yowsup/856_2056730083/axolotl.db]
D 2019-06-02 20:26:06,771 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-06-02 20:26:06,779 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-06-02 20:26:06,779 yowsup.axolotl.manager - load_unsent_prekeys
I 2019-06-02 20:26:06,783 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2019-06-02 20:26:06,783 yowsup.layers.noise.layer - Received auth event
D 2019-06-02 20:26:06,783 yowsup.env.env - Env not set, setting it to android
D 2019-06-02 20:26:06,783 yowsup.env.env - Current env changed to android 
D 2019-06-02 20:26:06,783 yowsup.layers.noise.layer - Performing handshake [username= 8562056730083, passive=True]
D 2019-06-02 20:26:06,784 yowsup.layers.noise.layer - Starting handshake worker
D 2019-06-02 20:26:07,487 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-02 20:26:07,487 yowsup.layers.network.layer - Disconnected
D 2019-06-02 20:26:07,488 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/workers/handshake.py", line 42, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/protocol.py", line 88, in start
    self._machine.finish()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 397, in _trigger
    raise MachineError(msg)
MachineError: "Can't trigger event finish from state init!"
`

**And sometimes I get this:** 

`D 2019-06-02 20:26:51,962 yowsup.config.manager - load_path(path=856_2056730083)
W 2019-06-02 20:26:51,962 yowsup.config.manager - load_path couldn't find the path: 856_2056730083
D 2019-06-02 20:26:51,962 yowsup.config.manager - Detecting config for profile=856_2056730083, dir=/home/kaustubh/.config/yowsup/856_2056730083/
D 2019-06-02 20:26:51,962 yowsup.config.manager - Trying /home/kaustubh/.config/yowsup/856_2056730083/config.json
D 2019-06-02 20:26:51,962 yowsup.config.manager - load_path(path=/home/kaustubh/.config/yowsup/856_2056730083/config.json)
D 2019-06-02 20:26:51,962 yowsup.config.manager - Detected config type: json
D 2019-06-02 20:26:51,962 yowsup.config.manager - Opening config for reading
D 2019-06-02 20:26:51,962 yowsup.config.manager - Loading config
D 2019-06-02 20:26:51,963 yowsup.profile.profile - Constructed Profile(profile_name=856_2056730083)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.5
protobuf       v3.8.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2019-06-02 20:26:52,035 yowsup.stacks.yowstack - Initializing stack
D 2019-06-02 20:26:52,035 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-06-02 20:26:52,035 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fb097c79c50>
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fb097c63790>
D 2019-06-02 20:26:52,036 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-06-02 20:26:52,037 yowsup.stacks.yowstack - Constructed Interface Layer
D 2019-06-02 20:26:52,037 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=856_2056730083))
D 2019-06-02 20:26:52,037 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-06-02 20:26:52,037 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
D 2019-06-02 20:26:52,037 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e12.whatsapp.net', 443))
D 2019-06-02 20:26:52,336 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-06-02 20:26:52,337 yowsup.layers.network.layer - Connected
D 2019-06-02 20:26:52,337 yowsup.axolotl.factory - get_manager(profile_name=856_2056730083, username=8562056730083)
D 2019-06-02 20:26:52,339 yowsup.axolotl.manager - Initialized AxolotlManager [username=8562056730083, db=/home/kaustubh/.config/yowsup/856_2056730083/axolotl.db]
D 2019-06-02 20:26:52,339 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-06-02 20:26:52,349 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-06-02 20:26:52,349 yowsup.axolotl.manager - load_unsent_prekeys
I 2019-06-02 20:26:52,355 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2019-06-02 20:26:52,355 yowsup.layers.noise.layer - Received auth event
D 2019-06-02 20:26:52,355 yowsup.env.env - Env not set, setting it to android
D 2019-06-02 20:26:52,355 yowsup.env.env - Current env changed to android 
D 2019-06-02 20:26:52,355 yowsup.layers.noise.layer - Performing handshake [username= 8562056730083, passive=True]
D 2019-06-02 20:26:52,355 yowsup.layers.noise.layer - Starting handshake worker
D 2019-06-02 20:26:53,057 yowsup.profile.profile - write_config for 856_2056730083
D 2019-06-02 20:26:53,058 yowsup.common.tools - writeProfileData(profile_name=856_2056730083, name=config.json, val=[omitted])
D 2019-06-02 20:26:53,059 yowsup.common.tools - Writing /home/kaustubh/.config/yowsup/856_2056730083/config.json
D 2019-06-02 20:26:56,024 yowsup.layers.logger.layer - rx:
<failure reason="401" location="frc">
</failure>

D 2019-06-02 20:26:56,024 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2019-06-02 20:26:56,025 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-02 20:26:56,025 yowsup.layers.network.layer - Disconnected
D 2019-06-02 20:26:56,025 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False`

I have registered the number successfully by yowsup-cli
Thanks

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
