### ISSUE TITLE
Cannot send messages - "Sent keys were not accepted" exception

### ISSUE THREAD

**Issue by NelsonGaldeman** [tgalal/yowsup#2791]
I'm using yowsup-cli script. First, I registered a new number without issues. Then, I tried to send a test message to my real whatsapp number (Ofc not the same).

**Debug output**

[yowsup log.txt](https://github.com/tgalal/yowsup/files/3249003/yowsup.log.txt)

**Config file**

```
{
    "__version__": 1,
    "cc": "54",
    "client_static_keypair": "********************l9baq7+2LRiQ8YRwsexaFr**************************",
    "edge_routing_info": "******==",
    "expid": "***************==",
    "fdid": "*******************************",
    "id": "**********************",
    "mcc": "000",
    "mnc": "000",
    "phone": "54911*********",
    "pushname": "Prueba",
    "server_static_public": "***************************************",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
```

**Versions**

yowsup-cli     v3.2.0
yowsup         v3.2.3 (master branch code. Commit hash: 7397993ea7e7673321fd9dac3feaeb670358060e)
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.6.1
protobuf       v3.8.0rc1
python 2.7.16
Windows 10

**To Reproduce**

`python yowsup-cli demos -d -E android -c 54************ -s 54************ "test"`

**Expected behavior**

I expect to receive a "test" message on my phone.

**OS (please complete the following information):**

Windows 10.

**Comment by tgalal** [comment]
I made a change that will either fix the issue or narrow down why this happens. You'll have to delete your axolotl.db in order to try it out. According to the attached logs this would be the file at:

````C:\Users\siste\AppData\Local\yowsup\yowsup\54**************\axolotl.db````

 Please try it and report back/close the issue if it's fixed

**Comment by NelsonGaldeman** [comment]
It worked, thank you.

**Comment by Muruganandhan** [comment]
Worked, Thank you!
