### ISSUE TITLE
error: Septup script exited with error: don't know how to compile C/C++ code in platform 'nt' w

### ISSUE THREAD

**Issue by designAP** [tgalal/yowsup#2792]
Hi, I have the following problem, I try to install yowsup, but at the moment of almost finishing its installation it throws:

> error: Septup script exited with error: don't know how to compile C/C++ code in platform 'nt' w

The procedure I perform is:

- Install GCC
- Install ZLIB

All from **minGW** and then install with the following command from the yowsup directory:

python **septup.py** install python setup.py install

also add the patch when creating the distutils.cfg file in the directory:

> PYTHONPATH\Lib\distutils

And in my case it was:

> C:\Python37-32\Lib\distutils

And the content of the patch is:

```
[build]
compiler=mingw32
```
Everything indicated in the basic guide

I'm doing all this process and configuring from **windows 10**

**I would appreciate your prompt support.** I just need to implement this great library that I want to use.

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
