### ISSUE TITLE
Please Update Sample Application

### ISSUE THREAD

**Issue by langioletto** [tgalal/yowsup#2798]
Please Update Sample Application

https://github.com/tgalal/yowsup/wiki/Sample-Application

run.py returns error

```
  File "/usr/local/lib/python3.6/dist-packages/yowsup/config/transforms/config_dict.py", line 27, in reverse
    return self._cls(**data)
TypeError: __init__() got an unexpected keyword argument 'login'
```

Very thanks

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.

**Comment by analistamarcioprado** [comment]
@tgalal congratulations on the initiative, I think @langioletto wants an updated version of the Sample Application.

I for example am using the following versions:
yowsup-cli v3.2.0
using:
   consonance v0.1.3-1
   protobuf v3.8.0
   cryptography v2.7
   yowsup v3.2.3
   dissononce v0.34.3
   python-axolotl v0.2.2

When I try to run run.py from the page (https://github.com/tgalal/yowsup/wiki/Sample-Application) the following error is returned:

root@whatsapp:~/robo# python run.py 
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
AttributeError: type object 'YowCoderLayer' has no attribute 'PROP_DOMAIN'

**Comment by victormatuk** [comment]
still have same error until now a days

When I try to run run.py from the page (https://github.com/tgalal/yowsup/wiki/Sample-Application) the following error is returned:

root@whatsapp:~/robo# python run.py
Traceback (most recent call last):
File "run.py", line 31, in
stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
AttributeError: type object 'YowCoderLayer' has no attribute 'PROP_DOMAIN'
