### ISSUE TITLE
Reply to comment

### ISSUE THREAD

**Issue by mikesalmonuk** [tgalal/yowsup#2801]
Just wondering if you think it would be possible to ever support reply to messages, such as:
![Screenshot_20190529-211227_WhatsApp](https://user-images.githubusercontent.com/5956319/59132474-2f543880-896d-11e9-8470-d9fee488b930.jpg)
(apologies, not actually an issue, but currently can't find a way to reply to a specific message like the screenshot above)

**Comment by Sharissa90** [comment]
yowsup can send quoted message like your picture. just build message with ExtendedTextMessageProtocolEntity and send simple like that..

**Comment by Neolysion** [comment]
@Sharissa90 does receiving such messages work too?

**Comment by Sharissa90** [comment]
@Neolysion yes its work too, you can test it through echoclient demos

**Comment by mikesalmonuk** [comment]
Thanks @Sharissa90 - I can see the class `ExtendedTextMessageProtocolEntity` which extends `ProtomessageProtocolEntity` just like the normal text message, but can you set the body like I have above, with the 👍 for example. The init function of `ExtendedTextMessageProtocolEntity` doesn't have a body param. Do you by any chance have a basic example of how you've done it building a message with ExtendedTextMessageProtocolEntity? Thanks!

**Comment by ersinayaz** [comment]
hi,
have you found a solution to the problem?
-
thanks
