### ISSUE TITLE
CustomApp - Set environment

### ISSUE THREAD

**Issue by NelsonGaldeman** [tgalal/yowsup#2806]
How can I set the android env on a custom app? I've seen a line but I think it may be old and no longer works.

`stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())`

It seems that PROP_RESOURCE is no longer part of YowCoderLayer.

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/blob/master/yowsup-cli#L208
