### ISSUE TITLE
Trigger presence subscription on app startup

### ISSUE THREAD

**Issue by NelsonGaldeman** [tgalal/yowsup#2807]
I succesfully finished my custom app using yowsup, the only issue is that I should trigger the initial execution sending a whatsapp command to the phone.

I've tried to invoke `onConnected` callback but it's not called.

**run.py**
```
from yowsup.stacks import  YowStackBuilder
from layer import TestLayer
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env import YowsupEnv


stackBuilder = YowStackBuilder()

stack = stackBuilder\
	.pushDefaultLayers()\
	.push(TestLayer)\
	.build()

stack.setProfile("54911**********")
YowsupEnv.setEnv("android")
stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
stack.loop()
```

**layer.py**
```
from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.common.tools import Jid
from yowsup.layers.protocol_presence.protocolentities    import *
from yowsup.layers.protocol_messages.protocolentities    import *

class TestLayer(YowInterfaceLayer):

	def onConnected(self):
		print "connected"

	@ProtocolEntityCallback("message")
	def onMessage(self, messageProtocolEntity):
		if messageProtocolEntity.getBody().lower() == "start":
			#initial code here

        #irrelevant code here...
```

"connected" never appears in the console.

**Comment by tgalal** [comment]
you listen to events by apply the decorator `EventCallback` to your method, example:

```python
from yowsup.layers import YowLayerEvent, EventCallback

class Layer:
    @EventCallback(YowNetworkLayer.EVENT_STATE_CONNECTED)
    def method_name_doesnt_matter(self, event):
        do_stuff
```

The `EVENT_STATE_CONNECTED` however only indicates successful connection to server, but no authentication/handshake happened yet. If you actually want to listen to successful authentication,that is, an indication of being ready to send to and receive messages, you don't listen for an event, but decorate your callback method using `@ProtocolEntityCallback("success")`

**Comment by NelsonGaldeman** [comment]
I will try it out, thank you! The library is awesome!
