### ISSUE TITLE
Getting blocked at the time of registration

### ISSUE THREAD

**Issue by chetanunadkat90** [tgalal/yowsup#2810]
**Describe the bug**

Getting blocked every time I am trying to register using yowsup
version 
yowsup-cli v3.2.0
using:
  yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.2
  cryptography v2.7
  protobuf v3.8.0

**Debug output**

Switch on debug logging and include output along with the error or problem you see. If you are using yowsup-cli, this can be enabled by passing ```---debug```.

Please include any output as code blocks for proper formatting. For example:
```

yowsup# yowsup-cli registration --register 385896 --phone 254782808038 --cc 254 -E android --debug
D 2019-06-12 15:27:03,867 yowsup.env.env - Current env changed to android 
D 2019-06-12 15:27:03,868 yowsup.config.manager - load(path_or_profile_name=254782808038, profile_only=False)
D 2019-06-12 15:27:03,868 yowsup.config.manager - _load_path(path=254782808038)
D 2019-06-12 15:27:03,869 yowsup.config.manager - _load_path couldn't find the path: 254782808038
D 2019-06-12 15:27:03,869 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2019-06-12 15:27:03,869 yowsup.config.manager - Detecting config for profile=254782808038, dir=/root/.config/yowsup/254782808038
D 2019-06-12 15:27:03,870 yowsup.config.manager - Trying /root/.config/yowsup/254782808038/config.yo
D 2019-06-12 15:27:03,870 yowsup.config.manager - Trying /root/.config/yowsup/254782808038/config.json
D 2019-06-12 15:27:03,870 yowsup.config.manager - _load_path(path=/root/.config/yowsup/254782808038/config.json)
D 2019-06-12 15:27:03,871 yowsup.config.manager - Detected config type: json
D 2019-06-12 15:27:03,871 yowsup.config.manager - Opening config for reading
D 2019-06-12 15:27:03,871 yowsup.config.manager - Loading config
D 2019-06-12 15:27:03,872 yowsup.profile.profile - Constructed Profile(profile_name=254782808038)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.7
protobuf       v3.8.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2019-06-12 15:27:04,015 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2019-06-12 15:27:04,015 yowsup.profile.profile - Constructed Profile(profile_name=254782808038)
D 2019-06-12 15:27:04,015 yowsup.axolotl.factory - get_manager(profile_name=254782808038, username=254782808038)
D 2019-06-12 15:27:04,017 yowsup.axolotl.manager - Initialized AxolotlManager [username=254782808038, db=/root/.config/yowsup/254782808038/axolotl.db]
D 2019-06-12 15:27:04,018 yowsup.axolotl.manager - load_latest_signed_prekey
D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - Encrypting parameters
D 2019-06-12 15:27:04,022 yowsup.common.http.warequest - pre-encrypt (encoded) parameters = 
cc=254&in=782808038&lg=en&lc=GB&mistyped=6&authkey=b9IMiY4T2qnmsNUeWb1RtkE%2dHt%2djbBNySTnWACl2Lgw&e_regid=awzSpA&e_keytype=BQ&e_ident=i8Ocoqfnrtrq9oWvqMTqqg62vO%5fw79zE0K6mpEIlGD0&e_skey_id=AAAA&e_skey_val=0YuweYjyEdQ0tFviVP7VhtflownEPbppr92I5frcXSE&e_skey_sig=CnXXeW6uq85OcLr2C%2d1spVIO7FaDVfIklFc7ApnO2pbjvmQ1hVi01mmS2aL%5fyB%2dLldatpvE0vOWSA1S0PebtAw&fdid=e6d0f4a6%2d85bc%2d4aa6%2daff6%2dddffce5ff2be&expid=HfXTKlSzRKqEbYsY512JUw&network_radio_type=1&simnum=1&hasinrc=1&pid=7802&rc=0&id=%c8%00%97%eb%f1%d5%9c%c3%f9%28%b8%cdSa9%bb%c8%1a%b3%ec&code=385896
D 2019-06-12 15:27:04,026 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/register, headers={'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'0qV3aQYNKEmfnk28XZ8kUGPtRmGbhcaicTRIrgTUDB+secdyjqsChMCQxDrIjvjBdlBzLJbrUi9/lzzOdJ24rvozMMR9SBiygvyEoU1IeWMR1zdPzo+ana1LFKIKrvZLeusvp2UbrC6xlRLgItwMui35Eotv3BEkgN+fGj2DqmkTtmNsKxhIFrQc3AC+6aMhuzR2XQ7JguutGS3EyNi3EpSB8CD4j0+rvqKsLAQt96fF945TdRcY2Utg6FMdCIKlQp7RCe2mRexPYBbEQGsLJT77d6mf0sbwQTeVu2hcACYpqG4/KeMgRsbMUHhtSMIoRQLJ24/VFb4flKvqq9GFFnFHQW5/b95E+SMXi7Ynq77Ou/kiCQg7phwHXbh8eO1O/hZqIg4w/MPJP5nDstPta0EG+PhFHFZ3cZAW15urNTu82ib+KkImflB0y8cLJOCV+r0vv/5BdPvFzMnxSJGuSLUgBtL69FLfH7nRzEaLv9GqzrbsNaGaZ1acQrAs420uxGg2mQMmXxY0RNf4k9/MFz1OvpSMhT4xuUrZtQsx8toA33S8HhcUOtTp+B17rfDuzdrlIvjnSqj1AcQZWw8I9K/zcDGACfnkblPrvKMoeHfkJv11qAz0Mli9klJfxoi1jonz9bA1kOOfzlqXFcTh+nsfBBQvjQFLYeacv6I2hhGjTMLlamMiLJ8KGH0UMaJloxVR2oEMieVEISkTL9McVE962BV1pqnRmZ+to6TbVFqAEkERPkbahS/uvwZhRuT2QqpCraEkO/5D2VVGTb25Kc6gKO1xY2xWT7Ki0ic=')], reqType=GET, preview=False)
D 2019-06-12 15:27:04,031 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2019-06-12 15:27:04,033 yowsup.common.http.warequest - Sending GET request to /v2/register?ENC=0qV3aQYNKEmfnk28XZ8kUGPtRmGbhcaicTRIrgTUDB%2bsecdyjqsChMCQxDrIjvjBdlBzLJbrUi9%2flzzOdJ24rvozMMR9SBiygvyEoU1IeWMR1zdPzo%2bana1LFKIKrvZLeusvp2UbrC6xlRLgItwMui35Eotv3BEkgN%2bfGj2DqmkTtmNsKxhIFrQc3AC%2b6aMhuzR2XQ7JguutGS3EyNi3EpSB8CD4j0%2brvqKsLAQt96fF945TdRcY2Utg6FMdCIKlQp7RCe2mRexPYBbEQGsLJT77d6mf0sbwQTeVu2hcACYpqG4%2fKeMgRsbMUHhtSMIoRQLJ24%2fVFb4flKvqq9GFFnFHQW5%2fb95E%2bSMXi7Ynq77Ou%2fkiCQg7phwHXbh8eO1O%2fhZqIg4w%2fMPJP5nDstPta0EG%2bPhFHFZ3cZAW15urNTu82ib%2bKkImflB0y8cLJOCV%2br0vv%2f5BdPvFzMnxSJGuSLUgBtL69FLfH7nRzEaLv9GqzrbsNaGaZ1acQrAs420uxGg2mQMmXxY0RNf4k9%2fMFz1OvpSMhT4xuUrZtQsx8toA33S8HhcUOtTp%2bB17rfDuzdrlIvjnSqj1AcQZWw8I9K%2fzcDGACfnkblPrvKMoeHfkJv11qAz0Mli9klJfxoi1jonz9bA1kOOfzlqXFcTh%2bnsfBBQvjQFLYeacv6I2hhGjTMLlamMiLJ8KGH0UMaJloxVR2oEMieVEISkTL9McVE962BV1pqnRmZ%2bto6TbVFqAEkERPkbahS%2fuvwZhRuT2QqpCraEkO%2f5D2VVGTb25Kc6gKO1xY2xWT7Ki0ic%3d
I 2019-06-12 15:27:04,150 yowsup.common.http.warequest - b'{"status":"fail","reason":"blocked","login":"254782808038"}\n'
```

**Comment by chetanunadkat90** [comment]
> **Describe the bug**
> 
> Getting blocked every time I am trying to register using yowsup
> version
> yowsup-cli v3.2.0
> using:
> yowsup v3.2.3
> consonance v0.1.3-1
> dissononce v0.34.3
> python-axolotl v0.2.2
> cryptography v2.7
> protobuf v3.8.0
> 
> **Debug output**
> 
> Switch on debug logging and include output along with the error or problem you see. If you are using yowsup-cli, this can be enabled by passing `---debug`.
> 
> Please include any output as code blocks for proper formatting. For example:
> 
> ```
> yowsup-cli  v3.2.0
> yowsup      v3.2.3
> 
> 
> Copyright (c) 2012-2019 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> W 2019-06-12 15:26:45,038 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
> I 2019-06-12 15:26:47,160 yowsup.common.http.warequest - b'{"login":"254782808038","status":"fail","reason":"temporarily_unavailable","retry_after":300,"sms_wait":300,"voice_wait":300}\n'
> {
>     "__version__": 1,
>     "cc": "254",
>     "client_static_keypair": "QF25RiiZrxi59R6FPW9L7Wfl2YmRFZlt3+DpfbHVsUJv0gyJjhPaqeaw1R5ZvVG2QT4e36NsE3JJOdYAKXYuDA==",
>     "expid": "HfXTKlSzRKqEbYsY512JUw==",
>     "fdid": "e6d0f4a6-85bc-4aa6-aff6-ddffce5ff2be",
>     "id": "yACX6/HVnMP5KLjNU2E5u8gas+w=",
>     "login": "254782808038",
>     "mcc": "000",
>     "mnc": "000",
>     "phone": "254782808038",
>     "sim_mcc": "000",
>     "sim_mnc": "000"
> }
> status: b'fail'
> login: b'254782808038'
> retry_after: 300
> root@whatshash-python-2:~/.config/yowsup# yowsup-cli registration --register 385896 --phone 254782808038 --cc 254 -E android --debug
> D 2019-06-12 15:27:03,867 yowsup.env.env - Current env changed to android 
> D 2019-06-12 15:27:03,868 yowsup.config.manager - load(path_or_profile_name=254782808038, profile_only=False)
> D 2019-06-12 15:27:03,868 yowsup.config.manager - _load_path(path=254782808038)
> D 2019-06-12 15:27:03,869 yowsup.config.manager - _load_path couldn't find the path: 254782808038
> D 2019-06-12 15:27:03,869 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
> D 2019-06-12 15:27:03,869 yowsup.config.manager - Detecting config for profile=254782808038, dir=/root/.config/yowsup/254782808038
> D 2019-06-12 15:27:03,870 yowsup.config.manager - Trying /root/.config/yowsup/254782808038/config.yo
> D 2019-06-12 15:27:03,870 yowsup.config.manager - Trying /root/.config/yowsup/254782808038/config.json
> D 2019-06-12 15:27:03,870 yowsup.config.manager - _load_path(path=/root/.config/yowsup/254782808038/config.json)
> D 2019-06-12 15:27:03,871 yowsup.config.manager - Detected config type: json
> D 2019-06-12 15:27:03,871 yowsup.config.manager - Opening config for reading
> D 2019-06-12 15:27:03,871 yowsup.config.manager - Loading config
> D 2019-06-12 15:27:03,872 yowsup.profile.profile - Constructed Profile(profile_name=254782808038)
> yowsup-cli     v3.2.0
> yowsup         v3.2.3
> consonance     v0.1.3-1
> dissononce     v0.34.3
> python-axolotl v0.2.2
> cryptography   v2.7
> protobuf       v3.8.0
> 
> 
> Copyright (c) 2012-2019 Tarek Galal
> http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> 
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> 
> 
> W 2019-06-12 15:27:04,015 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
> D 2019-06-12 15:27:04,015 yowsup.profile.profile - Constructed Profile(profile_name=254782808038)
> D 2019-06-12 15:27:04,015 yowsup.axolotl.factory - get_manager(profile_name=254782808038, username=254782808038)
> D 2019-06-12 15:27:04,017 yowsup.axolotl.manager - Initialized AxolotlManager [username=254782808038, db=/root/.config/yowsup/254782808038/axolotl.db]
> D 2019-06-12 15:27:04,018 yowsup.axolotl.manager - load_latest_signed_prekey
> D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
> D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
> D 2019-06-12 15:27:04,019 yowsup.common.http.warequest - Encrypting parameters
> D 2019-06-12 15:27:04,022 yowsup.common.http.warequest - pre-encrypt (encoded) parameters = 
> cc=254&in=782808038&lg=en&lc=GB&mistyped=6&authkey=b9IMiY4T2qnmsNUeWb1RtkE%2dHt%2djbBNySTnWACl2Lgw&e_regid=awzSpA&e_keytype=BQ&e_ident=i8Ocoqfnrtrq9oWvqMTqqg62vO%5fw79zE0K6mpEIlGD0&e_skey_id=AAAA&e_skey_val=0YuweYjyEdQ0tFviVP7VhtflownEPbppr92I5frcXSE&e_skey_sig=CnXXeW6uq85OcLr2C%2d1spVIO7FaDVfIklFc7ApnO2pbjvmQ1hVi01mmS2aL%5fyB%2dLldatpvE0vOWSA1S0PebtAw&fdid=e6d0f4a6%2d85bc%2d4aa6%2daff6%2dddffce5ff2be&expid=HfXTKlSzRKqEbYsY512JUw&network_radio_type=1&simnum=1&hasinrc=1&pid=7802&rc=0&id=%c8%00%97%eb%f1%d5%9c%c3%f9%28%b8%cdSa9%bb%c8%1a%b3%ec&code=385896
> D 2019-06-12 15:27:04,026 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/register, headers={'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'0qV3aQYNKEmfnk28XZ8kUGPtRmGbhcaicTRIrgTUDB+secdyjqsChMCQxDrIjvjBdlBzLJbrUi9/lzzOdJ24rvozMMR9SBiygvyEoU1IeWMR1zdPzo+ana1LFKIKrvZLeusvp2UbrC6xlRLgItwMui35Eotv3BEkgN+fGj2DqmkTtmNsKxhIFrQc3AC+6aMhuzR2XQ7JguutGS3EyNi3EpSB8CD4j0+rvqKsLAQt96fF945TdRcY2Utg6FMdCIKlQp7RCe2mRexPYBbEQGsLJT77d6mf0sbwQTeVu2hcACYpqG4/KeMgRsbMUHhtSMIoRQLJ24/VFb4flKvqq9GFFnFHQW5/b95E+SMXi7Ynq77Ou/kiCQg7phwHXbh8eO1O/hZqIg4w/MPJP5nDstPta0EG+PhFHFZ3cZAW15urNTu82ib+KkImflB0y8cLJOCV+r0vv/5BdPvFzMnxSJGuSLUgBtL69FLfH7nRzEaLv9GqzrbsNaGaZ1acQrAs420uxGg2mQMmXxY0RNf4k9/MFz1OvpSMhT4xuUrZtQsx8toA33S8HhcUOtTp+B17rfDuzdrlIvjnSqj1AcQZWw8I9K/zcDGACfnkblPrvKMoeHfkJv11qAz0Mli9klJfxoi1jonz9bA1kOOfzlqXFcTh+nsfBBQvjQFLYeacv6I2hhGjTMLlamMiLJ8KGH0UMaJloxVR2oEMieVEISkTL9McVE962BV1pqnRmZ+to6TbVFqAEkERPkbahS/uvwZhRuT2QqpCraEkO/5D2VVGTb25Kc6gKO1xY2xWT7Ki0ic=')], reqType=GET, preview=False)
> D 2019-06-12 15:27:04,031 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
> D 2019-06-12 15:27:04,033 yowsup.common.http.warequest - Sending GET request to /v2/register?ENC=0qV3aQYNKEmfnk28XZ8kUGPtRmGbhcaicTRIrgTUDB%2bsecdyjqsChMCQxDrIjvjBdlBzLJbrUi9%2flzzOdJ24rvozMMR9SBiygvyEoU1IeWMR1zdPzo%2bana1LFKIKrvZLeusvp2UbrC6xlRLgItwMui35Eotv3BEkgN%2bfGj2DqmkTtmNsKxhIFrQc3AC%2b6aMhuzR2XQ7JguutGS3EyNi3EpSB8CD4j0%2brvqKsLAQt96fF945TdRcY2Utg6FMdCIKlQp7RCe2mRexPYBbEQGsLJT77d6mf0sbwQTeVu2hcACYpqG4%2fKeMgRsbMUHhtSMIoRQLJ24%2fVFb4flKvqq9GFFnFHQW5%2fb95E%2bSMXi7Ynq77Ou%2fkiCQg7phwHXbh8eO1O%2fhZqIg4w%2fMPJP5nDstPta0EG%2bPhFHFZ3cZAW15urNTu82ib%2bKkImflB0y8cLJOCV%2br0vv%2f5BdPvFzMnxSJGuSLUgBtL69FLfH7nRzEaLv9GqzrbsNaGaZ1acQrAs420uxGg2mQMmXxY0RNf4k9%2fMFz1OvpSMhT4xuUrZtQsx8toA33S8HhcUOtTp%2bB17rfDuzdrlIvjnSqj1AcQZWw8I9K%2fzcDGACfnkblPrvKMoeHfkJv11qAz0Mli9klJfxoi1jonz9bA1kOOfzlqXFcTh%2bnsfBBQvjQFLYeacv6I2hhGjTMLlamMiLJ8KGH0UMaJloxVR2oEMieVEISkTL9McVE962BV1pqnRmZ%2bto6TbVFqAEkERPkbahS%2fuvwZhRuT2QqpCraEkO%2f5D2VVGTb25Kc6gKO1xY2xWT7Ki0ic%3d
> I 2019-06-12 15:27:04,150 yowsup.common.http.warequest - b'{"status":"fail","reason":"blocked","login":"254782808038"}\n'
> ```

**Comment by NelsonGaldeman** [comment]
Are you using online numbers or you bought it on a store? Maybe those were numbers previously blocked by whatsapp.

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
