### ISSUE TITLE
Random disconnects in network layer

### ISSUE THREAD

**Issue by mikesalmonuk** [tgalal/yowsup#2811]
After leaving yowsup to run on my server for a few hours and all working alright, I get the occasional disconnected error, where yowsup-cli just disconnects, as picked up the debug logs. This happened early hours of the morning, when I wasn't even chatting with yowsup, and no one else is using my yowsup instance (new number, no other contacts yet), so wasn't after receiving a message or anything.

This is the output from the debug logs, after running `yowsup-cli` echo demo client with the `--debug` flag set:
```
D 2019-06-13 04:20:45,473 yowsup.layers.protocol_iq.layer - ping queue size: 1
D 2019-06-13 04:20:45,473 yowsup.layers.logger.layer - tx:
<iq id="315" xmlns="w:p" type="get" />
D 2019-06-13 04:20:45,702 yowsup.layers.logger.layer - rx:
<iq t="1560399645" type="result" from="447********5@s.whatsapp.net" id="315" />
D 2019-06-13 04:21:35,522 yowsup.layers.protocol_iq.layer - ping queue size: 1
D 2019-06-13 04:21:35,523 yowsup.layers.logger.layer - tx:
<iq id="316" xmlns="w:p" type="get" />
D 2019-06-13 04:21:35,751 yowsup.layers.logger.layer - rx:
<iq t="1560399695" type="result" from="447********5@s.whatsapp.net" id="316" />
D 2019-06-13 04:22:25,553 yowsup.layers.protocol_iq.layer - ping queue size: 1
D 2019-06-13 04:22:25,553 yowsup.layers.logger.layer - tx:
<iq id="317" xmlns="w:p" type="get" />
D 2019-06-13 04:22:25,783 yowsup.layers.logger.layer - rx:
<iq t="1560399745" type="result" from="447********5@s.whatsapp.net" id="317" />
D 2019-06-13 04:22:54,976 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-13 04:22:54,976 yowsup.layers.network.layer - Disconnected
D 2019-06-13 04:22:54,977 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-06-13 04:22:54,977 yowsup.layers.protocol_iq.layer - stopping ping thread
D 2019-06-13 04:22:55,586 yowsup.layers.protocol_iq.layer - YowPingThread-2 - ping thread stopped
```

I've not included any of the config info, as I'm using a standard installation of yowsup, all's working fine, but it's just randomly i get the disconnect issue, sometimes after an hour or two, sometimes after many hours, and wonder if anyone else has come across the above too?

**Comment by tgalal** [comment]
The diconnection is not triggered by yowsup, but because of network/server causing the connection to be dropped. I think it's normal to always expect random disconnections; there is no information how WA's servers behave, for example whether connection are dropped in some circumstances. You can react by listening to `YowNetworkLayer.EVENT_STATE_DISCONNECTED` and recovering the connection from there.

**Comment by mikesalmonuk** [comment]
👍 Thanks for the feedback. Just wanted to check it wasn't a networking issue within yowsup, and random disconnects are probably expected like mine above. I'll put a listener on `YowNetworkLayer.EVENT_STATE_DISCONNECTED` and handle that connected state change accordingly.
