### ISSUE TITLE
send message using python

### ISSUE THREAD

**Issue by heavener93630939gustavo** [tgalal/yowsup#2820]
I want to use python to send message sending message with yowsupcli is working. i have this code for python But i do not know what is CREDENTIALS.

from yowsup.demos import sendclient

stack = stackBuilder\
        .pushDefaultLayers()\
        .push(EchoLayer)\
        .build()
config_manager = ConfigManager()
config = config_manager.load_path("/path/to/config")
config.login = "49XXXXXXX"
profile = YowProfile(config.login,config)
stack.setProfile(profile)

unSender=sendclient.YowsupSendStack(CREDENTIALS, [(['mobile_number', 'message_text'])],True)
unSender.start()

**Comment by tgalal** [comment]
use the demos as reference instead of import and using them in your code
