### ISSUE TITLE
Send media

### ISSUE THREAD

**Issue by petrium** [tgalal/yowsup#2821]
Hello! Sorry for my english.

I can not send media.
Does this release (yowsup version: 3.2.3, yowsup-cli version: 3.2.0) support media sending?

While testing image sending (python, yowsup-cli), revealed the following errors:
1. In mediauploader not transmitted required second argument "config_or_profile":
https://github.com/tgalal/yowsup/blob/7f336c7c300ffe00e04be339f029ff23679fa1c1/yowsup/layers/protocol_media/mediauploader.py#L18
https://github.com/tgalal/yowsup/blob/7f336c7c300ffe00e04be339f029ff23679fa1c1/yowsup/common/http/warequest.py#L43
2. In mediauploader fail response - result["url"]=None
https://github.com/tgalal/yowsup/blob/7f336c7c300ffe00e04be339f029ff23679fa1c1/yowsup/layers/protocol_media/mediauploader.py#L138
3. In "demos/cli/layer.py" method "fromFilePath" not defined in ImageDownloadableMediaMessageProtocolEntity:
https://github.com/tgalal/yowsup/blob/7f336c7c300ffe00e04be339f029ff23679fa1c1/yowsup/demos/cli/layer.py#L531
For the test, I run in yowsup-cli:
/image send {phonenumber} {/path-to/image.jpeg}
This also applies to the example in wiki: [https://github.com/tgalal/yowsup/wiki/Upload-and-send-Media]()

Is there a working example send media in python or yowsup-cli?

**Comment by tgalal** [comment]
Please the issues search box

**Comment by Jeffrey-Kimani** [comment]
I have the same problem too, where is the duplicate issue log anyway?

**Comment by Jeffrey-Kimani** [comment]
Can't seem to find it

**Comment by bryanjhv** [comment]
#2503 #2628 #2682 and I can keep counting.
Wanna see X feature implemented? Submit a PR.

**Comment by brahimwakrim87** [comment]
Hi , anyone  has resolved the issue ,
