### ISSUE TITLE
keepalive question again

### ISSUE THREAD

**Issue by tsifra** [tgalal/yowsup#2824]
I'm playing with demo echo app. After several hours of working it stops answering messages. I've tried to investigate. No luck. Connection lost. All info that i found is outdated (2015).

There is record in changelog [2.2.78] - 2015-02-17 about this "Keep connection alive through periodic pinging". But i'm using latest version 3.2.3

I've added to Echo layer
```
    @ProtocolEntityCallback("iq")
    def onIq(self, entity):
        print("[iq] {}".format(str(datetime.now().strftime("%Y-%m-%d %H:%M"))))
```
It confirms that iq messages are not there after 2-3 hours. Please help to find docs or tickets about this issue. Trying to implement support chat for customers.

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
