### ISSUE TITLE
handshake_failed_exception

### ISSUE THREAD

**Issue by carlosqlz** [tgalal/yowsup#2827]
Hello, I have already registered, but when trying to send a message it is returned:

root@ubuntuZabbix:/usr/lib/zabbix/alertscripts/yowsup# ./yowsup-cli demos -c ~/.config/yowsup/55xxxxxxxx/config.json -s 55xxxxxxxxx "teste2" -d
D 2019-06-24 22:48:15,883 yowsup.config.manager - load(path_or_profile_name=/root/.config/yowsup/55xxxxxxxx/config.json, profile_only=False)
D 2019-06-24 22:48:15,883 yowsup.config.manager - _load_path(path=/root/.config/yowsup/55xxxxxxx/config.json)
D 2019-06-24 22:48:15,883 yowsup.config.manager - Detected config type: json
D 2019-06-24 22:48:15,883 yowsup.config.manager - Opening config for reading
D 2019-06-24 22:48:15,883 yowsup.config.manager - Loading config
D 2019-06-24 22:48:15,883 yowsup.profile.profile - Constructed Profile(profile_name=55xxxxxx)
Traceback (most recent call last):
  File "./yowsup-cli", line 722, in <module>
    if not parser.process():
  File "./yowsup-cli", line 610, in process
    self.startSendClient()
  File "./yowsup-cli", line 649, in startSendClient
    from yowsup.demos import sendclient
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/layers/noise/workers/handshake.py", line 3, in <module>
    from consonance.exceptions.handshake_failed_exception import HandshakeFailedException
ImportError: No module named handshake_failed_exception

yowsup-cli v3.2.0
using:
  consonance v0.1.0
  protobuf v3.6.1
  cryptography v2.6.1
  yowsup v3.2.3
  dissononce v0.34.3
  python-axolotl v0.1.42

**Comment by carlosqlz** [comment]
News
After reinstalling with the correct dependencies, a new error follows:


D 2019-06-25 00:41:56,015 yowsup.config.manager - load(path_or_profile_name=/root/.config/yowsup/55xxxxx/config.json, profile_only=False)
D 2019-06-25 00:41:56,015 yowsup.config.manager - _load_path(path=/root/.config/yowsup/55xxxx/config.json)
D 2019-06-25 00:41:56,015 yowsup.config.manager - Detected config type: json
D 2019-06-25 00:41:56,015 yowsup.config.manager - Opening config for reading
D 2019-06-25 00:41:56,015 yowsup.config.manager - Loading config
D 2019-06-25 00:41:56,015 yowsup.profile.profile - Constructed Profile(profile_name=xxxx)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.7
protobuf       v3.8.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2019-06-25 00:41:56,064 yowsup.stacks.yowstack - Initializing stack
D 2019-06-25 00:41:56,064 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-06-25 00:41:56,064 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f5e1af9ab90>
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f5e1af826d0>
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-06-25 00:41:56,065 yowsup.stacks.yowstack - Constructed Interface Layer
D 2019-06-25 00:41:56,066 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=55xxxx))
D 2019-06-25 00:41:56,066 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-06-25 00:41:56,066 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
D 2019-06-25 00:41:56,066 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e2.whatsapp.net', 443))
D 2019-06-25 00:41:56,214 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-06-25 00:41:56,214 yowsup.layers.network.layer - Connected
D 2019-06-25 00:41:56,214 yowsup.axolotl.factory - get_manager(profile_name=55xxxx, username=55xxxx)
D 2019-06-25 00:41:56,214 yowsup.axolotl.manager - Initialized AxolotlManager [username=55xxxx, db=/root/.config/yowsup/55xxxxx/axolotl.db]
D 2019-06-25 00:41:56,215 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-06-25 00:41:56,237 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-06-25 00:41:56,237 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-06-25 00:41:56,237 yowsup.layers.noise.layer - Received auth event
D 2019-06-25 00:41:56,237 yowsup.env.env - Env not set, setting it to android
D 2019-06-25 00:41:56,237 yowsup.env.env - Current env changed to android
D 2019-06-25 00:41:56,237 yowsup.layers.noise.layer - Performing handshake [username= 55xxxx, passive=True]
D 2019-06-25 00:41:56,237 yowsup.layers.noise.layer - Starting handshake worker
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/zabbix/alertscripts/yowsup/yowsup/layers/noise/workers/handshake.py", line 42, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/protocol.py", line 84, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/handshake.py", line 84, in perform
    cipherstatepair = self._start_handshake_ik(stream, client_payload, dissononce_s, dissononce_rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/handshake.py", line 179, in _start_handshake_ik
    self._handshakestate.write_message(client_payload.SerializeToString(), message_buffer)
  File "build/bdist.linux-x86_64/egg/dissononce/extras/processing/handshakestate_forwarder.py", line 16, in write_message
    return self._handshakestate.write_message(payload, message_buffer)
  File "build/bdist.linux-x86_64/egg/dissononce/extras/processing/handshakestate_guarded.py", line 98, in write_message
    result = self._handshakestate.write_message(payload, message_buffer)
  File "build/bdist.linux-x86_64/egg/dissononce/processing/impl/handshakestate.py", line 147, in write_message
    self._e = self._dh.generate_keypair()
  File "build/bdist.linux-x86_64/egg/dissononce/dh/x25519/x25519.py", line 28, in generate_keypair
    private = x25519.X25519PrivateKey.generate()
  File "/usr/local/lib/python2.7/dist-packages/cryptography-2.7-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.

D 2019-06-25 00:42:06,664 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-25 00:42:06,664 yowsup.layers.network.layer - Disconnected
D 2019-06-25 00:42:06,664 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
^C

**Comment by carlosqlz** [comment]
News

After searching, I found issue 2658, with the command:
pip install cryptography
solved my problem, I'm getting send messages :)

**Comment by pu8asr** [comment]
I have installed all dependencies but this erros:
root@administrador:~# pip install cryptography
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages/cryptography-3.1.1-py2.7-linux-x86_64.egg
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages/cffi-1.14.3-py2.7-linux-x86_64.egg (from cryptography)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages/enum34-1.1.10-py2.7.egg (from cryptography)
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/dist-packages/ipaddress-1.0.23-py2.7.egg (from cryptography)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from cryptography)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages/pycparser-2.20-py2.7.egg (from cffi!=1.11.3,>=1.8->cryptography)

root@administrador:~# /root/yowsup/yowsup-cli demos --config /root/yowsup/config.json --send 5592"MyNumber" "Message."
/usr/local/lib/python2.7/dist-packages/dissononce-0.34.3-py2.7.egg/dissononce/dh/x25519/x25519.py:1: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
Traceback (most recent call last):
  File "/root/yowsup/yowsup-cli", line 722, in <module>
    if not parser.process():
  File "/root/yowsup/yowsup-cli", line 610, in process
    self.startSendClient()
  File "/root/yowsup/yowsup-cli", line 649, in startSendClient
    from yowsup.demos import sendclient
  File "/root/yowsup/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/root/yowsup/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/root/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/root/yowsup/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/root/yowsup/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/root/yowsup/yowsup/layers/noise/workers/handshake.py", line 3, in <module>
    from consonance.exceptions.handshake_failed_exception import HandshakeFailedException
ImportError: No module named handshake_failed_exception

Anyone idea?!

**Comment by hossinasaadi** [comment]
@pu8asr 
try install exact version of **consonance** 
  consonance v0.1.3-1
