### ISSUE TITLE
config.id is not set

### ISSUE THREAD

**Issue by nosuchip** [tgalal/yowsup#2828]
**Describe the bug**

Unable to confirm account by SMS

**Debug output**

```
yowsup-cli registration --register 497539 --config-phone 79522433000 --config-cc 7
E 2019-06-26 16:32:46,183 yowsup.config.manager - Could not find a config for username=79522433000, paths checked: /home/alp/.config/yowsup/79522433000/config.yo:/home/alp/.config/yowsup/79522433000/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/home/alp/proj/.venvs/wassup/bin/yowsup-cli", line 687, in <module>
    if not parser.process():
  File "/home/alp/proj/.venvs/wassup/bin/yowsup-cli", line 352, in process
    self.handleRegister(self.args["register"], config)
  File "/home/alp/proj/.venvs/wassup/bin/yowsup-cli", line 382, in handleRegister
    req = WARegRequest(config, code)
  File "/home/alp/proj/.venvs/wassup/lib/python3.7/site-packages/yowsup/registration/regrequest.py", line 38, in __init__
    raise ValueError("config.id is not set.")
ValueError: config.id is not set.
```

**Config file**
Config file is missing, only file `axolotl.db` file exists under `~/.config/yowsup/79522433000/`

**Versions**

yowsup-cli  v3.2.0
yowsup      v3.2.3
Python 3.7.3
dissononce==0.34.3
consonance==0.1.2
python-axolotl==0.2.2
python-axolotl-curve25519==0.4.1.post2
yowsup==3.2.3

Please include python version, yowsup version, yowsup-cli version, as well as versions for consonance, dissononce, python-axolotl, and cryptography packages. Some of this information can be obtained if you run yowsup-cli with ```--debug``` flag, or through ```yowsup-cli version```.

If you are not using a released version but code directly from the repository, please indicate the commit hash.

**To Reproduce**

- SMS was received using my code:
```
        YowsupEnv.setEnv('android')

        config = YowConfig(
            phone=data['phone'],
            cc=data['cc'],
            mcc='000',
            mnc='000',
            sim_mcc="000",
            sim_mnc="000",
        )

        codeReq = WACodeRequest('sms', config)
        result = codeReq.send()
```

that returned response 
```
{
    "code": null,
    "length": 6,
    "login": "79522433000",
    "method": "sms",
    "param": null,
    "reason": null,
    "retry_after": 65,
    "sms_wait": 65,
    "status": "sent",
    "type": null,
    "voice_wait": 65
}
```

- Trying to active account using yowsup-cli:
```
yowsup-cli registration --register CODE_FROM_SMS --config-phone 79522433000 --config-cc 7
```
but got exception (see in "Debug output").

**Expected behavior**
Response received without exceptions.

**OS (please complete the following information):**
Linux Arch x64

**Comment by nosuchip** [comment]
Found. It is crucial to save config or pass ID value to my configuration manually

**Comment by nickdeng1216** [comment]
I am facing the same issue now. Could you please advice how to save config manually? What is the content of this config?

**Comment by nickdeng1216** [comment]
> Found. It is crucial to save config or pass ID value to my configuration manually

I am facing the same issue now. Could you please advice how to save config manually? What is the content of this config?

**Comment by aniwn88480857** [comment]
Did you solve this problem?
I also encountered a similar situation.
error is
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 369, in handleRequestCode
    self._config_manager.save(self._config)
TypeError: save() missing 1 required positional argument: 'config'
