### ISSUE TITLE
Setup Problem with Consonase 0.1.3-1

### ISSUE THREAD

**Issue by WandersonSangreal** [tgalal/yowsup#2830]
**Describe the bug**

What happened? Please make sure to first search existing issues and read the [FAQ](https://github.com/tgalal/yowsup/wiki/FAQ) in case this is already addressed.

On Setup ```python setup.py install``` the process failed. I just access the page mentioned in the error "https://pypi.org/simple/consonance/" and the version wasn't there 'consonance==0.1.3-1'

Please include any output as code blocks for proper formatting. For example:
```
Installed /usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg
Processing dependencies for yowsup==3.2.3
Searching for consonance==0.1.3-1
Reading https://pypi.python.org/simple/consonance/
No local packages or download links found for consonance==0.1.3-1
error: Could not find suitable distribution for Requirement.parse('consonance==0.1.3-1')

```

**OS (please complete the following information):**
Which OS did you encounter the bug on?

Debian 8.9

**Additional context**

**Comment by tgalal** [comment]
consonance-0.1.3.post1.tar.gz is consonance==0.1.3-1

**Comment by WandersonSangreal** [comment]
I cleaned up the template to not to cause confusion...

**Comment by danielct59** [comment]
root@mk-auth:~# yowsup-cli demos -c /root/.config/yowsup/558888689819/config.json -e -d
D 2019-06-27 10:09:39,356 yowsup.config.manager - load(path_or_profile_name=/root/.config/yowsup/558888689819/config.json, profile_only=False)
D 2019-06-27 10:09:39,356 yowsup.config.manager - _load_path(path=/root/.config/yowsup/558888689819/config.json)
D 2019-06-27 10:09:39,357 yowsup.config.manager - Detected config type: json
D 2019-06-27 10:09:39,357 yowsup.config.manager - Opening config for reading
D 2019-06-27 10:09:39,357 yowsup.config.manager - Loading config
D 2019-06-27 10:09:39,358 yowsup.profile.profile - Constructed Profile(profile_name=558888689819)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.7
protobuf       v3.9.0rc1


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2019-06-27 10:09:39,666 yowsup.stacks.yowstack - Initializing stack
D 2019-06-27 10:09:39,667 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-06-27 10:09:39,668 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-06-27 10:09:39,668 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-06-27 10:09:39,669 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-06-27 10:09:39,669 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-06-27 10:09:39,669 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f7a4cc87320>
D 2019-06-27 10:09:39,669 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f7a4af7cbe0>
D 2019-06-27 10:09:39,670 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-06-27 10:09:39,670 yowsup.stacks.yowstack - Constructed Interface Layer
D 2019-06-27 10:09:39,670 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=558888689819))
D 2019-06-27 10:09:39,670 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-06-27 10:09:39,670 yowsup.layers.network.layer - Connecting to e1.whatsapp.net:443
D 2019-06-27 10:09:39,670 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e1.whatsapp.net', 443))
D 2019-06-27 10:09:39,707 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-06-27 10:09:39,708 yowsup.layers.network.layer - Connected
D 2019-06-27 10:09:39,708 yowsup.axolotl.factory - get_manager(profile_name=558888689819, username=558888689819)
D 2019-06-27 10:09:39,709 yowsup.axolotl.manager - Initialized AxolotlManager [username=558888689819, db=/root/.config/yowsup/558888689819/axolotl.db]
D 2019-06-27 10:09:39,709 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-06-27 10:09:39,724 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-06-27 10:09:39,724 yowsup.axolotl.manager - load_unsent_prekeys
I 2019-06-27 10:09:39,763 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2019-06-27 10:09:39,764 yowsup.layers.noise.layer - Received auth event
D 2019-06-27 10:09:39,764 yowsup.env.env - Env not set, setting it to android
D 2019-06-27 10:09:39,764 yowsup.env.env - Current env changed to android
D 2019-06-27 10:09:39,765 yowsup.layers.noise.layer - Performing handshake [username= 558888689819, passive=True]
D 2019-06-27 10:09:39,765 yowsup.layers.noise.layer - Starting handshake worker
D 2019-06-27 10:09:42,977 yowsup.layers.logger.layer - rx:
<failure location="vll" reason="403" />
D 2019-06-27 10:09:42,978 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2019-06-27 10:09:42,978 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-27 10:09:42,978 yowsup.layers.network.layer - Disconnected
D 2019-06-27 10:09:42,978 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by modcastro** [comment]
just run: pip install consonance==0.1.3-1

**Comment by tgalal** [comment]
@danielct59 are you lost?

**Comment by WandersonSangreal** [comment]
@tgalal, recently I've tried to install it again and it worked... so I think it's a repository problem with consonance... I'm not sure, so if you agree you can close! Thanks for considering...

**Comment by danielct59** [comment]
@tgalal  Consegui resolver, Muito Obrigado
