### ISSUE TITLE
Verify number registered in whatsapp (Sync?)

### ISSUE THREAD

**Issue by carjr** [tgalal/yowsup#2840]
I'm trying to check if a number has whatsapp or not, but I can not, can anyone help me?

**Comment by carjr** [comment]
?

**Comment by tgalal** [comment]
Hi @carjr. It's is neither a chat room nor a help forum where you just ask people to "help you out", so please don't treat it as such. Things you could instead do:

- Search previous issues
- Look at demos
- Post exactly what you have tried and what problem you faced. A simple "I can not do something" is useless and wastes everyone's time asking you describe your problem properly.

Nevertheless, I can refer you to  [contacts_sync function in this demo](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L415) which does the same thing. If you still have questions on usage, search previous issues. If you encounter a problem (for example, it's not working,) please open a new issue and follow the bug report template. Thanks!

**Comment by carjr** [comment]
Excuse!!! So see if this looks better, I'm using the following version

yowsup-cli 3.2.0
yowsup 3.2.3

when running yowsup-cli demo - S XXXXXXX -c whats.config

I get the following return:


I 2019-07-19 09: 53: 03,893 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
I Q:
ID: 1
Type: result
from: XXXXXXXXXX@s.whatsapp.net
Wait: 462066
Version: 1563540416863447
In Numbers:
Out Numbers: XXXXXXX
Invalid Numbers:

Regardless if the number I'm querying has whatsapp or not, and I can not figure out what I'm doing wrong, I'd just like to identify if that number has whatsapp or not

**Comment by tgalal** [comment]
- In Numbers are valid whatsapp users
- Out numbers are non-whatsapp users
- Invalid numbers are not valid in terms of formatting with respect to being phone numbers.
