### ISSUE TITLE
consonance dependency fail during installation

### ISSUE THREAD

**Issue by AL-Kateb** [tgalal/yowsup#2843]
**Describe the bug**

Cannot install yowsup, whenever I run `python setup.py install` I get the following error:

```
Reading https://pypi.python.org/simple/consonance/
No local packages or download links found for consonance==0.1.3-1
error: Could not find suitable distribution for Requirement.parse('consonance==0.1.3-1')

```

**Debug output**
If I run `yowsup-cli --debug` I get 

```
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: consonance==0.1.3-1

```

**Versions**
python -V
Python 2.7.5

**OS (please complete the following information):**
Linux CentOS-75-64-minimal 3.10.0-862.14.4.el7.x86_64

I've cloned the consonance git and ran python setup.py install, and everything ran smoothly, I still fail to install yoswsup though.
I came across #2830 but there's nothing in that issue that could constitute a solution

Thanks

**Comment by godsondawuni** [comment]
please try this 
[root@localhost yowsup]# pip install consonance
[root@localhost yowsup]# python setup.py install

**Comment by bryanjhv** [comment]
Which is your `pip` version?
You could try upgrading `pip`.

**Comment by AL-Kateb** [comment]
Thanks very much, this worked,

**Comment by MaheshPandhega** [comment]
> I had the same issue and this is how i resolved it
> first install consonance
> [root@localhost yowsup]# pip install consonance
> then
> [root@localhost yowsup]# python setup.py install
> you can also upgrage your pip version
> [root@localhost yowsup]# pip install --upgrade pip



> I had the same issue and this is how i resolved it
> first install consonance
> [root@localhost yowsup]# pip install consonance
> then
> [root@localhost yowsup]# python setup.py install
> you can also upgrage your pip version
> [root@localhost yowsup]# pip install --upgrade pip

I'm still having an error
is there another way?

Python 2.7.5
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
