### ISSUE TITLE
<failure reason="403" location="frc" />

### ISSUE THREAD

**Issue by everaldoscabral** [tgalal/yowsup#2848]
D 2019-08-05 17:08:49,923 yowsup.env.env - Current env changed to android
D 2019-08-05 17:08:49,923 yowsup.layers.noise.layer - Performing handshake [username= 55799193XXX, passive=True]
D 2019-08-05 17:08:49,924 yowsup.layers.noise.layer - Starting handshake worker
D 2019-08-05 17:08:52,323 yowsup.layers.logger.layer - rx:
<failure reason="403" location="frc" />
D 2019-08-05 17:08:52,324 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2019-08-05 17:08:52,324 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-08-05 17:08:52,324 yowsup.layers.network.layer - Disconnected
D 2019-08-05 17:08:52,324 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

Version:

[root@zabbix-server yowsup-master]# python3.6 yowsup-cli version
yowsup-cli v3.2.0
using:
  yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.2
  cryptography v2.7
  protobuf v3.9.0

**Comment by everaldoscabral** [comment]
Solved.

**Comment by solovevpv** [comment]
@everaldoscabral how you solved?

**Comment by everaldoscabral** [comment]
> @everaldoscabral how you solved?

https://github.com/tgalal/yowsup/commit/b0b80e1dbbb0103d7e990f2b68660addb46a942f

Upgrade WA 3.0
