### ISSUE TITLE
Error getting lastseen information

### ISSUE THREAD

**Issue by pzverr** [tgalal/yowsup#2850]
Hi!
Please tell me how to get last time seen information correctly.
I am trying this command in yowsup-cli:
```
/L
/contacts sync +my-real-number
/contact lastseen my-real-number@s.whatsapp.net
```
And i receiving error message yowsup.demos.cli.layer - Error getting lastseen information for my-real-number@s.whatsapp.net
My whatsapp profile is open.
I do not understand what could be the mistake...

yowsup-cli v3.2.0
Using yowsup v3.2.3

**Comment by bryanjhv** [comment]
More information could be useful.
Anyway, I don't think WhatsApp lets you see **your own** last seen.

**Comment by NelsonGaldeman** [comment]
> 
> 
> More information could be useful.
> Anyway, I don't think WhatsApp lets you see **your own** last seen.

It's "imposible" because you need to be "available" in order to get last seen/online status from WhatsApp so your own last seen will **always** return the current time.

**Comment by pampasdev** [comment]
This fails for other contacts as well now.

**Comment by julioo-cain** [comment]
Hi @pzverr 
did you solve the problem?
i faced with this too!

**Comment by pzverr** [comment]
Hi. @julioo-cain
I could not solve this problem :(

**Comment by Pyatka-Ubiyca** [comment]
me too

**Comment by lauriolasw** [comment]
Same here:

/L 
[connected]: /presence available
[connected]: /contact sync <nn>  
[connected]: /statuses get <nn> 
   statuses_get result: [ (jid) ...]  OK
[connected]: /contact lastseen <jid>
   E (timestamp) yowsup.demos.cli.layer - Error getting lastseen information for <jid>

Thanks
