### ISSUE TITLE
Can't register my device

### ISSUE THREAD

**Issue by OlegSavchuk** [tgalal/yowsup#2854]
When I try to register my device with the next command:

`yowsup-cli registration -r sms --phone 380####### --cc 380 --mcc 2## --mnc 03 --env android`

I'm facing with the next error:

> Traceback (most recent call last):
>   File "/bin/yowsup-cli", line 5, in <module>
>     pkg_resources.run_script('yowsup2==2.5.0', 'yowsup-cli')
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
>     execfile(script_filename, namespace, namespace)
>   File "/usr/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
>     if not parser.process():
>   File "/usr/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 189, in process
>     self.handleRequestCode(self.args["requestcode"], config)
>   File "/usr/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 206, in handleRequestCode
>     method
> TypeError: __init__() takes exactly 3 arguments (8 given)

**Comment by devalexanderdaza** [comment]
@tgalal Hi! This project dead? Thanks for answer!

**Comment by tgalal** [comment]
you are using an outdated yowsup version
