### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by xmaster17** [tgalal/yowsup#2856]
When you run the /L command. How to fix?

![image](https://user-images.githubusercontent.com/54384273/63482704-8bc1f100-c4a2-11e9-9e2e-57ec1b20e08f.png)

**Comment by bryanjhv** [comment]
Please paste the command you used to start `yowsup-cli`. People can't guess how are you doing things that it goes wrong. As far as I can tell (given the almost nothing information you provided), you're not supplying the CLI a config file correctly.

**Comment by xmaster17** [comment]
@bryanjhv   
`yowsup-cli demos -c 77******* --yowsup`  

if used command `yowsup-cli demos -c /.config/yowsup/77*******/config.json --yowsup`  
to
![image](https://user-images.githubusercontent.com/54384273/63486770-8324e700-c4b1-11e9-82d5-792b727249af.png)

**Comment by bryanjhv** [comment]
Please make sure the config exists, line 6 in your image shows clearly that no config file was found.
Side note: please paste your output as code blocks, it's easier to read, manage, and also downloads faster.

**Comment by xmaster17** [comment]
Screenshots were already ready. I've tried a lot of things.

![image](https://user-images.githubusercontent.com/54384273/63487263-33471f80-c4b3-11e9-87ab-06a8fe418e31.png)

**Comment by bryanjhv** [comment]
Please copy this script into a text file (replacing it accordingly) and run it.
Then paste the output of that here.

```python
try:
    open('/.config/yowsup/**********/config.json')
except:
    print('could not read file')
```

**Comment by xmaster17** [comment]
@bryanjhv Yes shows error from print (

**Comment by bryanjhv** [comment]
Ok. Check your paths, maybe the shell you're using is mapping directories or the like, and while it shows a successful `cat`, maybe that file doesn't exist in filesystem (and Python won't apply those quirks when reading files).
Maybe a `readlink -f` could show the real path to the file, or just copy files (`cp -rf /.config/yowsup ~/.config`) to where Yowsup expects them, and call the CLI without any config argument.

**Comment by xmaster17** [comment]
If you run python and enter the command open('/.config/yowsup/77***/config.json') then all ok  
если add .read() then the file data is visible

It turns out that python normally reads from this path

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
