### ISSUE TITLE
Can't register - bad_param number

### ISSUE THREAD

**Issue by GM12Tick** [tgalal/yowsup#286]
Hi,
Tried to register and failed. 
python yowsup-cli -c user.conf -r sms -d
{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.15 S40Version/14.26 Device/
Nokia302'}
cc=1&in=786275***_&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=e312b0eb24288f5c9bfd7e2328fb31ec&token=4d80047a049129f5b6c93298931608b3
Opening connection to v.whatsapp.net
Sending GET request to /v2/code?cc=1&in=786275**_*&lc=US&lg=en&mcc=000&mnc=000&method=sms&id=e312b0eb24288f5c9bfd7e2328fb31ec&token=4d80047a049129f5b6c93298931608b3
WACodeRequest:  {"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param

Conf:
cc=1 #if not specified it will be autodetected
phone=1786275****
id=0000000000
password=MDAwMDAwMDAwMA==
Any idea? tried voice / sms still the same.

**Comment by khaliltoubia** [comment]
help  I have the same problem   



DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.328 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=70&in=226442&lc=GB&lg=en&sim_mcc=961&sim_mnc=451&mcc=961&mnc=451&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=560&rchash=f5da69761dbb847c3eed1003e47ad8736f7eb31b537f6bf03001b28e6e9a41c9&anhash=%E2%84%28%1F8e%02%EC%814N%E7E%01%DE%3ClZ%1A%16&extexist=1&extstate=1&token=nFtJmsJ7j2WfY3GANNOw73KlgyI%3D&id=3%7Ei%07%5Cw%05%9D%8F%F4%95%0F%5C%1FWG%C9%97%BE%1F
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=70&in=226442&lc=GB&lg=en&sim_mcc=961&sim_mnc=451&mcc=961&mnc=451&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=560&rchash=f5da69761dbb847c3eed1003e47ad8736f7eb31b537f6bf03001b28e6e9a41c9&anhash=%E2%84%28%1F8e%02%EC%814N%E7E%01%DE%3ClZ%1A%16&extexist=1&extstate=1&token=nFtJmsJ7j2WfY3GANNOw73KlgyI%3D&id=3%7Ei%07%5Cw%05%9D%8F%F4%95%0F%5C%1FWG%C9%97%BE%1F
INFO:yowsup.common.http.warequest:{"login":"70226442","status":"fail","reason":"bad_param","param":"number"}
