### ISSUE TITLE
error when receiving media

### ISSUE THREAD

**Issue by Gabriel712** [tgalal/yowsup#2861]
Hello everyone,
I received some media messages. (PKMSG)
and YOWSUP goes into some loop and receives no other message but I can send messages.
I believe there should be an error in LAYER_RECEIVE in the funct Retry...

logger.warning("InvalidMessage for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))

I tested on Linux and Windows 

yowsup version: 3.2.3
yowsup-cli version: 3.2.0
requires:
- python>=2.7,<=3.7
- consonance==0.1.3-1
- python-axolotl==0.2.2
- protobuf>=3.6.0
- six==1.10

an additional note,
i broke some loop in retry and improved

**Comment by tgalal** [comment]
duplicate #2720
