### ISSUE TITLE
REGISTRATION FAILED || Bad param : number

### ISSUE THREAD

**Issue by adrijanb** [tgalal/yowsup#2865]
**Describe the bug**

I just wanted to register a new number on WhatsApp via yowsup. Unfortunately, this is currently not possible for whatever reason. I have already set the new version of WhatsApp 2.19.244 and the hash.

2019-09-06 13:38:26,553 yowsup.common.http.warequest - {"login":"1301*******","status":"fail","reason":"bad_param","param":"number"}

status: fail
reason: bad_param
param: number
login: 1301*******

Command used to register:
yowsup-cli registration --requestcode voice --config-phone 1301******* --config-cc 1 --config-mcc 310 --config-mnc 260

**Versions**

yowsup-cli v3.2.0
using:
  consonance v0.1.3-1
  protobuf v3.9.1
  cryptography v2.5
  yowsup v3.2.3
  dissononce v0.34.3
  python-axolotl v0.2.2

If you are not using a released version but code directly from the repository, please indicate the commit hash.

**OS (please complete the following information):**
LINUX - Ubuntu 18.04

**Comment by bryanjhv** [comment]
Did you supply `--config-phone` prefixed with country code?

**Comment by adrijanb** [comment]
> Did you supply `--config-phone` prefixed with country code?

Yes, I did. I also provided the command used by me!

**Comment by adrijanb** [comment]
Fixed it. My number was not accepted by whatsapp.
