### ISSUE TITLE
user had missing parameters: ['key'], is that a valid user

### ISSUE THREAD

**Issue by DaqingFeng** [tgalal/yowsup#2868]
**Describe the bug**
base on yowsup  i  implement a chat client. but i got a exception

**Debug output**

 Failed to create prekeybundle for 62xxx5@s.whatsapp.net, user had missing parameters: ['key'], is that a valid user

```
debug output here
```

**Config file**
 ----Sample
 {
    "__version__": 1,
    "cc": "27",
    "client_static_keypair": "wBLqKB8xxxx=",
    "expid": "QxmTR3HoTTWKspxMJe7ocA==",
    "fdid": "874190d5-78a4-4ade-bcc8-c4ae9673c812",
    "id": "c6+WU6R0fdirdf8NLUsdaeIYDEw=",
    "mcc": "655",
    "mnc": "100",
    "phone": "276xxx",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

**Versions**

yowsup-cli v3.2.0
using:
  yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.2
  cryptography v2.7
  protobuf v3.9.1

**To Reproduce**

Include information about how to reproduce, even if the problem is sporadic any hints about the environment would help.

**Expected behavior**
disconnect the connection.

**OS (please complete the following information):**
Windows 10 

**Additional context**

**Comment by tgalal** [comment]
```user had missing parameters: ['key'], is that a valid user```

exactly what is says, you are attempting to send to a non valid whatsapp user and there is no reason to expect the connection to be closed in this case (if that's what you want). You could however [sync](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_get.py) to identify valid numbers before attempting to send.
