### ISSUE TITLE
All accounts are getting banned

### ISSUE THREAD

**Issue by apepenkov** [tgalal/yowsup#2869]
Whatever account i am trying to use gets banned... But it used to work. What it can be connected with? i re-installed liberary, chanfed ip, nothing helps

**Comment by tgalal** [comment]
three things you could have done before opening this issue

- read the file called [README](https://github.com/tgalal/yowsup/blob/master/README.md)
- read [FAQ](https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account)
- use the search function

**Comment by apepenkov** [comment]
I already read it, lol. Accounts are being banned when adding - just after creating keys
