### ISSUE TITLE
Banning accounts (not while registering new) 

### ISSUE THREAD

**Issue by apepenkov** [tgalal/yowsup#2870]
When i am trying to sign in into existing accounts (NOT CREATE NEW ONES) everything getting banned, right after recieving keys i get disconnect and 403. I changed IP, devices, nothing helps. I used to use accounts fine, with 0 bans, but something happened

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
