### ISSUE TITLE
problem when rejester on yowsup old version

### ISSUE THREAD

**Issue by cool4tec** [tgalal/yowsup#2871]
when i try to rejester my number to yowsup i get old version i try to update env.py file to version 2.19.24 md5MD5_CLASSES = "TswPb+d6fbbR++wGwCmH2Q==" but i get the same problem pleas help

**Comment by tgalal** [comment]
fixed in master

**Comment by cool4tec** [comment]
how to fix it

**Comment by NelsonGaldeman** [comment]
> 
> 
> how to fix it

Download yowsup again from master branch.
