### ISSUE TITLE
config file to send yowsup not work

### ISSUE THREAD

**Issue by cool4tec** [tgalal/yowsup#2872]
after i rejestered my number i want to send whatsap but when i ttry to add config file its not work the old one put example for new config file thank for help

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.

**Comment by cool4tec** [comment]
the problem after i regestered i don't see password only i see id phone cc client_static_keypair wher to put password in config if i see in rejestretion deatles

**Comment by tgalal** [comment]
There is no password anymore; client_static_keypair is used for authentication. After registration you can just login with the supplied config without changing.

**Comment by cool4tec** [comment]
its worked but its take long time msg to send and its send from yowsup i regestered with put client_static_keypair
