### ISSUE TITLE
Number blocked

### ISSUE THREAD

**Issue by patricklucca** [tgalal/yowsup#2896]
Hi, since yesterday when I try to register a number it is instantly banned, all the premises have been made to avoid the ban, but the ban still happens.

**Comment by syberi** [comment]
Did the number have a history in whatsapp, before using yowsup? I think new accounts all check for bots.  I also blocked, although there was almost no traffic.

**Comment by patricklucca** [comment]
The numbers used had conversations made in the official whatsapp app, yet he received the block. None of them were new accounts.

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
