### ISSUE TITLE
message not send

### ISSUE THREAD

**Issue by sachin2625** [tgalal/yowsup#2920]
I have run the command but It was not working with in two days.
Before two days it was working.

sachin@sachin-HP-EliteBook-840-G1:~$ yowsup-cli demos -c 91xxxxxxxxxx  -s 91xxxxxxxxxx "Testing"
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2020-01-23 14:43:30,036 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
I 2020-01-23 14:43:30,352 yowsup.axolotl.manager - Loaded 812 unsent prekeys

Only this was showing.

**Comment by AnusFiedel** [comment]
same here:
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2020-01-23 17:02:56,744 yowsup.layers.network.layer - Connecting to e8.whatsapp.net:443

and freezes forever...

**Comment by tgalal** [comment]
#2919 2919
