### ISSUE TITLE
Yowsup Login

### ISSUE THREAD

**Issue by julioo-cain** [tgalal/yowsup#2929]
According to the below URL, It seems WhatsApp does not support Android version 2.3 and older versions from February 1, 2020:
https://faq.whatsapp.com/en/android/21166563

In the other hand, I can not log in using yowsup from yesterday, is there any relation between these?

is there anybody else who has an issue for log in yowsup-cli?
Before this happens, I can work with yowsup-cli very well without any problem, but now I can not log in.
general disconnect event is emitted when I try to log in.

**Comment by daddo1990** [comment]
I just installed it, but it gives me this error after '/ L':

`[Offline]:
[Offline]: / L
I 2020-02-03 12: 09: 07,282 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
I 2020-02-03 12: 09: 07,679 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected:
[Offline]:
[Offline]:`

**Comment by jowiemann** [comment]
Guys, check pull request #2924, it should solve your problem.
