### ISSUE TITLE
After writing the command (/ L ) the expected Conversion ( [offline]: ) to ( [online]: )

### ISSUE THREAD

**Issue by a-elmohamady** [tgalal/yowsup#2938]
**Describe the bug**

After writing the command (**/ L** ) the expected Conversion (    **[**offline**]:**     )  to (    **[online]:**   )

**Debug output**

python yowsup-cli demos --yowsup --phone xxxxxxxxxxxxxx --debug
D 2020-02-20 17:50:56,791 yowsup.config.manager - load(path_or_profile_name=xxxxxxxxxxxxxx, profile_only=False)
D 2020-02-20 17:50:56,792 yowsup.config.manager - _load_path(path=xxxxxxxxxxxxxx)
D 2020-02-20 17:50:56,792 yowsup.config.manager - _load_path couldn't find the path: xxxxxxxxxxxxxx
D 2020-02-20 17:50:56,792 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-02-20 17:50:56,792 yowsup.config.manager - Detecting config for profile=xxxxxxxxxxxxxx, dir=/root/.config/yowsup/xxxxxxxxxxxxxx
D 2020-02-20 17:50:56,793 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxx/config.yo
D 2020-02-20 17:50:56,793 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxx/config.json
D 2020-02-20 17:50:56,793 yowsup.config.manager - _load_path(path=/root/.config/yowsup/xxxxxxxxxxxxxx/config.json)
D 2020-02-20 17:50:56,793 yowsup.config.manager - Detected config type: json
D 2020-02-20 17:50:56,794 yowsup.config.manager - Opening config for reading
D 2020-02-20 17:50:56,794 yowsup.config.manager - Loading config
D 2020-02-20 17:50:56,794 yowsup.profile.profile - Constructed Profile(profile_name=xxxxxxxxxxxxxx)
D 2020-02-20 17:50:56,795 yowsup-cli - starting cmd
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.8
protobuf       v3.10.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2020-02-20 17:50:56,853 yowsup.stacks.yowstack - Initializing stack
D 2020-02-20 17:50:56,853 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-02-20 17:50:56,854 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-02-20 17:50:56,854 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-02-20 17:50:56,855 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-02-20 17:50:56,855 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-02-20 17:50:56,855 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f47a7fdc7b8>
D 2020-02-20 17:50:56,855 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f47a96b59e8>
D 2020-02-20 17:50:56,855 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-02-20 17:50:56,857 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2020-02-20 17:50:56,858 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=xxxxxxxxxxxxxx))
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2020-02-20 17:51:05,249 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-02-20 17:51:05,249 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
D 2020-02-20 17:51:05,250 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e7.whatsapp.net', 443))
E 2020-02-20 17:53:15,359 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 420, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 428, in handle_connect_event
    raise OSError(err, _strerror(err))
TimeoutError: [Errno 110] Connection timed out

D 2020-02-20 17:53:15,360 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-02-20 17:53:15,360 yowsup.layers.network.layer - Disconnected
D 2020-02-20 17:53:15,453 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:
[offline]:
[offline]:

**Versions**

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.8
protobuf       v3.10.0

**Expected behavior**
[online]:

**OS (please complete the following information):**
Ubuntu server
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by Johnprogg** [comment]
It's Fixed ?

**Comment by Johnprogg** [comment]
Now It's Working @a-elmohamady a-elmohamady?
