### ISSUE TITLE
Presence Not Working.

### ISSUE THREAD

**Issue by Johnprogg** [tgalal/yowsup#2940]
Hey, Guys i see Status Subscribe is not working since this morning, Does anyone facing the same issue is there any fix ?

**Comment by Johnprogg** [comment]
It's Working now.

**Comment by cagataydagnik** [comment]
presence works for me about 1 day then stops. how did you work. can you help me?

**Comment by ersinayaz** [comment]
Az daha dayan kısa süre sonra eline alcaksın o projeyi 😂
