### ISSUE TITLE
how many numbers can we use in same IP (server) ?

### ISSUE THREAD

**Issue by fevzican** [tgalal/yowsup#2942]
Is whatsapp blocking to use numbers in same IP ? How many numbers can allowed?

**Comment by gmistick** [comment]
Depends on your activity.
Don't forget that public wifi is hosting multiple users, i would assume they would not ban a specific ip..

If you are registering numbers from same ip or spamming etc, then probably you will be banned.

**Comment by fevzican** [comment]
> Depends on your activity.
> Don't forget that public wifi is hosting multiple users, i would assume they would not ban a specific ip..
> 
> If you are registering numbers from same ip or spamming etc, then probably you will be banned.

yes, it makes sense. However they may suspect for all access from same ip and all day online. 
How many numbers can we subscribe presence, do you know that ?

**Comment by gmistick** [comment]
Wouldn't recommend subscribing for presence , i think it might cause fast banning as there were many articles about it online and it is on Whatsapp attention.

**Comment by fevzican** [comment]
> Wouldn't recommend subscribing for presence , i think it might cause fast banning as there were many articles about it online and it is on Whatsapp attention.

actually i subscribed for presence of 3-4 numbers for a month and number didnt get ban. After almost a month, got ban.

**Comment by gmistick** [comment]
What exactly did you do? 
T0 - register
T0+(seconds) -- Subscribe to presence of 3-4 numbers
T0+Month --> Ban?

How many subscribes per day, per connections. Did you just subscribe at start of month and then you got info until the end of month? (this doesn't seem right)
