### ISSUE TITLE
ValueError: config.id is not set

### ISSUE THREAD

**Issue by nickdeng1216** [tgalal/yowsup#2956]
**Describe the bug**
It's my first time to use yowsup and after I run 'yowsup-cli registration --register 531-819 --phone 85269309454 --cc 852', I got the below exceptions that are related to config. 

**Debug output**
yowsup-cli registration --register 531-819 --phone 85269309454 --cc 852 --debug
D 2020-03-16 16:37:26,242 yowsup.config.manager - load(path_or_profile_name=85269309454, profile_only=False)
D 2020-03-16 16:37:26,242 yowsup.config.manager - _load_path(path=85269309454)
D 2020-03-16 16:37:26,242 yowsup.config.manager - _load_path couldn't find the path: 85269309454
D 2020-03-16 16:37:26,242 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-03-16 16:37:26,243 yowsup.config.manager - Detecting config for profile=85269309454, dir=/root/.config/yowsup/85269309454
D 2020-03-16 16:37:26,243 yowsup.config.manager - Trying /root/.config/yowsup/85269309454/config.yo
D 2020-03-16 16:37:26,243 yowsup.config.manager - Trying /root/.config/yowsup/85269309454/config.json
E 2020-03-16 16:37:26,243 yowsup.config.manager - Could not find a config for profile=85269309454, paths checked: 85269309454:/root/.config/yowsup/85269309454/config.yo:/root/.config/yowsup/85269309454/config.json
D 2020-03-16 16:37:26,243 yowsup.profile.profile - Constructed Profile(profile_name=85269309454)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.8
protobuf       v3.11.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2020-03-16 16:37:26,310 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2020-03-16 16:37:26,310 yowsup.profile.profile - Constructed Profile(profile_name=85269309454)
D 2020-03-16 16:37:26,310 yowsup.axolotl.factory - get_manager(profile_name=85269309454, username=85269309454)
D 2020-03-16 16:37:26,311 yowsup.axolotl.manager - Initialized AxolotlManager [username=85269309454, db=/root/.config/yowsup/85269309454/axolotl.db]
D 2020-03-16 16:37:26,312 yowsup.axolotl.manager - load_latest_signed_prekey
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.2.3', 'yowsup-cli')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 722, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 389, in process
    self.handleRegister(self.args["register"], config)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 418, in handleRegister
    req = WARegRequest(config, code)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/registration/regrequest.py", line 38, in __init__
    raise ValueError("config.id is not set.")
ValueError: config.id is not set.

**Config file**

There is no config file under the project directory except axolotl.db.

**Versions**

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.8
protobuf       v3.11.3
centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by ecclesion** [comment]
hello, I found this problem too
have you found any solution to this yet?
thank you
