### ISSUE TITLE
Old_Version

### ISSUE THREAD

**Issue by christopherbentley** [tgalal/yowsup#2970]
Old Version even though I had newest stored in env_android.py
Version: 2.02.124
MD5: R4LeoAEBkTDrbXgRY1ZOKg==
I 2020-04-18 22:29:38,443 yowsup.common.http.warequest - b'{"login":"49...","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'49...'

**Comment by ahdelim** [comment]
I guess it is version 2.20.124 ...?

**Comment by returnWOW** [comment]
You maybe should clone the latest code from github, and run python3 setup.py install to update code?Some other reason is login api to old than whatsapp official api. Sorry for my bad English.

**Comment by christopherbentley** [comment]
@returnWOW I did that allready. But still I get the Same Error

**Comment by returnWOW** [comment]
https://github.com/tgalal/yowsup/issues/2564 ,There have solution.

**Comment by returnWOW** [comment]
In my server, version info is below,but response same error.
_MD5_CLASSES = "/QhoCBMppKpKQumhTC8kcQ=="
_VERSION = "2.19.244"

**Comment by christopherbentley** [comment]
Solved it I typed wrong Version
