### ISSUE TITLE
Msg not send

### ISSUE THREAD

**Issue by DeLuca92** [tgalal/yowsup#2973]
Is correct?
I don't know the problem

root@daniel:/home/daniel/Downloads/yowsup-master# yowsup-cli demos -c number.config  -s 555197913001 "Messagshufggfhe" -d
D 2020-04-21 11:24:58,107 yowsup.config.manager - load(path_or_profile_name=number.config, profile_only=False)
D 2020-04-21 11:24:58,107 yowsup.config.manager - _load_path(path=number.config)
D 2020-04-21 11:24:58,107 yowsup.config.manager - Trying auto detect config type by parsing
D 2020-04-21 11:24:58,107 yowsup.config.manager - Trying to parse as keyval
D 2020-04-21 11:24:58,107 yowsup.config.manager - number.config was not parseable as keyval, reason: list index out of range
D 2020-04-21 11:24:58,107 yowsup.config.manager - Trying to parse as json
D 2020-04-21 11:24:58,107 yowsup.config.manager - Successfully detected json as config type for number.config
D 2020-04-21 11:24:58,107 yowsup.config.manager - Detected config type: json
D 2020-04-21 11:24:58,107 yowsup.config.manager - Opening config for reading
D 2020-04-21 11:24:58,107 yowsup.config.manager - Loading config
D 2020-04-21 11:24:58,108 yowsup.config.manager - load(path_or_profile_name=15199668722, profile_only=True)
D 2020-04-21 11:24:58,108 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-04-21 11:24:58,108 yowsup.config.manager - Detecting config for profile=15199668722, dir=/root/.config/yowsup/15199668722
D 2020-04-21 11:24:58,108 yowsup.config.manager - Trying /root/.config/yowsup/15199668722/config.yo
D 2020-04-21 11:24:58,108 yowsup.config.manager - Trying /root/.config/yowsup/15199668722/config.json
D 2020-04-21 11:24:58,108 yowsup.config.manager - _load_path(path=/root/.config/yowsup/15199668722/config.json)
D 2020-04-21 11:24:58,108 yowsup.config.manager - Detected config type: json
D 2020-04-21 11:24:58,108 yowsup.config.manager - Opening config for reading
D 2020-04-21 11:24:58,108 yowsup.config.manager - Loading config
D 2020-04-21 11:24:58,108 yowsup.profile.profile - Constructed Profile(profile_name=15199668722)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.8
protobuf       v3.11.4

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2020-04-21 11:24:58,185 yowsup.stacks.yowstack - Initializing stack
D 2020-04-21 11:24:58,185 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-04-21 11:24:58,185 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fc3725acf10>
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fc3715fe2b0>
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-04-21 11:24:58,186 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-04-21 11:24:58,187 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=15199668722))
D 2020-04-21 11:24:58,187 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-04-21 11:24:58,187 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
D 2020-04-21 11:24:58,187 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e2.whatsapp.net', 443))
D 2020-04-21 11:24:58,367 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-04-21 11:24:58,367 yowsup.layers.network.layer - Connected
D 2020-04-21 11:24:58,367 yowsup.axolotl.factory - get_manager(profile_name=15199668722, username=15199668722)
D 2020-04-21 11:24:58,368 yowsup.axolotl.manager - Initialized AxolotlManager [username=15199668722, db=/root/.config/yowsup/15199668722/axolotl.db]
D 2020-04-21 11:24:58,368 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-04-21 11:24:58,371 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-04-21 11:24:58,371 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-04-21 11:24:58,374 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-04-21 11:24:58,374 yowsup.layers.noise.layer - Received auth event
D 2020-04-21 11:24:58,374 yowsup.env.env - Env not set, setting it to android
D 2020-04-21 11:24:58,374 yowsup.env.env - Current env changed to android 
D 2020-04-21 11:24:58,374 yowsup.layers.noise.layer - Performing handshake [username= 15199668722, passive=True]
D 2020-04-21 11:24:58,374 yowsup.layers.noise.layer - Starting handshake worker
D 2020-04-21 11:24:58,602 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-04-21 11:24:58,602 yowsup.layers.network.layer - Disconnected
D 2020-04-21 11:24:58,602 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by DeLuca92** [comment]
I update to WA 3.0, now works

**Comment by Lotykun** [comment]
Hi.. @DeLuca92 same problem here, Can you explain how to update WA to 3.0? Or link the related issue in which is explained.. thanks
