### ISSUE TITLE
Disconnected Error Please Help Urgent please!

### ISSUE THREAD

**Issue by HelloWar75** [tgalal/yowsup#2983]
**Describe the bug**

What happened? Please make sure to first search existing issues and read the [FAQ](https://github.com/tgalal/yowsup/wiki/FAQ) in case this is already addressed.

**Debug output**

Switch on debug logging and include output along with the error or problem you see. If you are using yowsup-cli, this can be enabled by passing ```---debug```.

Please include any output as code blocks for proper formatting. For example:
```
debug output here
```

**Config file**

`{
    "__version__": 1,
    "cc": "55",
    "client_static_keypair": "xxxxxxxxxxxx",
    "edge_routing_info": "xxxxxxx==",
    "expid": "xxxxxxxxxxxxxxxxx",
    "fdid": "xxxxxxxxxxxxxx",
    "id": "xxxxxxxx",
    "mcc": "000",
    "mnc": "000",
    "phone": "555199xxxxxxx",
    "server_static_public": "xxxxxxx",
    "sim_mcc": "000",
    "sim_mnc": "000"
}`

**Versions**

Python 3.6.8
yowsup-cli v3.2.0
Using yowsup v3.2.3

**To Reproduce**

I register, after that I try to log in with the command:
yowsup-cli demos -c /home/luisjustin/.config/yowsup/555199xxxxxxxx/config.json -y -d

**Console**
`
D 2020-05-11 17:28:02,860 yowsup.stacks.yowstack - Initializing stack
D 2020-05-11 17:28:02,860 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-05-11 17:28:02,860 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-05-11 17:28:02,861 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-05-11 17:28:02,861 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-05-11 17:28:02,861 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-05-11 17:28:02,862 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f5acfd409e8>
D 2020-05-11 17:28:02,862 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f5ad22c2f28>
D 2020-05-11 17:28:02,862 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-05-11 17:28:02,866 yowsup.stacks.yowstack - Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2020-05-11 17:29:07,672 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-05-11 17:29:07,672 yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
D 2020-05-11 17:29:07,672 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e14.whatsapp.net', 443))
D 2020-05-11 17:29:07,835 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-05-11 17:29:07,835 yowsup.layers.network.layer - Connected
D 2020-05-11 17:29:07,835 yowsup.axolotl.factory - get_manager(username=5551998104603)
D 2020-05-11 17:29:07,836 yowsup.axolotl.manager - Initialized AxolotlManager [username=5551998104603, db=/home/luisjustin/.config/yowsup/5551998104603/axolotl.db]
D 2020-05-11 17:29:07,836 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-05-11 17:29:07,841 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-05-11 17:29:07,841 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-05-11 17:29:07,844 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-05-11 17:29:07,844 yowsup.axolotl.factory - get_manager(username=5551998104603)
D 2020-05-11 17:29:07,845 yowsup.axolotl.manager - Initialized AxolotlManager [username=5551998104603, db=/home/luisjustin/.config/yowsup/5551998104603/axolotl.db]
D 2020-05-11 17:29:07,845 yowsup.axolotl.factory - get_manager(username=5551998104603)
D 2020-05-11 17:29:07,846 yowsup.axolotl.manager - Initialized AxolotlManager [username=5551998104603, db=/home/luisjustin/.config/yowsup/5551998104603/axolotl.db]
D 2020-05-11 17:29:07,846 yowsup.layers.noise.layer - Received auth event
D 2020-05-11 17:29:07,846 yowsup.config.manager - Detecting config for username=5551998104603, dir=/home/luisjustin/.config/yowsup/5551998104603/
D 2020-05-11 17:29:07,846 yowsup.config.manager - Trying /home/luisjustin/.config/yowsup/5551998104603/config.yo
D 2020-05-11 17:29:07,846 yowsup.config.manager - Trying /home/luisjustin/.config/yowsup/5551998104603/config.json
D 2020-05-11 17:29:07,846 yowsup.config.manager - load_path(path=/home/luisjustin/.config/yowsup/5551998104603/config.json)
D 2020-05-11 17:29:07,846 yowsup.config.manager - Detected config type: json
D 2020-05-11 17:29:07,846 yowsup.config.manager - Opening config for reading
D 2020-05-11 17:29:07,846 yowsup.config.manager - Loading config
D 2020-05-11 17:29:07,847 yowsup.env.env - Env not set, setting it to android
D 2020-05-11 17:29:07,847 yowsup.env.env - Current env changed to android 
D 2020-05-11 17:29:07,847 yowsup.layers.noise.layer - Performing handshake [username= 5551998104603, passive=True]
D 2020-05-11 17:29:07,847 yowsup.layers.noise.layer - Starting handshake worker
D 2020-05-11 17:29:08,229 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-05-11 17:29:08,229 yowsup.layers.network.layer - Disconnected
D 2020-05-11 17:29:08,286 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: 
[offline]:
[offline]:

`

**Expected behavior**

**OS (please complete the following information):**
Which OS did you encounter the bug on?
Redhat Enterprise 8

**Additional context**

**Comment by mape221** [comment]
Same error.
D 2020-05-12 15:46:23,377 yowsup.stacks.yowstack - Initializing stack
D 2020-05-12 15:46:23,377 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-05-12 15:46:23,378 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-05-12 15:46:23,378 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-05-12 15:46:23,379 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-05-12 15:46:23,379 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-05-12 15:46:23,379 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7ff3a10d75c0>
D 2020-05-12 15:46:23,379 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7ff3a21bd2e8>
D 2020-05-12 15:46:23,379 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-05-12 15:46:23,380 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-05-12 15:46:23,380 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=573503189885))
D 2020-05-12 15:46:23,380 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-05-12 15:46:23,380 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
D 2020-05-12 15:46:23,380 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e3.whatsapp.net', 443))
D 2020-05-12 15:46:26,182 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-05-12 15:46:26,182 yowsup.layers.network.layer - Connected
D 2020-05-12 15:46:26,182 yowsup.axolotl.factory - get_manager(profile_name=573503189885, username=573503189885)
D 2020-05-12 15:46:26,185 yowsup.axolotl.manager - Initialized AxolotlManager [username=573503189885, db=/home/manolo/.config/yowsup/573503189885/axolotl.db]
D 2020-05-12 15:46:26,185 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-05-12 15:46:26,193 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-05-12 15:46:26,193 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-05-12 15:46:26,219 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-05-12 15:46:26,219 yowsup.layers.noise.layer - Received auth event
D 2020-05-12 15:46:26,220 yowsup.env.env - Env not set, setting it to android
D 2020-05-12 15:46:26,220 yowsup.env.env - Current env changed to android 
D 2020-05-12 15:46:26,220 yowsup.layers.noise.layer - Performing handshake [username= 573503189885, passive=True]
D 2020-05-12 15:46:26,220 yowsup.layers.noise.layer - Starting handshake worker
D 2020-05-12 15:46:26,607 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-05-12 15:46:26,608 yowsup.layers.network.layer - Disconnected
D 2020-05-12 15:46:26,609 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by antoniovalenzuela** [comment]
Same issue

D 2020-05-30 19:06:34,765 yowsup.layers.noise.layer - Starting handshake worker
D 2020-05-30 19:06:35,114 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-05-30 19:06:35,115 yowsup.layers.network.layer - Disconnected
D 2020-05-30 19:06:35,116 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by antoniovalenzuela** [comment]
tried different numbers, on different platforms.

- VPS - Debian GNU/Linux 9 (stretch)
- RPI3 - Raspbian GNU/Linux 10 (buster)

**Comment by HelloWar75** [comment]
In the pull requests have a solution but is not merged with the master branch.

**Comment by antoniovalenzuela** [comment]
there was progress ... I received the notice without the message.

![image](https://user-images.githubusercontent.com/28113584/83360574-42b39d00-a350-11ea-90ee-c411cff11db1.png)

**Comment by antoniovalenzuela** [comment]
works
https://github.com/tgalal/yowsup/pull/2924#issuecomment-637073913
