### ISSUE TITLE
smth went wrong with 405 err

### ISSUE THREAD

**Issue by vdpopov** [tgalal/yowsup#2986]
Hi everyone
I suddenly started getting 405 error:

D 2020-05-19 00:11:05,273 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2020-05-19 00:12:02,789 yowsup.config.manager - load(path_or_profile_name=/opt/scripts/*/7**********/config.json, profile_only=False)
D 2020-05-19 00:12:02,789 yowsup.config.manager - _load_path(path=/opt/scripts/*/7**********/config.json)
D 2020-05-19 00:12:02,789 yowsup.config.manager - Detected config type: json
D 2020-05-19 00:12:02,789 yowsup.config.manager - Opening config for reading
D 2020-05-19 00:12:02,789 yowsup.config.manager - Loading config
D 2020-05-19 00:12:02,789 yowsup.config.manager - load(path_or_profile_name=7**********, profile_only=True)
D 2020-05-19 00:12:02,789 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-05-19 00:12:02,789 yowsup.config.manager - Detecting config for profile=7**********, dir=/var/lib/nginx/.config/*/7**********
D 2020-05-19 00:12:02,789 yowsup.config.manager - Trying /var/lib/nginx/.config/*/7**********/config.json
D 2020-05-19 00:12:02,790 yowsup.config.manager - _load_path(path=/var/lib/nginx/.config/*/7**********/config.json)
D 2020-05-19 00:12:02,790 yowsup.config.manager - Detected config type: json
D 2020-05-19 00:12:02,790 yowsup.config.manager - Opening config for reading
D 2020-05-19 00:12:02,790 yowsup.config.manager - Loading config
D 2020-05-19 00:12:02,790 yowsup.profile.profile - Constructed Profile(profile_name=7**********)
D 2020-05-19 00:12:02,931 yowsup.stacks.yowstack - Initializing stack
D 2020-05-19 00:12:02,932 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-05-19 00:12:02,932 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-05-19 00:12:02,932 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fac6a311d90>
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fac6a2fa8d0>
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-05-19 00:12:02,933 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=7**********))
D 2020-05-19 00:12:02,934 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-05-19 00:12:02,934 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
D 2020-05-19 00:12:02,934 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e6.whatsapp.net', 443))
D 2020-05-19 00:12:03,097 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-05-19 00:12:03,097 yowsup.layers.network.layer - Connected
D 2020-05-19 00:12:03,097 yowsup.axolotl.factory - get_manager(profile_name=7**********, username=7**********)
D 2020-05-19 00:12:03,098 yowsup.axolotl.manager - Initialized AxolotlManager [username=7**********, db=/var/lib/nginx/.config/*/7**********/axolotl.db]
D 2020-05-19 00:12:03,098 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-05-19 00:12:03,125 yowsup.axolotl.manager - len(pending_prekeys) = 1476
D 2020-05-19 00:12:03,125 yowsup.axolotl.manager - load_unsent_prekeys
D 2020-05-19 00:12:03,125 yowsup.layers.noise.layer - Received auth event
D 2020-05-19 00:12:03,126 yowsup.env.env - Env not set, setting it to android
D 2020-05-19 00:12:03,126 yowsup.env.env - Current env changed to android 
D 2020-05-19 00:12:03,126 yowsup.layers.noise.layer - Performing handshake [username= 7**********, passive=False]
D 2020-05-19 00:12:03,126 yowsup.layers.noise.layer - Starting handshake worker
D 2020-05-19 00:12:03,501 yowsup.profile.profile - write_config for 7**********
D 2020-05-19 00:12:03,501 yowsup.common.tools - writeProfileData(profile_name=7**********, name=config.json, val=[omitted])
D 2020-05-19 00:12:03,501 yowsup.common.tools - Writing /var/lib/nginx/.config/*/7**********/config.json
D 2020-05-19 00:12:04,500 yowsup.layers.logger.layer - rx:
<failure reason="405" location="frc" />
D 2020-05-19 00:12:04,500 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2020-05-19 00:12:04,500 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-05-19 00:12:04,500 yowsup.layers.network.layer - Disconnected
D 2020-05-19 00:12:04,501 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

Does anyone know what to do with that?

**Comment by JoelSaldanaMontoya** [comment]
Hello @vdpopov 
Change this:
In yowsup/env/env_android.py

Change:
This line:      _VERSION = "2.21.001"
For this line:      _VERSION = "2.21.001"

Tell me how it's going.

Greetings from Peru.

**Comment by nightcoder22** [comment]
Hi @JoelSaldanaMontoya 
It worked.. i replaced,
_VERSION with 2.20.158
and 
_md5 with qNhJUjrBT3QiX2MR+sCuWw==

Thanks <3

**Comment by vdpopov** [comment]
@JoelSaldanaMontoya @nightcoder22 
Thanks y'all guys it works!

**Comment by HeinzFo** [comment]
> Hello @vdpopov
> Change this:
> In yowsup/env/env_android.py
> 
> Change:
> This line: _VERSION = "2.19.244"
> For this line: _VERSION = "2.21.001"
> 
> Tell me how it's going.
> 
> Greetings from Peru.

Works fine for me!
Many Thanks
