### ISSUE TITLE
broadcast not working properly

### ISSUE THREAD

**Issue by nirmalkarai** [tgalal/yowsup#300]
First of all thanks to @CODeRUS and @shirioko for their great reverse engineering work.
Problem : it tried to broadcast the message to 10 mobile number, but yowsup sent a message to one mobile number only rest of the 9 mobile number yowsup did  not send the message. Please can any one help me?
thanks in advance.

**Comment by OliverMaas** [comment]
Hi,
can't run "python yowsup-cli -c config.example -b number1,number2... "Mesage"" any more.
result:
Available commands:
===================
demos, version, registration

Any ideas how to run a broadcast message from command line?
