### ISSUE TITLE
failed registration 

### ISSUE THREAD

**Issue by adviraj** [tgalal/yowsup#3004]
yowsup.common.http.warequest - b'{"login":"91XXXXXXXXXX","status":"fail","reason":"bad_token"}\n'
status: b'fail'
reason: b'bad_token'
login: b'91XXXXXXXXXX

**Comment by fanishe** [comment]
Why you don't use search in issues?

**Comment by hossinasaadi** [comment]
open this file and replace new values
`/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/env/env_android.py
`

> for you maybe env_android.py file been in other path, search it :)


new Values :
```
    _MD5_CLASSES = "PzuZ7EJNcuXEealGEJT6+g=="
    _VERSION = "2.20.134"

```

also you can search in issues 
good luck

**Comment by mocart2** [comment]
i changed it, but i have new troible: 
```
[offline]:/L
I 2020-09-19 21:51:52,866 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
I 2020-09-19 21:51:52,969 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected:
```

**Comment by hossinasaadi** [comment]
> i changed it, but i have new troible:
> 
> ```
> [offline]:/L
> I 2020-09-19 21:51:52,866 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
> I 2020-09-19 21:51:52,969 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> general: Disconnected:
> ```

which cli version you use?

**Comment by adviraj** [comment]
> yowsup.common.http.warequest - b'{"login":"91XXXXXXXXXX","status":"fail","reason":"bad_token"}\n'
> status: b'fail'
> reason: b'bad_token'
> login: b'91XXXXXXXXXX
