### ISSUE TITLE
How save messages received in a database using Yowsup?

### ISSUE THREAD

**Issue by regisfcsantos** [tgalal/yowsup#301]
I'm using yowsup-cli to send and receive messages, but I want to know how can I store all them in a database? I saw in wazapp documentation, but I'm new with python. I didn't realize how can I store messages received from yowsup-cli on bash. By a Model, something with bash's history? (Note: As I want to put it in a server, it's possible access history of a host's bash?)

Any help? Thanks everybody!
##

**Comment by mutindaz** [comment]
I have implemented this feature with the current version of yowsup. This is what I have done according to my need of a USSD like feature for whatsapp.

Once I get a message from whatsapp - I do an http request to my server which is running php scripts, do my messages logs with php+mysql, process what I need then issue back response as json. 
Once my python script gets this response - formatted in a standard way like this:
{
	"message": "Response header instructions is here",
	"menu":[
		{"code": "1", "tag": "Check order status"},
		{"code": "2", "tag": "Check all orders status"}
	]
}
I now then format this to a standard string , and send it back to the person who requested this service- whatsapp no :  The response to user 

Response header instructions is here
-------------------------------------
1: Check order status
2: Check all orders status

Once the user selects any of the above items, I repeat the same procedure of doing an http request then formatting the response till I get my client satisfied.

I will issue a pull request with this example.

**Comment by blackjack4494** [comment]
Depending on how you are using Yowsup I would rather tend to use sqlite. 
It's faster and not using that much resources. (I do not want to start a discussion about it - just my personal opinion)
You can either use a database like @juanmas07 showed in his post or creating a text-file for every session with a number. 
But use the ListenerClient.py script as first step it's easy and working ;)

I am really busy right now but I can try to give a brief example with storing messages in txt file (~weekend).
So far look into this 
https://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files

**Comment by maruen** [comment]
Hi there...anybody could point me out how to get messages with yowsup library? I know how to send, but I couldn't figure out how to receive messages.
Thanks any help
