### ISSUE TITLE
Client does disconnect when doing /L

### ISSUE THREAD

**Issue by endroemily** [tgalal/yowsup#3030]
Hi guys i have a problem. Client does disconnect when doing /L

env_android.py:

> _VERSION = "2.20.206"
> _MD5_CLASSES = "oEYGYTr+K6IN0mDOrAZpsg=="

My config file:

> {
>     "__version__": 1,
>     "cc": "976",
>     "client_static_keypair": "mxxxxxxxxxxxxxx",
>     "expid": "xxx",
>     "fdid": "xxx",
>     "id": "xxx",
>     "login": "976*******",
>     "mcc": "123",
>     "mnc": "456",
>     "phone": "976******",
>     "sim_mcc": "000",
>     "sim_mnc": "000"
> }

versions i use:

> yowsup-cli     v3.2.0
> yowsup         v3.2.3
> consonance     v0.1.3-1
> dissononce     v0.34.3
> python-axolotl v0.2.2
> cryptography   v3.3.1
> protobuf       v3.14.0
> six v1.10

Debug:
> Yowsup Cli client
> Type /help for available commands
> [offline]:/L
> D 2020-12-18 13:43:10,295 yowsup.layers.network.layer - Created asyncore dispatcher
> I 2020-12-18 13:43:10,296 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
> D 2020-12-18 13:43:10,296 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e6.whatsapp.net', 443))
> D 2020-12-18 13:43:10,347 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
> D 2020-12-18 13:43:10,347 yowsup.layers.network.layer - Connected
> D 2020-12-18 13:43:10,348 yowsup.axolotl.factory - get_manager(profile_name=976********, username=976********)
> D 2020-12-18 13:43:10,350 yowsup.axolotl.manager - Initialized AxolotlManager [username=976********, db=/root/.config/yowsup/976********/axolotl.db]
> D 2020-12-18 13:43:10,350 yowsup.axolotl.manager - level_prekeys(force=False)
> D 2020-12-18 13:43:10,356 yowsup.axolotl.manager - len(pending_prekeys) = 812
> D 2020-12-18 13:43:10,357 yowsup.axolotl.manager - load_unsent_prekeys
> I 2020-12-18 13:43:10,360 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> D 2020-12-18 13:43:10,360 yowsup.layers.noise.layer - Received auth event
> D 2020-12-18 13:43:10,361 yowsup.env.env - Env not set, setting it to android
> D 2020-12-18 13:43:10,361 yowsup.env.env - Current env changed to android
> D 2020-12-18 13:43:10,361 yowsup.layers.noise.layer - Performing handshake [username= 976********, passive=True]
> D 2020-12-18 13:43:10,361 yowsup.layers.noise.layer - Starting handshake worker
> D 2020-12-18 13:43:10,528 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
> D 2020-12-18 13:43:10,528 yowsup.layers.network.layer - Disconnected
> D 2020-12-18 13:43:10,558 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
> general: Disconnected:
> [offline]:
> 

I'm using centos7 with python 3.6 and python 3.8 i'm always get this error. Anyone can help me? Thanks, best regards.

**Comment by ben221199** [comment]
@endroemily Post your fix please :D
