### ISSUE TITLE
bad_token return when trying to register

### ISSUE THREAD

**Issue by mthushara** [tgalal/yowsup#3040]
**Describe the bug**

When I try to register my mobile number with yowsup-cli, I'm getting "bad_token" as the reason and it fails. 
Please help me on this

**Command used to register**
python3.6 yowsup-cli registration -r sms -c zap.conf -E android -d
(zap.conf having the mobile number details)

**Debug output**
D 2021-01-06 23:48:51,604 yowsup.env.env - Current env changed to android
D 2021-01-06 23:48:51,604 yowsup.config.manager - load(path_or_profile_name=zap.conf, profile_only=False)
D 2021-01-06 23:48:51,604 yowsup.config.manager - _load_path(path=zap.conf)
D 2021-01-06 23:48:51,604 yowsup.config.manager - Trying auto detect config type by parsing
D 2021-01-06 23:48:51,604 yowsup.config.manager - Trying to parse as keyval
D 2021-01-06 23:48:51,604 yowsup.config.manager - Successfully detected keyval as config type for zap.conf
D 2021-01-06 23:48:51,604 yowsup.config.manager - Detected config type: keyval
D 2021-01-06 23:48:51,604 yowsup.config.manager - Opening config for reading
D 2021-01-06 23:48:51,605 yowsup.config.manager - Loading config
D 2021-01-06 23:48:51,605 yowsup.config.manager - load(path_or_profile_name=9477XXXXXXX, profile_only=True)
D 2021-01-06 23:48:51,605 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2021-01-06 23:48:51,605 yowsup.config.manager - Detecting config for profile=9477XXXXXXX, dir=/root/.config/yowsup/9477XXXXXXX
D 2021-01-06 23:48:51,605 yowsup.config.manager - Trying /root/.config/yowsup/9477XXXXXXX/config.yo
D 2021-01-06 23:48:51,605 yowsup.config.manager - Trying /root/.config/yowsup/9477XXXXXXX/config.json
E 2021-01-06 23:48:51,605 yowsup.config.manager - Could not find a config for profile=9477XXXXXXX, paths checked: /root/.config/yowsup/9                 4778455034/config.yo:/root/.config/yowsup/9477XXXXXXX/config.json
D 2021-01-06 23:48:51,605 yowsup.profile.profile - Constructed Profile(profile_name=9477XXXXXXX)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.9.2
protobuf       v3.12.2

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2021-01-06 23:48:51,665 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2021-01-06 23:48:51,665 yowsup.profile.profile - Constructed Profile(profile_name=9477XXXXXXX)
D 2021-01-06 23:48:51,665 yowsup.axolotl.factory - get_manager(profile_name=9477XXXXXXX, username=9477XXXXXXX)
D 2021-01-06 23:48:51,667 yowsup.axolotl.manager - Initialized AxolotlManager [username=9477XXXXXXX, db=/root/.config/yowsup/9477XXXXXXX                 /axolotl.db]
D 2021-01-06 23:48:51,668 yowsup.axolotl.manager - load_latest_signed_prekey
D 2021-01-06 23:48:51,668 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2021-01-06 23:48:51,668 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2021-01-06 23:48:51,668 yowsup.common.http.warequest - Encrypting parameters
D 2021-01-06 23:48:51,669 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=94&in=778455034&lg=en&lc=GB&mistyped=6&authkey=0JH5Ozoog5hRG%5fCTCRsb%2ddUBQhQ57QPxApxYH0hzc0g&e_regid=Ayz8Cg&e_keytype=BQ&e_ident=ti                 7fF1gVrZ4rjnhHWK%2dojmXBlS2HPc%5fgFIfzgD1VrDk&e_skey_id=AAAA&e_skey_val=VqaEKVtW8Ki322Pb3xMGZ3fAJd3gBk%2dBzeMHeWxb7G8&e_skey_sig=Qn7TI0x                 owjXuLVg04M2ODd2fjV3nu%2dhvEG%5fRw8icETkFGj5LeF9A3z3n69YDQv78s0RunLSGOnvvYM7i8A3QBw&fdid=090fb7af%2d0242%2d43e4%2d87aa%2d5dd642ccea57&ex                 pid=lg212FJPSyii1Ucdvjie2g&network_radio_type=1&simnum=1&hasinrc=1&pid=3531&rc=0&mcc=000&mnc=000&sim_mcc=000&sim_mnc=000&method=sms&reas                 on=&token=xwuYIB8c%2bJ4heiJ%2fAQEYcsRTHm4%3d&hasav=1&id=R%de%c0l%18g%d9I8%19%5du%be%d6%aa%b2e%93%d5%ab
D 2021-01-06 23:48:51,671 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent'                 : 'WhatsApp/2.21.1 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'q4m5mbJCsmJbXk2JrzsgWti2sqR/01MHwIX                 QRg446S/Uiku9K8OQbtNdibVaBErgiePESrlJLXDuMQy1q8kgzdwCwFGEvPiWvdlA44kI5giZ1Vy8RpeuUJkKe7eeF1JC5Xs+NgoHSop2AD44n67wefaqDA9t/xEPfIgppu1bxM4                 rwCdJwlyDJZoGbl0WtgERSeeP3AqBJvAlRDMLF77/XGbITfpACHy6BehQ93ig6bK5OdTk1mWU3kgXGTIjH8ga64wX/1+VSme/gS5hfw4wmAO05tYvXy+kvlzut1Y6QN7pnjXcPvU                 Lqetwr0Pw/E5bhjA0FE9Zuc8xyax9FViY24nH29Ha336fW+AJtACTtU1T5ZxpijMrcZoDC91wkA5kKm/6pr16RFJH+WU9BBcg//uuCqG/SLZx2siUoCgiFpdtZ4Q8nxrec6SaqvO                 /y5K8JY/cOTI8fP0x/NyAWMl+K8UNAqAH5LKfcEt3fOV2QsXOQuGtCDhllnlVhGGcQgiCLSSyLOWGkyOhjHgf4NG7U6Wg9KbKyhDPGdYbb2+z7meXa9LVELJqKUUA5aZvypAb0Ea                 hRliDXkgsnm4UoBls3clC97Wo9+oeuEOwsQ+F7VMpOiB7P/9wmNNyC78skQo6mUfZoaEQQc3rinELl+bt1hOK6IeFiJGzBKr/VYmhgjqEutLzhYWyKrCR4zk0Scd8G7KapDPrVZ1                 VrTKieT6fcNkb4fygjjdIOUD9pfGgHVkOInLC+KUIv+a0hGxryXsGKlCp3+T2KNUPxhZp3DVkn91ZAfqA52cFXhkKRVw8J4Ila6YsIrMaUW1K7pysAwNebxOaSa6mOepL/A7/+nh                 fjpxueqC8llPJeJAkZ+EbRyf42jI4/b6FeV5ClhHEYu3upWRmi9t74KDzuYA83d1Nuc1hvAf7mA==')], reqType=GET, preview=False)
D 2021-01-06 23:48:51,676 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2021-01-06 23:48:51,691 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=q4m5mbJCsmJbXk2JrzsgWti2sqR%2f01MHwIXQRg446                 S%2fUiku9K8OQbtNdibVaBErgiePESrlJLXDuMQy1q8kgzdwCwFGEvPiWvdlA44kI5giZ1Vy8RpeuUJkKe7eeF1JC5Xs%2bNgoHSop2AD44n67wefaqDA9t%2fxEPfIgppu1bxM4                 rwCdJwlyDJZoGbl0WtgERSeeP3AqBJvAlRDMLF77%2fXGbITfpACHy6BehQ93ig6bK5OdTk1mWU3kgXGTIjH8ga64wX%2f1%2bVSme%2fgS5hfw4wmAO05tYvXy%2bkvlzut1Y6Q                 N7pnjXcPvULqetwr0Pw%2fE5bhjA0FE9Zuc8xyax9FViY24nH29Ha336fW%2bAJtACTtU1T5ZxpijMrcZoDC91wkA5kKm%2f6pr16RFJH%2bWU9BBcg%2f%2fuuCqG%2fSLZx2si                 UoCgiFpdtZ4Q8nxrec6SaqvO%2fy5K8JY%2fcOTI8fP0x%2fNyAWMl%2bK8UNAqAH5LKfcEt3fOV2QsXOQuGtCDhllnlVhGGcQgiCLSSyLOWGkyOhjHgf4NG7U6Wg9KbKyhDPGdY                 bb2%2bz7meXa9LVELJqKUUA5aZvypAb0EahRliDXkgsnm4UoBls3clC97Wo9%2boeuEOwsQ%2bF7VMpOiB7P%2f9wmNNyC78skQo6mUfZoaEQQc3rinELl%2bbt1hOK6IeFiJGzB                 Kr%2fVYmhgjqEutLzhYWyKrCR4zk0Scd8G7KapDPrVZ1VrTKieT6fcNkb4fygjjdIOUD9pfGgHVkOInLC%2bKUIv%2ba0hGxryXsGKlCp3%2bT2KNUPxhZp3DVkn91ZAfqA52cFX                 hkKRVw8J4Ila6YsIrMaUW1K7pysAwNebxOaSa6mOepL%2fA7%2f%2bnhfjpxueqC8llPJeJAkZ%2bEbRyf42jI4%2fb6FeV5ClhHEYu3upWRmi9t74KDzuYA83d1Nuc1hvAf7mA%                 3d%3d
I 2021-01-06 23:48:52,758 yowsup.common.http.warequest - b'{"login":"9477XXXXXXX","status":"fail","reason":"bad_token"}\n'
status: b'fail'
reason: b'bad_token'
login: b'9477XXXXXXX'

**Config file**

Just pasting the "yowsup/env/env_android.py" file to see if I have done anything wrong.

from .env import YowsupEnv
import base64
import hashlib

class AndroidYowsupEnv(YowsupEnv):
    _SIGNATURE = "MIIDMjCCAvCgAwIBAgIETCU2pDALBgcqhkjOOAQDBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNV" \
        "BAcTC1NhbnRhIENsYXJhMRYwFAYDVQQKEw1XaGF0c0FwcCBJbmMuMRQwEgYDVQQLEwtFbmdpbmVlcmluZzEUMBIGA1UEAxMLQnJ" \
        "pYW4gQWN0b24wHhcNMTAwNjI1MjMwNzE2WhcNNDQwMjE1MjMwNzE2WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5" \
        "pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExFjAUBgNVBAoTDVdoYXRzQXBwIEluYy4xFDASBgNVBAsTC0VuZ2luZWVyaW5nMRQwEg" \
        "YDVQQDEwtCcmlhbiBBY3RvbjCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+AtlEm" \
        "aUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb+DtX58aophUPBPuD9tPFHsMCN" \
        "VQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jr" \
        "qgvlXTAs9B4JnUVlXjrrUWU/mcQcQgYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO" \
        "8yk8b6oUZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GFAAKBgQDRGYtLgWh7zyRtQainJfCpiaUbzjJuhMgo4fVWZIvXHaS" \
        "HBU1t5w//S0lDK2hiqkj8KpMWGywVov9eZxZy37V26dEqr/c2m5qZ0E+ynSu7sqUD7kGx/zeIcGT0H+KAVgkGNQCo5Uc0koLRW" \
        "YHNtYoIvt5R3X6YZylbPftF/8ayWTALBgcqhkjOOAQDBQADLwAwLAIUAKYCp0d6z4QQdyN74JDfQ2WCyi8CFDUM4CaNB+ceVXd" \
        "KtOrNTQcc0e+t"

    _MD5_CLASSES = "VRW2nQS8XrRMczQeAwaJgA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.21.1"
    _OS_NAME = "Android"
    _OS_VERSION = "8.0.0"
    _DEVICE_NAME = "star2lte"
    _MANUFACTURER = "samsung"
    _BUILD_VERSION = "star2ltexx-user 8.0.0 R16NW G965FXXU1ARCC release-keys"
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
    .
    .

**Versions**

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.9.2
protobuf       v3.12.2

**To Reproduce**

Just run below register command

python3.6 yowsup-cli registration -r sms -c zap.conf -E android -d

**Expected behavior**
Registration should return ok

**OS (please complete the following information):**
Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Additional context**
N/A

**Comment by ironbat1** [comment]
you need to add last two numbers to register, 
_VERSION = "2.21.1.XX"

But while using yowsup delete them,
You only need these 2 numbers on registration

**Comment by mthushara** [comment]
"ironbat1" Thank you very much for the direction.
It is working now.
Highly appreciate your prompt response with correct instruction.

Good Luck !

Cheers
