### ISSUE TITLE
Reg failed after input OTP: "reason":"temporarily_unavailable"

### ISSUE THREAD

**Issue by bahtiarp** [tgalal/yowsup#3051]
Today i try several time to reg new number, but always failed: "reason":"temporarily_unavailable".
Is there anybody get the same problem?
+/- 3 weeks ago till successful for registration.

![image](https://user-images.githubusercontent.com/3410804/107653935-c03bf500-6cb4-11eb-8038-cd48e722b4d0.png)

**Comment by endroemily** [comment]
I didn't try but maybe client_static_keypair is now invalid in the new version. Because client_static_keypair_pwd_enc is used in new whatsapp versions.

**Comment by bahtiarp** [comment]
i found altenatif solution to my case. Just set temporary the wa version to v3 for reg only.
