### ISSUE TITLE
Who can send me a complete configuration file of yowsup?

### ISSUE THREAD

**Issue by lovethiscode** [tgalal/yowsup#3057]
I want to develop a mobile tool(android), which can export WhatsApp account information on android into Yowsup configuration file, so that I can directly use Yowsup to log in WhatsApp. But I don't have a complete Yowsup configuration file template, anyone who wants to send one to me: jinxing007x@outlook.com

Because WhatsApp's client_static_keypair_pwd_enc is encrypted and can't be used directly, many people need a tool that can decrypt it.

**Comment by ben221199** [comment]
https://github.com/ben221199/WAPI/wiki/WhatsApp-Keystore

**Comment by ben221199** [comment]
config.json (`C:\Users\<username>\AppData\Local\yowsup\yowsup\<number>`):
```json
{
    "__version__": 1,
    "cc": "7",
    "client_static_keypair": "base64-client_static_keypair",
    "edge_routing_info": "base64-edge_routing_info",
    "expid": "base64-expid",
    "fdid": "uuid-fdid",
    "id": "base64-id-20bytes",
    "login": "<cc+in>",
    "mcc": "<mcc>",
    "mnc": "<mnc>",
    "phone": "<cc+in>",
    "server_static_public": "base64-server_static_public",
    "sim_mcc": "<sim_mcc>",
    "sim_mnc": "<sim_mnc>"
}```

**Comment by ben221199** [comment]
yowsup.conf (`$REPO/`):
```properties
client_static_keypair=base64-client_static_keypair
expid=base64-expid
fdid=uuid-fdid
id=base64-id-20bytes
login=cc+in
mcc=mcc
mnc=mnc
phone=cc+in
sim_mcc=sim_mcc
sim_mnc=sim_mnc
```

**Comment by ben221199** [comment]
Thats it.

**Comment by lovethiscode** [comment]
> @lovethiscode wdyt? Can we use your tool to export complete yowsup config + axolotl.db for yowsup?

I have exported the configuration file of Yowsup. If you need to export the axolotl.db , you need to give me a template so that I can export the axolotl.db of WhatsApp.
 send one to me: jinxing007x@outlook.com

yowsup_config_tool.apk  can help you.
https://github.com/lovethiscode/Gorgeous-Whatsapp

**Comment by ben221199** [comment]
I still don't understand this issue. I think it is a stupid question.

**Comment by lovethiscode** [comment]
I will close this issue now and let's discuss in another place.

https://github.com/lovethiscode/Gorgeous-Whatsapp/wiki/Export-complete-yowsup-config---axolotl.db-for-yowsup
