### ISSUE TITLE
General ban problems

### ISSUE THREAD

**Issue by brkphp** [tgalal/yowsup#3065]
Hello everyone, normally the register / login processes were working fine. Registration has been successful for 2-3 days, but I get 403 while logging in. Is this a known issue now?
I can rarely login without errors.

Example results:
10/10 successful register
10/3 successful login

**Debug output**
SUCCESS 
----

[offline]:/L
D 2021-03-31 11:21:42,776 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-03-31 11:21:42,776 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
D 2021-03-31 11:21:42,776 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e12.whatsapp.net', 443))
D 2021-03-31 11:21:42,856 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-03-31 11:21:42,856 yowsup.layers.network.layer - Connected
D 2021-03-31 11:21:42,856 yowsup.axolotl.factory - get_manager(profile_name=4915219351602, username=4915219351602)
D 2021-03-31 11:21:42,857 yowsup.axolotl.manager - Initialized AxolotlManager [username=4915219351602, db=/root/.config/yowsup/4915219351602/axolotl.db]
D 2021-03-31 11:21:42,857 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-03-31 11:21:42,892 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-03-31 11:21:42,892 yowsup.axolotl.manager - load_unsent_prekeys
D 2021-03-31 11:21:42,892 yowsup.layers.noise.layer - Received auth event
D 2021-03-31 11:21:42,893 yowsup.env.env - Env not set, setting it to android
D 2021-03-31 11:21:42,893 yowsup.env.env - Current env changed to android
D 2021-03-31 11:21:42,893 yowsup.layers.noise.layer - Performing handshake [username= 4915219351602, passive=False]
D 2021-03-31 11:21:42,893 yowsup.layers.noise.layer - Starting handshake worker
D 2021-03-31 11:21:43,369 yowsup.profile.profile - write_config for 4915219351602
D 2021-03-31 11:21:43,369 yowsup.common.tools - writeProfileData(profile_name=4915219351602, name=config.json, val=[omitted])
D 2021-03-31 11:21:43,369 yowsup.common.tools - Writing /root/.config/yowsup/4915219351602/config.json
D 2021-03-31 11:21:43,737 yowsup.layers.logger.layer - rx:
<success location="odn" creation="1617180640" t="1617189703" props="26" />
D 2021-03-31 11:21:43,738 yowsup.layers.protocol_iq.layer - starting ping thread.
Auth: Logged in!

ERROR 
----
[offline]:/L
D 2021-03-31 11:21:00,652 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-03-31 11:21:00,652 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
D 2021-03-31 11:21:00,652 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e15.whatsapp.net', 443))
D 2021-03-31 11:21:00,734 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-03-31 11:21:00,734 yowsup.layers.network.layer - Connected
D 2021-03-31 11:21:00,734 yowsup.axolotl.factory - get_manager(profile_name=4915219158183, username=4915219158183)
D 2021-03-31 11:21:00,735 yowsup.axolotl.manager - Initialized AxolotlManager [username=4915219158183, db=/root/.config/yowsup/4915219158183/axolotl.db]
D 2021-03-31 11:21:00,735 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-03-31 11:21:00,782 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-03-31 11:21:00,782 yowsup.axolotl.manager - load_unsent_prekeys
I 2021-03-31 11:21:00,798 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2021-03-31 11:21:00,798 yowsup.layers.noise.layer - Received auth event
D 2021-03-31 11:21:00,799 yowsup.env.env - Env not set, setting it to android
D 2021-03-31 11:21:00,799 yowsup.env.env - Current env changed to android
D 2021-03-31 11:21:00,799 yowsup.layers.noise.layer - Performing handshake [username= 4915219158183, passive=True]
D 2021-03-31 11:21:00,799 yowsup.layers.noise.layer - Starting handshake worker
D 2021-03-31 11:21:01,305 yowsup.profile.profile - write_config for 4915219158183
D 2021-03-31 11:21:01,305 yowsup.common.tools - writeProfileData(profile_name=4915219158183, name=config.json, val=[omitted])
D 2021-03-31 11:21:01,305 yowsup.common.tools - Writing /root/.config/yowsup/4915219158183/config.json
D 2021-03-31 11:21:01,413 yowsup.layers.logger.layer - rx:
<failure reason="403" location="odn" />
general: Login Failed, reason: 403

**Versions**
yowsup-cli v3.2.0
using:
  consonance v0.1.3-1
  protobuf v4.0.0rc2
  cryptography v3.3.2
  yowsup v3.2.3
  dissononce v0.34.3
  python-axolotl v0.2.2

**OS (ubuntu 18.04):**

**Comment by lovethiscode** [comment]
There is no maintenance, and Blocked has been mentioned by the author

**Comment by safciplak** [comment]
Let's fork and development now.

**Comment by brkphp** [comment]
> There is no maintenance, and Blocked has been mentioned by the author

We had already updated to 4.0 and we could get 10/10 login 1 week ago, I think whatsapp got a little patch.
(I know there can always be a ban issue)

**Comment by ironbat1** [comment]
Are you using the latest version of WP on "yowsup/env/env_android.py"

**Comment by brkphp** [comment]
I was using the latest version.

I found the problem ..

**If a 401/403 error is received on a server too many times, Whatsapp spams that server for 1-2 days and does not allow it to login with the new number.**

Thanks everyone I am closing the issue.

**Comment by safciplak** [comment]
Hi Burak
Can you send me an email.
I waiting thank you so much.

Best regards
Safak Ciplak
Software Craftsman
