### ISSUE TITLE
Cannot get presence for some of my numbers

### ISSUE THREAD

**Issue by pooja29193** [tgalal/yowsup#3076]
I'm using JIO numbers for whatsapp account. it was working fine till last few days back. Now i have noticed that for few numbers, its not giving presence for any number & for few it gives presence notification but only for few numbers, for some of the numbers, it does not return any response

**Comment by AkashVirani** [comment]
@pooja29193  I am also facing same issue.

**Comment by endroemily** [comment]
@pooja29193 @AkashVirani What numbers do you have this problem with? Can you share a few numbers that works and does not work as an example?

**Comment by pooja29193** [comment]
The problem is not with the numbers, because those same numbers which are working on server, are working on other

**Comment by sebastian275** [comment]
which yowsup and whatsapp app version u r using ?

**Comment by endroemily** [comment]
> The problem is not with the numbers, because those same numbers which are working on one server, are working on other

It is interesting. It seems unlikely that it would do something like this, I am using the same feature and I did not have this problem.

**Comment by AkashVirani** [comment]
@sebastian275 @endroemily : I am using whatsapp version 2.21.10.16 and latest yowsup version.

I have started scanning numbers with yowsup-cli after reaching to 200+ phone numbers, I am not getting presence even if we are adding that number in our contact (/contacts sync +123456...). I tried with older phone numbers and it was working fine

**Comment by endroemily** [comment]
> @sebastian275 @endroemily : I am using whatsapp version 2.21.10.16 and latest yowsup version.
> 
> I have started scanning numbers with yowsup-cli after reaching to 200+ phone numbers, I am not getting presence even if we are adding that number in our contact (/contacts sync +123456...). I tried with older phone numbers and it was working fine

Are you watching 200 numbers with only 1 client?

**Comment by AkashVirani** [comment]
@endroemily : Do you have any idea about the limit, or we can remove older phone numbers and start watching new numbers?

**Comment by endroemily** [comment]
> @endroemily : Do you have any idea about the limit, or we can remove older phone numbers and start watching new numbers?

However, I do not know what the upper limit is. How many numbers have you watched the most with 1 client? Also yes, you can remove old numbers and watch new ones.

**Comment by AkashVirani** [comment]
@endroemily : It was around 200 numbers only, also unsubscribe in the presence not working because after unsubscribing also we are getting presence for that number.
Please let me know if you have any other option to remove older number and adding new one.

**Comment by mprataps** [comment]
> @endroemily : It was around 200 numbers only, also unsubscribe in the presence not working because after unsubscribing also we are getting presence for that number.
> 
> Please let me know if you have any other option to remove older number and adding new one.
> 
> 

Facing same issues. Help please

**Comment by pooja29193** [comment]
For me it was working for max 100 numbers only,

**Comment by pooja29193** [comment]
But now have started getting this weird issue that for few numbers, it gives presence but not for few

**Comment by mprataps** [comment]
presence unsubscribe not working for me

**Comment by mprataps** [comment]
> But now have started getting this weird issue that for few numbers, it gives presence but not for few
> 
> 

Try with different wa acc

**Comment by AkashVirani** [comment]
@endroemily: You mentioned above that we can remove old numbers and see the new one. Can you please guide me on that part?

**Comment by pooja29193** [comment]
today i checked and found that my issue is automatcally resolved. nw tracking is working for all numbers

**Comment by mprataps** [comment]
@pooja29193 my presence unsubscribe not working . Any solution 

Thanks.

**Comment by AkashVirani** [comment]
> today i checked and found that my issue is automatcally resolved. nw tracking is working for all numbers

@pooja29193 : for how many numbers it is working can you check and confirm?

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
