### ISSUE TITLE
Presence subscribe limit

### ISSUE THREAD

**Issue by AkashVirani** [tgalal/yowsup#3081]
I was trying to subscribe the presence and saw that it is working till 190 to 200 numbers. After that I was not getting presence for any new number. I was also not able to unsubscribe the presence

Can someone guide me on that?
Many thanks in advance.

**Comment by ermancanitatli** [comment]
- You can't listen to 200 numbers.After number 40, your previous listen will be unsubscribed.
- Unsubscribe is not working for now unfortunately

**Comment by AkashVirani** [comment]
@ermancanitatli : I am good if I can listen 40 numbers. but the issue is after subscribing 200 numbers, I am not able to listen any numbers. If I am trying to do, I am not getting any response.
Do you have any idea why it is behaving like this?

**Comment by ermancanitatli** [comment]
Security precautions.
Whatsapp wants to block this situation because privacy violation

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
