### ISSUE TITLE
Can't login , Register ok

### ISSUE THREAD

**Issue by hummans** [tgalal/yowsup#3082]
i have tryed  to many new numbers and fresh install on diferent linux,it registers allright but when i try to login /L it gives me the same error 
Please any help ? 
i m new at this 
THNX

[offline]:/L
I 2021-06-18 02:33:23,426 yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
I 2021-06-18 02:33:23,565 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2021-06-18 02:33:23,567 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.8/asyncore.py", line 438, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.8/asyncore.py", line 426, in handle_connect_event
    self.handle_connect()
  File "/root/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/root/yowsup/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/root/yowsup/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/root/yowsup/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/root/yowsup/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
    self.broadcastEvent(
  File "/root/yowsup/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/root/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/root/yowsup/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/root/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/root/yowsup/yowsup/layers/noise/layer.py", line 98, in on_auth
    useragent=UserAgentConfig(
  File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected: 
[offline]:

**Comment by sprestay** [comment]
> i have tryed to many new numbers and fresh install on diferent linux,it registers allright but when i try to login /L it gives me the same error
> Please any help ?
> i m new at this
> THNX
> 
> I 2021-06-18 02:33:23,426 yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
> I 2021-06-18 02:33:23,565 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> E 2021-06-18 02:33:23,567 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
> File "/usr/lib/python3.8/asyncore.py", line 91, in write
> obj.handle_write_event()
> File "/usr/lib/python3.8/asyncore.py", line 438, in handle_write_event
> self.handle_connect_event()
> File "/usr/lib/python3.8/asyncore.py", line 426, in handle_connect_event
> self.handle_connect()
> File "/root/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
> self.connectionCallbacks.onConnected()
> File "/root/yowsup/yowsup/layers/network/layer.py", line 54, in onConnected
> self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
> File "/root/yowsup/yowsup/layers/**init**.py", line 94, in emitEvent
> self.__upper.emitEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 94, in emitEvent
> self.__upper.emitEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 94, in emitEvent
> self.__upper.emitEvent(yowLayerEvent)
> [Previous line repeated 3 more times]
> File "/root/yowsup/yowsup/layers/**init**.py", line 88, in emitEvent
> if self.__upper and not self.__upper.onEvent(yowLayerEvent):
> File "/root/yowsup/yowsup/layers/**init**.py", line 212, in onEvent
> stopEvent = stopEvent or s.onEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 109, in onEvent
> return self.event_callbacks[eventName](yowLayerEvent)
> File "/root/yowsup/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
> self.broadcastEvent(
> File "/root/yowsup/yowsup/layers/**init**.py", line 202, in subBroadcastEvent
> self.broadcastEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 103, in broadcastEvent
> self.__lower.broadcastEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 103, in broadcastEvent
> self.__lower.broadcastEvent(yowLayerEvent)
> File "/root/yowsup/yowsup/layers/**init**.py", line 103, in broadcastEvent
> self.__lower.broadcastEvent(yowLayerEvent)
> [Previous line repeated 1 more time]
> File "/root/yowsup/yowsup/layers/**init**.py", line 98, in broadcastEvent
> if self.__lower and not self.__lower.onEvent(yowLayerEvent):
> File "/root/yowsup/yowsup/layers/**init**.py", line 109, in onEvent
> return self.event_callbacks[eventName](yowLayerEvent)
> File "/root/yowsup/yowsup/layers/noise/layer.py", line 98, in on_auth
> useragent=UserAgentConfig(
> File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/useragent.py", line 58, in **init**
> app_version = AppVersionConfig(app_version)
> File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/appversion.py", line 15, in **init**
> self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
> ValueError: too many values to unpack (expected 3)
> 
> general: Disconnected:
> [offline](/L):

Just change _VERSION in env/env_android.py from "1.2.3.4" to "1.2.3"

**Comment by hummans** [comment]
Thanks
but now i m getting this:

[offline]:/L
I 2021-06-21 00:31:32,993 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
I 2021-06-21 00:31:33,259 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected: 
[offline]:

**Comment by tgalal** [comment]
Fixed.
