### ISSUE TITLE
Registration failing with "old_version" with "Android" env

### ISSUE THREAD

**Issue by alexcarpenedo** [tgalal/yowsup#3085]
I've already tested all the ways and the problem still remains...

E 2021-06-23 18:40:37,472 yowsup.config.manager - Could not find a config for username=cc----------, paths checked: /home/servidor/.config/yowsup/cc----------/config.yo:/home/servidor/.config/yowsup/cc----------/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2021-06-23 18:40:38,073 yowsup.common.http.warequest - b'{"login":"cc----------","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'cc----------'

**Comment by ermancanitatli** [comment]
for login

```
``  _MD5_CLASSES = "9cGBR5d0y9dXWrZd30Yuow=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.21.5"
    _OS_NAME = "Android"
    _OS_VERSION = "8.0.0"
    _DEVICE_NAME = "star2lte"
    _MANUFACTURER = "samsung"
    _BUILD_VERSION = "star2ltexx-user 8.0.0 R16NW G965FXXU1ARCC release-keys"
    _AXOLOTL = True
```

**Comment by SidorinSergey** [comment]
Please kindly try this:
Correct values env_android.py for today:
_VERSION = = "2.21.12" #2.21.12.22
_MD5_CLASSES = "5ym5gLRrSZJQ+ZWWrpHaMg=="

At least registration/validation works :)

**Comment by alirezadigi** [comment]
Hi @SidorinSergey and @ermancanitatli !
I tried both of them but yowsup-cli doesnt work yet.

**Comment by SidorinSergey** [comment]
@alirezadigi 
You have to download a new whastapp apk: https://www.whatsapp.com/android/ and save the version wrote on website (ex: Version 2.18.213)
Run this https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py file.apk,
The MD5 and the version, you have to change the file yowsup/env/env_android.py:
_MD5_CLASSES = "NEW_VALUE"
_VERSION = "NEW_VALUE"

Compile again yowsup

thx https://github.com/tgalal/yowsup/issues/2536#issuecomment-405359251 

as i mentioned before, i only could register and validate account, but not send messages. It seems that each new version you also have to change values according to this pr:
https://github.com/tgalal/yowsup/pull/3045

**Comment by ozymoz** [comment]
Hello there;
The updated information is below but I am getting an error.

up-to-date information

8AsvZ5b5TXrCHaCGHuWEgw==
2.21.14.19 // 2.21.14

error

W 2021-07-16 03:46:48,092 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
{'status': 'fail', 'reason': 'bad_token', 'length': None, 'method': None, 'retry_after': None, 'code': None, 'param': None, 'login': '447985117735', 'type': None, 'sms_wait': None, 'voice_wait': None}

**Comment by leonidasroberto** [comment]
some update to this ?

**Comment by normalscene** [comment]
Just in case someone looking for the latest version and classDex as of 3rd September, 2021:

Version: 2.21.17.25
ClassesDex: RVbKldZNiLEcM2I22tNswA==

**Comment by juangarlop** [comment]
version must contain only 3 octects.

what is about version? is it v4? i don't get connected.

offline]:/L
I 2021-09-03 08:49:09,404 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
I 2021-09-03 08:49:09,535 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected: 
[offline]:


:(

**Comment by tgalal** [comment]
Fixed.
