### ISSUE TITLE
[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by korniarp** [tgalal/yowsup#3087]
Can somebody help me resolve the issue. Attached my client code here.
from socket import AF_INET,socket,SOCK_STREAM
from threading import Thread
#GLOBAL CONSTANTS
#HOST = '27.32.123.32'
 HOST = "localhost"
PORT = 5500
ADDR=(HOST,PORT)
BUFSIZ=512

#GLOBAL VARIABLES
messages = []
client_socket = socket(AF_INET,SOCK_STREAM)
client_socket.connect(ADDR)

def receive_messages():
    """
    receive messages from server
    :return: None
    """
    while True:
        try:
            msg = client_socket.recv(BUFSIZ).decode()
            messages.append(msg)
            print(msg)
        except Exception as e:
            print("[EXPECTION]",e)

def send_message(msg):

    """
    send message to server
    :param msg: str
    :return: None
    """
    client_socket.send(bytes(msg,"utf8"))
    if msg == "{quit}" :
        client_socket.close()

receive_thread = Thread(target=receive_messages)
receive_thread.start()

send_message("Kornia")
send_message("hello")

**Comment by ben221199** [comment]
For me, rerunning the process did it.

**Comment by korniarp** [comment]
Hey @ben221199 I will try once again! Thanks!

**Comment by aanaliudin** [comment]
> For me, rerunning the process did it.

Hey @ben221199 you have a source that works ?

Please help me.. sent to me a source on aanaliudin25@gmail.com

Thanks

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
