### ISSUE TITLE
Register Token Error

### ISSUE THREAD

**Issue by muratpolat** [tgalal/yowsup#3094]
I am getting an error while registering.

{'status': 'fail', 'reason': 'bad_token', 'length': None, 'method': None, 'retry_after': None, 'code': None, 'param': None, 'login': '*******', 'type': None, 'sms_wait': None, 'voice_wait': None}

What can I do about it?

**Comment by muratpolat** [comment]
I am getting number with real device. It connects to the server. Once connected, I cannot connect again. If there is someone who will support me on this library, please contact me: kutsalpolat@gmail.com

**Comment by dshetyo** [comment]
Am also getting same error

**Comment by tgalal** [comment]
Please try with latest version and re-open if issue persists.
