### ISSUE TITLE
No error but i got general: Disconnected:

### ISSUE THREAD

**Issue by geek3000** [tgalal/yowsup#3097]
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2021-09-25 21:19:00,515 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
I 2021-09-25 21:19:01,110 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected: 
[offline]:
[offline]:

Version: 2.21.18.17
ClassesDex: clTBUKC4nLHJ+1y5meGNyg==

**Comment by tgalal** [comment]
Please try with latest version and re-open if issue persists
