### ISSUE TITLE
yowsup.axolotl.manager - Loaded 812 unsent prekeys

### ISSUE THREAD

**Issue by lrqxyz** [tgalal/yowsup#3099]
Hey guys, I am trying to run the command, but I get this error below. How can I fix it?

How can I see the error logs, what would be the command?

```
/usr/bin/python3.6 ./yowsup-cli demos -c /etc/zabbix/zap.conf -s 5517xxxxxxxx "Mensagem de teste"
yowsup-cli  v3.6.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2021-10-01 22:19:43,288 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443
I 2021-10-01 22:19:43,434 yowsup.axolotl.manager - Loaded 812 unsent prekeys

```

**Comment by jackRowscal** [comment]
No error

user --debug for debug mode

**Comment by lrqxyz** [comment]
@jackRowscal 

`D 2021-10-04 08:26:32,651 yowsup.stacks.yowstack - Initializing stack
D 2021-10-04 08:26:32,652 yowsup.stacks.yowstack - Constructed Network Layer
D 2021-10-04 08:26:32,652 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2021-10-04 08:26:32,654 yowsup.stacks.yowstack - Constructed Noise Layer
D 2021-10-04 08:26:32,654 yowsup.stacks.yowstack - Constructed Coder Layer
D 2021-10-04 08:26:32,654 yowsup.stacks.yowstack - Constructed Logger Layer
D 2021-10-04 08:26:32,655 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fc82a58a4a8>
D 2021-10-04 08:26:32,655 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fc82b8a9828>
D 2021-10-04 08:26:32,655 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2021-10-04 08:26:32,656 yowsup.stacks.yowstack - Constructed Interface Layer
D 2021-10-04 08:26:32,656 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=15623522963))
D 2021-10-04 08:26:32,656 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-10-04 08:26:32,656 yowsup.layers.network.layer - Connecting to e9.whatsapp.net:443
D 2021-10-04 08:26:32,657 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e9.whatsapp.net', 443))
D 2021-10-04 08:26:32,787 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-10-04 08:26:32,787 yowsup.layers.network.layer - Connected
D 2021-10-04 08:26:32,787 yowsup.axolotl.factory - get_manager(profile_name=15623522963, username=15623522963)
D 2021-10-04 08:26:32,789 yowsup.axolotl.manager - Initialized AxolotlManager [username=15623522963, db=/root/.config/yowsup/15623522963/axolotl.db]
D 2021-10-04 08:26:32,789 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-10-04 08:26:32,797 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-10-04 08:26:32,797 yowsup.axolotl.manager - load_unsent_prekeys
I 2021-10-04 08:26:32,804 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2021-10-04 08:26:32,804 yowsup.layers.noise.layer - Received auth event
D 2021-10-04 08:26:32,804 yowsup.env.env - Env not set, setting it to android
D 2021-10-04 08:26:32,804 yowsup.env.env - Current env changed to android
D 2021-10-04 08:26:32,804 yowsup.layers.noise.layer - Performing handshake [username= 15623522963, passive=True]
D 2021-10-04 08:26:32,805 yowsup.layers.noise.layer - Starting handshake worker
D 2021-10-04 08:26:33,281 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2021-10-04 08:26:33,281 yowsup.layers.network.layer - Disconnected
D 2021-10-04 08:26:33,282 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
`

**Comment by lrqxyz** [comment]
@jackRowscal I already have the 3.0 updates applied as well.

**Comment by tgalal** [comment]
Please try with latest version and re-open if the issue persists.
