### ISSUE TITLE
Authentication failure using the API

### ISSUE THREAD

**Issue by blacklight** [tgalal/yowsup#31]
I've been using Yowsup API for many days flawlessly. Anyway, since 2 days my code suddenly refuses to authenticate to Whatsapp, and on any authentication the auth_fail handler is always triggered. Was something changed in the authentication mechanism? Shall I provide further details?

**Comment by Sree-Ravali** [comment]
Hi,
I used below link for yowsup installation
https://github.com/tgalal/yowsup
I am able to register my number and send messages from command prompt
I am facing issue when I am trying to integrate with SAPUI5
I got the password in this format StxUI7Y0LhFHAO+4iD0BGPGFhjg=
Is this the password format which i have to give as input to python code to authenticate 
Please reply asap

Thanks,
Ravali

**Comment by jlguardi** [comment]
Yes, it is.

**Comment by Sree-Ravali** [comment]
But authentication is not happening
please assist me
