### ISSUE TITLE
Blocks after first login

### ISSUE THREAD

**Issue by gughovh** [tgalal/yowsup#3100]
<ack id="PSAS1487100006" class="notification" type="psa" to="status@broadcast" participant="0@s.whatsapp.net" />

D 2021-10-04 10:16:45,552 yowsup.layers.logger.layer - rx:
<stream:error>
  <ack id="PSAS1487100006" />
</stream:error>
E 2021-10-04 10:16:45,552 yowsup.layers.interface.interface - Stream Error type: ack
{'ack': None}

I 2021-10-04 10:16:45,552 yowsup.layers.interface.interface - Initiating reconnect
D 2021-10-04 10:16:45,552 yowsup.layers.protocol_iq.layer - stopping ping thread
E 2021-10-04 10:16:45,564 yowsup.layers.network.dispatcher.dispatcher_socket - Traceback (most recent call last):

**Comment by phpjoker** [comment]
email to whatsapp and request unblock! :(

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
