### ISSUE TITLE
Does this lib works without getting blocked?

### ISSUE THREAD

**Issue by dshetyo** [tgalal/yowsup#3101]
I tried read android whats app contect resolver of whats app and my whats app account got banned. This was un related to 'yowsup' lib.

A) Now i want to try yowsup, but fear that by new acccount will be blocked too. Is this lib save?
B) I just want to get last seen time/online time of a user. Are there any easy ways which can be used without login ?

**Comment by tgalal** [comment]
Info about blocking: https://github.com/tgalal/yowsup/wiki/FAQ.
For consultancy related to specific use-cases please refer to the [README](https://github.com/tgalal/yowsup).
