### ISSUE TITLE
Registration cli not working

### ISSUE THREAD

**Issue by dshetyo** [tgalal/yowsup#3104]
wsup-cli registration --requestcode sms --phone 919322695940 --cc 91 --mcc 404 --mnc 86 -d
```

D 2021-10-10 10:31:49,724 yowsup.config.manager - Detecting config for username=919322695940, dir=/Users/dshetyo/Library/Application Support/yowsup/919322695940/
D 2021-10-10 10:31:49,724 yowsup.config.manager - Trying /Users/dshetyo/Library/Application Support/yowsup/919322695940/config.yo
D 2021-10-10 10:31:49,724 yowsup.config.manager - Trying /Users/dshetyo/Library/Application Support/yowsup/919322695940/config.json
E 2021-10-10 10:31:49,724 yowsup.config.manager - Could not find a config for username=919322695940, paths checked: /Users/dshetyo/Library/Application Support/yowsup/919322695940/config.yo:/Users/dshetyo/Library/Application Support/yowsup/919322695940/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2021-10-10 10:31:49,889 yowsup.axolotl.factory - get_manager(username=919322695940)
D 2021-10-10 10:31:49,906 yowsup.axolotl.manager - Initialized AxolotlManager [username=919322695940, db=/Users/dshetyo/Library/Application Support/yowsup/919322695940/axolotl.db]
D 2021-10-10 10:31:49,911 yowsup.axolotl.manager - load_latest_signed_prekey
D 2021-10-10 10:31:49,911 yowsup.axolotl.manager - generate_signed_prekey
D 2021-10-10 10:31:49,912 yowsup.axolotl.manager - load_latest_signed_prekey
D 2021-10-10 10:31:49,918 yowsup.env.env - Env not set, setting it to android
D 2021-10-10 10:31:49,918 yowsup.env.env - Current env changed to android
D 2021-10-10 10:31:49,918 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2021-10-10 10:31:49,918 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2021-10-10 10:31:49,918 yowsup.common.http.warequest - Encrypting parameters
D 2021-10-10 10:31:49,919 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=91&in=9322695940&lg=en&lc=GB&mistyped=6&authkey=WPla6bmd1h60OU%2dS3m9MYlnGvhswkXsWtU4q9Eny%5fiE&e_regid=Wk3qSw&e_keytype=BQ&e_ident=agYwqB4IABGZxTH%2db6w6R4brGFGTRgIZ%2ddiWMNXhVW4&e_skey_id=AAAA&e_skey_val=OEM3QXXVUrbvMgCT5q1lxW66eSLGWsQbLO%2dZCbqGiTE&e_skey_sig=4gDXix%2dMAYpd2SBTJX9FZCFjYjZupGx9l4JwnReklWheMEbdbvwuUHP%2dNqP9hs%2dXygHYd6j7zCY4920eTA0HBw&fdid=ffbdca18%2d8235%2d437c%2d960b%2d8a0532761592&expid=FDlQkOn0TtODw4wmIS%5fkMA&network_radio_type=1&simnum=1&hasinrc=1&pid=8783&rc=0&mcc=404&mnc=086&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=L6VFKdbwxX8logatJ%2fMDaJcQQRo%3d&hasav=1&id=%5f%a3%81T%f8o%c7X%a8%df%0cS%8a%c0%87%ffK%e0%3b%03
D 2021-10-10 10:31:49,921 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'EzkWO9PweypLPNpomBqf+r7yqss5lEChBz1aESdU0geNHA0KYSk20iuVMTUQZ8NC0jbdRdHaxPtmIlmpDa2Pe+Bdapvmb1rPDoqyfriRCvLMNKX8Hkp4mvBwS58/Fswekfa0PntJhY6TC4MnhfHrqrl1af0OEWO2y9a6bKjcgUF4hn9KRXxdtAuuPOlyiEQnZIP8kkNb41Ewx5uIi4Vxzq8F05dX1P9etaMiziTFRSyY39HyISvh6fkMTzzr+tDAGaS+AY0uxh/K4GH9wX6PkKxfYc4jj+f3z/qMRSbwIqhiRPQBB1qBM9Ltl+utGqJzdIeUl/4RNsszYi4wmbG51wVTRFTAKiHErCNhS2KGMM1A2IbhIw2FuR8kDsYhxVrp/L9aFDbAuJa0dUKHWaRXL6H40az0qeewDicHYnYapdN31nwjlhEwwVheCWhdBsetrSSNw/KrWF1QQ7FM0MUePV+A/2oqSD+zugI8qd82O7T7D91HUGmEyCtvTkjAlpgGPLC3y5kLjsigIXtNpNfnjNbRmwNHpxFoFoTBnhbqK5e0z1EYj9fxky65su8A+X3Pq1YE1txJvZ+jY6BD8us+qIGox+X5w7l/iMQWOYd0fHqEPZ40CuH64t8k2+mUJ+ayVoEtTQj8gaXI/ENj7wJkR8dkbKIQL4ZsUQ7mOaDkaw5RLUm9kG6gxeJ/IKH6nxYcHjpge+86Vce9+X1qaOPbiARYT2V15f7+xOPdJOnQpmjP2eKMVHO7UHb9ghm6Y0lb9VM99+YLlNO2T+N19htK3uBrv3qzog3aepsuxFFjsKQ83giPbxKCiUT7j62P0tpLxt9EXIxV5iqM+slI4Y5R8k63tZjSsIYhFPFOtRq9fYn7JFHPh0/vn6u26r9ebiyDWlAnplMFiVFabfwytPH3roE6++tBoplZWZEkU2M=')], reqType=GET, preview=False)
D 2021-10-10 10:31:49,923 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2021-10-10 10:31:49,943 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=EzkWO9PweypLPNpomBqf%2br7yqss5lEChBz1aESdU0geNHA0KYSk20iuVMTUQZ8NC0jbdRdHaxPtmIlmpDa2Pe%2bBdapvmb1rPDoqyfriRCvLMNKX8Hkp4mvBwS58%2fFswekfa0PntJhY6TC4MnhfHrqrl1af0OEWO2y9a6bKjcgUF4hn9KRXxdtAuuPOlyiEQnZIP8kkNb41Ewx5uIi4Vxzq8F05dX1P9etaMiziTFRSyY39HyISvh6fkMTzzr%2btDAGaS%2bAY0uxh%2fK4GH9wX6PkKxfYc4jj%2bf3z%2fqMRSbwIqhiRPQBB1qBM9Ltl%2butGqJzdIeUl%2f4RNsszYi4wmbG51wVTRFTAKiHErCNhS2KGMM1A2IbhIw2FuR8kDsYhxVrp%2fL9aFDbAuJa0dUKHWaRXL6H40az0qeewDicHYnYapdN31nwjlhEwwVheCWhdBsetrSSNw%2fKrWF1QQ7FM0MUePV%2bA%2f2oqSD%2bzugI8qd82O7T7D91HUGmEyCtvTkjAlpgGPLC3y5kLjsigIXtNpNfnjNbRmwNHpxFoFoTBnhbqK5e0z1EYj9fxky65su8A%2bX3Pq1YE1txJvZ%2bjY6BD8us%2bqIGox%2bX5w7l%2fiMQWOYd0fHqEPZ40CuH64t8k2%2bmUJ%2bayVoEtTQj8gaXI%2fENj7wJkR8dkbKIQL4ZsUQ7mOaDkaw5RLUm9kG6gxeJ%2fIKH6nxYcHjpge%2b86Vce9%2bX1qaOPbiARYT2V15f7%2bxOPdJOnQpmjP2eKMVHO7UHb9ghm6Y0lb9VM99%2bYLlNO2T%2bN19htK3uBrv3qzog3aepsuxFFjsKQ83giPbxKCiUT7j62P0tpLxt9EXIxV5iqM%2bslI4Y5R8k63tZjSsIYhFPFOtRq9fYn7JFHPh0%2fvn6u26r9ebiyDWlAnplMFiVFabfwytPH3roE6%2b%2btBoplZWZEkU2M%3d
I 2021-10-10 10:31:50,344 yowsup.common.http.warequest - b'{"login":"919322695940","reason":"old_version","status":"fail"}\n'
status: b'fail'
reason: b'old_version'
login: b'919322695940'
```

Any help ?
```

yowsup-cli version
yowsup-cli v3.2.0
Using yowsup v3.2.3
```

**Comment by meshkin** [comment]
same problem

**Comment by sijumanuel** [comment]
same problem

**Comment by meshkin** [comment]
I fixed problem by replace _VERSION & _MD5_CLASSES values (yowsup/env/env_android.py) with:
_VERSION=2.21.22.23
_MD5_CLASSES=MLwX3h0zuSgWY1Oc7sxHXQ==

I changed them and rebuild it and passed this step.
but when I want send message, received bellow error:
`File "/usr/local/lib/python3.7/site-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)`
then i change _VERSION to 3 octed => _VERSION=2.21.22 and try send message again, but issued bellow error:
`[offline]:/L
D 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443
D 2021-11-16 05:57:40,500 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e4.whatsapp.net', 443))
D 2021-11-16 05:57:40,735 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-11-16 05:57:40,735 yowsup.layers.network.layer - Connected
D 2021-11-16 05:57:40,735 yowsup.axolotl.factory - get_manager(profile_name=XXXXXXXXXXXX, username=XXXXXXXXXXXX)
D 2021-11-16 05:57:40,736 yowsup.axolotl.manager - Initialized AxolotlManager [username=XXXXXXXXXXXX, db=/root/.config/yowsup/XXXXXXXXXXXX/axolotl.db]
D 2021-11-16 05:57:40,737 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - load_unsent_prekeys
I 2021-11-16 05:57:40,741 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Received auth event
D 2021-11-16 05:57:40,742 yowsup.env.env - Env not set, setting it to android
D 2021-11-16 05:57:40,742 yowsup.env.env - Current env changed to android 
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Performing handshake [username= XXXXXXXXXXXX, passive=True]
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Starting handshake worker
D 2021-11-16 05:57:41,219 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2021-11-16 05:57:41,220 yowsup.layers.network.layer - Disconnected
D 2021-11-16 05:57:41,237 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: 
[offline]:`

no any idea?
Do you have this problem too?

**Comment by ozymoz** [comment]
> I fixed problem by replace _VERSION & _MD5_CLASSES values (yowsup/env/env_android.py) with: _VERSION=2.21.22.23 _MD5_CLASSES=MLwX3h0zuSgWY1Oc7sxHXQ==
> 
> I changed them and rebuild it and passed this step. but when I want send message, received bellow error: `File "/usr/local/lib/python3.7/site-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__ self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected) ValueError: too many values to unpack (expected 3)` then i change _VERSION to 3 octed => _VERSION=2.21.22 and try send message again, but issued bellow error: `[offline]:/L D 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Created asyncore dispatcher I 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443 D 2021-11-16 05:57:40,500 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e4.whatsapp.net', 443)) D 2021-11-16 05:57:40,735 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect D 2021-11-16 05:57:40,735 yowsup.layers.network.layer - Connected D 2021-11-16 05:57:40,735 yowsup.axolotl.factory - get_manager(profile_name=XXXXXXXXXXXX, username=XXXXXXXXXXXX) D 2021-11-16 05:57:40,736 yowsup.axolotl.manager - Initialized AxolotlManager [username=XXXXXXXXXXXX, db=/root/.config/yowsup/XXXXXXXXXXXX/axolotl.db] D 2021-11-16 05:57:40,737 yowsup.axolotl.manager - level_prekeys(force=False) D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - len(pending_prekeys) = 812 D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - load_unsent_prekeys I 2021-11-16 05:57:40,741 yowsup.axolotl.manager - Loaded 812 unsent prekeys D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Received auth event D 2021-11-16 05:57:40,742 yowsup.env.env - Env not set, setting it to android D 2021-11-16 05:57:40,742 yowsup.env.env - Current env changed to android D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Performing handshake [username= XXXXXXXXXXXX, passive=True] D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Starting handshake worker D 2021-11-16 05:57:41,219 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close D 2021-11-16 05:57:41,220 yowsup.layers.network.layer - Disconnected D 2021-11-16 05:57:41,237 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False general: Disconnected: [offline]:`
> 
> no any idea? Do you have this problem too?

Country Code: 7
Phone Number: 79619209609
W 2021-11-16 14:36:44,959 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
{'status': 'sent', 'reason': None, 'length': 6, 'method': 'sms', 'retry_after': 64, 'code': None, 'param': None, 'login': '79619209609', 'type': None, 'sms_wait': 65, 'voice_wait': 65}
Code: 701901
W 2021-11-16 14:37:33,372 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
Traceback (most recent call last):
  File "/Users/ozymoz/register.py", line 34, in <module>
    config.edge_routing_info = base64.b64decode(result['edge_routing_info'])
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by meshkin** [comment]
yes of course, i received this error at the end of registration code step, but because I received result as a json with :
`{"ststus": "ok", ... "id":"XXXXXXXXXXXXXXXXXXXXXXXX", ...}`

I thought the result is successful and continue next step for send message, then got the top error.

**Comment by tgalal** [comment]
fixed.
