### ISSUE TITLE
Presence Subscribe always giving offline notification.

### ISSUE THREAD

**Issue by nightcoder22** [tgalal/yowsup#3106]
Recently I observed that after subscribing for presence, yowsup sends back only offline status even for online. i.e, whenever contact is online I get an offline response and when the contact becomes offline I again get an offline response.
Anyone else facing the same issue?

**Comment by kylonrizoki** [comment]
It doesn't matter if you take it offline again. this happens sometimes in yowsup. it has been for a long time.

the most important problem;

yowsup showing offline when target people is online.

I absolutely agree with you. I have that same problem.

**Comment by nightcoder22** [comment]
Exactly that is what I am saying. Even when contact is online. Yowsup emits an offline event. For some number, this thing works fine.

**Comment by kylonrizoki** [comment]
Is there any people who living a same problem ?

**Comment by kylonrizoki** [comment]
> Recently I observed that after subscribing for presence, yowsup sends back only offline status even for online. i.e, whenever contact is online I get an offline response and when the contact becomes offline I again get an offline response. Anyone else facing the same issue?

Can you write your md5 key, maybe it is related old key

**Comment by nightcoder22** [comment]
I am using the latest one.. See below.
--> WhatsApp Version Name: 2.21.22.27
--> WhatsApp ClassesDEX MD5 : nEG6qf/MmSVlqTa5kfvJ6g==

**Comment by kylonrizoki** [comment]
are you sure? are they true? because when try with yours, whatsapp dont connect

**Comment by kylonrizoki** [comment]
> Recently I observed that after subscribing for presence, yowsup sends back only offline status even for online. i.e, whenever contact is online I get an offline response and when the contact becomes offline I again get an offline response. Anyone else facing the same issue?

did you solve your problem?

**Comment by kylonrizoki** [comment]
@nightcoder22  did you solve your problem ?

**Comment by kylonrizoki** [comment]
@nightcoder22 did you solve your problem ?

**Comment by ozymoz** [comment]
> @nightcoder22 did you solve your problem ?

developer@ozymoz.com Elimde sorunsuz api mevcut.

**Comment by kylonrizoki** [comment]
> > @nightcoder22 did you solve your problem ?
> 
> [developer@ozymoz.com](mailto:developer@ozymoz.com) Elimde sorunsuz api mevcut.

Discord ?

**Comment by lovethiscode** [comment]
There is a new way to get online status

**Comment by nightcoder22** [comment]
> There is a new way to get online status

Do you mind sharing it?

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
