### ISSUE TITLE
Able to register, unable to send messages

### ISSUE THREAD

**Issue by DoHITB** [tgalal/yowsup#3107]
**Describe the bug**
Hello. I'm trying to use yowsup for my website (as a kind of contact form); so, I have 2 phone lines (to clarify, I own and pay both lines).

I was able to register my second line, but I'm not able to send a testing message to my main line... I'm getting `yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close` error...

Maybe there's some config that I'm missing... I went to wiki and tried to fill all possible fields but looks like it's not working either...

**Debug output**

PFA debug output. The phone marked as "346..." is my second line (the one that is registered via yowsup), and "346xxx" is my main line (used on my mobile phone).

```
#yowsup-cli registration --config-phone 346... --config-cc 34 --config-mcc 214 --config-mnc 01 --config-sim_mcc 214 --config-sim_mnc 01 -r sms
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2021-10-10 18:12:17,906 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
W 2021-10-10 18:12:17,910 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2021-10-10 18:12:18,891 yowsup.common.http.warequest - b'{"flash_type":0,"login":"346...","reason":"incorrect","sms_length":6,"sms_wait":0,"status":"fail","voice_length":6,"voice_wait":0}\n'
I 2021-10-10 18:12:19,541 yowsup.common.http.warequest - b'{"flash_type":1,"length":6,"login":"346...","method":"sms","notify_after":86400,"retry_after":125,"sms_wait":125,"status":"sent","voice_wait":65}\n'
status: b'sent'
length: 6
method: b'sms'
retry_after: 125
login: b'346...'
sms_wait: 125
voice_wait: 65


#yowsup-cli registration --config-phone 346... --config-cc 34 --config-mcc 214 --config-mnc 01 --config-sim_mcc 214 --config-sim_mnc 01 -R xxx-xxx
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2021-10-10 18:14:43,046 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2021-10-10 18:14:44,192 yowsup.common.http.warequest - b'{"edge_routing_info":"E_R_I","login":"346...","security_code_set":false,"status":"ok","type":"existing"}\n'
{
    "__version__": 1,
    "cc": "34",
    "client_static_keypair": "C_S_K",
    "edge_routing_info": "E_R_I",
    "expid": "EXP",
    "fdid": "FDID",
    "id": "ID",
    "login": "346...",
    "mcc": "214",
    "mnc": "01",
    "phone": "346...",
    "sim_mcc": "214",
    "sim_mnc": "01"
}
status: b'ok'
login: b'346...'
type: b'existing'
edge_routing_info: b'E_R_I'



#yowsup-cli demos --config-phone 346... --config-cc 34 --config-id "ID" --config-mcc 214 --config-mnc 01 --config-sim_mcc 214 --config-sim_mnc 01 --config-client_static_keypair "C_S_K" --config-expid "EXP" --config-fdid "FDID" --config-edge_routing_info "E_R_I" -s 346xxx "HOLA" --debug
D 2021-11-16 18:58:08,867 yowsup.config.manager - load(path_or_profile_name=346..., profile_only=False)
D 2021-11-16 18:58:08,868 yowsup.config.manager - _load_path(path=346...)
D 2021-11-16 18:58:08,868 yowsup.config.manager - _load_path couldn't find the path: 346...
D 2021-11-16 18:58:08,868 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2021-11-16 18:58:08,868 yowsup.config.manager - Detecting config for profile=3463..., dir=/something
D 2021-11-16 18:58:08,868 yowsup.config.manager - Trying /something/config.yo
D 2021-11-16 18:58:08,868 yowsup.config.manager - Trying /something/config.json
D 2021-11-16 18:58:08,868 yowsup.config.manager - _load_path(path=/something/config.json)
D 2021-11-16 18:58:08,869 yowsup.config.manager - Detected config type: json
D 2021-11-16 18:58:08,869 yowsup.config.manager - Opening config for reading
D 2021-11-16 18:58:08,869 yowsup.config.manager - Loading config
D 2021-11-16 18:58:08,870 yowsup.profile.profile - Constructed Profile(profile_name=346...)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.6.1
protobuf       v4.0.0rc2


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2021-11-16 18:58:09,137 yowsup.stacks.yowstack - Initializing stack
D 2021-11-16 18:58:09,138 yowsup.stacks.yowstack - Constructed Network Layer
D 2021-11-16 18:58:09,138 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2021-11-16 18:58:09,140 yowsup.stacks.yowstack - Constructed Noise Layer
D 2021-11-16 18:58:09,140 yowsup.stacks.yowstack - Constructed Coder Layer
D 2021-11-16 18:58:09,141 yowsup.stacks.yowstack - Constructed Logger Layer
D 2021-11-16 18:58:09,141 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0xb6032cd0>
D 2021-11-16 18:58:09,141 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0xb5ac1f10>
D 2021-11-16 18:58:09,141 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2021-11-16 18:58:09,142 yowsup.stacks.yowstack - Constructed Interface Layer
D 2021-11-16 18:58:09,142 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=346...))
D 2021-11-16 18:58:09,143 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-11-16 18:58:09,143 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
D 2021-11-16 18:58:09,143 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e7.whatsapp.net', 443))
D 2021-11-16 18:58:09,283 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-11-16 18:58:09,283 yowsup.layers.network.layer - Connected
D 2021-11-16 18:58:09,284 yowsup.axolotl.factory - get_manager(profile_name=346..., username=346...)
D 2021-11-16 18:58:09,286 yowsup.axolotl.manager - Initialized AxolotlManager [username=346..., db=/something/axolotl.db]
D 2021-11-16 18:58:09,286 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-11-16 18:58:09,321 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-11-16 18:58:09,321 yowsup.axolotl.manager - load_unsent_prekeys
I 2021-11-16 18:58:09,353 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2021-11-16 18:58:09,354 yowsup.layers.noise.layer - Received auth event
D 2021-11-16 18:58:09,354 yowsup.env.env - Env not set, setting it to android
D 2021-11-16 18:58:09,354 yowsup.env.env - Current env changed to android
D 2021-11-16 18:58:09,355 yowsup.layers.noise.layer - Performing handshake [username= 346..., passive=True]
D 2021-11-16 18:58:09,355 yowsup.layers.noise.layer - Starting handshake worker
D 2021-11-16 18:58:09,985 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2021-11-16 18:58:09,985 yowsup.layers.network.layer - Disconnected
D 2021-11-16 18:58:09,986 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
^C
Yowsdown
```

**Config file**

It's sometimes useful to post contents of your configuration file. If you do some, make sure to mask out your phone number, login, id, client_static_keypair, fdid, expid, otherwise you risk your account getting taken over.

Also please always post contents of your profile's config.json, and not just a different path you pass to yowsup-cli
(see [What is inside a profile's config.json?](https://github.com/tgalal/yowsup/wiki/FAQ#what-is-inside-a-profiles-configjson))

**Versions**

Included on the debug dump

**OS (please complete the following information):**
Raspbian (Raspberry Pi 4)

Thanks.

**Comment by ozymoz** [comment]
Hello there; Can I learn MD5 and version information?

**Comment by meshkin** [comment]
no any idea?
if some one fixed the problem, please explain it...

**Comment by DoHITB** [comment]
> Hello there; Can I learn MD5 and version information?
 ```
    _MD5_CLASSES = "FvBkNweJGf4WVuHWSU793g=="
    _VERSION = "2.21.15"
```

**Comment by ozymoz** [comment]
> no any idea?
> if some one fixed the problem, please explain it...

What is your ongoing problem? Is it about registering?

**Comment by meshkin** [comment]
> > no any idea?
> > if some one fixed the problem, please explain it...
> 
> What is your ongoing problem? Is it about registering?

i receiving bellow error when i registering number with received code:
`
Traceback (most recent call last):
File "/Users/ozymoz/register.py", line 34, in
config.edge_routing_info = base64.b64decode(result['edge_routing_info'])
File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 80, in b64decode
s = _bytes_from_decode_data(s)
File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 45, in _bytes_from_decode_data
raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
`

but status is ok.
then i wants to login and send message, but receiving this error:
`
File "/usr/local/lib/python3.7/site-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)`
then i change _VERSION to 3 octed => _VERSION=2.21.22 and try send message again, but issued bellow error:
`[offline]:/L
D 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-11-16 05:57:40,500 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443
D 2021-11-16 05:57:40,500 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e4.whatsapp.net', 443))
D 2021-11-16 05:57:40,735 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-11-16 05:57:40,735 yowsup.layers.network.layer - Connected
D 2021-11-16 05:57:40,735 yowsup.axolotl.factory - get_manager(profile_name=XXXXXXXXXXXX, username=XXXXXXXXXXXX)
D 2021-11-16 05:57:40,736 yowsup.axolotl.manager - Initialized AxolotlManager [username=XXXXXXXXXXXX, db=/root/.config/yowsup/XXXXXXXXXXXX/axolotl.db]
D 2021-11-16 05:57:40,737 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-11-16 05:57:40,739 yowsup.axolotl.manager - load_unsent_prekeys
I 2021-11-16 05:57:40,741 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Received auth event
D 2021-11-16 05:57:40,742 yowsup.env.env - Env not set, setting it to android
D 2021-11-16 05:57:40,742 yowsup.env.env - Current env changed to android 
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Performing handshake [username= XXXXXXXXXXXX, passive=True]
D 2021-11-16 05:57:40,742 yowsup.layers.noise.layer - Starting handshake worker
D 2021-11-16 05:57:41,219 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2021-11-16 05:57:41,220 yowsup.layers.network.layer - Disconnected
D 2021-11-16 05:57:41,237 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: 
[offline]:`
`

**Comment by joaoavilars** [comment]
same error here...

**Comment by Whatsapp-Protocol** [comment]
Your account may be disabled. Registering with yowsup can easily lead to it being disabled

**Comment by FoIsBo** [comment]
> > > no any idea?
> > > if some one fixed the problem, please explain it...
> > 
> > 
> > What is your ongoing problem? Is it about registering?
> 
> i receiving bellow error when i registering number with received code: `Traceback (most recent call last): File "/Users/ozymoz/register.py", line 34, in config.edge_routing_info = base64.b64decode(result['edge_routing_info']) File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 80, in b64decode s = _bytes_from_decode_data(s) File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 45, in _bytes_from_decode_data raise TypeError("argument should be a bytes-like object or ASCII " TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'`

I have the same error. Any solutions?

**Comment by meshkin** [comment]
> 

unfortunately, i'm not found any solutions.
if anyone solved this issue, please share it...

**Comment by meshkin** [comment]
> > > > no any idea?
> > > > if some one fixed the problem, please explain it...
> > > 
> > > 
> > > What is your ongoing problem? Is it about registering?
> > 
> > 
> > i receiving bellow error when i registering number with received code: `Traceback (most recent call last): File "/Users/ozymoz/register.py", line 34, in config.edge_routing_info = base64.b64decode(result['edge_routing_info']) File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 80, in b64decode s = _bytes_from_decode_data(s) File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py", line 45, in _bytes_from_decode_data raise TypeError("argument should be a bytes-like object or ASCII " TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'`
> 
> I have the same error. Any solutions?

unfortunately, i'm not found any solutions.
if anyone solved this issue, please share it...

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
