### ISSUE TITLE
Offline instead of Online

### ISSUE THREAD

**Issue by kylonrizoki** [tgalal/yowsup#3108]
I haven't edited Yowsup for the last 3 months. It has been working perfectly for the past 3 months. But some numbers tracked are not working since 14 December.

Most of the followers don't post their "online" status. It coming as Offline.  (Many numbers are working at the same time without any problems)

(ı am using more than 1 year, it is new problem. maybe about whatsapp beta version, protocol etc.)

**Comment by farheennextolive** [comment]
Was anyone able to resolve this issue?

**Comment by halper03** [comment]
i have same problem.

**Comment by Macarthurval** [comment]
Same problem here, it seems that the problem is with all numbers.

**Comment by ersinayaz** [comment]
It's no use looking for a solution. All your services will end in a short time anyway

**Comment by Macarthurval** [comment]
> It's no use looking for a solution. All your services will end in a short time anyway

Is it an intuition or do you have some interesting information to share?

**Comment by kylonrizoki** [comment]
Are there any solutions ?

**Comment by lauriolasw** [comment]
Same here! No 'online' status received from subscriptions, only 'offline'

I noticed that even though the yowsup client instance is set to online (/ presence available), it doesn't show as "online" in the official WA client (and nor as "last seen...")

Any idea?

**Comment by kylonrizoki** [comment]
I saıd to everyone 20 days ago.

**Comment by ORMiK0** [comment]
today whatsapp disabled lastseen information for contacts, which do not have your contact number

**Comment by ersinayaz** [comment]
> It's no use looking for a solution. All your services will end in a short time anyway
 

> Is it an intuition or do you have some interesting information to share?

more than intuition :)

**Comment by ersinayaz** [comment]
> > It's no use looking for a solution. All your services will end in a short time anyway
> 
> Is it an intuition or do you have some interesting information to share?

more than intuition :)

**Comment by Exoata** [comment]
> > > It's no use looking for a solution. All your services will end in a short time anyway
> > 
> > 
> > Is it an intuition or do you have some interesting information to share?
> 
> more than intuition :)

I have a solution but I need a good developer.
ata.mehmet16@gmail.com

**Comment by lauriolasw** [comment]
> > > > It's no use looking for a solution. All your services will end in a short time anyway
> > > 
> > > 
> > > Is it an intuition or do you have some interesting information to share?
> > 
> > 
> > more than intuition :)
> 
> I have a solution but I need a good developer. I can see online status without any contact [ata.mehmet16@gmail.com](mailto:ata.mehmet16@gmail.com)

Please share your knowledge, we will be happy to help you!

**Comment by ekucet** [comment]
> the end

is it really over?

**Comment by sorosons** [comment]
it is not about yowsup it is about whatsapp.

**Comment by emrecanozkok** [comment]
> > the end
> 
> is it really over?

whatsapp now working like what it should be. i tested all the situations. only work when you add number to your contacts you can see online notifications.its hard to believe but this is the reality.also we knew something like this would happen.

**Comment by ekucet** [comment]
have you found a solution?

**Comment by lovethiscode** [comment]
I have a way to know if it is online or offline.

**Comment by sorosons** [comment]
Dear Friends,

Due to the latest updates to the official whatsapp servers, all whatsapp
trackers in the world no longer work.

However, we have made our application working again. The app can detect a
change in the status of numbers you are tracking.

But sometimes the app gets confused about the type of status change.
Therefore, sometimes you may receive an OFFLINE message when the number is
indeed ONLINE. The opposite is also possible.

Our developers are working on it. We will fix all the problems and get the
app fully working again.

You will be satisfied with our service!

Thank you for your patience!

lovethiscode ***@***.***>, 11 Ara 2021 Cmt, 12:02 tarihinde
şunu yazdı:

**Comment by sorosons** [comment]
What is this way

**Comment by ekucet** [comment]
https://wabetainfo.com/whatsapp-is-enabling-new-privacy-measures-to-protect-users/

**Comment by ersinayaz** [comment]
whatsapp diyor ki: bu kadar ele düşen işe kalıcı çözüm getirdim boşuna ugrasmayın :) 
gönül rahatlıgıyla uygulamalarınızı yayından çekebilirsiniz. :)
türkçe yazıyorum çünkü bu işi yapanların ve bu konu baslıgını takip edenlerin %99'u türk :)

**Comment by sorosons** [comment]
:))

Ersin AYAZ ***@***.***>, 12 Ara 2021 Paz, 02:08 tarihinde
şunu yazdı:

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
