### ISSUE TITLE
Whatsapp update Broke App

### ISSUE THREAD

**Issue by sorosons** [tgalal/yowsup#3112]
Hello guys is there any ways to get online notıfıcatıon

**Comment by lauriolasw** [comment]
Discussion #3108

**Comment by ORMiK0** [comment]
today whatsapp disabled lastseen information for contacts, which do not have your contact number

**Comment by ekucet** [comment]
have you found a solution?

**Comment by tgalal** [comment]
For consultancy related to specific use-cases please refer to the [README](https://github.com/tgalal/yowsup).
