### ISSUE TITLE
Presence (online/offline status) not working - 2022!

### ISSUE THREAD

**Issue by ersinayaz** [tgalal/yowsup#3119]
**The expected day has come!** 
WhatsApp has now stopped providing presence information.
I guess the only solution is to communicate between wa users.
My advice is to stay away from those who offer support for money. because there is no solution to this problem anymore.

**Comment by ozymoz** [comment]
Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?

**Comment by zek** [comment]
It stopped regionially. Soon it'll stop for numbers in all countries.

**Comment by ersinayaz** [comment]
> Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?

şimdilik çalışıyor sistemleriniz diyelim. hatta farkında olmadığınız ama çalışmayan numaralarınızın olduğuna eminim.
Bu çalışmayan numaralarınız bir kaç gün içinde çoğalacak.
Sorunuza cevap verecek olursam, evet artık offline bilgiside gelmiyor.

**Comment by ersinayaz** [comment]
> It stopped regionially. Soon it'll stop for numbers in all countries. Can you contact with me via discord?
> 
> zek#7943

It would be healthier to continue under this topic.
will be more beneficial for yowsup community.

**Comment by ozymoz** [comment]
> > Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?
> 
> şimdilik çalışıyor sistemleriniz diyelim. hatta farkında olmadığınız ama çalışmayan numaralarınızın olduğuna eminim. Bu çalışmayan numaralarınız bir kaç gün içinde çoğalacak. Sorunuza cevap verecek olursam, evet artık offline bilgiside gelmiyor.

Evet bazı numaralardan gelmiyordu çok az bi kısım olduğundan önemsemedim. Sanırım bölgesel güncelleme geliyor. 2-3 haftaya tüm bölgelerde aktif olacaktır.

**Comment by sorosons** [comment]
Peki kimse kimseyle birşey bedava paylaşacakmı ??

**Comment by zek** [comment]
Parayla paylaşmayan bedava niye paylaşsın 😅 herkes sır küpü

**Comment by sorosons** [comment]
Yok yok Herkes Parayla satıyor :) Geçen sefer birisi dissappering mesajı 5k dolara satıyordu ya 👯

**Comment by sensuslankoylu** [comment]
> Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?

ya kardeşim heryerde yazıyorsun yok bende calısıyor ediyor. Bende de çalışıyor sorun o değil. kimisi 10bin kimisi 1 milyon kimisi 10 milyon herkes birşeyler kazanıyor. Elbette azçok herkes durumdan tedirgin. Geliyorsun topic altına bende çalışıyor yazıp duruyorsun. Eee kardeşim bizde de çalışıyor. Ama merak etme oda kapanacak yani. Adam bunu kapatıyor yavaş yavaş artık bu işin ömrü 3-5 ay bile değil.

**Comment by ozymoz** [comment]
> > Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?
> 
> ya kardeşim heryerde yazıyorsun yok bende calısıyor ediyor. Bende de çalışıyor sorun o değil. kimisi 10bin kimisi 1 milyon kimisi 10 milyon herkes birşeyler kazanıyor. Elbette azçok herkes durumdan tedirgin. Geliyorsun topic altına bende çalışıyor yazıp duruyorsun. Eee kardeşim bizde de çalışıyor. Ama merak etme oda kapanacak yani. Adam bunu kapatıyor yavaş yavaş artık bu işin ömrü 3-5 ay bile değil.

Bu yazdıklarını bilmiyormuyum yada farkindami değilmiyim sanıyorsun. Mal mal konuşup durmuşsun. İkinci yazdığımı oku,

**Comment by sensuslankoylu** [comment]
> > > Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?
> > 
> > 
> > ya kardeşim heryerde yazıyorsun yok bende calısıyor ediyor. Bende de çalışıyor sorun o değil. kimisi 10bin kimisi 1 milyon kimisi 10 milyon herkes birşeyler kazanıyor. Elbette azçok herkes durumdan tedirgin. Geliyorsun topic altına bende çalışıyor yazıp duruyorsun. Eee kardeşim bizde de çalışıyor. Ama merak etme oda kapanacak yani. Adam bunu kapatıyor yavaş yavaş artık bu işin ömrü 3-5 ay bile değil.
> 
> Bu yazdıklarını bilmiyormuyum yada farkindami değilmiyim sanıyorsun. Mal mal konuşup durmuşsun. İkinci yazdığımı oku,

afedersinde mal mal konuşan sensin her topic altında "ama bende çalışıyor" yazmaktan bıkmadın. varsa bir bilgin yaz yoksa edebiyat yapma. o malı sana yedirirler aslan parçası.

**Comment by sorosons** [comment]
Bu arada Bazı numaralr daha gitmeye başladı hemde hızlı şekilde gerçekten bir şey bilen varsa paylaşsın :)

**Comment by ozymoz** [comment]
> > > > Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?
> > > 
> > > 
> > > ya kardeşim heryerde yazıyorsun yok bende calısıyor ediyor. Bende de çalışıyor sorun o değil. kimisi 10bin kimisi 1 milyon kimisi 10 milyon herkes birşeyler kazanıyor. Elbette azçok herkes durumdan tedirgin. Geliyorsun topic altına bende çalışıyor yazıp duruyorsun. Eee kardeşim bizde de çalışıyor. Ama merak etme oda kapanacak yani. Adam bunu kapatıyor yavaş yavaş artık bu işin ömrü 3-5 ay bile değil.
> > 
> > 
> > Bu yazdıklarını bilmiyormuyum yada farkindami değilmiyim sanıyorsun. Mal mal konuşup durmuşsun. İkinci yazdığımı oku,
> 
> afedersinde mal mal konuşan sensin her topic altında "ama bende çalışıyor" yazmaktan bıkmadın. varsa bir bilgin yaz yoksa edebiyat yapma. o malı sana yedirirler aslan parçası.

Bekliyorum yedirmeni. Bilgi edinip ortaya cozum çıkarmaya çalışıyorum. Zaten 1-2 hafta sonra abi api satiyormusun diye yazacaksin bana. Diger arkadaşlar icin yazıyorum yowsup haricinde kısmen manuel kısmen oto başka bir cozum daha var. Otomasyonu bitirince genel olarak duyuracağım.

**Comment by lauriolasw** [comment]
> **The expected day has come!** WhatsApp has now stopped providing presence information. I guess the only solution is to communicate between wa users. My advice is to stay away from those who offer support for money. because there is no solution to this problem anymore.


Same problem here   :-(   no more presence updates
Are we really at the end?

**Comment by lauriolasw** [comment]
> Bekliyorum yedirmeni. Bilgi edinip ortaya cozum çıkarmaya çalışıyorum. Zaten 1-2 hafta sonra abi api satiyormusun diye yazacaksin bana. Diger arkadaşlar icin yazıyorum yowsup haricinde kısmen manuel kısmen oto başka bir cozum daha var. Otomasyonu bitirince genel olarak duyuracağım.

Thanks Ozymoz
We need to stay togheter!

**Comment by Macarthurval** [comment]
Yes... it seems it's over. It was beautiful while it lasted...

**Comment by sensuslankoylu** [comment]
> > > > > Benim sistemlerim hala çalışıyor. Hiç bir şekilde status alamıyor musunuz ?
> > > > 
> > > > 
> > > > ya kardeşim heryerde yazıyorsun yok bende calısıyor ediyor. Bende de çalışıyor sorun o değil. kimisi 10bin kimisi 1 milyon kimisi 10 milyon herkes birşeyler kazanıyor. Elbette azçok herkes durumdan tedirgin. Geliyorsun topic altına bende çalışıyor yazıp duruyorsun. Eee kardeşim bizde de çalışıyor. Ama merak etme oda kapanacak yani. Adam bunu kapatıyor yavaş yavaş artık bu işin ömrü 3-5 ay bile değil.
> > > 
> > > 
> > > Bu yazdıklarını bilmiyormuyum yada farkindami değilmiyim sanıyorsun. Mal mal konuşup durmuşsun. İkinci yazdığımı oku,
> > 
> > 
> > afedersinde mal mal konuşan sensin her topic altında "ama bende çalışıyor" yazmaktan bıkmadın. varsa bir bilgin yaz yoksa edebiyat yapma. o malı sana yedirirler aslan parçası.
> 
> Bekliyorum yedirmeni. Bilgi edinip ortaya cozum çıkarmaya çalışıyorum. Zaten 1-2 hafta sonra abi api satiyormusun diye yazacaksin bana. Diger arkadaşlar icin yazıyorum yowsup haricinde kısmen manuel kısmen oto başka bir cozum daha var. Otomasyonu bitirince genel olarak duyuracağım.

Güzel kardeşim bizde zaten çalışıyor. zaten bununda bir yolu var. Otomasyona vs de gerek yok.

**Comment by zek** [comment]
Bir çok uygulama, kullanıcılara sorun var diye mesaj atıyor. 
Görüştüğüm bir kaç kişi numara banlanması sorunu yaşadığından bahsediyor. 
Bizde çalışıyor yazan arkadaşlar da muhtemelen sorun yaşadığının farkında değiller. 
Birileri bir şekilde bu işi devam ettiriyor hala ama yakında tamamen bitecek.
Yowsup tespit oluyor her türlü

**Comment by sensuslankoylu** [comment]
> 

bu arada bizde çalışıyor dediğim sorun yaşamadığımız anlamını taşımıyor. eskisinden daha kolay ban atıyor.

**Comment by bluej4ker** [comment]
Mesaj göndermedeki sınırları nasıl ayarlıyorsunuz? Wp mesaj gönderme limitlerini bir türlü çözemedim çok dengesiz davranıyor.

**Comment by sensuslankoylu** [comment]
Artık biz çözümü olmadığı aşikar. whatsapp uzun süredir geliştirmeye başladığı bot engelleme sistemini tamamen devreye almış gözüküyor. Şuan hiçbir şekilde çalışmıyor. Evet yöntem var fakat eğer mesaj atmayı başarabilirseniz.dün ile bugun arasında bile deli gibi fark var hesap acmaya ve presence atmaya kızmıyor.Adam direk mesaj attırmıyor. ip,telefon,imei,hat hareket durumu herşeye bakıyor @ozymoz artık üretilecek bir çözüm yok. client tan bile uygulamayı acıp mesaj atsan adam banlıyor

**Comment by ozymoz** [comment]
> Artık biz çözümü olmadığı aşikar. whatsapp uzun süredir geliştirmeye başladığı bot engelleme sistemini tamamen devreye almış gözüküyor. Şuan hiçbir şekilde çalışmıyor. Evet yöntem var fakat eğer mesaj atmayı başarabilirseniz.dün ile bugun arasında bile deli gibi fark var hesap acmaya ve presence atmaya kızmıyor.Adam direk mesaj attırmıyor. ip,telefon,imei,hat hareket durumu herşeye bakıyor @ozymoz artık üretilecek bir çözüm yok. client tan bile uygulamayı acıp mesaj atsan adam banlıyor

Hacim cozum yowsup degilki. Yowsup yıllardır çalıştı diye kimse yedek ikinci sistem araştırmamış. Yowsupla fiziksel hatlar bile calismiyor. Baska calisan yöntemler var, storeda calisan uygulamalarda var suan. Tahmini 3-4 gün sonra işlemlerimi bitiririm. Yeni yöntemde numara aktif etme veya ban olaylarının testine girerim. O aşamada sorun cikcakmi suan bilmiyorum. 1-2 numara aktif edip 40-50 numara track ettim sorun yok. Limitleri öğrenmek zaman alacak.

**Comment by sensuslankoylu** [comment]
@ozymoz store da ben en az 30 app denedim calısan bulamadım gerçekten varsa bana iletirmisin yada buraya yazaiblirmisin hangileri calısıyor.Bu arada ben burayı çoğu kişi yowsup kullandığı için takip ediyorum bende farklı şeyler kullanıyorum. whatsapp üzerinde herhangi bir şekilde business olsun normal olsun webden açıp bile mesaj atsan direk ban atıyor adam.bu saat saat değişiyor gittikçe sıklaşıyor. ilk açılan hesaplar elbette calısıyor taaki mesaj atana kadar.ilk iletişimin karşıdan gelmesini bekliyor whatsapp

**Comment by ozymoz** [comment]
> @ozymoz store da ben en az 30 app denedim calısan bulamadım gerçekten varsa bana iletirmisin yada buraya yazaiblirmisin hangileri calısıyor.Bu arada ben burayı çoğu kişi yowsup kullandığı için takip ediyorum bende farklı şeyler kullanıyorum. whatsapp üzerinde herhangi bir şekilde business olsun normal olsun webden açıp bile mesaj atsan direk ban atıyor adam.bu saat saat değişiyor gittikçe sıklaşıyor. ilk açılan hesaplar elbette calısıyor taaki mesaj atana kadar.ilk iletişimin karşıdan gelmesini bekliyor whatsapp

Waradar çalışıyor ilk numaraları sisteme eklemeleri manuel sonrasında veriler doğru geliyor atlamada görmedim. Numaranın sisteme eklenmesi 20-30 dk numara değiştirmeye de 1 saat engel koyuyorlar. Otomasyonları yok görünüyor.

**Comment by bluej4ker** [comment]
12 farklı numaraya mesaj gönderdikten sonra whatsapp direk hesabı kapatıyor. İstediğiniz kadar hesabınızı ısıtın bir şey değişmiyor maleseft. Whatsapp limitlerini iyi öğrenmek gerekiyor bu sorunu çözmek için.

**Comment by kylonrizoki** [comment]
@ozymoz did you find any solution? please send me msg on discord : kylonrizoki#3255

**Comment by zek** [comment]
If anyone able to help me to trace raw whatsapp xml messages, I know a solution to track presence events.

**Comment by muratuygun** [comment]
#safetynet

**Comment by ReiDx** [comment]
Sistem gitti arkadaşlar seen çözdük demişte ben çözdüklerini düşünmüyorum.
Fawa uygulamasını test için satın aldım. Denedim sadece offline verisini alıyolar ilk offline giriş ikinci offline çıkış olarak tamamen yanlış veri üzerine kurulu bi sistemleri var.
Şu zamanda kimseden api felan almayın parayı çöpe atarsınız.
Rodwa'nın sahibi de 7 haneli rakama Rodwa'yı sattı zaten.
Bölgesel olarak yaşanan kesinti ileriki hafta tüm herkeste kesilecek. Yeşil tikli businness hesabınız olsa bile hiçbir kifayeti yok artık. Hiçbir şekilde alamıyorsunuz.
Sebebine gelince Avrupa Birliğinin Facebook üzerine kurduğu bir sıkı yönetim var.
Takip eden kitle bilir Mark Zuckerberg hizmetini Avrupa'da kesmek hakkında açıklama yaptı.
Yani istesenizde göremeyeceksiniz. Şu dönemde api alan arkadaşlar paranızı çöpe atın daha iyi.

**Comment by sensuslankoylu** [comment]
> Sistem gitti arkadaşlar seen çözdük demişte ben çözdüklerini düşünmüyorum. Fawa uygulamasını test için satın aldım. Denedim sadece offline verisini alıyolar ilk offline giriş ikinci offline çıkış olarak tamamen yanlış veri üzerine kurulu bi sistemleri var. Şu zamanda kimseden api felan almayın parayı çöpe atarsınız. Rodwa'nın sahibi de 7 haneli rakama Rodwa'yı sattı zaten. Bölgesel olarak yaşanan kesinti ileriki hafta tüm herkeste kesilecek. Yeşil tikli businness hesabınız olsa bile hiçbir kifayeti yok artık. Hiçbir şekilde alamıyorsunuz. Sebebine gelince Avrupa Birliğinin Facebook üzerine kurduğu bir sıkı yönetim var. Takip eden kitle bilir Mark Zuckerberg hizmetini Avrupa'da kesmek hakkında açıklama yaptı. Yani istesenizde göremeyeceksiniz. Şu dönemde api alan arkadaşlar paranızı çöpe atın daha iyi.

sen yanlış app e bakmışsın wa radar ı dene bi.

**Comment by ertanboler** [comment]
Merhaba herkese,
pek çözümü yok gibi bu işin. Herkes bir şeyler deniyor, ama eğer wa client applere arkadan farklı bir bilgi iletmiyorsa veya algoritmalarını banlanmadan kandıracak bir yöntem bulamadıysanız boşa çabalamamak lazım. O çalışıyor bu çalışmıyor gibi şeyler çok işe yarar doneler değil. Bu arada bu işin ilklerinden biriyim, whatscope/wscope un yapımcısıyım. Yıllarca yöntem üstüne yöntem deneyerek 4 yılı aşkın açık tuttuğumuz kendi API'larımızla yürüttük, sonra wa avukatları ile dogrudan temasla anlaşıp bıraktık. Yowsup ile bir süredir tekrar denemeler yaptık. Velhasılı opensource olan herşeyi yakalarlar gibi.

Bence asıl yoğunlaşmanız gereken iOS gibi davranmak. Ben bildiklerimi anlatayım; geliştiren ilerleyen bizimle paylaşsın.

-Sunucunuz/IP'niz ban yedi diye birşey yok, tüm ip'ler bir iOS cihaz veya connectionUpgrade ile değişmiyorsa tümü varsayılan suspected olarak nitelendirilir. Denemelerinizi yapacağınız sunucuya vpn kurup iOS cihazla bağlanın bir süre oyalanın, sonra pc/mac ile bağlanın ve iOS'in wa web ini açın. IP adresinizi trusted duruma alın.

-Yapabiliyosanız iOS jailbreak veya diğer yöntemlerle trafiği sniffleyin, mantığınızda hata varmı önce onu görün. Wa açık bırakmışsa iOS tarafında bırakmıştır.

-Takip edeceğiniz no'ya bir block atın, sonra unblock yapın ve deneyin.

-Eğer wa öğrenebilen bir ban/bloklama sistemi kullanıyorsa mağduru oynayın, sistemi yanıltın. Yani message storeunuza karşıdan gelen bir mesaj varmış gibi mesaj üretip ekleyin, veya engelleyip kaldırın, veya arama kaydı oluşturun, veya durum için seen gönderin gibi.

Bunları denedikten sonra hala çözüm göremiyorsanız önerim:
Zaten python/php/mysql ve react-native/flutter/swift/kotlin vb öğrenmişsinizdir bu süreçte; vakit kaybetmeden yeni ve 3. taraflardan bağımsız uygulamalar geliştirin. Saplantı haline getirmeyin. Yukarıda da belirttiğim gibi, işin ilklerindenim, gerçekten 3. taraflara bağımlı her türlü proje stresinizi artırır hayat kalitenizi düşürür; özgün olun... 
Bu süreçte kazancınızı iyi değerlendirdiyseniz yeni projelerinize sermaye yapın. Panik yapmayın.
En önemlisi de çalışmayan sistemlerle kullanıcılarınızı kandırmayın, doğruluktan sapmayın.

Eleştiren olur, hak veren olur, herbirine saygı duyarım. Ben 16 yıllık 30+ üzeri dilde çalışmış bir yazılımcı olarak, tersine mühendislikte ciddi emek ve gönül vermiş biri olarak diyeceğim ufkunuzu açık tutun. Yeni projeler üretin.

Saygı ve selamlarımla,

**Comment by reddington000** [comment]
@ertanboler çok bilgilendirici bir yazı olmuş teşekkürler. Bir sorum olacaktı, WA avukatları iletişime geçerek sizi neyle itham ettiler acaba ? Size para mı verdiler kaldırmanız için ? Yoksa Türkiye içinde bir dava süreci mi oluştu ?

**Comment by ertanboler** [comment]
> @ertanboler çok bilgilendirici bir yazı olmuş teşekkürler. Bir sorum olacaktı, WA avukatları iletişime geçerek sizi neyle itham ettiler acaba ? Size para mı verdiler kaldırmanız için ? Yoksa Türkiye içinde bir dava süreci mi oluştu ?

app ismi konusunda hak iddiasında bulundular, isim değiştik, storelara kaldırılması için baskı yaptılar, storelar da direnemedi, kaldırıldı. Biz de uğraşmadık.

Sorun hakkında gelişme gösteren arkadaşlar var mı?

**Comment by sensuslankoylu** [comment]
Yani her zaman dedim yine diyorum, her zaman daha iyisi mutlaka vardır. Nasıl çalıştığını burda ortalama herkes biliyor. Önceden online/offline alamazdık ama hesap açardık. Şimdi hesap açamıyoruz. Bir sürü kriter devreye giriyor. bu işi emülatör ile yapan var, el ile yapan var. Deli gibi paranın döndüğü yerde stresi bırakın başka birşeye geçin diyen arkadaş lütfen bu kadar organic kazanç sağlayacak başkabir kategori önersinde oraya geçelim. Yaşadığınız durumları bende defalarca yaşadım. Her app banlandığında yenisini attım. Telefonunuz db sinde mesajn oluşturmanız birisini engellemeniz hiçbirşey ifade etmeyecektir. Whatsapp tarafında yaptığınız tüm işlemler karşı tarafa mesaj formatında hashlenerek gönderildiğini için whatsapp bunun ne olduğunu bilemeyeceği için sizi en kötü durumla, mesaj atmakla itham edecektir. Hesap demleme vs olayları yalan. Tek gerçek şu : tertemiz bir telefon ve aynı networkteki bir sunucu.

**Comment by ertanboler** [comment]
@sensuslankoylu mesajımı iyi okuduysanız zaten nasıl ban yemeden register olacağınızı anlatmışım, devlet sırrı değil yani. Buradaki herkes az çok kendine göre uzman. Yazdıklarımı art niyetle okursanız, ön yargı ile okursanız zaten anlamanıza imkan yok.
Kategori soruyorsanız girersiniz marketlerin toplist'lerine bakarsınız, analiz yaparsınız, aradığınız kendine uygun kategoriyi bulursunuz. Şöyle bir göz gezdirseniz bile android için dating kategorisinin top grossing de ilk 100ün yarısından çoğu olduğunu görürsünüz. 
Android'den ne yaparsanız yapın pek ilerleme kaydedemezsiniz. iOS diye boşuna yazmamışım.
Network için zaten serverınıza kurduğunuz VPN lerle gerçek iOS cihaz bağlayın demişim.
Mesajınızda soruna katkı sağlayacak pek bir şey göremedim.
Başarılar diliyorum.

**Comment by bluej4ker** [comment]
Mesaj göndermek dışında somut bir yol bulabilen var mı? veya mesaj gönderme limitlerini anlayabilen? Hatlarda 15-20 mesajdan sonra hemen hattı banlıyor wa. Yeni bir telefon ve aynı networkte sunucu denemelerim tamamen başarısızlıkla sonuçlanıyor.

**Comment by sensuslankoylu** [comment]
@ertanboler Allah razı olsun reis herşeyi söylemişsin fakat burda 16 yıl tecrübe ve maalesef 30 dil iş yapmıyor. Yowsup ın daha master ı çalışmazken bir şekilde forkları bularak çalıştıran insanlar bu yaptıklarınızı emin olun denedi. Bu piyasayı elimine eden adamların yarısı zaten benim arkadaşım. Sadece presence updatelerini almak için sadece 6-7 yol var. Bu yorumlarım yowsuptan bağımsızdır ben yowsup kullanmayı geçen sene bıraktım. Herkesin ticari iş yaptığı yerde çözüm bulanlar elbette konuşmuyor. Bende çözüm bulamadım ama en azından yarı manuel bir şekilde işlerimizi sürdürüyoruz. Sorunun temel kaynağıda insanların tek hesaptan 40 numara takip etmeye çalışıyor oluşu.

edit: ayrıca bu işi ios ile çözmek bir çare değil.500 tane wp hesabına sahip olması gereken bir kişi 14 günde bir tekrar hesap açmak zorunda kalacak. Bunun en temiz yolu bu işi android de yapmak.

**Comment by resatkrlc** [comment]
@sensuslankoylu Bir sorum var, 6-7 yol derken neyi kastettiniz? Benim bildiğim sadece mesaj atmak var, başka yolu var mı acaba?

**Comment by ersinayaz** [comment]
notiseen geliştiricisi buralarda mı ?
**çalışmayan** app için 4 gündür günde 10 tane **spam** bildirim yollamakla kullanıcı tutulmaz.
Bu tarz davranışlar yüzünden AppStore/GPlay'den yaptırımlar alacağız senin yüzünden!

**Comment by ertanboler** [comment]
@sensuslankoylu  kişisel yazmaktan kaçınmanı öneririm. Kişisel bir durum yok burada. Senin piyasayı domine eden arkadaşlarına beni sorarsın. Kişiselleştirirsen sen zararlı çıkarsın. Çok heyecanlısın, kendi paranı kazanmanın verdiği hissi tatmışsın ve korkuların yükselmiş. Dikkat et sözlerine. Kişisel yazmaya devam etmemeni öneririm. Bu arada 17 yılı devirmişim.
Yowsup konusuna yazıp da polemik yapacaksan uğraşma, arkadaşlarına sor numaramı versinler buyur gel çayımı iç.
Her neyse...

@ersinayaz Çalışan uygulama arayan kullanıcıları kendilerine çekerek çalışmayan sistemle para kazanma derdinde olanlar çok maalesef. Refundlar artınca ios da play de temizliğe başlar.

Ek bilgi olarak Twilio insanlara zaten sahipli olan numaralar satıyor bilginiz olsun. Bendeki aktif numaralara en az 1-2 register smsleri geliyor. Twilio'a da dikkat etsin herkes, diğer servisleri kullanmanızı öneririm.

**Comment by reddington000** [comment]
Herkes çok gergin.
@ersinayaz, noti seen @ozymoz 'un.

**Comment by ersinayaz** [comment]
Çalışmayan sistem için scam davranışlar bu işi yapan/yapmış olan/yapmaya devam edecek olan herkesi 1. derecede etkiler.
Bu tür davranışlar sonucu AppStore'a giden refund ve şikayetler sonrasında inceleme gelip tüm herkesin zararına sonuçlar oluşacaktır.

Çözebilen yoluna baksın, çözemeyene kolaylıklar gelsin.

**Comment by ekucet** [comment]
> Çalışmayan sistem için scam davranışlar bu işi yapan/yapmış olan/yapmaya devam edecek olan herkesi 1. derecede etkiler. Bu tür davranışlar sonucu AppStore'a giden refund ve şikayetler sonrasında inceleme gelip tüm herkesin zararına sonuçlar oluşacaktır.
> 
> Çözebilen yoluna baksın, çözemeyene kolaylıklar gelsin.

Çözen var mı acaba? Yani bu işin bir çözümü mevcut mu? 3-5 aydır buralardayım. Bu arada dediklerinize harfiyen katılıyorum. Hit&Run yapmaya çalışan çok var.

**Comment by ersinayaz** [comment]
yowsup devri bittiği için konuyu kapatıyorum arkadaşlar.

Dileyen olursa bir wa grubu kurdum. Tanışıp, yowsup harici fikir alışverişi yapmak isteyenler katılabilir.
https://chat.whatsapp.com/Fee5ul2Fr1M95buyAtFXbE

**Comment by reddington000** [comment]
Ben de 2 yıldır bu sektördeyim, naçizane fikrim çalışan arkadaşların da numaraları yakında çalışmamaya başlayacak. Benim de şuan çalışan numaralarım var. WABetaInfo geçen gün yine bi anket yaptı, kimler online mevzusunun kapanmasını istiyor diye. Çok ciddi bir kitle var bu konuda. WA yöneticileri doğrudan bu twitter hesabını takip ediyorlar. Bence WA yakın bir süreçte artık Contactlara da bunu göstermeyecek.

**Comment by Macarthurval** [comment]
I'm petty sure most of us here would greatly appreciate it if you would use the English language to share your thoughts. Surely it will be easier for everyone to collaborate. I don't mean to bother, I just hope you understand, thank you.

Eminim buradaki çoğumuz düşüncelerinizi paylaşmak için İngilizce kullanırsanız çok memnun oluruz. Elbette herkesin işbirliği yapması daha kolay olacaktır. Rahatsız etmek istemem, umarım anlamışsınızdır, teşekkür ederim.

**Comment by ayotawaska** [comment]
if anybody need presence api, contact : ayotawaska@gmail.com

**Comment by mehmeteyuce** [comment]
You can see the communication status without sending a message to the number. If you are interested in the method : mehmetyuce3382@gmail.com

**Comment by mehmeteyuce** [comment]
It is possible to find out the presence status of anyone.
mehmetyuce3382@gmail.com

**Comment by MYuceOps** [comment]
There is a way to get the presence feature without sending a message. 
TG: @Mehmet33Yuce

**Comment by yucelermehmet33** [comment]
It is possible to find out the presence status of anyone.
Mail: mehmetyuce3382[at]gmail.com
Telgram: Mehmet33Yuce
