### ISSUE TITLE
bad_param backup_token

### ISSUE THREAD

**Issue by Joshuwatomy** [tgalal/yowsup#3158]
getting error bad param backup_token

W 2022-07-29 12:12:34,232 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2022-07-29 12:12:35,175 yowsup.common.http.warequest - b'{"login":"917xxxxxx81","param":"backup_token","reason":"bad_param","status":"fail"}\n'
status: b'fail'
reason: b'bad_param'
param: b'backup_token'
login: b'9175xxxxxx81'

**Comment by hirschbach** [comment]
Hi Joshuwatomy,

please, can you tell me the solution for the "backup_token" problem?

Thanks
