### ISSUE TITLE
no_routes error

### ISSUE THREAD

**Issue by Joshuwatomy** [tgalal/yowsup#3159]
getting this error 

W 2022-07-29 14:07:02,755 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2022-07-29 14:07:03,294 yowsup.common.http.warequest - b'{"flash_type":0,"login":"91xxxxxxxx72","reason":"no_routes","retry_after":3600,"sms_wait":0,"status":"fail","voice_wait":0}\n'
status: b'fail'
reason: b'no_routes'
retry_after: 3600
login: b'91xxxxxxxx72'
sms_wait: 0
voice_wait: 0

**Comment by s3b4st14nm** [comment]
I had the same problem here... but... **what was the solution for this?**

Thanks in advance!

___ output:
`I 2023-09-04 14:59:48,445 yowsup.common.http.warequest - b'{"email_otp_wait":0,"flash_type":0,"login":"1849XXXXXXX","reason":"no_routes","retry_after":3600,"sms_wait":0,"status":"fail","voice_wait":0,"wa_old_wait":0}\n'
status: b'fail'
reason: b'no_routes'
retry_after: 3600
login: b'1849XXXXXXX'
sms_wait: 0
voice_wait: 0`

**Comment by ScubaInstructor** [comment]
I had the same issue today with a brand new mobile number.

`I 2023-09-11 20:33:59,173 yowsup.common.http.warequest - b'{"email_otp_wait":0,"flash_type":0,"login":"41xxxx","reason":"no_routes","retry_after":3600,"sms_wait":0,"status":"fail","voice_wait":0,"wa_old_wait":0}\n'`

I registered that number once on a phone with the WhatsApp app (just to check it is working).

After that yowsup-cli registration worked fine for me.
