### ISSUE TITLE
yowsup died again?

### ISSUE THREAD

**Issue by Whomakes** [tgalal/yowsup#3185]
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.3
cryptography   v36.0.1
protobuf       v4.0.0rc2

==================
Type /help for available commands

D 2022-12-13 07:49:38,991 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-12-13 07:49:38,991 yowsup.layers.network.layer - Connecting to g.whatsapp.net:443
D 2022-12-13 07:49:38,991 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('g.whatsapp.net', 443))
D 2022-12-13 07:49:39,051 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-12-13 07:49:39,051 yowsup.layers.network.layer - Connected
D 2022-12-13 07:49:39,051 yowsup.axolotl.factory - get_manager(profile_name=/home/strix/Dropbox/whatsapp/configs/xxxxxxxxxx, username=xxxxxxxxxxxxxx)
FullPath:  /home/strix/Dropbox/whatsapp/configs/xxxxxxxxxxxx/axolotl.db 

D 2022-12-13 07:49:39,065 yowsup.axolotl.manager - Initialized AxolotlManager [username=xxxxxxxxxxxxxx, db=/home/strix/Dropbox/whatsapp/configs/xxxxxxxxxxxxxx/axolotl.db]
D 2022-12-13 07:49:39,065 yowsup.axolotl.manager - level_prekeys(force=False)
D 2022-12-13 07:49:39,065 yowsup.axolotl.manager - len(pending_prekeys) = 0
I 2022-12-13 07:49:39,066 yowsup.axolotl.manager - Generating 812 prekeys, current max_prekey_id=0
I 2022-12-13 07:49:39,195 yowsup.axolotl.manager - Storing 812 prekeys
D 2022-12-13 07:49:40,305 yowsup.axolotl.manager - load_unsent_prekeys
I 2022-12-13 07:49:40,323 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2022-12-13 07:49:40,323 yowsup.layers.noise.layer - Received auth event
D 2022-12-13 07:49:40,323 yowsup.env.env - Env not set, setting it to android
D 2022-12-13 07:49:40,323 yowsup.env.env - Current env changed to android 
D 2022-12-13 07:49:40,323 yowsup.layers.noise.layer - Performing handshake [username= xxxxxxxxxxx, passive=True]
D 2022-12-13 07:49:40,323 yowsup.layers.noise.layer - Starting handshake worker
D 2022-12-13 07:49:40,571 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-12-13 07:49:40,571 yowsup.layers.network.layer - Disconnected
D 2022-12-13 07:49:40,623 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = True
D 2022-12-13 07:49:40,623 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-12-13 07:49:40,623 yowsup.layers.network.layer - Connecting to g.whatsapp.net:443
D 2022-12-13 07:49:40,623 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('g.whatsapp.net', 443))
D 2022-12-13 07:49:40,679 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-12-13 07:49:40,680 yowsup.layers.network.layer - Connected
D 2022-12-13 07:49:40,680 yowsup.axolotl.manager - level_prekeys(force=False)
D 2022-12-13 07:49:40,681 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2022-12-13 07:49:40,681 yowsup.axolotl.manager - load_unsent_prekeys
I 2022-12-13 07:49:40,683 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2022-12-13 07:49:40,683 yowsup.layers.noise.layer - Received auth event
D 2022-12-13 07:49:40,683 yowsup.env.env - Env not set, setting it to android
D 2022-12-13 07:49:40,683 yowsup.env.env - Current env changed to android 
D 2022-12-13 07:49:40,683 yowsup.layers.noise.layer - Performing handshake [username= xxxxxxxxxxxxx, passive=True]
D 2022-12-13 07:49:40,683 yowsup.layers.noise.layer - Starting handshake worker
D 2022-12-13 07:49:41,572 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-12-13 07:49:41,572 yowsup.layers.network.layer - Disconnected
general: Disconnected: 
[offline]:
[offline]:D 2022-12-13 07:49:41,673 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

general: Disconnected: 
[offline]:

**Comment by houjianwen123** [comment]
same issues

**Comment by clarithromycine** [comment]
same issue

**Comment by dreascomputer** [comment]
same here

**Comment by calvaresefabio** [comment]
same issue

**Comment by calvaresefabio** [comment]
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v3.4.8
protobuf       v3.12.4


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2022-12-13 10:39:11,437 yowsup.stacks.yowstack - Initializing stack
D 2022-12-13 10:39:11,438 yowsup.stacks.yowstack - Constructed Network Layer
D 2022-12-13 10:39:11,438 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2022-12-13 10:39:11,439 yowsup.stacks.yowstack - Constructed Noise Layer
D 2022-12-13 10:39:11,439 yowsup.stacks.yowstack - Constructed Coder Layer
D 2022-12-13 10:39:11,439 yowsup.stacks.yowstack - Constructed Logger Layer
D 2022-12-13 10:39:11,439 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f42d05344c0>
D 2022-12-13 10:39:11,439 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f42d0e0a950>
D 2022-12-13 10:39:11,440 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2022-12-13 10:39:11,444 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2022-12-13 10:39:11,444 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=39xxxxxxxxx))
Yowsup Cli client
==================
Type /help for available commands

[offline]:


Any idea?

**Comment by nightcoder22** [comment]
Maybe DNS issue like earlier? Does anyone have new IP -> Hostname mapping?

**Comment by ORMiK0** [comment]
duplicate: issues #3178 and #3182
Now we can't send keys without authorization from whatsapp.

**Comment by houjianwen123** [comment]
> duplicate: issues #3178 and #3182 Now we can't send keys without authorization from whatsapp.

It seem not the same ,#3178 and #3182 is the sent key exception when ax db recreated or some other , but this time like the time appear on Oct that cause by socket sent message but receive no data return not error code . just no data ,then the program run to the disconnect step

**Comment by ORMiK0** [comment]
> It seem not the same 
You are wrong. 
Now I upload a whatsapp account from android device with auth_token and add node to send this auth_token. And this account can send prekeys and messages.

**Comment by Whomakes** [comment]
Any idea? @tgalal can you tell me the cost for which you could restore the project?

**Comment by dragontin1988** [comment]
> Any idea? @tgalal can you tell me the cost for which you could restore the project?

@Whomakes ,Could you add my TG @dragontin to discuss how to fix the issue?

**Comment by Rodrigosolari** [comment]
From what I could see, it was connecting to other servers, I had it running connected to chat.cdn.whatsapp.net, or g.whatsapp.net, but now I can't find anything, any help?

**Comment by bahtiarp** [comment]
https://github.com/tgalal/yowsup/issues/3038
Try version 5.2 on the noise layer.

**Comment by Whomakes** [comment]
> #3038 Try version 5.2 on the noise layer.

 if 'Handshake message does not contain server hello!' in entity.getReason():
TypeError: argument of type 'NoneType' is not iterable

**Comment by Whomakes** [comment]
> > #3038 Try version 5.2 on the noise layer.
> 
> if 'Handshake message does not contain server hello!' in entity.getReason(): TypeError: argument of type 'NoneType' is not iterable

5.0 working! @bahtiarp Thanks!!!

**Comment by sheyg1** [comment]
> 
> 5.0 working! @bahtiarp Thanks!!!

Can you please share what you did in order to get it to working state?
No luck here with any version

**Comment by rafaelnordavind** [comment]
> > 5.0 working! @bahtiarp Thanks!!!
> 
> Can you please share what you did in order to get it to working state? No luck here with any version

No luck here with 5.0. same error

D 2023-02-01 18:40:19,684 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2023-02-01 18:40:19,685 yowsup.layers.network.layer - Disconnected
D 2023-02-01 18:40:19,761 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
