### ISSUE TITLE
/L Disconnected WhatsApp 2.22.24.76

### ISSUE THREAD

**Issue by ChowSings** [tgalal/yowsup#3188]
```
_MD5_CLASSES = "fJdJ2pZOVbYYjN+D8g8mUQ=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

_VERSION = "2.22.24.76" # 2.20.206.24
_OS_NAME = "Android"
_OS_VERSION = "8.0.0"
_DEVICE_NAME = "star2lte"
_MANUFACTURER = "samsung"
_BUILD_VERSION = "star2ltexx-user 8.0.0 R16NW G965FXXU1ARCC release-keys"
_AXOLOTL = True
```

```
D 2022-12-21 15:07:57,175 yowsup-cli - starting cmd
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v38.0.4
protobuf       v4.0.0rc1
```

```
[offline]:/L
  D 2022-12-21 15:09:02,282 yowsup.layers.network.layer - Created asyncore dispatcher
  I 2022-12-21 15:09:02,282 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
  D 2022-12-21 15:09:02,282 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e13.whatsapp.net', 443))
  D 2022-12-21 15:09:02,296 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
  D 2022-12-21 15:09:02,296 yowsup.layers.network.layer - Connected
  D 2022-12-21 15:09:02,296 yowsup.axolotl.factory - get_manager(profile_name=91941****388, username=91941****388)
  D 2022-12-21 15:09:02,297 yowsup.axolotl.manager - Initialized AxolotlManager [username=91941****388, db=/root/.config/yowsup/919415264388/axolotl.db]
  D 2022-12-21 15:09:02,298 yowsup.axolotl.manager - level_prekeys(force=False)
  D 2022-12-21 15:09:02,298 yowsup.axolotl.manager - len(pending_prekeys) = 0
  I 2022-12-21 15:09:02,298 yowsup.axolotl.manager - Generating 812 prekeys, current max_prekey_id=0
  I 2022-12-21 15:09:02,530 yowsup.axolotl.manager - Storing 812 prekeys
  D 2022-12-21 15:09:05,362 yowsup.axolotl.manager - load_unsent_prekeys
  I 2022-12-21 15:09:05,366 yowsup.axolotl.manager - Loaded 812 unsent prekeys
  D 2022-12-21 15:09:05,366 yowsup.layers.noise.layer - Received auth event
  D 2022-12-21 15:09:05,366 yowsup.env.env - Env not set, setting it to android
  D 2022-12-21 15:09:05,366 yowsup.env.env - Current env changed to android
  D 2022-12-21 15:09:05,366 yowsup.layers.noise.layer - Performing handshake [username= 91941****388, passive=True]
  D 2022-12-21 15:09:05,367 yowsup.layers.noise.layer - Starting handshake worker
  D 2022-12-21 15:09:05,391 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
  D 2022-12-21 15:09:05,391 yowsup.layers.network.layer - Disconnected
  D 2022-12-21 15:09:05,405 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
  general: Disconnected:
```

**Comment by Rodrigosolari** [comment]
Change the endpoint to chat.cdn.WhatsApp.net y g.WhatsApp.net and try

**Comment by ChowSings** [comment]
> Change the endpoint to chat.cdn.WhatsApp.net y g.WhatsApp.net and try

Can you post the code and path?

Thanks！

**Comment by Rodrigosolari** [comment]
https://github.com/tgalal/yowsup/blob/master/yowsup/common/constants.py#L4-L19
c.whatsaap.net

**Comment by li894882182** [comment]
still return general: Disconnected , how to fix it?

**Comment by li894882182** [comment]
@Rodrigosolari  , can you help me please?

**Comment by ChowSings** [comment]
> c.whatsaap.net

```
[offline]:
D 2022-12-26 11:42:46,223 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-12-26 11:42:46,223 yowsup.layers.network.layer - Connecting to g.whatsapp.net:443
D 2022-12-26 11:42:46,223 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('g.whatsapp.net', 443))
D 2022-12-26 11:42:46,247 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-12-26 11:42:46,247 yowsup.layers.network.layer - Connected
D 2022-12-26 11:42:46,247 yowsup.axolotl.factory - get_manager(profile_name=919908539862, username=919908539862)
D 2022-12-26 11:42:46,248 yowsup.axolotl.manager - Initialized AxolotlManager [username=919908539862, db=/root/.config/yowsup/919908539862/axolotl.db]
D 2022-12-26 11:42:46,248 yowsup.axolotl.manager - level_prekeys(force=False)
D 2022-12-26 11:42:46,251 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2022-12-26 11:42:46,251 yowsup.axolotl.manager - load_unsent_prekeys
I 2022-12-26 11:42:46,255 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2022-12-26 11:42:46,255 yowsup.layers.noise.layer - Received auth event
D 2022-12-26 11:42:46,255 yowsup.env.env - Env not set, setting it to android
D 2022-12-26 11:42:46,255 yowsup.env.env - Current env changed to android
D 2022-12-26 11:42:46,255 yowsup.layers.noise.layer - Performing handshake [username= 919908539862, passive=True]
D 2022-12-26 11:42:46,255 yowsup.layers.noise.layer - Starting handshake worker
D 2022-12-26 11:42:46,350 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-12-26 11:42:46,350 yowsup.layers.network.layer - Disconnected
D 2022-12-26 11:42:46,411 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:
[offline]:
```

/yowsup/common/constants.py

```
class YowConstants:
    DOMAIN       = "s.whatsapp.net"
    ENDPOINTS     = (
        #("chat.cdn.whatsapp.net", 443),
        #("c.whatsaap.net", 443),
        ("g.whatsapp.net", 443),
        #("e1.whatsapp.net", 443),
        #("e2.whatsapp.net", 443),
        #("e3.whatsapp.net", 443),
        #("e4.whatsapp.net", 443),
        #("e5.whatsapp.net", 443),
        #("e6.whatsapp.net", 443),
        #("e7.whatsapp.net", 443),
        #("e8.whatsapp.net", 443),
        #("e9.whatsapp.net", 443),
        #("e10.whatsapp.net", 443),
        #("e11.whatsapp.net", 443),
        #("e12.whatsapp.net", 443),
        #("e13.whatsapp.net", 443),
        #("e14.whatsapp.net", 443),
        #("e15.whatsapp.net", 443),
        #("e16.whatsapp.net", 443),
        )

    WHATSAPP_SERVER = "s.whatsapp.net"
    WHATSAPP_GROUP_SERVER = "g.us"

    YOWSUP = "yowsup"

    PREVIEW_WIDTH = 64
    PREVIEW_HEIGHT = 64

```

**Comment by Whomakes** [comment]
Change noise layer to 5.0

**Comment by Whomakes** [comment]
def __init__(self):
        super(YowNoiseLayer, self).__init__()
        self._wa_noiseprotocol = WANoiseProtocol(
            5, 0, protocol_state_callbacks=self._on_protocol_state_changed
        )  # type: WANoiseProtocol

        self._handshake_worker = None
        self._stream = BlockingQueueSegmentedStream()  # type: BlockingQueueSegmentedStream
        self._read_buffer = bytearray()
        self._flush_lock = threading.Lock()
        self._incoming_segments_queue = Queue.Queue()
        self._profile = None
        self._rs = None

**Comment by Whomakes** [comment]
class YowConstants:
    DOMAIN       = "s.whatsapp.net"
    ENDPOINTS     = (
        ("chat.cdn.whatsapp.net", 443),
        ("g.whatsapp.net", 443),
        )

    WHATSAPP_SERVER = "s.whatsapp.net"

    YOWSUP = "yowsup"

    PREVIEW_WIDTH = 64
    PREVIEW_HEIGHT = 64

**Comment by li894882182** [comment]
@tgalal   i Change noise layer to 5.0 , but still return general: Disconnected

`

class YowNoiseLayer(YowLayer):
    DEFAULT_PUSHNAME = "yowsup"
    HEADER = b'WA\x04\x00'
    EDGE_HEADER = b'ED\x00\x01'
    EVENT_HANDSHAKE_FAILED = "org.whatsapp.yowsup.layer.noise.event.handshake_failed"

    def __init__(self):
        super(YowNoiseLayer, self).__init__()
        self._wa_noiseprotocol = WANoiseProtocol(
            5, 0, protocol_state_callbacks=self._on_protocol_state_changed
        )  # type: WANoiseProtocol

        self._handshake_worker = None
        self._stream = BlockingQueueSegmentedStream()  # type: BlockingQueueSegmentedStream
        self._read_buffer = bytearray()
        self._flush_lock = threading.Lock()
        self._incoming_segments_queue = Queue.Queue()
        self._profile = None
        self._rs = None`

**Comment by Whomakes** [comment]
Show u noise layer

**Comment by li894882182** [comment]
![image](https://user-images.githubusercontent.com/33271933/209560499-53409023-7788-4c05-ae9e-c371930d5330.png)

**Comment by li894882182** [comment]
noise layer to 5.0 at line 39 , but line 32 is still4.0 , and i changed it to 5.0 , then its return 
general: Disconnected: Authentication Failure

**Comment by Whomakes** [comment]
class YowNoiseLayer(YowLayer):
    DEFAULT_PUSHNAME = "yowsup"
    HEADER = b'WA\x05\x00'
    EDGE_HEADER = b'ED\x00\x01'
    EVENT_HANDSHAKE_FAILED = "org.whatsapp.yowsup.layer.noise.event.handshake_failed"

    def __init__(self):
        super(YowNoiseLayer, self).__init__()
        self._wa_noiseprotocol = WANoiseProtocol(
            5, 0, protocol_state_callbacks=self._on_protocol_state_changed
        )  # type: WANoiseProtocol

        self._handshake_worker = None
        self._stream = BlockingQueueSegmentedStream()  # type: BlockingQueueSegmentedStream
        self._read_buffer = bytearray()
        self._flush_lock = threading.Lock()
        self._incoming_segments_queue = Queue.Queue()
        self._profile = None
        self._rs = None

**Comment by Whomakes** [comment]
copy and past in u layer

**Comment by li894882182** [comment]
![image](https://user-images.githubusercontent.com/33271933/209561411-0d59c342-aecb-4400-8b3e-f3c0885f756f.png)


![image](https://user-images.githubusercontent.com/33271933/209561427-c90bf9ae-7d40-42aa-a043-46abe98d959d.png)

**Comment by Whomakes** [comment]
find it in the discussion.  this has been fixed too

**Comment by li894882182** [comment]
yes , thank you very much , proplem resolved 

https://github.com/bizzu/yowsup/commit/a02d85c5412c61306628544958728d06974b749b

**Comment by Rodrigosolari** [comment]
not connect!!!

**Comment by Rodrigosolari** [comment]
D 2022-12-26 23:45:11,962 yowsup.layers.noise.layer - Starting handshake worker
D 2022-12-26 23:45:13,980 yowsup.layers.logger.layer - rx:
<failure vt="15" reason="403" location="nao" />
D 2022-12-26 23:45:13,981 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2022-12-26 23:45:13,981 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-12-26 23:45:13,981 yowsup.layers.network.layer - Disconnected
D 2022-12-26 23:45:13,982 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by li894882182** [comment]
@Rodrigosolari   use those can fix it

first: https://github.com/tgalal/yowsup/issues/3188#issuecomment-1365232807

second :https://github.com/tgalal/yowsup/wiki/Sample-Application

**Comment by Rodrigosolari** [comment]
Not, my problem is other... error 403 account is banned...

**Comment by magnussolution** [comment]
hello, i made these adjustments, and working perfect per 12 hours, now i receive 

`general: Login Failed, reason: 402`

    _MD5_CLASSES = "fJdJ2pZOVbYYjN+D8g8mUQ=="
    _VERSION = "2.22.24.76"

**Comment by sjoerdj** [comment]
What worked for me:

1. Updating yowsup/layers/noise/layer.py as follows:

![image](https://user-images.githubusercontent.com/47718586/208474924-0839dbe4-823a-4c49-9590-d1024deea56f.png)

2. [Updating /yowsup/layers/coder/decoder.py and /yowsup/layers/coder/encoder.py](https://github.com/tgalal/yowsup/issues/3090#issuecomment-924989153) to deal with token 247.

3. Re-registering my phone number

**Comment by ChowSings** [comment]
@sjoerdj @Rodrigosolari @Whomakes Thanks
succeeded! , I modified these files, hope that helps someone

```
/yowsup/common/constants.py
/yowsup/layers/noise/layer.py
/yowsup/env/env_android.py
/yowsup/layers/coder/encoder.py
/yowsup/layers/coder/decoder.py
```

fixed [yowsup.zip](https://github.com/tgalal/yowsup/files/10319889/yowsup.zip)

**Comment by magnussolution** [comment]
> @sjoerdj @Rodrigosolari @Whomakes Thanks succeeded! , I modified these files, hope that helps someone
> 
> ```
> /yowsup/common/constants.py
> /yowsup/layers/noise/layer.py
> /yowsup/env/env_android.py
> /yowsup/layers/coder/encoder.py
> /yowsup/layers/coder/decoder.py
> ```
> 
> fixed [yowsup.zip](https://github.com/tgalal/yowsup/files/10319889/yowsup.zip)

work. thanks so much

**Comment by magnussolution** [comment]
worked per 24 hours and return error again

`general: Login Failed, reason: 402`
