### ISSUE TITLE
who can give me new version info

### ISSUE THREAD

**Issue by li894882182** [tgalal/yowsup#3209]
the lib return old_version last night .

whatsapp business version : 2.23.7.75(expired)

whatsapp update version last night.

who can give me new version,key,md5classes

i can pay you , thanks!

**Comment by bahtiarp** [comment]
@li894882182 
WhatsApp Version: 2.23.12.78
WhatsApp MD5 Classes: RJ1Jh/FuCM+48uDx6MJerg==
where to send my paypal account? 😎

**Comment by li894882182** [comment]
> 

please give me your USDT address

**Comment by bahtiarp** [comment]
> > 
> 
> please give me your USDT address

my BTC address: 1CyQTvyo3g7E7MhMCb2QyNqD3W8uK9qivb

🙏

**Comment by li894882182** [comment]
> > > 
> > 
> > 
> > please give me your USDT address
> 
> my BTC address: 1CyQTvyo3g7E7MhMCb2QyNqD3W8uK9qivb
> 
> 🙏

um...... do you have TRC address ?  i don`t have BTC , just TRC .

**Comment by li894882182** [comment]
> > > 
> > 
> > 
> > please give me your USDT address
> 
> my BTC address: 1CyQTvyo3g7E7MhMCb2QyNqD3W8uK9qivb
> 
> 🙏

and , can you help me to solved new version problem : code_checkpoint ? i can pay you . i`m using a golang program now . i think this problem is because whatsapp offical add a picture verify code before regist .

**Comment by evgenysh** [comment]
contact for token: https://t.me/evgenysh78
