### ISSUE TITLE
"code_checkpoint" on bussiness ,some one solved it?

### ISSUE THREAD

**Issue by hnduomi** [tgalal/yowsup#3210]
when request code response is 
{'login': '1xxxxx', 'reason': 'code_checkpoint', 'status': 'fail'}

version is 2.23.12.78 WA bussiness

**Comment by hnduomi** [comment]
business version from 2.23.7.75 to latest,
 every version, same response
android env

**Comment by li894882182** [comment]
i need solved that too . i think it`s because app add a picture verify code on regist .

**Comment by huoxing007** [comment]
yowsup has expired, many functions are not available, if you pay I can tell how to regist.

**Comment by li894882182** [comment]
> 

give me your telegram or whatsapp , i will contact you .

**Comment by li894882182** [comment]
> yowsup has expired, many functions are not available, if you pay I can tell how to regist.

i contact you on telegram already , we can discussion this thing.

**Comment by huoxing007** [comment]
please give me your whatsapp. i will contact you. @li894882182

**Comment by li894882182** [comment]
> please give me your whatsapp. i will contact you. @li894882182

959696203985

**Comment by redvisfii** [comment]
I can pay you , pls contact me aslo @huoxing007 , my whatsapp 17828545351

**Comment by Manjit2003** [comment]
Anyone who want to get such issues solved, WhatsApp me on +91 74477 66766

**Comment by clown542603** [comment]
https://t.me/saber7575 @Manjit2003 @huoxing007 ,I also want to solve this problem, please add me

**Comment by is99zsq** [comment]
solved.   it is the captcha step in new version.

contact me for details
https://t.me/a4096m

**Comment by RobLinux** [comment]
Just re-ask the code with "method" = "captcha". In the answer you'll get "image_blob" as PNG containing the code. enjoy

**Comment by RobLinux** [comment]
https://github.com/WhiskeySockets/Baileys/issues/364
