### ISSUE TITLE
I'm Paying for yowsup-cli registration

### ISSUE THREAD

**Issue by pedrochavezx** [tgalal/yowsup#3229]
I will pay the person who helps me to make only the yowsup-cli registration --requestcode module work, I don't care about everything else, I just need it to work 100% (yowsup-cli registration --requestcode) and I will pay. 
Reading and searching the internet I have managed to go from old_version to bad token.
If you are interested https://t.me/Chavezpedro65

**Comment by siddharthdeo99** [comment]
I have fixed it.
<img width="1394" alt="Screenshot 2023-08-19 at 3 30 20 PM" src="https://github.com/tgalal/yowsup/assets/41829093/77006769-a243-407d-999e-fc1d41b7b0b1">

![WhatsApp Image 2023-08-19 at 3 33 51 PM](https://github.com/tgalal/yowsup/assets/41829093/668898b1-5e20-4fe8-a3f9-8894f4cd6591)

**Comment by pedrochavezx** [comment]
thank you siddharthdeo99 for helping to solve my problem, very responsive I recommend you.

**Comment by franktscholes864** [comment]
@siddharthdeo99 Can you give me your Tg? I am willing to pay for consultation or purchase.

**Comment by siddharthdeo99** [comment]
> @siddharthdeo99 Can you give me your Tg? I am willing to pay for consultation or purchase.

You can find me here, https://t.me/killerzzz_sid
