### ISSUE TITLE
Is this library working ??

### ISSUE THREAD

**Issue by ibrahemesam** [tgalal/yowsup#3251]
I wanna know if this library is still working. ie: not broken due to a WhatsApp backend update.
<hr>
I am writing an app that has a required feature to send text msg in WhatsApp to the customer.<br>
I tried selenium but it requires that a web browser instance to be running. that is too much RAM. my app can't app afford that.<br>
So, is this library still working ? can I depend on it ??

**Comment by Tatitooo** [comment]
hello, you can use https://github.com/wppconnect-team/wppconnect-server (i'm not a contributor in this project)

**Comment by raphaelvserafim** [comment]
https://api-wa.me

**Comment by ibrahemesam** [comment]
> hello, you can use https://github.com/wppconnect-team/wppconnect-server (i'm not a contributor in this project)

Wppconnect Server automates a chrome web-browser instance. which uses too much RAM. I wanna something lite. something that communicates directly through WhatsApp's WebSocket Server

**Comment by borisjota** [comment]
Hello, did you find any library that works for you? I have the same problem.

**Comment by ibrahemesam** [comment]
Nothing yet. If you find one, please let me know

**Comment by JenteJan** [comment]
@ibrahemesam, have you checked out whatsmeow? It's written in golang but might be what you're looking for. anyways Im also still looking into ways to connect whatsapp

**Comment by ibrahemesam** [comment]
@JenteJan, yes & thank you 3><br> [it's difinitely what I'm looking for](https://www.phind.com/agent?cache=cls6lzrp10003jh071exjj8hx). When I continue working on my project, I'm gonna test it. and if it works, I'm gonna compile it as a shared library and use it directly in my python project.

**Comment by danchikon1011** [comment]
@ibrahemesam, can you show code how do you use whatsmeow in your python code?

**Comment by cshintov** [comment]
Doesn't this violate Whatsapp's [TOS](https://www.whatsapp.com/legal/terms-of-service#terms-of-service-third-party-services)? 

```
Based on WhatsApp’s Terms of Service (ToS) that you’ve provided, using Yowsup2 (or similar third-party tools) to send WhatsApp messages would likely violate their ToS. Here’s a breakdown of the specific clauses that are relevant:
1. Clause on Unauthorized Use:

    WhatsApp restricts the use of unauthorized software, APIs, or automation:

        "(f) involve any non-personal use of our Services unless otherwise authorized by us."

    Using Yowsup2 or any unofficial client is unauthorized since it interacts with WhatsApp’s services without permission.

2. Harm to WhatsApp’s Services:

    WhatsApp explicitly states you cannot create software that functions similarly to WhatsApp:

        "(i) create software or APIs that function substantially the same as our Services and offer them for use by third parties in an unauthorized manner."

    Since Yowsup attempts to reverse-engineer the WhatsApp protocol, it falls under this clause.

3. No Bulk or Automated Messaging:

    WhatsApp prohibits auto-messaging:

        "(e) involve sending illegal or impermissible communications such as bulk messaging, auto-messaging, auto-dialing, and the like."

    Yowsup can automate message sending, which violates WhatsApp’s terms.

4. Reverse Engineering and Unauthorized Access:

    WhatsApp prohibits reverse engineering and unauthorized access:

        "(a) reverse engineer, alter, modify, create derivative works from, decompile, or extract code from our Services;"

    Tools like Yowsup rely on reverse-engineering WhatsApp’s protocols, which is explicitly prohibited.

Consequences:

    If you use Yowsup2 or similar tools:
        Account Suspension or Ban: WhatsApp actively bans accounts that use unauthorized tools.
        Legal Consequences: In extreme cases, WhatsApp may pursue legal action, especially if the use violates privacy laws or involves unauthorized data collection.
        Service Disruption: WhatsApp regularly updates its protocols to block unauthorized clients like Yowsup.
        ```

**Comment by ibrahemesam** [comment]
@danchikon1011 ,
no, it's has many propertory code. I don't wanna clean all that just to reply to you.
Anyway, use [Neonize](https://github.com/krypton-byte/neonize). it's a python bindings for [whatsmeow](https://godocs.io/go.mau.fi/whatsmeow)

**Comment by ibrahemesam** [comment]
@cshintov who cares ?
I am not a big company. my app will be sold only in Egypt which is too naive and primitive to care for softwate licensing or TOS
