### ISSUE TITLE
iPhone to Android Whatsapp

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#331]
I apologise for posting in this section of the forum but I really need some help.

I am away from my home country right now so therefore, I am unable to do text message verification. I am also a new user of Android coming from an iPhone 4.

What I want to do is transfer my WhatsApp account from the iPhone 4 to my Oneplus One KitKat.

I have extracted the pw.dat and my Cache file from iOS which according to 
https://github.com/venomous0x/WhatsAPI/issues/871

Contains the necessary information I need to complete the port. The next part I'm unsure about is how I can place this information into my Android. I've searched online and there appears to be ways to extract the password from Android (https://github.com/tgalal/yowsup/issues/234), however, there appears to be no way of inserting it.

Any ideas?
##

**Comment by 3dluis** [comment]
This is soluction https://developers.facebook.com/docs/whatsapp.

**Comment by zaidalikhan9** [comment]
Today we will help you out in transferring WhatsApp from iPhone to Android. Just follow the below steps carefully.

**Solution 1: Misleading Solutions that don’t work:** In the start, users can iPhone to Android WhatsApp transfer through iCloud. Then move WhatsApp from iPhone to Android through iTunes and at the end Transfer WhatsApp from iPhone to Android by Google Drive easily. This one isn't users friendly, but you can try if you are interested.

**Solution 2: Transfer WhatsApp with iSkysoft Toolbox**: In the beginning users can download iSkysoft Toolbox and connect their phones to their PC, tap “WhatsApp” and click on the option of “Transfer WhatsApp Message”.At the end you can pick the devices and press on the option of "Transfer" to exit. 
Click [Guide to WhatsApp Transfer](https://toolbox.iskysoft.com/topic/whatsapp-transfer.html) to explore much more iphone to iPhone, Android to Android Whatsapp Transfer data. Good luck.
