### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by WhyNotHugo** [tgalal/yowsup#336]
Account deletion does not seem to be possible, either with the cli app, or the library itself.

This is a really big annoyance for me: I tried out the yowsup app on pidgin, and now all my contacts see me on whatsapp, assuming they can message me over it.
I'm assuming this is also important to anybody who's changing numbers, since they'll want their contacts/etc deleted from their account before they give it up.

**Comment by ngenglala** [comment]
guys, can you give me the command line how to unregister your number from yowsup???
or how to delete it, cause i enter the wrong number... 
i using ubuntu 14.04 lts i386
