### ISSUE TITLE
Cannot send images

### ISSUE THREAD

**Issue by 2opremio** [tgalal/yowsup#35]
I m trying to mimic this example from WhatsAPI:

https://github.com/venomous0x/WhatsAPI/issues/51

By making the following call in CmdClient.py:

``` python
self.methodsInterface.call("message_imageSend",(self.jid,"http://www.anony.ws/i/2012/10/15/JKetE.jpg","JKetE.jpg",270038,open("/Users/fons/thumb.jpgb64",'r').read()))
```

which worked nicely under whatsapi the last time I tried. However, I get the following error:

<pre>
<code>
ignored toString call, probably encountered byte
ignored toString call, probably encountered byte
Unhandled exception in thread started by <bound method WhatsappCmdClient.onAuthSuccess of <Examples.CmdClient.WhatsappCmdClient instance at 0x1020cab90>>
</code>
</pre>

Any tips on how to make it work? (sending textual messages works without problems)

Thanks in advance

**Comment by morfeokmg** [comment]
@ericmarcos, could you please share me the details of your correction?, I have the same problem with legacy. 

BR
