### ISSUE TITLE
no_routes

### ISSUE THREAD

**Issue by capsload** [tgalal/yowsup#370]
I recently get No_Routes as fail message. 

Any clue?

**Comment by d0x** [comment]
@dezember yes, i could do the registration by hand and then continue using yowsup

1. Install whatsapp on a phone or emulator (i used the android sdk emulator)
2. get the password files with `adb pull`
3. follow the dectryption part on this tutorial: http://www.digitalinternals.com/security/extract-whatsapp-password-android/374/
4. use the password you get at the end to use the yowsup-cli like: 
`./yowsup-cli  demos -l 491577xxxxxxx:cHzM7D2+9xxxxxxxx -s 49176xxxxxx "Hallo Welt"`

**Comment by dezember** [comment]
@d0x I gave another try with android emulator. Still no success. It gives me authentication failure.

This only happens when I register the new number on the emulator. But the authentication is successful when I use my pw and me files present on my device using WhatsApp. I am interested in using another number for WhatsApp with Yowsup.

**Comment by rahulchipad06** [comment]
Getting same error for all numbers:
yowsup-cli registration -m 404 -n 20 -p 9198******* -C 91 -r voice
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by dbosanzio** [comment]
I tryed now with a new phone number never register:
root@luigi-ubuntu:~/LAB/y3/yowsup# /usr/local/bin/yowsup-cli registration -m 222 -n 01 -p xxxxxxxxxx  -C 39 -r sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

I did this from an ubuntu desktop 14.04.1 updated in a virtualbox with nat network. Internet works correctly.

**Comment by edgars** [comment]
Hi guys, same issue here with numbers from Brazil

**Comment by pinpuk** [comment]
@d0x  : What is the known key ? is that the hexdump of pw_salt ?

Decrypt WhatsApp Password

Decryption is done in 2 steps. First, we need to use the PBKDF2 key derivation function. This function needs a pass phrase that is derived from a known key and the WhatsApp username. First, create the pass phrase file “pbkdf2_pass.bin” with the known key using xxd – a tool to create a binary file from a hex dump.

**Comment by d0x** [comment]
@pinpuk He wrote the `known key` there:

`echo c2991ec29b1d0cc2b8c3b7556458c298c29203c28b45c2973e78c386c395 | xxd -r -p > pbkdf2_pass.bin`

It is the same for everyone

**Comment by kuldippatel** [comment]
Pardon my ignorance. Does this solve the problem of no_route? Can you please elaborate how to use it in Legacy code?

**Comment by pinpuk** [comment]
@kuldippatel I will try what @d0x suggested : follow this tutorial: http://www.digitalinternals.com/security/extract-whatsapp-password-android/374/  - so i hope it solves the problem about no_route. I hope the developers solve it :)

**Comment by dbosanzio** [comment]
The Saga Problem "no_route" reamin & continue:

root@luigi-ubuntu:~# /usr/local/bin/yowsup-cli registration -m 222 -n 01 -p 39xxxxxxxxxx  -C 39 -r sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes
root@luigi-ubuntu:~# 

The same error  from WAT "WhatsApp Registration Tool" https://github.com/shirioko/WART

I think there are big problem for Italy phone number registration for new number  because something at whatsapp algo/procedure changed.
![cattura](https://cloud.githubusercontent.com/assets/5989857/5603628/15f8113c-938f-11e4-8def-69993d3bf815.JPG)

**Comment by dezember** [comment]
I am unsure if the MD5 keys are actually working now. Whatsapp must have changed the registration method.

**Comment by dezember** [comment]
It seems less like a geographical registration problem.i have tried registration from several countries but its in vain.

**Comment by tgalal** [comment]
#1279940 should hopefully fix it, reopen the issue if it doesn't

**Comment by micha137** [comment]
I can confirm that it works, i received a registration code (after solving https://github.com/tgalal/yowsup/issues/500)

**Comment by technocode** [comment]
Yes its 100% works...

**Comment by dezember** [comment]
Perfect. Working! Thank you @tgalal

**Comment by rahulchipad06** [comment]
i have downloaded latest code.
 
Not working with numbers from india.
sudo yowsup-cli registration -m 404 -n 20 -p 91******** -C 91 -r sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

i have tried for already registered number but not working.
sudo yowsup-cli registration -m 404 -n 20 -p 91******** -C 91 -e
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}

status: fail
sms_length: 6
reason: incorrect
voice_length: 6

**Comment by rahulchipad06** [comment]
it is fixed for new numbers.what about alreadly register numbers.previously it was working

yowsup-cli registration -m 404 -n 20 -p 91******** -C 91 -e
usage: registration [-h] [-v] [-d] [--help-config] [-c CONFIG] [-m MCC]
                    [-n MNC] [-p PHONE] [-C CC] [-r (sms|voice) | -R code]
registration: error: unrecognized arguments: -e

**Comment by assegaf** [comment]
its working, but its use user agent: Nokia S40 client, its possible to use different method/register for Android Client (Newest ) ?

**Comment by tgalal** [comment]
@assegaf why?

**Comment by tgalal** [comment]
@rahulchipad06 you cannot check exists explicitly using -e argument now, do a '-r sms' instead and it will automatically do the exists request for you before attempting to request sms code.

**Comment by assegaf** [comment]
@tgalal oh no need, but it seem register using User Agent S40 and login using other user agent like Android 2.11.x seem working, 

maybe kinda weird, we register using S40 but use messaging E2E encryption axolotl (currently for android only), which currently Whatsapp Official S40 don't support yet.

**Comment by tgalal** [comment]
I agree probably it's not the best way, but it works, and e2e ecryption works, so for now it's ok I guess.

**Comment by horaceho** [comment]
```
$ python yowsup-cli registration -v
yowsup-cli v2.0.9
Using yowsup v2.2.15
```
```
$ python yowsup-cli registration -d -p 8526X9X4X1X -C 852 -m 454 -n 04 -r sms
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=852&in=8526X9X4X1X&lc=GB&lg=en&mcc=000&mnc=000&sim_mcc=454&sim_mnc=004&method=sms&network_radio_type=1&reason=self-send-jailbroken&token=3cd0f6a8eb104e6b0216630b2dddb5c5&id=%BCN%EB%AF%9C%3C%A5%9E%09s%2B%CA%A1%CD%91O%C3%E8U%1D
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=852&in=6X9X4X1X&lc=GB&lg=en&mcc=000&mnc=000&sim_mcc=454&sim_mnc=004&method=sms&network_radio_type=1&reason=self-send-jailbroken&token=3cd0f6a8eb104e6b0216630b2dddb5c5&id=%BCN%EB%AF%9C%3C%A5%9E%09s%2B%CA%A1%CD%91O%C3%E8U%1D
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes
```

```no_routes``` for a Hong Kong number.

**Comment by catch2patch** [comment]
Same here, russian numbers:

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=7&in=968xxxxxxx&lc=GB&lg=en&mcc=000&mnc=000&sim_mcc=250&sim_mnc=028&method=sms&network_radio_type=1&reason=self-send-jailbroken&token=5ca7d64bb2f1b0a4411208af6c66d591&id=M%D1%2B%5E%C0%5DH%9F%F3%FC%F1%F7b%3F9%0B%C1%DB%21%0B
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=7&in=968xxxxxxx&lc=GB&lg=en&mcc=000&mnc=000&sim_mcc=250&sim_mnc=028&method=sms&network_radio_type=1&reason=self-send-jailbroken&token=5ca7d64bb2f1b0a4411208af6c66d591&id=M%D1%2B%5E%C0%5DH%9F%F3%FC%F1%F7b%3F9%0B%C1%DB%21%0B
INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"no_routes","retry_after":3600}\n'
status: b'fail'
retry_after: 3600
reason: b'no_routes'

It was working a week ago. Maybe they updated something like hashes or token generation way?

**Comment by ashwinrath** [comment]
I think the best way to get the password is to use WART . It sends a password or a 6 digit code . It also automatically detects if the code needs to be sent by SMS or by Voice.

Here are the steps i followed 

1) Download WART , start exec and enter phone number with CC . Hit request code.
2) Got a prompt stating that the code would be sent by voice.
3) Got call on phone which gave me the 6 digit code.
4) Entered code in WART and got password.
5) Added password to config file . The config file format is the same as used in previous yowsup versions.
6) Ran the yowsup-cli to send a message.

**Comment by toannq177** [comment]
Hi, 
I'm using a Vietnam phone number and still have the same issue.

**Comment by italogf** [comment]
My  problem no_routes was solved after I make a new yowsup clone.

2015-02-10 3:19 GMT-02:00 T Nguyen <notifications@github.com>:

**Comment by ashwinrath** [comment]
@toannq177 did you use WART ? using yowsup-cli gave me the no routes . WART however managed to get the password.

**Comment by toannq177** [comment]
@ashwinrath hi new yowsup build now fixes the problem. I don't use WART btw.

**Comment by ymys** [comment]
Same here with cc 62 (Indonesia). 
yowsup-cli: 2.0.9
yowsup: 2.2.78

**Comment by widnyana** [comment]
@ymys i have no problem with Indonesian number.
```
$ yowsup-cli version                                                                                                                                                                
yowsup-cli v2.0.9
Using yowsup v2.2.78
```

**Comment by ymys** [comment]
@widnyana thanks for your info. After test on another machine, the problem was solved.

**Comment by yniwly43** [comment]
Just a remark - sometimes the server's IP causes blocking, or no_routes.. in that case, just use a different IP.

I tried registering with 1 IP, got no_routes, tried another IP - exactly the same - it worked.

**Comment by Nickiler531** [comment]
Hi! i trying it for Colombia but the no_routes error appear.


yowsup-cli  v2.0.15
yowsup      v2.5.0

yowsup-cli registration --requestcode sms --phone 573196193239 --cc 57 --mcc 732 --mnc 154

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by renato-farias** [comment]
Hi Guys,

Just an update... I got the same problem, but, I tried using the debug command stdout (the URI [resource + attrs]) + the headers of that request and I passed it thru curl request, it worked perfectly:

curl 'https://v.whatsapp.net/v2/code?cc=55.......ED%E2eI%E0%3D%3F%CCO' -H 'Accept: text/json' -H 'User-Agent: WhatsApp/2.16.9 S40Version/14.26 Device/Nokia-302'.

The response was: {"status":"sent","length":6,"method":"sms","retry_after":64,"sms_wait":64,"voice_wait":64}.

I received the SMS correctly. But, When I tried to execute the register thru the cli, it raises with the following message:

    Traceback (most recent call last):
  File "/home/web/.virtualenvs/whatsapp/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/home/web/.virtualenvs/whatsapp/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/web/.virtualenvs/whatsapp/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/web/.virtualenvs/whatsapp/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/web/.virtualenvs/whatsapp/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 191, in process
    self.handleRegister(self.args["register"], config)
  File "/home/web/.virtualenvs/whatsapp/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 215, in handleRegister
    req = WARegRequest(config["cc"], config["phone"], code)
  File "/home/web/.virtualenvs/whatsapp/local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/registration/regrequest.py", line 35, in __init__
    raise ValueError("You have to request code first")
ValueError: You have to request code first

**Comment by jlguardi** [comment]
@renato-farias You need to create the Id file. This file contains just the Id sent in the code request. 
This file I created by yowsup if response of code request is success so you don't have this file. Then, if you try to register with t code yo get w curl, you miss the Id.

**Comment by dzfweb** [comment]
@jlguardi  i received the sms code, but when i register it, i get ` `ValueError("You have to request code first")`

i need to manually create an id file?

**Comment by jlguardi** [comment]
@dzfweb you really need the same id file generated while sms was sent. Otherwise register doesn't work. Probably you used other computer or user. Search it.

**Comment by Teyae** [comment]
still "no route". cc code 86
