### ISSUE TITLE
ACCOUNT KILLED - STEP BY STEP - WHATS WRONG?

### ISSUE THREAD

**Issue by h1rule** [tgalal/yowsup#391]
Hello.
Using the latest yowsup.

Fresh install, fresh account, it was registered. First thing was "success" but SMS didnt delivered. Sent again -> Auth invalid -> Account blocked.

$ ./yowsup-cli -c config.example -r voice
Detected cc: 1
status: sent
retry_after: 82805
length: 6
method: voice

$ ./yowsup-cli -c config.example -R 496595
Detected cc: 1
status: ok
kind: free
pw: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
price: $0.99
price_expiration: 1419895106
currency: USD
cost: 0.99
expiration: 1448448096
login: 190999xxxxx
type: existing

$ nano config.example #just insered the password into the config

$ ./yowsup-cli -c config.example -s 49151XXXXXXXXX "hi"
Detected cc: 1
Authed 190999xxxxx
Sent message #message didnt recieved!

$ ./yowsup-cli -c config.example -s 49151XXXXXXXXX "hi"
Detected cc: 1
Auth Failed! #and account is blocked.

Why do you think is that like this?
##

**Comment by rami-dabain** [comment]
So what is the maximum simcards per IP ?
what will happen if you're connected to a public wifi with 100 users on it ?

**Comment by aesedepece** [comment]
We run >150 simcards from the same IP, none got blocked under rational usage by strictly following WhatsApp terms of use.
