### ISSUE TITLE
Reason_ old_version

### ISSUE THREAD

**Issue by juancresc** [tgalal/yowsup#394]
I'm getting an old_version reason when trying to request the code

python yowsup-cli --requestcode sms -c config

Failed, reason: old_version. Checking for a new token..
Fetched a new token, persisting !
Now retrying the request..
status: fail
reason: old_version

is there anything we can do to continue activating lines?

I'm also getting auth failed in my previous working number :(

**Comment by rs-renato** [comment]
Still getting old_version to following token:

"v": "2.12.49",
"r": "S40-2.12.49",
"u": "WhatsApp/2.12.49 S40Version/14.26 Device/Nokia302",
"t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1413401214298{phone}",
"d": "Nokia302"

**Comment by CODeRUS** [comment]
Update to yowsup2, legacy code is outdated
