### ISSUE TITLE
Yowsup disconnecting after brief period and failing to reconnect (Authentication Failure)

### ISSUE THREAD

**Issue by programmer-ke** [tgalal/yowsup#398]
Yowsup stopped working on my VPS on 13th Nov (failed authentication). 

I pulled the latest version into my local machine today and using the same credentials could the `yowsup-cli` to authenticate and send/receive messages. However after pushing the changes onto my VPS, it authenticated and worked for only a brief amount of time (about 2 minutes) before disconnecting. 

Authentication now fails on both the VPS and my local machine using the same set of credentials.

I don't know if it's related to: https://github.com/tgalal/yowsup/issues/332

Anyone experiencing the same issue? Any help will be appreciated.

PS: Thanks for your great work @tgalal and the rest!

**Comment by codejunky** [comment]
I still encounter this issue.

My setup is:

> 
> (whatsapi-virtualenv)[jan@virtual demos]$ yowsup-cli version
> yowsup-cli v2.0.13
> Using yowsup v2.4.48

This is the output:

> [offline]: /L
> Auth: Logged in!
> general: Disconnected: Connection Closed
> [connected]:
> 
> [offline]:

**Comment by sree0410** [comment]
i have the same problem 

anything to do with -E option while registering ?
how do authenticate the login what i have obtained ?

please help 

Thanks in advance
