### ISSUE TITLE
How to use ping

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#402]
Hi, 

how can I get the result of a ping ? 

To send it out, I used the example in the cli/layer.py: 

``` python
print("Do a Ping")
entity = PingIqProtocolEntity(to = YowConstants.DOMAIN)
self.toLower(entity)
```

I can see it is send out and I also got an answer:

```
Do a Ping
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="w:p" type="get" id="1417385489-9">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="1417385489-9">
</iq>
```

However, how can I reach this result? 

I tried already:

``` python
@ProtocolEntityCallback("result")
def onResult(self, entity):
    print(entity)

@ProtocolEntityCallback("iq")
def onIq(self, entity):
    print(entity)
```

But both of them are not hit. Do I need to do something else ? 

Background is, I need some connection monitoring, so in case the IP connection get interrupted (e.g. DSL reconnect), I want to do a clean disconnect and reconnect. If there is a easier way to do this, that would be of course also interesting. :)

Thomas

**Comment by rulogarcillan** [comment]
why not send ping 

    entity = PingIqProtocolEntity(to = YowConstants.DOMAIN)
NameError: global name 'PingIqProtocolEntity' is not defined

**Comment by viksit** [comment]
You'll need to import the right class first.

**Comment by rulogarcillan** [comment]
Hi, I'm trying to ping to try to resolve the disconnect (see # 429), but never prints the ping me

def onEvent(self, event):
        if event.getName() == "MAKE_PING":
            print('onEvent: Tipo de evento: %s' % event.getName())
            entity = PingIqProtocolEntity(to = YowConstants.DOMAIN)
            self.toLower(entity)
            self.pingcount += 1
            print time.asctime( time.localtime(time.time())) + " Pingcount: {0}".format(self.pingcount)

        else:
            print('onEvent: Tipo de evento: %s' % event.getName())

    @ProtocolEntityCallback("iq")
    def onIq(self, entity):
        print(entity)

**Comment by viksit** [comment]
Same here - I have almost exactly the same code, but I can't seem to see the ping come in.
@tgalal - any possible insights?

Thanks.
