### ISSUE TITLE
yowsup-cli: Send message to group does not work

### ISSUE THREAD

**Issue by jroman** [tgalal/yowsup#412]
Hi there,
I detected that group messages were not being delivered. Checking with the legacy version I see that the @xxx to append to the number is different when sending to a number that to a group.

The solution might be modifying `demos/cli/layer.py`, method `normalizeJid()`, and leave it as in:

```
    def normalizeJid(self, number):
        if '@' in number:
            return number

	if '-' in number:
		return "%s@g.us" % number
	else:
		return "%s@s.whatsapp.net" % number
```

Hope this helps.

**Comment by gromeck** [comment]
Sorry, but still buggy ...

in ~/demos/sendclient/layer.py the number (phone) is still not normalized!

**Comment by capsload** [comment]
Im still unable to send messages to groups, using yowsup-cli demos -s GROUPCREATORNUMBER-TIMESTAMP

:(

**Comment by edgdelgado** [comment]
me 2

**Comment by Rudu-be** [comment]
Also not working for me

> yowsup-cli demos -c yowsup.config -s 32475123456-1420558637@g.us 'message'

but

> yowsup-cli demos -c yowsup.config -s 32475123456 'message'

works fine

In demos --yowsup i can send without problems.

**Comment by tgalal** [comment]
@capsload @edgdelgado @Rudu-be send demo is supposed to be fixed since 4c4193a01c931c8f06688b3ab8dfc0c5205ab2fe no?

**Comment by Rudu-be** [comment]
I didnt see the update, it is working now, THX

**Comment by LeVadim** [comment]
same issue, I can't send the group message using JID
