### ISSUE TITLE
Yowsup 2.0 - Sending images from desktop

### ISSUE THREAD

**Issue by vsarinho** [tgalal/yowsup#413]
Do you have an example?? 

According to cli example:

    #@clicmd("Send and image")
    def image_send(self, jid, path):
        pass

**Comment by nautical** [comment]
I was able to upload the image successfully , the sending part is not working , will try your code and update.

**Comment by morfeokmg** [comment]
Let me if understand your change,  we need two steps for send the image to the smartphone. 
1. Upload the image to the wattsapp server. 
2. Send the message to the group or participant,  as the image uploaded. 

My question is: what kind of message we need for send the image in step 2. (text, url, image) 
What I need implement for end the module?? 

I implement the legacy version for my server and I have reports on image format,  my idea is send these one's to my wattsapp. Only I need the second step for complete this one. 

I review the code but I don't the implementation for the command,  I know how can with xml,  only need the information for the command of send the image (that I understand the the command for upload is very different  for the step 2nd)

**Comment by morfeokmg** [comment]
This is my test. 
I executed in debug mode. 

....
    YowsupConnectionManager:	starting reader
    YowsupConnectionManager:	started
    Sending picture /home/morfeokmg/watts/Caso1.jpg of size 42781 with name Caso1.jpg
    Sending media_requestUpload
    BinTreeNodeWriter:	Outgoing
    BinTreeNodeWriter:	
    <iq to="s.whatsapp.net" xmlns="w:m" type="set" id="upload_1">
       <media type="image" hash="hsjVxrz8M1Z0J8nNmQAcBph3NIsuU6SDiNl6xiGp6OM="    size="42781">
       </media>
    </iq>

......

    BinTreeNodeReader:	Incoming
    BinTreeNodeReader:	
    <iq type="result" from="s.whatsapp.net" id="upload_1">
        <duplicate mimetype="image/jpeg"     filehash="hsjVxrz8M1Z0J8nNmQAcBph3NIsuU6SDiNl6xiGp6OM="     url="https://mmi631.whatsapp.net/d/AubJPvfWLCHP69u3qvJxNxoTVl1N0wNkjuC0mnt4B5t0.jpg"     height="434" width="700" type="image" size="42781">
        </duplicate>
    </iq>

    Request Dublicate: hash: hsjVxrz8M1Z0J8nNmQAcBph3NIsuU6SDiNl6xiGp6OM= url:     https://mmi631.whatsapp.net/d/AubJPvfWLCHP69u3qvJxNxoTVl1N0wNkjuC0mnt4B5t0.jpg 
    Sending message_image
    BinTreeNodeWriter:	Outgoing
    BinTreeNodeWriter:	
    <message to="XXXXXXX-XXXXX@g.us" type="text" id="1420751496-0">
        <media     url="https://mmi631.whatsapp.net/d/AubJPvfWLCHP69u3qvJxNxoTVl1N0wNkjuC0mnt4B5t0.jpg"     type="image" file="Caso1.jpg" size="42781">
        796573
        </media>
        <x xmlns="jabber:x:event">
            <server>
            </server>
        </x>
    </message>

    BinTreeNodeReader:	Incoming
    BinTreeNodeReader:	
    <ack count="5" t="1420751480" from="XXXXXXXXXXX@g.us" id="XXXXXXX-0" class="message">
    </ack>

    Got request MediaReceipt


Please, I need know what I need modify or implement in the code!!!!. 

Best Regards.

**Comment by nautical** [comment]
@ivanbaldo can u give a gist of example that you wrote worked ?

**Comment by morfeokmg** [comment]
Are your changes!, as I comment "...Let me if understand your change..." jejejejejejee. 
Your sirpoot / UploaderClient.py
and your recomendation for the bitearray.

**Comment by morfeokmg** [comment]
I review the code on connectionmanager.py
 I think that the incomplete code is: 

      @mediaNode
	def sendImage(self, jid, url, name, size, preview):
		return "image"


If this is correct, i Need implement some return as 

        return ProtocolTreeNode("media", {"type":"location","latitude":latitude,"longitude":longitude},None,preview)

but i don't know the variables, @tgalal, @chirikchik, @debianitram do you know what parameters i need??? 

Thanks in advance!

**Comment by morfeokmg** [comment]
I analize the debug, and this is my unique conclusion 

From UploaderClient.py the correct execution is: 

				ReaderThread:	Read thread startedX
				 YowsupConnectionManager:	started
				Sending picture /home/morfeokmg/watts/CasoMau.jpg of size 42781 with name CasoMau.jpg
				Sending media_requestUpload
				BinTreeNodeWriter:	Outgoing
				BinTreeNodeWriter:	
				<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="upload_1">
				    <media type="image" hash="hsjVxrz8M1Z0J8nNmQAcBph3NIsuU6SDiNl6xiGp6OM=" size="42781">
				    </media>
				</iq>


This part doesn't work or is incomplete (I think that is the second option)
(from UploaderClient.py Interface : message_imageSend)

				def doSendImage(self, url):
			                print("Sending message_image")
			                statinfo = os.stat(self.path)
			                name=os.path.basename(self.path)
			
			                #im = Image.open("c:\\users\\poot\\desktop\\icon.png")                                                                                               
					#im.thumbnail(size, Image.ANTIALIAS)                                                                                                                 
			
				        msgId = self.methodsInterface.call("message_imageSend", (self.jid, url, name,str(statinfo.st_size), "yes"))
					#msgId = self.methodsInterface.call("message_imageSend", (self.jid, url, name,str(statinfo.st_size), self.createThumb()))                            
					self.sentCache[msgId] = [int(time.time()), self.path]
				



				Request Dublicate: hash: hsjVxrz8M1Z0J8nNmQAcBph3NIsuU6SDiNl6xiGp6OM= url: https://mmi631.whatsapp.net/d/AubJPvfWLCHP69u3qvJxNxoTVl1N0wNkjuC0mnt4B5t0.jpg 
				Sending message_image
				BinTreeNodeWriter:	Outgoing
				BinTreeNodeWriter:	
				<message to="XXXXXXXXXXX-XXXXXXX@g.us" type="text" id="XXXXXXXXX-0">
				    <media url="https://mmi631.whatsapp.net/d/AubJPvfWLCHP69u3qvJxNxoTVl1N0wNkjuC0mnt4B5t0.jpg" type="image" file="CasoMau.jpg" size="42781">
				        796573
				    </media>
				    <x xmlns="jabber:x:event">
				        <server>
				        </server>
				    </x>
				</message>



But   message_imageSend
Is  
          self.methodInterface.registerCallback("message_imageSend",self.sendImage)


and sendImage is not implemented


				@sendMessage
			        @mediaNode
				def sendImage(self, jid, url, name, size, preview):
					return "image"				



what I Need for implement the missing code?



Thanks!

**Comment by tgalal** [comment]
Hi all! I appreciate your efforts a lot! I've finished building this into yowsup and yowsup-cli and will publish it with documentation in a few a hours.

**Comment by morfeokmg** [comment]
If we can contribute something, we will be very pleased !!!!

**Comment by morfeokmg** [comment]
Sorry @tgalal, do you have the update or only the documentation? 

BR

**Comment by nautical** [comment]
Thanks working well now ..

**Comment by morfeokmg** [comment]
hi!, some update????

BR

**Comment by morfeokmg** [comment]
Sorry, some update????

**Comment by morfeokmg** [comment]
@tgalal, i search in the documents, but doesn't have more about this one: 

             def sendImage(self, jid, url, name, size, preview):
                #return "image"
                self._d("sending image (" + name + ":" + str(size) + ")")

                return ProtocolTreeNode("media",     {"type":"image","name":name,"size":size,"url":url,"to":jid},None,preview)


I review your code, but, i don't understand in what part is implemented the types for ProtocolTreeNode.

Please, help me to understand this one!

BR

**Comment by tgalal** [comment]
I'm sorry there is not going to be an update/support for legacy (unless someone wants to send a pull a request). This issue was opened for yowsup2 though and sending images is working there so I'll need to close it

**Comment by morfeokmg** [comment]
OK, thanks!, let me open some request for legacy.

**Comment by jigarrdesai** [comment]
how to sent image from path using yowsup-cli demos command?

**Comment by niravtrivedi** [comment]
I have tried below steps 

pip uninstall PIL
sudo apt-get install libjpeg-dev
pip install -I pillow

Thanks
