### ISSUE TITLE
Please add batch command capabilities to cli and improve examples

### ISSUE THREAD

**Issue by de666** [tgalal/yowsup#418]
Please add simple how to for oneshot application like connect, send and disconnect.
I've tried to use the SEND_AND_EXIT event inside the cli module but without success.
The code is something like this

```
from yowsup.demos import cli
import yowsup
from yowsup.layers import YowLayerEvent

credentials = tuple(['123456789', 'aabbccddaabbccdd='])
message = 'test message'
number = '123546987'
cli_stack = cli.YowsupCliStack(credentials)
cli_layer=cli.layer.YowsupCliLayer()
kwargs = {"credentials": credentials, "target": cli_layer.normalizeJid(number), "message": message}
cli_stack.stack.broadcastEvent(YowLayerEvent(cli_layer.EVENT_SENDANDEXIT, **kwargs))
```

But it doesn't work.
Anyway I think the documentation lacks support for such applications, i.e. something simple which do the thing in a syncronous way (I know that this api is obvioulsy asyncronous)

example:

Connect
Wait until connect
Send a message
Wait until message is sent
Disconnect

Also I think the cli shuould have the same capabilities of the previous cli (ex. to send one shot messages).
Furthermore there is no explanation inside the tutorial about how to stop the stack loop because the tutorial assumes that you want always to develop an application (service) which loops forever.
##

**Comment by nico81** [comment]
Yes, I need an /exit command to quit cli ;)

**Comment by BodduSatya** [comment]
@de666
do you have any solution for batch cmds from cli?
