### ISSUE TITLE
Create a periodic server ping

### ISSUE THREAD

**Issue by tgalal** [tgalal/yowsup#429]
A connection to WhatsApp  server with no ongoing traffic is kept alive through 2 methods:
 - WhatsApp sends us a ping every now and then, yowsup automatically pongs it, that's currently implemented and working.
 - We send a WhatsApp a ping ([PingIqProtocolEntity] (https://github.com/tgalal/yowsup/blob/master/yowsup%2Flayers%2Fprotocol_iq%2Fprotocolentities%2Fiq_ping.py)) for example by using '/ping' in [Yowsup Command line client](https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Command-line-client)

The problem is whatsApp does not always send us pings, and so the connection could be dropped without us realizing (connection might actually seem open until we try to send something and then it disconnects). Therefore we need to schedule a periodic ping to send to WhatsApp, say every 2 minutes for the following reasons:
 - For WhatsApp to keep our connection alive
 - For detecting that connection is gone and recovering quickly if it ever happens

**Comment by msshapira** [comment]
@galmeida Did you get round to sending the PR?

**Comment by viksit** [comment]
+1 - would love to see a PR for this.

**Comment by galmeida** [comment]
I will send it today but probably @tgalal will recommend some changes.

**Comment by rulogarcillan** [comment]
Thanks galmeida because I am unable to leave Online

**Comment by viksit** [comment]
@galmeida in case you have a PR, perhaps you can put it on a gist somewhere, and I (or someone else) can help out in reviewing/editing it before a formal PR?

**Comment by galmeida** [comment]
I found a bug, I'll try to fix it and upload it somewhere

**Comment by galmeida** [comment]
code available here: https://github.com/galmeida/yowsup/tree/auto-ping, thanks for reviewing

**Comment by kuldippatel** [comment]
@galmeida @tgalal 
Question: Is the current Yowsup code takes care of sending auto-ping? If not, can you share  sample code? I was sending ping myself in legacy code. Ping/Pong did not work and not relible if WhatsApp does not send ping.

**Comment by galmeida** [comment]
@kuldippatel, please check the link in the comment above yours

**Comment by rulogarcillan** [comment]
I downloaded your layer stack but the attachment in n is where I have to call to automatically reconnect, I am new to python and I'm lost

In what I call stack to automatically connect to lose connection?

**Comment by CODeRUS** [comment]
Also whatsapp server timeout is 900 seconds, you can schedule to ping every 14 minutes safely.

**Comment by viksit** [comment]
@galmeida btw I reviewed that code a few weeks ago - could you submit a PR?

**Comment by galmeida** [comment]
@viksit will do that right away

**Comment by idigevian** [comment]
@tgalal Staying connected to Whatsapp is going to be a requirement for a lot of folks. If we can include this use case in the Sample App, then i suppose it will benefit a lot of us.

**Comment by Maria00** [comment]
Im trying to connect to the whatsapp server but always says: "general : Disconnected: Connection Closed [offline]" , and when i make a ping directly to the server with the comand /ping, a message appear that says Error: Not connected.

**Comment by juandedmv** [comment]
It found some solution to the disconnection

**Comment by juandedmv** [comment]
It found some solution to the disconnection??

**Comment by bkoroglu** [comment]
After investigating all issues related to disconnection, I understand that yowsup can send and receive ping requests by default when you start your app. It is our responsibility to set the interval of ping requests, awaring of being disconnected and recovering. Am I Wrong?

**Comment by tsifra** [comment]
Guys,  do you have any problems with keepalive using latest version of yowsup available for today?
@bkoroglu how about you?

For me yowsup is not able to handle messages after 2-3 hours

I've created special "ping" thread sending messages to my number. This makes lifetime longer, but some time after 2-3 hours message handling dies anyway.
```
def wa_keepalive():
    while 1:
        time.sleep(1800)
        print(time.ctime())
        layer = stack.getLayer(8)
        layer.message_send('xxx', 'ping text')
```
