### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by andro1de1** [tgalal/yowsup#430]
![captura de pantalla de 2014-12-03 21 46 53](https://cloud.githubusercontent.com/assets/10042101/5292865/05dad206-7b36-11e4-8791-375895b8ed50.png)

just stopped working :(   (02:50 GMT)

....whatsapp servers?

**Comment by ciudadanoterrorista** [comment]
[offline]:/L

general: Disconnected: Connection Closed
[offline]:

general: Disconnected: Connection Closed

**Comment by kapil019** [comment]
Same here 
Disconnected: Connection Closed
general: Disconnected: Connection Closed
