### ISSUE TITLE
Old Messages

### ISSUE THREAD

**Issue by techupin** [tgalal/yowsup#450]
Hello,

I just downloaded Yowsup 2.0 and logged in through the command line using `yowsup-cli demos -y` option...

My question is...

I logged and and all my messages just flashed and paged down...  I logged out and logged back in.
How do I fetch/see my old messages?

Thanks!

TU

**Comment by kerel-fs** [comment]
To recover your messages from console output, you could use this regular expression:
```
\[(?P<senderid>[0-9]*)\/(?P<groupid>[0-9]*-[0-9]*)@g.us\((?P<datetime>(?:[0-9]{2}\-){2}2015 [0-9]{2}:[0-9]{2})\)\]:\[(?P<id>[A-Z0-9a-z]{13}|.*)\]\t (?P<body>.*)\nMessage (?P=id): Sent delivered receipt\n\[connected]:
```
https://regex101.com/r/sQ6uK6/3
https://gist.github.com/kerel-fs/d64f12c5a23577ca2b9a

(yowsup version 2.4)
