### ISSUE TITLE
pass credentials from layer to stack

### ISSUE THREAD

**Issue by kwiiby** [tgalal/yowsup#451]
Hi, I'm trying to set credentials by my layer (editing echoclient), but I can't..

Here is my code:
self.YowInterfaceLayer.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, ("number", "password"))

Error: 'EchoLayer' object has no attribute 'YowInterfaceLayer'

I've tried to set credentials in layer, then in stack I access like this: EchoLayer.credentials but it says that EchoLayer has no attribute 'credentials'

**Comment by shubham14** [comment]
Hi,
I am having this error "NameError: global name 'AuthError' is not defined"

**Comment by shubham14** [comment]
I Tried Re-registering,but it made no difference

**Comment by Dl0tt** [comment]
have you imported AuthError on your run.py?

```python
from yowsup.layers.auth import AuthError
```

-------- Original Message --------

**Comment by shubham14** [comment]
Thanks,it worked but I have one more query.
This is my code,I am able to send messages but not recieve them,it displays nothing

https://gist.github.com/shubham14/e7fbed7a748965897e69

Please look into it and help,
Thanks

**Comment by maruen** [comment]
@kwiiby Could you pass the parameter with setProp ? Im facing the same problem you faced.
Could you get it working?
