### ISSUE TITLE
ImportError: No module named Yowsup.connectionmanager

### ISSUE THREAD

**Issue by ishail** [tgalal/yowsup#472]
Hi,

On the "[Legacy] Yowsup Documentation" page, it is said that for connecting to signals one should use object of YowsupConnectionManager. But I'm unable to find that class in the code. Will you guys please help me to locate that?

**Comment by pballart** [comment]
How did you get it?

**Comment by ishail** [comment]
Actually it is in legacy and I was trying to find it in master
