### ISSUE TITLE
A simple send message python script

### ISSUE THREAD

**Issue by kxr** [tgalal/yowsup#475]
Hello every one,

Can anyone help me in writing a very basic send-message python script that simply connects, sends message, acknowledges the receipt, and disconnects.

Since last two days, I've been struggling with the code and the sample application, but can't get my head around this. The library is very well written but a bit difficult to comprehend for python newbies like me. Any help, hint, referrence etc. would be highly appreciated.

Best Regards,
Khizer

**Comment by blueredfish** [comment]
Happy new year!!!
Thank you so much for your work and effort, it's incredible!!.

Best regards.

**Comment by naveen1988** [comment]
Hello everyone,

I want to send image file through yowsup, is there any way to send using command line same like sending message.

**Comment by dektiram** [comment]
Hello everyone,

I want to make run.py call "yowsup/demos/sendclient/layer.py". I don't know to make that. would you like to explain or give an complete example please...

**Comment by dsiwer** [comment]
Hi Everyone! and thanks Tarek, this piece of code-art is wonderful!

I'm looking for the simples way to send a message, using:
MORE_IMPORTS_EXCLUDED in this message

from yowsup.demos import sendclient
unSender=sendclient.YowsupSendStack(CREDENTIALS, [(['mobile_number', 'message_text'])],True)
unSender.start()

And the message is sent, but as I can see in layer.py, it raises an exception to end the process.

I've been trying other examples, like the ones above, but If when I call send_message, it never gets out of the loop. If a comment the try_except block that makes the stack.loop(), the the message is sent, but subsequent calls to the function do not deliver the messages.

Can someone shed some light on this?

Many thanks in advance,
Diego

**Comment by mevinbabuc** [comment]
@tgalal after handling the `onsuccess` by passing the message to the `self.toLower(messageEntity)` do we have to send something back to the whatsapp server as a ack ? Can I get more clarity on why the number gets blocked. Or is there a way to be safe from getting blocked by whatspp ?

**Comment by Gaur1988** [comment]
please send complete example...

**Comment by leandromaiaf** [comment]
Hey guys, could somebody send the full script? Thanks

**Comment by shubhamivane** [comment]
Please send me full working script.

**Comment by ilhamhidayat** [comment]
@kxr 
assalamu'alaikum

dear kxr, 
i have a problem that same with you about "how to write a very basic send-message python script that simply connects, sends message, acknowledges the receipt, and disconnects. have you found the solution?
please help me how to solve my problem. i cant read tarek's comment. i really need that script to finish my study.
thank you for your attention.

best regards
ilham hidayat

**Comment by patelnilanj** [comment]
@junky84 have you make the code when gpio goes high, the message should send.
