### ISSUE TITLE
Changing the nickname.

### ISSUE THREAD

**Issue by chrisduerr** [tgalal/yowsup#476]
I've read through some of the sourcecode of yowsup bot couldn't find a way to change the nickname in the demos. I'm currently at the point where I have the echo client with closed to no modification and looking for an easy way to integrate the nickname which is displayed in group chats behind the number to get changed.
I hope you are able to help me with that.
##

**Comment by UndeadLeech** [comment]
PresenceProtocolEntity seems to be unable to get passed to a lower level because of missing tags.
So this code isn't working for me. Could be that this is my fault but I am not 100% sure because other stuff like pings seem to not work for me, too.

**Comment by rusan** [comment]
It works but only for contacts. But... for iphone apps on notification screen you can see this name :).

**Comment by UndeadLeech** [comment]
Shouldn't this name be displayed when you're in a group chat with that person but you didn't add them yet?
And how are you getting that to work? Because for me it's always saying something about a missing Tag?!

**Comment by tgalal** [comment]
@UndeadLeech you need to post more details about that missing tag. Any logs/ stacks traces?

**Comment by UndeadLeech** [comment]
![whatsappbot_name_error](https://cloud.githubusercontent.com/assets/8886672/5697451/1bb0327c-99f1-11e4-9273-b8825171ef7d.png)

This is the error I get in my cmd. For me it looks like I am doing something wrong or it shouldn't be possible to do it that way.

**Comment by tgalal** [comment]
if your layer sits above YowProtocolLayers, then you shouldn't do:
 > self.toLower(entity.toProtocolTreeNode())

Instead it should be just:
> self.toLower(entity)

**Comment by UndeadLeech** [comment]
I tried that out before and it's not returning an error. But it doesn't change the name in group chats. 
This is meant to change the name displayed after the number when a contact is not added, right?
And if it is and should work, is there any special time I need to call it? Or should it work whenever I am logged in? Thank you for your help :) .

**Comment by addodelgrossi** [comment]
I have same question. I can invoke code, but my profile name is not changed.

```
        entity = PresenceProtocolEntity(name="Meu Novo Nome")
        self.toLower(entity)
```
Thank you for your help :) .

**Comment by UndeadLeech** [comment]
So is this problem on our end or is it not 100% supporte since Yowsup 2.0?

**Comment by nurderfsv** [comment]
Is there a possible solution to the question of changing the nickname?

**Comment by bdbais** [comment]
I tried but nothing work, 

my code:

```
    @ProtocolEntityCallback("success")
    def onSuccess(self, successProtocolEntity):

        entity = PresenceProtocolEntity(name = "Bot nr 1")
        self.toLower(entity)
```

**Comment by jroman** [comment]
This is what I did:

File: yowsup/demos/cli/layer.py
Method: onSuccess()

```
    @ProtocolEntityCallback("success")
    def onSuccess(self, entity):
        self.connected = True
        self.output("Logged in!", "Auth", prompt = False)
        self.notifyInputThread()
###########  Start of my code
        try:
           self.profile_setStatus( MY_NICK_NAME)
        except BaseException, e:
              self.output( "CATCHED Exception while setting nick name after login: %s" % (str( e),), tag = "Exception in my code")
###########  END of my code
```

Hope this helps.
--
jroman

**Comment by jlguardi** [comment]
Changing nickname works perfectly using the code of @bdbais. The main problem is what this function does.
I mean: nickname is just displayed in the official client if you don't have registered the recipient. Otherwise, this app displays your local name for the recipient.

These are the logs for mobile changing nickname:
```
<message to="34xxxxxx@s.whatsapp.net" type="text" id="146xxxxx-15">
...
DEBUG:yowsup.layers.logger.layer:tx:
<presence name="changed">
</presence>
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<presence from="34xxxxx@s.whatsapp.net">
</presence>
...
<message to="34xxxxxx@s.whatsapp.net" type="text" id="146xxxxx-17">
```

yowsup client listening:
```
<message type="text" notify="34xxxxxx" from="34xxxxxxxx@s.whatsapp.net" id="146xxxxx-15" t="146xxxx">...
#changed nickname
<message type="text" notify="nickname changed" from="34xxxxxxxx@s.whatsapp.net" id="146xxxxx-17" t="146xxxx">...
```

As you can see, notify token changes correctly.

**Comment by ciclanoio** [comment]
![name](https://user-images.githubusercontent.com/6903142/58770886-cf821a00-8587-11e9-84d3-60ee58414bb8.png)

How to change this name ? Don't work for me @tgalal  

I try :  
       self.toLower(PresenceProtocolEntity(name="Mauricio")) Update name don't work
       self.toLower(SetStatusIqProtocolEntity(text='Working'))  # Set status text updated ok

  Thanks
