### ISSUE TITLE
Not receiving confirmation code.

### ISSUE THREAD

**Issue by NickCis** [tgalal/yowsup#477]
I've downloaded lastest version of yowsup. When i try to get the registration code with the cli interface, although, it says that the message has been sent, it never arrieves.
My carrier is Movistar/Argentina, (mcc: 722, mnc: 07, according to [wikiepdia] (http://es.wikipedia.org/wiki/MCC/MNC), and doubled checked with the phone information).
Looking in the request url, the mnc sent is 007, `&mcc=000&mnc=000&sim_mcc=722&sim_mnc=007&method=sms`, although i write `07`. I have the same problem using whats Api. (WhatsApi sends `sim_mnc=070`, instead of `sim_mnc=007`).
Any ideas what might be the problem? or how can i help to fix it?.

    [nickcis@myhost yowsup]$ python yowsup-cli registration --debug --mcc 722 --mnc 07 --phone 541135683012 -C 54 --id 000000000000000 -r sms
    DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.53 S40Version/14.26 Device/Nokia302'}
    DEBUG:yowsup.common.http.warequest:cc=54&in=1135683012&lc=US&lg=en&mcc=000&mnc=000&sim_mcc=722&sim_mnc=007&method=sms&id=5284047f4ffb4e04824a2fd1d1f0cd62&network_radio_type=1&reason=self-send-jailbroken&token=b9d5084813137f2b586a23223cf60cd6
    DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
    DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=54&in=1135683012&lc=US&lg=en&mcc=000&mnc=000&sim_mcc=722&sim_mnc=007&method=sms&id=5284047f4ffb4e04824a2fd1d1f0cd62&network_radio_type=1&reason=self-send-jailbroken&token=b9d5084813137f2b586a23223cf60cd6
    INFO:yowsup.common.http.warequest:b'{"status":"sent","length":6,"method":"sms","retry_after":46805}\n'
    length: 6
    status: b'sent'
    retry_after: 46805
    method: b'sms'

**Comment by tgalal** [comment]
1279940031d129045a17d8ba1a5aaf8863fea065 should hopefully fix it, reopen the issue if it doesn't
