### ISSUE TITLE
Number blocked

### ISSUE THREAD

**Issue by kuldippatel** [tgalal/yowsup#491]
Hello there,

I love this messaging platform and would love to follow their guidelines.
Any idea, under what circumstances WhatsApp blocks a number? 

Sending 1 message to 30 numbers over the period of 2-3 days spread across 10-15 minutes resulted in blocking :(. Any set of rules that we know of? Would like to follow them strictly if known.

Looking forward to hear from you.
Kuldip

**Comment by tgalal** [comment]
Sorry we wouldn't be interested in providing this info to prevent abuse by spammers.
