### ISSUE TITLE
Request code:  getting no_routes for an Indian number.

### ISSUE THREAD

**Issue by kuldippatel** [tgalal/yowsup#495]
Did not face this issue before for other numbers. Please help.

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by aesedepece** [comment]
Same issue trying to register any Spanish number.
I always get "no_routes" for all of them even specifying mcc and mnc.
Also unsuccessfully tried from different IPs.
Legacy branch fails as well.

**Comment by aesedepece** [comment]
This is likely a duplicate of #370
