### ISSUE TITLE
readline error ubuntu 14.04

### ISSUE THREAD

**Issue by DhirManish** [tgalal/yowsup#496]
Processing dependencies for yowsup2==2.0.53
Searching for readline
Reading https://pypi.python.org/simple/readline/
Download error on https://pypi.python.org/simple/readline/: [Errno 104] Connection reset by peer -- Some packages may not be found!
Couldn't find index page for 'readline' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 110] Connection timed out -- Some packages may not be found!
No local packages or download links found for readline
error: Could not find suitable distribution for Requirement.parse('readline')

**Comment by tgalal** [comment]
"Connection reset by peer", not a yowsup problem
