### ISSUE TITLE
sample Key sets

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [tgalal/yowsup#498]
@tgalal 
Please can you kindly send me some sample keys from your test suite.
I'm testing an alternative implementation.

**Comment by tgalal** [comment]
is that a yowsup issue ?

**Comment by CharlesOkwuagwu** [comment]
No its not please, I didn't now how to reach you off-the record.

Thanks.

**Comment by CharlesOkwuagwu** [comment]
Never mind, I've got decryption & encryption fully working in my .Net version. Cheers.
