### ISSUE TITLE
Unable to send axolotl keys: server answers "not-authorized"

### ISSUE THREAD

**Issue by aesedepece** [tgalal/yowsup#499]
When trying to use Yowsup2 with YowAxolotlLayer layer in my stack, login succeeds with:
```xml
<success status="active" kind="free" creation="1415386262" expiration="1446922262" props="4" t="1420212479">[...]</success>
```
But right after that, yowsup sends the following stanza to server:
```xml
<iq to="s.whatsapp.net" xmlns="encrypt" type="set" id="1">
  <list>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
    <key>
      <id>[...]</id>
      <value>[...]</value>
    </key>
  </list>
  <identity>[...]</identity>
  <registration>[...]</registration>
  <type>[...]</type>
  <skey>
    <id>[...]</id>
    <value>[...]</value>
    <signature>[...]</signature>
  </skey>
</iq>
```
Which is answered with:
```xml
<iq type="error" from="s.whatsapp.net" id="1">
 <error text="not-authorized" code="401">
 </error>
</iq>
```
Why am I not authorized to set my keys?
My credentials were created with legacy branch of yowsup. Do you know if WhatsApp servers only allow the use of encryption for credentials created with version greater than 2.11.452 or so?

**Comment by aesedepece** [comment]
Following exception is also raised:
```
Sent keys where not accepted
```
(btw: "were" instead of "where")

**Comment by tgalal** [comment]
lol yeah thanks for pointing it out I'll fix the type. For the not-authorized error I am not sure but what you say makes sense. Can you try register again ?

**Comment by aesedepece** [comment]
I'll try to as soon as I'm able, because at the moment I'm facing #495 / #480

**Comment by assegaf** [comment]
yeah I think newest wa still register to v.whatsapp.net , but seem with new method or parameter, if only mitmproxy style interception works we can sure see what are the changes.

**Comment by aesedepece** [comment]
After re-registering with the latest changes (1279940) and using Android env instead of S40, keys are correctly generated and sent. Thanks @tgalal
