### ISSUE TITLE
yowsdown message

### ISSUE THREAD

**Issue by pinpuk** [tgalal/yowsup#502]
yowsup-cli demos -l 32xxxxxxx:base64password= -s Hello World

Yowsdown

the base64password ends with =  do I need to include it ?

**Comment by pinpuk** [comment]
yowsup-cli demos -l 32xxxxxxx:base64password= -s 32xxxxxxx Hello World

Yowsdown

sorry forgot the number but (its still Yowsdown)

**Comment by CODeRUS** [comment]
https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0#yowsup-cli-demos

**Comment by tgalal** [comment]
Yowsdown in this demo means message was sent, check your phone. I agree that  it should output a more clear message to indicate that, i'll change it.

**Comment by tgalal** [comment]
if you were not receiving the message, it's very likely related to a bug I've just fixed. Please update and try again.

**Comment by pinpuk** [comment]
@tgalal I did check my phone and I did received the message. Good idea to change the output message. 
You may close.
