### ISSUE TITLE
cant sent message

### ISSUE THREAD

**Issue by sabry2010** [tgalal/yowsup#508]
@tgalal  
hi thanks for your work 
i have big problem i have used last update of yowsup and after that i try send message 
whatsapp block the number and the result back from python  array is empty can you help me please to fix this issue
best regards

Executing /usr/local/bin/python yowsup-cli -c 201065226297.example -s 96560011468 "hi test message" message sent
96560011468Array ( ) 3532Array ( [0] => )

**Comment by tgalal** [comment]
block the number ?

**Comment by tgalal** [comment]
+ that's not the  last update of yowsup

**Comment by sabry2010** [comment]
i download the last update and change the old one 
can you write me the paython command  to send the message

**Comment by sabry2010** [comment]
@tgalal  Can You Help me

**Comment by tgalal** [comment]
sorry you have to help yourself
