### ISSUE TITLE
How I can I run youwsup from php?

### ISSUE THREAD

**Issue by jandrito80** [tgalal/yowsup#51]
I want to send and receive messages from php. I need to register a new number with the script "python. / Yowsup config.example-cli-c-d - requestcode voice".
I do not know python, how I can run this on my server from php?
Thanks for your understanding.

**Comment by Gonzo2028** [comment]
This is sadly not possible or at least very tricky, because you cannot run it in php exec, some switches and functions are not available. You can send easily, but receiving is impossible.
