### ISSUE TITLE
YowMediaProtocolLayer doesn't support "audio" and "video" types

### ISSUE THREAD

**Issue by aesedepece** [tgalal/yowsup#512]
"audio" and "video" media types need to be added to YowMediaProtocolLayer.

I'm one of those who prefers to fix things instead of complaining or demanding, so I assign this issue to myself. :blush:

**Comment by aesedepece** [comment]
Work is going on https://github.com/waalt/yowsup/commits/audio-and-video-receive
Audio is done, though I want to catch some more specific attributes :white_check_mark:

**Comment by aesedepece** [comment]
Audio-specific attributes are:
* abitrate
* acodec="aac"
* asampfreq
* duration
* seconds

**Comment by tgalal** [comment]
Cool that's great! I'm overwhelmed by the things I need to implement and you are providing great help! Thanks !!

**Comment by aesedepece** [comment]
This week I'll keep on working on this. I think it'll took me a pair of days.
Sorry for the delay :sweat: 

BTW @tgalal, I've written unit tests for new classes and want to include them in the PR, but I'm not sure how to run them as I never used python tests before. Could you enlighten me? The Wiki page on the matter is empty: https://github.com/tgalal/yowsup/wiki/Unit-testing
Thanks a lot!

**Comment by aesedepece** [comment]
Video-specific attributes are:
* abitrate
* acodec
* asampfmt
* asampfreq
* duration
* encoding
* height
* fps
* seconds
* vbitrate
* vcodec
* width

**Comment by aesedepece** [comment]
Ok, I eventually figured out how to run tests (```nosetests```).
PR is in https://github.com/tgalal/yowsup/pull/626 :wink:
