### ISSUE TITLE
There is a code error in this class: LiteIdentityKeyStore->isTrustedIdentity() method

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [tgalal/yowsup#516]
You are not passing **recipientId** as expected in your select statement ...

def isTrustedIdentity(self, recipientId, identityKey):
        q = "SELECT public_key from identities WHERE recipient_id = ?"
        c = self.dbConn.cursor()
        **c.execute(q, (identityKey.getPublicKey().serialize(),))**
        result = c.fetchone()
        if not result:
            return True
        return result[0] == identityKey.getPublicKey().serialize()

**Comment by tgalal** [comment]
thanks for reporting this!
