### ISSUE TITLE
Logging in two users simultaneously

### ISSUE THREAD

**Issue by anmoluppal** [tgalal/yowsup#517]
I was wondering if it's possible to login 2 users simultaneously, I was trying to do this, But I dont have any fair knowledge of threadings, All I want to know is if there is a way to do something like this ? and if so ? Can someone lay an outline of this process? Any help would be appreciated,  I want to login my both whatsapp numbers and simultaneously receive messages for any or both of them?

**Comment by tgalal** [comment]
if you are referring to yowsup-cli, you can just run 2 instances from 2 different shells or something, right ?

**Comment by anmoluppal** [comment]
Nah I want to login 2 user simultaneously (impicitly in the source code) and want the output(notifications, unread messages etc. ) to be shown on a single cmd terminal , Is that possible ?

**Comment by tgalal** [comment]
ah nope not possible with current implementation.

**Comment by anmoluppal** [comment]
Thanks a lot for clarifying the issue, I would love to work on such implementation if my schedule allows me to do so , Thanks
