### ISSUE TITLE
Sending read receipts in groups

### ISSUE THREAD

**Issue by tcoenraad** [tgalal/yowsup#524]
As given in the [sample app](https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app#layerpy-iv) on the wiki, I [send receipts](https://github.com/tcoenraad/inter-actief-botje/blob/master/layer.py#L26) after receiving any message. This works as expected in private conversations, in which I get blue checks and I can see a seen and delivered time in the message info dialog.

However, this does not work in groups, and the delivery and read check remains grey. In the message info dialog, the message does not seem to be delivered to the Yowsup client, although the message is in fact passed through Yowsup. Can you please help? A similar issue is described in the WhatsAPI issue tracker: https://github.com/mgp25/WhatsAPI-Official/issues/153

**Comment by rienheuver** [comment]
+1 on this problem

**Comment by Kurocon** [comment]
This also affects my application.

**Comment by tcoenraad** [comment]
This fix looks promising: https://github.com/mgp25/WhatsAPI-Official/commit/afb1db3cebf631241186458f444f4e071ea456be

**Comment by matteocontrini** [comment]
This is the other modified part: https://github.com/mgp25/WhatsAPI-Official/commit/602be31d39dddcdf268bfeb157ab1ed2c7c9f2f2

**Comment by tcoenraad** [comment]
Updated Echo client on wiki: https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app/fe016691b6092a77b65326070fff8d480630d9cc
