### ISSUE TITLE
Enable autoreceipt for all messages

### ISSUE THREAD

**Issue by addodelgrossi** [tgalal/yowsup#525]
In file [yowsup/demos/cli/layer.py](yowsup/demos/cli/layer.py) exists property 

``` python
PROP_RECEIPT_AUTO       = "org.openwhatsapp.yowsup.prop.cli.autoreceipt"
```

But I did not understand.
##

**Comment by tgalal** [comment]
At the moment this property is not being used, but is supposed to be enabled for all messages by default. Are you getting a different behavior?

**Comment by tgalal** [comment]
Sorry I'm wrong, auto receipt is actually not enabled by default. I've updated the issue title and will close it once it's implemented
