### ISSUE TITLE
Yowsdown

### ISSUE THREAD

**Issue by XaKaX** [tgalal/yowsup#526]
I'm getting the message **Yowsdown** even though I receive the message on my mobile phone.
Shouldn't I get something like
**Sent message**
**Got sent receipt** ?

Here is the thing:
**root@xakax:/home/xakax/yowsup-master#** yowsup-cli demos -l 5535********:blablabla/blablabla= -s 5535******** "Saudade"

Yowsdown
**root@xakax:/home/xakax/yowsup-master#**

When I add the -d (debug), here is what I see:
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5535********" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�ym޹��ǐr@�QbL��{.}
HEX:86796ddeb9edf2c79072408a51624ca9cf7b2e7d
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
4�>HϺ�yA-��lXS�VI���a dE�1`#�S6e]�F�m/-
HEX:3404a13e8e5648cfbad479412d89bf6c5853f05649e0daff61201a126445c0316023fc5336655dcc46b26d2f182d
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1420734365" expiration="1452270365" props="4" t="1420735487">
	�M#�2�c�^�.Aa���
HEX:09ca4d23da32d663151dbe5e812e411b61b3bff9
</success>

DEBUG:yowsup.layers.logger.layer:tx:
<message to="5535********@s.whatsapp.net" type="text" id="1420735487-1">
<body>
Saudade
HEX:53617564616465
</body>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1420734365" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1420735487" from="5535********@s.whatsapp.net" id="1420735487-1" class="message">
</ack>

Yowsdown
root@xakax:/home/xakax/yowsup-master#

**Comment by Ipystar** [comment]
I think you should pull the latest version of Yowsup, I dont think you would get that error anymore.
