### ISSUE TITLE
I do not receive encrypted messages

### ISSUE THREAD

**Issue by Udirley** [tgalal/yowsup#528]
python2.7 /usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config.teste-CCCCC -e -m
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Segmentation fault
##

**Comment by Udirley** [comment]
After changing the files below

yowsup/layers/axolotl/layer.py
yowsup/layers/axolotl/protocolentities/iq_key_get.py

The result became this

INFO:yowsup.layers.axolotl.layer:Textsecure layer is generating keys, this might take a minute
DEBUG:yowsup.layers.axolotl.layer:Generating Identity...
DEBUG:yowsup.layers.axolotl.layer:Generating Registration Id...
DEBUG:yowsup.layers.axolotl.layer:Generating 200 PreKeys...
DEBUG:yowsup.layers.axolotl.layer:Generating Signed PreKey
Segmentation fault

**Comment by zoqui** [comment]
I´m also facing issues to receive encrypted messages:

$python yowsup-cli demos -c config.cfg -e -m
...
yowsup-master/yowsup/layers/axolotl\layer.py", line 245, in onSentKeysError
    raise Exception("Sent keys were not accepted")
Exception: Sent keys were not accepted

====
when trying to receive messages without -m flag I got as result:
...
yowsup-master/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

===
debugging it I see there is no such child node (body) but "enc",
I´ve tried to replace node.getChild("body") to node.getChild("enc") but it does not echo a decrypted message

**Comment by tgalal** [comment]
@zoqui which python version are you using ?

**Comment by zoqui** [comment]
Hi and thank you!
Python version 2.7

Trying now to implement a simple echo with Axolotl layer, but I´m not sure how to build the session.

Response from 
axolotl\sessioncipher.py", line 65, in decryptMsg 
axolotl.nosessionexception.NoSessionException: No session for: 5519991042827, 1

**Comment by Udirley** [comment]
I redid the test using Python3.3 but the same problem occurs.

python3.3 /usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config.teste-C -e -m
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Segmentation fault

Agradeço qualquer ajuda.

**Comment by abhiramnarla** [comment]
Is the problem still there? If not, how did you resolve it? 

Thank you.
