### ISSUE TITLE
Send emoji through yowsup-cli

### ISSUE THREAD

**Issue by Pedro-H-Fialho** [tgalal/yowsup#529]
How am I supposed to use the Emotions unicode when sending a message

I took the unicode from http://apps.timwhitlock.info/emoji/tables/unicode

And tried
**yowsup-cli demos -l phobe:b64pass -s phone UNICODE**

But I receive it in plain text.

Thanks in advance.
##

**Comment by kuldippatel** [comment]
Please use SoftBank codes from this page : code.iamcal.com/php/emoji/

**Comment by Ipystar** [comment]
@kuldippatel Did you try out what you just suggested? It doesnt work

**Comment by tgalal** [comment]
At the moment yowsup-cli is not meant to be used for sending emoji. But I'll leave this issue open as a reference in case it gets implemented, I've updated the issue title as well

**Comment by kuldippatel** [comment]
I had used it in legacy code.

Sample code.

finalMsg= msg+ u'\ue058'

**Comment by tgalal** [comment]
@kuldippatel yes it should work fine from code, sending from command line using yowsup-cli is a diff thing in this scenario

**Comment by CODeRUS** [comment]
just add two commands in cli:
"/:)" - semd smile emoji
"/:(" - send sad emoji
or so :D

**Comment by dedmen** [comment]
You could replace some stuff code side but that wont be a general solution to the Problem. You can add some Emojis but not every single one... Well you could but you get the point.
I did something like that to be able to send NewLine by replacing all "###" with "\n"

**Comment by kuldippatel** [comment]
Hey, 
it is not working from the code.  Can somebody share a sample snippet? I am getting an exception.

**Comment by kuldippatel** [comment]
@tgalal  Sorry Tarek for duplication. Thanks for closing it.

**Comment by sinanm89** [comment]
I am unable to send smileys, I get the error;
```
File "/Users/sbot/Documents/projects/Sbot/yowsup/structs/protocoltreenode.py", line 69, in toString
    out += "\nHEX:%s\n" % binascii.hexlify(self.data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ue058' in position 16: ordinal not in range(128)
```
while trying to send `text_msg = u"*slow clap* ... \ue058"` I tried to use 
`text_msg = "*slow clap* ... \ue058"` but it sends the literal text not the emoticon. Anyone know how?

**Comment by Dl0tt** [comment]
you have to encode it, like so:

text_msg = "*slow clap* ... \ue058".encode("utf-8")

-------- Original Message --------
