### ISSUE TITLE
bad param id

### ISSUE THREAD

**Issue by darw1b** [tgalal/yowsup#532]
Hi guys! New yowsup is awesome! But sometimes I've got a problem like this:
I've got a sms, but when i try to enter it, i receive an error:

-bash-4.1$ yowsup-cli registration --register 290117 --debug --phone 3809348335XX --cc 380
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=380&in=9348335XX&id=%A8%8A%7C%D0%EF%01%1A%AB%80%02%19%0A&code=290117
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=380&in=9348335XX&id=%A8%8A%7C%D0%EF%01%1A%AB%80%02%19%0A&code=290117
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"}

status: fail
reason: bad_param

What's that error means? 
Best Regards

**Comment by tgalal** [comment]
Which python version ? And you say sometimes? Does it not always happen ?

**Comment by darw1b** [comment]
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2

Not always, 5%. If you need, I can give you more examples

**Comment by tgalal** [comment]
Yeah a couple of more invalid ids would be helpful. Thanks for the info!

**Comment by darw1b** [comment]
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'} DEBUG:yowsup.common.http.warequest:cc=380&in=934590674&id=%90H%CF%F3%E1%5C%0A&code=360757 DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=380&in=934590674&id=%90H%CF%F3%E1%5C%0A&code=360757 INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"} status: fail reason: bad_param

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'} DEBUG:yowsup.common.http.warequest:cc=380&in=934594012&id=%0A&code=600957 DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=380&in=934594012&id=%0A&code=600957 INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"} status: fail reason: bad_param

**Comment by blu3bird23** [comment]
same here.
Python 2.7.6 (default, Sep  9 2014, 15:04:36) (Mac OS X 10.10.1)

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=49&in=1764xxxxx88&id=m%00e%04%7B%BC%F8w%E4-%18%0A&lg=en&lc=GB&token=MJoUTBb5O7uKlrvy9I%2Fzg5MCpS4%3D
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=49&in=1764xxxxx88&id=m%00e%04%7B%BC%F8w%E4-%18%0A&lg=en&lc=GB&token=MJoUTBb5O7uKlrvy9I%2Fzg5MCpS4%3D
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"}

**Comment by darw1b** [comment]
last one
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'} DEBUG:yowsup.common.http.warequest:cc=79&in=030119867&id=%FE%0A&code=325647 DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=79&in=030119867&id=%FE%0A&code=325647 INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"} status: fail reason: bad_param

**Comment by tgalal** [comment]
thanks!, the failing requests output you posted really helped. I added a bugfix which I think would take care of it, are you able to confirm? @darw1b @blu3bird23

**Comment by blu3bird23** [comment]
you have to request a new code. But works like a charm now. Thanks for your work!
