### ISSUE TITLE
Earth to Tgalal: I think you have a problem

### ISSUE THREAD

**Issue by iipystar** [tgalal/yowsup#535]
Sincerly I think tgalal has a problem, funny enough it might even be mental. For someone who is the author of an opensource project that can not seem to handle any views he feels are dissenting is really childish. I said i was writing a tutorial for newbies to this library and that WARRANTED A BAN? Whats your problem? Guido, DHH and other programming GODS arent as vain and immature as you are. And see how big their "babies" have become.
You really need to work on yourself and grow up because you can not shape the world in your own image.

P.S: I know you are going to ban me again and block me from the repository, I dont care anymore. I have even lost interest in this hopeless library because of your FUCKED UP ATTITUDE. I am moving over to WHATSAPI so who cares what you do anymore.

**Comment by mgp25** [comment]
@iipystar get a life man. So you only show your childish attitude and ignorance. I wont help you in WhatAPI. @tgalal is my mate.

I wont give you support

**Comment by iipystar** [comment]
@mgp25 go fuck yourself. I will use whatapi whether you like it or not. You have no say over that. Moreover I don't need your help faggot. I am waiting for @coderus to jump on this thread too. All of you are faggots. Whatsapi is open source and I will use it, so get over it. 
@tgalal pls block me again. I am waiting
