### ISSUE TITLE
the upload image sample code is not working for me...

### ISSUE THREAD

**Issue by andrewsub** [tgalal/yowsup#538]
Hi everybody,

I tried to use the sample code from here: https://github.com/tgalal/yowsup/wiki/Yowsup2:-Upload-and-send-Media but nothing happens - no errors and the image is never sent.

On the other hand, I do succeed to upload images from the demo cli. what do I do wrong?

layer.py

from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.auth import YowAuthenticationProtocolLayer
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
import sys
from yowsup.common import YowConstants
import datetime
import os
import logging
from yowsup.layers.protocol_receipts.protocolentities    import *
from yowsup.layers.protocol_groups.protocolentities      import *
from yowsup.layers.protocol_presence.protocolentities    import *
from yowsup.layers.protocol_messages.protocolentities    import *
from yowsup.layers.protocol_acks.protocolentities        import *
from yowsup.layers.protocol_ib.protocolentities          import *
from yowsup.layers.protocol_iq.protocolentities          import *
from yowsup.layers.protocol_contacts.protocolentities    import *
from yowsup.layers.protocol_profiles.protocolentities    import *
from yowsup.layers.protocol_chatstate.protocolentities   import *
from yowsup.layers.protocol_privacy.protocolentities     import *
from yowsup.layers.protocol_media.protocolentities       import *
from yowsup.layers.protocol_media.mediauploader import MediaUploader
from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
from yowsup.layers.axolotl import YowAxolotlLayer

class MyYowsupApp(YowInterfaceLayer):

    def requestImageUpload(self, imagePath):
        self.demoContactJid = "12345...@s.whatsapp.net" #only for the sake of simplicity of example, shoudn't do this
        self.filePath = imagePath #only for the sake of simplicity of example, shoudn't do this
        requestUploadEntity = RequestUploadIqProtocolEntity("image", filePath = imagePath)
        self._sendIq(requestUploadEntity, self.onRequestUploadResult, self.onRequestUploadError)

    def onRequestUploadResult(self, resultRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
        mediaUploader = MediaUploader(self.demoContactJid, self.getOwnJid(), self.filePath,
                                      resultRequestUploadIqProtocolEntity.getUrl(),
                                      resultRequestUploadIqProtocolEntity.getResumeOffset(),
                                      self.onUploadSuccess, self.onUploadError, self.onUploadProgress)
        mediaUploader.start()

    def onRequestUploadError(self, errorRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
        print("Error requesting upload url")

    def onUploadSuccess(self, filePath, jid, url):
        #convenience method to detect file/image attributes for sending, requires existence of 'pillow' library
        entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, None, to)
        self.toLower(entity)

    def onUploadError(self, filePath, jid, url):
        print("Upload file failed!")

    @ProtocolEntityCallback("success")
    def onSuccess(self, entity):
        self.connected = True
        print "Logged in!"
        self.requestImageUpload("C:\\someimage.jpg")

run.py:

import threading
from layer import MyYowsupApp
from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS
from yowsup import env
from yowsup.demos.cli.layer import YowsupCliLayer

CREDENTIALS = ("9876...", "somepass") # replace with your phone and password
if __name__==  "__main__":
    layers = (
        MyYowsupApp,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
    ) + YOWSUP_CORE_LAYERS

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
    
    target=stack.loop

**Comment by andrewsub** [comment]
I have found the problem:
I did this:
	layers = (
	MyYowsupApp,
	(YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
	) + YOWSUP_CORE_LAYERS

instead of this:
	layers = 
	        (MesajeraLayer,) +\
            (YOWSUP_PROTOCOL_LAYERS_FULL,) +\
            YOWSUP_CORE_LAYERS

YOWSUP_PROTOCOL_LAYERS_FULL holds in it: YowMediaProtocolLayer

**Comment by tomatensuppe** [comment]
can you post you full running code ??????

**Comment by tomatensuppe** [comment]
what is MesajeraLayer ?
