### ISSUE TITLE
Installation on Windows with mingW32 gives chmod error

### ISSUE THREAD

**Issue by coursera125** [tgalal/yowsup#540]
I  am using Python 3.4 on Windows 7. I am trying to install Yowsup with mingW32 compiler but it gives me following error:

File "setup.py", line 273, in run
RuntimeError: chmoderror

Any help is appreciated.
Thanks

**Comment by tgalal** [comment]
Is it by any chance the same error mentioned in the [installation instructions for windows](https://github.com/tgalal/yowsup#windows) ?

**Comment by coursera125** [comment]
Hey, thanks for reply.
yes it is same error but when I trying to install PyCrypto with pip separately it gives the same chmod error

**Comment by tgalal** [comment]
If I remember correctly the only way I got it to work on Windows is using easy_install (pip did not work) with that url
 > easy_install http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe

It's not working for you?

**Comment by CharlesOkwuagwu** [comment]
no luck either

**Comment by coursera125** [comment]
I have python 3.4 and there is no binaries available for python34

**Comment by tgalal** [comment]
how about [this](https://github.com/axper/python3-pycrypto-windows-installer) ?

**Comment by coursera125** [comment]
Hey thanks lot.
it finally works. I am able to install yowsup.
