### ISSUE TITLE
Activation fails with no apparent reason

### ISSUE THREAD

**Issue by mateidumitru** [tgalal/yowsup#541]
This is what yowsup-cli returns when I run "python yowsup-cli -c config --register 681-511 --debug".

```
{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
cc=40&in=72xxxxxxx&id=d41d8cd98f00b204e9800998ecf8427e&code=xxxxxx
Opening connection to v.whatsapp.net
Sending GET request to /v2/register?cc=40&in=72xxxxxxx&id=d41d8cd98f00b204e9800998ecf8427e&code=xxxxxx
WARegRequest:   {"status":"fail","reason":"missing"}

status: fail
reason: missing
```

**Comment by tgalal** [comment]
can you try update to latest version? this looks like and outdated yowsup version to me.

**Comment by mateidumitru** [comment]
This actually shipped with breakbot, which might not be compatible with the latest yowsup. I'll give it a go and see if it works.

**Comment by mateidumitru** [comment]
```
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=40&in=727647619&id=X%0A&code=681511
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=40&in=727647619&id=X%0A&code=681511
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"id"}

status: fail
reason: bad_param
```
This is what the latest version of yowsup spits out when running 
    python yowsup-cli registration -R xxxxxx --mcc 226 --mnc 01 --phone 4072xxxxxxx --cc 40 --debug

**Comment by tgalal** [comment]
hold on

**Comment by tgalal** [comment]
I've submitted a potential fix, can you please try latest source and post result ?

**Comment by mateidumitru** [comment]
Sure thing, hold on.

**Comment by tgalal** [comment]
you don't need to request another code I think, did you try register with same code ?

**Comment by mateidumitru** [comment]
Yup, complains about a 'mismatch'. The code is a few hours old already, that might be it.

**Comment by tgalal** [comment]
ok then, thanks for your help, would be great if you post here if it worked, then close the issue if so :)

**Comment by mateidumitru** [comment]
The fix did indeed work. Thank you.
