### ISSUE TITLE
Store and use next challenge

### ISSUE THREAD

**Issue by MostafaBalata** [tgalal/yowsup#547]
In which file i can find the challenge key?
##

**Comment by tgalal** [comment]
what challenge key?

**Comment by MostafaBalata** [comment]
I mean the Next challenge key.. where is it stored?

**Comment by tgalal** [comment]
not storing any challenge keys

**Comment by CODeRUS** [comment]
o_O wtf?

**Comment by tgalal** [comment]
yet. lol.  I'll  close this when it's added
