### ISSUE TITLE
yowsup-cli /disconnect causes an error

### ISSUE THREAD

**Issue by viksit** [tgalal/yowsup#548]
It appears that the asyncore loop is somehow not getting terminated correctly?

```
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!

[connected]:/Disconnect

Traceback (most recent call last):
[connected]:  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1621, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline

  File "build/bdist.macosx-10.9-x86_64/egg/yowsup/demos/cli/stack.py", line 42, in start
  File "build/bdist.macosx-10.9-x86_64/egg/yowsup/stacks/yowstack.py", line 49, in loop
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
select.error: (9, 'Bad file descriptor')
```
##

**Comment by tgalal** [comment]
Should be fixed, can you confirm ?

**Comment by omarfuzzer** [comment]
Hi I have this problem when installing dependencies from windows

C: \ Python27 \ Scripts> easy_install python-axolotl-curve25519
Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Best match: python-axolotl-curve25519 0.1
downloading https://pypi.python.org/packages/source/p/python-axolotl-curve25519/
python-axolotl-curve25519-0.1.tar.gz # md5 = f28d902df9044f0bf86a35a4bd2ec092
Processing python-axolotl-curve25519-0.1.tar.gz
Writing c: \ users \ fuzzer \ appdata \ local \ temp \ easy_install-u6pbjp \ python-axolotl-cu
rve25519-0.1 \ setup.cfg
Running python-axolotl-curve25519-0.1 \ setup.py -q bdist_egg --dist-dir c: \ users \
fuzzer \ appdata \ local \ temp \ easy_install-u6pbjp \ python-axolotl-curve25519-0.1 \ Egg-
dist-tmp-8_oozs
curve25519module.c
curve25519module.c (76): error C2143: syntax error: missing ';' before 'type'
curve25519module.c (78): error C2065: 'result': undeclared identifier
curve25519module.c (82): error C2143: syntax error: missing '{' before '*'
curve25519module.c (100): warning C4133: 'return': incompatible types - from 'P
yObject * 'to' int * '
curve25519module.c (146): warning C4133: 'initializing': incompatible types - f
rom 'int * (__ cdecl *) (PyObject *, PyObject *)' to 'PyCFunction'
error: Setup script exited with error: command 'C: \\ Users \\ AppData \\ \\ fuzzer Loca
l \\ Programs \\ Common \\ \\ Microsoft Visual C ++ for Python 9.0 \\ \\ \\ Bin \\ VC cl.exe 'fai
led with exit status 2

C: \ Python27 \ Scripts>.

thanks for your help

**Comment by luckydonald** [comment]
Is not fixed. Mac OS 10.9.5, Python 3.4.2, 321d0a8..7395da4

**Comment by alexisjk** [comment]
Have same problem :  
Microsoft Visual Studio 10.0\\VC\\BIN\cl.exe' failed with exit status 2

Any Suggestion?

**Comment by viksit** [comment]
@tgalal not fixed yet - tried and same issue.

**Comment by nerble** [comment]
I got this after a spontaneous disconnect, which seems similar:

13: general: Disconnected: Connection Closed 
14: [offline]: 
15: [offline]:[offline]:[offline]:Traceback (most recent call last): 
16:   File "/usr/local/bin/yowsup-cli", line 304, in <module> 
17:     if not parser.process(): 
18:   File "/usr/local/bin/yowsup-cli", line 223, in process 
19:     self.startCmdline() 
20:   File "/usr/local/bin/yowsup-cli", line 249, in startCmdline 
21:     stack.start() 
22:   File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 28, in start 
23:     self.stack.loop(timeout = 0.5, discrete = 0.5) 
24:   File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 162, in loop 
25:     asyncore.loop(*args, **kwargs) 
26:   File "/usr/lib/python2.7/asyncore.py", line 216, in loop 
27:     poll_fun(timeout, map) 
28:   File "/usr/lib/python2.7/asyncore.py", line 145, in poll 
29:     r, w, e = select.select(r, w, e, timeout) 
30: select.error: (9, 'Bad file descriptor')

**Comment by CreatorSky** [comment]
Modify /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py and set the default of use_poll from False to True:

Line 207:

`def loop(timeout=30.0, use_poll=False, map=None, count=None):`

to

`def loop(timeout=30.0, use_poll=True, map=None, count=None):`

and that solved my issue .
Best of luck.
