### ISSUE TITLE
whatsapp can only be installed on one device per phone number

### ISSUE THREAD

**Issue by dlebrecht** [tgalal/yowsup#551]
hi guys, 

i'm trying to use the pidgin whatsapp plugin on my computer AND my android official whatsapp together with the same phone number, but i apparently can't get them working simultaneously on both devices. Whenever i activate one device, the other is disactivated. Then i have to request a new code to be able to reactivate it, and then the password changes etc. The official client on android spells out the error as "whatsapp can only be installed on one device per phone number"

am i missing something? how do people achieve this?

cheers
dl

**Comment by tgalal** [comment]
no one achieves this because it's not possible to sign in with same phone number in 2 places

**Comment by CODeRUS** [comment]
http://www.whatsapp.com/faq/general/21009863
