### ISSUE TITLE
How to use --exists / -e command ?!

### ISSUE THREAD

**Issue by clarityworld** [tgalal/yowsup#554]
Hello I just registerd my phone number and want to login, 

wa_bot.py:138: Auth Failed: invalid

But my Auth failed so I want to check if the password changed somehow...
But I can't get get the  --exists / -e command  to work, all it outprint me is demos , regi , version.

Im very sure I use the right password and number..  It worked fine to create them.
http://puu.sh/eBBXR/afebf9f22b.png

**Comment by tgalal** [comment]
I removed explicit calls to "exists" since it depends on the Id used at registration, which is now generated and not to be stored inside the config anymore.  Instead you need to request code/ sms, and this will implicitly do an 'exists' call before actual request of registration code.
