### ISSUE TITLE
?? WhatsApp threatens legal action against API developers ????

### ISSUE THREAD

**Issue by suraj-mahajan** [tgalal/yowsup#556]
http://www.itnetwerk.com/news/2012/09/27/whatsapp-threatens-legal-action-against-api-developers/

WhatsApp Inc. has, however, been in touch with the developers behind the GitHub project WhatsAPI, an open source implementation of the WhatsApp protocol written in PHP and Python. The company has threatened to take legal action against the developers if they do not take the project offline. heise Security has been told by one of the developers that they have decided to acquiesce to this request and to cease working on the API.

WhatsApp’s ultimatum has not come out of the blue â€“ it was issued shortly after heise Security demonstrated how easy it was to compromise other users’ accounts using the API. This does not, however, alter the underlying problem. There is now a web service based on the API which can be used by an attacker to send and receive messages in the name of a WhatsApp user by simply having their phone number and IMEI or Wi-Fi adapter MAC address. Users are advised against using the service, however, as it is quite possible data allowing permanent access to such an account could fall into the wrong hands.

The way it has dealt with this serious problem does not inspire confidence in the company behind the app, which is used by millions of smartphone owners around the world to send more than one billion messages a day.

**Comment by CODeRUS** [comment]
2012, really?

**Comment by mgp25** [comment]
*sigh...* 

I would recommend to every user to read everything and search before posting it... As @CODeRUS said that info was about 2 years ago.

**Comment by CharlesOkwuagwu** [comment]
Lol @suraj-mahajan did you have an actual question?

**Comment by dedmen** [comment]
This is from the German News from today.
http://www.rtl.de/cms/news/rtl-aktuell/aerger-im-netz-whatsapp-sperrt-tausende-user-fuer-24-stunden-44ac2-51ca-12-2184148.html
translation: https://translate.google.com/translate?hl=de&sl=de&tl=en&u=http%3A%2F%2Fwww.rtl.de%2Fcms%2Fnews%2Frtl-aktuell%2Faerger-im-netz-whatsapp-sperrt-tausende-user-fuer-24-stunden-44ac2-51ca-12-2184148.html&sandbox=1
Which could affect us.

**Comment by mgp25** [comment]
It seems WhatsApp is trying to ban/block users using third party apps, that wont happen at all ;)
