### ISSUE TITLE
How to send read ack?

### ISSUE THREAD

**Issue by cyb3rwin** [tgalal/yowsup#557]
How to send whatsapp read sign to sender, so the sender will know if their message was read.

**Comment by jerryames** [comment]
Second that, trying to find a read signal back to server and sender.

**Comment by cyb3rwin** [comment]
how to do that? i still confused

**Comment by tgalal** [comment]
You need to Send a [OutgoingReceiptProtocolEntity(id, to, read = True)](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_receipts/protocolentities/receipt_outgoing.py)
