### ISSUE TITLE
notification type picture/delete

### ISSUE THREAD

**Issue by dedmen** [tgalal/yowsup#561]
ValueError: Unimplemented notification type 
`<notification type="picture" notify="**" from="***@s.whatsapp.net" id="***" t="***">
<delete jid="***@s.whatsapp.net">
</delete>
</notification>`

**Comment by ant9000** [comment]
I know that protocol implementation is still incomplete: in the meantime it would be possible to just `ack` received nodes before using `self.raiseErrorForNode(node)` - otherwise communication won't go on.

Antonio
