### ISSUE TITLE
How to check when the contact status (the status in text, not /lastseen) was updated?

### ISSUE THREAD

**Issue by jerryames** [tgalal/yowsup#562]
Yowsup is amazing. Solved lots of problem when I deal with customers just after one week I found out about yowsup.

On iPhone, you can click "info" button on a contact and find out when the contacts'  status was updated. Like "It is a wonderful world" 120d23hours ago. It give you a sense that the contact as setup quite sometime and more reliable. How do we get this information on Yowsup. Thanks a million if anyone can help me out on this. :)

**Comment by dedmen** [comment]
When you have synced your contact you will get notifications once they change they status and then you can write down the time when you get the notification. Thats how i do it. Or maybe the Notification iteself includes a Timestamp i cant look it up right now

**Comment by CODeRUS** [comment]
in whatsapp there is sendGetStatuses method.

**Comment by jerryames** [comment]
CODeRUS, I checked into Whatsapi, it is using php and have trouble to input user identify. It seems I have to sniff it from my network or re setup my account. Do we have sendGetStatuses in yowsup?

**Comment by jerryames** [comment]
dedmen, thanks for the reply. hope we can get something like sendGetStatuses to make life easier.

**Comment by tgalal** [comment]
WIP

**Comment by jerryames** [comment]
tgalal, It seem the feature has been added in yowsup. Can you give an example of how to use the new feature? Thank you!

**Comment by jerryames** [comment]
Do we have this feature yet? sendGetStatuses?

**Comment by dedmen** [comment]
We have the feature when this issue/feature request gets closed

**Comment by jerryames** [comment]
OK :)

**Comment by jerryames** [comment]
816 solve the problem of checking last seen. How to get Contact Status? Like it was changed and what is the status, like the response in PHP version: since: 2015-Jul-19 19:09:29 getstatus-1437342675-1, Status: Hey there! I am using WhatsApp.
