### ISSUE TITLE
Is the new official whatapp web interface a gamechanger?

### ISSUE THREAD

**Issue by msshapira** [tgalal/yowsup#565]
[https://blog.whatsapp.com/614/WhatsApp-Web]

WhatsApp Web

Today, for the first time, millions of you will have the ability to use WhatsApp on your web browser. Our web client is simply an extension of your phone: the web browser mirrors conversations and messages from your mobile device -- this means all of your messages still live on your phone.

To connect your web browser to your WhatsApp client, simply open https://web.whatsapp.com in your Google Chrome browser. You will see a QR code --- scan the code inside of WhatsApp, and you’re ready to go. You have now paired WhatsApp on your phone with the WhatsApp web client. Your phone needs to stay connected to the internet for our web client to work, and please make sure to install the latest version of WhatsApp on your phone. Unfortunately for now, we will not be able to provide web client to our iOS users due to Apple platform limitations.

We really hope you find web client useful in your everyday lives.

**Comment by CODeRUS** [comment]
What is your question?

**Comment by msshapira** [comment]
Well, it's almost as if whatapp have published there own API. Almost,
because it relies on a phone being connected

**Comment by CODeRUS** [comment]
It using different API. Web app connected to whatsapp server and talking with your phone, it's asking for contacts and messages on your phone. Using your phone for everything.
