### ISSUE TITLE
"Last seen at" never Updated

### ISSUE THREAD

**Issue by jerryames** [tgalal/yowsup#566]
refer back to https://github.com/tgalal/yowsup/issues/137

I have the same problem, the "last seen at" never updated (still appears to be several days ago when I login on my mobile phone). I have another whatsapp number that never login in mobile and the last seen on that number updated everytime I log in. 

The solution on https://github.com/tgalal/yowsup/issues/137 does not work since I am in Yowsup 2 and those functions disappeared, at least I did not find it.

No sure how to get my main number (after I login back from mobile to yowsup) /lastseen updated. Thank you!

**Comment by jerryames** [comment]
I am on the track of solving the problem. Just not so familiar with yowsup to get the last point. 

I found the code in cli that can set the presence to avaialble

https://github.com/tgalal/yowsup/blob/567c93f6c55baf62b6393baeaea5f30cd196643c/yowsup/demos/cli/layer.py

    @clicmd("Set presence as available")
    def presence_available(self):
        if self.assertConnected():
            entity = AvailablePresenceProtocolEntity()
            self.toLower(entity)

I tried to alter the code given in the sample code 

https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app

I just do not know how to put the code in. It should be simple, Please help.

**Comment by jerryames** [comment]
Well, I got it work by inserting my code into cli. It is centrally not the best way. But it works for now, I am just too new to python, less than an week, and too new to yowsup. If anyone can let me know how to alter the code in https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app, I will really appreciate. 

Lots of to learn in python. I still did not figure out a way to get the contact status update timestamp, refer to https://github.com/tgalal/yowsup/issues/562 . Seem can by done in WhatsAPI with sendGetStatuses method, hope we can get same method in yowsup.

**Comment by tgalal** [comment]
Add to your stack YowPresenceProtocolLayer, so it would be like:

run.py:
```python
from layer import EchoLayer
from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS
from yowsup import env

#### >>>>> PRESENCE STUFF
from yowsup.layers.presence import YowPresenceProtocolLayer
#### <<<<<

CREDENTIALS = ("phone", "password") # replace with your phone and password

if __name__==  "__main__":
#### >>>>> PRESENCE STUFF
    layers = (
        EchoLayer,
        (YowPresenceProtocolLayer, YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
    ) + YOWSUP_CORE_LAYERS
#### <<<<<
    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal

    stack.loop() #this is the program mainloop
```

And send a AvailablePresenceProtocolEntity by adding to layer.py something like:
```python
from yowsup.layers.protocol_presence.protocolentities import AvailablePresenceProtocolEntity

def sendAvailable(self):
    self.toLower(AvailablePresenceProtocolEntity())

```

**Comment by alvariux** [comment]
Just for clarification make sure you add **YowPresenceProtocolLayer** at the beginning of the list because I added to the end and was not working.
