### ISSUE TITLE
Al mandar /L me manda general: Login Failed, reason: not-authorized

### ISSUE THREAD

**Issue by RaulCer** [tgalal/yowsup#567]
Hola, estoy tratando de hacer una prueba con los demos /yowsup/yowsup/demos$ yowsup-cli demos --yowsup --config config, pero al mandarle el /L me arroja el siguiente error:
[offline]:/L
general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

Este es mi archivo de configuracion:
cc=52
phone=52xxxxxxx
id=
password=7r67AFGe6wI0zngrP7htnKHU0UQ=

Como puedo corregir esto?

Saludos

**Comment by mgp25** [comment]
@RaulCer Try to write in English in order to people could understand and help you, also writing in English will help other people with the same issue as you.

`not-authorized` means your number is blocked.

Regards

**Comment by tgalal** [comment]
@mgp25 Or incorrect password, right?

**Comment by mgp25** [comment]
@tgalal true

**Comment by XaKaX** [comment]
Why would a number get blocked? Is there a way of restoring it?
I've got the same problem. It was working perfectly and suddenly stopped. Is there a way to re-register?

**Comment by RaulCer** [comment]
Hi, Since I resolved detail, my country code is 55 (mexico), di high number like this: 55 + cell number, but in my config file I put it like this: 551 + phone number, just put that one before cell number, so do not check error.
Greetings.

**Comment by jroman** [comment]
Sorry, but I can not understand... Could you please explain if you solved the problem and how?

Perdón, pero no entiendo tu respuesta: Podrías explicar si lo resolviste y cómo? 

GRACIAS!

**Comment by tierra721** [comment]
hi  my friends , i dont speak english but  will be try,,,,
i install yowsup  but when i try send message , the system showme ...

yowsup-cli demos -s 528661303006 "hola gay" -c config.exa
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Authentication Error: not-authorized

my config.exa=

cc = 52
phone = 528661303006
id =
password = MuwMFqpXCSFcQOxjDwcqhBCQ2a0=

can you helpme

**Comment by carlosdiaz** [comment]
@tierra721  Publicaste información privada , ahora cualquiera puede enviar mensajes con tus datos, no estoy seguro si puedes editar tu comentario pero si puedes borra tu telefono y password, con respecto a tu error te recomiendo que descargues la ultima version de yowsup e intentes nuevamente

**Comment by jlguardi** [comment]
Prueba a registrar de nuevo tu número, debes tener mal la contraseña o has sido bloqueado. Durante este proceso te dice 'bloqued' si te ha bloqueado whatsapp por algún motivo

**Comment by RaulCer** [comment]
Agrega un uno despues del 52
para Mexico es 521XXXXXXXXXX

Saludos

**Comment by Alej89** [comment]
I have the same error, and I could not fix it. Does anyone know how to login, using the /login command?? (not using the quick login command /L)

**Comment by dacasti2** [comment]
by adding 1 on my config file solved the same problem reported here. thank you.
l0k1@l0k1:~/yowsup$ more config 
## Actual config starts below ##
  cc=52 #if not specified it will be autodetected
  phone=521554xxxxxx6  # HERE I ADDED 1 after 52
  password=PASSWORD=
