### ISSUE TITLE
Trouble writing yowsup echo client

### ISSUE THREAD

**Issue by pjepper** [tgalal/yowsup#570]
I am attempting to make a yowsup sample app by following the directions on this page:

https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app

When I run 'run.py' in the command line I get this error message:

Traceback (most recent call last):
  File "yowsup.py", line 1, in <module>
    from layer import EchoLayer
  File "/Users/PJ/Desktop/layer.py", line 1, in <module>
    from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
  File "/Users/PJ/Desktop/yowsup.py", line 1, in <module>
    from layer import EchoLayer
ImportError: cannot import name EchoLayer

Am I missing a step?  
##

**Comment by erhan-** [comment]
I have just copy pasted the two files and ran it and it worked without a problem. Did your forget layer.py?

**Comment by tgalal** [comment]
@pjepper did you?

**Comment by pjepper** [comment]
@erhan, I copy and pasted layer.py and saved it.  Then I copy and pasted run.py, and saved it.  then I ran run.py.  

Am I supposed to copy and paste layer.py in run.py?

i dont quite follow you when you say 'i copy and pasted the two files and ran it'.

**Comment by erhan-** [comment]
I did it the same way as you actually pjepper.
