### ISSUE TITLE
Auth Failed for existing number and no_route for registering new numbers?

### ISSUE THREAD

**Issue by kuldippatel** [tgalal/yowsup#571]
Is Auth token expired? Nothing is working.
##

**Comment by emamirazavi** [comment]
Also for me!!! What's the matter?!

**Comment by dedmen** [comment]
Whatsapp is going offensive against WhatsApp+ and other custom Clients. Today i got an Whatsapp update maybe they changed the registration process to tackle custom Clients.

**Comment by CODeRUS** [comment]
No, i think it's just pigs fly.

**Comment by emamirazavi** [comment]
Hey! Probably this would be the response of tgalal! Yes, I was using 0.9
version and when I tested 2.x.x version problem incredibly was solved! What
is the main difference between 0.9 and 2.x.x?!

**Comment by CODeRUS** [comment]
@emamirazavi https://github.com/tgalal/yowsup#whats-new-in-yowsup-2

**Comment by kuldippatel** [comment]
Yeah, Legacy code stopped working suddenly. The above page has generic comments. Looking for specific reasons why it is not working with legacy code and works with 2.0.

**Comment by tgalal** [comment]
Legacy code is outdated, because I stopped updating it

**Comment by emamirazavi** [comment]
My serious project now is down and no one can help me! Tarek PlZ give me some solutions to debug version 0.9 and give multi connection(several clients) feature to version 2.X,
Many thanks,

**Comment by kuldippatel** [comment]
emamirazavi. Why do you need multiple connections? How many numbers/connections are allowed from one IP?

**Comment by biji** [comment]
Tried to change token to this:
https://github.com/tgalal/yowsup/commit/ecca9071bd1af5514df0f5d7fc37fe3c00d6602e
but also no route

only registering failed, but sending message no problem

I hope someone can fix this :)
