### ISSUE TITLE
sending a message to a group?

### ISSUE THREAD

**Issue by h1rule** [tgalal/yowsup#573]
hello,

i was trying to send a message to a whatsapp group, the "yowsup bot" is already added to it.
im using this cmd to send it, "message sent" but no message arrives in the whatsapp group on the phone.

yowsup-cli demos --config bot.conf -s 49xxxxxxxx-xxxxxxxxx "this is my message"
##

**Comment by capsload** [comment]
Ok. Figured that out too,

/message send 49xxxxxxx-1xxxxxx@g.us "challo"

sends the message to the group,
but only if i start yowsup with -y and then /L.

Anyway to do it without logging in? straight as command? just like ./yowsup-cli demos -s number text ?

**Comment by amiralhe** [comment]
Hello capsload,

you need to adjust the layer.py the sendclient for send to group

In the pull request queue already exists correction, need only wait for the update.

att,

**Comment by tgalal** [comment]
@capsload the send demo required appending @g.us to the group ID, now it's fine though, can you confirm? Something like this should work:
 >  yowsup-cli demos -c configs/config.txt -m -s xxxxxxxxxx-xxxxxxxxxx "Hello world"

**Comment by amiralhe** [comment]
Perfect Thanks Tarek.

Att,

**Comment by pickfire** [comment]
How do I know which member of the group send a messages?

**Comment by idigevian** [comment]
Just reviving the question from pickfire.

How do we know who has sent a message in the group ? i..e if we need to send different individual response to the person replying in the group then how can that be achieved ?

**Comment by idigevian** [comment]
Got it: messageProtocolEntity.getParticipant() will do the work!!
