### ISSUE TITLE
Whatsapp messages on Pi-Lite

### ISSUE THREAD

**Issue by suui007** [tgalal/yowsup#578]
Dear Tarek,
Thanks for the great programm.
We are working on a project in which the raspberry pi is supposed to read out the received whatsapp messages and print them on a Pi-Lite Matrix LED Panel. We have come to the point where we are searching for the function, where the actual received message is printed in the console and we can't find it. Where can we actually receive the body of the message?
Could you please help us out?
Thank you in advance!

Vy

**Comment by suui007** [comment]
Sorry. We have found the problem :) Your layers are totally fine :)
You are awesome, we were stupid :)

**Comment by tgalal** [comment]
no worries ;)
