### ISSUE TITLE
Error in  register new number for sending message

### ISSUE THREAD

**Issue by abbas224252** [tgalal/yowsup#58]
On Monday i have register 5 number its working . But when i try to register  today i get this error . 
Please help me .

C:\Python27\python.exe C:/Python27/yowsup/yowsup-cli -c config -r sms
status: fail
param: number
reason: bad_param

Process finished with exit code 0

**Comment by mohande3** [comment]
hi
i from iran
my number :  9399172443
code my countery :  98
i try every time , it is error Bad Parramtr
i dont know my number ? 
please help me ....

**Comment by jlguardi** [comment]
@mohande3 I've sent to you a registration sms without problems. Use s40 env due to Android env requires/uses other params for registration.
```
./yowsup-cli registration -r sms -d -p 9893xxxxxxx -C 98 -d
```

Use env_s40.py with version 2.16.11 and TOKEN="PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"

**Comment by mohande3** [comment]
i use this method from whatsAppAPI : 
WhatsAppApi.Register.WhatsRegisterV2.RequestCode(txtNumberPhone.Text.Trim()
                , out password, out request, out response, out error, "sms")
but this not work . 
help me to correction my error , 
thanks

**Comment by jlguardi** [comment]
Here we just manage tgalal/yowsup issues. Please, post the issue to the correct github.

**Comment by mohande3** [comment]
i dont found correct post , i have to
