### ISSUE TITLE
Echoclient stops working after a while (~1 hour) reconnect/keepalive?

### ISSUE THREAD

**Issue by mode2k** [tgalal/yowsup#583]
Hi,
i tried the demo program echo client. In the first moment it absolutely works as designed. But when its idle for a while (one hour or so) its not working anymore.
It does not send receipts oder replys the messages. In log layer i can not see anything. Even not a disconnect.

Is there a keepalive or reconnect i can use to keep the connection established? 

Regards

Mode

**Comment by tgalal** [comment]
see #429
