### ISSUE TITLE
1.How to get PushName    AND  2. How to get credentials in cli.py ?

### ISSUE THREAD

**Issue by kuldippatel** [tgalal/yowsup#584]
1. Any idea how to get whatsapp profile name of the sender?  messageProtocolEntity.getName() does not help.

2. How to access the phone number of the current config in cli.py?  Was not able to do getProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS) in this file.

**Comment by tgalal** [comment]
1- through messageProtocolEntity.getNotify()
2- cli.py is responsible for parsing command input, so ideally should have nothing to do with actual yowsup stuff. You can get this properties from the actual interface layer (layer.py in case of cli demo), through self.getProp, or self.getOwnJid()
