### ISSUE TITLE
notification with type='web' produce an exception

### ISSUE THREAD

**Issue by jlguardi** [tgalal/yowsup#585]
I've recieved an exception from protocol_notification/layer.py +39
```
def recvNotification(self, node):
        if node["type"] == "picture":
            ....
        else:
            self.raiseErrorForNode(node)
```

due to notification of type 'web'. Obviously it is no managed on this function and I've fixed this issue adding:
```
      if node["type"] == "web
            pass
```

However, I'd like to manage it properly so I need to know what does it mean. Does somebody know?

**Comment by erhan-** [comment]
These are part of the new Web functionality at: https://web.whatsapp.com/
I had this same "issue" yesterday when i tried it out for the first time.
