### ISSUE TITLE
whatsapp is free for end-users or not ?

### ISSUE THREAD

**Issue by shirishag75** [tgalal/yowsup#594]
Hi all, 
This is probably off-topic to the client per-se but these are the details I got :-

    $yowsup-cli registration --register xxx-xxx --phone 91xxxxxxxxx --cc 91
    INFO:yowsup.common.http.warequest:{"status":"ok","login":"xxxxxxxxxx","pw":"somepassword","type":"new","expiration":1453993755,"kind":"free","price":"\u20b9 55","cost":"55.00","currency":"INR","price_expiration":1425460676}
    
    status: ok
    kind: free
    pw: xxxxxxxxxxxxxxxxxx
    price: ₹ 55
    price_expiration: 1425460676
    currency: INR
    cost: 55.00
    expiration: 1453993755
    login: xxxxxxxxxxx
    type: new

Can anybody tell what the cost thing is about.

**Comment by CODeRUS** [comment]
Are you kidding me? http://www.whatsapp.com/faq/general/23014681

**Comment by shirishag75** [comment]
@CODeRUS thank you for clearing that up, my bad.
