### ISSUE TITLE
Howto Get profile picture for contact

### ISSUE THREAD

**Issue by jroman** [tgalal/yowsup#598]
Hi,

Using the demo.cli I tryied to get the profile picture with the command

`/contact       picture [jid]
`

but did not get any result, or did not know how to get it.

Any guide about how to get the picture?

Thanks.

**Comment by jroman** [comment]
Hi,

sorry, but... I still not find the contact profile picture...

Thanks!

**Comment by davidpaulrosser** [comment]
I can see the response coming through when logging is turned on. How can we subscribe to the callback?

**Comment by davidpaulrosser** [comment]
Figured it out,

1. First import the **YowProfilesProtocolLayer**.
2. Add it to your stack

```
layers = (
			YowsupLayer,
			(YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowChatstateProtocolLayer, YowProfilesProtocolLayer),
			YowLoggerLayer,
			YowCoderLayer,
			YowCryptLayer,
			YowStanzaRegulator,
			YowNetworkLayer
		)
```

3. Then in your custom yowsup layer add:

```
@ProtocolEntityCallback("iq")
	def onIq(self, entity):
		print '[YowsupLayer::iq] -->', entity
```

**Comment by jroman** [comment]
Hi,

I have just updated to the latests commits. Any advance in this issue?
I still do not find where the contact picture is stored when received...

Thanks!

**Comment by tgalal** [comment]
@jroman 
- [How to get picture](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L179)
- [How to store received picture data in callback]
(https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L487)

**Comment by jroman** [comment]
So great. Thanks a lot.
