### ISSUE TITLE
network layer: Disconnected, reason: Connection Closed

### ISSUE THREAD

**Issue by emamirazavi** [tgalal/yowsup#599]
I want to listen for several accounts. What is your solution?! In 0.9 i just called connection manager for several accounts with their configurations and i had no problem(Each connection run in it's own thread). Now, in current version 2.x.x, How can i listen for several accounts without using threading? I've read that asyncore can handle several channels to protect from problems of using threading. 
How can i implement this feature for asyncore.loop(*args, **kwargs) or in fact for self.stack.loop()?
Many thanks in advance,

@see https://docs.python.org/2/library/asyncore.html
"If your operating system supports the select() system call in its I/O library (and nearly all do), then you can use it to juggle multiple communication channels at once; doing other work while your I/O is taking place in the “background.” Although this strategy can seem strange and complex, especially at first, it is in many ways easier to understand and control than multi-threaded programming. The asyncore module solves many of the difficult problems for you, making the task of building sophisticated high-performance network servers and clients a snap. For “conversational” applications and protocols the companion asynchat module is invaluable."

**Comment by emamirazavi** [comment]
I tested threading for each new YowStack but each new one disconnects another one!!!
and network layer tells me: Disconnected, reason: Connection Closed
How can i handle several socket connection for several WA clients?!

**Comment by tgalal** [comment]
At the moment the same yowsup instance (both yowsup2 and legacy) cannot handle multiple connections, regardless of asyncore stuff. Might be something to consider in the future though, but there are much higher priority stuff at the moment.

**Comment by emamirazavi** [comment]
Tgalal PLZ guide me to develop and add this feature. I can!!!

**Comment by yniv** [comment]
@emamirazavi Does this work now? have you implemented it????

**Comment by yniv** [comment]
@tgalal is there a solution for it? what should be done?

**Comment by jodersus** [comment]
Have you tried multiprocessing instead of threading? threading shares memory space while multiprocessing doesn't. Just a guess...
