### ISSUE TITLE
AttributeError: YowNetworkLayer instance has no attribute 'out_buffer' - when sending from a new layer

### ISSUE THREAD

**Issue by mp3il** [tgalal/yowsup#602]
Hi all
im getting
AttributeError: YowNetworkLayer instance has no attribute 'out_buffer'

when im trying to send a message from a new layer i have added just above the echo client

i want 2 layers, one to echo messages, and another to expose a method to send a message to a jid.

any ideas what im doing wrong?
##

**Comment by tgalal** [comment]
Can you post some code ?
