### ISSUE TITLE
Background and debug mode

### ISSUE THREAD

**Issue by tobasrisch** [tgalal/yowsup#605]
Hello everyone,
I'm trying to run echoclient example in the background, even when I've logged out.
I've tested it with nohup and screen, but in less than 15min the example doesn't echo anymore.
It seems Whatsapp server drops the connection.

I've tried to enable the debug as @tgalal wrote in his help page, but I think I'm doing something wrong because nothing is displayed. 
I've just modified *run.py* code adding **YowLoggerLayer** as this:

    ...
    if __name__==  "__main__":
        layers = (
                EchoLayer,
                (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowLoggerLayer,
                YowNetworkLayer
            )
    ...

But nothing but the echo is displayed on screen.

Is there a way to see what yowsup is sending or receiving to/from Whatsapp to know why in this example the connection is dropped?

Thank you!

**Comment by eternautaCAT** [comment]
Note that the output of YowLoggerLayer deppends on where you place the layer.

Anyway, maybe you should try to make ping (see /ping in the yowsup-cli) every few seconds for mantain the connection alive.

**Comment by tgalal** [comment]
this is very likely because of #429

**Comment by tgalal** [comment]
#429 was fixed, please reopen if it didn't take care of the problem for you
