### ISSUE TITLE
Paste function -e (echo) duplicate

### ISSUE THREAD

**Issue by cablack** [tgalal/yowsup#606]
Dear, I am testing the response function (-e) as follows:

yowsup-cli demos -c yowsup-cli.config -e

But when sending a response coming from a device the application receives the message and the smartphone that sent the message receives a copy.

Does anyone know how to stop it?

Sorry my English is google

**Comment by eternautaCAT** [comment]
Don't use the "-e" if you don't want send a copy.

Just use yowsup-cli demos -y -c yowsup-cli.config and then type in the command line "/L" (without quotes) and press Enter.

Then you can type "/help" and see others useful commands.

**Comment by tgalal** [comment]
Echo demo is supposed to "echo" messages back,  so no problem here.
