### ISSUE TITLE
no_routes... again

### ISSUE THREAD

**Issue by darw1b** [tgalal/yowsup#607]
Hi guys! Old error coming back! I'm using the latest yowsup. Now, when I wanna register new Russian, Ukranian numbers I always get 

status: fail retry_after: 3600 reason: no_routes

Does anybody got the same?

**Comment by lhgomes** [comment]
Same problem here. Numbers of carrier Entel from Chile.

**Comment by catch2patch** [comment]
same here..

**Comment by DagoW** [comment]
I don't know if it's related; I had many failures today
when I tried to connect with yowsup-cli demos -y.
Eventually it worked, but it took several minutes of retrying
before I got ...
[connected]:
(Using cc=972)

**Comment by aesedepece** [comment]
WhatsAPI and Coseme users are getting ```no_routes``` since yesterday, just like before the last token update, so we should assume that ```WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302``` UA has been already banned.

**Comment by XaKaX** [comment]
Getting no_outes as well!

**Comment by catch2patch** [comment]
are there any news about no_routes problem? 
does it work for anyone or it's completely spoiled?

**Comment by XaKaX** [comment]
@catch2patch I've been trying since yesterday with 3 different numbers, and no lucky. My country code is 55 (Brazil).
Perhaps it's the User Agent as @aesedepece have mentioned.
Any lucky changing it?

**Comment by frenton** [comment]
I just tried registering several new numbers (different providers) using yowsup. Always "no_routes". Then I tried with WART and the code was sent to some numbers, but only for a few providers (no "no_routes" problem). Maybe this information can help.

**Comment by darw1b** [comment]
All right guys, let's check the latest news
It seems to be an identity problem
https://github.com/mgp25/WhatsAPI-Official/issues/341
and WART 1.7.3 is really working good
let's waiting for yowsup
