### ISSUE TITLE
Find out whether contact number has WhatsApp.

### ISSUE THREAD

**Issue by XaKaX** [tgalal/yowsup#609]
From a list of phone numbers (contact list), is there a way of finding out which of them are valid WhatsApp numbers with yowsup-cli demos?

Thanks in advance.

**Comment by dedmen** [comment]
(yowsup-cli demos -y -d)
Request number without whatsapp account:
´´´
[connected]:/presence subscribe 49133373434
DEBUG:yowsup.layers.logger.layer:tx:
<presence to="49133373434@s.whatsapp.net" type="subscribe">
</presence>
 
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<presence type="unavailable" from="49133373434@s.whatsapp.net" last="error">
</presence>
 ´´´
Request number with whatsapp account
´´´
/presence subscribe 491748050***
DEBUG:yowsup.layers.logger.layer:tx:
<presence to="491748050***@s.whatsapp.net" type="subscribe">
</presence>
 
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<presence type="unavailable" from="491748050***@s.whatsapp.net" last="deny">
</presence>
´´´
last can also be a timestamp

**Comment by tgalal** [comment]
Or official way would be through 
 > /contacts sync number1,number2,number3

**Comment by srdavidsilva** [comment]
Hello, how are you?
Sorry reopen the topic, but did not find it anywhere.
Is there any way to do the same direct contact validation linux shell?
Without the need to access the yowsup-cli console?
Thank U

**Comment by dedmen** [comment]
Take a look at https://github.com/tgalal/yowsup/blob/legacy/src/Yowsup/Contacts/contacts.py That may still work and it looks like it could be implemented in Shell

**Comment by tgalal** [comment]
@dedmen that doesn't work anymore. 
@srdavidsilva Only way is through yowsup cli demo at least until me or someone creates a new "sync and exit" demo for that. If interested to implement it, check out [contacts sync](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L292) and [send and exit demo](https://github.com/tgalal/yowsup/tree/master/yowsup/demos/sendclient) as references.

**Comment by srdavidsilva** [comment]
Friends,

Thank you very much!
Unfortunately my knowledge is somewhat limited yet to develop something new
so for now, I'll need a simpler solution to implement and eventually start
working on an improvement for all of us.

You have already validate using this link?
https://v.whatsapp.net/v2/exist?cc=***&in=****

I'm trying but I always have to answer this:
{"status": "fail", "reason", "incorrect", "sms_length": 6, "voice_length":
6}

I imagine you're missing something, just do not know what, yet.

Thanks again for your help.

*David Silva*

2015-02-16 11:38 GMT-02:00 Tarek <notifications@github.com>:

**Comment by dedmen** [comment]
I read that Link now requires your credentials but i dont know the parameter name for them.
You could wait till someone implements a demo for that purpose or.
Start Yowsup-Cli demos -y -d then do /contacts sync and then look at the output and there you should see if it was successful or not and if that number has an whatsapp account.
@tgalal How to differentiate if the sync to a number was successful? i always get the same reply also with numbers which dont have whatsapp.

**Comment by srdavidsilva** [comment]
Thank you friend.
As I understand it, to run the sync in the demo you must register the user
before and subscribe. I guess it's whatsapp same requirement.
To solve this, a way I found is to seek some user data, image type, last
access, etc .. I think with a good combination of these data, take to
verify the existence or not of account on whatsapp.

**Comment by serchmontano** [comment]
Any solution for 2018?
