### ISSUE TITLE
Changing group subject.

### ISSUE THREAD

**Issue by chrisduerr** [tgalal/yowsup#615]
I've seen some example code for changing the subject of a group and tried using it.

<code>entity = SubjectGroupsIqProtocolEntity(messageProtocolEntity.getFrom(), "Only a test")
self.toLower(entity)</code>

I currently placed it in my "onReceive" for being sure it's getting executed while I am connected but it seems like I cannot get it to work...
No errors or anything it just doesn't change the subject.

I have the same problem with the nickname (other issue) and as far as I know, placing these two lines anywhere when i am logged in should make it work, right?

Any thoughts on that?
##

**Comment by UndeadLeech** [comment]
Can anyone tell me if the methods out of the demo client's layer.py work when implementing them yourself?
I tried out SubjectGroupsIqProtocolEntity, PresenceProtocolEntity(name = name) and none of them seem to do anything for me.
Would be very happy if anyone of you knew what's going on. No errors or anything they just don't do stuff.

**Comment by mutindaz** [comment]
I thought it was me alone with the same issue. I can't create a group and I don't get any error.
 entity = CreateGroupsIqProtocolEntity("My Group here") is it not supposed to create a group with the name supplied? 

When i print entity this is what i get.... 
ID: 1
Type: set
xmlns: w:g
to: g.us
where is the group id? If i try to print entity.groupId() I just get 1. 

Anyone who knows the best way to handle this ? I need to create a group and add a participant.
Thanks
