### ISSUE TITLE
Error yowsup

### ISSUE THREAD

**Issue by Alej0m0ren0** [tgalal/yowsup#616]
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
##

**Comment by birdman2005** [comment]
yes it appears again!

**Comment by CODeRUS** [comment]
are you using latest commits?

**Comment by birdman2005** [comment]
yes, with mnc mcc radio and reason removed

**Comment by birdman2005** [comment]
send "GET /v2/code?cc=86&in=13321950869&lc=GB&lg=en&sim_mcc=460&sim_mnc=002&method=sms&token=a5b548186cd7450a08e3d6c60333e35e&id=.%12.M%60%25b%1B%29%22%3Eg.%05.%3E.F.O HTTP/1.1
Host: v.whatsapp.net
User-Agent: WhatsApp/2.12.60 S40Version/14.26 Device/Nokia306
Accept: text/json

received "{"status":"fail","reason":"no_routes","retry_after":3600}"

Is there something wrong with id?

**Comment by lylepratt** [comment]
I just installed via `pip` and am also encountering this error.
