### ISSUE TITLE
Sending Audio with yowsup-cli

### ISSUE THREAD

**Issue by bbtimx** [tgalal/yowsup#617]
Hey,

I add some code to yowsup-cli to send audio:

<pre lang="python"><code>
audioOpts = self.add_argument_group("Audio client demo")
        audioOpts.add_argument('-a', '--audio', action="store", help = "Send a Audio to specified phone number, "
                                                                     "wait for server receipt and exit",  
metavar=("phone", "path"), nargs = 2)
</code></pre>

and

<pre lang="python"><code>
def startSendAudio(self):
        from yowsup.demos import sendaudio
        credentials = self._getCredentials()
        if not credentials:
            print("Error: You must specify a configuration method")
            sys.exit(1)

        try:
            stack = sendaudio.YowsupSendStack(credentials, [([self.args["audio"][0], self.args["audio"][1]])],
                                               self.args["moxie"])
            stack.start()
        except KeyboardInterrupt:
            print("\nYowsdown")
            sys.exit(0)
</code></pre>

Create new folder called sendaudio with stack.py ( copy from SendClient ) and layer.py.

layer.py:

<pre lang="python"><code>
from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.auth import YowAuthenticationProtocolLayer
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
import sys
from yowsup.common import YowConstants
import datetime
import os
import logging
from yowsup.layers.protocol_receipts.protocolentities    import *
from yowsup.layers.protocol_groups.protocolentities      import *
from yowsup.layers.protocol_presence.protocolentities    import *
from yowsup.layers.protocol_messages.protocolentities    import *
from yowsup.layers.protocol_acks.protocolentities        import *
from yowsup.layers.protocol_ib.protocolentities          import *
from yowsup.layers.protocol_iq.protocolentities          import *
from yowsup.layers.protocol_contacts.protocolentities    import *
from yowsup.layers.protocol_profiles.protocolentities    import *
from yowsup.layers.protocol_chatstate.protocolentities   import *
from yowsup.layers.protocol_privacy.protocolentities     import *
from yowsup.layers.protocol_media.protocolentities       import *
from yowsup.layers.protocol_media.mediauploader import MediaUploader
from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
from yowsup.layers.axolotl import YowAxolotlLayer
import threading

logger = logging.getLogger(__name__)

class SendAudio(YowInterfaceLayer):

    PROP_MESSAGES = "org.openwhatsapp.yowsup.prop.sendclient.queue" #list of (jid, message) tuples

    def __init__(self):
        super(SendAudio, self).__init__()
        self.ackQueue = []
        self.lock = threading.Condition()
        self.connected = True
        self.jidAliases = {
            # "NAME": "PHONE@s.whatsapp.net"
        }

    @ProtocolEntityCallback("success")
    def onSuccess(self, successProtocolEntity):
        for target in self.getProp(self.__class__.PROP_MESSAGES, []):
            phone, message = target
            print("\n %s" % phone)
            print("\n %s" % message)
            self.audio_send(phone, message)

    
    @ProtocolEntityCallback("ack")
    def onAck(self, entity):
        self.lock.acquire()
        if entity.getId() in self.ackQueue:
            self.ackQueue.pop(self.ackQueue.index(entity.getId()))

        if not len(self.ackQueue):
            self.lock.release()
            logger.info("Message sent")
            raise KeyboardInterrupt()

        self.lock.release()
    
    def audio_send(self, number, path):
        if self.assertConnected():
            jid = self.aliasToJid(number)
            entity = RequestUploadIqProtocolEntity(RequestUploadIqProtocolEntity.MEDIA_TYPE_AUDIO, filePath=path)
            successFn = lambda successEntity, originalEntity: self.onRequestUploadResultAudio(jid, path, successEntity, originalEntity)
            errorFn = lambda errorEntity, originalEntity: self.onRequestUploadError(jid, path, errorEntity, originalEntity)

            self._sendIq(entity, successFn, errorFn)
    
    def doSendAudio(self, filePath, url, mediaType, to, ip = None):
        entity = DownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, mediaType, ip, to)
        self.toLower(entity)
    
    def onRequestUploadResultAudio(self, jid, filePath, resultRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
        if resultRequestUploadIqProtocolEntity.isDuplicate():
            self.doSendAudio(filePath, resultRequestUploadIqProtocolEntity.getUrl(), "audio", jid,
                             resultRequestUploadIqProtocolEntity.getIp())
        else:
            mediaUploader = MediaUploader(jid, self.getOwnJid(), filePath,
                                      resultRequestUploadIqProtocolEntity.getUrl(),
                                      resultRequestUploadIqProtocolEntity.getResumeOffset(),
                                      self.onUploadSuccessAudio, self.onUploadError, self.onUploadProgress, async=False)
            mediaUploader.start()

    def onRequestUploadError(self, jid, path, errorRequestUploadIqProtocolEntity, requestUploadIqProtocolEntity):
        logger.error("Request upload for file %s for %s failed" % (path, jid))

    def onUploadSuccessAudio(self, filePath, jid, url):
        self.doSendAudio(filePath, url, "audio", jid)

    def onUploadError(self, filePath, jid, url):
        logger.error("Upload file %s to %s for %s failed!" % (filePath, url, jid))

    def onUploadProgress(self, filePath, jid, url, progress):
        sys.stdout.write("%s => %s, %d%% \r" % (os.path.basename(filePath), jid, progress))
        sys.stdout.flush()
        
    def assertConnected(self):
        if self.connected:
            return True
        else:
            self.output("Not connected", tag = "Error", prompt = False)
            return False
            
    def aliasToJid(self, calias):
        for alias, ajid in self.jidAliases.items():
            if calias.lower() == alias.lower():
                return self.normalizeJid(ajid)

        return self.normalizeJid(calias)
        
    def jidToAlias(self, jid):
        for alias, ajid in self.jidAliases.items():
            if ajid == jid:
                return alias
        return jid

    def normalizeJid(self, number):
        if '@' in number:
            return number
        elif "-" in number:
            return "%s@g.us" % number

        return "%s@s.whatsapp.net" % number
</code></pre>

Now with <code>python yowsup-cli demos -c config -a 49xxxxxxxx test.mp3</code> nothing happens.

Any ideas? THX
##

**Comment by tgalal** [comment]
Where are you calling startSendAudio?

**Comment by bbtimx** [comment]
Solved it :)

Now I have the next problem when sending audio files:

python c:\Python27\bosmon.py -t audio -l 49xxxxxxxxxx -p C1xxxxxxxxxxqyyyyyyyyyyyyyy -to 49yyyyyyyyyyyy -i audio.aac
No handlers could be found for logger "yowsup.layers.protocol_media.mediauploader"

Upload file audio.aac to https://mmi205.whatsapp.net/u/3W65EJS_YUN7pYYT_-Lxxxxxxxxxxxxxxw/Arevkyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzooorv for 49xxxxxxxxxxx@s.whatsapp.net failed!

It allways says it fail but sometimes i reveived the audio successfully.
No duplicated files!
Same with wave files.

**Comment by kwiiby** [comment]
Thanks man, this code works.

**Comment by chetanunadkat90** [comment]
Hi I am getting following error while running above changes 
audioOpts.add_argument('-a', '--audio', action="store", help = "Send a Audio to specified phone number, "
            ^
SyntaxError: invalid syntax

**Comment by holdack182** [comment]
i implemented the code, and i receive no error... but.... it seems the action does not get done. here's the console output: nothing happens... 

pi@raspberrypi ~/yowsup $ python yowsup-cli demos -c config -a 55xxxxxxxxxxxx ~/yowsup/audio.wav 
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

 5513xxxxxxxx

 /home/pi/yowsup/audio.wav

**Comment by holdack182** [comment]
not sure if it's that clear, but it seems to get stuck at:


self._sendIq(entity, successFn, errorFn)

**Comment by yssharma** [comment]
Stuck at same place as holdack182. Is anyone able to get it working? Any tips?

I get no errors but it just stuck after the messages:
 91XXXXXXXXXX
 /home/yash/Desktop/wallies/peac.jpg

**Comment by gfngr** [comment]
same here, is it possible to send audio files like mp3 via the cli?

**Comment by Abhijeet0** [comment]
getCredential() method not found in yowsup-cli file
