### ISSUE TITLE
Message read status

### ISSUE THREAD

**Issue by baldantas** [tgalal/yowsup#618]
I'm new to the forum,
I have configured the Yowsup, and all the examples of DEMO could test. How can I check if a sent message has been received or read by the recipient?

God bless you all.

**Comment by tgalal** [comment]
You need to listen for [IncomingReceiptProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_receipts/protocolentities/receipt_incoming.py)

**Comment by baldantas** [comment]
Hello tgalal,
I created a simple code in python to me return the status of a sent message, as follows:

```
def startStatusMensagem(self):
        from yowsup.layers.protocol_receipts.protocolentities import IncomingReceiptProtocolEntity

        try:
            stack = IncomingReceiptProtocolEntity(self.args["status"][0], self.args["status"][1], self.args["status"][2])

            print(stack.fromProtocolTreeNode(stack.toProtocolTreeNode()))
        except KeyboardInterrupt:
            print("\nYowsdown")
            sys.exit(0)
```

When running from the command line with the following words:
/var/www/wa/yowsup_2/yowsup-master/./yowsup-cli demos -c /var/www/wa/yowsup_2/yowsup-master/config.conf -w 1424365438-1 55848834524 1424368168.76

I get the following return:
Receipt:
ID: 1424365438-1
From: 55848834524
Timestamp: 1424368168.76

It should not return me the message status, next to the parameter RECEIPT? Did I do something wrong?

The command is running without error, but the message status is not returned.

Looking forward.
God bless you.

**Comment by ak52** [comment]
Have you found any solution ? I get the same results with no response if the message is read or not
