### ISSUE TITLE
¿the password in the config file?

### ISSUE THREAD

**Issue by steve1982** [tgalal/yowsup#62]
![response_error](https://f.cloud.github.com/assets/3285601/71243/c44d9f90-5fde-11e2-8188-ad1268c5ba11.JPG)
It is impossible for me to send a message through yowsup, I do not need to code the password in config file in the "password" field.
to request the code I get a code Whatsapp the format: XXX-XXX Is this the password for config?. if I put this code the lib base64.py throws an error.
Finally, when sending a message I receive "Auth Failed".
I attach the error.

Thankyou:))

**Comment by kndone** [comment]
This is my config file, it's really working for me;

cc=52 #if not specified it will be autodetected
phone=521XXXXXXXXXX
password=XXXXXXXXXXXXXXXXXXXXXXXXXXX=

Don't forget to add the area code after the country code, for Mexico it's 1
