### ISSUE TITLE
Still no Ping response.

### ISSUE THREAD

**Issue by mode2k** [tgalal/yowsup#622]
Hi,

i wrote my own layer:
MyLayer.py:

    import logging
    import time
    from yowsup.layers.interface                          import YowInterfaceLayer
    from yowsup.layers.interface                          import ProtocolEntityCallback
    from yowsup.layers.protocol_messages.protocolentities import TextMessageProtocolEntity
    from yowsup.layers.protocol_receipts.protocolentities import OutgoingReceiptProtocolEntity
    from yowsup.layers.protocol_acks.protocolentities     import OutgoingAckProtocolEntity
    from yowsup.layers.protocol_iq.protocolentities       import PingIqProtocolEntity
    from yowsup.layers.protocol_iq.protocolentities       import *
    from yowsup.common                                    import YowConstants

    logger = logging.getLogger('Whatsapp')

    class MyLayer(YowInterfaceLayer):
        def setPlugin(self, plugin):
            self._plugin = plugin

        @ProtocolEntityCallback("message")
        def onMessage(self, messageProtocolEntity):
            #send receipt otherwise we keep receiving the same message over and over
            logger.info("Received Message: ID {}  From {}  Body {}".format(messageProtocolEntity._id, messageProtocolEntity._from, messageProtocolEntity.body))

            logger.info("Sending Receipt")
            receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
            self.toLower(receipt)
            self._plugin.message_received(messageProtocolEntity.getBody(), messageProtocolEntity.getFrom())

        @ProtocolEntityCallback("receipt")
        def onReceipt(self, entity):
            logger.info("Received Receipt: ID {}".format(entity._id))
            logger.info("Sending ACK")
            ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
            self.toLower(ack)

        @ProtocolEntityCallback("ack")
        def onAck(self, entity):
            logger.info("Received ACK: ID {}  Class {}".format(entity._id, entity._class))

        @ProtocolEntityCallback("success")
        def onSuccess(self, entity):
            logger.info("Received Success: Status {}  Kind {}  Creation {}  Expiration {}".format(entity.status, entity.kind, time.strftime('%d.%m.%Y %H:%M:%S', time.localtime(entity.creation)), time.strftime('%d.%m.%Y %H:%M:%S', time.localtime(entity.expiration))))

        @ProtocolEntityCallback("failure")
        def onFailure(self, entity):
            logger.info("Received Failure: {}".format(entity))

        @ProtocolEntityCallback("chatstate")
        def onChatstate(self, entity):
            logger.info("Received Chatstate: {}".format(entity))

        @ProtocolEntityCallback("iq")
        def onIq(self, entity):
            logger.info("Received IQ: {}".format(entity))

        @ProtocolEntityCallback("notification")
        def onNotification(self, notification):
            notificationData = notification.__str__()
            logger.info("Received Notification: {}".format(notificationData))

        def sendMsg(self, msg, num):
            outgoingMessageProtocolEntity = TextMessageProtocolEntity(msg, to="%s@s.whatsapp.net" % num)
            logger.info("Sending Message {0} to {1}".format(msg, num))
            self.toLower(outgoingMessageProtocolEntity)

        def do_ping(self):
            ping_entity = PingIqProtocolEntity(to = YowConstants.DOMAIN)
            self.toLower(ping_entity)
            logger.info("Pinging...")

it should Write every Callback Event to my log. For Message sending, ACK and Receipt it works fine.

But when a send a Ping this way:

    MyLayer.do_ping()

I never get a response. I was hoping to get a IQ Callback with the ping response. What am i doing wrong?

I am using last commit:
commit 0abd81c539211ec7d90869a838eeb622729998c0
Merge: ecca907 423b294
Author: Tarek Galal <tare2.galal@gmail.com>
Date:   Sun Feb 8 11:38:40 2015 +0100
    Merge branch 'samuel-barrado-add_participant'

Regards

Mode

**Comment by mode2k** [comment]
Ok, found my mistake.
Of course a have to add the IqProctolLayer to my Stack. I missed that.

Regards

Mode

**Comment by carlosfelipe29** [comment]
Good Afternoon, 
I a newer on yowsup, and I want to know,  How I put the function that do ping to the whatsapp server in the run.py example.

I am working with a run.py and the layer.py,  I modified the layer.py, but in order to have ping every minute, how it works on the run.py

I appreciate your help.
