### ISSUE TITLE
send images automatically

### ISSUE THREAD

**Issue by padre** [tgalal/yowsup#624]
It would be possible to send images automatically? as 

yowsup-cli demos -c config -s phone "Message"

but with images. If I want to send a picture I have to do manually:

yowsup-cli demos --yowsup --config config

and then:
/image send phone "pathImg"

It would be possible to do this automatically? Thanks!!
##

**Comment by eternautaCAT** [comment]
There is not such option, but you can implement this using the library. The send-client example in demos directory maybe is a helpful guide for you.

**Comment by tgalal** [comment]
waiting for #555

**Comment by padre** [comment]
Oh, good :D

 Thank you very much to both.
