### ISSUE TITLE
Maintaining state in a yowsup application

### ISSUE THREAD

**Issue by zenithanon** [tgalal/yowsup#627]
I want to implement a USSD like application based on yowsup. Its like a question and answer like app.
Example:

Me: REPORT  ----- > Yowsup number
Yowsup app: NAME?
ME: [my name]
Yowsup app: AGE?
ME: [age]
etc
I would like the app to gather all variables before doing a database insert. I would like to know how to implement this

**Comment by dedmen** [comment]
Thats more a python problem than an Yowsup specific problem.

**Comment by eternautaCAT** [comment]
I agree with dedmen.

This question is more for stackoverflow, i think.

Anyway, try to store the values in a global list, and when you get all you need, then make the database insert.

**Comment by zenithanon** [comment]
Thanks. But would having a global list scale?

**Comment by tgalal** [comment]
closing as not exactly yowsup issue

**Comment by gisho** [comment]
@zenithanon  you would just send the message to an actual USSD app that keeps state.   here is a simple example using zeromq
```
    def ussdRequest(self,messageProtocolEntity):
        try:
           context = zmq.Context()
           sock = context.socket(zmq.REQ)
           sock.connect("tcp://127.0.0.1:5690")
           message = "{msisdn}||{message}".format(msisdn=messageProtocolEntity.getFrom(False),
                                                   message=messageProtocolEntity.getBody())
           print "req >> %s from %s"% (messageProtocolEntity.getBody(),messageProtocolEntity.getFrom(False))
           sock.send(message)
           resp = sock.recv()
           resp = resp.split('||')
           outgoingMessageProtocolEntity = TextMessageProtocolEntity(
                  resp[1],to = '%s@s.whatsapp.net'% (resp[0]))
           self.toLower(outgoingMessageProtocolEntity)
           print "resp << %s to %s"% (resp[0],resp[1])
           sock.close()
        except Exception,e:
            print e
```
