### ISSUE TITLE
does @ProtocolEntityCallback("presence") exist?

### ISSUE THREAD

**Issue by eternautaCAT** [tgalal/yowsup#628]
I want to cath the response of a SubscribePresenceProtocolEntity, and i try

@ProtocolEntityCallback("presence")
    def onPresence(self, presenceProtocolEntity):
        #do stuff

but doesn't work.

I want to process the result for see the "last" attribute.

Any sugerence?

**Comment by tgalal** [comment]
Do you have YowPresenceProtocolLayer in your stack ?

**Comment by tgalal** [comment]
sorry turns out it's probably related to #636
