### ISSUE TITLE
Questions on Contact Sync

### ISSUE THREAD

**Issue by yunghee** [tgalal/yowsup#629]
Dear Sir,

May I know how many contacts can be synced in one batch?
Will Whatsapp block my number if I attempt to sync too many contacts, or send sync command too frequent?
##

**Comment by dedmen** [comment]
I have 74 contacts and i am syncing each individual as fast as yowsup can handle it. I didnt experience any problem yet.. But syncing them in one batch returns an error and just doesnt work like it should.

**Comment by bachoo786** [comment]
when you say you are syncing contacts you mean you are saving them? I am on raspberry and trying to save them but I do not know how?

Its hard for me to keep remembering numbers when I want to send a message to them. Please help
