### ISSUE TITLE
Need help yowsup-cli and php.

### ISSUE THREAD

**Issue by IAntaresI** [tgalal/yowsup#631]
When you run the console command
yowsup-cli demos -l 491577xxxxxxx: cHzM7D2 + 9xxxxxxxx -s 49176xxxxxx "Hallo Welt"
Messages sent all is well.
But when the same commands in php shell_exec ('yowsup-cli demos -l 491577xxxxxxx: cHzM7D2 + 9xxxxxxxx -s 49176xxxxxx "Hallo Welt"')
not performed.

tried options
shell_exec ('/ usr / local / bin / yowsup-cli demos -l 491577xxxxxxx: cHzM7D2 + 9xxxxxxxx -s 49176xxxxxx "Hallo Welt"'),
shell_exec ('/ usr / bin / python / usr / local / usr / local / bin / yowsup-cli demos -l 491577xxxxxxx: cHzM7D2 + 9xxxxxxxx -s 49176xxxxxx "Hallo Welt"')
the ____ does not work.

Partial execution of the command works as follows:
shell_exec ('yowsup-cli demos') or
shell_exec ('yowsup-cli demos -l 491577xxxxxxx: cHzM7D2 + 9xxxxxxxx')
gives the result

usage: demos [-h] [-v] [-d] [--help-config] [-l phone: b64password | -c CONFIG]
              [-m] [-y] [-e] [-s phone message]

Run a yowsup demo

optional arguments:
   -h, --help show this help message and exit
   -v, --version Print version info and exit
   -d, --debug Show debug messages
   --help-config Prints a config file sample

Configuration options for demos:
   -l phone: b64password, --login phone: b64password
                         WhatsApp login credentials, in the format
                         phonenumber: password, where password is base64
                         encoded.
   -c CONFIG, --config CONFIG
                         Path to config file containing authentication info.
                         For more info about config format use --help-config
   -m, --moxie Enable experimental support for the new WhatsApp
                         encryption

Command line interface demo:
   -y, --yowsup Start the Yowsup command line client

Echo client demo:
   -e, --echo Start the Yowsup Echo client

Send client demo:
   -s phone message, --send phone message
                         Send a message to specified phone number, wait for
                         server receipt and exit

Please tell me if there is full of opportunities to perform this commando through php.
OS ubuntu 14.04 lts.

**Comment by dedmen** [comment]
shell_exec ("yowsup-cli demos -l 491577xxxxxxx:b64Password -s 49176xxxxxx \"Hallo Welt\"");
Try that... 
What is that ": cHzM7D2 + 9xxxxxxxx" supposed to be?
try with a config file.
Will Yowsup-Cli or echo client start correctly?

**Comment by tgalal** [comment]
obviously not a yowsup problem
