### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tfvtfv** [tgalal/yowsup#632]
Hi, sorry, I am a newbie, but I really think that I have tried hard to get this from documentation, without success:

1.) https://github.com/tgalal/yowsup#installation-updated-dec-31-2014
Docu say "install zlib". I can get a compiled binary following the link, but which directory am I supposed to put this to under Win7?

2.) Connection manager
I tried to ret most recent version of yowsup from here:
https://github.com/tgalal/yowsup/archive/master.zip
and while my sendclient examples work well using yowsup-cli, I fail to get Yowsup.connectionmanager running, since this module is simply not present. How do I get hold of connectionmanager.px?

EDIT:
I have meanwhile found that I can get the connectionmanager.py by doing a 
'pip install Yowsup' with capital Y. However, things get very confusing afterwards, since the file is copied into the yowsup directory, while all subroutines refer to a Yowsup (capital 'Y' director)

I am missing something here, sorry for asking those dumb questions.

Thanks again for that great piece of software, learned a lot during the recent weks (but not enough I think ;-) )
##

**Comment by tgalal** [comment]
1- I guess Windows\System32
2- There is Yowsup legacy branch which has the new connectionmanager you are looking for, and there is yowsup2 found in pip under the name yowsup2, which does not contain connectionmanager anymore.  But in general why are you looking for connectionmanager specifically?

**Comment by tfvtfv** [comment]
@tgalal 
Why I am looking for the connection manager:
* My overall task simple, I want to write a small Windows application that simultaneously allows to send and receive messages
* I have understood and can handle the concept of signals and methods as described here:
https://github.com/tgalal/yowsup/wiki/%5BLegacy%5D-Yowsup-Documentation
With that, I'd be able to solve the above problem (but I don't get this installed properly, and I don't want to use it since it seems to be a dead code branch).
* For yowsup2, I do not understand how to handle that rather simply task:
+ Decorators have been new for me (you can do a lot in Python even without decorators), but I think I have understood that concept now. Nevertheless, a higher hurdle for a newbie than signals and methods. My problem is that there is no documentation on the underlying functions.
+ I can send and receive by invoking yowsup-cli from the command line, but first of all this is clumsy, and furthermore I cannot read any output from a yowsup-cli pipe when doing a system call so far.
+ I have tried to dig into the yowsup-cli code to rewrite it so that I only use the parameters necessary for me, and call them directly from my windows program. Seems the most promising approach at the moment, but I need to understand your code much better before I will succeed. And I wold not call that approach "using an interface", that's more like reengineering. :-)
+ I have worked through the sample codes for sendclient and echo. I think I understand that I need to combine those two into my own layer, but I have not really succeeded doing so. Receiving messages is done in a loop, which gives me a headache, since this is blocking, and getting the messages out is again either done clumsy in my own way, or using the layer communication structure, which I have not fully understood so far.

I think one of two things would help, and I'd be happy to help with documentation from next week on:
a. (in the shord run) Give a few more examples in addition to echoclient and sendclient, such as 
a1: send and receive: show sending and receiving in one program
a2: layer communication: show how information (such as a received message) gets transmitted out of your modules in a proper way
b. (in the long run): Set up a documentation similar to the one listed above for signals and methods for the connectionmanager. A programmer still wants to receive these signals and use those methods, how can this be done (for each of the listed items in connectionmanager) in yowsup2?

Sorry for that rather lengthy reply, but I hope this might help you to understand the obstacle.
