### ISSUE TITLE
Small error in docu

### ISSUE THREAD

**Issue by tfvtfv** [tgalal/yowsup#633]
In https://github.com/tgalal/yowsup/wiki/%5BLegacy%5D-Yowsup-Documentation

I think that you want to write:
methodsInterface.call("message_ack", ("identifier@s.whatsapp.net", messageId)

instead of:
methodsInterface.call("message_id", ("identifier@s.whatsapp.net", messageId)

**Comment by tgalal** [comment]
Yup, thanks!
