### ISSUE TITLE
Connectionmanager

### ISSUE THREAD

**Issue by tfvtfv** [tgalal/yowsup#634]
I suggest to add a sentence on the relation between master and legacy package in the wiki, especially to comment on on the intended use of the connectionmanager.py.

Does 'legacy' mean that this functionality is no longer supported in the most actual yowsup2 version?

If it is suported, how are both packes to be installed at the same time?

I am happy to help with documentation (such as FAQ), but at the moment it seems that I can only list the questions and not the answers :-)

**Comment by tgalal** [comment]
If you read the [readme](https://github.com/tgalal/yowsup/blob/master/README.md):
 > What's new in Yowsup 2

> Everything! The old library code was so messed up that I was disgusted just by looking at it. I rewrote the library from ground up with a much more robust, extensible architecture and a much simpler and easier to read code.

> For devs, the update is breaking for any old code. While old code will stay in "legacy" branch for a while, it's advised that you upgrade your code. Unless your code is a full fledged WhatsApp application, migrating won't be a hard task.

I think this is a clear explanation for the relation between master and legacy and for what happened to connectionmanager.py.
