### ISSUE TITLE
Activation fails with bad-pram

### ISSUE THREAD

**Issue by GewoonGijs** [tgalal/yowsup#635]
Activation fails. Please help:

python yowsup-cli  registration -d  --requestcode voice --phone 31xxxxxxx --cc 31
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.61 S40Version/08.71 Device/NokiaX2-01'}
DEBUG:yowsup.common.http.warequest:cc=31&in=xxxxxxx&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=voice&token=40e222ea12f15f1fd50c6d799194017b&id=%E6%B2%2A%C5%ABi%D2S%7D%8B%F1%C0%E4k5Pb%1Dj%8B
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=31&in=xxxxxxxx&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=voice&token=40e222ea12f15f1fd50c6d799194017b&id=%E6%B2%2A%C5%ABi%D2S%7D%8B%F1%C0%E4k5Pb%1Dj%8B
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param
##

**Comment by tgalal** [comment]
sure about your number? Does it have leading zero(s) after country code ?

**Comment by gijs69** [comment]
Actually it is my land line number and indeed without the leading '0's

Verstuurd vanaf mijn iPhone

**Comment by blackjack4494** [comment]
Try this:
python yowsup-cli registration --requestcode voice --phone 31xxxxxxxxxx --cc 31 --mcc 204 --mnc 02

Or change mcc and mnc to cellphone provider.
https://en.m.wikipedia.org/wiki/Mobile_country_code#N

But it should work with valid mcc mnc. While 000 for both is not working especially for mnc it is actually restricted to two numbers so max 00 not 000.

**Comment by medisoft** [comment]
Hi, i'm with same problem. I tested with my own cell phone, and I got the password, but with my voip line (that accepts sms) I'm getting 

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param


I think I'm missing the right mcc and mnc, and don't know how to get that. Is there a way to get that info somewhere?

**Comment by medisoft** [comment]
I was able to work with a voip from other country, and receiving a call with the code, after that I got the password. Thank you

**Comment by ArmeF97** [comment]
How did you do that @medisoft ?
