### ISSUE TITLE
Error running yowsup echo client

### ISSUE THREAD

**Issue by norberto-enomoto** [tgalal/yowsup#638]
I am trying to run yowsup sample app by following the directions on this page:

https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app

When I run 'run.py' in the command line I get this message:

ubuntu@ip-172-30-0-132:~/yowsup-master/yowsup/demos/echoclient$ python run.py
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
No handlers could be found for logger "yowsup.stacks.yowstack"

What´s wrong?
##

**Comment by blackjack4494** [comment]
http://stackoverflow.com/questions/17626694/remove-python-userwarning

So you can either change the permissions or just ignore the warning.
To your second warning. You just can ignore the logger error it will not affect anything.

**Comment by gautammaloo** [comment]
@norberto-enomoto @blackjack4494 for second warning you have to configure the logger's handler.
For python 2.7x if you don't want to see this msg, you could just use Null Handler.
Put this in run.py
import logging
logging.getLogger("yowsup.stacks.yowstack").addHandler(logging.NullHandler())

check out http://stackoverflow.com/questions/11191398/error-message-no-handlers-could-be-found-for-logger-zodb-filestorage-on-copied
https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library
