### ISSUE TITLE
Any hint on sending a vcard via cli?

### ISSUE THREAD

**Issue by ncri** [tgalal/yowsup#640]
I'm not very familiar with python, so far I used the cli sendclient demo to send messages. That is working fine. Any hints on how to send a vcard? Do I have to implement my own demo? I hacked the sendclient demo a bit, but didn't succeed in changing it to send a vcard. Either params to VCardMediaMessageProtocolEntity were wrong or the client was just hanging without any response.
##

**Comment by dedmen** [comment]
Look at the echoclient demo it does also echo vcards.
and at layers/protocol_media/protocolentities/message_media_vcard.py
it looks like card_data is just a string of the vcard data.

**Comment by tgalal** [comment]
@ncri also you need to have YowMediaLayer in your stack which sendclient demo doesn't have by default

**Comment by ncri** [comment]
Thx, for the hints, I thought I had done all this, but I will give it another try.

**Comment by ncri** [comment]
Sorry, I'm a bit lost here, I tried to hack a demo together but I don't get it working. 
Currently my demo hangs with this warning:

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

Also, which layers do I need? I just used the ones in the sendclient demo, only changing the SenLayer to my new SendVCardLayer layer:

            SendVCardLayer,
            (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
            YowLoggerLayer,
            YowCoderLayer,
            YowCryptLayer,
            YowStanzaRegulator,
            YowNetworkLayer

Is this correct? Everything else in stack.py is pretty much the same, I just changed the includes.

layer.py is also quite the same as in the sendclient, I'm trying to send the vcard in the success callback - no idea if that is the right place:

```
 @ProtocolEntityCallback("success")
    def onSuccess(self, successProtocolEntity):
        self.lock.acquire()
        for target in self.getProp(self.__class__.PROP_MESSAGES, []):
            phone = target
            messageEntity = VCardMediaMessageProtocolEntity("vcard", {"name":"Test"}, None, to = phone)
            self.ackQueue.append(messageEntity.getId())
        self.lock.release()
```

Then, in yowsup-cli.pyI added the necessary code for the new demo including this command to send it:

```
def startVCardClient(self):
  ...
  stack = sendvcard.YowsupSendVCardStack(credentials, [([self.args["vcard"][0]])], self.args["moxie"])
```

Any help is greatly appreciated... This can't be so difficult... ;-)

**Comment by ncri** [comment]
Just pushed the relevant files here: https://github.com/ncri/vcard_demo_files

**Comment by ncri** [comment]
Okay, I set up the whole thing again in a slightly different way but still don't get it working.
I basically still use a modified sendclient demo. In my layer.py I do:

    @ProtocolEntityCallback("success")
    def onSuccess(self, successProtocolEntity):
        for target in self.getProp(self.__class__.PROP_MESSAGES, []):
            phone, message = target
            outVcard = VCardMediaMessageProtocolEntity('Test', {"name":"abc"} ,to = phone)
            print("Echoing vcard (%s, %s) to %s" % ('Test', {"name":"abc"}, phone))
            #send receipt otherwise we keep receiving the same message over and over
            self.toLower(outVcard)

The last line here causes an error:

    TypeError: must be string or buffer, not dict

Any hints to fix this are very appreciated... Stuck here quite long. Wonder why this is so difficult. ;-)

(I know there is stuff in the code for sending a message thats not needed here, I will clean that up later. First I want to get it work.)

**Comment by ncri** [comment]
I finally got this working, with lots of debugging. In case anyone is interested in the solution, I can post it here. 

Only one thing I don't quite understand yet: I had to use an ackQueue similar to the sendclient demo, to make the demo exit after sending the vcard. Not sure what that is about. Anyone can give me an idea or point me to some infos about this?

**Comment by blue-boxme** [comment]
I'm interested. Post it here please

**Comment by ncri** [comment]
Okay, the working demofiles and cli changes are here: https://github.com/ncri/vcard_demo_files

**Comment by ncri** [comment]
The vcard is defined in layer.py.

This is how it is sent: 

    python yowsup-cli demos -c auth.txt -vc number_to_send_to

**Comment by abhishekdeshkar** [comment]
@ncri  : How to send image with VCard ?

**Comment by ncri** [comment]
No idea, never tried.
