### ISSUE TITLE
SendClient & EchoClient

### ISSUE THREAD

**Issue by blackjack4494** [tgalal/yowsup#649]
So,
I was 'just' trying to send a message to myself with the SendClient (Demo).
Of course I couldn't see if I Received the message but just wanted to know if I would get any kind of errors back.
So, when I started EchoClient (Demo) I am getting the message I sent to myself before over and over again. 

Some points to think about:
-automatically block a try with SendClient to send yourself a message (should be easy if you know what you do to disable it - for any reason)
-build in a 'check'-function to prevent sending/getting the same message all over again

Now I have to find out how to delete my own chat :D

EDIT 1#:
/group leave 'number'
is working to delete your own chat as well as chats with single contacts not only groups ;)
##

**Comment by eXayte** [comment]
I've made a pull request for this:
https://github.com/tgalal/yowsup/pull/651
