### ISSUE TITLE
environment Variable.

### ISSUE THREAD

**Issue by abhijo89** [tgalal/yowsup#655]
I am using this application in my system for notify the user ones the background scripts complete it execution. I use supervisor  (Ubuntu 14.04 LTS ) .  

When i run yowsup in terminal it works fine for me.But  if i add it in supervisor  it will not work .
I know this is something i have to do with environment variable .. Can any one help me for this issue ?

**Comment by tgalal** [comment]
I don't think it's a yowsup problem
