### ISSUE TITLE
Question: receiving a video

### ISSUE THREAD

**Issue by firstlevelIT** [tgalal/yowsup#656]
is it possible receive a video?
there is an example available?

**Comment by blackjack4494** [comment]
https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_media/protocolentities/message_media.py#L95

**Comment by firstlevelIT** [comment]
Thanks. I can't find any working example. I tested yowsup-cli but I can see only image type file. No event in case of video.

**Comment by tgalal** [comment]
WIP

**Comment by luckydonald** [comment]
Like right now? 
I see, it is just missing in [layers/protocol_media/layer.py:32](https://github.com/tgalal/yowsup/blob/c3c6db42a34b20f001fa4aad80fb776d12eaf0ec/yowsup/layers/protocol_media/layer.py#L32)? If so I'd file a request, or does this need bigger changes? (probably a protocolentities too?)

**Comment by tgalal** [comment]
There is already a pull request for it: #626, sorry I've been away for a while, I'll merge it very soon.

**Comment by luckydonald** [comment]
Awesome :D

**Comment by aesedepece** [comment]
This is duplicate of #512, so it can be already closed because #626 was merged 19 days ago :wink:
