### ISSUE TITLE
Yowsup doesn't work for me anymore since last update.

### ISSUE THREAD

**Issue by UndeadLeech** [tgalal/yowsup#662]
![img_20150228_052025 1](https://cloud.githubusercontent.com/assets/8886672/6424832/bdb69b14-bf09-11e4-890f-7a66e7dc7bef.jpg)

This is what happened to me after installing axolotl.
I am not 100% sure what the best way might be to fix this so I thought while doing further debugging I'd ask here if anyone had an idea.

**Comment by blackjack4494** [comment]
Did you always use python 3??
Try 
sudo python run.py
This will use python 2.x mostly 2.7

**Comment by UndeadLeech** [comment]
Yes I was always using python 3 and it worked before. So running with python 2 would mean that a lot of stuff I made wouldn't work.
But this seems to be a problem with yowsup which should be able to run on python 3 right?

**Comment by UndeadLeech** [comment]
So the issue looks like it's a problem with python. I guess because python-axolotl is python 2.7.
I didn't find an official looking version for python 3 myself, so is yowsup not supposed to run on  python 3 or is it intended for me to remake axolotl in python 3 myself by using 2to3 or other stuff?

**Comment by tgalal** [comment]
axolotl supports python3, problem is your protobuf (axolotl dependency) installation is outdated and does not support python3, you just need to update that.
