### ISSUE TITLE
Broadcast Not Working

### ISSUE THREAD

**Issue by NilayKulkarni** [tgalal/yowsup#663]
I'm working on an app which sends broadcast messages to certain users, but I'm not able to find any way I can send it. Because I can send messages by def onMessage after @ProtocolEntityCallback("message") but I couldn't find any way I could braodcast a certain string. Here's my layer file : http://pastebin.com/P2A4p7eM

**Comment by tgalal** [comment]
It's not clear what the problem is, reopen if still an issue
