### ISSUE TITLE
Echo client raises the following warning when i tried to run it 

### ISSUE THREAD

**Issue by ahumblenerd** [tgalal/yowsup#665]
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

**Comment by blackjack4494** [comment]
https://github.com/tgalal/yowsup/issues/639
Please look for similar topics before you post them. There is also another topic where there is a fixed described.

**Comment by tgalal** [comment]
duplicate #639
