### ISSUE TITLE
Is it possible to create an auto responder for whatsapp?

### ISSUE THREAD

**Issue by Snowlav** [tgalal/yowsup#668]
I use whatsapp A LOT for my business, and it would make a very very large impact on my communication if I could have a desktop application for it.

While that is possible, and they released a web app as well (yay!) I still have a lot of time where I am not at my desk, or have my phone with me.
Usually this means I come back and am bombarded with urgent messages and alike.

It'd be great if there was a way to respond to all the messages when I am not around, just a simple message with:
"Hey! Thanks for reaching me but unfortunately I am currently not available"
"For urgent matters that can not wait X minutes/hours please contact me at this number: "

That way I can give people an estimate on when I will be back, and give them a back up option to either call my private line, or my home where my wife usually will pick up the phone if it's really urgent.

I looked into some different options like patched apk's etc but nothing beats a desktop application.

Thank you for taking your time to read this, I hope someone can answer soon :)

EDIT: the title, have been reading up on Evan Spiegel and his baby snapchat, so I mixed the two up.
My bad.

**Comment by dedmen** [comment]
Is it possible? Sure!
You could just edit the echo demo to respond with a specific message instead of the message it became.
I wrote an C++ Qt based Handler on top of Yowsup. Something like that can easily be build and extended with a nice UI.

**Comment by Snowlav** [comment]
@dedmen My coding experience is limited, so I'd like to do it python as I have some experience with that.
It's nice to know it's possible though, thanks!

Are there any problems I might run into? Like limits in replying or anything else, I never experience those just typing / manually but I don't know if things are different when doing it automated?

**Comment by dedmen** [comment]
Youll get problems if you message people that dont know you.. And as Whatsapp is against automated systems they might sometime detect if youre answering unhuman fast so you may need to add a little delay.. But just Answering to people that message you shouldnt yield any problems.

**Comment by Snowlav** [comment]
Ah yes, I see. Does this rule apply when the people that message me know
me, but I don't know them?
I am thinking about using this idea for my first line of contact, meaning
all inquiries etc from people will be send to me through whatsapp,

This means I could (potentially / worst case scenario) have a 100 people or
so messaging me in 1-1.5 hours.

Any problems with those numbers? Are there any "written" limits (like X
replies / hour / day or whatever)

Thanks for the help so far :) !

2015-03-03 13:17 GMT+01:00 dedmen <notifications@github.com>:

**Comment by rodrigofaillace** [comment]
@Snowlav , will you abort using Whatsapp Official Mobile App?

It won´t be possible using Yowsup and the official app together, ok?

regards.

**Comment by Snowlav** [comment]
@rodrigofaillace that's fine :) I am okay with going desktop app only for a first line of communication.

**Comment by dedmen** [comment]
They cant enforce other Limits than in real Whatsapp... And you can write 100 Messages in an Hour that should really be no problem.

**Comment by EliaComputers** [comment]
Check the #647? :) I use Yowsup for home Automation but your project is the same :)

**Comment by kuldippatel** [comment]
I am running an encyclopedia on +919963064258, Give it a try. There will be more features soon.

**Comment by asanf** [comment]
dedmen I would really like more information on that Qt/C++ handler, any link or reference you used to make C++ talk to python?

**Comment by dedmen** [comment]
Its really nothing professional.
I used QProcess to start python with yowsup.
Im running yowsup-cli demos -y -d so i get all debug messages. My 
Program just executes the yowsup-cli commands and then reads the debug 
messages and analyzes them.

**Comment by TKStudio** [comment]
You can use my app for that (Root needed):
https://play.google.com/store/apps/details?id=tkstudio.wachatbot

**Comment by mgp25** [comment]
4,84€? sick, i have the same script for free.

**Comment by muglikar** [comment]
Hi @dedmen how did you build the C++ Qt based Handler on top of Yowsup?

**Comment by dedmen** [comment]
@muglikar Qt Launches the python process and then takes the Process output and parses it using RegularExpressions

**Comment by globalsend** [comment]
Hi, we have a cloud system that can reply automatically. You can reply text, image (including subtitle), video (including subtitle) and audio.
System has 3 types of campaigns:

- Single keyword: where user send a keyword and the system finds a match and replies with text, audio, video or image.

- Public campaign: you define a general keyword and you upload a CSV with a second keyword, and more information on the next columns. So for example people send ZIP 2234 and system can reply: Hello [name], the zipcode $[zip] is from state $[state], etc.

- Private campaign: it will match user number with number in csv and send personal information.

I have a demo number, and backend. Write me if you are interested.

Thanks

**Comment by thez3r0** [comment]
@globalsend Can you share the Codes.?

**Comment by mgp25** [comment]
@tgalal please block this cretin @globalsend 

Do you know why we dont update the API to latest protocol? Because of people messing with it.

STOP THE FUCKING SPAM

**Comment by godlikecs12** [comment]
@dedmen I'm new to programming, could you explain more or share some pieces of the code?
It would be a great help for me.

**Comment by dedmen** [comment]
@godlikecs12 no i can't share my code. But basically its just running python and parsing its output using Regular expressions. Thats all there is to it. And every part of that is programming language specific

**Comment by baylarov2016** [comment]
I sell WhatsApp autoreply 100$ skype live:aleksdeerio ! ICQ 706284150 WhatsApp +79996251456

**Comment by surajkumar25** [comment]
Please do have a look (https://www.tejarat.in/) Our company deals with WhatsApp marketing in the most modern way and is money efficient too. We provide services like Whatsapp auto responder Or WhatsApp Bulk messaging. 
Any queries you can contact me personally 
Email I'd:  tejaratmarketing2002@gmail.com

**Comment by r10crescamos** [comment]
@globalsend  Hi, we have a cloud system that can reply automatically. You can reply text, image (including subtitle), video (including subtitle) and audio.
System has 3 types of campaigns:

Single keyword: where user send a keyword and the system finds a match and replies with text, audio, video or image.
Public campaign: you define a general keyword and you upload a CSV with a second keyword, and more information on the next columns. So for example people send ZIP 2234 and system can reply: Hello [name], the zipcode $[zip] is from state $[state], etc.
Private campaign: it will match user number with number in csv and send personal information.
I have a demo number, and backend. Write me if you are interested. hello (at) globalsend.com.ar

Thanks


demo plis

**Comment by davidneujahr** [comment]
hey testing

**Comment by davidneujahr** [comment]
Hey guys I am not a coder, but I stumbled across the website in search for a auto respond-er for whatsapp. Please if anyone can point me to the right direction in downloading a auto respond-er for whatsapp, or create me a bot to respond to whatsapp automatically I will pay what ever price it is. If someone can code and even add tweaks like respond to the person writing then block them after the auto responder I would love to pay a coder to build me my own custom bot for what'sapp Please anyone who wants to make good money contact me asap my whatsapp is (usa) +19144255408 (picture of a hot girl thats me lol ) email paperzink (at)gmail(.)com
