### ISSUE TITLE
(Legacy)Still getting Reason_ old_version to version 2.12.49

### ISSUE THREAD

**Issue by rs-renato** [tgalal/yowsup#669]
I'm getting an old_version reason when trying to request the code

python yowsup-cli --requestcode sms -c config

Failed, reason: old_version. Checking for a new token..
status: fail
reason: old_version

These insue was marked as closed before, but same with version 2.12.49
as following token data, the error persist..

"v": "2.12.49",
"r": "S40-2.12.49",
"u": "WhatsApp/2.12.49 S40Version/14.26 Device/Nokia302",
"t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1413401214298{phone}",
"d": "Nokia302"

**Comment by CODeRUS** [comment]
really? still using so outdated (for ages) version?

**Comment by rs-renato** [comment]
I'm in legacy version, and it was working till now, the problem is I need to register a new device.
So, in these legacy version I can't register any more? Just if I update to new Yowsup 2?

**Comment by CODeRUS** [comment]
you can get  token data from https://coderus.openrepos.net/whitesoft/whatsapp_scratch
but no idea if legacy registration code still valid

**Comment by rs-renato** [comment]
I will try get this token data and test it here, thanks!

So, the file src/Yowsup/Common/constants.py was updated in November,
so I wondered its still evoluting same as legacy version..

**Comment by rs-renato** [comment]
@CODeRUS , it's worked, Thank you!

the updated token data for legacy version is:


"v": "2.12.61",
"r": "S40-2.12.61",
"u": "WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302",
"t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1419900882708{phone}",
"d": "Nokia302"

**Comment by assegaf** [comment]
@CODeRUS 
https://coderus.openrepos.net/whitesoft/whatsapp_scratch

hi coderus, any update for the updated token for 2.12.68 ?
