### ISSUE TITLE
No handlers could be found for logger "yowsup.stacks.yowstack"

### ISSUE THREAD

**Issue by fabioviggiano** [tgalal/yowsup#671]
Hi everybody,
I'm sorry for my bad english, otherwise I' ll try to ask you a problem that I'm having with yowsup. I' m trying to run the Yowsup 2.0 Sample using Ubuntu. I' don't have any problems to run the demo folder, send and receive messages, etc.. 

The issue is with the Sample with 2 file: layer.py and run.py.

It returns me the following error:

No handlers could be found for logger "yowsup.stacks.yowstack"

I' ve looked for something, but I only read about two developers with the same problems; can someone help me to run this Yowsup Sample?

**Comment by widnyana** [comment]
that's not a big issue. just an info from python logging module that it can't find logging handler for `yowsup.stacks.yowstack`

to solve it, just register a logging handler for them.

**Comment by fabioviggiano** [comment]
import logging

# create logger with 'spam_application'
logger = logging.getLogger('yowsup.stacks.yowstack')
logger.setLevel(logging.DEBUG)

Like this? I have tried in this way but it continues to give the same error.

**Comment by fabioviggiano** [comment]
These are the two file:

- run.py

import logging

from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup import env
from layer import EchoLayer
from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator
 

CREDENTIALS = ("17277052319", "eURQTXheUs4ti86OOpH/JQbNkUM=")

 
if __name__==  "__main__":
    layers = (
            EchoLayer,
            (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
            YowCoderLayer,
            YowCryptLayer,
            YowStanzaRegulator,
            YowNetworkLayer
        )
 
    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client
 
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
 
    stack.loop()


- layer.py

from yowsup.layers                                     import YowLayer
from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_messages.protocolentities  import TextMessageProtocolEntity
from yowsup.layers.protocol_receipts.protocolentities  import OutgoingReceiptProtocolEntity
from yowsup.layers.protocol_acks.protocolentities      import OutgoingAckProtocolEntity
 
class EchoLayer(YowInterfaceLayer):    
    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):                                        
                if messageProtocolEntity.getType() == 'text':
                        self.onTextMessage(messageProtocolEntity)
   
    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
        self.toLower(ack)
               
    def onTextMessage(self, messageProtocolEntity):
                receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
 
                if 'Hi' in messageProtocolEntity.getBody():
                         antwort = 'HEY!'
                         self.toLower(receipt)              
                         self.toLower(TextMessageProtocolEntity(antwort, to = messageProtocolEntity.getFrom()))
 

How can i register the logging handler for yowsup.stacks.yowstack?

**Comment by widnyana** [comment]
try to put this on your `run.py`

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by fabioviggiano** [comment]
@widnyana 

Thank you a lot! Now, it returns me all the logs through output and; it writes:

DEBUG like -> Initializing stack - Constructed Stanza Regulator Layer - 

One Warning and at the end:

2015-03-06 12:21:40,747 - yowsup.stacks.yowstack - DEBUG - Constructed Interface Layer

Is it right or am I in fault?

**Comment by widnyana** [comment]
Yes it is. That was some debug message from yowsup. 

Have fun exploring yowsup!

-----Original Message-----
