### ISSUE TITLE
Wrong license in setup.py in 2.2.78 version

### ISSUE THREAD

**Issue by eribertomota** [tgalal/yowsup#675]
Hi,

The setup.py file says: license='MIT License' and ''License :: OSI Approved :: MIT License'". The generated yowsup2.egg-info file will follow this.

The file yowsup/registration/regrequest.py also uses MIT.

Note that if you don't write GPL-3+ in README or in file headers, we will consider GPL-3 in Debian.

Regards,

Eriberto

**Comment by eribertomota** [comment]
The file yowsup/registration/regrequest.py also uses MIT.

Note that if you don't write GPL-3+ in README or in file headers, we will consider GPL-3 in Debian.

Regards,

Eriberto

**Comment by tgalal** [comment]
Fixed in 8eed1ddc81ee8a72603b85c79cfcdaf278d306cd
