### ISSUE TITLE
WARNING: yowsup will break with Python 2.7.9 on Debian and others (SSL certificate verify failed)

### ISSUE THREAD

**Issue by eribertomota** [tgalal/yowsup#677]
Hi Tarek,

Yesterday I started to package the yowsup 2.2.78 in Debian (Sid, unstable). When testing the yowsup-cli, I received in my screen:

Traceback (most recent call last):
[...]
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

After several tests and searches on Google, I found/concluded that:

- The Python 2.7.9 enabled certificate validation by default for HTTP connections, see PEP476[1].

[1]  https://www.python.org/dev/peps/pep-0476

- The CA certificates are installed in Debian via package ca-certificates. The current version is 20141019[2]. Maybe this version doesn't have the 'Go Daddy' certificate used by 'v.whatsapp.net'. Is very important to say that ca-certificates-20141019 will be the official version for Jessie (future Debian Stable in one or two months) and is the current version in Sid.

[2] https://packages.qa.debian.org/c/ca-certificates.html

- To test the current ca-certificates we can do:

$ openssl s_client -connect v.whatsapp.net:443

or

$ curl https://v.whatsapp.net

In the first case the reply was (tested on Jessie and Sid, the relevant portions only):

eriberto@libra:~$ openssl s_client -connect v.whatsapp.net:443
CONNECTED(00000003)
depth=2 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify error:num=20:unable to get local issuer certificate
verify return:0

The second test:

eriberto@libra:~$ curl https://v.whatsapp.net
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

- I 'downgraded' the Python to 2.7.8 version[3] and the yowsup-cli worked fine when registering:

$ yowsup-cli registration  --requestcode sms --phone 556182xxxxxx --cc 55 --mcc 724 --mnc 02
INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":1805}

[3] http://snapshot.debian.org/package/python2.7/2.7.8-12/

I suppose that the your source code can request to Python to avoid the certificate validation if the Python version is >= 2.7.9 and if the auth fail. A command line option is a good idea to do this. However, the better option (alternative to an option as --no-verify-cert) is check if is ok the certificate used by WhatsApp.net and make available (in a readme) the procedures to user install a valid certificate from Go Daddy.

Cheers,

Eriberto

**Comment by ortimanu** [comment]
Do you have the steps to solve this using a python version >= 2.7.9?

**Comment by eribertomota** [comment]
2015-04-08 0:28 GMT-03:00 Manuel Ortiz <notifications@github.com>:

> Do you have the steps to solve this using a python version >= 2.7.9?
>

Hi,

No, I am not a Python programmer. I will wait a fix from Tarek to put the
new version in Debian (and Ubuntu, Mint, Kali, etc, by migration).

I think that have a way to ask to Python to ignore this fact and go ahead.

Regards,

Eriberto

**Comment by tgalal** [comment]
@eribertomota 

Thanks for the detailed description :) I added a potential fix for python 2.7.9

**Comment by eribertomota** [comment]
Thanks a lot!

I am adding a patch to 2.2.78 in Debian.

Cheers,

Eriberto
