### ISSUE TITLE
Set GroupProfileImage with yowsup?

### ISSUE THREAD

**Issue by capsload** [tgalal/yowsup#678]
Hello,

is there a one-line command available to set profile image for a group? like

./yowsup --demos groupprofile "jid@s.whatsapp" /path/to/image.png

??

**Comment by kuldippatel** [comment]
First of all, Is set profile picture for individual available? Did I miss?

**Comment by tgalal** [comment]
No set profile picture yet, but when it's there I don't think there would a one line command for it, it will most probably go inside yowsup demos --yowsup
