### ISSUE TITLE
no_routes again

### ISSUE THREAD

**Issue by dedmen** [tgalal/yowsup#684]
This is not generally a yowsup problem.
I dont like the idea to reopen #370 and as it seems to be a different problem i'll just create a new issue.
As stated in #370 and #625 im getting no_routes in trying to register an american phone number.
But its different than in the other issues.
I tried registering via:
* Yowsup on: 
 * -My Server in France
 * -My PC in Germany
 * -My PC via VPN to Sweden
 * -My PC via VPN to USA
* Android Virtual Machine with whatsapp on:
 * -My Server in France
 * -My PC in Germany
 * -My PC via VPN to Sweden
 * -My PC via VPN to USA

And none is working yowsup is giving me "no_routes" and the VM with Android and whatsapp shows me the equivalent error message just no_routes in more words.
I have yet to try the online solution stated in #625 but i dont think it will make a difference.
I tried it with 3 different american numbers from 2 different providers.
Does somebody know if theres something going on with Whatsapp in general?

And thats another issue i dont think is important enough to post... I need an American number because my German number doesnt receive any contact notifications like status and picture updates.

**Comment by catch2patch** [comment]
Which providers have you tried?

**Comment by dedmen** [comment]
Well "Providers" k7.net and simplevoicebox.com

**Comment by jlguardi** [comment]
Some K7 numbers are blocked (whatsapp sends no_routes) but 1 every 10 numbers worked for me.

**Comment by dedmen** [comment]
Oh you were right... The 3rd number i got worked. I tried a second which didnt work but then the third does. Thank you ^^
anybody knows anything about the other problem? 
when i do /contacts sync with my american number it syncs and i get notifications. 
But with my german number i dont get any notifications and i mostly dont get an answer to the contacts sync request. 
Only for the sync to my private number i get an answer but im still not getting notifications on status change.

**Comment by mutindaz** [comment]
I am getting the same error in another machine. On my development machine, which is local its working but when I move the same to an aws instance, I get the no_routes error.

**Comment by dedmen** [comment]
Maybe it checks if youre on a static ip address when registering.. Which totally makes sence.. Legitimate phones dont have a static ip.. Just register on your home machine and then use the credentials on your Server

**Comment by jlguardi** [comment]
@dedmen I think it has no sense. I've got static IP on my office and no problem during the register. Moreover, on 3G networks we have dynamic IP but not on wifi connections where public IP depends of the contract with your provider.

Has someone snif oficial request?

**Comment by dedmen** [comment]
We know Whatsapp is banning some Phone numbers its possible they are also banning certain ip ranges... Like the AWS... But you dont have to register on the Server you can also do that on a connection where it works.

**Comment by jlguardi** [comment]
You are right!

**Comment by mutindaz** [comment]
@dedmen that makes sense now.
