### ISSUE TITLE
What is iq, ib?

### ISSUE THREAD

**Issue by ngalongc** [tgalal/yowsup#685]
I am so fascinated by this project as I am learning python for half an year and keep trying to find project that amazed me. 
And then I found yowsup, which is insanely useful project and practical for me to control my raspberry pi through whatsapp!
So I really want to contribute to this project but I found it is not easy to learn yowsup from scratch.
Here is one of the question that bothers me the most,(which I have googled it for about half an hour and get nothing easy to understand),
there are seven protocolEntity, i can understand most of it but I really can't figure out what do iq, ib means. I don't know if I can ask this kind of silly question here. If not, I will delete this question. Thank you.

**Comment by CODeRUS** [comment]
iq is common request/reply nodes, ib is special nodes with offline messages count for example.

**Comment by ngalongc** [comment]
Thank you very much for your respond
However due of my limited knowledge, I still can't get the core concept of request/reply node nor special nodes with offline messages count.

**Comment by ngalongc** [comment]
After some inspection with the debug option of yowsup-cli,
My guess are ib node and iq node are sent by yowsup-cli to tell whatsapp I am still alive,
then whatsapp will reply.
This particular information is represented by iq node and ib node.

```    
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>
<iq xmlns="w:p" type="get" id="1">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="XXXXXXXXX@s.whatsapp.net" id="1">
</iq>

Iq:
ID: 1
Type: result
from: XXXXXXXX@s.whatsapp.net


```

**Comment by tgalal** [comment]
@ngalongc See [this](http://xmpp.org/rfcs/rfc6120.html#stanzas-semantics-iq) for IQ.
For ib, I think offline count is the only instance where I've seen ib stanzas.

You contributions are very welcomed :)
