### ISSUE TITLE
Echo Demo disconnected after some time idle

### ISSUE THREAD

**Issue by forewerton** [tgalal/yowsup#689]
I'm running the last version of Echo demo application and around 15 minutes after it started I got this debug message:

```
DEBUG:yowsup.layers.logger.layer:rx:
<iq type="get" xmlns="urn:xmpp:ping" from="s.whatsapp.net" id="1426541912-ping">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ping>
</ping>
</stream:error>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
```

How can I prevent yowsup from disconnect?
##

**Comment by opetmar** [comment]
same problem but with me it show "DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed" after 1 minute or less

**Comment by gautammaloo** [comment]
@forewerton @opetmar Check this out https://github.com/tgalal/yowsup/issues/648

**Comment by ThomasRgbg** [comment]
I have the same problem. I reduced the ping interval as mentioned in #648 down to 30 seconds. I have a stable connection for about 5 minutes, but then I get disconnected. Looks like a server side disconnect ? 

```
14:49:42 DEBUG:yowsup.layers.protocol_iq.layer:waitPong:ping queue size: 1
14:49:42 DEBUG:yowsup.layers.logger.layer:send:tx:
<iq xmlns="w:p" type="get" id="12">
</iq>

14:49:42 DEBUG:yowsup.layers.logger.layer:receive:rx:
<iq type="result" from="4915785709972@s.whatsapp.net" id="12">
</iq>

14:49:42 DEBUG:wa_layer:onIq:onIQ: Got iq (Ping reply)
14:49:52 DEBUG:yowsup.layers.logger.layer:receive:rx:
<stream:error>
<ack>
</ack>
</stream:error>

14:49:53 DEBUG:yowsup.layers.network.layer:handle_close:Disconnected, reason: Connection Closed
14:49:53 DEBUG:yowsup.layers.network.layer:handle_close:Disconnected, reason: Connection Closed
14:50:07 DEBUG:yowsup.layers.protocol_iq.layer:waitPong:ping queue size: 1
14:50:07 DEBUG:yowsup.layers.logger.layer:send:tx:
<iq xmlns="w:p" type="get" id="13">
</iq>

14:50:07 DEBUG:yowsup.layers.network.layer:handle_close:Disconnected, reason: Connection Closed
```

**Comment by ThomasRgbg** [comment]
I just found a possible reason, in my local application was 6539dfb915002c3744045b1efbc384b60f071675 not applied. I had a pile-up of msg read notification which does not acknowledged correct and maybe the server throwed me out.

**Comment by nihalsharma** [comment]
This thing is still happening! After a while the messages are not getting delivered. Any fixes?

**Comment by eduardomiranda** [comment]
Does anyone know how to solve that problem? I am stuck with that issue!
