### ISSUE TITLE
running yowsup from php

### ISSUE THREAD

**Issue by steve1982** [tgalal/yowsup#69]
Hello,

Any example of how to run intermediate 
with yowsup.py running and passing parameters from php to send a message or retrieving contact data form php?

Thankyou

**Comment by lorenzoPrimi** [comment]
@WhiteHatAlister I can't download that file, could you reshare it?
thanks

**Comment by erm3nda** [comment]
@WhiteHatAlister the mega link is not working https://mega.co.nz/#!NNZFxBaZ!EPVxUlHFcvZRz6iUsjdf4mE4x5AViTylAiK-JKx6k-E.

**Comment by wgcv** [comment]
i have this code is very simple in php only to send menssage! https://github.com/wgcv/WhatsappEnvioMensajes
if you want to try
104.236.230.65/index.php?numero=0199999999999&mensaje=MENSSAGE

**Comment by erm3nda** [comment]
Check that http://bitacora.eniac2000.com/?tag=yowsup

**Comment by pabloruan0710** [comment]
@AlisterAmo link is not working, please new link or exemple for mail pabloruan@outlook.com?

**Comment by subhamsuthar** [comment]
@AlisterAmo link is not working, please new link or exemple for mail subhamsuthar97@gmail.com ?
