### ISSUE TITLE
Define client receivers

### ISSUE THREAD

**Issue by ksketo** [tgalal/yowsup#691]
Hello. When I send a message to a number, through the yowsup client, this message is delivered on the watsapp app. Assuming that a 3rd party iOS client is using the whatsapp server to send a message, is there a way to choose the receivers of the message, so that it is delivered only on the iOS client recipient, but not on whatsapp iOS app? For example, in telegram you register your app and you get an app_id. Can something similar be done with yowsup?

**Comment by dedmen** [comment]
As far as i know.. No becasue i dont think XMPP supports such thing. Correct me if im wrong

**Comment by tgalal** [comment]
No it's not possible
