### ISSUE TITLE
Stream error

### ISSUE THREAD

**Issue by ResonantWave** [tgalal/yowsup#692]
I am getting a stream error few minutes after starting yowsup. I am also using the sample app provided. I think it is related with ack.
```
<stream:error>
<ack>
</ack>
</stream:error>
```

**Comment by CODeRUS** [comment]
not sending ack after receiving notification or message

**Comment by ResonantWave** [comment]
I assumed that, but I don't know what exactly to do. I'm using the sample code, and apparently it should send ack's

**Comment by CODeRUS** [comment]
check previous log and see after which messages ack is not sent.

**Comment by ResonantWave** [comment]
Just before the ack error:

```
<receipt participant="@s.whatsapp.net" t="1426860437" from="@g.us" id="1426860408-7" type="read">
<list>
<item id="1426860307-1">
</item>
<item id="1426860308-3">
</item>
</list>
</receipt>
```

**Comment by CODeRUS** [comment]
not this one. acks are sending for <message> and <notification> nodes

**Comment by ResonantWave** [comment]
Sorry for my incompetence then, but I don't know how to look.

**Comment by CODeRUS** [comment]
look from beginnig :)

**Comment by ResonantWave** [comment]
What should I look for?

**Comment by CODeRUS** [comment]
you should look for nodes with message and notification tags

**Comment by CODeRUS** [comment]
seems you just didn't added YowAckProtocolLayer

**Comment by ResonantWave** [comment]
Yes, I did added it. It is just the sample app (https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app). It includes the AckProtocolLayer in run.py

**Comment by ResonantWave** [comment]
It is strange, because the last message I can see in the log has an ack. After that, some <receipt> and finally the crash

**Comment by ResonantWave** [comment]
I don't know if this is normal, but there are 2 types of ack
```
<ack type="delivery" id="1426857499-27" class="receipt"
```
and
```
<ack count="21" t="1426860377" from="@g.us" id="1426860376-6" class="message">
```

**Comment by ResonantWave** [comment]
So, any ideas?

**Comment by igormsg** [comment]
i got this error too

**Comment by lcmeyer37** [comment]
I get this error for 'videos' and 'audio' media types. I notice that in Echo sample app and yowsup-cli when I receive this type of media I just get one grey check, so WhatsApp servers keep sending this data to my client and then it crashes with that error.

**Comment by tgalal** [comment]
#626

**Comment by gonzalosr** [comment]
Same problem here, but it seems to be a problem with delivery receipt acks.

Updated to the master branch today to no avail, maybe I am missing something in my code.

here is the full debug log:

```
DEBUG    30-04-2015 12:22 layer.py:13  : rx:
<receipt offline="3" retry="3" from="xxxxx@s.whatsapp.net" id="1430386282-39" t="1430386165">
</receipt>

DEBUG    30-04-2015 12:22 layer.py:8   : tx:
<ack class="receipt" type="delivery" id="1430386282-39">
</ack>

DEBUG    30-04-2015 12:22 layer.py:13  : rx:
<ib from="s.whatsapp.net">
<offline count="1">
</offline>
</ib>

DEBUG    30-04-2015 12:23 xmlstream.py:1683: Scheduled event: Session timeout check: ()
DEBUG    30-04-2015 12:23 layer.py:13  : rx:
<stream:error>
<ack>
</ack>
</stream:error>
```

Thanks in advance for any help on this issue

**Comment by trx222** [comment]
I also have this problem with php port -
https://github.com/mgp25/Chat-API/issues/76

**Comment by aesedepece** [comment]
I think the error is that now ACKs MUST contain the ```to="xxxxx@s.whatsapp.net"``` attribute.

**Comment by mgp25** [comment]
Fixed in php: https://github.com/mgp25/Chat-API/commit/07d28e15ce1a41793556230f61441d9705119d20

You can compare and fix it in python.

Regards

**Comment by aesedepece** [comment]
Thanks a lot @mgp25. You are our hero :)

**Comment by mgp25** [comment]
This should be the result, so you can compare:

```xml
tx  <message to="xxx@s.whatsapp.net" type="text" id="1430479701-3" t="1430479701">
tx    <body>test</body>
tx  </message>

rx  <ack from="xxx@s.whatsapp.net" id="1430479701-3" class="message" t="1430479701"></ack>

rx  <receipt from="xxx@s.whatsapp.net" id="1430479701-3" t="1430479709"></receipt>

tx  <ack to="xxx@s.whatsapp.net" class="receipt" id="1430479701-3"></ack>

tx  <ack to="xxx@s.whatsapp.net" class="receipt" id="1430479701-3"></ack>
```

**Comment by gonzalosr** [comment]
Wow. Thanks @mgp25

**Comment by davidpaulrosser** [comment]
Can someone upload a fix for this please? : )

**Comment by aguiraf** [comment]
Thanks @mgp25  for the hint! 
The outgoing ack not only needs the ```to="..."``` attribute but also a ```type="read"``` for those  ```<receipt>``` which carry that attribute.
Just pushed a PR that fix all these: #756

**Comment by emamirazavi** [comment]
many thanks Rafael.

**Comment by gonzalosr** [comment]
Thanks Rafael. Your fix works great.

**Comment by matteocontrini** [comment]
The fix is by @CODeRUS, after the issue was raised [here](https://github.com/hidespb/node-whatsapi/issues/43). You have to thank him...

**Comment by davidpaulrosser** [comment]
Thanks Rafael, works perfectly now.

**Comment by emamirazavi** [comment]
Hi, I again have this problem... apparently sometimes i have no ack
sent(tx) after reading some group messages!

Logged in! ??9393310102@s.whatsapp.net
2015-05-05 22:09:31,345 DEBUG rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1430842107" type="groups">
</dirty>
</ib>


2015-05-05 22:09:31,368 DEBUG rx:
<message retry="1" participant="??9359621023@s.whatsapp.net" t="1430833909"
from="??9103871392-1423772032@g.us" offline="1" type="media"
id="1430833865-2" notify="TEST TEST">
...

2015-05-05 22:09:31,369 DEBUG rx:
<ib from="s.whatsapp.net">
<offline count="1">
</offline>
</ib>

2015-05-05 22:10:31,402 DEBUG rx:
<stream:error>
<ack>
</ack>
</stream:error>

**Comment by volumetric** [comment]
Thanks a lot @aguiraf This took the whole 2 days for me, but finally a persistent connection.
