### ISSUE TITLE
Does not run install on Mac Yosemite

### ISSUE THREAD

**Issue by johnparra** [tgalal/yowsup#693]
This is the error:1 warning generated.
Building using 4 processes
clangclang: : warningwarning: : -framework Tcl: 'linker' input unused-framework Tcl: 'linker' input unused

clang: warning: -framework Tk: 'linker' input unusedclang
: warning: -framework Tk: 'linker' input unused
In file included from Tk/tkImaging.c:52:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/tk.h:78:11: fatal error: 
      'X11/Xlib.h' file not found
# include <X11/Xlib.h>

```
            ^
```

In file included from _imagingtk.c:19:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/tk.h:78:11: fatal error: 
      'X11/Xlib.h' file not found
# include <X11/Xlib.h>

```
            ^
```

1 error generated.
1 error generated.
clang: error: no such file or directory: 'build/temp.macosx-10.10-intel-2.7/_imagingtk.o'
clang: error: no such file or directory: 'build/temp.macosx-10.10-intel-2.7/Tk/tkImaging.o'
error: Setup script exited with error: command 'cc' failed with exit status 1
##

**Comment by pbotadra** [comment]
Try installing it via pip. Worked fine for me on Yosemite.

**Comment by ahumblenerd** [comment]
Installing with pip worked for me . You might need to give super user privilages to complete it . :)
