### ISSUE TITLE
Issue while istalling yowsup2.2.78 setup

### ISSUE THREAD

**Issue by vijayrajput** [tgalal/yowsup#694]
Hi ,

I am new to python , try to reading some material and tutorial.
I have installed spyder IDE and Python 3.4 to execute setup install command to install yowsup 2.2.78 

While installing i am getting following error. Please help 
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/pycrypto/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
Couldn't find index page for 'pycrypto' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
No local packages or download links found for pycrypto
error: Could not find suitable distribution for Requirement.parse('pycrypto')

Regards,
Vijay

**Comment by Goldbricker** [comment]
Whenever I've seen this getaddrinfo failed in the past it usually means it's trying to download something from the internet but isn't able to usually because no connection is available.

**Comment by dipankar** [comment]
Yeah, @Goldbricker is correct  @vijayrajput the error is because pycrypto is not installed and it was unable to download the package during installation.

**Comment by tgalal** [comment]
I'll assume it's working now

**Comment by vijayrajput** [comment]
Thanks, yes it is working now, some issue with my proxy setting to download content
