### ISSUE TITLE
WhatsApp Calls

### ISSUE THREAD

**Issue by rcetrangolo** [tgalal/yowsup#695]
Hi,

we'll be able to use WA phone calls with yowsup ? I mean, to call and to answer phone calls through the API.

thank you

regards

**Comment by erhan-** [comment]
I hope not.

**Comment by blackjack4494** [comment]
I still do not understand why you all are unhappy to see the call function implemented.
In my eyes it is important to see what functions are implemented in the official whatsapp application.
As no one is really trying to get the call function to work I looked into the code and found something.

Next to the expected functions like
Java_com_whatsapp_Voip_startCall
Java_com_whatsapp_Voip_endCall
Java_com_whatsapp_Voip_acceptCall
Java_com_whatsapp_Voip_rejectCall
Java_com_whatsapp_Voip_muteCall
.....

I could find this:
Java_com_whatsapp_Voip_startCallRecording
.....

Until now this option is not available for android users. And i doubt it will ever be available for us. I guess it is 'hidden' function to give whatsapp/nsa (whatever) the possibility to record calls in the background.
There is a lot more but this is just a brief overview.

**Comment by CODeRUS** [comment]
because whatsapp not worth it. if you need - go and implement it yourself.

**Comment by tgalal** [comment]
@rcetrangolo @blackjack4494 it's not a priority at the moment, at least until yowsup supports all non-calls related WhatsApp features. And even then, I don't think anyone would be motivated enough to work on it.
