### ISSUE TITLE
Whatsapp registration on virtual numbers not working?

### ISSUE THREAD

**Issue by viksit** [tgalal/yowsup#698]
Hi all,

Has anyone tried registration using virtual numbers from Google voice or Twilio recently? I've been unable to use it and I'm wondering if there's something weird going on? I know I have the right Twilio MCC and MNC codes, and for Google Voice, I'm using what worked for me before.

```
./yowsup-cli registration --requestcode sms --phone 1xxxxxxxx --cc 1 --mcc xxx --mnc xxx -d
..
..

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param
```

PS I've verified the registration works for a legitimate mobile number that already has whatsapp on it as a client.
##

**Comment by jlguardi** [comment]
I had this issue with some K7 numbers (some times I can register a number but usually the number is already blocked). I think WA has a list of virtual numbers.

**Comment by lucsansag** [comment]
I'm having the same problem, registration is failing with all virtual numbers I've tried from different sources.Are there any working right now?

**Comment by nico81** [comment]
Anyone succeeded?

**Comment by espeed** [comment]
Yes, I was able to register a Twilio number.

**Comment by viksit** [comment]
Which MCC and MNC were you using?

**Comment by espeed** [comment]
Did not use any. 

Enter your Twilio number here to get its values https://www.twilio.com/lookup

**Comment by viksit** [comment]
@espeed could you elaborate on how you registered your number then? When I've done this like mentioned in the first item in this thread, I get that error - with or without mcc/mnc codes.

Could you perhaps paste your command with the number redacted?

**Comment by espeed** [comment]
This worked for me...

```bash
$ yowsup-cli registration --requestcode sms --phone 1214XXXXXXX --cc 1
$ yowsup-cli registration --register XXXXXX --phone 1214XXXXXXX --cc 1
```

**Comment by viksit** [comment]
Ah thanks. And which version of yowsup?

**Comment by espeed** [comment]
@viksit Yowsup 2.2.78, cloned from master today.

**Comment by nico81** [comment]
I get an error:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"number"}
status: fail
param: number
reason: bad_param

Same number type (1214XXXXXXX)

**Comment by espeed** [comment]
Is the number already registered to another phone/client? 

Twilio does a 60-day check, and WhatsApp expires inactive numbers after 45 days so it shouldn't be the case of an already blocked number.

Make sure you deactivate all other clients it's registered to.

**Comment by assegaf** [comment]
45 days expire ? Do you have this info based on experience ?

**Comment by espeed** [comment]
See http://www.whatsapp.com/faq/en/general/24068052

**Comment by espeed** [comment]
See also http://www.whatsapp.com/faq/en/general/28030001

**Comment by nico81** [comment]
I got the number from twilio, I don't know if it's registered to another client.
I think the problem is local to yowsup, it's still associated to another (real) number, and it's working.
How can I unlink yowsup from actual number?

**Comment by espeed** [comment]
Delete the .storage dir

**Comment by nico81** [comment]
Nothing, same error.
I can't find .storage dir, I found .yowsup inside user home, no luck even deleting it.
"Bad Param" of param number seems like these numbers (I tried U.K. number too), so i think it's before to ask validation to WhatsApp server

**Comment by technocode** [comment]
LOL

**Comment by nerble** [comment]
Haven't been able to register numbers from Skype, despite having correct information etc.  Same error as viksit.  Have also had success with 'real' numbers with same client.

**Comment by intval** [comment]
Yep, doesn't work with virtual number for me, but worked with real numbers

But here what worked for me:
1. Go to twilio, Choose add new number
2. In the search form - choose type 'mobile' and 'sms' as capabilities
3. Pick any of the suggested phone numbers and check it against https://www.twilio.com/lookup
4. It should say `mobile` and **not** `voip` - than you'll not have the `bad_param number` error



> Laura (WhatsApp Support)
Feb 9, 15:29
Hi,
Thanks for your message.
Unfortunately, WhatsApp does not support VOIP numbers registration in WhatsApp.
These numbers are not currently supported for use with WhatsApp. Please use a real phone number with a real SIM card to use WhatsApp.
Thank you for your understanding.
Laura
WhatsApp Support Team


![](http://i.imgur.com/ZRboyWe.png)

**Comment by decade21** [comment]
Twilio mobile numbers don't work for me as well. WhatsApp recognizes the phone number and lets me send a verification SMS, but the message is never received.

**Comment by chenwayne** [comment]
Personnally tried working using Twilio number(type mobile)

Mark date: 15th Nov 2016

1. you need to select a phone number from Twilio, in advanced filter, make sure select mobile, (not local, nor Toll-free, you may need to change the country to find a country which support mobile numbers, USA does not support mobile numbers)


2. you may check at the link given above: twilio.com/lookup. to verify it is a mobile number. then you may use yowsup-cli to register 

3. When register, you can check your verification sms in twilio admin panel, even no need a physical mobile

**Comment by orige** [comment]
@chenwayne Is this still working?
I've tried with Australian numbers and didn't receive any messages.

**Comment by innogo** [comment]
Hey, you can ask WhatsApp directly through support to A-list your Google Voice number like myself. The reason behind the change from what they advised me was to prevent spam and it was happening from Certain countries in the East. I gave them my number, they verified it was a real account from my history and listed it. I had to do the same with Viber and Gemini Exchange. I have my GV number working on all social apps now. :) thought this might help anyone.... be patient with talking to support and send them valid details.
