### ISSUE TITLE
Adafruit : Internet Of Things Printer

### ISSUE THREAD

**Issue by deadindenver** [tgalal/yowsup#701]
Hello, i am working on an "Internet Of Things Printer" by Adafruit https://www.adafruit.com/products/1289

I am very new at this so please excuse my ignorance. but i am having trouble getting Yowsup to play ThermalWhats to play on my printer, and i absolutely love the idea of what you have done here.

I understand that i most likely have my MNC and MCC wrong Is there anyway to look this up?  i have read the wiki to no avail and tried quite a few of the different codes and two of my phone numbers , after that i wouldnt even know where do I enter my credentials into ThermalWhats.py?  

Also how to find the THERMAL PRINTER SERIAL ADDRESS? and where do i enter it into ThermalWhats.py?

I have attached some screenshots, any help would be greatly appreciated.

Please advice,

deadindenver

![screen shot 2015-04-04 at 1 05 40 pm](https://cloud.githubusercontent.com/assets/11642055/6994233/72cb7490-dace-11e4-937f-e263ded01247.png)
![screen shot 2015-04-04 at 12 51 32 pm](https://cloud.githubusercontent.com/assets/11642055/6994234/72cd1a3e-dace-11e4-82d6-bf3a93606d58.png)
![screen shot 2015-04-04 at 12 47 10 pm](https://cloud.githubusercontent.com/assets/11642055/6994235/72cecd3e-dace-11e4-9f2c-0abafc5a99ce.png)

**Comment by dedmen** [comment]
American CC is not 01 its 1 so your number starts with 1### 
And i dont think its a Yowsup issue...

**Comment by tgalal** [comment]
yup not exactly a yowsup issue
