### ISSUE TITLE
Set Nickname with yowsup 2.0 ?

### ISSUE THREAD

**Issue by capsload** [tgalal/yowsup#702]
Hello,

i was searching a way to change my Nickname using yowsup (the iOS Push nickname).

But were not able to find something. All sources used to be yowsup 1.0 

:(

How could i do it? (Im just using yowsup demos cli.)

**Comment by dedmen** [comment]
yowsup-cli
/presence name [name]                        Set presence name   
Should be it.
https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Command-line-client

**Comment by capsload** [comment]
Does it save that nickname when i close that process?

**Comment by dedmen** [comment]
It sets it to you Whatsapp Account so its stored on Whatsapp Servers

**Comment by capsload** [comment]
I did

/presence name "Bier Bot"

but it doesnt change :(

**Comment by dedmen** [comment]
What name is it showing?

**Comment by capsload** [comment]
Ok, when i use /presence name "Bier Bot"
and send a message, it shows "Bier Bot" as Push Notification Nickname.

But, when i /disconnect, and connect again with /L, it just shows the number instead of Bier Bot,


Its not saving the Nickname to WhatsApp Servers. :(

**Comment by dedmen** [comment]
Do you only check in yowsup or on an external whatsapp client? Try joining a group with yowsup and your private number then let yowsup send a message to the group and check if the right name is displayed there

**Comment by capsload** [comment]
IT works, but only if i type /presence name "NAME" before sending the message. If i disconnect the session and start it up again, and send a message again, WITHOUT THE PRESENCE NAME before, it shows just the number as nickname.

**Comment by dedmen** [comment]
Another way would be using the real Whatsapp app to set the nickname.. register the number on a virtual machine or a real phone.. than change nickname and picture there and then extract the login information from your phone and use that to login with yowsup... or just set the name on every yowsup startup

**Comment by capsload** [comment]
first methode is too risky for me, (got 20 sim cards banned from whatsapp so far messed it up).

thats my command i use currently:

./yowsup-cli demos --config bot.conf -s 49151XXX-141XXX "hello i dont have a nickname."

any idea how to include the nickname there? no way right? 

dang! :D, because it works partelly, with the presence thing, but it gets "resetted" after disconnect. :(

**Comment by dedmen** [comment]
you can modify yowsup-cli code so it first executes the set name command.. but your writing a bot as i see so you can just execute the command on first start and thats the easiest solution.
Im always using the first method.. theres really no difference between registering with yowsup and registering with the real app.. in the backend atleast...
With yowsup you get the login data directly.
With the real app you have to extract it which takes 2-5 minutes but then you can easily set picture status and nickname via the real app

**Comment by dedmen** [comment]
modify  yowsup/yowsup/demos/cli/layer.py https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L344

change

        def onSuccess(self, entity):
            self.connected = True
            self.output("Logged in!", "Auth", prompt = False)
            self.notifyInputThread()
to

        def onSuccess(self, entity):
            self.connected = True
            self.output("Logged in!", "Auth", prompt = False)
            self.notifyInputThread()
            if self.assertConnected():
                        entity = PresenceProtocolEntity(name = name)
                        self.toLower(entity)

**Comment by capsload** [comment]
Trying that out! Thank you <3

**Comment by capsload** [comment]
Hey man, after the try today, it didnt worked :(

**Comment by CODeRUS** [comment]
you do not see available presence node with nickname in debug output?

**Comment by dedmen** [comment]
What didnt work? Did it not execute the code or what?
another solution would be That.. But i dont really know python so... try it out ^^

        def onSuccess(self, entity):
            self.connected = True
            self.output("Logged in!", "Auth", prompt = False)
            self.notifyInputThread()
            presence_name("YOUR NAME")

**Comment by capsload** [comment]
Trying out (also in debug) in a few moments. Thank you guys for the help.

**Comment by capsload** [comment]
Didnt worked @dedmen  :(

Debug:

./yowsup-cli demos -d --config bot.conf -s 49151xxxxx "Testmsg, blame me for that"
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer -                                                                                                                                                              Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="49152xxx" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒~▒++▒▒▒e▒!+▒▒▒(:=▒
HEX:f37ec82b2badbb9765exxxxx
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒~▒[▒j▒o▒g▒8▒▒r▒)\M▒iψ▒▒߁▒▒▒o▒▒Y^\▒\▒,▒
HEX:17e1107eeb5bae6a906fc067fd38affxxxxxf81819cde6f92d559155e                                                                                                                                                             5c975cd310192c05b1
</response>

PuTTYDEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1420620825" expiration="145215682                                                                                                                                                             5" props="4" t="1428513311">
%޼▒D▒▒>▒<▒▒
HEX:cefc28d72cexxxxc8844dde8
</success>

4915118518535
DEBUG:yowsup.layers.logger.layer:tx:
<message to="49151xxxxx@s.whatsapp.net" type="text" id="1428513311-1">
<body>
Testmsg, blame me for that
HEX:546573746dxxxxx696b6f20666f722074686174
</body>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1428091408" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1428513312" from="4915xxxxx@s.whatsapp.net" id="1428513311-1" class=                                                                                                                                                             "message">
</ack>

**Comment by CODeRUS** [comment]
use code markdown please

**Comment by dedmen** [comment]
Censor your phone number if you dont want to let it get out.. As is see the on_success function isnt executed.  Else you would see the "Logged in!" Message...
Thats because you are not executing the yowsup-cli cli demo youre executing the sendclient demo which is in another file...
https://github.com/tgalal/yowsup/blob/master/yowsup/demos/sendclient/layer.py
but you would have to set all imports there and... Its too much of a hassle for me to do that now..

**Comment by capsload** [comment]
alright :(.

**Comment by capsload** [comment]
[connected]:/presence name "BierBot"
DEBUG:yowsup.layers.logger.layer:tx:
<presence name="BierBot">
</presence>

**Comment by capsload** [comment]
So its too much work to implement it to the sendclient demo right?

**Comment by dedmen** [comment]
Its doable in under 10 minutes im sure but not for me ^^ I may try it when
i have time to do it. Why are you using the sendclient demo anyway? If you
want your bot to receive mesages and show online youre better off using the
command-line demo or writing your own application.

**Comment by capsload** [comment]
Its PHP based, it sends messages to a WA Group when someone drinks a beer!

**Comment by capsload** [comment]
So im asking @CODeRUS @tgalal if you could add the "set nickname" thing in https://github.com/tgalal/yowsup/blob/master/yowsup/demos/sendclient/layer.py 

or tell me what i have to input so its working for each message :) thank you!

**Comment by dedmen** [comment]
http://pastebin.com/e48s5SG4 That may be enough.. Im not sure and i havent tried if it works.

**Comment by capsload** [comment]
Okay, i've replaced that https://github.com/tgalal/yowsup/blob/master/yowsup/demos/sendclient/layer.py with your paste code.
where should i set the nick? :P

**Comment by dedmen** [comment]
on Line 20
eigher 
    entity = PresenceProtocolEntity(name = "YOURNAME")
or
    entity = PresenceProtocolEntity("YOURNAME")
i think the first one

**Comment by capsload** [comment]
Yeah, included that, Message still coming as number, instead of Nickname. :(((

**Comment by dedmen** [comment]
Try adding a third parameter to all TextMessageProtocolEntity
like TextMessageProtocolEntity(message, to = phone, notify = "MY NAME")

**Comment by capsload** [comment]
Hah man, that finally worked!! thank you very much :)

**Comment by nurderfsv** [comment]
Hi,sorry for reoping this topic, but for it does not work as supposed in this. The nickname shown is the phone number. Can someone probably help me?
This is my code: 

```python
phoneNumber = self.normalizeJid("49xxxxxxxx")

  notifyUser = "MY NAME"

  self.toLower(TextMessageProtocolEntity("eyo", to=phoneNumber, notify=notifyUser)) ```

So I am getting the message but I'm not getting MY NAME as nickname.

**Comment by jegue** [comment]
me too! for a long time now! no fix yet! i think

**Comment by jodersus** [comment]
I use this inside my upmost layer and it simply works (code extract):

```
    def receive(self, entity):
      if entity.getTag() == "success":
        self.toLower(PresenceProtocolEntity(name = "wsap.me"))
      elif .....
```

Hope it helps.

Cheers,

**Comment by jegue** [comment]
I will try! and let you know how it goes, thankyou

**Comment by jegue** [comment]
yeap I can get to work with the /L and after /message send 1678...  hi, but when i use the yowsup-cli demos  -s does not show my name!! I am New to this! can you be more specific.
did a very crazy bot!  +55 61 9694-2271, Bring meaning to your metrics and stories to your dates.
just send a integer value! like a data 1978 or a 22 number! will tell you a real fact about the number
thanks for your help!

**Comment by jokebattle3** [comment]
All previous solutions do not work for me. I've done some debugging and found (with debug mode on) out that yowsup is not sending 
``` "<presence name="MYNAME">
</presence>" 
```
to the server.

I'm trying to set the name inside the onSuccess function with:
```
        entity = PresenceProtocolEntity(name = "my name")
        self.toLower(entity)
```

I have no clue why yowsup is not firing the function to send the presence tag to the server. Does anyone has an idea?

**Comment by jodersus** [comment]
Have you imported the protocol_presence layer?
```
from yowsup.layers.protocol_presence.protocolentities    import *
```

**Comment by jokebattle3** [comment]
@jodersus This solved the problem! Thank you very much!

**Comment by dwalke15** [comment]
Hi,

To add a bit more detail. The default stack built for sendclient does not include the YowPresenceProtocolLayer. Hence the above actions passes through the stack without action.

To add you need to edit stack.py under sendclient example. Add the import at the start:

from yowsup.layers.protocol_presence           import YowPresenceProtocolLayer
 

and then add YowPresenceProtocolLayer into each YowParallelLayer list under both paths of the if / else.

This will add presence processing and all of the above will work.
