### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by alucardsl** [tgalal/yowsup#704]
you could not mount a more detailed manual for windows?
I tried to install with step by step the main page however it still fails

**Comment by bbtimx** [comment]
Hey,

Downloadv and Install:
1. python-2.7.9.msi ( with pip and windows path )
2. vcredist_x86.exe
3. Win32OpenSSL-1_0_1L.exe
4. gcc-mingw-4.3.3-setup.exe
5. pycrypto-2.6.win32-py2.7.exe

run in cmd "python -m pip yowsup2 install"

OR

Download yowsup2 and extract into python27 install folder.
run in cmd:
1. cd [python27 install folder]
2. python setup build
3. python setup install

**Comment by tgalal** [comment]
not enough details
