### ISSUE TITLE
Forward incoming text/media via broadcast

### ISSUE THREAD

**Issue by pakgayaa** [tgalal/yowsup#709]
Hi,

@tgalal - Great work on the library. I have been exploring yowsup for sending messages to subscribers. I know that the video sending functionality is still WIP. However, is it possible to do something where i can intercept incoming messages from a fixed phone number, and forward those to a broadcast group? Since the message is already cooked and the media already uploaded, would it be possible to manipulate the xmpp in order to accomplish this?

Also, is there a way to do broadcast of images?

I have decent working knowledge of python, but am a bit lost right now as to whether or not this is possible (not very familiar with the whatsapp protocol/encryption). Any pointers to how I can accomplish this would be great.

Thanks!

**Comment by tgalal** [comment]
"intercept incoming messages from a fixed phone number, and forward those to a broadcast group"
Sure, just listen to incoming message then create and send a [BroadcastTextMessage](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_messages/protocolentities/message_text_broadcast.py). This would only work for text messages though, broadasting media (even already uploaded media) is still work in progress. 

I've just created #722 for that.
