### ISSUE TITLE
Error, phone number does not start with the specified country code

### ISSUE THREAD

**Issue by idigevian** [tgalal/yowsup#711]
Hey Tarek,

I ran the below command (with my correct phone number), but got an Error

./yowsup-cli registration -r sms -C 65 -p XXXX-XXXX -m 525 -n 05
Error, phone number does not start with the specified country code

I am running on OSX 10.8.1

If you can kindly guide me on what i might be missing or doing incorrectly then that will be extremely helpful. Let me know if you need any information from my side.

Regards,
Idi

**Comment by jlguardi** [comment]
Can you try with your phone number starting with 65 and without '-'. I mean:
```
./yowsup-cli registration -r sms -C 65 -p 65XXXXXXXX -m 525 -n 05
```

**Comment by idigevian** [comment]
prefixing the phone number with the country code worked!

Thank you very much!!!

Regards,
Idi

**Comment by sagargulati** [comment]
I am trying this one:
./yowsup-cli registration -p 20xxxxxxxx -C 1 -r voice
Same error:
Error, phone number does not start with the specified country code

**Comment by jlguardi** [comment]
If this is a USA number, your command should be:
'''
./yowsup-cli registration -p 120xxxxxxxx -C 1 -r voice
'''

**Comment by Ruddymarquez** [comment]
yowsup-cli registration --requestcode sms --config-phone +584127885694 --config-cc 58 --config-mcc 734 --config-mnc 02
E 2022-03-08 14:38:04,771 yowsup.config.manager - Could not find a config for profile=+584127885694, paths checked: +584127885694:/home/ruddy/.config/yowsup/+584127885694/config.json:/home/ruddy/.config/yowsup/+584127885694/config.yo
Error, phone number does not start with the specified country code
