### ISSUE TITLE
Echo Client  

### ISSUE THREAD

**Issue by dickenjose** [tgalal/yowsup#712]
Hello , I appreciate the great work done in Yowsup , i was watching the documentation , really long python was not reviewing a tutorial achieved finally turning a spotlight from whatshapp with the example of (echo client) I have the following problems or questions:
1. when I run run.py everything works perfectly but the connection drops in a few minutes sometimes more sometimes less, as I can make the connection is longer or not disconnected ??
2. which part of the code which sends the message back , as I want to receive another message on my cell when you run that action not quite understand very well the code ( I'm with a tutorial and I'm new ) .
   Please like would have to do the same layer.py code to send messages or alerts to the number that sent the message.
##

**Comment by jlguardi** [comment]
I'll try to answer:

1.- If you are using last versión, you need to include protocol_iq layer in layer.py to start a ping thread which keeps alive the connection. I think this layer is not used in this example to keep as simple as posible. 
2.- onTextMessage and onMediaMessage resend input message to the sender. You can edit both to change demo working.

**Comment by dickenjose** [comment]
Thanks for your help , but as I can include protocol_iq in layer.py
2 and I can at this myself layer.py include the part for sending whatsaap Raspberri to help me with this problem I have mad because even I can not solve and understand very well the code .

**Comment by dickenjose** [comment]
not like putting the iq protocol ?? for the session lasts all the time here I have my code where I put the protocol .. ???

from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_messages.protocolentities  import TextMessageProtocolEntity
from yowsup.layers.protocol_receipts.protocolentities  import OutgoingReceiptProtocolEntity
from yowsup.layers.protocol_acks.protocolentities      import OutgoingAckProtocolEntity
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
import os





class EchoLayer(YowInterfaceLayer):

    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        #send receipt otherwise we keep receiving the same message over and over

        if True:
        	receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
            	outgoingMessageProtocolEntity = TextMessageProtocolEntity(
                messageProtocolEntity.getBody(),
                to = messageProtocolEntity.getFrom())

    	self.toLower(receipt)
   	self.toLower(outgoingMessageProtocolEntity)
	send = (outgoingMessageProtocolEntity.getBody())
	global send
	

    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
        self.toLower(ack)
	global send
	if (send == "On"):
		GPIO.output(17,GPIO.HIGH)
	elif (send == "Off"):
		GPIO.output(17,GPIO.LOW)
 	else: 
			os.system ('sudo python send.py')

**Comment by dickenjose** [comment]
using the example and my little python conocimineto achieve light a LED with On and off with Off , the last else want to display a message that says " try off or on" but not how to send messages within that connection that po is certainly not indefinitely , cut time to time and I have to restart setup.py please help thanks ...

**Comment by dickenjose** [comment]
Tgalal Dear Sir , thank you for the work I do I tell him I was fine, finally achieves send messages from the example echo client that public , which incidentally was my mistake not read all the documentation .
Now I have the following problem is still not like having to run the run.py this not finalize anything, is currently about 20 minutes or so and cut run.py process . Please I hope you can help me with this as I have no idea which depends the line is active .
