### ISSUE TITLE
Question: How to know who has sent a message in a group

### ISSUE THREAD

**Issue by idigevian** [tgalal/yowsup#714]
Hi There,

I am able to receive messages sent to a group and also send messages to a group. However, when i receive a message from a group, i am not able to understand who all sent that message.

In below example it is not clear who sent the message. Is it possible to get hold of the message sender, when messages are sent to a group ?

=============================================================================
[XXXXXXXX-1422590545@g.us(15-04-2015 05:23)]:[1429046492-37]	 Happy Good Friday!
Message 1429046492-37: Sent delivered receipt
[connected]:

[XXXXXXXX-1422590545@g.us(15-04-2015 05:24)]:[1429046363-24]	 Thank mate
Message 1429046363-24: Sent delivered receipt
[connected]:

[XXXXXXXX-1422590545@g.us(15-04-2015 05:24)]:[1429046363-26]	 Wish you the same
Message 1429046363-26: Sent delivered receipt
[connected]:
=============================================================================
 
Regards,
Idi

**Comment by gojigeje** [comment]
:+1: 
any updates for this issue?

**Comment by dedmen** [comment]
run yowsup-cli with the -d parameter
