### ISSUE TITLE
Basic Python script sends message to specific number.

### ISSUE THREAD

**Issue by TheCrow** [tgalal/yowsup#718]
Hello guys,

I have accomplished the yowsup-cli registration and send a message with the yowsup-cli demo. :+1: 

I am quite new to Python and I would like to integrate Yowsup in an existing Python script so it can send a whatsapp message to a specefic number. Thats the only feature I would like to use. (it is for a simple notification) 

It would be great if someone could help me out, I think there are alot of people with little knowledge in Python who would love to use this and understands the basic.

Thanks in advance

**Comment by jlguardi** [comment]
Have you tried to use sendClient demo inside your script using os.system("sendClient ....")

**Comment by TheCrow** [comment]
Well I am not sure if i am able to use it, because you have to connect to the whatsapp server before you can use the send client command?
I am looking for a simple sample script that I can study and use.

**Comment by jlguardi** [comment]
All commands with yowsup require to connect before. SendClient is the simplest example which connects and sends text message. It can be used from an external code as an synchronuos call with os.system.

**Comment by TheCrow** [comment]
in Yowsub/Demos/sendclient folder I find 3 files: __init_.py , layer.py and stack.py I cannot find the place where I can put my login credentials or  a number to send an message.
I think a lot of users included me would be very grateful if there is a script where you can put the needed information and send the message. (like the cli demo /send message)

**Comment by tgalal** [comment]
> yowsup-cli demos --help-config
```
############# Yowsup Configuration Sample ###########
#
# ====================
# The file contains info about your WhatsApp account. This is used during registration and login.
# You can define or override all fields in the command line args as well.
#
# Country code. See http://www.ipipi.com/help/telephone-country-codes.htm. This is now required.
cc=49
#
# Your full phone number including the country code you defined in 'cc', without preceding '+' or '00'
phone=491234567890
#
# You obtain this password when you register using Yowsup.
password=NDkxNTIyNTI1NjAyMkBzLndoYXRzYXBwLm5ldA==
#######################################################
```

yowsup-cli demos --send 49xxxxxxxxxx "Hello World"
