### ISSUE TITLE
How can I send Image on whatsapp ?

### ISSUE THREAD

**Issue by niravtrivedi** [tgalal/yowsup#719]
Hi 

Trying to send image on whatsapp but I cannot sent it.Getting import error " ImportError: No module named Yowsup.connectionmanager

Script executing using simple python command : 
http://sirpoot.blogspot.in/2014/11/using-yowsup-to-send-audio-and-video.html
script is downloaded from above url.

Please help me , where i'm doing mistake(s)

**Comment by jlguardi** [comment]
Do you have set PYTHONPATH environment variable as described in yowsup install tutorial?

**Comment by tgalal** [comment]
That guide was in legacy yowsup, it's not maintained anymore. Here is [documentation](https://github.com/tgalal/yowsup/wiki/Yowsup2:-Upload-and-send-Media) on how to do this with yowsup2.

**Comment by niravtrivedi** [comment]
Thanks @tgalal and @jlguardi for quick help.It's done sending video from cli, added cli command in cli_demo to send video.

Thanks again :)

**Comment by xwanyiri** [comment]
@niravtrivedi does your solution for sending video still work?

**Comment by leowidodo** [comment]
I found this on youtube. Demo for sending message and image using python.
https://www.youtube.com/watch?v=sSGYWdcj1HU
