### ISSUE TITLE
Getting the name of the person on yowsup-cli

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#723]
Hey people I have a question!

When I receive a message I can just get the phone number of the person who sent it. Can I get the name of that person too? Even if that person didn't add me as a contact?

**Comment by dedmen** [comment]
You get the name too... start in debug mode and youll see the other persons name in the notify parameter

**Comment by lcmeyer37** [comment]
Thanks I see the notify variable in notification.py. But, I'm kinda confused how to get this variable if someone sends a message.

**Comment by lcmeyer37** [comment]
Thanks man! Helped a lot!
