### ISSUE TITLE
a couple of bugs in IncomingReceiptProtocolEntity

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#729]
1) in toProtocolTreeNode() : 
node.setAttribute("1" if self.offline else "0")  missed key "offline"
2) In fromProtocolTreeNode:
node.getAttributeValue("timestamp") used instead of node.getAttributeValue("t") 
3) in __str__ sometimes "\n%s" instead of "%s\n"

**Comment by tgalal** [comment]
Thanks for reporting, fixed in bd94425a9e11b74ecda9693141bf121c5e1835e4
