### ISSUE TITLE
Legacy - Old version

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#734]
How to fix the old version in yowsup legacy ?
##

**Comment by awesomebytes** [comment]
This worked for me:
https://github.com/rs-renato/yowsup/commit/c635eec8d968ad9489cb509ec07298a881491649

**Comment by rami-dabain** [comment]
It is working this way i confirm. merge requested ?

**Comment by awesomebytes** [comment]
I've got no time right now, if you could do it would be nice. I fixed it
locally only.

**Comment by awesomebytes** [comment]
It stopped working again, I got a new token from:
https://github.com/sumppen/WhatsApi4J/blob/bd1de290e8f46a65c88b5681ccd8ae8f3c2d5a91/src/main/java/net/sumppen/whatsapi4j/WhatsApi.java

**Comment by mgp25** [comment]
@awesomebytes there is a pull request pending for approval already.

Use this always: https://coderus.openrepos.net/whitesoft/whatsapp_version

**Comment by aesedepece** [comment]
PR is https://github.com/tgalal/yowsup/pull/790
