### ISSUE TITLE
Prevent media streaming 

### ISSUE THREAD

**Issue by mutindaz** [tgalal/yowsup#735]
How do I prevent media streaming from my application?

This is a small fix that I have tried.
```python
message_type = messageProtocolEntity.getType()
if message_type == "text":
    #process my message here 

# then send reciept of the message 
receipt = OutgoingReceiptProtocolEntity(message_id,message_from)
self.toLower(receipt)  
```

This is the error that I get if someone tries to send a media message. Does it mean that it streams by default and how can I prevent this?. Thanks

```python
DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ack>
</ack>
</stream:error>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ack>
</ack>
</stream:error>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
````

**Comment by tgalal** [comment]
You cannot prevent receiving media. You must at least send receipt for then receiving them OutgoingReceiptProtocolEntity otherwise you end up with stream error
