### ISSUE TITLE
Whatsapp network packets

### ISSUE THREAD

**Issue by kwiiby** [tgalal/yowsup#740]
How do you built this API? sniffing network packets, understanding and then simulating?

Is it hard to decipher whatsapp packets?

Packets are modified all the time?

Thanks, I really want to help keep API updated, each commit has taken a long time.
##

**Comment by dedmen** [comment]
packet sniffing is kinda hard... I already tried it but Whatsapp only accepts the real SSL Certificate.. I think hes decompiling the apk package and just looking at the source
