### ISSUE TITLE
Auth Error, reason not-authorized

### ISSUE THREAD

**Issue by addodelgrossi** [tgalal/yowsup#746]
I am found error "Auth Error, reason not-authorized", but I was using over 3 months without problems.

I tried using existsrequest.py , but I have a question in the utilization:

WAExistsRequest(cc, p_in, idx)
cc = contry code
p_in = Phone Number ?
idx ??

Would you help me?
Thanks

**Comment by aesedepece** [comment]
Something happened with every WhatsApp API (yowsup, Loqui IM, Chat API, etc.) and it seems none is working.

**Comment by aesedepece** [comment]
Pull request fixing this → https://github.com/tgalal/yowsup/pull/748

**Comment by lcmeyer37** [comment]
This fixed #745, thank you! But, trying to register on windows I'm getting #743. (Windows Python 3.0+)
