### ISSUE TITLE
old_version ?

### ISSUE THREAD

**Issue by altair86** [tgalal/yowsup#747]
Cant register using:
```
sudo yowsup-cli registration -p XXXXXXXXXX -r sms --cc X
```
There is error:
```
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version
```
There is versions:
```
yowsup-cli v2.0.9
Using yowsup v2.2.78
```

**Comment by aesedepece** [comment]
Update to last changes. Registration token changed recently.

**Comment by altair86** [comment]
Its magic :)
Thank you

**Comment by aesedepece** [comment]
You received the SMS, right?
But can you succesfully login? There are many worrying reports of '''<not-authorized>''' reports at the moment and we are trying to figure out what's going on.

**Comment by domingopa** [comment]
@aesedepece 

hello
Did you see this problem?
https://github.com/mgp25/Chat-API/issues/661
randomly from yesterday we did not receive the mss.

Did you have news?

greetings and thanks

**Comment by domingopa** [comment]
We have strange behaviors. Very worrying
:o:

**Comment by lcmeyer37** [comment]
People I also commented this problem on #743, this is the error of registration given on Windows, and it also shows the equivalent one on Linux. I think it's also related to #745

**Comment by tgalal** [comment]
4fcca47110ffd56fbae53e116ae6f52afa7b7095  fixes registration "old_version" error

**Comment by zandervalle** [comment]
Hey there,
I'm new to this all and installed yowsup through pip2. How do I upgrade or even see the version I have? 'cause I've got the status: fail; reason: old_version; too.
Thanks
Zander

**Comment by zandervalle** [comment]
Sorry for disturbing, got update by git clone.
Now it works!
