### ISSUE TITLE
Can sombody provide the latest WhatsApp XAP?

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#75]
Hello everyone,

I'd like to study the Windows Phone version of WhatsApp. I have the XAP files for version 2.8.4 

However I'd like to have the latest version. You can download the XAP from the Windows Phone marketplace if you have  a Windows Phone, however I don't have one.

Can somebody download it and share it?

Kind regards,
Swen
##

**Comment by 3dluis** [comment]
This is soluction. https://developers.facebook.com/docs/whatsapp

Official API of Whatsapp
