### ISSUE TITLE
Authentication Failure out of a sudden

### ISSUE THREAD

**Issue by abloch** [tgalal/yowsup#750]
I use Yowsup the same way for some time now and this morning, it suddenly sent me "Authentication Failure".
anything changed? maybe whatsapp found a way to block yowsup?

**Comment by davidpaulrosser** [comment]
I made the same mistake.. [#767](https://github.com/tgalal/yowsup/issues/747)

**Comment by hbtsmith** [comment]
I guess something has changed on whatsapp side, I am having the very same problem now...

**Comment by capsload** [comment]
Same problem here!

**Comment by capsload** [comment]
fix https://github.com/tgalal/yowsup/commit/6345f77b56e474f0eb6143b1363a789254da9ccd

**Comment by tgalal** [comment]
Yup 6345f77b56e474f0eb6143b1363a789254da9ccd should fix this

**Comment by abloch** [comment]
sorry, this is still unauthorized failure for ,e even after the upgrade...

**Comment by abloch** [comment]
thanks a lot @capsload !!! well done
and @tgalal - I wish I could find a way to thank you enough for this awesome awesome project
