### ISSUE TITLE
How to handle reconnections?

### ISSUE THREAD

**Issue by davidpaulrosser** [tgalal/yowsup#752]
Hi,

My app keeps dropping connection every 2 minutes or so. Do you know why this is happening?

I get a stream error message before it drops:

```
DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ack>
</ack>
</stream:error>
```

**Comment by gonzalosr** [comment]
Yes, it's dropping connections because correct acks are not being sent due it seems to changes in the whatsapp API.

I've referenced my error here: #692

**Comment by davidpaulrosser** [comment]
Closing as it's now been fixed.
