### ISSUE TITLE
Not-authorized / but authorisation dont fail

### ISSUE THREAD

**Issue by Schwertspize** [tgalal/yowsup#754]
If i try to use
yowsup-cli demos -c config.cfg -d -s 43xxxxxxx test
it failes with

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="436763024575" mechanism="WAUTH-2">
;??Ч?[??n#ͥ?2??.??Z1??j[?+???b????u,?*??
HEX:060f3bb1f6d0a78e5bcfd66e23cda5e332e99af22e8ed4115a31a63f6a5be72bd3d1db629cb9abeb752c832ac2cc
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
*??%???ɏ?C??1??j???
HEX:2aa7fc25d9dcd6c98f974392ae31b18e6a9497bf
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
????&3ዝkX??
           #?2?p????T|.???.P???ǲN??tH?
HEX:a9e6901deac42633e18b9d6b5889810c23fd32b670900492a7e2547c2ef8fcd32e50add4e7c7b24ebde374489a1a
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

If i try 
yowsup-cli demos -c config.cfg -d -y
then /L
it says 

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="436763024575" mechanism="WAUTH-2">
??!?Ч?[??n#ͥ?2??.??Z1??j[?+???b????u,?+??
HEX:fefb217ff6d0a78e5bcfd66e23cda5e332e99af22e8ed4115a31a63f6a5be72bd3d1db629cb9abeb752c832bc7c9
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
?]?2??I???A?<)
HEX:13e85df60e32b7011511a04989f1e9b2419c3c29
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
n? x?
     ,?O???]ɱ??i????)??И????ə???ŅlMH7
HEX:6ec12078990b2cc7114f9493835dc9b1a9b069ae88f2d629a5f0d098fac61eaad6c999188486dd01c5856c4d4837
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1419960848" expiration="1451496848" props="4" t="1430486907">
??5?``???E??J?32
HEX:a10db1cb35aa0e7f6060a6bdf845e1e84ae03332
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
Auth: Logged in!
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>

[connected]:

and i can send messages.

My config:
cc=43
phone=43xxxxxxxxxx
password=Udixxxxxxxxxxxxxxxx/8=

**Comment by hbtsmith** [comment]
I am having the same problem now. Probably whatsapp have changed something in its protocol...

**Comment by Schwertspize** [comment]
It's since May 1st. (I think 00:00)
Yes probably WhatsApp changed something...

**Comment by capsload** [comment]
Same here!

**Comment by capsload** [comment]
fix https://github.com/tgalal/yowsup/commit/6345f77b56e474f0eb6143b1363a789254da9ccd
