### ISSUE TITLE
Handling Calls

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#755]
Hey people, I noticed that now when I run my app client it can receive calls from other users. So, I actually HAVE to handle the calls coming, so I don't get socket errors after from the program. Do you know how to properly handle the calls? Or, how to just handle messages, properly ignoring other types of contact without getting any bugs on my app?

Thank you,

Lucas Meyer.

**Comment by aguiraf** [comment]
Same problem here.
This seems related to #692 and recent wa changes in the way of managing ```<ack>``` tags.
I think we should reply to  ```<call>``` tags with a proper ```<ack>``` , but this is not yet handled by yowsup. let's study a bit...

**Comment by 0xTryCatch** [comment]
Which environment are you guys using? I guess Android?

**Comment by lcmeyer37** [comment]
Windows and Python 3.0+

**Comment by 0xTryCatch** [comment]
I mean Yowsup environment

**Comment by lcmeyer37** [comment]
Windows and Python 3.0+, yowsup v2.2.78 after I applied the fix #748 by @aesedepece

**Comment by 0xTryCatch** [comment]
You don't seem to get my question. Anyway, switch your Yowsup environment from Android to S40 to avoid calls (but you will loose encryption).

**Comment by lcmeyer37** [comment]
Sorry, I really didn't understand it. How do I change the environment in my python program? Never had to take a look at this before.

**Comment by aguiraf** [comment]
needed a bit to realize,
``` env.CURRENT_ENV.getResource() = Android-2.12.68```
so we should switch to S40?  trying...

**Comment by lcmeyer37** [comment]
__init__.py on /env folder. Set CURRENT_ENV = S40YowsupEnv()

Thanks @0xTryCatch

**Comment by assegaf** [comment]
easy, change to S40 no more calls, currently this api Dont Support Call Receive/Send ..

**Comment by aesedepece** [comment]
Setting environment to S40 avoids receiving calls, but breaks Axolotl cypher.
I think we can't consider this solved.

**Comment by mgp25** [comment]
@assegaf you can try latest commits to support call from Chat API

Regards

**Comment by aesedepece** [comment]
Cool, thanks for the reference implementation @mgp25.
If nobody here minds, I assign this issue to myself :)

**Comment by lcmeyer37** [comment]
Ok @aesedepece . I reopened the issue! haha

**Comment by aesedepece** [comment]
I already got it working. Now I'm writing the tests and running the new code with several lines and calling from different contacts.
I'll send tge pull request later today :)
