### ISSUE TITLE
Not authorized using send client

### ISSUE THREAD

**Issue by ronaldlee82** [tgalal/yowsup#757]
Anyone know how to fix the issue?
yowsup suddenly not-authorized when using the send client. I can login using Yowsup command line client. 

yowsup-cli demos -c /root/.yowsup/auth -s XXXXXXXX "test"
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Authentication Error: not-authorized

yowsup-cli demos -c /root/.yowsup/auth -y
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:

**Comment by capsload** [comment]
same here!

**Comment by capsload** [comment]
fix https://github.com/tgalal/yowsup/commit/6345f77b56e474f0eb6143b1363a789254da9ccd

**Comment by ronaldlee82** [comment]
fixed! thanks capsload!
