### ISSUE TITLE
check account

### ISSUE THREAD

**Issue by wormen** [tgalal/yowsup#758]
Hello
Tell me, how can I check on the number is registered account?
seen previously I asked this question, but there are links do not work

**Comment by tgalal** [comment]
You need to send a [GetSyncIqProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_get.py)

You will get as a result [ResultSyncIqProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_result.py) with the following attributes:

- **inNumbers**: Registered WhatsApp numbers
- **outNumbers**: Numbers not registered on WhatsApp
- **invalidNumbers**: Invalid numbers 

If you are using yowsup-cli command line client demo, then you can use:
> /contacts      sync           [contacts]                    

Contacts should be comma separated phone numbers, with no spaces

**Comment by wormen** [comment]
>/contacts sync [contacts]
This is not an option, since it is designed for numbers added earlier,  I need to check that had not yet been added to the contact list

**Comment by DaurenD** [comment]
Hello, I'm new to python. What do you mean by:

> You need to send a GetSyncIqProtocolEntity

I just have to initialize GetSyncIqProtocolEntity object? How to actually send sync request?
