### ISSUE TITLE
Disconnected despite --keepalive

### ISSUE THREAD

**Issue by Ready2X** [tgalal/yowsup#76]
Hey there, I tried to listen for messages with param -k, but after three minutes the connectionmanager diconnect me 

What I´m doing wrong?

macbook:src Udo$ python yowsup-cli -c /Users/Udo/Downloads/entwicklungskram/yowsup-master/src/config.txt -l -k -a
Connecting to c.whatsapp.net
Authed 491523954XXXX
491525872XXXX@s.whatsapp.net [03-02-2013 06:51]:test
491525872XXXX@s.whatsapp.net [03-02-2013 06:54]:Test
Disconnected because closed

**Comment by jlguardi** [comment]
Deprecated.
