### ISSUE TITLE
Getting fail status 

### ISSUE THREAD

**Issue by niravtrivedi** [tgalal/yowsup#760]
Hi 

(1)
I'm running below command to get registration code.
cmd : ./yowsup-cli registration --requestcode sms --config mywhatsup.config
Outpur : INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

(2)
i'm little bit confuse, using below example to send media what should in stack file
https://github.com/tgalal/yowsup/wiki/Yowsup2:-Upload-and-send-Media

please help me where i m wrong .

Nirav

**Comment by Gurzo** [comment]
i solved the first issue, upgrading yowsup from git (git clone .. python setup.py install) instead of pip install --upgrade

**Comment by tgalal** [comment]
@niravtrivedi needs to contain YowMediaProtocolLayer. Something like this is sufficient:
> stack = YowStackBuilder().pushDefaultLayers(encryptionEnabled).push(yourLayer).build()

**Comment by niravtrivedi** [comment]
@Gurzo thanks for quick response
@tgalal thank you too for quick response and give valuable, Ok i'll try with this. What i had done : updated code in demos->sendclient->layer.py added code for send media (copied from demos->cli) and keep stack.py unchanged but getting media sending error. 

I could finish this will mail example code.

**Comment by niravtrivedi** [comment]
@all thanks for quick response

Will re-open issue if need more help
