### ISSUE TITLE
Status Fail due to Older Version

### ISSUE THREAD

**Issue by johnddep** [tgalal/yowsup#762]
Hi,

I have made the change: "python-axolotl>=0.1.7" in the setup.py file and installed again, but still I am getting the error:

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

Kindly help.

**Comment by ivandavid77** [comment]
Same here, but problem presents when register phone, yowsup updated today, the phone first was registered with official whatsapp client, then stopped and unistalled, phone was restarted.
Command (number from Mexico):
$yowsup-cli registration --requestcode sms --phone 521228XXXXXXX --cc 52 --mcc 334 --mnc 020
Response:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version

My configuration:
$ uname -a
Linux wasender1 3.11.0-12-generic #19-ubunty SMP Wed Oct 9 16:12:00 UTC 2013 i686 i686 i686 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:        13.10
Codename:       saucy

$ python --version
Python 2.7.5+

$ pip list
apt-xapian-index (0.45)
chardet (2.0.1)
distribute (0.7.3)
Landscape-Client (13.7.3)
PAM (0.4.2)
Pillow (2.8.1)
pip (6.1.1)
protobuf (2.6.1)
pycrypto (2.6.1)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.8.9.1ubuntu1)
python-axolotl (0.1.7)
python-axolotl-curve25519 (0.1)
python-dateutil (2.4.2)
python-debian (0.1.21-nmu2ubuntu1)
requests (1.2.3)
setuptools (15.2)
six (1.9.0)
ssh-import-id (3.19)
Twisted-Core (13.0.0)
urllib3 (1.6)
yowsup2 (2.2.78)
zope.interface (4.0.5)

any ideas???

**Comment by rami-dabain** [comment]
I confirm same issue . can't register due to new version

**Comment by valdekjr** [comment]
Hi, same here. not able to register due to new version.
./yowsup-cli registration --phone 55XXXXXXXXXXX --cc 55 --requestcode sms --debug
Number from Brazil

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}
status: fail
reason: old_version

**Comment by valdekjr** [comment]
Sorry, after clone as ivandavid77 mentioned, looks like it worked. Checking.

**Comment by tgalal** [comment]
@johnddep did you pull latest sources or made that change yourself?

Also I updated pip yesterday so upgrading through pip should also work. Please try and post result

**Comment by alain061191** [comment]
if response of "yowsup-cli demos -v" not equals  "yowsup-cli v2.0.9 Using yowsup v2.2.79" then
execute this steps:

1.1 = pip install yowsup2
1.2 = pip install yowsup2 --upgrade (if error then re-execute to solve)

2.1 = yowsup-cli registration --requestcode sms --phone YOUR_PHONE --cc XX --mcc XXX --mnc XXX -d
2.2 = yowsup-cli registration -R CODE

3.1 = yowsup-cli demos -d -c "YOUR_PATH"/config.example -s YOUR_PHONE "New updape yowsup is 2.2.79!"

do it! and post result

**Comment by PHPian** [comment]
yowsup-cli registration --requestcode sms --phone 91##### --cc 91 --mcc 404 --mnc 010 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=91&in=##&lc=GB&lg=en&sim_mcc=404&sim_mnc=010&method=sms&token=598f80a77119ea384ba3c7f888fd448b&id=2%15%EB%E4%9E%EDs%9D.%E9O%A2%08%2F%ED1%9A%91%A2%29
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=91&in=##&lc=GB&lg=en&sim_mcc=404&sim_mnc=010&method=sms&token=598f80a77119ea384ba3c7f888fd448b&id=2%15%EB%E4%9E%EDs%9D.%E9O%A2%08%2F%ED1%9A%91%A2%29
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

**Comment by amitvarma** [comment]
@alain061191  , I followed your step, after step 2.1 got the below message 
status:OK.
kind: free
pw: 9******Wt*****o=
price: â¹ 55
price_expiration: 1434379532
currency: INR
cost: 55.00
login: 919*************
type: existing
expiration: 1458215620
 
but  didn't receive sms code yet, for registration. 
Thanks.

**Comment by PHPian** [comment]
Any input on the "No routes" failure @tgalal

**Comment by tgalal** [comment]
@amitvarma this response means whatsapp detected you were previously registered from same client and instead of sending you sms code, it returned you a new password which you can use right away

**Comment by rami-dabain** [comment]
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc={IREMOVED THIS }&in={MY PHNE NUMBER}&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=960b040e1b0ad6b7ae295cd89d2289d2&id=T%AC%5CQi%29%B2U%8F%82%17d0X%982%92%21c%D3
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=***&in=*********&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=960b040e1b0ad6b7ae295cd89d2289d2&id=T%AC%5CQi%29%B2U%8F%82%17d0X%982%92%21c%D3
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by alissonx** [comment]
I have last version.... but have the same error

# yowsup-cli registration -c /usr/local/etc/zabbix22/zabbix/zap.conf --requestcode sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version
[103447 refs]

**Comment by jlguardi** [comment]
Read #1335

**Comment by dotsanjay** [comment]
@jlguardi I am doing wget for master.zip and installing via "python setup install". I guess its a latest built, but and still getting old_version error. Can you please help me to get the correct step to install it,
status: fail
reason: old_version
login: 6584515022

**Comment by dotsanjay** [comment]
@jlguardi Have you merged the fix with the master?

**Comment by jlguardi** [comment]
@dotsanjay apply #1889 to your code and install it.

**Comment by dotsanjay** [comment]
@jlguardi Thank you so much :) Its working now

**Comment by GCUGreyArea** [comment]
yowsup-cli registration --requestcode sms --phone XXXXXXXXXXX --cc XX --mcc XXX --mnc XX -d
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/home/pi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'yowsup-cli'

**Comment by GCUGreyArea** [comment]
Are there any other libraries to communicate with, well frankly any usable service. Preferably c++?

**Comment by sgmoorthy** [comment]
has this been fixed ? i am getting same error.. any help ?
`INFO:yowsup.common.http.warequest:{"login":"44XXXXXXXXXX","status":"fail","reason":"old_version"}`

**Comment by dkiran** [comment]
@GCUGreyArea  did you got any solution for 'No Script named 'yowsup-cli'
