### ISSUE TITLE
Running from Git Source

### ISSUE THREAD

**Issue by immenz** [tgalal/yowsup#768]
Is it possible to run a self-written Project with imports from the git source of yowsup?

I mean, as an example app there have to be 2 files, a layer.py and a run.py. 
I've cloned latest changes (with new ack-format) in my yowsup git folder, and placed my 2 files there also. But when I try to execute run.py, there are errors because new getType() and getFrom() functions are unknown. The Stacktrace points to my /usr/local/lib installation of yowsup...

I've seen that the demo apps (echoclient, cli) are using the git source...
##

**Comment by tgalal** [comment]
I think you'd need to remove your local yowsup installation from inside /usr/local/lib/pythonx.y/site-packages or something like that. At least that's how I do it.
