### ISSUE TITLE
Argument error since PR #756

### ISSUE THREAD

**Issue by ResonantWave** [tgalal/yowsup#770]
Since PR #756, I've been getting this error (And no changes were made in my side): 
```
ERROR:root:__init__() takes exactly 5 arguments (4 given)
```
I've made a bash loop, so the python script restarts after an error. The strange thing is that sometimes the error appears, and others it just doesn't, until it receives any message, where the error appears again.

So, any ideas on what's happening? Has any function changed?

**Comment by betoroar** [comment]
Fixes #763

**Comment by ResonantWave** [comment]
I was already ahead of that fix, and still the error appears. I even downloaded the most recent commit (94605c7095), and not fixed yet.

**Comment by tgalal** [comment]
@ResonantWave Recently OutgoingAckProtocolEntity constructor [was changed](https://github.com/tgalal/yowsup/commit/7cb3679451e6a6c9aa61b22dfe36ff7ccc65bc3b#diff-5bc06bf70111bfd7dfaaa8331807c912) and now it must take an extra argument "to", which is the jid of the sender of the message we are acking. Could it be in your code it's not updated to contain that argument yet?

**Comment by ResonantWave** [comment]
That did it. Thank you very much and sorry (because the fault was mine, indeed).

**Comment by yorickr** [comment]
onReceipt in https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app should be updated as well then, it's lacking the jid argument.

**Comment by tgalal** [comment]
@yorickr thanks for the tip, updated
