### ISSUE TITLE
Authentication Error: unhandled Stream

### ISSUE THREAD

**Issue by r00kieCoder** [tgalal/yowsup#773]
Echo client disconnects with this message after some time.  But initially it is working fine?
```
DEBUG:yowsup.layers.logger.layer:rx:
<iq type="get" xmlns="urn:xmpp:ping" from="s.whatsapp.net" id="xxxx-ping">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ping>
</ping>
</stream:error>

Authentication Error: Unhandled stream:error node:
<stream:error>
<ping>
</ping>
</stream:error>
```
Thank you for any help you can provide.

**Comment by tgalal** [comment]
Is it with a specific demo or your code? Do you have YowIqProtocolLayer in your stack ?

**Comment by r00kieCoder** [comment]
Hi tgalal, this is with the latest demo code (echoclient).  In stack.py I don't have YowIqProtocolLayer, I will add that now and then report back.  Thank you for your response.

**Comment by tgalal** [comment]
@r00kieCoder I realized yesterday that echoclient didn't have YowIqProtocolLayer and so was not responding to pings from server, I updated it in the repo.

**Comment by r00kieCoder** [comment]
@tgalal I added YowIqProtocolLayer into stack.py, for some reason it doesnt seem to have helped, I still get this:

```
DEBUG:yowsup.layers.logger.layer:rx:
<iq type="get" xmlns="urn:xmpp:ping" from="s.whatsapp.net" id="xxxxxxxxxx-ping">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ping>
</ping>
</stream:error>

Authentication Error: Unhandled stream:error node:
<stream:error>
<ping>
</ping>
</stream:error>
```

Perhaps I did something wrong, even though there was just two places in stack.py to insert it.  I will update from the repo, try again, then report back.

Thanks tgalal

**Comment by r00kieCoder** [comment]
@tgalal Hi :)  I updated everything again from the git, and now things have improved.  Echoclient was disconnecting after 2 minutes, now today it ran for 2 hours before disconnecting.  I didnt catch the error, so I'm running it again to catch the error now.  Definitely a huge improvement with the latest changes! Will report back as soon as I can.

**Comment by r00kieCoder** [comment]
@tgalal OK, I can confirm the disconnect I referred to above since the latest update was my own fault. I fixed that and EchoClient has been running perfectly ever since. All looking good! Thanks very much for being so responsive, this is an awesome project. Have a great day!
