### ISSUE TITLE
yowsup-cli: Get disconnected after 2 or 3 minutes. 

### ISSUE THREAD

**Issue by jerryames** [tgalal/yowsup#775]
After login in cli,  message "Disconnected: Connection Closed" appears every 2 minutes.

I did not change anything. The problem just started to appear about one week ago. Anyone has the same problem?

Used to be able to stay connected for days if not weeks. Anything changed in Whatsapp to prevent yowsup-cli stay connected?
##

**Comment by jroman** [comment]
Same problem here.

I have tried with an old yowsup-cli version with same result.

**Comment by jerryames** [comment]
It seems it will disconnected every 100 seconds. If using /ping, will not get disconnected until 100 later.
Anyway to change the auto ping to less than 100 seconds. That should keep it connected.

**Comment by jroman** [comment]
In which file is the auto-ping done?

**Comment by jerryames** [comment]
Anyway to make cli ping the server, say, every 60 seconds?

**Comment by jerryames** [comment]
I may have found the solution.

yowsup/layers/protocol_iq/layer.py 

The original code ping server every 120 seconds, I change it to 60 seconds. Done :)


from:


    def run(self):
        while not self._stop:
            for i in range(1, 24):
                time.sleep(5)



to 


    def run(self):
        while not self._stop:
            for i in range(1, 12):
                time.sleep(5)

**Comment by jroman** [comment]
Great!

I tried with 95 seconds (19x5) but I did not see any ping. So, let's do it to 12x5.

Thanks!

**Comment by jerryames** [comment]
Mine is working fine since morning. :)

**Comment by jroman** [comment]
`for i in range(1, 18)`

is OK, too, not 19.

**Comment by idigevian** [comment]
Hi Guys,

Can you share the code snippet on how to keep the session alive in python code ?

Thanks!

**Comment by jroman** [comment]
Read jerryames comment written 2 days ago.

**Comment by Rafiudo** [comment]
Don't work for me :(

**Comment by jerryames** [comment]
It should have the problem I have. Very stable for the past few days, not a single disconnection. 

Make sure you change the code in the right place.

**Comment by janboll** [comment]
Reducing the ping intervall worked for me too.
@tgalal is it possible to implement a parameter to set the ping intervall-time?

**Comment by jerryames** [comment]
yowsup-cli started to disconnected again from this Friday. Ping server does not solve the problem. If anyone figure it out, please share.
