### ISSUE TITLE
youwup stop working this may 1st -status fail- old version

### ISSUE THREAD

**Issue by checoGarcia** [tgalal/yowsup#776]
Hi yowsup fellows, I've been happily using yousup for 4 months with no issues until this may 1st 15. I have a server (windows server sp2) that is 24/7 running my application. the error that comes up is:
"AuthError(nodeEntity.getReason()) yowsup.laers.auth.autherror: AuthError: not-authorized"
Then I thought my configure file was expired and I try to get a new registration by doing:
"yowsup-cli registration --requestcode sms --phone 52444xxxxxx --cc 52 --mcc 334 --mnc 020"
Then i got the following error message:
"INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version"
I read a previous similar issue that says that they solve it  by using the new version of youwsup 2.2.78, but it doesn't change anything, the errors still the same.
I hope you guys can help me with this issue, thanks in advance!

**Comment by tgalal** [comment]
Download latest sources or upgrade through pip to 2.2.79 (repo still has version at 2.2.78 though, but fixed)

**Comment by raooll** [comment]
it is not working even after the the latest update.

**Comment by tgalal** [comment]
@raooll can you please try with --debug as argument and post output?

**Comment by raooll** [comment]
@tgalal  please have a look

Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="918971128893" mechanism="WAUTH-2">
?\Q??R?弇ooG??fH蒅|=??a?7)n???a???Bֳ?
HEX:d15c511fff9252cb17e5bc876f6f47fbb06648e89285027c3dc6d261c01d37296e8fc9d66192db05fe1342d6b3d8
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
????wu?I?@???V?????

HEX:9aa3e2f27775ce49ff40f2d9f75698a8d1fbc10a
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
A?f?Q????Z0?͌?¼??.??J3_?
 ?腄z?RΧ????
*?
HEX:419966e151ae98c8f15a30b9cd8ce0c2bcb6b5172eb6b94a335fb10a2099e885847ab452cea7d214f787f00a2aa1
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

**Comment by raooll** [comment]
@tgalal  I have two numbers both are showing the same behaviours , 
Whatsapp pushed an update of app on may 5 (not sure if related)
Here's the output from the other number

[offline]:/L
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="919769588581" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
ai?WUB?°?լY?????
HEX:6169ba0757554285c2b0f18bd5ac5992f4f5f5f2
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
??"?6??J?????iY???V??^??ce?.?*v??CG??B????'
HEX:9cad228d3681b04afdccf991e4aa6959bfa4db5698f65ed5dd6365f52ef62a76c1fe43470fada74218ba81dade27
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

**Comment by raooll** [comment]
@tgalal I m sorry , wrong thread, i'll move this to the right one.

**Comment by djgel** [comment]
[root@sv]# /usr/bin/python /opt/yowsup-master/src/yowsup-cli -c src/zapzap.config -e  --debug
{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.53 S40Version/14.26 Device/Nokia302'}
cc=55&in=6198319315&id=18c0ccbc183b23a08af3b424cf0d57c0
Opening connection to v.whatsapp.net
Sending GET request to /v2/exist?cc=55&in=6198319315&id=18c0ccbc183b23a08af3b424cf0d57c0
WAExistsRequest:        {"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by djgel** [comment]
I update a version before this!

**Comment by checoGarcia** [comment]
Thanks @tgalal, now its working!! After getting the newest version 2.2.79 works like a charm, but i had the issue of "5 argument required and 4 given" in OutgoingAckProtocolEntity, but just by adding entity.getFrom() as an argument did the trick!

**Comment by dotsanjay** [comment]
@tgalal: I have version 2.2.79
Here is my log:
DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani'}
DEBUG:yowsup.common.http.warequest:cc=65&in=84515022&lc=GB&lg=en&sim_mcc=525&sim_mnc=001&mcc=525&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9616&rchash=365e611b02c89269214463d9614172a46acae02c13ab1ec48148aa75b43498a4&anhash=%A5T%EB%D9%DBB%2A%DF%0Es%B4.%3B%E3%3C%BD%D0H%F8%18&extexist=1&extstate=1&token=Zf62j3Z8WGmTM5z1%2FzUhXzweQnQ%3D&id=%8A%21%98%EA%DC%9A%03%B3%FA%C5%B13%AF3%CE%60%D5q%5C%C0
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=65&in=xxxxxxx&lc=GB&lg=en&sim_mcc=525&sim_mnc=001&mcc=525&mnc=001&method=sms&mistyped=6&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=9616&rchash=365e611b02c89269214463d9614172a46acae02c13ab1ec48148aa75b43498a4&anhash=%A5T%EB%D9%DBB%2A%DF%0Es%B4.%3B%E3%3C%BD%D0H%F8%18&extexist=1&extstate=1&token=Zf62j3Z8WGmTM5z1%2FzUhXzweQnQ%3D&id=%8A%21%98%EA%DC%9A%03%B3%FA%C5%B13%AF3%CE%60%D5q%5C%C0
INFO:yowsup.common.http.warequest:{"login":"65XXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 65XXXXXXXX

**Comment by dotsanjay** [comment]
I have hide my number 65XXXXXXXX
