### ISSUE TITLE
how to send image and text at the same time

### ISSUE THREAD

**Issue by chetanunadkat90** [tgalal/yowsup#784]
Hi ,

I am trying to send image as well as text to same request.
can somebody please suggest how can i do it

**Comment by tgalal** [comment]
If you mean image caption, then [ImageDownloadableMediaMessageProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py) constructor accepts caption as an argument. Same thing in ImageDownloadableMediaMessageProtocolEntity.fromFilePath static method

**Comment by chetanunadkat90** [comment]
Thank you tgalal.. :)
