### ISSUE TITLE
Connection fidelity

### ISSUE THREAD

**Issue by Dl0tt** [tgalal/yowsup#787]
Sometimes running the script will output YowNetworkLayer.EVENT_STATE_CONNECT and YowNetworkLayer.EVENT_STATE_CONNECTED, however it doesn't receive any message.

I've updated yowsup from git, but it didn't fix it and I'm sure my number isn't banned

**Comment by tgalal** [comment]
post some code which is not working ?

**Comment by Dl0tt** [comment]
I can't really find what's "wrong", sometimes it receives messages, sometimes it doesn't

Apparently it's the same problem as #804 and by what i've observed it happens when i'm not disconnected properly from whatsapp servers, it won't display me as "online", but "last seen" continues to update to the current time (the code isn't receiving messages or not running and opening a chat with the number will display "last seen: [current time]" even tough it's off for 10 minutes). I don't know what makes me disconnect properly and what doesn't, but i'm using a modified version of Echo client from the Sample App section of the wiki.

Anyway, connecting every time i get disconnected will eventually get messages, I just wanted to increase the program's uptime

Thanks

**Comment by tgalal** [comment]
See my reply in #804

**Comment by Dl0tt** [comment]
I'm closing this since it's a duplicate, i'll make new questions on #804

-------- Original Message --------
