### ISSUE TITLE
registration failed - old version

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#788]
root@host:/opt/yowsup-master# ./yowsup-cli registration -d --cc 7 --phone 79990000001 --requestcode sms
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.61 S40Version/08.71 Device/NokiaX2-01'}
DEBUG:yowsup.common.http.warequest:cc=7&in=9990000001&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=2b0f331b34909472071c4d4120c27594&id=%B6x+x%AC%14%B3%04%A0%85%E0%A7N%94%BB%BA%BA%F2%1BD
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=7&in=9990000001&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=2b0f331b34909472071c4d4120c27594&id=%B6x+x%AC%14%B3%04%A0%85%E0%A7N%94%BB%BA%BA%F2%1BD
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by tgalal** [comment]
that's an outdated version, update your repo or package

**Comment by daemonserj** [comment]
Tnx I already relised thet just after repporting bug :)
