### ISSUE TITLE
Help with setup mass mailing

### ISSUE THREAD

**Issue by DmitryKudryavtsev** [tgalal/yowsup#791]
Hello everyone!

There is a list of employees of the company he is in the background phone.txt
How to set a variable in a line that posts the order sent to all numbers?

$1="/srv/phone.txt"
yowsup-cli demos -c /srv/yowsup-cli.config -s "$1"  "test mailing"

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

How to solve this problem?

To specify a nickname?

How to make a report on the mass distribution who are not delivered, you can specify a file logging?

BR!

**Comment by dedmen** [comment]
Mass mailing is exactly what whatsapp wants to stop. And if whatsapp sees yowsup as a problem they will cut yowsups wings off...
Its not a yowsup problem... the sendmessage demo accepts a phone number and the text as parameters.. so just give it the phone number instead of a path to a text file.

**Comment by DmitryKudryavtsev** [comment]
Ok 

As in the string to specify niknam and the path to the image file : 

yowsup-cli demos-c /srv/yowsup-cli.config -s 79251111111 "test mailing"

How can you record a log of a successful send and unsuccessful ?

If I every 3 seconds will generate a message that looks over the sheet via the web client :

root@whatsapp:/var/www/html# cat index.php 
<?php
echo exec('cd /usr/local/bin ; yowsup-cli demos --config /srv/yowsup-cli.config --send 7' . htmlspecialchars($_GET["number"]) .' "'.htmlspecialchars($_GET["message"]). '"');
?>

Will scetate mass sending ?

**Comment by dedmen** [comment]
yowsup doesnt log anything to a file.. You could start with -d parameter then youll see the receipt message...
If its for employees of the company you could also just create a whatsapp group invite all employees and send the message in the group every time..

**Comment by DmitryKudryavtsev** [comment]
OK , thanks !

How to insert photos ?

How to specify a nickname ?
