### ISSUE TITLE
authentication error: not-authorized

### ISSUE THREAD

**Issue by onahoe** [tgalal/yowsup#792]
After I paused my work some weeks, I tried to startup my program again today, but I got the following error in connecting. authentication error: not-authorized

What's the problem? is my account banned or something? I don't really get it, sorry.

Thank you!
onahoe

**Comment by dedmen** [comment]
Are you using up-to-date yowsup? there have been some changed with the new whatsapp version so the older yowsup version from a few weeks ago doesnt work anymore.

**Comment by aesedepece** [comment]
Which branch are you using? (master or legacy)
If legacy, PR https://github.com/tgalal/yowsup/pull/790 fixes it.

**Comment by onahoe** [comment]
Yes, I'm using up-to-date yowsup (master-branch).
How can I fix it for the master branch?

**Comment by onahoe** [comment]
I just tested the legacy branch (with token update) - I'm getting "Auth Failed"

**Comment by tgalal** [comment]
have you tried registering again ?

**Comment by onahoe** [comment]
@tgalal Yes, I registered a new number, downloaded the latest yowsup (master) and I'm still getting not-authorized

**Comment by onahoe** [comment]
Worked with the same number on a different server. lol.
Seems like the hwid/ip or something got banned?

**Comment by tgalal** [comment]
not sure..
