### ISSUE TITLE
small bugs and mistypings

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#794]
in receipt_incoming.py in line 60
node.getAttributeValue("timestamp"), instead of 
node.getAttributeValue("t"),

in message_text.py line 19
"body" instead of "Body" concerning all of entities sylistic.

**Comment by daemonserj** [comment]
So it would be nice if you add
Timestamp to message.py.__str__

**Comment by tgalal** [comment]
thanks for reporting!
