### ISSUE TITLE
How to insert a picture in a message?

### ISSUE THREAD

**Issue by DmitryKudryavtsev** [tgalal/yowsup#797]
How well this line to add a picture to the text?
/usr/local /bin/yowsup-cli demos -c /srv/yowsup-cli.config -s $p "$1"

To specify an alias instead of numbers?

**Comment by DmitryKudryavtsev** [comment]
oot@whatsapp:/srv/img# yowsup-cli demos -c /srv/yowsup-cli.config --ImageDownloadableMediaMessageProtocolEntity /srv/img/logo.png -s 7915XXXXXXX "test mailing"
usage: demos [-h] [-v] [-d] [--help-config] [-l phone:b64password | -c CONFIG]
             [-m] [-y] [-e] [-s phone message]
demos: error: unrecognized arguments: --ImageDownloadableMediaMessageProtocolEntity /srv/img/logo.png


How to specify the argument?

**Comment by dedmen** [comment]
the sendmessage example only sends Messages not pictures.

**Comment by DmitryKudryavtsev** [comment]
Ok, how to send a photo?

**Comment by tgalal** [comment]
There is no way in yowusp demos to send image by passing it as argument to command line. You can see how it works [here](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L313) and in [Wiki](https://github.com/tgalal/yowsup/wiki/Yowsup2:-Upload-and-send-Media), and implement it.
