### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#799]
HI,

    Can anyone please suggest where to pass path of profile picture????

I have updated yowsup-master.. just need to know the parameters..

Waiting for response..

Regards..

**Comment by tgalal** [comment]
[See this](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L191)

**Comment by Narendra-Kumar** [comment]
I already use that method.

but I get error :
    pictureData = src.resize((640, 640)).tobytes("jpeg", "RGB")
  File "G:\Python27\lib\site-packages\pillow-2.8.1-py2.7-win32.egg\PIL\Image.py", line 664, in tobytes
  File "G:\Python27\lib\site-packages\pillow-2.8.1-py2.7-win32.egg\PIL\Image.py", line 434, in _getencoder
SystemError: unknown raw mode

Please help...
Is this is the problem of any python packages, that not exist or not properly installed.
If not, then tell me the python command using yowsup-cli to set profile pic

thanks..
