### ISSUE TITLE
Client connect but not receive message after two or more reconnections

### ISSUE THREAD

**Issue by betoroar** [tgalal/yowsup#804]
I had a client working fine to last week but, lastly it disconnect and stop receive message, then i have to reconnect two or more times until can receive messages. On that tries, it appear online but not receive any messages.

What could be happened?

Sorry for my english!!
##

**Comment by raooll** [comment]
I am facing the same problem, I stop getting incoming messages randomly , while I am able to send messages during this time.

**Comment by raooll** [comment]
@betoroar  did you find anything useful ?

**Comment by betoroar** [comment]
nothing yet!

**Comment by raooll** [comment]
This keeps happening randomly , I have no idea why ?

**Comment by tgalal** [comment]
Are you not handling some messages or notifications (for example groups?) If I remember correctly sometimes whatsapp will stop sending you message until either you send receipts for all received messages (or acks for notifications), or until they expire. If that's the case then you reconnecting several times, makes whatsapp retry sending u old messages/notifications and will expire after some retries, and then send u the new ones.

**Comment by rami-dabain** [comment]
Facing same problem, it runs perfectly until it disconnects, even if there were no messages to receive after a reconnect it does not receive any new sent messages.
