### ISSUE TITLE
Add caption to image

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#805]
hi,,
 I i am able to send image...
but now i want to send text along with image (i.e. caption)
I have implemented new mageDownloadableMediaMessageProtocolEntity also..

but how to pass caption as argument with yowsup-cli command??

**Comment by tgalal** [comment]
Not possible with  yowsup-cli, but you can modify [cli layer](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L328) yourself to accept a caption.

**Comment by Narendra-Kumar** [comment]
caption is done.. by modifying media client layer

**Comment by jlguardi** [comment]
I propose this pull request #894.

**Comment by jlguardi** [comment]
Reimplementation in #948
