### ISSUE TITLE
how to use sendclient demo within an own project

### ISSUE THREAD

**Issue by grindelsack** [tgalal/yowsup#806]
Hi all,

I would like to integrate yowsup in some of my current python projects and looking for some guidance how to do this best. I already found the sendclient demo however i do not have an clue how to use it in my projects. Based on what I've read at https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app I assume that I need a kind of run.py which is calling layer.py however I do not have an idea how this run.py must look like. I tried to adapt the script coming with the echo-client sample-app without success, thus I would really appreciate if someone would give me some further guidance how to proceed.

Thanks for any help and this great piece of software.

Best regards,
Joern

**Comment by janboll** [comment]
Hi,

As i read through your comment i assumed that you struggle with the basics. Basicly the Sample-App is a good starting point. You can use the code found there to build up your own implementation of a client. 
So i would suggest that you try editing the existing run.py and layer.py to meet your demands. That was at least the way i started.

Once you got a food on the ground i would suggest to use the YowStackBuilder, as this is recommended and provides the best usability. See cli for an example: https://github.com/tgalal/yowsup/blob/377aa083b4777c8f5c6a47575edd2eea33ce375d/yowsup/demos/cli/stack.py 

Best regards,
Jan

**Comment by tgalal** [comment]
@janboll thanks for explaining!
