### ISSUE TITLE
Error, phone number does not start with the specified country code on US phone number

### ISSUE THREAD

**Issue by sagargulati** [tgalal/yowsup#807]
Hello,
I am trying to register my phone using:
./yowsup-cli registration -p 206XXXXXXX -C 1 -r voice
But I get this error:
Error, phone number does not start with the specified country code.
What should be the country code and how number should be entered.

Already tried with cc as 206, 20 it says bad_number
cc with 1 says the above error.

Help appreciated!

Thanks!

**Comment by dedmen** [comment]
./yowsup-cli registration -p 1206XXXXXXX -C 1 -r voice
add the 1 infront of the -p parameter

**Comment by sagargulati** [comment]
root@newyork:~/yowsup# ./yowsup-cli registration -p 1206xxxxxxx -C 1 -r voice
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":                                                                                        "number"}

**Comment by SpEcHiDe** [comment]
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"bad_param","param":"number"}

status: fail
param: number
reason: bad_param

I am getting this error when I am trying to register

**Comment by tgalal** [comment]
If country code is XX, and phone number is 0YYYYYYYY (assuming there is a starting zero), then:
> ./yowsup-cli registration -p XXYYYYYYYY -C XX -r voice

note that if the number started with zero, it's omitted in the command.
