### ISSUE TITLE
Default Yowsup Echo client demo (in yowsup-cli) exits after 60 seconds

### ISSUE THREAD

**Issue by mtreble14** [tgalal/yowsup#810]
This is what I'm running:
    (date; yowsup-cli demos -c config.example -e; date)

And without any interaction with the WA account, the program exits after 62-63 seconds.

root@myserver:/home/somefolder# (date; yowsup-cli demos -c config.example -e; date)
Tue May 19 02:07:03 UTC 2015
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Tue May 19 02:08:05 UTC 2015

root@myserver:/home/somefolder# (date; yowsup-cli demos -c config.example -e; date)
Tue May 19 02:09:37 UTC 2015
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Tue May 19 02:10:40 UTC 2015

I tried using the latest version as well:
    pip install yowsup2 --upgrade
but results were still the same.

root@myserver:/home/somefolder# (date; yowsup-cli demos -c config.example -e; date)
Tue May 19 02:25:23 UTC 2015
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Tue May 19 02:26:26 UTC 2015

**Comment by WeWin55** [comment]
Ive got the same problem, but no fix.

**Comment by bhavesh53** [comment]
+1 same problem here

**Comment by zoqui** [comment]
registering with new credentials (pwd) worked for me.

**Comment by jroman** [comment]
Whatsapp servers disconnect after ~60 secs of inactivity. Latest yowsup version is pinging the servers in an interval less than 60 secs so the problem is avoided.

So, I guess your problem is with getting the latest version of the library.

Cheers.

**Comment by zoqui** [comment]
It was the latest version, and only worked after registering with new credentials again.
