### ISSUE TITLE
Send Enter in Whatsapp message.

### ISSUE THREAD

**Issue by WeWin55** [tgalal/yowsup#812]
Hello,

Ive got a shell script that sends $2 as text and $1 are the people.
For example: sh send.sh mom "how was your day?"

Now i want to send a Return in the message, \n doesnt work and i dont know how to send it.

Thanks in advance.

EDIT: Is there a way to define the presence name in the config file?
/presence name "Raspberry"

**Comment by jroman** [comment]
Something I missed, too.

**Comment by dedmen** [comment]
If youre using the cli demo you can use a little workaround:
in yowsup/demods/cli/layer.py
    def message_send(self, number, content):
     if self.assertConnected():
      content = content.replace("###","\n")
      outgoingMessage ....

**Comment by holdack182** [comment]
thanks for the workaround!
also, for those who want to have the lines replaced when using -s to send message, you can have the same approach on file yowsup/demos/sendclient/layer.py on:

def onSuccess

right after 
phone, message = target
message = message.replace("###", "\n")


then you can normally do:
yowsup-cli demos -c config -s 55xxxxxxxxxx "test###of###linebreak"

:-)

**Comment by MPG1967** [comment]
Works for me. 

by the way, i do this:

message = message.replace("\\n", "\n")

works fine.
