### ISSUE TITLE
Stream error again

### ISSUE THREAD

**Issue by davidpaulrosser** [tgalal/yowsup#815]
My application is getting the stream error message again.

```
<stream:error>
<ack>
</ack>
</stream:error>
```

Any idea why?

**Comment by davidpaulrosser** [comment]
Pull the latest code, seem to fix it.

**Comment by davidpaulrosser** [comment]
Still getting the stream error. Anyone else?

**Comment by dedmen** [comment]
Im using the version from 18.05.2015 and im getting stream error after about two days runtime.

**Comment by davidpaulrosser** [comment]
Can we get this fixed as soon as possible? I have a project going live next Tuesday!

**Comment by dedmen** [comment]
My second client which is not doing presence subscribe doesnt have the problem.. its now running for about 4 days

**Comment by rgrativol** [comment]
I'm having the same error.

**Comment by dedmen** [comment]
I Just noticed my second client which is not getting stream:error is not receiving notifications.

**Comment by davidpaulrosser** [comment]
Would really appreciate it if this can get fixed by tomorrow!

**Comment by mgp25** [comment]
Is ack issue, maybe yowsup is missing some ack, its simple to add it. Check your debug log

**Comment by davidpaulrosser** [comment]
Seems to be working fine now.
