### ISSUE TITLE
Get the last visit of contact

### ISSUE THREAD

**Issue by DrMartiner** [tgalal/yowsup#816]
Hello,

How can I get the last visit of contact?

Best regards,
Alexei

**Comment by tgalal** [comment]
I've just implemented that. Use LastseenIqProtocolEntity from protocol_presence, [see this](https://github.com/tgalal/yowsup/blob/develop/yowsup/demos/cli/layer.py#L198) in yowup cli demo as an example. It's still in develop branch though.
