### ISSUE TITLE
Error when registering a phone number

### ISSUE THREAD

**Issue by ExplodingCamera** [tgalal/yowsup#817]
I am getting an error when i want to register a Number

yowsup-cli registration -c config.yowsup --requestcode sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"too_recent","retry_after":69}

status: fail
retry_after: 69
reason: too_recent

**Comment by ExplodingCamera** [comment]
I forgot that my server is in france while my number is germany.

**Comment by mgp25** [comment]
```
status: fail
retry_after: 69
reason: too_recent
```
You need to wait 69 seconds to try again
