### ISSUE TITLE
Strange sending limit

### ISSUE THREAD

**Issue by andygreens** [tgalal/yowsup#818]
Hello! I've got 37 people in my office. And I've been using yowsup to send messages about meetings once or twice a month. I am not really good at bash, so I modified your code in sendclient layer. I did put an extra loop and an array with their numbers, to send the message to all of them. Everything was fine until recently my account got banned after sending 8 messages in a row. I tried two more new sim cards, as I thought there was something wrong with my number and the account, but got the same issue... What's the deal? Do you know why they ban my account at the 8th message now?
##

**Comment by KuttKatrea** [comment]
You should have used a broadcast message to all of them, instead of a loop.
A loop can create very suspicious activity

**Comment by catch2patch** [comment]
I guess something's wrong either with the token (there is no up to date android token yet) or with the auth code or there's something changed in the protocol. I had the same problem over a month ago. I lead the online gaming comunity and use the api to send messages to the members about the raid bosses respawn or upcoming PvP events. 
Last time I had the problem my numbers were also blocked at 8th message, but the migration to yowsup-master and updating the tokens have solved the problem. But now it doesn't help, the 8th message is fatal.
BTW I've tried to use broadcasting earlier and also recently, but almost 30% of the members can't receive it, despite of they have added my number to contacts.

**Comment by Dl0tt** [comment]
Is it happening only with private messages or sending messages to groups in sequence also blocks the number?

**Comment by bdbais** [comment]
There is some update about this thread? I've put a waiting time before sending messages prevently added on a queue, but I notice there is a sort of limit after this I was disconnected from server.

**Comment by Dl0tt** [comment]
Its not a bug, it's a feature. This is one of the ways WhatsApp prevents spam, so if you need to send the same message to many people you have to use broadcast or a group. The same will happen if you have the app on a phone. This prevents unwanted messages because the number only receives the message if you are on his phone list.
