### ISSUE TITLE
Disconnected and blocked after receiving <presence>

### ISSUE THREAD

**Issue by aguiraf** [tgalal/yowsup#819]
Hello all,
after several day working normally, receiving and replying to messages, I received this:
```
<presence type="unavailable" from="39********79@s.whatsapp.net" last="deny">
</presence>
```
from a number I never subscribed presence to (I have no subscriptions at all).
I got immediately disconnected; and any further attempt to reconnect resulted in 
```
<failure>
<not-authorized>
</not-authorized>
</failure>
```

Then I tried to register again, resulting in an even worse:
```
status: fail
reason: blocked
```
The code base working was prior than @aesedepece 's  https://github.com/tgalal/yowsup/pull/796,
but apart of getting and printing the presence values, 
has the `<presence >` to be `<ack>`ed  or replied in any way in the protocol?
Do those `type="unavailable"` and `last="deny"` mean something strange?

**Comment by aesedepece** [comment]
* `type="unavailable"` means that contact just disconnected from WhatsApp.
* `last="deny"` means that contact don't publish its last connection timestamp.

Receiving presence from a not subscribed contact sounds quite weird, and so does the immediate disconnect and block. I've never seen such case.

**Comment by CODeRUS** [comment]
presence subscribe is permanent, you don't need to call it after each login. so once you sent subscribe you will receive presence from  this person until you send unsubscribe.

**Comment by aesedepece** [comment]
@CODeRUS Yep, I forgot to mention that. Thanks for pointing out!

**Comment by aguiraf** [comment]
thank you all for explaining! 
While the reception of presence messages remains strange, the block seems uncorrelated.
closing...

**Comment by zextr** [comment]
@aguiraf I got the same problem today.. my number got blocked.. is your number unblocked or not?
