### ISSUE TITLE
Connection auto-closing at login

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [tgalal/yowsup#820]
I don't know what's happening and it's already the second time that it happened to me. Every time that I try to login on Yowsup CLI or to use any other script that uses Yowsup libraries, it closes the connection and I'm not able to login. Last time it happened, I don't know what I did, but it went back to normality after one week with this problem. Please someone help me!

$ ./yowsup-cli demos -c WhatsApp/.config -y -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - Groups Iq Layer - Media Layer - Privacy Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
 ==================
Type /help for available commands

\[offline\]: /L
DEBUG:yowsup.layers.logger.layer:tx:
&lt;stream:features&gt;
&lt;readreceipts&gt;
&lt;/readreceipts&gt;
&lt;groups_v2&gt;
&lt;/groups_v2&gt;
&lt;privacy&gt;
&lt;/privacy&gt;
&lt;presence&gt;
&lt;/presence&gt;
&lt;/stream:features&gt;

DEBUG:yowsup.layers.logger.layer:tx:
&lt;auth passive=&quot;false&quot; user=&quot;5581XXXXXXXX&quot; mechanism=&quot;WAUTH-2&quot;&gt;
y??c?m?4TJt?.?Sq&gt;.?[??&gt;i?????Iy(8Ey?&gt;شO
HEX:79f7f30263f26df63415544a74bb2e8d53713e152e9d5b9d823e69ab1d9eacf0eb497928384579943e1be0d8b44f
&lt;/auth&gt;

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
\[offline\]:
\[offline\]:
general: Disconnected: Connection Closed
\[offline\]:

**Comment by t0rr3sp3dr0** [comment]
WhatsApp problem, not Yowsup

**Comment by CODeRUS** [comment]
you logging with wrong nextchallenge

**Comment by Robert213123** [comment]
same problem here
CODeRUS, what do you mean by "logging with wrong nextchallenge?"
