### ISSUE TITLE
yowsup-cli  running from php command line but not from browser

### ISSUE THREAD

**Issue by chetanunadkat90** [tgalal/yowsup#822]
Hi I have following code which runs perfectly from command line but doesnt run when invoked through browser. Are there any shared libraries those need to be involved

<?php
$command1 = "yowsup-cli demos -c config -s 9999999999 hi";
                $result = shell_exec($command1);
?>

**Comment by dedmen** [comment]
when running from browser the working directory is not the same as command line... and the way you are setting the config parameter its searching for the config on workingDir/config.. Which works from command line because the working dir is the correct one.

**Comment by chetanunadkat90** [comment]
Hi thanks for quick reply.. Above Php is working from command line.. But not from browser... Can plz suggest the changes required

**Comment by 0xTryCatch** [comment]
You can't use ```shell_exec()``` in a webserver environment. Use CLI

**Comment by dedmen** [comment]
I dont  now php that much but i would suggest replace the config with the
full path to it and make sure the permissions are right so the webserver
can access yowsup and the config

**Comment by chetanunadkat90** [comment]
I tried adding configuration file and cli location. Still its not working from browser.Also gave 777 rights to all files.

**Comment by Gonzo2028** [comment]
i had a similar issue and i figured out the reason.
yowsup-cli/yowsup adds a .yowsup directory into the users directory.
If you run it ni /home/yourusername/.yowsup.
If you run it in a browser its run as http (under arch) which h as its folder here /srv/http/.yowsup.
This results in key conflicts when switching between the two.

I simlinked the one to the other to fiddle that out.

**Comment by JairusLopes** [comment]
Boa tarde !!!
Para resolver este problema ("Não executar no navegador"), eu simplesmente dei um chmod 777 na pasta do apache  "/var/www". Pois no momento que ele executa o comando de envio ele escreve um arquivo temporário neste diretório "www".
