### ISSUE TITLE
requestcode - old_version

### ISSUE THREAD

**Issue by norberto-enomoto** [tgalal/yowsup#823]
I'm using the current version - yowsup-master. I'm trying to request the code and I'm getting the following error:

kylix_mbp:yowsup-master enomoto$ yowsup-cli registration --requestcode sms --phone 5511xxxxxxxxx --cc 55

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

What's wrong?

Thanks

Norberto Enomoto

**Comment by dedmen** [comment]
Latest whatsapp version is 2.12.94 but yowsup is still running on 2.12.67.. You have to wait till yowsup updates
