### ISSUE TITLE
Blocked account and right behavior before send message

### ISSUE THREAD

**Issue by DrMartiner** [tgalal/yowsup#825]
Hello,

I need sending notification for clients of financial service (50-200 notifications per once). When I sent 6-8 messages in loop with timeout 30-40 sec between one message and 3-4 min between 6-8 messages, my account was blocked.

How can I do it without block? What should I do in loop (sync a contact or subscribe on him before send a message and etc)?

Best regards,
Alexei.

PS: I try to use broadcast message, but it does not working.
PSS: I think that I can see behavior of legal client in Wireshark and do similar. Is it help for me? What do you think?
##

**Comment by DrMartiner** [comment]
Btw, should I change the ENV (for example, on iPhone client) for the normal sending?

**Comment by mgp25** [comment]
@DrMartiner only send messages to people that already have your number added in their contact list, if its not that way, you are spamming

**Comment by DrMartiner** [comment]
@mgp25 I can ask for my clients, that they add me to contact list. How can I check exists my phone in his contacts list or not?

**Comment by mgp25** [comment]
@DrMartiner you cant check if they have you already, is not possible

**Comment by carlosdiaz** [comment]
DrMartiner you can ask them to add you as a contact, in addition if you have more simcards you can send the message from a different msisdn as well.

**Comment by DrMartiner** [comment]
@carlosdiaz I have enough SIM cards, but I can't send more 8-10 sms (account will be blocked). It's not right. I try to find ways for resolve it. I try to simulate human behavior: sent available and typing, made delay and etc, but I had not success. Everything depends on the limit (8-10 messages). I'm desperate... :-(

@mgp25 What can I do also?

**Comment by mgp25** [comment]
@DrMartiner if you send messages to people that havent your number you will be blocked for sure. You can't do anything, if you have a financial service use email, not WhatsApp

Regards

**Comment by catch2patch** [comment]
It's a weird problem about 8 messages limit. If I send messages right from and

**Comment by kwiiby** [comment]
@catch2patch do the clan members have your number in their contacts, right? that's why you don't get blocked.

**Comment by catch2patch** [comment]
@kwiibi, I guesss most of them does. But there are 3-10 new clanmembers every day, and it's possible that not all of them have added my number as a contact before receiving message. i don't know the way to check if a contact has added my number.so I have to send to anybody that subscribed to the info on the clan forum.
