### ISSUE TITLE
Auth Error, reason not-authorized

### ISSUE THREAD

**Issue by krmboya** [tgalal/yowsup#826]
I started getting this error yesterday, after running successfully since a similar glitch earlier this month.

I've both tried both the most updated version from master, and this patch that updates `env_android.py` https://github.com/tgalal/yowsup/pull/824 but still getting the same error.

Anyone else experiencing this?

**Comment by dedmen** [comment]
Did you try reregistering? altough i think that also isnt working right now.

**Comment by mgp25** [comment]
@krmboya `not-Authrized` means blockes

**Comment by krmboya** [comment]
I've tried re-registering but if fails giving the reason 'blocked'.

Is it possible to find out why a number got blocked? We've been careful to avoid spamming, only sending messages to people who already have our number in their whatsapp contacts.
