### ISSUE TITLE
How to get contact status using yowsup-cli?

### ISSUE THREAD

**Issue by jroman** [tgalal/yowsup#827]
Just a plain question: How can a see a contact status using the interactive `yowsup-cli`?

Thanks in advance.

**Comment by dedmen** [comment]
Sync with the contact and youll get his status as soon as he changes it.

**Comment by jroman** [comment]
You mean running:
`/contacts sync nnn`

and then, receiving:

`Notification: Notification`
`From: nnn@s.whatsapp.net`
`Type: status`

But I miss the status itself...

Thanks for answering!

**Comment by dedmen** [comment]
start yowsup-cli with debug parameter

**Comment by jroman** [comment]
Done. And?

**Comment by dedmen** [comment]
You should now see the status in the debug output

**Comment by jerryames** [comment]
We need to find a way to check the status instead of waiting for changes. Most people do not change status for years.

**Comment by jroman** [comment]
The versions I had in January produced outputs like:
`Notification: From :nnn@s.whatsapp.net, Type: status=HelloWorld status`

Now, the produced output is like:
`Notification: Notification`
`From: nnn@s.whatsapp.net`
`Type: status`

Maybe is a matter of touching the to_string in some place...

But I agree, a command like
`/contact getStatus nnn`
would be great.

Have a great day!

**Comment by jerryames** [comment]
I am waiting for this feature for months. It will be really really helpful to me.

**Comment by tgalal** [comment]
see my reply in #816

**Comment by jerryames** [comment]
816 solve the problem of checking last seen. How to get Contact Status? Like it was changed and what is the status, like the response in PHP version: since: 2015-Jul-19 19:09:29 getstatus-1437342675-1, Status: Hey there! I am using WhatsApp.
