### ISSUE TITLE
Restful Api

### ISSUE THREAD

**Issue by EliasKotlyar** [tgalal/yowsup#830]
Dear Developers.

Many Thanks for this great Project. Unfortunately i was not able to use this tool trough the CLI,because of the security settings of PHP. So i programmed a Restful Interface using this beatiful project. I think that many Devs are having similar problems with integration of this Tool. A Restful Api would improve this situation.

My Question is:
Would you like me to integrate a Restful Interface into the "Core"? Maybe as a Demo? Would you merge it together,or should we keep my project as a Extensiont?

You can find my Project under:
https://github.com/EliasKotlyar/Yowsup-Restful

**Comment by tgalal** [comment]
That's actually very useful piece of work. Although would be great to have it as a demo, I don't want to include additional dependencies that are unnecessary for yowsup (flask). So having it as an extension would be best IMO
