### ISSUE TITLE
How to send messages by yowsup and see the answer in whatsapp?

### ISSUE THREAD

**Issue by fpedroso8** [tgalal/yowsup#831]
I wonder if you have any way to send the message by yowsup and receive a reply in the same number in whatsapp, using only a phone number.

**Comment by CODeRUS** [comment]
http://www.whatsapp.com/faq/general/21009863

**Comment by fpedroso8** [comment]
humm, thank you, but how do I see the message of the response by yowsup

**Comment by dedmen** [comment]
you can get the whatsapp login details out of your phone... And then you use for example the sendmessage demo from yowsup.. It connects to whatsapp (therefore your phone gets disconnected) then send the message and disconnect... after a short time your phone should reconnect and will receive the reply.. but you wont see the message yowsup sent on your phone. And its possible that your phone reconnects faster that yowsup can send the message.
