### ISSUE TITLE
demos: commandline client => error handling

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#840]
Hello,

Python is not my programming language, and I think it never will be :-(

As I've seen, the demo commandline client gives no error results sending mesages. For example. After < /message send bullshit bullshit > I will get not error message.

So my wish is. Can some body give me some advise to implement error messages. Thank you.

Best regards
Jörg
##

**Comment by dedmen** [comment]
start the cmd-cli demo with the -d parameter that will show you everything yowsup sends and receives in decrypted form

**Comment by jowiemann** [comment]
Thank you for your answer. When setting the -d parameter the command line interface will give a lot of informations, but, as I think, not the information I need. What I need is a clear message that shows me if a message, an image, ... was send or not and if not, what was the error. 

Best regards Jörg
