### ISSUE TITLE
Echoclient and sendclient can't be used simultaneously

### ISSUE THREAD

**Issue by vyom180** [tgalal/yowsup#842]
I am new to yowsup and i am trying to integrate AIML with yowsup to generate automated bot replies.
I used run.py and layer.py as in the sample app to receive messages which I store in a database and then pick up the messages from the database, pass it through my AIML code and send the response to the user using layer.py and stack.py file of sendclient . i made bash files to run the scripts continuously but i see that when i run the bash file to receive messages, my sendclient disconnects and vice-versa. Need help to resolve th. Also if there is any other alternative i can use to implement the same?
##

**Comment by dedmen** [comment]
The problem is there can only be one client connected to an whatsapp account at a time.. I build a wrapper around the client demo for my project.

**Comment by tgalal** [comment]
You can have 1 layer for both sending and receiving, see layer in [echo client](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/layer.py) or [cli demo](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py)

**Comment by tawanda** [comment]
tgala, if you have 1 kayer for both sending and receiving, how do you pass messages to it for sending   once its in the async loop. I thought of passing data to the layer through a cache like redis, but the loop would need to check the cache every x seconds to see if there are any messages to send. however I dont know if there is a method that ticks every x seconds i can piggie onto to do the cache check
