### ISSUE TITLE
YOWSUP_FULL_STACK generates warning

### ISSUE THREAD

**Issue by drencrom** [tgalal/yowsup#844]
When using YOWSUP_FULL_STACK to define the layers this warning is always generated:

WARNING - Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

**Comment by ComFreek** [comment]
I received the same warning yesterday. Although I did not use `YOWSUP_FULL_STACK`, the fix should be analogous to mine (passing a tuple or list to YowParallelLayer's constructor, and `YOWSUP_FULL_STACK` is in fact [only a tuple](https://github.com/tgalal/yowsup/blob/a26601cdfeaae4f593b9f91df8d7aa4a58d88a3b/yowsup/stacks/__init__.py#L50)):

```
from yowsup.layers import YowParallelLayer

# Former code line: YOWSUP_FULL_STACK
# Now:
YowParallelLayer(YOWSUP_FULL_STACK)
```

**Comment by drencrom** [comment]
That does not work. I think that `YowParallelLayer` should be used when you add a tuple to the layers tuple. In my case I only have this:

    layers = (ipcLayer,) + YOWSUP_FULL_STACK

so I think the `YowParallelLayer` should be used inside the yowsup code.

**Comment by ComFreek** [comment]
Right!
The lines [50-51 of stacks/__init__.py](https://github.com/tgalal/yowsup/blob/a26601cdfeaae4f593b9f91df8d7aa4a58d88a3b/yowsup/stacks/__init__.py#L50-L51)
```python
YOWSUP_FULL_STACK = (YOWSUP_PROTOCOL_LAYERS_FULL,) +\ 
                                              YOWSUP_CORE_LAYERS 
```
should be changed to
```python
YOWSUP_FULL_STACK = (YowParallelLayer(YOWSUP_PROTOCOL_LAYERS_FULL),) +\ 
                                              YOWSUP_CORE_LAYERS 
```

**Comment by drencrom** [comment]
I can't test it right now, but if you are certain that this is the solution you should send a pull request.

**Comment by drencrom** [comment]
Solved the problem using
```python
stackBuilder = YowStackBuilder()

stack = stackBuilder\
	.pushDefaultLayers(True)\
	.push(ipcLayer)\
	.build()
```
