### ISSUE TITLE
unicode message

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#847]
hiii

 how to send multilanguage message using yowsup command line tool??????

**Comment by dedmen** [comment]
as far as i know input is UTF-8 compatible..

**Comment by Dl0tt** [comment]
Make sure that "# -*- coding utf-8 -*-" is the first line of your layer.py (and wherever there's multilanguage letters within the code)

This should fix if you're getting "SyntaxError: Non-ASCII '\x**' in file ***.py on line *** but no encoding declared"

If you're getting something like "UnicodeEncodeError: 'ascii' codec can't encode character u'\x**' in position **: ordinal not in range (128)"

Then it means you're sending a unicode string that contains multilanguage letters, so you need to encode it, like so:

my_string = my_string.encode('utf8')
