### ISSUE TITLE
Create group failed

### ISSUE THREAD

**Issue by Robert213123** [tgalal/yowsup#848]
I'm receveing this error when y try to create a group:

ERROR:yowsup.layers.protocol_groups.layer:Group create failed
<error text="resource-constraint" code="500">

Any help?
##

**Comment by jlguardi** [comment]
I've the same issue:

More detailed info:
```
/groups create subject
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="g.us" xmlns="w:g" type="set" id="1">
<group action="create" subject="subject">
</group>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq type="error" from="g.us" id="1">
<error text="resource-constraint" code="500">
</error>
</iq>

ERROR:yowsup.layers.protocol_groups.layer:Group create failed
```

This software was running last week but now... :(

**Comment by jlguardi** [comment]
However, other commands on groups work correctly:
```
/groups list
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="g.us" xmlns="w:g" type="get" id="7">
<list type="participating">
</list>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="g.us" id="7">
<group s_t="14336xxxxx" creation="14336xxxxx" owner="3xxxxxxxx@s.whatsapp.net" id="3xxxxxxxx-1433xxxxxx" s_o="3xxxxxxxxx@s.whatsapp.net" subject="group name">
</group>
...
```

**Comment by aesedepece** [comment]
That `<error text="resource-constraint" code="500">` sounds to me like you have overpassed the maximum number of groups you can create or join.

**Comment by jlguardi** [comment]
I thought that but I've tested with other lines. Including a new one.

**Comment by aesedepece** [comment]
I have a clue: nn XMPP (the protocol WhatsApp was derived from), such `<error text="resource-constraint" code="500">` is a `wait` error. That means that you have overpassed the maximum number of times you can perform such action __per unit of time__.

If this is true, just try again after 24 hours or so and let's see what happens.

**Comment by Robert213123** [comment]
It works with Chat-API. Si it's a library problem.

Yowsup:
<iq to="g.us" xmlns="w:g" type="set" id="1">
<group action="create" subject="My new Group chat">
</group>
</iq>

ChatsAPI:
<iq xmlns="w:g2" id="2" type="set" to="g.us">
tx    <create subject="My new Group chat">
tx      <participant jid="xxxxxxxxxx@s.whatsapp.net"></participant>
tx    </create>
tx  </iq>

Apparently ChatAPI creates the group with a participant. Yowsup, doesn't. 

Could be that the problem?

**Comment by jlguardi** [comment]
As pointed @Robert213123 the problem is in the library.

If I replace w:g message by w:g2 (and all message content) it works!!!

Participant tag is not required. Works perfectly without it.

I propose this patch:
```
diff --git a/yowsup/layers/protocol_groups/protocolentities/iq_groups_create.py b/yowsup/layers/protocol_groups/protocolentities/iq_groups_create.py
index 91a6ad5..c0810ed 100644
--- a/yowsup/layers/protocol_groups/protocolentities/iq_groups_create.py
+++ b/yowsup/layers/protocol_groups/protocolentities/iq_groups_create.py
@@ -1,9 +1,11 @@
 from yowsup.structs import ProtocolEntity, ProtocolTreeNode
-from .iq_groups import GroupsIqProtocolEntity
-class CreateGroupsIqProtocolEntity(GroupsIqProtocolEntity):
+from .iq_groups_v2 import GroupsV2IqProtocolEntity
+class CreateGroupsIqProtocolEntity(GroupsV2IqProtocolEntity):
     '''
-    <iq type="set" id="{{id}}" xmlns="w:g", to="g.us">
-        <group action="create" subject="{{subject}}"></group>
+    <iq type="set" id="{{id}}" xmlns="w:g2", to="g.us">
+        <create subject="{{subject}}">
+             <participant jid="{{jid1}}"></participant>
+             <participant jid="{{jid2}}"></participant>
+        </create>
     </iq>
     '''
 
@@ -16,12 +18,16 @@ class CreateGroupsIqProtocolEntity(GroupsIqProtocolEntity):
 
     def toProtocolTreeNode(self):
         node = super(CreateGroupsIqProtocolEntity, self).toProtocolTreeNode()
-        node.addChild(ProtocolTreeNode("group",{"action": "create", "subject": self.subject}))
+        cnode = ProtocolTreeNode("create",{ "subject": self.subject})
+        # optional param
+        #cnode.addChild(ProtocolTreeNode("participant",{"jid": jid1}))
+        #cnode.addChild(ProtocolTreeNode("participant",{"jid": jid2}))
+        node.addChild(cnode)
         return node
 
     @staticmethod
     def fromProtocolTreeNode(node):
         entity = GroupsIqProtocolEntity.fromProtocolTreeNode(node)
         entity.__class__ = CreateGroupsIqProtocolEntity
-        entity.setProps(node.getChild("group").getAttributeValue("subject"))
-        return entity
\ No newline at end of file
+        cnode = node.getChild("create")
+        entity.setProps(cnode.getAttributeValue("subject"))
+        entity.setProps(cnode.getChild("participant").getAttributeValue("jid"))
+        return entity
```

I'm going to prepare a pull request on this focus.

Thx.

**Comment by sudhackar** [comment]
@jlguardi Did you make a pull request yet?

**Comment by jlguardi** [comment]
@sudhackar I'm fixing more errors in group management tools. I'll make the pull request today or tomorrow.

**Comment by jlguardi** [comment]
Pull request #872.

note:
group_list currently doesn't work. I've no idea about current protocol for this call.

**Comment by vineet3011** [comment]
@jlguardi  did you find fix of group list ?

**Comment by jlguardi** [comment]
My production code is working. I'll review my master for bugs but I think I made all merges correctly.

**Comment by tgalal** [comment]
@jlguardi I tested your changes from the pull request, and setting group subject as well as everything else worked
