### ISSUE TITLE
Nagios 3 notification no longer working since new version

### ISSUE THREAD

**Issue by borisski** [tgalal/yowsup#849]
I used yowsup a long time for notification together with nagios, 

# sample command.cfg

define command {
        command_name    notify-host-by-whatsapp
        command_line    $USER1$/yowsup/yowsup-cli demos -c $USER1$/yowsup/src/config -s $_CONTACTWHATSAPP$ '$NOTIFICATIONTYPE$ Host : $HOSTNAME$ is $HOSTSTATE$ @ $LONGDATETIME$'   2>&1 | tee -a /tmp/nagios.log
}

define command {
        command_name    notify-service-by-whatsapp
        command_line    $USER1$/yowsup/yowsup-cli demos -c $USER1$/yowsup/src/config -s $_CONTACTWHATSAPP$ '$NOTIFICATIONTYPE$ Host : $HOSTNAME$ - Service : $SERVICEDESC$ is $SERVICESTATE$ @ $LONGDATETIME$' 2>&1 | tee -a /tmp/nagios.log
}
# sample contacts_nagios2.cfg

define contact{
        contact_name                    user1
        service_notification_period     24x7
        host_notification_period        24x7
        service_notification_options    c,r
        host_notification_options       d,r
        service_notification_commands   notify-service-by-whatsapp
        host_notification_commands      notify-host-by-whatsapp
        _whatsapp                               352********
}

I encountered access permission issues and had to configure the file "constants.py" accordingly to point to a directory with wirte access permission for user nagios (otherwise it was trying to write over /root/.yowsup) 

class YowConstants:
    DOMAIN       = "s.whatsapp.net"
    ENDPOINTS     = (
        ("c2.whatsapp.net", 443),
        )

    PATH_STORAGE = "/var/lib/nagios/.yowsup"

    PREVIEW_WIDTH = 64
    PREVIEW_HEIGHT = 64

Now it's working again, hopefully my 2 cents could help someone.

**Comment by tgalal** [comment]
Thanks!
