### ISSUE TITLE
Notification asking to remove participant from group

### ISSUE THREAD

**Issue by davidpaulrosser** [tgalal/yowsup#850]
Hi,

I'm receiving an error asking to remove someone from a group. Am I supposed to do something?

I think it's causing the stream error again for me : /

```
<notification retry="4" participant="xxxx@s.whatsapp.net" t="1433343365" from="xxx-xxx@g.us" offline="4" type="w:gp2" id="4200022493" notify="Cormac McNamara">
<remove subject="xxx">
<participant jid="xxx@s.whatsapp.net">
</participant>
</remove>
</notification>
```

**Comment by aesedepece** [comment]
Do you have the latest Yowsup snapshot?
Notifications with type `w:gp2` are supported since c6b66f4b7c0ce4e2108d98e76afc8e52274356ef (merged on Jan 7).

**Comment by tgalal** [comment]
I assume current code fixes that, reopen if not
