### ISSUE TITLE
Not receiving any Notifications

### ISSUE THREAD

**Issue by dedmen** [tgalal/yowsup#852]
Since the 23rd March i didnt receive any notifications on my yowsup bot. Nothing in my code has changed and i also didnt update yowsup at the time it stopped working. I updated today but its still not working. Before i was getting status and profile picture notifications of every contact i synced but now im not receiving anything.
Im using an American number i got for free (also not changed the number) because with my german number i didnt get any notifications from the beginning on.
Does anybody know if whatsapp has some new limitations?
My german number was totally new but the American number was used before by other people i dont know. 
But i dont think it will just be available after the account had a minimum amount of conversation because im writing with my german bot every day. 
Both are btw receiving presence messages fine.
##

**Comment by aesedepece** [comment]
What layers are in your stack? Maybe the `YowNotificationsProtocolLayer` is not.

**Comment by dedmen** [comment]
Forgot to say im using the cli-demo ^^ sorry

**Comment by dedmen** [comment]
._. Ill have to push this because problem persists. German number no notifications since it was created... And American Number suddenly stopped working :/ I dont know what to do

**Comment by dedmen** [comment]
Changed to a new number still not receiving Any Notifications (Status or Picture) my target is synced and i also did presence subscribe, Nothin...
it just looked like it crashed after i changed my status with xml-not-well-formed but it doesnt crash again when i change my status now.

**Comment by rami-dabain** [comment]
Having the same issue

**Comment by abhiramnarla** [comment]
Maybe your axolotl DB is messed up and you are getting a Exception: No such signedprekeyrecord! 
Even I wasn't receiving any text messages, when I looked into it that was the problem.

**Comment by dedmen** [comment]
Receiving text messages works fine..

**Comment by rami-dabain** [comment]
Indeed, receiving message works fine, but no notifications for image change or status change, presence working though
