### ISSUE TITLE
Simple question. Is this illegal?

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#853]
Hey people, I don't know much about the legal uses of this library. Like, can I simply create a commercial program and use it? Or is it illegal?

**Comment by mgp25** [comment]
Only for personal usage

**Comment by lcmeyer37** [comment]
@mgp25 Okay, so like I can develop an app with this for my company for example? I just cannot sell it. Is that right?

**Comment by CODeRUS** [comment]
personal means you will use it to send messages only to your known contacts and not allow anybody to send messages to other peoples or control your account in any other way.

**Comment by lcmeyer37** [comment]
Okay like, but what I'm doing is a client. That just receives messages of people that want to contact us, and put this on a database. But, they want to contact us, they have our number etc. So, is that ok? Or am I using illegally whatsapp server info or something?

**Comment by aesedepece** [comment]
Everything you do with this software is legal as long as you strictly follow:
* Its license (GPLv3): https://github.com/tgalal/yowsup/blob/master/LICENSE
* WhatsApp Terms of Service: https://www.whatsapp.com/legal/
* Your own country's laws in matter of telecommunications and data protection.

**Comment by lcmeyer37** [comment]
Thank you @aesedepece

**Comment by mgp25** [comment]
@lcmeyer37 @aesedepece negative

Althoug yowsup or WhatsAPI is GPLv3 Licensed or MIT, is UNAUTHORIZED by WhatsApp, and you use it by your own risk.

And as WhatsApp ToS states, you can only use it for personal usage only, this mean to chat with your friends, family etc, NEVER with companies or comercial use

**Comment by lcmeyer37** [comment]
I guess I'm reopening this issue then. Because on the first page it states that "Yowsup is a python library that enables you build application which use WhatsApp service. Yowsup has been used to create an unofficial WhatsApp client Nokia N9 through the Wazapp project which was in use by 200K + users as well as another fully featured unofficial client for Blackberry 10", that's why I thought creating a simple client database woudnl't be a problem @mgp25.

**Comment by mgp25** [comment]
@lcmeyer37 time to time. WhatsApp has been very restrictive lately and are suing API developers + companies using this.
