### ISSUE TITLE
How can I check whether a user has registered an account with WhatsApp

### ISSUE THREAD

**Issue by wormen** [tgalal/yowsup#854]
Tell me, how can I check the availability of the subscriber installed on a smartphone messenger WhatsApp?

**Comment by tgalal** [comment]
I don't understand the question :/

**Comment by wormen** [comment]
How can I check whether a user has registered an account with WhatsApp?
so clearly written?

**Comment by mgp25** [comment]
@wormen sync, check other issues + wiki

**Comment by wormen** [comment]
I have looked anything about it not found

**Comment by widnyana** [comment]
@wormen quick skimmign through issue, i found this [235](https://github.com/tgalal/yowsup/issues/235) maybe that will help

**Comment by tgalal** [comment]
using [GetSyncIqProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_get.py)

Yowsup cli:
```
/contact sync NUMBERS
```
Sync demo:
```
yowsup-cli demos --sync NUMBERS
```

**Comment by wormen** [comment]
incorrectly identifies ...

the first room has an account
```
yowsup-cli demos -c /wa/data/9243230039/config.dat --sync 79143416701
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Iq:
ID: 1
Type: result
from: 79243230039@s.whatsapp.net
Wait: 167361
Version: 1435241195301354
In Numbers:
Out Numbers: 79143416701
Invalid Numbers:

Yowsdown
```

Room on the second account no

```
yowsup-cli demos -c /wa/data/9243230039/config.dat --sync 79145709081
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Iq:
ID: 1
Type: result
from: 79243230039@s.whatsapp.net
Wait: 165802
Version: 1435241195301354
In Numbers:
Out Numbers: 79145709081
Invalid Numbers:

Yowsdown
```

.... In the second query answer is incorrect

**Comment by tgalal** [comment]
use full number with country code and '+' prefix

**Comment by wormen** [comment]
nothing has changed, the same response

**Comment by tgalal** [comment]
then either the number is wrong or doesn't have an account.

**Comment by wormen** [comment]
numbers are correct, this is what I need
identify, have an account or not, but in both cases, the answers are the same, that is not correct, because one of the rooms have a registered account

**Comment by wormen** [comment]
Now check occurs correctly, but there is a problem ... sometimes hangs when checking process

**Comment by antonygunawan94** [comment]
@wormen  @tgalal 
any update according to this issue?
I'm having the same trouble with sync, 
it output the same response even though I give 2 different number
the first one is the correct one
and the second one is the false one
but it output the same output for both of the number
