### ISSUE TITLE
Set profile picture

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#859]
hi,

  I have written code to set profile picture...

but i just want command to be written in yowsup-cli file....

how to pass argument as profile picture path????

Regards..

**Comment by jlguardi** [comment]
yowsup-cli has this function already in the trunk version:

```
@clicmd("Set profile picture")
def profile_setPicture(self, path):
if self.assertConnected() and ModuleTools.INSTALLED_PIL():
def onSuccess(resultIqEntity, originalIqEntity):
```

To use this method:
```
/profile setPicture "/tmp/logo.jpg"
```
