### ISSUE TITLE
demo for receiving message.

### ISSUE THREAD

**Issue by girish946** [tgalal/yowsup#860]
I want to write the code to receive a message.
this module should just receive a message and exit.
can any one give me the directions...
I've gone through yowsup.demos.cli but couldn't understand how to keep the thread alive and receive the messages.

thanks in advance!
##

**Comment by tgalal** [comment]
if you look at [line 53 in echo layer](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/stack.py#L53):
> self.stack.loop()

is what keeps the program from exiting and receive messages

**Comment by shubham14** [comment]
I created a list to append the recevied messages(in layer.py) and then tried printing them out in run.py but it is returning an empty list.Please help
