### ISSUE TITLE
registration failled?

### ISSUE THREAD

**Issue by lingjip** [tgalal/yowsup#864]
yowsup-cli registration -C 86 --phone 8613824364200 -m 460 -n 00 -R 123456 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.82 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=86&in=13824364216&id=%1Dp%21%CB%994P%B3%D9%02%2AG%5E%87%5Ci%9A%0E%E7%9D&code=123456
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/register?cc=86&in=13824364216&id=%1Dp%21%CB%994P%B3%D9%02%2AG%5E%87%5Ci%9A%0E%E7%9D&code=123456
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"guessed_too_fast","retry_after":88}

status: fail
retry_after: 88
reason: guessed_too_fast

**Comment by mgp25** [comment]
Try again, you 'guessed' the code too fast (not human), you need to respect the timing

**Comment by lingjip** [comment]
How to get the password instead of guessing ?

**Comment by tgalal** [comment]
Why are you even guessing?! First you request a registration code using:

>yowsup-cli registration -C 86 --phone 8613824364200 -m 460 -n 00 -r sms

Then you receive a code via SMS to this number, and then you enter that code

>yowsup-cli registration -C 86 --phone 8613824364200 -m 460 -n 00 -R CODE
