### ISSUE TITLE
Convert the audio clip received to text and echoing the text to user rather than echoing the audio clip.

### ISSUE THREAD

**Issue by vyom180** [tgalal/yowsup#866]
Whenever I send any message, echoclient sends the same message back whether it's a text or any media. What I want is that whenever i send an audio recording on whatsapp, it calls a google speech to text converter api(or any other api), convert the audio file to text and echoes it the user.  I have no clue as to how to convert that audio to text. Can somebody guide me?

**Comment by tgalal** [comment]
text - audio conversion is obviously something outside yowsup's scope.

**Comment by vyom180** [comment]
I know it's not but it would be helpful if you tell me how to send the received audio clip to any audio-text converter. and then echo the text to user

**Comment by aesedepece** [comment]
Sure @vyom180, but this is not the right place as for that question as this is an issue tracker for Yowsup library development.
A quick search in your favourite search engine gives you this:
https://pypi.python.org/pypi/SpeechRecognition/
It's well-documented and should fit your needs.
