### ISSUE TITLE
How to convert an audio message to text message using goolge API or somethingelse? #2

### ISSUE THREAD

**Issue by Nakodaji** [tgalal/yowsup#867]
I am working on a project as in automated chat_bot, and i wanna add a new feature of voice chat in it. For that i need to convert the voice message to text using some existing API's and then pass it through the bot and reconvert the textual response created by the bot to an appropriate voice message, but I got stuck in that would you suggest me is there a way out from it ..
using google API or something..

**Comment by tgalal** [comment]
#866 #865   معرفتكش أنا كدة

**Comment by Nakodaji** [comment]
معرفتكش أنا كدة
