### ISSUE TITLE
No such signedprekeyrecord! 1040

### ISSUE THREAD

**Issue by bmutinda** [tgalal/yowsup#869]
Anyone ever received this error while decrypting messages? No matter how many times I retry to connect new database to fix this is not recreated. Using the latest yowsup version. 

Any help appreciated.

**Comment by mutindaz** [comment]
Well,
Got a small solution that I am not sure whether it solves the problem completely or not.
Basically I connected using yowsup-cli, send a message to the number which had the issue and the error was resolved.

**Comment by tunetopj** [comment]
Does somebody know the reason for this error? Any way of avoiding it?
What is it that yowsup-cli does that solves this thing?

**Comment by sinanm89** [comment]
@tunetopj I think its trying to sync/get all the messages it doesnt have up until that point. When I leave the server running for a few minutes it stops giving out the error (try removing the bot from group messages with heavy traffic and re-add after the error is non-present)

**Comment by tunetopj** [comment]
Why would the sync give error? 
Anyways, on leaving the server running for some time, it does some retries stops, but the error occurs again if you restart the server.
Also, how does running yowsup-cli solve this?

**Comment by sinanm89** [comment]
I dont know what gives the error unfortunately. I meant the run.py and
layer.py from the demo. Not the cli.

**Comment by tunetopj** [comment]
Just found that this issue is fixed :
https://github.com/tgalal/yowsup/commit/6ebbbe2eabdadf6521b803975a93c66869aa7535

I need to update my yowsup code :|

**Comment by appa1303** [comment]
Hi,
If you still have this problem, i came across a simpler solution, Delete the SQLIte DB
on windows it can be found in: D:\Users\[user name]\Downloads\yowsup-master\yowsup
