### ISSUE TITLE
receive DLR

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#875]
hi,,

 how to keep track of sent messages????

I mean , how to call message_delivered method????

what command should be written in yowsup-cli?????

Regards,
....

**Comment by tgalal** [comment]
what do you mean by track ?

**Comment by Narendra-Kumar** [comment]
Hi, 
I want to track, that receiver received the message or not. If receiver received, then when he received.

Please help... 

regards
Narendra

**Comment by tgalal** [comment]
Listen for [IncomingReceiptProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_receipts/protocolentities/receipt_incoming.py)
