### ISSUE TITLE
Message not getting received on Whatsapp when I run yowsup-cli demos

### ISSUE THREAD

**Issue by ignitedpear** [tgalal/yowsup#884]
When I run the following command for 10 times in a loop
yowsup-cli demos -d -c CONFIG -s "$number" "$message" >> logs.txt 2>&1

I get "Message sent" for all the 10 messages. But my Whatsapp phone does not receive half the messages:

 I sent:
"Random 1", "Random 2", ... , "Random 10"

What I received on my phone:
Random 1, 2, 4, 6, 8, 10

Why am I not able to get all the messages?

**Comment by jlguardi** [comment]
Try to see logs (-d). Usually, 2 connections too soon fails. So you can try to add a sleep of 2-3 secs between them.

**Comment by ignitedpear** [comment]
In the logs I get same IDs for the messages getting dropped:
id="1434802864-1" (Random 1, received)
id="1434802865-1" (Random 2, received)
id="1434802865-1" (Random 3, dropped)
id="1434802866-1" (Random 4, received)
id="1434802866-1" (Random 5, dropped)
id="1434802867-1" (Random 6, received)
id="1434802867-1" (Random 7, dropped)
id="1434802868-1" (Random 8, received)
id="1434802868-1" (Random 9, dropped)
id="1434802869-1" (Random 10, received)

Adding a sleep of 2-3 secs seems like a hardcoding/hack. Why not ensure that not more than one message gets the same id?

**Comment by ignitedpear** [comment]
This appears to be a race condition. 

In the class MessageProtocolEntity, in __init__(), the following line is the victim of this race condition:
self._id            = self._generateId() if _id is None else _id

Can we synchronize this using a lock or something?

**Comment by jlguardi** [comment]
The problem is that you are calling send method in the same second but by two different executions. It means. You call the program at 1434802865 and the message is sent and you leave the app. Then, in the same second, you call again the app and the message goes out with the same id. So whatsapp server rejects the message. 
It isn't a race condition of the app but your script. Add a sleep of a second and it will work.

**Comment by tgalal** [comment]
@jlguardi is right, thanks for explaining!
