### ISSUE TITLE
How to use Group Info ? 

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#885]
Hi, 

I'm trying to use the group info command (https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/layer.py#L266).

However, in the cli-demo there is no function handling the result ? 

I just see the result in the debug output. 

Thomas

**Comment by jlguardi** [comment]
You can manage it in method:
onIq and check if input entity is of type ListGroupsResultIqProtocolEntity

```
def onIq(self, entity):
  if isinstance(entity, ListGroupsResultIqProtocolEntity): 
    do somthing...
```

**Comment by ThomasRgbg** [comment]
Hi, 

great thanks... just overlooked this....

But can some how match the request and the response ? 

In the log is a transaction ID  visible (at :yowsup.layers.logger.layer:send:tx:
/ yowsup.layers.logger.layer:receive:rx:), but can I get this up to the application level ?

**Comment by tgalal** [comment]
@jlguardi @ThomasRgbg 

In a YowInterfaceLayer  you can use:

> self._sendIq(iqEntity, onSuccess, onError)

onSuccess is a function that gets passed the ResultIqEntity(or a subclass of it), and the IqEntity that was originally sent.
onError is a function that takes the ErrorIqEntity (or a subclass of it), and the  IqEntity that was originally sent.

This way you get only the associated result/error iq responses and don't need to do filtering for them your self using "isinstance". Please [see this](https://github.com/tgalal/yowsup/blob/ea907ce95e4df25f6043f480cbed8d0393d83d7a/yowsup/demos/cli/layer.py#L183) as an example.

**Comment by ThomasRgbg** [comment]
Hi, 

I still have not found a way, how to match the request and response. My problem is, I want to issue requests from different origins, but need to pass the results back. 

So callbacks in your example help me to catch the result, but if e.g. groups list is initiated multiple times, I can't match the result. (Well, Groups list is maybe a bad example for this, group info is a better one)
