### ISSUE TITLE
echo client Disconnect after some time

### ISSUE THREAD

**Issue by paul218** [tgalal/yowsup#886]
i did an aplication with echo client using layer.py and run.py ..but after some time the run.py is disconnect and closed  ..i am using the lasted version of youwsup (yowsup-cli v2.0.9 yowsup v2.3.84)
please how i can solved this ???
##

**Comment by jlguardi** [comment]
It usually means that you forget to send acks of input messages/notifications/iqs/acks but you send message or other packages.

Review your code and check receipt acks.
