### ISSUE TITLE
Whatsapp Voip 

### ISSUE THREAD

**Issue by biddyweb** [tgalal/yowsup#887]
Played around with voip calls over this weekend. Was able to ring different phones although this has not been consistent. Might be going into the audio proper over the week. Anyone interested in joining me in this implementation? Please leave a message.
##

**Comment by aesedepece** [comment]
As it has been said some times WhatsApp voice calls are out of the focus of this project.

Nevertheless, I'm personally interested on it. Count on me.

**Comment by assegaf** [comment]
hmm this is interesting, voip call sip ?
I am interested, let me know what is your github project url for this.

**Comment by mgp25** [comment]
Good luck

PJSIP, SDES enc... as it is p2p calls, you will need to {r. engineer}, be careful what goes public whatsapp is around the corner, just saying... :smile:

**Comment by biddyweb** [comment]
Just for introduction. With my research online and personally, they dont use SIP. They use a custom version of XMPP like in the rest of the protocol(FunXMPP).  Also calls are routed peer-to-peer.

**Comment by biddyweb** [comment]
So is there anywhere we can have a closed community meeting where the "Eyes of Whatsapp" cant reach.

**Comment by mgp25** [comment]
@biddyweb they only use FunXMPP for setup/teardown, not data. I think we have more or less a prototype of how it works and how to do it. I don't think people will use it as it is supposed to be used

**Comment by biddyweb** [comment]
@mgp25  Is right. FunXMPP is used for only signalling.

**Comment by assegaf** [comment]
I see, same as event of xmpp for signaling, is it possible to use asterisk as its core gateway voice ?

**Comment by biddyweb** [comment]
Yes but i think it would require creating an asterisk module for that which will be able to understand FunXMPP.

**Comment by assegaf** [comment]
https://github.com/bg111/asterisk-chan-dongle/

this could help understanding how to create asterisk module, by copying its purpose.
unfortunately dont understand c lang.

**Comment by emamirazavi** [comment]
You can count on me. Asterisk is obsolete and heavy soft switch and it's
very distant solution for a server written with good light programming
language like erlang. XMPP can be used just for signaling. It may be peer 2
peer because for now WA does not support conference calls.

**Comment by CODeRUS** [comment]
may be, can be. wtf? get wireshark in your hands and check it. and yes, of course it peer to peer.

**Comment by blackjack4494** [comment]
I cannot remember that good. I did some research before but did not post any packet analyzer log. 
A little bit you can find here:
https://github.com/tgalal/yowsup/issues/695#issuecomment-94174088

First I thought WhatsApp is using Jingle (extension for XMPP) but it seems to be using 
http://www.pjsip.org/
Have fun with your research. Hope this can help you to at least start. Just see this guess as a possibility because it can also be something else. You know whatsapp likes to create or modify existing things for their own use.

**Comment by emamirazavi** [comment]
If it uses pjsip, PJ has python module and it can handle call on your OS...
If anybody can research on this(using pjsip by WA server), do and give us
the feedback.

**Comment by assegaf** [comment]
I think we must focus on signaling first which are already xmpp and make documentation of it.
the simple one, like accept and reject, and dial ...

**Comment by mgp25** [comment]
@assegaf we know already that signaling, irrelevant at this step and pretty easy to do

**Comment by blackjack4494** [comment]
@emamirazavi pjsip is written in c so it does not matter if we are using android or python or linux etc. ;)
as well i edited my post some minutes after you commented. There is already an android app with all functions even video ;)

**Comment by biddyweb** [comment]
@blackjack4494 Is this android app open source.Can you give name of the app. Thanks

**Comment by blackjack4494** [comment]
@biddyweb when you see this is hosted on code.google.com you should know there is code in 99% of all cases. so yes it is open source.
https://code.google.com/p/csipsimple/source/browse/trunk/CSipSimple
Better use git. I personally do not like their source interface

**Comment by biddyweb** [comment]
This is not whatsapp bro. I have worked with csipsimple,linphone and sipdroid. They all use SIP.

**Comment by blackjack4494** [comment]
Yeah they do use SIP.
Also there is Google Talk:
https://developers.google.com/talk/call_signaling

You can see a nice documentation how all those things work. It is the same procedure whatsapp uses.
what may be also some difficult is to figure out how the bridge in whatsapp between xmpp and the voip lib works. for that a good packet analyzing is needed.

**Comment by mgp25** [comment]
@blackjack4494 packet analyzing wont help as much as you think, you need to check elsewhere :wink:

**Comment by biddyweb** [comment]
@mgp25  Why do you think packet analysing wont help? Been using the packet data and made some headway already.

**Comment by mgp25** [comment]
@biddyweb because im used to deal with WhatsApp stuff and i know how this protocol works, anyway, if you want try with withshark and will check yourself

**Comment by biddyweb** [comment]
@mpg25 Can you give insight in how to decrypt the hex data in the packets??

**Comment by biddyweb** [comment]
During a call i get session, i get this:
<call from="xxxxxxxxxxxx@s.whatsapp.net" id="1434981563-168" t="1434997462">
<reject call-id="1434997443-1" reason="unsupported-audio-caps">
</reject>
</call>
I assume its because am not sending the appropriate info on codecs etc.

**Comment by emamirazavi** [comment]
@mgp25 Can you please describe the protocol and how it works?!

**Comment by aabdelrahmanm** [comment]
@biddyweb are you still working on this stuff? I'd love to contribute if you are interested please let me know :).

**Comment by blackjack4494** [comment]
any news on this?

**Comment by dylanmoring** [comment]
I'm not in any position to contribute (unfortunately, not a programmer), but this paper looks like it might help for anyone interested in working on something like this:

http://www.fit.vutbr.cz/research/pubs/index.php?file=%2Fpub%2F10979%2FWhatsApp.pdf&id=10979

**Comment by Mazuco** [comment]
Humm very interesting.

Maybe is possible to inter ligation WhatsApp VoIP to Asterisk VoIP?

Or with Telegram app?




2016-03-10 13:29 GMT-03:00, dylanmoring <notifications@github.com>:

**Comment by thundergreen** [comment]
+1 for transwhat and conversations

Thorsten Fröhlich
Am 10.03.2016 19:34 schrieb "Vitor Mazuco" <notifications@github.com>:

**Comment by blackjack4494** [comment]
@biddyweb can you publish your code you used to ring some phones? i got some spare time and would like to have a look on this (:

**Comment by markosjal** [comment]
Here is my 2 cents. 

I wanted a way to route and answer whatsapp calls on my PBX. 

I came up with the idea of using an android set top box (sideloaded APK because Play store would not let me load it) and chan_mobile (bluetooth) , however it seems whatsapp calls can not be answered using bluetooth , at least on any android device I have tried, and I have now tried a few with standard handsfree devices.

If you ask me this is a serious oversight on the part of whatsapp and as I have now told them it is dangerous that while driving thy can only answer a call with a swipe.  They claim "...contact the device manufacturer...." , meanwhile the device manufacturer would clearly nopt support a 3rd party app

ANyone here answering whatsapp or skype calls on android via a bluetooth device?

It turns out Skype may have he same issue as I hoped that I could use one android device and chan_mobile to answer both skype and whatsapp. 

we work so hard to make standards compliant protocols so some jerk can come along and give us a proprietary protocol that interfaces to absolutely nothing.

**Comment by mirh** [comment]
> http://www.fit.vutbr.cz/research/pubs/index.php?file=%2Fpub%2F10979%2FWhatsApp.pdf&id=10979

Cool paper. Another sum up is [here](https://webrtchacks.com/whats-up-with-whatsapp-and-webrtc/).

**Comment by tgalal** [comment]
no plans

**Comment by assegaf** [comment]
I am successfully integrate both inbound and outbound rtp audio to sip using android phone only, not a server/pc/yowsup.

**Comment by mobilipia** [comment]
> I am successfully integrate both inbound and outbound rtp audio to sip using android phone only, not a server/pc/yowsup.

Can you show us code?

**Comment by assegaf** [comment]
there is no code actually, just specific hardware that modified and custom rom android, so I am sorry it only for specific android machine I develeop.

**Comment by assegaf** [comment]
Successfully developed implementation to do simulate sound from microphone, please anybody who want to contribute join our fb group for more technical development
https://www.facebook.com/groups/503559474430266

**Comment by g4w4** [comment]
@

> Successfully developed implementation to do simulate sound from microphone, please anybody who want to contribute join our fb group for more technical development https://www.facebook.com/groups/503559474430266

how can i start the project and help

**Comment by assegaf** [comment]
join the facebook group and start testing in private, I have the testing ready

**Comment by assegaf** [comment]
demo available using free sip server,
https://github.com/assegaf/siptowhatsapp

**Comment by brewkon** [comment]
Completed all voice call functions
https://github.com/brewkon/WhatsappVoiceCall

**Comment by andreensteven** [comment]
https://github.com/andreensteven/whatsapp-voice-call
