### ISSUE TITLE
 how can i Write a simple Yowsup Send client and Echo client

### ISSUE THREAD

**Issue by paul218** [tgalal/yowsup#890]
i can use Echo clien with run.py and layer.py ..but now i need to do echo for for incoming messages and   at any time send a  message ....how can i use echo and send client together

**Comment by jlguardi** [comment]
You cannot use echo client and call externally send client. You can edit cli/layer to add an echo and call this app.

**Comment by paul218** [comment]
i am a new in python ....how can i a send message in echo client

**Comment by zoraf** [comment]
I have seen that downloading yowsup-cli master, a demo echo app is inside demos folder. but how can i use it??
