### ISSUE TITLE
New enc type "skmsg", also new enc v(ersion) 2

### ISSUE THREAD

**Issue by fridtjof** [tgalal/yowsup#898]
I received an encrypted message today which looked like this:

``` xml
<message retry="2" participant="xxx@s.whatsapp.net" notify="xxx" phash="1:6juc6XCc" from="xxx@g.us" offline="2" type="text" id="1435254452-61" t="1435269065">
<enc type="skmsg" v="2">
�UOGl���ޝ
�j�6%2P�0Z;f������1O'�_zٕv����Վ�T�8��z:��-   ���i����?%<�9üD2~�D�GS�m�5� @U߫������
HEX:3308caf99c8e0610021a402563dc5cc5138c1b04f45746bf3942378e18d7ad430d9b554f476c9f91c1de9d0ac56ab636253250e5305a3b66a8a0b4dff3ff314f27f3b95f7ad9957699cfe0bdc1d58edc5402d03897937a3adce22d09f48400ced1698bbc9a9f3f253cd339c3bc44327e01b244d647531db16da4350eb0204055dfab87e8f78b07fc0bef86
</enc>
</message>
```

When YowAxolotlLayer tries to process it, this happens:

  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps
    assert encType in "pkmsg", "msg"
AssertionError: msg

**Comment by assegaf** [comment]
interesting, do you know what device and version the message came from ?
it seem like its https://en.wikipedia.org/wiki/PKCS_12

**Comment by CODeRUS** [comment]
@assegaf its TextSecure, not PKCS https://github.com/WhisperSystems/libaxolotl-java

**Comment by assegaf** [comment]
oh I see, seem its the new version 2 ?
I wonder from what version and Device, whatsapp update it

**Comment by prasselpikachu** [comment]
I asked the sender of this message. She specified the following:

Android 4.1.1
WhatsApp 2.12.124
On an Asus Padfone 2

**Comment by prasselpikachu** [comment]
Any news on this?

**Comment by CODeRUS** [comment]
I don't see group encryption with 2.12.161 version

**Comment by assegaf** [comment]
I tried to check newest 2.12.158 android, seem its send using encription as default , not checking first if target support encription or not
sample TX :   
[message to="yyyyyy@s.whatsapp.net" type="text" id="1435182781-2"]
 [enc v="2" type="pkmsg" ]
  ** some encoded msg **
 [/enc]
[/message]


kinda weird, pkmsg and skmsg, thats two different mode, except @prasselpikachu  have typo ?

**Comment by prasselpikachu** [comment]
The reason I saw this was exactly the type; It made yowsup crash in the first place due to EncryptedMessageProtocolEntity asserting type == "pkmsg"

**Comment by CODeRUS** [comment]
@assegaf pkmsg is KreKeyMessage skmsg is SnderKeyMessage, RTFM please before asking.

And i still see no group encryption for me, so can't sniff it and implement it

**Comment by hyades** [comment]
Same issue for

**Comment by CODeRUS** [comment]
what vrsion you using? i'm updating whatsapp every day and still see no group encryption

**Comment by hyades** [comment]
@CODeRUS 2.12.158, android 5.0.2

**Comment by prasselpikachu** [comment]
Correct me if I don't get it, but what does this have to do with group messages? Looking at the JID, it's a private message, right?

**Comment by assegaf** [comment]
seem from group.
from="xxx@g.us" ..

**Comment by prasselpikachu** [comment]
Oh, you're right. Nevermind lol

**Comment by Dl0tt** [comment]
I had this problem whenever the program received messages from a group I created, but it didn't happen on groups created by other numbers. Changing the env to S40YowsupEnv() solved it for me.

**Comment by CharlesOkwuagwu** [comment]
Try this,
Login with WHATSAPP_VER = "2.12.81" and you always receive `<enc v="1" ...>`
Login with WHATSAPP_VER = "2.12.*88*" and you start to receive `<enc v="2" ...>`

**Comment by CharlesOkwuagwu** [comment]
Decrypting v="2" message with existing v="1" code:
`<message from="XXXXXXXXXXXXX@s.whatsapp.net" id="1436700596-18" type="text" t="1436774161" notify="XXXXX XXXXX">
  <enc v="2" type="msg">330A21051628D4A152DF1B536DCC3B00EB946967DF63964CB174D1F636B406395A16EC0F100218032210EC2F66534BE7600279B886AB34E5CA525BBCDEFCC11CEA75</enc>
</message>`


WhisperMessage
ratchetKey = 051628D4A152DF1B536DCC3B00EB946967DF63964CB174D1F636B406395A16EC0F
counter = 2
previousCounter = 3
ciphertext = EC2F66534BE7600279B886AB34E5CA52
`[LF] [TAB]**Connected**[SOH]'

Just seems to add some additional `SOH` padding after the message, and `TAB and LF` before it. 

Besides that, it seems you can decode v2 encrypted messages with v1 decryption

**Comment by tgalal** [comment]
@CharlesOkwuagwu thanks for the info!

**Comment by CharlesOkwuagwu** [comment]
hi Tgal, there is more info...

**Comment by Wilm0r** [comment]
So do I understand correctly that I can choose between having my client crash on a NoneType dereference, or have my client crash on this assertion, when I receive these new encrypted messages?

It would be nice if yowsup could swallow these messages, report to the client that it received a message it could not decode, and move on with life...

**Comment by K4CZP3R** [comment]
bump, what can i do?

**Comment by alafanechere** [comment]
I encounter the same issue.
I solved some registration issues by implementing changed proposed by @jlguardi  in his PR: 
[https://github.com/tgalal/yowsup/pull/1336/files](url)

After these changes my environment is the following : 
````
_MD5_CLASSES = "7UDPOXwpiLBvEjT8uNwsuA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.12.440"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "GalaxyS3"
    _AXOLOTL = True
```

And I keep getting this `AssertionError: msg` after login successfully with the `/login` command on `yowsup-cli demos -y` console.

I indeed wrote a message in a group in which my 'bot' is a participant.

**Comment by jlguardi** [comment]
In my pull request #1336 I've changed env from S40 to android for registration and running so group messages encryption is enabled.
Enable again S40 env for runtime and it will fix the issue. However someone should implement skmsg and pkmsg before the end of S40 support. 
I'll try to por from chat-api but I think it's too hard for me.

**Comment by alafanechere** [comment]
Thanks for the answer. Unfortunately  I still have the same error when I get back to S40 env like so : 
in `warerequest.py`
````
from yowsup.env import S40YowsupEnv
CURRENT_ENV = S40YowsupEnv()
````

**Comment by alafanechere** [comment]
Thanks @jlguardi  I figured this out. So when I use the current master version of Yowsup, with the S40 environment now I encounter this error while trying to receive a message from a group : 
````
ERROR:yowsup.layers.axolotl.layer:Unknown version: 5
`````
Here you have the log provided by the `yowsup-cli demos` in console mode, after logging successfully : 
````
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<message participant="33645492037@s.whatsapp.net" notify="augustin lafanechere" from="33645492037-1457638332@g.us" type="text" id="65CB2575B2FB7F2FADAB1C74FF5CFC" t="1457686350">
<enc type="skmsg" v="2">
?\?AN??zD?dľo?qDFH???PzVm?,c?v9j?f:?
HEX:3308dca882ca0410081a202280879b2906cca2b31bab9485c3301b94279514ae84e2f99fef20f6835850fc5c5e3ebaa065f7d3ebbd0daa8fafb10d93ef8f9c135c99414eb6d07a44119a646ccc8c6f8d71444648a1abc2501e7a561d6d892c1a63d8c28376396ac5663a84
</enc>
</message>

ERROR:yowsup.layers.axolotl.layer:Unknown version: 5
DEBUG:yowsup.layers.logger.layer:tx:
<receipt to="33645492037-1457638332@g.us" type="retry" id="65CB2575B2FB7F2FADAB1C74FF5CFC">
<retry count="1" v="2" t="1457686350" id="65CB2575B2FB7F2FADAB1C74FF5CFC">
</retry>
<registration>
D??K
HEX:44fc3f4b
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<ack type="retry" from="33645492037-1457638332@g.us" class="receipt" id="65CB2575B2FB7F2FADAB1C74FF5CFC">
</ack>

````

**Comment by msshapira** [comment]
@jlguardi looks like tgalal is not pushing the port from chat-api.
Maybe it's time to fork off from yowsup and start merging PRs and implement
e2e encryption.
I guess i can look into porting this...

**Comment by tgalal** [comment]
@msshapira I am working on it on wa16 branch

**Comment by msshapira** [comment]
@tgalal
Thanks. Was getting worried you had forfieght the repo

**Comment by yniv** [comment]
If i register a number with the new Android env and then run it on the S40 env it will work??
Also, you're talking about the end of S40 support... I already have some numbers which are already registered with S40 and working for a long time already... does that mean they will get blocked eventually???? do I need to re-register them as android?

**Comment by K4CZP3R** [comment]
Yes, i did it so

**Comment by jlguardi** [comment]
No, I've got some numbers registered with S40 but working with Android env. The Id is used for registration (Id differs from S40 and Android) but in all other operations but registering, just password is required and no check about architecture is made.
In summary, you can change from S40 env to Android env with problems but some encryption issues will appear due to unsupported API (WIP in branch wa16).
However, I'm still using S40 upon protocol 1.6 was implemented.

**Comment by yniv** [comment]
@jlguardi  So the code you added in the last days are only for registering new numbers ? 
after you register them you still run them with the S40 env?

**Comment by jlguardi** [comment]
@yniv Yes it is. I modified #1336 to use android at register time and S40 in the normal usage.
