### ISSUE TITLE
status Whatsapp account

### ISSUE THREAD

**Issue by wormen** [tgalal/yowsup#899]
Tell me, how can I check the account is locked or not

**Comment by jlguardi** [comment]
If you get not-authorized while session init, possibly  you are blocked. You can check with registration again and you will get more info. If reason is 'blocked' you need to wait for 45 days!

**Comment by wormen** [comment]
This is understandable, but I'm interested in is the process of checking the status of

**Comment by CODeRUS** [comment]
status of account is received after (un)authorization. Additionaly you will receive blocked details during registration. No other ways you can use are exists.
