### ISSUE TITLE
How to send  message to a group using Yowsup-cli?

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#903]
Hello,

in the youwsup cli there are many commands related to groups, that i have successfully used (create, demote, promote, kick, list, and so on) but i wasn't able to find the way for send message to a group, so the question issue is: How to send message to a group using yowsup-cli ?

Regards

**Comment by jlguardi** [comment]
It's like normal message but jid is longer. Actually, jid format is creatorjid-timestamp. You can get the list of groups that you belong with '/groups list'. I mean, use /message send xxxxx-ttttt "my messade" to send a group message.

**Comment by Agandir** [comment]
Perfect, now is clear, thanks :)
