### ISSUE TITLE
Match Callbacks with the original request

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#906]
Hi, 

it is maybe better to continue on a new issue, since a new question. Original is #885.

I still have not found a way, how to match the request and response. My problem is, I want to issue requests from different sources, but need to pass the results back.

So callbacks in your example in #885 help me to catch the result, but if e.g. groups list is initiated multiple times, I can't match the result. (Well, Groups list is maybe a bad example for this, group info is a better one)

**Comment by tgalal** [comment]
I don't understand why initiating multiple times would not match request/response if you use _sendIq ?

**Comment by ThomasRgbg** [comment]
Maybe I just do a silly python misunderstanding, but something I would like to do:

(taking your example again as base)
'''
  def profile_setStatus(self, text):
        if self.assertConnected():

            def onSuccess(resultIqEntity, originalIqEntity):
                result = str(resultIqEntity)
                return result

            def onError(errorIqEntity, originalIqEntity):
                logger.error("Error updating status")

            entity = SetStatusIqProtocolEntity(text)
            self._sendIq(entity, onSuccess, onError)

            # Here I would like to use the result from onSuccess().
            print(result)
'''

But my understanding is, onSuccess() will be called much later when profile_setStatus() is already long finished. (Since the response from the Server could come in much later)

But is there a way to bring this result back into the original function.

Doing this with global variables is not easy as soon a second request is send before the result comes in. And resultIqEntity does not contain the IQ-id (sequence number?), so I can not match the results easily.

**Comment by tgalal** [comment]
ah now I got it. You want a blocking wait for response. That's not supported at the moment, might be something worth adding though. Anyway for now, I think you can get around your problem by doing something like this:


```python
  def profile_setStatus(self, text):
        if self.assertConnected():

            def onSuccess(resultIqEntity, originalIqEntity, var1, var2):
                result = str(resultIqEntity)
                return result

            def onError(errorIqEntity, originalIqEntity, var1, var2):
                logger.error("Error updating status")
           
            var1 = "something"
            var2 = "something
            successWrapper = lambda successEntity, originalEntity: onSuccess(successEntity, originalEntity, var1, var2)
            errorWrapper = lambda errorEntity, originalEntity: onError(errorEntity, originalEntity, var1, var2)


            entity = SetStatusIqProtocolEntity(text)
            self._sendIq(entity, successWrapper, errorWrapper)
```

This way, variables that were declared at the specific request, will be passed directly to associated callbacks only, and you can use them from there without needing global vars

**Comment by ThomasRgbg** [comment]
works, thanks a lot.
