### ISSUE TITLE
Call backs for Group Info not working

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#908]
Hi, 

taking the recommendations for the callback handling in #885, this works for groups list very well. 

However, for group info, I don't see the onSuccess callback is called. While e.g. in groups list it works.

**Comment by tgalal** [comment]
Something like this in your YowInterfaceLayer should work
```python 
def onGroupCreateSuccess(self, resultIqEntity, originalIqEntity):
    print(resultIqEntity)
def groups_create(self, subject):
    entity = CreateGroupsIqProtocolEntity(subject)
    self._sendIq(entity, self.onGroupCreateSuccess)
```
