### ISSUE TITLE
install yowsup on synology DS215j

### ISSUE THREAD

**Issue by NCS80** [tgalal/yowsup#910]
Hi,

I've been experementing with yowsup and I think it's really cool, so thumbs up for you guys!

Now I want to run it from my NAS since it can handle python and it's always up.
Only think is I got some problems installing it on there and I was wonderinng if someone could give me some advice.

The main problem is that, in the setup script, it fails to setup Pillow. This because of the fact that ccache isn't available. I've tried to install it but compiling it fails due to, since the DS215j uses the Marvell Armada 375 chip, gcc doesn't compile on that platform.

Is there a way to get yowsup working by cross compiling or something?
Or does it work without using pillow since I don't want to send images anyway?

Hope someone can help, thanks in advance!

gr

N
##

**Comment by tgalal** [comment]
you can download the repo, change setup.py to remove pillow from dependencies at [line 7](https://github.com/tgalal/yowsup/blob/master/setup.py#L7), the install using ```python setup.py install```

**Comment by NCS80** [comment]
Yeah tried that, but then I discovered I get the same error for python-axolotl-curve25519-0.1

maybe if I cross compile all that on a linux distro and put in all the files manually, would that work?

**Comment by tgalal** [comment]
I guess if compiled on same arch then might work. You can however omit also 'python-axolotl' from dependencies in setup.py and then just don't use axolotl layer nor '--moxie' switch in yowsup cli

**Comment by NCS80** [comment]
ok interesting! Don't you need it to communicate with whatsapp?
What is it exactly used for?

**Comment by tgalal** [comment]
it activates end to end encryption. It's not yet available in whatsapp on all platforms which allows us to disable it in yowsup for now.

**Comment by NCS80** [comment]
Aha but this can give problems in the future?

Thanks a lot for your help man, really appriciate it!

**Comment by tgalal** [comment]
For sure when whatsapp makes e2e encryption mandatory on all platforms it would be problem, but I have no idea when this would happen though.

**Comment by NCS80** [comment]
Hmm we'll see then, not a problem to worry about right now. Hopefully a compiler will be available when that time comes!

I'll continue experimenting,  again, thanks for the help!

**Comment by NCS80** [comment]
One more question.

I get errors on axolotl when using yowsup-cli demos --yowsup --login and also in the sample code.
I guess it has to do with the YowAuthenticationProtocolLayer. How can I configure not to use axolotl?

thx

**Comment by tgalal** [comment]
I've just updated the demos in commit f47d6f9780939cdde647388a363e01f3e496ee85 to not crash when no axolotl is installed. So try using yowsup's develop branch now.

**Comment by NCS80** [comment]
Thx!
