### ISSUE TITLE
DuplicateMessageException: 

### ISSUE THREAD

**Issue by akhld** [tgalal/yowsup#911]
I'm hitting this exception ever since i got the example sample app crashed after making some changes to it.

   axolotl.duplicatemessagexception.DuplicateMessageException: Received message with old counter: 1, 0

Any workaround to get ride of it?

**Comment by akhld** [comment]
never mind, used the cli to get ride of it.

**Comment by sinanm89** [comment]
Im currently getting this. The workaround I've done is comment out the else block at line 184 in sessioncipher.py ;

    else:
        raise DuplicateMessageException("Received 
            "with old counter: %s, %s" % (chainKey.getIndex(), counter))

after that I uncomment these lines and re-run it. Its dirty but works for me at the moment.
