### ISSUE TITLE
How do I send continuous ping to a user using the same stack?

### ISSUE THREAD

**Issue by nihalsharma** [tgalal/yowsup#913]
The cli tool, on each send, spins up a new stack and send the message. How do I send multiple message using the same stack (no new stack per message)? Or I have to create new stack for each message?

**Comment by tgalal** [comment]
what do you by spins up a new stack for each message, which cli tool ?

**Comment by nihalsharma** [comment]
I am using yowsup-cli2. The example of send client creates a new stack and then sends all the messages in the queue. It is send only one time. If I have to send messages continuously, I can not simply put the messages in the queue and send, as the method is called only once. For that I have to create a new stack and put the next set of messages in the queue and then send it. 

I simply needed a solution where I can put the messages in the queue any time I want to, and it is listened by methods which triggers send call. Can you please help me out here?

Thanks

**Comment by tgalal** [comment]
Yes that's what the send client does. Sends messages in the queue and exits. You can for example modify it to not raise the Interrupt at line 49, and have a thread consuming a blocking queue that sends messages as they're added
