### ISSUE TITLE
Problems in string decoding in Python3

### ISSUE THREAD

**Issue by SafaAlfulaij** [tgalal/yowsup#918]
When using python3, and trying to get _Arabic_ text messages bodies, I get some strange text as a result.
Examples:
"Ø§Ø¹Ø±ÙÙÙ Ø§Ø®Ø±Ø·Ù ÙØ­Ø¯ Ø¨ÙØ­Ø¶Ø±"
"ð" < should be an Emoji.
I think it's a problem with that "latin-8" encoding/decoding.
##

**Comment by tgalal** [comment]
please post stacktrace

**Comment by SafaAlfulaij** [comment]
Python doesn't report any problems, it runs yowsup example normally. I can't see any usage of debugging a working situation :)

**Comment by ihfazhillah** [comment]
this problem in python3

**Comment by tgalal** [comment]
fixed
