### ISSUE TITLE
Send location

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#924]
hi,,

  i want to send location to destinaton... how do i send location using yowsup demos????

Regards

**Comment by carlosdiaz** [comment]
Hi, I'm interested in this topic as well, can anybody point one example about how to do this?

**Comment by Dl0tt** [comment]
latitude="28.3744278" #from -90 to 90, positive means north and negative means south
    longitude="-81.5494113" #from -180 to 180, positive means east and negative means west
    locationName="Epcot\n200 Epcot Center DR, Orlando FL" #optional, the first line will become a clickable link, the second won't
    locationURL="disneyworld.disney.go.com" #optional, this is the link you'll be redirected when you click the locationName
    locationEncoding="raw" #don't touch this
    outLocation = LocationMediaMessageProtocolEntity(latitude,
    	longitude, locationName,
    	locationURL, locationEncoding,
    	to = messageProtocolEntity.getFrom())
    self.toLower(outLocation)

optional arguments can be replaced by:

    locationName=None
    locationURL=None

**Comment by Narendra-Kumar** [comment]
Can you please advise where to add this code????
I have created layer.py for the same but no result. I am not getting any error but below code is not working..

outLocation = LocationMediaMessageProtocolEntity(latitude,
    longitude, locationName,
    locationURL, locationEncoding,
    to = messageProtocolEntity.getFrom())
self.toLower(outLocation)

**Comment by Dl0tt** [comment]
On layer.py make sure you imported the protocolentities for media:
```python
from yowsup.layers.protocol_media.protocolentities	import *
```
also, on run.py you should have YowMediaProtocolLayer imported and on your layers tuple:

```python
from yowsup.layers.protocol_media		import YowMediaProtocolLayer
```
then
```python
    layers = (
        (...)
        YowMediaProtocolLayer,
        (...)
```

**Comment by carlosdiaz** [comment]
Hi @Narendra-Kumar, I tested and worked, I recommend you to try the echo example:

in run.py
```python
if __name__==  "__main__":
    layers = (
        EchoLayer,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, 
            YowReceiptProtocolLayer, YowAckProtocolLayer,
            YowMediaProtocolLayer)
    ) + YOWSUP_CORE_LAYERS

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)              
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal

    stack.loop() #this is the program mainloop
```

and then in layer.py
```python

from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_media.protocolentities     import *

class EchoLayer(YowInterfaceLayer):

    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):

        if messageProtocolEntity.getType() == 'text':
            self.onTextMessage(messageProtocolEntity)
        elif messageProtocolEntity.getType() == 'media':
            self.onMediaMessage(messageProtocolEntity)

        self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
        self.toLower(messageProtocolEntity.ack())
        self.toLower(messageProtocolEntity.ack(True))


    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        self.toLower(entity.ack())

    def onTextMessage(self,messageProtocolEntity):
        # just print info
        print("Echoing %s to %s" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False)))

    def onMediaMessage(self, messageProtocolEntity):
        # just print info
        if messageProtocolEntity.getMediaType() == "image":
            print("Echoing image %s to %s" % (messageProtocolEntity.url, messageProtocolEntity.getFrom(False)))

        elif messageProtocolEntity.getMediaType() == "location":
            print("Echoing location (%s, %s) to %s" % (messageProtocolEntity.getLatitude(), messageProtocolEntity.getLongitude(), messageProtocolEntity.getFrom(False)))

        elif messageProtocolEntity.getMediaType() == "vcard":
            print("Echoing vcard (%s, %s) to %s" % (messageProtocolEntity.getName(), messageProtocolEntity.getCardData(), messageProtocolEntity.getFrom(False)))
```
try to send your location and see what you get .

Cheers

**Comment by Narendra-Kumar** [comment]
i tried above code...

LocationMediaMessageProtocolEntity is not getting called.. Not getting any error but no success also.

Please advise

**Comment by Dl0tt** [comment]
Post your run.py

-------- Original Message --------

**Comment by Narendra-Kumar** [comment]
run.py

def __init__(self, credentials, location, encryptionEnabled = False):
        
        if encryptionEnabled:
            layers = (
                LocationLayer,
                (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer,YowAckProtocolLayer,YowMediaProtocolLayer,YowIqProtocolLayer,YowChatstateProtocolLayer,YowProfilesProtocolLayer),
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
            )
        else:
            env.CURRENT_ENV = env.S40YowsupEnv()
            layers = (
                LocationLayer,
                (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer,YowAckProtocolLayer,YowMediaProtocolLayer,YowIqProtocolLayer,YowChatstateProtocolLayer,YowProfilesProtocolLayer),
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
             )

        self.stack = YowStack(layers)
        self.stack.setProp(LocationLayer.PROP_location, location)
        self.stack.setProp(YowAuthenticationProtocolLayer.PROP_PASSIVE, True)
        self.stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, credentials)
        self.stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])
        self.stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
        self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())

    def start(self):
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
        try:
            self.stack.loop()
        except AuthError as e:
            print("Authentication Error: %s" % e.message)


layer.py

from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_contacts.protocolentities  import GetSyncIqProtocolEntity, ResultSyncIqProtocolEntity
from yowsup.layers.protocol_iq.protocolentities import ErrorIqProtocolEntity
import threading
from yowsup.layers.protocol_media.protocolentities  import LocationMediaMessageProtocolEntity
import logging
import sys
logger = logging.getLogger(__name__)

class LocationLayer(YowInterfaceLayer):

	PROP_location = "org.openwhatsapp.yowsup.prop.syncdemo.picture"

	def __init__(self):
		super(LocationLayer, self).__init__()
		self.ackQueue = []
		self.lock = threading.Condition()
		self.connected = True
		self.jidAliases = {
			# "NAME": "PHONE@s.whatsapp.net"
		}

	#call back function when there is a successful connection to whatsapp server
	@ProtocolEntityCallback("message")
	def onMessage(self, messageProtocolEntity):
			location= self.getProp(self.__class__.PROP_location, [])
			print "IQ:\n", location
			latitude="28.3744278"
			longitude="-81.5494113"
			#to="919898989898"
			
			locationName="Epcot\n200 Epcot Center DR, Orlando FL"
			locationURL="disneyworld.disney.go.com"
			locationEncoding="raw"
			outLocation = LocationMediaMessageProtocolEntity(latitude,longitude, locationName,locationURL, locationEncoding,to = "918898080801")
			self.toLower(outLocation)

			self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
			self.toLower(messageProtocolEntity.ack())
			self.toLower(messageProtocolEntity.ack(True))

			#self._sendIq(outLocation)
			#sys.exit(1)

	@ProtocolEntityCallback("ack")
	def onAck(self, messageProtocolEntity):
		self.lock.acquire()
		if messageProtocolEntity.getId() in self.ackQueue:
			self.ackQueue.pop(self.ackQueue.index(entity.getId()))

		if not len(self.ackQueue):
			self.lock.release()
			logger.info("Location sent")
			raise KeyboardInterrupt()

		self.lock.release()

**Comment by Narendra-Kumar** [comment]
Hi friends, I get solution, and below is sample code:

yowsup/location/__init__.py
----------------------------

from .stack import SendLocation







yowsup/location/stack.py
----------------------------

import sys

from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS, YOWSUP_PROTOCOL_LAYERS_FULL
from yowsup.layers import YowLayerEvent
from yowsup.layers.auth import YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.coder import YowCoderLayer
from yowsup.layers.network import YowNetworkLayer
from yowsup.common import YowConstants
from yowsup import env

from .layer import SendLocationLayer


class SendLocation(object):

    def __init__(self, credentials, locationdetails):
        layers = (SendLocationLayer,) + (YOWSUP_PROTOCOL_LAYERS_FULL,) + YOWSUP_CORE_LAYERS

        self.stack = YowStack(layers)
        self.stack.setProp(SendLocationLayer.PROP_MESSAGES, locationdetails)
        self.stack.setProp(YowAuthenticationProtocolLayer.PROP_PASSIVE, True)
        self.stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, credentials)
        self.stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])
        self.stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
        self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())

    def start(self):
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
        try:
            self.stack.loop()
        except AuthError as e:
            print("Authentication Error: %s" % e.message)











yowsup/location/layer.py
----------------------------


import os
import sys
import logging

from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
from yowsup.layers.protocol_media.protocolentities import *
from yowsup.layers.protocol_media.mediauploader import MediaUploader
from yowsup.common import MediaDiscover
from yowsup.layers.protocol_messages.protocolentities import MessageProtocolEntity
from yowsup.layers.protocol_media.protocolentities       import *

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)
import threading

class SendLocationLayer(YowInterfaceLayer):

    PROP_MESSAGES = "org.openwhatsapp.yowsup.prop.sendclient.queue" #list of (jid, message) tuples


    def __init__(self):
        super(SendLocationLayer, self).__init__()
        self.ackQueue = []
        self.lock = threading.Condition()
        self.connected = True
        self.jidAliases = {
            # "NAME": "PHONE@s.whatsapp.net"
        }

    @ProtocolEntityCallback("success")
    def onSuccess(self, messageProtocolEntity):
        for target in self.getProp(self.__class__.PROP_MESSAGES, []):
            number,latitude,longitude,locationName,locationURL = target
            if self.connected:
                entity=LocationMediaMessageProtocolEntity(latitude,longitude,locationName,locationURL,"raw",to = "%s@s.whatsapp.net" % number)
                self.ackQueue.append(entity.getId())
                self.toLower(entity)
            else:
                self.output("Not connected", tag = "Error", prompt = False)
                return False


    @ProtocolEntityCallback("ack")
    def onAck(self, entity):
        self.lock.acquire()
        if entity.getId() in self.ackQueue:
            self.ackQueue.pop(self.ackQueue.index(entity.getId()))

        if not len(self.ackQueue):
            self.lock.release()
            logger.info("Message sent")
            raise KeyboardInterrupt()

        self.lock.release()

    def aliasToJid(self, calias):
        for alias, ajid in self.jidAliases.items():
            if calias.lower() == alias.lower():
                return self.normalizeJid(ajid)

        return self.normalizeJid(calias)

    def jidToAlias(self, jid):
        for alias, ajid in self.jidAliases.items():
            if ajid == jid:
                return alias
        return jid

    def normalizeJid(self, number):
        if '@' in number:
            return number
        elif "-" in number:
            return "%s@g.us" % number

        return "%s@s.whatsapp.net" % number






yowsup-cli
----------------------------

Add lines in DemosArgParser init method:
----------------------------------------




        sendOpts = self.add_argument_group("Send location")
        sendOpts.add_argument('-loc', '--location', action="store", help = "Set a location on registered phone number, "
                                                                     "wait for server receipt and exit",
                              metavar=("phone","latitude","longitude","locationName","locationURL"), nargs = 5)


		
add line in process method:
---------------------------

        elif self.args["location"]:
	        self.startLocation()




Add method in DemosArgParser:
------------------------------
    def startLocation(self):

        from yowsup.location import SendLocation
        credentials = self._getCredentials()
        if not credentials:
            print("Error: You must specify a configuration method")
            sys.exit(1)

        try:
            stack = SendLocation(credentials, [([self.args["location"][0], self.args["location"][1], self.args["location"][2], self.args["location"][3], self.args["location"][4]])])
            stack.start()
        except KeyboardInterrupt:
            print("\nYowsdown")
            sys.exit(0)




Execute script :

yowsup-cli demos -c configsms.example -loc 19.1791203 72.8361517 "" ""

here I left blank location name and location location url

**Comment by Zyrix** [comment]
This doesn't work anymore since the latest WhatsApp Update a couple of days ago. Anybody have an idea to get this working again?
