### ISSUE TITLE
Yowsup CLI - Some Utf-8 characters are replaced wih � - Screenshot inside.

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#927]
Hello,

I'm using Yowsup CLI a lot lately and even with my low skillcap i managed to achieve pretty much everything that i needed to achieve, but this is beyond my possibilities ;)

This issue is pretty simple, some characted, like  "è" (and others) are replaced with the character � when sending message through the Yowsup CLI.      If this same character "è" is used for an account status update, it is replaced with nothing, simply ignored.

![screen1](https://cloud.githubusercontent.com/assets/13108035/8629844/761341d6-275f-11e5-9e96-170b1d14d226.png)

![screenshot_2015-07-11-00-03-07](https://cloud.githubusercontent.com/assets/13108035/8629988/0e1a852e-2761-11e5-9e4e-6da000a670d6.jpeg)

Until now i have tried to convert the text that contain that characters in Utf-8 , utf-8 without Bom, ansi (though notepad++) but i was unable to send that character (and others too) correctly.

I have also tried to invoke python 3 instead of python 2 changing the first line of ywsup-cli script  with
#!/usr/bin/python3  but this didn't solved the problem too.

I'm out of solutions, and in need of help about this issue ;)

thanks in advance.

**Comment by CODeRUS** [comment]
use utf8 terminal

**Comment by Agandir** [comment]
Thanks, i feel a little bit dumb, but this was caused by the emulate terminal encoding type of the automation software.

Nice catch!
