### ISSUE TITLE
reason:blocked few minutes after registering

### ISSUE THREAD

**Issue by coi6644** [tgalal/yowsup#928]
Hi all, 

I received reason blocked, few minutes after registering. The first time, whatsapp servers returned the password to me, and it worked for some minutes or an hour. Sudenly it stopped worked and when  I try to register again returns this message:
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

What can I do to solve this issue?
##

**Comment by fire829** [comment]
Same shit... Why?...

**Comment by jlguardi** [comment]
I got this some time ago due to high traffic after registering. Up to 200 non-spam but autoresponse chats.

**Comment by fire829** [comment]
I have sent ZERO messages. Only registered with cli tool.
