### ISSUE TITLE
block, cause: Unauthorized applications

### ISSUE THREAD

**Issue by kickino** [tgalal/yowsup#929]
Hey all,
I got blocked and the response from WhatsApp support was:

"Thanks for your message.
It appears that you are using an unauthorized application of WhatsApp. Unauthorized applications are not supported; they contain source code which WhatsApp can not guarantee as safe. Your private information is potentially being passed to 3rd parties. In addition, these may not function correctly and may cease to work at any given time.
Please uninstall your application and install an authorized version from:
www.whatsapp.com/download
After installing the authorized version, please reply to this email with a screenshot or an image of your screen from inside the app.
You can refer to your phone's user manual for detail steps of taking screenshots on your device.
Please note WhatsApp only works on smartphones, non-telephony devices including tablets are not supported."

Any idea how we could make it seem like we would use the official client? :D 
I am using currently the send function in the demo command. :)

Greetings, kickino
##

**Comment by mgp25** [comment]
@kickino there are many features we haven't implemented yet, so is very easy to detect if its the API or official client

**Comment by Agandir** [comment]
Around 7-10 days ago i was able to create all the groups that i wanted with the yowsup demo cli, but today i got a permanent suspension on 5 accounts after just a group created each.    I assume that the reason is the detected usage of unauthorized apllication detection, like op stated.

**Comment by kickino** [comment]
So there is no solution?😰😰
I built a monitoring solution on top of this and now this time is wasted cause whatsapp blocked this 😢😢
And I don't even harm anybody with providing this feature for my team. So sad.

**Comment by Agandir** [comment]
Give enough time to the developers to sniff and implement the functions  that miss ;)

For example, regarding to the permabans that i got lately when creating groups (same action performed on the regular whatsapp client lead to nothing or at max temporary ban, and same action performed on yowsup client 10 days ago also produced nothing or a temp ban) i'm pretty sure that sooner or later they will come with an update that will avoid instant permaban ;)
