### ISSUE TITLE
Registration Error Re-Asking!

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#930]
Hello People!

I tried to register a new number using Yowsup on Python 3.4 for Windows and I'm getting this error SSL: CERTIFICATE_VERIFY_FAILED, which I've mentioned before on post #743.

I'd like to know if it exists already a fix for this problem, or if the registration part of yowsup is just working temporarily on Linux for the moment.

Thanks,
##

**Comment by tgalal** [comment]
duplicate #743
