### ISSUE TITLE
Problem recieving messages in my Yowsup project

### ISSUE THREAD

**Issue by shubham14** [tgalal/yowsup#931]
I have created a list to store incoming or recieved messages in layer.py, but when I try print out the list, it is printing an empty list.
This is the code snippet,

layer.py

 def onMessage(self, messageProtocolEntity):
        if messageProtocolEntity.getType() == 'text':
            recv_msg.append((messageProtocolEntity.getFrom(),messageProtocolEntity.getBody()))

run.py

(in my recv_message function)
try:
        # Program main loop
        #stack.loop()
        print recv_msg
    except AuthError as e:
        print('Authentication error %s' % e.message)
        sys.exit(1)

Please Help  
##

**Comment by tgalal** [comment]
Is your onMessage decorated with @ProtocolEntityCallback("mesage") ?

```python
@ProtocolEntityCallback("message")
def onMessage(self, messageProtocolEntity):
    ...
```

**Comment by shubham14** [comment]
yes it is

**Comment by shubham14** [comment]
Can you take a look where I went wrong,here is my code
https://gist.github.com/shubham14/e7fbed7a748965897e69

**Comment by shubham14** [comment]
@tgalal can you help me?
I want to create a loop to read from contacts from a csv and send them the messages from the csv itself,but after the first iteration, 'KeyboardInterrupt' is raised and the loop terminates.Please have a look at my code.The keyboardInterrupt is in Layer.py
https://gist.github.com/shubham14/2293b9855355fc0c197d

**Comment by jlguardi** [comment]
I suppose you are getting an ack of a previous execution before to onSuccess execution so ackQueue is empty and keyboardinterrupt is raised. 
Try to lock at init() end and release after onSuccess and remove lock.aquire from onSuccess.

**Comment by shubham14** [comment]
@jlguardi Tried it out ,still isnt working and shouldn't ackQueue be empty so as to give a check for "ack" and hence showing "Message sent"

**Comment by shubham14** [comment]
When I try to receive messages from groups ,I get an AssertionError:msg like this,
File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.123-py2.7.egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps
    assert encType in "pkmsg", "msg"
AssertionError: msg

Please help

**Comment by niki239** [comment]
I got exactly the same issue, when trying to receive messages from groups. Does anybody know, why this issue appears and how to solve it? Please help!

**Comment by prasselpikachu** [comment]
#898
