### ISSUE TITLE
How to check periodically file to send text messages?

### ISSUE THREAD

**Issue by marcio-ota** [tgalal/yowsup#933]
I developed a layer to interact with the user, as a echoclient...

stack = YowStack(layer)
...
inside stack.loop()

Where i can put a loop to check the content of a file, to send the text???

**Comment by tgalal** [comment]
In your layer, start a thread that periodically does that.

**Comment by kxr** [comment]
Can you please elaborate this? Please :)

**Comment by marcio-ota** [comment]
Create the function in the same class

def someFunc(self)
    while True:
        print "sleeping"
        time.sleep(10)


on event connected call the function:

def onEvent(self, event):
    if event.getName() == YowNetworkLayer.EVENT_STATE_CONNECTED:
        self.log.Debug('onEvent: CONNECTED')
        threading.Thread(target=self.someFunc).start()

**Comment by kxr** [comment]
Thank you so much. Exactly what i was looking for.
