### ISSUE TITLE
is there any way to manually send "typing" status before we send actual message ?

### ISSUE THREAD

**Issue by ashishnetworks** [tgalal/yowsup#934]
I am in middle of a project where my bot seems quite artificial because it directly sends reply without showing typing status. It would have been pretty realistic if I could send 'typing' status for a few sec before I actually sent those replies.  does anybody knows it ? Thanks a lot

Edit 1 : I tried following code before program sends reply but its't working any idea ?

```
    entity = OutgoingChatstateProtocolEntity(ChatstateProtocolEntity.STATE_TYPING, 'xxx@s.whatsapp.net')
    self.toLower(entity)
```

Here xx@s.whatsapp.net is respective JID of receiptant  

I also included following libraries
from yowsup.layers.protocol_chatstate.protocolentities import ChatstateProtocolEntity, OutgoingChatstateProtocolEntity

But in the vain .. and its not working
##

**Comment by tgalal** [comment]
Do you have YowChatstateProtocolLayer in your stack ?

**Comment by ashishnetworks** [comment]
It worked thank you for your hint :+1: . I didn't know I should have included YowChatstateProtocolLayer in stack of run.py file.
