### ISSUE TITLE
Old version problem

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#936]
Hi,,,

    Is there any problem with registration module as i am getting error as 

INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

It was working fine..

Since morning only, i am getting this error...

Please reply...

**Comment by 0xTryCatch** [comment]
Are you using the latest code?

**Comment by Narendra-Kumar** [comment]
yes

**Comment by rami-dabain** [comment]
why this issue has been close?
using latest version and not being able to register or login.

how to update to the new version?

**Comment by 0xTryCatch** [comment]
Give more info please. What happens when you register and login?

**Comment by tgalal** [comment]
Please pass "--debug" argument and post some logs

**Comment by rami-dabain** [comment]
when I register a new number which never been used before it says "old
version" ... and when trying to login with an old number it rises an error
with reason :"auth error" or something like that

**Comment by 0xTryCatch** [comment]
Again, post full logs

**Comment by geversoncarvalho** [comment]
Same problem here
