### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#938]
Hi....

  I have registered cards and yowsup is working fine. i.e. same code is executed successfully from another pc but if i run same program from my pc, i am getting authentication problem.

Please advise if there is any case where IP gets blocked?????

**Comment by rami-dabain** [comment]
probbly  new verison, can't register new number or run old ones

**Comment by geversoncarvalho** [comment]
Hi...
I could solve the problem updating the yowsup version, i've found it was the version sent with the user-agent:

class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.12.82"

After to update with master's version it began to work. I think whatsapp is blocking old versions.
