### ISSUE TITLE
Are you planning on bringing the WART password to Yowsup?

### ISSUE THREAD

**Issue by MASTER260** [tgalal/yowsup#942]
EDIT: nvm.

**Comment by mgp25** [comment]
@MASTER260 the 'password' is only a salt, the way it's done now it's with random unique bytes so now it's more secure, having a salt with a default way of generating an identity it's very insecure

**Comment by MASTER260** [comment]
Thank you.  I had a feeling that might be the case, but I wasn't sure and wanted to stay on the safe side.  Thank you for this good news, sorry if I was rude.

**Comment by MASTER260** [comment]
Meh, whatever.  Personally, I don't care so much about this title, I was just wondering if it's possible to remove the first title I had so it doesn't display...  It would give me piece of mind.  (I know, I'm crazy.)

**Comment by MASTER260** [comment]
Hey, you can reclose this if you want, I just reopened it in case you didn't get a notification for the last comment I posted because it was closed.

**Comment by tgalal** [comment]
I did
