### ISSUE TITLE
Account is blocked

### ISSUE THREAD

**Issue by maggnetz** [tgalal/yowsup#944]
Got a number that is running more then a year (Not a spam number) ,suddenly yesterday getting the blocked messages.

any ideas why?
##

**Comment by jlguardi** [comment]
I had same issue. I thought they used c1 server issue to detect us.

**Comment by 0xTryCatch** [comment]
Hard to believe. WA has many ways to detect APIs, don't worry

**Comment by jlguardi** [comment]
I've registered a new number to replace the blocked one but it is blocked after 7 hours working (1000 messages but no spam and no repeated messages). The sw is the same since 1 year ago but yowsup updates.

**Comment by mgp25** [comment]
@jlguardi it doesn't matter if it's spam or not, if you send unsolicited messages you will be blocked, also, any kind of bulk receiving / sending is being blocked by WhatsApp

The API is meant to be used for personal usage only not as a service.

**Comment by jlguardi** [comment]
When I said that is not spam I meant that they are not unsolicited messages. No bulk messages sent or recieved. I manage lot of messages from people to people.

**Comment by 0xTryCatch** [comment]
And there you have the problem. "A lot of messages" is not possible.

**Comment by jlguardi** [comment]
I know that "a lot of messages" is a problem but this line was running for several months and always managing similar number of messages. I expected to be blocked long time ago but, as describe @maggnetz, it was yesterday.
So I think some new rules are analyzing wa accounts.

**Comment by vmorenomarin** [comment]
I use WhatsApp via Pidgin; But since sunday, when I try to connect appears a message like "not-authorized". Is there way to disable the account for to try again?
