### ISSUE TITLE
May I please have my last issue marked as spam? (Or removed if that's a premium feature that you have.)

### ISSUE THREAD

**Issue by MASTER260** [tgalal/yowsup#945]

**Comment by tgalal** [comment]
stop

**Comment by MASTER260** [comment]
Can I at least have this marked as spam?  I mean, that's basically what this is anyways, and I apologize for that.  Basically, I just want it removed, and I think marking it as spam will notify the mods about that.  At the very least I'd like the old title of this thread no longer displayed, but I don't know if that's possible at all.  So, yeah.  Sorry that I've been so damn annoying.  You don't have to accept my apology if you don't want to, but please tell me if you got this message at least.

**Comment by tgalal** [comment]
1 more similar comment and you're banned.
