### ISSUE TITLE
Can I use Yowsup for commercial propose?

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [tgalal/yowsup#954]
I'm developing an app that uses Yowsup to send and receive messages in an automated way via WhatsApp. Can I commercially distribute this app? If yes, is there some requirement, something that I have to do? Or is just use, without any requirement?

**Comment by mgp25** [comment]
@t0rr3sp3dr0 no, you cant and you musn't

**Comment by Rubenfranco** [comment]
A

Enviado desde mi Windows Phone
________________________________
De: mgp25<mailto:notifications@github.com>
Enviado: ‎14/‎11/‎2015 20:22
Para: tgalal/yowsup<mailto:yowsup@noreply.github.com>
Asunto: Re: [yowsup] Can I use Yowsup for commercial propose? (#954)

@t0rr3sp3dr0 no, you cant and you musn't

---
