### ISSUE TITLE
how to sync

### ISSUE THREAD

**Issue by NCS80** [tgalal/yowsup#956]
Hi,

I've been working with yowsup for a couple of weeks now, and I find it really nice. But sometimes it's a bit hard to figure out how to use it. For now I used the echotest demo to experiment, but now I want to add syncing.

What is the easiest way to sync a contact at the moment a message is received?

thanks a lot!

gr
##

**Comment by tgalal** [comment]
[GetSyncIqProtocolEntity](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_contacts/protocolentities/iq_sync_get.py)
