### ISSUE TITLE
stream:error ack

### ISSUE THREAD

**Issue by gibma** [tgalal/yowsup#957]
Hi!

I use a very small subset of yowsup for only login, send a message and logoff. My code is frequently updated with the improvements made in yowsup, so it should be free of known bugs.

But now i get some stream:errors while sending acks as response to old receipt-messages.

As you can see, the first receipt will be retried every time i log in, but will never succeed.

I compared the structure of my ack message with it on yowsup, but can not see any difference.

Can someone give me a hint, what is wrong? Is there a difference in sending acks to offline receipt messages?

Thanks in advance!
Joachim

```
>>   <stream:features><presence></presence><groups_v2></groups_v2><readreceipts></readreceipts></stream:features>
  >> <auth mechanism="WAUTH-2" user="4917611111111"></auth>
<<   <start from="s.whatsapp.net"></start>
<<   <stream:features></stream:features>
<<   <challenge>[HEX]</challenge>
  >> <response>[HEX]</response>
<<   <success t="1437651905" props="4" kind="free" status="active" creation="1427580327" expiration="1459116327">[HEX]</success>
<<   <receipt from="4915122222222@s.whatsapp.net" id="waapi-1437389317032-7" retry="1" offline="1" type="read" t="1437389325"></receipt>
  >> <ack to="4915122222222@s.whatsapp.net" id="waapi-1437389317032-7" type="read"></ack>
...
<<   <ib from="s.whatsapp.net"><offline count="20"></offline></ib>
<<   <stream:error><ack></ack></stream:error>
```
##

**Comment by Mithotyn** [comment]
Sorry. Clicked wrong button. :-(
