### ISSUE TITLE
demo crashes when receiving payment for the number.

### ISSUE THREAD

**Issue by sgitkene** [tgalal/yowsup#960]
This

http://imgur.com/DwTPuG7

came right after payment. I can't launch yowsap now:

http://imgur.com/rnapVOC

I feel like fool now for having payed for Whatsapp ಠ_ಠ
##

**Comment by tgalal** [comment]
Use yowsup from dev branch to get past "Unknown ib" error
To get around "Unimplement notification type" error for now,  login several times and then at some point whatsapp will stop sending you this notification

**Comment by sgitkene** [comment]
thanks!

It works for now. (I commented out the part where that exception is raised)
