### ISSUE TITLE
Curiosity: How to use a number registered with Yowsup into a mobile device (or emulator) with the official whatsapp client?

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#962]
As title say, not an issue but a curiosity.

I found guides on how to use a number registered with the whatsapp official client  (extracting the b64 password) into an api client (like yowsup) but how to use a number registered with yowsup (this mean that i have the number:b64pass) into an official client ?  (assuming that the mobile device has not yet whatsapp installed, or it has been just installed but never used).

Thanks to anyone that will answer to this curiosity ;)
##

**Comment by mgp25** [comment]
@Agandir it's possible to do as far as i know with android devices, but you have to serialize and encrypt the password into the device and also change some data in a .xml. 

My recommendation: don't do hard things that aren't, simple register again the number.

**Comment by Agandir** [comment]
mgp25, thanks for the reply.
Of course is easier to re-register the numbers, but that doesn't answer to my question about this curisity.   If you have more info or link about how to serialize and encrypt, and which files to modify, feel free to write/post links about
Thanks

**Comment by mgp25** [comment]
Just reverse the process we use to extract password, encrypt it and change it, i don't have an android device to explain you, if you know, it will take you only about 5 minutes. But it's a waste of time to do that
