### ISSUE TITLE
How to check Contact Status?

### ISSUE THREAD

**Issue by jerryames** [tgalal/yowsup#964]
issue 562 and 816 is closed by the new function of lastseen. However issue 816 solve the problem of checking last seen. How to get Contact Status? Like when it was changed and what is the status text. The response in PHP version sendGetStatuses: 

since: 2015-Jul-19 19:09:29 getstatus-1437342675-1, Status: Hey there! I am using WhatsApp.

I am waiting for this feature for many months. Hope we can have a similar function of sendGetStatuses.
##

**Comment by jerryames** [comment]
Anyone knows how to get the response as in PHP version of sendGetStatuses?

**Comment by tgalal** [comment]
599c08ca974075e69d4db0c2fa631ac67f7613c5
