### ISSUE TITLE
Sending multiple messages through Yowsup

### ISSUE THREAD

**Issue by shubham14** [tgalal/yowsup#967]
This is what I did,
from newrun import send_message,recv_message
send_message('918447453529','hello',0)
send_message('918447453529','hi',0)

 But after the first message is sent, a KeyboardInterrupt is raised and the second message is not sent.
Please help

**Comment by tgalal** [comment]
maybe post the code of send_message function? Or easier just remove the raise KeyboardInterrupt that must be there somewhere
