### ISSUE TITLE
Problem storing prekeys

### ISSUE THREAD

**Issue by Brianvdb** [tgalal/yowsup#971]
When I was running my application on the raspberry pi for the first time i got an error:

```
 TypeError: 'str' does not support the buffer interface
```

on this line (dev-branch): https://github.com/tgalal/yowsup/blob/develop/yowsup/layers/axolotl/layer.py#L352

I fixed it with this line:

```
 return binascii.unhexlify(_id.encode())
```

I was using Python 3.2

I am currently unable to do a pull request therefore i made this issue.
##

**Comment by mode2k** [comment]
Someone add this .encode() to dev branch, please. Thanks!
