### ISSUE TITLE
status: fail, reason:no_routes

### ISSUE THREAD

**Issue by mannemvamsi** [tgalal/yowsup#974]
I know some people got this error https://github.com/tgalal/yowsup/issues/370. but I haven't found any right solution . 

Can somebody help me to resolve this ? 

I am using virtual server from digital ocean, I deleted whatsapp account from my phone. Tried to register from yowsup-cli. It says failed with reason no_routes.
##

**Comment by TamCore** [comment]
Hint: Try the registration from your home network. Was trying it the whole day from my server which is hosted by OVH. Came home, tried it on my laptop and bam, it worked :P

**Comment by mannemvamsi** [comment]
@TamCore Thanks, I couldn't configure the requirements properly at home(windows). So, I used this https://github.com/WHAnonymous/Chat-API/wiki . It worked great.

**Comment by lalves** [comment]
the same here.. I was using machines on digital ocean and got blocked... tried from corp network and worked with the same number...

**Comment by progressify** [comment]
I have the same problem, on my server hosted by OVH it give me no_routes, but if I try for my home network is it ok... 
Why this issue?
