### ISSUE TITLE
Registration code via voice fails

### ISSUE THREAD

**Issue by dgua** [tgalal/yowsup#980]
In the past, I was always able to request a registration code via voice. Now it does not work anymore. When I try:

yowsup-cli registration --requestcode voice  --phone 1408xxxxxxx --cc 1 --mcc 310, 

I get all the correct output:

status: ok
kind: free
pw: b2RDpOouDVmnluqolcKwkH2B4yE=
price: $0.99
price_expiration: 1441495267
currency: USD
cost: 0.99
login: 1408xxxxxxx
type: existing
expiration: 1459694538

But no more phone call with the code. I cannot get SMS on this number (it's an ooma line). 

Any ideas?

**Comment by CODeRUS** [comment]
you got pw in response. what do you need?

**Comment by dgua** [comment]
You are right. Everything works. 
I was just following the documentation, where it says registration is a two-step process. 
Please update the documentation.
