### ISSUE TITLE
send VCard/Media

### ISSUE THREAD

**Issue by wormen** [tgalal/yowsup#982]
tell me how I can send VCard or media files ... I have nenashel no mention in this regard
##

**Comment by wormen** [comment]
tell me how to accomplish what I described above?

**Comment by Dl0tt** [comment]
you want to send a Vcard/Media with yowsuo-cli or usong run.py/layer.py?

**Comment by wormen** [comment]
yes, with yowsup-cli

**Comment by wormen** [comment]
the answer seems a long time to wait ...

**Comment by Narendra-Kumar** [comment]
You can see issue:
https://github.com/tgalal/yowsup/issues/909#issuecomment-132389863


The example given in this issue is working for me.
Please try that example, may be it also work for you.

**Comment by wormen** [comment]
Unfortunately, I do not understand in python
How can I send from yuwsup-cli?

**Comment by ihfazhillah** [comment]
for image use /image send number pathfile

**Comment by wormen** [comment]
@ihfazhillah You can send commands to an example?

**Comment by nedimhx** [comment]
@Dl0tt can you make and example how to send image using run.py/layer.py 

So when sender send "takephoto" my script will need to execute bash comand to download photo from ip cam and then yowsup need to send photo from predefined location, where photo is previous saved from ip cam.

regards
