### ISSUE TITLE
@tgalal, how did you dissected Whatsapp?

### ISSUE THREAD

**Issue by BernardoLima** [tgalal/yowsup#989]
How did you do to discover all packets structure, etc?

**Comment by WHAnonymous** [comment]
@BernardoLima using magic! This isn't the best place to talk about this

**Comment by maruen** [comment]
@tgalal I'm interested in know about this, if you could share.
What would be the better place to talk about?

thanks

-- 



*Maruen Mehana Mobile: +55 (011) 98438.8499 *




*São Paulo - SP / BrasilThe way of the righteous is like the first gleam of
dawn,which shines ever brighter until the full light of day. - Proverbs
4:18*
