### ISSUE TITLE
Stopping background thread?

### ISSUE THREAD

**Issue by docgonzo2015** [tgalal/yowsup#992]
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead 
sendclient/stack.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

i can't find it to stop it :-(

**Comment by Dl0tt** [comment]
in your run.py, instead of:

```python
    layers = (
        EchoLayer,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
    ) + YOWSUP_CORE_LAYERS
```
use:
```python
	layers = (
		MyCustomLayer,
		YowParallelLayer((
			YowAckProtocolLayer,
			YowAuthenticationProtocolLayer,
			YowMediaProtocolLayer,
			YowMessagesProtocolLayer,
			YowReceiptProtocolLayer,
		)),
		YowAxolotlLayer,#not mandatory, but will be soon
		YowLoggerLayer,
		YowCoderLayer,
		YowCryptLayer,
		YowStanzaRegulator,
		YowNetworkLayer
	)
```

Make sure to import YowParallel layer with ```from yowsup.layers import YowParallelLayer```

**Comment by MostafaBalata** [comment]
use YowStackBuilder  to solve your issue. :dart:
