### ISSUE TITLE
Send and Receive with the same connection

### ISSUE THREAD

**Issue by omarjimenezo** [tgalal/yowsup#999]
I'm developing a CRM for my company, who will send notifications to the employees through whatsapp, I already have send and echo on the same layer, I have a while which checks if there's notifications on the database, and if there's one it has to send the message, if not, it has to listen to incoming messages, but when I execute the run.py file, it first checks if there's  something to send, and then listens to incoming messages as expected, but, it keeps listening forever until it receives an ack or an incoming message, and then it does exit the echo layer and check for new messages to send.

How can I make listenMSG() exit after a certain period of time so it can check whether there's any messages to send again?

Here is the code:

```
from yowsup.layers.interface import YowInterfaceLayer
from stack import YowsupSendStack
from stack import YowsupEchoStack
import MySQLdb as mdb
import threading
import sys
import os
import time

def sendMSG(camp_id,usuario_id):
  CREDENTIALS = ("521"+sys.argv[1], sys.argv[2]) # number and password
  num_id  = sys.argv[1]
  passwo  = sys.argv[2]
  try:
    condb = dbconn()
    with condb:
      cur = condb.cursor(mdb.cursors.DictCursor)
      try:
        stack = YowsupSendStack( CREDENTIALS, num_id, condb )
        stack.start(condb,num_id)
      except KeyboardInterrupt:
        sql = "SOME UPDATE"
        cur.execute(sql)
  except mdb.Error, e:
    print( "Error %d: %s" % (e.args[0],e.args[1]) )
  finally:    
    if condb:    
      condb.close()

def listenMSG():
  CREDENTIALS = ("521"+sys.argv[1], sys.argv[2]) # number and password
  try:
    stack = YowsupEchoStack( CREDENTIALS, sys.argv[1] )
    stack.start(condb,num_id)
  except KeyboardInterrupt:
    print('\nKeyboardInterrupt')

if __name__ == "__main__":
  num_id    = sys.argv[1]
  password  = sys.argv[2]
  CREDENTIALS = ("521"+num_id, password)
  while 1: 
    sql = "SELECT MSGS FROM DB"
    condb = dbconn()
    cur = condb.cursor(mdb.cursors.DictCursor)
    cur.execute(sql)
    result = cur.fetchall()
    if result:
      time.sleep(1)
      for row in result:
        camp_id    = row['camp_id']
        usuario_id = row['usuario_id']
        sendMSG(camp_id,usuario_id) #if there's something to send
    else:
        time.sleep(1)
        listenMSG() #if there's nothing to send, then listen
```
##

**Comment by sinanm89** [comment]
Instead of stopping and starting the listenMSG() try setting up a watchdog that queries at times and sends the msgs.

**Comment by omarjimenezo** [comment]
Yeah, the problem is the listenMSG(), it keeps listening until "ack" event or an incoming message is received, I want to switch between sendMSG() and listenMSG() periodically, I think that maybe making a function that broadcast an event and making listenMSG() subscribes to that event, can be the solution, this event would make listeningMSG() to stops and let the while in the __main__ (It's my watchdog) keeps working, but now the thing is that I don't know how to broadcast an event.
